### ISSUE TITLE
[PVP][Items] Add a way to automatically scale itemlevel of pvp items.

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2244]
Originally reported on Google Code with ID 2245
```
PVP item level will rise in PVP combat.

620 -> 675(Honor)
660 -> 690(Conquest)

Would it be possible to implement this part of the simulationcraft?
```

Reported by `qwerttyyyuii` on 2014-12-01 14:12:08

**Comment by Collisionc** [comment]
Closing as this just isn't feasible anymore. We'd have to implement every single pvp talent as well. :\
