### ISSUE TITLE
[Report] JSON ouput

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2269]
Originally reported on Google Code with ID 2270
```
I'm using simcraft as part of a personnal app. I'm currently parsing the text output
but it would be nice to have a structured format output. Bonus point if you go with
JSON.
```

Reported by `lussanp` on 2014-12-11 12:06:48

**Comment by scamille** [comment]
A lot of the basic data is now available in the json report, integrated into master branch.

I'll continue working on it step by step, adding the more detailed stuff in.

If you need anything specific more quickly, please tell me.
