### ISSUE TITLE
Windows XP / Pre-SP2 Win Vista / Pre-SP 1 Windows 7 are no longer supported

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2385]
Originally reported on Google Code with ID 2386

```
(Windows 32bit self-extracting zip — installer)

This packages contains SimulationCraft.exe and is not a valid Win32 application!


```

Reported by `ipredok62` on 2015-01-15 07:56:00

**Comment by scamille** [comment]
Going to close this, as this should no longer be relevant.

I assume windows releases still work on Windows 7 SP1 or higher (but I am not sure at all). But Windows7 support has ended since the the beginning of 2020 anyway.
