### ISSUE TITLE
Add in option that will allow dual wield enemies to miss.

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2488]
Originally reported on Google Code with ID 2489
```
What steps will reproduce the problem?
1. load up attached .simc file
2. sim it
3. look at report and notice enemy autoattacks with auto-attacks and offhand auto attacks
are not missing

What is the expected output? What do you see instead?
autoattacks from dual wielding enemy is supposed to have +19% miss chance

What version of the product are you using? On what operating system?
610-7

Please provide any additional information below.
heres a link of the sim report from simming the .simc
https://dl.dropboxusercontent.com/u/9768004/test_DW.html


```

Reported by `arexdramon` on 2015-03-16 00:12:03

<hr>
 * *Attachment: [simc_gui.simc](https://storage.googleapis.com/google-code-attachments/simulationcraft/issue-2489/comment-0/simc_gui.simc)*

**Comment by scamille** [comment]
I'm closing this for now.

If there ever is a relevant boss with missing dual wield, and someone can get accurate numbers for it, we'll gladly update our model in SimC.
