### ISSUE TITLE
easier way to generate many gear sets?

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2523]
Originally reported on Google Code with ID 2524
```
I use SIMC a lot to compare different gear sets, but it has been time consuming to generate
all those gear sets into the Automation tab. For example, I have 2 head pieces, 3 hand
pieces, 2 leg pieces, 2 weapons, and 4 trinkets, which forms 96 different sets of gear,
and I want to get the best combination of them. It is almost impossible for me to input
them all by hand. Is there a way to auto generate gear sets for users like me? Can
you add this feature into SIMC?
Thank you.
```

Reported by `thllxb` on 2015-04-14 15:20:14

**Comment by scamille** [comment]
I'm going to close this Issue.

For Simc, gear lists are really just one of many import factors. While it certainly would be nice to have better support for generating/editing the input (GUI paperdoll, online character profile like wowhead/ask.mr.robot, or automated gear list generators ), it is not a core feature/task of SimC, and especially one for which we don't have the manpower.

We always tried to leave those tasks to external tools, and even though there is a Automation tab now, that developer is not active anymore as well. Unless maintained, it will perish one day as well, and certainly not be improved to the levels requested here.

The AutoSimC project looks like a nice idea, and I would recommend you to directly help to develop it further.
