### ISSUE TITLE
mage simc is not reality

### ISSUE THREAD

**Issue by candela0720** [simulationcraft/simc#2620]
Step 1.mage legendary ring use 3 minutes, it's not reality 
other melee class don't wait ring cooldown for mage(like a rogue)

Step 2. Tome of Shifting Words, arcane blast casting fomula is false
=(base casting -(base casting * trinket grade))/(1+haste percent)

Step 3. Tome of Shifting Words, arcane blast ruducing global cooldown, 
but have limit global cooldown sec.

over 50% haste, use arcane power arcane blast gc fixed by trinket grade
normal - gc 0.87.sec
heroic - gc 0.821 sec
mythic - gc 0.764 sec

casting < gc - gc is arcane blast casting time. but 735 simc mage cast 0.64 arcane blast during
over 50% haste (buff - time warp) 

Please provide any additional information below.

**Comment by Frostedmages** [comment]
Handled here: http://altered-time.com/forum/viewtopic.php?f=17&t=1964

**Comment by Frostedmages** [comment]
As there is no indication that this will be changed to the GCD behavior of other spells, the module has been updated.

https://github.com/simulationcraft/simc/commit/6fd56377c90cbd68acde83c0021a90050737334f
