### ISSUE TITLE
Starters Guide web page opens every launch

### ISSUE THREAD

**Issue by canofbutter** [simulationcraft/simc#2624]
The web page for the Starters Guide (https://github.com/simulationcraft/simc/wiki/StartersGuide) launches every time Simulationcraft is opened now.  (Using SimulationCraft 622-01 build from Sept 7).  If this is intentional, please reassign to an enhancement request to provide an option to disable this feature.

**Comment by scamille** [comment]
Seems to be WebEngine related problem, so I can't investigate it with MinGW QT build.

The problem has likely to do with the switch of Starters Guide from GoogleCode to Github. We'll have to wait for Collision to do something about it.

**Comment by navv1234** [comment]
Should be fixed in the next build Collision does.
