### ISSUE TITLE
Build issue (c++10) on OSX (Yosemite)

### ISSUE THREAD

**Issue by wkrueger** [simulationcraft/simc#2626]
Hi, today I felt like hacky and gave building simcraft a try. (Keep in mind im a bit rookie on this things)

I'm on OSX 10.10.5.

  * installed qt using `brew install qt5` (then used the symlink force command)
  
  * changed qt path on `build_snapshtot_osx.sh`

  * ran
```
/usr/local/Cellar/qt5/5.4.2/bin/qmake simcqt.pro
./build_snapshot_osx.sh
```
That throws me something like `array: No such file or directory`.

After some research I was able to compile after I removed a reference to libstdc on `simcqt.pro`. Also had to increase the osx target version.

```
-    QMAKE_CXXFLAGS += -stdlib=libstdc++
-    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.6
+    QMAKE_CXXFLAGS += -stdlib=libc++
+    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7
```
Still couldnt compile the UI, but im currently done for today :) CLI worked fine.

**Comment by scamille** [comment]
Try with e83f4438b7bde18a73243ec565471a517c26dea6

**Comment by scamille** [comment]
And I added your changes in e0593486cbd9b82eab277235fcab593c4b5fbd4f

libc++ is the new default since OSX10.7, so I hope this will work now.

**Comment by navv1234** [comment]
Oops, did I forget to change the GUI specific stuff. Anyhow, yeah, min version to 10.7 and STL to libc++ is the way to go now.

**Comment by navv1234** [comment]
In our simcqt.pro, I put in ```QMAKE_CXXFLAGS_RELEASE += -DNDEBUG -std=c++0x``` because our jenkins-build of the gui failed, as c++11 CONFIG directive was unknown there.
