### ISSUE TITLE
Can't see the 620-02 updated version

### ISSUE THREAD

**Issue by macwelldeath** [simulationcraft/simc#2627]
I been trying to update simulation craft but I can't see the option to download 620-02 version. I can only see 620-01 version. How can i fix it so I can download 620-02 update on the Simulation Craft.

**Comment by scamille** [comment]
I can see the download just fine here: http://www.simulationcraft.org/download.html
or more specifically http://www.simulationcraft.org/2015/07/12/release-620-02.html with all windows download links working.

If you are looking for a 6.2.2 - 622 build: You can get alpha builds at http://downloads.simulationcraft.org/?C=M;O=D . A official release will follow eventually.
