### ISSUE TITLE
Archmage's Greater Incandesence.

### ISSUE THREAD

**Issue by Nuggnar** [simulationcraft/simc#2628]
All the reports you've posted show this buff being added to the dynamic buffs of all the classes, but I'm not sure it is a buff a player can get in game. It's listed as an ability of the Fel Extractors.

[http://www.wowhead.com/npc=94285/fel-extractor#abilities]

**Comment by Fredyy90** [comment]
Its the Proc of the Legendary Rings:
http://www.wowhead.com/items?filter=minrl=100;maxrl=100;qu=5;sl=11;cr=195;crs=1;crv=0;gb=1#0+2
