### ISSUE TITLE
Nightly build crashes - build 622-01 2015-09-08

### ISSUE THREAD

**Issue by skules** [simulationcraft/simc#2629]
So the previous builds obviously crashed when trying to load the results page (unsure if this got fixed).

On the newest pushed nightly build (8th sept) both 64bit and 32bit simply just crash.

So far only - simc-620-02-win32 - works for me.

simc-622-01-win32 - I recieve 2 errors, ordinal 3906 not located in dynamic link library LIBEAY32.dll , and the same with ordinal 4369. Then upon attemping to load it just crashes (simulationcraft.exe has stopped working). On the previous nightly build i still got those 2 ordinal errors but it atleast opened (the results page obviously didn't work though).

simc-622-01-win64 - Straight up crashes after attemping to load (simulationcraft.exe has stopped working).

Unsure if you can replicate these.

If this is considered a duplicate (which i don't think it is), just copy and paste my post to whatever issue thread. If you need more info from me I'll be checking back later.

**Comment by skules** [comment]
Bump. 11th sept build also exact same issues

**Comment by Collisionc** [comment]
Try this one out - http://downloads.simulationcraft.org/SimcSetup-622-01-Win64.exe

**Comment by scamille** [comment]
@Collisionc Try c978bceac115ed00ea0b0ad57fcfb1a79e256ec3

**Comment by skules** [comment]
The one you linked (http://downloads.simulationcraft.org/SimcSetup-622-01-Win64.exe) Appears to be working perfectly, along with the newest 64 bit .exe from 14th sept. But the .7z file has issues.

However the 2 .7z files  - 

simc-622-01-win64.7z	14-Sep-2015  - Loads up but crashes when trying to show results page.
simc-622-01-win32.7z	14-Sep-2015  - Doesn't load. "application was uanble to start correctly (0xc000007b)  - This also happens with the .exe

**Comment by Collisionc** [comment]
The .7z files should work now, let me know.

**Comment by skules** [comment]
simc-622-01-win64.7z	23-Sep-2015  -- crashes trying to display results
SimcSetup-622-01-Win64.exe	23-Sep-2015  - crashes while trying to display results
simc-622-01-win32.7z	23-Sep-2015 - Ordinal missing and then crashes on start
same with .exe 32bit

**Comment by Collisionc** [comment]
Is it still occuring with the latest builds? Sorry for the lack of response, I haven't had much free time lately, but I do update the nightly builds every few days generally still.

**Comment by skules** [comment]
+1 so no idea
