### ISSUE TITLE
Blizzard API item fetch is broken

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2630]
Leaving this here to remind me to fix it at some point.

Blizzard JSON end point item fetching is currently broken. The new system requires that the GET requests are provided an item context (e.g., raid difficulty), when an item context exists for an item.

Item contexts are given in the character profile output item JSON, however not all "context" values there are actually usable as item contexts. To properly support the system, the item must first be fetched without any item context. The result will give one of two options: 1) If the item has item contexts, it will list all of the available contexts, 2) If the item has no available item contexts, it returns the attributes of the item.

In 1, the list of available contexts can be compared against the character profile specified context, and if it matches, the "real stats" can be fetched by re-doing the query with the correct item context. In 2, the data can be parsed as is.

Open question is how to support this for command-line based options, since it then becomes relevant to understand the item contexts when fetching item data based on user given options. At bare minimum, the  `heroic`, `mythic`, and `lfr` options can be mapped to Blizzard API item contexts, but this is somewhat unwieldy for users to have to specify the context. Another option in some cases would be to determine the context from user given bonus ids, if possible.

**Comment by Collisionc** [comment]
I believe this is fixed, yes?

**Comment by navv1234** [comment]
Not by me, at least.
