### ISSUE TITLE
Undead racial (Touch of The Grave) buff not update at simcraft?

### ISSUE THREAD

**Issue by Nakrib** [simulationcraft/simc#2632]
Undead racial (Touch of The Grave) buff not update at simcraft? I used simcraft on my ud lock  but still 2k totg damage at results. I have 8k spell power.

**Comment by navv1234** [comment]
Is this now actually live in-game? I implemented it some time ago but never enabled it because people were claiming it's not actually live.

**Comment by Nakrib** [comment]
Yeah. It is active. And i think other buffs( trinket,boss damage taken,ring) impact it as well. Spell tooltip not fix yet.

**Comment by navv1234** [comment]
Can it critical strike?

**Comment by navv1234** [comment]
I enabled the hotfix in commit 156a1c2. Should appear in the next release.

**Comment by qqgduc** [comment]
Yes it can critical strike. The linked log shows this: https://www.warcraftlogs.com/reports/RXbN4AVPaDjmY8yW#fight=6&type=damage-done&source=19&ability=127802
