### ISSUE TITLE
Crash in windows 10

### ISSUE THREAD

**Issue by Zannazesch** [simulationcraft/simc#2633]
After installing w10 I have had problems with SimCraft. Whenever I press simulate, it dies on me. Crashes.

I have tried:
 - Both 32 and 64 installations.
 - Both 32 and 64 zip files.
 - Compatibility for both w7 and w8 for all above mentioned installations.
 - Running as admin for all above solutions.

None of this changed the bug in any way. It still died on me whenever I press simulate.

Anyone got anything like this and/or a solution?

**Comment by scamille** [comment]
Please attach the simc_gui.simc file from your SimC installation folder to this ticket. It contains the exact input used to start your last simulation.

This makes it much easier for us to replicate the issue.

Have you tried simulating other character (friends from armory, or sample profiles in SimC)?

**Comment by Zannazesch** [comment]
I have been able to run another character on my pc in in the 64bit. However, my own char still won't process.
I have been able to run my own char on another PC running w10, though.

After running a sim of someone else, it seems to have fixed itself. I can now run everything again.

**Comment by scamille** [comment]
Ok great to hear.

Next time the simulation crashes, please make a copy of the simc_gui.simc file directly after it, and create a new ticket here. There might be some special combination of character spec/glyphs/items/action priority list with certain environement options ( fight style, combat length, etc. ) which triggers the crash.

Btw: I don't think this has anything to do with Win10 in particular. More important ( please add next time as well ) is the exact version of SimulationCraft you're running.

**Comment by Zannazesch** [comment]
I will.

Well, It just occured just after I installed w10, so I thought it had something to do with that.

Thanks for the response :)
