### ISSUE TITLE
Retina support for OS X

### ISSUE THREAD

**Issue by lzanita09** [simulationcraft/simc#2634]
Currently I'm using a macbook pro, and SimulationCraft seems to be scaled under the retina display
![screen shot 2015-10-01 at 7 16 46 am](https://cloud.githubusercontent.com/assets/1761573/10223186/ba5b5304-680c-11e5-88bf-f7eddf65c2c5.png)

I don't know much about Qt, but after a bit googling I found out that I can add
```xml
<key>NSPrincipalClass</key>
<string>SC_MainWindow</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
```
to `Simulationcraft.plist`, then build from source. This is what I got afterwards,
<img width="1491" alt="screen shot 2015-10-01 at 7 16 58 am" src="https://cloud.githubusercontent.com/assets/1761573/10223322/50ba8bee-680d-11e5-81fc-f58581826c74.png">

Is this something can be added so that simc looks sharper on OS X?

**Comment by navv1234** [comment]
I added it but I don't have a hiDPI display so I have no clue of its efficacy.

**Comment by lzanita09** [comment]
I can test it for you when the latest OS X build is out.
