### ISSUE TITLE
Troll Elemental Shaman bugged priority list

### ISSUE THREAD

**Issue by Xife** [simulationcraft/simc#2638]
Importing a Troll Elemental it shows, under the "# Executed every time the actor is available." bar, for ascendance:
actions+=/ascendance,if=spell_targets.chain_lightning>1|(dot.flame_shock.remains>buff.ascendance.duration&(target.time_to_die<20|buff.bloodlust.up|buff.berserking.up|set_bonus.tier15_4pc_caster=1)&cooldown.lava_burst.remains>0)

However for every other race it shows for ascendance:
actions+=/ascendance,if=spell_targets.chain_lightning>1|(dot.flame_shock.remains>buff.ascendance.duration&(target.time_to_die<20|buff.bloodlust.up|time>=60)&cooldown.lava_burst.remains>0)

This ends up simming troll shamans ~3k dps lower then other races in equivalent gear.

**Comment by mrdmnd** [comment]
So it looks like we need to swap the set bonus thing for `time >= 60`, right?

**Comment by mrdmnd** [comment]
Oh, interesting. Okay, so looking at the comments, here's the relevant bit:
https://github.com/simulationcraft/simc/blob/master/engine/class_modules/sc_shaman.cpp#L5782-L5790

**Comment by mrdmnd** [comment]
Fix is in: https://github.com/simulationcraft/simc/pull/2679
