### ISSUE TITLE
max_time overflow with most recent shuffling of headers

### ISSUE THREAD

**Issue by physcx** [simulationcraft/simc#2639]
setting max_time as a command line argument is causing an overflow / assert to be hit

currently looks like SC_USE_INTEGER_TIME is set in simulationcraft.hpp and it was recently pulled out of the list of files being included by sc_option.cpp in this commit
https://github.com/simulationcraft/simc/commit/19a4c053b31692d89e3baad7d15ae74c8a8df51a

guessing one set off cpp's are compiling with doubles and another with int64s for types causing the assert fail
simc physcx.simc iterations=100 max_time=450 vary_combat_length=0 html=pc.html threads=1
SimulationCraft 622-01 for World of Warcraft 6.2.2 Live (build level 20444)

Simulating... ( iterations=100, threads=1, target_error=0.000,  max_time=4646624099911598, vary_combat_length=0.00, optimal_raid=1, fight_style=Patchwerk )

simc: ./sc_timespan.hpp:151: timespan_adl_barrier::timespan_t timespan_adl_barrier::operator+(timespan_adl_barrier::timespan_t, timespan_adl_barrier::timespan_t): Assertion `right < zero() || left < zero() || left <= max() - right' failed.

**Comment by natehieter** [comment]
Oh how I long for the days of one dir and one header......

serge, if you are going hack and slash, why not get rid of timespan altogether.  It has been years since we transitioned to milliseconds.  I don't see the project ever going back to double.  

Or go one step further:  If you place such a high value on organization and consistency, why don't we just declare that TIME is in milliseconds always and forever.... and change the entire interface and engine to reflect that.

**Comment by navv1234** [comment]
+1 for ditching timespan_t and just going for int64_t millisecond time.

**Comment by scamille** [comment]
I think this also was the cause of our mysterious rng timespan wrapper functions not working when defined in the .cpp file.

**Comment by scamille** [comment]
I'd vote for keeping timespan_t as it is now, just without all the floating point code in it, purely as a milli-second, integer based time class. It still encapsulates InGame time nicely, and adds type-safety to the now very few places where we still use hardcoded time values.

And for practical reasons, it is a mature and well integrated part of SimC, with low maintenance and complexity costs. There are other things, as discussed for example the whole DBC stuff, which could do with some rework.
