### ISSUE TITLE
Crash on monk dps action lists

### ISSUE THREAD

**Issue by MoldySponge** [simulationcraft/simc#2641]
most abilities crash program if done before rising_sun_kick. The exact reasoning for this and reproducing seems to be problematic based in different scenarios. However, an easy way to replicate the problem is as follows, using the standardized monk simulation:

# Executed every time the actor is available.

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/fists_of_fury
actions+=/call_action_list,name=opener,if=talent.serenity.enabled&talent.chi_brew.enabled&cooldown.fists_of_fury.up&time<20

crashes the program vs.

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/call_action_list,name=opener,if=talent.serenity.enabled&talent.chi_brew.enabled&cooldown.fists_of_fury.up&time<20

which does not

To boil the problem down more.
actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/jab

^ crashes

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/rising_sun_kick
actions+=/jab

^does not crash

**Comment by Hinalover** [comment]
can you please post the complete APL (with gear)? Not sure if it's related to set bonuses or not.

**Comment by MoldySponge** [comment]
# Originally crashed with this list:
As a note I have 4pc heroic tier

monk="Hairyteeth"
origin="https://us.api.battle.net/wow/character/kilrogg/hairyteeth/advanced"
thumbnail="http://us.battle.net/static-render/us/kilrogg/159/167017375-avatar.jpg"
level=100
race=night_elf
role=dps
position=back
professions=leatherworking=700/skinning=700
talents=http://us.battle.net/wow/en/tool/talent-calculator#fb!0010211
glyphs=floating_butterfly/zen_meditation/touch_of_karma/blackout_kick/zen_flight
spec=windwalker
iterations=10000
calculate_scale_factors=0
#dps_plot_stat=haste,crit_rating,mastery,versatility,multistrike,agility
#reforge_plot_output_file=hairyteethrfpof.html
html=hairyscaling.html

head=,id=124262,bonus_id=566
neck=,id=124207,bonus_id=567,enchant_id=5320
shoulder=,id=124273,bonus_id=564/566,gem_id=127763
back=,id=124134,bonus_id=566,enchant_id=5313
chest=,id=116180,bonus_id=69/535/618
wrist=,id=116181,bonus_id=146/536/618
hands=,id=124256,bonus_id=566
waist=,id=124276,bonus_id=564/566,gem_id=127763
legs=,id=124268,bonus_id=566
feet=,id=124252,bonus_id=566
finger1=,id=124188,bonus_id=566,enchant_id=5327
finger2=,id=124636,bonus_id=650/627,enchant_id=5327
trinket1=,id=124517,bonus_id=561/566
trinket2=,id=124225,bonus_id=567
main_hand=,id=124371,bonus_id=566,enchant=mark_of_warsong
off_hand=,id=124368,bonus_id=566,enchant=mark_of_warsong

optimal_raid=1
#override.str_agi_int=1
#override.critical_strike=1
actions.precombat=flask,type=greater_draenic_agility_flask
actions.precombat+=/food,type=salty_squid_roll
actions.precombat=stance,choose=fierce_tiger
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=draenic_agility
initial_chi=6

# Executed every time the actor is available.

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/use_item,name=maalus_the_blood_drinker,if=buff.tigereye_brew_use.up
#actions+=/use_item,name=mirror_of_the_blademaster,if=buff.tigereye_brew_use.up
actions+=/potion,name=draenic_agility,if=buff.maalus.up
actions+=/call_action_list,name=tibce
actions+=/cancel_buff,name=spirit_shift,if=buff.spirit_shift.remains<4&buff.maalus.remains<2&buff.maalus.up
actions+=/call_action_list,name=ebce
actions+=/call_action_list,name=todce
actions+=/call_action_list,name=fofce
actions+=/call_action_list,name=tiger_palmce
actions+=/call_action_list,name=rskce
actions+=/call_action_list,name=cece
actions+=/call_action_list,name=cwce
actions+=/call_action_list,name=jabce

#ALL THE TIMES TO JAB
actions.jabce=jab,if=chi.max-chi>=1

#ALL THE TIMES TO TIGER PALM
actions.tiger_palmce=tiger_palm,if=buff.tiger_power.remains<3|!buff.tiger_power.up
#actions.tiger_palmce+=/tiger_palm,if=energy<30&chi.max-chi>3&buff.combo_breaker_tp.react
#actions.tiger_palmce+=/tiger_palm,if=energy<30&chi.max-chi>2&chi.max-chi<4&buff.combo_breaker_tp.react&!buff.combo_breaker_ce.react&!cooldown.rising_sun_kick.up&!cooldown.fists_of_fury.up
#actions.tiger_palmce+=/tiger_palm,if=energy<30&chi.max-chi<3&chi.max-chi>0&buff.combo_breaker_tp.react&!buff.combo_breaker_ce.react&!cooldown.rising_sun_kick.up&!cooldown.fists_of_fury.up

#ALL THE TIMES TO RSK
actions.rskce=rising_sun_kick,if=buff.tiger_power.up&chi.max-chi<4&buff.tiger_power.remains>3&cooldown.fists_of_fury.remains>3
actions.rskce+=/rising_sun_kick,if=debuff.rising_sun_kick.down|debuff.rising_sun_kick.remains<3

#ALL THE TIMES TO FoF
actions.fofce=fists_of_fury,if=buff.tiger_power.up&debuff.rising_sun_kick.up&buff.tiger_power.remains>5&debuff.rising_sun_kick.remains>5


#ALL THE TIMES TO CE
actions.cece=chi_explosion,if=buff.tiger_power.up&buff.tiger_power.remains>2&debuff.rising_sun_kick.up&debuff.rising_sun_kick.remains>2&chi.max-chi<2&cooldown.rising_sun_kick.remains>2&cooldown.fists_of_fury.remains>2&!(buff.combo_breaker_tp.up&buff.combo_breaker_ce.up)
actions.cece+=/chi_explosion,if=buff.tiger_power.up&buff.tiger_power.remains>2&debuff.rising_sun_kick.up&debuff.rising_sun_kick.remains>2&chi.max-chi<4&cooldown.rising_sun_kick.remains>2&cooldown.fists_of_fury.remains>2&buff.combo_breaker_ce.up&!buff.combo_breaker_tp.up
actions.cece+=/chi_explosion,if=buff.tiger_power.up&buff.tiger_power.remains>2&debuff.rising_sun_kick.up&debuff.rising_sun_kick.remains>2&chi.max-chi<2&cooldown.rising_sun_kick.remains>2&cooldown.fists_of_fury.remains>2&buff.combo_breaker_tp.up&!buff.combo_breaker_ce.up
actions.cece+=/chi_explosion,if=buff.tiger_power.up&buff.tiger_power.remains>2&debuff.rising_sun_kick.up&debuff.rising_sun_kick.remains>2&chi.max-chi<4&cooldown.rising_sun_kick.remains>2&cooldown.fists_of_fury.remains>2&buff.combo_breaker_tp.up&buff.combo_breaker_ce.up
#ALL THE TIMES TO ToD
#-ToD, if target.health <= 10% and ToD.up
actions.todce=touch_of_death,if=target.health.percent<10&cooldown.touch_of_death.up

#ALL THE TIMES TO TiB
actions.tibce=tigereye_brew,if=buff.tigereye_brew.stack>=8&cooldown.fists_of_fury.remains<4&!buff.tigereye_brew_use.up
actions.tibce+=/tigereye_brew,if=buff.tigereye_brew.stack>=10&cooldown.fists_of_fury.remains<4&buff.tigereye_brew_use.remains<3
actions.tibce+=/tigereye_brew,if=buff.tigereye_brew.stack>8&cooldown.fists_of_fury.up&buff.tigereye_brew_use.remains<3
actions.tibce+=/tigereye_brew,if=buff.tigereye_brew.stack>=12&cooldown.fists_of_fury.remains>=12&buff.tigereye_brew_use.remains<=3
actions.tibce+=/tigereye_brew,if=buff.tigereye_brew.stack>19

#ALL THE TIMES TO ENERGIZING BREW
actions.ebce=energizing_brew,if=chi.max-chi>=4&energy<30&cooldown.fists_of_fury.remains>8

#ALL THE TIMES TO CHI WAVE
actions.cwce=chi_wave,if=chi.max-chi>=4&cooldown.fists_of_fury.remains>2&cooldown.rising_sun_kick.remains>2&energy<20

# The bug is easily reproducable with the default list given, simply un-comment the jab line right after storm_earth_fire in the beginning of the APL.

monk="Monk_Windwalker_1h_T18H"
level=100
race=blood_elf
role=dps
position=back
talents=0230023
glyphs=touch_of_death,blackout_kick
spec=windwalker

#Executed before combat begins. Accepts non-harmful actions only.

actions.precombat=flask,type=greater_draenic_agility_flask
actions.precombat+=/food,type=salty_squid_roll
actions.precombat+=/stance,choose=fierce_tiger
actions.precombat+=/legacy_of_the_white_tiger,if=!aura.str_agi_int.up|!aura.critical_strike.up
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=draenic_agility

#Executed every time the actor is available.

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
#actions+=/jab
actions+=/call_action_list,name=opener,if=talent.serenity.enabled&talent.chi_brew.enabled&cooldown.fists_of_fury.up&time<20
actions+=/chi_sphere,if=talent.power_strikes.enabled&buff.chi_sphere.react&chi<chi.max
actions+=/potion,name=draenic_agility,if=buff.serenity.up|(!talent.serenity.enabled&(trinket.proc.agility.react|trinket.proc.multistrike.react))|buff.bloodlust.react|target.time_to_die<=60
actions+=/blood_fury,if=buff.tigereye_brew_use.up|target.time_to_die<18
actions+=/berserking,if=buff.tigereye_brew_use.up|target.time_to_die<18
actions+=/arcane_torrent,if=chi.max-chi>=1&(buff.tigereye_brew_use.up|target.time_to_die<18)
actions+=/chi_brew,if=chi.max-chi>=2&((charges=1&recharge_time<=10)|charges=2|target.time_to_die<charges*10)&buff.tigereye_brew.stack<=16
actions+=/tiger_palm,if=!talent.chi_explosion.enabled&buff.tiger_power.remains<6.6
actions+=/tiger_palm,if=talent.chi_explosion.enabled&(cooldown.fists_of_fury.remains<5|cooldown.fists_of_fury.up)&buff.tiger_power.remains<5
actions+=/tigereye_brew,if=buff.tigereye_brew_use.down&buff.tigereye_brew.stack=20
actions+=/tigereye_brew,if=buff.tigereye_brew_use.down&buff.tigereye_brew.stack>=9&buff.serenity.up
actions+=/tigereye_brew,if=talent.chi_explosion.enabled&buff.tigereye_brew.stack>=1&t18_class_trinket&set_bonus.tier18_4pc=1&buff.tigereye_brew_use.down
actions+=/tigereye_brew,if=buff.tigereye_brew_use.down&buff.tigereye_brew.stack>=9&cooldown.fists_of_fury.up&chi>=3&debuff.rising_sun_kick.up&buff.tiger_power.up
actions+=/tigereye_brew,if=talent.hurricane_strike.enabled&buff.tigereye_brew_use.down&buff.tigereye_brew.stack>=9&cooldown.hurricane_strike.up&chi>=3&debuff.rising_sun_kick.up&buff.tiger_power.up
actions+=/tigereye_brew,if=buff.tigereye_brew_use.down&chi>=2&(buff.tigereye_brew.stack>=16|target.time_to_die<40)&debuff.rising_sun_kick.up&buff.tiger_power.up
actions+=/fortifying_brew,if=target.health.percent<10&cooldown.touch_of_death.remains=0&(glyph.touch_of_death.enabled|chi>=3)
actions+=/touch_of_death,if=target.health.percent<10&(glyph.touch_of_death.enabled|chi>=3)
actions+=/rising_sun_kick,if=(debuff.rising_sun_kick.down|debuff.rising_sun_kick.remains<3)
actions+=/serenity,if=chi>=2&buff.tiger_power.up&debuff.rising_sun_kick.up
actions+=/fists_of_fury,if=buff.tiger_power.remains>cast_time&debuff.rising_sun_kick.remains>cast_time&energy.time_to_max>cast_time&!buff.serenity.up
actions+=/hurricane_strike,if=energy.time_to_max>cast_time&buff.tiger_power.remains>cast_time&debuff.rising_sun_kick.remains>cast_time&buff.energizing_brew.down
actions+=/energizing_brew,if=cooldown.fists_of_fury.remains>6&(!talent.serenity.enabled|(!buff.serenity.remains&cooldown.serenity.remains>4))&energy+energy.regen<50
actions+=/call_action_list,name=st,if=active_enemies<3&(level<100|!talent.chi_explosion.enabled)
actions+=/call_action_list,name=st_chix,if=active_enemies=1&talent.chi_explosion.enabled
actions+=/call_action_list,name=cleave_chix,if=(active_enemies=2|active_enemies=3&!talent.rushing_jade_wind.enabled)&talent.chi_explosion.enabled
actions+=/call_action_list,name=aoe_norjw,if=active_enemies>=3&!talent.rushing_jade_wind.enabled&!talent.chi_explosion.enabled
actions+=/call_action_list,name=aoe_norjw_chix,if=active_enemies>=4&!talent.rushing_jade_wind.enabled&talent.chi_explosion.enabled
actions+=/call_action_list,name=aoe_rjw,if=active_enemies>=3&talent.rushing_jade_wind.enabled
actions+=/tiger_palm,if=buff.combo_breaker_tp.react

actions.aoe_rjw=chi_explosion,if=chi>=4&cooldown.fists_of_fury.remains>4
actions.aoe_rjw+=/rushing_jade_wind
actions.aoe_rjw+=/chi_wave,if=energy.time_to_max>2&buff.serenity.down
actions.aoe_rjw+=/chi_burst,if=energy.time_to_max>2&buff.serenity.down
actions.aoe_rjw+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking&buff.serenity.down
actions.aoe_rjw+=/blackout_kick,if=buff.combo_breaker_bok.react|buff.serenity.up
actions.aoe_rjw+=/tiger_palm,if=buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.aoe_rjw+=/blackout_kick,if=chi.max-chi<2&cooldown.fists_of_fury.remains>3
actions.aoe_rjw+=/chi_torpedo,if=energy.time_to_max>2&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.aoe_rjw+=/expel_harm,if=chi.max-chi>=2&health.percent<95
actions.aoe_rjw+=/jab,if=chi.max-chi>=2

actions.aoe_norjw_chix=chi_explosion,if=chi>=4&cooldown.fists_of_fury.remains>4
actions.aoe_norjw_chix+=/rising_sun_kick,if=chi=chi.max
actions.aoe_norjw_chix+=/chi_wave,if=energy.time_to_max>2
actions.aoe_norjw_chix+=/chi_burst,if=energy.time_to_max>2
actions.aoe_norjw_chix+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking
actions.aoe_norjw_chix+=/chi_torpedo,if=energy.time_to_max>2&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.aoe_norjw_chix+=/spinning_crane_kick

actions.cleave_chix=chi_explosion,if=chi>=4&cooldown.fists_of_fury.remains>2
actions.cleave_chix+=/tiger_palm,if=buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.cleave_chix+=/chi_wave,if=energy.time_to_max>2
actions.cleave_chix+=/chi_burst,if=energy.time_to_max>2
actions.cleave_chix+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking
actions.cleave_chix+=/chi_torpedo,if=energy.time_to_max>2&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.cleave_chix+=/expel_harm,if=chi.max-chi>=2&health.percent<95
actions.cleave_chix+=/jab,if=chi.max-chi>=2

actions.st_chix=chi_explosion,if=chi>=2&buff.combo_breaker_ce.react&cooldown.fists_of_fury.remains>2
actions.st_chix+=/tiger_palm,if=buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.st_chix+=/rising_sun_kick
actions.st_chix+=/chi_wave,if=energy.time_to_max>2
actions.st_chix+=/chi_burst,if=energy.time_to_max>2
actions.st_chix+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking
actions.st_chix+=/expel_harm,if=chi.max-chi>=2&health.percent<95
actions.st_chix+=/jab,if=chi.max-chi>=2
actions.st_chix+=/chi_explosion,if=chi>=5&cooldown.fists_of_fury.remains>4
actions.st_chix+=/chi_torpedo,if=energy.time_to_max>2&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.st_chix+=/tiger_palm,if=chi=4&!buff.combo_breaker_tp.react

actions.st=blackout_kick,if=set_bonus.tier18_2pc=1&buff.combo_breaker_bok.react
actions.st+=/tiger_palm,if=set_bonus.tier18_2pc=1&buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.st+=/rising_sun_kick
actions.st+=/blackout_kick,if=buff.combo_breaker_bok.react|buff.serenity.up
actions.st+=/tiger_palm,if=buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.st+=/chi_wave,if=energy.time_to_max>2&buff.serenity.down
actions.st+=/chi_burst,if=energy.time_to_max>2&buff.serenity.down
actions.st+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking&buff.serenity.down
actions.st+=/chi_torpedo,if=energy.time_to_max>2&buff.serenity.down&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.st+=/blackout_kick,if=chi.max-chi<2
actions.st+=/expel_harm,if=chi.max-chi>=2&health.percent<95
actions.st+=/jab,if=chi.max-chi>=2

actions.opener=tigereye_brew,if=buff.tigereye_brew_use.down&buff.tigereye_brew.stack>=9
actions.opener+=/blood_fury,if=buff.tigereye_brew_use.up
actions.opener+=/berserking,if=buff.tigereye_brew_use.up
actions.opener+=/arcane_torrent,if=buff.tigereye_brew_use.up&chi.max-chi>=1
actions.opener+=/fists_of_fury,if=buff.tiger_power.remains>cast_time&debuff.rising_sun_kick.remains>cast_time&buff.serenity.up&buff.serenity.remains<1.5
actions.opener+=/tiger_palm,if=buff.tiger_power.remains<2
actions.opener+=/rising_sun_kick
actions.opener+=/blackout_kick,if=chi.max-chi<=1&cooldown.chi_brew.up|buff.serenity.up
actions.opener+=/chi_brew,if=chi.max-chi>=2
actions.opener+=/serenity,if=chi.max-chi<=2
actions.opener+=/jab,if=chi.max-chi>=2&!buff.serenity.up

actions.aoe_norjw=chi_wave,if=energy.time_to_max>2&buff.serenity.down
actions.aoe_norjw+=/chi_burst,if=energy.time_to_max>2&buff.serenity.down
actions.aoe_norjw+=/zen_sphere,cycle_targets=1,if=energy.time_to_max>2&!dot.zen_sphere.ticking&buff.serenity.down
actions.aoe_norjw+=/blackout_kick,if=buff.combo_breaker_bok.react|buff.serenity.up
actions.aoe_norjw+=/tiger_palm,if=buff.combo_breaker_tp.react&buff.combo_breaker_tp.remains<=2
actions.aoe_norjw+=/blackout_kick,if=chi.max-chi<2&cooldown.fists_of_fury.remains>3
actions.aoe_norjw+=/chi_torpedo,if=energy.time_to_max>2&(((charges=2|(charges=1&recharge_time<=4))&!talent.celerity.enabled)|((charges=3|(charges=2&recharge_time<=4))&talent.celerity.enabled))
actions.aoe_norjw+=/spinning_crane_kick

head=mask_of_the_hurricanes_eye,id=124262,bonus_id=566
neck=choker_of_the_great_betrayer,id=124210,bonus_id=566,enchant=gift_of_multistrike
shoulders=mantle_of_the_hurricanes_eye,id=124273,bonus_id=566
back=cloak_of_desperate_temerity,id=124134,bonus_id=566,enchant=gift_of_multistrike
chest=tunic_of_the_soulbinder,id=124245,bonus_id=566
wrists=bloodcult_bracers,id=124279,bonus_id=566
hands=fistwraps_of_the_hurricanes_eye,id=124256,bonus_id=566
waist=flayed_demonskin_belt,id=124277,bonus_id=566
legs=legwraps_of_the_hurricanes_eye,id=124268,bonus_id=566
feet=jungle_assassins_footpads,id=124252,bonus_id=566
finger1=spellbound_runic_band_of_unrelenting_slaughter,id=118307,enchant=gift_of_multistrike
finger2=portal_key_signet,id=124189,bonus_id=566,enchant=gift_of_multistrike
trinket1=sacred_draenic_incense,id=124517,bonus_id=566
trinket2=soul_capacitor,id=124225,bonus_id=566
main_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_the_thunderlord
off_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_the_thunderlord

#Gear Summary
#gear_ilvl=712.50
#gear_agility=3891
#gear_stamina=5184
#gear_crit_rating=1416
#gear_haste_rating=672
#gear_mastery_rating=131
#gear_multistrike_rating=2408
#gear_versatility_rating=243
#gear_armor=1246
#set_bonus=tier18_2pc=1
#set_bonus=tier18_4pc=1

**Comment by navv1234** [comment]
> actions+=/chi_brew,if=chi.max-chi>=2&((charges=1&recharge_time<=10)|charges=2|target.time_to_die 

This line in the provided APL is lacking a right parenthesis, which will abort the simulation.

**Comment by MoldySponge** [comment]
While I would like very much the error in pasting that occurred here for whatever reason to be the actual problem, that is not the case. Something as simple as the following APL works if rising_sun_kick is first and crashes otherwise:

monk="Hairyteeth"
origin="https://us.api.battle.net/wow/character/kilrogg/hairyteeth/advanced"
thumbnail="http://us.battle.net/static-render/us/kilrogg/159/167017375-avatar.jpg"
level=100
race=night_elf
timeofday=night
role=dps
position=back
professions=leatherworking=700/skinning=700
talents=http://us.battle.net/wow/en/tool/talent-calculator#fb!0020212
glyphs=floating_butterfly/zen_meditation/touch_of_karma/blackout_kick/zen_flight
spec=windwalker

actions.precombat=flask,type=greater_draenic_agility_flask
actions.precombat+=/food,type=salty_squid_roll
actions.precombat+=/stance,choose=fierce_tiger
actions.precombat+=/legacy_of_the_white_tiger,if=!aura.str_agi_int.up|!aura.critical_strike.up
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=draenic_agility

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/rising_sun_kick
actions+=/fists_of_fury
actions+=/jab

head=mask_of_the_hurricanes_eye,id=124262,bonus_id=566
neck=faulty_detonator_cord,id=124207,bonus_id=567,enchant=75mult
shoulders=mantle_of_the_hurricanes_eye,id=124273,bonus_id=564/566,gems=75mult
back=cloak_of_desperate_temerity,id=124134,bonus_id=566,enchant=gift_of_multistrike
chest=supple_vest,id=116180,bonus_id=69/535/618
wrists=supple_bracers,id=116181,bonus_id=146/536/618
hands=fistwraps_of_the_hurricanes_eye,id=124256,bonus_id=566
waist=waistwrap_of_banishment,id=124276,bonus_id=564/566,gems=75mult
legs=legwraps_of_the_hurricanes_eye,id=124268,bonus_id=566
feet=jungle_assassins_footpads,id=124252,bonus_id=566
finger1=serrated_demontooth_ring,id=124188,bonus_id=566,enchant=50mult
finger2=maalus_the_blood_drinker,id=124636,bonus_id=627/650,enchant=50mult
trinket1=sacred_draenic_incense,id=124517,bonus_id=561/566
trinket2=soul_capacitor,id=124225,bonus_id=567
main_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_warsong
off_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_warsong

# Here is the same APL again but in a different order which should be irrelevant to crashes but still crashes:
monk="Hairyteeth"
origin="https://us.api.battle.net/wow/character/kilrogg/hairyteeth/advanced"
thumbnail="http://us.battle.net/static-render/us/kilrogg/159/167017375-avatar.jpg"
level=100
race=night_elf
timeofday=night
role=dps
position=back
professions=leatherworking=700/skinning=700
talents=http://us.battle.net/wow/en/tool/talent-calculator#fb!0020212
glyphs=floating_butterfly/zen_meditation/touch_of_karma/blackout_kick/zen_flight
spec=windwalker

actions.precombat=flask,type=greater_draenic_agility_flask
actions.precombat+=/food,type=salty_squid_roll
actions.precombat+=/stance,choose=fierce_tiger
actions.precombat+=/legacy_of_the_white_tiger,if=!aura.str_agi_int.up|!aura.critical_strike.up
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=draenic_agility

actions=auto_attack
actions+=/invoke_xuen
actions+=/storm_earth_and_fire,target=2,if=debuff.storm_earth_and_fire_target.down
actions+=/storm_earth_and_fire,target=3,if=debuff.storm_earth_and_fire_target.down
actions+=/fists_of_fury
actions+=/jab
actions+=/rising_sun_kick

head=mask_of_the_hurricanes_eye,id=124262,bonus_id=566
neck=faulty_detonator_cord,id=124207,bonus_id=567,enchant=75mult
shoulders=mantle_of_the_hurricanes_eye,id=124273,bonus_id=564/566,gems=75mult
back=cloak_of_desperate_temerity,id=124134,bonus_id=566,enchant=gift_of_multistrike
chest=supple_vest,id=116180,bonus_id=69/535/618
wrists=supple_bracers,id=116181,bonus_id=146/536/618
hands=fistwraps_of_the_hurricanes_eye,id=124256,bonus_id=566
waist=waistwrap_of_banishment,id=124276,bonus_id=564/566,gems=75mult
legs=legwraps_of_the_hurricanes_eye,id=124268,bonus_id=566
feet=jungle_assassins_footpads,id=124252,bonus_id=566
finger1=serrated_demontooth_ring,id=124188,bonus_id=566,enchant=50mult
finger2=maalus_the_blood_drinker,id=124636,bonus_id=627/650,enchant=50mult
trinket1=sacred_draenic_incense,id=124517,bonus_id=561/566
trinket2=soul_capacitor,id=124225,bonus_id=567
main_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_warsong
off_hand=hammer_of_wicked_infusion,id=124371,bonus_id=566,enchant=mark_of_warsong

# I also gave multiple examples,
So even if the paste on the one you posted didn't work because of the syntax the paste on the others also replicate the bug. This happened when my own chi explosion rotation worked fine on the release version but the exact same .simc does not work in the nightly. Did you try the other APL's or to replicate the way the problem the way I described? 

I'm not trying to be rude, I'm simply asking because I've tried multiple times in different ways on two different machines and if you had different results (even with the syntax on the one fixed) I would very much like to know.

Also, while I haven't delved into the code on Simulation Craft I know it is creating a string of actions and ultimately my guess would be until it tried running that line with the syntax error it would run (or attempt to) without crashing in the same way. example: when I mess up syntax it usually tells me in the console output rather than crashing the whole program.

**Comment by navv1234** [comment]
Fixing the error and uncommenting Jab did nothing. This latest one you gave seems to yield a crash.

**Comment by navv1234** [comment]
It's fixed in da6c441, will be in next release.

**Comment by scamille** [comment]
5e0d01362b49ab43d5b8ea1da06292d80cf034d8 should improve error reporting in the GUI for future problems as well.

And thanks for reporting this issue.
