### ISSUE TITLE
ilevel attribute in XML reporting

### ISSUE THREAD

**Issue by effinhunter** [simulationcraft/simc#2642]
When generating XML output, there is currently no reporting of ilevel attributes. This is useful for distinguishing between items with and without custom item levels, which helps when theorycrafting potential new items such as the Mythic Dungeon 690-725 ilevel versions.

The intent would be that the following .simc settings line:
trinket2=blood_seal_of_azzakel,id=109995,ilevel=725

Would generate the following item element in the XML report:
< item name="blood_seal_of_azzakel" slot="13" id="109995" ilevel="725" / >

Currently, the output does not output ilevel attributes, so a normal item and the custom item are indistinguishable.
< item name="blood_seal_of_azzakel" slot="13" id="109995" / >

**Comment by scamille** [comment]
@navv1234 is this the correct field to use?

diff --git a/engine/player/sc_item.cpp b/engine/player/sc_item.cpp
index a727aa8..41dd90e 100644
--- a/engine/player/sc_item.cpp
+++ b/engine/player/sc_item.cpp
@@ -636,6 +636,9 @@
   if ( parsed.addon_stats.size() > 0 || ! parsed.encoded_addon.empty() )
     writer.print_attribute( "addon", encoded_addon() );
 
+  if ( parsed.item_level > 0 )
+    writer.print_attribute( "item_level", util::to_string( parsed.item_level ) );
+
   writer.end_tag( "item" );
 }

**Comment by navv1234** [comment]
Use `item_t::item_level()` to avoid any/all confusion about what ilevel the item was simulated with. The sim has a wide variety of ilevel manipulators.

**Comment by scamille** [comment]
Fixed in 96c3cb3ee813b60d02cf3d3b17bbc2a900409035

**Comment by navv1234** [comment]
One clarifying question. Did you only want to report the item level in the xml, if the user specifies `ilevel` option on the item? 

The if check does exactly that. I hope that global ilevel settings are elsewhere in the xml report, otherwise it's not going to work when the user for example uses the `scale_to_itemlevel` option.

**Comment by effinhunter** [comment]
For my purposes, all I would need is an item level reported for custom ilevel commands per item in a Simcraft profile. I think if I were to use scale_to_itemlevel, I would want that as more of a global setting somewhere in the resulting XML to be able to parse it, but I have no plans for that kind of test right now with XML results enabled.
