### ISSUE TITLE
[Death Knight] Unending Hunger with Glyph of Resilient Grip and Glyph of Tranquil Grip

### ISSUE THREAD

**Issue by bpalguta** [simulationcraft/simc#2644]
When using Glyph of Resilient Grip and Glyph of Tranquil Grip, Death Grip can be cast with no GCD penalty to add a stack of Hungering Blows that procs from the trinket Unending Hunger. Is there anyways simcraft can be updated to reflect this interaction?

**Comment by navv1234** [comment]
Hmm, does this let you spam Death Grip for rapid stack generation, if you target a boss (who is presumably immune to gripping)?

**Comment by bpalguta** [comment]
It indeed does. Lets you end up with 18+ seconds of the buff

**Comment by navv1234** [comment]
Interesting, okay. I'll see what I can do.

**Comment by bpalguta** [comment]
Here's just a single parse where I know this trick is used. I've pinned the
related info.
https://www.warcraftlogs.com/reports/QVvRYN281Kt4pfPX#fight=80&type=damage-done&source=8&start=103761457&end=103773071&pins=0%24Separate%24%23244F4B%24casts%240%240.0.0.Any%2472515438.0.0.DeathKnight%24true%240.0.0.Any%24false%2449576%5E0%24Separate%24%23909049%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%2472515438.0.0.DeathKnight%24false%24183941

**Comment by navv1234** [comment]
Blizzard hotfixed this recently, so not going to bother putting in the 0cd death-grip just for the purpose of locking the sim up :).
