### ISSUE TITLE
Constant Crashing and Lock Ups on Windows 10 x64 version

### ISSUE THREAD

**Issue by JamesAMB** [simulationcraft/simc#2646]
The program opens up completely fine, and I even run it as administrator. Import all works fine, but when I actually go to simulate, my computer locks up and freezes for the duration of the simulation. Audio and video lags extremely bad and just straight up can't do anything. The old build doesn't do this, but of course the old build isn't updated. Also, because it freezes my computer it causes my video card to actually crash and get an error. I don't know what's going on but it's extremely frustrating.

I'm running Windows 10 x64
8350 8 Core AMD
Nvidia 770 video card

**Comment by navv1234** [comment]
Tried lowering the process priority from the GUI options?

**Comment by Collisionc** [comment]
Yeah, change the process priority. It should default to low, but I think there was a build where I had it set to normal by accident at some point. You can also reduce the number of threads.

**Comment by mrdmnd** [comment]
This seems to be resolved in later builds; it defaults to low now.
