### ISSUE TITLE
GUI spell query error box + overrides not applying in sim

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#2647]
Theres some oddities happening with the spell query and spell override system.
Using the october 19 GUI version of SimC 64-bit found at downloads.simulationcraft.org

So doing a spell query, such as

![image](https://cloud.githubusercontent.com/assets/2127021/10941135/9e6404f6-82cf-11e5-9d75-6f197fb15336.png)

will cause this to happen.

![image](https://cloud.githubusercontent.com/assets/2127021/10941152/b781551a-82cf-11e5-86ad-869550a8bb72.png)

Hitting OK will make the error box go away and the query goes through seemingly without a problem.

Then there is the spell overrides not applying. Say I want to override enrage's damage buff effect from 10% to 15%. Doing override.spell_data=effect.155456.base_value=15 in the overrides tab or in the actor sim tab will cause the spell query to return the new 15% value in the second effect field of spell ID  12880 (Warrior enrage), but the simulation will not reflect this. Even trying an absurd value like 200 will not change the damage output. Here's the .simc generated by the GUI.

http://pastebin.com/raw.php?i=h0TnMzHC

Lastly, when doing an override, the top of the html report will show the 'current simulator hotfixes' and 'current simulator-wide DBC data overrides'. The hotfixes will expand normally, but when expanding the overrides, this comes out, and then the program will sometimes lag out and fade out like its frozen/hanging, depending on how many of these override lines pop up. This time, it was 6, but other times, its 50-100 lines of the same thing. PC is a 4.6GHz 8-core intel and 32GB DDR4-3000 RAM.

![image](https://cloud.githubusercontent.com/assets/2127021/10941641/1157ee9e-82d2-11e5-887d-01861ac747b0.png)

**Comment by ssateneth** [comment]
Sorry about the font going haywire in the post. I just copy pasted the contents of the .simc file since it wouldnt let me attach it.

**Comment by ssateneth** [comment]
Just to add on, running the same sim multiple times will add more lines.

Changing the override value to something else and running it again will mix the old override values and the new ones.

![image](https://cloud.githubusercontent.com/assets/2127021/10942846/6a613842-82d7-11e5-942b-61e0b4812ff0.png)

**Comment by ssateneth** [comment]
So the error box on doing spell queries is fixed now. The overrides are still not applying though, even though the spell query will show the updated overridden value.

**Comment by navv1234** [comment]
Overrides work fine, from what I can see. Not sure if @collisionc built a release with the latest commit that fixed them.

**Comment by ssateneth** [comment]
In case its difficult to follow what im doing, here are the .simc files
 https://dl.dropboxusercontent.com/u/9768004/simc-profiles.zip

and here is a video i took showing whats happening. 3 minutes long.
http://www.twitch.tv/ssateneth/v/24339851

**Comment by ssateneth** [comment]
Seems fixed now. Changing to webengine instead of webkit fixed the hang problem too.
