### ISSUE TITLE
Wowhead tooltips freeze the client

### ISSUE THREAD

**Issue by 1stNoob** [simulationcraft/simc#2648]
In the results tab, if i hover over "Uther's Insight" the client freeze for about 20 secounds.

**Comment by navv1234** [comment]
You can add "wowhead_tooltips=0" to the override tab, it should be fixed then. Unfortunately it also removes the buff/action tooltips from the report.

**Comment by mrdmnd** [comment]
Was this ever looked into, @scamille ?

**Comment by scamille** [comment]
Not by me, that's something for navv1234 :-)
Maybe something has been done, I remember him communicating with wowhead devs at some point.

@1stNoob is this still a problem?

**Comment by navv1234** [comment]
We use wowdb tooltips now. Guess I forgot to close this issue.

**Comment by scamille** [comment]
Ok great. The official release probably does not yet contain them, but you can find nightly releases at http://downloads.simulationcraft.org/?C=M;O=D
