### ISSUE TITLE
No mastery rating for Holy Paladin

### ISSUE THREAD

**Issue by Nolivfr** [simulationcraft/simc#2649]
Hi

There is a problem with Holy Paladin rating, mastery always shows -0.00/-0.01-0.02, which I think is an error :smile:
I reported this on IRC and got confirmation that Holy Paladin module (all heal modules?) is currently "broken" (read: not updated).

![Hpal mastery scaling problem](http://i.imgur.com/ge6SjN7.png)

- SimC 622-01

**Comment by scamille** [comment]
Yes the healing modules are not fully supported.
Priest is largely outdated, and all the other never have been fully implemented.

This won't change unless someone dedicated picks up work on such a module. In any case unlikely before legion.

Related to this: We do have plans to develop a better system of annotating classes/specs/other things in 7.0, specially to inform about such unfinished modules.
