### ISSUE TITLE
TMI

### ISSUE THREAD

**Issue by serrufs** [simulationcraft/simc#2654]
why in the "TMI Standard boss" is not present "T18M / H / N / L"?

For http://www.wowhead.com/item=133598 it ignores the demon boss or humanoid.

**Comment by scamille** [comment]
T18 TMI seems to be implemented in the CLI, just not hooked up to the GUI.

**Comment by serrufs** [comment]
And add it to the GUI?

**Comment by mrdmnd** [comment]
I've done this in the PR here: https://github.com/simulationcraft/simc/pull/2678
