### ISSUE TITLE
initial_combo_points is an 'unknown option'

### ISSUE THREAD

**Issue by crtab** [simulationcraft/simc#2660]
Should be reproducable using any of the default rogue imports. Attempting to use initial_combo_points fails with an 'unknown option' error.

Usage is describe here:
https://github.com/simulationcraft/simc/wiki/Rogues

**Comment by crtab** [comment]
Cheers for the fix - unrelated, is there an artifact repo where I can pick up CI builds or is my only option to build it myself?

**Comment by navv1234** [comment]
legion-dev branch has legion development, but it's still so early that there are no builds of it. I imagine eventually windows "nightly" builds are going to appear to our download server, like we do with live.

**Comment by crtab** [comment]
I'm referring to master builds - I'm looking for a build with this change in it but the last of the Windows builds was on the 27th of Nov. I followed through to Travis CI but couldn't find a reference to an artifact repo.

**Comment by scamille** [comment]
checkout https://github.com/simulationcraft/simc/wiki/HowToBuild for how to build SimC yourself. This is definitely the fastest way, and you're independent from any maintainer.

I'm not sure how exactly windows nightly builds (http://downloads.simulationcraft.org/?C=M;O=D) are triggered, but in the end collisionc decides how and when he builds those. We are lucky to even have them ( we didn't have them in the past ).

Other than that, there are no automated builds you can pick up. Try building SimC yourself, it should be quite easy to do so - if not, tell us what can be improved. Building the GUI is by nature a bit more complicated though.

**Comment by crtab** [comment]
Thanks for the direction. I've managed to build SimC, which was quite easy to compile with the instructions provided. I've shelved building the GUI for now due to the dependancy on QT - I discovered a little too late that the QT 5.5.1 pre-built binaries are not compatible with VS 2015.
