### ISSUE TITLE
Change initial_combo_points to add combo points as part of actions.precombat

### ISSUE THREAD

**Issue by crtab** [simulationcraft/simc#2661]
In an attempt to sim the benefit of starting a fight with combo points pre-existing, I used initial_combo_points but it adds the combo points at Combat Time = 0.0. 

The use case here is: Using the sub rogue profile as an example, after having preserved combo points from a previous kill or Honor Among Thieves proc, I would then cast Premeditation and slice_and_dice as precombat actions using my preserved combo points. The current result is that slice_and_dice would use only the combo points I gained from premeditation and the combo points from 'initial_combo_points' are added when combat begins at time 0.

For this to work, I would need initial_combo_points to add combo points similar to the way Premiditation does as a precombat action or initial_combo_points should add combo points prior to precombat actions.

Alternatively if there is a way to proc Honor Among Thieves as a pre-combat action.

**Comment by crtab** [comment]
I managed to get the fix I was looking for by modifying the fix from #2660 so that intial_combo_points are set during rogue_t::init_resources rather than after the super class' combat_begin. 

Line 5981
// rogue_t::init_resources =================================================

void rogue_t::init_resources( bool force )
{
  player_t::init_resources( force );

  resources.current[ RESOURCE_COMBO_POINT ] = 0;

  if (initial_combo_points > 0)
	  resources.current[RESOURCE_COMBO_POINT] = initial_combo_points; // User specified Combo Points.
}

Overloaded rogue_t::combat_begin() can then be removed.

I can not commit this change as I do not have Git adequately set up on my dev box right now.

**Comment by mrdmnd** [comment]
Can you fork the repo, create a pull request, and CC me? I'll merge this for you.

**Comment by navv1234** [comment]
Fixed in bef57b2.
