### ISSUE TITLE
Results outside of margin of error with scaling on/off

### ISSUE THREAD

**Issue by Kylis** [simulationcraft/simc#2663]
So I ran a set of sims with scaling off and then decided I wanted to run them with scaling on but got results that were different by more than the margin of error listed on either sim. Let me know if you need any files to go with this or anything as this seems very odd since the only thing I changed was listing the scaling I figured the sims would be within each others margin of error.

**Comment by scamille** [comment]
Thanks for the report.

Some files for reproducing the problem would be great. Preferrably the simc_gui.simc file you can find in your SimC folder, where all the options for the last simulations are found.

Also some exact dps values & error margins which you observed.

Technically, the dps difference can be outside of the error margin (=95% confidence interval) we give. If my understanding of the underlying statistics is completely correct, if you repeat the simulation eg. 100 times, the true DPS value will be in the each confidence interval 95 of the times. See https://en.wikipedia.org/wiki/Confidence_interval#Meaning_and_interpretation

**Comment by mrdmnd** [comment]
Please attach the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file that resides in your simulation craft directory; it contains all the relevant info for us to work with.

**Comment by Collisionc** [comment]
No response, closing.
