### ISSUE TITLE
simulate

### ISSUE THREAD

**Issue by xhighpaulx** [simulationcraft/simc#2664]
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.attack_power_multiplier=1
override.spell_power_multiplier=1
override.critical_strike=1
override.haste=1
override.multistrike=1
override.mastery=1
override.stamina=1
override.str_agi_int=1
override.versatility=1
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by scamille** [comment]
There seems to be no input/text in the simulate tab when you hit the simulate button. Therefore there is nothing to simulate, which results in the error.

**Comment by mrdmnd** [comment]
I'm assuming this is a user issue with importing character data. Will close, if there's something substantial here, please feel free to re-open.
