### ISSUE TITLE
Trying to Sim using MrRobot

### ISSUE THREAD

**Issue by Hellbounder** [simulationcraft/simc#2665]
SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.025
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.9
optimal_raid=0
override.attack_power_multiplier=1
override.spell_power_multiplier=1
override.critical_strike=1
override.haste=1
override.multistrike=1
override.mastery=1
override.stamina=1
override.str_agi_int=1
override.versatility=1
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,sta,ap,crit,haste,mastery,mult,wdps,wohdps,armor,bonusarmor
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by scamille** [comment]
There seems to be no input/text in the simulate tab when you hit the simulate button. Therefore there is nothing to simulate, which results in the error.

Please copy-paste the profile from Ask Mr.Robot properly into the simulate tab before hitting *simulate*.

**Comment by Hellbounder** [comment]
the normal process up until a few weeks ago for me was to take the Mr robot string and paste on welcome tab of Simcraft. then hit enter and await the result. 

now I just tried as you said entering into the simulate tab itself and it does the same thing.

**Comment by Hellbounder** [comment]
SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.025
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.9
optimal_raid=0
override.attack_power_multiplier=1
override.spell_power_multiplier=1
override.critical_strike=1
override.haste=1
override.multistrike=1
override.mastery=1
override.stamina=1
override.str_agi_int=1
override.versatility=1
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,sta,ap,crit,haste,mastery,mult,wdps,wohdps,armor,bonusarmor
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

Below is my info i copy pasted in to the text field as requested and above is the message i get asking to send you.

Log saved to: warrior=onsie
origin="http://www.askmrrobot.com/wow/player/eu/silvermoon/onsie"
level=100
race=human
role=attack
spec=arms
professions=Jewelcrafting=700/Blacksmithing=700
talents=2113311
glyphs=58095/58096/58098/58372/58384

head=faceguard_of_iron_wrath,id=124334,bonus_id=40/565/567,upgrade=2,gem_id=127762
neck=glowing_taladite_pendant,id=115799,bonus_id=58/539/618,upgrade=2,enchant_id=5317
shoulders=doomcriers_shoulderplates,id=124343,bonus_id=561/566,upgrade=2
chest=breastplate_of_iron_wrath,id=124319,bonus_id=566,upgrade=2
waist=girdle_of_demonic_wrath,id=124350,bonus_id=567,upgrade=2
legs=legplates_of_iron_wrath,id=124340,bonus_id=567,upgrade=2
feet=cruel_hope_crushers,id=124323,bonus_id=567,upgrade=2
wrists=breachscarred_wristplates,id=124353,bonus_id=566,upgrade=2
hands=gauntlets_of_iron_wrath,id=124329,bonus_id=567,upgrade=2
finger1=congealed_globule_loop,id=124197,bonus_id=567,upgrade=2,enchant_id=5326
finger2=thorasus_the_stone_heart_of_draenor,id=124634,bonus_id=639/649,enchant_id=5324
trinket1=worldbreakers_resolve,id=124523,bonus_id=564/566,upgrade=2,gem_id=127762
trinket2=empty_drinking_horn,id=124238,bonus_id=564/566,upgrade=2,gem_id=127762
back=cloak_of_incendiary_wrath,id=124144,bonus_id=567,upgrade=2,enchant_id=5312
main_hand=maul_of_tyranny,id=124375,bonus_id=561/566,upgrade=2,enchant_id=5384

**Comment by scamille** [comment]
Your simulate tab should looks more or less like this:

![simc_simulatetab](https://cloud.githubusercontent.com/assets/1479348/11761182/56d50da4-a0b8-11e5-8ad9-6de82c90ff91.jpg)

**Comment by Hellbounder** [comment]
Ok thank you, it is now working just i have to correct how i use it now, thanks a lot for helping me resolve this much appreciated.

**Comment by scamille** [comment]
Ok great!

I'm not sure how it even worked before when pasting to the welcome tab. Maybe that feature was removed when cleaning up the GUI. Sorry for the inconvenience.

But the way I showed you is how it is supposed to be done ;)
