### ISSUE TITLE
mirror of the blademaster trinket broken?

### ISSUE THREAD

**Issue by Twinkeli** [simulationcraft/simc#2666]
Straight to the point.

Mirror of the blademaster trinket should update dynamically with haste, but it seems to have some problems in sims. (atleast with rapid fire)

I'm going to link you two(2) simc APLs with same gear setups and stuff to show some proof of this.

http://pastebin.com/dd1EJ3qv
"actions+=/use_item,name=mirror_of_the_blademaster"

http://pastebin.com/s3ihV3Gz
"actions+=/use_item,name=mirror_of_the_blademaster,if=buff.rapid_fire.up"

These are sub 1min fights where both APL's get one trinket usage, due to rapid fire being 15sec haste buff it should benefit both APLs the same amount, but it gives nothing to the first APL because it uses the trinket 1second before it uses rapid fire.

I have tried to make some extremely simple 2-3 line APLs where i try to reproduce this but in those sims it somehow seems to update dynamically.

It also seems to not update dynamically with hunter 2pc bonus (buff.rapid_fire_t18), i haven't tested other classes/enchants/bloodlust, neither have i tested different trinket procs like agility/multistrike etc.

Here is a screenshot of my sim results http://i.imgur.com/NjEuE7l.png

**Comment by Twinkeli** [comment]
Also seems like the hunter 2pc set bonus isn't activating careful aim on sims

**Comment by scamille** [comment]
@lokrick do you want to take a look?

Twinkell: I can't guarantee that there is a dev still actively interested in the master branch. Many are already working on legion. If you can provide specific changes for the default APL, that makes it much more easy to just integrate them. Dunno how complicated 2pc bonus is.

**Comment by navv1234** [comment]
Mirror of Blademaster Felstorm is intentionally snapshotting attack speed in the simulator. Do you have a WCL log or two to show otherwise?

**Comment by navv1234** [comment]
Fixed in 17bd0ed, I think. This was surprisingly complicated to fix.
