### ISSUE TITLE
warrior simulation inconsistencies

### ISSUE THREAD

**Issue by mitsy0** [simulationcraft/simc#2668]
When I mention scaling factors I mean(haste, crit, mult,mastery vers) using simcraft x64
I start with sim1.txt.  Looking at the scaling factors haste is rated at 12.50 over all other stats.  The dps simulation is 84481dps.  So I change enchants to increase dps based on the scaling factors and the findings are contradictions.
1. I change the neck enchant which was mastery with a scale factor of 6.78 to haste. I get the following:(sim2.txt) 85282 dps and haste still is on top of the scaling factors. with 7.72.
2. The problem I see is that if I change the enchant of the ring instead of the neck the results are not expected(sim3.txt). I get 86108dps and haste is the lowest on the scaling factors.
The results don't support the scaling factors 85282 vs 86159 only have a 25 haste difference yet is over 800dps difference.  And the jump from 84481 to 86159
 by changing 50 mastery to haste is also unsupported.
I tried changing the iterations the adding warrior_fixed_time=0 and others but the results had the same inconsistencies as this example.

[text_results.zip](https://github.com/simulationcraft/simc/files/68199/text_results.zip)

**Comment by scamille** [comment]
1. What are the number of iterations you used for your tests, and what are the error-margings given for the scale factors?

2. Can you please attach the simc_gui.simc file (found in your SimC folder, contains all the settings of your last simulation) here?

**Comment by mitsy0** [comment]
[simc_gui.zip](https://github.com/simulationcraft/simc/files/70550/simc_gui.zip)
I tried different iterations 10,000->50,000 same results.  The error from the files I attached are 0.28 0.29 0.28 0.28 0.28 0.28.  I attached the html results on the text_results.zip

**Comment by Collisionc** [comment]
You are very likely right at a haste breakpoint where it's significantly less valuable. There are 3-4 points where haste's value goes up quite a bit, and then dips afterwards due to wild strike's GCD that is non-hasted.

**Comment by Collisionc** [comment]
Example reforge plot of your character -- Your current gear is the baseline.
![Reforge Plot](http://collision.heroicstrike.org/2015-12-24_19-36-52.png)

As I mentioned, you're right at a haste breakpoint. There are many reasons behind this, but ultimately it comes down to 1 thing.  Wild strike's non-hasted gcd really fouls up the rotation since there are 0.1-0.3 second periods where you either don't do anything, or use wild strike and push back bloodthirst 0.1-0.3 seconds.

**Comment by mitsy0** [comment]
Thank you for your time.  The graph clears things up for me.
