### ISSUE TITLE
Can't create https connecton

### ISSUE THREAD

**Issue by wojing** [simulationcraft/simc#2669]
1.import my role from battle.net
2. click the login on the web page
3.then:
    Oops! An error occured loading https://www.battlenet.com.cn/login/zh/?ref=http://www.battlenet.com.cn/wow/zh/&app=com-wow
Network Error 99: Error creating SSL context ()

verision: 622-01 ,623-01
env: win7 64 sp1

**Comment by jdcranke07** [comment]
I'm having this exact same issue. I'm using Windows 10 and the last update worked, but this one won't. I have installed, uninstalled, and reinstalled both x86 and x64 versions.

**Comment by navv1234** [comment]
Not sure why this happens, but you could try installing OpenSSL (https://www.openssl.org/community/binaries.html). I believe our Windows releases no longer include the library on Windows. Remember to use the correct version (32 vs 64 bit) if you do.

**Comment by Collisionc** [comment]
I'll include them in the future, didn't think they would be needed for importing armories.
