### ISSUE TITLE
Hammer of Wrath never got boosted by 8% in patch 6.2.3. Only the tooltip was updated.

### ISSUE THREAD

**Issue by YasinUludag** [simulationcraft/simc#2670]
Here is a thread that explains the entire issue: http://eu.battle.net/wow/en/forum/topic/17289308934

It still does 240% damage and not 259.2%. Should be easy fix!

**Comment by YasinUludag** [comment]
Bumped official thread. Hopefully blizz will address this soon?

**Comment by navv1234** [comment]
I added a hotfix into the Paladin module in c215c66. Closing.
