### ISSUE TITLE
Issue running sim

### ISSUE THREAD

**Issue by Trekie7** [simulationcraft/simc#2671]
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.attack_power_multiplier=1
override.spell_power_multiplier=1
override.critical_strike=1
override.haste=1
override.multistrike=1
override.mastery=1
override.stamina=1
override.str_agi_int=1
override.versatility=1
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: http://us.battle.net/wow/en/

# Unable to determine Server and Character information!

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by mrdmnd** [comment]
From a later issue, it looks like you were successfully able to run the sim. Will close this issue.
