### ISSUE TITLE
How to Question:  Once I run a simulation, how do I determine any changes recommeded to my Gems and Enchants?

### ISSUE THREAD

**Issue by Trekie7** [simulationcraft/simc#2672]
I have successfully run one simulation and have looked at the results.  I can't determine where within the results I receive information that can provide recommendations to more optimal gemming and enchanting - can you provide some guidance or a link to a document that can help please?

**Comment by Frostedmages** [comment]
The sim doesn't give direct output like this. It simply gives DPS statistics based on your input, and some basic stats on different stats if you calculate scale factors (in a very simple nut shell). It's up to you to interpret the results when it comes to how (if) you change your enchanting and gems.

**Comment by mrdmnd** [comment]
As frostmages has said, the way to use the sim is to generate stat weights, then gem according to those stat weights. If you use the Pawn addon, the sim directly can generate Pawn scales from its computed stat weights, which should help out in-game.
