### ISSUE TITLE
Newest build doesn't start

### ISSUE THREAD

**Issue by fateswarm** [simulationcraft/simc#2677]
Win 10 64. Both versions 32, 64 exit without a warning. Seems like another QT issue.

**Comment by fateswarm** [comment]
Clarification, it doesn't start anything, not even a crash report window.

**Comment by scamille** [comment]
1. Are you starting SimulationCraft.exe? (simc.exe is a command-line only tool)
1. Please check your AntiVirus settings. The problem you describe is usually caused by an overzealous AntiVir program blocking SimulationCraft.exe. We do not sign our binaries, and false positives might block SimC.

**Comment by fateswarm** [comment]
The latest build works fine.

**Comment by mrdmnd** [comment]
Can we mark this as closed?

**Comment by mrdmnd** [comment]
Will close; if you still have issues, please feel free to re-open.
