### ISSUE TITLE
Stone of the Elements ICD now 40 seconds.

### ISSUE THREAD

**Issue by Valkyrst** [simulationcraft/simc#2681]
Hi,

So based on some recent testing, Stone of the Elements now has a 40 second Internal Cooldown instead of 115 seconds as previously. This should quite significantly affect simulations for classes.

I would definitely appreciate a look into this, since it's a huge boost to classes that benefit from it.

Thanks,
Valkyrst

**Comment by mrdmnd** [comment]
I'll take a look at this one.

**Comment by Valkyrst** [comment]
![screen shot 2016-01-29 at 12 58 27](https://cloud.githubusercontent.com/assets/16952693/12669816/80239094-c689-11e5-99ad-1d7ef291a89d.png)
![screen shot 2016-01-29 at 12 55 03](https://cloud.githubusercontent.com/assets/16952693/12669828/92b276b2-c689-11e5-8f72-fae03d12b891.png)

**Comment by mrdmnd** [comment]
https://github.com/simulationcraft/simc/pull/2682

I'd be a lot happier with this if there were a link to warcraft logs.

**Comment by kenthklui** [comment]
Looking at last night's logs, I am unable to find any proof of the ICD being reduced to 40 seconds.

https://www.warcraftlogs.com/reports/M9J18Qcxk4gDvnhV#type=auras&boss=-2&source=7&ability=60234&view=events&pins=2%24Off%24%23244F4B%24expression%24type%3D%22applyBuff%22

It is still 55 as far as I can tell.

**Comment by kenthklui** [comment]
Closing this due to lack of updates.
