### ISSUE TITLE
Sub Rogue profile requires glyph of energy

### ISSUE THREAD

**Issue by canofbutter** [simulationcraft/simc#2683]
Several pool_resource actions in the default sub rogue profile require Glyph of Energy.  If not using this glyph, the results include only a single Garrote and auto attacks.

**Comment by mrdmnd** [comment]
Pull requests welcome! Are there realistically any other glyphs you'd ever run over that?

**Comment by canofbutter** [comment]
Realistically? Probably not - it came up for me because the realm I'm on had no affordable copies of the glyph available at the time (it's not auto learned), and I wanted to see if I was doing ok with my new 100 sub rogue even without it.  I understand that this use case may be outside the intentions of simc, but found it interesting none-the-less that there's not really a way to compare the performance of the glyph vs other glyphs with the default profile.

**Comment by mrdmnd** [comment]
That's entirely fair, and yes, Simcraft should be modified to model this situation - we intend to support all configurations of talents and glyphs.

**Comment by navv1234** [comment]
Subtlety default APL now conditionally figures out the pooling thresholds. Closing.
