### ISSUE TITLE
Active DPS distribution graph missing in 623-02

### ISSUE THREAD

**Issue by You-Too** [simulationcraft/simc#2684]
I don't know if there's a reason to why it's missing but this graph was pretty useful in my opinion.
The info it contained can still be found in Statistics & data analysis / DPS but the graph was really a lot more user friendly to look at.

**Comment by navv1234** [comment]
We have not removed any charts from the HTML reports that I know of. Was this with google charts, or highcharts?

**Comment by You-Too** [comment]
Both. Here are some screenshots comparing 623-01 and 623-03. (says 623-02 on top though)
http://imgur.com/a/F8a05

**Comment by navv1234** [comment]
Bug found and fixed in a69f351. Thanks, closing.
