### ISSUE TITLE
Trying to get 3pc Nightslayer to work

### ISSUE THREAD

**Issue by Ghettomagic** [simulationcraft/simc#2686]
So, I was trying to test out something and it wouldn't work in the Simulator. It appears that tier bonuses aren't in the program past 14 or something. Is there a way I can manually input the 30 seconds CD reduction on vanish from the nightslayer 3 pc?

**Comment by kenthklui** [comment]
Generally speaking, tier bonuses from past expansions are not supported. You could probably do a manual spell data override though.

https://github.com/simulationcraft/simc/wiki/SpellData

**Comment by Ghettomagic** [comment]
I appreciate the reply, but the steps I should take to make vanishes cooldown 60 seconds is gibberish to me. Can't really gather what I should be typing in to override.
