### ISSUE TITLE
Attack Table

### ISSUE THREAD

**Issue by 1stNoob** [simulationcraft/simc#2687]
[https://github.com/simulationcraft/simc/issues/1807](1807)

> In MoP, block was moved to a separate roll.  Thus, for auto-attacks we use a two-roll
system:
#1: miss/dodge/parry/glancing/crit/hit
#2: block/no-block

I don't think this is still correct. In the past days i looked into that and made some calculations on it and compaire them to my logs.

Character:
http://eu.battle.net/wow/en/character/alleria/M%C3%ADshra/simple

Logs:
https://www.warcraftlogs.com/reports/BJ3gR8YQhT49q7pZ

The 2 roll system give me a 37,57 % block chance against a boss. I got the same value in a default sim vs fluffy pillow.

block from weapon enchant:
((Mastery / 100) * Uptime) / MasteryCoefficient = Mastery = Block
((500 / 100) * 42,19%) / 110) = 1,92%

block from trinket:
((Mastery / 100) * Uptime) / MasteryCoefficient = Mastery = Block
((1526 / 100) * 62,68%) / 110) = 8,69%

Both uptime values taken from a log.

Calculation for block:
((100 - (dodge + parry - 2 * BossAvoidanceCoefficient)) / 100) * (block + blockWeaponEnchant + blockTrinket - BossAvoidanceCoefficient) = block
((100 - (5% + 26,79% - 2 * 4,5%)) / 100) * (42,55% + 1,92% + 8,69% - 4,5%) = 37,57%

The 1 roll system calculation give me 53,16% block (42,55% + 1,92% + 8,69% - 4,5%).

In all the logs i linked above i get a block value vs melee arround 50%. So there is a big discrepancy between real data and the 2 roll calculation and a not so big discrepancy between real data and 1 roll calculation.

EDIT: Ignore all of that ... i misread the information provided by warcraftlogs. It gives me arround 50% block for the 2. roll not for 1. and 2. roll.

**Comment by mrdmnd** [comment]
Okay, are you okay with us closing the issue, then?

**Comment by 1stNoob** [comment]
Sure
