### ISSUE TITLE
Protection Paladin DPS too low

### ISSUE THREAD

**Issue by myth384** [simulationcraft/simc#2689]
I am simulating my fellow tank, who plays a Protection Paladin, to get TMI stat weights for him. I noticed his simulated DPS (24k) using all three action lists is a lot lower than he actually pulls (+30k).

I started comparing our DPS, because I had control issues as a Brewmaster with the gear I collected based on my TMI stat weights. The huge difference between my simulated DPS  (30k) and his DPS (24k) does not match the reality and does not explain my control issues I had.

**Comment by mrdmnd** [comment]
Hi! Thanks for reporting. Without access to the simc file that you are using, there's not much we can do to diagnose issues. Can you upload that file, and some real in game logs that demonstrate the discrepancy?

**Comment by myth384** [comment]
Heya, thanks for the fast reply!
Please find the attached zip archive with two simc files, one for my paladin friend and one for my monk. I don't have any in game logs at the moment. However, we both have around the same iLvl and are doing the same DPS (after I changed some enchants and gems). The simulated DPS of my monk is around the same as in game. So that should be a good reference. But if you really need more information from in game, please let me know.
Both action lists are lightly modified versions of the default action lists. I only removed actions that are anticipating on damage bursts coming from the boss, to get better TMI results as advised by Theck.
[simc.zip](https://github.com/simulationcraft/simc/files/137516/simc.zip)

**Comment by mrdmnd** [comment]
Tagging @mserrano because he's familiar with the Paladin code. It looks like this APL you're using for the paladin doesn't use the legendary ring or armor pots at all, even though the paladin in question has it equipped?

**Comment by mserrano** [comment]
Prot Paladin is unfortunately not very well-supported at the moment. The Prot APL hasn't been updated since before 6.1, I think.

**Comment by bitfluxhound** [comment]
Will be fixed in legion.
