### ISSUE TITLE
Automation talent indexes are inconsistent with those used by the battle.net talent calculator

### ISSUE THREAD

**Issue by nzall** [simulationcraft/simc#2690]
I'm not sure whether this can be considered a bug or not, but I just tried to do a talent automation for my MM hunter. I copied the talents over from the EU.Battle.Net talent calculator, but apparently, the Automation uses a 1-indexed system for determining talent positions, while the battle.net version uses a 0-indexed system. This is confusing and means that users can't just copy-paste their talents over from the battle.net calculator, but instead have to manually adjust every digit to compensate.

It would be easier for the user if the automation calculator was consistent with that of the Battle.net calculator. From what I can tell, this wouldn't even be a big change: when the talent number is read from the user, just add 1111111 to compensate for the 0-index. However, I do understand that this could be a breaking change for existing automation profiles.

**Comment by mrdmnd** [comment]
I 100 percent agree and was personally bitten by this when I started. Should be a relatively easy fix.

**Comment by scamille** [comment]
Automation is gone for now.
