### ISSUE TITLE
This Arcane Blast doesn't look normal on multiple targets 

### ISSUE THREAD

**Issue by Curnivore** [simulationcraft/simc#2692]
http://i.imgur.com/xNtq7g2.png

I run 8 targets and I saw this. That doesn't sound logical. Did it simultaneously run 8 arcane blasts at a time?

It was an almost default imported script. No raid/multiple character setup or anything fancy like that.

**Comment by fateswarm** [comment]
PS. I know the APL does not support that many targets optimally. I wonder how that kind of DPET can come about from a single target spell. Even if the APL is not optimal I would expect there would be mechanical limitations to prevent that sort of thing.

**Comment by scamille** [comment]
Can you attach the [simc_gui.simc](https://github.com/simulationcraft/simc/wiki/simc_gui.simc) from that simulation? Should make it much easier to replicate the problem.

**Comment by kenthklui** [comment]
The reason this happens is because Arcane Blast is only being casted on the pull, and never used again afterwards. Precombat actions have a execution time of zero, which means the DPET is a division by zero, giving an absurd number.

**Comment by Frostedmages** [comment]
Shall I consider this closed, or do we want to look into adding in support for correcting DPET values for spells cast during pre-combat?

**Comment by scamille** [comment]
@Collisionc do you have any plans to adjust this? I don't have time to try things out, but it might help not to call stats -> add_execute in action_t::execute for pre-combat actions. But that might screw something else up ;)

**Comment by Collisionc** [comment]
I'll check it out
