### ISSUE TITLE
Incorrect Unholy trinkets in default Sim profile

### ISSUE THREAD

**Issue by Deorigosa** [simulationcraft/simc#2693]
Please, adjust default Unholy trinkets to be Unending Hunger and either Vial of Convulsive Shadows for single target or Discordant Chorus for AoE. That won't be useful too much, but at least some people will stop using "BiS" trinkets and showing AMR or Noxxic for their arguments.

**Comment by mrdmnd** [comment]
Howdy. I had made that fix earlier, and it looks like someone else regenerated profiles from a bad state. I'll regenerate the profiles with the correct trinkets (UEH + VoCS) for ST.

**Comment by mrdmnd** [comment]
Fixed in https://github.com/simulationcraft/simc/pull/2694
