### ISSUE TITLE
Censure Damage

### ISSUE THREAD

**Issue by JamesJohns** [simulationcraft/simc#2696]
I'm just getting back into wow, and wanted to benchmark my dps.  I turned off all of the single actions and non-raid buffs, and removed my trinkets and cancled them from input, and started with melee on a Raid Dummy.  That worked great, and my numbers matched simcraft.  I then turned on Seal of truth, and simulated.  It said that Censure should be ticking for 1850, but it was only ticking for 1450.  The stats in the result section matched my stats on live, so there's not a buff that I managed to unclick.  Looking back through the forums it seems like there used to be a bug in how simc calculated censure.  Not sure if it's back or if this is unrelated.  I'm using version 623-02.
Thanks,
James

**Comment by mrdmnd** [comment]
Pinging @mserrano for all Ret Paladin related issues.

**Comment by Collisionc** [comment]
Closing as legion is coming.
