### ISSUE TITLE
Unholy DK won't sim

### ISSUE THREAD

**Issue by Matadorinicuo** [simulationcraft/simc#2702]
Please let me know if I'm doing something wrong or what. When i try to run a simulation on my DK in frost spec it works fine, but when I switch to unholy and try again I get this:

Player Depravado could not find spell data for action scourge_strike_shadow
Simulation has been canceled after 1 iterations! (thread=0)                     
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow
Player Depravado could not find spell data for action scourge_strike_shadow

**Comment by navv1234** [comment]
Did you sim a low level character? There might be some issue with that.

**Comment by Matadorinicuo** [comment]
Level 72, but I thought it odd that it worked just fine on frost spec

**Comment by navv1234** [comment]
Yeah, the problem is that the shadow damage portion of scourge strike is tagged as a min level of 80.

**Comment by Matadorinicuo** [comment]
Good to know, thanks! I changed level to 80 and it worked I'll just extrapolate from there.
