### ISSUE TITLE
SimCraft Linux command line not importing item upgrade stages

### ISSUE THREAD

**Issue by RossosHEX** [simulationcraft/simc#2703]
SimulationCraft 623-03
for World of Warcraft 6.2.3 Live (build level 20886)
Downloaded zip yesteday 2015-04-14 and built under Ubuntu 14.04 with Make while in engine/

I am using command line ./simc guild_st.simc 
where guild_st.simc is a file with names of my guildies in proper format ending with some options
```
iterations=1000
threads=7
optimal_raid=1
html=consideration_st.html
hosted_html=1
```
The SimCraft then proceeds and spamming me for each character with 
```
@BCP API: Unable to download player from 'http://eu.battle.net/api/wow/character/The-Maelstrom/Ronight?fields=talents,items,professions&locale=en_US'
```
(different servers and names for each individual char ofc)
then goes spends like 12-14 min running.
Produces the HTML file as requested but something is odd, the dps values are all lower than expected.

Upon closer investigation I've found errors in GEAR list importing.
So apparently the gear is correct, enchants are there, gems too, heroic warforged is ok, etc.
BUT! Item upgrades are all 0/2. (I am talking for when items are indeed upgraded 2/2 obviously)
Why is that? And how can I fix that? can I force for all item to be considered 2/2 upgrade with options in guild_st.simc  file?

Thank you in advance.

**Comment by RossosHEX** [comment]
also getting some compiling warnings

```
sc_main.cpp: In static member function ‘static void {anonymous}::sim_signal_handler_t::report(int)’:
sc_main.cpp:27:79: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
       (uint64_t) global_sim -> target -> resources.initial[ RESOURCE_HEALTH ] );
                                                                               ^
sc_main.cpp:27:79: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
```

**Comment by RossosHEX** [comment]
it would appear that http://www.simulationcraft.org/reports/Raid_T18H.html is also without item upgrades as well

**Comment by RossosHEX** [comment]
.simc_api is sorted out in my ~/ directory now
no more BCP API: errors

still no upgrade=2 though

**Comment by scamille** [comment]
Thanks for your report. Most devs are already working on legion, but I'm sure we can get this fixed.

@navv1234 Can you take a look?

**Comment by RossosHEX** [comment]
So! Long story short:
It is sort of on part my nubiness
the problem is caused because Linux compiler doesn't automatically links to OPENSSL
thus in order for SimulationCraft to be able to connect to https:// and JSON it needs to be compiled with extra option
```
make OPENSSL=1
```

AND ofcause BIG THANK YOU to @reia on IRC channel for providing me with the solution.
```
yes but we don't autodetect, sec
try a rebuild
make OPENSSL=1
if you have more cores
add -j <numberofcores>
also, in case you didnt know
if you want an optimized executable
compile with make OPENSSL=1 optimized
```

PS. It's not a bug, it's working as intended kind of thing xD

**Comment by lichtschlag** [comment]
I am experiencing the same error as @RossosHEX , but am not able to get it running by linking to openssl (Openssl links, but Battle.net fetch remains failing).

The issue at #2630 also references problems with the Battle.net Api.

**Comment by navv1234** [comment]
#2630 won't have a direct effect on this, it is more the fact that simc has not needed external item APIs for a very long time, so the few we use have not been maintained properly.

On OS X you do not need to do anything special (if you compile from command line), simc uses, and is automatically linked against SecureTransport framework.

**Comment by lichtschlag** [comment]
I'm really not familiar with the simcraft source or the battle.net api, so I'm not really feeling confident about this, but...

The URLs that the simc commandline queries, including the one mentioned by @RossosHEX above return a 403 forbidden for me in the browser, and also for parse_player(), line 747, sc_bcp_api.cpp. Some searching leads me to believe this is related to a switch in the APIs http://us.battle.net/en/forum/topic/19496980106. That indicates that my problem has nothing to do with SSL, right? But...

I only get the error if I compile from source (master), not if I use the simc from the Mac dmg file.

**Comment by RossosHEX** [comment]
My issue was Linux specific.
I was never getting '403 forbidden'. 
As for source code and API, I can just assure you that those are working fine to this day.

@SimulationCraft 623-03 for World of Warcraft 6.2.3 Live (build level 20886)

**Comment by navv1234** [comment]
@lichtschlag If you are getting 403, it probably means you don't have an API key? We do not include any kind of default API key in the source code, you will need to get one for yourself.

See https://github.com/simulationcraft/simc/wiki/BattleArmoryAPI

**Comment by lichtschlag** [comment]
Fantastic, that was indeed the issue.
I feel I should have figured that one out myself. It's not mentioned at the build instructions (https://code.google.com/archive/p/simulationcraft/wikis/HowToBuild.wiki and https://github.com/simulationcraft/simc/wiki/HowToBuild) and the command line output does not provide a hint to the error. May I suggest to give a hint towards this problem when 403 is returned? Like this:

> if ( profile.HasParseError() )
> {
>     sim -> errorf( "BCP API: Unable to download player from '%s'\n", player.cleanurl.c_str() );
>     if (!sim->apikey) { sim -> errorf("If you built this from source, remember to add your own api key.") }
>     return nullptr;
> }

**Comment by Collisionc** [comment]
I'll add in that error, it's a good idea.

**Comment by Collisionc** [comment]
Added in feedback to help out in the future.
