### ISSUE TITLE
I want to report two bugs

### ISSUE THREAD

**Issue by CJLlwz** [simulationcraft/simc#2705]
These two bugs are all about character import.

Bug 1. After importing a character, the upgrade level of his equipment is not imported, whitch caused next simulations are based on wrong data and lower than the real value. Meanwhile, where the code "upgrade=2" should be is replaced by another strange code like "initial_cd=5.00684e-308" or other numbers.
Bug 2. When I want to import my newer character to be compared with my older one, after having changed my equipment on WOW and close the game to make sure the information on community has been updated, the code of the lastest import by my character is the same as older one, not the newer one. Only I could import the right newer code after restart the SIMC program each time.

I'm a Chinese WOWer who are very interested in simulating the DPS of my character by SIMC. These two bugs realy cause bad effects.

**Comment by aggixx** [comment]
> Bug 1. After importing a character, the upgrade level of his equipment is not imported, whitch caused next simulations are based on wrong data and lower than the real value. Meanwhile, where the code "upgrade=2" should be is replaced by another strange code like "initial_cd=5.00684e-308" or other numbers.

This sounds like something I fixed a while back.

> Bug 2. When I want to import my newer character to be compared with my older one, after having changed my equipment on WOW and close the game to make sure the information on community has been updated, the code of the lastest import by my character is the same as older one, not the newer one. Only I could import the right newer code after restart the SIMC program each time.

May have just been an armory issue.

I'm going to close this ticket due to the age and since I have no way to know if they still are occurring, but if they are please reopen this ticket or make a new ticket. Thanks!

**Comment by clowerweb** [comment]
I'm getting the 0/2 upgrade level bug. Built using the command line on Ubuntu 14.04 x64 using `make optimized` (I also tried without the `optimized` parameter).  All items in the character's report say "Upgrade Level: 0/2", even though they are all 2/2 on the Armory. I am using my own API key, and everything else is correct (gems, enchants, talents).

**Comment by navv1234** [comment]
Can you give your region/realm/char so we can take a look?

**Comment by clowerweb** [comment]
us/lightbringer/scathe. Maybe I should note that I'm also using the command line version with the following profile.simc

```
armory=us,lightbringer,Scathe
iterations=1000
report_details=0
json=us-lightbringer-scathe.json
```
