### ISSUE TITLE
simcraft for wotlk 3.3.5a

### ISSUE THREAD

**Issue by shaharazu** [simulationcraft/simc#2706]
can any one give me a link to simcraft 3.3.5a pls?

**Comment by Collisionc** [comment]
http://simc.heroicstrike.org/

I rehosted the old ones for you.

http://simc.heroicstrike.org/Wrath_Downloads/simc-335-1-win32.zip

should be the one you are looking for.

**Comment by ERPedersen** [comment]
Hi, I just stumbled over this issue. Is it possible to get a link to 3.4.0?

**Comment by vituscze** [comment]
No, that's not possible. 3.4.0 didn't exist back when WotLK simc was still being maintained.
