### ISSUE TITLE
Low level frost mage crash

### ISSUE THREAD

**Issue by a3b2c1** [simulationcraft/simc#2709]
Hello
I was playing around with a low level frost mage in simcraft and it kept crashing on me regardless of the input. I found it'd run successfully if the character level was at 81 or above which is odd since I can't find any difference between those two levels in terms of spells or abilities. The only thing I can think of is that there's something wrong with the mastery effect in there or something perhaps.
This is in the live version btw, and I do understand if you don't care at this point with legion around the corner and everything, just thought i'd let you know just in case.
cheers

**Comment by aggixx** [comment]
Guessing this is a null pointer exception on some effect that the module writer mistakenly assumed would always be there. If you run into these in legion though please do make another ticket, thanks!

**Comment by FLeXyo** [comment]
This is still an issue in the current build. If you try to simulate a mage lower than level 78.
