### ISSUE TITLE
[DW Frost DK] Tier 13 2 Piece Bonus Crash

### ISSUE THREAD

**Issue by LateralusGT** [simulationcraft/simc#2712]
When I try to run this, it always crashes the program. I think I have pinpoint it to the tier 13 2 piece set. It does not give me an error code or anything like that, it just says windows has to close the program. Any ideas?

**Comment by Collisionc** [comment]
Old tier bonuses will be disabled in Legion, so I'm marking this as something we will not fix since legion is almost out.
