### ISSUE TITLE
Demon Hunter - APL suggestion

### ISSUE THREAD

**Issue by Koxomathical** [simulationcraft/simc#2716]
I know it's early for DH stuff, but I was playing a bit with the Havoc profile and I noticed that everything is basically added to a single paragraph.

My question is if it's possible to make multiple paragraphs (2 at least) to make it easier to write/read APL for havoc basic profile? Rogues have multiple for Finisher prio, builder prio - I think it would be a nice thing to have something like that for DH.

Paragraph Nr1 would be "General APL" and maybe there could be a secondary paragraph for "Metamorphosis APL" so you/we could remove the |buff.metamorphosis.up/down etc.. parts.

**Comment by mrdmnd** [comment]
Pull requests welcome! You can always fork and submit a cleanup PR =) 

Yes, that seems like a reasonable way to organize an APL.

**Comment by aggixx** [comment]
It is good feedback and I can think about how I want to approach it.

Closing for now. If you want to give it a shot yourself feel free to make a pull request or new ticket with a modified APL and I can add it.
