### ISSUE TITLE
JSON Reports

### ISSUE THREAD

**Issue by aethys256** [simulationcraft/simc#2719]
Hello,
I'm using json reports to parse a lot of sims to a spreadsheet.

In the "dps" section of a character, "mean" is the same number as what is shown as "median" in the html report.
If I do the mean of the "min" and "max" value I found another thing, so I assume that "mean" is in fact "median".

Also for the "mean_variance", I can retrieve the number by doing from the html report "median*(variance_pct/2)", so I assume that the "mean_variance" is (in absolute value) in fact the positive (or negative as it is centered) part of the variance shown in the html reports, right ?

PS : If I'm not wrong, Variance is based on the mean and not the median, as it seems that only the median is reported (and tagged as mean), what is used by simc to compute the mean_variance ?

PS2 : From HTML Report : Median = 212088.9 and Variance = 0.046 (4.6%), below the JSON report :
         "dps": {
                        "name": "Subtlety T19H Damage Per Second",
                        "sum": 4685043175.863656,
                        "count": 22090,
                        "mean": 212088.87170048239,
                        "min": 180033.38859007284,
                        "max": 256245.3764421962,
                        "variance": 96213052.98410672,
                        "std_dev": 9808.825260147452,
                        "mean_variance": 4355.502624902975,
                        "mean_std_dev": 65.9962318992757
                    },

Thank you in advance, and @navv1234 told me to tag you @scamille :)

**Comment by scamille** [comment]
Where do you see the median in the html report? I can find only the mean reported there as well.

mean_variance is the variance of the distribution divided by distribution size. See central limit theorem for more details.

we use the standard deviation of the mean distribution to give a confidence interval for the mean dps distribution, basically what you see as "error" in the html reports is +-1.96*mean_std_dev.

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/master/engine/util/sample_data.hpp for the calculations,
https://github.com/simulationcraft/simc/blob/master/engine/report/sc_report_json.cpp#L44 for the JSON reporting

https://github.com/simulationcraft/simc/wiki/FightingVariance has a bit about central limit theorem/statistics as well.

**Comment by aethys256** [comment]
> Where do you see the median in the html report? I can find only the mean reported there as well.

In any HTML report, if you mouseover a bar in the bar chart, you will see the min/max/etc..
And the mean seems to be reported as the median. Wich is what confuses me.

Thanks for the links, will look into.

**Comment by scamille** [comment]
@navv1234 that seems to be a highcharts problem then.
https://github.com/simulationcraft/simc/blob/master/engine/report/sc_chart.cpp#L2933 uses mean() from the sample data, but
https://github.com/simulationcraft/simc/blob/master/engine/report/sc_chart.cpp#L3181
sells it as "median".

**Comment by navv1234** [comment]
That's what the boxplot value variable is (median). There is no mean there to assign to.

EDIT: Do we have an actual median method in sample data? :)

**Comment by scamille** [comment]
percentile(0.5)

**Comment by navv1234** [comment]
K guess we need to change that for highcharts actually. The JSON report in general could use some pretty heavy cleanup, I'll try to find time from somewhere before legion releases.

**Comment by aethys256** [comment]
This can be closed, we have now JSON2 (as a "beta"), and the median/mean thing has been "clarified".
