### ISSUE TITLE
[Legion-Dev] Assertion failed! on using Blood Boil

### ISSUE THREAD

**Issue by jokre33** [simulationcraft/simc#2721]
Using up the last charge of Blood Boil throws 0 to ~100 "Assertion failed!" errors.

```
File: ..\engine\sim\sc_cooldown.cpp
Line: 343

Expression: current_charge > 0
```

The APL i'm currently observing the behavior with is [this one](http://pastebin.com/ZbFX3Vzu).

Using Blood Boil as the only Spell in the APL doesn't seem to trigger this error, but using it with 1 charge (for example `actions+=/blood_boil` as last action) in a more complex one has the behavior described above.

Using `actions+=/blood_boil,if=cooldown.blood_boil.charges>=1` to make sure that a charge is available doesn't change the behavior.

**Comment by navv1234** [comment]
Fixed in d836f0b.

EDIT: Also note that Blood dk sim is very much in flux still, I haven't put all the talents in yet, and really done no work on the "tanking" side of things.
