### ISSUE TITLE
Legion Beta - Guardian APL

### ISSUE THREAD

**Issue by Driber** [simulationcraft/simc#2724]
actions+=/moonfire,if=buff.galactic_guardian.up|=!ticking
actions+=/mangle
actions+=/thrash_bear
actions+=/swipe_bear

should be default prio

**Comment by aggixx** [comment]
If you have a complete APL I can add it. I know the current one is pretty bad/dated I just haven't gotten around to updating it.

**Comment by Driber** [comment]
I will be working on it soonish™.

**Comment by Driber** [comment]
```
actions=auto_attack
actions+=/skull_bash
actions+=/berserking
actions+=/rage_of_the_sleeper
actions+=/use_item,slot=trinket2
actions+=/barkskin
actions+=/incarnation
actions+=/bristling_fur,if=buff.ironfur.remains<2&rage<40
actions+=/ironfur,if=buff.ironfur.down|rage.deficit<25
actions+=/frenzied_regeneration,if=!ticking&incoming_damage_6s%health.max>0.25+(2-charges_fractional)*0.15
actions+=/pulverize,cycle_targets=1,if=buff.pulverize.remains<gcd*3
#^actions+=/thrash_bear,if=remains<gcd*2|(dot.thrash_bear.stack<3&buff.incarnation.up)
actions+=/moonfire,if=!ticking
actions+=/lunar_beam,if=buff.rage_of_the_sleeper.up
actions+=/thrash_bear,if=buff.rage_of_the_sleeper.up&active_enemies>=2
actions+=/swipe_bear,if=buff.rage_of_the_sleeper.up&active_enemies>=2
actions+=/moonfire,if=buff.galactic_guardian.up
actions+=/mangle
actions+=/thrash_bear,if=talent.pulverize.enabled&buff.pulverize.remains<3.6
actions+=/thrash_bear
actions+=/moonfire,cycle_targets=1,if=!ticking&!talent.galactic_guardian.enabled
actions+=/swipe_bear
```

I use the APL defensiv-cooldown-part as seen in the current build, since I have no idea how to improve it. The rest should be alot better, but maybe still far from perfect.
The Thrash_Bear line marked with "#^" need to have an OR `dot.thrash_bear.stack<5&buff.incarnation.up`, when  Elize's Everlasting Encasement is equipt, but I lack the skill to code it.

**Comment by Driber** [comment]
Also the Thrash line should be:
actions+=/thrash_bear,if=remains<gcd*2|(dot.thrash_bear.stack<3&buff.incarnation.up)

But once posted it disapears :S

**Comment by scamille** [comment]
Try code tags for APL, documentated at https://guides.github.com/features/mastering-markdown/

**Comment by Driber** [comment]
Done.
Many Thanks!
