### ISSUE TITLE
Ret Paladin rotation : too many Avenging Wraths?

### ISSUE THREAD

**Issue by Jeff75** [simulationcraft/simc#2726]
In the Paladin_Retribution_T18N rotation, it looks like Avenging Wrath is being cast every 30 seconds for the first 2 minutes of the fight:

0:06.073    avenging_wrath  Paladin_Retribution_T18N
0:36.073    avenging_wrath  Paladin_Retribution_T18N
1:09.048    avenging_wrath  Paladin_Retribution_T18N
2:11.797    avenging_wrath  Paladin_Retribution_T18N

And then it moves to the actual 2 minute cooldown:

4:14.438    avenging_wrath  Paladin_Retribution_T18N
6:20.317    avenging_wrath  Paladin_Retribution_T18N

Is this a bug in SimC, or is there a way to reduce the cooldown of Avenging Wrath that I'm not aware of?  This would greatly affect the DPS of a ret paladin in simulations, because AW gives you access to Hammer of Wrath every other spell and increases your damage.

**Comment by skudnfroodie** [comment]
The 2pT18 gives you 3 charges of AW
