### ISSUE TITLE
Legion - Feral Clearcasting Rate and 50% Bonus Haste

### ISSUE THREAD

**Issue by ShmooDude** [simulationcraft/simc#2730]
The value for the clearcasting proc rate is in line 1545 of sc_druid.cpp

EDIT: Guess I should also say the new value is 5.25 (from 3.5)

Not sure how to do the bonus haste.

EDIT: Specifically bonus haste from gear.

**Comment by aggixx** [comment]
Clearcasting rate is incorporated automatically via hotfix data, haste multiplier was implemented by 4681c1828836f11dd1ae18c34471ad319757402b.
