### ISSUE TITLE
Demo warlock sim

### ISSUE THREAD

**Issue by EMTGuy777** [simulationcraft/simc#2733]
I just simmed my 743 demo warlock using Beotorch.com. My warlock is Malefaction-Proudmoore. It simmed that I was going to do 6.485 dps.

**Comment by Twintop** [comment]
I think @Undertoe and @tjc12821 are still working on the Demo Warlock APL right now since it is empty in the Warlock module.

**Comment by Undertoe** [comment]
This is not a problem on live simcraft.  This is a problem with Beotorch.com not being updated yet.

**Comment by Twintop** [comment]
Demo's APL function was empty at the time of this bug report, I checked. Site is updated now.
