### ISSUE TITLE
[Warrior] - Frothing Berserker buff persists as long as you remain at 100 rage

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2734]
Behavior: The Frothing Berserker buff from the level 75 talent is continually re-triggered while a player remains at 100 rage.

Expected behavior: The buff should only last 6 seconds after reaching 100 rage and remaining capped. You must go below 100 rage by spending any and reach 100 again to re-trigger the buff.

Steps to recreate:
Sim a warrior profile with the Frothing Berserker talent enabled. Add nothing but auto-attack to the action list. Once the buff is activated after reaching 100 rage the first time, it never fades.

**Comment by Collisionc** [comment]
Thanks, I'll fix it.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/8693d9f0fa12625586ee99d6ecd0463a8ebf4d2d

fixed
