### ISSUE TITLE
[Warrior] - Raging Blow damage lower ingame than in simc.

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2735]
This may just be a very recent hotfix that's yet to be announced, but Raging Blow damage as calculated by SimCraft is too high. In-game tooltips are accurate and reflect the 136% weapon damage the attack is actually doing, while SimCraft's spell data dump is using 146% weapon damage for its value.

**Comment by Collisionc** [comment]
We pull spelldata directly from the client when hotfixes are pushed now, and before the previous hotfix it was dealing 153% weapon damage, hotfix nerfed 5% down to 146%.

**Comment by Collisionc** [comment]
Imported my character using simc addon to double-check, and the damage from raging blow in game is actually a little higher than simc. There's probably a damage multiplier missing somewhere, but I'll investigate.

**Comment by amulder87** [comment]
I think you may be testing on the raid dummy in your garrison, which has less armor than it ought to for some reason. It takes about 9.54% more damage which would make 136% WD look like ~148.97% WD and seem slightly higher in-game than it ought if you're comparing to 146%. The org dummy over in the valley of honor is accurate.

With some items removed to avoid annoying procs, I have 6052 AP and am dual wielding "large club"s, which have a 3-5 damage range to keep numbers consistent and simple. With the inner rage talent, my RB tooltip claims it'll average 29,121 damage. (6052/3.5*3.3 + 4)*1.36(136% wep dmg)*2.5(inner rage)*1.5(dual wielding) = 29121.8. If I RB the raid level dummy in orgrimmar, which should deal 59.404% dmg after armor, I get a damage of 11533 MH and 5767 OH. 29121.8*.59404 = 17299.6, and 11533 + 5767 = 17300, so it all checks out. In comparison, SimCraft gives a damage of 12382 MH and 6191 OH, which is perfectly correct for 146% WD, but doesn't match live numbers for some reason.

Doing the same tests without the inner rage talent and factoring out my enrage damage buff gives me the same result of 136% weapon damage, to rule out that multiplier being the cause. As a sanity check, I compared damage on BT as well and got a 7361 hit with those same stats, which is exactly what you'd expect at 217% WD. SimCraft concurs and shows an expected 7361 BT hit, which isolates it down to just being RB base damage that's off as far as I can tell.

**Comment by Collisionc** [comment]
Stupid garrison dummy. I will confirm tomorrow and fix it. Thanks!

**Comment by Collisionc** [comment]
http://collision.heroicstrike.org/explorer_2016-07-22_22-28-27.png

It's freaking warpaint. They must have accidentally added raging blow to the spell,. so it's reducing effect#2 of raging blow by 10, aka reducing weapon damage by 10%

**Comment by amulder87** [comment]
Rofl, that's gotta be one of the most ridiculous bugs I've ever heard of. I never expected that to be doing it. So just untalenting warpaint makes it do normal damage?

I posted this to Bug Report forums: http://us.battle.net/wow/en/forum/topic/20747695186#1. If you have any sway with any Blizzard developers, feel free to suggest they fix it too :)

**Comment by Collisionc** [comment]
Yeah, I thought something was odd because one of my other friends was like "nah, raging blow damage is fine." but he wasn't currently using that talent. I did a quick lookup of the spell and realized what was going on.

**Comment by amulder87** [comment]
This isn't a big deal, but I'm not seeing RB damage change in Simcraft when choosing Warpaint, even though spell data is still showing RB is affected by Warpaint's effect.

**Comment by Collisionc** [comment]
I used the wrong talent, warbringer instead of war paint.. stupid tab-completion. Doesn't matter, it was fixed in game today. 

https://github.com/simulationcraft/simc/commit/063bddbb83251b5f74f1319c55b704864fef7c0a

**Comment by amulder87** [comment]
Awesome, thanks! Glad to see that one didn't hang around for a while.
