### ISSUE TITLE
Warlock - Demonology

### ISSUE THREAD

**Issue by SaberTJ** [simulationcraft/simc#2736]
Talent choices for demonlogy has 2 issues -

Choices you pick don't save for simulation.

Talent rows don't match live.  (for ex - Grimoires aren't in same row.)

**Comment by navv1234** [comment]
If you are talking about our current official release, that is for World of Warcraft 6.2.3. We have not released an official release for 7.0.3 yet.

**Comment by aggixx** [comment]
Hi, you can find 7.0.3 builds at the bottom of the page here: http://downloads.simulationcraft.org/ or compile them yourself from source. If you're still having this problem please reopen the issue.
