### ISSUE TITLE
Document about operator priorities

### ISSUE THREAD

**Issue by AeanSR** [simulationcraft/simc#2740]
https://github.com/simulationcraft/simc/wiki/ActionLists#complete-list-of-operators

The wiki page lists `&` and `|` as the same priority, while logical-AND operator is lower than logical-OR. It could be tested out by a single line APL `actions=bloodthirst,if=1|0&0`, the simulator will evaluate as `1|(0&0)` then cast bloodthirst.

This is super misleading since I am doing [APL translation](https://github.com/AeanSR/irecore2/blob/master/libic/apltr.cpp#L1370) to keep the behavior consistent between simc and my simulator.

**Comment by navv1234** [comment]
Looks like we didn't update the documentation when we made OR be lower in precedence than AND. Fixed it now.
