### ISSUE TITLE
[Warrior] - Rampage GCD and haste

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2742]
It looks like current SimCraft is set to fix Rampage's GCD at 1.5s and not let haste affect it, but it works a bit differently on live now(no idea when this behavior began). Haste modifies it as if it had a base GCD of 2s, but only kicks in if it would reduce its GCD below 1.5s. That is, you get a GCD of MIN(1.5, 2.0/(1+Haste%)).

For a bit of proof, from my cast events in this log: https://www.warcraftlogs.com/reports/HDZQF8rfb9AXtYz3#type=casts&source=10&view=events&start=992756&end=1006124

00:00:24.096    Rallik casts Rampage on Archimonde
00:00:24.912    Rallik casts Bloodthirst on Archimonde

There's only a 0.816s gap between Rampage and BT there. In the gear I'm wearing I have 45.35% haste with full stacks of Berserker's Fury. I had full stacks of Berserker's Fury, Bloodlust, and War Machine active, bringing my total haste modifier to: 1.4535*1.3*1.3 = 2.456. That gives a rampage GCD of 2/2.456 = 0.814s. Testing on a dummy without enough haste to bring the value below 1.5s (anything less than 33.33%) shows the GCD remaining fixed at 1.5s.

**Comment by Collisionc** [comment]
Good catch. That has changed since I initially implemented it.
