### ISSUE TITLE
Spec can't be chosen from the UI options when importing

### ISSUE THREAD

**Issue by epigramx** [simulationcraft/simc#2747]
I won't be surprised if this is in a TODO list already but I couldn't find it with a quick search. The game currently allows all specs, there is no 1 active and 1 inactive, so the options could have all specs to choose from because the armory appears to show the talents currently. I guess the ideal could be Active + all the specs explictly on the "Armory Spec" dropdown list.

**Comment by Collisionc** [comment]
I believe Navv is hacking something together that may allow this.

**Comment by navv1234** [comment]
UNlikely this will actually happen. The problem is that we can easily let you choose the specialization (and the corresponding talent setup) ,but your artifact will still be of wrong type.

**Comment by Collisionc** [comment]
Oh, yeah... I forgot about the artifact thing.
