### ISSUE TITLE
[Hunter] Barrage's Auto Shot delay calculation is off

### ISSUE THREAD

**Issue by pottm** [simulationcraft/simc#2748]
Expected:
Auto Shot to release 500 ms after Barrage cast ends. (Auto Shot has a 500 ms "cast time")

Observed:
Casting Barrage simply adds 3000 ms to the Auto Shot timer.

Important lines from debug log:
63.202      MM performs auto_shot (94)
63.202      MM schedules execute for auto_shot (106)
63.202      New Action Execute Event: MM auto_shot 2.7 (target=Fluffy_Pillow, marker=0)
63.202      Add Event: Action-Execute time=65.9270 rs-time=0.0000 id=855

63.921      MM schedules execute for barrage (64)
63.921      New DoT End Event: MM barrage 2.715
63.921      Add Event: DoT End time=66.6360 rs-time=0.0000 id=861
63.921      Rescheduling event Action-Execute (855) from 65.93 to 68.93

68.927      MM performs auto_shot (39)

In this example, I would expect the second Auto Shot to release at 66.636 + .5 = 67.136

**Comment by Kennyloggins** [comment]
Indeed, you are correct. I just pushed the fix ( b1ccfa7 ). It appears to be working as it should now.

93.862 Hunter_MM_Legion performs auto_shot (65)
96.040 Hunter_MM_Legion performs barrage (105)
99.401 Hunter_MM_Legion performs auto_shot (47)
