### ISSUE TITLE
Can't pool_resource in secondary action lists unless you know the ability or talent

### ISSUE THREAD

**Issue by ShmooDude** [simulationcraft/simc#2750]
I was trying to put Elune's Guidance in an action list but if you're not talented into it, it throws the following error:
`anonymous-namespace'::pool_resource_t::reset: can't find next action.

`actions.action_list=pool_resource,wait=0.1,for_next=1,extra_amount=50
actions.action_list+=/elunes_guidance,if=combo_points=0`

It works fine if you put those lines in the main action list:
`actions+=/pool_resource,wait=0.1,for_next=1,extra_amount=50
actions+=/elunes_guidance,if=combo_points=0`

**Comment by Collisionc** [comment]
Looks like this has been fixed already, as I am unable to reproduce it. Please let me know if you still need help.
