### ISSUE TITLE
Balance haste scaling/plot bug

### ISSUE THREAD

**Issue by Gebuz** [simulationcraft/simc#2751]
Using the default T19 balance profile, but changing the talents to:
talents=3000333
and adding some haste (since the default profile has 0):
gear_haste_rating=4000
drops the haste scale factor to below 1 when it would usually be in the 4-7 range. It seems to only occur when using all four of those talents, but I could be wrong.
Plotting the stats also shows that there is something wrong. Losing haste is a significant bigger loss than any other stat, while gaining haste is actually a dps loss most of the time. 
Here is a screenshot of the plots: http://i.imgur.com/uS3SNzk.png

Also, Force of Nature is not working, but I assume you're already aware of that since it is not in the APL.

**Comment by Gebuz** [comment]
It seems to just be Stellar Flare that is causing the issue.

**Comment by Collisionc** [comment]
This appears to be fixed, as I just ran it and haste turned up like this:

http://collision.heroicstrike.org/SimulationCraft_2016-08-29_23-50-46.png

That's a reasonable haste chart for a caster.
