### ISSUE TITLE
conditional with RP/rune (Death Knight)

### ISSUE THREAD

**Issue by mike-o-gh** [simulationcraft/simc#2752]
I'm working on implementing a blood DK APL and am tearing out my hair currently - hopefully someone can help.  I narrowed down my APL to just the following basic list to test my understanding of how things work:
actions+=/death_strike,if=runic_power>105
actions+=/heart_strike
(Heart strike generates runic power and death strike spends it).  My issue is that death strike will sometimes obey the conditional rule and sometimes not.  I see similar issues with conditionals on number of runes.  This seems so basic, I don't know what I'm missing.

**Comment by navv1234** [comment]
Testing that out, not seeing any place where death_strike would be executed if runic power was below 105 when I run a blood dk test profile. Would need a full profile to see what's going on here.

**Comment by mike-o-gh** [comment]
Thank you for checking it out.  Profile that I am simulating:

###
deathknight="Gilbat_Active"
origin="https://us.api.battle.net/wow/character/malganis/Gilbat/advanced"
thumbnail="http://us.battle.net/static-render/us/internal-record-3684/104/117515880-avatar.jpg"
level=100
race=orc
role=tank
position=front
professions=mining=700/herbalism=313
talents=http://us.battle.net/wow/en/tool/talent-calculator#da!1001020
spec=blood

actions=auto_attack
actions+=/blood_boil,target_if=!dot.blood_plague.ticking
actions+=/death_strike,if=runic_power>105
actions+=/heart_strike

main_hand=hellrender,id=124360,bonus_id=566,upgrade=2,enchant=rune_of_the_fallen_crusader
###

I'm getting a feeling that there's something wrong with my install of simc; I don't really have any other ideas since you say that it works OK on your end.

**Comment by navv1234** [comment]
Nope, nothing with that either. I essentially changed the code to forcefully crash the simulator if it ever used death strike below or equal to 105 runic power, and the sim does not crash.

How do you figure that the conditional is sometimes obeyed and sometimes not?

**Comment by mike-o-gh** [comment]
I run a sim with iteration = 1 and look through the Sample Sequence Table in the Action Priority List section.  In this one, the first 2 death strikes are OK, but the 3rd occurs with only 70 rp.
![image](https://cloud.githubusercontent.com/assets/3255794/17645186/019f9924-616c-11e6-87c5-5685e4204f4c.png)

**Comment by navv1234** [comment]
Are you using gui? I cant really replicate this with any build i can get my hands on.

EDIT: Tried with the latest windows build on our download site, and that seems to be ok too.

**Comment by mike-o-gh** [comment]
I just ran the same profile via the command line (which I forgot I could do until your last comment), and everything seems to work OK.  What I was doing before was (on Windows) starting the GUI via simulationcraft.exe and then going through the process of importing from the armory, setting up the profile, etc.  I don't know why that wasn't working, but I'm fine with running via command line for now.

I'd like to test out a few more things later today before closing this issue, but it's looking good.

**Comment by navv1234** [comment]
You should have a simc_gui.simc file somewhere on windows when you use the gui (in the same directory as the simulationcraft.exe perhaps). That file is the "full simulation setup" for the gui, that is being run. Can you post it if you can get the gui to do weird behavior with the conditionals?

**Comment by mike-o-gh** [comment]
Sure.  It is still misbehaving via GUI:

### Begin GUI options

item_db_source=legionhead/local/bcpapi/wowhead
target_error=0
iterations=1
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.9
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1

### End GUI options

### Begin simulateText

deathknight="Gilbat_Active"
origin="https://us.api.battle.net/wow/character/malganis/Gilbat/advanced"
thumbnail="http://us.battle.net/static-render/us/internal-record-3684/104/117515880-avatar.jpg"
level=100
race=orc
role=tank
position=front
professions=mining=700/herbalism=313
talents=http://us.battle.net/wow/en/tool/talent-calculator#da!1001020
spec=blood

actions=auto_attack
actions+=/blood_boil,target_if=!dot.blood_plague.ticking
actions+=/death_strike,if=runic_power>105
actions+=/heart_strike

main_hand=hellrender,id=124360,bonus_id=566,upgrade=2,enchant=rune_of_the_fallen_crusader

### End simulateText

### Begin overrides

# User-specified persistent global and player parameters will be set here.

### End overrides

### Begin final options

### End final options

### END

**Comment by mco26cornelledu** [comment]
`### Begin GUI options ###
item_db_source=legionhead/local/bcpapi/wowhead
target_error=0
iterations=1
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.9
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
deathknight="Gilbat_Active"
origin="https://us.api.battle.net/wow/character/malganis/Gilbat/advanced"
thumbnail="http://us.battle.net/static-render/us/internal-record-3684/104/117515880-avatar.jpg"
level=100
race=orc
role=tank
position=front
professions=mining=700/herbalism=313
talents=http://us.battle.net/wow/en/tool/talent-calculator#da!1001020
spec=blood

actions=auto_attack
actions+=/blood_boil,target_if=!dot.blood_plague.ticking
actions+=/death_strike,if=runic_power>105
actions+=/heart_strike

main_hand=hellrender,id=124360,bonus_id=566,upgrade=2,enchant=rune_of_the_fallen_crusader

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
`

**Comment by navv1234** [comment]
`default_skill=0.9` will generate false positives.

**Comment by mike-o-gh** [comment]
Ugh, OK thank you for your help in tracking this down.  I feel like an idiot now, but at least know what was going on...
