### ISSUE TITLE
Gunpowder Charges (Consumable Item) not implemented.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#2754]
http://www.wowhead.com/item=133775/gunpowder-charges

This item does ridiculous damage on a short cooldown, and is not on the GCD. It is probably worth implementing, though it may be fixed/nerfed by Blizzard.

**Comment by amulder87** [comment]
That's the quest item. The crafted consumable is: http://www.wowhead.com/item=132510/gunpowder-charge

**Comment by Collisionc** [comment]
This recently was changed to be on the potion cd, so this is no longer useful as while potions are crappy, you can at least use them twice.
