### ISSUE TITLE
Unable to extract player talent specialization

### ISSUE THREAD

**Issue by JoutKazegawa** [simulationcraft/simc#2758]
That's what it said. Everytime I try to import a character.

 **Unable to generate profile: "the url to the character armory"**

Then

**BCP API: Unable to extract player talent specialization from "url of the character armory"**

And it is with every character I try to simulate.

This happens trying to go with bnet or by simple pasting the url of the character on the bar.

Any help?

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/issues/2757

Try the 2nd comment.

**Comment by JoutKazegawa** [comment]
Already did. =(

**Comment by Collisionc** [comment]
Can you link me the armory you are trying to import? What version of simc ?

**Comment by JoutKazegawa** [comment]
Both

http://us.battle.net/wow/en/character/zuljin/Vymissa/advanced

and

http://us.battle.net/wow/pt/character/zuljin/Vymage/advanced

**Comment by Collisionc** [comment]
What version of simulationcraft?

**Comment by JoutKazegawa** [comment]
The last one of the site.

**Comment by Collisionc** [comment]
Does it say 703-01 WebEngine at the top of the window?

**Comment by JoutKazegawa** [comment]
Says Simulcraft 623-02 Webkit

**Comment by Collisionc** [comment]
http://downloads.simulationcraft.org/SimcSetup-703-01-Win64.exe

That will work. 623-02 will not work with the changes made in legion.

**Comment by JoutKazegawa** [comment]
Oh, ty <3
