### ISSUE TITLE
generate_profiles.sh not correctly counting artifact points

### ISSUE THREAD

**Issue by skasch** [simulationcraft/simc#2759]
I get the following message when running `generate_profiles.sh`:

`Player Rogue_Assassination_T19P has 19 artifact points, maximum allowed for T19P is 21. Add more!`

Even though I'm pretty sure the Assassination_T19P profile has 21 points.

**Comment by Collisionc** [comment]
I'll look into it, the code seemed to work when I tested it against warrior profiles.

**Comment by Collisionc** [comment]
Disabled until I can work it out.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/07fe8bbf4c55f8cccf62f0935c892c5fc6c95017
https://github.com/simulationcraft/simc/commit/7a826ca460fbf299f499a12e81d5213fd853ed0c

should be fixed now, let me know if you run into anything .
