### ISSUE TITLE
MacOSX + Parallels + Win10 Crash - Fix: Run as admin w/ Vista Compatability

### ISSUE THREAD

**Issue by joelwmale** [simulationcraft/simc#2764]
Hi,

When I try to open SimC it crashes instantly, it loads the main screen then says: SimulationCraft has stopped working. A problem caused the program to stop working correctly.

My windows is up to date, no more updates to be done - fresh install also.

How can I work out what's causing the issue?

**Comment by Collisionc** [comment]
More information helps. What os are you running, computer specs, etc

**Comment by joelwmale** [comment]
I'm running MacOS but using Parallels Desktop to VM Windows 10. It's fresh install windows 10, all updates installed. That's really it. Literally a fresh install of Win10.

I looked for program requirements but couldn't find any.

**Comment by Collisionc** [comment]
If you run the program 'simc.exe' does it crash when loading as well?
ex: Open cmd prompt in the same folder as simc.exe
type in
simc.exe warrior_fury_t19p.simc

**Comment by joelwmale** [comment]
Running at CMD runs fine, I get:

http://pastebin.com/Xhw6WHEu - as the output.

If i try to open SimulationCraft.exe, it quickly loads the whole screen (so I can see Welcome, Import, etc) then just crashes immediately as it loads.

**Comment by Collisionc** [comment]
It's going to be some odd issue with parallels and the library we use for the GUI. I don't know how much I can help you, but I'll try. 

Can you check the appdata folder to see if it is able to create a simulationcraft folder there?  Usually it's something like this:
C:\Users\yourusername\AppData\Roaming\SimulationCraft

**Comment by joelwmale** [comment]
While looking for that, I found the following in:

C:\Simulationcraft(x64)\703-01:
http://pastebin.com/KnhKvrF6

I have:
C:\Users\joel\AppData\Roaming\SimulationCraft
with a file SimulationCraft (type: Configuration Settings): http://pastebin.com/PsyiD9NB

I also have an empty folder here:
C:\Users\joel.SimulationCraft

**Comment by joelwmale** [comment]
I would love to run SimC on Mac but it's not up to date yet I believe so :( - If that's going to be support before legion raids come out, then we don't need to worry about this issue too much. I'm sure people will use the native mac version instead of porting to windows.

**Comment by joelwmale** [comment]
Ok - quick update, I went through some windows capability troubleshooting for the lols, and it ran it in Windows Vista SP2, with Run as Admin, and its not crashing and just simmed my character without issues! @Collisionc

**Comment by Collisionc** [comment]
Ah, good to hear that. I was going to suggest deleting the simulationcraft.ini and letting it rebuild, but I forgot all about compatability mode.

**Comment by joelwmale** [comment]
Thanks for your help. I'll close this out now and stay tuned for if the mac version gets updated! Thanks again!
