### ISSUE TITLE
Missing EU-Pozzo dell'Eternità in Import a character

### ISSUE THREAD

**Issue by barsa-net** [simulationcraft/simc#2765]
In "Import a character" window (Ctrl + I), EU server "Pozzo dell'Eternità"/"Well of Eternity" is missing from the dropdown list.
Version: simc-703-01-win64-e84e5af

**Comment by navv1234** [comment]
New server?

**Comment by barsa-net** [comment]
Nope, the server is open since late 2012

**Comment by Collisionc** [comment]
Did you change the armory region to EU before pressing ctrl + I? 

It's under Options --> Globals

Pozzo dell'Eternita shows up for me.

**Comment by barsa-net** [comment]
Seems that if I have EU already selected when the GUI start, I have to change "Armory Region" to something else and back to EU every time I execute to make it work.

Have it anything to do with this line of code? [https://github.com/simulationcraft/simc/blob/legion-dev/qt/sc_importWidget.cpp#L65](https://github.com/simulationcraft/simc/blob/legion-dev/qt/sc_importWidget.cpp#L65)

**Comment by Collisionc** [comment]
Maybe. I'll see if there is a way to fix that.

**Comment by Collisionc** [comment]
@navv1234 I looked over your code and I can't figure out why it's not working.

**Comment by navv1234** [comment]
This should be fixed in 48826ea.

**Comment by Collisionc** [comment]
Uploaded new version that has fix.

**Comment by barsa-net** [comment]
Now it respond to saved region setting, thanks.
