### ISSUE TITLE
Greater Blessing of Might Values Too High

### ISSUE THREAD

**Issue by ExemplarSA** [simulationcraft/simc#2766]
Values from Aug 19th 2016 version (today, as of this writing)

Values on default self-application of Greater Blessing of Might appear wrong.  "Paladin_Retribution_T19P" consistently shows BoM as 7.1% of total damage.  30% chance to proc for 10% damage should, as Blizzard stated, average to 3%, which would be closer to 2.9% of total damage.  That's 240% stronger than designed.

"Paladin_Retribution_T19P" sims to ~236,669
"Paladin_Retribution_T19P_no_GBoM" sims to ~219,539
No GBoM \* 1.03 to add it in = 219,539 \* 1.03 = 226,125 (4.4% variance from Sim-with-GBoM)

Additionally, cannot apply GBoM to non-Retribution-Paladin sims.  It would be nice to examine how it performs on other classes rather than guessing "3% of total DPS".  Ex: a class could have many small attacks vs several huge ability hits - statistics would lead to more of the small hits proccing than the large, producing overall less than 3% of their total damage output.  Variance may be negligible, but it would still be nice to model.

**Comment by mserrano** [comment]
Greater Blessing of Might is currently defaulting to pretending there are 3 copies of the Blessing on the casting paladin. This is intended to provide a better approximation of the damage contribution of the spell. This behavior can be disabled with `paladin_fake_gbom=0` in the actor, at which point it will assume there is only one copy.

Applying GBoM to non-ret paladins is a reasonable future feature request and is something I'd like to do at some point.

**Comment by mserrano** [comment]
I will note that I think you may be misunderstanding GBoM's behavior. Even if a spec has many small attacks and a handful of large ones, you expect 10% of the small ones and 10% of the large ones to proc GBoM on average, leading to an average benefit of 3%. The difference between many rolls with small payoffs and few rolls with large payoffs is more in terms of variance than in terms of average benefit.

**Comment by ExemplarSA** [comment]
I'd strongly suggest not defaulting to triple blessing the Ret.  Blizzard has stated they assume/balance around 3 Greater Blessings in use, but that not all 3 are Might.  Comparing DPS between classes with that setting falsely inflates Ret when comparing directly to other classes, and deflates them compared to 3 GBoM on higher DPS classes.

Might I suggest GBoM be offboarded to the Buffs screen?  Where it could have a parenthetical noting actual use is max 3 targets per Ret?  That would immediately permit usage on any class/sim and remove any confusion from triple application on the Ret.

**Comment by Collisionc** [comment]
The values aren't too high, and high end guilds are exclusively using them on DPS. I will add in a way to bless other classes, and have the damage transfer to the paladin, but it will take a while.

**Comment by Collisionc** [comment]
Well, glad I didn't do that since it would have been a lot of work and it's getting removed from the game.
