### ISSUE TITLE
SimC crashing whole system on Brewmaster Monk

### ISSUE THREAD

**Issue by Undyingone** [simulationcraft/simc#2768]
I have run Simulations on the 7.0 version on every single spec and character that I play. Brewmaster Monk is particularly frustrating because the "Simulate" bar does not move and instead bogs down and completely locks up my PC. It has happened 3 separate times. If you want to try, the toon's name is Gahege on Blade's Edge. The character is my least favorite tank spec to play, but I still want accurate sims for stat priorities and gear upgrades anyway. Thanks for your help with this.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/issues/2775
