### ISSUE TITLE
Blood DK Tank rotation missing

### ISSUE THREAD

**Issue by Undyingone** [simulationcraft/simc#2769]
Says it in the subject.

**Comment by mike-o-gh** [comment]
In my limited testing, there are a few major issues that I see with blood that would trump narrowing down an APL:
Dancing Rune Weapon doesn't duplicate spells correctly (should get double runic power & double blood shield stacks)
Need some way of determining if you're standing in death & decay (15% more runic power if talented)

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/issues/2775
