### ISSUE TITLE
Fury of Elune

### ISSUE THREAD

**Issue by cyberc0re** [simulationcraft/simc#2770]
Fury of Elune expires early - Expires the moment it goes below 12 Astral Power. On live it drops when the player hits 0 Astral Power.

Lunar Strikes doesn't seem to be generating the correct amount of Astral Power with Incarnation and Blessing of Elune active during Fury of Elune or Fury of Elune is consuming more than 12AsP/s.

The sim shows

![i2t2oxk](https://cloud.githubusercontent.com/assets/21131722/17822950/9ef40e5a-661f-11e6-80e3-37c5d22ee425.png)

Lunar Strikes should be generating 21 and spending 12 leaving a 9 Astral Power Gain, but it currently only gains 3. 

Might be happening with Solar Wrath as well.

**Comment by Collisionc** [comment]
As far as I can tell, this doesn't seem to be a problem in the current build. Is it ?

**Comment by cyberc0re** [comment]
It looks like the issue with both Lunar Strike and Solar Wrath still persist, with the recent hotfixes Lunar Strike should be generating 25.5 Astral Power, and Solar Wrath should be generating 16.5. With bloodlust Solar Wrath is GCD capped at .75, but is losing 3 Astral Power per cast when it should be gaining 4.

![image](https://cloud.githubusercontent.com/assets/21131722/18053529/89b61792-6dc5-11e6-8074-94b77b452520.png)
![image](https://cloud.githubusercontent.com/assets/21131722/18053542/a199c9da-6dc5-11e6-9cf2-e3c8f6fc3e1b.png)

It does seem that something was fixed as Fury of Elune lasts longer than 15 seconds, however I assume that's just the recent Astral Power gain buffs and not the underlying issues.

For reference, here is the APL I'm using, modified to get the most possible out of Fury of Elune.

http://pastebin.com/N7SZ1Rds

For a bit of reference, on the 110 premade server with 6% haste and no bloodlust, I'm able to maintain Fury of Elune for 34 seconds, versus the mere ~20 of the sim, using the exact same rotation

**Comment by cyberc0re** [comment]
Seems the actual astral power generation is fine, perhaps it has something to do with the drain rate of Fury of Elune?

Unless I'm mistaken it should be draining for 12 astral power per second under all circumstances.

**Comment by Collisionc** [comment]
AFAIK, Fury of Elune's 12 astral power per second scales with haste, but if you could confirm/deny that I can fix it either way.

**Comment by cyberc0re** [comment]
That does seem to be true actually. Without bloodlust the duration is about where I'm expecting to be, I guess I'm just a big noob and this was never an issue :ok_hand:

**Comment by Collisionc** [comment]
No worries!
