### ISSUE TITLE
The melee bug of  the unholy deathknight's pet still exisits.

### ISSUE THREAD

**Issue by noeatingman** [simulationcraft/simc#2772]
Now we know that the ghoul'S ability "Cleaver" is dealing 125% of "nomal melee",   this damage data is regular in simulation.

BUT the melee damage in simulation is about 1.68 times than the normal data.      EVEN higher than Cleaver!

**Comment by navv1234** [comment]
Fixed in b23e489bb0f10ccf9cd296f4494ed79c5040c703.
