### ISSUE TITLE
Wrong stat budget for craft ring bonus_id

### ISSUE THREAD

**Issue by skasch** [simulationcraft/simc#2773]
When I run:

```
finger1=maelstrom_band,id=130230,bonus_id=669/1784
```

with `bonus_id=1784` being the id for 100% critical strike, `bonus_id=669` being the id for a crafted gear ilvl 840 and `id=130240` the ring with base versatility, I get the following stats:

```
ilevel: 840, stats: { +997 Sta, +1011 Vers, +1769 Crit }
```

Which is wrong: 1769 is far too high! The total stat budget should be 1769, hence the crit stat shoult be at 758 instead.

**Comment by skasch** [comment]
I also tried with

```
finger1=maelstrom_band,id=130229,bonus_id=667/1718
```

with `bonus_id=1718` being another id for 100% critical strike, but I get the following stats:

```
ilevel: 840, stats: { +997 Sta, +1011 Vers, +707 Crit }
```

which looks correct, yay! However, when I do 

```
finger1=maelstrom_band,id=130229,bonus_id=667/1719
```

where `bonus_id=1719` being the id for 100% versatility, I get

```
ilevel: 840, stats: { +997 Sta, +1011 Vers }
```

It looks like that it doesn't add any additional versatility; I do not know if it's possible or not, and I don't know how to confirm that. Can I reliably suppose that it's impossible?

EDIT: I would like to also get the confirmation that +707 stat is the right value for the crafted ring, it's still off compared to other rings of same level by a few dozen points.

**Comment by navv1234** [comment]
That's what simc presumes .. you cannot double stats. Should be easily changed if it turn out in game you can.
