### ISSUE TITLE
Action pirority list for unholydeathknight

### ISSUE THREAD

**Issue by noeatingman** [simulationcraft/simc#2776]
HELLO!I m very grateful for u can solve the problems I metioned about unholy dk. So I modified some code for unholyDK's action priority.  hope that I can make it better.

 Executed every time the actor is available.

actions=auto_attack
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury
actions+=/berserking
actions+=/use_item,slot=finger1
actions+=/potion,name=deadly_grace,if=buff.unholy_strength.react
actions+=/outbreak,target_if=!dot.virulent_plague.ticking
actions+=/dark_transformation

actions+=/run_action_list,name=valkyr,if=talent.dark_arbiter.enabled&pet.valkyr_battlemaiden.active
actions+=/call_action_list,name=generic

actions.valkyr=death_coil
actions.valkyr+=/apocalypse,if=debuff.festering_wound.stack>=7
actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<8&cooldown.apocalypse.remains<2
actions.valkyr+=/call_action_list,name=aoe,if=active_enemies>=2

actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<=3
actions.valkyr+=/scourge_strike
actions.valkyr+=/clawing_shadows

actions.generic=dark_arbiter,if=runic_power>90
actions.generic+=/summon_gargoyle
actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=7
actions.generic+=/apocalypse,if=debuff.festering_wound.stack>=7
actions.generic+=/scourge_strike,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/clawing_shadows,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/death_coil,if=runic_power>80

actions.generic+=/festering_strike,if=debuff.festering_wound.stack<6&cooldown.apocalypse.remains<2
actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=3&cooldown.apocalypse.remains>8
# actions.generic+=/festering_strike,if=debuff.soul_reaper.up&!debuff.festering_wound.up

actions.generic+=/defile
actions.generic+=/call_action_list,name=aoe,if=active_enemies>=2
actions.generic+=/scourge_strike,if=debuff.scourge_of_worlds.up&debuff.festering_wound.stack>=2
actions.generic+=/clawing_shadows,if=debuff.scourge_of_worlds.up&debuff.festering_wound.stack>=2

actions.generic+=/scourge_strike,if=buff.unholy_strength.react&debuff.festering_wound.stack>=3&rune>=2
actions.generic+=/clawing_shadows,if=buff.unholy_strength.react&debuff.festering_wound.stack>=3&rune>=2
actions.generic+=/festering_strike,if=debuff.festering_wound.stack<=3&!talent.blighted_rune_weapon.enabled
actions.generic+=/festering_strike,if=debuff.festering_wound.stack<=3&cooldown.blighted_rune_weapon.remains>3
actions.generic+=/blighted_rune_weapon,if=debuff.festering_wound.stack<=3

actions.generic+=/scourge_strike,if=buff.necrosis.react
actions.generic+=/clawing_shadows,if=buff.necrosis.react
actions.generic+=/death_coil,if=!talent.dark_arbiter.enabled&buff.sudden_doom.react
actions.generic+=/death_coil,if=talent.shadow_infusion.enabled&talent.dark_arbiter.enabled&!buff.dark_transformation.up&cooldown.dark_arbiter.remains>15
actions.generic+=/death_coil,if=talent.dark_arbiter.enabled&buff.sudden_doom.react&cooldown.dark_arbiter.remains>5

actions.generic+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled

actions.generic+=/festering_strike,if=rune>=3&debuff.festering_wound.stack<=4
actions.generic+=/scourge_strike,if=rune>=3
actions.generic+=/clawing_shadows,if=rune>=3

actions.generic+=/death_coil,if=talent.dark_arbiter.enabled&buff.sudden_doom.react&cooldown.dark_arbiter.remains>5&runic_power>60

actions.generic+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled&runic_power>60

actions.aoe=death_and_decay,if=spell_targets.death_and_decay>=2
actions.aoe+=/epidemic,if=spell_targets.epidemic>4
actions.aoe+=/scourge_strike,if=spell_targets.scourge_strike>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/clawing_shadows,if=spell_targets.clawing_shadows>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/epidemic,if=spell_targets.epidemic>2

**Comment by navv1234** [comment]
Not seeing any benefit from this when comparing T19P and current talent/gear setup. Where is this setup supposed to be better?

**Comment by noeatingman** [comment]
it improves the priority about action of festeringstrike ,scourge strike, and death coil.As we know that 7.0 we will pay more attentions on festering wounds("all will serve" is not suitable for all situation in 7.0 's raid).              and when "aoe epidemic,if=spell_targets.epidemic>4" should have more priority, if we cast death and decay before using epidemic, we will waste some scourgestrike in death and decay.

And I improved the action for apocalypse  and soul reaper.so they can be a strong combo when CD.

actions.generic+=/summon_gargoyle
**actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=7**
actions.generic+=/apocalypse,if=debuff.festering_wound.stack>=7
actions.generic+=/scourge_strike,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/clawing_shadows,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/death_coil,if=runic_power>80

actions.generic+=/festering_strike,if=debuff.festering_wound.stack<6&cooldown.apocalypse.remains<2
**actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=3&cooldown.apocalypse.remains>8**

Maybe my code is bad because I'M not good at this,but I just want "when we have lots of sudden bennifits,we should use scourgesgrike to explore the wounds"can be actualized in action.
And I want to actualize "reserve enough runes(>=3) ,and you can cast more scourgestrike when buffs on"

THIS IS MY SIMC FOR T19P and current talent/gear MODE，1 target,    250s 's battle time.

![simc](https://cloud.githubusercontent.com/assets/21128720/17877478/2b298942-6916-11e6-99bd-cfba181c8eea.png)

ALSO I'M woundering  how to simucraft diffirent artifacts.  

# THANK YOU VERY MUCH FOR UR REPLY!!!

**Comment by navv1234** [comment]
There's a recently update unholy default APL, can you check your stuff against that one?

**Comment by noeatingman** [comment]
IT'S much better now,and it's perfect to use the idea necrosis.  Really appreciate that!

**Comment by navv1234** [comment]
Alright, closing this.
