### ISSUE TITLE
Missing damage from trinket (Terrorbound Nexus)

### ISSUE THREAD

**Issue by torstorruste** [simulationcraft/simc#2777]
I do not see any damage done by the trinket Terrorbound Nexus when trying to simulate the following profile:
[monk_trinket1.txt](https://github.com/simulationcraft/simc/files/429180/monk_trinket1.txt)

I expect the trinket to do at least some damage. In comparison, this is an attempt to simulate the same using AMR:
https://beta.askmrrobot.com/wow/simulator/report/740ceee027aa43b0bd8222d67b1ffd48

**Comment by aggixx** [comment]
Its not implemented because I don't know how many times it hits. I can trivially pick some arbitrary number and implement it like that but that's hardly of much value. If you have any combat logs of it that would be helpful.

**Comment by torstorruste** [comment]
I am unfortunately unable to find any logs using the trinket. I see that AMR has chosen four hits by the waves. I don't know if they base that on logs or just on the description.

**Comment by aggixx** [comment]
Fixed in 78e09269bda683704a66a5aa4c8d5767c29a9c40.
