### ISSUE TITLE
Import fail

### ISSUE THREAD

**Issue by SeedLotus** [simulationcraft/simc#2778]
I`m a chinese player and i wanna use this simc tool. But i can`t import all of my character. This is the error information.
# Profile will be downloaded into a new tab.
# 
# Clicking Simulate will create a simc_gui.simc profile for review.
# 无法从此链接生成档案： http://www.battlenet.com.cn/wow/zh/character/寒冰皇冠/Seedlotus/simple
# BCP API: Unable to download player from 'http://cn.battle.net/api/wow/character/寒冰皇冠/Seedlotus?fields=talents,items,professions&locale=en_US'
# BCP API: Unable to extract player talent specialization from 'http://cn.battle.net/wow/en/character/寒冰皇冠/Seedlotus/advanced'.

I`ll be happy if dear you can help me fix this error. Thanks for all.

**Comment by Collisionc** [comment]
How are you trying to import your character? It works fine for me if I do this:

(video)
http://collision.heroicstrike.org/2016-08-22_08-35-51.mp4
