### ISSUE TITLE
[Survival] Mortal Strike Pet Abilities Proc Hunting Companion

### ISSUE THREAD

**Issue by dashbrown** [simulationcraft/simc#2784]
Pet special abilities will trigger Hunting Companion. The only abilities that affect bosses are:

Carrion Bird - Bloody Screech
Riverbeast - Gruesome Bite
Scorpid - Deadly Sting

Bosses are immune to Growl and Snare effects, but pets with Mortal Strike abilities have a 0-cost ability on a 6-second cooldown which bosses are not immune to.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/6d488c7dc8639b4aaaf36239ea62903ac0c7479d

Fixed by yourself. :)

**Comment by dashbrown** [comment]
My fix was removing the proc from auto attacks, not adding them to mortal strike abilities. I can take a look at implementing that, though.

**Comment by Collisionc** [comment]
whoops. If you don't do it, I will sometime in the next few days .

**Comment by Styrth** [comment]
Any update on this? Pets don't use their special abilities yet.

**Comment by Nakauri** [comment]
Frosted took a look at this for me prior to this report being sent in, but didn't commit anything after concluding it would be a bit more involved and that the hunter pet module was a tad outdated, needing more specific attention. 

I would recommend revamping pets to swap between tenacity and ferocity (mainly for BM + apex predator), and focusing on pets with high frequency extra attacks or the most popular. IE, Carrion Bird (6s), Riverbeast (6s), Scorpid (6s), Crocolisk (10s), Spider (10s), Warp Stalker (15s). These will see more effect from Hunting Companion than, ie, a Nether Ray (lust).

**Comment by Collisionc** [comment]
I believe this has been finally added.
