### ISSUE TITLE
[Warrior] Tactician proc chance reduced by Dauntless

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2785]
Every ability should use its base rage cost to count towards Tactician proc chances, but Dauntless currently reduces an ability's chance to proc Tactician in SimC. If I sim a profile that does nothing but whirlwind and auto-attack, I see the same number of Tactician procs with and without Dauntless. I'd expect to see the Dauntless sim have 25% more tactician procs since 25% more whirlwinds are used due to the reduced rage cost.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/54333a3a954014072fbef74e2f9073d7772d38a1

fixed
