### ISSUE TITLE
[Warrior] Rend ticking every 6s instead of every 3s

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2786]
Rend should tick every 3s, but it ticks every 6 in SimC. Simming a single use of it shows a tick time at 6s, 12s, and then 15s(for a pro-rated 50% damage). The damage values on each tick match what's seen in game, which makes it deal 50% of the total damage it ought to in SimC.

**Comment by amulder87** [comment]
Looks like this is just being caused T18 4pc actually. Breaking that set bonus makes it tick like normal.

**Comment by Collisionc** [comment]
Stupid old tier bonuses.

**Comment by amulder87** [comment]
Hey just a heads up, the change you made to T18 support is adding a flat 1 rage to the cost of Slam with or without this set bonus now!

**Comment by Collisionc** [comment]
Stupid old tier bonuses. :D
