### ISSUE TITLE
[Shadow Priest] Small issues in the default APL

### ISSUE THREAD

**Issue by pnmueller** [simulationcraft/simc#2788]
The following part of the SP default APL (as of the latest commit) is either unnecessarily complex or bugged:
actions.main+=/mind_blast,if=talent.legacy_of_the_void.enabled&(insanity<=81|(insanity<=75.2&talent.fortress_of_the_mind.enabled))
actions.main+=/mind_blast,if=!talent.legacy_of_the_void.enabled|(insanity<=96|(insanity<=95.2&talent.fortress_of_the_mind.enabled))

First off, (insanity<=81|(insanity<=75.2&talent.fortress_of_the_mind.enabled) is functionally equivalent to insanity<=81 because in any case where insanity<=75.2, the statement would already return true after checking <=81. This applies similarly to the second line.

Thus currently it's functionally equivalent to:
actions.main+=/mind_blast,if=talent.legacy_of_the_void.enabled&insanity<=81
actions.main+=/mind_blast,if=!talent.legacy_of_the_void.enabled|insanity<=96

This shows that the first line is also redundant because it's always be covered by the second part of the or-statement in the second line as well, making it ultimately functionally equivalent to just this line:
actions.main+=/mind_blast,if=!talent.legacy_of_the_void.enabled|insanity<=96

With the current APL, that'd practically be equivalent to a simple actions.main+=/mind_blast since a LotV would basically never reach >96 insanity without activating VF previously anway.
I doubt that's what you wanted to achieve so I tested two versions (using the default non-StM profile to reduce variance) that make more sense to me:
1) Cast MB if less than 2/3 of the insanity goes over the supposed threshold to enter void form.
actions.main+=/mind_blast,if=talent.legacy_of_the_void.enabled&(insanity<=80.2|(insanity<=81&!talent.fortress_of_the_mind.enabled))
actions.main+=/mind_blast,if=!talent.legacy_of_the_void.enabled&(insanity<=95.2|(insanity<=96&!talent.fortress_of_the_mind.enabled))
2) Cast MB if less than 2/3 of the insanity is wasted altogether.
actions.main+=/mind_blast,if=insanity<=95.2|(insanity<=96&!talent.fortress_of_the_mind.enabled)
3) To check whether I've made a mistake the APL that should be equivalent to the original.
actions.main+=/mind_blast

Going by some quick sims (0.01% target error) using the T19P default profile with level 100 talents of LotV and non-LotV (no level 100 selected at all as not to suffer from StM's variance):
LotV: 1 = 2 = 3 = default (differences were smaller than the error of ~20 DPS each)
Non-LotV: 3 = default > 1 = 2  (difference of ~200 DPS between 3/default and 1/2)

Thus I'd suggest just replacing the aforementioned lines by a simple actions.main+=/mind_blast (= use MB whenever it's ready) as it's practically equivalent to the current conditions and seems to be superior to delaying MB until VF.

**Comment by Twintop** [comment]
Good catch. A little background on what these lines were originally intended to accomplish:

Looking at these (non LotV first):

actions.main+=/mind_blast,if=talent.legacy_of_the_void.enabled&(insanity<=81|(insanity<=75.2&talent.fortress_of_the_mind.enabled))
actions.main+=/mind_blast,if=!talent.legacy_of_the_void.enabled|(insanity<=96|(insanity<=95.2&talent.fortress_of_the_mind.enabled))

This line is checking to see if you can get in to Voidform in the next GCD by, at most, channeling Mind Flay (2 ticks \* 2 Insanity per tick, thus the <= 96 (probably should have been less than, not less than or equal to), or 95.2 if FotM is enabled). The thought behind this being if you're going to be nn Voidform in GCD+1 in either case, you might as well save Mind Blast. The other line (with LotV) should be the same logic but using 85 Insanity as the gate (so FotM should be 80.2, not 75.2).

With that being said, that logic was put in place (and never updated) back when entering Voidform was an instant cast, whereas now you have to cast Void Eruption to enter, delaying Mind Blast by 1 + 1 1/3 GCDs potentially, which I agree doesn't make a bunch of sense.

Ultimately, you should be using Mind Blast in this position unless there's a compelling reason not to, such as potentially not refreshing SWP or VT slightly earlier on some other target (where you'll still get to 100 / 85 Insanity).

Have you tried checking any other intervals of missing Insanity (like <=97, 98, or 82,83) in the off chance that sometimes a refreshing of VT does the trick and still makes it worthwhile?

I'm out of town for the weekend so I won't be able to look in to it on my side until Sunday night.

**Comment by pnmueller** [comment]
Maybe I'm missing something here but given that MB is positioned below the refresh logic for single target VT/SW:P, changing it to e.g. <=97 shouldn't make any positive difference for the case you mentioned.  For multi-target it might make a difference (cycling SWP/VT is currently handled below MB) although you could just shift MB's priority to below those for the same result.

Edit: Quickly checked <=97 and <=98 for non-FotM and non-LotV and the sims are within ~0.03% of using it at any insanity (once again with an error of 0.01%).

**Comment by pnmueller** [comment]
When comparing racials, I noticed that Berserking isn't used very well during the first Bloodlust (too early to be precise).
I've adjusted usage to this before running sims again:
Removed:
actions.vf+=/berserking,if=buff.voidform.stack>=10&buff.insanity_drain_stacks.stack<=20&!talent.surrender_to_madness.enabled
actions.vf+=/berserking,if=buff.voidform.stack>=10&talent.surrender_to_madness.enabled&target.time_to_die>variable.s2mcheck-(buff.insanity_drain_stacks.stack)+70
Added:
actions.vf+=/berserking,if=buff.voidform.stack>=10&buff.insanity_drain_stacks.stack<=20&!talent.surrender_to_madness.enabled&!buff.bloodlust.up
actions.vf+=/berserking,if=buff.voidform.stack>=10&talent.surrender_to_madness.enabled&target.time_to_die>variable.s2mcheck-(buff.insanity_drain_stacks.stack)+70&!buff.bloodlust.up
actions.vf+=/berserking,if=buff.voidform.stack>=20&buff.insanity_drain_stacks.stack<=30&!talent.surrender_to_madness.enabled&buff.bloodlust.up
actions.vf+=/berserking,if=buff.voidform.stack>=20&talent.surrender_to_madness.enabled&target.time_to_die>variable.s2mcheck-(buff.insanity_drain_stacks.stack)+70&buff.bloodlust.up

I simply adjusted the required amount of stacks to be >=20 (and <=30 in case of non-StM) instead of >=10 (and <=20 in case of non-StM) during bloodlust to account for the longer expected void form uptime. You could theoretically shorten it to two lines again but that'd make those lines fairly bloated so I simply split it into two cases (2 lines if no bloodlust, 2 lines if bloodlust).

Here are some sims:
Adjusted APL: http://hidden.bplaced.net/PriestSims/SP_HordeRaces.html (previously troll would be behind goblin for non-S2M so the adjustment definitely helped with non-S2M)
With the default APL, however, troll was winning against other races for T19M_S2M, e.g. http://hidden.bplaced.net/PriestSims/SP_S2M_OldAPL.html shows troll significantly ahead of goblin which was winning with the adjusted APL.

Thus I'd conclude that for now the best option seems to be to adjust Berserking for non-S2M to have a >=20 stack threshold during bloodlust and keep S2M to have a >=10 stack threshold during bloodlust. I don't have any time to do more simulations right now (and the data I have gathered so far is already conclusive on troll winning in all cases with proper Berserking usage) but I'd strongly assume you could optimize the S2M case further, e.g. to use Berserking only at >20 stacks with bloodlust up unless that'd result in a usage of Berserking being skipped altogether.

**Comment by Twintop** [comment]
Haven't forgotten about this, just busy with Legion stuffs.

**Comment by pnmueller** [comment]
I wouldn't bother right now either. Just keep it in mind before doing any comparisons where this might have an effect (e.g. comparing racials for your site).

I'll probably also look into the APL as well as the module a bit more once raids are released.
