### ISSUE TITLE
Automatic waiting and ability delays

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2789]
This may not be resolvable with how the SimC engine is currently designed, but the automatic 0.1s waiting action that's triggered when no action in a priority list is ready causes undesirable behavior by delaying potentially usable abilities longer than you would want.

If I sim a warrior with gear totaling 21% haste and an APL like this:

```
warrior="Test"
level=110
race=orc
role=attack
position=back
talents=0000311
spec=arms

# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.pre_combat+=/snapshot_stats
actions=auto_attack
actions+=/focused_rage,if=buff.battle_cry.up
actions+=/battle_cry
```

I'll see ability usage that looks like this, only fitting 4 focused rage casts inside the 5s BC window:

```
0:00.000    battle_cry  
0:00.000    focused_rage
0:00.000    Waiting 1.300 sec
0:01.300    focused_rage
0:01.300    Waiting 1.300 sec
0:02.600    focused_rage
0:02.600    Waiting 1.300 sec
0:03.900    focused_rage
0:03.900    Waiting 56.100 sec
```

Even though FR is coming off CD every 1.24s, it's being delayed to 1.3s by waiting events. If I add something to the GCD so no waiting actions are triggered in this time, the off-gcd abilities can then trigger on CD instead. E.g., changing the APL to:

```
warrior="Test"
level=110
race=orc
role=attack
position=back
talents=0000311
spec=arms

# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.pre_combat+=/snapshot_stats
actions=auto_attack
actions+=/focused_rage,if=buff.battle_cry.up
actions+=/slam,if=buff.battle_cry.up
actions+=/battle_cry
```

will result in no waiting events delaying FR's CD, which allows 5 uses to fit inside the same window like we'd expect when past the 20% haste breakpoint:

```
0:00.000    battle_cry
0:00.000    slam
0:00.000    focused_rage
0:01.243    slam
0:01.243    focused_rage
0:02.485    slam
0:02.485    focused_rage
0:03.728    slam
0:03.728    focused_rage
0:04.971    slam
0:04.971    focused_rage
0:06.215    Waiting 53.800 sec
```

This is a fairly extreme use-case to highlight the issue, but the same thing can happen in any real sim that's resource or CD constrained. Abilities on or off the GCD coming off CD in the middle of a wait event will be delayed until the end of the event even when they should be immediately usable. The same goes for a lack of resources triggering a wait. If an auto attack grants enough rage to allow an ability on the APL to fire during a wait event, it still has to complete the wait duration before being triggered. The more a class/spec enters wait times, the more they'll be impacted by the micro-delays adding up over a fight.

**Comment by navv1234** [comment]
We have something for abilities on GCD that allows them to be queued 250ms (by default) before their cooldown actually elapses. That support would need to be extended to abilities that can be used during GCD too, but I have not had time to look into how hard that is to implement. As an example, if I disable the explicit support for focused rage being usable while GCD is elapsing, I do get this:

```
0.000 Test performs focused_rage (0)
1.234 Test performs focused_rage (0)
```

Which is presumable what you are talking about here.

**Comment by navv1234** [comment]
I now adjusted the queue stuff so that if you are not in a GCD, abilities that the sim allows to be used during the GCD are given the same 250ms queueing treatment as normal on-gcd abilities.

Allowing that to occur while the GCD is elapsing requires more extensive changes, and will have to wait (at least a bit).

**Comment by natehieter** [comment]
Investigate trigger_ready.  Might require some enhancements to warrior
module to use.

**Comment by navv1234** [comment]
Trigger_ready is more or less bound to GCD, adapting it for ability use during GCD might be tricky.

**Comment by Collisionc** [comment]
Closing as this was fixed inside https://github.com/simulationcraft/simc/issues/2811
