### ISSUE TITLE
Destruction Havoc Implementation

### ISSUE THREAD

**Issue by nasirabtw** [simulationcraft/simc#2791]
I thought just removing the charge mechanic from WoD would let havoc function properly, but it hits an infinite loop somewhere, and target_list stuff is beyond my purview.

http://www.wowhead.com/spell=80240/havoc

Applies a debuff to the current target for 8 (20 with wreak havoc talented) seconds. During the debuff direct spells cast at any other target are duplicated onto the debuffed target. 'single target spells' are immolate, incinerate, conflagrate, chaos bolt, shadowburn, and channel demonfire.

**Comment by Collisionc** [comment]
I got your back bro.

**Comment by Collisionc** [comment]
I don't think you need target list at all, not sure why it's there.

**Comment by YepItsEuko** [comment]
How do you implement Havoc in a 2 target sim? I have been trying to look it up but this page is the closest I have actually even come to information on it. I tried adding `actions+=/havoc,if=remains=0` to the beginning of my APL but I believe this just makes it cast it on each target infinitely (casting on a different target removes the buff), seeing as it cast it 174.8x in a 300s fight.

Edit- For those that might want to know this in the future.. I use `actions+=/havoc,line_cd=20,target=enemy2` for my APL and add `
enemy=Fluffy_Pillow
enemy=enemy2
` in the overrides tab.
