### ISSUE TITLE
Simcraft search function not allowing me to find profile

### ISSUE THREAD

**Issue by gonlaz** [simulationcraft/simc#2792]
It's kind of crazy, I cannot search for my toon profiles because the home page of the current wow site is only half showing on the simcraft screen. I use a 26" widescreen, used simcraft a year ago with no issues but this time I can't "search", no room on the screen, hope that makes sense. And when I try to enter my profile manually, no results to sim, so I am finding it difficult to know what I am doing wrong, I apologize if this is the wrong place however I do not see any other place to post. Thanks in advance!

![untitled](https://cloud.githubusercontent.com/assets/21298496/18037643/595d124e-6d57-11e6-99ed-427062007d7a.png)

**Comment by Collisionc** [comment]
Blizzards website change destroyed the browser we were using in that version. That's also an extremely old version. It actually doesn't even work that well in the new version either, but we're still trying to find a way around that.

http://downloads.simulationcraft.org/?C=M;O=D

We haven't officially released 703-01 yet, but the top .7z files are the newest versions of simc.

There's also a giant warning when you open the program. :) 

![Image](http://collision.heroicstrike.org/SimulationCraft_2016-08-28_21-49-29.png)

**Comment by gonlaz** [comment]
Thank you for the response, I greatly appreciate it. If I cannot pull profiles with the link you offered are there other ways of calculating weights? Sadly I summer not a theorycrafter and haven't the slightest how to do it on my own. Thanks either way!

**Comment by Collisionc** [comment]
The newest version has a new method of importing, you will see it when you load the program.

**Comment by gonlaz** [comment]
Works great, thank you for your work :) 

```
On Monday, August 29, 2016 11:20 PM, Alex <notifications@github.com> wrote:
```

 The newest version has a new method of importing, you will see it when you load the program. —
