### ISSUE TITLE
[Linux] SimC fails to load sample profiles

### ISSUE THREAD

**Issue by adamhl8** [simulationcraft/simc#2793]
On Linux, SimC fails to load any of the sample profiles and the Sample Profiles tab appears blank.

I get this message in my terminal:

`Sample Profiles Base Path:  "$HOME/.local/share/SimulationCraft/SimulationCraft/profiles"  exists:  false`

It  seems as though it's assuming I've run the install script.

Would it be possible to add some kind of fallback so it looks for the profiles directory based off the executable location?

**Comment by scamille** [comment]
Fixed in 41b1a424a825062e8070eeca3ea25376f5a2b94c

Not sure if I broke the install script/packaging, but I hope not. Not sure if anyone uses that anymore ;)
