### ISSUE TITLE
[Frost DK] potion,type instead of potion,name

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#2795]
I'm not entirely sure but all frost DK scripts mention `actions+=/potion,type=deadly_grace` in the in-combat rotation.
The prepot action says `actions.precombat+=/potion,name=deadly_grace`

Which one is the correct one?

**Comment by navv1234** [comment]
Either works.

**Comment by navv1234** [comment]
If one or the other is easier for ovale (name was the original one), I can adjust the default APL as necessary. We don't really care either way.

**Comment by Hemario** [comment]
It will prevent us having to facilitate both. 
It should be a simple "or" statement in the place where we check the name.

Why is there a difference anyway if they do the same thing?
Wouldn't it be just easier to delete the "type" functionality and go with name always?

**Comment by navv1234** [comment]
I now changed DKs and Rogues to use "name" across the board (flasks, potions, food, augments). I can't speak for other class modules at the moment.
