### ISSUE TITLE
cooldown.gcd.remains returning 0 when the GCD has just been triggered

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2796]
I'd like to setup an APL that only uses Battle Cry and Avatar in sync with the GCD's availability, along with various other conditions. There's not much advantage in using these cooldowns in between GCDs since they only buff damaging actions that are on the GCD. My intention is to use them immediately prior to using a GCD ability(as you would with a macro), which allows you to fit the most GCDs inside their duration as you can.

I tried adding "if=!cooldown.gcd.remains", but it's evaluating to true even when a GCD has just been used, causing the cooldown to fire immediately after a GCD ability was used instead of immediately before one, even though it's earlier in the action list than the on-GCD abilities. Are off-GCD abilities being evaluated strictly after all the on-GCD abilities are evaluated, but before they're actually processed and update the state of the simulator? Is there some existing way I can get around this behavior or accomplish what I'm looking to do here?

I'd expect battle cry to trigger immediately before the first Execute is used inside a colossus smash with this APL:

```
warrior="Warrior Test"
level=110
race=goblin
role=attack
position=back
talents=1332311
artifact=36:137469:137363:137377:0:1136:1:1137:1:1139:1:1142:1:1145:3:1147:3:1148:3:1149:3:1150:6:1356:1
spec=arms

actions=charge
actions+=/auto_attack
actions+=/battle_cry,if=!cooldown.gcd.remains&debuff.colossus_smash.up
actions+=/colossus_smash,if=debuff.colossus_smash.down&target.health.pct<20&!cooldown.battle_cry.remains
actions+=/execute,if=buff.battle_cry.up

main_hand=stromkar_the_warbreaker,id=128910,bonus_id=750,gem_id=137469/137363/137377,relic_id=3412/3412/3412
```

Instead, it's triggered immediately after the colossus smash:

```
5:12.100    colossus_smash
5:12.100    battle_cry
5:13.590    execute
5:15.079    execute
5:16.567    execute
5:18.056    Waiting 54.100 sec
```

**Comment by Collisionc** [comment]
Try using gcd.remains instead.

**Comment by Collisionc** [comment]
Did that work for you ?

**Comment by amulder87** [comment]
Hey sorry, I was on vacation and couldn't check for a few days. I just tried replacing !cooldown.gcd.remains with !gcd.remains or gcd.remains=0 in that profile, and that prevents battle cry from ever firing, even though it should definitely be true for plenty of GCDs after colossus smash is used. The sample sequence table just ends up looking like:

```
5:12.100    colossus_smash
5:13.588    Waiting 43.300 sec
5:56.888    colossus_smash
5:58.591    Waiting 31.500 sec
```

**Comment by Collisionc** [comment]
I'll look into it, been busy. : )

**Comment by Collisionc** [comment]
Ok, corrected.    gcd.remains=0 will now work like you want it to. :)

**Comment by amulder87** [comment]
Works like a charm! This is awesome, thanks!
