### ISSUE TITLE
[Windows] Crash during scale factor calculations

### ISSUE THREAD

**Issue by skubBoy** [simulationcraft/simc#2797]
Using the latest release available on the website (703-01) on win 7. Experiencing crashes during scale factor calculations but if I turn them off my simulations finish fine. Unsure if there are any dump files I need to provide.

**Comment by Collisionc** [comment]
Can you provide the simc_gui.simc file that is the same directory after it crashes?

**Comment by skubBoy** [comment]
Here it is: a.pomf.cat/huxbqy.simc

**Comment by Collisionc** [comment]
Ok, fixed it I think. 

Try the 703-02 download here - http://downloads.simulationcraft.org/?C=M;O=D
