### ISSUE TITLE
In game addon error

### ISSUE THREAD

**Issue by jazz836062** [simulationcraft/simc#2798]
I receive an error when I have the simulationcraft addon enabled.  It has to do with the artifact.  This is the latest one.

Message: Interface\FrameXML\MainMenuBar.lua:126: Usage: GetCostForPointAtRank(rank)
Time: 09/03/16 13:10:29
Count: 1
Stack: Interface\FrameXML\MainMenuBar.lua:126: in function <Interface\FrameXML\MainMenuBar.lua:124>
...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:234: in function <...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:229>
...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:295: in function <...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:282>
...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:313: in function <...aft\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:312>

Locals: pointsSpent = nil
artifactXP = nil
numPoints = 0

It makes the artifact interface not usable at all (I can't open it).

Also, I'm not sure is this is the correct place to put this.  If there is a different place, please let me know and I will post it there.  Thanks for everything you guys and gals do.

**Comment by Collisionc** [comment]
This should have been fixed with an update yesterday, although you may have to update it to the alpha version.

**Comment by Collisionc** [comment]
If you use curse client to update addons, right click simulationcraft and change release type to alpha and then update again. 

(Although we are going to have to  update it again for another issue possibly)

**Comment by Collisionc** [comment]
Ok, we updated the addon to work properly, even as non-alpha version. It might take a few hours to show up on curse.com, but it will effectively force-open your artifact weapon everytime /simc is typed, because of the way blizzard has everything designed.
