### ISSUE TITLE
[Mac] no html inside simulationcraft GUI

### ISSUE THREAD

**Issue by Brear** [simulationcraft/simc#2800]
with V703-01 no html-content is shown inside the GUI.

**Comment by Collisionc** [comment]
I think navv is the only person who uses OSX.

**Comment by navv1234** [comment]
Yes second person who reports this, but I have no clue what the problem is, really. What OS X version are you running?

EDIT: Nevermind I see something now .. investigating.

**Comment by Brear** [comment]
hello navv,
some additional information maybe it helps. What I´ve tested.
3 different Mac`s. 2x OS X 10.11.6 (15G1004), 1x OS X 10.10.5 (14F27).
Made two complete clean installs. Fresh dmg download from simulationcraft.org website. 
703-01 no html
623-02 html working
The difference that I´ve seen is that 623-02 **WebKit** and 703-01 **WebEngine**.
Maybe there...

Edit: Normally I´m using german as system language. Changed to english. No difference

**Comment by navv1234** [comment]
Yeah I found the issue .. I think, something messed up in our osx package script.

**Comment by navv1234** [comment]
Alright, new version uploaded now. It should work.

**Comment by Brear** [comment]
Thanks navv,
downloaded new version. Works perfect again.

**Comment by navv1234** [comment]
Alright.
