### ISSUE TITLE
[Windows] Armory import crashes

### ISSUE THREAD

**Issue by cenkbut** [simulationcraft/simc#2807]
Since the armory is back with artifacts and items and all.

When I navigate to my advanced armory (http://eu.battle.net/wow/en/character/twisting-nether/******/advanced) from the embedded browser and press import, after the bar reaches 70% or so the application crashes with an access violation error.

Thanks a lot,
Fred

**Comment by Collisionc** [comment]
Try the top 703-02 version here - http://downloads.simulationcraft.org/?C=M;O=D

We didn't know how blizzard would put artifacts in armory so we didn't have any code to support it.

**Comment by cenkbut** [comment]
Thanks for the swift response. I have tried both 703-02 executable and the 7z package problem still happens but more further down the line in the import process around 80% of the bar or so. is there anyway I can get my debug logs and send it to you. Might help I believe.

**Comment by Collisionc** [comment]
I'd need to know your character's name so I can try to import the armory.

**Comment by Collisionc** [comment]
Also, btw, you'll still need to use the simc addon as we haven't found a way to import artifact traits from armory yet.

**Comment by Collisionc** [comment]
Try the newest 703-02 that was uploaded today, it should import from armory with artifact traits.

**Comment by Collisionc** [comment]
Just tried it out with a bunch of armories, the newest 703-02 release works fine. We will release an official version of 703-02 sometime in the next few days.
