### ISSUE TITLE
Player uses call_action_list with unknown action list core

### ISSUE THREAD

**Issue by gjritter** [simulationcraft/simc#2809]
I'm currently getting this output when importing my Blood DK from the armory and attempting to simulate:

```
Player Furor uses call_action_list with unknown action list core
Simulation has been canceled during player setup! (thread=0)                     
Player Furor uses call_action_list with unknown action list core
```

I'm on Windows 10, using 703-02.

Steps to reproduce:
1. Import character Furor-Garona
2. Press Simulate
3. See the messages above on the results tab

I apologize if I've missed a setup step somewhere, but wasn't finding anything matching this in past issues  or in the starters guide.

**Comment by Collisionc** [comment]
Unfortunately blood dk isn't fully implemented yet, we hope to get it up and running soon. 

https://github.com/simulationcraft/simc/issues/2775
