### ISSUE TITLE
SIMC CRASHING

### ISSUE THREAD

**Issue by kriptic1** [simulationcraft/simc#2810]
i open up SIMC client and when i try to import my character (beenafflock) its starts to import then halfway though it crashes the client i have even tried uninstalling and reinstalling the client i can import some of my other characters though.
PLEASE HELP

**Comment by Collisionc** [comment]
Can you link the armory? There are a lot of beenafflocks.

**Comment by kriptic1** [comment]
http://us.battle.net/wow/en/character/kelthuzad/Beenafflock/simple

**Comment by kriptic1** [comment]
i have figured out a way to make it work though the add-on but for some reason it crashes if i try to import from battle net and i know right now it doesn't matter but for the future when they do put it on battle.net would be easier to just import that way

**Comment by Collisionc** [comment]
Try this version - http://downloads.simulationcraft.org/SimcSetup-703-02-Win64.exe

It'll be officially released sometime today/tomorrow, but it should allow bnet imports of your character.

**Comment by kriptic1** [comment]
downloaded the new version and loaded a little farther but still crashes

**Comment by Collisionc** [comment]
Ah, ok. We will need to fix this, check back tomorrow.

**Comment by navv1234** [comment]
This should now be fixed

**Comment by Collisionc** [comment]
Just uploaded a newer version of 703-02-win64.exe, try reinstalling it and see if it works.
