### ISSUE TITLE
[Rogue] Subtlety Finality

### ISSUE THREAD

**Issue by aethys256** [simulationcraft/simc#2813]
Hello,
In the 22133 build, Blizzard changed Finality behavior.
Before it was replacing the next finisher by an improved version (roughly 15% increased dmg), now it does gives a buff of 4% per CP on the next finisher (from 4% to 24% then with DS).

Here's how I would model it :
- Remove Finality Eviscerate & Nightblade action
- Remove the Finality expressions (we will check the buffs in the APL instead)
- Create Finality Eviscerate Buff (no ICD it seems, proc on Eviscerate cast)
- Create Finality Nightblade Buff (no ICD it seems, proc a bit after Nighblade cast, between application & first tick basically, not sure if it's a bug or not)
- Add a condition in Eviscerate, Nightblade and Death from Above to check if the corresponding Finality buff is there, if yes consume it and apply the modifier to the action.
- Make it possible to check the % of the modifier buff in the APL (because of DS, we might cast sometimes at 5 or 6 CPs depending on procs), this thing could be useful (Maybe by using stacks on the buff, like 1 stack = 4%, max 6 stacks.)
- Make an expression like "target.finality_nightblade" so we can check if the nightblade on the current target (because of cycle_targets=1) is a finality one or not. (Used for "fishing")

Just for reference, seems Nightblade and Eviscerate are updated on AMR (since 22133 with 5% per stack and 22201 with 4%) :
http://www.askmrrobot.com/wow/theory/mechanic/spell/eviscerate?spec=RogueSubtlety&version=7_0_3_22498
http://www.askmrrobot.com/wow/theory/mechanic/spell/nightblade?spec=RogueSubtlety&version=7_0_3_22498

WoWHead links :
http://www.wowhead.com/spell=197496 <- Finality: Eviscerate (Proc from Normal Eviscerate and DfA)
http://www.wowhead.com/spell=197498 <- Finality: Nightblade (Proc from Normal Nightblade)

Nightblade dot damage is still entirely overwritten. (Same behavior as before), there is no "partial snapshot" from my tests.
I'm not sure about Weaponmaster interaction.

**Comment by mrdmnd** [comment]
Thanks for the note. This seems like a reasonable approach.

**Comment by navv1234** [comment]
Initial sketch in dd237e8.

Two expressions are available to check the state of finality on the on going nightblade dot on a target. On a nightblade apl line `finality`, and on any APL line `dot.nightblade.finality` will evaluate to 1 when the on-going dot is the finality version.
