### ISSUE TITLE
Please help, I can not use your program, an error!

### ISSUE THREAD

**Issue by Gifted81** [simulationcraft/simc#2814]
Player Райдеон uses call_action_list with unknown action list core
Simulation has been canceled during player setup! (thread=0)  
Player Райдеон uses call_action_list with unknown action list core

**Comment by Gifted81** [comment]
I also use your addon to import into the program of the character with the artifact.

**Comment by Collisionc** [comment]
Same issue as:  https://github.com/simulationcraft/simc/issues/2809
which is also probably related to https://github.com/simulationcraft/simc/issues/2775

Unfortunately blood dk hasn't been completed yet. =(

**Comment by Gifted81** [comment]
все я понял!спасибо за ответ
