### ISSUE TITLE
[Rogue] Outlaw's RtB pre combat not showing buffs

### ISSUE THREAD

**Issue by eduardo-skrepnek** [simulationcraft/simc#2818]
On a simulation, under Action Priority List > Sample Sequence Table, the Roll the Bones on pre combat is not displaying the buffs on the column "buffs".
There could be one of two issues:
1. Just display, but the buffs are there
2. The buffs are not being included on the combat start, affecting the result of simulations.

There is 2 prints showing the RtB before and on combat
![rtb_before](https://cloud.githubusercontent.com/assets/11316915/18417361/53de4a1a-7804-11e6-8a64-a3000fdf3982.png)
![rtb_during](https://cloud.githubusercontent.com/assets/11316915/18417362/53e2b1d6-7804-11e6-8221-07444d1902b5.png)

**Comment by aethys256** [comment]
It does work but it isn't displayed.

> 0.000 Rogue_Outlaw_T19M performs marked_for_death (100)
> 0.000 Rogue_Outlaw_T19M marked_for_death hits Fluffy_Pillow for 0 physical damage (none)
> 0.000 Fluffy_Pillow gains marked_for_death_1 ( value=-0.00 )
> 0.000 Rogue_Outlaw_T19M gains 5.00 (5.00) combo_points from marked_for_death (5.00/6.00)
> 0.000 Rogue_Outlaw_T19M performs roll_the_bones (100)
> 0.000 Rogue_Outlaw_T19M roll_the_bones hits Fluffy_Pillow for 0 physical damage (none)
> 0.000 Rogue_Outlaw_T19M consumes 0.0 energy for roll_the_bones (100)
> 0.000 Rogue_Outlaw_T19M gains 1.00 (1.00) combo_points from Ruthlessness (1.00/6.00)
> 0.000 Rogue_Outlaw_T19M gains alacrity_1 ( value=0.01 )
> 0.000 Rogue_Outlaw_T19M gains roll_the_bones_1 ( value=-0.00 )
> 0.000 Rogue_Outlaw_T19M gains broadsides_1 ( value=-0.00 )

**Comment by Collisionc** [comment]
It's a feature with buffs/debuffs that are cast precombat, originally (I think?) the code was put there to make sure that old school raid buffs (battle shout, commanding shout, blessings, etc.) didn't clutter the sample sequence table.  

Now that those raid buffs are gone, we can probably adjust it to show buffs that occur in precombat.

**Comment by Collisionc** [comment]
Wasn't a good idea to show all buffs, forgot about flasks, augments, etc. :P

However, what was happening is that the rtb buffs (jolly rodgers and whatnot) have an infinite duration in spelldata as they show up as auras. So, I gave them a fixed duration matching the duration of rtb_buffs whenever they were triggered in simc, as we are filtering out precombat buffs that have infinite durations in the sample sequence.
