### ISSUE TITLE
[Hunter] The Artifact skill for survival hunter seems abnormal

### ISSUE THREAD

**Issue by yueyue252** [simulationcraft/simc#2819]
It seems the artifact skill of survival hunter dealt too much damage.  I also found that there are two versions of this skill.  I wondered whether the errors came from here.
1. Furiously strikes all enemies in front of you, dealing [ **625% of Attack Power** ] Physical damage. Damage increased by Mongoose Fury.  (from http://www.wowdb.com/spells/203415-fury-of-the-eagle)
2. Furiously strikes all enemies in front of you, dealing (**(225% of Attack power) \* 5**) Physical damage. Damage increased by Mongoose Fury. (from http://www.wowhead.com/spell=203415/fury-of-the-eagle#comments)

Here is my character import data from your addon. While only use this skill without any buff on a raid dummy ingame shows 300k damage, but the sims showed a total of over 500k damage.  Software version is simc-703-02-win64-f68d796.7z

hunter="Survival Hunter"
level=110
race=blood_elf
region=cn
server=
role=attack
professions=enchanting=762/jewelcrafting=745
talents=2312312
spec=survival
artifact=34:0:0:0:0:1068:1:1072:3:1073:3:1075:3:1076:3:1080:1:1082:1:1338:1

head=,id=134211,bonus_id=1727/1512/3336
neck=,id=136020,bonus_id=3427/1482/3338
shoulder=,id=134478,enchant_id=5442,bonus_id=1727/1492/1813
back=,id=134405,bonus_id=1727/1808/1497/3336
chest=,id=139707,bonus_id=3386/3383
shirt=,id=98543
tabard=,id=23192
wrist=,id=139282,bonus_id=1726/1492/3337
hands=,id=139117,bonus_id=3397/1808/1497/3336
waist=,id=137520,bonus_id=1727/1492/1813
legs=,id=134483,bonus_id=1727/1497/3336
feet=,id=134386,bonus_id=1726/1492/3339
finger1=,id=134531,bonus_id=1727/1492/1813
finger2=,id=130231,bonus_id=3372/689/601/669,gem_id=130221
trinket1=,id=139113,bonus_id=3397/1808/607/1492/1675
trinket2=,id=137537,bonus_id=1727/1497/3336
main_hand=,id=128808,bonus_id=728,relic_id=1727:1492:1813/1727:1492:1813/1726:1477,gem_id=137550/137472/137302/0

**Comment by Collisionc** [comment]
Oh, didn't realize there was an issue for this.

fixed here: https://github.com/simulationcraft/simc/commit/b023e89bb50084f1119f626a1bad677306c055e2
