### ISSUE TITLE
[Elemental Shaman] Gear/enchant/food/apl/pet-apl changes

### ISSUE THREAD

**Issue by Bloodmallet** [simulationcraft/simc#2820]
shaman="Shaman_Elemental_T19P"
level=110
race=orc
role=spell
position=ranged_back
talents=3112212
artifact=40:137365:137272:137365:0:291:1:294:1:295:1:296:1:298:3:300:6:301:3:302:3:303:3:1350:1
spec=elemental
# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.
# Executed before combat begins. Accepts non-harmful actions only.

actions.precombat=flask,type=whispered_pact
actions.precombat+=/food,name=fishbrul_special
actions.precombat+=/augmentation,type=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.

actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/stormkeeper
actions.precombat+=/totem_mastery
# Executed every time the actor is available.
# Bloodlust casting behavior mirrors the simulator settings for proxy bloodlust. See options 'bloodlust_percent', and 'bloodlust_time'.

actions=bloodlust,if=target.health.pct<25|time>0.500
# In-combat potion is preferentially linked to Ascendance, unless combat will end shortly

actions+=/potion,name=deadly_grace,if=buff.ascendance.up|target.time_to_die<=30
actions+=/totem_mastery,if=buff.resonance_totem.remains<2
actions+=/fire_elemental
actions+=/storm_elemental
actions+=/elemental_mastery
actions+=/blood_fury,if=!talent.ascendance.enabled|buff.ascendance.up|cooldown.ascendance.remains>50
actions+=/berserking,if=!talent.ascendance.enabled|buff.ascendance.up
actions+=/run_action_list,name=aoe,if=active_enemies>2&(spell_targets.chain_lightning>2|spell_targets.lava_beam>2)
actions+=/run_action_list,name=single
# Single target action priority list

actions.single=ascendance,if=dot.flame_shock.remains>buff.ascendance.duration&(time>=60|buff.bloodlust.up)&cooldown.lava_burst.remains>0&!buff.stormkeeper.up
actions.single+=/flame_shock,if=!ticking
actions.single+=/flame_shock,if=maelstrom>=20&remains<=buff.ascendance.duration&cooldown.ascendance.remains+buff.ascendance.duration<=duration
actions.single+=/earth_shock,if=maelstrom>=92
actions.single+=/icefury,if=raid_event.movement.in<5
actions.single+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)
actions.single+=/elemental_blast
actions.single+=/earthquake_totem,if=buff.echoes_of_the_great_sundering.up
actions.single+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single+=/frost_shock,if=talent.icefury.enabled&buff.icefury.up&((maelstrom>=20&raid_event.movement.in>buff.icefury.remains)|buff.icefury.remains<(1.5_spell_haste_buff.icefury.stack))
actions.single+=/frost_shock,moving=1,if=buff.icefury.up
actions.single+=/earth_shock,if=maelstrom>=86
actions.single+=/icefury,if=maelstrom<=70&raid_event.movement.in>30&((talent.ascendance.enabled&cooldown.ascendance.remains>buff.icefury.duration)|!talent.ascendance.enabled)
actions.single+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single+=/stormkeeper,if=(talent.ascendance.enabled&cooldown.ascendance.remains>10)|!talent.ascendance.enabled
actions.single+=/totem_mastery,if=buff.resonance_totem.remains<10|(buff.resonance_totem.remains<(buff.ascendance.duration+cooldown.ascendance.remains)&cooldown.ascendance.remains<15)
actions.single+=/lava_beam,if=active_enemies>1&spell_targets.lava_beam>1
actions.single+=/lightning_bolt,if=buff.power_of_the_maelstrom.up,target_if=!debuff.lightning_rod.up
actions.single+=/lightning_bolt,if=buff.power_of_the_maelstrom.up
actions.single+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1,target_if=!debuff.lightning_rod.up
actions.single+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single+=/lightning_bolt,target_if=!debuff.lightning_rod.up
actions.single+=/lightning_bolt
actions.single+=/flame_shock,moving=1,target_if=refreshable
actions.single+=/earth_shock,moving=1
# Multi target action priority list

actions.aoe=stormkeeper
actions.aoe+=/ascendance
actions.aoe+=/liquid_magma_totem
actions.aoe+=/flame_shock,if=spell_targets.chain_lightning=3&maelstrom>=20,target_if=refreshable
actions.aoe+=/earthquake_totem
actions.aoe+=/lava_burst,if=buff.lava_surge.up&spell_targets.chain_lightning=3
actions.aoe+=/lava_beam
actions.aoe+=/chain_lightning,target_if=!debuff.lightning_rod.up
actions.aoe+=/chain_lightning
actions.aoe+=/lava_burst,moving=1
actions.aoe+=/flame_shock,moving=1,target_if=refreshable
# pet apl for Primal Fire Elemental

pet=primal_fire_elemental
actions=fire_nova,if=active_enemies>2
actions+=/immolate,target_if=!ticking
actions+=/fire_blast

head=shadow_archers_helm,id=139244,bonus_id=1727
neck=breathless_choker,id=137461,bonus_id=1727,enchant=mark_of_the_hidden_satyr
shoulders=epaulets_of_deceitful_intent,id=134480,bonus_id=1727
back=cloak_of_fading_echoes,id=134405,bonus_id=1727,enchant=binding_of_intellect
chest=tunic_of_screaming_earth,id=137354,bonus_id=1727
wrists=remorseless_chain_armbands,id=137405,bonus_id=1727
hands=gloves_of_fleshshaping,id=134468,bonus_id=1727
waist=permafrost_waistband,id=137520,bonus_id=1727
legs=leggings_of_acidic_venom,id=137450,bonus_id=1727
feet=striders_of_furious_flight,id=137517,bonus_id=1727
finger1=band_of_callous_dominance,id=134528,bonus_id=1727,enchant_id=5427
finger2=seal_of_the_nazjatar_empire,id=134525,bonus_id=1727,enchant_id=5427
trinket1=oakhearts_gnarled_root,id=137306,bonus_id=1727
trinket2=naraxas_spiked_tongue,id=137349,bonus_id=1727
main_hand=the_fist_of_raden,id=128935,bonus_id=744,gem_id=137365/137272/137365,relic_id=3412/3412/3412
off_hand=the_highkeepers_ward,id=128936,ilevel=870

**Comment by Bloodmallet** [comment]
Just got a message that some characters are missing due to markdown conversion. Please be aware of this

**Comment by navv1234** [comment]
This is now incorporated, forgot to close the issue.
