### ISSUE TITLE
Raging Furystone Gorget effect NYI

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2821]
Tried a profile with [Raging Furystone Gorget](http://www.wowhead.com/item=130243/raging-furystone-gorget) equipped, but charge was still only generating 20 rage instead of 25.

**Comment by amulder87** [comment]
I tried it again with simc-703-02-win64-c0561a2.7z, but it looks like it's still only giving 20 rage when equipped. I'm using: `neck=raging_furystone_gorget,id=130243,stats=966haste_744mastery,enchant=mark_of_the_distant_army` as the line for it in gear. Does that seem right, or do I have to do anything special to add on its special effect?

**Comment by Collisionc** [comment]
Ok, I'll look into it later today.

**Comment by Collisionc** [comment]
Stupid initialization order crap. It works now.
