### ISSUE TITLE
[Windows 7 + Radeon] Program freezes on launch. 

### ISSUE THREAD

**Issue by fredz0r** [simulationcraft/simc#2824]
Title.
Run as administrator was not helping at all. Compatibility mode either.
![crash](https://cloud.githubusercontent.com/assets/22157795/18451096/080cc6f8-790c-11e6-8c8a-538fffba08e6.jpg)

Running on Windows 7 Professional 64-bit (6.1, Build 7601)

If i can be more specific tell me how.

**Comment by Collisionc** [comment]
Click on the windows start button, then "Run" and type in 
dxdiag
(press enter)
It'll take 20-30 seconds to load up, but click the button that says " Save all Information", and then upload that file here.  This will just tell me what the specs of your computer are, as well as what drivers/windows updates are installed.

In the past this has been an issue with older AMD/ATI video cards, but I need to see your full list of computer specs to find out.

**Comment by fredz0r** [comment]
[DxDiag.txt](https://github.com/simulationcraft/simc/files/468476/DxDiag.txt)

Probably AMD/ATI issue

**Comment by Collisionc** [comment]
Yeah, we use QT for the gui interface and it has been dogged by issues with radeon cards on windows 7. 

They currently have an issue open for this - https://bugreports.qt.io/browse/QTBUG-49954 - and it is marked as critical, so hopefully it'll be resolved soon. 

There's another issue that could be related - https://bugreports.qt.io/browse/QTBUG-55198 - Basically, if you have two video cards active (Your i7-4790k has a video card integrated), the internal blacklist that they use doesn't work, and it crashes on loading. 

With that being said, try these two things - 
1: Update drivers for the intel integrated graphics and the radeon
2: If that doesn't work, disable the intel HD graphics in bios or in control panel.

If one of those two doesn't work, I'll see what I can do to workaround it.

**Comment by fredz0r** [comment]
Disabled HD graphics in bios, same problem. Launch, 2sec after it freezes.

If its relevant, if i open like 3 simulationcraft.exe at same time it works somehow but i can't alt+tab or it will crash

**Comment by Collisionc** [comment]
Try this version out: 

http://downloads.simulationcraft.org/simc-703-02-win64-92671b8.7z

You'll need http://www.7-zip.org/ to extract it, but I added something that may fix it, but I can't test it as I don't have a win7 machine or a radeon card. =\

**Comment by fredz0r** [comment]
:( Same issue

**Comment by Collisionc** [comment]
http://downloads.simulationcraft.org/simc-703-02-win64-fae9ee1.7z

Attempt 2

**Comment by fredz0r** [comment]
:( Same issue

**Comment by Collisionc** [comment]
Have you disabled your antivirus and tried redownloading?

**Comment by fredz0r** [comment]
I do not use antivirus.

**Comment by Collisionc** [comment]
What was the last version that worked properly?

**Comment by fredz0r** [comment]
Ahh i don't know, i guess i never runned it before in this setup.

**Comment by fredz0r** [comment]
it seems to be fixed any how! I guess it was some windows updates that came up!

**Comment by Collisionc** [comment]
Glad to see!
