### ISSUE TITLE
Missing MIT license of rapidjson library

### ISSUE THREAD

**Issue by v3rd1shax** [simulationcraft/simc#2826]
Seems this project uses [rapidjson](https://github.com/miloyip/rapidjson) library(under simc/engine/util/rapidjson). and this lib requires MIT license.  
Any consideration of adding it?

**Comment by navv1234** [comment]
Think I added all external library licenses now in 9bbae12.

**Comment by navv1234** [comment]
I'll close this, if you have more notes on this stuff, just comment here and I'll take a look.
