### ISSUE TITLE
[Addon] String Import Error

### ISSUE THREAD

**Issue by equh** [simulationcraft/simc#2828]
Program: Simulationcraft 703-01, Addon: Simulationcraft 1.5.1
When importing the String from the Addon into Simulation if get this Error:

SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.
# SimulationCraft encountered an error!
- Category: Simulation setup error
- Error: Nothing to sim!
## All options used for simulation:

``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=0
override.bleeding=0
override.mortal_wounds=0
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Collisionc** [comment]
Can you paste what the addon shows?

**Comment by equh** [comment]
ok i got it now.. call me idiot user. I tried to paste it to the small line at the bottom..
