### ISSUE TITLE
simc fails when importing a windwalker monk on Ubuntu 14.04

### ISSUE THREAD

**Issue by naddeoa** [simulationcraft/simc#2829]
Just checked out the latest commit  on the legion-dev (at [this commit](https://github.com/simulationcraft/simc/commit/e89da213af78c5efb4948e0ece51550190afddb3)) branch and built it on Ubuntu 14.04. Using the following command:

```
simc armory=us,area-52,malsung calculate_scale_factors=1 html=output.html
```

I get this output:

```
@@Module for class javascript:; is currently not available.
SimulationCraft 703-02 for World of Warcraft 7.0.3 Live (wow build 22522, git build e89da21)
ERROR! Setup failure: Unknown option 'armory' with value 'us,area-52,malsung'
```

It seems that simc dies whenever I try to run a simulation my monk. That said, I can run simulation on my warlock just fine it seems (`simc armory=us,area-52,livelock calculate_scale_factors=1 html=output.html`)

**Comment by navv1234** [comment]
This is because you don't have an api key, and the armory html stuff we use as a fallback has probably changed some due to legion. See https://github.com/simulationcraft/simc/wiki/BattleArmoryAPI how to easily get yourself an api key, which will let you use the JSON-based blizzard endpoint, which will let you sim your char.

**Comment by naddeoa** [comment]
I do have an api key, and I keep it in `~/.simc_apikey` just like the wiki says. Also, I can confirm that simc works on my warlock, which I assume would also require an API key?

**Comment by navv1234** [comment]
Yes, but that error is for 100% certain coming from the armory fallback, so the apikey is not working for some reason.

**Comment by naddeoa** [comment]
I can give you output from a working command for my warlock. Are you saying that you need different API keys for different classes?

**Comment by navv1234** [comment]
No, one api key should be sufficient, your warlock probably still works through the fallback we use.

**Comment by navv1234** [comment]
You can do something like

```
simc debug=1 armory=us,area-52,malsung > debug.txt
```

If apikey works, you should see at the top of the debug.txt file a json file. If it's using the fallback one, it should be a bastardized version of a html output. The difference should be obvious.

EDIT: That being said, I see the issue in the html output now, I'll try to fix this in the next couple of days.

**Comment by naddeoa** [comment]
That produced some interesting output. It looks like its working to an extent. It isn't producing HTML though, it clearly needs to be converted. I'll attach the output. 
[malsung.txt](https://github.com/simulationcraft/simc/files/473316/malsung.txt)

**Comment by navv1234** [comment]
Yes, it's a bastardized version of html (our parser parsed version of it). In any case, that output only comes when the apikey-based api cannot be used. So something is wrong with the apikey.

**Comment by naddeoa** [comment]
What is the best way to test that theory? I'm still a little lost as to what I can actually do if my API key works for non monks and the other battle.net calls. Perhaps if I swap mine out with the standard one that you ship with releases?

**Comment by navv1234** [comment]
did you run the same line i pasted above for your other char, and it gives you json output (in the debug.txt file)?

**Comment by naddeoa** [comment]
It appears to be the same html/template language as my monk. Is your API key checked into source? It seems like that one should work. At least, it would tell me if I need to make a new one for sure.

**Comment by navv1234** [comment]
Have you checked from dev.battle.net that your apikey is valid, and that it's the correct one? The file should be 33 bytes long, and contain the "key" from the site.

**Comment by naddeoa** [comment]
I'm ok with posting the key here, they're pretty easy to get anyway. I'll just make a new one if someone steals it.

https://us.api.battle.net/wow/achievement/2144?locale=en_US&apikey=xxxx

That is a sample call to their api that uses my api key. It appears to work.

EDIT: removed the key after solving the issue

**Comment by navv1234** [comment]
Does `simc debug=1 apikey=vcysa57ptabb8dpaats4uyv94wccnpkx armory=us,area-52,malsung > debug.txt` get you a JSON output?

**Comment by naddeoa** [comment]
It appears to give the same feedback. This also appears, I assume over stderr:

[debug.txt](https://github.com/simulationcraft/simc/files/473382/debug.txt)

```
Module for class javascript:; is currently not available.
ERROR! Setup failure: Unknown option 'armory' with value 'us,area-52,malsung'
```

**Comment by navv1234** [comment]
Oh, I bet you did not compile with OpenSSL. So, make clean, make OPENSSL=1 optimized

Let's see if that works.

**Comment by naddeoa** [comment]
I assume that should be `make OPENSSL=1`, or is that an environmental variable

**Comment by navv1234** [comment]
Yeah, pass it to make.

**Comment by naddeoa** [comment]
That's it!

I had to `sudo apt-get install libssl-dev` for the headers, but it looks like its working now. That said, I followed the instructions in https://github.com/simulationcraft/simc/wiki/HowToBuild#command-line-interface to build, so it seems like that section should be updated with this extra information.

**Comment by navv1234** [comment]
Yeah, I'll update that, instructions were written before TLS connection was mandatory to use the json api.

**Comment by naddeoa** [comment]
Thanks a lot for your help!

I just removed the API key for safe measure, but looks like this is resolved.

**Comment by naddeoa** [comment]
BTW, without you I would have never known about the `debug=` option. Is there a wiki page where all of the CLI options are listed? I can't find a help menu in the CLI if there is one.

**Comment by navv1234** [comment]
https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface and all the subpages there.

**Comment by naddeoa** [comment]
Thanks again.

**Comment by navv1234** [comment]
It's reasonably up to date, but some newer stuff might be missing. We are slack with documentation :(

**Comment by navv1234** [comment]
I'll abuse your monk at some point to fix the fallback parsing, since your monk reliably produces the error. For some reason not all monk characters do that ..

**Comment by naddeoa** [comment]
I was thinking about that. It might be because my monk was realm transferred, race changed and name changed. I remember for a short while after doing those things I couldn't even look him up on the armory website. It might be a blizzard thing.
