### ISSUE TITLE
SimC won't start - Reporting missing DLLs

### ISSUE THREAD

**Issue by Athanasiosdk** [simulationcraft/simc#2830]
Hey! 

Sorry if I missed something extremely obvious, but I cannot make SimC work :x 

I've tried different downloads, the zips and the installer, tried running as admin, moving the folder back and forth, running in compatibility mode and so on and so forth. 
It keeps telling me that the .dll files are missing, which is weird, because I am staring right at them... Halp

Thanks in advance!
~Athan

**Comment by Collisionc** [comment]
What windows  version are you running and which dlls does it say are missing

**Comment by Athanasiosdk** [comment]
Windows10

I redownloaded it again and now I'm getting a 0xc0000906 windows error instead, which I guess means there's some larger underlying issue here

It mentioned "Qt5WebEngineWidgets"  and "Qt5Svg" before.

**Comment by Athanasiosdk** [comment]
Okay, so, sorry for my rookie mistakes, but apparently disabling Windows Defender fixes the issue - Does this mean I'd have to disable WD every time I want to Sim or can someone a lot more well-versed than me figure out something smarter?

**Comment by Collisionc** [comment]
Have you tried the newest download? 
http://downloads.simulationcraft.org/?C=M;O=D

At the top.

I made a change that may help, I was using a beta version of QT Framework (used for our gui) and I guess defender is going nuts about it for no reason. I swapped back to an older version.

**Comment by Athanasiosdk** [comment]
Alright, I tried the newest download, and it works like a charm. Whatever you did, it solved the issue. 

Thanks a lot for the quick response - Have a nice day :)!
