### ISSUE TITLE
Weapon Rank & Gold Dragons Awkward

### ISSUE THREAD

**Issue by OmarMAbbasi** [simulationcraft/simc#2831]
While 840 is a great place to put the ilvl, choosing 19 as the rank for each weapon leaves a lot of specs in an awkward spot. 

The gold dragons are designed to be the largest DPS boosts for a single rank. While a few classes result in a bigger boost by reaching for a  longer path to get a specific single gold dragon rather than taking a path that gets them two quickly, most will have 2 gold dragons at rank 19. 

Havoc, Feral, Marksman, Windwalker, and Affliction all end up exactly one point away from their next gold dragon using the "ideal" path. 

A more accurate picture of where specs are currently would be to set all the classes at 20 points. This would bring these 5 specs in line with the rest of the 2 gold dragon classes, while not impacting the rest of the other classes much (if at all).

**Comment by Collisionc** [comment]
Unfortunately we had to set the line somewhere, we had already adjusted it from 18 to 19 once. It's a massive amount of work to redo everyone again to 20. :\

We will add T19H profiles which have 25 artifact points soon.
