### ISSUE TITLE
[Balance Druid] Gear, Talents, and Traits

### ISSUE THREAD

**Issue by Kroxywuff** [simulationcraft/simc#2833]
Could someone look into the balance druid profile that you're simming?

The gear uses the 815 darkmoon trinket instead of the upgraded one. The cloak is enchanted with agility. 

Those blatant issues aside the actual gear/talents/artifact aren't properly picked. The sims from all of the boomkin theorycrafters are looking at something like this http://us.battle.net/wow/en/tool/talent-calculator#Uaa!21..122 being the best for patchwerk single target fights. Sims are also showing stellar flare and astral communion to be interchangeable with the choices in the link above.

The stat weighting also shows that haste and crit should be prioritized over the full crit build that the sims are using now. Trinkets like naraxas spiked tongue and oakheart's gnarled root sim higher than the choices used.

Simulation results also show that http://www.wowhead.com/artifact-calc/druid/balance/G1u-I7BAsDQMA0DQNBADQRA0FAFBYBQXAUGQFQ4B is a higher dps return pathway and that relic slots should try to buff scythe of the stars over anything else.

**Comment by Collisionc** [comment]
Resolved. Sims significantly higher... Feel free to post other profile ideas, as profiles are probably the most tedious aspect of simc for people who don't play the spec.
