### ISSUE TITLE
[Prot Warrior] Ignore Pain with Vengeance Calculation

### ISSUE THREAD

**Issue by Beowulfe222** [simulationcraft/simc#2834]
Ignore Pain is currently not calculating it's rage cost correctly while the Vengeance: Ignore Pain buff is active.

It may also not be calculating shield value correctly, I haven't been able to determine this.

With Vengeance: Ignore Pain active, Ignore Pain should cost 50% rage, changing the rage cost from 20-60 to 10-30. Instead, Ignore Pain is routinely using more than 30 rage even with the buff up (continually absorbing 40 - 50 rage). The buff is having no effect on overall rage cost, or at least is not lowering the maximum cost of Ignore Pain.

**Comment by Collisionc** [comment]
Yeah, I've been meaning to fix this, just haven't had time yet.
