### ISSUE TITLE
[Protection Paladin] Consecration does not provide it's buff.

### ISSUE THREAD

**Issue by Derrickster** [simulationcraft/simc#2835]
Consecration now provides a buff that enhances the use of a few spells, namely: Light of the Protector, Shield of the Righteous, and Hammer of the Righteous.

**Comment by bitfluxhound** [comment]
Not sure what you mean. Consecration being down vs up is accounted in all of those spells.

**Comment by Derrickster** [comment]
When standing in consecration Protection paladins get a buff called "consecration" having this buff increases the healing of Light of the Protector, the effects of Shield of the Righteous, and causes Hammer of the Righteous to do AoE damage. I found this out by attempting to use "actions.prot=+/hammer_of_the_righteous,if=buff.consecration.up" and the sim not running and returning the error that "buff.consecration" doesn't exist.

**Comment by scamille** [comment]
The paladin module (https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_paladin.cpp) seems to have a bool standing_in_consecration(); function, which is used in the spells you mentioned for checking if the extra bonus is up.

The whole thing not being a buff can make it a bit intransparent, but I suspect there are implementation-reasons why this was not implemented as a buff. @theckhd or @bitfluxhound may comment on this.

A simple compromise might be adding a benefit_t\* to explicitly track the % of times those spells where used while standing inside consecration vs. being outside.

**Comment by bitfluxhound** [comment]
I believe why it  was never made a buff was due to previously being a pure dmg ability, and once it got defensive benefits, those were simply baked in. And from what I remember, it didn't give buff when it was being updated.

**Comment by Derrickster** [comment]
So if I'm reading this right (I'm nowhere near a programmer) The buffed spells do currently check if you are standing in Consecration, but Consecration itself doesn't actually provide your character with a buff due to how it was previously put in to simcraft's code? I guess the follow-up question for that would be is there some way to write an if/then action so that an ability is only cast if you are standing in it? If not I personally wouldn't rate this as a major update concern as how once your rotation gets going you will almost always be in consecration unless there is movement.

**Comment by aggixx** [comment]
With the way the simulator works you will never not be standing in your consecration (unless it is inactive).
