### ISSUE TITLE
Other feral bugs

### ISSUE THREAD

**Issue by zoopercat** [simulationcraft/simc#2837]
I'm really really sorry for doing this, but we found other bugs with abilities when testing simC. We weren't able to pinpoint exactly where they are, we ran out of time. But if someone goes through and tests each ability in-game and compares it to simC, while using a rotation with ONLY that ability, they should pop up.

It's good to do a once-over post-launch anyway, right?!! So sorry. If we have time to dig into this more I will let you know.

**Comment by mrdmnd** [comment]
thanks for reporting! any idea of what direction to start looking in?

**Comment by Collisionc** [comment]
Yeah, it'd be nice to have some sort of clue, does something do too much damage, too little damage, proccing more combo points...etc.

**Comment by zoopercat** [comment]
Looks like it's ashamane's bite, doing too much dmg in SimC compared to
in-game.

**Comment by scamille** [comment]
@aggixx can you take a look?

**Comment by aggixx** [comment]
I assume you mean ashamane's frenzy not ashamane's bite? Per yellow's issue #2859. Closing this assuming its a duplicate, let me know if not.

**Comment by zoopercat** [comment]
Correct, he submitted the bug (better than I did). Yes, this should be
closed. TY.
