### ISSUE TITLE
[Warrior] - Focused Rage consumed at time MS lands

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2838]
I was testing out some ingame macros to cast FR both before and after MS and found that you can macro FR before MS and have it work like you expect, but macroing FR after MS causes the FR to be consumed without buffing MS's damage. It seems that if you cast FR after MS's cast has been scheduled but before it lands, the FR doesn't buff MS's damage but is munched anyways.

This is really only relevant for the sim since the current profile will cast FR before MS when below 3 stacks, but will cast it immediately after MS when at 3 stacks. If MS/FR are being cast in sync, this results in 0 lost time on FR's CD, since they both cast at the same timestamp. In reality, it's impossible to do this since you'll be forced to delay FR briefly after an MS cast to avoid it being consumed and doing nothing.

**Comment by Collisionc** [comment]
I'll have to do some hackery here, but I can probably make it work like that.

**Comment by Collisionc** [comment]
do you have any logs for this? Is there a certain time frame where focused rage is not consumed, such as 0.01 seconds after? Or is it only when they happen at the same moment.

**Comment by Collisionc** [comment]
Put a temporary fix in. The magic is in this expression: 
((!buff.focused_rage.react&prev_gcd.mortal_strike)|!prev_gcd.mortal_strike)

!buff.focused_rage.react is basically buff.focused_rage.down with 0.1-0.2~ seconds of human delay when the buff initially expires. This expression will make sure focused rage always has 0.1-0.2 seconds of delay after mortal strike is used, but allow it to be used freely otherwise. 

Honestly wasn't much of a dps loss, around 3-5k

**Comment by amulder87** [comment]
Nice, that works for me since it's how a player would have to play it anyways, thanks!

**Comment by amulder87** [comment]
Heya, I just opened up the sample profile and ran it again to re-test this. I'm still seeing FR being used simultaneously after MS when that conditional is in place, e.g.

```
2:18.263    mortal_strike   Fluffy_Pillow   66.2/100: 66% rage  corrupted_blood_of_zakajz, focused_rage(3), precise_strikes, battle_cry, shattered_defenses
2:18.263    focused_rage    Fluffy_Pillow   66.2/100: 66% rage  corrupted_blood_of_zakajz, focused_rage, battle_cry
2:19.263    hamstring   Fluffy_Pillow   66.2/100: 66% rage  corrupted_blood_of_zakajz, focused_rage, battle_cry
2:19.668    mortal_strike   Fluffy_Pillow   66.2/100: 66% rage  corrupted_blood_of_zakajz, focused_rage, battle_cry
2:19.668    focused_rage    Fluffy_Pillow   66.2/100: 66% rage  corrupted_blood_of_zakajz, focused_rage, battle_cry
2:21.075    colossus_smash  Fluffy_Pillow   100.0/100: 100% rage    focused_rage
2:21.075    focused_rage    Fluffy_Pillow   88.0/100: 88% rage  focused_rage(2), precise_strikes, shattered_defenses
2:22.478    focused_rage    Fluffy_Pillow   76.0/100: 76% rage  focused_rage(3), precise_strikes, shattered_defenses
2:22.484    slam    Fluffy_Pillow   76.0/100: 76% rage  focused_rage(3), precise_strikes, shattered_defenses
2:23.891    slam    Fluffy_Pillow   60.0/100: 60% rage  focused_rage(3), precise_strikes, shattered_defenses
2:25.299    mortal_strike   Fluffy_Pillow   69.2/100: 69% rage  focused_rage(3), precise_strikes, shattered_defenses
2:25.299    focused_rage    Fluffy_Pillow   48.4/100: 48% rage  focused_rage
```

**Comment by Collisionc** [comment]
Bleh, I forgot that we queue those, so if the mortal strike hasn't happened yet, then the previous gcd was not mortal strike. I'll have to do something more creative.

**Comment by Collisionc** [comment]
Ok, so what that small tweak does is make it so that there is a small 0.06~ second delay in focused rage applying the buff.  Since the action list reacts to focused rage having 3 stacks, it effectively eliminates using focused rage at the same instant as mortal strike.

**Comment by amulder87** [comment]
Will that have any odd behavior at times when you use FR immediately prior to MS? E.g. like in a macro to cast BC+FR+MS? If it delays the buff application, would those FRs not buff MS?

**Comment by amulder87** [comment]
So I looked at current after this change, and it's both doing the behavior mentioned above as well as still using FR immediately following an MS clear.

E.g. should have 2 stacks of FR, but only has 1 at the time MS is applied:

```
0:00.000    focused_rage    Fluffy_Pillow   59.8/130: 46% rage  precise_strikes, shattered_defenses, potion_of_the_old_war
0:01.000    avatar  Fluffy_Pillow   59.8/130: 46% rage  bloodlust, avatar, focused_rage, precise_strikes, shattered_defenses, potion_of_the_old_war
0:01.303    focused_rage    Fluffy_Pillow   73.0/130: 56% rage  bloodlust, avatar, focused_rage, precise_strikes, shattered_defenses, potion_of_the_old_war
0:01.306    heroic_leap Fluffy_Pillow   73.0/130: 56% rage  bloodlust, avatar, focused_rage, precise_strikes, shattered_defenses, potion_of_the_old_war
0:01.306    battle_cry  Fluffy_Pillow   73.0/130: 56% rage  bloodlust, avatar, focused_rage, precise_strikes, shattered_defenses, potion_of_the_old_war
0:01.306    hamstring   Fluffy_Pillow   73.0/130: 56% rage  bloodlust, avatar, corrupted_blood_of_zakajz, focused_rage, precise_strikes, battle_cry, shattered_defenses, potion_of_the_old_war
0:01.306    mortal_strike   Fluffy_Pillow   73.0/130: 56% rage  bloodlust, avatar, corrupted_blood_of_zakajz, focused_rage, precise_strikes, battle_cry, shattered_defenses, potion_of_the_old_war
```

Still hitting FR simultaneously following an MS use:

```
0:04.540    mortal_strike   Fluffy_Pillow   109.1/130: 84% rage bloodlust, avatar, corrupted_blood_of_zakajz, focused_rage(3), precise_strikes, battle_cry, shattered_defenses, potion_of_the_old_war
0:04.540    focused_rage    Fluffy_Pillow   109.1/130: 84% rage bloodlust, avatar, corrupted_blood_of_zakajz, battle_cry, potion_of_the_old_war
```

**Comment by Collisionc** [comment]
I hate this spell.

**Comment by amulder87** [comment]
Maybe it just isn't worth trying to fix. The sim may play optimally in a way a player couldn't replicate, but I don't think it has a very large impact(no more than 1-2% DPS). I think the last change you made to delay FR's application briefly probably has a worse impact on the accuracy than the behavior that existed before.
