### ISSUE TITLE
[Warrior] - Minor Arms T19P APL changes after FR hotfix

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2839]
Can replace the actions.execute block with:

```
actions.execute+=/mortal_strike,if=buff.battle_cry.up&buff.focused_rage.stack=3
actions.execute+=/execute,if=buff.battle_cry_deadly_calm.up
actions.execute+=/colossus_smash,if=buff.shattered_defenses.down
actions.execute+=/warbreaker,if=buff.shattered_defenses.down&rage<=30
actions.execute+=/execute
# actions.execute+=/heroic_charge,if=rage.deficit>=40&(!cooldown.heroic_leap.remains|swing.mh.remains>1.2)
#Remove the # above to run out of melee and charge back in for rage.
```

Also a minor change to BC line to try to put up SD before using BC, yields a decent gain when possible:

```
actions+=/battle_cry,if=(buff.bloodlust.up|time>=1)&!gcd.remains&(buff.shattered_defenses.up|cooldown.colossus_smash.remains&cooldown.warbreaker.remains)|target.time_to_die<=5
```

BS started being a DPS loss for some reason in execute range. MS/FR removed from rotation entirely outside of BC. I can't really explain why MS isn't worth hitting at all over execute though. It should be higher damage per rage compared to execute still, and it ought to be better to burn unspent FR stacks rather than just letting them fade in between BCs, but I couldn't find any condition where it was a dps gain to hit it.

**Comment by amulder87** [comment]
Figured out what was going on with MS below 20%. For some reason, the run_action_list,name=single is triggering even in execute range, but the only thing it tries to do is hit FR. That was keeping the FR stacks rolling between BCs even without a FR line in the execute action list and maintaining them until they could be burned inside BC. Using MS in between BC casts prevents those stacks from being carried forward to the next BC, which isn't worth doing for the ~1% extra damage per rage MS has over execute.

Changing the run single action list line to: `actions+=/run_action_list,name=single,if=target.health.pct>20` and adding `actions.execute+=/focused_rage,if=buff.focused_rage.stack<3&buff.focused_rage.remains<5&cooldown.colossus_smash.remains` to the start of the execute action list will explicitly support this behavior without it being accidental, but it's a super tiny optimization only worth .1% dps over ignoring the leftover stacks.

**Comment by adamhl8** [comment]
Thanks for the report. Everything you suggested resulted in a DPS gain except for `actions.execute+=/focused_rage,if=buff.focused_rage.stack<3&buff.focused_rage.remains<5&cooldown.colossus_smash.remains`. Adding in that line was just _barely_ a DPS loss. (About ~60 less DPS over 100K iterations)

a54f4be
