### ISSUE TITLE
Trojan Detected on simc-703-01-win64.7z

### ISSUE THREAD

**Issue by Moowalker** [simulationcraft/simc#2840]
I am not sure if its a false positive or not but my antivirus has picked up the following trojan:
Trojan:WIn32/Varpes.M!cl

at the following files:
libGLESV2.dll
Qt5Core.dll
Qt5Qml.dll
Qt5Quick.dll
Qt5WebChannel.dll
bearer\qnativewifibearer.dll
iconengines\qsvgicon.dll
imageformats\qicns.dll
imageformats\qico.dll
imageformats\qsvg.dll
position\qtposition_positionpoll.dll
position\qtposition_serialnmea.dll

**Comment by Collisionc** [comment]
It's a false positive. 

http://downloads.simulationcraft.org/?C=M;O=D

Try the top 703-02 downloads there, they shouldn't trigger your antivirus, I used a non-alpha version of QT for those.
