### ISSUE TITLE
Bug with importing char

### ISSUE THREAD

**Issue by Buffshamys** [simulationcraft/simc#2841]
Told me to open ticket and copy paste this. Hope you can help me
# Profile will be downloaded into a new tab.
# 
# Clicking Simulate will create a simc_gui.simc profile for review.
# Unable to generate profile from: http://eu.battle.net/wow/en/character/ravencrest/Buffshamys/simple
# Player Buffshamys_Active's role (spell) or spec(restoration) isn't supported yet.
# No active players in sim!

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/issues/2775

**Comment by Collisionc** [comment]
Unfortunately we just don't support healing at this time. We're a bunch of volunteers with limited time, and just so happen to not play a healer so there's not much motivation. If anyone wants to add in healing, it's certainly doable, it would just require some effort.
