### ISSUE TITLE
Warrior Fury and arms  Bug Scripts ( Addons simulationCraft with Ovale Spell Priority )

### ISSUE THREAD

**Issue by alexmr06** [simulationcraft/simc#2846]
When the glue simulation input, nothing appears on output ( Fury Warrior , similar to Arms) .

And not use the T19 Warrior addon script on SimulationCraft and when the glue on addon Oval Spell Priority.

Thank you for the future resolution of the problem.

Screen : http://www.noelshack.com/2016-37-1474110357-nouvelle-image-bitmap.png

**Comment by Collisionc** [comment]
Fixed in 703-03.

**Comment by alexmr06** [comment]
ok :D. thank you for everything.
