### ISSUE TITLE
Bag after simulation

### ISSUE THREAD

**Issue by zinkovsky** [simulationcraft/simc#2847]
Ногаживот: Unable to find consumable jade_serpent_potion for potion,name=jade_serpent_potion,if=buff.bloodlust.react|target.time_to_die<=60
Ногаживот: Unable to initialize consumable jade_serpent_potion for potion,name=jade_serpent_potion,if=buff.bloodlust.react|target.time_to_die<=60

**Comment by zinkovsky** [comment]
my role heal, but simulat dps report

**Comment by Collisionc** [comment]
see: https://github.com/simulationcraft/simc/issues/2775
