### ISSUE TITLE
Issue installing Simcraft.

### ISSUE THREAD

**Issue by tallyun** [simulationcraft/simc#2849]
I start to install it then it always stops at 10% then about five minutes later it says it's going to take three hours then stops again.
I've tried installing other things and had no issues with it but I seem to only get the problem with simcraft.

**Comment by Collisionc** [comment]
What operating system are you using, and have you installed simulationcraft previously without issues?

**Comment by tallyun** [comment]
I am using Windows 7. I've installed it before but it was a while ago.

**Comment by Collisionc** [comment]
Temporarily you can use the .7z file instead of the installer: http://downloads.simulationcraft.org/simc-703-02-win64.7z

You just need 7zip or winrar to extract it, then run simulationcraft.exe inside the folder. 

Also, try uninstalling older versions of simulationcraft if you can.
