### ISSUE TITLE
Demon Spikes cooldown is not affected by Haste

### ISSUE THREAD

**Issue by jokre33** [simulationcraft/simc#2850]
Tested by overriding the haste value of a Character to 0, 5000, and 50000 and using this APL:

```
actions=auto_attack
actions+=/demon_spikes
actions+=/felblade
actions+=/shear
```

Expected would be an Interval of <=15s, <=13s and <=6s.
Currently the Interval stays at ~15s in all three cases.

Most probable cause is that the "Vengeance Demon Hunter" hidden passive Effect 2, which is used as an indicator of wether a cooldown is hasted, is not affecting Demon Spikes.

**Comment by Collisionc** [comment]
Yeah, mortal strike had the same issue. It seems that if a spell has cooldown charges, it doesn't show up in that spell effect.

**Comment by Collisionc** [comment]
Fixed.
