### ISSUE TITLE
Versatility gems say "+250 Vers" but are actually 150

### ISSUE THREAD

**Issue by danakj** [simulationcraft/simc#2851]
Hopefully this is only a bug affecting the Gear output.

Do a sim with a +150 vers gem in it. For example:
trinket1=,id=134203,bonus_id=3397/1808/607/1512/3337,gem_id=130221

That gem is http://www.wowhead.com/item=130221/versatile-maelstrom-sapphire. Wowhead also says +250, but the item in game says it is actually +150.

The "Gear" in the sim results shows:
Three-Toed Rabbit Foot
ilevel: 850, stats: { +1233 Agi, +932 Vers }, gems: { +250 Vers }

When you hover the item, the tooltip shows the correct +150 however.

Below is a full sim that demonstrates it:
rogue="Anansie"
level=110
race=worgen
region=us
server=proudmoore
role=attack
professions=leatherworking=800/skinning=815
talents=1113222
spec=outlaw
artifact=44:0:0:0:0:1052:1:1054:1:1057:1:1060:3:1061:3:1063:2:1064:3:1065:3:1066:3:1348:1

head=,id=134440,bonus_id=1727/1502/3336
neck=,id=134498,bonus_id=1727/1808/1497/3336
shoulder=,id=133620,bonus_id=1727/1808/1502/3336,gem_id=130247
back=,id=134411,bonus_id=1726/1808/1502/3337,gem_id=130221
chest=,id=134197,bonus_id=1727/1512/3336
wrist=,id=134461,bonus_id=1727/1502/3336
hands=,id=137480,bonus_id=1727/1497/3336
waist=,id=134199,bonus_id=3397/1502/3336
legs=,id=134460,bonus_id=1727/1502/3336
feet=,id=137397,bonus_id=1727/1502/3336
finger1=,id=130230,bonus_id=3362/689/601/669,gem_id=130221
finger2=,id=134524,bonus_id=1727/1492/1813
# Rabbit

trinket1=,id=134203,bonus_id=3397/1808/607/1512/3337,gem_id=130221
# Tirathon trinket2=,id=137537,bonus_id=1727/41/1492/1813
# Six Feather
# trinket2=,id=141585,bonus_id=1497
# Darkmoon

trinket2=,id=128705,bonus_id=669
main_hand=,id=128872,bonus_id=742,relic_id=1727:1492:1813/3397:1512:3337/1727:1492:1813,gem_id=136718/141263/137365/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0
# relics are
# blood: http://www.wowhead.com/item=137412/fistful-of-eyes&bonus=1727&spec=260 (reduce energy of finishers) - from Arcway: Nal'tira
# iron: http://www.wowhead.com/item=137472/betrugs-vigor&bonus=1727&spec=260 (increase run thru damage) - from Violet Hold: Betrug
# storm: http://www.wowhead.com/item=137365/condensed-saltsea-globule&bonus=1727&spec=260 (increase run thru damage) - from Eye of Ashara: Hatecoil
# Executed before combat begins. Accepts non-harmful actions only.

actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,name=seedbattered_fish_plate
# Snapshot raid buffed stats before combat begins and pre-potting is done.

actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death,if=raid_event.adds.in>40
actions.precombat+=/roll_the_bones,if=!talent.slice_and_dice.enabled
# Executed every time the actor is available.
# Condition to continue rerolling RtB; if SnD, consider that you never have to reroll

actions=variable,name=rtb_reroll,value=!talent.slice_and_dice.enabled&(rtb_buffs<=1&!(equipped.thraxis_tricksy_treads&buff.true_bearing.up)&!((buff.curse_of_the_dreadblades.remains>3|cooldown.curse_of_the_dreadblades.remains<3)&(buff.true_bearing.up|buff.shark_infested_waters.up|buff.grand_melee.up)))
# Condition to use Saber Slash

actions+=/variable,name=ss_useable,value=(combo_points<4+talent.deeper_stratagem.enabled)
# Normal rotation

actions+=/call_action_list,name=bf
actions+=/call_action_list,name=cds
actions+=/call_action_list,name=stealth
actions+=/death_from_above,if=energy.time_to_max>2&!variable.ss_useable
actions+=/slice_and_dice,if=!variable.ss_useable&buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<(1+combo_points)*1.8
actions+=/roll_the_bones,if=!variable.ss_useable&buff.roll_the_bones.remains<target.time_to_die&(buff.roll_the_bones.remains<=3|variable.rtb_reroll)
actions+=/killing_spree,if=energy.time_to_max>5|energy<15
actions+=/call_action_list,name=build
actions+=/call_action_list,name=finish,if=!variable.ss_useable
# Blade Flurry

actions.bf=cancel_buff,name=blade_flurry,if=equipped.shivarran_symmetry&cooldown.blade_flurry.up&buff.blade_flurry.up&spell_targets.blade_flurry>=2|spell_targets.blade_flurry<2&buff.blade_flurry.up
actions.bf+=/blade_flurry,if=spell_targets.blade_flurry>=2&!buff.blade_flurry.up
# Cooldowns

actions.cds=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|buff.adrenaline_rush.up
actions.cds+=/use_item,slot=trinket2
actions.cds+=/blood_fury
actions.cds+=/berserking
actions.cds+=/arcane_torrent,if=energy.deficit>40
actions.cds+=/cannonball_barrage,if=spell_targets.cannonball_barrage>=1
actions.cds+=/adrenaline_rush,if=!buff.adrenaline_rush.up
actions.cds+=/marked_for_death,target_if=min:target.time_to_die,if=target.time_to_die<combo_points.deficit|((raid_event.adds.in>40|buff.true_bearing.remains>15)&combo_points.deficit>=4+talent.deeper_strategem.enabled+talent.anticipation.enabled)
actions.cds+=/sprint,if=equipped.thraxis_tricksy_treads&!variable.ss_useable
actions.cds+=/curse_of_the_dreadblades,if=combo_points.deficit>=4&(!talent.ghostly_strike.enabled|debuff.ghostly_strike.up)
# Condition to use stealth abilities

actions.stealth=variable,name=stealth_condition,value=(combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&!debuff.ghostly_strike.up)+buff.broadsides.up&energy>60&!buff.jolly_roger.up&!buff.hidden_blade.up&!buff.curse_of_the_dreadblades.up)
# Stealth

actions.stealth+=/ambush
actions.stealth+=/vanish,if=variable.stealth_condition
actions.stealth+=/shadowmeld,if=variable.stealth_condition
# Finishers

actions.finish=between_the_eyes,if=equipped.greenskins_waterlogged_wristcuffs&buff.shark_infested_waters.up
actions.finish+=/run_through,if=!talent.death_from_above.enabled|energy.time_to_max<cooldown.death_from_above.remains+3.5
# Builders

actions.build=ghostly_strike,if=combo_points.deficit>=1+buff.broadsides.up&!buff.curse_of_the_dreadblades.up&(debuff.ghostly_strike.remains<debuff.ghostly_strike.duration*0.3|(cooldown.curse_of_the_dreadblades.remains<3&debuff.ghostly_strike.remains<14))&(combo_points>=3|(variable.rtb_reroll&time>=10))
actions.build+=/pistol_shot,if=combo_points.deficit>=1+buff.broadsides.up&buff.opportunity.up&energy.time_to_max>2-talent.quick_draw.enabled
actions.build+=/saber_slash,if=variable.ss_useable

**Comment by Collisionc** [comment]
You're using an old version. The official release of 703-02 does not have this issue. 

![Image](http://collision.heroicstrike.org/SimulationCraft_2016-09-18_01-23-24.png)

**Comment by danakj** [comment]
Ooh thanks I was just going to come tell you my version.

**Comment by danakj** [comment]
Confirmed fixed in 703-03. Thanks!
