### ISSUE TITLE
[Prot Warrior] Ultimatum and Vengeance: Focused Rage Interaction

### ISSUE THREAD

**Issue by Beowulfe222** [simulationcraft/simc#2853]
If a prot warrior has both the Ultimatum and Vengeance: Focused Rage buffs up at the same time and uses Focused Rage, it should only consume the Ultimatum buff. The user should keep the Vengeance: Focused Rage buff.

The current SimulationCraft build will consume both buffs on Focused Rage use.

**Comment by Collisionc** [comment]
Got them both, thanks!
