### ISSUE TITLE
[Warrior] Prot Warrior Bugs

### ISSUE THREAD

**Issue by adamhl8** [simulationcraft/simc#2854]
Here's the [SimC report](https://dl.dropboxusercontent.com/u/50556991/results_html.html) I'm looking at.   For some things, I'm comparing it to this [AMR sim](http://www.askmrrobot.com/wow/simulator/report/fe7dfd739a924691aad52c76b8076273). I tried to make things as similar as possible between the two sims. Both are using the same APL, boss, etc.

What I noticed (not trying to suggest one sim is more accurate than the other, I'm just pointing out discrepancies):
- Shield Slam
  - ~25 more casts of Shield Slam in SimC
  - ~483K average damage in AMR, 331K in SimC
  - Crit 46.1% of the time in AMR, 35.4% in SimC
    - Maybe Shatter the Bones isn't being applied in SimC?
- More Devastate casts in AMR; most likely due to the decreased # of Shield Slam casts
- Neltharion's Fury damage in AMR is really low. I'm pretty sure SimC's damage is correct.
- Far too few Vengeance: Focused Rage casts in SimC.
- Scales of Earth seems to be proccing too often.
- IP uptime and cast count seems to be a bit low.
- RFDT is off.
  - In the report, RFDT is reported to have generated 0.05 rage.
  - `melee_main_hand` (which I assume is actually RFDT) generated 776 rage, only 28.65%. That's extremely low.

I'll update this as I find more.

**Comment by Collisionc** [comment]
Most of that is just action list related? The RFDT is definitely bugged, and when that grants more rage the rest will probably fall in line.

**Comment by Collisionc** [comment]
Yeah, that was silly bug from me.

Fixed here: https://github.com/simulationcraft/simc/commit/5346ef309d1c3cb877858cb9d5db176397e6996c
