### ISSUE TITLE
Assasination artifact trait "Bag of tricks" Does not show up as a source of damage.

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#2855]
I editted the "Artifact=" line to add the last trait i was missing "Bag of tricks" and noticed it doesn't show up on any of the sources of damage,

Here's a picture: http://imgur.com/a/ZH1JA let me know if you need more information.

**Comment by navv1234** [comment]
The damage is called "Poison Bomb", is it not in the report (cant tell from the image you pasted)?

**Comment by ghost** [comment]
You're right it does show up in the raw abillity summary. Just not in any of the fancy graphics!

**Comment by navv1234** [comment]
Hmm, technically I think it might make sense to actually put Poison Bomb damage under Envenom as a compound damage source. I'll see what I can do.
