### ISSUE TITLE
Simulating a DH with fight_style=LightMovement

### ISSUE THREAD

**Issue by j3rem1e** [simulationcraft/simc#2856]
simc crash with : 

```
@SimulationCraft 703-03 for World of Warcraft 7.0.3 Live (wow build 22522, git build 0b6b6a4)


Simulating... ( iterations=10000, threads=8, target_error=0.000,  max_time=450, vary_combat_length=0.20, optimal_raid=1, fight_style=LightMovement )

Assertion failed: (current_charge > 0), function start, file sim/sc_cooldown.cpp, line 348.
Abort trap: 6
```

If I add a "debug=1" into the profile, the simulation runs, without this assertion failed.

**Comment by scamille** [comment]
Can you share the input (profile) you used for the simulation?
If you are using the GUI, attach the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file.

**Comment by j3rem1e** [comment]
I use this profile : 

```
iterations=10000
target_error=0.000
optimal_raid=1

default_region=eu
default_server=hyjal

fight_style=LightMovement
html=report_aoe.html

#debug=1
armory=Yåmm
```

**Comment by navv1234** [comment]
This is fixed in a3ac15d, however it does rise the question of should interrupting an action (movement interrupting it for example) even trigger a cooldown.

**Comment by j3rem1e** [comment]
Thanks, it's working.

Probably not related, but I have this warning when I do a Simulation with a DH : "Player Yåmm has duplicate buffs named 'nemesis' with source 'Yåmm' - the end is near."

Moreover, if I launch a simulation with fight_style=HecticAddCleave, it fails with : "Assertion failed: (p() -> buff.metamorphosis -> check()), function execute, file class_modules/sc_demon_hunter.cpp, line 3724."

**Comment by navv1234** [comment]
@aggixx can take a look at those, the first one is because the same source has created two buffs of the same name on the same target (could be itself).

**Comment by aggixx** [comment]
These should both already be fixed.
