### ISSUE TITLE
Documentation for Artifact Customization

### ISSUE THREAD

**Issue by Muenze** [simulationcraft/simc#2857]
Could you provide Information about the artifact property of simc, how to customize, where to build the string.

**Comment by navv1234** [comment]
Wowhead's artifact calculator tool has a "simulationcraft" export (behind the upper right corner "link"-link). This is the format, which is artifact_id:relic0id:relic1id:relic2id:relic2id, followed by any number of powerid:rank pairs. Power ids are blizzard internal construct and not available anywhere easily.

**Comment by Muenze** [comment]
Thank you very much
