### ISSUE TITLE
Terrorbound Nexus only hits once

### ISSUE THREAD

**Issue by dfherr** [simulationcraft/simc#2858]
My simcraft executes shadow_wave of Terrorbound Nexus, but only hits the target once.

On dummy testing the shadow waves usually hit twice, once when expanding and once when coming back. This halves the actual damage of this trinket.

**Comment by aggixx** [comment]
It should hit two times, that was the intent. I also recall checking that it hit two times as many times as it had procced after I implemented it. Needs checking I guess.

**Comment by dfherr** [comment]
i reran the sim and checked the log. my bad, it hits twice.
