### ISSUE TITLE
ashamane's frenzy bleed doing too much damage

### ISSUE THREAD

**Issue by yellowsix** [simulationcraft/simc#2859]
I'm having difficulty getting Ashamane's Frenzy bleed to show the correct damage in simc (it is far too high), and I'm fairly certain it is a bug rather than a configuration issue at this point, here are details:

http://www.mmo-champion.com/threads/1967444-Legion-Feral-Discussion?p=42370977&viewfull=1#post42370977

The AMR simulator seems to be handling it exactly as the game is handling it, if you want to use that as a reference.

**Comment by aggixx** [comment]
Last you and I (or maybe it was Swol?) talked about this we basically had no idea how to get accurate numbers, so I'm not surprised its inaccurate. Guess you figured it out then? Looks like you have the bleed just as an ignite with the stack count not doing anything relevant.

**Comment by yellowsix** [comment]
Yeah at one point in beta the game was doing something very strange with this and many other accumulating DoTs. But now it has the expected behavior for an accumulating DoT that refreshes on each individual hit, and uses the "old school" refreshing rule that creates N + 1 new ticks on refresh. Sometimes the first tick happens before and sometimes after the 11th direct hit, but that nuance is safe to ignore.
