### ISSUE TITLE
Failed start of the program.

### ISSUE THREAD

**Issue by Nachsus** [simulationcraft/simc#2861]
When i try running the program it sais that "QtWebEngineWdgets.dll" is missing from my PC. And i cannot seem to find a fix.

**Comment by Collisionc** [comment]
Are you running 703-02 ?

**Comment by Nachsus** [comment]
Yes i am running that version. I also tried getting one of builds that update every few days, and the file is not missing in that but i get another error with those saying: 0xc0000906

**Comment by Collisionc** [comment]
Does it say anything else other than that? such as a file name that is giving the error, also what version of windows are you using and try disabling your antivirus temporarily to see if it works.

**Comment by Nachsus** [comment]
Hello and thank you for the help :). By your suggestion i tried disabling my antivirus but it did not do anything. However after that i attempted to disable Windows SmartScreen and now the programm launches up fine. :) 

Just to answer your question:
It did not say what file name, and i am using windows 10 with all of the current updates.

Again ty for helping.
