### ISSUE TITLE
Simulation error Nothing to Sim!

### ISSUE THREAD

**Issue by rikhalshah** [simulationcraft/simc#2863]
Hi there, could you please help me? Thank you.

SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.
# SimulationCraft encountered an error!
- Category: Simulation setup error
- Error: Nothing to sim!
## All options used for simulation:

``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by rikhalshah** [comment]
Ok now that I have learned to import a char. Everytime I simulate the simulationcraft.exe crashes.

**Comment by Collisionc** [comment]
Can you link your armory of the character?

**Comment by rikhalshah** [comment]
I think I know the issue. Armory has not updated my new character that did a faction transfer. Can't find my lvl 110 priest in armory.

**Comment by rikhalshah** [comment]
Found it on the website 

http://us.battle.net/wow/en/character/frostmourne/Paderi/simple

But if I log on to mobile armory I can't select this char

**Comment by Collisionc** [comment]
Does it crash at the very end of the simulation?

**Comment by rikhalshah** [comment]
Yes I think so. Import done. Copied the text simulate and it crashes.

**Comment by Collisionc** [comment]
Try this version: http://downloads.simulationcraft.org/simc-703-03-win64-15c616f.7z

**Comment by rikhalshah** [comment]
Ok that worked! Thank you for fixing it

**Comment by Collisionc** [comment]
Great!
