### ISSUE TITLE
About 'chaos_strike’ of DH

### ISSUE THREAD

**Issue by liyunzhi1993** [simulationcraft/simc#2865]
It's going to cause 2 damage,but only show 1 damage on SIMC.

**Comment by liyunzhi1993** [comment]
it will affect haste income

**Comment by aggixx** [comment]
It does hit two times, it just shows as one portion of the damage breakdown (some damage meters will display this differently).

**Comment by liyunzhi1993** [comment]
The screenshot of WCL shows there have 0.3s delay of the off-hand annihilation/chaos strike after the player cast spell. It means the two part of damage of one spell may gains different buffs especially like momentum.
![qq 20160921115700](https://cloud.githubusercontent.com/assets/6257587/18697310/83b50b84-7ff2-11e6-8af8-3fda3425437c.png)

**Comment by aggixx** [comment]
Everything you describe is implemented.
