### ISSUE TITLE
Import does not pull Demon Hunter talents

### ISSUE THREAD

**Issue by fonehtiks** [simulationcraft/simc#2869]
Import does not pull Demon Hunter talents. 

demonhunter="Donskoi"
origin="https://us.api.battle.net/wow/character/moon-guard/Donskoi/advanced"
thumbnail="http://us.battle.net/static-render/us/moon-guard/156/127726236-avatar.jpg"
level=110
race=night_elf
timeofday=day
role=attack
position=back
professions=alchemy=763/herbalism=782
_**talents=1133111**_ 
talent_override=fel_barrage,if=desired_targets>1|raid_event.adds.exists
artifact=3:0:0:0:0:1001:3:1002:3:1003:3:1005:3:1006:3:1010:1:1012:1:1013:1:1015:1:1330:1
spec=havoc

_**talents=1133111**_  needs to be manually added in order to obtain accurate results.

**Comment by fonehtiks** [comment]
not 100% sure how it's all structured, and super new to github :)  but it looks like demon hunter isnt in util::create_blizzard_talent_url and 

`   case DEMON_HUNTER_HAVOC:     url += "gaa"; break;
   case DEMON_HUNTER_VENGEANCE: url += "gZa"; break;`

would need to be added to sc_util.cpp and 
`case DEMON_HUNTER : c = 'g'; break;`
 to sc_player.cpp. I might be missing other areas, but still poking through :)

**Comment by fonehtiks** [comment]
Poking through the code and it looks like DH isn't included in player_t::create_talents_armory() on sc_player or util::create_blizzard_talent_url in sc_util. If I paste in an armory talent calc URL in place of 1133111 it errors out so I'm guessing DH is set up somewhere else? :)

**Comment by fonehtiks** [comment]
heres the codes:

for util::create_blizzard_talent_url()
   case DEMON_HUNTER_HAVOC:     url += "gaa"; break;
   case DEMON_HUNTER_VENGEANCE: url += "gZa"; break;

which means player_t::create_talents_armory() uses:
      case DEMON_HUNTER : c = 'g'; break;

if I'm being completely stupid with this let me know :)

**Comment by navv1234** [comment]
Thanks, this should be fixed in 9d4cb84.

**Comment by Collisionc** [comment]
http://downloads.simulationcraft.org/?C=M;O=D

Top 703-03 version will have this fix. We will release an official version in a few days.
