### ISSUE TITLE
[Shadow Priest] APL Bug/Improvement

### ISSUE THREAD

**Issue by pnmueller** [simulationcraft/simc#2870]
The current SP APL cancels mind flay early to schedule a wait event for void bolt:
actions.s2m+=/wait,sec=action.void_bolt.usable_in,if=action.void_bolt.usable|action.void_bolt.usable_in<gcd.max_0.8
[...]
actions.s2m+=/mind_flay,if=!talent.mind_spike.enabled,chain=1,interrupt_immediate=1,interrupt_if=action.void_bolt.usable_in<gcd.max_0.8

This results in a fairly significant amount of mind flay ticks being lost for no reason.

Replacing the last line with the following to only cancel if VB is actually ready improves default T19P S2M DPS over 450 seconds from ~287k to ~296k by significantly reducing the amount of early deaths (see DPS distribution):
actions.s2m+=/mind_flay,if=!talent.mind_spike.enabled,chain=1,interrupt_immediate=1,interrupt_if=action.void_bolt.usable

If you do the same change for outside of void form, i.e. replacing the line
ctions.vf+=/mind_flay,if=!talent.mind_spike.enabled,chain=1,interrupt_immediate=1,interrupt_if=action.void_bolt.usable_in<gcd.max*0.8
by the line
actions.vf+=/mind_flay,if=!talent.mind_spike.enabled,chain=1,interrupt_immediate=1,interrupt_if=action.void_bolt.usable
you can increase DPS even further to ~298k for the default S2M profile.

The latter change also increases the DPS of the default LotV profile by ~2.2k.

**Comment by PhiNikM** [comment]
Still not fixed even though it's literally changing two lines in the default APL?

**Comment by scamille** [comment]
Thanks for the improvement tips!

With Twintop gone, we unfortunately do not have a dedicated shadow developer anymore.

If you are interested in getting commit access, just send me a message. Or you can also create pull requests, which might get merged in much faster.
