### ISSUE TITLE
[Warrior] [Arms] - Corrupted Blood of Zakazj bugs

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2872]
As far as I can tell, there's 3 bugs affecting corrupted blood at the moment in SimC:

1) The buff in simc is pulling a 50% value instead of 20% for its effect. It shows as a line in the logs like:
`1.289 Test gains corrupted_blood_of_zakajz_1 ( value=0.50 )`

2)  The buff is proccing from its own ticks while it's active. Logs show, for example:
`3.313 Test corrupted_blood_of_zakajz Fluffy_Pillow: ... total_amount=237191 ...`
followed by
`3.313 Test corrupted_blood_of_zakajz residual_action delay_event_start amount=118595.500000`
adding 50% of the value of the tick back to the buff's remaining damage to tick out.

3) The buff isn't benefiting from the CS debuff, even though it mostly does in game(which is probably a WoW bug since it's an obvious case of double-dipping).

While it benefits from CS in game, it does so by snapshotting the CS debuff's damage mod whenever the buff's damage is recalculated when an attack lands. E.g. if you had 85% mastery and a 100% total CS debuff, an example scenario for the damage output would look like this:

BC begins, CS currently not active
deal 100k damage (20k banked)
deal 200k damage (60k total banked)
15k dot tick (45k banked)
CS deals 275k (100k banked, CS is _not_ modifying tick damage yet since CS wasn't active when CS's damage was dealt and the ticks were recalculated)
25k dot tick (75k banked)
deal 100k damage (95k banked, CS snapshotted)
BC ends
47.5k tick(23.75k tick doubled by CS, 71.25k banked, CS still snapshotted)
47.5k tick
CS ends
47.5k tick (damage continues to benefit from CS snapshot)
47.5k tick

If CS were to fall off in the middle of BC and another attack lands afterwards, it would clear the CS snapshot, e.g.:

BC begins, CS already active
deal 100k damage (20k banked, CS snapshotted)
deal 200k damage (60k total banked, CS snapshotted)
CS ends
30k dot tick (45k banked, CS snapshotted)
deal 100k damage (65k banked, CS no longer snapshotted)
BC ends
16.25k tick(4 ticks of the 65k remaining damage, no CS benefit)
16.25k tick
CS active again
16.25k tick (still doesn't benefit from CS since tick damage wasn't recalculated)
16.25k tick

**Comment by Collisionc** [comment]
Arms has some stupid mechanics.

**Comment by Collisionc** [comment]
Ended up being a very slight nerf to corrupted blood, but it'll probably boost the value of mastery a little more.
