### ISSUE TITLE
[Shaman] [Enhancement] Scaling masteries trinket and food issues

### ISSUE THREAD

**Issue by Poteuf** [simulationcraft/simc#2876]
1) Foods fishbrul_special and Drogbar-Style Salmon scales with mastery in simcraft but dosen't on live. Tooltips ingame are wrongs too btw.

2] On the other hand, the trinket "Tempered Egg of Serpentrix" scale on live but not in simcraft.

**Comment by Collisionc** [comment]
Fixed the #2 part, not entirely sure what's the best way with fixing #1 though.

**Comment by Collisionc** [comment]
Nevermind, didn't fix #2. @navv1234 is looking into it.

**Comment by navv1234** [comment]
2) is now fixed in da2018a.
