### ISSUE TITLE
Parser Error & simulate Crash

### ISSUE THREAD

**Issue by greyhard** [simulationcraft/simc#2877]
Not fully parsed
http://eu.battle.net/wow/ru/character/%D0%B0%D0%B7%D1%83%D1%80%D0%B5%D0%B3%D0%BE%D1%81/%D0%98%D0%BA%D1%80%D0%B8%D0%BD%D0%BA%D0%B0/advanced

And crash on simulate start

**Comment by Collisionc** [comment]
see issue: https://github.com/simulationcraft/simc/issues/2775
Healers are not currently supported. We will make sure it doesn't crash in the future, but we have no timetable on adding healers.
