### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ripoldyeller** [simulationcraft/simc#2878]
# SimulationCraft encountered an error!
- Category: Option parsing error
- Error: Unexpected parameter 'fefe#'. Expected format: name=value
## All options used for simulation:

``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
fefe# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Collisionc** [comment]
There is no character to sim?

**Comment by ripoldyeller** [comment]
I've been able to get my character to sim using the bnet import, but when
using the simc addon I get this error returned every time. I have tried
pasting the info into the simulate window or the import window. Same result
either way. Maybe I am just misunderstanding how to use the tool.Gear
equipped doesn't seem to matter. One example string the simc addon returns
is:

mage="Medinaa"
level=110
race=human
region=us
server=korgath
role=attack
professions=tailoring=776/inscription=739
talents=2122121
spec=fire
artifact=54:0:0:0:0:748:1:749:3:751:3:752:2:754:3:755:3:756:3:759:1:762:1:763:1:1340:1

head=,id=134216,bonus_id=3432/1497/1674
neck=,id=133767,bonus_id=1727/1808/1492/1813,gem_id=130215
shoulder=,id=139129,enchant_id=5882,bonus_id=3397/1512/3337
back=,id=134410,enchant_id=5433,bonus_id=1727/1497/3336
chest=,id=139751,bonus_id=3385/3384
wrist=,id=139130,bonus_id=3411/1527/3337
hands=,id=134349,bonus_id=3432/1512/3337
waist=,id=127001,bonus_id=689/1718/3408/600/669
legs=,id=126999,bonus_id=689/1683/3408/600/669
feet=,id=126996,bonus_id=689/1718/3408/600/669
finger1=,id=141546,enchant_id=5423,bonus_id=1472
finger2=,id=130229,enchant_id=5423,bonus_id=3346/689/601/669,gem_id=130219
trinket1=,id=137349,bonus_id=1726/1492/3337
trinket2=,id=128709,bonus_id=689/600/669
main_hand=,id=128820,bonus_id=730,relic_id=3397:1492:1675/1726:1502:3337/3397:1492:1675,gem_id=141261/137303/141261/0
off_hand=,id=133959,relic_id=0/0,gem_id=0/0/0/0

If it is user error I apologize, I just figured if something was going on I
would try and help identify the error by submitting a ticket.

**Comment by Collisionc** [comment]
There might be a bug that is fixed already, but not publicly released.

Try this version: http://downloads.simulationcraft.org/simc-703-03-win64-d80465b.7z

**Comment by ripoldyeller** [comment]
SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us
reproduce the issue.

# SimulationCraft encountered an error!
- Category: Simulation setup error
- Error: Nothing to sim!

## All options used for simulation:

``` ini

### Begin GUI options ###

item_db_source=local/bcpapi/wowhead

target_error=0

iterations=10000

default_world_lag=0.1

max_time=300

vary_combat_length=0.2

fight_style=Patchwerk

tmi_window_global=6

target_level+=3

target_race=Humanoid

default_skill=1.0

optimal_raid=0

override.bloodlust=1

override.bleeding=1

override.mortal_wounds=1

threads=4

process_priority=Low

statistics_level=1

### End GUI options ###

### Begin simulateText ###

# Profile will be downloaded into a new tab.

#

# Clicking Simulate will create a simc_gui.simc profile for review.


### End simulateText ###

### Begin overrides ###

# User-specified persistent global and player parameters will be set here.


### End overrides ###

### Begin final options ###

### End final options ###

### END ###

```

DPS Ranking:

293323 100.0% Raid

293323 100.0% Medinaa

HPS Ranking:

0 100.0% Raid

Player: Medinaa human mage fire 110

DPS: 293322.6 DPS-Error=278.8/0.095% DPS-Range=56486/19.3%
DPS-Convergence=59.3%

HPS: 0.0 HPS-Error=0.0/0.0%

DPR=17.3 RPS-Out=16860.6 RPS-In=16860.6 Resource=(mana) Waiting=0.0 ApM=47.5

Origin: https://us.api.battle.net/wow/character/korgath/medinaa/advanced

Talents: http://us.battle.net/wow/en/tool/talent-calculator#eZ!1011010

Artifact:
54:0:0:0:0:748:1:749:3:751:3:752:2:754:3:755:3:756:3:759:1:762:1:763:1:1340:1

Core Stats: strength=4875|4550(4550) agility=6577|6252(6252)
stamina=30494|30494(25359) intellect=30628|28921(27911) spirit=0|0(0)
health=1829640|1829640 mana=1100000|1100000

Generic Stats: mastery=15.68%|15.68%(4517) versatility=0.66%|0.66%(262)
leech=0.00%|0.00%(0)

Spell Stats: power=30628|28921(0) hit=15.00%|15.00%(0)
crit=58.58%|39.68%(10389) haste=8.38%|8.38%(2725) speed=8.38%|8.38%
manareg=16500|16500(0)

Attack Stats: power=0|0(0) hit=7.50%|7.50%(0) crit=38.58%|34.68%(10389)
expertise=7.50%|7.50%(0) haste=8.38%|8.38%(2725) speed=8.38%|8.38%

Defense Stats: armor=1610|1610(1610) miss=3.00%|3.00% dodge=3.00%|3.00%(0)
parry=0.00%|0.00%(0) block=0.00%|0.00%(0) crit=0.00%|0.00%
versatility=0.33%|0.33%(262)

Priorities (actions.precombat):

flask,type=flask_of_the_whispered_pact/food,type=the_hungry_magister

augmentation,type=defiled/snapshot_stats/mirror_image/potion,name=deadly_grace

pyroblast

Priorities:

counterspell,if=target.debuff.casting.react

time_warp,if=target.health.pct<25|time=0

shard_of_the_exodar_warp,if=buff.bloodlust.down

mirror_image,if=buff.combustion.down

rune_of_power,if=cooldown.combustion.remains>40&buff.combustion.down&(cooldown.flame_on.remains<5|cooldown.flame_on.remains>30)&!talent.kindling.enabled|target.time_to_die.remains<11|talent.kindling.enabled&(charges_fractional>1.8|time<40)&cooldown.combustion.remains>40

call_action_list,name=combustion_phase,if=cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)|buff.combustion.up

call_action_list,name=rop_phase,if=buff.rune_of_power.up&buff.combustion.down

call_action_list,name=single_target

Priorities (actions.rop_phase):

rune_of_power/pyroblast,if=buff.hot_streak.up/call_action_list,name=active_talents

pyroblast,if=buff.kaelthas_ultimate_ability.react

fire_blast,if=!prev_off_gcd.fire_blast

phoenixs_flames,if=!prev_gcd.phoenixs_flames

scorch,if=target.health.pct<=25&equipped.132454/fireball

Priorities (actions.combustion_phase):

rune_of_power,if=buff.combustion.down/call_action_list,name=active_talents

combustion/potion,name=deadly_grace/blood_fury/berserking/arcane_torrent

pyroblast,if=buff.hot_streak.up/fire_blast,if=buff.heating_up.up/phoenixs_flames

scorch,if=buff.combustion.remains>cast_time

scorch,if=target.health.pct<=25&equipped.132454

Priorities (actions.active_talents):

flame_on,if=action.fire_blast.charges=0&(cooldown.combustion.remains>40+(talent.kindling.enabled*25)|target.time_to_die.remains<cooldown.combustion.remains)

blast_wave,if=(buff.combustion.down)|(buff.combustion.up&action.fire_blast.charges<1&action.phoenixs_flames.charges<1)

meteor,if=cooldown.combustion.remains>30|(cooldown.combustion.remains>target.time_to_die)|buff.rune_of_power.up

cinderstorm,if=cooldown.combustion.remains<cast_time&(buff.rune_of_power.up|!talent.rune_on_power.enabled)|cooldown.combustion.remains>10*spell_haste&!buff.combustion.up

dragons_breath,if=equipped.132863

living_bomb,if=active_enemies>3&buff.combustion.down

Priorities (actions.single_target):

pyroblast,if=buff.hot_streak.up&buff.hot_streak.remains<action.fireball.execute_time

phoenixs_flames,if=charges_fractional>2.7&active_enemies>2

flamestrike,if=talent.flame_patch.enabled&active_enemies>2&buff.hot_streak.react

pyroblast,if=buff.hot_streak.up&!prev_gcd.pyroblast

pyroblast,if=buff.hot_streak.react&target.health.pct<=25&equipped.132454

pyroblast,if=buff.kaelthas_ultimate_ability.react

call_action_list,name=active_talents

fire_blast,if=!talent.kindling.enabled&buff.heating_up.up&(!talent.rune_of_power.enabled|charges_fractional>1.4|cooldown.combustion.remains<40)&(3-charges_fractional)_(12_spell_haste)<cooldown.combustion.remains+3|target.time_to_die.remains<4

fire_blast,if=talent.kindling.enabled&buff.heating_up.up&(!talent.rune_of_power.enabled|charges_fractional>1.5|cooldown.combustion.remains<40)&(3-charges_fractional)_(18_spell_haste)<cooldown.combustion.remains+3|target.time_to_die.remains<4

phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up|buff.incanters_flow.stack>3|talent.mirror_image.enabled)&artifact.phoenix_reborn.enabled&(4-charges_fractional)*13<cooldown.combustion.remains+5|target.time_to_die.remains<10

phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up)&(4-charges_fractional)*30<cooldown.combustion.remains+5

scorch,if=target.health.pct<=25&equipped.132454/fireball

Actions:

combustion Count= 4.3| 80.22sec DPE= 0| 0% DPET= 0 DPR= 0.0 pDPS= 0

conflagration_dot Count= 89.0| 3.18sec DPE= 2713| 0% DPET= 0 DPR= 0.0 pDPS=
804 TickCount=136 MissTick=0.0% Tick=1779|1|2382 UpTime=89.0%

conflagration_explosion Count= 30.0| 9.69sec DPE= 27224| 1% DPET= 0 DPR=
0.0 pDPS= 2721 Miss=0.00% Hit=13742|12702|19054 Crit=34600|25913|48587|64.6%

deadly_grace Count= 24.6| 4.64sec DPE=318633| 9% DPET= 0 DPR= 0.0 pDPS=
26725 Miss=0.00% Hit=139268|119709|179563 Crit=377609|239418|448909|75.3%

fire_blast Count= 34.8| 8.70sec DPE=139120| 6% DPET= 0 DPR=12.6 pDPS= 16144
Miss=0.00% Crit=139120|90688|170040|100.0%

fireball Count= 89.1| 3.19sec DPE=116615|12% DPET= 63942 DPR= 5.3 pDPS=
34622 Miss=0.00% Hit=63574|60571|90856 Crit=140824|123565|231684|68.8%

flame_on Count= 4.7| 74.64sec DPE= 0| 0% DPET= 0 DPR= 0.0 pDPS= 0

ignite Count=218.7| 1.38sec DPE=100466|25% DPET= 0 DPR= 0.0 pDPS= 73379
TickCount=299 MissTick=0.0% Tick=73490|2776|253250 UpTime=99.6%

phoenix_reborn Count= 24.9| 11.70sec DPE= 34120| 1% DPET= 0 DPR= 0.0 pDPS=
2831 Miss=0.00% Hit=17153|15877|23815 Crit=43263|32389|60729|65.0%

phoenixs_flames Count= 14.1| 21.97sec DPE=344361| 6% DPET=261561 DPR= 0.0
pDPS= 16249 Miss=0.00% Crit=344672|194333|364375|100.0%

phoenixs_flames_splash Count= 14.1| 21.97sec DPE= 0| 0% DPET= 0 DPR= 0.0
pDPS= 0

potion Count= 2.0| 0.00sec DPE= 0| 0% DPET= 0 DPR= 0.0 pDPS= 0

pyroblast Count= 80.3| 3.74sec DPE=376345|34% DPET=282803 DPR=13.5
pDPS=101124 Miss=0.00% Hit=160118|142257|213385
Crit=440229|290204|544132|75.7%

rancid_maw Count= 12.7| 23.08sec DPE=335509| 5% DPET= 0 DPR= 0.0 pDPS=
14318 Miss=0.00% Hit=171691|158320|237480 Crit=425749|316640|593701|65.1%

rune_of_power Count= 8.7| 37.75sec DPE= 0| 0% DPET= 0 DPR= 0.0 pDPS= 0

scorch Count= 0.4| 48.34sec DPE= 59688| 0% DPET= 43074 DPR= 5.4 pDPS= 72
Miss=0.00% Crit=59689|32391|60732|100.0%

unstable_magic_explosion Count= 22.3| 12.44sec DPE= 58343| 1% DPET= 0 DPR=
0.0 pDPS= 4333 Miss=0.00% Hit=58344|30285|115842

Constant Buffs:
defiled_augmentation/flask_of_the_whispered_pact/molten_armor/the_hungry_magister

Dynamic Buffs:

ace_of_hellfire : start= 2.0 refresh= 0.0 interval= 82.8 trigger= 80.9
uptime=12.51% benefit=13%

bloodlust : start= 1.0 refresh= 0.0 interval= 0.0 trigger= 0.0
uptime=13.60% benefit=20%

combustion : start= 4.3 refresh= 0.0 interval= 80.2 trigger= 80.2
uptime=14.23% benefit=68%

eight_of_hellfire : start= 2.0 refresh= 0.0 interval= 83.4 trigger= 81.2
uptime=12.62% benefit=13%

enhanced_pyrotechnics : start=21.9 refresh= 5.9 interval= 12.7 trigger=
10.0 uptime=29.49% benefit=24%

five_of_hellfire : start= 2.0 refresh= 0.0 interval= 83.4 trigger= 81.4
uptime=12.36% benefit=12%

four_of_hellfire : start= 2.0 refresh= 0.0 interval= 84.1 trigger= 81.7
uptime=12.48% benefit=13%

heating_up : start=89.7 refresh= 0.0 interval= 3.4 trigger= 3.4
uptime=37.55% benefit=47%

hot_streak : start=80.6 refresh= 0.0 interval= 3.7 trigger= 3.7
uptime=26.71% benefit=39%

potion_of_deadly_grace : start= 2.0 refresh= 0.0 interval= 78.7 trigger=
0.0 uptime=19.72% benefit=20%

pyretic_incantation : start=36.7 refresh=135.2 interval= 8.2 trigger= 1.7
uptime=76.32% benefit=82%

rune_of_power : start= 8.7 refresh= 0.0 interval= 37.8 trigger= 37.8
uptime=28.07% benefit=28%

seven_of_hellfire : start= 2.0 refresh= 0.0 interval= 83.3 trigger= 81.7
uptime=12.49% benefit=13%

six_of_hellfire : start= 2.0 refresh= 0.0 interval= 83.3 trigger= 80.9
uptime=12.55% benefit=13%

three_of_hellfire : start= 2.0 refresh= 0.0 interval= 84.5 trigger= 82.3
uptime=12.53% benefit=13%

two_of_hellfire : start= 2.0 refresh= 0.0 interval= 84.2 trigger= 82.5
uptime=12.46% benefit=12%

Up-Times:

0.0% : Mana Cap

Procs:

89.7 | 3.36sec : Heating Up generated

8.6 | 29.80sec : Heating Up removed

32.2 | 9.36sec : IB conversions of HU

80.6 | 3.73sec : Total Hot Streak procs

219.5 | 1.37sec : Hot Streak spells used

172.0 | 1.75sec : Hot Streak spell crits

1.6 | 75.48sec : Wasted Hot Streak spell crits

1.0 | 0.00sec : Direct Ignite applications

1.0 | 0.00sec : Ignites spread

Gains:

4934727.3 : mp5_regen (mana)

Waiting: 0.00%

**\* Targets ***

Target: Fluffy_Pillow humanoid enemy unknown 113

DPS: 0.0 DPS-Error=0.0/0.000% DPS-Range=0/0.0% DPS-Convergence=0.0%

HPS: 0.0 HPS-Error=0.0/0.0%

Core Stats: strength=0|0(0) agility=0|0(0) stamina=0|0(0) intellect=0|0(0)
spirit=0|0(0) health=0|70037829 mana=0|0

Generic Stats: mastery=0.00%|0.00%(0) versatility=0.00%|0.00%(0)
leech=0.00%|0.00%(0)

Spell Stats: power=0|0(0) hit=0.00%|0.00%(0) crit=0.00%|0.00%(0)
haste=0.00%|0.00%(0) speed=0.00%|0.00% manareg=0|0(0)

Attack Stats: power=0|0(0) hit=0.00%|0.00%(0) crit=5.00%|5.00%(0)
expertise=0.00%|0.00%(0) haste=0.00%|0.00%(0) speed=0.00%|0.00%

Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00% dodge=3.00%|3.00%(0)
parry=3.00%|3.00%(0) block=3.00%|3.00%(0) crit=0.00%|0.00%
versatility=0.00%|0.00%(0)

Priorities (actions.precombat):

snapshot_stats

Priorities:

Actions:

Constant Buffs: bleeding/mortal_wounds

Dynamic Buffs:

Health Decade (0 - 10) : start= 1.0 refresh= 0.0 interval= 0.0 trigger= 0.0
uptime=10.65% benefit=11%

Health Decade (10 - 20) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=12.49% benefit=12%

Health Decade (20 - 30) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=11.35% benefit=11%

Health Decade (30 - 40) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=12.09% benefit=12%

Health Decade (40 - 50) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=11.67% benefit=12%

Health Decade (50 - 60) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=10.00% benefit=10%

Health Decade (60 - 70) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime= 8.36% benefit= 8%

Health Decade (70 - 80) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime=13.30% benefit=13%

Health Decade (80 - 90) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime= 6.08% benefit= 6%

Health Decade (90 - 100) : start= 1.0 refresh= 0.0 interval= 0.0 trigger=
0.0 uptime= 4.01% benefit= 4%

Waiting: 0.00%

Waiting:

All players active 100% of the time.

Baseline Performance:

RNG Engine = sse2-sfmt

Iterations = 10003

TotalEvents = 24128814

MaxEventQueue = 55

TargetHealth = 70037829

SimSeconds = 3002319

CpuSeconds = 8.281

WallSeconds = 2.401

SpeedUp = 362544

EndTime = 2016-09-23 17:03:39-0500 (1474668219)

**Comment by Collisionc** [comment]
There's probably a really small step that you are missing, so I did a quick video of how I did your character:

http://collision.heroicstrike.org/2016-09-23_18-47-59.mp4

(Only thing to note, I clicked the reset all settings button because I had changed a lot of settings earlier.)

**Comment by ripoldyeller** [comment]
Problem solved. Thank you very much for taking the time. In case you come
across something similar, here is what was wrong: I was pasting into the
box at the bottom of the screen instead of the large text field.
