### ISSUE TITLE
[Unholy DK] Inaccurate Sims

### ISSUE THREAD

**Issue by Thepiegod** [simulationcraft/simc#2880]
No matter which version I use, when I attempt to sim my character I sim at sub 150k dps single target with an 853 ilvl.

Edit: It apparently has something to with player skill level as when I set that to elite, I sim at 266k, but at average sub 150k.

**Comment by Collisionc** [comment]
Yeah, player skill will dramatically affect the dps. Our "Average" probably needs to be set at a lower failure threshold.

**Comment by Collisionc** [comment]
Ok, adjusted the defaults in the gui so that they are a bit more realistic. Will be in the next release.
