### ISSUE TITLE
Ret Paladin using Divine Storm in single target fight

### ISSUE THREAD

**Issue by lelitha** [simulationcraft/simc#2881]
I've trawled through the action list but can't find any instance where Divine Storm should be allowed to take precedence over Templar's Verdict. Bug?

**Comment by Solrante** [comment]
Why do u want to use DS in over a ST? TV always does more damage...

**Comment by lelitha** [comment]
That's my point, I don't want to use Divine Storm but Simcraft IS using it, and I can't figure out why

**Comment by mrdmnd** [comment]
Is skill set to something other than elite?

**Comment by Collisionc** [comment]
Most likely related to the player skill setting. This will accidentally trigger spells that you don't mean to use.

**Comment by lelitha** [comment]
I had it on elite though :/
