### ISSUE TITLE
Affliction Warlock Artifact Weapon/Trait crashing program

### ISSUE THREAD

**Issue by RavyDavy** [simulationcraft/simc#2887]
So from within WoW, I use the simc addon to copy my details, and when I paste it into Simulationcraft and simulate, the program stops with a "SimulationCraft has stopped working" message, which forces me to close it.

If however I either unequip my weapon, or delete the line where the artifact traits are, or set them all to 0, then the program sims fine.

> warlock="Ravylock"
> level=110
> race=dwarf
> region=eu
> server=saurfang
> role=attack
> professions=herbalism=796/inscription=702
> talents=1211223
> spec=affliction
> artifact=39:0:0:0:0:915:3:917:3:918:3:919:3:922:3:925:1:926:1:929:1:999:1:1353:1
> 
> head=,id=139086,bonus_id=1727/1502/1813
> neck=,id=137311,enchant_id=5439,bonus_id=1727/1502/3336
> shoulder=,id=134221,bonus_id=1726/1497/3339
> back=,id=134406,enchant_id=5436,bonus_id=1726/1487/3339
> chest=,id=138215,bonus_id=1807/1472
> shirt=,id=98084
> wrist=,id=134437,bonus_id=1726/1487/3339
> hands=,id=134261,bonus_id=1727/1502/1813
> waist=,id=134171,bonus_id=1726/1512/3337
> legs=,id=134427,bonus_id=1727/40/1492/1813
> feet=,id=134176,bonus_id=3397/1808/1492/1675,gem_id=130220
> finger1=,id=134527,enchant_id=5429,bonus_id=1727/1492/1813
> finger2=,id=137438,enchant_id=5428,bonus_id=1727/1497/3336
> trinket1=,id=134292,bonus_id=3432/604/1497/1674
> trinket2=,id=139321,bonus_id=1805/1492/3336
> main_hand=,id=128942,bonus_id=747,relic_id=3397:1492:1675/1727:1502:3336/1727:1497:3336,gem_id=141254/137350/136719/0

**Comment by 4word** [comment]
I am having the same issue. For me, it crashed during the scaling steps.

With int, crit, haste, mastery, versatility all enabled for scaling on 25k iterations, it crashed twice on crit and once on haste before I commented out the artifact line. Now it gets through them just fine.

This happens on both 703-02 and nightly 703-03

**Comment by Collisionc** [comment]
Ok, got it. Thanks!
