### ISSUE TITLE
[Demon Hunter] Demon Blades not taken into account

### ISSUE THREAD

**Issue by nihilisticGoliath** [simulationcraft/simc#2892]
Hello! :)

 As the title says, I'm not seeing a way to run simulations using the Demon Blades talent. Am I missing something, or is it not available?

**Comment by aggixx** [comment]
It is implemented, make sure you have the Demon Blades talent selected in the simulation. You can see the actor's talents at the top of its section in the report.

**Comment by nihilisticGoliath** [comment]
> You can see the actor's talents at the top of its section in the report.

Thank you for responding, @aggixx .
... But I'm not seeing what talents that are being simulated. Demon Blades are not referenced in the simulation profile (though Demon's Bite is), and since I'm fetching my character from the Armory, I don't understand why that's the case.

I'm not sure what I'm doing wrong. This is what the Talent-section looks like, and, to me, none stand out as being selected;
![talents questionmark](https://cloud.githubusercontent.com/assets/22441804/19049095/4290e7f2-89a9-11e6-86ce-00fe50ebbe0d.png)
