### ISSUE TITLE
Twisting Wind overpowered

### ISSUE THREAD

**Issue by Wenoxar** [simulationcraft/simc#2893]
Hello,

I'm using the newest SimulationCraft build. 

Playing Fire mage, simulating 360s fight (6 minutes) so approximate raid fight length. Single target. 

Result? Twisting Wind ilvl 880 trinket does 8,9% of total damage done. 

Reality? Twisting Wind does around 1,5~3% of total damage done. 

Also, some logs to prove that Twisting Wind isn't any near to do 8-10% of total damage like SimCraft does:
https://www.warcraftlogs.com/reports/JNWQ17TrGMgnjKYk#fight=6&type=damage-done&source=12
https://www.warcraftlogs.com/reports/czbBfWtvx13GnyNJ#fight=12&type=damage-done&source=157
https://www.warcraftlogs.com/reports/DHY3VLXqRCf9mrQv#fight=15&type=damage-done&source=23

Is this meant to be or is it bugged? 

Thanks!

**Comment by Wenoxar** [comment]
Any opinion, please?

**Comment by skudnfroodie** [comment]
Hi,
it is fixed in the nightly builds. Please download the latest nightly build from here: http://downloads.simulationcraft.org/?C=M;O=D
