### ISSUE TITLE
SimCraft for legion crashes on startup

### ISSUE THREAD

**Issue by Ghost60175** [simulationcraft/simc#2894]
Hi,

I have downloaded and installed the new version of SimCraft on my laptop (with Windows7 x64bits).
All the installation has been made without any problem, but when I want to start SimCraft..., I have a crash. A window has been displayed (saying that SimCraft has crashed). I, of course, pressed the "Send information" button.

I remember that I already had this kind of problem, and the solution was to install a x86 version.
How can I do now? Using SimCraft is essential for me, for my gameplay, my stuff and many other things.
May you please help me to find a solution?

Best regards,

Alex

**Comment by Collisionc** [comment]
see issue https://github.com/simulationcraft/simc/issues/2864

I'm working to fix this, hopefully I can get something in soon.

**Comment by Collisionc** [comment]
As I mentioned in that issue, can you make sure windows is completely updated via windows updates?

**Comment by Ghost60175** [comment]
Hello,

yes, I've checked windows and it is correctly updated.
I have no new update to install according to Windows Update.

**Comment by Collisionc** [comment]
Ok, see if the 32 bit version works.
http://downloads.simulationcraft.org/SimcSetup-703-03-Win32.exe

**Comment by Ghost60175** [comment]
Hi,

I don't understand why this issue is closed.
It is still open for me.
Every time you sent me a new version, I tried it (when it was possible, because in many cases, the link provided was not funtionning (see below).

I sent you an message the 20th of october saying this:
    Hi,
    As promised, I tried to download your new version but I've got an error:
    Not Found
    The requested URL /simc-703-04-win64-1cf0421.7z was not found on this server.
    I think your link is no more available.

And until now, I have no reply, no news... and I find that the issue has been closes by "Collisionc".

I have sent you my DxDiag and I have made all the available updates. SimCraft is still not funtionning on my Laptop.

Best regards,

**Comment by bitfluxhound** [comment]
http://downloads.simulationcraft.org/SimcSetup-710-01-Win64.exe

**Comment by Ghost60175** [comment]
Good afternoon,

I've downloaded this new version and installed it on my laptop.
But unfortunately, I got a dramatic crash on start-up (once again).
I really don't understand where is the problem.
My last thoughts are about some libraries (especially graphic libraries maybe).
What do you use in this soft?

Best regards.
