### ISSUE TITLE
Segmentation Fault when simulating guardian druid without casting moonfire

### ISSUE THREAD

**Issue by RichoDemus** [simulationcraft/simc#2901]
I tried to build my own APL for guardian druids and noticed that Simulationcraft crashed, I managed to narrow it down to that if I remove moonfire I get a segmentation fault when I start the simulation, the following works:

```
actions=auto_attack
actions+=/moonfire
```

the following doesn't work:

```
actions=auto_attack
#actions+=/moonfire
```

please let me know if I can do anything to assist in troubleshooting this, I'm running 703-02 on windows 7

**Comment by scamille** [comment]
Can you please post the full profile you used, which crashes? See also https://github.com/simulationcraft/simc/wiki/simc_gui.simc if you are using the GUI.

I cannot get it to crash with a simple 'druid=foo spec=guardian actions=auto_attack' simulation. So it is likely some combination with gear/talents/artifacts, so we would need to know what your exact setup was.

**Comment by RichoDemus** [comment]
I'm using the command line

this is my profile in it's entirety:

```
armory=eu,Silvermoon,Richodemus
html=data/richo_druid.html
actions=auto_attack
```

and this is the output

```
@SimulationCraft 703-02 for World of Warcraft 7.0.3 Live (wow build 22522, git build 8621124)


Simulating... ( iterations=1000000, threads=4, target_error=0.200,  max_time=450, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )

sim_signal_handler: Segmentation fault! Iteration=0 Seed=15330443818559368998 TargetHealth=0
```

I'm running Xubuntu, heres my uname -a:

> Linux richo-xubuntu 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
