### ISSUE TITLE
[Hunter] Barrage hotfix

### ISSUE THREAD

**Issue by Jayezi** [simulationcraft/simc#2903]
https://github.com/simulationcraft/simc/commit/85155aa1698f735330d01897b03a6e45f1336ab4
Am I correct in reading the barrage hotfix as buffing 20% instead of nerfing it as it should? AMR and Simc are showing wildly different values after the change.

**Comment by Collisionc** [comment]
This should be resolved in latest nightly. Someone did a + instead of a -.  :)
