### ISSUE TITLE
[Demonology] Incorrect spell power value on sample profile

### ISSUE THREAD

**Issue by phranq2** [simulationcraft/simc#2904]
The sample profile used for the sims on the main results page has a Demonology Warlock with 30207 spell power buffed (+8954 from gear). However, simming any actualy Demonology Warlock will give a much lower spell power number despite having better gear than the sample profile. The sample profile then simulates with significantly higher DPS per ability than an actual character.

**Comment by YepItsEuko** [comment]
This was stated in another recent post, but this is due to the demonology's offhand having SP instead of Int. This SP is not being added into the calculation and it makes a huge difference.

**Comment by navv1234** [comment]
Fixed in 0393196.
