### ISSUE TITLE
Crashing when completing

### ISSUE THREAD

**Issue by Nidums** [simulationcraft/simc#2905]
I've tried re-installing going back to older versions however ever since I got the new silly w10 update every time I sim anything, it crashes when it goes to show me the results page.

**Comment by Collisionc** [comment]
Can you upload or copy/paste the simc_gui.simc file contents here?

**Comment by Nidums** [comment]
### Begin GUI options

item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1

### End GUI options

### Begin simulateText

druid="Nidomz"
level=110
race=night_elf
region=eu
server=ravencrest
role=attack
professions=enchanting=44/jewelcrafting=800
talents=3211322
spec=feral
artifact=58:0:0:0:0:1153:1:1154:1:1155:1:1156:1:1157:1:1158:1:1161:3:1163:3:1164:3:1165:3:1166:3:1167:3:1327:1

head=,id=134240,bonus_id=3411/1808/1517/3336,gem_id=130219
neck=,id=130239,enchant_id=5439,bonus_id=1753/689/601/669,gem_id=130219
shoulder=,id=139206,bonus_id=1807/1477/3336
back=,id=134412,enchant_id=5435,bonus_id=3411/1808/1517/3337,gem_id=130219
chest=,id=139208,bonus_id=1805/1492/3336
shirt=,id=89191
wrist=,id=139730,bonus_id=3386/3384,gem_id=130219
hands=,id=134239,bonus_id=1727/1808/1512/3336,gem_id=130219
waist=,id=133976,bonus_id=1811
legs=,id=134194,bonus_id=1727/1808/1507/3336,gem_id=130219
feet=,id=134441,bonus_id=3413/1808/1512/3336,gem_id=130219
finger1=,id=136713,enchant_id=5427,bonus_id=3360/689/600/669,gem_id=130219
finger2=,id=133637,enchant_id=5427,bonus_id=3414/1808/1507/1813,gem_id=130247
trinket1=,id=128705,bonus_id=689/601/669
trinket2=,id=133644,bonus_id=3410/42/1502/3336
main_hand=,id=128860,bonus_id=723,relic_id=3412:1502:1813/3428:1637:3336/1805:1487,gem_id=137370/140413/139263/0
off_hand=,id=128859,relic_id=0/0,gem_id=0/0/0/0

### End simulateText

### Begin overrides

# User-specified persistent global and player parameters will be set here.

### End overrides

### Begin final options

### End final options

### END

**Comment by Nidums** [comment]
The very latest as of today update fixed my issue.
