### ISSUE TITLE
Rogue Profile Question

### ISSUE THREAD

**Issue by knoxz** [simulationcraft/simc#2907]
Hi there, 
can anybody answer me what the variable "ticking" in the Assasination profile does mean?
Thanks in advance!

Cheers

**Comment by knoxz** [comment]
Also what does 
`rupture,if= talent.exsanguinate.enabled & remains - cooldown.exsanguinate.remains < (4 + cp_max_spend * 4) * 0.3 & new_duration - cooldown.exsanguinate.remains >= (4 + cp_max_spend * 4) * 0.3 + 3`

Mean. more specific what does "the reamains - cooldown.exsanguinate.remains" and "new_duration" mean?

**Comment by navv1234** [comment]
remains is the remaining duration of rupture on the target, new_duration is the rupture's new total duration if you'd refresh it.
