### ISSUE TITLE
Fire Mage - Incorrect Ability Usage

### ISSUE THREAD

**Issue by frognose** [simulationcraft/simc#2909]
I have my Global Options set to a 5 minute Patchwerk style fight, and there are several errors in the Ability Usage section of the Results:

1) ~4 counts of dragons_breath,if=equipped.132863 - I do not have this legendary item 
2) ~5 counts of flamestrike,if=talent.flame_patch.enabled&active_enemies>2&buff.hot_streak.react - I do not have the Flame Patch talent and, being a Patchwerk fight, there should never be more than one active enemy
3) ~3 counts of pyroblast,if=buff.kaelthas_ultimate_ability.react - I do not have the legendary which provides this buff, either
4) ~5 counts of living_bomb,if=active_enemies>3&buff.combustion.down - again, there should not be more than 1 active enemy
5) Several counts of using Scorch, conditional on item 132454 (another legendary I do not have) being equipped

**Comment by skudnfroodie** [comment]
Please reproduce the issue and then attach the simc_gui.simc from the simc folder.
What version of simc are you running? The official 703-3 from simulationcraft.org, a nightly build, something else?

**Comment by frognose** [comment]
My apologies for not providing adequate info the first time; I've never posted here before and didn't know what would be required.

I've been downloading the most recently uploaded build each night (from http://downloads.simulationcraft.org/?C=M;O=D). I first noticed it yesterday, but it's still occurring in today's.

I can't seem to attach the simc_gui.simc file to this post. Even if I zip it, I get a message telling me the file type isn't supported (and to try a zip file instead... >_>). I've uploaded it to an external hosting site I found on Google... Sorry for the inconvenience.

http://www.megafileupload.com/g14m/simc_gui.simc

**Comment by skudnfroodie** [comment]
The wrong usage of spells comes from the player skill option not being set on elite, https://github.com/simulationcraft/simc/wiki/Characters#skill
With APLs this complex a 10% chance to ignore the if statement is going to generate bad results.

**Comment by frognose** [comment]
Aha! Thankyou! I'll change that and stop asking silly questions, then. :)
