### ISSUE TITLE
Able to import and run from unix shell?

### ISSUE THREAD

**Issue by briancray** [simulationcraft/simc#2910]
I'd like to automate this using the shell. I see there's a unix shell app, can that be run from the shell to import and simulate? thanks

**Comment by navv1234** [comment]
https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface

**Comment by briancray** [comment]
For anyone else wondering, here's the specific configuration: https://github.com/simulationcraft/simc/wiki/Characters#importation-armory

I do have another question though, perhaps a feature request. Can we add min_level or something so we can only test 110s in our guild? Thanks!

**Comment by scamille** [comment]
We strongly recommend setting up a manual list of characters you want to sim. Besides low-level characters, there are healer/tanks which might sometimes crash as well, and which you dont want to simulate anyway.
