### ISSUE TITLE
"Simulation setup error: Nothing to sim!"

### ISSUE THREAD

**Issue by Aldonza** [simulationcraft/simc#2913]
# SimulationCraft encountered an error!
- Category: Simulation setup error
- Error: Nothing to sim!
## All options used for simulation:

``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,crit,haste,mastery,vers,leech
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

DPS Ranking:
 159470 100.0%  Raid
 159470  100.0%  Aldonza

HPS Ranking:
      0 100.0%  Raid

Player: Aldonza orc hunter marksmanship 110
  DPS: 159469.5  DPS-Error=120.9/0.076%  DPS-Range=25320/15.9%  DPS-Convergence=69.9%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=8778.3  RPS-Out=18.1 RPS-In=18.1  Resource=(focus) Waiting=5.3 ApM=36.4
  Talents: 1113121
  Artifact: 55:0:0:0:0:307:1:308:1:309:1:312:3:314:3:315:3:316:2:317:1:320:1:1337:1
  Core Stats:    strength=6234|6234(6234)  agility=20174|18809(18365)  stamina=25902|25902(22234)  intellect=6003|6003(6003)  spirit=2|2(2)  health=1554120|1554120  mana=0|0
  Generic Stats: mastery=16.97%|16.29%(6326)  versatility=6.53%|6.53%(2612)  leech=1.69%|1.69%(389)
  Spell Stats:   power=0|0(0)  hit=15.00%|15.00%(0)  crit=24.20%|24.20%(3220)  haste=14.71%|14.71%(4782)  speed=14.71%|14.71%  manareg=0|0(0)
  Attack Stats:  power=20174|18809(0)  hit=7.50%|7.50%(0)  crit=24.20%|24.20%(3220)  expertise=7.50%|7.50%(0)  haste=14.71%|14.71%(4782)  speed=14.71%|14.71%
  Defense Stats: armor=2392|2392(2392) miss=3.00%|3.00%  dodge=13.75%|12.66%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=3.26%|3.26%(2612)
  Priorities (actions.precombat):
    flask,type=flask_of_the_seventh_demon/food,type=nightborne_delicacy_platter
    summon_pet/snapshot_stats/potion,name=deadly_grace/augmentation,type=defiled
    windburst
  Priorities:
    auto_shot/use_item,name=horn_of_valor/arcane_torrent,if=focus.deficit>=30
    blood_fury/berserking/auto_shot/call_action_list,name=cooldowns/a_murder_of_crows
    barrage/piercing_shot,if=!talent.patient_sniper.enabled&focus>50
    windburst,if=active_enemies<2&buff.marking_targets.down&(debuff.vulnerability.down|debuff.vulnerability.remains<cast_time)
    windburst,if=active_enemies<2&buff.marking_targets.down&focus+cast_regen>90
    windburst,if=active_enemies<2&cooldown.sidewinders.charges=0
    arcane_shot,if=!talent.patient_sniper.enabled&active_enemies=1&debuff.vulnerability.react<3&buff.marking_targets.react&debuff.hunters_mark.down
    marked_shot,if=!talent.patient_sniper.enabled&debuff.vulnerability.react<3
    marked_shot,if=prev_off_gcd.sentinel
    sentinel,if=debuff.hunters_mark.down&buff.marking_targets.down/explosive_shot
    marked_shot,if=active_enemies>=4&cooldown.sidewinders.charges_fractional>=0.8
    sidewinders,if=active_enemies>1&debuff.hunters_mark.down&(buff.marking_targets.react|buff.trueshot.react|charges=2)
    arcane_shot,if=talent.steady_focus.enabled&active_enemies=1&(buff.steady_focus.down|buff.steady_focus.remains<2)
    multishot,if=talent.steady_focus.enabled&active_enemies>1&(buff.steady_focus.down|buff.steady_focus.remains<2)
    arcane_shot,if=talent.true_aim.enabled&active_enemies=1&(debuff.true_aim.react<1|debuff.true_aim.remains<2)
    aimed_shot,if=buff.lock_and_load.up&debuff.vulnerability.remains>gcd.max
    piercing_shot,if=talent.patient_sniper.enabled&focus>80
    marked_shot,if=!talent.sidewinders.enabled&(debuff.vulnerability.remains<2|buff.marking_targets.react)
    pool_resource,for_next=1,if=talent.sidewinders.enabled&(focus<60&cooldown.sidewinders.charges_fractional<=1.2)
    aimed_shot,if=cast_time<debuff.vulnerability.remains&(focus+cast_regen>80|debuff.hunters_mark.down)
    marked_shot/black_arrow
    sidewinders,if=debuff.hunters_mark.down&(buff.marking_targets.remains>6|buff.trueshot.react|charges=2)
    sidewinders,if=focus<30&charges<=1&recharge_time<=5
    multishot,if=spell_targets.barrage>1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
    arcane_shot,if=spell_targets.barrage=1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
    arcane_shot,if=focus.deficit<10
  Priorities (actions.cooldowns):
    potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23
    trueshot,if=(buff.bloodlust.react|target.health.pct>20+(cooldown.trueshot.remains+15))|buff.bullseye.react>25
  Actions:
    aimed_shot    Count= 88.9|  3.37sec  DPE=240747|45%  DPET=157962  DPR= 6044.0  pDPS=71368  Miss=0.00%  Hit=190515|181922|215257  Crit=400116|382036|452040|24.2%
    auto_shot     Count=115.0|  2.62sec  DPE= 24702| 6%  DPET=  9479  DPR=    0.0  pDPS= 9448  Miss=0.00%  Hit=19891|19004|22538  Crit=39777|38007|45076|24.2%
    barrage       Count= 14.3| 22.05sec  DPE=623410|19%  DPET=230155  DPR=10390.1  pDPS=29572  TickCount=226  MissTick=0.0%  Tick=31596|30220|35757  CritTick=63195|60439|71514|24.3%  UpTime=11.6%
    blood_fury    Count=  3.0|120.52sec  DPE=     0| 0%  DPET=     0  DPR=    0.0  pDPS=    0
    deadly_grace  Count= 15.3|  1.56sec  DPE= 78578| 3%  DPET=     0  DPR=    0.0  pDPS= 4060  Miss=0.00%  Hit=63348|63348|63348  Crit=126696|126696|126696|24.0%
    fel_meteor    Count= 28.4| 10.75sec  DPE= 41226| 2%  DPET=     0  DPR=    0.0  pDPS= 3893  Miss=0.00%  Hit=33198|33198|33198  Crit=66396|66396|66396|24.2%
    marked_shot   Count= 26.0| 11.42sec  DPE=235021|13%  DPET=193436  DPR= 7834.0  pDPS=20383  Miss=0.00%  Hit=189162|75549|223481  Crit=378161|151098|446963|24.3%
    sidewinders   Count= 31.5|  9.54sec  DPE=118276| 8%  DPET= 97893  DPR=    0.0  pDPS=12396  Miss=0.00%  Hit=95248|89744|110838  Crit=190584|179488|221676|24.2%
    trueshot      Count=  1.9|  0.00sec  DPE=     0| 0%  DPET=     0  DPR=    0.0  pDPS=    0
    windburst     Count= 12.7| 22.60sec  DPE=197864| 5%  DPET=156499  DPR= 9170.7  pDPS= 8349  Miss=0.00%  Hit=148141|144010|170398  Crit=296297|288020|340797|24.0%
  Constant Buffs: defiled_augmentation/flask_of_the_seventh_demon/nightborne_delicacy_platter
  Dynamic Buffs:
    blood_fury             : start= 3.0 refresh=  0.0 interval=120.5 trigger=120.5 uptime=14.76%  benefit=15%
    bloodlust              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.53%  benefit=20%
    lock_and_load          : start= 9.0 refresh=  0.2 interval= 30.7 trigger= 30.1 uptime= 5.90%  benefit= 7%
    marking_targets        : start=26.3 refresh=  8.5 interval= 11.6 trigger=  8.7 uptime=36.07%  benefit=50%
    potion_of_deadly_grace : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 7.78%  benefit= 8%
    trueshot               : start= 1.9 refresh=  0.0 interval=150.6 trigger=  0.0 uptime= 9.39%  benefit=13%
    valarjars_path         : start= 3.0 refresh=  0.0 interval=120.5 trigger=120.5 uptime=28.57%  benefit=29%
  Up-Times:
      1.8% : Focus Cap  
  Procs:
     62.0 |   3.65sec : starved: barrage
      9.2 |  30.10sec : lock_and_load
      2.5 |  54.44sec : no_vuln_aimed_shot
      1.8 |  70.36sec : no_vuln_marked_shot
     34.8 |   8.69sec : marking_targets
      8.5 |  31.60sec : wasted_marking_targets
  Gains:
      1711.6 : sidewinders (focus)  (overflow=1.2%)
      3646.0 : focus_regen (focus)  (overflow=2.4%)
  Scale Factors:
    Weights :  Agi=5.89(0.15)  AP=0.00(0.00)  Crit=3.90(0.15)  Haste=3.99(0.15)  Mastery=5.28(0.15)  Vers=3.75(0.15)  Wdps=0.00(0.00)
    Wowhead : 
  Waiting: 5.31%

 **\* Targets **\* 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|57206662  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.33%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.35%  benefit=11%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.39%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.97%  benefit=11%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.34%  benefit=10%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.96%  benefit=11%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.72%  benefit=12%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.70%  benefit=11%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 6.54%  benefit= 7%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.71%  benefit= 5%
    hunters_mark             : start=26.8 refresh=  0.0 interval= 11.2 trigger= 11.2 uptime=53.51%  benefit=49%
    vulnerability            : start=10.3 refresh= 60.9 interval= 30.0 trigger=  4.2 uptime=94.67%  benefit=92%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
     5.3% : Aldonza

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10003
  TotalEvents   = 19592146
  MaxEventQueue = 38
  TargetHealth  = 57206662
  SimSeconds    = 3011023
  CpuSeconds    = 11.716
  WallSeconds   = 3.376
  SpeedUp       = 257008
  EndTime       = 2016-09-26 15:15:13-0700 (1474928113)

Scale Factors:
  Aldonza  Agi=5.89(0.15)  AP=0.00(0.00)  Crit=3.90(0.15)  Haste=3.99(0.15)  Mastery=5.28(0.15)  Vers=3.75(0.15)  Wdps=0.00(0.00)

**Comment by Collisionc** [comment]
Just in case you are making a similar mistake that a different person did:
Make sure you are doing this:

http://collision.heroicstrike.org/2016-09-23_18-47-59.mp4

**Comment by Aldonza** [comment]
I'm not sure what was wrong, whether it was the installation or my error, but all is well now.  Thank you for your time.

**Comment by Collisionc** [comment]
No problem!
