### ISSUE TITLE
New Gear; Confusing Data

### ISSUE THREAD

**Issue by Aldonza** [simulationcraft/simc#2914]
New gear in my bags says composite score = 8738.6 with +4% upgrade, but the equipped piece has a composite score of 9185.2!  Which do I believe; the lower composite score or the "+4% upgrade"?

**Comment by scamille** [comment]
How is this SimC related?

**Comment by Aldonza** [comment]
I expect I confused SimC effects with Pawn effects.  Sorry to have 
wasted your time.
Brad

Brad Snow
s/v Aldonza
svaldonza@gmail.com

**Comment by scamille** [comment]
Yes even though SimulationCraft can generate stat weights used for Pawn (there is a pawn string exported when you create scale factors), we do not have anything to do with the InGame addon.
