### ISSUE TITLE
How to properly apply override?

### ISSUE THREAD

**Issue by ng7373** [simulationcraft/simc#2916]
I am trying to determine my new stat values for arcane, but I can't seem to get the override to work.  If i input name=97395ff9bc1030d97f348ce122d87a33575984aa in the over ride its still giving me mastery as my lower stat value which doesn't seem quite.

**Comment by navv1234** [comment]
You are trying to apply a commit id to the sim. You will need to get a nightly build from http://downloads.simulationcraft.org/?C=M;O=D (if you are on windows) to get the new changes to the program that show in the commit log.
