### ISSUE TITLE
Damaging procs not benefiting from increased damage debuffs

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2918]
As far as I've seen, all damaging effects benefit from the CS debuff in game while they currently don't in SimC. A short list of abilities that get boosted damage from CS would include:

Mark of the Hidden Satyr
Mark of the Distant Army
Potion of the Old War
Potion of Deadly Grace
Gift of Radiance's on-use spear
Spontaneous Appendages
Terrorbound Nexus
Spiked Counterweight - Both the initial damage hit and the bonus damage from the 15% increased damage buff are modified, and the damage added by CS doesn't count against the cap the buff is limited to, e.g. if the trinket said "up to 360,000 damage dealt", it could actually deal 720,000 with a 100% CS debuff up the whole time.

There's probably many more I'm missing. I think it's safe to just assume literally everything benefits.

Edit and title change: After looking at some other logs, this is likely the case with any debuff that modifies the damage the target receives. I saw the same behavior with the Ghostly Strike debuff from rogues for example.

[An example log](https://www.warcraftlogs.com/reports/KDP1fXhbBzpQ9L82#fight=3&type=damage-done&source=8&ability=228780&start=788404&end=795711&target=43) for the counterweight debuff with CS up the whole time: dealt 910.6k damage. Expected maximum for 845 ilvl trinket modified by CS from a player with 13,570 mastery: 436,636 \* (1.31 + 13570/17500) = 910,573.

[An example log](https://www.warcraftlogs.com/reports/fdz29V3RyALCc1qv#fight=5&type=damage-done&source=134&ability=228780&start=2447607&end=2461463) for the counterweight debuff with Ghostly Strike up the whole time: dealt 480.3k damage. Expected maximum for 845 ilvl trinket modified by GS: 436,636*1.1 = 480,299.

**Comment by Collisionc** [comment]
Yeah, you're right.  I've noticed this as well in game, just haven't had time to look into fixing it. 

Fun note, paladin greater blessing of might also double dips on colossus smash. Arms warriors are probably the best target for rets to bless.

**Comment by Collisionc** [comment]
Warrior was fixed here - https://github.com/simulationcraft/simc/commit/b52eb17f059bd0b62a0b85ebf6a87d59c310d6bf

Other classes were already updated, unless you notice one missing.

The spiked counterweight will require a little extra thought.

**Comment by amulder87** [comment]
War changes are looking good to me, other than the spiked counterweight vulnerability component like you mentioned. I didn't dig into mechanics of any other classes in SimC, just noticed the same behavior was applying across the board when I saw some other logs, so I'll just assume they're working well now too :)

**Comment by Collisionc** [comment]
Ok, that wasn't as bad as I thought it would be.  Let me know if anything else comes up
