### ISSUE TITLE
Crash on Holy Priest

### ISSUE THREAD

**Issue by ConnorRowe** [simulationcraft/simc#2920]
Simulating my warlock works fine, but when I try to simulate my priest, the program crashes.

Attached is my simc_gui.simc file (converted to txt so I can upload it).

[simc_gui.simc.txt](https://github.com/simulationcraft/simc/files/499330/simc_gui.simc.txt)

**Comment by skudnfroodie** [comment]
Healer and some tanks are not implemented at the moment.
https://github.com/simulationcraft/simc/issues/2775
