### ISSUE TITLE
Support for Sephuz's Secret

### ISSUE THREAD

**Issue by pwfff** [simulationcraft/simc#2922]
I got http://www.wowhead.com/item=132452/sephuzs-secret on my Unholy DK, and it procs every minute and a half from my pet's stun. The buff isn't showing up in my sim results though.

**Comment by skudnfroodie** [comment]
According to the tooltip, it only procs vom successfully applied cc. In default settings you fight against a boss in simc, so alppliing cc isn't an option - therefore the ring can't proc.
Is it ingame also procing against raid bosses?

**Comment by pwfff** [comment]
Yup. I think it's a bug, but hopefully it doesn't get fixed because it's made my opener amazing. Logs for proof: https://www.warcraftlogs.com/reports/kb6XdacJgz2NqtKW#type=auras&target=12&ability=208052

**Comment by Collisionc** [comment]
Hah, that's ridiculous. I imagine they'll fix it, but I'll see about getting it added.

**Comment by crtab** [comment]
Hey guys, also wondering about this item. Since this will be proccable off interrupts in 7.1.5, I think its a reasonable candidate for inclusion. My own concern is to compare it with Insignia of Ravenholdt in M+, so perhaps a part solution to this would be to add a target type that is stunnable - I've tried the 5 man target type, so I assume the spell details aren't coded?

**Comment by Collisionc** [comment]
Yeah, I'll add it before 7.1.5

**Comment by Collisionc** [comment]
It's slowly getting added for most specs.

**Comment by Collisionc** [comment]
Ok, added.

**Comment by Krimsun** [comment]
A Warlocks Infernal can proc the ring like the DKs pet, with Meteor Strike, which has a 1 minute cooldown. Not sure how this compares to the Doomguard, or other Grimoires even, but would be interesting to check on it, please.

**Comment by vhtr** [comment]
Im simming aoe fights for ele shaman, earthquake triggers sephuz yet the buff isnt showing up in dynamic buffs in result screen.

**Comment by navv1234** [comment]
Sephuz related stuff has been implemented in the modules as far as i know. Closing.
