### ISSUE TITLE
Paladin: 8-piece order hall set bonus not simmed 

### ISSUE THREAD

**Issue by Zoddo13** [simulationcraft/simc#2923]
Hi!

I have this SIM here:

paladin="Kladdis"
level=110
race=blood_elf
region=eu
server=nerathor
role=attack
professions=herbalism=788/jewelcrafting=777
talents=1112212
spec=retribution
artifact=2:0:0:0:0:40:1:41:3:42:3:47:3:50:3:51:3:53:3:54:1:350:1:353:1:1275:1

head=,id=139693,bonus_id=1502/3381 
neck=,id=130242,enchant_id=5439,bonus_id=1771/689/601/669,gem_id=130246
shoulder=,id=139695,bonus_id=3384
back=,id=139248,enchant_id=5431,bonus_id=1807/1472
chest=,id=139690,bonus_id=3386/3384
tabard=,id=69210
wrist=,id=139697,bonus_id=3385/3384,gem_id=130220
hands=,id=139692,enchant_id=5444,bonus_id=3385/3384
waist=,id=139696,bonus_id=3385/3384
legs=,id=139694,bonus_id=3386/3384
feet=,id=139691,bonus_id=3386/3384
finger1=,id=134542,enchant_id=5424,bonus_id=1727/1492/1813
finger2=,id=130229,enchant_id=5424,bonus_id=3349/689/601/669,gem_id=130220
trinket1=,id=140030,bonus_id=3397/42/1482
trinket2=,id=137539,bonus_id=1726/1477
main_hand=,id=120978,bonus_id=737,relic_id=1807:1472/3428:1657:3337/3432:1512:3337,gem_id=139252/140429/141276/0

It has all order hall set items equipped but the proc is not showing up.

**Comment by navv1234** [comment]
The order hall 8 piece set bonus is probably not implemented currently, @mserrano?

**Comment by Zoddo13** [comment]
I have it equiped a it proccs so it is implemented.

**Comment by navv1234** [comment]
Yes, I mean in simc.
