### ISSUE TITLE
CN character profile import issue

### ISSUE THREAD

**Issue by acmajia** [simulationcraft/simc#2924]
I am a CN server player.

When I use simc to simulate, the results always show me the wrong dps data.
(I'am a ilvl850+ ret paladin, the simulation result tells me my dps is 1300K. And when I simulate a 870+ ret paladin, the dps is 461499812261274.....)

Here is the head part of my imported profile:

> paladin="Acmajia_Active"
> origin="http://cn.battle.net/wow/en/character/熊猫酒仙/Acmajia/advanced"
> level=110
> race=human
> role=attack
> position=back
> professions=alchemy=764/blacksmithing=755
> talents=http://cn.battle.net/wow/en/tool/talent-calculator#bb!0021001
> artifact=2:0:0:0:0
> spec=retribution

Compared to the imported profile of US server character, it seems like my artifact value was failed to import.

My "armory region" has set to CN. Did I missed something more to configure in the new version? In the previous version(MoP, WoD) I just use the default setting to import and simulate.

**Comment by navv1234** [comment]
See #2933, best option is to use the Simulationcraft addon until Blizzard gives us enough data to fully import CN region characters.

**Comment by acmajia** [comment]
Thanks！
