### ISSUE TITLE
[Hunter] Steady Focus not triggered correctly

### ISSUE THREAD

**Issue by Jayezi** [simulationcraft/simc#2925]
The Steady Focus talent is not correctly being triggered after 3 Arcane Shots. Using the default apl, builds using Steady Focus spend the majority of the time spamming Arcane Shots until Steady Focus is gained. The log shows the beginning of an iteration up to the point Steady Focus is gained.
[log.txt](https://github.com/simulationcraft/simc/files/500055/log.txt)

**Comment by Collisionc** [comment]
This seems to be fixed already, unless you are using an unusual talent build ? Make sure you try the newest version - http://downloads.simulationcraft.org/simc-703-03-win64-8556408.7z

**Comment by Jayezi** [comment]
Happens still on the newest versions. Talent build is Steady Focus, Lock and Load, Sentinel, A Murder of Crows, and Trick Shot on the imported T19H profile.
![log](https://cloud.githubusercontent.com/assets/4423285/19088311/36256316-8a3b-11e6-949e-86a34d61ed3d.jpg)

**Comment by Collisionc** [comment]
Yeah, each peck from a murder of crows was canceling the buff, so it was constantly canceling it while you were spamming arcane shot.

**Comment by Collisionc** [comment]
It should be fixed in that commit though. Nightlies 703-04 will work fine.
