### ISSUE TITLE
Rogue Outlaw, Blunderbuss not benefitting from Greenskin's Waterlogged Wristcuffs legendary power.

### ISSUE THREAD

**Issue by Cakku** [simulationcraft/simc#2926]
The artifact trait Blunderbuss should benefit from all skill dmg increases for Pistol shot, including the legendary bracers Greenskin's Waterlogged Wristcuffs, but currently it doesn't seem to work as Pistol shot dmg is higher when using the legendary bracers.
Tested on build 703-3

**Comment by Collisionc** [comment]
Closing as release 703-03 will be out soon.
