### ISSUE TITLE
Devilsaur Shock-Baton incorrectly simmed.

### ISSUE THREAD

**Issue by kbrougham** [simulationcraft/simc#2927]
I only have a retribution paladin I can test this on, but I'm not sure currently how the trinket is simulated, but it doesn't seem to match how it reacts in-game.

I tried running simulations comparing Virtues blade (physical) and blade of wrath (holy damage). Virtues blade does not proc the trinket in game, and blade of wrath does. Specifically, both application and damage over time damage sources seem to be able to proc the trinket.

I'll list abilities test and whether or not the proc the trinket, as I'm not sure the "rules" that it follows. Unfortunately I can only provide my testing in the case of Retribution DPS.

**Crusader Strike (Physical):**     No
**Zeal (Physical):**                      No
**Zeal Cleave (Physical):**           No
**Judgment          (Holy)** :         No
**Blade of Justice (Physical):**     No
**Blade of Wrath (Holy):**           Yes (Both application and DoT effects)
**Divine Hammer (Holy):**          No
**Justicar's Vengeance (Holy):**  No
**Eye for an Eye (Physical):**       No
**Execution Sentence (Holy):**   Yes (On Burst damage)
**Consecration (Holy):**             Yes
**Wake of Ashes (Holy):**            Yes (Both application and DoT effects)
**Shield of Vengeance (Holy):**   No (Both immune and not-immune to blind fail)
**Blinding Light (Holy):**             No
**Holy Wrath (Holy):**                 Yes
**Greater Blessing of Might (Holy):** No
**Templar's Verdict (Holy):**       No (Echo doesn't either)
**Divine Storm (Holy):**              No (Echo doesn't either)

**Comment by Collisionc** [comment]
Simc already models most of that, except for blessing of might. Are you sure it doesnt' proc off blessing of might if someone mights you?

**Comment by Collisionc** [comment]
Ok, it should all be fixed now. I made it so blessing of might cannot proc that as well.

**Comment by kbrougham** [comment]
Are you positive of that?

I'm not exactly sure if there's a way to view an event list of all abilities happening to know where the procs are coming from, but, realistically, I don't see how it could be proccing so often in sims that don't use Blade of Wrath.

> paladin="Kairusux"
> level=110
> race=human
> region=us
> server=kelthuzad
> role=attack
> professions=mining=545/engineering=747
> talents=113**_1**_122
> spec=retribution
> artifact=2:0:0:0:0:40:1:41:3:42:3:47:3:50:3:51:3:53:3:54:1:350:1:353:1:1275:1
> 
> head=,id=139693,bonus_id=3385/3384
> neck=,id=121284,enchant_id=5439,bonus_id=3432/1502/3336
> shoulder=,id=134518,enchant_id=5881,bonus_id=1727/1492/1813
> back=,id=136977,enchant_id=5431,bonus_id=1727/1502/3336
> chest=,id=134503,bonus_id=1727/1492/1813
> shirt=,id=42378
> tabard=,id=52252
> wrist=,id=139235,bonus_id=1807/1477/3336
> hands=,id=139225,bonus_id=1807/1472
> waist=,id=139227,bonus_id=1805/1487
> legs=,id=134183,bonus_id=1726/1517/3337
> feet=,id=134273,bonus_id=3397/1512/3337
> finger1=,id=134532,enchant_id=5424,bonus_id=1727/1492/1813
> finger2=,id=134525,enchant_id=5424,bonus_id=1727/1492/1813
> trinket1=,id=140030,bonus_id=3432/1487/1674
> trinket2=,id=137539,bonus_id=1726/1482/3339
> main_hand=,id=120978,bonus_id=737,relic_id=3432:1502:3336/1807:1477:3336/3397:1492:1675,gem_id=141260/139256/141260/0

This is the profile I'm simulating with. I'm using simc-703-03-win64-147ac41.7z which was released 2016-10-04 19:40, and is the newest version available on the nightly downloads page.

I ran two simulations, the only difference being the bolded 1, changing virtue's blade to blade of wrath.

Virtue's Blade: http://i.imgur.com/Blj6bVi.png

Blade of Wrath: http://i.imgur.com/QBkk3ko.png

In both cases, there is an interval of approximately 12 seconds. While this isn't an issue with blade of wrath, there is no way that virtue's blade should be triggering this often. The only ability that would even trigger it is wake of ashes, which is on a 30 second cooldown (Or 24, if you go from the end of the DoT effect).

On my testing in game, I'm getting around 1/3rd the amount of procs on a dummy while utilizing virtue's blade, so something is definitely not working properly. If the greater blessing change is not currently in effect that could possibly cause the discrepancy.

**Comment by Collisionc** [comment]
Looks like judgment is still proccing it somehow, I'll get it fixed.

**Comment by Collisionc** [comment]
Do you know if the aoe component of judgment can proc it ?

**Comment by kbrougham** [comment]
It doesn't look like it does, no.

**Comment by kbrougham** [comment]
Because I just realized I never tested:

Templar's Verdict
Divine Storm
And Echo for either of them also do not proc the baton

**Comment by Collisionc** [comment]
Hopefully that cleans it up. It'll be in the next release.
