### ISSUE TITLE
Ignore pain not calculating correctly

### ISSUE THREAD

**Issue by jpm0511** [simulationcraft/simc#2928]
I am simulating using the prot warrior Clutch from US-Area 52 as my reference, using the default action list. In the simulation results ignore pain is averaging around 170k per cast with roughly 11% uptime. Looking at logs from mythic ursoc Clutch's ignore pains average around 938k per cast with roughly 50% uptime. Something seems off.

**Comment by Collisionc** [comment]
What version are you using?

**Comment by jpm0511** [comment]
7.03 release 2, the one that's currently on the website. Is there a newer one?

**Comment by Collisionc** [comment]
Yeah, there are new unofficial updates every day or so.

http://downloads.simulationcraft.org/?C=M;O=D

The top downloads there will be the newest version.  Prot warrior is still a work in progress, but it should be a lot better in that version.

**Comment by jpm0511** [comment]
ok, I'll try that out, thanks!
