### ISSUE TITLE
Stuck at 0%

### ISSUE THREAD

**Issue by ngniech** [simulationcraft/simc#2930]
New to SimC but every time after I load in my character and try and click simulate it is stuck at 0% and never moves.  Even changed iterations to 1 and still nothing, just 0/1.  Is there something else needed in order to get this working?

Tried running as administrator and setting to windows 7 compatibility already.

Forgot to mention that for 1 iteration my cpu is being used at about 30% for SimC and for 50k iterations it is being used at near 100%. i5 4690k cpu. So it is doing something, but just being stuck at 0% progress for a long time.

Another thing I noticed is that it works for my 100 alts and my gf's 110 character.  The only it doesnt work for is the only one I want to use the thing for which is frustrating.  The character is Åthena-Turalyon

**Comment by ngniech** [comment]
Forgot to mention that for 1 iteration my cpu is being used at about 30% for SimC and for 50k iterations it is being used at near 100%.  i5 4690k cpu.  So it is doing something, but just being stuck at 0% progress for a long time.

**Comment by Collisionc** [comment]
Unfortunately healers are not supported at the moment. See: https://github.com/simulationcraft/simc/issues/2775

We have made changes to the simulator to ensure that it just ends the simulation instead of doing this, and it will be in the next release.

**Comment by ngniech** [comment]
So its not that healers arent supported because I can run it against other healers and yeah stuff doesnt really show up but it runs.  Try on Ptah on Turalyon or any healer.  It will run.  But for some reason Åthena wont run and the CPU gets stuck in a loop.  Is it because the alt code in the front of the name?

**Comment by Collisionc** [comment]
It's an issue specific to druid healer, then. The results from all healer simulations are not accurate whatsoever. :(
