### ISSUE TITLE
 The Wildshaper's Clutch Legendary

### ISSUE THREAD

**Issue by lukeyboy89** [simulationcraft/simc#2931]
It looks like this legendary is not implemented into simc core since I tried to play around with it in the APL but it looks like there is no support. Could you please add it?

**Comment by aethys256** [comment]
Looks like it is in the Feral Module :
https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_druid.cpp#L2333

But yeah the default APL don't have it and I'm not sure how I would add it, you might want to check with @aggixx ^^ (Or maybe someone else ?)

**Comment by aggixx** [comment]
It is implemented. You can conditionalize stuff for it in the apl using the expression "equipped.the_wildshapers_clutch".
