### ISSUE TITLE
[Chinese Servers] Inflated stats when importing from armory.

### ISSUE THREAD

**Issue by slayerxj** [simulationcraft/simc#2933]
The simulating result shows the DPS of my character is more than a million.
The text is as below:

> DPS Ranking:
> 1009754 100.0%  Raid
> 1009754  100.0%  Avaron_Active
> 
> HPS Ranking:
>       0 100.0%  Raid
> 
> Player: Avaron_Active human paladin retribution 110
>   DPS: **1009754.0**  DPS-Error=653.5/0.065%  DPS-Range=115849/11.5%  DPS-Convergence=70.9%
>   HPS: 0.0 HPS-Error=0.0/0.0%
> 
>   Origin: http://cn.battle.net/wow/en/character/铜龙军团/Avaron/advanced
>   Talents: http://cn.battle.net/wow/en/tool/talent-calculator#bb!0001110
>   Artifact: 2:0:0:0:0
>   Core Stats:    strength=27755|26048(25321)  agility=3200|3200(3200)  stamina=28046|28046(28046)  intellect=7328|7328(7328)  spirit=0|0(0)  health=1682760|1682760  mana=220000|220000
>   Generic Stats: mastery=256.49%|256.49%(57046)  versatility=3.84%|3.84%(1534)  leech=0.00%|0.00%(0)
>   Spell Stats:   power=27755|26048(0)  hit=15.00%|15.00%(0)  crit=153.58%|153.58%(52003)  haste=19.43%|18.25%(5932)  speed=19.43%|18.25%  manareg=0|0(0)
>   Attack Stats:  power=27755|26048(0)  hit=7.50%|7.50%(0)  crit=153.58%|153.58%(52003)  expertise=7.50%|7.50%(0)  haste=19.43%|18.25%(5932)  speed=19.43%|18.25%
>   Defense Stats: armor=3981|3981(3981) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=18.22%|17.11%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=1.92%|1.92%(1534)

I thought it's obviously incorrect. Or I misunderstand the result?
I've run on stable and nightly version. If you need to reproduce this phenomenon, you can just import my character to have a try.

**Comment by aggixx** [comment]
Your crit and mastery is inflated somehow, likely SimC is being fed bad info by wowhead or armory or something about how much stats an item has. Can't reproduce though because it seems you're in different gear in your prot spec right now.

**Comment by navv1234** [comment]
I fixed an issue that causes the inflation in 23fad78, however the problem is that CN region does not get access to enough information from armory to simulate chars. If you want to simulate yourself, you should use the Simulationcraft addon on curse.com.
