### ISSUE TITLE
Cannot see the results after the sim

### ISSUE THREAD

**Issue by OneOfA11** [simulationcraft/simc#2936]
Hello,
I have installed the latest version of Simcraft and everything was fine but last night when I tried to sim my char I was surprised. I can start the program even I can start the simulation but at the end I cannot see the result in the program. I can find the result in the program directory from simc_report but I want to make more simulations and compare each other. 
You can see what happens when the simulation ends:
![screenshot_15](https://cloud.githubusercontent.com/assets/22553655/19010595/9ccd9640-878b-11e6-9376-0efb5c177874.png)

Best regards,
Alex

**Comment by Collisionc** [comment]
What windows version are you running ? Also, try this version - http://downloads.simulationcraft.org/simc-703-03-win64-dc8362c.7z - and see if your issue is fixed already.

**Comment by Collisionc** [comment]
Try both of these downloads to see if one of them work:

http://downloads.simulationcraft.org/simc-703-03-win64-8556408.7z
http://downloads.simulationcraft.org/simc-703-03-win32-8556408.7z

**Comment by OneOfA11** [comment]
I am using Windows 10 x64.
Both versions giving the same result as before.
Could you please tell me how to remove completely SimCraft from my PC because when I extract version 03 I see the same settings as v02

**Comment by Collisionc** [comment]
That's how it should work, the settings carry over between versions. 

If you click the button that says "Reset all settings" in the program  it will clear out everything.

**Comment by OneOfA11** [comment]
Thanks for the fast reply.
I reset the settings with this button and now when I start the exe file I receive "We have reset your configuration settings due to major changes to the GUI" and then I receive the same window with the error message from my first reply. Now I cannot start the program. :/

**Comment by OneOfA11** [comment]
Ok, now 32bit version is working. Interesting.

**Comment by Collisionc** [comment]
Good to know. I will release 32 bit versions from now on, as it seems there is a problem with the 64 bit on some rare computers.
