### ISSUE TITLE
Spontaneous appendages, enhancement shaman

### ISSUE THREAD

**Issue by Delerp** [simulationcraft/simc#2937]
Spontaneous appendages trinket currently procs stormbringer for enh shamans, this could be a bug though in the game, i assume this is not accounted for in the sims at the moment.

Simulationcraft also reports that the damage hit of spontaneous appendages is about half of what ingame(simcraft : ~7k-~15k, in game : ~15k-~30k per hit on a ilvl 850 spontaneous appendages)

**Comment by navv1234** [comment]
The damage should be fixed (was affected by armor), the Enhancement thing i'll fix at some point I guess.

**Comment by navv1234** [comment]
The Stormbringer part fixed in 804a05d2bd811e8919dd196db0291b3b136012a8.

**Comment by amulder87** [comment]
It looks like being modified by armor is fixed now, but the proc doesn't yet scale with the ilvl of the trinket. It seems to use 10425 as the base average proc damage whether the trinket is set to LFR or Mythic.

**Comment by Delerp** [comment]
I noticed this too, the damage is way too low in simcraft, but stormbringer version is probably not up yet as nightly i assume.

**Comment by navv1234** [comment]
Yeah, it's currently using player level to scale the damage, I'll fix that.

EDIT: 8f61552 should enable ilevel based scaling on the base damage. The shaman version was also mitigated by armor, which also got fixed.

**Comment by Collisionc** [comment]
http://downloads.simulationcraft.org/simc-703-03-win64-dc8362c.7z and the official 703-03 release (whenever we do that) have working versions of this.
