### ISSUE TITLE
Different outcome from GUI and CLI

### ISSUE THREAD

**Issue by RichoDemus** [simulationcraft/simc#2938]
I'm getting different outcomes when simming this file: [gist](https://gist.github.com/RichoDemus/633fc64dcd8d8ef2732bbd7faff71000)

I created it by just importing my character in the GUI and simulating, and then it looks fine.

however if I load it in the CLI only brambles is counted as healing

Here are the pictures of the graphs:
![healing_cli](https://cloud.githubusercontent.com/assets/1078462/19017600/f2b82d68-883f-11e6-9006-a4722dfc71e8.png)
![healing_gui](https://cloud.githubusercontent.com/assets/1078462/19017599/f2b72b48-883f-11e6-942c-67551be4fa6f.png)

and here are the outcomes:

[results_cli.txt](https://github.com/simulationcraft/simc/files/504704/results_cli.txt)
[results_gui.txt](https://github.com/simulationcraft/simc/files/504705/results_gui.txt)

After having looked at the results it seems like both actually count the healing, so the matter is probably more of why the CLI doesn't generate the pie chart correctly
I'm running 703-02

**Comment by Collisionc** [comment]
The gui may have a different default setting (Probably somewhere in statistics) than the CLI, as they are identical otherwise. I'll look into it.

**Comment by Collisionc** [comment]
Yeah, looks like CLI was defaulting to 450 seconds, while the gui was changed to 300. I matched the CLI to be 300 in this commit - https://github.com/simulationcraft/simc/commit/d2aefb067f35e55dc273a417510c2a52c8236ac6
