### ISSUE TITLE
SimulationCraft Crash

### ISSUE THREAD

**Issue by Baege** [simulationcraft/simc#2941]
Hello,

After a forced update from Windows 10, Simcraft no longer functions. When I hit simulate, it runs for a couple of seconds and then crashes, searches for a solution, fails, and closes. The error file lists 

> C:\Simulationcraft(x64)\703-02\resources\qtwebengine_devtools_resources.pak
> Some features may not be available.
> [1002/111211:ERROR:resource_bundle.cc(720)] Failed to load C:\Simulationcraft(x64)\703-02\resources\qtwebengine_devtools_resources.pak
> Some features may not be available.
> [1002/111211:ERROR:resource_bundle.cc(720)] Failed to load C:\Simulationcraft(x64)\703-02\resources\qtwebengine_devtools_resources.pak
> Some features may not be available.
> [1002/111211:ERROR:resource_bundle.cc(720)]

over and over again. Tried reinstalling. Any help would be appreciated.

**Comment by Collisionc** [comment]
Hrm. Thanks for that error file, that may help me fix another thing...

**Comment by Collisionc** [comment]
Looks like that's a file that was added in QT 5.7, but doesn't exist in QT 5.6. For the next release version (703-03) we're going back to QT 5.6 to hopefully fix some of these crashing issues that we cannot reproduce locally. 

Try this download -http://downloads.simulationcraft.org/simc-703-03-win64-804a05d.7z

**Comment by Collisionc** [comment]
Try both of these downloads to see if one of them work:

http://downloads.simulationcraft.org/simc-703-03-win64-8556408.7z
http://downloads.simulationcraft.org/simc-703-03-win32-8556408.7z

**Comment by Baege** [comment]
Hello,

Thanks for your responses. Sorry for not following up sooner; a couple of hours after starting this thread, while trying to find a solution, I went in looking for an older version and ended up finding the 703-03 files and downloaded them and the win32 worked, while the win64 did not.

**Comment by Collisionc** [comment]
Try the newer versions that I linked above, it's great if the 32 bit works, but it'd be worth trying 64 again.
