### ISSUE TITLE
Simcraft crashing when I change region to EU.

### ISSUE THREAD

**Issue by leicaaaaa** [simulationcraft/simc#2942]
Stops working right away whenever I switch regions, if I manually paste in my armory link it will also crash, same for the string from the addon.

What gives?

Edit: Also happens when I simulate preset profiles, so it's just simcraft in general.

**Comment by Collisionc** [comment]
What version are you running ? If it's not 703-03, try this - http://downloads.simulationcraft.org/simc-703-03-win64-804a05d.7z

**Comment by leicaaaaa** [comment]
Sadly that version did not work either, maybe it's an issue on my end.

Pre-Legion I had no issues though so I'm not sure.

**Comment by Collisionc** [comment]
What windows version do you have? Make sure to do the following as well: 
1: Update windows
2: Update Video card drivers (The browser inside the gui uses your gpu to accelerate some things)

**Comment by Collisionc** [comment]
Try both of these downloads to see if one of them work:

http://downloads.simulationcraft.org/simc-703-03-win64-8556408.7z
http://downloads.simulationcraft.org/simc-703-03-win32-8556408.7z

**Comment by leicaaaaa** [comment]
Both of those worked.

Thank you.

To answer your previous questions:

GPU driver was up to date, using Windows 8.1, updated as much as possible afaik.

**Comment by Collisionc** [comment]
Great!
