### ISSUE TITLE
Storm Tempest Legendary - Enhancement Shaman

### ISSUE THREAD

**Issue by aycheff** [simulationcraft/simc#2943]
Simming the Storm Tempest legendary waist for Enhancement Shaman is currently giving a damage value on single target patchwerk simulation. The legendary states the following, "Enemies hit by your Stormstrike become lightning charged for 15 sec, zapping a nearby enemy every 1 sec for 15,509 damage.". So it should return no damage recorded in simulation results.

**Comment by Collisionc** [comment]
Any logs to show this? Not that I don't believe you, I just don't have the legendary to test. :)  The wording does make it seem like it shouldn't work on single target, but blizzard has done odd things in the past.

**Comment by aycheff** [comment]
Sure. My apologizes, I should've uploaded it with the OP. 

This SS shows the belt equipped.
http://puu.sh/rx1zp/34c2bf36b4.jpg

Here is the log.
https://www.warcraftlogs.com/reports/yCKHDTq7Ra382rfk/#type=damage-done&source=1
