### ISSUE TITLE
Demon Hunter Fel Blade

### ISSUE THREAD

**Issue by Auluras** [simulationcraft/simc#2945]
I was speced for Fel Blade, Ran the Simulation. it never once used the ability, it had damage for all my other abilities but never once used Fel Blade

**Comment by scamille** [comment]
Did you check if it was in the action priority list you used to simulate your character? The actions you use are part of the input you specify when simulating a character.

If this is still a problem, please provide the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file, generated when you do that simulation.

**Comment by Zarania** [comment]
No response, Felblade is being used by the APL.
