### ISSUE TITLE
Slam should be better for warriors

### ISSUE THREAD

**Issue by vbezhenar** [simulationcraft/simc#2946]
According to my calculations, Slam should be better than FR ability in most circumstances after recent FR nerf, because its damage/rage ratio higher even with SD buff. I'm not sure how to make a best rotation. The following change did +5k DPS for my character:

```
-actions.single+=/slam,if=buff.battle_cry_deadly_calm.up|buff.focused_rage.stack=3|rage.deficit<=30
+actions.single+=/slam
```

I don't know for what gear I should test rotations, I just used mine. I also checked with Warrior_Arms_T19H, increase was 3.5k (380k -> 383,5k).

**Comment by Collisionc** [comment]
Sorry, been fairly busy lately, I'll look into this.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/d4100e9748b53e2ebc44cf5fa6b63373475505de

Done, thanks.
