### ISSUE TITLE
[Ret Paladin] Consecration

### ISSUE THREAD

**Issue by Jazzer360** [simulationcraft/simc#2947]
I've been doing some sims with consecration, and I'm getting inconsistent results in game.

In game:
Regardless of haste levels, I'm getting 12 ticks per consecration in game. I've tested on a dummy with 89% haste, and it's always 12 ticks of consecration (over a shorter period).

In the simulator:
When I run a sim with the output logged, I've seen as many as 27 ticks (during bloodlust).

Haste is currently only shortening the time between ticks as well as lowering the cooldown on consecration.

Edit1: Running a bunch more tests in game, and it's not always 12, sometimes it is 13, but after a bunch of testing, I've not managed to get one to tick more than 13 times. I still have not seen it tick more than 12 times when I've been at 89% haste.

Edit2: Basically, it looks like the simulation is hasting the ticks, but not shortening the duration of the ground effect based on haste levels. The duration should match the cooldown on the ability, and the ticks should tick faster based on haste.

**Comment by Jazzer360** [comment]
Here's a sample sim you can run to demonstrate the behavior:
(no bloodlust for simplicity, overrode haste to 20k rating for illustrative purposes)

```
paladin="ConsecrationTest"
level=110
race=human
role=attack
spec=retribution
talents=3000000

head=,id=133629,bonus_id=3413/1517/3337
neck=,id=134529,bonus_id=1727/1492/1813
shoulder=,id=134272,bonus_id=3432/1502/3336
back=,id=134412,enchant_id=5433,bonus_id=3413/1517/3337
chest=,id=139690,bonus_id=3386/3384
tabard=,id=5976
wrist=,id=133632,bonus_id=1727/1492/1813
hands=,id=134268,bonus_id=3432/1517/3337
waist=,id=137361,bonus_id=1727/1502/3336
legs=,id=139694,bonus_id=3385/3384
feet=,id=139691,bonus_id=3385/3384
finger1=,id=133634,enchant_id=5426,bonus_id=1727/1502/3336
finger2=,id=134542,enchant_id=5426,bonus_id=1727/1808/1497/3336,gem_id=130216
trinket1=,id=134322,bonus_id=3432/604/1497/1674
trinket2=,id=121287,bonus_id=3432/607/1532/3337
main_hand=,id=120978,bonus_id=737,relic_id=1826:1457/3411:1507:3336/3432:1502:3336,gem_id=133685/137375/141260/0

gear_haste_rating=20000
optimal_raid=0

actions=consecration/wait,sec=30

log=1
output=consecration.txt
```

**Comment by Collisionc** [comment]
Ok, fixed.
