### ISSUE TITLE
Bough of Corruption for melees

### ISSUE THREAD

**Issue by filipefranchesco** [simulationcraft/simc#2949]
I'm not sure if it affects all melees or only my spec, Enhancement Shaman (kind of a "melee caster", elemental damage and stuff).

In any simulation with my character while using Bough of Corruption (trinket from Xavius), it deals no damage. I dropped it yesterday and killed some bosses with it, and it has procs for me (pretty decent damage, 6~7% on single depending on procs), but for the simulations it is basically a mastery-only trinket, so it is worse than many other trinkets.

For test purposes you can import my character (Chescool-Azralon). I probably won't change this trinket for some time.

PS: I've simulated on current release and on some of the latest builds, with no damage in any of them. Also, trinket isn't on Enhance loot table.

Edit: as of october 9th, one of the latest windows build (not release) already includes its damage. Didn't test with the release version, tho.

**Comment by Collisionc** [comment]
Yeah, looks like it was added here: https://github.com/simulationcraft/simc/commit/7f69a1298cab0c3ac67f278ac7e4374e18511676
adjusted here: https://github.com/simulationcraft/simc/commit/92e5b881a20bc6a28475ad5b7953de5a6a2cfb31
more adjustment here:
https://github.com/simulationcraft/simc/commit/d0ee0e96bfacd0462104419affa3a9589f66aaf7

It will be in the next official release, or any new nightly.
