### ISSUE TITLE
Divide by Zero error during character import

### ISSUE THREAD

**Issue by Rahirith** [simulationcraft/simc#2950]
I just downloaded SimCraft, and I've run into an appcrash when attempting my first character import. I attempted a VB debug, and it came back with a divide by zero exception somewhere in the execution of the import. I've tried both the 64bit and 32bit versions of SimCraft, and both gave the same error at the same time. I'm currently running on 64bit Win7 Home Premium if that makes a difference compatibility-wise.

**Comment by Collisionc** [comment]
Can you link your armory?

**Comment by Rahirith** [comment]
us.battle.net/wow/en/character/queldorei/Xiaoyin/simple

**Comment by Collisionc** [comment]
Ok. Fixed that, unfortunately there are still other problems with brewmaster, but at least now it won't crash when you try to import.
