### ISSUE TITLE
Fury Warrior Problems?

### ISSUE THREAD

**Issue by Boomer725** [simulationcraft/simc#2954]
Every time I try to run my new warrior I get the same errors: 

Player Vidraxx uses run_action_list with unknown action list movement
Simulation has been canceled during player setup! (thread=0)  
Player Vidraxx uses call_action_list with unknown action list bladestorm
Player Vidraxx uses call_action_list with unknown action list bladestorm
Player Vidraxx uses call_action_list with unknown action list bladestorm

I'm still pretty new to simcraft, but I used it on my mage @ low levels and never had this issue before, but maybe I missed something or changed something accidentally.

**Comment by Collisionc** [comment]
Low level simulations always break something, I'll see what I can do.

**Comment by Collisionc** [comment]
Should be fixed in next release.
