### ISSUE TITLE
SimulationCraft crashing on simulation

### ISSUE THREAD

**Issue by wrawrux** [simulationcraft/simc#2955]
So when trying to sim my character Simulation Craft is now crashing. Either I get the windows dialogue that the program has stopped working, or my computer freezes and I have to restart. I have simulated my character many times before with no issue, so I reinstalled with the newest version and still have the same issue.
Edit: so the issue seems fixed. For some reason it was creating two profiles when I imported my character. So I deleted all the profiles, re-imported and it works.

**Comment by Latzan** [comment]
I still got this problem, used simcraft a lot in mop and draenor, but the legion version keeps crashing (stops responding and closes down), have tried reinstalling newer version as you released but still got the same problem. Have also both imported from bnet and from the ingame addon.

**Comment by scamille** [comment]
If SimulationCraft crashes when starting/during a simulation, please always post the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file, containing input for the last simulation. This allows us to replicate and fix the problem.

It is always possible that some exotic talent/gear combination causes crashes.

**Comment by Latzan** [comment]
Thanks for the response, hope this helps.
[simc_gui.zip](https://github.com/simulationcraft/simc/files/517599/simc_gui.zip)

**Comment by Collisionc** [comment]
Also post your dxdiag:

 Instructions:
Click on, "Start Button".
Click on, "Run".
In the pop-up window enter DxDiag and hit ok.
The DirectX Diagnostic Tool pop-up window should appear.
Click on, "Save all information".
"Save As" window should be present.
Click on, "Save" (The file should be saved to your desktop as DxDiag.txt)
Exit the DirectX Diagnostic Tool.

Upload the dxdiag file for us to look at.

**Comment by Latzan** [comment]
[DxDiag.txt](https://github.com/simulationcraft/simc/files/518156/DxDiag.txt)

**Comment by Collisionc** [comment]
When is it crashing? On load, or later?

**Comment by Latzan** [comment]
The crash happens just when its about to finish the simulation.

**Comment by scamille** [comment]
If you look into your simulationcraft installation folder, is there a simc_report.html file containing the simulation you did?

**Comment by Collisionc** [comment]
Try this: 
http://downloads.simulationcraft.org/simc-703-04-win64-1cf0421.7z
