### ISSUE TITLE
Mark of the Satyr dealing slightly more damage in-game

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#2956]
No idea why, but mark of the satyr is now dealing more than the average of 45k SimC is currently using. Here's a log hitting a dummy with no versatility gear and no buffs used:
https://www.warcraftlogs.com/reports/cfLZMApRa8BqGDCX/#type=damage-done&source=5&ability=191259

It looks like it's dealing an average of 50k now instead of 45k.

**Comment by Collisionc** [comment]
Seems to be doing about 10% more damage in game than sim, adjusted.
