### ISSUE TITLE
Command !prev.focused_rage and !prev_off_gcd.focused_rage issues

### ISSUE THREAD

**Issue by Nightstand** [simulationcraft/simc#2959]
I am trying to resolve an issue where the simulation will use focused rage directly after an on-GCD ability, and then again before the next on-GCD ability.  It is difficult to replicate this behavior ingame, so I want to create APL logic that will prevent the sim from performing this back to back.   !prev.focused_rage nor !prev_off_gcd.focused_rage seem to do what I think they would (prevent running the line if the previous ability used was focused_rage).  I am running the logic in two separate lines for clarity, but I don't see how that would affect the APL reading the previously used ability.

**Comment by Nightstand** [comment]
APL I was using when I ran into this issue:

actions.single+=/mortal_strike,if=buff.battle_cry.up&buff.battle_cry.remains<gcd
actions.single+=/colossus_smash,if=buff.shattered_defenses.down
actions.single+=/focused_rage,if=(cooldown.colossus_smash.remains>24)&rage>28&buff.focused_rage.stack<3&!prev_off_gcd.focused_rage
actions.single+=/focused_rage,if=(cooldown.colossus_smash.remains<1&rage.deficit<37&buff.focused_rage.stack<1&!prev_off_gcd.focused_rage)
actions.single+=/focused_rage,if=(cooldown.colossus_smash.remains<1&rage.deficit<70&buff.focused_rage.stack<3&cooldown.battle_cry.remains<6&!prev_off_gcd.focused_rage)
#actions.single+=/focused_rage,if=(cooldown.colossus_smash.remains<1&rage.deficit<37&buff.focused_rage.stack<1)
#actions.single+=/focused_rage,if=(cooldown.colossus_smash.remains<1&rage.deficit<70&buff.focused_rage.stack<1&cooldown.battle_cry.remains<6)
#actions.single+=/focused_rage,if=cooldown.battle_cry.remains<3&rage.deficit<75&buff.focused_rage.stack<3
actions.single+=/warbreaker,if=debuff.colossus_smash.down
actions.single+=/mortal_strike
actions.single+=/slam
actions.single+=/focused_rage,if=equipped.archavons_heavy_hand
#actions.single+=/heroic_charge,if=rage.deficit>=40&(!cooldown.heroic_leap.remains|swing.mh.remains>1.2)
#Remove the # above to run out of melee and charge back in for rage.
actions.single+=/bladestorm,interrupt=1,if=raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets

**Comment by Nightstand** [comment]
Tried to work around it with a series of (prev.slam|prev.mortal_strike|prev.colossus_smash|prev.warbreaker), still didn't work.  Friend suggests it may be due to a queuing system that's used now for simc?

**Comment by Collisionc** [comment]
I'm going to close this as I believe it was fixed sometime in the last 3 months, please let me know if you have more issues with it.
