### ISSUE TITLE
Simcraft Crashing

### ISSUE THREAD

**Issue by Tic3ooo** [simulationcraft/simc#2961]
Simcraft was working fine for me, then one day it suddenly started crashing upon completing a simulation. A newer version has since came out, and I am still experiencing the same issue.
[simc_gui.zip](https://github.com/simulationcraft/simc/files/517791/simc_gui.zip)

**Comment by Collisionc** [comment]
Can you post your dxdiag? 

Instructions:
Click on, "Start Button".
Click on, "Run".
In the pop-up window enter DxDiag and hit ok.
The DirectX Diagnostic Tool pop-up window should appear.
Click on, "Save all information".
"Save As" window should be present.
Click on, "Save" (The file should be saved to your desktop as DxDiag.txt)
Exit the DirectX Diagnostic Tool.

**Comment by Tic3ooo** [comment]
[DxDiag.txt](https://github.com/simulationcraft/simc/files/518220/DxDiag.txt)

**Comment by Collisionc** [comment]
Try this: 
http://downloads.simulationcraft.org/simc-703-04-win64-1cf0421.7z

**Comment by Tic3ooo** [comment]
Same issue is occurring. Beings to simulate, then crashes at the end.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/9ae71694f3d1a9f4c9587d731446b22bbd570f30

Should be fixed in the newest nightly. Let me know if it isn't.

**Comment by Tic3ooo** [comment]
Tried downloading the latest nightly, simc-703-04-win64-9ae7169.7z, and now as soon as I attempt to run the application, I get a popup from simcraft saying "We have reset your configuration settings due to major changes in the GUI", immediately followed by Simcraft crashing.

I can't even open the newest version.

**Comment by EduardoOliveira** [comment]
I have the same issue, any ideas?
