### ISSUE TITLE
[Mage] SimCraft crash with low level fire mage. 

### ISSUE THREAD

**Issue by nixpix76** [simulationcraft/simc#2965]
Edit. Updated post below

**Comment by nixpix76** [comment]
I ran the SimCraft at home now, on my primary computer and I am getting the same crash, so it has to have something to do with my character specifically (it only crashes when Simming this char specifically). I have uploaded the updated files here:

https://ufile.io/ff63

**Comment by Collisionc** [comment]
Thanks for reporting, low level characters sometimes cause crashes that we don't see at max level. It will be fixed in next release.
