### ISSUE TITLE
Simcraft Crashing

### ISSUE THREAD

**Issue by plspidey** [simulationcraft/simc#2966]
Hello, 
Simcraft was working fine, but recently it started crashing on hitting simulate when I am using a lengedary item from another spec. Trying to sim my frost DK while using a Unholy DK legendary belt.

Tried with the new release version and still have the issue. Same thing with the nightly builds.

[simc_gui.zip](https://github.com/simulationcraft/simc/files/520462/simc_gui.zip)

**Comment by nygax** [comment]
I got the same thing, had to switch to a different belt to run the sim

**Comment by Collisionc** [comment]
This is resolved in the newest simc versions - http://downloads.simulationcraft.org/?C=M;O=D
