### ISSUE TITLE
Error shaman Enhancement

### ISSUE THREAD

**Issue by alexmr06** [simulationcraft/simc#2967]
Hello, small oval on error reporting when I copy the sim once created. Cordially. Thank you for the help you provide.

link 1: http://imgur.com/a/IqJD5

**Comment by navv1234** [comment]
This is an Ovale issue. Simulationcraft by itself has nothing to do with Ovale, so you would be better served contacting them.

**Comment by alexmr06** [comment]
oh ok :) thx for this help.
