### ISSUE TITLE
Shadow Blade OH Damage Modifier

### ISSUE THREAD

**Issue by Fierydemise** [simulationcraft/simc#2968]
SimC appears not to be applying the OH damage modifier to shadow blade OH attacks.

This is incorrect as seen in this log:
https://www.warcraftlogs.com/reports/wc73Wz6RbXAjN2gF#type=damage-done&source=13

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/af91bc0ec88081e5c86792b78e8d2b7b36e0e55a
