### ISSUE TITLE
Unable to simulate stat weights

### ISSUE THREAD

**Issue by energipsy** [simulationcraft/simc#2969]
Just yesterday I was able to find the stat weights for my character by going to Options>Scaling>selecting the stats and simulating.
Now, however, while the option to check off scaling is still there, the stats below don't show up. When I simulate, it doesn't calculate stat weights either.
I feel like this is an error on my end -- is there anything I'm missing?
<img width="1082" alt="screen shot 2016-10-11 at 11 06 25 am" src="https://cloud.githubusercontent.com/assets/22773958/19278044/886dea2e-8fa1-11e6-9173-0cd1496aa419.png">

**Comment by Collisionc** [comment]
Try making the window bigger, it's possible that the checkboxes aren't showing up due to the extremely small window.  I'll see if there's anything I can do to make it work better though.

**Comment by energipsy** [comment]
Wow, this actually fixed my problem. The stats to check off were hidden when the client wasn't fully stretched vertically. Works great now, though, so thank you!
