### ISSUE TITLE
[Shadow] Haste scales negatively

### ISSUE THREAD

**Issue by artdedeco** [simulationcraft/simc#2973]
I've just ran a sim with my character and simc is reporting these values for stat scaling:

`Intellect=7.38, CritRating=11.21, HasteRating=-12.77, MasteryRating=6.46, Versatility=5.47`

As you can see, haste is negative. I simmed with a 1000 haste gem and the dps came actually lower than the original sim, so this is indeed a bug in the sims and not simply a visual/reporting bug.
Using Simc 7.0.3-03

Steps to repro:

1 - Import my character Livywel@Azralon (I haven't tested with other characters... yet?)
2 - Set this configs:

>  Iterations: 10000
> Length: 300sec
> Vary: 20%
> Style: HeavyMovement
> Skill: Elite
> Target type: TMI Standard Boss
> TMI SB: T19N
> World Lag: Australia - 200ms
> Deterministic RNG: Yes
> Everything else: Default (I guess)

3 - Enable scaling on Int, Crit, Haste, Mastery and Vers; Center Scale Delta set to No and Scale Over DPS

4 - Simulate

**Comment by scamille** [comment]
Thats when you create a plot.

E.g with 

``` dps_plot_stat=haste
dps_plot_points=20
dps_plot_step=100
dps_plot_target_error=0
dps_plot_iterations=10000
```

in the override tab, I get a plot like this ![livywel_plot](https://cloud.githubusercontent.com/assets/1479348/19360261/146073b6-917e-11e6-80ea-c8c8c4c47f75.png) showing a plateau/hole in the haste scaling, which of course leads to negative scale factors if you happen to be at the negative flank.

Now why exactly this happens would need further analysis, eg. by creating a manual sims at ~minus 300 haste, which seems to do more dps than with your current equipment. Very likely it has to do with something in the APL, where you can squeeze something better into the rotation with less haste.

Specifically check the "Action Priority List" section in the html report, which might indicate something.

**Comment by scamille** [comment]
Or a bit more appropriately with bigger deltas. (I underestimated stat values a bit, default scale factor delta is 1138 nowadays).
![livywel_plot2](https://cloud.githubusercontent.com/assets/1479348/19360767/34d104b0-9180-11e6-8712-104cd373d1bc.png)

```
dps_plot_stat=haste
dps_plot_points=20
dps_plot_step=500
dps_plot_target_error=0
dps_plot_iterations=1000
```

**Comment by artdedeco** [comment]
Well, it seems the people over HowToPriest already [figured this out](https://howtopriest.com/viewtopic.php?f=75&t=8825#p73851). Twintop seems to have used custom scripts at [his sims](https://www.beotorch.com/batch.php?r=9354d26f-6917-11e6-9379-008cfa070490).

He's probably going to contribute them back, I guess?

Edit: or maybe not, since [he's retiring](https://howtopriest.com/viewtopic.php?f=4&t=8833).

**Comment by scamille** [comment]
S2M action priority list is very hard to fine-tune for all use cases, as is easy to see when looking at the APL with the special s2mcheck variable.
Main problem is when exactly to cast S2M, so you maximize its length without prematurely dying, and that is strongly haste dependent.

I think Twintop did a great job at optimizing s2m, but it will probably never be perfect - something which it shouldnt be, because in real life you cant even really calculate the formula in the s2m rota that are already in there. Very easy to screw up by using s2m too early and dying at 10% boss hp, or too late and not maximizing your potential. But thats whats so interesting about the talent ;)
