### ISSUE TITLE
[Rogue] Dreadlord's Deceit legendary doesn't start stacked

### ISSUE THREAD

**Issue by Kretuhtuh** [simulationcraft/simc#2976]
The legendary item Dreadlord's Deceit provides up to 30 stacks of a damage buff to Fan of Knives, which actually results in some pretty good burst. Unfortunately, it doesn't start the fight fully stacked. In actual play, I will always start a boss fight with 30 stacks of the Dreadlord's Deceit buff, and I'd like simcraft to mirror that for my opener.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/8bfcc1c6ba3ec75c6eb38767f4247cda05fec967
