### ISSUE TITLE
Copying a character doesn't copy the artifact information

### ISSUE THREAD

**Issue by Jackal42** [simulationcraft/simc#2978]
I'm having trouble with copying a character.  The attached script is a simplified version of a script that worked on SimulationCraft v6, but fails on the current version 7.03_3.  Looking at the results, it appears that the artifact information isn't copied correctly.  I didn't see any changes in the documentation that relate to this.

[demo.txt](https://github.com/simulationcraft/simc/files/528334/demo.txt)

**Comment by navv1234** [comment]
Yeah, this is a known issue. For now, artifact= strings will get properly copied but if you fetch a profile from the armory, that information is not. I'll try to get in a fix this weekend.

**Comment by navv1234** [comment]
Fixed in the next simc release.
