### ISSUE TITLE
Frostscythe not cleaving

### ISSUE THREAD

**Issue by Blin-da-med** [simulationcraft/simc#2980]
Hello,

Have an issue with simming cleave situation as frost dk at simcraft version 703-03.
The idea of my simulation was heavy aoe situation on m+ packs. So did like 40 sec combat in patchwerk mode with 4 targets with that apl:
actions=auto_attack
actions+=/blood_fury
actions+=/berserking
actions+=/sindragosa's_fury,if=buff.pillar_of_frost.up&debuff.razorice.stack=5
actions+=/pillar_of_frost
actions+=/howling_blast,target_if=!dot.frost_fever.ticking
actions+=/frostscythe,if=buff.killing_machine.up
actions+=/glacial_advance
actions+=/remorseless_winter
actions+=/frostscythe
actions+=/frost_strike
actions+=/empower_rune_weapon
actions+=/arcane_torrent,if=runic_power.deficit>25
So it just uses Frostscythe (FSC next in the text below) complitelly ignoring rp usage with frost strike.
The data i got made me think that FSC is not cleaving at all.
During 40 sec simulation it was casted 16 FSC which gave 16 hits while 1 use of Sindragosa's fury gave 4 hits, 3 uses of Glasial advance gave 12 hits, same for Frozen pulse, remorseless winter.
So all aoe abilities used in my simulation gave x4hits exept FSC.
As in the tooltip of FSC is stated: " A sweeping attack that strikes **all enemies in front of you** for $sw1 Frost damage." it also should cleave all simulated targets and i think thats just a bug of Simcraft.
Data provided.
[FSCBUG.txt](https://github.com/simulationcraft/simc/files/529653/FSCBUG.txt)

**Comment by navv1234** [comment]
I enabled unlimited target aoe for Frostscythe in cc544ab.
