### ISSUE TITLE
[Guardian Druid] Error in rotation

### ISSUE THREAD

**Issue by Mirondos** [simulationcraft/simc#2981]
the default rotation for guardian druid only outputs damage from Moonfire, auto attack and mangle.
i am not an expert with coding, but after reading the documentation was able to edit the rotation so that it includes Rage of the Sleeper and thrash, and only casts moonfire with a proc (galactic guardian keeps it up 99% of the time, so I only need it for the extra rage). it seemd to work well, but if i add swipe to the rotation and then simulate it says
Nothing to report
Sum of all Simulation Durations is zero.
removing swipe from the rotation does not go back to a simulable profile, so I have to re-import it.
The rotation i tried to input is:

actions=auto_attack
actions+=/skull_bash
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/use_item,slot=trinket2
actions+=/barkskin
actions+=/rage_of_the_sleeper
actions+=/bristling_fur,if=buff.ironfur.remains<2&rage<40
actions+=/ironfur,if=buff.ironfur.down|rage.deficit<25
actions+=/frenzied_regeneration,if=!ticking&incoming_damage_6s%health.max>0.25+(2-charges_fractional)*0.15
actions+=/pulverize,cycle_targets=1,if=buff.pulverize.down
actions+=/thrash
actions+=/mangle
actions+=/swipe
actions+=/pulverize,cycle_targets=1,if=buff.pulverize.remains<gcd
actions+=/lunar_beam
actions+=/incarnation
actions+=/pulverize,cycle_targets=1,if=buff.pulverize.remains<3.6
actions+=/thrash_bear,if=talent.pulverize.enabled&buff.pulverize.remains<3.6
actions+=/moonfire,if=buff.galactic_guardian.up
actions+=/moonfire,if=remains<2

is something wrong?

**Comment by bitfluxhound** [comment]
Outdated rotation.

**Comment by Mirondos** [comment]
It's Simulationcraft's default one, with a couple changes i tried to make in order to update it. in the end i went for the following one:
actions=auto_attack
actions+=/skull_bash
actions+=/use_item,slot=trinket2
actions+=/barkskin
actions+=/rage_of_the_sleeper
actions+=/bristling_fur,if=buff.ironfur.remains<2&rage<40
actions+=/ironfur,if=buff.ironfur.down|rage.deficit<25
actions+=/frenzied_regeneration,if=!ticking&incoming_damage_6s%health.max>0.25+(2-charges_fractional)*0.15
actions+=/thrash_bear
actions+=/mangle
actions+=/swipe_bear
actions+=/moonfire,cycle_targets=1,if=buff.galactic_guardian.up
actions+=/moonfire,cycle_targets=1
actions+=/moonfire
I know it may not be the best rotation, and it may need some more scripting, but then again i'm neither an expert theorycrafter nor programmer, I just tried to update a Totally-not-good rotation to a kind-of-ok one.

**Comment by bitfluxhound** [comment]
actions=auto_attack
actions+=/incarnation
actions+=/rage_of_the_sleeper
actions+=/lunar_beam
actions+=/frenzied_regeneration,if=(incoming_damage_5s>=health.max_0.5)|(health<=health.max_0.4)
actions+=/bristling_fur,if=buff.ironfur.stack=1|buff.ironfur.down
actions+=/ironfur,if=(buff.ironfur.up=0)|(buff.gory_fur.up=1)|(rage>=80)
actions+=/moonfire,if=buff.incarnation.up=1&dot.moonfire.remains<=4.8
actions+=/thrash_bear,if=buff.incarnation.up=1&dot.thrash.remains<=4.5
actions+=/mangle
actions+=/thrash_bear
actions+=/pulverize,if=buff.pulverize.up=0|buff.pulverize.remains<=6
actions+=/moonfire,cycle_targets=1,if=buff.galactic_guardian.up=1&(!ticking|dot.moonfire.remains<=4.8)
actions+=/moonfire,if=buff.galactic_guardian.up=1
actions+=/swipe_bear

**Comment by Mirondos** [comment]
I really thank you for this.

**Comment by Mirondos** [comment]
Actually, it doesn't work: when i simulate it says:
Nothing to report
Sum of all Simulation Durations is zero.

EDIT: There was a copying problem with the frenzied regeneration line: probably related to the fact that the simc multiplication symbol is read as italic marker from this forum. I figured it out after a while and fixed it. thank a lot again.

**Comment by bitfluxhound** [comment]
Closing this, will update apl in c, over the weekend.
