### ISSUE TITLE
Crash on Startup win7 x64

### ISSUE THREAD

**Issue by vigilyn** [simulationcraft/simc#2982]
The newest nightly build crashes on startup and immediately memory dumps.

Running on Windows 7 x64 in a VM, latest updates. Previous versions had no issue.

**Comment by vigilyn** [comment]
Running simc from command line works fine, the issue is with the gui.

**Comment by Collisionc** [comment]
Yeah, I was just able to reproduce this in a VM... and I did a stupid thing, I'll fix.

**Comment by Collisionc** [comment]
Try this: 
http://downloads.simulationcraft.org/simc-703-04-win64-1cf0421.7z

**Comment by vigilyn** [comment]
Works now, thank you.
