### ISSUE TITLE
DH Vengeance Soul Barrier is not counting healing correctly

### ISSUE THREAD

**Issue by Rikxz** [simulationcraft/simc#2984]
When Soul Barrier is toggled on, it reduces the amount of healing that the simmed character receives from Lesser Souls.

To replicate, run a sim with Soul Barrier and one without.  In the Resources tab it'll show drastically less health gained from Lesser Souls on Soul Barrier.

**Comment by Zarania** [comment]
I see the issue.  I'm going to do some testing tonight and I'll have a fix for this shortly.

**Comment by Zarania** [comment]
Fixed in a9659b052cc1f50b03b1384e0ed35e29c1d94b31

Will be in the next nightly.
