### ISSUE TITLE
Issue with Unholy DK talent infected claws

### ISSUE THREAD

**Issue by Jimmy469** [simulationcraft/simc#2985]
Using simc version 7.0.3 to compare effectiveness of DK talents, I discovered the following behavior which appears to be a simc bug.

When applying festering wounds on a target with the infected claws talent, an incorrect number of stacks can be applied if both the player and pet are applying wounds (which would happen in any appropriate situation).

When only applying wounds with the pet, or with only the player, the behavior appears to be correct.

The bug can be seen by using the profile from here: http://pastebin.com/vFy716bp
The profile contains only a few actions; summoning a pet and casting festering strike. It also contains an override for festering wounds max stacks and duration, making it stack infinitely and have infinite duration.

To see the bug in action, start by disabling the infected claws talent (talents=2211203) and check the average # of festering wound debuffs on fluffy pillow. Using 300s sim length, I was observing 84.25 stacks on the target. Because stacks are applied from 0, and applied evenly throughout the fight, the target ends the fight at average double that # of stacks (168.5). 

Next, re-enable infected claws and disable the player's festering strike (remove the line from APL). Using same conditions, I was observing an average of 17.2 stacks, so the target ends the fight at approx 34.4 stacks. This is consistent with the expected # of stacks (35% \* # of claw attacks).

Expected behavior for infected claws + festering strike would be for the stacks to stack, and thus to average 101.45 stacks/end fight at 202.9 stacks. However, running the sim, I was observing that the target had an average of 92.45 stacks/end fight at 184.9 stacks.

Therefore, I believe there is a bug in the way simc is handling infected claws applying stacks to a target that also has stacks being applied to it with festering strike.

**Comment by navv1234** [comment]
This is because Festering Wounds spell data indicates that it has a one second ICD. Does Infected Claws in game bypass this?

**Comment by Jimmy469** [comment]
There doesn't appear to be an ICD in game.

See 
![image](https://cloud.githubusercontent.com/assets/2487101/19470101/03f0b1be-94d3-11e6-9e17-eb18f4dd84f7.png)

from
https://www.warcraftlogs.com/reports/4cxrPm9KQtjZyaTN#fight=4&type=auras&source=7&spells=debuffs&by=target&ability=194310&target=30&view=events

1 application was from festering strike, one was from pet, within 1 second.

**Comment by navv1234** [comment]
Yeah, seems so. I'll move the ICD to DK only side.

**Comment by navv1234** [comment]
Fixed in f7b8107.
