### ISSUE TITLE
Seraphim on Protection paladin crashing every simulation

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#2986]
I tried to test different talent builds on my protection paladin to try and find the best setup to increase my damage but literally every single try with Seraphim crashed the application into a force close. I tried the setup with other 100 talents and it worked, then back to Seraphim and it stopped working, I tried changing talents for lower levels and it still didnt work with Seraphim but the two other talents.

**Comment by bitfluxhound** [comment]
http://i.imgur.com/Zi9SyHA.png

Just worked fine for me.

**Comment by ghost** [comment]
This for example didn't work for me: http://eu.battle.net/wow/en/tool/talent-calculator#bZa!1021011!c

However, this http://eu.battle.net/wow/en/tool/talent-calculator#bZa!1021010!c and http://eu.battle.net/wow/en/tool/talent-calculator#bZa!1021012!c both works perfectly fine. Try importing my character then and see if it makes any difference? http://eu.battle.net/wow/en/character/ravencrest/Synthet%C3%ACc/advanced

**Comment by bitfluxhound** [comment]
Can you post what you get after import, and i'll run that. Mb the issue is there.

**Comment by ghost** [comment]
I just get the  "X program has stopped responding" windows error, every single try. I've tried re-installing, restart PC/program etc. Only occurs when I use Seraphim, no other talent has caused this problem, and I have been playing around with pretty much all of them.

**Comment by bitfluxhound** [comment]
So the issue isn't with simulation, it's the issue with importing a profile.

**Comment by ghost** [comment]
I dont see how its a problem with profile though as literally every other talent setup works perfectly fine on that specific paladin.

**Comment by bitfluxhound** [comment]
Same issue as #2979 , trying to import a paladin with 3rd talent in lvl 100 tier crashes on import. (Sera - prot, Holy Wrath - ret)
