### ISSUE TITLE
Timewalking pieces are not scaled correctly.

### ISSUE THREAD

**Issue by KnightoftheVoid** [simulationcraft/simc#2987]
I obtained the Hourglass of the Unraveller (iLVL 820) from the current Burning Crusade Timewalking event.  Stated proc on the trinket is 4,512 attack power, testing the trinket in-game I am receiving 6,768, or 150% of the amount stated.  However, when running Simulationcraft it lists the proc as 1,016 attack power, so I believe it is still loading in the WoD iLVL version of the trinket / proc.  Not sure if this is true for all other Timewalking pieces / trinkets or not.  Character with trinket equipped for reference:  Slashpopcorn-Tichondrius.

**Comment by bitfluxhound** [comment]
The issue is with armory also not scaling it up properly.

**Comment by scamille** [comment]
@navv1234 So we wont/cant fix anything here, unless Blizz gives us proper data? Then I'll tag it approriately.

**Comment by navv1234** [comment]
No clue, would need a profile with such items, the one above there does not contain a timewalking trinket.

**Comment by navv1234** [comment]
So does anyone have a profile with actual timewalking 820 items so I could at least take a look at what's going on?

**Comment by tjl1973** [comment]
There's my current armoury for my elemental shaman. Cloak of Hidden Flasks is showing 463 in sims but it's an 830 piece in the armoury.

http://us.battle.net/wow/en/character/stormrage/Ukyo/advanced

The piece on wowhead is: http://www.wowhead.com/item=81136/cloak-of-hidden-flasks&bonus=615

even when I put this item number and the bonus, it simulates as 463.

**Comment by navv1234** [comment]
I'll take a look what happens there. Thanks.

**Comment by navv1234** [comment]
Where are you seeing 463? It seems to simulate as ilevel 830 with a freshly compiled copy?

**Comment by tjl1973** [comment]
I'm using the OS X build from March 12.

**Comment by navv1234** [comment]
Imported your character with the addon or from armory?

**Comment by tjl1973** [comment]
I just did a straight import from armoury. I've also tried putting in the item id and bonus and get the same issue.

**Comment by navv1234** [comment]
Can't say I'm seeing that. Where are you seeing the ilevel 463?

**Comment by tjl1973** [comment]
Listed under gear, in the results. I just did a download of the March 13 OS X build and get the same issue.

**Comment by tjl1973** [comment]
If you hover over the item and look at the detail, it will say 830, but when you look at the info below the name under gear, it has 463 and the wrong stat weights.

**Comment by navv1234** [comment]
Yeah, this is something completely unrelated to the tooltip. I'll fix it if I can figure out how.
