### ISSUE TITLE
Wrong raid buffed stat values

### ISSUE THREAD

**Issue by Pestitschek** [simulationcraft/simc#2988]
Hi,
Using 703-03 Version
Importing gear from battle net (http://us.battle.net/wow/en/character/azralon/Eumesminha/simple)

Currently either the importer or whatever SimC considers buffs/modifiers are wrong for primary stats. Bug is also present for Spell Power (Yes, demonology warlocks have them because of offhand artifact).
Combat Ratings are fine (Mastery, Haste, Vers, etc.]

In-game:
On the character stat panel, it shows that my character has:
Intellect = 21,990 (7,331+14,659)
Stamina = 34,974 (6,259+28,715)
and 11,091 Spell Power.

Not sure if it helps with your debugging, but I have 13,412 Intellect from Gear, 200 from Cloak Enchant, 7331 from base stats.

_[If you sum these 3 sources, 13,412+200+7,331 = 20,943. There is the 5% from Cloth Armor bonus
20,943 \* 1.05 = 21,990,15 (which matches with the value stated on the character panel)]_

Now on SimulactrionCraft:
OBS: There is an action on APL to use Flask of Whispered Pact (+1300 Int).

Final stats on the profile after simulation are:

```
    Raid-Buffed Unbuffed    Gear Amount
Int 22211   20504   12198 (879)
Sta 32377   32377   20172
SP  25135   23428   2924
```

**Not a single of these value matches with in-game values.**
Raid-Buffed should show 21990,15+1300*1.05 = 23,355.15 (Yes, the flask benefits from Cloth Armor bonus)

Same bug applies to Stamina. And no clue from where that value of 2924 spellpower came from on SimulationCraft.

**Comment by YepItsEuko** [comment]
I have to agree with this post, the demonology SP stat is the largest issue, and if the rest is correct it impacts everything out there. Please fix the SP issue and check in on the rest, devs.

**Comment by Collisionc** [comment]
This ended up being a warlock-specific issue, and should be resolved in the newest 710-01 downloads: http://downloads.simulationcraft.org/?C=M;O=D
