### ISSUE TITLE
Guardian Druid/Unholy Deathknight

### ISSUE THREAD

**Issue by Dontpuntme** [simulationcraft/simc#2993]
For guardian druid it appears the simulation doesn't thrash unless you have 2 or more targets however because thrash generates rage for survivability it should be cast on every fight including one target and for dps it dot should be kept active on one target. Also I did not look into if this was an issue but although it is common knowledge amongst the death knight community I don't know if people besides Death knights realize castigor has a chance to proc 2 extra wounds instead of just one which makes rotational adjustments.

**Comment by bitfluxhound** [comment]
Guardian trash works properly in latest simc version.

**Comment by navv1234** [comment]
We implement the Castigator double crit behavior.
