### ISSUE TITLE
Sorcerous Shadowruby Pendant on Use not used in simulations

### ISSUE THREAD

**Issue by ataraxey** [simulationcraft/simc#2996]
Hello,

The item [Sorcerous Shadowruby Pendant](http://www.wowhead.com/item=130233/sorcerous-shadowruby-pendant) has an on-use ability that shoots 1 of 7 spells that does considerable damage to the target, on a 5 minute cooldown. 

When simming myself with build simc-703-04-win64-d7c65eb and looking at the action list and damage charts it appears to never use the item.

This item is BIS for fire mages if it is "of the decimator", so i'd love to understand how it does against other similar necks or greater ilevel.

Is this a known bug? Or was this left out intentionally?

**Comment by Frostedmages** [comment]
Add a use_item line for it.

**Comment by ataraxey** [comment]
Where do I add that? Sorry, am unfamiliar with custom additions
