### ISSUE TITLE
[Rogue-Assassination] Difference in Dmg Numbers of Kingsbane and Poisonbomb when Master Poison is talented

### ISSUE THREAD

**Issue by ShadowVamp** [simulationcraft/simc#2997]
I have been trying to sim my character for stat weights and dps for Master Poison/ Agonizing Poison Assassination build. When I compared my sim results and live results on dummy, I realized my live results are consistently outdpsing my sim results. I tracked down the difference in dps to 2 sources, Kingsbane DoT and Poison Bomb. My theory is that simcraft does not account for the buff to Kingsbane DoT and Poison Bomb when Master Poisoner is talented. I tried the Rogue Discord but no one has followed up on this issue.

**Comment by aethys256** [comment]
Kingsbane damage should take this in consideration.
I fixed Poison Bomb.
https://github.com/simulationcraft/simc/commit/b50e4ceb1daa0b2ac9a636caddf7f21e7af99085

**Comment by ShadowVamp** [comment]
@Aethys256 Could you check for Kingsbane DoT again? I am still doing more dps with Kingbane on live, sometimes even double the average dmg shown on sims. It may not be MP, it could be Kingsbane not increasing each time a lethal poison is applied.

**Comment by ccjara** [comment]
Seconding this. It is higher without Master Poisoner already. The Kingsbane dot sims for about 35% DPS lower.
