### ISSUE TITLE
[Rogue-Assassination] Wrong item level relics in weapon T19M

### ISSUE THREAD

**Issue by vargen2** [simulationcraft/simc#2999]

**Comment by skasch** [comment]
Vendetta relics are better than any relic you can find in EN, hence the chosen relics; however, they should be (as it is now allowed) ilvl 865, for MM+ ilvl.

**Comment by aethys256** [comment]
I took the EN relic for the moment until the T19M rules are being set in the stone.
Anyway, Master Assassin are the best relics.

**Comment by aethys256** [comment]
I changed it to the T19H one for now since they are better.
https://github.com/simulationcraft/simc/commit/e52095d077d97f23c93767dabfb5b889ee5c959d
