### ISSUE TITLE
Mistweaver Monk not being imported

### ISSUE THREAD

**Issue by LordKodos** [simulationcraft/simc#3000]
My Mistweaver Monk is not being imported properly, but all of my other characters are. This is annoying because my Monk is my main.
I just get this 
# Profile will be downloaded into a new tab.
# 
# Clicking Simulate will create a simc_gui.simc profile for review.
# Unable to generate profile from: http://us.battle.net/wow/en/character/darkspear/Alandréa/simple
# Monk mistweaver healing for player Alandréa_Active is not currently supported.
# No active players in sim!

**Comment by bitfluxhound** [comment]
Just like simulation says, healer specs and some of the tank ones are currently disabled. If you wish to import this character you will have to do so as a windwalker.
