### ISSUE TITLE
off-spec legendaries crashing simc

### ISSUE THREAD

**Issue by nygax** [simulationcraft/simc#3001]
I was trying to sim my frost spec (http://pastebin.com/fn4zR5rY) while wearing the unholy legendary belt (http://www.wowhead.com/item=132441) and as soon as I hit simulate simcraft would crash (a box would pop up saying "simulationcraft has stopped working")

after some trial and error, I figured out that if I swapped to a different non-legendary belt the sim worked fine, so it must have been the belt causing the crash

**Comment by navv1234** [comment]
Fixed in 7fc8c86c416d8d3cfc76ef3276aa7eb4026dfcf2.
