### ISSUE TITLE
SimC not calculating primary stats properly in PTR build

### ISSUE THREAD

**Issue by rfmaida** [simulationcraft/simc#3002]
The latest nightly Windows build as of 2016-10-20 19:09 SimcSetup-703-04 apparently isn't calculating base primary stats properly, as seen in this screenshot. Both were from the same profile/APL, but the PTR one seems to have far less base STR/INT/AGI/Stam:

![simc_stat_bug](https://cloud.githubusercontent.com/assets/22973530/19587465/7b4cfee2-972c-11e6-9ed8-b792db247526.png)

**Comment by Collisionc** [comment]
Yeah, we're looking into it.... not sure what happened on blizzards end.

**Comment by navv1234** [comment]
This should be fixed now, no? Or is it still happening. The reason it was going on was we did not have base data for ptr in legion.

**Comment by rfmaida** [comment]
Er... nope, actually I just tried the latest nightly build 710-01-Win64 and now there isn't even an option to use PTR at all, only Live. Does 710-01 already have the PTR changes on it?

**Comment by Collisionc** [comment]
710-01 moved ptr ---> live, so ptr is the only data.

**Comment by rfmaida** [comment]
Ah, okay. Looks like it's fixed, then. Thanks!
