### ISSUE TITLE
[Subtlety-rogue] wrong DPS calculation.

### ISSUE THREAD

**Issue by Stabmeqt** [simulationcraft/simc#3003]
Hi. I searched through all the opened issues, but didn't found a single mention of subject.
It looks like simulated DPS is much higher than real DPS that can actually be pulled. 

I got 10 top logs of subtlety rogues on mythic Ursok, simulated them and compared simulated DPS to real logged DPS. Simulated DPS is like 40-70k higher than real logs.

**Comment by aethys256** [comment]
Do you have more infos ?
Like the profile used, the report, the log you're referring to, etc...

**Comment by Stabmeqt** [comment]
When i was looking on this issue, i picked top subtlety mythic Ursok log. It's not the top1 log for current moment, but it was the one i simulated  
thoroughly - https://www.warcraftlogs.com/reports/Jk98DtQam7N1MrPq#fight=31&type=damage-done&source=6

Log DPS is 410k

I modelled all the gear, talents, artifact this guy from log had on the moment of kill, and came up with that profile:

rogue="Soulldier"
origin="https://us.api.battle.net/wow/character/malganis/Soulldier/advanced"
thumbnail="http://us.battle.net/static-render/us/malganis/177/141473713-avatar.jpg"
level=110
race=blood_elf
role=attack
position=back
professions=leatherworking=800/skinning=800
talents=http://us.battle.net/wow/en/tool/talent-calculator#cb!1102100
artifact=17:0:0:0:0:851:1:852:3:853:2:854:3:857:3:858:3:859:3:860:3:861:1:862:1:864:1:865:1:866:1:1349:1
spec=subtlety

head=cowl_of_fright,id=139205,bonus_id=1806/1507/3336
neck=chain_of_the_green_flight,id=137311,bonus_id=3418/1517/1813,enchant=mark_of_the_hidden_satyr
shoulders=otherworldy_leather_mantle,id=139206,bonus_id=1805/1487
back=drape_of_vile_misfortune,id=137530,bonus_id=3410/1808/1522/3337,gems=200agi,enchant=200agi
chest=scarred_ragefang_chestpiece,id=139208,bonus_id=1806/1502
wrists=wristwraps_of_broken_trust,id=139209,bonus_id=1806/1517/3337
hands=brinewashed_leather_grips,id=134239,bonus_id=3411/1808/40/1507/1813,gems=150mastery
waist=lifeless_buckled_girdle,id=139197,bonus_id=1805/1487
legs=wardens_martial_greaves,id=137515,bonus_id=3413/1527/3337
feet=shadow_satyrs_walk,id=137032,bonus_id=1811
finger1=signet_of_the_highborne_magi,id=134537,bonus_id=3412/1517/3337,enchant=200mastery
finger2=grubby_silver_ring,id=139236,bonus_id=1805/1808/1487,gems=150mastery,enchant=200mastery
trinket1=bloodthirsty_instinct,id=139329,bonus_id=1805/41/1487
trinket2=sixfeather_fan,id=141585,bonus_id=1507/3336
main_hand=fangs_of_the_devourer,id=128476,bonus_id=743,gem_id=139267/139251/139253/0,relic_id=1805:1487/1805:1487/1806:1507:3336/0
off_hand=fangs_of_the_devourer,id=128479

Simulation with a fight type "Patchwerk" reaches 450k dps. "LightMovement" - 440k. But i believe "Patchwerk" should fit perfectly fine, because a light movement that takes place on Ursok is fully compensated by increased number of finishers due to shuriken stom usage (when there is an add).

Sorry, i don't know how to get HTML report from simc, so i attached text report

[report.txt](https://github.com/simulationcraft/simc/files/546350/report.txt)

**Comment by aethys256** [comment]
With the latest changes, this is going to be more close to the in-game behavior.
It's entirely normal you don't see the exact numbers as one log (especially when the context is different).
