### ISSUE TITLE
Sanguino server doesn't exist

### ISSUE THREAD

**Issue by dugarryxl** [simulationcraft/simc#3004]
Hello.
Im triying to load my profile from sanguino and it didn`t work.
Im looking at the servers list and it doesn't exist.
Any idea for run simc?
Thank you in advance

**Comment by Collisionc** [comment]
Go to options tab, make sure to select EU as your region.

**Comment by dugarryxl** [comment]
OMFG!.
Thank you very much and sorry.

**Comment by Collisionc** [comment]
No problem!
