### ISSUE TITLE
Protection Warrior - Into The Fray

### ISSUE THREAD

**Issue by coltraine** [simulationcraft/simc#3005]
It appears that when the talent, "Into The Fray," for Protection Warriors is selected it is not applying the 3% haste buff to the simulations.

**Comment by Collisionc** [comment]
Yeah, I was dreading making this work with multiple adds. :D

**Comment by coltraine** [comment]
Hah, I understand, this project must  be overwhelming especially during the
start of this expansion. Just thought I would try post and bring it to
attention if it was unnoticed. Good luck with it and thank you for all the
hard work you put in, we all love and appreciate you for it!

**Comment by Collisionc** [comment]
Finally added. I'll probably tweak it some later, but it works for now. https://github.com/simulationcraft/simc/commit/11327624538f209f5072c32cf3c163aad2a24ef0

(Right now it won't update stacks if a target moves out of range, but will update if the target dies.)
