### ISSUE TITLE
Brewmaster Monk crashing Simulationcraft

### ISSUE THREAD

**Issue by kadunz** [simulationcraft/simc#3007]
Every time i try to import or simulate a brewmaster monk it crashes.

**Comment by bitfluxhound** [comment]
Does it crash, or simply return an error message ?

**Comment by kadunz** [comment]
It just crashes. "SimulationCraft has stopped working"

**Comment by ManagerWoW** [comment]
Was due to this commit:

https://github.com/simulationcraft/simc/commit/d7a08fa846ff6a4d795b8d20e36c035d3fd6ac3d

**Comment by kadunz** [comment]
The client still currently crashes. Not sure what the reason is.

**Comment by Collisionc** [comment]
@ManagerWoW on the case.

**Comment by ManagerWoW** [comment]
Hina's https://github.com/simulationcraft/simc/commit/26bae85e742648a5088bcc7117a1bb8f9873d00d fixed the crashes. Should be good to close.
