### ISSUE TITLE
How do you properly calculate the "relic_id" attribute for warforged/titanforged relics?

### ISSUE THREAD

**Issue by mrabey** [simulationcraft/simc#3008]
I would like to test a few relics I have sitting in bags.  I have gone through WoWhead to find item ID's and the bonus_id associated with warforged and titanforged relics.  The item_id for the relics are correct. However, bonus_id's associated with an item only account for two of the three numbers in your colon-separated set.

For example:

I have 2x Shieldmaiden's Prayer (item_id 141260) that are warforged to 835 which results in a bonus_id of 1497:3396 on WoWHead.  SimulationCraft imports the relic_id as "3396:1497:3336".   I see that both 1497 and 3396 are present although reversed. Where does the 3336 come from?

**Comment by aethys256** [comment]
Your best bet is to just put the gem_id and override the total ilevel by adding ",ilevel=xxx" at the end

Example for Subtlety T19H :
`main_hand=fangs_of_the_devourer,id=128476,gem_id=136721/137377/136721,relic_id=1517:1727/1517:1727/1517:1727`
->
`main_hand=fangs_of_the_devourer,id=128476,gem_id=136721/137377/136721,ilevel=894`

To compute the ilevel, it's 750 (base artifact) + bonus_relic1 (48 in my example), + bonus_relic2 (48 again) + bonus_relic3 (48 again).

Doing so, you only need the itemID and not anymore the bonus id.

**Comment by navv1234** [comment]
You can use wowhead's bonus ids in simc and they should give you identical results. The simc addon, and the armory import will use bonus ids that blizzard thinks the item needs. The bonus id system is incredibly complicated and full of features, some of which outsiders can only guess, and in this case, the 3336 is probably needed for blizzard, but not for us.
