### ISSUE TITLE
SimulationCraft does not start at all

### ISSUE THREAD

**Issue by syxer** [simulationcraft/simc#3009]
Hello, 
I try to run SimulationCraft ( as administrator) and does not happen anything. Click on start waiting for several second and later nothing happen. 

I could read in previous similar post that you asked to upload DxDiag so here is mine: 

https://ufile.io/ed67

Do you have any idea what is ths problem? 

I tried to run x64, x86 version, the result is the same. 

Your support would be highly appreciate it. 

Thanks in advance! 

Regards,
syxer

**Comment by Collisionc** [comment]
Try 710-01 (preview), I fixed a huge error after 703-03. 

http://downloads.simulationcraft.org/?C=M;O=D

**Comment by syxer** [comment]
Got to following failure: 
http://tinypic.com/r/ae38mh/9

Any idea? 

Thanks in advance! 

syxer

**Comment by Collisionc** [comment]
Install the program to a different folder or try right clicking and run as administrator.

**Comment by syxer** [comment]
Does not work at all. 
Tried to run as adminstrator, installed for different folder. 

Is there any other program necessary to be installed in order to run the program?

**Comment by Collisionc** [comment]
It appears that this is an issue with your windows installation if right clicking and "run as admin" does not function. 

There is one workaround and two fixes that I have found on the internet:
Workaround:
Disable UAC - User Account Control - http://superuser.com/questions/83677/disabling-uac-on-windows-7 - has some instructions on doing that for windows 7. 
Fixes:
1: Unlock the default administrator account, logon it, run the following command in command prompt:
sfc /scannow 
2: If you do not know how to do the previous step, a reinstall is probably your best option.

**Comment by syxer** [comment]
Did evertyhing, still not working. Also did not work after reinstall. 

is there any chance to fix it without reinstall the windows?

**Comment by Collisionc** [comment]
Probably not from what I'm reading. :(

**Comment by Collisionc** [comment]
It's either a folder permissions issue or you need to right click and run
as administrator. If it's a folder issue, try installing to a different
folder.
