### ISSUE TITLE
Shaman Elemental T19M Profile

### ISSUE THREAD

**Issue by ShamanStarsha** [simulationcraft/simc#3011]
shaman="Shaman_Elemental_T19M"
level=110
race=troll
role=spell
position=ranged_back
talents=3112212
artifact=40:0:0:0:0:291:1:292:1:293:1:294:1:295:1:296:1:297:1:298:3:299:3:300:3:301:3:302:3:303:3:304:3:305:3:306:3:1350:1
spec=elemental

head=greyed_dragonscale_coif,id=139214,bonus_id=1806
neck=blackened_portalstone_necklace,id=139332,bonus_id=1806,enchant=mark_of_the_hidden_satyr
shoulders=Echoes_of_the_Great_sundering,id=137074
back=evergreen_vinewrap_drape,id=139248,bonus_id=1806,enchant=binding_of_intellect
chest=patient_ambushers_hauberk,id=139221,bonus_id=1806
wrists=manacles_of_the_nightmare_colossus,id=139222,bonus_id=1806
hands=gauntlets_of_the_demented_mind,id=138214,bonus_id=1806
waist=laughing_sisters_pouchchain,id=139211,bonus_id=1806
legs=disjointed_linkage_leggings,id=139216,bonus_id=1806
feet=Scored_Ironclaw_Sabatons,id=139220,bonus_id=1806
finger1=twicewarped_azsharan_signet,id=139238,bonus_id=1806,enchant_id=5427
finger2=grubby_silver_ring,id=139236,bonus_id=1806,enchant_id=5427
trinket1=swarming_plaguehive,id=139321,bonus_id=1806
trinket2=twisting_wind,id=139323,bonus_id=1806
main_hand=the_fist_of_raden,id=128935,bonus_id=744,gem_id=139264/139259/139264,relic_id=1806/1806/1806
off_hand=the_highkeepers_ward,id=128936

**Comment by aethys256** [comment]
Thanks I pushed it.
If you want to modify something, do not hesitate to Pull Request changes to the generate file.
