### ISSUE TITLE
703-03 Crashes When Simming Unholy DK

### ISSUE THREAD

**Issue by Mumush666** [simulationcraft/simc#3012]
SimC 703-03 sims my frost death knight just fine, but when I switch specs, import his armory, and start a sim, SimC just crashes.  Every time.  Character Name:  Gölgoth

**Comment by navv1234** [comment]
Need a region and a server as well.

**Comment by Mumush666** [comment]
Area 52-US

**Comment by pabloogc** [comment]
Same here, program crashes when I simulate this character: 
http://eu.battle.net/wow/en/character/uldum/Skellyvac/simple

**Comment by pabloogc** [comment]
Looks like the crash is related to the frost legendary belt. If I sim without it it works fine.

**Comment by Collisionc** [comment]
I believe this was recently fixed, try the latest 710-01 download: http://downloads.simulationcraft.org/?C=M;O=D

**Comment by navv1234** [comment]
No, was not fixed, but is now in c37280510b6599035620a748fc087908abb0fe59.
