### ISSUE TITLE
710-01 Fire Mage problem

### ISSUE THREAD

**Issue by Krisko94** [simulationcraft/simc#3013]
Not sure if this is the right place to report this problem but I hope someone sees it. 
In the newest build (SimcSetup-710-01-Win64.exe 2016-10-23 05:18    44M) and the one up on the site for raid results (http://www.simulationcraft.org/reports/Raid_T19P.html) Fire mages Fire Blast never crits, making the spec way worse than it really is.

**Comment by Collisionc** [comment]
Thanks, used the wrong spell id since there are now 3 ranks on fire blast.
