### ISSUE TITLE
710-01 Outlaw Rogue: Greenskin's Waterlogged Wristcuffs APL

### ISSUE THREAD

**Issue by Eowyndra** [simulationcraft/simc#3016]
@Aethys256 

Currently the OTL APL only uses Between the Eyes if Shark Infested Waters is up (for the crit bonus).

"actions.finish=between_the_eyes,if=equipped.greenskins_waterlogged_wristcuffs&buff.shark_infested_waters.up"

If I didn't make a mistake it seems that using Between the Eyes on cooldown even without SiW  is a substantial damage increase with the Greenskin's bracers, Blunderbuss trait and Quick Shot talent.

Here is my /simc string if you want to run some tests:

rogue="Eowyndra"
level=110
race=undead
region=eu
server=frostwolf
role=attack
professions=alchemy=800/enchanting=776
talents=3113222
spec=outlaw
artifact=44:0:0:0:0:1052:1:1053:1:1054:1:1056:1:1057:1:1059:2:1060:3:1061:3:1062:3:1063:3:1064:3:1065:3:1066:3:1348:1

head=,id=141453,bonus_id=1482/3336
neck=,id=130236,enchant_id=5439,bonus_id=3401/689/600/669,gem_id=130221
shoulder=,id=134374,enchant_id=5442,bonus_id=3418/1542/3337
back=,id=137483,enchant_id=5435,bonus_id=3418/1532/3337
chest=,id=137514,bonus_id=3416/1808/41/1522/3336,gem_id=130219
shirt=,id=98082
wrist=,id=137099,bonus_id=1811
hands=,id=137509,bonus_id=3416/1808/1522/3336,gem_id=130219
waist=,id=134199,bonus_id=3416/1808/1527/3336,gem_id=130222
legs=,id=137069,bonus_id=1811
feet=,id=134441,bonus_id=3414/1527/3337
finger1=,id=134524,enchant_id=5427,bonus_id=3411/1808/42/1507/3336,gem_id=130219
finger2=,id=130230,enchant_id=5430,bonus_id=3361/689/601/669,gem_id=130221
trinket1=,id=139329,bonus_id=1805/1487
trinket2=,id=141585,bonus_id=1522/3337
main_hand=,id=128872,bonus_id=742,relic_id=1807:1472/1727:1502:3336/1727:1492:1813,gem_id=139260/137472/137365/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0

If you have any questions, just highlight me on discord @Eowyndra

Thanks!

**Comment by aethys256** [comment]
Solved in:
https://github.com/simulationcraft/simc/commit/4d4ac42d64531816ae0e3a5420d640a6cb92bdb1
