### ISSUE TITLE
Feral APL broken

### ISSUE THREAD

**Issue by Tomslack** [simulationcraft/simc#3018]
Reported this to pawkets on discord but will report here too,

https://www.diffchecker.com/VcpmhROQ

Has quite heavily broken feral's rotation, looks like its no longer casting healing touch for bloodtalons, or ashamane's frenzy

Needs reverting to this version 

http://pastebin.com/gy859jXH

This is the previous version with HT replaced with regrowth

Thanks

**Comment by Collisionc** [comment]
Thanks, fixed.
