### ISSUE TITLE
DK Rune Regen

### ISSUE THREAD

**Issue by rfmaida** [simulationcraft/simc#3019]
Not being able to access rune regeneration times is making it increasingly difficult to craft accurate APLs for DKs, most notably Frost. There are some hacky workarounds we've gotten for Machinegun builds, but the accuracy of the sim still suffers by not knowing how long until another rune is available. An experimental build using Gathering Storm is all but impossible to sim, because knowing how long until the next rune is usable is crucial to the build.

Documentation currently shows that there isn't any way to track this ( https://github.com/simulationcraft/simc/wiki/DeathKnights ) - are there already plans to change this, or is there some bug/technical limitation blocking it? It'd be immensely useful if this could be implemented.

**Comment by navv1234** [comment]
I'll try to get some rune regen expressions back in shortly, if you need it. When I rewrote the rune regen system a few months back I tried to ask people if anyone used them, and the consensus then seemed to be that they are not really needed or something.

**Comment by boogyness** [comment]
Hello,
I agree with rfmaida. I would be really helpful if we could know when a rune will be charged and how many runes are currently up!
Thanks a lot for your work on SimulationCraft. It's a wonderful tool!

**Comment by navv1234** [comment]
710-01 adds "rune.time_to_X" expression, which returns the time it will take the death knight (with current regeneration rate) to get X full runes. Is this sufficient or do you need more elaborate tools to express what you need?
