### ISSUE TITLE
Can't plot dps for tank

### ISSUE THREAD

**Issue by OrcinusDrake** [simulationcraft/simc#3020]
Scaling plot doesn't seem to work for dps on my tank.

scale_over=xxxx
dps_plot_stat=haste,crit_rating,mastery,versatility

xxxx = dps, I get a dtps plot
xxxx = raid_dps, I get a dtps plot
xxxx = raid_hps, I get a dtps plot
xxxx = tmi, I get a tmi plot
xxxx = dtps, I get a dtps plot
xxxx = default, I get a dtps plot
xxxx = hps, I get a hps plot

I know I can get scale factors, but I want to know whether those factors I'm getting are just because my gear is in a quirky spot or if I really should be stacking certain stats for damage.

**Comment by ManagerWoW** [comment]
Adding to this:  The GUI doesn't have any Scale Over options for plots, like scaling does. It is always DTPS for tanks.

Scaling: http://manager.heroicstrike.org/2016-10-24_02-29-51.png
Plots: http://manager.heroicstrike.org/2016-10-24_02-28-59.png

**Comment by seanpeters86** [comment]
closing due to stale
