### ISSUE TITLE
710-01 Retribution Paladin

### ISSUE THREAD

**Issue by tomtim90** [simulationcraft/simc#3021]
Using the newly revised Blade of Wrath talent with the default APL does not work. I've gotten around this by adding:

`actions+=/call_action_list,name=VB,if=talent.blade_of_wrath.enabled` 

since in theory it should be the same priority list as VB, but BoJ will be usable more often. 

By doing that it then sims fine and the sims reflect that CD reset behavior showing more TV usage and more BoJ usage.

**Comment by ubersonic** [comment]
Where are you adding that?

I tried putting it in overrides but it crashed the Sim
