### ISSUE TITLE
Frost DK Crashes

### ISSUE THREAD

**Issue by Mumush666** [simulationcraft/simc#3022]
While simming my Frost DK running Crit/Haste/Mastery plots SimC crashes.  I have reproduced the crash 10 times in a row.
![untitled](https://cloud.githubusercontent.com/assets/22685801/19655055/b1a63614-9a2b-11e6-9053-6d60e5369977.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/22685801/19655059/b79c559e-9a2b-11e6-9216-88d8e20d75f3.jpg)

**Comment by scamille** [comment]
Please attach the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file generated when you start the simulation.
This helps us reproduce the problem.

Your original title simc version: simc-710-01-win64-a151e0a 2016-10-24 06:22

**Comment by Mumush666** [comment]
How do I attach the file to a post?  I keep getting "We don't support that file type."

**Comment by scamille** [comment]
hum rename to .txt or copy-paste it into a code section, see https://guides.github.com/features/mastering-markdown/ .

**Comment by Mumush666** [comment]
[simc_gui.txt](https://github.com/simulationcraft/simc/files/549581/simc_gui.txt)

**Comment by Mumush666** [comment]
I was able to sim my Frost DK successfully with the latest version posted on the index.  Thank you!
