### ISSUE TITLE
[Warrior] Heroic_Charge not charging after a heroic_leap

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#3024]
If I understand it correctly, the heroic_charge action should either heroic leap out and charge back in or simulate walking out and charging back in if heroic leap is unavailable at the time, but it currently seems to never charge whenever it uses heroic leap and instead just causes a wait event after using the leap. I'm currently working around it by just adding heroic_leap to the action list so its CD is always burned immediately and it doesn't cause a heroic charge to fizzle.

E.g. the simple action stats table shows data like this when heroic_leap isn't deliberately burned every CD:

| Simple Action Stats | Execute | Interval |
| --- | --- | --- |
| Charge | 22.5 | 17.41sec |
| heroic_charge | 31.5 | 12.02sec |
| Heroic Leap | 10.2 | 38.88sec |

And looks like this when it is burned on CD:

| Simple Action Stats | Execute | Interval |
| --- | --- | --- |
| Charge | 23.7 | 16.80sec |
| heroic_charge | 23.0 | 16.64sec |

**Comment by Collisionc** [comment]
Should be fixed now. It'll just run the simulation a little slower, as it was only checking charge when the gcd was available, which sometimes happened after the warrior had lept out, and had already walked in a few yards inside of charge's minimum range. Now it's checking every 0.1 seconds.

**Comment by amulder87** [comment]
It looks like heroic_charge doesn't charge at all now. Leap appears to be used still, but only 1 charge action from the one on pull happens.

Edit: Scratch that, discovered the default_actions setting and disabled that so my APL activates. Looks like it's all working well now, thanks!

**Comment by amulder87** [comment]
Actually, my APL is just being ignored and it's always loading the default APL or something?

**Comment by Collisionc** [comment]
Set default_actions=0 I made a silly change
