### ISSUE TITLE
Nature's Call Cleansed Drake's Breath Issue

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3025]
there is a problem with one of the 4 procs of the Nature's Call trinket,
i did multiple 400 second simulations and ended up with ~4 procs of it, listed in the Simple Action Stats frame.
The problem behind is, that there is no damage registered for it.

**Comment by devlinate** [comment]
I would like to add to this as I've also not seen it show up as a damage source in simc. 

I ran some tests on a dummy for ~45 minutes with an 865 natures call, here's the log if it's of any use:
https://www.warcraftlogs.com/reports/k9qMxKAGLH6ycDaj#type=damage-done&source=5

**Comment by navv1234** [comment]
What class/spec is this WCL log made with? It's likely there are some multipliers affecting the damage, since satyr seems to be inflated by roughly 25.8%

**Comment by navv1234** [comment]
Nature's Call drake breath is currently there. Closing.
