### ISSUE TITLE
Elemental Shaman APL missing aoe

### ISSUE THREAD

**Issue by alexmbits** [simulationcraft/simc#3026]
Hello,

Ever since commit cf479061d67cb513e3b8549cf8e7c0aaae66aa7 Earthquake Totem was removed from both AoE rotation and from single target in case of legendary shoulders (Echoes of Great Sundering).

I don't know if that means Earthquake Totem isn't viable anymore or someone forgot to add it?

Thank you for awesome program :)

**Comment by Collisionc** [comment]
The name of earthquake totem was changed to earthquake in 7.1, just needed to update that.
