### ISSUE TITLE
[Hunter] non-Patient Sniper Vulnerable stack count

### ISSUE THREAD

**Issue by Jayezi** [simulationcraft/simc#3027]
For 7.1, I see the Vulnerable buff being given the old stack count of 3 instead of the new 2 but each buffing damage by the new 50% instead of the old 25%. Sims show inflated dps numbers as non-Patient Sniper builds are getting a full time damage buff equal to Patient Sniper's temporary buff.

**Comment by nasirabtw** [comment]
Fixed in 0c81b9ecba8d6a154d62cebd818bc47ad7b7a7cc
