### ISSUE TITLE
Cant Launch Simcraft

### ISSUE THREAD

**Issue by dmelt** [simulationcraft/simc#3028]
Cant get Simcraft to work. Here is the error i'm getting in Windows Event Viewer. Please let me know if anyone can help navigate me through this issue.

Faulting application name: SimulationCraft.exe, version: 0.0.0.0, time stamp: 0x57f4064e
Faulting module name: Qt5Core.dll, version: 5.6.0.0, time stamp: 0x56d82c24
Exception code: 0xc0000005
Fault offset: 0x00000000000b0493
Faulting process id: 0x15e0
Faulting application start time: 0x01d22f0b61252d65
Faulting application path: C:\Simulationcraft(x64)\703-03\SimulationCraft.exe
Faulting module path: C:\Simulationcraft(x64)\703-03\Qt5Core.dll
Report Id: 9f6a3763-9afe-11e6-93c0-0014d1fa2033

**Comment by Collisionc** [comment]
This was (probably) fixed since 703-03

try the latest versions at the top : http://downloads.simulationcraft.org/?C=M;O=D

**Comment by dmelt** [comment]
I downloaded the top file > extracted to my desktop > moved the file to Program Files (x86) folder > Tried to run Simcraft.exe...No Workie! 

```
On Tuesday, October 25, 2016 9:47 PM, Alex <notifications@github.com> wrote:
```

 This was (probably) fixed since 703-03try the latest versions at the top : http://downloads.simulationcraft.org/?C=M;O=D—

**Comment by Collisionc** [comment]
Try disabling your antivirus temporarily, redownloading, and then re-running the program.
