### ISSUE TITLE
Ring of Collapsing Futures

### ISSUE THREAD

**Issue by Thepiegod** [simulationcraft/simc#3029]
The active on this ring does not appear to be accounted for in sims

**Comment by Collisionc** [comment]
Added here - https://github.com/simulationcraft/simc/commit/86c346c7177cc03387ddf39766268d35398355ed 

Recent nightly builds will have it, and you can check that you currently have 2 stacks of temptation debuff with this: 
buff.temptation.stack<2

**Comment by mythrilgolem** [comment]
for others, this looks like:

actions+=/use_item,name=ring_of_collapsing_futures,if=buff.temptation.stack<2
