### ISSUE TITLE
Can't import Protect Paladins' relics.

### ISSUE THREAD

**Issue by v3rd1shax** [simulationcraft/simc#3030]
I imported  Slootbag's (A prot pal) armory: 
[http://eu.battle.net/wow/en/character/twisting-nether/Slootbag/advanced](http://eu.battle.net/wow/en/character/twisting-nether/Slootbag/advanced)

and found there is no gem_id but only relic_id in the player profile. and after I ran simulate the client just crashed. Here is the weapon part:

```
main_hand=oathseeker,id=128867
off_hand=truthguard,id=128866,bonus_id=736,relic_id=3418:1532:3337/1806:1502/1806:1507:3336/0
```

And I checked another paladin Treckie:
[http://eu.battle.net/wow/en/character/tarren-mill/Treckie/simple](http://eu.battle.net/wow/en/character/tarren-mill/Treckie/simple)
and got the same result, the gem_id is missing and I cannot know which relic he is using.

**Comment by navv1234** [comment]
This should be fixed in 710-01 release, so closing.
