### ISSUE TITLE
[Death Knight] Frozen Pulse sims about 50-60% too low

### ISSUE THREAD

**Issue by gixxpunk** [simulationcraft/simc#3031]
As already discussed here: https://github.com/simulationcraft/simc/commit/6d6483667c67642baafce2485ef4faf07049126d Frozen Pulse currently sims about 50-60% too low.

 Simc shows 7-8%. Ingame 12-13%.

http://abload.de/img/fp_borked76bkg.jpg

**Comment by gixxpunk** [comment]
For OB+RA playstyle this override brings numbers more in line to what we see ingame:

`override.spell_data=effect.287339.ap_coefficient=1.05`

**Comment by gixxpunk** [comment]
Had a deeper look at FDK APL and stripped it down to the absulute minimum and exactly the same how i use it ingame. Sadly this did change nothing for FP uptime. Then I had a closer look at the results page of my sims and found something imho strange:

auto_attack_mh = 209.44 executions
frozen_pulse = 154.46 executes
frozen_pulse_1 = 91.17%

Those numbers imho do not match. If we assume an uptime of 90% at 209 mh auto attacks, this should generate 188 frozen_pulse ticks and not only 154.

Looks like we miss 22% of all FP ticks. Is there something wrong with the internal calculation? Or maybe haste not included in some calculations?

@navv1234
Could you please have a look at this?

**Comment by navv1234** [comment]
Misses do not generate Frozen Pulse in simc.

**Comment by gixxpunk** [comment]
So looking at my Recount ingame screenshot, this would bring us following numbers:

422 melee hits (mh+oh) at 24% miss chance -> 555 hits (mh+oh) without miss chance
555/2 -> **277,5 mh attacks**

My Recount screenshot shows 284 Frozen Pulse ticks. Those numbers imho are close enough to give it a shot and change FP trigger to also proc from misses.

What do you think?

**Comment by navv1234** [comment]
I think it should be looked at from a combatlog.

**Comment by gixxpunk** [comment]
Looked at a few Ursoc (normal) logs:

melee casts (melee hits) -> frozen pulse ticks
152 (126) -> 75
171 (141) -> 100
168 (138) ->94
140 (124) -> 90

**Comment by navv1234** [comment]
Looking at WCL logs, it procs from both hands, not just main hand.

EDIT: And does not proc from misses.

**Comment by gixxpunk** [comment]
This would probably double it's damage and bring it to ~15% of our overall damage in simc. I have not seen such high FP numbers ingame even with huge packs of mobs. Also Recount would have shown nonsense for me when I tested with only oh equipped.

**Comment by navv1234** [comment]
https://www.warcraftlogs.com/reports/8JHaRvwgtQz3BXGc#fight=10&type=damage-done&source=8&view=events&graph=false&pins=2%24Off%24%23244F4B%24any%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%24195750%7C-32%7C1

**Comment by gixxpunk** [comment]
Well, looks like you are right. Never trust Recount! Sorry for all the hassle... :(

**Comment by ssateneth** [comment]
I just tested ingame that frozen pulses DO trigger from both main hand autoattacks AND offhand autoattacks. Doesn't seem to matter if the attacks are synced or desynced.

Synced: https://gyazo.com/b327c0338b7c687880167060dccdb5fb
Desynced: https://gyazo.com/f721adc21da1bd3c90ac4255f2a30e75

Combat log doesn't seem to discern between MH and OH autoattacks, but can tell which is which based on how hard it hit. Can see 5 pairs of AA hits followed each followed by a pair of FP hits on the first screenshot, and a 7 consecutive melee autoattacks each followed by their own FP on the second one

Misses definitely do not cause FP to proc either, as seen in this SS.
https://gyazo.com/b509498c572a15a19b906ae952cb4b29

**Comment by gixxpunk** [comment]
So after the revert to mh+oh we are now back to nearly 15% for FP in simc. I now use this override to bring it back to reality:
`override.spell_data=effect.287339.ap_coefficient=0.58`

I also use a different core APL, as it provides more DPS (ST and AOE):
http://pastebin.com/24WZLERB
Feel free to test the new APL and tell me your opinion.

**Comment by ssateneth** [comment]
Since FP activates on 1 or less runes instead of 0 runes now, will need to wait for rune system overhaul to better craft a FP APL (Talking about telling us information about partial runes, how far they are charged. This means possibly not using a 1 rune ability if another rune is immediately about to come off cooldown so you can obliterate instead for more damage and a possible Rime proc)

I should also note that with FP, you get a minor gain by not using Obliteration cooldown until you have (edit) 2 or less (edit) runes left. Also another minor gain if you don't use sindragosa's fury until you have both pillar of frost AND unholy strength up (Not FP specific).

I also tried your different core APL, doesnt seem to work in my favor, lose about 0.1% DPS with it, due to the obliteration frost strikes being pushed further down.

**Comment by ssateneth** [comment]
Going to bump this since I noticed a large (>2%) gain by not spamming howling blast with FP talent selected. Probably also goes for frostscythe. Remorseless winter is still good to use on cooldown though, probably since it fills a GCD and uses a rune if it can't obliterate, keeping FP uptime higher, as well as being good damage on its own.

**Comment by navv1234** [comment]
No clue about what "rune system overhaul" is, I will add a "how long will it take me to get X runes" expression at some point. If you need/want something else, you are going to need to spell it out.

As for adjusting the AP coefficient, that makes little to no sense unless we know the client data is actually wrong (individual FP hits are doing completely wrong damage).

**Comment by rfmaida** [comment]
There's most certainly something broken with Frozen Pulse in SimC right now, It definitely procs off both MH and OH in-game:
![fp_uptime_game](https://cloud.githubusercontent.com/assets/22973530/19826575/1d7eaeba-9d5c-11e6-84ce-d014f4b59072.png)
(as you can see, the offhand hits, 9k base/18k crit, and mainhand hits, 18k base, both proc FP)

But that uptime doesn't match up with sims - take, for example, this one, where there were a combined 436.6 MH/OH hits, but only 135.6 FP hits... when the majority of the fight was spent below 1 rune:
![fp_uptime_sim](https://cloud.githubusercontent.com/assets/22973530/19826564/f3695f80-9d5b-11e6-9757-28f21756ed43.png)

[(sim results page here)](https://drive.google.com/file/d/0B8cguQM4dM2GM203OFk5c2pXbFU/view?usp=sharing)

**Comment by gixxpunk** [comment]
What talents did you use? Are you using nightly builds?
I have never seens such low FP values in simc after this patch:
https://github.com/simulationcraft/simc/commit/924acbc36e61120957955591a1930f5d3e7fa64e

**Comment by ssateneth** [comment]
@rfmaida this has already been fixed, check nightly builds if you can't compile your own copy. http://downloads.simulationcraft.org/?C=M;O=D

**Comment by ssateneth** [comment]
This ticket can probably be closed as the original issue has already been fixed.

**Comment by navv1234** [comment]
Okay, we can revisit this if you guys uncover something wrong with the frost stuff. 710-01 release includes the rune.time_to_X expression that may or may not let you test things out. Closing for now.
