### ISSUE TITLE
Ursoc's Rending Paw pooling damage when refreshed and snapshotting stats/vulnerabilities

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#3036]
Starting in 7.1, the proc started pooling the dot damage when refreshed(like how corrupted blood of zakazj works) instead of just refreshing the base damage. It also snapshots all stats when applied or refreshed including temporary buffs(like Battle Cry) and target debuffs(like Colossus Smash).

A great example of damage ticks from [a log](https://www.warcraftlogs.com/reports/Qg7xbM19B4rNjDyW#fight=18&type=damage-done&source=76&ability=221770&view=events) after patch, with relevant buffs/debuffs added in:

```
00:02:36.066    Ursoc is afflicted by Colossus Smash from Plka
00:02:36.683    Plka gains Battle Cry from Plka
00:02:37.195    Ursoc is afflicted by Rend Flesh from Plka
00:02:39.206    Plka Rend Flesh Ursoc Tick *54506*
00:02:40.338    Ursoc's Rend Flesh is refreshed by Plka
00:02:41.218    Plka Rend Flesh Ursoc Tick *77911*
00:02:41.684    Plka's Battle Cry fades from Plka
00:02:43.228    Plka Rend Flesh Ursoc Tick *77911*
00:02:43.485    Ursoc's Rend Flesh is refreshed by Plka
00:02:45.204    Plka Rend Flesh Ursoc Tick 46288
00:02:47.216    Plka Rend Flesh Ursoc Tick 46288
00:02:49.214    Plka Rend Flesh Ursoc Tick 46288
00:02:49.335    Plka's Colossus Smash fades from Ursoc
00:02:51.206    Plka Rend Flesh Ursoc Tick 46288
00:02:53.211    Plka Rend Flesh Ursoc Tick 46288
```

The first tick of the first application did 54506 damage, so it would do a noncrit damage of 27253 per tick for 4 ticks for 109012 damage total. CS is factored in there, but I'm not going to bother factoring it out since it affects all of these ticks. After being refreshed once, it ticks for 77911 damage, and would have ticked 5 times at that amount for a total of 444061 damage from both applications, giving us a damage for the second application before crits are applied of (444061/2)-109012 = 113018.5 damage. The last refresh happens after BC fades so only about a 10% crit chance is snapshotted for the rest, and none of them happen to crit. The total base damage factoring out crits across all 3 applications would be 336604, so the last application would have dealt 114573.5 damage on its own. When CS fades, the already applied debuff is unaffected and continues to tick at the previously snapshotted value.

Timeline with this analysis:

```
Dot applied, CS+BC snapshotted, base damage(including CS) of 27253 for 4 ticks
critical tick of 54506, 81759 remaining in pool
refresh adds 113018.5 damage to pool for a total of 194777.5, BC+CS still snapshotted, new base tick damage is 38955.5 for 5 ticks
critical tick of 77911, 155822 remaining in pool
BC fades, still snapshotted
critical tick of 77911, 116866.5 remaining in pool
refresh adds 114573.5 damage to pool for a total of 231440, CS still snapshotted, BC isn't, new base tick damage is 46288 for 5 ticks
3 rend ticks @ 46288
CS fades, still snapshotted
2 rend ticks @ 46288
```

**Comment by Collisionc** [comment]
That was way easier than I thought it'd be.
