### ISSUE TITLE
Outlaw bug: True Bearing + Between the Eyes

### ISSUE THREAD

**Issue by NetRollTUZ** [simulationcraft/simc#3037]
In current (and all previous) version in outlaw spec., with buff True Bearing Simc thinks BtE self-reduce CD on cast. In game it is only visual:
1) Sometimes BtE don't self-reduce CD (best variant, coz don't confuse)
2) Sometimes game client show self CD reduce after casting BtE, but you can't use it. In this case character will try to cast (you will see starting animation and flash), but can't finish it. I guess this is just client-server desync.

So SimC long time overrate Legendary bracers and Blurred Time perk.
http://puu.sh/rWB2f/c69371ae32.png

**Comment by mrdmnd** [comment]
Interesting. Do you have a screen cap demonstrating this? cannot recreate at work.

**Comment by NetRollTUZ** [comment]
I make short video after raid night. Guess it will be more revealing.

**Comment by mrdmnd** [comment]
Thank you, that'll be useful.

**Comment by NetRollTUZ** [comment]
Video example of bug in game: https://youtu.be/XM0T_OF5Ktw
In SimC in "Sample Sequence Table" with legendary bracers: http://puu.sh/rXelI/32d4cfae75.png

**Comment by NetRollTUZ** [comment]
Because after my ingame bug-reports on EU+US it still ig game, I guess nobody read them, so I did post on US forum: http://us.battle.net/forums/en/wow/topic/20749868430?page=1#post-1
Maybe it helps a bit, but anyway till fix it may be months. Or they simpy remove BtE from buff.
So I think fix in SimC may help us a lot in a real evaluation of legendary bracers today.

**Comment by aethys256** [comment]
Thanks for the detailed report, I'll disable it for the moment.

Fixed in https://github.com/simulationcraft/simc/commit/e9decde963da7733073d4c7c7678a10a5f3b2712
