### ISSUE TITLE
Crashes as soon as I hit simulate

### ISSUE THREAD

**Issue by omidimaru** [simulationcraft/simc#3039]
Hey, so as the title says.
DxDiag:              http://pastebin.com/d7P8AWzC
simc_gui.simc:    http://pastebin.com/Ai7FZkiB
profile:                http://pastebin.com/NV2Jd37j

Any help would be appreciated - tried the 32 and 64 bit, both the same result. Crashes as soon as I hit simulate

**Comment by Collisionc** [comment]
This is an issue that was fixed a few days ago, I tried the sim_gui.simc file out and it works fine on the newest version. Try it out at the top of this page: http://downloads.simulationcraft.org/?C=M;O=D

We'll have an official release sometime soon.

**Comment by omidimaru** [comment]
worked beautifully, thank you
