### ISSUE TITLE
[Druid] Balance spec Astral power bug

### ISSUE THREAD

**Issue by Talonmies90** [simulationcraft/simc#3042]
Boomkins primary astral power generator, Solar Wrath, does NOT create any astral power on current simcraft version.

This bug is visible on the front page simulations

From http://www.simulationcraft.org/reports/Raid_T19H.html
Resource GainsTypeCountTotalAverageOverflow
new_moon Astral Power 7.88 78.75 (8.51%) 10.00 0.00 0.00% 
half_moon Astral Power 7.53 150.54 (16.27%) 20.00 0.00 0.00% 
full_moon Astral Power 7.13 285.39 (30.85%) 40.00 0.00 0.00% 
moonfire Astral Power 14.36 43.07 (4.66%) 3.00 0.00 0.00% 
sunfire Astral Power 1.00 3.00 (0.32%) 3.00 0.00 0.00% 
lunar_strike Astral Power 22.29 364.37 (39.39%) 16.35 0.00 0.00%

**Comment by Tomslack** [comment]
Override being used to ameliorate this bug is 

override.spell_data=effect.280099.base_value=80

**Comment by Collisionc** [comment]
I fixed this here: https://github.com/simulationcraft/simc/commit/2127af789053c7b2d079b911dc677dae309d7e4d 

Should be in the latest nightly version.
