### ISSUE TITLE
Shadowpriest - SimC tanking haste

### ISSUE THREAD

**Issue by joebywan** [simulationcraft/simc#3043]
Haste is a primary stat for spriests, but Simulationcraft wants me to tank it way below 20%. I've read that apparently it's not handling working with surrender to madness?  Is this part of it?

Anyway, just hoping bringing it to attention might help it get sorted.

Thanks :)

**Comment by N1gh7h4wk** [comment]
Did you use a Surrender to Madness APL, or just Legacy of the Void builds?
For Legacy of the Void, haste is much more devalued, especially with the Auspicious Spirits talent.

**Comment by joebywan** [comment]
Is there a guide on doing this? I've just been importing my toon and getting it to sim.

⁣​

**Comment by N1gh7h4wk** [comment]
I'm not sure about guides, but for shadow priests with surrender to madness, there are some problems with simcraft. They may be resolved with my latest proposed changes, but that's yet to be implemented. The timing of the start of surrender to madness is harder to implement than you might think.

**Comment by joebywan** [comment]
Ok, well what are you talking about with using a StM APL?  How would I do this, is it obtainable on the website?

**Comment by N1gh7h4wk** [comment]
If you import your toon with the newest nightly build of simcraft, it should work relatively fine, when using surrender to madness as talent.

**Comment by joebywan** [comment]
Think it might need a bit of tuning, it now thinks haste is worth less than versatility, and that apparently I can do 450k dps.

**Comment by N1gh7h4wk** [comment]
It would be easier to see, if you included a simcraft report, like the .html file.
Also, if you have more than 10k haste, this is expected.

**Comment by N1gh7h4wk** [comment]
I reviewed the trigger, seemed to still have too much haste influence, made a pull request for the new one.

**Comment by joebywan** [comment]
It wouldn't let me upload the html directly, had to zip it.

For some reason now it's sorted it's haste issue out, but it's still saying I should be pulling 400k+ dps.  I've maxxed a 500k peak once when I was under blood lust, lingering & power infusion (140%+ haste for the win), but still wasn't 400k overall.

[results_html.zip](https://github.com/simulationcraft/simc/files/570404/results_html.zip)

Is there a different boss I should be using or something?  I also don't usually pot/flask/food as I'm too poor atm.  Are they enabled for this?

Also my belt is giving me +2 charges of Mind Blast, is this taking those into account?

**Comment by N1gh7h4wk** [comment]
Looks fine to me. Also note that it's a simulation of what is possible, sometimes the decision making in the sim cannot be matched 100% since its going so fast for s2m. From my in game experience, i'd say it is possible to pull those numbers over that fight duration, but still those are numbers you obtain when playing very well (95+ %tile). 
The Legendary belt should increase your dps by 5-10%.
The sim is using pots, flask and food.

**Comment by joebywan** [comment]
Is there a way to stop it using pots/flask/food?

I get that the belt will increase dps, I was asking whether the sim is actually using the 3 charges.

**Comment by N1gh7h4wk** [comment]
Simc will use all three charges.
To stop using flask, food, pots and runes you need to remove some lines.
`actions.precombat=flask,type=flask_of_the_whispered_pact
actions.precombat+=/food,type=azshari_salad
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/potion,name=deadly_grace
actions=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=40|(buff.voidform.stack>80&buff.power_infusion.up)`
