### ISSUE TITLE
Importing Demonology Artifact

### ISSUE THREAD

**Issue by YepItsEuko** [simulationcraft/simc#3047]
By default, importing a demonology character's b.net profile does not import the artifact/relic information. This was done on the 10/27 (I believe that was when I downloaded?) 710-01 build. I love the changes made for destro sims, but now I can no longer (easily) sim my demo spec.

**Comment by navv1234** [comment]
Would need to have region/server/char, I fixed the demo artifact import issues (more generally, non-mainhand artifact import issues) and it should be in 710-01 that is out right now.

EDIT: Closing this for now, if it still does not work just reply here with the above info and I'll take a closer look.
