### ISSUE TITLE
Survival Hunter - 7.1 Fix - Pet Auto Attacks can proc Hunting Companion (Survival Mastery) & Related issues.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3048]
Previously, only "special" attacks (Basic Attacks, Thunderstomp (tenacity-only) and pet-racial special abilities (example: http://www.wowhead.com/spell=24423/bloody-screech) could have a chance to proc Hunting Companion. Now auto attacks can do it too. The same goes for Growl, the pet taunt. Since bosses cannot be taunted, it is advised to have Growl enabled for the extra chance. Silly, I know.

Things that lack implementation are, in order of priority-ish:
- Pet auto attacks.
- Growl (pet taunt, the good old one)
- Pet special abilities (like Bloody Screech).
- Tenacity-only ability Thunderstomp (it's not really worth going Tenacity but it'd be nice to be able to sim it).

All of these things will provide a sizable buff to Survival Hunter damage, as well as buff its Mastery value significantly in sims.

**Comment by nasirabtw** [comment]
Pet Attacks, Basic Attacks, and Flanking Strike added in d514aae7baefe7823d42f8a1af80c799004e2bbb

Still need to add growl, special attacks, and thunderstomp.

**Comment by nasirabtw** [comment]
Pet Special Abilities and Growl added in 67aa884f4d288ad0597402f31a35e45cc65d6620

**Comment by Collisionc** [comment]
I think these are fixed, but please let me know if they aren't.
