### ISSUE TITLE
Survival Hunter - Animal Instincts 7.1 implementation.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3049]
This tier 1 talent was revamped in 7.1.

Whenever you cast Flanking Strike, you will have a cooldown reduction of 3 seconds on a random one of the following abilities:

Flanking Strike itself
Mongoose Bite
Aspect of the Eagle
Harpoon

Things to know:
- If a spell is already off cooldown, it will skip it. That way you will never waste the benefit.
- For example, if everything is available to cast except Flanking Strike, it will always reduce the cd of Flanking Strike (the one that you just put on cooldown).
- The CD reduction (base of 3 seconds) is reduced by Haste. 15% Haste is a 15% reduction in the cooldown reduction.
  So.
  10% Haste = 2.7 second reduction.
  20% Haste = 2.4 second reduction.

The latter is presumably implemented because Haste reduces the cooldown of most major Survival abilities altogether.

**Comment by nasirabtw** [comment]
Added in d514aae7baefe7823d42f8a1af80c799004e2bbb
Still need to add proc tracking for which spell it triggered on.

**Comment by nasirabtw** [comment]
Added proc tracking and fixed bugs.
