### ISSUE TITLE
Simcraft doesnt recognize Kara relics (balance)

### ISSUE THREAD

**Issue by Vikerules** [simulationcraft/simc#3051]
Just put in a new relic i got from Kara with BiS relic stat/effect and my dps dropped about 50k when i simmed. Checked gear and it shows weapon at ilvl 841 when it should be 887. The relic was from The Curator, Fauna Analysis Widget for balance druids

**Comment by navv1234** [comment]
703-series simulationcraft does not have kara items, we released 710-01 recently, which should fix this issue.
