### ISSUE TITLE
[Druid] Feral - Bug with Regrowth and Ailuro Pouncers Legendary effect

### ISSUE THREAD

**Issue by MoonBunnie** [simulationcraft/simc#3052]
Ailuro Pouncers Legendary, when equipped (feet=ailuro_pouncers,id=137024,bonus_id=1811), is correctly allowing the Predatory Swiftness buff to stack to 3, and is periodically granting a new stack every 15 seconds. However, Regrowth is consuming all stacks of Predatory Swiftness when cast currently. This behavior is incorrect as each cast of Regrowth should only consume a single stack of Predatory Swiftness. See attached image for evidence where Predatory Swiftness goes from 2 stacks to 0 after a single cast of Regrowth. 
![psbug](https://cloud.githubusercontent.com/assets/5158073/19790161/deac61c4-9c6a-11e6-96f0-7c0818806028.PNG)

**Comment by Fruchuxs** [comment]
I can confirm this wrong behavior.

**Comment by Collisionc** [comment]
Thanks for reporting, will be fixed in next version.

**Comment by Tiswone1994** [comment]
Still not fixed.

https://github.com/simulationcraft/simc/issues/3322
