### ISSUE TITLE
[Rogue] Outlaw - Unable to sim for speed scaling (Thraxi's Tricksy Treads)

### ISSUE THREAD

**Issue by Strudelninja** [simulationcraft/simc#3055]
At the moment you are unable to get stat weights or scale factors for movement speed. For all the Outlaw Rogues with Thraxi's it's extremely important to know so that you can consider speed stat, movement speed buffs and equipment effects when minmaxing your dps.

**Comment by navv1234** [comment]
I added speed scaling possibility (and autodetection if the boots are equipped), should be in 710-01. The results seem a bit odd though.

**Comment by VeryRare** [comment]
@navv1234  Hey Navv, I know this issue is closed but I was wondering if their was any update on Thraxi's Tricksy Treads since you said the results seem a bit odd.  Specifically with racials (Worgen sprint and NE quickness) and the bear tartar food buff.
