### ISSUE TITLE
[Paladin] Protection - judgement SotR CD reduction not working

### ISSUE THREAD

**Issue by vaelrock** [simulationcraft/simc#3056]
Here's a list of some bugs I found while playing a little with the sim to test some talents impact on dps/survivability :
### judgment does not reduce the remaining cooldown on Shield of the Righteous at all

a sim with the sample profile T19P and only those actions :

```
talents=2231122
actions=auto_attack
actions+=/shield_of_the_righteous
actions+=/judgment
```

shows 24 SotR uses.
Removing the judgment line also gives 24 uses
-> it should reduce it by 2 s on each judgment hit, and 4s on each judgment crit
### level 30 First Avenger is not working like in game

a sim with the sample profile T19P and only those actions :

```
talents=3231122
actions=auto_attack
actions+=/avengers_shield
actions+=/hammer_of_the_righteous
```

shows 35.5 Grand Crusader procs on average
changing the talents line to 3131122 to get _First Avenger_ then makes it only 38.8, meaning the sim currently considers that the 10% Grand Crusader proc boost is multiplicative (0.15*1.1) instead of additive (0.15+0.1).
I can confirm in game for sure that it's additive and you should get something like 59 procs (very fast to test).
### level 30 Crusader's Judgment

using this :

```
talents=3231122
actions=auto_attack
actions+=/judgment
actions+=/hammer_of_the_righteous
```

shows 67.5 judgment uses.
Changing the talent line to 3331122 to get _Crusader's Judgment_ shows exactly the same judgment count.
But for whatever reasons, Grand Crusader proc count jumps from 32.3 to 42.5 when it should stay the same. What is expected is at least 1 judgement more because it has 2 charges, and then ~ 32 more because of the Grand Crusader procs.
From my in-game short tests, refreshing Grand Crusader without using it still triggers the talent.

Those bugs greatly impact the simulated survivability of the Paladin Tank because judgement is the primary source of Shield of the Righteous cooldown reduction. It's currently impossible to get good weightstats because of it.

Hoping that someone can fix this in the next weeks :)

Thanks for all the work done on this fantastic tool since many years.

**Comment by bitfluxhound** [comment]
FA fixed in 24af151

**Comment by bitfluxhound** [comment]
J fixed in a9d4b3b

CJ will be fixed Soon(TM)

**Comment by bitfluxhound** [comment]
CJ fixed in db56c70

**Comment by vaelrock** [comment]
Thanks a lot ! Will test this the next nightly build :)

**Comment by vaelrock** [comment]
I don't know if I should open a new issue for it, but I found another peculiar bug with the last second tier talent Bastion of Light.

Steps to reproduce :
- import the Paladin_Protection_T19P profile
- set talents to 2031223
- add 10000 haste on the tabard (inflates the bug it seems)
- uncheck bloodlust
- run simc with default values
  -> we get 50.1 SotR uses

then :
- set talents to 2231223
- run simc
  -> we get 57.1 SotR uses with 3 Bastion of Light uses. This seem quite fine, max gain is 9 SotR, but 7 seem much more realistic.

Now the bug :
- just check blood lust
- set talents to 2031223
  -> we get 50.7 SotR uses, it seems to be a logical gain

and finally :
- set talents to 2231223
- run simc
  -> we get 63.4 SotR uses ! or 12.7 more, which is simply not possible any way you look at it.

I found it when comparing the Bastion of Light talent with the now correctly behaving Crusader's Judgment. Bastion of Light was much better when in theory it shouldn't be and quickly saw a strange amount of SotR uses.
This bug is very strange, because it is caused by bloodlust, so there might be some complex interaction in the code with it that just makes the SotR charges not simulated correctly when reset at 3 during short high haste period. The same thing seems to be happening with Seraphim.

Bastion of Light is basically just 3 free SotR. It's CD is just as a standard ability one : it snapshots your stats when starting, meaning that you should always use your haste procs before using it.
Whether it being at 0 charge or 2 doesn't change anything, the CD behaves independently of the charges.
That's why BoL is "just" 3 free SotR at max (probably 2.X in reality).

Note : Waiting to be at 3 charges of SotR before using Seraphim if your 3rd one has only 1 to 2s remaining should be a theoretical gain, albeit a very small one probably not worth adding to the APL,
But trying to get a haste cap letting you go back up to 3 charges when Seraphim is up is probably a good thing to aim for (with some more SotR uses in-between).

**Comment by vaelrock** [comment]
I'm sorry to spam here, but it seems that when the talent Grand Crusader is used in conjonction with Seraphim, the expected added SotR count is wrong.

**_Update while writing this post:**_ Well in fact, the Seraphim talent is lowering the SotR count by way too much anyway, so might be a problem with it, the APL being OK AFAIK : there's no possibility to not cast SotR if >=1.99 charges. But I removed the condition _&!(debuff.eye_of_tyr.up&buff.aegis_of_light.up&buff.ardent_defender.up&buff.guardian_of_ancient_kings.up&buff.divine_shield.up&buff.potion.up_ just to make sure.

Using the exact same setup than my previous post with bloolust :
- talents=2031223 we get 50.7 SotR for 81.1 J
- talents=2331223 we get 62.4 SotR for 133.6 J, which is what you should expect with a 11.5 to 12s SotR CD (52.5J at 11.4%crit = 117s gained, or  a little more than 10 SotR, not accounting BL)
- talents=2031222 we get 15.2 SotR for 84.1 J, 8.9 Seraphim uses ate 17.8 SotR, meaning without the talent we should have done 33 SotR, which is impossible if with the first talent test we get more than 50.
- talents=2331222  we get 22.5 SotR for 140.4 J. only 7 more SoTR with an additional 56.3 J, the Seraphim SotR bug is just inflated.

**Comment by bitfluxhound** [comment]
I'll take a look at it

**Comment by bitfluxhound** [comment]
I've improved Sera / fixed CJ bug, but it looks like there's still an issue with charges and active haste buffs (if you add 20k static haste BoL still behaves normally).

Atm need to turn off bloodlust in sims.
