### ISSUE TITLE
Incorrect Import

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3060]
http://us.battle.net/wow/en/character/khadgar/Euphrum/simple

After I upgraded my neck from 855->870 (same item) and getting a different new pants, the import isn't working correctly. As you can see on the page my average ilvl is 876, but on an import it'll say gear_ilvl=871.13. My sim dps actually went down also, even though they are clear upgrades for me. 

Last time I did an import (a day ago or so), the import worked correctly. I've been using the current stable version for a while now. The only thing I can think of that changed between now and yesterday are my gear upgrades. 

Please investigate, thanks!

EDIT: I just realized I swapped out my 2nd relic to Ruffian's Poisoned Blade (same ilvl, slightly better skill), which is a relic from Kara. Might be a Kara loot problem.

**Comment by navv1234** [comment]
Unsure where you are seeing 871.13, imported your character and it's at 876.88. Looking at debug logs, all the items agree with HTML armory item levels, and simc's html report.

**Comment by TCSybert** [comment]
Kara relics are causing issues right now.

**Comment by navv1234** [comment]
What issues, the profile above imports fine?

**Comment by TCSybert** [comment]
Not sure about his but if you do Síns - Thrall NA then I am missing a relic on import but not in game or BNET. It is missing a Kara relic that I got.

**Comment by navv1234** [comment]
I'm seeing 3 relics? 850, 860 and 845?

**Comment by TCSybert** [comment]
When I run the sim it doesn't show up. What version are you using?

**Comment by navv1234** [comment]
A compiled one.

**Comment by TCSybert** [comment]
Sorry, what does that mean? I'm new hear. Does that mean a non released version?

**Comment by ghost** [comment]
http://imgur.com/a/gwxdR

Dunno what to tell you, I'm using latest stable release x64 on Win7 and have successfully used it to import a 875 ilvl build of that same character few days ago, before my gear upgrades, as I have stated in the original post. Maybe it's fixed in a nightly build and you're using that? Screenshot is from just now.

Looking at other issues submitted, seems like it's a Kara relic issue.

**Comment by TCSybert** [comment]
I just DLed the newest nightly version and if fixed the issue.
