### ISSUE TITLE
SV Hunter Food throws error

### ISSUE THREAD

**Issue by Vernriley** [simulationcraft/simc#3062]
Critocalypse: Unable to find consumable seed-battered_fish_plate for food,type=seed-battered_fish_plate
Critocalypse: Unable to initialize consumable seed-battered_fish_plate for food,type=seed-battered_fish_plate

It defaults to "nightborne_delicacy_platter" but this is not the food SV hunters use.

**Comment by navv1234** [comment]
Try seedbattered_fish_plate.

**Comment by Collisionc** [comment]
Went ahead and changed survival food to seedbattered_fish_plate.
