### ISSUE TITLE
Mage Fireblast CD

### ISSUE THREAD

**Issue by Magewindo** [simulationcraft/simc#3063]
I am not sure, because I am new to SimCraft, but it seems like the CD-reduction through haste is not implemented for the fireblast-damage-simulation. Is that correct?

e.g. my fireblast-cds are reduced to 11.1 sec with 2535 haste on my gear.

**Comment by Frostedmages** [comment]
Looking at Fireblast intervals, they are reduced as expected with additional haste. So it seems to be working fine. Going to close this.
