### ISSUE TITLE
Toe Knee's Promise NYI

### ISSUE THREAD

**Issue by Thordros** [simulationcraft/simc#3065]
Toe Knee's Promise from the new Karazhan doesn't appear to be implemented for any of the melee DPS specs I've tested it on.

Example 1:

Take the default profile Paladin_Retribution_T19H profile, remove the actor's trinkets and action list to ensure the sim uses the default APL, and add a comparison to the end between Toe Knee's Promise and a Faulty Countermeasure (see attached file ToeKneeSim1.txt). The results will show that the sim automatically includes the Faulty Countermeasure (and all other Legion trinkets) in the action list, while it does not attempt to use Toe Knee's Promise.

Example 2:

Take the default Paladin_Retribution_T19H profile, remove the actor's trinkets, add the following line to the action list, and add a comparison with Toe Knee's Promise to the end (see attached file ToeKneeSim2.txt):

`actions+=/use_item,name=toe_knees_promise`

The results will give the following error:

`Player toe_knees_promise_855 has 'use_item' action with no custom buff or action setup.`

[ToeKneeSim1.txt](https://github.com/simulationcraft/simc/files/560072/ToeKneeSim1.txt)
[ToeKneeSim2.txt](https://github.com/simulationcraft/simc/files/560071/ToeKneeSim2.txt)

**Comment by Collisionc** [comment]
It has been added in the newest nightlies. http://downloads.simulationcraft.org/?C=M;O=D
