### ISSUE TITLE
Import Issue (Relics)

### ISSUE THREAD

**Issue by Iznogud91** [simulationcraft/simc#3066]
Hi guys!
I just noticed an issue, which kinda bothers me, because I can't sim my character correctly now.
Here is my character, maybe some of you can try it out and tell me, if they have the same problem: http://eu.battle.net/wow/en/character/blackhand/Iznolich/advanced
The problem is, that no matter how I import my character (through Battle.net or with the ingame addon Simulationcraft) the fire relic is always lower itemlevel than it should be.
It should be the same ilvl than my shadow one (870 ilvl)...and only my blood one is from Karazhan so Im a bit confused why there is a problem.
It causes my weapon to be way lower ilvl, so my stat weights and all that stuff are not how they should be.
Hope u guys can tell me, if I do something wrong, or if it's a bug.
Greets Izno

EDIT: I just realised...that if I would add those 51 ilvl from the Kara relic, my weapon ilvl would be like it is ingame...so probably it's because of the Kara item...but then the tooltip overall of the weapon with a blue relic and stuff is wrong (also the ilvl in the tooltip).

**Comment by Vikerules** [comment]
Ever since i got a kara relic my sim dps dropped 50k and i have NO IDEA what to do now or how to fix it...

**Comment by Iznogud91** [comment]
710-01 fixed everything for me!
