### ISSUE TITLE
Nightly Build - Protection Paladin TMI positive haste scale issue

### ISSUE THREAD

**Issue by MalzM** [simulationcraft/simc#3069]
When simulating my current setup (see attachment) with the current nightly build (710-01), with 4 heroic instance targets over ~100s, scaling for TMI, then haste is for some reason assigned a highly positive value (bad) while in the stable build (703-03) it is rated highly negative (good). When plotting the haste vs TMI there seems to be a dip, even though that does not make any sense.

[Thoril.TXT](https://github.com/simulationcraft/simc/files/560477/Thoril.TXT)

**Comment by bitfluxhound** [comment]
There were issues with 7.1 spell data. it was fixed in a9d4b3b.
