### ISSUE TITLE
[Warrior DPS] Arms legendary leggings take effect when the character is Fury.

### ISSUE THREAD

**Issue by Chinch335** [simulationcraft/simc#3070]
This was found with the 710-10-win64 exe build that was posted 10-30 15:08.

A player in the warrior discord was wondering why his character, when specced Fury, was simming so much higher than other Fury warriors of similar item level. I asked for his character's name/realm to see if I could figure anything out. 

My character simmed at 439k with 869 ilvl.
His character simmed at 459k with 863 ilvl. Note that he has the Arms legendary leggings, Weight of the Earth, which have the effect of applying Colossus Smash to targets hit by Heroic Leap.

After some investigation, we found that his profile was indeed using Heroic Leap while mine was not, and that Fluffy Pillow did indeed have 30.99% average uptime for the Colossus Smash debuff while mine, of course, had none. 

Thusly, in simcraft, the Arms legendary Weight of the Earth is applying Colossus Smash when the player is specced Fury, while it does _not_ behave this way in game currently.

**Comment by Collisionc** [comment]
Thanks for reporting, fixed it.
