### ISSUE TITLE
Update the "Automation" import page for Legion

### ISSUE THREAD

**Issue by cremor** [simulationcraft/simc#3071]
Quick fixes:
- Remove the comparison type "Glyphs" (maybe replace it with an "Artifact" comparison type)
- Replace the text box "Default Glyphs" with "Default Artifact"
- "Level" should default to 110

Fixes that require more work:
- Update the "Rotation Abbrevations" for all specs

**Comment by Collisionc** [comment]
Removed glyph settings and changed default level to 110... the others will require more work than I feel like doing at the moment.

**Comment by cremor** [comment]
Closing this since it isn't relevant any more.
