### ISSUE TITLE
[Trinket] Bloodstained Handkerchief

### ISSUE THREAD

**Issue by Jazzer360** [simulationcraft/simc#3076]
Currently, the bloodstained handkerchief trinket bleed effect is not affected by haste in simulations, ticking once every 3 seconds exactly.

Have been testing it, and the interval between ticks is definitely lowered by haste.

**Comment by Jazzer360** [comment]
Looks like the same thing applies to Toe Knee's Promise trinket. Haste is increasing the total ticks of each use of the trinket, as well as speeding up the tick rate.

**Comment by Collisionc** [comment]
Fixed both.
