### ISSUE TITLE
[Death Knight] Improved Frost APL for 7.1

### ISSUE THREAD

**Issue by rodalpho** [simulationcraft/simc#3077]
APL changes:

1) The APL is still tuned for the old 7.0 Frozen Pulse, which activates on 0 runes active. Now that it works with 1 rune active, the three lines in core to use single-rune abilities are a DPS loss. I tested this with 0200000 talents to eliminate any interaction as well.

2) With the Frozen Pulse change, it outperforms Horn of Winter on single-targets and thus should be the default talent choice.

3) The APL section designed to maximize Icy Talons uptime isn't worth doing either. Removing it entirely had no impact on performance. 

710-02 10/31 snapshot T19H default profile: 349.7k DPS
710-02 10/31 snapshot attached profile: 360.7k DPS (+3.1%)

[FrostT19H_.profile.txt](https://github.com/simulationcraft/simc/files/562619/FrostT19H_.profile.txt)

**Comment by navv1234** [comment]
Adjusted the default APL and T19H default talent selection. T19P already seemed to use Frozen Pulse.
