### ISSUE TITLE
[Death Knight] Frost APL Improvements.

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#3078]
Edit: I see a new APL was implemented a few hours before this suggestion. Let this one sit until I figure out where it lies and what changes can be merged.

Minor gain with syncing Sindragosa's Fury with, in addition to Pillar of Frost, Unholy Strength, unless the boss will die before Pillar will be up again.
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up
to
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up&(buff.unholy_strength.up|(buff.pillar_of_frost.remains<3&target.time_to_die<60))

Minor gain with Obliteration cooldown with Frozen Pulse talent if you use Obliteration with 2 or fewer runes as opposed to on cooldown.
actions+=/obliteration
to
actions+=/obliteration,if=!talent.frozen_pulse.enabled|(talent.frozen_pulse.enabled&rune<=2)

With Frozen Pulse proc change to <2 runes from 0 runes, this eliminates spamming of 1 rune abilities, aside from Remorseless Winter. Gain is about 2-3%.
Also some reordering of the core to better synergize AOE with Frostscythe KM procs, AOE target breakpoints, and Glacial Advance and its AOE breakpoints. Causes some significant AOE performance improvements.
Frostscythe is not worth using on single target, even with KM procs, so it gets reduced to being viable only on cleave or more targets. Frostscythe KM procs edges out OB when used on 2 target cleave, but otherwise OB is used as rune spenders to cause more Rimes. Glacial Advance also falls down the list due to OB + Rime procs outweighing the damage, but its cleave/AOE damage is great, so it's cleave line is kept higher.

actions.core=frost_strike,if=buff.obliteration.up&!buff.killing_machine.react
actions.core+=/remorseless_winter,if=(spell_targets.remorseless_winter>=2|talent.gathering_storm.enabled)&!(talent.frostscythe.enabled&buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/frostscythe,if=(buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/glacial_advance,if=spell_targets.glacial_advance>=2
actions.core+=/frostscythe,if=spell_targets.frostscythe>=3
actions.core+=/obliterate,if=buff.killing_machine.react
actions.core+=/obliterate
actions.core+=/glacial_advance
actions.core+=/remorseless_winter,if=talent.frozen_pulse.enabled

Have yet to see any other measurable improvements with the talents I've played with so far..

**Comment by gixxpunk** [comment]
Most of the changes:
https://github.com/simulationcraft/simc/pull/3080
