### ISSUE TITLE
[Priest] Shadowform uptime

### ISSUE THREAD

**Issue by danaesignal** [simulationcraft/simc#3082]
Simcraft seems to list Shadowform as having a 100% uptime-- it's a 'constant buff' on the report. But Shadowform isn't constant; it drops on and off in accordance with Voidform, so it's uptime should be the inverse of Voidform's. Similarly, when I look at a sample sequence table for a Shadow Priest report, I don't actually see Shadowform being applied and removed in the buffs column.

Either this an issue of not properly displaying the actual uptime of Shadowform, or the Shadow Priest module incorrectly assuming a 100% Shadowform uptime. The former is a minor issue, but the latter would significantly (and incorrectly) inflate DPS numbers.

**Comment by scamille** [comment]
Thanks for reporting. I added shadowform just from  the tooltip, where it doesnt state anywhere that it is exclusive with Voidform.

@N1gh7h4wk are we sure that the dmg-bonus from shadowform is removed during Voidform? Or is it just the visual buff effect?

**Comment by Delmortis** [comment]
When voidform is up shadowform is just hidden. It's 10% damage buff and 10% physical damage reduction still apply. The damage buff was countered by the reduction to the baseline scaling of most of our spells.

Sent from my Samsung device

-------- Original message --------

**Comment by danaesignal** [comment]
I don't think that's accurate. First of all, the developers already commented on Twitter that the damage reduction buff is _not_ retained, as seen here: [https://twitter.com/WarcraftDevs/status/791093019713777666](url).

Second, I loaded up the game and the c4ec018 build of Simcraft and verified this myself. In game, my Void Bolt does approximately 111,770 damage in Voidform, or 223540 on a crit. When I ran a simulation of the character, ensuring I disabled all talents and buffs (food, flask, rune, Twist of Fate, etc) that could affect Void Bolt damage, it reported that a non-critical Void Bolt did approximately 10% more than the value I saw in-game.

As soon as I figure out how to upload a log to WarcraftLogs that includes my gear, I can link to that and upload a corresponding Simcraft report for your verification (should you not just independently verify it yourself).

**Comment by N1gh7h4wk** [comment]
When we are in Voidform, we now gain 30% more shadow damage, not 20% like in 7.0.x
The Shadowform buff should fade when entering VF and be reapplied right after leaving.

**Comment by N1gh7h4wk** [comment]
And its nice to hear after running like 15+ hours of sims for statweights.
[http://www.wowhead.com/spell=228264/voidform]
Not really that clear about it, but it removes the Shadowform for the duration.

**Comment by scamille** [comment]
I'll add some hidden shadowform_state buff (which does nothing, just tracks if you initially went into shadowform), so that I can easily expire and re-trigger shadowform buff on voidform enter/leave.
