### ISSUE TITLE
Simcraft won't run simulations

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3083]
I'm relativelynew to Simcraft, but i installed it a few days ago to test it. Everything seemed to be working fine. But since it doesn't support healers i uninstalled it afterwards. 
Today i wanted to try it again for my DD but after i installed it like i did last time import my profile and started a simulation the simulation just won't finished i waited almost an hour but it wouldn't work. 
It looks like the test is running and Simcraft will use almost the entire CPU capacity but like it said before the test just won't finish. I tried reinstalling it, installing the 32Bit Version and using the Version without an installer but nothing seems to work. Can anyone help me?

**Comment by ghost** [comment]
I just found out i doesn't seem to be a problem with my Simcraft but rather my Character eu,frostwolf,stinimac. What could cause such an issue?

**Comment by imsilvz** [comment]
Hi. I'm in the same situation. I run the program and none of the simulations will complete, I've never used simcraft before but I've attempted several installs on two different machines for both the x86 and x64 versions. I left it for 30 minutes earlier today, and not a single simulation completed in that time despite running all four cores of the machine at full usage (i5 6500, 3.6ghz)

**Comment by bitfluxhound** [comment]
Doesn't support healers.

**Comment by N1gh7h4wk** [comment]
If you want to simulate your DPS, make sure your armory shows your toon in the DPS specc and gear.

**Comment by ghost** [comment]
Thank you for your responses. I know that it doesn't support healers but for me the armory does show the shadow spec 
http://eu.battle.net/wow/de/character/frostwolf/Stinimac/advanced
Additionally when you try to import a healer profile Simcraft just tells you that it doesn't support healers  and never imports the profile. I was able to import the profile and it listed the shadow spec in the next step.

**Comment by navv1234** [comment]
This is fixed in b0209bcca13e98e5f184ff733dbc2783ca0a8bf3, and will be fixed in the next release, or whenever we have a new nightly binary available.
