### ISSUE TITLE
[Survival Hunter] A Murder of Crows doesn't work.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3084]
To reproduce:

Download latest build.
Enable A Murder of Crows talent (leftmost tier 30 talent)
Put it in APL (it is in default)
Run the sim.

You will find that A Murder of Crows is never used.
https://puu.sh/s33q4/9bbaa4136f.png

**Comment by nasirabtw** [comment]
Fixed in e83d68e743d9b752dbcd37775dea0297934ef527
