### ISSUE TITLE
[Survival Hunter] Flanking Strike damage from pet is too low.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3085]
Observed damage ingame (fully naked, 888 weapon).
https://puu.sh/s34f0/8a90dc2943.png

40.1k minimum hit from the pet portion of Flanking Strike.

A naked sim achieves something much lower, 24.6k.
https://puu.sh/s34if/4393bfe0f4.png

**Comment by nasirabtw** [comment]
Fixed in 1850cb45cce947bac2aaa7d49628d03c6312259a
