### ISSUE TITLE
Further Frost DK Profile 7.1 Optimizations

### ISSUE THREAD

**Issue by rodalpho** [simulationcraft/simc#3087]
Another change to the Frost DK profile. 

It was using Frostscythe on a single target with Killing Machine active. This is a DPS loss with 7.1 obliterate/howling blast buffs. Frostscythe should be used on 3 targets with Killing Machine and on 4 targets regardless.

[FDK_7.1_profile.txt](https://github.com/simulationcraft/simc/files/565177/FDK_7.1_profile.txt)

**Comment by ssateneth** [comment]
I had a minor gain using KM on 2 and regardless with 3, though YMMV depending on gear I suppose.

**Comment by rodalpho** [comment]
Just simmed it adjusting the attached profile and I cannot duplicate. They're essentially identical at 10k iterations. Since they're identical, I wouldn't object to changing it to 2/3 if you think that would be easier for a human to execute, but it doesn't really matter.

Latest snapshot my profile: 335.5k
Latest snapshot my profile w/KM on 2 and regardless on 3: 335.5k

**Comment by ssateneth** [comment]
It helps if you actually select the frostscythe talent as well as select different amount of targets as this is an enhancement with regards to AOE, not to single target.
FS with 3 targets + KM, and 4 regardless
With Glacial Advance
1 target: 311662
2 targets: 421388
3 targets: 568897
4 targets: 720976

With Obliteration
1 target: 324012
2 targets: 418282
3 targets: 552021
4 targets: 733298

FS with 2 targets + KM, and 3 regardless
With Glacial Advance
1 target: 311548
2 targets: 440218 (+20k)
3 targets: 575914 (+8k)
4 targets: 720836

With Obliteration
1 target: 323992
2 targets: 433409 (+15k)
3 targets: 585082 (+33k)
4 targets: 733203

**Comment by gixxpunk** [comment]
@rodalpho
Your APL is a 2,5k DPS loss on ST compared to my patch.
https://github.com/simulationcraft/simc/pull/3080
Just wait until it gets merged.

**Comment by rodalpho** [comment]
@ssateneth, Heh, that's a very good point. Will reevaluate after 3080 is merged.
