### ISSUE TITLE
[Frost Mage] blizzard,if=talent.artic_gale.enabled APL not working

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3088]
Despite having Arctic Gale talented, the default action list has 0 counts of it being used, and the sample sequence list shows more Frostbolts being cast over Blizzard.

Sample Sequence: 012367JKLAEGFFFHAFFFIFAJIFIAFICBIAFFIIAFID8IIIIIEIFFFIIIIID8JICBFFFID8IIHIFFIIMAIIFEGIAFFFIFAIDFIFAFFICBJAFFIDFAIILIEIFFIIHIFFID8ICBFFFFID8IJFEGFF

![untitled](https://cloud.githubusercontent.com/assets/23202001/19911815/46623e90-a096-11e6-9fa2-7307c0eb3d67.png)

**Comment by Joux4** [comment]
Note that this is just a typo (artic instead of arctic) and the maker of the APL (frosted) is aware.

**Comment by Frostedmages** [comment]
Yup. Fixed.
