### ISSUE TITLE
Cant Launch SimulationCraft

### ISSUE THREAD

**Issue by znasti** [simulationcraft/simc#3090]
When I start the program, it just says cannot launch due to changes in the GUI configuration.

**Comment by gi2k15** [comment]
Having the same issue, running the live version and then the nightly build one. Same problem happened.

![capture](https://cloud.githubusercontent.com/assets/21974171/20005188/e1fd0712-a277-11e6-86dd-7b5cc3c3ab5c.JPG)

**Comment by gi2k15** [comment]
znasti, for some unexplained reason, after I restarted the computer, the program opened again and seems to be working perfectly.

**Comment by Collisionc** [comment]
Are you using a laptop with switchable graphics, @znasti ?
