### ISSUE TITLE
Suggestion: "Nythendra" style sim 

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3091]
It'll be exactly like Patchwerk, except there will be random intervals where melee cannot be within melee range and casters cannot stand still to cast. Something like 8-10 seconds per every 60 seconds?

With the current build Outlaw rogues are shooting up high in the SimDPS charts, but it does not quite reflect real life results. This is due to dps uptime. When outlaw rogues cannot be within melee range of a boss, they effectively cannot do any dps. In contrast, assassination/subtlety rogues use DoT finishers that are a large component of their dps output, which allows them to do a decent amount of dps even while away from the boss or dancing around somewhere, making them equal or better than outlaw rogues in real life situations.

I don't know how hard this would be to code, but for the first iteration it'd be fine to make it so that for those "trouble" intervals people simply don't take any action. For the next iteration, we can then figure out what most classes could be doing while moving around to maximize dps (pistol shot for outlaw, instant casts for casters, etc).

If successfully done I think this should become the de facto standard sim style instead of the patchwerk style, which simply does not reflect the raiding environments of now (especially mythic raids).

Thanks for reading! Love SimCraft, keep up the good work.

**Comment by skudnfroodie** [comment]
https://github.com/simulationcraft/simc/wiki/RaidEvents
