### ISSUE TITLE
Karazhan Trinket Empowerment

### ISSUE THREAD

**Issue by 4DHalibut** [simulationcraft/simc#3093]
It doesn't look like simc simulates the trinket empowerment from the [chest piece](http://www.wowhead.com/item=142203/harness-of-smoldering-betrayal) off of Nightbane. I tried it with the [Bloodstained Handkerchief](http://www.wowhead.com/item=142159/bloodstained-handkerchief) and the damage remains about the same when swapping in the chest.
I believe the empowerment is +30% to the proc dmg/effect

Currenty using: simc-710-02-win64-cd65504

**Comment by Swiftdeus** [comment]
Having the same issue with Deteriorated Construct Core, the Damage from it doesn't seem to be there at all.

**Comment by nasirabtw** [comment]
The only two trinkets that are still lacking chest multiplier are Bloodstained Handkerchief and Eye of Command. The others have been implemented. No eta on when we'll get the two remaining done.

**Comment by navv1234** [comment]
All trinkets should now be properly empowered.

**Comment by Bekeuh** [comment]
Still does not work for Eye of Command.

**Comment by Bekeuh** [comment]
![image](https://cloud.githubusercontent.com/assets/24372307/21211182/b0ef9fa2-c281-11e6-8539-0bf37b51e42d.png)

Still 140 instead of 183.
