### ISSUE TITLE
Simulation not starting with Legendary equipped for different Spec

### ISSUE THREAD

**Issue by ollidiemaus** [simulationcraft/simc#3094]
Okay so here is what happened.
I wanted to start simulation my feral with the tearstone equiped.
When I try to start it the Simulation stucks at 0 of 10k iterations and nothing happens.

As soon as I equiped a different Ring it works.

It would be greate to:
a) get a notification to unequip the legendary
b) just ignore the proc of the ring ( maybe would be better?)

**Comment by navv1234** [comment]
Can't reproduce this. Equipping the ring on a feral profile works fine, will need more information as to exactly what you did. Furthermore, the ring is not implemented in simc, and the ring does not autodetect into anything that would proc automatically.
