### ISSUE TITLE
retri paladin artifact weapon not showing correct ilvl on simulation

### ISSUE THREAD

**Issue by mariohdd** [simulationcraft/simc#3095]
i used to simulate and it would show me 305 k dps , got a new item to re-simulate today. which increased my weapons ilvl to 885. then noticed dps showed as 275 k dps ( i got curious as to why) i went down to the gear tab in the results and noticed it had my weapon's ilvl at 843 . can this be fixed by any chance ?

**Comment by ccjara** [comment]
Yes, by updating your Simc to the newest version so it actually recognizes the Karazhan relic you probably have.

**Comment by Collisionc** [comment]
Yeah,  the top download here: http://downloads.simulationcraft.org/?C=M;O=D will work
