### ISSUE TITLE
Import doesn't get artifact traits (linux build)

### ISSUE THREAD

**Issue by wolfiestyle** [simulationcraft/simc#3096]
I created and added my own api key, but I still don't get the artifact traits loaded. This error displays on the console after importing:
```
@@BCP API (html): Note, Blizzard does not provide Artifact trait information on their HTML armory page. The actor will be simulated without any artifact traits. The simulator output for the actor will not be correct.
```
Don't know if my api key is correct or not, i picked the one displayed in https://dev.battle.net/apps/myapps after `Game APIs: Basic Plan`

using Gentoo Linux x86_64

**Comment by navv1234** [comment]
Install openssl(-dev) and recompile.

**Comment by wolfiestyle** [comment]
I have `openssl-1.0.2j` installed. (on gentoo everything is "dev", because we compile everything in our systems).

```
[I] dev-libs/openssl
     Available versions:  
     (0.9.8) 0.9.8z_p8^d
     (0)    1.0.2j^d [M]~1.1.0b(0/1.1)^d
       {+asm bindist gmp kerberos rfc3779 sctp sslv2 +sslv3 static-libs test (+)tls-heartbeat vanilla zlib ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32" CPU_FLAGS_X86="sse2"}
     Installed versions:  1.0.2j^d(14:51:50 29/09/16)(asm sslv3 tls-heartbeat zlib -bindist -gmp -kerberos -rfc3779 -sctp -sslv2 -static-libs -test -vanilla ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="32 64 -x32" CPU_FLAGS_X86="sse2")
```

If you suggest a SSL issue, is there a way i can debug it? I know nothing about the bnet api, i could try issuing the requests by hand or something.

**Comment by navv1234** [comment]
oh, you'll want to do `make OPENSSL=1` or so.

**Comment by wolfiestyle** [comment]
Tried that but didn't work.
Was looking through the code and effectively the api request fails (it hit's that `// FIXME: report unable to use SSL`). After that, it silently fails into html scraping mode.
I found that for unix it uses a custom http(s) implementation that messes directly with sockets and openssl... why? shouldn't it be using libcurl instead? or that qt_network lib that it's linking against but effectively not using (i'm building the Qt version).

**Comment by wolfiestyle** [comment]
hacked together libcurl support for this (replaces the unix http download):
https://github.com/darkstalker/simc/blob/a40779d42f3f362e141a5ae715d81f5b0e1ce74e/engine/interfaces/sc_http.cpp#L176

don't know if it's fully correct, but at least it works for me.

**Comment by navv1234** [comment]
Simc has tried to keep external dependencies to a minimum, and I dunno why OPENSSL=1 would not work, I suppose if you have it installed in some non standard place, you would want to use OPENSSL_PATH to indicate that.

**Comment by wolfiestyle** [comment]
libcurl is the most popular library for http and present on pretty much 99% of the linux/unix systems. I think that reinventing the wheel for "minimizing dependencies" isn't a good idea, specially on complex topics like http(s) support.
BTW for finding openssl the makefile should be using `pkg-config` instead of relying on standard locations.
