### ISSUE TITLE
app can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing

### ISSUE THREAD

**Issue by georgemoldo** [simulationcraft/simc#3099]
i installed today simcraft for the first time and got this error every time i start to open the app. i tried all installers including zip 32/ 64. Can anyone help?
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SimulationCraft.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5816061c
  Fault Module Name:	i-ms-win-crt-runtime-l1-1-0.dll
  Fault Module Version:	6.3.9600.18233
  Fault Module Timestamp:	56bb4e1d
  Exception Code:	c0000135
  Exception Offset:	0009d3c2
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/wiki/CommonIssues
