### ISSUE TITLE
Deteriorated Construct Core Not showing Damage in Simulation

### ISSUE THREAD

**Issue by Swiftdeus** [simulationcraft/simc#3100]
I was simulating some trinkets against each other last night when I noticed the Deteriorated Construct Core's damage proc was not on the damage percentage at all. A similar trinket (Twisting Winds) damage proc was simulated and damage was seen on overall. I was using the latest simc version.

**Comment by Frostedmages** [comment]
I just ran a sim with a Frost Mage and see Volatile Energy in the damage breakdown. What are you trying to sim with?

**Comment by Swiftdeus** [comment]
I ran it with my hunter. I will attempt again when I get off work, but it was not in the damage breakdown at all.
