### ISSUE TITLE
[Beast Mastery] Unrealistic Dire Beast DPS gain from 4057 to 4058 Haste.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3102]
Has existed for a while.

To reproduce:

Run this profile: http://pastebin.com/HJDAQy0Z

Overwrite the Haste rating to 4057, run a sim.
Overwrite the Haste rating to 4058, run a sim.

The sim gains 15 Dire Beast auto attacks from 1 point of Haste to another.

**Comment by Collisionc** [comment]
What happens in game? When is the additional auto attack added?

**Comment by Azortharion** [comment]
In-game, additional Haste increases the chance for Dire Beast to get another attack. There is no distinct breakpoint. This mechanic is commented in the hunter module as so: http://i.imgur.com/GqQvwEZ.png

It should therefore be impossible for 1 point of Haste to add an extra attack to so many Dire Beasts.

**Comment by Azortharion** [comment]
Bumping as it is still not fixed.

**Comment by Collisionc** [comment]
I really don't know that was expected to work, but it should work now.
