### ISSUE TITLE
Tank Trinket Procs Not showing up on Sim's. 

### ISSUE THREAD

**Issue by Justnova** [simulationcraft/simc#3103]
Hello! I've been using Simulation Craft to Sim tank damage and to help determine which trinkets I should be using. I've noticed that trinkets that have proc effects are not procing or showing up during the boss fight. For example: 
Goblet of Nightmarish Ichor,(http://www.wowhead.com/item=139324/goblet-of-nightmarish-ichor&bonus=1807#comments)  
Procs the effect (http:// www.wowhead.com/spell=222027/nightmarish-ichor); however, this does not show up as a buffed gained anywhere in the simulation. I've even looked into the simulated combat log and it does not show up in there. I've noticed this also with Grotesque Statuette and other tanking trinkets. I'm not sure if I'm missing an option somewhere or if this is a bug. Thanks!

**Comment by navv1234** [comment]
Tanking trinkets are generally poorly supported because of no volunteers with interest in modeling them. Closing for now.
