### ISSUE TITLE
Aggramar's Stride Causing Crashing

### ISSUE THREAD

**Issue by tino1317** [simulationcraft/simc#3104]
Ever since I equipped this legendary on my paladin simcraft (x86) crashes as soon as I click simulate.

Here is my simc_gui:

http://rg.to/file/b0ea0d169335ad451fb2849bd0a6f90b/simc_gui.zip.html

**Comment by Collisionc** [comment]
Not able to reproduce on newest simc, try the top downloads here - http://downloads.simulationcraft.org/?C=M;O=D

**Comment by billzabka** [comment]
Hitting the same issue on the latest build.  Most of the times it gets through the sim ok but if I check off "Scaling" it crashes every time.  It only shows a generic "SimulationCraft has stopped working" message.  No other error info.

**Comment by Collisionc** [comment]
Can you copy/paste the contents of simc_gui.txt (same folder as the program) after it has crashed?

**Comment by billzabka** [comment]
### Begin GUI options

item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=crit,haste,mastery,vers
statistics_level=1

### End GUI options

### Begin simulateText

paladin="REDACTED"
level=110
race=draenei
region=us
server=REDACTED
role=attack
professions=blacksmithing=798/mining=800
talents=1222212
spec=retribution
artifact=2:0:0:0:0:40:1:41:3:42:3:44:3:47:3:49:1:50:3:51:3:53:3:54:1:350:1:353:1:1275:1

head=,id=136728,bonus_id=3432/1808/1497/1674,gem_id=130221
neck=,id=141696,enchant_id=5439,bonus_id=1807/41/1472
shoulder=,id=139695,enchant_id=5881,bonus_id=3385/3384
back=,id=134290,enchant_id=5431,bonus_id=3432/1808/1522/3337,gem_id=130221
chest=,id=121732,bonus_id=3474/42/1507/1674
wrist=,id=134362,bonus_id=1727/43/1502/1813
hands=,id=142125,bonus_id=3453/1472
waist=,id=142129,bonus_id=3453/1492/3337
legs=,id=139097,bonus_id=3473/1507/3336
feet=,id=132443,bonus_id=1811/3458
finger1=,id=139103,enchant_id=5424,bonus_id=3473/1517/3337
finger2=,id=121288,enchant_id=5424,bonus_id=3432/1507/3336
trinket1=,id=141482,bonus_id=1472
trinket2=,id=136715,bonus_id=1727/1502/3336
main_hand=,id=120978,bonus_id=737,relic_id=3432:1497:1674/1807:1472/3473:1502:1674,gem_id=141260/139266/141260/0

**Comment by min2max** [comment]
Exact same issue in latest build. Ret paladin + Aggramar's Stride, if "Scaling" is enabled, crashes 100%.

Do not have this issue in 710-01

**Comment by min2max** [comment]
### Begin GUI options

item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
statistics_level=1

### End GUI options

### Begin simulateText

paladin="赛尔弥"
level=110
race=human
region=cn
server=
role=attack
professions=blacksmithing=758/mining=800
talents=1322112
spec=retribution
artifact=2:0:0:0:0:40:1:41:3:42:3:43:3:44:3:47:3:49:1:50:3:51:3:52:3:53:3:54:1:351:1:353:1:1275:1

head=,id=139229,bonus_id=1805/1502/3337
neck=,id=139332,enchant_id=5439,bonus_id=1805/1487
shoulder=,id=134518,enchant_id=5441,bonus_id=1727/1502/3336
back=,id=139248,enchant_id=5434,bonus_id=1805/1507/3337
chest=,id=134503,bonus_id=1727/1527/3337
shirt=,id=11840
tabard=,id=43154
wrist=,id=134522,bonus_id=3417/1532/3337
hands=,id=139226,bonus_id=1805/1492/3336
waist=,id=137086,bonus_id=1811
legs=,id=142127,bonus_id=3453/1472
feet=,id=132443,bonus_id=1811
finger1=,id=134489,enchant_id=5428,bonus_id=3415/42/1522/3337
finger2=,id=139238,enchant_id=5428,bonus_id=1805/1808/1487,gem_id=130246
trinket1=,id=137539,bonus_id=1727/1502/3336
trinket2=,id=141482,bonus_id=1472
main_hand=,id=120978,bonus_id=737,relic_id=1805:1492:3336/3414:1532:3337/3412:1517:3337,gem_id=139252/137358/137346/0

### End simulateText

### Begin overrides

# User-specified persistent global and player parameters will be set here.

### End overrides

### Begin final options

### End final options

### END

**Comment by Collisionc** [comment]
Yeah, figured it out... it was crashing non warriors. Thanks !
