### ISSUE TITLE
Spiked Counterweight not including dots

### ISSUE THREAD

**Issue by Twitchys** [simulationcraft/simc#3105]
In doing trinket comps for feral druid, I noticed that the vulnerability debuff from Spiked Counterweight (www.wowhead.com/item=136715/) is not including damage from feral druid dots. It appears the same is true for Assassination rogue's rupture as well. The debuff is amplifying damage from direct damage including cat_melee, Shred, and Rake. 

Refer to WCL: Vv93MwLhCXb4HFxq for in game behavior. It looks like it includes at least all damage from the primary actor, but does not include Potion of the Old War for instance.

**Comment by Collisionc** [comment]
That should fix it.
