### ISSUE TITLE
stuck at 0 of X iterations. Not sure if error in program or if I'm just doing something wrong.

### ISSUE THREAD

**Issue by Saltyclams** [simulationcraft/simc#3106]
I'm new to the Simcraft thing because I have mained heals since ICC, so I have never used it. I'm in Shadow spec, not a healing spec. I had a friend walk me through it and it all works fine for him. However, when I do the exact same thing he does, I have 0 iterations going through. 

I saw something about a legendary for a different spec messing with things, so I took off my Prydez thinking maybe that could be an issue. Nope, same thing. 

I've tried uninstalling and reinstalling and nothing. I don't know what the problem is.

My toon name is Clâms of Proudmoore. I've had many people try and simulate my char on their computers and it also gets stuck at 0/X iterations. 

Possibly the â is blowing up the simcraft and not allowing it to work.

**Comment by kbrougham** [comment]
The character name doesn't really do anything but show the name on the info at the end, so you can try changing the name where you have `="Clâms"` to `="test"` to see if that actually confirms whether or not it's your name doing it.

**Comment by Collisionc** [comment]
Can you copy/paste the contents of the simc_gui.txt file that is in the same folder as simulationcraft.exe after you run the simulation?

**Comment by Collisionc** [comment]
It looks like it was fixed at some point, as in the latest build - http://downloads.simulationcraft.org/?C=M;O=D - i can simulate your character without any crashing.
