### ISSUE TITLE
[Balance] Fury of Elune/Impecable Fel Essence interaction

### ISSUE THREAD

**Issue by Killuha** [simulationcraft/simc#3110]
Astral Power spent by the Fury of Elune talent does not count towards the cooldown reduction you get with the Impecable Fel Essence legendary.

PS: I'd also like to suggest to change the APL so sims with Impecable Fel Essence check if Incarnation is up before casting Fury of Elune.

**Comment by Collisionc** [comment]
Ok, fixed it so that fury of elune will count towards the CD reduction.
