### ISSUE TITLE
[Warrior] Bloodletting Manacles

### ISSUE THREAD

**Issue by siralia** [simulationcraft/simc#3113]
It's seems simc doesn't use equip effect of the warrior legendary bracers.

**Comment by Collisionc** [comment]
Added it, thanks.

**Comment by siralia** [comment]
I'm getting significantly less healing on simc then on logs. It's probably because the bracers heal you for all of the phantom rage you spend trough ultimatum and vengeance.

**Comment by Collisionc** [comment]
Ah, yeah. I forgot about protections phantom rage. Ill fix it.

**Comment by siralia** [comment]
stil not fixed, just making sure you remember @Collisionc

**Comment by Collisionc** [comment]
Should be fine now.
