### ISSUE TITLE
[Request] A stronger TMI boss

### ISSUE THREAD

**Issue by siralia** [simulationcraft/simc#3115]
The TMI boss hit like a noodle compared to bosses like xavius and ursoc, since warriors have RFDT i would like to have a boss that hits harder.
T19M TMI boss sim max hits are 770.209
xavius hit me for max 1.151.295
ursoc hit me for max 1.168.169 pre enrage

**Comment by OrcinusDrake** [comment]
You can do this yourself. Just add:

enemy=TougherTMI
actions=auto_attack,damage=2000000

To the end of your apl

**Comment by siralia** [comment]
Thank you very much
