### ISSUE TITLE
[Survival] Unstable Horrorslime procs for Survival.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3117]
The "ranged-only" trinket, Unstable Horrorslime from Emerald Nightmare, can proc from Survival. It procs from all of Survival's "ranged" attacks and its traps: Throwing Axes (ranged), Explosive Trap and its DoT, Dragonsfire Grenade and its DoT, and Serpent Sting and its DoT. It does not proc for Survival in SimCraft.

**Comment by Collisionc** [comment]
It appears to be proccing, just under the name "Volatile Ichor" for Survival.  It might have been fixed in the last few days, though.
