### ISSUE TITLE
[Frost mage] Deadly Grace not working properly

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3118]
The number of bolts fired by Deadly Grace does not match in-game numbers. It looks like the trigger condition is broken. Using the following APL that simply spams Ice Lance produces no Deadly Grace bolts whatsoever.

    actions.precombat+=/water_elemental
    actions.precombat+=/snapshot_stats

    actions=potion,type=deadly_grace
    actions+=/ice_lance

Doing the same thing in-game (with around 9k haste) produces around 13 bolts.

**Comment by vituscze** [comment]
Frostbolt, Ice Nova and Glacial Spike also do not work with Deadly Grace (neither does Ebonbolt, but this seems to match in-game behavior).

**Comment by Frostedmages** [comment]
Odd. I'll look into this, thanks.

**Comment by Frostedmages** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/766ce8611dc0bc20b89f1fa22ad50160d8f9da58

Thanks again for the heads up.
