### ISSUE TITLE
[Warrior] Ceann-Ar Charger not working

### ISSUE THREAD

**Issue by fuzzeyn** [simulationcraft/simc#3119]
Was testing the effective value of the Ceann-Ar Charger (id=137088,bonus_id=1811/3458) by replacing it with the nearly identical eventide casque (id=140881,bonus_id=1492:3444), but no changes to dps were found.  Upon further inspection there was no rage generation reported for the Ceann-Ar Charger and the total amount of rage spent on abilities seemed to be in line with the reported amount of rage generated.

**Comment by Collisionc** [comment]
Not able to reproduce this, there may be something odd with your simulation setup. Can you copy/paste the simc_gui.txt file that is created after running the simulation wtih the ceann-ar charger ?
