### ISSUE TITLE
Strength of the Nazjatar - Relic not being simulated

### ISSUE THREAD

**Issue by fuzzeyn** [simulationcraft/simc#3120]
The iron relic, Strength of the Nazjatar (item=143685) doesn't appear to be simulating correctly.  When reviewing gear in my results, it shows my weapons as missing the relic entirely.  Temp solution has been to use Betrug's Vigor (item=137472) in it's place.

**Comment by Collisionc** [comment]
This is already fixed, we just haven't made an official release yet. 

http://downloads.simulationcraft.org/?C=M;O=D
Top download should have the fix already.
