### ISSUE TITLE
Holy Paladin causing crash

### ISSUE THREAD

**Issue by Deviannt1** [simulationcraft/simc#3124]
Hello, 

Sims work fine on my Protection Paladin, however when i try to sim Holy the program stops working immediately. I have tried simming the character naked, but no change. Here's the imoprted string for verification.

paladin="Andreos"
level=110
race=human
region=us
server=gilneas
role=healer
professions=herbalism=109/mining=112
talents=1131323
spec=holy
artifact=48:0:0:0:0:965:1:1342:1

head=,id=139231,bonus_id=1805/1487
neck=,id=135915,bonus_id=3486/1808/42/1497/1674
shoulder=,id=137524,bonus_id=1727/1492/1813
back=,id=133765,bonus_id=1727/1492/1813
chest=,id=134179,bonus_id=3432/1497/1674
tabard=,id=69210
wrist=,id=141439,bonus_id=43/3466/1472
hands=,id=134180,bonus_id=3473/42/1512/3336
waist=,id=121278,bonus_id=3474/42/1507/1674
legs=,id=136729,bonus_id=3432/42/1512/3337
feet=,id=134185,bonus_id=1825/1477/3339
finger1=,id=137533,bonus_id=1727/1492/1813
finger2=,id=134527,bonus_id=1826/1457
trinket1=,id=121311,bonus_id=3397/605/1497/3336
trinket2=,id=121287,bonus_id=3394/605/1477/1675
main_hand=,id=128823,bonus_id=735,relic_id=1824:1472:3339/0,gem_id=141276/0/0/0

**Comment by Collisionc** [comment]
Healers are not currently supported. 

https://github.com/simulationcraft/simc/issues/2775

I will fix the crash, though.
