### ISSUE TITLE
Wriggling Sinew on-use ability is not showing in Automation Results

### ISSUE THREAD

**Issue by Zaymage** [simulationcraft/simc#3125]
[wriggling sinew automation problem.zip](https://github.com/simulationcraft/simc/files/574024/wriggling.sinew.automation.problem.zip)

**Comment by Zaymage** [comment]
Fixed the issue I believe. Was looking through the other profiles and this code seemed to make it work:

#this ensures on-use trinkets will be included in the action list
default_actions=1

**Comment by Collisionc** [comment]
Yeah, adding default_actions=1 will fix most problems like this. I'm going to make it a default option at some point.
