### ISSUE TITLE
Simcraft not showing pawn code of results page

### ISSUE THREAD

**Issue by davidseymour99** [simulationcraft/simc#3129]
Hi I have the latest versions of all the software add ons but its not difplaying a pawn code like it used to? Please can you help  me?

**Comment by zjhuntin** [comment]
@davidseymour99 I think that you need to have the enable scaling button checked in the scaling tab under options. I was having the same problem when it was unchecked. Though that may be a problem too?

**Comment by davidseymour99** [comment]
you top dude! you star! thats the problem
