### ISSUE TITLE
[Vengeance] Scale values not normalizing

### ISSUE THREAD

**Issue by Coldsu** [simulationcraft/simc#3131]
Tested with two different people, dtps is showing scale values negatively, which get flipped when normalized and then put into the pawn string, but since they're not normalizing the pawn string/comparison is completely reversed.

http://puu.sh/sa9SF/0e57252425.png

Other metrics such as damage are fine.

**Comment by Collisionc** [comment]
Fixed this here - https://github.com/simulationcraft/simc/commit/49ce228451368e9cef599dd56b3f9368fc8c4373

Will be in the next release.
