### ISSUE TITLE
Assasination Rogue Master Poisoner Talent Wrong Rotation

### ISSUE THREAD

**Issue by mariusz6892** [simulationcraft/simc#3132]
Master poisoner talent is simming badly, mostly because it always uses envenom on 6 CP. I simmed MP talent with 5+ cp and I had more dps. What is more, I think that MP talent is bugged, because I am doing like 20 k dps more than I sim

**Comment by aethys256** [comment]
APL was fixed in https://github.com/simulationcraft/simc/commit/5d8692d9cd7bba118b9a1de2b311c5ca48f4099f.

Currently Master Poisoner works with (on SimC) :
- Poison Bomb (Bag of Tricks)
- Deadly Poison (Apply & DoT)
- Kingsbane (Apply & DoT)
- Agonizing Poison

Do you see one missing interaction ?

**Comment by Benni1990** [comment]
You included Surge of Toxins in the point of Agonizing Poison? I think it gets buffed aswell, no?
