### ISSUE TITLE
Cannot start simcraft

### ISSUE THREAD

**Issue by Rambotowel** [simulationcraft/simc#3142]
whenever i go to start Simcraft i get an error that reades

The program cannot start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer.

ive looked around and there are no simple fixes for this, meanign everything wants me to download some third party program and register to fix. any help is welcome thank you!

**Comment by Alpheus** [comment]
Check https://github.com/simulationcraft/simc/wiki/CommonIssues
