### ISSUE TITLE
Bug Druid DPS

### ISSUE THREAD

**Issue by Benvenho** [simulationcraft/simc#3144]
Hello, my main spec is druid restoration, and as it says on the site I can not do the simulation for healer specs, so I try to do the simulation for my feral and my balance spec, but the program ends and i cant cancel the simulation, and does not make the simulation .. so came here report this "bug".

Sincerely, Benvenho

**Comment by Collisionc** [comment]
Can you post the simc_gui.txt file that is located in the simulationcraft folder after you try to simulate your character?
