### ISSUE TITLE
Elemental Shaman DPS sims too high

### ISSUE THREAD

**Issue by sboc** [simulationcraft/simc#3147]
I've done quite a few tests and I can never seem to actually do the DPS simulationcraft sims. I've created a LUA rotation checker script validating the action priority It still sims like 5-10% higher than this is able to put out - consistently.

**Comment by ghost** [comment]
Same thing for Outlaw rogue.

**Comment by mrdmnd** [comment]
This is generally a function of latency and human reaction time, and a number of small factors that are mostly out of human control. The Simcraft numbers are never "this is what you should be able to produce" but rather, meant for automated comparison across pieces of gear, or rotational changes.
