### ISSUE TITLE
[Perspective] Result of simulation T19M_L2_A35

### ISSUE THREAD

**Issue by quaid007** [simulationcraft/simc#3148]
Hello,
The results of simulations are not always actual and behind the log results.
When people have had things T19H raid and one legendary, simulation present only for T19P.
When people have had things T19M raid and two legendary, simulation present only for T19H.
I think it would be good if the simulation ahead of logs or same, and will be very nice to start simulations for T19M_L2_A35 (T19M with 2 Legendary items and Artifact with 35 traits).
I hope it will be interesting to many people.
Thanks.

**Comment by Collisionc** [comment]
We will take this into account in the future. We're constantly trying to improve the raid outputs.
