### ISSUE TITLE
roll the bones and sequence sample

### ISSUE THREAD

**Issue by loginhere** [simulationcraft/simc#3151]
i have reviewed 6 different sample sequences for outlaw rogue and each one had a significantly positive
roll the bones sequence.  the logic seems fine for what to keep, but each one was getting an inordinate set of good rolls in each complete sample sequence.  the only one i saw reroll 8 times, got a 6 buff out of 14 total rolls.  6 sequence checks is anecdotal at best, and the sample sequences might not really be what's happening.  given the single target disparity between sim and reality, i thought i would check.

can you double check roll the bones (actual rolling, not the keep logic). 

thank you

**Comment by loginhere** [comment]
latest simcraft outlaw rogue sample sequence
it doesnt show initial buff because it uses a prebuff, but it doesn't reroll so it must be a good one
after that 
1) roll 2 buff grand melee/broasides
2) roll true bearing
3) roll 2 buff grand melee/true bearing
4) roll 2 buff jolly roger/buried treasure
5) roll 2 buff jolly roger/buried treasure
6) roll 2 buff grand melee/true bearing
7) roll true bearing

if this is the actual start, then outlaw dps numbers are inflated.  as i said previously, this seems to happen when i download and run simcraft as well

0124567NIJEMLGMGMGMGMGMGMGMGMONEMGMPGGMGGMGEMGGBGFMGMGFMGEMGGMFGMGMFGMKMFEMGMFGMGGMFGMFEBGGIFGMGFGEMKMLGMFJHMGMGMKMGMGMGMKMONEGMGGFGMJGFGGMKBGEFMGGGGGMGGFGMKMFGEGGMFGGFMONEGMJKMPGGGIGGBGGMGGEGMGGGMGEFMLGMFMGMGMFMGMGGFEMGGGFMKMGGGBFGEFMGFGGMGFGMFGEFMGGFMGGFIGMFGEGGMGONGBKMGEFGMGJGGGMFGEGGMKMLGMGMGMKMGMGMFMJGMKMONEGMPGGFGMGFGBGMGEMKMGFMGGMF

**Comment by mrdmnd** [comment]
The "dps numbers" are aggregated over many runs. The sample sequence is just that - a sample. In particular, it happens to be the "first" run. You can see the buff uptime distribution in the "Procs" section - in particular, mine looks like this:

```
Proc                     N Interval
Roll the Bones: 1 buff  7.3 35.3sec
Roll the Bones: 2 buffs 4.3 62.5sec
Roll the Bones: 3 buffs 0.5 115.5sec
Roll the Bones: 6 buffs 0.2 120.5sec
```

I do not believe there is a bug to be resolved here. More statistical evidence welcome; one single sample sequence is insufficiently convincing.

**Comment by navv1234** [comment]
I did check the roll distribution briefly, and it is fine (given enough iterations, 0-5 range is uniformly distributed). I did also  check the distribution of triggered buffs, and it was also roughly uniformly distributed (the fact there are 1, 2, 3 and 6 different buffs triggered increases variance some).
