### ISSUE TITLE
[Warlock] Demonology will report inflated numbers if used as a copy

### ISSUE THREAD

**Issue by IgorekSF** [simulationcraft/simc#3153]
This issue will occur if several specs for a warlock are simulated in the same page, with demonology not being the top one.  Specifically, the following will trigger this issue:

warlock="name"
[....]
spec=destruction
artifact=...
[gear]

copy="demo"
artifact=....

The damage reported for the Demonology spec will be inflated by a fraction that depends on the number of points in the Destruction artifact. That damage differential comes from Thal'kiel's Consumption.

What appears to be happening is that a successive declaration of `artifact` does not override the previous one; instead, it appends to it. As such the second warlock has, in addition to his normal traits, all of the Destruction traits declared above (this can be verified by looking at the Purchased points: X,  total Y part of the output, which will be drastically inflated for the Demonology spec). 

For all other specs, this won't matter, as the traits from another spec do nothing (or are explicitly disabled). However, the specifics of TKC come into play here. Additional traits also increase the HP of the warlock, by 0.75% per point; that increases the base HP of the demons, and it is that base HP that inflates the damage of TKC.

**Comment by navv1234** [comment]
Yeah, I forgot to reset the new (more complicated) artifact data for actors when parsing the artifact= option, should be properly reset now when you use copy option.
