### ISSUE TITLE
[Frost mage] Zann'esu Journey bug

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3154]
The Blizzard damage modifier granted by Zann'esu Journey's buff persists for much longer than intended.

When the APL casts Blizzard at non-zero stacks of Zann'esu, the damage modifier lasts until it casts another Blizzard with non-zero stacks.

Consider the following profile:

```
fixed_time=1

mage="5x Flurry then Blizzard spam"
level=110
race=troll
role=spell
position=back
spec=frost
actions.precombat=snapshot_stats
actions=flurry,if=time<10
actions+=/blizzard
waist=,id=133970

copy=1
name="5x Flurry, Blizzard, 3x Flurry then Blizzard spam"
actions=flurry,if=time<10
actions+=/blizzard,if=time<13
actions+=/flurry,if=time<17
actions+=/blizzard

copy=2
name="Blizzard spam"
actions=blizzard
```

DPE of Blizzard at 0 stacks is around 36.5k (given by the "Blizzard spam" profile). Expected DPE for the profile "5x Flurry then Blizzard spam" should be slightly above 36.5k, but in reality is 100k (roughly 2.75 times higher). Same thing goes for "5x Flurry, Blizzard, 3x Flurry then Blizzard spam", expected 36.5k, reported 76k (roughly 2.05 times higher).

**Comment by vituscze** [comment]
This also means that the following APL action will need some updates:

```
actions+=/blizzard,if=talent.arctic_gale.enabled|active_enemies>1|((buff.zannesu_journey.stack>4|buff.zannesu_journey.remains<cast_time+1)&equipped.133970)
```

This unknowingly takes advantage of this bug by casting Blizzard on cooldown with zero stacks of Zann'esu Journey (since `buff.zannesu_journey.remains<cast_time+1` always holds with zero stacks) and once Flurry is cast, it waits for 5 stacks (to snapshot the highest damage modifier for further zero stack Blizzards).

**Comment by vituscze** [comment]
I believe this could be fixed simply by updating `legendary.zannesu_journey_multiplier` everytime `blizzard_t::execute` is called.

That is, changing this line in `engine/class_modules/sc_mage.cpp`:

```
if ( p() -> legendary.zannesu_journey && p() -> buffs.zannesu_journey -> check() )
```

to

```
if ( p() -> legendary.zannesu_journey )
```

**Comment by Frostedmages** [comment]
There are a few problems with this I need to work out. I haven't forgotten about this (or the flurry thing). I'm nearly done with the PTR updates, I'll come back around to these after those.

**Comment by Frostedmages** [comment]
Fixed here: https://github.com/simulationcraft/simc/commit/876a5a69a296077cbd4dffecd2ccf7abd9c2a9d8
