### ISSUE TITLE
Stats to be scaled showing up as blank

### ISSUE THREAD

**Issue by Kdub74** [simulationcraft/simc#3155]
There are no stats in the "Stats to be scaled" window as seen in the attached image. It actually automatically seems to still scale secondary stats, and on my main (enhance shaman) it simulates Agility, but on my alts (DK and Warlock) it doesn't scale Strength or Intelligence.

This error is noticed on Ver 710-02

![simcraft error](https://cloud.githubusercontent.com/assets/23421982/20239841/235f7ca6-a8bf-11e6-8433-ba70bc91276e.jpg)

**Comment by seansehr** [comment]
I am also having this issue. @Kdub74 were you able to resolve?

**Comment by Collisionc** [comment]
Maximizing the window should fix that. We'll adjust it in the future so that it works in a smaller window, but it's a low priority for now.
