### ISSUE TITLE
[Rogue] The Devilsaur's Bite with Agonizing Poison

### ISSUE THREAD

**Issue by saxoccer** [simulationcraft/simc#3158]
Sims are undervaluing the proc damage on "The Devilsaur's Bite" trinket for Assn rogues that have taken the talent Agonizing Poison.  In-game testing shows the proc is affected by the increased damage % that Agonizing Poison provides to all abilities.
With my current gear, this results in Devilsaur's Bite doing ~40% more damage than SimCraft suggests it should.

**Comment by navv1234** [comment]
Agonizing Poison is working fine on it, but we were not ignoring armor for the proc.
