### ISSUE TITLE
Gaining 2 artifact points is a DPS loss

### ISSUE THREAD

**Issue by jazz836062** [simulationcraft/simc#3160]
I simmed my frost mage and simply copied the profile and modified the artifact to add 2 points and get me another golden dragon.  This results in a 9k dps loss as compared to current which can't be correct.  simc file below.

mage="Jazzytwo_Current"
level=110
race=gnome
region=us
server=trollbane
role=attack
professions=herbalism=377/tailoring=800
talents=3122111
spec=frost
artifact=53:0:0:0:0:783:1:784:3:785:3:786:3:788:3:789:3:790:3:791:2:792:3:793:1:795:1:796:1:798:1:1296:1

head=,id=139189,bonus_id=1805/1507/3337
neck=,id=141696,enchant_id=5439,bonus_id=1806/42/1517/3337
shoulder=,id=139192,bonus_id=1805/1487
back=,id=139248,enchant_id=5436,bonus_id=1805/1808/1487,gem_id=130220
chest=,id=137352,bonus_id=3416/1522/3336
shirt=,id=98083
wrist=,id=132406,bonus_id=1811
hands=,id=133609,enchant_id=5444,bonus_id=3413/1517/3337
waist=,id=138217,bonus_id=1806/1507/3336
legs=,id=139190,bonus_id=1805/1512/3337
feet=,id=139195,bonus_id=1806/1507/3336
finger1=,id=142172,enchant_id=5428,bonus_id=42/3453/1472
finger2=,id=139238,enchant_id=5428,bonus_id=1805/1492/3336
trinket1=,id=139323,bonus_id=1806/1507/3336
trinket2=,id=139321,bonus_id=1805/1487
main_hand=,id=128862,bonus_id=731,relic_id=1805:1487/3467:1482:3336/1805:1487,gem_id=139250/142514/139250/0

copy="Jazzytwo_+2 AP"
artifact=53:0:0:0:0:783:1:784:3:785:3:788:3:789:3:790:3:791:3:792:3:793:1:795:1:796:1:797:1:798:1:1296:1
main_hand=,id=128862,bonus_id=731,relic_id=1805:1487/3467:1482:3336/1805:1487,gem_id=139250/142514/139250/0

**Comment by vituscze** [comment]
The copy is missing 3 points in Let It Go (trait id 786), which explains the difference.

**Comment by jazz836062** [comment]
Confirmed.  I dumb sometimes.  Thanks for catching that.  Can close this.
