### ISSUE TITLE
[Shadow Priest] Wrong Insanity Drain.

### ISSUE THREAD

**Issue by N1gh7h4wk** [simulationcraft/simc#3163]
The Insanity Drain start was correctly pulled down to 8 instead of 9, but the drain per insanity_drain_stacks was increased by 10%. So it should drain 0.55 more Insanity per second, or as coded 0.055 more drain per tick instead of 0.05.
Side note: the Drain is only updated every 2 seconds.
Last build of wow: `8.5+0.5*insanity_drain_stacks`
The Simcraft Insanity drain right now looks like (in per second) 8 8 9 9 10 10
It should be like `7.45 + 0.55*insanity_drain_stacks` now.
So for example (in per second): 8 8.55 9.1 9.65 10.20 10.75

**Comment by lgkern** [comment]
Updated the drain formula with https://github.com/simulationcraft/simc/pull/3164

**Comment by scamille** [comment]
Was that a 7.1.0 or 7.1.5 change? I'm trying to see if there was a data change on specific spell data. Maybe I can find those 50% (now 55%) somewhere, instead of keeping it hardcoded.

**Comment by N1gh7h4wk** [comment]
0.55 insanity drain/s² instead of 0.5 insanity drain/s² was a 7.1 Hotfix. On PTR they plan on increasing it even more tho.

> Shadow: Voidform’s Insanity drain now begins at 8 Insanity per second (down from 9), but will increase at a 10% faster rate

**Comment by lgkern** [comment]
That is a 7.1.0 hotfix, Not sure if you would be able to in the way it is implemented today. The drain stacks were manually implemented by Twintop because they aren't represented as spells, so the whole insanity drain system is hidden.
