### ISSUE TITLE
[Fire Mage] Marquee Bindings of the Sun King

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#3166]
As reported on Ovale https://github.com/Sidoine/Ovale/issues/157 

actions.rop_phase+=/pyroblast,if=buff.kaelthas_ultimate_ability.react
and
actions.single_target+=/pyroblast,if=buff.kaelthas_ultimate_ability.react

need to take into account the casttime of pyroblast itself.
If the buff expires while pyroblast is being cast, we don't have the 300% dmg increase.
I guess a better action could be taken in that case.

**Comment by Collisionc** [comment]
Ended up being a 1.5k dps increase on the mage_fire_t19m.simc profile with the bracers equipped to add this.
