### ISSUE TITLE
[Druid] Feral Affinity Shred not scaling with bleeds.

### ISSUE THREAD

**Issue by Bunnychaser999** [simulationcraft/simc#3168]
Currently using feral affinity as any druid spec, when using shred the shred damage does not scale with having a bleed active (20% damage.)

You can replicate this by simply having the character cast shred with bleed override and without.

APL used: 

actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/cat_form
actions.precombat+=/prowl
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war

actions+=/rake,if=buff.prowl.up&buff.cat_form.up
actions=auto_attack
actions+=/potion,name=old_war,if=buff.rage_of_the_sleeper.up
actions+=/call_action_list,name=cat,if=(cooldown.thrash_bear.remains>0&cooldown.mangle.remains>0&buff.rage_of_the_sleeper.down&buff.incarnation.down)|!dot.rip.ticking
actions+=/call_action_list,name=bear

actions.bear+=/bear_form
actions.bear+=/incarnation
actions.bear+=/moonfire,if=!dot.moonfire.ticking&(talent.incarnation.enabled|talent.soul_of_the_forest.enabled)
actions.bear+=/lunar_beam,if=dot.rip.remains>10&buff.bear_form.up
actions.bear+=/rage_of_the_sleeper,if=dot.rip.remains>10&buff.bear_form.up
actions.bear+=/thrash_bear,if=buff.incarnation.up=1&dot.thrash.remains<=4.5
actions.bear+=/pulverize
actions.bear+=/maul
actions.bear+=/mangle
actions.bear+=/moonfire,if=buff.galactic_guardian.up
actions.bear+=/swipe_bear

actions.cat+=/cat_form,if=buff.cat_form.down
actions.cat+=/ferocious_bite,if=(dot.rip.ticking&dot.rip.remains<3&target.time_to_die>3&target.health.pct<25)|(combo_points=5&energy>=50&dot.rip.remains>10)
actions.cat+=/rake,if=!dot.rake.ticking
actions.cat+=/shred

**Comment by Alpheus** [comment]
This is from my branch, I got this

**Comment by Alpheus** [comment]
Should be fixed with the incoming pull request

**Comment by Alpheus** [comment]
This has been fixed.
