### ISSUE TITLE
Simcraft crashes when attempting scales

### ISSUE THREAD

**Issue by intinerious** [simulationcraft/simc#3169]
Hi,

Every time I try to run a Sim to find stat weights, the application crashes. I can simulate without the stat weights just fine. I have tried different versions (starting with the most recent), multiple characters (shadow priest, enh shaman), imports from the addon or armory, nothing seems to matter. Everything works fine until I try to simulate weights, and then it always crashes. Any help?

**Comment by Collisionc** [comment]
Can you post the simc_gui.txt file that is located in the folder with simulationcraft after it crashes ?

**Comment by intinerious** [comment]
Maybe I'm a complete dope, but I don't see simc_gui.txt. I see simc_gui.simc and simc_report.txt, but that one is blank.

![image](https://cloud.githubusercontent.com/assets/23512736/20652706/268849f8-b4cc-11e6-8f5c-2e1b0305cdd0.png)

**Comment by Collisionc** [comment]
Sorry, simc_gui.simc is the file I need to see. : )

**Comment by intinerious** [comment]
Won't let me upload that file type, opened it in notepad and this is what I got:

```
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
shaman="Retsamtac"
level=110
race=tauren
region=us
server=durotan
role=attack
professions=alchemy=776/herbalism=172
talents=3213112
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:3:907:3:908:2:909:3:910:3:911:3:912:3:1351:1

head=,id=139081,bonus_id=3474/1507/1674
neck=,id=133636,enchant_id=5439,bonus_id=3412/1808/1517/3337,gem_id=130222
shoulder=,id=139218,enchant_id=5441,bonus_id=1807/1477/3336
back=,id=134290,enchant_id=5432,bonus_id=3474/1512/3336
chest=,id=137498,bonus_id=3413/1517/3337
wrist=,id=139222,bonus_id=1805/1808/1492/3336,gem_id=130247
hands=,id=139966,bonus_id=3432/1517/3337
waist=,id=137456,bonus_id=1727/1492/1813
legs=,id=132466,bonus_id=3459/3458
feet=,id=134464,bonus_id=3414/1808/1507/1813,gem_id=130222
finger1=,id=139237,enchant_id=5425,bonus_id=1807/1472
finger2=,id=138220,enchant_id=5425,bonus_id=1807/1472
trinket1=,id=139325,bonus_id=1807/1808/1472,gem_id=130222
trinket2=,id=140030,bonus_id=3474/1497/1674
main_hand=,id=128819,bonus_id=745,relic_id=1482:3336/3397:1517:3337/3413:1507:3336,gem_id=141522/141263/133682/0
off_hand=,id=128873,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

Is that what you need? If not I can zip it or something I suppose.

Also, thanks :)

**Comment by Collisionc** [comment]
Yeah, that works. I'll check it out.

**Comment by Collisionc** [comment]
Try clicking the "Reset all settings" button in the GUI under OPtions --> Globals ---> Basic Options

(Just to make sure something weird in an old setting isn't crashing it)

Also, open up the command prompt where the file 'simc_gui.simc' is located, (Open file explorer, right click in the background of the folder, "Open command window here"), and type in

simc.exe simc_gui.simc

Just to see if it crashes using the command line executable.

**Comment by intinerious** [comment]
After "reset all", the same appears to happen: I can sucessfully simulate without scaling turned on, but as soon as I enable it, it crashes when I attempt to simulate.

**Comment by Collisionc** [comment]
Try the command line client (i updated my comment) just to see if it crashes there too.

**Comment by Collisionc** [comment]
Can you uplaod your dxdiag ?

**Comment by Collisionc** [comment]
Try setting this in your simulation - just copy/paste the following line in the sim

decorated_tooltips=0
