### ISSUE TITLE
Crashes at end of sim

### ISSUE THREAD

**Issue by hastingwood** [simulationcraft/simc#3173]
Sorry to bother you but after windows updates and/or the latest version of Simulationcraft I get a "Simulationcraft has stopped working" crash at the end of running a sim.
I have tried the latest nightly build (710-03)  too, no joy. On build 710-02 I had to set it to win8 compatibility or I would get a crash when trying to change something on the options page, then that would bomb out too with the same error at the end of the sim.

https://dl.dropboxusercontent.com/u/104201466/simc_gui.simc
https://dl.dropboxusercontent.com/u/104201466/DxDiag.txt

Many thanks :)

**Comment by Collisionc** [comment]
Does 710-01 work?

**Comment by hastingwood** [comment]
Thanks for the reply. Nope, crashes at the end of the sim as well. :(

**Comment by Collisionc** [comment]
I may have fixed it in another issue, basically it was crashing trying to generate a player report for the enemy target. See if this works: 
http://downloads.simulationcraft.org/simc-710-03-win64-4238a18.7z

**Comment by Collisionc** [comment]
Ok. Figured it out. It's Adaware -- LavasoftTcpService64.dll

Either uninstall Adaware or add decorated_tooltips=0 to your simulation to see if that fixes it.
