### ISSUE TITLE
Hunter_SV_T19H using a lowtier Trinket

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3175]
Hello,

The Hunter_SV_T19H Profile is using Tirathorn's Betrayal, which is a lowtier Trinket for SV Hunters.
Is it possible to be changed to Eye of Command or Chaos Talisman of the same itemlv?

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/06f88a2975046750971ec58555c302ea3194ccae
