### ISSUE TITLE
SimulationCraft crashes constantly while simming.

### ISSUE THREAD

**Issue by omgthisnamesux** [simulationcraft/simc#3178]
Attempting to Sim my Belf Ret Paladin, here's the string:

paladin="Suks"
level=110
race=blood_elf
region=us
server=thrall
role=attack
professions=alchemy=778/herbalism=743
talents=1132210
spec=retribution
artifact=2:0:0:0:0:40:1:1275:1

head=,id=123913,bonus_id=689/1697/3408/600/669
neck=,id=130242,enchant_id=5889,bonus_id=1762/689/601/669,gem_id=130220
shoulder=,id=123915,enchant_id=5442,bonus_id=689/1721/3408/600/669
back=,id=134405,bonus_id=1727/1808/42/1512/3337
chest=,id=134179,bonus_id=3413/1527/3337
wrist=,id=141439,bonus_id=3466/1472
hands=,id=141695,enchant_id=5444,bonus_id=1807/1472
waist=,id=137361,bonus_id=1727/1527/3337
legs=,id=137342,bonus_id=1727/1492/1813
feet=,id=132443,bonus_id=1811
finger1=,id=134537,enchant_id=5428,bonus_id=1727/1808/1517/3337,gem_id=130220
finger2=,id=139103,bonus_id=3432/1527/3337
trinket1=,id=128711,bonus_id=689/600/669
trinket2=,id=138225,bonus_id=1805/1487
main_hand=,id=120978,bonus_id=737,relic_id=0/0,gem_id=0/0/0/0

Every time when it gets to scaling Crit, it crashes.

**Comment by Collisionc** [comment]
Can you upload the simc_gui.txt file that is located in the simulationcraft folder after the crash ?
