### ISSUE TITLE
Crash at Simulate! - Choker of Barbed Reins / Guardian Druid

### ISSUE THREAD

**Issue by Sabnock** [simulationcraft/simc#3180]
The application appears to crash at the start of the simulation because of this item :
neck=,id=142174,enchant_id=5439,bonus_id=3452/1477/3336

Same effect in 32 and 64, 710-02 and 710-03.

Removing the neck, or using a different one fixes the issue.

**Comment by Collisionc** [comment]
What spec are you simulating with it? Not able to reproduce the crash at the moment.

**Comment by Sabnock** [comment]
Guardian Druid

**Comment by Collisionc** [comment]
Can you link your druid's armory? It must be some odd interaction between other items.

**Comment by Sabnock** [comment]
druid="Blackleaves"
level=110
race=worgen
region=us
server=turalyon
role=tank
professions=alchemy=752/herbalism=676
talents=1133321
spec=guardian
artifact=57:0:0:0:0:948:3:949:3:950:3:951:3:952:3:953:1:954:3:956:3:957:1:958:1:959:1:960:1:961:1:962:1:979:1:1334:1

head=,id=139205,bonus_id=1806/40/1502
neck=,id=142174,enchant_id=5439,bonus_id=3452/1477/3336
shoulder=,id=135604,enchant_id=5442,bonus_id=3428/1677/1502/3337
back=,id=139248,enchant_id=5435,bonus_id=1805/1512/3337
chest=,id=139208,bonus_id=1806/1507/3336
shirt=,id=44694
wrist=,id=137056,bonus_id=3459/3458
hands=,id=139202,enchant_id=5444,bonus_id=1806/1502
waist=,id=139198,bonus_id=1806/41/1512/3336
legs=,id=134451,bonus_id=3411/1808/1527/3337,gem_id=130221
feet=,id=137397,bonus_id=1727/1532/3337
finger1=,id=134493,enchant_id=5430,bonus_id=3418/40/1532/3337
finger2=,id=134542,enchant_id=5430,bonus_id=3414/1808/1532/3337,gem_id=130247
trinket1=,id=139329,bonus_id=1807/1472
trinket2=,id=133644,bonus_id=3413/1517/3337
main_hand=,id=128821,bonus_id=724,relic_id=3474:1507:1674/1805:1492:3336/3473:1507:3336,gem_id=143683/139254/140088/0
off_hand=,id=128822,relic_id=0/0,gem_id=0/0/0/0

**Comment by Sabnock** [comment]
The previous comment contains the exact loadout that causes the crash. My druid's armory doesn't reflect this loadout anymore.

**Comment by Praxeomatic** [comment]
I have this issue as well.

The neck in question is "Choker of Barbed Reins"

Here is the loadout (for me) that causes the crash:

druid="Mauly"
level=110
race=tauren
region=us
server=malganis
role=tank
professions=alchemy=780/herbalism=815
talents=1313321
spec=guardian
artifact=57:0:0:0:0:948:3:949:3:950:3:951:3:952:3:953:3:954:3:955:3:956:3:957:1:958:1:959:1:960:1:961:1:962:1:979:1:1334:1

head=,id=134447,bonus_id=3417/1522/3336
neck=,id=142174,bonus_id=3452/1477/3336
shoulder=,id=137364,enchant_id=5883,bonus_id=3418/40/1517/1813
back=,id=137531,enchant_id=5311,bonus_id=3418/1532/3337
chest=,id=142203,bonus_id=41/3454/1472
wrist=,id=137056,bonus_id=1811
hands=,id=137480,bonus_id=3510/1537/3337
waist=,id=137513,bonus_id=3418/1522/3336
legs=,id=142418,bonus_id=3506/1808/1492/3336,gem_id=130222
feet=,id=137025,bonus_id=1811/3458
finger1=,id=134527,enchant_id=5428,bonus_id=3418/40/1532/3337
finger2=,id=137533,enchant_id=5429,bonus_id=3510/1808/40/1532/3336,gem_id=130222
trinket1=,id=141482,bonus_id=1472
trinket2=,id=139329,bonus_id=1805/1502/3337
main_hand=,id=128821,bonus_id=724,relic_id=3510:1537:3337/3454:1472/3417:1512:1813,gem_id=137375/143524/137327/0
off_hand=,id=128822,relic_id=0/0,gem_id=0/0/0/0
