### ISSUE TITLE
Player Milokkr uses call_action_list with unknown action list core

### ISSUE THREAD

**Issue by Milokk** [simulationcraft/simc#3181]
I try to simulate my Frost/Blood DK and get the following error message
EU Darksorrow-Milokkr

Player Milokkr uses call_action_list with unknown action list core
Simulation has been canceled during player setup! (thread=0)                     
Player Milokkr uses call_action_list with unknown action list core
Player Milokkr uses call_action_list with unknown action list core

I use Windows 10, SimulationCraft build 710.02

Plz help meh.

**Comment by Collisionc** [comment]
Try the latest version at the top of this list: http://downloads.simulationcraft.org/?C=M;O=D

I'm not able to currently reproduce this.

**Comment by navv1234** [comment]
Potentially an issue with trying to simulate a Blood Death Knight, since we do not support them.
