### ISSUE TITLE
Simulationcraft does not start

### ISSUE THREAD

**Issue by morisatok1** [simulationcraft/simc#3183]
Hello everyone,
I am wondering is any1 else having the problem where the simulation-craft does not start. I open the program but nothing happens, does not appear on my processes. I tried dling both the 64-bit and 32-bit, turning off firewall, redownloading it, but none of these methods worked. Does any1 have any suggestions? Im using windows 8.1.
Thank you

**Comment by Collisionc** [comment]
If you try the http://downloads.simulationcraft.org/simc-710-01-win64.7z version does it tdo this?
