### ISSUE TITLE
[Frost mage] Water Jet is missing a tick

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3184]
In game, Water Jet does one tick instantly and then 4 ticks over 4 seconds (modified by haste). In SimC, Water Jet just does 4 ticks over 4 seconds.

Profile:

```
fixed_time=1
log=1
mage="Water Jet test"
level=110
spec=frost
actions.precombat=water_elemental
actions.precombat+=/snapshot_stats
actions=water_jet,if=time=0
actions+=/frostbolt,if=time=0
```

Log:
https://www.warcraftlogs.com/reports/mzA8yNckxqhFvbrj#fight=2&type=damage-done&source=5&view=events&ability=-31687&start=939928&end=965888

**Comment by Frostedmages** [comment]
Fixed in mage-legion-dev
