### ISSUE TITLE
[Hotfixes] find_spell( integer ) does not check against hotfixed data.

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3185]
Frozen Orb (84714) requires level 57, but it uses the spell Frozen Orb (84721, frozen_orb_bolt in SimC) that requires 81. As a result, it's impossible to sim characters between levels 57 and 80 that use Frozen Orb.

Profile:
```
mage="Frozen Orb test"
level=80
spec=frost
actions.precombat=snapshot_stats
actions=frozen_orb
```

**Comment by Frostedmages** [comment]
I mean, technically I guess this is a problem. It's very low on my "list of things to fix" list though.

**Comment by vituscze** [comment]
Understandable. I came across this when trying to calculate stat weights for Herald of the Titans alt, I got around it by manually editing engine/dbc/generated/sc_spell_data.inc (I think; it's been a long time, I usually just edit the executable).

**Comment by Collisionc** [comment]
Hotfixed it so that the spell will now be usable at level 57.

**Comment by vituscze** [comment]
The hotfix sadly doesn't work, when dbc.spell grabs it, it still has level() == 81.

**Comment by Collisionc** [comment]
I'll check it out today.

**Comment by Collisionc** [comment]
This is going to be outside my paygrade, one of the methods we use for checking spelldata is not using hotfix data to determine whether or not the character can use a spell. The hotfix I put in works in other circumstances. 

I can probably put together a hacky solution to make it work at lower levels, but it will be a fairly low priority.

**Comment by Collisionc** [comment]
Ok, put in hacky solution for now.

**Comment by navv1234** [comment]
This should probably now be fixed, and you could remove whatever hacky thing you added.
