### ISSUE TITLE
[Frost mage] Ray of Frost does not update tick time

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3186]
I noticed that doing stat scaling on one of my profiles started giving negative weight to haste, which should be impossible. Turns out that the extra added stats used to compute weights pushed the profile above 50% passive haste, reducing the cast time of Rune of Power below 1 sec and causing Ray of Frost to be cast before raidwide Bloodlust. This wouldn't be an issue in game, as the number of ticks/tick time is dynamically updated based on your current haste, but SimC does not do this, leading to huge damage loss on the opening Ray and thus giving negative weight for haste.

Aside from this problem with opener, this could be problematic with trinkets like this one http://www.wowhead.com/item=140809/whispers-in-the-dark

Profile:
```
fixed_time=1
log=1

mage="Ray of Frost 49% haste"
level=110
spec=frost
talents=102
actions.precombat=snapshot_stats
actions=rune_of_power,if=time=0
actions+=/ray_of_frost,if=time<50
gear_haste_rating=12500


mage="Ray of Frost 51% haste"
level=110
spec=frost
talents=102
actions.precombat=snapshot_stats
actions=rune_of_power,if=time=0
actions+=/ray_of_frost,if=time<50
gear_haste_rating=13000
```

**Comment by vituscze** [comment]
Also, this leads to RoF + TV doing much better in SimC than in game.

If Icy Veins is extended to last until next RoF, that RoF will get 30% haste for its full duration even though Icy Veins usually falls off during the first few seconds.

Profile:

```
override.bloodlust=0

fixed_time=1
log=1

mage="full IV"
level=110
spec=frost
talents=1
actions.precombat=snapshot_stats
actions=icy_veins,if=time=0
actions+=/ray_of_frost,if=time=0
# 100% crit to reduce variance
gear_crit_rating=50000

mage="1/10 IV"
level=110
spec=frost
talents=1
actions.precombat=snapshot_stats
actions=icy_veins,if=time=0
actions+=/ray_of_frost,if=time=19
gear_crit_rating=50000
```

**Comment by navv1234** [comment]
Channeled spells traditionally are snapshotting cast speed at the beginning of cast, because if they would not, things get really confusing. Has this now changed then?

**Comment by vituscze** [comment]
I don't think it has changed, Ray of Frost is just an exception.

You can check this log to be sure. Roughly the first half of RoF is with Icy Veins (tick time around 0.54 sec), then at 10:55:47.133, Icy Veins is removed (tick time goes up to around 0.71 sec).

[WoWCombatLog.txt](https://github.com/simulationcraft/simc/files/606017/WoWCombatLog.txt)

**Comment by Collisionc** [comment]
Is this still a concern?

**Comment by vituscze** [comment]
It is, Ray of Frost + Thermal Void is still doing much better in SimC than in the actual game.

**Comment by Collisionc** [comment]
Do they both last 10 seconds no matter what, or will more haste lead to the same amount of ticks, just in a shorter period ?

**Comment by vituscze** [comment]
Ray of Frost always lasts 10 seconds. You can think of it as a 10 sec DoT that you have to channel to maintain.

**Comment by Collisionc** [comment]
Ok, will be fixed in the next release... make sure to check it to make sure it's not doing anything odd, as this isn't something that we've ever had in the simulation.

**Comment by Collisionc** [comment]
http://downloads.simulationcraft.org/?C=M;O=D uploaded version with this in it

**Comment by vituscze** [comment]
So far it looks like it's working as expected, I'll let you know if I come across anything unusual.
