### ISSUE TITLE
[Frost mage] Icicle damage not stored properly

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3187]
When SimC creates an Icicle, the stored damage does not take versatility (and possibly other damage buffs) into account. Versatility is applied when the Icicle is launched. Normally, this wouldn't change all that much, but this has rather big effect on Glacial Spike.

Compare:

```
intellect = 9958
versatility = 1921
mastery = 0

frostbolt_damage = 21916 (= 9958 * 2.1 * (1 + 1921/40000))
icicle_damage = 3945 (= 21916 * 0.18)
glacial_spike_damage = 98944 (= (9958 * 7.5 + 3945 * 5) * (1 + 1921/40000))
```

Profile:
```
fixed_time=1
log=1

mage="Glacial Spike versatility"
level=110
spec=frost
talents=0000002
actions.precombat=snapshot_stats
actions=glacial_spike,if=buff.icicles.react=5
actions+=/frostbolt
gear_versatility_rating=1921
gear_intellect=2630
```

```
frostbolt_damage = 21916
icicle_damage = 3945
glacial_spike_damage = 97997
```

As far as I can tell, current in-game behavior is this: when you cast Frostbolt, create Icicle corresponding to damage your Frostbolt would do target dummy (i.e. take in account Rune of Power, Incanter's Flow, versatility, damage done buffs, but not damage taken debuffs). When you launch Icicle, take stored damage and apply damage taken debuffs. When you cast Glacial Spike, apply everything (which means that RoP, IF, versatility, damage done buffs double dip).

**Comment by Frostedmages** [comment]
okydokie, thanks!.

**Comment by Frostedmages** [comment]
I know why this is happening, but I'm very confused why I did this. Need to figure out what past-frosted was thinking...

**Comment by Frostedmages** [comment]
Fixed in mage-legion-dev.

**Comment by vituscze** [comment]
By the way, your fix made Frostbolt unable to crit.

In particular: https://github.com/simulationcraft/simc/commit/728cb0708a30769f058407b482a7b22a9506d77b#diff-f1be41589292135fe73732f95a4b1cfdR4678

**Comment by Frostedmages** [comment]
oops! fixed. Sorry about that.
