### ISSUE TITLE
[item] Eye of Command overvalued Crit rating

### ISSUE THREAD

**Issue by hughrocks** [simulationcraft/simc#3188]
Each stack of Eye of Command buff 'Legion's Gaze' should be 140 crit rating (for the base 860 version), whereas in SimC it's 197 per stack. 

Not sure if value wrong for other ilvls.

**Comment by navv1234** [comment]
According to what? Base version on both wowhead and wowdb (and simc) seem to think it's 197 per stack. If it has changed in game to 140, then there's been a hotfix I suppose.

**Comment by hughrocks** [comment]
In-game it's 140! will screenshot this evening

**Comment by Fjellryn** [comment]
Hello, quick dummy test on Live servers with Eye Of Command trinket : http://imgur.com/a/ZKlMh

Simc had Legion's gaze buff at 140.95 crit rating per stack as of 15th november and this is what I see in game right now.

Couldn't test with a Nightbane chest as I currently don't own one, but the expected result would be 140.95*1.30 crit rating per stack

**Comment by navv1234** [comment]
Fixed in 921fa0a.
