### ISSUE TITLE
ID's available to sim without having the item?

### ISSUE THREAD

**Issue by adam-kelsey** [simulationcraft/simc#3189]
Are the ID's randomly generated as they come or does everything have its own ID? I would like to sim trinkets and gear by just putting in the ID and seeing how they do without having to gain the actual item so I know what to get, but I can't seem to find a list of ID's. Is there one available?

**Comment by N1gh7h4wk** [comment]
The items are pulled from Databases like wowhead or wowdb via the item id. You can check for the item on those websites and use the item ID.
