### ISSUE TITLE
WW MONK Haste stat below 0 (- 0.52 for me) 

### ISSUE THREAD

**Issue by Manawanui** [simulationcraft/simc#3191]
So, How is that possible? I know haste is garbage for ww monk, but seriously i do have only 4% haste and it scales for me as -0.52 on simcraft. So basicly items with 865 ilvl (360 agi less etc) are showing like boosting while simulation dps is at least 6k less.. Is that a bug or?

**Comment by Hinalover** [comment]
Haste tends to fluctuate QUITE a bit; especially below 10% haste. What you are seeing is that you are on a cusp of a haste break point with getting FoF and/or RSK's cooldown low enough that haste isn't needed AT THAT POINT. Plus you have to look beyond the fact that it is a negative value. If you look at the bar lines for Haste, there is a bottom value and a top value. Top value is most likely over 0 value. So I wouldn't not worry too much about it at this time.

**Comment by Manawanui** [comment]
I understand, But then pawn shows me that 865 ilvl hands with vers/mastery are better than 880 with haste/matery but when it comes to simulation, haste one are way better. So I am just confused which Scale i should put into haste so it will be fine.

**Comment by Hinalover** [comment]
If that happens, what I tend to do is make an executive decision of haste being 2/3rds - 3/4th the value of crit/vers (whichever is lower). And WDPS being half the value of crit/vers

**Comment by Manawanui** [comment]
Somehow it fixed after I've simulated with more haste, i feel like it was to low to scale, and i've seen before best haste is between 5-10%, now after I made it min %, it gives me normal scale, 6.5 or smthing like that. So its not bugged i guess ^%^
