### ISSUE TITLE
[Assassination Rogue]Subterfuge talent not working for garrote and Single target Subterfuge logic

### ISSUE THREAD

**Issue by Dakiel** [simulationcraft/simc#3193]
Quote from Wowhead
Subterfuge	Talent
Requires Rogue (Assassination, Subtlety)
Requires level 30
Your abilities requiring Stealth can still be used for 3 sec after Stealth breaks.

 Assassination
Also causes Garrote to deal 100% increased damage and have no cooldown when used from Stealth or 3 sec after Stealth breaks

If the damage buff for Garrote is working, we should find a pike on the Garrote damage graph about every 2 minutes(the cooldown of Vanish).
It should be quite obvious because this talent double the damage of Garrote.

What's more, I noticed that there is a comment in the source code.
Gives as much time as possible to spam Garrote if Subterfuge enabled (only useful on AoE)

But I think for single target if a rogue use Garrote when stealthed, and cast another Garrote to refresh the Garrote to 1.3 times the original duration.

For the live version, Subterfuge only buff 100% the damage of Garrote, 125% on PTR.
If my calculation is right, the bonus damage of double Garrote would be higher than the bonus damage of Nightstalker Rupture.

And the default food for Assassination Rogue should not be seedbattered_fish_plate(375 Vers) but 375 mastery one.

**Comment by navv1234** [comment]
The talent is working fine for Garrote, but the default APL is not taking advantage of it. @Aethys256 might know better why?

**Comment by Dakiel** [comment]
@Aethys256 Let me do the math comparing Subterfuge and Nightstalker for single target using Agonizing Poison.
There are two option for subterfuge when using Subterfuge talent.
1. Only use Garrote once, Garrote damage is 810% AP * 125% over 18 seconds.
2. Use Garrote once when break stealth, and use Garrote again to refresh the DoT before the subterfuge buff expire. The duration of this "super" garrote would be 18*1.3+2=25.4 seconds ( 2 seconds means the gap between two Garrote casts).

Considering the fact that latest simulation did not use Deep Strategem but Vigor, I would not consider 6 combo rupture.

For Nightstalker 5 combo rupture in 7.1.5, the extra damage would be 150% AP * 24/2 * 1.3 * 50%(Nightstalker buff) = **1170% AP during 31.2 seconds.**
Consider Blood of the Assassinated proc chance is 35%, the extra damage would be 1170% / ( 24 * 1.3 ) * ( 65% * 100% * ( 24 * 1.3 ) +  35% * ( 200% * 10 + 100% * ( 24 * 1.3 - 10 ))) = **1301.25 %**

For Subterfuge Garrote single use, the extra damage would be 810% AP * 125% (Subterfuge buff) = **1012.5 % AP during 18 seconds.**
For Subterfuge Garrote single use, the extra damage would be 810% AP / 18 * (2+18*1.3) * 125% (Subterfuge buff) = **1428.75 % AP during 25.4 seconds.** 

Let's talk about some other skills / buffs may have influence on this comparison.
Pros:
1. The duration of Vendetta is 20 seconds, the short duration of Garrote would be another advantage.
2. Players can cast this "super" Garrote once as starter and cast again with Vanish. Indeed, you can cast a Nightstalker 5 combo rupture as starter, but not every time you have 5 combo before combat ( especially in raid ). What's more, the 24s duration is shorter that 31.2s.

Cons:
1. The second Garrote would cost another 45 energy.
2. The stack of Agonizing Poison would be lower when entering the combat.

**Comment by aethys256** [comment]
Thanks, I'll look again what can I do to improve the APL.

**Comment by Dakiel** [comment]
@Aethys256 
Hi, actually I'm not talking about the APL.
What I am talking about is that the 125% Garrote damage boost from subterfuge is NOT working.

Let me simply show you a log(using T19H_NH profile with Nightstalker change to Subterfuge).
0.000 Rogue_Assassination_T19M_NH performs garrote (170)
2.000 Rogue_Assassination_T19M_NH garrote ticks (1 of 9) Fluffy_Pillow for 47529 physical damage (hit)
4.000 Rogue_Assassination_T19M_NH garrote ticks (2 of 9) Fluffy_Pillow for 47529 physical damage (hit)
4.178 Fluffy_Pillow gains agonizing_poison_1 ( value=0.04 )
5.494 Fluffy_Pillow gains agonizing_poison_2 ( value=0.04 )
6.000 Rogue_Assassination_T19M_NH garrote ticks (3 of 9) Fluffy_Pillow for 110042 physical damage (crit)
6.018 Fluffy_Pillow gains agonizing_poison_3 ( value=0.04 )
8.000 Rogue_Assassination_T19M_NH garrote ticks (4 of 9) Fluffy_Pillow for 118423 physical damage (crit)
8.028 Fluffy_Pillow gains agonizing_poison_4 ( value=0.04 )
9.034 Fluffy_Pillow gains vendetta_1 ( value=0.30 )
9.034 Fluffy_Pillow gains agonizing_poison_5 ( value=0.04 )
10.000 Rogue_Assassination_T19M_NH garrote ticks (5 of 9) Fluffy_Pillow for 92548 physical damage (hit)
12.000 Rogue_Assassination_T19M_NH garrote ticks (6 of 9) Fluffy_Pillow for 185095 physical damage (crit)
14.000 Rogue_Assassination_T19M_NH garrote ticks (7 of 9) Fluffy_Pillow for 92548 physical damage (hit)
15.061 Rogue_Assassination_T19M_NH performs garrote (51)
16.000 Rogue_Assassination_T19M_NH garrote ticks (1 of 11) Fluffy_Pillow for 185095 physical damage (crit)
18.000 Rogue_Assassination_T19M_NH garrote ticks (2 of 11) Fluffy_Pillow for 92804 physical damage (hit)
20.000 Rogue_Assassination_T19M_NH garrote ticks (3 of 11) Fluffy_Pillow for 92804 physical damage (hit)

It is apparently that Subterfuge is not working!

What's more, I also notice that there's a huge mistake in subterfuge APL.
It seems that Vanish would be casted 0.00s when using Subterfuge talent.
0.000 Rogue_Assassination_T19M_NH performs stealth
0.000 Rogue_Assassination_T19M_NH gains stealth_1 ( value=-0.00 )
0.000 Rogue_Assassination_T19M_NH schedules execute for vanish
0.000 Rogue_Assassination_T19M_NH performs vanish (170)
0.000 Rogue_Assassination_T19M_NH vanish hits Fluffy_Pillow for 0 physical damage (none)
0.000 Rogue_Assassination_T19M_NH gains vanish_1 ( value=-0.00 )
0.000 Rogue_Assassination_T19M_NH schedules execute for garrote

**Comment by aethys256** [comment]
I'll look at it when I'll be back.

**Comment by aethys256** [comment]
I improved as much as I could the APL in regards to this.
