### ISSUE TITLE
Star of Hollow Spite not working

### ISSUE THREAD

**Issue by marlaasinger** [simulationcraft/simc#3195]
Hey, just got the iron relic off of nightbane star of hollow spite, and when i try and sim it shows that i have the relic equipped but it doesn't add it stats. For example although when i scroll over my weapon after i simmed it says it has 3 relics equipped a 880, 865, and 875 however it shows its ilvl as 850 and my dps is severely down (around 55k) after equipping it when it should be up. Thanks in gneeral though this program has been incredibly useful just hoping you can fix this so i can keep getting accurate results.

**Comment by Collisionc** [comment]
Try the latest nightly - http://downloads.simulationcraft.org/?C=M;O=D - At the top. This should be fixed now.
