### ISSUE TITLE
Balance Druid priority list has a huge fail...

### ISSUE THREAD

**Issue by jmbruni** [simulationcraft/simc#3199]
Hi - I was simming my Boomkin and the priority lists the way you have them defined and the actual spell lists reveal something wrong in the inner code for the spec.  Astral Communion is used to charge your Astral Power back up so you can unload with Star Surge, Star Fall, or Fury of Elune, yet in the action lists have Astral Communion followed by a huge ton of Solar Wrath (Astral Power builder).  Upon further inspection the Astral Communion is adding it's 75AP but the Solar Wraths that follow are using AP instead of charging it...no wonder Star Surge is a rare thing in this list.  I have included the log file it produced...I think...if you need more please let me know.

Thank you!
[log.txt](https://github.com/simulationcraft/simc/files/611542/log.txt)

**Comment by jmbruni** [comment]
Hello, I've done some more looking at the scripting for the Balance Druid using talents 1300221 (includes Incarnation, Astral Communion, and Fury of Elune) and am seeing errors in the basic Astral Power calculations involving these talents.

The first problem - where AP is low and Astral Communion is cast, the AP goes up by 75, all is good...this is where the priority fails - after Astral Communion you must cast AP spenders or cap and the sim starts casting Solar Wrath which builds AP by 8 each cast - instead is subtracting 6AP with each cast...it isn't until a Moonfire is cast that the Wrath casts start adding AP again.

The second problem involves Fury of Elune which costs 6AP to cast and 12AP each second thereafter, with your AP pool modified by Fury AND whatever else you cast as Fury runs through your AP.  There is a point at the first Fury cast where a few Moon casts and a few Wrath casts were all very close to 1 second or 2 seconds apart making calculating the AP loss or gain can be fairly accutrate and the sim doesn't get it right at all (I have included a 30 second segment you can follow if you'd like)...

A step-by-step analysis:

1) t=14.05 AP shows 96, Fury of Elune is cast, AP remains at 96, should be 90

2) t=15.07 AP 96, Half Moon is cast - AP goes to 72...if 96 was right this should be 100, if 90 was there as it should be then AP should be 98 (-12AP/sec for Fury of Elune and +20 for Half Moon = +8AP)

3) t=16.41 AP says 72, Solar Wrath is cast - AP goes to 68.  (Fury of Elune still costs 12AP/sec and Wrath is +8AP - this combo should net -4AP so this calculation seems correct)

4) t=17,41 AP says 68, Solar Wrath is cast - AP goes to 62  (This should net the same -4AP as above but comes out as -6AP)

5) t=18.40 AP says 62, Full Moon is cast - AP goes to 56 (this is a consistent -6AP drop again but is also inaccurate.  1sec of Fury is -12AP, Full Moon is +40AP = +28AP for a new total of 90AP)

6) t=20.35 AP says 56, New Moon is cast - AP goes to 60.  (2 secs of Fury here = -24AP, New Moon is +10AP for a net of -14AP for this event.  56-14=42 or 90-14=76.)

7) t=21.32, AP says 60, Solar Wrath is cast - AP goes to 52.  (Fury = -12AP, Wrath = +8AP, total= - 4AP)

So....I am not sure where the equation fails but something is amiss and I don't think it is just Astral Communion...any help is appreciated.

PS - this all using the new 710-03 release.
[slice.txt](https://github.com/simulationcraft/simc/files/613105/slice.txt)

**Comment by Killuha** [comment]
Both of your problems come down to Fury of Elune(FoE) and how it works.

In the first case, you simply have FoE consuming astral power and Astral Communion is used to prolong the uptime of FoE, which is handled correctly by the APL.

The second case is due to FoE ticks scaling with haste, both damage and astral power drain and that you are reading the log wrong. 
The astral power shown is at the moment the action is taken, any gains or losses are reflected in the next entry.

1. t=14.05 asp 96 // FoE is cast, 

2. t=15.07 asp 72 //-6asp from initial FoE cast and -18asp from FoE drain, Half Moon cast begins.

3. t=16.41 asp 68 //+20asp from Half Moon and -24asp from 1.36seconds of FoE, Solar Wrath cast begins.

4. t=17,41 asp 62 //+12asp from Solar Wrath(Incarnation is active) and -18asp from FoE, Full Moon cast begins.

Hope that clears things up for you.

**Comment by jmbruni** [comment]
I have gone back to the logs and there is still an issue - though I think I have it pinned down a bit more.  I have enclosed some  documents in a couple formats for you:


1. "CURRENT moonkin run 1206.html" - a save generated by the Simulationcraft software and

2. "CURRENT moonkin run 1206.txt" - the log file generated by the software.

I took the line by line sim report (5 minutes and 344 lines) and parsed it manually adding a bunch of material -- I split out the per second damage done by Fury's DoT component since the 1 second intervals never seemed to fall on the same moments as other spells, and I added columns for my notes on AP+ events, AP- events, running totals of all of these, and a column showing the delta between the lines as the sim reported it.  I wanted to break out all the components so I wasn't guessing about the plus or minus numbers in the sim's report (ie: when a spell is cast either generating or using AP and the per second component of Fury of Elune is running - the total of the transaction is shown in the sim report as a plus or minus to AP but not all the components are displayed.)


The spreadsheet I sent is:


3. "CURRENT Moon ability list from 1206 sim.ods" from Open Office Calc (Excel) and

4.CURRENT Moon ability list from 1206 sim.pdf" - an exported version of #3


The spreadsheet, as mentioned above, is the saved html with modifications to allow me to parse it.  There is a note at the top and another at the bottom explaining format and results.  It's divided into 7 parts - parts 2, 4, and 6 are the Fury of Elune segments (2 and 4 also have Incarnation as a factor) and sections 1, 3, 5, and 7 are "standard rotation" segments.  Each part has the spells and their costs and benefits broken down with totals for my ap+, ap-, and ap running total columns.  These were compared with the AP value and percentage the program displays.


There is definitely a discrepancy between the manual and simulated results.  I studied the spell listings and noted some problems - namely that the Fury spell indicates a cost of 6 ap but never applies it - it also says something about a DoT component with a tick rate at 0.5s, which isn't accurate.  The Fury (ticks) listing is the DoT component and it lists no  costs at all nor does it refer to DoT damage. Is it possible these were added in reverse?  Also it seems like the decrement or increment value is just incorrect.


There is also an issue with the Incarnation spell...all the damage and haste benefits seem to be accurate but there is a multiplier to AP generated by Solar Wrath and Lunar Strike which I don't think is working.  Solar Wrath generates 8AP per cast unless Incarnation is up in which case it is 1.5x for 12AP generated.  The same 1.5x multiplier applies to Lunar Strike, making its +12AP become +18AP with Incarnation.  I don't see the multiplier in any of the tooltips attached to the notes in the program.


These are how the spells work according to in-game tooltips and monitoring...


Fury of Elune costs 6ap to cast and ticks for -12 ap per second.


Incarnation gives a 1.35X modifier to damage by LS and SW and gives a 1.50X modifier to the AP generated by them.  LS generates 12 AP baseline (18 modified) and SW generates 8 AP baseline (12 modified).


I hope all this isolates demonstrates the problems I see and that they are easily correctable.


It's funny that you mentioned Haste scaling for the spells because I am doing all this as a spin-off from my discovery that Haste is unwanted on the Moonkin (I had been stacking it previously) and that Versatility is the top stat (at least on the last 6 or 7 scaled sims I've done on my toon and using your prebuilt models.)  I've taken my Haste from 22% back to about 8% and am trying to channel everything into Versa.  I am not yet sure about the damage output but the "rotation" sure feels smoother.


Please let me know how all this looks to you and if there is anything I can do to help on this or any other project you are working on (yes, I am volunteering).  I appreciate your efforts on this and everything else you and the team do.  Thanks!


Mike Bruni

jmbruni@msn.com




________________________________

**Comment by Collisionc** [comment]
This is the debug log from a balance druid as of today, the only odd thing is that internally we have fury of elune consuming 6 astral power every 0.5 seconds, but that's the same as consuming 12 every 1 second (non-hasted.)

210.182 Druid_Balance_T19M gains 7.00 (8.00) astral_power from solar_wrath (100.00/100.00)
210.186 Druid_Balance_T19M gains incarnation_chosen_of_elune_1 ( value=0.35 )
210.186 Druid_Balance_T19M performs fury_of_elune (100)
210.186 Druid_Balance_T19M consumes 6.0 astral_power for fury_of_elune (94)
210.535 Druid_Balance_T19M: fury_of_elune consumes ticking cost 6.0 (6.0) astral_power for fury_of_elune (88).
210.881 Druid_Balance_T19M: fury_of_elune consumes ticking cost 6.0 (6.0) astral_power for fury_of_elune (82).
213.655 Druid_Balance_T19M gains 12.00 (12.00) astral_power from solar_wrath (66.00/100.00)

It looks like everything is working properly, it's just that our html output can be difficult to read since the resource gains typically happen after the spell has been cast.
