### ISSUE TITLE
Unstable Affliction is refunding Soul Shards while wearing Recurrent Ritual

### ISSUE THREAD

**Issue by treisk** [simulationcraft/simc#3200]
When simming Affliction DPS, I noticed it was abnormally high. Upon further inspection, I noticed that a large majority of my time spent casting was spent casting UA, rather than Drain Life. I then looked at the Soul Shard tracker and noticed this:

http://puu.sh/stISM/abbadd5bb5.png

Log: http://pastebin.com/raw/RJgVH5v2

**Comment by Foo0** [comment]
It's the Demonology Shoulders, Recurrent Ritual, or at least it is for me. Seeing the same bug.

**Comment by treisk** [comment]
Am also using Recurrent Ritual. This is likely the cause. Editing title to reflect.

**Comment by navv1234** [comment]
This should be fixed in cf3d8c7d57be69f1990d7acf6d08e036467279d5.
