### ISSUE TITLE
[Client] Blank window into not responding on startup

### ISSUE THREAD

**Issue by skarlsen** [simulationcraft/simc#3202]
Hi there!

I have been experiencing this issue since I returned to WoW at the release of Legion. That includes several 7.0 and 7.1 versions of the client.
The issue happens upon starting the client. The window appears, but is completely blank. After a few moments, it just tells me that the application is not responding. This happens with both the 32- and 64-bit versions. 

However, uninstalling and reinstalling the program sometimes solves the problem for what appears to be exactly one program startup. I haven't been able to pinpoint what causes the uninstall and reinstall procedure to only sometimes work. After closing the program, the same issue reappears. That happens even when doing nothing in the first session (no importing character, no simulation, no options changing. Literally nothing, just opening and closing it). 

When uninstalling (and removing the remaining files from the folder) and reinstalling the program, no simc_gui.simc file or any other error log file is created.

This happens on Windows 10, build 1607 ("Redstone 1"/"Anniversary Update") with no other anti-virus than Windows Defender.

**Comment by Collisionc** [comment]
Try the .7z version to see if maybe there's something wrong with our installer: http://downloads.simulationcraft.org/simc-710-03-win64-84c44bc.7z

Winrar or 7zip can open that, just extract and run.

**Comment by skarlsen** [comment]
Sorry for the late reply.
Still seeing this issue when downloading .7z instead of installer. This is for 32-, and 64-bit, as well as nightly builds. I haven't been able to narrow down what's causing the issue, but I have figured out that a reinstall isn't the only way to solve it. Sometimes, I can open it up, getting the blank window and 'not responding'-error, only to open it back up 15 seconds later to it working.

**Comment by Collisionc** [comment]
What video card are you using, as well as the driver? (Just post dxdiag if you can)

**Comment by skarlsen** [comment]
https://gist.github.com/skarlsen/a1b4881dacfa9c4cefa6388ee2596fe7

**Comment by Collisionc** [comment]
Try this: 

Create an environment variable named QT_OPENGL
Instructions for making environment variables: https://kb.wisc.edu/cae/page.php?id=24500
Set QT_OPENGL to one of the following - Try software first, then desktop, then angle
software
desktop
angle
After setting QT_OPENGL to any of those 3, reload simulationcraft to see if it works.

**Comment by skarlsen** [comment]
Just wanted to tell you that I haven't encountered this issue after setting the 'QT_OPENGL = software' environment variable. I haven't used SimulationCraft extensively over the holidays, but I have used it enough for it would be highly unlikely to not have encountered the issue, should the variable not already have fixed it. Thanks for the help @Collisionc
