### ISSUE TITLE
[DH Vengeance] consume magic missing in APL

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#3203]
Please add consume_magic if the target is casting a spell for increased pain generation

**Comment by Zarania** [comment]
Fixed in 4515207944443dbbe54733de724297b1e8b31b06

**Comment by Hemario** [comment]
I don't see it in the APL script. Can you check again?

**Comment by Zarania** [comment]
I added it then merged in their changes and commited.  Here's the raw change:  https://github.com/simulationcraft/simc/commit/e21216cf558c41be18f7627e75f439dfa6b9ad76

It will be in the next nightly build that is after the commit listed.
