### ISSUE TITLE
[Fire Mage] Empowered Spellblade (lvl 35 artifact trait) has no effect

### ISSUE THREAD

**Issue by Sneepsin** [simulationcraft/simc#3207]
The lvl 35 artifact weapon trait (5% fire damage) has no effect on dps

**Comment by vituscze** [comment]
This has been implemented in https://github.com/simulationcraft/simc/commit/bbfacb513c857621813d58df399c6fb62e179370

Get the newest version and it should work.

**Comment by Frostedmages** [comment]
Already fixed, closing.
