### ISSUE TITLE
[Survival Hunter] Default priority list - raptor strike not used, when throwing axes are skilled

### ISSUE THREAD

**Issue by Plategoron** [simulationcraft/simc#3208]
Sadly, I'm too much of a noob to change the file myself.

The default action priority for survival hunters has this as the last line:

actions+=/raptor_strike,if=!talent.throwing_axes.enabled&focus>75-cooldown.flanking_strike.remains*focus.regen

Which means, raptor strike does not get used, when throwing axes are skilled.
Since it's the last line anyway and the 75 focus leftover make sure, that flanking strike and lacerate can still be used directly after, the restriction of not having throwing axes should be removed, like this:

actions+=/raptor_strike,if=focus>75-cooldown.flanking_strike.remains*focus.regen

You could even improve the cap, at which raptor strike gets used, by substracting another global cooldown with focus.regen. Not quite sure, how global cooldown is implemented in code, but it should be something like this:
actions+=/raptor_strike,if=focus>75-(gcd+cooldown.flanking_strike.remains)*focus.regen

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/06f88a2975046750971ec58555c302ea3194ccae
