### ISSUE TITLE
[Balance Druid] Emerald Dreamcatcher priority list incorrect

### ISSUE THREAD

**Issue by Slippykins** [simulationcraft/simc#3209]
The current priority list using build 710-03 does not model the legendary The Emerald Dreamcatcher properly for haste above 30%. In this scenario, the optimal rotation is:
(1) Pool 100 AP -> 
(2) Starsurge -> Lunar Strike -> Starsurge -> 2x Solar Wrath -> repeat from (2) until AP depleted.

As such, the priority list should read:

actions.ed+=/solar_wrath,if=buff.solar_empowerment.stack>=2&buff.the_emerald_dreamcatcher.remains>execute_time*2
actions.ed+=/lunar_strike,if=buff.lunar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time
actions.ed+=/solar_wrath,if=buff.solar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time
actions.ed+=/new_moon,if=astral_power<=90
actions.ed+=/half_moon,if=astral_power<=80&!buff.the_emerald_dreamcatcher.up
actions.ed+=/full_moon,if=astral_power<=60&!buff.the_emerald_dreamcatcher.up

**Comment by Collisionc** [comment]
Is this still the case with the recent changes to the helm?

**Comment by Slippykins** [comment]
Yes, the helm rotation is consistent with pre-7.1.5. Only the duration of Starsurge-weaving was altered.

**Comment by Slippykins** [comment]
An updated ED APL is provided below, courtesy of Jundarer. It performs better than the one suggested above, but is much more complex.

actions.ed=astral_communion,if=astral_power.deficit>=75&buff.the_emerald_dreamcatcher.up
actions.ed+=/incarnation,if=astral_power>=85&!buff.the_emerald_dreamcatcher.up|buff.bloodlust.up
actions.ed+=/celestial_alignment,if=astral_power>=85&!buff.the_emerald_dreamcatcher.up
actions.ed+=/starsurge,if=(buff.celestial_alignment.up&buff.celestial_alignment.remains<(10))|(buff.incarnation.up&buff.incarnation.remains<3*execute_time&astral_power>78)|(buff.incarnation.up&buff.incarnation.remains<2*execute_time&astral_power>52)|(buff.incarnation.up&buff.incarnation.remains<execute_time&astral_power>26)
actions.ed+=/stellar_flare,cycle_targets=1,max_cycle_targets=4,if=active_enemies<4&remains<7.2&astral_power>=15
actions.ed+=/moonfire,if=((talent.natures_balance.enabled&remains<3)|(remains<6.6&!talent.natures_balance.enabled))&(buff.the_emerald_dreamcatcher.remains>gcd.max|!buff.the_emerald_dreamcatcher.up)
actions.ed+=/sunfire,if=((talent.natures_balance.enabled&remains<3)|(remains<5.4&!talent.natures_balance.enabled))&(buff.the_emerald_dreamcatcher.remains>gcd.max|!buff.the_emerald_dreamcatcher.up)
actions.ed+=/starfall,if=buff.oneths_overconfidence.up&buff.the_emerald_dreamcatcher.remains>execute_time&remains<2
actions.ed+=/half_moon,if=astral_power<=80&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=6
actions.ed+=/full_moon,if=astral_power<=60&buff.the_emerald_dreamcatcher.remains>execute_time
actions.ed+=/solar_wrath,if=buff.solar_empowerment.stack>1&buff.the_emerald_dreamcatcher.remains>2*execute_time&astral_power>=6&(dot.moonfire.remains>5|(dot.sunfire.remains<5.4&dot.moonfire.remains>6.6))&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=90|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85)
actions.ed+=/lunar_strike,if=buff.lunar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=11&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=77.5)
actions.ed+=/solar_wrath,if=buff.solar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=16&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=90|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85)
actions.ed+=/starsurge,if=(buff.the_emerald_dreamcatcher.up&buff.the_emerald_dreamcatcher.remains<gcd.max)|astral_power>90|((buff.celestial_alignment.up|buff.incarnation.up)&astral_power>=85)|(buff.the_emerald_dreamcatcher.up&astral_power>=77.5&(buff.celestial_alignment.up|buff.incarnation.up))
actions.ed+=/starfall,if=buff.oneths_overconfidence.up&remains<2
actions.ed+=/new_moon,if=astral_power<=90
actions.ed+=/half_moon,if=astral_power<=80
actions.ed+=/full_moon,if=astral_power<=60&((cooldown.incarnation.remains>65&cooldown.full_moon.charges>0)|(cooldown.incarnation.remains>50&cooldown.full_moon.charges>1)|(cooldown.incarnation.remains>25&cooldown.full_moon.charges>2))
actions.ed+=/solar_wrath,if=buff.solar_empowerment.up
actions.ed+=/lunar_strike,if=buff.lunar_empowerment.up
actions.ed+=/solar_wrath

**Comment by Collisionc** [comment]
Allright, added. Thanks !
