### ISSUE TITLE
Demon Hunter 35 Artifact Trait Chaos Burn Bugged

### ISSUE THREAD

**Issue by Diablobtm** [simulationcraft/simc#3212]
The 35th Demon Hunter Trait, Chaos Burn, which increases all damage by 5% isn't working.  Saw a similar problem listed with the Fire Mage Spell Blade, which was fixed recently.

**Comment by martinhoite** [comment]
Had the same "problem" with WW monk trait, that was added in an update so make sure you're using the latest version: http://downloads.simulationcraft.org/?C=M;O=D

Direct link to the version where it's most likely fixed:
http://downloads.simulationcraft.org/SimcSetup-710-03-Win64.exe

That said, I can't find _any_ mention of Chaos Burn in the [Demon Hunter Engine](https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_demon_hunter.cpp)

**Comment by Diablobtm** [comment]
Downloaded the latest one before making the ticket.

**Comment by Morphinicus** [comment]
I am seeing this issue with the build from 12-05-16. I ran two tests with my DH(Same gear), one with 34 traits and one with 35 traits and the DPS number was the same, 412k DPS

**Comment by Morphinicus** [comment]
This issue has been fixed.

**Comment by SagepathSReinhardt** [comment]
Fixed in 42b17b202966ec13fb18ea5f02a5c60842316d1e

**Comment by Zarania** [comment]
Fixed in 42b17b2
