### ISSUE TITLE
Worldbreaker's resolve still effective at max level

### ISSUE THREAD

**Issue by a3ng7n** [simulationcraft/simc#3215]
It looks like the trinket from hellfire citadel is still effective at level 110, even though the tooltip says that the trinket only works up to 109.

The following is a screenshot of the results from a trinket comparison I did - the buff in question is the "Berserker's Fury" buff, which shouldn't be occurring:
![image](https://cloud.githubusercontent.com/assets/4608714/20857353/215c63d6-b8de-11e6-87c9-a2f2f2c72fdd.png)

And here's the gear listing from that run:
![image](https://cloud.githubusercontent.com/assets/4608714/20857355/4b42f05c-b8de-11e6-9e0e-3c03a8329167.png)

Finally, attached are the results - see result G_14:
[worldbreakers_bug.zip](https://github.com/simulationcraft/simc/files/628722/worldbreakers_bug.zip)

**Comment by a3ng7n** [comment]
Also, the version of the program I'm using is 710-02.

**Comment by Collisionc** [comment]
Thanks, I'll break it for level 110.
