### ISSUE TITLE
 Draugr, Girdle of the Everlasting King - Rune Generation

### ISSUE THREAD

**Issue by Diablobtm** [simulationcraft/simc#3216]
The rune generation feature of Draugr, Girdle of the Everlasting King seems off, as a the number of festering strikes utilized in comparing sims with and without is negible.  I believe instead of having a 30% chance to proc the item is operating at only a 3% chance in the sim, so just a missed decimal point.

**Comment by navv1234** [comment]
You can see exactly how many times it procced, the Gains section in the report should have the number of procs. Looking at the code, it has the correct proc rate, so the issue could potentially be in the action priority list.

**Comment by Diablobtm** [comment]
Yeah I see it, seems alright where it concerns the proc rate.  Good catch in the gains section, since executed festering strike 59 times and got 17 runes so yeah, we're good there.  Still, the net increase on DPS doesn't seem correct and so I'm thinking action priority list as well now.
