### ISSUE TITLE
SimulationCraft vs bags

### ISSUE THREAD

**Issue by sektr63a** [simulationcraft/simc#3218]
Hello! Thanks for a good program, guys. It`s perfect!
Can you add, please, scanning bags function for check best items that player has
Sorry for my English.
Thanks!

**Comment by mitzzz** [comment]
[https://mods.curse.com/addons/wow/254069-simpermut](url)

**Comment by NicolasMuzette** [comment]
> https://mods.curse.com/addons/wow/254069-simpermut

404 :/
