### ISSUE TITLE
[Guardian Druid] Adaptive Fur increases incoming magic damage

### ISSUE THREAD

**Issue by Symondus** [simulationcraft/simc#3219]
When simulating my guardian druid i noticed quite inflated incoming magic damage. I could track the issue to the artefact trait adaptive fur that resulted in about 4 times as high magic damage as without the trait.

**Comment by Symondus** [comment]
I could track the error further to 

the target_mitigation function in sc_druid.cpp 

in the line
s -> result_amount *= 1.0 + buff.adaptive_fur -> value();

the value() function returns the spell shool and not the percentage change -0.10.

**Comment by Collisionc** [comment]
Thanks.
