### ISSUE TITLE
Druid Balance Talent "Nature's Balance" doesn't extend dot duration correctly

### ISSUE THREAD

**Issue by Jundarer** [simulationcraft/simc#3220]
Sunfire works if you manually extend the base duration from 2 seconds to the correct 4 seconds but it does not seem to extend the duration of moonfire at all. Atm in the balance spells list the base values are 2 and 4 seconds while they are actually 4 and 6 scaling with haste. Also the max duration of each dot does not seem to be supported.

**Comment by Collisionc** [comment]
Sorry for the delay, got it. I'll add in AoE stuff later.
