### ISSUE TITLE
Simcraft Crashing when i try to Simulate.

### ISSUE THREAD

**Issue by Tormention** [simulationcraft/simc#3221]
Here is the Simc_gui.

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
deathknight="Rebekah"
origin="https://us.api.battle.net/wow/character/ghostlands/Rebekah/advanced"
thumbnail="http://us.battle.net/static-render/us/ghostlands/124/132392572-avatar.jpg"
level=110
race=human
role=attack
position=back
professions=mining=643/herbalism=640
talents=http://us.battle.net/wow/en/tool/talent-calculator#dZ!1122112
artifact=12:0:0:0:0:108:3:113:3:117:3:119:1:122:1:124:1:1090:3:1332:1
spec=frost

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,name=countless_armies
actions.precombat+=/food,name=fishbrul_special
actions.precombat+=/augmentation,name=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war

# Executed every time the actor is available.
actions=auto_attack
actions+=/pillar_of_frost
actions+=/mind_freeze
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury,if=!talent.breath_of_sindragosa.enabled|dot.breath_of_sindragosa.ticking
actions+=/berserking,if=buff.pillar_of_frost.up
actions+=/use_item,slot=trinket2
actions+=/potion,name=old_war
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up
actions+=/obliteration
actions+=/breath_of_sindragosa,if=runic_power>=50
actions+=/run_action_list,name=bos,if=dot.breath_of_sindragosa.ticking
actions+=/call_action_list,name=shatter,if=talent.shattering_strikes.enabled
actions+=/call_action_list,name=generic,if=!talent.shattering_strikes.enabled

actions.bos=howling_blast,target_if=!dot.frost_fever.ticking
actions.bos+=/call_action_list,name=core
actions.bos+=/horn_of_winter
actions.bos+=/empower_rune_weapon,if=runic_power<=70
actions.bos+=/hungering_rune_weapon
actions.bos+=/howling_blast,if=buff.rime.react

actions.core=frost_strike,if=buff.obliteration.up&!buff.killing_machine.react
actions.core+=/remorseless_winter,if=(spell_targets.remorseless_winter>=2|talent.gathering_storm.enabled)&!(talent.frostscythe.enabled&buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/frostscythe,if=(buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/glacial_advance,if=spell_targets.glacial_advance>=2
actions.core+=/frostscythe,if=spell_targets.frostscythe>=3
actions.core+=/obliterate,if=buff.killing_machine.react
actions.core+=/obliterate
actions.core+=/glacial_advance
actions.core+=/remorseless_winter,if=talent.frozen_pulse.enabled

actions.generic=howling_blast,target_if=!dot.frost_fever.ticking
actions.generic+=/howling_blast,if=buff.rime.react
actions.generic+=/frost_strike,if=runic_power>=80
actions.generic+=/call_action_list,name=core
actions.generic+=/horn_of_winter,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/horn_of_winter,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/frost_strike,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/frost_strike,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/empower_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/hungering_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/hungering_rune_weapon,if=!talent.breath_of_sindragosa.enabled

actions.shatter=frost_strike,if=debuff.razorice.stack=5
actions.shatter+=/howling_blast,target_if=!dot.frost_fever.ticking
actions.shatter+=/howling_blast,if=buff.rime.react
actions.shatter+=/frost_strike,if=runic_power>=80
actions.shatter+=/call_action_list,name=core
actions.shatter+=/horn_of_winter,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/horn_of_winter,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/frost_strike,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/frost_strike,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/empower_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/hungering_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/hungering_rune_weapon,if=!talent.breath_of_sindragosa.enabled

head=deathlords_helm,id=139676,bonus_id=3385/3383
neck=tightweb_choker,id=134541,bonus_id=1727/1492/1813
shoulders=nightsfall_shoulderplates,id=139060,bonus_id=3474/40/1507/1674
back=evergreen_vinewrap_drape,id=139248,bonus_id=1807/1808/1472,gems=150haste,enchant=150str
chest=skoldiir_breastplate,id=134179,bonus_id=3396/1487/1675
tabard=tabard_of_brute_force,id=43349
wrists=demonsteel_armguards,id=123917,bonus_id=689/1696/3408/601/668
hands=tarnished_dreamkeepers_gauntlets,id=141695,bonus_id=1805/1492/3336
waist=waistplate_of_nameless_horror,id=139227,bonus_id=1807/1472
legs=greaves_of_the_godking,id=133630,bonus_id=3411/1507/3336
feet=rockbound_sabatons,id=134141,bonus_id=3432/1502/3336
finger1=dingy_wedding_band,id=134534,bonus_id=1727/1492/1813,enchant=150haste
finger2=band_of_fused_coral,id=134532,bonus_id=1726/1477
trinket1=ursocs_rending_paw,id=139328,bonus_id=1805/41/1487
trinket2=vindictive_gladiators_badge_of_victory,id=135700,bonus_id=3428/41/1472
main_hand=blades_of_the_fallen_prince,id=128292,bonus_id=717,gem_id=140416/139268/139250/0,relic_id=3428:1637:3336/1807:1472/1807:1472/0,enchant=rune_of_razorice
off_hand=blades_of_the_fallen_prince,id=128293,enchant=rune_of_the_fallen_crusader

# Gear Summary
# gear_ilvl=848.50
# gear_strength=12984
# gear_stamina=18297
# gear_crit_rating=4816
# gear_haste_rating=7711
# gear_mastery_rating=3031
# gear_versatility_rating=310
# gear_leech_rating=847
# gear_avoidance_rating=412
# gear_armor=4001

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by Collisionc** [comment]
Not able to reproduce, are you using 710-03 nightly? ex:  http://downloads.simulationcraft.org/simc-710-03-win64-cdbd392.7z

**Comment by Collisionc** [comment]
Try this version, actually: http://downloads.simulationcraft.org/simc-710-03-win64-4238a18.7z

**Comment by Collisionc** [comment]
Also post your dxdiag. : ) 

Instructions: https://us.battle.net/support/en/article/Obtaining-System-Files
