### ISSUE TITLE
Ursoc's Rending Paw - Possibly Simming Incorrectly (Fury Warrior)

### ISSUE THREAD

**Issue by Talique** [simulationcraft/simc#3224]
Comparing in-game damage logs, damage meters and online log services, it appears that Ursoc's Rending Paw does more damage in-game (for a fury warrior) than it sims in Simcraft (both version 710-03 and 710-02).  I've been trying to figure out why (but I am not knowledgeable enough about how simcraft works front end or back to determine exactly why). 

I saw a prior fix by Collisionc regarding it snapshotting Damage Amplifiers (Dragons Roar [20% Damage) and Stat Mods (Battle Cry [100% Crit]). Comparing results I get from simcraft against the other sources, I'm seeing higher Max ticks everywhere else.

Perhaps this is a unique to Fury thing (our mastery does scale Ursoc's tick damage). Simcraft is returning me a maximum tick (on Crit) of 61k and I have seen upwards of 85k in game (and on logs) w/ 37% mastery currently.

Log with an example (118k Tick): https://www.warcraftlogs.com/reports/vb1c8pHBmWxLFNtf#fight=30&type=damage-done&source=16&ability=221770
My Armory (incase needed): http://us.battle.net/wow/en/character/thunderhorn/Talic/simple

To replicate in-game higher than Simmed procs 100% of the time, I'm Avatar->Dragon's Roar -> Reck -> (Bloodthirst target to engage auto attack + force enrage) -> auto-attack crit

**Comment by gixxpunk** [comment]
Same for Frost DK. Paw sims significantly lower compared to warcraftlogs.

**Comment by Collisionc** [comment]
Blizzard has adjusted that trinket multiple times, they probably tweaked it again, should be easy to fix.

**Comment by Collisionc** [comment]
Ah, it's a stupid ignite. I forgot to implement that part.

**Comment by Collisionc** [comment]
Ok, I think that's much closer now. Ends up being 3.3%~ of your damage using that character.
