### ISSUE TITLE
[Frost mage] Spellborne incorrectly boosts Icicle damage

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3225]
Spellborne (Frost mage paragon trait) applies its damage bonus twice. Once when an Icicle is created after Frostbolt deals damage and then again when the Icicle is fired and deals damage. It should apply only when Icicle is created and not when it deals damage.

Tested with both legion-dev and mage-legion-dev.

**Comment by Frostedmages** [comment]
fixed in mage-legion-dev
