### ISSUE TITLE
Toravon's Whiteout Bindings

### ISSUE THREAD

**Issue by Ophidon** [simulationcraft/simc#3226]
I am unsure the bonus from this Frost DK legendary is applying correctly. Putting these on raised my overall dps on the sim by only around 3k (which would be explained immediately by about the 265ish STR gain they gave me). Furthermore, I can beat the sim number now, on a ST test dummy, on a sustained 5m fight, without the benefit of hero or pots. Before, that never would have happened.

 Also, I also can find no mention of the Toravon's Whiteout Bindings buff in the sim buff list.

**Comment by navv1234** [comment]
The bonus from Toravon's Whiteout Bindings is applying correctly. We do not signal it's presence in any way (is there a separate buff for this in game?), but rather just grant a passive 15% frost damage increase while Pillar of Frost is up. Closing this for now. The issues with you "beating" the simulator are more than likely related to the default action list, which we are always accepting improvements for.
