### ISSUE TITLE
Enable scaling freezing PC

### ISSUE THREAD

**Issue by mondayzc** [simulationcraft/simc#3227]
Tried both 64 & 32 bit of the current build and the most recent beta ones. Also "reset all settings" and tried again. Last week I could use the scaling option without a hitch, so it's weird.

here's simc_gui:

### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers,wdps
center_scale_delta=1
scale_over=DPS
statistics_level=1
### Begin simulateText ###
druid="raid"
level=110
race=night_elf
region=us
server=firetree
role=attack
professions=engineering=726/jewelcrafting=786
talents=3311322
spec=feral
artifact=58:0:0:0:0:1153:1:1154:1:1155:1:1156:1:1157:1:1158:1:1159:1:1160:3:1161:3:1162:3:1163:3:1164:3:1165:3:1166:3:1167:3:1168:3:1327:1

head=,id=134447,bonus_id=3418/1808/1527/3336,gem_id=130222
neck=,id=132444,enchant_id=5439,bonus_id=1811,gem_id=130222
shoulder=,id=134374,enchant_id=5881,bonus_id=3414/1537/3337
back=,id=137530,enchant_id=5435,bonus_id=3509/1808/1522/1813,gem_id=130222
chest=,id=139208,bonus_id=1806/1502
tabard=,id=20132
wrist=,id=137056,bonus_id=3459/3458
hands=,id=134371,bonus_id=3510/1547/3337
waist=,id=134199,bonus_id=3510/1552/3337
legs=,id=134450,bonus_id=3418/1532/3337
feet=,id=135599,bonus_id=3451/1688/1507/3336
finger1=,id=134531,enchant_id=5429,bonus_id=3414/1808/1507/1813,gem_id=130219
finger2=,id=137533,enchant_id=5427,bonus_id=3418/1532/3337
trinket1=,id=139329,bonus_id=1805/1808/1492/3336,gem_id=130221
trinket2=,id=136144,bonus_id=3476/607/1472/1813
main_hand=,id=128860,bonus_id=723,relic_id=3418:1527:3336/3451:3139:3337/3412:1527:3337,gem_id=133683/140413/137307/0
off_hand=,id=128859,relic_id=0/0,gem_id=0/0/0/0

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by Collisionc** [comment]
Are you using the installer or the .7z file ?

**Comment by Collisionc** [comment]
Also see if this fixes it: 
http://downloads.simulationcraft.org/simc-710-03-win64-4238a18.7z

**Comment by Collisionc** [comment]
If that doesn't work, try adding

decorated_tooltips=0

at the bottom of your simulation.
