### ISSUE TITLE
Rogue (for new PTR build) => BtE fixed!

### ISSUE THREAD

**Issue by NetRollTUZ** [simulationcraft/simc#3229]
Tonight they finally fixed "Between the Eyes" cooldown self-reduction under "True Bearing" buff. On PTR.
So in buid for 7.1.5 you may disable fix for that bug.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/9fb8a83235f00ea797e2b6172fbcd562a697cfa0
