### ISSUE TITLE
[Frost mage] Spellborne doesn't affect Water Elemental

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3230]
In SimC, Spellborne currently works with player damage and not pet damage. However, according to in-game testing, Spellborne also boosts pet damage.

    int = 35372
    mastery = 0.3585
    vers = 0.0544

    coef = 1.0
    cold_outside = 1.3
    pet_sp_mult = 0.75

    waterbolt_dmg = int * pet_sp_mult * coef * cold_outside * (1 + mastery) * (1 + vers)
                  = 49400

    waterbolt_dmg_range = (waterbolt_dmg * 0.875, waterbolt_dmg * 1.125)
                        = (43225, 55575)

My highest recorded Waterbolt damage is 58904, which should only be possible if Spellborne affects Water Elemental (3/20 Spellborne gives max damage 58910).

Same thing goes for Water Jet. Highest possible tick without Spellborne with the same stats as above is 30182, highest recorded tick is 31990.

**Comment by Frostedmages** [comment]
fixed in mage-legion-dev.

**Comment by vituscze** [comment]
I don't want to open separate issue as it's pretty much the same thing, so here goes.

Frostbolt used by Mirror Image pets also works with Spellborne. I suspect that will require the same fix.

Water Jet is also behaving in a weird way. It is affected by Spellborne, but not by Incanter's Flow or Rune of Power (current SimC Water Jet is affected by all three). I pointed out this inconsistency in a PTR feedback post, but for now, that is the current behavior on both live and PTR.

**Comment by Frostedmages** [comment]
Fixed.

As for WJ, that sounds like an in game bug? If it still exists when 715 goes live I'll update the sim to reflect the bug in the game, but for now we can hope it gets fixed (and it's pretty minor in the overall dps output).
