### ISSUE TITLE
SimulationCraft not working

### ISSUE THREAD

**Issue by sahandil** [simulationcraft/simc#3231]
Hi,
So I'm struggling to get simulcraft working for a full week now, the problem occur when I try to start the program it doesn't open a gives me an 0xc000007b error (if I use the 64bits version) or a 0xc00005 error for the 32bits,
 I tried using package files and .exe I tried older and last released version and I always get the same result, well no and that's the strange part sometime just after re-instalaltion of the soft it will open using the (launch simulationcraft after finish installation) but not everytime, when this happen i can use it normally but if I dare to close it it will never start again.

Ps: My visual c++ packages are up to date http://imgur.com/a/xSm8J

**Comment by Collisionc** [comment]
If you change the location where it is installed, does it make a difference ? Try C:\Program Files (x86)\Simulationcraft\

**Comment by Collisionc** [comment]
Also, can you post your dxdiag here?

Instructions:   https://us.battle.net/support/en/article/Obtaining-System-Files

**Comment by sahandil** [comment]
Hi, sorry for the wait I wasn't in town
I was already installing it in C:\Program Files (x86)\Simulationcraft\  so I tried to do it somewhere else (even on an other disck) and it still change nothing.

I linked the dxdiag to this message
Thx for your time
[Dxdiag.txt](https://github.com/simulationcraft/simc/files/665331/Dxdiag.txt)

**Comment by Collisionc** [comment]
Try this:

Create an environment variable named QT_OPENGL
Instructions for making environment variables: https://kb.wisc.edu/cae/page.php?id=24500
Set QT_OPENGL to one of the following - Try software first, then desktop, then angle
software
desktop
angle
After setting QT_OPENGL to any of those 3, reload simulationcraft to see if it works.

**Comment by sahandil** [comment]
Still not working after trying that so I went with an "easier" solution, just running it in a virtual machine and it works  okay, so I don't know what's wrong with my OS but thank you for your help trying to fix it, I hope it won't happen to someone else.

Thanks again, cheers

**Comment by Collisionc** [comment]
Yeah, unfortunately there are just some computer configurations that the QT Library we use for the GUI doesn't currently work with. :( Blizzard has had some of the same/similar crashing issues with the b.net client as well, as they use QT  as well. 

Generally, Windows 7 + Radeon 7xxx/6xxx (and prior) series have issues it seems. Running in a VM is a good workaround, though. 

Try newer versions out in a few months, we're very aware of these crashes on computers like yours, and will continue to look for ways to workaround them.

**Comment by Sparrow1988** [comment]
As strange as it sounds go and check if u have both 32 bit and 64 bit visual c++ packages cause I had been missing one that was 32 bit and instaled it and that solved my problem with simcraft. Hope that helps.
