### ISSUE TITLE
[Assassination] Vendetta usage with 3 MA relics and exsanguinate

### ISSUE THREAD

**Issue by Mangustimon** [simulationcraft/simc#3232]
Current APL isn't taking advantage of reduced CD of vendetta when using MA relics. APL still wants to wait exsang before using vendetta and this isn't optimal. The current vendetta action is:

actions.cds+=/vendetta,if=talent.exsanguinate.enabled&cooldown.exsanguinate.remains<5&dot.rupture.ticking

Removing "cooldown.exsanguinate.remains<5" results a huge (>10k ) dps gain when using 3 MA relics. I tested this with my char and mythic sample profile. I'm not sure what is the best possible vendetta (or exsang) usage with 3 MA relics, but even this fix results massive dps boost.

**Comment by omeomorfismo** [comment]
hi
i actually use
actions.cds+=/vendetta,if=talent.exsanguinate.enabled&energy.deficit>=75
actions.cds+=/vendetta,if=!talent.exsanguinate.enabled&(!artifact.urge_to_kill.enabled|energy.deficit>=88)

for 3MA, 3MA+boots, and 2MA+boots, all with EP
for the last maybe the energy is different, i dont try very much
