### ISSUE TITLE
[MM Hunter] Lone wolf does not interact properly with Aran's.

### ISSUE THREAD

**Issue by Dumbdragon** [simulationcraft/simc#3234]
As the title describes - SimC does not seem to factor in the +18% damage buff from Lone Wolf when calculating Aran's damage. Numbers:

On my tooltip:  https://gyazo.com/970e81a53aa80069387c271dbb203944 365K.
On SimC: https://gyazo.com/e8d4774bd7e53c5d4ef25ac06a2e5fef 383.5K. This fits; 365K * 1.05 from my paragon trait = 383.5K.

Actual minimum normal hit ingame:
https://gyazo.com/72b2f88dd76b8f4665594bdfcc9c4002 452.6K. 

Lone wolf fits perfectly: 383.5K * 1.18 = 452.6K. 

You may want to check other classes for similiar interactions if they happen to have them.

**Comment by Collisionc** [comment]
Yeah, blizzard changed this for a lot of specs a month ago or so, Arm's Seasoned Soldier used to be physical only.
