### ISSUE TITLE
Windwalker Monk Artifact Paragon Bug

### ISSUE THREAD

**Issue by Baggotry** [simulationcraft/simc#3237]
When I simmed my character before getting my 35 trait, I was at 412k. Now with no gear changes and a 35th trait, I am simming at 407k. No settings were changed between simming.
[addon import.txt](https://github.com/simulationcraft/simc/files/643981/addon.import.txt)

attached is the addon import text.

**Comment by Hinalover** [comment]
Which version of SimC are you using? I know I recently put in the paragon bonus. I'm just not sure off-hand when the last official release happened (whether it was released before or after my implement) I would suggest testing again using the nightly build.
http://downloads.simulationcraft.org/?C=M;O=D

I just ran your import using my local build which has the change already and to compare I took out the extra point into Paragon. It appears to be working fine.

https://i.gyazo.com/9da57d0c37b15c510a54b622675d1c51.png
