### ISSUE TITLE
Vanish Not Restoring Energy Via Master Of Shadows (SOLVED)

### ISSUE THREAD

**Issue by Maive23** [simulationcraft/simc#3242]
Title.

**Comment by Maive23** [comment]
I have solved the problem.  To fix, type the following into the "Simulate" tab in SimC:

override.spell_data=effect.271221.misc_value1=3
override.spell_data=effect.271221.base_value=30

These spell overrides will make Vanish restore 30 energy

**Comment by aethys256** [comment]
Should be fixed in https://github.com/simulationcraft/simc/commit/39dd761c96024a3add53fe65afee3f52caec6928

**Comment by Maive23** [comment]
Where do I put that code?

**Comment by mrdmnd** [comment]
Good find, Maive23.
