### ISSUE TITLE
[Assa Rogue] Rupture damage way too high for PTR version

### ISSUE THREAD

**Issue by Fjellryn** [simulationcraft/simc#3244]
(With 14/12 nightly build)

Using the default Rogue Assassination T19M NH profile, Rupture has a DPET of roughly 19M for PTR version, while in live version it is roughly 3M.

IIRC there was a similar issue with Subtletly's Eviscerate, something to do with spell rank?

**Comment by aethys256** [comment]
Yes it is a known issue, it's because they changed some spell data.
Thanks for the reminder !
