### ISSUE TITLE
[Frost Mage] Aran's Relaxing Ruby procs more in Sims than on a dummy

### ISSUE THREAD

**Issue by Tryxtira** [simulationcraft/simc#3245]
Hey, 

So, in a five-minute sim with no buffs, flasks, pots, heroism and also 0 % vary length the trinket procs 18 times. In about 20 five-minute-sessions it has only once proced more than ten times. I am very close to the simmed numbers, within 5-10% so my rotation is solid live. 

I can't think of any reason why there could be this big difference should be there. My own personal findings on dummy are also consistent with the 1.8 RPPM that I've read about. 

Here's the Simcraft:
http://imgur.com/a/VgsmF

Here's the dummylogs:
http://imgur.com/a/I3UTm

Thanks!

**Comment by vituscze** [comment]
SimC treats it as 1.75+haste RPPM. It looks like it's just 1.8 RPPM in game, with no haste scaling.

**Comment by Frostedmages** [comment]
I've known about this for a few weeks now - unfortunately I haven't been lucky enough to get the trinket and so have been outsourcing my data collecting to try and figure out where the discrepancy is coming from. Frost mage + haste logs are some of the last ones I'm waiting on to receive.

**Comment by Frostedmages** [comment]
https://www.altered-time.com/forum/viewtopic.php?f=2&t=3416

Collected data. Frost base RPPM is ~30% too high in SimC. Adjusted down in: 0fb579ef866abc72947d3552c9371e4f7e2145df

I'm going to leave this open for now, consider this a first pass at finer tuning the rate.

**Comment by Collisionc** [comment]
Closing as blizzard fixed a bug with rppm in 7.1.5 that led to this issue. The rppm has already been fixed in simc.
