### ISSUE TITLE
Marksmanship - Bursting Shot Legendary

### ISSUE THREAD

**Issue by Violentnacho** [simulationcraft/simc#3248]
Hey guys,
So, I have quite a few legendries on my Hunter now and I want to accurately sim them.  The issue is Simcraft does not take into consideration the Marksman bracers, Magnetized Blasting Cap Launcher, and it’s 800% damage increase.  So far I have figured out how to add Bursting Shot into my rotation and I have learned how to use the Spell Query to edit a spell (I made the spell 800% above it’s base).  That said every time I copy and paste the output from the Spell Query and hit sim… it errors out and sends me to the error log.  I’ve looked at multiple websites, and I just can’t figure it out.  Is there some sort of symbol or string I need before or after?  How do you guys do this (or a different way to tackle the issue)??

Thanks,

Violent.

**Comment by nuoHep** [comment]
Why do you try to modify the spell data? The wrists are working as intended (at least since 24046fe0) as far as I can tell (simming 2 hunters with `actions=bursting_shot`)

**Comment by Violentnacho** [comment]
Thanks for the reply, however, I literally only know how to do basic sim craft stuff... like scaling and simulating... what do I do with the information on that page you linked?

**Comment by nuoHep** [comment]
Nothing, it was simply a reference to the commit that added Bursting Shot & the mm leg wrists.
You didn't answer the question though. Why do you want to modify the spell data?

**Comment by Violentnacho** [comment]
I wanted to modify the spell data because it didn't appear to be working (maybe an old copy, i updated), so i was going to modify the spell to increase the damage done so it was more accurate.  I now see what I was doing wrong outside of not updating simcraft in a hot minute... thanks for your help
