### ISSUE TITLE
[Paladin] Chain of Thrayn

### ISSUE THREAD

**Issue by BenBurnett** [simulationcraft/simc#3250]
@mserrano 

When simulating a Ret Paladin wearing Chain of Thrayn SimC crashes. Looks like spell.chain_of_thrayn is pulling down "Uther's Guard" on live which only has 1 effect, and calls to effectN(4) cause a crash.

Was fixed locally by wrapping in a PTR check.

**Comment by mserrano** [comment]
Whoops, my bad. Thanks @Frostedmages for fixing this
