### ISSUE TITLE
Simulationcraft crashing whenever I try simulate (Retribution Paladin)

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3251]
Here's my SimC string:

paladin="Maerith"
level=110
race=blood_elf
region=eu
server=defias_brotherhood
role=attack
professions=herbalism=800/mining=800
talents=1112212
spec=retribution
artifact=2:0:0:0:0:40:1:41:3:42:3:43:3:44:3:47:3:49:1:50:3:51:3:52:3:53:3:54:1:351:1:352:1:353:1:1275:1

head=,id=134512,bonus_id=3413/41/1502/1813
neck=,id=134529,enchant_id=5439,bonus_id=3412/1808/1502/1813,gem_id=130220
shoulder=,id=142128,enchant_id=5442,bonus_id=1808/3453/1472,gem_id=130219
back=,id=137020,enchant_id=5434,bonus_id=3459/3458
chest=,id=139224,bonus_id=1805/1507/3337
wrist=,id=139235,bonus_id=1806/1502
hands=,id=139226,enchant_id=5444,bonus_id=1806/1502
waist=,id=142424,bonus_id=3507/1497
legs=,id=142127,bonus_id=3453/1472
feet=,id=132443,bonus_id=1811/3458
finger1=,id=139236,enchant_id=5428,bonus_id=1806/1507/3336
finger2=,id=134490,enchant_id=5428,bonus_id=1727/1512/3337
trinket1=,id=133644,bonus_id=3417/1517/3336
trinket2=,id=139325,bonus_id=1805/1487
main_hand=,id=120978,bonus_id=737,relic_id=3415:1507:1813/3474:1532:3337/3468:1497:3336,gem_id=137346/143701/142519/0

Running SimulationCraft(x64) version 710-3 (latest nightly build)

Starting the simulation results in this crash:
Problemereignisname:	APPCRASH
  Anwendungsname:	SimulationCraft.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5852e390
  Fehlermodulname:	SimulationCraft.exe
  Fehlermodulversion:	0.0.0.0
  Fehlermodulzeitstempel:	5852e390
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	00000000000dddb3
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	66ad
  Zusatzinformation 2:	66ad32b1daffa3ed1f84b43992560148
  Zusatzinformation 3:	d8e3
  Zusatzinformation 4:	d8e33903de4151437ce1206549b8545d

(sorry for german - I'm using a german Win7)

simc_gui.simc file contents:
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
paladin="Maerith"
level=110
race=blood_elf
region=eu
server=defias_brotherhood
role=attack
professions=herbalism=800/mining=800
talents=1112212
spec=retribution
artifact=2:0:0:0:0:40:1:41:3:42:3:43:3:44:3:47:3:49:1:50:3:51:3:52:3:53:3:54:1:351:1:352:1:353:1:1275:1

head=,id=134512,bonus_id=3413/41/1502/1813
neck=,id=134529,enchant_id=5439,bonus_id=3412/1808/1502/1813,gem_id=130220
shoulder=,id=142128,enchant_id=5442,bonus_id=1808/3453/1472,gem_id=130219
back=,id=137020,enchant_id=5434,bonus_id=3459/3458
chest=,id=139224,bonus_id=1805/1507/3337
wrist=,id=139235,bonus_id=1806/1502
hands=,id=139226,enchant_id=5444,bonus_id=1806/1502
waist=,id=142424,bonus_id=3507/1497
legs=,id=142127,bonus_id=3453/1472
feet=,id=132443,bonus_id=1811/3458
finger1=,id=139236,enchant_id=5428,bonus_id=1806/1507/3336
finger2=,id=134490,enchant_id=5428,bonus_id=1727/1512/3337
trinket1=,id=133644,bonus_id=3417/1517/3336
trinket2=,id=139325,bonus_id=1805/1487
main_hand=,id=120978,bonus_id=737,relic_id=3415:1507:1813/3474:1532:3337/3468:1497:3336,gem_id=137346/143701/142519/0

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by Collisionc** [comment]
Looks like this was already fixed in https://github.com/simulationcraft/simc/issues/3250

I'll upload a new nightly shortly (within 30 mintues)
