### ISSUE TITLE
Weight of the Earth APL support + run out/charge action request

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#3252]
The APL doesn't explicitly support Weight of the Earth at the moment. Ideal usage seems to just be using it when the CS debuff is down and WB/CS are both unavailable. Removing the "actions+=/heroic_leap" line from its current place and moving it below the actions lines for CS and WB is working best for me:

```
actions+=/colossus_smash,if=cooldown_react&debuff.colossus_smash.remains<gcd
actions+=/warbreaker,if=debuff.colossus_smash.remains<gcd
actions+=/heroic_leap,if=!equipped.weight_of_the_earth|equipped.weight_of_the_earth&debuff.colossus_smash.down
```

As an aside, would it be possible to get an action similar to heroic_charge that always simulates running out of range and charging back in? I'd like to sim charging in combat, but always save heroic leaps for refreshing CS when using legendary legs, but heroic_charge prioritizes using leap vs running out, so it eats them up.

**Comment by Collisionc** [comment]
I can add a flag to heroic_charge to disable leaping

**Comment by amulder87** [comment]
Awesome, that'd be perfect

**Comment by Collisionc** [comment]
heroic_charge,disable_heroic_leap=1,if=whatever

should work now
