### ISSUE TITLE
Can't complete requested iterations for my Balance Druid. Something's up with Starfall.

### ISSUE THREAD

**Issue by mountainpassing** [simulationcraft/simc#3253]
Getting this error message when I try to simcraft my Balance Druid using the /simc data. I copied and pasted the entire thing out of the results page. At first it would stop after 5 iterations (I have it set to do 10000), now it stops at 1. This same process is working fine for my other characters. Any suggestions?
 
Player Viilea could not find spell data for action starfall_tick
Simulation has been canceled after 1 iterations! (thread=0)                     
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick
Player Viilea could not find spell data for action starfall_tick

**Comment by Collisionc** [comment]
can you copy/paste the contents of your simulation here?

**Comment by Collisionc** [comment]
http://us.battle.net/wow/en/character/lightbringer/Viilea/simple

if this is your armory, it's because starfall's spelldata shows level 76 for some crazy reason.  It's fixed now though.
