### ISSUE TITLE
SimC crashing on finishing simulation

### ISSUE THREAD

**Issue by TreeFrost** [simulationcraft/simc#3255]
When i try to finish the simulation it crashes, or my pc freezes and i have to restart.

**Comment by Ragatokk** [comment]
Can confirm simuclation craft crashing after trying to sim my protection warrior 5 times in a row.
Build: http://downloads.simulationcraft.org/SimcSetup-710-03-Win64.exe
Character:  Loðbrók-Darksorrow (EU)
I used: Scaling STR, Mastery, Haste, Versatility, Crit, 3 targets, latency 50.

**Comment by Collisionc** [comment]
Ah ok, I can reproduce it using Ragtokks character. I'll check it out.

**Comment by TreeFrost** [comment]
my character is Jbwings-Daalaran(US)
Scaling: Agi, Mastery, Haste, Versatility, Crit, 1 target, latency 25

**Comment by Collisionc** [comment]
Try this version: http://downloads.simulationcraft.org/simc-710-03-win64-4238a18.7z 

I know it fixes Ragatokk's problem, not sure about treefrost .

**Comment by TreeFrost** [comment]
I'm using this version.

**Comment by Collisionc** [comment]
The version I linked was uploaded 20~ minutes ago, it may have the same "710-03", but it is different than other 710-03. :)

**Comment by TreeFrost** [comment]
Still doesnt work. Same error

**Comment by Collisionc** [comment]
can you link your dxdiag for me ? 

instructions: https://forums.2k.com/showthread.php?218586-How-to-post-a-quot-DXDiag-quot-DirectX-Diagnostics

just upload the dxdiag.txt file here

**Comment by TreeFrost** [comment]
[DxDiag.txt](https://github.com/simulationcraft/simc/files/659522/DxDiag.txt)

**Comment by Collisionc** [comment]
After looking over your dxdiag @TreeFrost, it's crashing due to ASProxy64.dll, which is part of some VPN software -- Astrill.

https://www.reddit.com/r/GrandTheftAutoV_PC/comments/32vego/potential_fix_for_those_crashing_intermittently/

It has been a huge issue with GTA5, and uninstalling it may fix your issues with simulationcraft. I don't know if this is something that we can workaround in simc. You could try uninstalling/reinstalling, or using some other method to connect to the VPN.

**Comment by Collisionc** [comment]
Another possible workaround is to set 
decorated_tooltips=0

It might be crashing when trying to pull wowhead tooltip pictures, possibly.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/issues/3254

**Comment by TreeFrost** [comment]
How would i change decorated tooltips to 0?

**Comment by Collisionc** [comment]
just add it to your sim, import your character then add 

decorated_tooltips=0

below it.

I'm kind of doubtful it will do anything, this is kind of assuming that your VPN is having issues with mmo-c's mouseover tooltips.

**Comment by TreeFrost** [comment]
oh it worked, thanks for the help

**Comment by Collisionc** [comment]
Good to know, we might disable those by default if it becomes a huge issue.

**Comment by Ragatokk** [comment]
Just want to say thanks for fixing this :)
