### ISSUE TITLE
Simulationcraft as stopped working. Windows is checking for a solution...

### ISSUE THREAD

**Issue by p1xel8ted** [simulationcraft/simc#3256]
When the Sim finishes, get the "... has stopped working." Happens regardless of 32/64 and happens on every 03 build for me (zip or installer)

[DxDiag.txt](https://github.com/simulationcraft/simc/files/659782/DxDiag.txt)

On investigation if I enable generate debug (gory details), it crashes as soon as I hit Simulate. If I disable debug, it runs the sim, then crashes.

**Edit - Can sim other things fine, just not DK. If I import using SimC addon, it crashes. If I import using armory, Sim runs fine, but errors with:

`Player Stiix uses call_action_list with unknown action list core`

#### simc_gui.simc file or contents

```
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=600
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
tmi_boss=TMI_Standard_Boss_T19M
tmi_boss_type=T19M
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=12
process_priority=Low
statistics_level=1
### End GUI options ###
```
#### Reproduction Steps:

All I do is import using the SimC addon (does the same thing if I import from Armory)

```
deathknight="Stiix"
level=110
race=human
region=us
server=khazgoroth
role=tank
professions=blacksmithing=796/jewelcrafting=769
talents=2112232
spec=blood
artifact=15:0:0:0:0:272:3:273:3:274:3:275:3:276:3:277:3:278:3:279:3:280:3:281:1:282:1:283:1:284:1:285:1:286:1:289:1:1331:1

head=,id=139229,bonus_id=1805/1808/1487,gem_id=130220
neck=,id=130244,enchant_id=5889,bonus_id=1762/689/600/670,gem_id=130220
shoulder=,id=139232,enchant_id=5441,bonus_id=1805/1487
back=,id=142540,enchant_id=5434,bonus_id=3468/1502/3336
chest=,id=139224,bonus_id=1805/1502/3337
wrist=,id=132365,bonus_id=1811/3458
hands=,id=139226,bonus_id=1805/1808/1487,gem_id=130246
waist=,id=139095,bonus_id=3416/1532/3336
legs=,id=139230,bonus_id=1805/42/1497/3336
feet=,id=139234,bonus_id=1805/1492/3336
finger1=,id=134533,enchant_id=5424,bonus_id=3414/1517/3336
finger2=,id=141492,enchant_id=5424,bonus_id=1808/3466/1482/3336,gem_id=130220
trinket1=,id=141482,bonus_id=1472
trinket2=,id=139324,bonus_id=1805/1497/3336
main_hand=,id=128402,enchant_id=3368,bonus_id=716,relic_id=1805:1487/1806:1517:3337/1805:1487,gem_id=139260/139251/139255/0

```

**Comment by Collisionc** [comment]
Try this: http://downloads.simulationcraft.org/simc-710-03-win64-e3a173d.7z

**Comment by p1xel8ted** [comment]
Thanks! That fixed the crashes. If I import with armory I still get the

`Player Stiix uses call_action_list with unknown action list core`

If I sim with the SimC wow addon export, all I do is use a potion and auto attack.

**Comment by Collisionc** [comment]
Yeah, I'm looking into it.

**Comment by Collisionc** [comment]
Oh, we have no action list for Blood still. You can either add your own, or wait until someone puts one together for Blood. :)

see https://github.com/simulationcraft/simc/issues/2775

Closing this as the crash is fixed.
