### ISSUE TITLE
Crashing as simulation ends

### ISSUE THREAD

**Issue by Sparrow26** [simulationcraft/simc#3257]
I have tried several other characters, of different classes and with different gear and such, and I still run into the same issue. I have re-installed several times, run as admin, run in compatibility mode and tried almost all versions I could find in posts like this one, still no luck.
DxDiag: https://www.dropbox.com/s/l3d2ju6vxvvabqb/DxDiag.txt?dl=0

#### Simulationcraft Version
710-03
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=1
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=High
statistics_level=1
### Begin simulateText ###
deathknight="Sparcrow"
origin="https://eu.api.battle.net/wow/character/tarren-mill/Sparcrow/advanced"
thumbnail="http://eu.battle.net/static-render/eu/tarren-mill/234/130519530-avatar.jpg"
level=110
race=orc
role=attack
position=back
talents=http://eu.battle.net/wow/en/tool/talent-calculator#dZ!1122210
artifact=12:0:0:0:0:108:3:109:3:110:3:113:3:117:3:119:1:120:1:122:1:123:1:124:1:1090:3:1091:1:1332:1
spec=frost

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,name=countless_armies
actions.precombat+=/food,name=fishbrul_special
actions.precombat+=/augmentation,name=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war

# Executed every time the actor is available.
actions=auto_attack
actions+=/pillar_of_frost
actions+=/mind_freeze
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury,if=!talent.breath_of_sindragosa.enabled|dot.breath_of_sindragosa.ticking
actions+=/berserking,if=buff.pillar_of_frost.up
actions+=/potion,name=old_war
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up
actions+=/obliteration
actions+=/breath_of_sindragosa,if=runic_power>=50
actions+=/run_action_list,name=bos,if=dot.breath_of_sindragosa.ticking
actions+=/call_action_list,name=shatter,if=talent.shattering_strikes.enabled
actions+=/call_action_list,name=generic,if=!talent.shattering_strikes.enabled

actions.bos=howling_blast,target_if=!dot.frost_fever.ticking
actions.bos+=/call_action_list,name=core
actions.bos+=/horn_of_winter
actions.bos+=/empower_rune_weapon,if=runic_power<=70
actions.bos+=/hungering_rune_weapon
actions.bos+=/howling_blast,if=buff.rime.react

actions.core=frost_strike,if=buff.obliteration.up&!buff.killing_machine.react
actions.core+=/remorseless_winter,if=(spell_targets.remorseless_winter>=2|talent.gathering_storm.enabled)&!(talent.frostscythe.enabled&buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/frostscythe,if=(buff.killing_machine.react&spell_targets.frostscythe>=2)
actions.core+=/glacial_advance,if=spell_targets.glacial_advance>=2
actions.core+=/frostscythe,if=spell_targets.frostscythe>=3
actions.core+=/obliterate,if=buff.killing_machine.react
actions.core+=/obliterate
actions.core+=/glacial_advance
actions.core+=/remorseless_winter,if=talent.frozen_pulse.enabled

actions.generic=howling_blast,target_if=!dot.frost_fever.ticking
actions.generic+=/howling_blast,if=buff.rime.react
actions.generic+=/frost_strike,if=runic_power>=80
actions.generic+=/call_action_list,name=core
actions.generic+=/horn_of_winter,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/horn_of_winter,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/frost_strike,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/frost_strike,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/empower_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/hungering_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/hungering_rune_weapon,if=!talent.breath_of_sindragosa.enabled

actions.shatter=frost_strike,if=debuff.razorice.stack=5
actions.shatter+=/howling_blast,target_if=!dot.frost_fever.ticking
actions.shatter+=/howling_blast,if=buff.rime.react
actions.shatter+=/frost_strike,if=runic_power>=80
actions.shatter+=/call_action_list,name=core
actions.shatter+=/horn_of_winter,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/horn_of_winter,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/frost_strike,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/frost_strike,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/empower_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/hungering_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.shatter+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.shatter+=/hungering_rune_weapon,if=!talent.breath_of_sindragosa.enabled

head=venomfanged_barbute,id=139229,bonus_id=1805/1487
neck=blackened_portalstone_necklace,id=139332,bonus_id=1807/1477/3336,enchant=mark_of_the_hidden_satyr
shoulders=midnight_heralds_pauldrons,id=139232,bonus_id=1805/1492/3336
back=cloak_of_unwavering_loyalty,id=134412,bonus_id=3412/42/1527/3337,enchant=150str
chest=greystone_chestpiece,id=139093,bonus_id=3474/1808/1507/1674,gems=100haste
wrists=dragonbone_wristclamps,id=138218,bonus_id=1805/1487
hands=repurposed_golem_grips,id=142125,bonus_id=3453/1482/3336
waist=koltiras_newfound_will,id=132366,bonus_id=1811/3458
legs=keelhauler_legplates,id=134514,bonus_id=1727/42/1497/3336
feet=trampling_warboots,id=139234,bonus_id=1805/1492/3336
finger1=braided_silver_ring,id=134539,bonus_id=1727/1808/1502/3336,gems=100haste,enchant=200crit
finger2=utgarde_royal_signet,id=133637,bonus_id=1727/1497/3336,enchant=200crit
trinket1=memento_of_angerboda,id=133644,bonus_id=3414/1808/1507/1813,gems=200str
trinket2=eye_of_command,id=142167,bonus_id=3453/1477/3336
main_hand=blades_of_the_fallen_prince,id=128292,bonus_id=717,gem_id=133683/137377/139259/0,relic_id=3413:1502:1813/1727:1497:3336/1807:1477:3336/0,enchant=rune_of_razorice
off_hand=blades_of_the_fallen_prince,id=128293,enchant=rune_of_the_fallen_crusader

# Gear Summary
# gear_ilvl=864.38
# gear_strength=15252
# gear_stamina=21575
# gear_crit_rating=5668
# gear_haste_rating=6194
# gear_mastery_rating=3612
# gear_versatility_rating=1729
# gear_speed_rating=894
# gear_armor=4185

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Nothing really, just import the character using the client then try to sim it on Windows 10.

**Comment by Collisionc** [comment]
LavasoftTcpService64.dll is the offender, uninstalling adaware should allow it to run. You could also try disabling the firewall in adaware or adding 

decorated_tooltips=0

to the simulation to see if it works.

**Comment by Collisionc** [comment]
duplicate - https://github.com/simulationcraft/simc/issues/3255
