### ISSUE TITLE
MM Hunter -- Legendary headpiece (910) scores lower than rare (840) 

### ISSUE THREAD

**Issue by Maxhawkgt** [simulationcraft/simc#3259]
Simcraft and pawn interaction have been working fine until I got a new headpiece for my MM hunter. Both have the same secondary stats (haste and mastery) but the rare 840 piece which obviously has lower values is a +187% upgrade per Pawn.

Simcraft version 7.1.0 version 2, Simcraft addon 1.51

My pawn string: ( Pawn: v1: "Myname": Agility=5.86, Ap=5.52, CritRating=5.40, HasteRating=2.72, MasteryRating=4.96, Versatility=4.88, Dps=13.68 )

![mm-headpc](https://cloud.githubusercontent.com/assets/24643626/21300456/24e71370-c572-11e6-8f03-d81af71c49f5.jpg)

**Comment by nuoHep** [comment]
That has nothing to do with simc really and should ideally be taken to Pawn devs as the final score is calculated client-side by the addon (especially considering all the stats are the same between the 2 items in the screenshot).

**Comment by Maxhawkgt** [comment]
That makes perfect sense. It just happened that I started to use simulation craft the same day and I thought it had something to do with the wonky rating.
