### ISSUE TITLE
Simcraft won't let me simulate my resto druid. PLZ help

### ISSUE THREAD

**Issue by thanalos** [simulationcraft/simc#3260]
Hello

Evrytime i want to Simulate the healing for my druid it won't let me. It's strange cause its working for my disco priest and demo lock.

evrytime i try and simulate i get this box and it starts to bugg me very hard.

Morphes is using an unsupported spec.
Druid restoration healing for player Morphes is not currently supported.
No active players in sim!

Is there something i am doing wrong or is this a faulty script from simcraft?
plz help.

![prob](https://cloud.githubusercontent.com/assets/24645947/21303525/33941a38-c5bf-11e6-8bc6-1ef574261433.png)
![prob1](https://cloud.githubusercontent.com/assets/24645947/21303531/3a10c668-c5bf-11e6-87b0-fabffa48f849.png)

**Comment by bitfluxhound** [comment]
Healer specs are not supported.

**Comment by thanalos** [comment]
thats kinda stupid since you could do it back in the day ... ooh well thnx anyway but you could have given people an explanation why instead of just saying "healer specs are not supported." thats just being lazy
