### ISSUE TITLE
[PTR] Item with incorrect stats

### ISSUE THREAD

**Issue by futscdav** [simulationcraft/simc#3263]
See the output html attached, it's the mage tier gloves, wowhead lists the correct stats. This is the only item I've encountered this bug so far, but can't say if there aren't more.

[output.zip](https://github.com/simulationcraft/simc/files/662393/output.zip)

**Comment by Frostedmages** [comment]
@navv1234 any idea?

**Comment by navv1234** [comment]
Yes, some clue. I'll fix it.

EDIT: Fixed in b2a748577 (don't ask).

**Comment by Frostedmages** [comment]
Thanks, closing this then.
