### ISSUE TITLE
Unable to run SimC 32/64

### ISSUE THREAD

**Issue by levinbolt** [simulationcraft/simc#3265]
Hi

I downloaded SimcSetup-710-03-Win64.exe. I ran the setup. I did not change any default folders. On Launch, I got the message about "major GUI changes" and it crashed. Based on your homepage comments, I then downloaded SimcSetup-710-03-Win32.exe. I first uninstalled the 64 bit version, removed all folders and installed the 32 bit version (using default paths). I got the same error and crash. 

No  simc_gui.simc file was found as stated in your bug report instructions. 

What I did find is that the QtWebEngine process is still running well after the crash. 

I am running Win7 Service Pack 1.

I have included the following:

1. Error messages on both 32 and 64 bit
2. DxDiag for both 32 and 64 bit. 
3. Screenshot showing process still running after crash

Can you please help me resolve?

Prasad
[SimC64bit error.txt](https://github.com/simulationcraft/simc/files/663673/SimC64bit.error.txt)
[DxDiag64.txt](https://github.com/simulationcraft/simc/files/663674/DxDiag64.txt)
[DxDiag32.txt](https://github.com/simulationcraft/simc/files/663675/DxDiag32.txt)
![simc leftover process after crash](https://cloud.githubusercontent.com/assets/24674185/21350742/00ddc046-c6df-11e6-9640-f64c34356094.JPG)
[simC32bit error.txt](https://github.com/simulationcraft/simc/files/663676/simC32bit.error.txt)

**Comment by Collisionc** [comment]
Most likely this is a similar issue to - https://github.com/simulationcraft/simc/issues/3177

Try the solution offered at - https://github.com/simulationcraft/simc/issues/3177#issuecomment-263156142

Make sure to end the QtWebEngineProcess.exe processes before reloading simc.
