### ISSUE TITLE
[Frost mage] Frozen Orb/Blizzard cannot overlap

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3270]
Right now in game, multiple instances of Frozen Orb/Blizzard can all deal damage at the same time. In SimC, only one Frozen Orb/Blizzard can deal damage.

For example, casting 2 Frozen Orbs 5 seconds apart produces 40 ticks in game but only 36 in SimC.

**Comment by kenthklui** [comment]
This is related to FO being implemented as a dot_t object. We'll need to somehow allow multiple instances applied at the same time.

**Comment by Frostedmages** [comment]
FO fixed here: 236584c206ff15bfc5a34b3308993258aac156aa

**Comment by Frostedmages** [comment]
Blizzard fixed here: https://github.com/simulationcraft/simc/commit/876a5a69a296077cbd4dffecd2ccf7abd9c2a9d8
