### ISSUE TITLE
KIl'jadens burning wish behaviour

### ISSUE THREAD

**Issue by Dalorian** [simulationcraft/simc#3272]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
[PTR]

Testing the trinket on PTR reveleaved that the damage from the trinket did NOT scale with RoP or AP.

The damage does however scale with PI.

The trinket does not generate a stack of PI nor does it affect the duration.

**Comment by Collisionc** [comment]
Closing as this has been implemented.
