### ISSUE TITLE
[Survival] Lacerate in 7.1.5

### ISSUE THREAD

**Issue by ArctosCethlenn** [simulationcraft/simc#3273]
On live lacerate has a cooldown, so "lacerate,if=dot.lacerate.ticking&dot.lacerate.remains<=3|target.time_to_die>=5" works as intended, but the same line in the 7.1.5 version (which is what shows up on http://www.simulationcraft.org/reports/Raid_T19M.html) leads to spamming lacerate at several points, rather than only using it to refresh the dot.

**Comment by gixxpunk** [comment]
Is this still an issue after latest Survivol updates?

**Comment by Jayezi** [comment]
That one guy's new sv apl fixed this since target.time_to_die>=5 is like always true and lacerate has no cooldown now.
