### ISSUE TITLE
Crashing when run Sim on any version

### ISSUE THREAD

**Issue by SgtMaDMaN** [simulationcraft/simc#3274]
So every time I open Sim and put my profile in weather it is from battle net or SimC in game, when i hit simulate it crashes. Tried older versions and newer versions still same thing. Not sure what to do to fix this 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/667378/DxDiag.txt)

**Comment by Collisionc** [comment]
Can you also copy the sim_gui.simc file or post the character you are trying to simulate?

**Comment by SgtMaDMaN** [comment]
I am trying to sim character Maddlock on Thunderlord server alliance . Had a friend sim him and it worked fine for him

**Comment by Collisionc** [comment]
Does it crash at the start or the end of the simulation?

**Comment by SgtMaDMaN** [comment]
In the middle . It runs for a second then windows message pops up saying it has encountered a problem and needs to shut down the program .

**Comment by Collisionc** [comment]
Can you run your character again for me, and then after it hangs/crashes, go to your simulationcraft folder and copy/paste the contents of the simc_gui.simc file ?

**Comment by SgtMaDMaN** [comment]
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
warlock="Maddlock"
level=110
race=human
region=us
server=thunderlord
role=attack

talents=2211112
spec=affliction
artifact=39:0:0:0:0:916:3:919:3:921:3:923:3:926:1:927:1:928:1:999:1:1353:1

head=,id=141449,bonus_id=3466/1472
neck=,id=142658,bonus_id=3462/1497/3336
shoulder=,id=139247,bonus_id=1826/1457
back=,id=134412,bonus_id=3410/1507/3336
chest=,id=134263,bonus_id=3397/1492/1675
wrist=,id=137314,bonus_id=1727/1492/1813
hands=,id=139125,bonus_id=3395/1497/3337
waist=,id=133613,bonus_id=1727/1492/1813
legs=,id=139126,bonus_id=3396/1492/3339
feet=,id=134417,bonus_id=1726/1487/3336
finger1=,id=134487,bonus_id=1727/1507/3337
finger2=,id=142655,bonus_id=3462/1492/3336
trinket1=,id=135925,bonus_id=3427/607/1467
trinket2=,id=139076,bonus_id=3396/603/1487/1675
main_hand=,id=128942,bonus_id=747,relic_id=1726:1497:3337/0,gem_id=137377/142057/0/0


### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

**Comment by SgtMaDMaN** [comment]
tryed it again and got all the way to sim haste and crashed again

**Comment by SgtMaDMaN** [comment]
Tried again and crashed whole comp . Blue screen

**Comment by Collisionc** [comment]
Sounds like your CPU doesn't have enough voltage. Simc is probably the most cpu/ram intensive thing you can run on your computer, and it has been known to crash systems that were barely stable.

Another possibility is a bad stick of RAM.
