### ISSUE TITLE
dtps on default targets is too low, also a suggestion of a scale factor sheet to add.

### ISSUE THREAD

**Issue by Ragatokk** [simulationcraft/simc#3275]
I would like to _request_ that the base targets do allot more damage such that I could get a somewhat accurate level of my stat weights.

Or alternatively could you create a quick guide on how to make a custom target as I only managed to get errors trying to follow this: https://github.com/simulationcraft/simc/wiki/Enemies

The current damage is just ridiculously low with 4x raid boss doing a combined dps of 120k on my warrior.
(I mean the stronger bosses on +10 tyrannical does 200k dps on me)

I believe this to be a major issue as I think the ignore pain takes a much larger portion of the damage then it should and thus making versatility more important.

I also got a _suggestion_ of adding a scale factor that weights normalized dtps at 2/3 and normalized dps at 1/3.
(ie: mastery -4.89 to str of -3.57 for dtps and 13.76 to 14.25 for dps = (-4.89/-3.57)(2/3)+(13.76/14.25)(1/3) = (1.37)(2/3)+(0.97)(1/3) = 1.24

**Comment by Cremator** [comment]
Try this code for some more damage:
`enemy=fluffy_pillow
actions=auto_attack,damage=1150000,attack_speed=2,aoe_tanks=1
actions+=/spell_dot,damage=711000,tick_time=2,dot_duration=12,cooldown=24,aoe_tanks=1,if=!ticking
actions+=/spell_nuke,damage=1215000,cooldown=24,attack_speed=2,aoe_tanks=1
actions+=/melee_nuke,damage=1360492,cooldown=10,attack_speed=2,aoe_tanks=1`

**Comment by Ragatokk** [comment]
Thanks allot for giving me this, super simple to change values and add enemies once you get it to work :)

**Comment by Collisionc** [comment]
I'll add in some better damage taken values for the tanks.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/5f7ca19dc697452e1af14de63f9782eb6a10995b

I increased damage done by 3-4x.
