### ISSUE TITLE
[Demonology Warlock] Change default potion to Prolonged Power

### ISSUE THREAD

**Issue by Azurrrr** [simulationcraft/simc#3276]
#Can you change default potion to [prolonged power](http://www.wowhead.com/item=142117/potion-of-prolonged-power)? it's always best choise for this spec. 
here:
`
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=prolonged_power
actions.precombat+=/demonic_empowerment
actions.precombat+=/demonbolt,if=talent.demonbolt.enabled
actions.precombat+=/shadow_bolt,if=!talent.demonbolt.enabled`
and here (in rotation):
`
actions+=/potion,name=prolonged_power,if=buff.soul_harvest.remains|target.time_to_die<=45|trinket.proc.any.react
`

[Warlock_Demonology_Prolonged_Power_AOE.txt](https://github.com/simulationcraft/simc/files/668303/Warlock_Demonology_Prolonged_Power.txt)
[Warlock_Demonology_Prolonged_Power_Solo.txt](https://github.com/simulationcraft/simc/files/668302/Warlock_Demonology_Prolonged_Power_Solo.txt)
[Warlock_Demonology_Deadly_Grace_AOE.txt](https://github.com/simulationcraft/simc/files/668304/Warlock_Demonology_Deadly_Grace_AOE.txt)
[Warlock_Demonology_Deadly_Grace_Solo.txt](https://github.com/simulationcraft/simc/files/668305/Warlock_Demonology_Deadly_Grace_Solo.txt)

**Comment by Azurrrr** [comment]
You can check this here (Guarm Mythyc):
https://www.warcraftlogs.com/reports/BTpPZmXkGyC8V2Kx#fight=33&type=auras&source=19
https://www.warcraftlogs.com/reports/qvXrFPYGhcmzC7xQ#fight=4&type=auras&source=25
https://www.warcraftlogs.com/reports/rKDad3cF7RJZAvkP#fight=8&type=auras&source=1

**Comment by Collisionc** [comment]
Yeah, seems to be a 0.5-1% dps increase over the other potion.
