### ISSUE TITLE
[Frost mage] Splitting Ice works incorrectly with Brain Freeze

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3277]
In SimC, Splitting Ice Ice Lance deals full shatter damage to the secondary target whenever the primary target has Winter's Chill debuff from Brain Freeze Flurry. It should deal full shatter damage only to the target with Winter's Chill.

This works correctly when the primary target doesn't have the debuff and the secondary target does.

**Comment by vituscze** [comment]
There are several issues with the current implementation related to this:

- Shatter crit bonus is applied to Blizzard per-wave instead of per-target
- Frozen Orb, Ebonbolt, Ray of Frost, Cone of Cold and Ice Time Nova ignore Shatter completely

**Comment by Frostedmages** [comment]
Fixed: https://github.com/simulationcraft/simc/commit/01daf80da78253cf2a495d903f4448682d27b73c

Thanks!
