### ISSUE TITLE
Clicking on AMR Gear Ranking leads to a 404

### ISSUE THREAD

**Issue by Foxtrot-India-Charlie-Sierra** [simulationcraft/simc#3279]
Please include a brief overview of the issue in the title above, as well as completing the following:
Clicking on the askmrrobot or wowhead link sends me to a 404 page.  (I'm wondering if it's because my realm name has a ' character in it:  Vek'nilash
#### Simulationcraft Version
710-03 but was present in previous version as well
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
Run a sim.  Click the link.  Opens default browser with a 404 on the AMR site.
Latest URL:  http://www.askmrrobot.com/wow/optimize/us/veknilash/Detrel#spec=WarriorArms;weights=Strength:1.00,AttackPower:0.95,CriticalStrike:0.97,Haste:1.41,Mastery:1.28,Versatility:0.98,MainHandDps:3.58
Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Can you give a link to a working URL from a character from Vek'nilash on AMR's website so we can know the correct formatting for it?

**Comment by Collisionc** [comment]
This on AMR's end, they've changed how that part of their site works and I doubt we'll be able to interface with it since they would rather you use their simulator. =\

**Comment by Collisionc** [comment]
I removed the link from the report as it's useless.

**Comment by yellowsix** [comment]
Yeah this is something that Theck added a while back I believe -- since updating for Legion that link format and related behavior isn't supported/relevant on AMR anymore, so it is safe to remove it.
