### ISSUE TITLE
Hidden Satyr no longer dealing damage

### ISSUE THREAD

**Issue by amulder87** [simulationcraft/simc#3282]
Looks like the 7.1.5 spelldata for Mark of the Hidden Satyr no longer has a damage value and deals no damage when it procs in simc now. Assuming it didn't change in 7.1.5, average base damage should still be 50k per proc.

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/264ec13c8ca0c673ed74780d20d0fbf0bdfa3b0d
