### ISSUE TITLE
Draught of Souls Damage 

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3283]
#### Simulationcraft Version

715-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/6W9NGiX8

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Draught of Souls does not model it's damage done correctly, in game the damage scales with Unholy DK Mastery and can do 4m+ damage from one use. In simulations the damage ends up being no higher than roughly 1.6m~ damage from multiple uses. The damage it does is also spread out over 10 seconds rather than 3 seconds.

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/96db1290d4fc3e119d871bb267bf5fbfbd029702
https://github.com/simulationcraft/simc/commit/a938923b0b2e8047794f544601e468608ebf628c
