### ISSUE TITLE
Unholy Death Knight T19 M NH Profile

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3284]
Simulationcraft Version

715-01

simc_gui.simc file or contents

This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/Zsy4RgvJ

Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

The Unholy DK T19 M NH profile has very off stats, such as haste levels that are so low it's stat weight is lower than that of STR. This improves it greatly while still keeping it all level 900 gear from Nighthold. The difference in damage is a good ~13k dps.

**Comment by gixxpunk** [comment]
THX! added https://github.com/simulationcraft/simc/commit/0cc63ecb10a4aed8def7e1dd27468eec34dd31b6
