### ISSUE TITLE
[Retribution Paladin]Liadrin's Fury Unleashed - Not generating HP on Avenging Wrath/Crusade Use

### ISSUE THREAD

**Issue by LordSkeletor** [simulationcraft/simc#3286]
Please include a brief overview of the issue in the title above, as well as completing the following:

Liadrin's Fury Unleashed is not granting 1HP upon activation of Avenging Wrath/Crusade. When using Avenging Wrath/Crusade in-game you are immediately granted 1HP.

#### Simulationcraft Version
710-03
World of Warcraft 7.1.0 Live (wow build level 22995, git build c5141f9)

#### simc_gui.simc file or contents
http://pastebin.com/6PcjCy39

**Comment by mserrano** [comment]
Should be fixed by 92db0ab0a66aac0980fbdd92ca12572568d5b5d9
