### ISSUE TITLE
Warrior t19 set bonus not implemented

### ISSUE THREAD

**Issue by Potaetoe** [simulationcraft/simc#3287]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
715-01
git build 5a5d37e

#### Reproduction Steps:

run an arms warrior profile with the below:
hands=,id=138354,bonus_id=3514
head=,id=138357,bonus_id=3514
shoulder=,id=138363,bonus_id=3514
legs=,id=138360,bonus_id=3514

or

set_bonus=tier19_2pc=1
set_bonus=tier19_4pc=1

If you don't change the gear the dps is both either the same or within the Margin of Error. If you change the gear it only changes based on stats.

**Comment by Collisionc** [comment]
Gotcha, thanks. I'll get it working.

**Comment by Collisionc** [comment]
Should be good to go. Thanks.

**Comment by amulder87** [comment]
Heya, quick heads up, I think the battle_cry_deadly_calm pseduo-buff needs to have its duration pulling from the 2pc too. You updated BC to:
```
.duration( spec.battle_cry -> duration() + sets.set( WARRIOR_ARMS, T19, B2 ) -> effectN( 1 ).time_value() )
```

but BC_DC is still using the 4set bonus:
```
.duration( spec.battle_cry -> duration() + sets.set( WARRIOR_ARMS, T19, B4 ) -> effectN( 1 ).time_value() )
```

**Comment by Collisionc** [comment]
yeah, thanks, missed it
