### ISSUE TITLE
[Balance Druid] Goldrinn's Fury artifact talent damage bonus not working

### ISSUE THREAD

**Issue by jjacko73** [simulationcraft/simc#3288]
It looks like the Balance druid last artefact talent that boosts all damage (called "Goldrinn's fury" and that can receive up to 20 points), has no impact at all on calculated damage/dps.
Putting more points in the talent, whether 1 or 20, has no impact.

Reproductible in all the versions i tested:
710-01, 710-02, 710-03, 715-01-win64-5a5d37e

**Comment by Hyperion244** [comment]
I can confirm that this is still happening as of the most recent nightly build

**Comment by Collisionc** [comment]
I'll get it fixed before we release an official version tonight

**Comment by Collisionc** [comment]
Ok, fixed.
