### ISSUE TITLE
[Frost Death Knight] Profile improvements

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#3289]
There are some minor improvements with the cooldowns of frost death knights.

actions+=/sindragosas_fury,if=buff.pillar_of_frost.up
can be replaced with
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up&(buff.unholy_strength.up|(buff.pillar_of_frost.remains<3&target.time_to_die<60))&debuff.razorice.stack==5&!buff.obliteration.up
Added a razorice 5 stack check, don't use during obliteration buff, and sync with PoF -and- unholy strength enchant proc unless mob is about to die, then just sync with PoF

actions+=/obliteration
can be replaced with
actions+=/obliteration,if=!talent.frozen_pulse.enabled|rune<2
Better synergizes with frozen pulse if taken to keep runes low.

I got a minor performance loss with this line and opted to remove it, got a small performance increase.
actions.generic+=/obliterate,if=equipped.132366&talent.frozen_pulse.enabled
Is this because I have both waist AND wrist legendaries? Will need some feedback on that.

This line may also be influenced by waist legendary. I increased the frost strike to not cap limit from 80 to 95, got a small perf increase. I am a gnome, so higher RP cap applies, hence using the 'deficit' instead Basically reduced deficit from 20 to 10.
actions.generic+=/frost_strike,if=runic_power>=80
change to
actions.generic+=/frost_strike,if=runic_power.deficit<=10
(Should also apply to the shatter sub-APL)

Using rime procs during obliteration is slightly inoptimum. Better off wasting them, unless you are cleaving 2+ targets. May change when tier is added into the mix due to RP gain, but doubt it. Applies to both sub-APLs again.
actions.shatter+=/howling_blast,if=buff.rime.react
to
actions.generic+=/howling_blast,if=buff.rime.react&(buff.obliteration.down|spell_targets.howling_blast>=2)

Small increase to empower/hunger your rune weapon if you have zero runes instead of not checking them (presumable 1 or 0 satisfies the condition). Probably shouldnt change it for breath of sindragosa talent. Change all empower/hungering rune weapon casts to have the addition of rune==0

actions.generic+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled&rune==0

Any reasonable feedback is welcome.

**Comment by gixxpunk** [comment]
> I got a minor performance loss with this line and opted to remove it, got a small performance increase.
actions.generic+=/obliterate,if=equipped.132366&talent.frozen_pulse.enabled
Is this because I have both waist AND wrist legendaries? Will need some feedback on that.

Removing this line results in a 7k dps loss for T10M_NH profile with Koltira's. So imho simply removing it is not a good solution. We need some smarter replacements.

I added everything else. THX!

**Comment by ssateneth** [comment]
Another obliteration tweak.

actions+=/obliteration,if=!talent.frozen_pulse.enabled|(rune<2&runic_power<28)
Netted me another +1k.  Runic power check added Tested 15-35, 28 had the best performance

**Comment by gixxpunk** [comment]
> actions+=/obliteration,if=!talent.frozen_pulse.enabled|(rune<2&runic_power<28)
Netted me another +1k. Runic power check added Tested 15-35, 28 had the best performance

~4k for T19M_NH. Added. THX!

**Comment by gixxpunk** [comment]
> I got a minor performance loss with this line and opted to remove it, got a small performance increase.
actions.generic+=/obliterate,if=equipped.132366&talent.frozen_pulse.enabled
Is this because I have both waist AND wrist legendaries? Will need some feedback on that.

This should also be OK now.
https://github.com/simulationcraft/simc/commit/8b2627d673d4b67b28324df673c9f67b882053c1

**Comment by ssateneth** [comment]
Surely there must be some reason that its a gain to drop rime procs if you can obliterate with tier + waist. Probably some sort of RP or Rune capping. Will need to look into it, maybe some sort of condition like what the obliteration action has.
