### ISSUE TITLE
Crashing at 100%

### ISSUE THREAD

**Issue by PursuingED** [simulationcraft/simc#3293]
vr 710-03

[simcgui.txt](https://github.com/simulationcraft/simc/files/678442/simcgui.txt)
[DxDiag.txt](https://github.com/simulationcraft/simc/files/678443/DxDiag.txt)

Simulate > Runs through Scaling > Gets to "100%" > Crashes

Last time I simmed myself I got crashes, but eventually it would turn over and give me a result (eventually). I have been at it for about 20 times now and the crash happens over and over at 100%.

**Comment by Collisionc** [comment]
Try the newer versions, at the top of this link  - http://downloads.simulationcraft.org/?C=M;O=D

**Comment by PursuingED** [comment]
This did the trick.
