### ISSUE TITLE
Naraxas spiked tonque for melee specs

### ISSUE THREAD

**Issue by ddrak3** [simulationcraft/simc#3299]
Naraxas Spiked Tonque sims the best dps trinket for guardian druids.
testing tells that it is really not good and definitely worse than most other trinkets.

issue is most likely because it calculates the maximum damage the trinket can do (maximum dmg is at 20yards range and more) and not the actual dmg it should do in melee range

for me: 290k at 20 yards, 80k in melee

**Comment by Collisionc** [comment]
Added.
