### ISSUE TITLE
Mark of the Trained Soldier

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3300]
#### Simulationcraft Version

715-01

Very simple in that Mark of the Trained Soldier should be giving +600 mastery now, instead of +300 mastery. Very simple test of use the enchant/take it off and you can see the difference of mastery only going up/down by 300.

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/c1e4f04add6bf9a57e45afee16a2bde60e501640
