### ISSUE TITLE
Incorrect stats on Beast Mastery artifact weapon

### ISSUE THREAD

**Issue by bendakwow** [simulationcraft/simc#3301]
#### Simulationcraft Version

715-01 (all builds)

#### Reproduction Steps:

Run a Beast Mastery sim in the 715-01 version. In the results, go to the Gear section. Notice that Titanstrike has way more crit and mastery than it should have. It inflates BM DPS by about 3-4%. 

Issue is not present in the 710-03 Live version (but is also bugged in the 710-03 PTR)

**Comment by navv1234** [comment]
This is now fixed.
