### ISSUE TITLE
[Unholy Death Knight] T19M Profile

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3302]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

715-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/gXXmYAMH

Default profile was previously using Unholy Frenzy, this switches it to Clawing Shadows instead, slightly increasing damage with appropriate gear.

**Comment by gixxpunk** [comment]
This looks just like a BiS compilation for another talent build...
Doesn't make much sense to implement as it breaks the current exchangeability between T19H_NH and T19M_NH. Also this could be done for pretty much every talent build and then there is the question which one to add to simc... Would be much better to search for APL improvements, as this will help everywhere.

**Comment by gixxpunk** [comment]
Btw. Default profile already uses Clawing Shadows. -> 1230023

**Comment by gixxpunk** [comment]
Haha, T19M not T19M_NH... Coffee first next time!
