### ISSUE TITLE
Elemental Shaman APL change 7.1.5

### ISSUE THREAD

**Issue by Bloodmallet** [simulationcraft/simc#3303]
```# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=whispered_pact
actions.precombat+=/food,name=fishbrul_special
actions.precombat+=/augmentation,type=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=prolonged_power
actions.precombat+=/stormkeeper
actions.precombat+=/totem_mastery

# Executed every time the actor is available.
# Bloodlust casting behavior mirrors the simulator settings for proxy bloodlust. See options 'bloodlust_percent', and 'bloodlust_time'. 
actions=bloodlust,if=target.health.pct<25|time>0.500
# In-combat potion is preferentially linked to Elemental Mastery or Bloodlust, unless combat will end shortly
actions+=/potion,name=prolonged_power,if=cooldown.fire_elemental.remains>280|target.time_to_die<=60
actions+=/totem_mastery,if=buff.resonance_totem.remains<2
actions+=/fire_elemental
actions+=/storm_elemental
actions+=/elemental_mastery
actions+=/blood_fury,if=!talent.ascendance.enabled|buff.ascendance.up|cooldown.ascendance.remains>50
actions+=/berserking,if=!talent.ascendance.enabled|buff.ascendance.up
actions+=/run_action_list,name=aoe,if=active_enemies>3&(spell_targets.chain_lightning>3|spell_targets.lava_beam>3)
actions+=/run_action_list,name=single_asc,if=talent.ascendance.enabled
actions+=/run_action_list,name=single_if,if=talent.icefury.enabled
actions+=/run_action_list,name=single_lr,if=talent.lightning_rod.enabled

# Multi target action priority list
actions.aoe=stormkeeper
actions.aoe+=/ascendance
actions.aoe+=/liquid_magma_totem
actions.aoe+=/flame_shock,if=spell_targets.chain_lightning=4&maelstrom>=20,target_if=refreshable
actions.aoe+=/earthquake
actions.aoe+=/lava_burst,if=buff.lava_surge.up&spell_targets.chain_lightning=4
actions.aoe+=/elemental_blast,if=!talent.lightning_rod.enabled&spell_targets.chain_lightning=4
actions.aoe+=/lava_beam
actions.aoe+=/chain_lightning,target_if=debuff.lightning_rod.down
actions.aoe+=/chain_lightning
actions.aoe+=/lava_burst,moving=1
actions.aoe+=/flame_shock,moving=1,target_if=refreshable





# Single target action priority list for Lightning Rod
actions.single_lr+=/flame_shock,if=!ticking
actions.single_lr+=/earthquake,if=buff.echoes_of_the_great_sundering.up&maelstrom>=86
actions.single_lr+=/earth_shock,if=maelstrom>=92
actions.single_lr+=/stormkeeper
actions.single_lr+=/elemental_blast
actions.single_lr+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_lr+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react&(!(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled)|(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled&cooldown.elemental_blast.remains>2+cast_time))
actions.single_lr+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single_lr+=/earth_shock,if=maelstrom>=86
actions.single_lr+=/totem_mastery,if=buff.resonance_totem.remains<10|(buff.resonance_totem.remains<(buff.ascendance.duration+cooldown.ascendance.remains)&cooldown.ascendance.remains<15)
actions.single_LR+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_lr+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3,target_if=debuff.lightning_rod.down
actions.single_lr+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3
actions.single_lr+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1,target_if=debuff.lightning_rod.down
actions.single_lr+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_lr+=/lightning_bolt,target_if=debuff.lightning_rod.down
actions.single_lr+=/lightning_bolt
actions.single_lr+=/flame_shock,moving=1,target_if=refreshable
actions.single_lr+=/earth_shock,moving=1
actions.single_lr+=/flame_shock,moving=1,if=movement.distance>6





# Single target action priority list for Icefury
actions.single_if+=/flame_shock,if=!ticking
actions.single_if+=/earthquake,if=buff.echoes_of_the_great_sundering.up&maelstrom>=86
actions.single_if+=/earth_shock,if=maelstrom>=92
actions.single_if+=/stormkeeper
actions.single_if+=/elemental_blast
actions.single_if+=/icefury,if=raid_event.movement.in<5|maelstrom<=76
actions.single_if+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_if+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&buff.stormkeeper.up&spell_targets.chain_lightning<3
actions.single_if+=/frost_shock,if=talent.icefury.enabled&buff.icefury.up&((maelstrom>=20&raid_event.movement.in>buff.icefury.remains)|buff.icefury.remains<(1.5*spell_haste*buff.icefury.stack))
actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react&((!talent.echo_of_the_elements.enabled|!talent.elemental_blast.enabled)|talent.echo_of_the_elements.enabled&cooldown.elemental_blast.remains>2+cast_time)
actions.single_if+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single_if+=/frost_shock,moving=1,if=buff.icefury.up
actions.single_if+=/earth_shock,if=maelstrom>=86
actions.single_if+=/totem_mastery,if=buff.resonance_totem.remains<10
actions.single_if+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_if+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3
actions.single_if+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_if+=/lightning_bolt
actions.single_if+=/flame_shock,moving=1,target_if=refreshable
actions.single_if+=/earth_shock,moving=1
actions.single_if+=/flame_shock,moving=1,if=movement.distance>6





# Single target action priority list for Ascendance
actions.single_asc=ascendance,if=dot.flame_shock.remains>buff.ascendance.duration&(time>=60|buff.bloodlust.up)&cooldown.lava_burst.remains>0&!buff.stormkeeper.up
actions.single_asc+=/flame_shock,if=!ticking
actions.single_asc+=/flame_shock,if=maelstrom>=20&remains<=buff.ascendance.duration&cooldown.ascendance.remains+buff.ascendance.duration<=duration
actions.single_asc+=/earthquake,if=buff.echoes_of_the_great_sundering.up&!buff.ascendance.up&maelstrom>=86
actions.single_asc+=/earth_shock,if=maelstrom>=92&!buff.ascendance.up
actions.single_asc+=/stormkeeper
actions.single_asc+=/elemental_blast
actions.single_asc+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_asc+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&buff.stormkeeper.up&spell_targets.chain_lightning<3
actions.single_asc+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)&(!(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled)|(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled&(cooldown.elemental_blast.remains>2+cast_time|cooldown.ascendance.remains<5|buff.ascendance.up)))
actions.single_asc+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single_asc+=/earth_shock,if=maelstrom>=86
actions.single_asc+=/totem_mastery,if=buff.resonance_totem.remains<10|(buff.resonance_totem.remains<(buff.ascendance.duration+cooldown.ascendance.remains)&cooldown.ascendance.remains<15)
actions.single_asc+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_asc+=/lava_beam,if=active_enemies>1&spell_targets.lava_beam>1
actions.single_asc+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3
actions.single_asc+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_asc+=/lightning_bolt
actions.single_asc+=/flame_shock,moving=1,target_if=refreshable
actions.single_asc+=/earth_shock,moving=1
actions.single_asc+=/flame_shock,moving=1,if=movement.distance>6
```

**Comment by alesaint** [comment]
Hi @pkaskaround,

Thx for your job.

I'm trying to launch simc 7.1.5 with your rotation but I lost 5k dps.
I'm trying to understand why and after some tests I added this line:

actions.single+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)

For Ascendance and Icefury and I win more than 10k dps

Let me know why you remove it:

My new rotation here for this 2 specs:


# Single target action priority list for Icefury
actions.single_if+=/flame_shock,if=!ticking
actions.single_if+=/earthquake,if=buff.echoes_of_the_great_sundering.up&maelstrom>=86
actions.single_if+=/earth_shock,if=maelstrom>=92
actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)
actions.single_if+=/stormkeeper
actions.single_if+=/elemental_blast
actions.single_if+=/icefury,if=raid_event.movement.in<5|maelstrom<=76
actions.single_if+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_if+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&buff.stormkeeper.up&spell_targets.chain_lightning<3
actions.single_if+=/frost_shock,if=talent.icefury.enabled&buff.icefury.up&((maelstrom>=20&raid_event.movement.in>buff.icefury.remains)|buff.icefury.remains<(1.5*spell_haste*buff.icefury.stack))
actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react&((!talent.echo_of_the_elements.enabled|!talent.elemental_blast.enabled)|talent.echo_of_the_elements.enabled&cooldown.elemental_blast.remains>2+cast_time)
actions.single_if+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single_if+=/frost_shock,moving=1,if=buff.icefury.up
actions.single_if+=/earth_shock,if=maelstrom>=86
actions.single_if+=/totem_mastery,if=buff.resonance_totem.remains<10
actions.single_if+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_if+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3
actions.single_if+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_if+=/lightning_bolt
actions.single_if+=/flame_shock,moving=1,target_if=refreshable
actions.single_if+=/earth_shock,moving=1
actions.single_if+=/flame_shock,moving=1,if=movement.distance>6

# Single target action priority list for Ascendance
actions.single_asc=ascendance,if=dot.flame_shock.remains>buff.ascendance.duration&(time>=60|buff.bloodlust.up)&cooldown.lava_burst.remains>0&!buff.stormkeeper.up
actions.single_asc+=/flame_shock,if=!ticking
actions.single_asc+=/flame_shock,if=maelstrom>=20&remains<=buff.ascendance.duration&cooldown.ascendance.remains+buff.ascendance.duration<=duration
actions.single_asc+=/earthquake,if=buff.echoes_of_the_great_sundering.up&!buff.ascendance.up&maelstrom>=86
actions.single_asc+=/earth_shock,if=maelstrom>=92&!buff.ascendance.up
actions.single_asc+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)
actions.single_asc+=/stormkeeper
actions.single_asc+=/elemental_blast
actions.single_asc+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_asc+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&buff.stormkeeper.up&spell_targets.chain_lightning<3
actions.single_asc+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)&(!(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled)|(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled&(cooldown.elemental_blast.remains>2+cast_time|cooldown.ascendance.remains<5|buff.ascendance.up)))
actions.single_asc+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable
actions.single_asc+=/earth_shock,if=maelstrom>=86
actions.single_asc+=/totem_mastery,if=buff.resonance_totem.remains<10|(buff.resonance_totem.remains<(buff.ascendance.duration+cooldown.ascendance.remains)&cooldown.ascendance.remains<15)
actions.single_asc+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_asc+=/lava_beam,if=active_enemies>1&spell_targets.lava_beam>1
actions.single_asc+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&spell_targets.chain_lightning<3
actions.single_asc+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_asc+=/lightning_bolt
actions.single_asc+=/flame_shock,moving=1,target_if=refreshable
actions.single_asc+=/earth_shock,moving=1
actions.single_asc+=/flame_shock,moving=1,if=movement.distance>6

**Comment by Bloodmallet** [comment]
I noticed this problem too. Might have to do with a different secondary distribution in early stages of the apl update for 7.1.5
I'm looking into it and will update later.

**Comment by Bloodmallet** [comment]
ok had another look at it (which hasn't ended but wanted to give some insight).

Your LvB lines aren't an increase on my end when i take out obsolete LvB delay i forgot to take out from previous Echo implementation.

Old:
`actions.single_lr+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react&(!(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled)|(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled&cooldown.elemental_blast.remains>2+cast_time))`
new:
`actions.single_lr+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react
`

Old:
`actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react&((!talent.echo_of_the_elements.enabled|!talent.elemental_blast.enabled)|talent.echo_of_the_elements.enabled&cooldown.elemental_blast.remains>2+cast_time)
`
New:
`actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react
`

Old:
`actions.single_asc+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)&(!(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled)|(talent.echo_of_the_elements.enabled&talent.elemental_blast.enabled&(cooldown.elemental_blast.remains>2+cast_time|cooldown.ascendance.remains<5|buff.ascendance.up)))
`
New:
`actions.single_asc+=/lava_burst,if=dot.flame_shock.remains>cast_time&(cooldown_react|buff.ascendance.up)
`

Positioning stays the same.

**Comment by Frostedmages** [comment]
Applied APL and the Lava Burst change mentioned above here:

https://github.com/simulationcraft/simc/commit/dd39a1f90b10268475372e28671fa7e7c091851b

Also regenerated and pushed T19P/H/M variants with the APL changes. T19H/M_NH profiles were missing, so those are not accounted for.

**Comment by alesaint** [comment]
thx @pkaskaround it's better ;)

Just one thing, for ice fury.

I have better results if I move lava burst before lightning_bolt

actions.single_if+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react
actions.single_if+=/lightning_bolt,if=buff.power_of_the_maelstrom.up&buff.stormkeeper.up&spell_targets.chain_lightning<3

instead of after frost_shock

actions.single_if+=/frost_shock,if=buff.icefury.up&((maelstrom>=20&raid_event.movement.in>buff.icefury.remains)|buff.icefury.remains<(1.5*spell_haste*buff.icefury.stack))
actions.single_if+=/lava_burst,if=dot.flame_shock.remains>cast_time&cooldown_react
actions.single_if+=/flame_shock,if=maelstrom>=20&buff.elemental_focus.up,target_if=refreshable

Best regards
