### ISSUE TITLE
[Unholy Death Knight] T19M NH Profile

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3304]
#### Simulationcraft Version

715-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/dq8eTV6A

Slight optimization to the APL, using Mastery food instead of Crit, as well as Prolonged Power instead of Old War in the second potion use.
Adds in Draught of Souls and two other gear changes to account for it.

**Comment by gixxpunk** [comment]
As discussed in Discord. Pushing back for now.

**Comment by gixxpunk** [comment]
Currently not possible to use different pots with automatic profile generation. I added everything else.
https://github.com/simulationcraft/simc/commit/53a84440ebc1edacd9aed5ccc67d0789d498a719
