### ISSUE TITLE
Computer Crashing when I Simulate

### ISSUE THREAD

**Issue by ddoggdall** [simulationcraft/simc#3305]
Please include a brief overview of the issue in the title above, as well as completing the following:
I import my character and hit simulate. Sometimes it freezes my entire computer during the initial sim. Other times it freezes my computer during the scaling potion.

Version 710-03

**Comment by Phizix** [comment]
how many iterations are you running?

**Comment by Collisionc** [comment]
please include the information that the issue asks for:

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.
