### ISSUE TITLE
Incorrect buff stats on Nightmare Egg Shell.

### ISSUE THREAD

**Issue by Traison** [simulationcraft/simc#3306]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
715-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
http://pastebin.com/jmbhAbLc

#### Reproduction Steps:
The Nightmare Egg Shell is showing differently in-game than what is being shown on the program or on WoWHead.

My current NES is 875 Titanforged 9, giving 1557 STR and 384 Haste every 1s for 20s.
On SimC and WoWH, the NES is showing 1557 STR and 584 Haste every 1s for 20s. 
http://www.wowhead.com/item=137312/nightmare-egg-shell&bonus=1527:3410

Since I became aware of this I have been examining every NES I came across; from pugs to guildies and random drops. Each one is far lower than what is shown on SimC and WoWH. I don't know which is wrong but I did try to contact GMs about this and after a long series of messages I got them to say that there was nothing wrong with my NES (meaning I have tried clearing Cache, Interface and WTF folders. Tooltip and buff both say the same info.)

**Comment by navv1234** [comment]
Not sure what you are looking at with the information. If you are looking at the HTML report tooltips you get when you mouse-over a spell, we have little to nothing to do with those. They come from Wowdb.

The amount of stats the buff gives in the actual simulator you can see by opening up the details pane of the buff (click on the Down Draft text). There should be a "stat" and "amount" there, which for an item:

```name=nightmare_egg_shell id=137312 slot=trinket1 quality=epic ilevel=875 type=armor/misc stats={ +1634 StrAgi } effect={ down_draft type=equip source=item driver=214340 trigger=214342 stat=Haste amount=0 duration=20 tick=1 proc_chance=101% rppm=0.7 icd=20 } source=Local proc_spells={ proc=OnEquip/214340 }```

Will give out 403 (403.37 actually) per stack, as seen here:

```
105.726 Shaman_Enhancement_T19P gains down_draft_1 ( value=-0.00 )
105.726 Shaman_Enhancement_T19P gains 403.37 haste_rating (temporary)
```

Is this not the correct amount you gain per stack in game?

**Comment by Traison** [comment]
Yes that is correct, I am getting the wrong values in game.
In game I am getting 384 points of haste on my Down Draft proc, stated correctly in in my stat window, my tool-tip and my buff.

In the buff details of SimC it does indeed say 403 Haste. In the Gear section of SimC, it says 584 if you mouse over the trinket. On WoWHead it says the same of 584 as well.

There are three conflicting sets of data here and I have no clue which one is right.

**Comment by navv1234** [comment]
You are comparing to PTR, right? Simulationcraft 715-01 is for 7.1.5, not 7.1.0. Stats will be changing somewhat in 7.1.5 due to their tweaks to combat ratings and some other stuff.

**Comment by Traison** [comment]
I have tried it with 710-03 and 715-01, both have the same values. Of course when 7.1.5 hits the stats will be changing, but that's not what the problem is now. 

Currently, none of the stats are matching properly for the NES anywhere I go. The game has different values from websites, and again from SimC.

**Comment by navv1234** [comment]
I just made a lvl1 shaman on PTR and linked a 875 ilevel Nightmare Egg Shell to chat. The tooltip is 1634 str/agi and 403 haste every 1sec.

**Comment by Traison** [comment]
Well okay then. I suppose I can't say that's not working. I'll just assume I'm messing something up on my end then. Thanks for your time.
