### ISSUE TITLE
[SV 7.1.5] Guerrilla Tactics not working at all

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3307]
Hello,

i wondered why SV Hunter dps was kinda low in the DPS Chart.
After some testing i found out, that the 50% more Explosive Trap damage isnt calculated if you spec into Guerilla Tactics.
The Damage shown in the Ability Breakdown is exactly the same as if you were specced into another Talent in that row.

**Comment by Collisionc** [comment]
This has been resolved as of the newest nightlies.  Let us know if you have any other problems.

Downloads: http://downloads.simulationcraft.org/?C=M;O=D
