### ISSUE TITLE
Feral Trait - Fangs of the First - not reflected in sim

### ISSUE THREAD

**Issue by Tissueisadruid** [simulationcraft/simc#3314]
**Please include a brief overview of the issue in the title above, as well as completing the following:**
My dps simmed exactly the same from when I had the 34th artifact trait and when I achieved the 35th. Nothing else was changed. I simply simmed before I achieved the 35th trait was achieved and after, showing the same dps. The 35th trait should have increased my damage by 5%. The Fangs of the First trait is shown in my results as being owned, but my simulated dps stayed exactly the same.

#### Simulationcraft Version
710-03

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by matheusmzs** [comment]
Ya =/ I saw this a few days ago... So when i decide to post i saw your post \o Ty! Hope get it fix asap!

**Comment by Twitchys** [comment]
This was addressed 7 days before report filed in commit https://github.com/simulationcraft/simc/commit/ef1bb7d29c15e8a5b6c039cf07abfff4fc0eb3fc.

**Comment by Collisionc** [comment]
Yeah, this should be fixed in nightly downloads. 
http://downloads.simulationcraft.org/?C=M;O=D
