### ISSUE TITLE
Request: Shockadin support (holy paladin DPS)

### ISSUE THREAD

**Issue by MartijnHols** [simulationcraft/simc#3319]
Shockadin is the name for Holy Paladin DPS builds where a holy paladin uses his spells for damaging, most notable Holy Shock. It has been gaining popularity due to some successful Paladins advocating it in the [#holy discord](https://discord.gg/7sD2eWb). The build sacrifices pretty much all healing capabilities for damage and in raids it is mostly done for fun, while in M+ it actually helps beating timers. With this issue I would like to request support for the build, I reckon it should be fairly simple to implement as the rotation isn't that complicated. From looking around in other issues, I don't expect healing support to be coming any time soon so this shouldn't interfere.

### Example log
https://www.warcraftlogs.com/reports/GxvCgAhdajyJZqVf#fight=14&type=damage-done&source=42 (top holy paladin at M Ursoc)

This shows Holy Shock being the main damaging spell. A large part of the damage done with this build is during Avenging Wrath, as this reduces the cooldown of Holy Shock by 50% and increases the critical strike chance by 20%. Crusader Strike reduces the cooldown of HS by 1.5 seconds when combined with the Crusader's Might talent, allowing for more Holy Shocks. Judgment increases the damage done by Holy Shock (and CS to a lesser extent), so this debuff should always be up when possible. The rotation is shown nicely in this timeline:
https://www.warcraftlogs.com/reports/GxvCgAhdajyJZqVf#fight=14&type=casts&source=42&view=timeline

### Why
It's hard to figure out proper stat weights for Shockadin right now. Due to Holy Shock having double the normal critical strike chance and Avenging Wrath giving 20% critical strike chance, one could argue any critical strike chance above the soft cap of 30% (as (30% + 20%)*2 = 100% crit chance) is wasted. However AW has an uptime of 25 seconds per 2 minutes (so 20.8%) so crit would still be really good during its downtime. But at a 80% reduced effectiveness, is it really better than Haste and Versatility? In addition it is quite difficult to figure out which trinkets are strongest; for example is Shock Baton doing nearly 20k DPS better than an Int+Haste with hard to determine DPS increase?

I realize the spec isn't serious enough for progress raiding (it's really fun for farm raids!), but it is seriously used for pushing M+ as it helps killing bosses quicker which helps beating timers.

**Comment by lorddev** [comment]
+1

**Comment by Fintehhe** [comment]
Shockadin support proposed in PR-4128. 
[https://github.com/simulationcraft/simc/pull/4128](url)

**Comment by jameswolfe** [comment]
+1 for shockadin, so few resources out there right now and it's a blast to play, plus you can pull considerable numbers on fights.

**Comment by Fintehhe** [comment]
@jameswolfe shockadin support is merged in main thread. And it’s available in nightly builds. Feel free to test. And if you find any bugs - open new issue and mention me in them - I’ll take a look. 

@MartijnHols please, close this issue since it’s resolved.
