### ISSUE TITLE
[Druid] Feral - Ailuros Pouncer Legendary bug

### ISSUE THREAD

**Issue by Tiswone1994** [simulationcraft/simc#3322]
https://github.com/simulationcraft/simc/issues/3052

This is still not fixed, even someone promised to fix that long time ago.
If u convert the Action list into a script, it still suggesting u using Regrowth 3 times in a row, to consum all stacks, instead of using it ONCE to only consume 1 stacks and keep the other 2 for further actions.

Example

At the moment it is like :

If u do have 3 Stacks (Predator Swiftness) it casts 3x times regrowth, then use the finisher.

But it should be

If u do have 3 Stacks (Predator Swiftness) Cast Regrowth to consume 1 stack, use the 2 stacks bloodtalents, and ONLY THEN use the next Stack (Predator Swiftness)

**Comment by Collisionc** [comment]
Should be resolved now, the original problem was fixed, the action list just wasn't updated to reflect it.
