### ISSUE TITLE
[Assa Rogue] vendetta APL

### ISSUE THREAD

**Issue by omeomorfismo** [simulationcraft/simc#3324]
with 7.1.5 nerf to DS, vigor appear to be the best choice, so the old APL arent optimized.

actions.cds+=/vendetta,if=talent.exsanguinate.enabled&(!artifact.urge_to_kill.enabled|(!talent.vigor.enabled&energy.deficit>=75)|(talent.vigor.enabled&energy.deficit>=125+!equipped.duskwalkers_footpads*5))
actions.cds+=/vendetta,if=!talent.exsanguinate.enabled&(!artifact.urge_to_kill.enabled|(!talent.vigor.enabled&energy.deficit>=88)|(talent.vigor.enabled&energy.deficit>=125+equipped.duskwalkers_footpads*5))

actually these commands appears to be good for AP and EX and the following setup
3MA+boots, 3MA, 0MA+boots

for 0MAand 3 gushing wound the old 

actions.cds+=/vendetta,if=talent.exsanguinate.enabled&cooldown.exsanguinate.remains<5&dot.rupture.ticking

is 1K dps ahead

still dont simmed with the new trinket, but i thought that the differences wont be big

**Comment by aethys256** [comment]
@Hebilicious Pull Requests should have fixed this.

**Comment by aethys256** [comment]
https://github.com/simulationcraft/simc/pull/3471

https://github.com/simulationcraft/simc/pull/3478
