### ISSUE TITLE
SimC Crash Blue Screen Flipping Between Sim Results Tabs

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3326]
#### Simulationcraft Version
710-03

#### If Simulationcraft is crashing, please include your dxdiag file
[DxDiag.txt](https://github.com/simulationcraft/simc/files/689297/DxDiag.txt)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

First simc_gui.simc
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
# Seal of Darkshire Nobility
# Evergreen Vinewrap Drape

rogue="Obsidianlord"
level=110
race=troll
region=us
server=thunderlord
role=attack
professions=alchemy=24/herbalism=278
talents=1213222
spec=outlaw
artifact=44:0:0:0:0:1052:1:1053:1:1054:1:1056:1:1057:1:1059:3:1060:3:1061:3:1062:3:1063:3:1064:3:1065:3:1066:3:1348:1

head=,id=139205,bonus_id=1807/1492/3337
neck=,id=142207,bonus_id=1808/3453/1482/3336,gem_id=130221
shoulder=,id=137510,bonus_id=3416/1512/1813
back=,id=139248,bonus_id=1807/1472
chest=,id=134373,bonus_id=1727/1808/1502/1813,gem_id=130221
wrist=,id=138219,bonus_id=1807/1472
hands=,id=139202,bonus_id=1807/1808/1487/3337,gem_id=130221
waist=,id=139197,bonus_id=1805/1487
legs=,id=142143,bonus_id=1808/3452/1477/3336,gem_id=130221
feet=,id=142956,bonus_id=3491/1681/1808/42/1512/3336,gem_id=130221
finger1=,id=137049,enchant_id=5430,bonus_id=1811/3458,gem_id=130247
finger2=,id=142171,bonus_id=3452/1472
trinket1=,id=137357,bonus_id=3412/1507/3336
trinket2=,id=139325,bonus_id=1807/1472
main_hand=,id=128872,bonus_id=742,relic_id=3452:1482:3336/3473:1507:3336/3474:1512:3336,gem_id=142179/143685/143704/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

Second simc_gui.simc
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
# Seal of Darkshire Nobility
# Evergreen Vinewrap Drape
# Misshapen Abomination Heart

rogue="Obsidianlord"
level=110
race=troll
region=us
server=thunderlord
role=attack
professions=alchemy=24/herbalism=278
talents=1213222
spec=outlaw
artifact=44:0:0:0:0:1052:1:1053:1:1054:1:1056:1:1057:1:1059:3:1060:3:1061:3:1062:3:1063:3:1064:3:1065:3:1066:3:1348:1

head=,id=139205,bonus_id=1807/1492/3337
neck=,id=142207,bonus_id=1808/3453/1482/3336,gem_id=130221
shoulder=,id=137510,bonus_id=3416/1512/1813
back=,id=139248,bonus_id=1807/1472
chest=,id=134373,bonus_id=1727/1808/1502/1813,gem_id=130221
wrist=,id=138219,bonus_id=1807/1472
hands=,id=139202,bonus_id=1807/1808/1487/3337,gem_id=130221
waist=,id=139197,bonus_id=1805/1487
legs=,id=142143,bonus_id=1808/3452/1477/3336,gem_id=130221
feet=,id=142956,bonus_id=3491/1681/1808/42/1512/3336,gem_id=130221
finger1=,id=137049,enchant_id=5430,bonus_id=1811/3458,gem_id=130247
finger2=,id=142171,bonus_id=3452/1472
trinket1=,id=137357,bonus_id=3412/1507/3336
trinket2=,id=139325,bonus_id=1807/1472
main_hand=,id=128872,bonus_id=742,relic_id=1507:1826/3473:1507:3336/3474:1512:3336,gem_id=137302/143685/143704/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:
After running the two simulations, one at a time. Go to the Results tab and click back and forth repeatedly in quick succession between the two Simulate tabs. After several iterations (roughly 5-10 for me) everything becomes non-responsive and I receive the windows blue screen of death. It shows a DPC Watch Dog issue.

**Comment by Zarggg** [comment]
BSoD in Windows is usually related to hardware problems, not software. In particular, the DPC_WATCHDOG_VIOLATION is often related to hard drive controllers.

If you are not familiar on how to use WinDBG to determine the failing driver, instructions are available here: http://www.techrepublic.com/blog/windows-and-office/how-do-i-use-windbg-debugger-to-troubleshoot-a-blue-screen-of-death/

**Comment by Collisionc** [comment]
Yeah, that is most likely related to graphics drivers, as part of your crashlogs include the following:

Fault bucket 0x133_DPC_nvlddmkm!gpuWatchdogCallback, type 0

nvlddmkm is a nvidia file.

Try running this program to completely nuke everything about nvidia/amd from your computer - http://www.guru3d.com/files-details/display-driver-uninstaller-download.html

Sometimes, nvidia/amd will fail to upgrade/delete old files and lead to problems like this. 

If that doesn't work, let me know.
