### ISSUE TITLE
Normalized scale factor values showing 0.00 across the board for Demon Hunter?

### ISSUE THREAD

**Issue by smo84** [simulationcraft/simc#3329]
Simming my characters, demon hunter has no normalized values. Simming my rogue, he does. also had a friend try importing my demon hunter and he has normalized values in results. Mine simply show 0.00 across the board. Enable Scaling is ticked, as well as agility, crit, haste, mastery and vers. 

Smo - Kil'Jaeden is the demon hunter.

#### simc_gui.simc file or contents

****Pasting simc_gui.simc

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
demonhunter="Smo"
origin="https://us.api.battle.net/wow/character/kiljaeden/Smo/advanced"
thumbnail="http://us.battle.net/static-render/us/kiljaeden/92/174754396-avatar.jpg"
level=110
race=blood_elf
role=attack
position=back
professions=alchemy=797/herbalism=800
talents=http://us.battle.net/wow/en/tool/talent-calculator#ga!0122000
talent_override=fel_barrage,if=active_enemies>1|raid_event.adds.exists
talent_override=momentum,if=active_enemies>1|raid_event.adds.exists
artifact=3:0:0:0:0:1000:3:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:7
spec=havoc

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/augmentation,type=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war
actions.precombat+=/metamorphosis,if=!(talent.demon_reborn.enabled&talent.demonic.enabled)

# Executed every time the actor is available.
actions=auto_attack
# "Getting ready to use meta" conditions, this is used in a few places.
actions+=/variable,name=pooling_for_meta,value=cooldown.metamorphosis.ready&(!talent.demonic.enabled|!cooldown.eye_beam.ready)&(!talent.chaos_blades.enabled|cooldown.chaos_blades.ready)&(!talent.nemesis.enabled|debuff.nemesis.up|cooldown.nemesis.ready)
# Blade Dance conditions. Always if First Blood is talented, otherwise 5+ targets with Chaos Cleave or 3+ targets without.
actions+=/variable,name=blade_dance,value=talent.first_blood.enabled|spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2)
# Blade Dance pooling condition, so we don't spend too much fury when we need it soon. No need to pool on
# single target since First Blood already makes it cheap enough and delaying it a tiny bit isn't a big deal.
actions+=/variable,name=pooling_for_blade_dance,value=variable.blade_dance&fury-40<35-talent.first_blood.enabled*20&(spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2))
# Chaos Strike pooling condition, so we don't spend too much fury when we need it for Chaos Cleave AoE
actions+=/variable,name=pooling_for_chaos_strike,value=talent.chaos_cleave.enabled&fury.deficit>40&!raid_event.adds.up&raid_event.adds.in<2*gcd
actions+=/blur,if=artifact.demon_speed.enabled&cooldown.fel_rush.charges_fractional<0.5&cooldown.vengeful_retreat.remains-buff.momentum.remains>4
actions+=/call_action_list,name=cooldown
# Fel Rush in at the start of combat.
actions+=/fel_rush,animation_cancel=1,if=time=0
actions+=/pick_up_fragment,if=talent.demonic_appetite.enabled&fury.deficit>=35
actions+=/consume_magic
# Vengeful Retreat backwards through the target to minimize downtime.
actions+=/vengeful_retreat,if=(talent.prepared.enabled|talent.momentum.enabled)&buff.prepared.down&buff.momentum.down
# Fel Rush for Momentum and for fury from Fel Mastery.
actions+=/fel_rush,if=(talent.momentum.enabled|talent.fel_mastery.enabled)&(!talent.momentum.enabled|(charges=2|cooldown.vengeful_retreat.remains>4)&buff.momentum.down)&(!talent.fel_mastery.enabled|fury.deficit>=25)&(charges=2|(raid_event.movement.in>10&raid_event.adds.in>10))
# Use Fel Barrage at max charges, saving it for Momentum and adds if possible.
actions+=/fel_barrage,if=charges>=5&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
actions+=/throw_glaive,if=talent.bloodlet.enabled&(!talent.momentum.enabled|buff.momentum.up)&charges=2
actions+=/fel_eruption
actions+=/fury_of_the_illidari,if=(active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>55&(!talent.momentum.enabled|buff.momentum.up)
actions+=/eye_beam,if=talent.demonic.enabled&(talent.demon_blades.enabled|talent.blind_fury.enabled|(!talent.blind_fury.enabled&fury.deficit<30))&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
actions+=/death_sweep,if=variable.blade_dance
actions+=/blade_dance,if=variable.blade_dance
actions+=/throw_glaive,if=talent.bloodlet.enabled&spell_targets>=2&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&(spell_targets>=3|raid_event.adds.in>recharge_time+cooldown)
actions+=/felblade,if=fury.deficit>=30+buff.prepared.up*8
actions+=/eye_beam,if=talent.blind_fury.enabled&(spell_targets.eye_beam_tick>desired_targets|fury.deficit>=35)
actions+=/annihilation,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8|buff.metamorphosis.remains<5)&!variable.pooling_for_blade_dance
actions+=/throw_glaive,if=talent.bloodlet.enabled&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&raid_event.adds.in>recharge_time+cooldown
actions+=/eye_beam,if=!talent.demonic.enabled&!talent.blind_fury.enabled&((spell_targets.eye_beam_tick>desired_targets&active_enemies>1)|(raid_event.adds.in>45&!variable.pooling_for_meta&buff.metamorphosis.down&(artifact.anguish_of_the_deceiver.enabled|active_enemies>1)&!talent.chaos_cleave.enabled))
# If Demonic is talented, pool fury as Eye Beam is coming off cooldown.
actions+=/demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<gcd&fury.deficit>=20
actions+=/demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<2*gcd&fury.deficit>=45
actions+=/throw_glaive,if=buff.metamorphosis.down&spell_targets>=2
actions+=/chaos_strike,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8)&!variable.pooling_for_chaos_strike&!variable.pooling_for_meta&!variable.pooling_for_blade_dance&(!talent.demonic.enabled|!cooldown.eye_beam.ready|(talent.blind_fury.enabled&fury.deficit<35))
# Use Fel Barrage if its nearing max charges, saving it for Momentum and adds if possible.
actions+=/fel_barrage,if=charges=4&buff.metamorphosis.down&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
actions+=/fel_rush,if=!talent.momentum.enabled&raid_event.movement.in>charges*10
actions+=/demons_bite
actions+=/throw_glaive,if=buff.out_of_range.up
actions+=/felblade,if=movement.distance|buff.out_of_range.up
actions+=/fel_rush,if=movement.distance>15|(buff.out_of_range.up&!talent.momentum.enabled)
actions+=/vengeful_retreat,if=movement.distance>15
actions+=/throw_glaive,if=!talent.bloodlet.enabled

actions.cooldown=nemesis,target_if=min:target.time_to_die,if=raid_event.adds.exists&debuff.nemesis.down&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>60)
actions.cooldown+=/nemesis,if=!raid_event.adds.exists&(cooldown.metamorphosis.remains>100|target.time_to_die<70)
actions.cooldown+=/nemesis,sync=metamorphosis,if=!raid_event.adds.exists
actions.cooldown+=/chaos_blades,if=buff.metamorphosis.up|cooldown.metamorphosis.remains>100|target.time_to_die<20
actions.cooldown+=/metamorphosis,if=variable.pooling_for_meta&fury.deficit<30
actions.cooldown+=/potion,name=old_war,if=buff.metamorphosis.remains>25|target.time_to_die<30

head=raddons_cascading_eyes,id=137061,bonus_id=1811/3458
neck=pendant_of_liquid_horror,id=141696,bonus_id=1805/1808/1492/3336,gems=150crit,enchant=mark_of_the_hidden_satyr
shoulders=epaulets_of_dessicated_foliage,id=134452,bonus_id=3417/1808/1527/3337,gems=150crit
back=cloak_of_unwavering_loyalty,id=134412,bonus_id=3414/1527/3337,enchant=200agi
chest=vest_of_rupturing_diamonds,id=137336,bonus_id=3417/1808/1512/1813,gems=150vers
shirt=precious_ribbon,id=52019
wrists=swordsingers_wristguards,id=134280,bonus_id=3510/1552/3337
hands=felbat_leather_gloves,id=134371,bonus_id=3418/40/1542/3337
waist=biornskin_belt,id=134199,bonus_id=3414/1808/1517/1813,gems=150crit
legs=fevermelt_legguards,id=134460,bonus_id=3510/1537/3337
feet=rivermane_sandals,id=139105,bonus_id=3509/1808/43/1547/3337,gems=150crit
finger1=sephuzs_secret,id=132452,bonus_id=1811,gems=200agi,enchant=200crit
finger2=grubby_silver_ring,id=139236,bonus_id=1805/1808/1492/3336,gems=150crit,enchant=200crit
trinket1=eye_of_guarm,id=142506,bonus_id=3468/1808/605/1492,gems=150mastery
trinket2=bloodthirsty_instinct,id=139329,bonus_id=1805/1808/1487,gems=150crit
main_hand=twinblades_of_the_deceiver,id=127829,bonus_id=719,gem_id=143525/143531/143525/0,relic_id=3454:1472/3454:1472/3454:1472/0
off_hand=twinblades_of_the_deceiver,id=127830

# Gear Summary
# gear_ilvl=881.94
# gear_agility=18402
# gear_stamina=27100
# gear_crit_rating=12087
# gear_haste_rating=4573
# gear_mastery_rating=3298
# gear_versatility_rating=3085
# gear_avoidance_rating=493
# gear_armor=2232

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by Collisionc** [comment]
Thanks for reporting, will be fixed in the next release.
