### ISSUE TITLE
[Neck Enchant] Mark of the Distant Army does not work.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3334]
The Mark of the Distant Army does no damage in the latest nightly.

https://puu.sh/tfhZE/ac6128130d.png

**Comment by Collisionc** [comment]
Does it seem to do the same damage as  before? Blizzard kind of ripped out the spelldata from it for some reason.

**Comment by YepItsEuko** [comment]
I was about to post this same thing. There were no changes to it in the patch notes so hopefully no changes to it in live. Back when this was in PTR people claimed no changes to it either.

**Comment by Collisionc** [comment]
Ok, just set it to the previous values.
