### ISSUE TITLE
Simulationcraft stops running after 1 Iteration

### ISSUE THREAD

**Issue by setjd** [simulationcraft/simc#3340]
Hi, I try to use Simcraft on a Win 8.1 PC. I imported the Character Data and just pressed Simulate. Literally did nothing else. Still Windows tells me the Program doesn't react after i started the Simulation. I checked the report file and there is some record for the first iteration. Also when I run the character setup on another PC it works just fine. So I assume the problem has something to do with the pc but I dont know how to figure out, what it is

#### Simulationcraft Version 710-03-Webengine

DxDiag is attatched

GUI is here: 

### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=0
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
hunter="Ofêlia"
origin="https://eu.api.battle.net/wow/character/thrall/Ofêlia/advanced"
thumbnail="http://eu.battle.net/static-render/eu/thrall/59/127006523-avatar.jpg"
level=110
race=blood_elf
role=attack
position=ranged_back
professions=skinning=800/leatherworking=745
talents=http://eu.battle.net/wow/en/tool/talent-calculator#YZ!0012210
artifact=55:0:0:0:0:307:1:308:1:309:1:310:1:311:1:312:3:313:3:314:3:315:3:316:3:317:3:318:3:319:3:320:1:321:1:322:1:1337:1
spec=marksmanship

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=prolonged_power,if=active_enemies>2
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/windburst

# Executed every time the actor is available.
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30&(!talent.sidewinders.enabled|cooldown.sidewinders.charges<2)
actions+=/blood_fury
actions+=/berserking
actions+=/volley,toggle=on
actions+=/auto_shot
actions+=/variable,name=safe_to_build,value=debuff.hunters_mark.down|(buff.trueshot.down&buff.marking_targets.down)
actions+=/variable,name=use_multishot,value=((buff.marking_targets.up|buff.trueshot.up)&spell_targets.multishot>1)|(buff.marking_targets.down&buff.trueshot.down&spell_targets.multishot>2)
actions+=/call_action_list,name=open,if=active_enemies=1&time<=15
actions+=/a_murder_of_crows,if=(target.time_to_die>=cooldown+duration|target.health.pct<20)&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=60&focus+(focus.regen*debuff.hunters_mark.remains)>=60))
actions+=/call_action_list,name=cooldowns
actions+=/call_action_list,name=trueshotaoe,if=(target.time_to_die>=cooldown+duration|target.health.pct<20)&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=60&focus+(focus.regen*debuff.hunters_mark.remains)>=60))
actions+=/black_arrow,if=debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=70&focus+(focus.regen*debuff.hunters_mark.remains)>=70)
actions+=/barrage,if=(target.time_to_20pct>10|target.health.pct<=20|spell_targets>1)&((buff.trueshot.down|(target.health.pct<=20&buff.bullseye.stack<29)|spell_targets>1)&debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=90&focus+(focus.regen*debuff.hunters_mark.remains)>=90))
actions+=/call_action_list,name=targetdie,if=target.time_to_die<6&active_enemies=1
actions+=/call_action_list,name=patient_sniper,if=talent.patient_sniper.enabled
actions+=/call_action_list,name=non_patient_sniper,if=!talent.patient_sniper.enabled

actions.cooldowns=potion,name=prolonged_power,if=spell_targets.multishot>2&((buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<62)
actions.cooldowns+=/potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<31
actions.cooldowns+=/trueshot,if=time<5|buff.bloodlust.react|target.time_to_die>=(cooldown+duration)|buff.bullseye.react>25|target.time_to_die<16

actions.non_patient_sniper=windburst
actions.non_patient_sniper+=/piercing_shot,if=focus>=100
actions.non_patient_sniper+=/sentinel,if=debuff.hunters_mark.down&focus>30&buff.trueshot.down
actions.non_patient_sniper+=/sidewinders,if=debuff.vulnerability.remains<gcd&time>6
actions.non_patient_sniper+=/aimed_shot,if=buff.lock_and_load.up&spell_targets.barrage<3
actions.non_patient_sniper+=/marked_shot
actions.non_patient_sniper+=/explosive_shot
actions.non_patient_sniper+=/sidewinders,if=((buff.marking_targets.up|buff.trueshot.up)&focus.deficit>70)|charges_fractional>=1.9
actions.non_patient_sniper+=/arcane_shot,if=!variable.use_multishot&(buff.marking_targets.up|(talent.steady_focus.enabled&(buff.steady_focus.down|buff.steady_focus.remains<2)))
actions.non_patient_sniper+=/multishot,if=variable.use_multishot&(buff.marking_targets.up|(talent.steady_focus.enabled&(buff.steady_focus.down|buff.steady_focus.remains<2)))
actions.non_patient_sniper+=/aimed_shot,if=!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>3
actions.non_patient_sniper+=/arcane_shot,if=!variable.use_multishot
actions.non_patient_sniper+=/multishot,if=variable.use_multishot

actions.open=a_murder_of_crows
actions.open+=/trueshot
actions.open+=/piercing_shot
actions.open+=/explosive_shot
actions.open+=/barrage,if=!talent.patient_sniper.enabled
actions.open+=/arcane_shot,line_cd=16&!talent.patient_sniper.enabled
actions.open+=/sidewinders,if=(buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&focus<80)
actions.open+=/marked_shot
actions.open+=/barrage,if=buff.bloodlust.up
actions.open+=/aimed_shot,if=(buff.lock_and_load.up&execute_time<debuff.vulnerability.remains)|focus>90&!talent.patient_sniper.enabled&talent.trick_shot.enabled
actions.open+=/aimed_shot,if=buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.open+=/black_arrow
actions.open+=/barrage
actions.open+=/arcane_shot
actions.open+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.open+=/sidewinders
actions.open+=/aimed_shot

actions.patient_sniper=marked_shot,cycle_targets=1,if=(talent.sidewinders.enabled&talent.barrage.enabled&spell_targets>2)|debuff.hunters_mark.remains<2|((debuff.vulnerability.up|talent.sidewinders.enabled)&debuff.vulnerability.remains<gcd)
actions.patient_sniper+=/windburst,if=talent.sidewinders.enabled&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>=50))|buff.trueshot.up
actions.patient_sniper+=/sidewinders,if=buff.trueshot.up&((buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&(focus.deficit>70|spell_targets>1)))
actions.patient_sniper+=/multishot,if=buff.marking_targets.up&debuff.hunters_mark.down&variable.use_multishot&focus.deficit>2*spell_targets+gcd*focus.regen
actions.patient_sniper+=/aimed_shot,if=buff.lock_and_load.up&buff.trueshot.up&debuff.vulnerability.remains>execute_time
actions.patient_sniper+=/marked_shot,if=buff.trueshot.up&!talent.sidewinders.enabled
actions.patient_sniper+=/arcane_shot,if=buff.trueshot.up
actions.patient_sniper+=/aimed_shot,if=debuff.hunters_mark.down&debuff.vulnerability.remains>execute_time
actions.patient_sniper+=/aimed_shot,if=talent.sidewinders.enabled&debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&(buff.lock_and_load.up|(focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*debuff.vulnerability.remains>=80))&(!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>5|focus>120)
actions.patient_sniper+=/aimed_shot,if=!talent.sidewinders.enabled&debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&(buff.lock_and_load.up|(buff.trueshot.up&focus>=80)|(buff.trueshot.down&focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*debuff.vulnerability.remains>=80))&(!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>5|focus>120)
actions.patient_sniper+=/windburst,if=!talent.sidewinders.enabled&focus>80&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>=50))
actions.patient_sniper+=/marked_shot,if=(talent.sidewinders.enabled&spell_targets>1)|focus.deficit<50|buff.trueshot.up|(buff.marking_targets.up&(!talent.sidewinders.enabled|cooldown.sidewinders.charges_fractional>=1.2))
actions.patient_sniper+=/piercing_shot,if=focus>80
actions.patient_sniper+=/sidewinders,if=variable.safe_to_build&((buff.trueshot.up&focus.deficit>70)|charges_fractional>=1.9)
actions.patient_sniper+=/sidewinders,if=(buff.marking_targets.up&debuff.hunters_mark.down&buff.trueshot.down)|(cooldown.sidewinders.charges_fractional>1&target.time_to_die<11)
actions.patient_sniper+=/arcane_shot,if=variable.safe_to_build&!variable.use_multishot&focus.deficit>5+gcd*focus.regen
actions.patient_sniper+=/multishot,if=variable.safe_to_build&variable.use_multishot&focus.deficit>2*spell_targets+gcd*focus.regen
actions.patient_sniper+=/aimed_shot,if=debuff.vulnerability.down&focus>80&cooldown.windburst.remains>focus.time_to_max

actions.targetdie=marked_shot
actions.targetdie+=/windburst
actions.targetdie+=/aimed_shot,if=debuff.vulnerability.remains>execute_time&target.time_to_die>execute_time
actions.targetdie+=/sidewinders
actions.targetdie+=/aimed_shot
actions.targetdie+=/arcane_shot

actions.trueshotaoe=marked_shot
actions.trueshotaoe+=/barrage,if=!talent.patient_sniper.enabled
actions.trueshotaoe+=/piercing_shot
actions.trueshotaoe+=/explosive_shot
actions.trueshotaoe+=/aimed_shot,if=(!talent.patient_sniper.enabled|talent.trick_shot.enabled)&spell_targets.multishot=2&buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.trueshotaoe+=/multishot

head=sea_stalkers_hood,id=134255,bonus_id=3473/1537/3337
neck=strand_of_the_stars,id=137487,bonus_id=3413/1502/1813
shoulders=shoulderguards_of_bane,id=133625,bonus_id=1727/1808/40/1492/1813
back=cape_of_the_duskwatch,id=137483,bonus_id=3414/1808/1507/1813
chest=sea_stalkers_shirt,id=134258,bonus_id=3474/1507/1674
wrists=runebands_of_the_worthy,id=133626,bonus_id=3410/1522/3337
hands=sea_stalkers_gloves,id=134253,bonus_id=3473/1512/3336
waist=laughing_sisters_pouchchain,id=139211,bonus_id=1805/43/1487
legs=felhammered_greaves,id=134483,bonus_id=3416/1522/3336
feet=black_venom_sabatons,id=139219,bonus_id=1805/1487
finger1=sephuzs_secret,id=132452,bonus_id=3459/3458
finger2=woebearers_band,id=133638,bonus_id=3412/1808/1502/1813
trinket1=bloodthirsty_instinct,id=139329,bonus_id=3379/1472/3337
trinket2=naraxas_spiked_tongue,id=137349,bonus_id=1727/1497/3336
main_hand=thasdorah_legacy_of_the_windrunners,id=128826,bonus_id=727,gem_id=137270/137412/137327/0,relic_id=1727:1492:1813/1727:1527:3337/3414:1517:3336/0

# Gear Summary
# gear_ilvl=861.93
# gear_agility=13277
# gear_stamina=22169
# gear_crit_rating=5361
# gear_haste_rating=2495
# gear_mastery_rating=7958
# gear_versatility_rating=2227
# gear_avoidance_rating=404
# gear_armor=2582
summon_pet=cat

### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### Begin final options ###
log=1
scale_only=none
dps_plot_stat=none
### END ###

Thank you Guys in Advance

**Comment by Hyperion244** [comment]
>Begin final options
log=1
scale_only=none
dps_plot_stat=none
End final options

You have logging enabled, which forces iterations to 1.   Go to the Options tab-->Globals---->Generate Debug--->None.  I'm guessing yours is set to "log only" instead of "none".

**Comment by setjd** [comment]
It was set to gory details. Unfortunately the Problem isnt solved :( I have the theory that there is an issue with the html output. Is there a possibility to deactivate the Html output and just get the textfile?

**Comment by Collisionc** [comment]
I think you forgot to attach your dxdiag, try posting it again.

**Comment by Collisionc** [comment]
This may have been a issue that was fixed since you posted this, try the newest download at the top here:
http://downloads.simulationcraft.org/?C=M;O=D

Re-import your character and it should work, at least it does here.
