### ISSUE TITLE
[Rogue - Assasination] APL - Finisher Theorie evaluation

### ISSUE THREAD

**Issue by fuu1** [simulationcraft/simc#3342]
The theorie is that due to the 7.1.5 changes the priority changes so that finishing at 4+ CP with Envenom and maintaining Rupture with 3+/4+ cp's with rupture will increse your dps.

Evaluation shows that maintaining Rupture with 3+ CP's end up in a damage loss however 4+ CP endet up in a relevant win.

Using Evenom at 4+cp's also ended up in slightly higher dps gain.

APL changes:
Evenom:
`actions.finish+=/envenom,if=combo_points>=5|(talent.elaborate_planning.enabled&combo_points>=3+!talent.exsanguinate.enabled&buff.elaborate_planning.remains<0.1)`
to 
`actions.finish+=/envenom,if=combo_points>=4|(talent.elaborate_planning.enabled&combo_points>=3+!talent.exsanguinate.enabled&buff.elaborate_planning.remains<0.1)`

Rupture:
`actions.maintain=rupture,if=(talent.nightstalker.enabled&stealthed.rogue)|(talent.exsanguinate.enabled&((combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1)|(!ticking&(time>10|combo_points>=2+artifact.urge_to_kill.enabled))))`
to
`actions.maintain=rupture,if=(talent.nightstalker.enabled&stealthed.rogue)|(talent.exsanguinate.enabled&((combo_points>=(cp_max_spend-talent.vigor.enabled)&cooldown.exsanguinate.remains<1)|(!ticking&(time>10|combo_points>=2+artifact.urge_to_kill.enabled))))`

edit: updated to be ideal for DS (for rupture)
credits for the theorie go to Lorentz.

**Comment by omeomorfismo** [comment]
im using 4+ for envenom with all permutation of talent but MP-DS where 5+ appear to be better.

meanwhile the conditional with .remains (with EP or surge of toxins) appear to be a considerable dps loss until you exclude the first seconds and when vendetta is up, but it is still behind of about 1k dps
actually the APL is

`(talent.master_poisoner.enabled&combo_points>=4+talent.deeper_stratagem.enabled&(!debuff.surge_of_toxins.up|(debuff.surge_of_toxins.up&time<=10)|(debuff.surge_of_toxins.up&time>10&(debuff.surge_of_toxins.remains<=0.1|debuff.vendetta.up))))|(!talent.master_poisoner.enabled&combo_points>=4&(!talent.elaborate_planning.enabled|(talent.elaborate_planning.enabled&(!buff.elaborate_planning.up|time<=10|(time>10&(buff.elaborate_planning.remains<0.1|debuff.vendetta.up))))))`
