### ISSUE TITLE
Titanstrike secondary stats inflated

### ISSUE THREAD

**Issue by Jayezi** [simulationcraft/simc#3349]
When simming any BM Hunter, importing from armory or using a sample profile etc, Titanstrike's secondary stats look double what they should be. I see the jump in the 2 specific secondary stats happen here dce5e1fd362c871082486548a1c0f8a47602adc3

**Comment by navv1234** [comment]
How are they doubled? The commit you are referring to is probably the first generation of profiles after getting the updated stat budgets for 7.1.5, so lots of stat changes there are expected. If I look at a ilevel 870 Titanstrike, it has the following stats ```stats={ +1641 Agi, +2461 Sta, +751 Crit, +721 Mastery } damage={ 8086 - 12131 }```. Are those not correct then? From a cursory glance, a 873 ilevel Titanstrike in Wowhead's Artifact trait calculator gets similar results.

**Comment by Azortharion** [comment]
An iLvl 874 Titanstrike ingame has 726 Crit and 697 Mastery.

If I plug in relics to get 872 on Wowhead, it has 1078 Crit and 1035 Mastery: https://puu.sh/tht97/ad7730f81f.png

Here are the stat amounts of several different iLvls: https://puu.sh/thta8/c2049258bb.png

**Comment by navv1234** [comment]
Are we talking PTR or live? Stats will change between PTR and Live for the same ilevel.

**Comment by Azortharion** [comment]
It is live. My understanding was that the value of each secondary stat point was changing, not the amount we'd find on weapons themselves. Fwiw, changing to PTR on Wowhead does not change the stats.

710-03 SimCraft gets the "right" numbers for BM (significantly reduced)

For the Marksmanship weapon, a 933 weapon has

710-03: 905 Crit, 869 Mastery
715-01: 950 Crit, 913 Mastery.

**Comment by Azortharion** [comment]
This is an 895 BM weapon on the PTR:

http://puu.sh/thtts/6f537f7836.jpg

It has 825 Crit and 792 Mastery.

This is the weapon in 715-01 Simcraft: https://puu.sh/thtuM/dcea3ea0e4.png

**Comment by navv1234** [comment]
Both change. Blizzard adjusted the rating conversion (how many points of rating it takes to get 1%), but they at the same time also increased the stats allocation budget for ilevels 800+. And thirdly, they adjusted the "combat rating penalty" for ilevels 800+ on jewels.

I would be very interested in seeing how the stats look on PTR, and whether they are wrong still, but I guess that's slightly difficult what with the character copy disabled.

**Comment by Azortharion** [comment]
In case you missed my comment due to github updating, PTR vs SimCraft:

This is an 895 BM weapon on the PTR:

http://puu.sh/thtts/6f537f7836.jpg

It has 825 Crit and 792 Mastery.

This is the weapon in 715-01 Simcraft: https://puu.sh/thtuM/dcea3ea0e4.png

**Comment by navv1234** [comment]
Yeah, it'll be fixed in a bit.

**Comment by Jayezi** [comment]
"The commit you are referring to is probably the first generation of profiles after getting the updated stat budgets for 7.1.5, so lots of stat changes there are expected."

Sorry I should have explained, I expected changes, but specifically the stats on Titanstrike (crit/mastery) seemed excessive there.

edit: accidentally closed
edit: ok actually is fixed after the revert
