### ISSUE TITLE
SimC crashing after every simulation

### ISSUE THREAD

**Issue by Imfiredup** [simulationcraft/simc#3352]
Simcraft worked fine before I updated to the new 7.1.5 download.  Now, whenever I Sim myself it crashes.  How do I fix it?

**Comment by Collisionc** [comment]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by ender444** [comment]
I have the same problem as well. I've had it before with the x64 version, x86 generally works fine. 

I imported; I hit simulate. It crashes after scaling. If I disable scaling, it crashes basically immediately.

[MSInfo.txt](https://github.com/simulationcraft/simc/files/697950/MSInfo.txt)
SIMC: http://pastebin.com/ZJT2xzEF

**Comment by Collisionc** [comment]
@ender444 Simulationcraft is crashing due to LavasoftTcpService64.dll - Which seems to be some sort of malware. 

https://toolslib.net/downloads/viewdownload/1-adwcleaner/ 

Adwcleaner should take care of it, make sure to restart your computer after the program has run. 

@Imfiredup try ADWcleaner as well, just in case.

**Comment by ender444** [comment]
That's Adaware's leftover crap... thought I had scrubbed it. Must have come back. Thanks for the tip!
