### ISSUE TITLE
[Beast Mastery] Crows doing too little damage.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3353]
Relevant commit(#3343) to this: https://github.com/simulationcraft/simc/commit/e5a7cb03ea9af355ee2dd15860a1f03426408cc7

Crows is doing too little damage, setting up a sim and a log on live servers to do basically the same thing with the exact same parameters, ingame AMOC damage looks like this:

https://puu.sh/ti9c7/80714c3d71.png

And this is in SimCraft: https://puu.sh/ti9dG/248356b37b.png

Log in question: https://www.warcraftlogs.com/reports/9jKz8JwXBkdmpy1D/#type=damage-done&source=27

**Comment by nuoHep** [comment]
While the referenced commit got effectively reverted in c90941ed74 it does not add up...
The multiplier is still there in the spell data, and it's still -45 which is computed as /1.45 (don't ask).
If we take simc numbers and multiply them by 1.45 (to get the pre-multiplied number) we get:

**Comment by nuoHep** [comment]
Should be fixed by c90941ed74d
