### ISSUE TITLE
[Beast Mastery] Barrage not getting its 80% spec-specific damage increase.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3354]
In 7.1.5, Barrage is supposed to deal 80% additional damage for Beast Mastery hunters. This is not implemented.

In SimCraft, this is the damage figures: https://puu.sh/ti9IF/9e6f1a93f7.png
In a log, the minimum damage is exactly 80% higher: https://puu.sh/ti9Jy/71558fe574.png

**Comment by nuoHep** [comment]
Should be fixed by c90941ed74d
