### ISSUE TITLE
[7.1.5] Crashing after simulation is DONE

### ISSUE THREAD

**Issue by KarimKarimKarim** [simulationcraft/simc#3358]
I got the latest 7.1.5 latest from http://downloads.simulationcraft.org/?C=M;O=D

I can import the Elemental Shammy I have but when the sim is done Simcraft just str8 up crashes.

Also, it seems to not crash when simulation with 32-bit 7.1.0 Verison ( I have 8.1 64-bit ), with the 64-bit 7.1.0 version not even working. But the 64-bit 7.1.5 works, but crashes after the simulation is done. Though I have no use for the 7.1 one since the talent trees are changed in 7.1.5 on Ele sHammy.

**Comment by KarimKarimKarim** [comment]
Also here is the thingy you need to reproduce.

https://paste.ee/p/fQpqt

**Comment by Collisionc** [comment]
Try adding 

decorated_tooltips=0

to your simulation and see if it crashes at the end 

If that doesn't, upload your dxdiag and I'll take a look at it.

**Comment by KarimKarimKarim** [comment]
At the end of the simulation thingy I just pressed enter for a new paragraph and added decorated_tooltips=0 is that ok ? I did that and it still crashed.

https://paste.ee/p/Ot9eH Here is the dxdiag

**Comment by Collisionc** [comment]
LavasoftTcpService64.dll is the culprit, which is Adaware. 

Uninstall adaware or add an exception for simulationcraft's folder and it should work.

**Comment by KarimKarimKarim** [comment]
Ok, after checking my machine for adware, it deleted that file you showed me and now the 64-bit one works. Wow ure a genius dude.

**Comment by Collisionc** [comment]
You may need to restart the computer after uninstalling adaware. It's definitely the culprit. If the 32 bit version works for you, that's great.

Can you upload another dxdiag after uninstalling adaware and restarting ?

**Comment by KarimKarimKarim** [comment]
Just did. Here you go man.

https://paste.ee/p/15ouz

0 problems after all this. Both 64 and 32 work flawlessly.

Btw. It wasnt an issue with the Adware program itself. It was about literal adware on my computer that needed an ad-ware program to clean it up.

**Comment by Collisionc** [comment]
Ah, glad to hear! Let us know if you have any other problems.

**Comment by KarimKarimKarim** [comment]
For sure man. Thanks a lot for the help, I would've never thought something like a forgotten file from some unwanted program ( you know those "You might be interested in this" programs that you clicked that ONE time 2 years ago ? :D ) that qualified as adware would ve been the issue.
