### ISSUE TITLE
SimC don't show Welcome and Results page

### ISSUE THREAD

**Issue by mopnex161** [simulationcraft/simc#3361]
Hello!
It does not show the Welcome, Result and Help tab, only black screen.
If i start programm with 256 colors then all right.
I think error in QtWebEngineProcess.exe
What to do?
Thank!

**Comment by Collisionc** [comment]
Try number 3 here: https://github.com/simulationcraft/simc/wiki/CommonIssues

It's for crashing, but it could fix your problem as well.
