### ISSUE TITLE
[Unholy Death Knight] Ring of Collapsing Futures

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3362]
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/mH8tBn3e

#### Reproduction Steps:

New lines to further optimize Ring of Collapsing Futures on use effect, overall gain instead of using the actions+=/use_item,slot=finger1 line.

**Comment by Collisionc** [comment]
Ok, added, thanks!
