### ISSUE TITLE
Result Page still showing  "SimulationCraft 710-03 for World of Warcraft 7.1.0 Live"

### ISSUE THREAD

**Issue by Alkahna** [simulationcraft/simc#3363]
The Resultpage still gives me the following output:

"SimulationCraft 710-03
for World of Warcraft 7.1.0 Live (wow build level 22995, git build e9420bc)"

I just downloaded the latest release (SimcSetup-715-01-Win32.exe	2017-01-11 16:43)

Is this a bug or is it not updated to patch 7.1.5 yet?

**Comment by Alkahna** [comment]
just tried the 64bit version and everything ok there, seems to be a problem only in 32bit version

**Comment by Collisionc** [comment]
Make sure you uninstall the old version of simulationcraft, it's probably opening that one.
