### ISSUE TITLE
Druid Crafted Neck - Equip effect not working

### ISSUE THREAD

**Issue by ithakus** [simulationcraft/simc#3365]
Please include a brief overview of the issue in the title above, as well as completing the following:

The Sylvan Maelstrom Amulet (Legion crafted neck for druids), item 130239, has an effect: "Equip: Increases versatility by xxx when outdoors". I am not able to find a way to evidence or test this so suspect that it is not implemented. Could you please check this.

#### Simulationcraft Version
All 7.1.03 and latest dailies

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
I'll try and add it in before we release 7.1.5 officially.

**Comment by Collisionc** [comment]
Ok, added with an option so you can enable/disable being outside.
Outside=0 will deactivate the versatility bonus if the neck is worn.

**Comment by ithakus** [comment]
Thank you - that's great!
