### ISSUE TITLE
Cant simulate my character. not even once.  

### ISSUE THREAD

**Issue by Dexterjones** [simulationcraft/simc#3366]
Please include a brief overview of the issue in the title above, as well as completing the following:

**Simulationcraft Version** 7.1.5 

 **If Simulationcraft is crashing, please include your dxdiag** 

#### simc_gui.simc file or contents
Cant as i  cannot sim 1 character at all. 

#### Reproduction Steps:

Im trying to simulate my character, but it never works. 
it works on other computers not mine  
whenever i sim my character i get Stopped working. after a brief moment 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/700685/DxDiag.txt)

**Comment by Collisionc** [comment]
See the first option here - https://github.com/simulationcraft/simc/wiki/CommonIssues

> If that does not work, there are various forms of malware that have been crashing Simulationcraft because they infected chrome, which is what Simulationcraft's GUI runs on. Try running ADWCleaner, which seems to fix this in a lot of cases - https://toolslib.net/downloads/viewdownload/1-adwcleaner/ - Make sure to restart computer after running this.

Your dxdiag shows LavasoftTcpService64.dll crashing Simulationcraft, and if you lookup that file on google - https://www.google.com/search?q=LavasoftTcpService64.dll&oq=LavasoftTcpService64.dll - there are numerous threads of people trying to remove it as it is a malicious program.

ADWCleaner seems to get rid of it in most cases, so give that a try.

**Comment by Dexterjones** [comment]
Thanks! it worked!

2017-01-12 9:36 GMT+01:00 Alex <notifications@github.com>:

**Comment by Collisionc** [comment]
Glad to hear it!
