### ISSUE TITLE
Player distance broken

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3367]
Spells with travel time impact instantly, it looks like player_t::get_player_distance returns zero even for casters/actors with distance=x.

**Comment by vituscze** [comment]
Profile used:

```
log=1
fixed_time=1
max_time=20
override.bloodlust=0

mage="test"
level=110
race=human
role=spell
position=back
talents=0000000
spec=frost

actions.precombat=snapshot_stats
actions=frostbolt,if=time>=1&time<2

```

Log with 715-01:
```

3.000 test performs frostbolt (1100000)
3.000 test schedules travel (1.071) for frostbolt
3.000 test gains 0.00 (33000.00) mana from mp5_regen (1100000.00/1100000.00)
3.000 test consumes 22000.0 mana for frostbolt (1078000)
3.000 test loses casting
3.000 test gains icicles_1 ( value=-0.00 )
3.000 test gains fingers_of_frost_1 ( value=-0.00 )
4.071 test frostbolt hits Fluffy_Pillow for 14363 frost damage (hit)
4.071 Fluffy_Pillow gains chilled_1 ( value=-0.00 )
```

Log with 1646e8bf1227fe78fc35c75be1aa37fc0100e41b :

```
3.000 test performs frostbolt (1100000)
3.000 test frostbolt hits Fluffy_Pillow for 14363 frost damage (hit)
3.000 Fluffy_Pillow gains chilled_1 ( value=-0.00 )
3.000 test gains 0.00 (33000.00) mana from mp5_regen (1100000.00/1100000.00)
3.000 test consumes 22000.0 mana for frostbolt (1078000)
3.000 test loses casting
3.000 test gains icicles_1 ( value=-0.00 )
```

**Comment by Collisionc** [comment]
Thanks, it's related to a change I put in last night to simplify some code. current.distance doesn't seem to do what I thought it would do.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/3ac91c12fb4ad37a9c5edf4310d5644ef6c71894 for reference

**Comment by Collisionc** [comment]
Just a stopgap until I do some extra stuff, should work fine.

**Comment by staal** [comment]
Tested nightly "fb226b4" which according to https://github.com/simulationcraft/simc/commits/legion-dev should contain this fix.

Don't think this works. Get the same output as above. Also tested Mage_Frost_T19M_NH with the following prepended:

> log=1
> fixed_time=1
> max_time=50

Output is similar, still no travel time:

> 5.669 Mage_Frost_T19M_NH frostbolt hits Fluffy_Pillow for 171738 frost damage (hit)
> 5.669 Mage_Frost_T19M_NH gains 0.00 (2788.50) mana from mp5_regen (1100000.00/1100000.00)
> 5.669 Mage_Frost_T19M_NH consumes 22000.0 mana for frostbolt (1078000)
> 5.669 Mage_Frost_T19M_NH schedules execute for deadly_grace
> 5.669 Mage_Frost_T19M_NH loses casting
> 5.669 Mage_Frost_T19M_NH gains icicles_1 ( value=-0.00 )

**Comment by Collisionc** [comment]
Whoops

https://github.com/simulationcraft/simc/commit/a0a938567f9ce19a8eb95699ef0970d68b01f4da

Was calculating the travel time for frostbolt to go from the target... back to the target.  I'll upload a new version in 10~ minutes or so.
