### ISSUE TITLE
[Destruction warlock] talents not updated to 7.1.5

### ISSUE THREAD

**Issue by qopec** [simulationcraft/simc#3369]
Hello,
after patch 7.1.5 were swapped talents eradiction and cataclysm and mana tap was replaced by emprovered life tap. In Simc I can see old talents atm, so for destros is Simc quite inaccurate.

**Comment by Collisionc** [comment]
If you check the newest betas, they will have the new talents. Top downloads are at top of this link - http://downloads.simulationcraft.org/?C=M;O=D
