### ISSUE TITLE
Mark of the distant army wrong damage

### ISSUE THREAD

**Issue by Bloodmallet** [simulationcraft/simc#3371]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

SimulationCraft 715-01
for World of Warcraft 7.1.5 Live (wow build level 23360)
pulled from github and build on my own

#### Reproduction Steps:
After using the simulationcraft addon to export my char i observered mark of the distant army dealing less than half the damage it's supposed to to.
`artifact=40:0:0:0:0:291:1:292:1:293:1:294:1:295:1:296:1:297:1:298:3:299:3:300:3:301:3:302:3:303:3:304:3:305:3:306:3:1350:1:1387:6

head=,id=139214,bonus_id=1806/1517/3337
neck=,id=139239,enchant_id=5438,bonus_id=1806/1808/1502,gem_id=130222
shoulder=,id=139217,enchant_id=5883,bonus_id=1806/1502
chest=,id=139221,bonus_id=1805/1512/3337
wrist=,id=137325,bonus_id=3418/43/1547/3337
hands=,id=141694,bonus_id=1806/1502
waist=,id=133805,bonus_id=3510/1537/3337
legs=,id=139215,bonus_id=1806/41/1502
feet=,id=139220,bonus_id=1806/1502
finger1=,id=132452,bonus_id=3459/3458,gem_id=130222
finger2=,id=137050,enchant_id=5427,bonus_id=1811,gem_id=130222
trinket1=,id=139321,bonus_id=1806/1517/3337
trinket2=,id=121311,bonus_id=3396/1808/41/603/1512/3337,gem_id=130222
main_hand=,id=128935,bonus_id=744,relic_id=1806:1507:3336/1806:1502/3507:1497,gem_id=139262/139250/142518/0
off_hand=,id=128936,relic_id=0/0,gem_id=0/0/0/0
`
Class elemental shaman

mark of the distant army deals between 23.6k and 29.5k each tick (three ticks, no crits each proc) ingame. simc html shows 11k damage as the average and max damage.

**Comment by Bloodmallet** [comment]
Oh right....the damage of distant army depends on spellpower for elemental (unequiping the weapon reduced the damage to ~13k ticks). But those variing numbers don't let me get an accurate % :(

**Comment by Collisionc** [comment]
I think it's due to the velocity. It's set to 1 yard per second for some reason, which is doing odd things on ranged classes.

**Comment by Collisionc** [comment]
Ok, should be fixed now.
