### ISSUE TITLE
[Frost Mage] Glacial Spike talent selected but results show icicle damage in pie chart

### ISSUE THREAD

**Issue by thepaan** [simulationcraft/simc#3372]
Please include a brief overview of the issue in the title above, as well as completing the following:

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=100000
default_world_lag=0.20
max_time=300
vary_combat_length=0.2
fight_style=HeavyMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
mage="Obelus"
origin="https://us.api.battle.net/wow/character/barthilas/Obelus/advanced"
thumbnail="http://us.battle.net/static-render/us/barthilas/65/172735553-avatar.jpg"
level=110
race=blood_elf
role=spell
position=back
professions=tailoring=800/enchanting=796
talents=http://us.battle.net/wow/en/tool/talent-calculator#eb!2020111
artifact=53:0:0:0:0:783:1:784:3:785:3:786:3:787:1:788:3:789:3:790:3:791:3:792:3:793:1:794:1:795:1:796:1:797:1:798:1:1296:1
spec=frost

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_whispered_pact
actions.precombat+=/food,type=azshari_salad
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/water_elemental
actions.precombat+=/snapshot_stats
actions.precombat+=/mirror_image
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/frostbolt

# Executed every time the actor is available.
actions=counterspell,if=target.debuff.casting.react
actions+=/ice_lance,if=buff.fingers_of_frost.react=0&prev_gcd.1.flurry&spell_haste<0.845
actions+=/time_warp,if=(time=0&buff.bloodlust.down)|(buff.bloodlust.down&equipped.132410&(cooldown.icy_veins.remains<1|target.time_to_die<50))
actions+=/call_action_list,name=cooldowns
actions+=/call_action_list,name=aoe,if=active_enemies>=4
actions+=/call_action_list,name=single

actions.aoe=frostbolt,if=prev_off_gcd.water_jet
actions.aoe+=/blizzard
actions.aoe+=/frozen_orb
actions.aoe+=/comet_storm
actions.aoe+=/ice_nova
actions.aoe+=/water_jet,if=prev_gcd.1.frostbolt&buff.fingers_of_frost.stack<(2+artifact.icy_hand.enabled)&buff.brain_freeze.react=0
actions.aoe+=/flurry,if=(buff.brain_freeze.react|prev_gcd.1.ebonbolt)&buff.fingers_of_frost.react=0
actions.aoe+=/frost_bomb,if=debuff.frost_bomb.remains<action.ice_lance.travel_time&buff.fingers_of_frost.react>0
actions.aoe+=/ice_lance,if=buff.fingers_of_frost.react>0
actions.aoe+=/ebonbolt,if=buff.brain_freeze.react=0
actions.aoe+=/glacial_spike
actions.aoe+=/frostbolt

actions.cooldowns=rune_of_power,if=cooldown.icy_veins.remains<cast_time|charges_fractional>1.9&cooldown.icy_veins.remains>10|buff.icy_veins.up|target.time_to_die.remains+5<charges_fractional*10
actions.cooldowns+=/potion,name=deadly_grace,if=cooldown.icy_veins.remains<1&active_enemies=1
actions.cooldowns+=/potion,name=prolonged_power,if=cooldown.icy_veins.remains<1
actions.cooldowns+=/icy_veins,if=buff.icy_veins.down
actions.cooldowns+=/mirror_image
actions.cooldowns+=/blood_fury
actions.cooldowns+=/berserking
actions.cooldowns+=/arcane_torrent

actions.single=ice_nova,if=debuff.winters_chill.up
actions.single+=/frostbolt,if=prev_off_gcd.water_jet
actions.single+=/water_jet,if=prev_gcd.1.frostbolt&buff.fingers_of_frost.stack<(2+artifact.icy_hand.enabled)&buff.brain_freeze.react=0
actions.single+=/ray_of_frost,if=buff.icy_veins.up|(cooldown.icy_veins.remains>action.ray_of_frost.cooldown&buff.rune_of_power.down)
actions.single+=/flurry,if=(buff.brain_freeze.react|prev_gcd.1.ebonbolt)&buff.fingers_of_frost.react=0
actions.single+=/frost_bomb,if=debuff.frost_bomb.remains<action.ice_lance.travel_time&buff.fingers_of_frost.react>0
actions.single+=/ice_lance,if=buff.fingers_of_frost.react>0&cooldown.icy_veins.remains>10|buff.fingers_of_frost.react>2
actions.single+=/frozen_orb
actions.single+=/ice_nova
actions.single+=/comet_storm
actions.single+=/blizzard,if=talent.arctic_gale.enabled|active_enemies>1|(buff.zannesu_journey.stack=5&buff.zannesu_journey.remains>cast_time)
actions.single+=/ebonbolt,if=buff.brain_freeze.react=0
actions.single+=/glacial_spike
actions.single+=/frostbolt

head=hood_of_darkened_visions,id=139189,bonus_id=1805/1487
neck=hatecoil_commanders_amulet,id=134492,bonus_id=3411/1517/3337,enchant=mark_of_the_hidden_satyr
shoulders=mantle_of_perpetual_bloom,id=139192,bonus_id=1805/1808/1492/3336,gems=150haste
back=stormsky_greatcloak,id=134202,bonus_id=3473/1808/1537/3337,gems=200int,enchant=200int
chest=belovirs_final_stand,id=133977,bonus_id=1811/3458
wrists=magtheridons_banished_bracers,id=138140,bonus_id=3459/3458
hands=gloves_of_arcane_confluence,id=142149,bonus_id=3453/1487/3337
waist=terrorweave_cinch,id=121323,bonus_id=3473/1808/1512/3336,gems=150haste
legs=leggings_of_countless_worlds,id=142151,bonus_id=3453/1492/3337
feet=cozy_dryad_hoofsocks,id=139194,bonus_id=1805/1497/3336
finger1=twicewarped_azsharan_signet,id=139238,bonus_id=1805/1487,enchant=200haste
finger2=ring_of_contempt,id=134490,bonus_id=3416/1522/3336,enchant=200haste
trinket1=devilsaur_shockbaton,id=140030,bonus_id=3474/41/1497/1674
trinket2=unstable_horrorslime,id=138224,bonus_id=1805/1502/3337
main_hand=ebonchill,id=128862,bonus_id=731,gem_id=140080/133768/142185/0,relic_id=3474:1522:3337/3413:1517:3337/3452:1487:3337/0

# Gear Summary
# gear_ilvl=875.20
# gear_stamina=26405
# gear_intellect=26410
# gear_crit_rating=8365
# gear_haste_rating=8573
# gear_mastery_rating=4748
# gear_versatility_rating=768
# gear_leech_rating=432
# gear_armor=1811

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Import character from armory. Edit last digit of talent line to have the GS talent. Click Simulate. Look at damage sources pie chart. Icicles exists.

**Comment by vituscze** [comment]
If you are at 4 Icicles, cast Frostbolt and Ice Nine procs, one of the Icicles gets released, so this is expected.
