### ISSUE TITLE
MAC OS X Version please

### ISSUE THREAD

**Issue by pprocess1** [simulationcraft/simc#3374]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by pprocess1** [comment]
PLease create a new Mac os x version, the other version is waaay ahaead of ours. Thank you!

**Comment by Manzazuu** [comment]
No news about this update yet?

**Comment by Alpheus** [comment]
http://www.filedropper.com/simc-715-01-legion-dev-osx-x86-01-16-e1886b4 This is the latest nightly as of the time of posting.

**Comment by Manzazuu** [comment]
It says this image cannot be recognized (when trying to open the file)

I downloaded it again, same results.

**Comment by navv1234** [comment]
I wrote myself a script to push tip-of-the-tree MacOS builds to downloads.simulationcraft.org now. I'll try to keep those up to date. 715-01 official release is also now available from the website.

**Comment by pprocess1** [comment]
Thank you sooo much!!!

Thank you,
Robert Borchardt

On Jan 18, 2017, at 7:19 AM, PRAISE EARTHQUAKE TOTEM <notifications@github.com<mailto:notifications@github.com>> wrote:


I wrote myself a script to push tip-of-the-tree MacOS builds to downloads.simulationcraft.org<http://downloads.simulationcraft.org> now. I'll try to keep those up to date. 715-01 official release is also now available from the website.

-
