### ISSUE TITLE
cruel_garrote dot debuff should be affected by haste

### ISSUE THREAD

**Issue by Crelam** [simulationcraft/simc#3377]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
 7.1.5 Live (wow build level 23360, git build fb226b4)
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

The cruel_garrote debuff applied by the Kara trinket bloodstained_handkerchief, has the hasted_ticks flag set to FALSE.  In game haste does speed up the dot ticks, so it should be TRUE.

Thanks.

**Comment by Collisionc** [comment]
Got it, thanks.
