### ISSUE TITLE
MM wrong Action Priority List

### ISSUE THREAD

**Issue by jmaster299** [simulationcraft/simc#3378]
710-3 Simulationcraft Version

Incorrect Action Priority List for Marksman Hunters when not using Sidewinders as a talent. Correct priority is 1-2 targets we only cast Arcane Shot, never Multi Shot. Multi Shot is only ever used when there are 3 or more targets. Yet all sims, including Patchwerk with default settings, is prioritizing Multi Shot. About 170+ per sim, with 5-10 Arcane Shots mixed in.

**Comment by Jayezi** [comment]
Whoever copied the list into the code a long time ago had a copy-paste error that gave multishot the wrong priority.
That version is for last patch and useless anyway, don't use it.

**Comment by jmaster299** [comment]
Can not sim with 7.1.5 PTR version either as SimC crashes every time I try. Does this mean the next version, whenever that gets released, will have the correct priority?

Edit:

Just simmed with the 715-01 version from the "nightly builds" that was uploaded earlier today (13 January). The priority list is better, but still wrong. For a Patchwerk single target fight, it still has an average 8 casts of Multi Shot. That should not happen, there is no scenario where Multi Shot will ever be cast during a single target fight. It won't ever be cast if there are fewer than 3 targets.

**Comment by Jayezi** [comment]
Definitely not happening on default 715 profile.

![apl](https://cloud.githubusercontent.com/assets/4423285/21952155/a0562556-d9da-11e6-81ce-9a4f43537889.jpg)

I'm betting the same profile persisted between installs since it's saved in user data, import a new profile.

**Comment by jmaster299** [comment]
Yes, it is. At least for the newest one available for download from what looks like 9am today.
![ms](https://cloud.githubusercontent.com/assets/25113065/21952318/3b7da10c-d9cd-11e6-99e1-2a61c259eabc.png)


And yes I did a fresh import. Again, it's much better, Arcane has priority now, but Multi Shot is still being cast. Not much, but it is being cast.

**Comment by Jayezi** [comment]
Post the profile you're using.

**Comment by jmaster299** [comment]
I've figured out the problem, and yes it's still a problem that should be fixed. It's a difference between using the "Elite" setting vs the "Good" setting. I sim using the "Good" setting because it's a more realistic outcome, usually. 99.9% of players aren't executing their rotation like a computer simulation can.

But there is no reason for the "Good" profile to be casting an incorrect spell several times. Difference between "Good" and "Elite" should come down to timings and APM, with a "Good" player being a few milliseconds slower for each cast, thus reducing their APM slightly, which therefore reduces their DPS slightly.

But there is no reason the "Good" profile should be fat fingering the same wrong multiple times.

**Comment by Collisionc** [comment]
Our player skill settings aren't perfect, we'll look at adding in a way to just simulate slower reactions in the future though.
