### ISSUE TITLE
Frost DK Action Priority list

### ISSUE THREAD

**Issue by Terrivar** [simulationcraft/simc#3382]
i was playing around with the BoS spec a bit and i noticed that it was droping the buff way to early by using frost strike when it was not needed also HRW wasnt getting used at the right time, changing the list so it looks like on the pictures solved the issiue
if somebody could implement that into the simc build it would be great cause it have no idea how to :)

[http://imgur.com/a/Keoqe](url)
[http://imgur.com/a/OdvxQ](url)

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/17284edc6bbbadf52e502fdcdf7352f233dceeb2
