### ISSUE TITLE
Cannot import my character.

### ISSUE THREAD

**Issue by HuckFroppi** [simulationcraft/simc#3383]
Hello,

I cannot import my character from battle.net. I just got the new legendary trinket Kil'jaeden's Burning Wish, and it seems there is a problem with it when I try to import it, this is what is says : 

Profile will be downloaded into a new tab.

Clicking Simulate will create a simc_gui.simc profile for review.

Unable to generate profile from: http://eu.battle.net/wow/en/character/suramar/Huck/advanced

Player Huck_Active could not find spell data for action kiljaedens_burning_wish
Simulation has been canceled during player setup! (thread=0)

That would be very nice if anyone had a solution for this since I no longer can get the stat wheight and I wanted to SimC my character with my other trinkets which I can no longer do. My character is an Enhancement Shaman. 

Thanks in advance for future answers.

**Comment by Collisionc** [comment]
Use the "beta" 715-01 versions listed at the top here - http://downloads.simulationcraft.org/?C=M;O=D

We'll do an official release sometime in the next few days.
