### ISSUE TITLE
[Monk WW] Possible typo in APL

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#3384]
https://github.com/simulationcraft/simc/blob/legion-dev/profiles/Tier19P/Monk_Windwalker_T19P.simc

Line 29 has a condition `cooldowntarget.time_to_die<=25`.
Is this a correct target? If so, who is meant by that target?

`actions+=/call_action_list,name=sef,if=!talent.serenity.enabled&equipped.drinking_horn_cover&((cooldown.fists_of_fury.remains<=1&chi>=3)|buff.storm_earth_and_fire.up|cooldown.storm_earth_and_fire.charges=2|cooldowntarget.time_to_die<=25|cooldown.touch_of_death.remains>=85)`

**Comment by Hinalover** [comment]
This was just a bad copy and paste, I'll get this fixed.

**Comment by Hinalover** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/38d13d8c6a98b60b339b2bdd7c384b6cc977b6a4
