### ISSUE TITLE
Lvl 60 Prot Paladin - Sim cancelled after 1 iteration

### ISSUE THREAD

**Issue by bobkat2000** [simulationcraft/simc#3386]
Last time I ran simulation on this char was on lvl 40 with v710-02 (and it was successful).  Now at lvl 60, I upgraded to 710-03 and tried, but got: 

Player Bobkitty could not find spell data for action blinding_light_effect
Simulation has been canceled after 1 iterations! (thread=0)                

Tried upgrading to 715-01 (latest 64-bit EXE from repository, and yes I'm on Win 10 64-bit OS) and same error.

simc_gui.simc contents (I had clicked "Reset All Settings" before trying again, but still same error):
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
paladin="Bobkitty"
level=60
race=blood_elf
region=us
server=borean_tundra
role=
professions=blacksmithing=300/mining=297
talents=2132000
spec=protection

head=,id=12410
neck=,id=64615
shoulder=,id=63244
back=,id=59433
chest=,id=64616
wrist=,id=12408
hands=,id=64580
waist=,id=12406
legs=,id=29945
feet=,id=12409
finger1=,id=13097
finger2=,id=59436
trinket1=,id=62966
trinket2=,id=62984
main_hand=,id=29913
off_hand=,id=62977

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

Not sure if dxdiag is required in this case?  I can run it and attach file if necessary.

**Comment by Collisionc** [comment]
Ok, should be fixed in future version.
