### ISSUE TITLE
[Blood DK] Simulation canceled

### ISSUE THREAD

**Issue by Roildan** [simulationcraft/simc#3393]
Hi, it's my first time on Simulationcraft so the error probably comes from me ^^'

So i tried to simulate my Blood Dk but the simutation didn't work : 

> Player Roildan uses call_action_list with unknown action list bos
Simulation has been canceled during player setup! (thread=0) 

I also tried to simulate an other Blood DK and the same errors appears. A friend tried with his own Simulationcraft but it's all the same for him.

#### simc_gui.simc file : [simc_gui.txt](https://github.com/simulationcraft/simc/files/706418/simc_gui.txt)

By looking into the simc_gui.simc file i saw : 

`actions+=/call_action_list,name=bos,if=talent.breath_of_sindragosa.enabled&!dot.breath_of_sindragosa.ticking`

I'm guessing this is where the error comes from as they've the same name (call action list named "bos").
I don't really understand why the spell Breath of Sindragosa is mentionned as it's a Frost DK spell.

So this is where i'm stuck...

Thank you for your help,

Roildan

**Comment by Collisionc** [comment]
Unfortunately blood dk just isn't a supported spec at the moment - https://github.com/simulationcraft/simc/issues/2775

The person who used to maintain blood dk is either too busy or doesn't play the game anymore.

**Comment by Roildan** [comment]
Hum, sadness is real :(

Ty for answering !
