### ISSUE TITLE
Cant get a weight for strengh and intellect.

### ISSUE THREAD

**Issue by hitokiri51** [simulationcraft/simc#3395]
Hi

I have tried different versions of simcraft for the past 2 days and I have the following issue: whenever I sim my rogue, using the simcraft addon, I go to options > Plots > anable plots and check agility, mastery, haste, versatility and crit.; and at the end I get the weights for all 5, but when I try this on my warrior or mage, checking strenght or intellect, I only get weights for mastery, haste, vers. and crit. rating.  I see on the simc.gui.simc file that it says agility on the line to scale only, but I have strenght checked.  I have tried closing and opening the program, reinstalling completely but noting seems to fix this.  Not sure if I´m missing a step to get a correct sim.  Please help.

Thanks in advance

715 - 01 Simulationcraft Version

#### simc_gui.simc file or contents
T## Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=0
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
dps_plot_stat=str,crit,haste,mastery,vers
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
statistics_level=1
### Begin simulateText ###
warrior="Desiraez"
level=110
race=undead
region=us
server=malganis
role=
professions=alchemy=800/enchanting=759
talents=2332133
spec=fury
artifact=35:0:0:0:0:980:1:981:1:982:1:984:1:985:1:986:1:987:1:988:3:989:3:990:3:991:3:992:3:993:3:994:3:995:3:996:3:1357:1:1394:1
 
head=,id=139058,bonus_id=3415/1532/3337
neck=,id=137487,enchant_id=5889,bonus_id=3417/1527/3337
shoulder=,id=134521,enchant_id=5882,bonus_id=3509/1808/43/1532/3336,gem_id=130221
back=,id=133639,enchant_id=5434,bonus_id=3417/1808/1527/3337,gem_id=130221
chest=,id=137018,bonus_id=1811
shirt=,id=6125
wrist=,id=133632,bonus_id=3416/1522/3336
hands=,id=134136,bonus_id=3474/1808/1522/3337,gem_id=130246
waist=,id=139227,bonus_id=1805/1487
legs=,id=134359,bonus_id=3416/1552/3337
feet=,id=139234,bonus_id=1805/1487
finger1=,id=142171,enchant_id=5428,bonus_id=1808/3452/1492/3337,gem_id=130221
finger2=,id=134530,enchant_id=5428,bonus_id=3418/1527/3336
trinket1=,id=144259,bonus_id=1811/3458
trinket2=,id=137539,bonus_id=3415/1507/1813
main_hand=,id=128908,bonus_id=751,relic_id=3414:1507:1813/1805:1492:3336/3474:1517:3336,gem_id=137546/137008/143705/0
off_hand=,id=134553,relic_id=0/0,gem_id=0/0/0/0
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
 
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by Collisionc** [comment]
Try the "Reset All Settings" button that is under the Options --> Globals ---> Basic Options area. I can't reproduce this, and that will wipe all configuration settings that are saved even after reinstalling.

**Comment by legarambor** [comment]
hey, I've got this issue too. To fix it i basically had to make my Simcraft window smaller... if i put it on fullscreen the stats would dissapear for some reason... I have no idea what is causing this.  (using a 4k screen)
