### ISSUE TITLE
[SV Hunter] Remove Serpent Sting initial hit

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3397]
there is a bug in the latest build regarding Serpent Sting and a mysterious initial hit on it.
Serpent Sting doesn't have an initial hit.

build 7.1.5 713fb1a

**Comment by Collisionc** [comment]
I didn't have time to test this as I'm heading out to lunch, but I uploaded a new version here -http://downloads.simulationcraft.org/?C=M;O=D

**Comment by Meatwookie** [comment]
just came home and tested it,
it is still in there
build f54a0e9

it looks like it does all the 720% AP damage as Hit + as DoT

**Comment by nuoHep** [comment]
Should be fixed by e71727558b372ccda622f3f9b0ca122e27ea4e9f

**Comment by Collisionc** [comment]
Thanks, didn't think about the weapon.
