### ISSUE TITLE
Compilation broken on Linux

### ISSUE THREAD

**Issue by thalyssra** [simulationcraft/simc#3402]
Commit 713fb1a1df0bce10b69ab6ee7efb144b31cd9a9d introduces some workaround(s) for Windows but doesn't seem to wrap it in anything to detect whether you're compiling on Windows/Linux/OS X, so it always attempts to build qt/sc_Workaround.cpp and fails because of the #include <windows.h> which doesn't exist (at least, on Linux).

**Comment by AdamKnube** [comment]
Confirmed. qt/Workaround.cpp needs some O/S detection.

**Comment by Collisionc** [comment]
I'll add that in, thanks.
