### ISSUE TITLE
[Brewmaster] Issues

### ISSUE THREAD

**Issue by ManagerWoW** [simulationcraft/simc#3403]
Follow up to https://github.com/simulationcraft/simc/commit/69c6a9b80a8c1b66ef536dbdf645242a0c2b8673

1. Blackout Combo still instantly crashes simc
2. Face Palm (artifact trait) is using the proc chance as its damage mod. The damage mod should be 200%
3. Stagger should proc [Choker of Barbed Reins](http://www.wowhead.com/item=142174/choker-of-barbed-reins) (it doesn't in simc)

**Comment by Collisionc** [comment]
Can you give me a profile with the crashing blackout combo? I couldn't get it to crash yesterday, so I just took a guess at something that was wrong.

**Comment by Collisionc** [comment]
Also, how in the heck is the spelldata so wrong for face palm. Does it always deal 200%, regardless of points in the artifact?

**Comment by ManagerWoW** [comment]
http://pastebin.com/8cguVik0

Ironskin Brew is crashing it (it's fine if you completely comment it out. Mainly looking just for damage done from BoC). 

If you really want to implement/fix it: How it works in game is when you Blackout Combo an Ironskin Brew, it gives you a hidden buff that pauses your stagger debuff for 3 seconds. Further damage taken still adds to your stagger DOT, but the duration and ticking damage is completely paused. The buff duration also stacks (not capped to 3s).

**Comment by Collisionc** [comment]
I haven't a clue how to implement that type of monster. I'll comment the line of code that's crashing it, but I just spent 30 minutes trying to delay a dot tick and it wasn't happening.

**Comment by ManagerWoW** [comment]
Just built, and everything looks good. Thank you!

**Comment by ManagerWoW** [comment]
Thank you. Just built and everything looks good.

**Comment by ManagerWoW** [comment]
Exploding Keg is using a 1.5s GCD, instead of 1s

Breath of Fire GCD is using a hasted 1.5s GCD, instead of 1s

Rushing Jade Wind's cooldown/duration/ticks should be hasted

----

http://manager.heroicstrike.org/2017-01-16_02-27-55.png

The Sample Sequence Table is using the timestamp when a spell is queued up, not actually executed. Example in the picture: RJW is casted every 6s, but Simc is showing when it is queued up every 5.8s.

```
5.804 Executing event: Player-Ready
5.804 action_t::cost: rushing_jade_wind base_cost=0.00 secondary_cost=0.00 cost=0.00 resource=chi
5.804 Add Event: core_event_t time=6.0000 rs-time=0.0000 id=114

6.000 Manager schedules execute for rushing_jade_wind_tick
6.000 Add Event: core_event_t time=6.0000 rs-time=0.0000 id=115
6.000 New Action Execute Event: Manager rushing_jade_wind_tick 0.0 (target=Fluffy_Pillow, marker=0)
```

**Comment by Collisionc** [comment]
Ok, test out the ironskin thing, it appears to be working... I hope.
