### ISSUE TITLE
Wowprogress dps rankings to be based on 7.1.5

### ISSUE THREAD

**Issue by Deviannt1** [simulationcraft/simc#3405]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
Yeah we can't do anything about this.
