### ISSUE TITLE
[Rogue] Blade Flurry not triggered by Run Through

### ISSUE THREAD

**Issue by pnmueller** [simulationcraft/simc#3406]
In-game Run Through has 30% of its damage cleaved onto nearby targets when Blade Flurry is active. This is not currently the case in Simulationcraft (pulled five minutes ago).

Looking at the module, the issue appears to be the check for the weapon attribute in the trigger_blade_flurry function which isn't set in run_through_t. This can be fixed by setting said weapon attribute in said method as is done for similar abilities such as Eviscerate.

**Comment by aethys256** [comment]
Thank you, remember you reported it to me on Discord but it was lost somewhere, as you can see it's way better to open an issue since I can keep track 👍
