### ISSUE TITLE
[Balance] Multi-target APL incorrect

### ISSUE THREAD

**Issue by Slippykins** [simulationcraft/simc#3409]
Just a couple of inefficiencies in the APL for Balance Druid AoE. I'll list the fixes to the APL necessary:

Default APL
> /moonfire line needs cycle_targets=1
> /call_action_list,name=ed needs &active_enemies<=2 added to end of if statement

Celestial_Alignment
> /starfall line if statement should be changed to if=(active_enemies>=2&talent.stellar_drift.enabled|active_enemies>=3)

Single_target
> same as above
> /starfall line if statement should be changed to if=(active_enemies>=2&talent.stellar_drift.enabled|active_enemies>=3)

**Comment by Collisionc** [comment]
Got it, thanks
