### ISSUE TITLE
[Trinket] Naraxas' Spiked Tongue - Rancid Maw proc does not appear in damage listing.

### ISSUE THREAD

**Issue by Azortharion** [simulationcraft/simc#3410]
Latest nightly.

If you run a sim on a character using the Naraxas' Spiked Tongue trinket, the damage of the trinket does not appear in the damage listing, but it does appear below, in the simple action stats menu.

https://puu.sh/toh9d/2c26a95f7b.png

**Comment by Collisionc** [comment]
It's probably due to some specs not having their distance set correctly.

**Comment by Collisionc** [comment]
That was annoying to track down, basically there were a lot of specs setting the value of base.distance later than they needed to.
