### ISSUE TITLE
Hunters broken on release simc-715-01-win64-c4f5bf8.7z	2017-01-17 03:56

### ISSUE THREAD

**Issue by ChadGoldstein** [simulationcraft/simc#3414]
Simc is showing that I should be doing nearly 2 million DPS on a patchwerk sim.
#### simc_gui.simc file or contents

DPS Ranking:
1959117 100.0%  Raid
1959117  100.0%  Kazinorian

HPS Ranking:
      0 100.0%  Raid

Player: Kazinorian blood_elf hunter marksmanship 110
  DPS: 1959117.3  DPS-Error=2358.6/0.120%  DPS-Range=423520/21.6%  DPS-Convergence=69.3%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=135643.6  RPS-Out=14.5 RPS-In=14.5  Resource=(focus) Waiting=1.8 ApM=47.6
  Origin: https://us.api.battle.net/wow/character/tichondrius/Kazinorian/advanced
  Talents: http://us.battle.net/wow/en/tool/talent-calculator#YZ!0002022
  Artifact: 55:0:0:0:0:307:1:308:1:309:1:310:1:311:1:312:3:313:3:314:3:315:3:316:3:317:3:318:3:319:3:320:3:321:1:322:1:1337:1:1369:16
  Core Stats:    strength=6228|6228(6228)  agility=32017|30652(29645)  stamina=50553|50553(35601)  intellect=6009|6009(6009)  spirit=2|2(2)  health=3033180|3033180  mana=0|0
  Generic Stats: mastery=27.75%|27.16%(14184)  versatility=2.56%|2.56%(1216)  leech=2.91%|2.91%(669)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=15.00%|15.00%(0)  crit=23.04%|23.04%(4818)  haste=9.71%|9.71%(3640)  speed=9.71%|9.71%  manareg=0|0(0)
  Attack Stats:  power=32017|30652(0)  hit=7.50%|7.50%(0)  crit=23.04%|23.04%(4818)  expertise=7.50%|7.50%(0)  haste=9.71%|9.71%(3640)  speed=9.71%|9.71%
  Defense Stats: armor=2825|2825(2825) miss=3.00%|3.00%  dodge=21.39%|20.65%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=1.28%|1.28%(1216)
  Priorities (actions.precombat):
    flask,type=flask_of_the_seventh_demon/food,type=nightborne_delicacy_platter
    summon_pet/snapshot_stats
    potion,name=prolonged_power,if=spell_targets.multi_shot>2
    potion,name=deadly_grace/augmentation,type=defiled/windburst
  Priorities:
    auto_shot/use_item,name=ring_of_collapsing_futures
    arcane_torrent,if=focus.deficit>=30&(!talent.sidewinders.enabled|cooldown.sidewinders.charges<2)
    berserking,if=buff.trueshot.up/blood_fury,if=buff.trueshot.up/volley,toggle=on
    variable,name=safe_to_build,value=debuff.hunters_mark.down|(buff.trueshot.down&buff.marking_targets.down)
    variable,name=use_multishot,value=((buff.marking_targets.up|buff.trueshot.up)&spell_targets.multi_shot>1)|(buff.marking_targets.down&buff.trueshot.down&spell_targets.multi_shot>2)
    variable,name=pooling_for_piercing,value=talent.piercing_shot.enabled&cooldown.piercing_shot.remains<5&focus<100&!buff.lock_and_load.up
    variable,name=sentinel_soon,value=talent.sentinel.enabled&!cooldown.sentinel.up&((cooldown.sentinel.remains>50&cooldown.sentinel.remains<(50+gcd.max))|(cooldown.sentinel.remains>40&cooldown.sentinel.remains<(40+gcd.max)))
    a_murder_of_crows,if=time=0/call_action_list,name=cooldowns
    call_action_list,name=targetdie,if=target.time_to_die<6&spell_targets.multi_shot=1
    call_action_list,name=patient_sniper,if=talent.patient_sniper.enabled
    call_action_list,name=non_patient_sniper,if=!talent.patient_sniper.enabled
  Priorities (actions.cooldowns):
    potion,name=prolonged_power,if=spell_targets.multi_shot>2&((buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<62)
    potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<31
    variable,name=trueshot_cooldown,op=set,value=time*1.1,if=time>15&cooldown.trueshot.up&variable.trueshot_cooldown=0
    trueshot,if=time<=15|buff.bloodlust.react|(variable.trueshot_cooldown>0&target.time_to_die>(variable.trueshot_cooldown+duration))|buff.bullseye.react>25|target.time_to_die<16
  Priorities (actions.patient_sniper):
    variable,name=vuln_aim_casts,op=set,value=floor(debuff.vulnerability.remains%(2*attack_haste))
    variable,name=vuln_aim_casts,op=set,value=floor((focus.regen*(debuff.vulnerability.remains-(2*attack_haste))+focus)%50),if=variable.vuln_aim_casts>floor((focus.regen*(debuff.vulnerability.remains-(2*attack_haste))+focus)%50)
    variable,name=focus_after_vuln,op=set,value=(focus.regen*debuff.vulnerability.remains)-(variable.vuln_aim_casts*50)
    sidewinders,if=buff.trueshot.up&(debuff.vulnerability.remains<(2*attack_haste)|focus<35)&(spell_targets.sidewinders<2|debuff.hunters_mark.down)
    sidewinders,if=buff.trueshot.down&debuff.vulnerability.remains<(2*attack_haste)&focus<60&(debuff.hunters_mark.down|(charges_fractional>1.3&spell_targets.sidewinders<2))
    windburst,if=debuff.vulnerability.remains<(2*attack_haste)&(talent.sidewinders.enabled|focus>60)&!variable.pooling_for_piercing
    black_arrow
    a_murder_of_crows,if=(target.time_to_die>=cooldown+duration|target.health.pct<20|target.time_to_die<16)&(debuff.vulnerability.remains<1|debuff.vulnerability.remains>(4*attack_haste+gcd))
    barrage,if=spell_targets>1|(target.health.pct<20&buff.bullseye.stack<25)
    piercing_shot,if=debuff.vulnerability.up&debuff.vulnerability.remains<4&focus>80
    marked_shot,if=!talent.sidewinders.enabled&spell_targets.multi_shot>1&(!variable.pooling_for_piercing|debuff.vulnerability.up)
    marked_shot,if=talent.sidewinders.enabled&((debuff.vulnerability.remains<(2*attack_haste)&focus>50)|spell_targets.sidewinders>1)
    marked_shot,if=!talent.sidewinders.enabled&spell_targets.multi_shot<2&debuff.vulnerability.remains<(2*attack_haste)&(debuff.hunters_mark.remains<gcd|focus>90)
    aimed_shot,if=debuff.vulnerability.remains>execute_time&(buff.trueshot.up|buff.lock_and_load.up)&(spell_targets.multi_shot<2|talent.sidewinders.enabled)&!variable.pooling_for_piercing
    aimed_shot,if=talent.sidewinders.enabled&variable.focus_after_vuln>60&!debuff.hunters_mark.up
    aimed_shot,if=debuff.vulnerability.remains>execute_time&debuff.vulnerability.remains-execute_time<1&!variable.pooling_for_piercing
    aimed_shot,if=debuff.vulnerability.remains>(execute_time*2)&(debuff.vulnerability.remains-(execute_time*2))<1&(focus+focus.regen*(debuff.vulnerability.remains-execute_time))>100&!variable.pooling_for_piercing
    aimed_shot,if=cast_regen+focus>focus.max&(debuff.vulnerability.remains>execute_time|cooldown.windburst.remains>3)&!variable.pooling_for_piercing
    arcane_shot,if=buff.trueshot.up&spell_targets.multi_shot<2
    multishot,if=buff.trueshot.up&spell_targets.multi_shot>1
    arcane_shot,if=spell_targets.multi_shot<2&(debuff.vulnerability.remains<(2*attack_haste)|(debuff.vulnerability.remains>(variable.vuln_aim_casts*2*attack_haste+gcd)&(debuff.vulnerability.remains-(variable.vuln_aim_casts*2*attack_haste+gcd))<1))
    multishot,if=spell_targets.multi_shot>1&(debuff.vulnerability.remains<(2*attack_haste)|(debuff.vulnerability.remains>(variable.vuln_aim_casts*2*attack_haste+gcd)&(debuff.vulnerability.remains-(variable.vuln_aim_casts*2*attack_haste+gcd))<1))
  Priorities (actions.targetdie):
    windburst
    aimed_shot,if=debuff.vulnerability.remains>execute_time&target.time_to_die>execute_time
    sidewinders/marked_shot/aimed_shot/arcane_shot
  Actions:
    aimed_shot                 Count= 81.7|  3.68sec  DPE=4193286|52%  DPET=2756998  DPR=109571.7  pDPS=1018121  Miss=0.00%  Hit=2563754|409506|5533521  Crit=6138465|878131|18067170|32.8%
    apply_temptation           Count=  4.7| 16.93sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=      0
    arcane_shot                Count=106.4|  2.79sec  DPE= 553561|10%  DPET= 453331  DPR=     0.0  pDPS= 196010  Miss=0.00%  Hit=425643|115722|854301  Crit=951132|317669|2573115|24.5%
    arcane_torrent             Count=  3.8| 91.07sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=      0
    auto_shot                  Count=124.1|  2.42sec  DPE= 519013| 4%  DPET= 216343  DPR=     0.0  pDPS=  75823  Miss=0.00%  Hit=139774|38564|283804  Crit=316016|104086|846918|24.8%
    call_of_the_hunter         Count= 10.6| 51.52sec  DPE= 475341| 1%  DPET=      0  DPR=     0.0  pDPS=  16827  Miss=0.00%  Hit=352128|106985|676071  Crit=838276|255325|2009334|25.3%
    collapse                   Count=  4.7| 16.93sec  DPE= 123016| 0%  DPET=      0  DPR=     0.0  pDPS=   1933  Miss=0.00%  Hit=98921|54459|397553  Crit=202374|108919|1205730|23.3%
    deadly_grace               Count= 23.8| 13.64sec  DPE= 412776| 2%  DPET=      0  DPR=     0.0  pDPS=  32888  Miss=0.00%  Hit=238204|107793|811680  Crit=862642|301820|2422104|29.3%
    legacy_of_the_windrunners  Count=  0.0|  0.00sec  DPE=      0| 6%  DPET=      0  DPR=     0.0  pDPS= 125565  Miss=0.00%  Hit=347903|56318|760403  Crit=834764|118267|2433289|32.8%
    marked_shot                Count= 23.0| 13.07sec  DPE=3038055| 0%  DPET=2829281  DPR=121524.4  pDPS=      0
    marked_shot_impact         Count=  0.0|  0.00sec  DPE=      0|11%  DPET=      0  DPR=     0.0  pDPS= 216018  Miss=0.00%  Hit=1928032|586188|3728943  Crit=4306514|1379266|11098163|38.2%
    potion                     Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=      0
    trueshot                   Count=  2.5|161.39sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=      0
    volley_tick                Count=124.1|  2.42sec  DPE= 335619| 7%  DPET=      0  DPR=111873.3  pDPS= 138764  Miss=0.00%  Hit=255596|71021|518319  Crit=577584|191211|1540615|24.9%
    windburst                  Count= 11.8| 24.43sec  DPE=3491372| 7%  DPET=2727054  DPR=160917.5  pDPS= 137170  Miss=0.00%  Hit=2464379|651348|4865572  Crit=5512195|1954045|14577174|24.8%
  Constant Buffs: defiled_augmentation/flask_of_the_seventh_demon/nightborne_delicacy_platter/volley
  Dynamic Buffs:
    blood_frenzy           : start=10.8 refresh=  6.4 interval= 28.1 trigger= 17.1 uptime=45.60%  benefit=46%
    bloodlust              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.45%  benefit=15%
    bullseye               : start= 1.0 refresh= 34.5 interval=  0.0 trigger=  0.9 uptime=10.59%  benefit=11%
    lock_and_load          : start= 9.5 refresh=  0.4 interval= 29.4 trigger= 28.0 uptime= 8.39%  benefit= 9%
    marking_targets        : start=41.9 refresh=  7.5 interval=  7.2 trigger=  6.1 uptime=30.55%  benefit=30%
    potion_of_deadly_grace : start= 2.0 refresh=  0.0 interval=287.8 trigger=  0.0 uptime=13.32%  benefit=13%
    rapid_killing          : start= 2.5 refresh=  0.0 interval=154.7 trigger=161.9 uptime=10.88%  benefit=18%
    temptation             : start= 1.0 refresh=  3.7 interval=334.6 trigger= 16.8 uptime=29.09%  benefit=75%
    trick_shot             : start= 1.0 refresh= 80.7 interval=179.8 trigger=  3.7 uptime=99.30%  benefit=99%
    trueshot               : start= 2.5 refresh=  0.0 interval=154.7 trigger=161.9 uptime=10.88%  benefit=15%
  Up-Times:
      1.3% : Focus Cap                     
  Procs:
     31.2 |   9.36sec : wasted_hunters_mark
      1.0 |  56.80sec : no_vuln_aimed_shot
      1.5 |  82.89sec : vuln_aimed_shot_0
      7.2 |  40.43sec : vuln_aimed_shot_10
      8.6 |  34.66sec : vuln_aimed_shot_20
      6.7 |  42.03sec : vuln_aimed_shot_30
     25.5 |  11.53sec : vuln_aimed_shot_40
      6.5 |  42.14sec : vuln_aimed_shot_50
     24.8 |  11.67sec : vuln_aimed_shot_60
      9.9 |  28.02sec : lock_and_load
      3.5 |  60.79sec : zevrims_hunger
     49.4 |   6.10sec : marking_targets
      7.5 |  36.85sec : wasted_marking_targets
  Gains:
        57.5 : arcane_torrent (focus)
       530.9 : arcane_shot    (focus)
      3537.7 : focus_regen    (focus)  (overflow=4.6%)
       129.9 : critical_focus (focus)
  Waiting: 1.84%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|695916213  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.04%  benefit= 4%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 6.56%  benefit= 7%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 7.65%  benefit= 8%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.26%  benefit= 8%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.85%  benefit= 9%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.78%  benefit= 9%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.95%  benefit= 9%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.67%  benefit=13%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=16.60%  benefit=17%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=17.63%  benefit=18%
    damage_taken             : start= 1.0 refresh=558.8 interval=  0.0 trigger=  0.5 uptime=100.00%
    hunters_mark             : start=21.0 refresh= 30.1 interval= 14.6 trigger=  5.9 uptime=64.75%
    vulnerability            : start=29.7 refresh=  6.1 interval= 10.3 trigger=  8.5 uptime=74.32%  benefit=99%
  Waiting: 0.00%
Waiting:
     1.8% : Kazinorian

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10011
  TotalEvents   = 19207143
  MaxEventQueue = 43
  TargetHealth  = 695916213
  SimSeconds    = 2996607
  CpuSeconds    = 26.078
  WallSeconds   = 2.787
  SpeedUp       = 114909
  EndTime       = 2017-01-16 21:55:21-0600 (1484625321)

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
Really don't know why that happened, but thanks for reporting. I'll upload a new version in 10~ minutes or so.
