### ISSUE TITLE
[Protection Warrior] Ravager and Archimonde's Hatred Reborn

### ISSUE THREAD

**Issue by Ritterbecks** [simulationcraft/simc#3415]
#### Simulationcraft Version 7.1.5 latest nightly

When simulating my Proection Warrior, Ravager seems to be way off. It does approximately 9 times more damage than ingame, where it is about 2% of my myth+ damage on HEAVY AoE pulls. The tooltip states it does round about the same dmg as Thunderclap, but over the complete duration and not per tick.

On a second note the new legendary tank trinket doesn't explode on expiring. It just disappears.

Thank you for your time.

**Comment by Collisionc** [comment]
Fixed ravager, the legendary will take more time.
