### ISSUE TITLE
Maybe make Sephuz, an option in the buffs?

### ISSUE THREAD

**Issue by achobanov** [simulationcraft/simc#3416]
This might not be a problem, but I can't seem to disable Hero buff. I unchecked it under Options, but I can still see 17% uptime on it. 

Now to the Sephuz issue - I think I should be able to disable (lol) it. Because on some bosses its not probably or even possible to activate Sephuz, let allone keep 30% uptime. 

SimulationCraft version is 715-01.

**Comment by lgkern** [comment]
Sephuz is implemented individually for each class. If it is proc'ing 30% of the time, either it is possible (constant adds) or the implementation is wrong. Which class / fight configuration are you finding that uptime?

**Comment by achobanov** [comment]
I used an updated version and it seems to work ok now. Otherwise I was Acane Mage on Patchwreck
