### ISSUE TITLE
SimulationCraft 710-03. Doesn't see crit stat on the engineering goggles. This item: http://www.wowhead.com/spell=235756/heavy-skullblasters#comments

### ISSUE THREAD

**Issue by mdrcorp** [simulationcraft/simc#3418]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by navv1234** [comment]
Adding the item straight up will not add additional stats to the item, it requires a bonus id to determine the stat value and type.
