### ISSUE TITLE
NH trinket "whispers in the dark"

### ISSUE THREAD

**Issue by ddrak3** [simulationcraft/simc#3420]
using newest simcraft nightly build

trinket: whispers in the dark, id=140809

simcraft tells me a 14% trinket uptime.
testing done by me shows that it is more like a 8 - 10% uptime

more data has to be collected, that is obvious, but i am fairly confident that simcraft is wront about the rppm of the trinket

this post is only here to inform you that the trinket is most likely not correctly implemeted

**Comment by ddrak3** [comment]
update: my results after further testing:
proc rate in nighthold raid seems to be almost exactly what simcraft tells me in sims.
proc rate in emerald nightmare is 50% of that value, uptime of about 6-8% over 30 boss fights of 3-4min each.
sample size still too low

**Comment by Jundarer** [comment]
Proc rate is correct in Simc since it's taken (pretty much) directly out of the WoW files.

**Comment by Frostedmages** [comment]
Proc rates from the game files can be wrong (see Aran's Relaxing Ruby). To test this though you will need to do 5-10hrs of a continuous log session to get a reasonably time-averaged proc rate to compare to the sim.

**Comment by Collisionc** [comment]
Closing until more data is provided.
