### ISSUE TITLE
Naraxas' Spiked Tongue not doing correct amount of damage?

### ISSUE THREAD

**Issue by loldcv** [simulationcraft/simc#3421]
#### Simulationcraft Version
715-01

#### simc_gui.simc file or contents
http://pastebin.com/Ci6G8dHe

![weird2](https://cloud.githubusercontent.com/assets/25203529/22070372/0b640e84-dd9c-11e6-8af4-d110f0a2d4af.PNG)

As seen in the image, my Trinket "Naraxas' Spiked Tongue" shows an iteration maximum damage of 145823, however in-game it consistently does 222000+ damage, sometimes even 400k+ when standing at the desired 20 yards distance from the target. Is this working correctly and I'm just doing something wrong or is something wrong here?

**Comment by loldcv** [comment]
It even sometimes crits for 400k damage.

**Comment by Collisionc** [comment]
add 

distance=20 

to the simulation, it looks like beastmastery isn't being set to the proper distance from the target  by default.

**Comment by Collisionc** [comment]
Yeah, I was setting the pet to 40 yards instead of the hunter. :D It'll be fixed in next release or nightly.

**Comment by loldcv** [comment]
Seems to be working as intended now, thank you very much!
