### ISSUE TITLE
[question] desired_targets

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#3423]
Ovale contributor here, been wondering what the variable "desired_targets" means.

For instance in the Havoc Demon Hunter APL:
`actions+=/fel_barrage,if=charges>=5&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)`

To what should that translate in WoW?

**Comment by Collisionc** [comment]
active_enemies > desired_targets effectively means that there are currently additional adds present that aren't normally there.  It's normally used with a long-cd AoE ability like bladestorm where you don't want to waste it on 2 targets when there could be 8 targets to hit in 30 seconds. 

Ex: 
Encounter with 3 permanent targets means that 'desired_targets' is always at 3.
active_enemies is the amount of available targets overall, normally 3.
A wave of 5 adds spawn, desired_targets will stay at 3, but active_enemies will now be 8
