### ISSUE TITLE
Different results for the same simulation

### ISSUE THREAD

**Issue by SebastianStruct** [simulationcraft/simc#3424]
I'm using the newest SimCraft build:
SimcSetup-715-02-Win64.exe 2017-01-18 22:59 45M

I've imported my character (Demonhunter, Havoc) from Arsenal. Same items and not logged in since yesterday.

My Settings:
Enable Scaling: Yes
Stats to scale: Agility, Crit, Haste, Mastery, Versatility

Then I simulated my character. The problem is that when I simulate 5x successively, each time different values or respectively another Pawn string comes out. Is this wanted?

**Comment by jwd83** [comment]
How many iterations are you doing? The numbers will be more consistent with more iterations. They recommend it be set to at least 10,000

**Comment by SebastianStruct** [comment]
I'm doing exactly 10,000 iterations (default value). 

All settings are default, except "Enable Scaling" and my corresponding values (agility, crit,...). It is strange that the results change every time I do the exact same simulation.

Could it be due to probabilities such as proc luck? 

EDIT: I guess my assumption is correct. More iterations -> more accurate / similar values
