### ISSUE TITLE
Eye of Command stacks resetting. Visible in Sample Sequence Table

### ISSUE THREAD

**Issue by jwd83** [simulationcraft/simc#3425]
Please include a brief overview of the issue in the title above, as well as completing the following:

SimulationCraft 715-01
for World of Warcraft 7.1.5 Live (wow build level 23360, git build 4e1343e)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

While reviewing the sample sequence table for the profile below I noticed that Legion's Gaze was resetting at times in a patchwerk encounter. Is this a bug? Also once reset it did not appear to start off at 1 stack, instead resuming at 2 (perhaps not seeing the first stack generating as it's from autos?) Section where it drops:

![image](https://cloud.githubusercontent.com/assets/52906/22098247/4b23d55c-ddf3-11e6-96a4-44231ecaeb7e.png)

demonhunter="BtrayerNewRelic"
level=110
race=night_elf
region=us
server=khaz_modan
role=
professions=alchemy=800/herbalism=267
talents=2223321
spec=havoc
artifact=3:0:0:0:0:1000:3:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:8

head=,id=137061,bonus_id=3459/3458
neck=,id=140899,enchant_id=5437,bonus_id=3514/1472/1813
shoulder=,id=139206,enchant_id=5883,bonus_id=1805/42/1492/3336
back=,id=142170,enchant_id=5435,bonus_id=1808/41/3452/1497/3337,gem_id=130219
chest=,id=142203,bonus_id=3454/1472
shirt=,id=44694
wrist=,id=142419,bonus_id=3468/1492
hands=,id=142430,bonus_id=3468/1492
waist=,id=142145,bonus_id=3453/1482/3336
legs=,id=134194,bonus_id=3412/1532/3337
feet=,id=142417,bonus_id=3468/1808/1492,gem_id=130222
finger1=,id=137038,enchant_id=5427,bonus_id=1811/3458,gem_id=130247
finger2=,id=142520,enchant_id=5427,bonus_id=3468/1808/1492,gem_id=130219
trinket1=,id=142166,bonus_id=42/3454/1472
trinket2=,id=142167,bonus_id=1808/3453/1472,gem_id=130219
main_hand=,id=127829,bonus_id=719,relic_id=3454:1472/3509:1532:3336/3454:1492:3337,gem_id=143525/137399/143525/0
off_hand=,id=127830,relic_id=0/0,gem_id=0/0/0/0

demonhunter="Btrayer"
level=110
race=night_elf
region=us
server=khaz_modan
role=
professions=alchemy=800/herbalism=264
talents=2223321
spec=havoc
artifact=3:0:0:0:0:1000:3:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:8

head=,id=137061,bonus_id=3459/3458
neck=,id=140899,enchant_id=5437,bonus_id=3514/1472/1813
shoulder=,id=139206,enchant_id=5883,bonus_id=1805/42/1492/3336
back=,id=142170,enchant_id=5435,bonus_id=1808/41/3452/1497/3337,gem_id=130219
chest=,id=142203,bonus_id=3454/1472
shirt=,id=44694
wrist=,id=142419,bonus_id=3468/1492
hands=,id=142430,bonus_id=3468/1492
waist=,id=142145,bonus_id=3453/1482/3336
legs=,id=134194,bonus_id=3412/1532/3337
feet=,id=142417,bonus_id=3468/1808/1492,gem_id=130222
finger1=,id=137038,enchant_id=5427,bonus_id=1811/3458,gem_id=130247
finger2=,id=142520,enchant_id=5427,bonus_id=3468/1808/1492,gem_id=130219
trinket1=,id=142166,bonus_id=42/3454/1472
trinket2=,id=142167,bonus_id=1808/3453/1472,gem_id=130219
main_hand=,id=127829,bonus_id=719,relic_id=3454:1472/3509:1532:3336/3453:1487:3337,gem_id=143525/137399/142181/0
off_hand=,id=127830,relic_id=0/0,gem_id=0/0/0/0

**Comment by navv1234** [comment]
Without knowing what specifically happened here, Eye of Command can drop naturally in the simulator, if you miss enough auto-attack swings. Coincidentally, since auto attacks do not show in the sample sequence table as it only records "button presses", the 2 stack is also possible.

**Comment by Zarania** [comment]
Nah, what's happening is Eye of Command is flagged as procing off white hits.  Demon Hunters have Chaos Blades which changes your white hits to be yellow, but still proc things that proc off white hits.  I know of the issue, just need to figure out the right solution for it.

**Comment by Zarania** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/728eb6c906d752cc20d459c8f9e72110dbb18f00

Should be in the next nightly.
