### ISSUE TITLE
Simulationcraft error (APPCRASH)

### ISSUE THREAD

**Issue by Lcdaxe** [simulationcraft/simc#3427]
Please include a brief overview of the issue in the title above, as well as completing the following:
**I can't even use the aplication, it just crashes right when I start it**

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
**This is the text that appears:
Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	SimulationCraft.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	587eae89
  Nombre del módulo con errores:	atioglxx.dll
  Versión del módulo con errores:	6.14.10.12337
  Marca de tiempo del módulo con errores:	52202b5f
  Código de excepción:	c0000005
  Desplazamiento de excepción:	00750705
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	11274
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789
(Sorry about the spanish stuff, but I am from Argentina**

**Comment by Lcdaxe** [comment]
Any help?

**Comment by Collisionc** [comment]
Try option 3 here - https://github.com/simulationcraft/simc/wiki/CommonIssues
