### ISSUE TITLE
Norgannon's Foresight Proc Not Activating

### ISSUE THREAD

**Issue by danaesignal** [simulationcraft/simc#3428]
While running a Light Movement sim with Norgannon's Foresight equipped I have noticed that the legendary effect seemingly never activates, and at no point do I cast any non-instant spell during movement.

#### Simulationcraft Version
Git build 3ccf48a

#### simc_gui.simc file or contents
http://pastebin.com/PNqp8vKg

#### Reproduction Steps:
1.) Equip Norgannon's Foresight on a shadow priest (have not tried other specs/classes)
2.) Run a simulation with light movement

**Comment by Collisionc** [comment]
Should work in future releases.
