### ISSUE TITLE
[Rogue] Kingsbane damage significantly lower than live

### ISSUE THREAD

**Issue by FrozenSoviet** [simulationcraft/simc#3429]
Currently in Simc build 715-02, kingsbane damage is approximatly ~7.7% of total damage, while on live logs it can be anywhere from 10-17% of dmg, and simc max ticks are ~1m crits while on live much greater kingsbane ticks can occur. 

See log: 
https://www.warcraftlogs.com/reports/L9g3B62PKFfMCpjt#fight=18&type=damage-done&start=6399029&end=6415476&source=12&view=events

https://www.warcraftlogs.com/reports/W47t6dbJgVB1FkL3#type=damage-done&source=9&fight=11&ability=192759&view=events

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/f28f50fb80159caf7d379135f32360f41cff1c54
