### ISSUE TITLE
virus detected in newest builds

### ISSUE THREAD

**Issue by rexall51** [simulationcraft/simc#3430]
When installing the latest 64 bit build as of 1/19/2017 webroot secure anywhere is detecting these two files as a threat:

qt5widgets.dll and qwindows.dll

I have installed the previous builds with no problems until now, these two files were immediately quarantined and blocked.

**Comment by eja-git** [comment]
I was just coming to post this same thing.  Nightly 64-bit build, installing via *.7z file.  Webroot tags it after unzip, but not if scanned as a zip...

**Comment by cremor** [comment]
Has to be a false positive. All scanners on VirusTotal say that they are clean:
[Qt5Widgets.dll results](https://www.virustotal.com/en/file/e6053dd3be588791c45a699071e9e570cebcb5c816d96fc01fddbce4b6e0e56b/analysis/1484941442/)
[qwindows.dll results](https://www.virustotal.com/en/file/ab597326c22d493d1dddaa980f31d53b0e935785d4b1c5c153e25dce792eb985/analysis/1484941535/)

**Comment by Collisionc** [comment]
Yeah, these are just false positives. Not much we can do about it.

**Comment by rexall51** [comment]
definitely a false positive, reinstalled again and no problems
