### ISSUE TITLE
BSOD when simulating 'CLOCK_WATCHDOG_TIMEOUT'

### ISSUE THREAD

**Issue by travvy87** [simulationcraft/simc#3431]
Version - 7.1.5 Release 1 64bit
[DxDiag.txt](https://github.com/simulationcraft/simc/files/718762/DxDiag.txt)

simc_gui.simc file appears to be empty - probably because the sim is failing.

Essentially when i click simulate, it will get to 50% or 75% before the PC will crash and BSOD. Never have any issues in any other programs and all diagnostics on PC come back clean.

**Comment by Collisionc** [comment]
See 4th option here - https://github.com/simulationcraft/simc/wiki/CommonIssues
