### ISSUE TITLE
Frost Deathknight APL issues

### ISSUE THREAD

**Issue by amollerson** [simulationcraft/simc#3432]
actions+=/sindragosas_fury,if=buff.pillar_of_frost.up&(buff.unholy_strength.up|(buff.pillar_of_frost.remains<3&target.time_to_die<60))&debuff.razorice.stack==5&!buff.obliteration.up

Has a double equals on debuff.razorice.stack==5, which is causing a syntax error.

**Comment by ssateneth** [comment]
Weird, I don't get that syntax error. But I'm using GUI so maybe it ignores it. I get correct behavior from = as well as ==

**Comment by sparkcoil** [comment]
Looks like the parser treats = and == the same without complaining, though looking through all the current APL files the only current usage is the one mentioned above.  The same allowance is made for ||, &&, ^^, ~~, and perhaps others.  I guess this was done to allow common C syntax to not cause hard errors in the APL.

**Comment by amollerson** [comment]
Guess I was mistaken. Thought since it was the only usage it was an error.

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/05a6f98cafae1f7627009ed5650480e0ecf72899
