### ISSUE TITLE
MM 2 peice being overvalued

### ISSUE THREAD

**Issue by Alatariel96** [simulationcraft/simc#3433]
When I sim myself with just the two set and a full artifact without quick shot relics I get a trueshot interval of 86 seconds. For this to be possible you would have to spend 64*35=2240 focus or 26 focus a second and it isn't even possible to generate that much focus with 100% haste

[APL used](http://pastebin.com/wAcSbuer)

simmed with a 200 second fight and 0 variance because I only wanted to see the cooldown of trueshot
Using 715-02

**Comment by Jayezi** [comment]
Looks like Windrunner procs were reducing the cooldown as if they were regular Aimed Shots, but I see a recent change in the newest nightly build that should fix it. I'm getting around 110 second intervals with it now.
http://downloads.simulationcraft.org/?C=M;O=D

**Comment by nuoHep** [comment]
Yeah, commit e9a99d13246bc9a2dc7d75f82db81e63295d7fec should've already fixed it, but I've just commited another one which should make the set implementation more robust to possible problems/inconsistencies in our handling of spell data.

**Comment by Alatariel96** [comment]
That was my bad Didn't see the change
