### ISSUE TITLE
[Rogue] Insignia Not Properly Simulated for Assassination

### ISSUE THREAD

**Issue by pnmueller** [simulationcraft/simc#3435]
The current Simulationcraft version doesn't appear to correctly model Insignia for Assassination. In particular, Simulationcraft models Insignia as if it always did the same percentage of the Mutilate's damage whereas in-game it takes pre-Vendetta damage, resulting in significantly lower Insignia damage. You can clearly see this when looking at the total damage contribution of Insignia but also when looking at the logs in detail:
In-game:
00:00:07.432	Rogue Mutilate Krosus *211720*
00:00:07.432	Rogue Mutilate Off-Hand Krosus *106134*
00:00:07.458	Rogue Insignia of Ravenholdt Krosus *66296*
00:00:07.458	Rogue Insignia of Ravenholdt Krosus *33234*
00:00:07.827	Krosus is afflicted by Vendetta from Rogue
00:00:08.430	Rogue Mutilate Krosus 147881
00:00:08.430	Rogue Mutilate Off-Hand Krosus 68424
00:00:08.454	Rogue Insignia of Ravenholdt Krosus *71240*
00:00:08.454	Rogue Insignia of Ravenholdt Krosus *32962*

Simulationcraft:
3.014 Rogue mutilate_mh hits Fluffy_Pillow for 214429 physical damage (crit)
3.014 Rogue insignia_of_ravenholdt hits Fluffy_Pillow for 34424 shadow damage (hit)
3.014 Rogue mutilate_oh hits Fluffy_Pillow for 114690 physical damage (crit)
3.014 Rogue insignia_of_ravenholdt hits Fluffy_Pillow for 18412 shadow damage (hit)
4.018 Fluffy_Pillow gains vendetta_1 ( value=0.30 )
5.021 Rogue mutilate_mh hits Fluffy_Pillow for 170481 physical damage (hit)
5.021 Rogue insignia_of_ravenholdt hits Fluffy_Pillow for 54737 shadow damage (hit)
5.021 Rogue mutilate_oh hits Fluffy_Pillow for 85236 physical damage (hit)
5.021 Rogue insignia_of_ravenholdt hits Fluffy_Pillow for 27367 shadow damage (hit)

As you can see, Simulationcraft has Insignia damage at a constant ~30% no matter if Vendetta is up. If you look at in-game logs however, Insignia damage drops to ~23% of Mutilate's damage which is ~30% of the pre-Vendetta damage. Thus it appears that Insignia is calculated without any debuffs taken into account in-game which is not properly reflected in Simulationcraft.

**Comment by aethys256** [comment]
Thanks, may you do some test for me ?
Test with 0 AP stacks (no poison) and 5 AP Stacks.

I would like to see if it ignores all target_modifier or just Vendetta.

Thank you in advance.

**Comment by aethys256** [comment]
See my commit: https://github.com/simulationcraft/simc/commit/b912654d60c44031d5df68569de3d39884a32212

This is what I have as result:
9.079 Rogue_Assassination_T19M_NH mutilate_mh hits Fluffy_Pillow for 148097 physical damage (hit)
9.079 Rogue_Assassination_T19M_NH insignia_of_ravenholdt hits Fluffy_Pillow for 97757 shadow damage (crit)
9.079 Rogue_Assassination_T19M_NH mutilate_oh hits Fluffy_Pillow for 148091 physical damage (crit)
9.079 Rogue_Assassination_T19M_NH insignia_of_ravenholdt hits Fluffy_Pillow for 48876 shadow damage (crit)
10.084 Fluffy_Pillow gains vendetta_1 ( value=0.30 )
12.093 Rogue_Assassination_T19M_NH mutilate_mh hits Fluffy_Pillow for 201377 physical damage (hit)
12.093 Rogue_Assassination_T19M_NH insignia_of_ravenholdt hits Fluffy_Pillow for 46524 shadow damage (hit)
12.093 Rogue_Assassination_T19M_NH mutilate_oh hits Fluffy_Pillow for 100685 physical damage (hit)
12.093 Rogue_Assassination_T19M_NH insignia_of_ravenholdt hits Fluffy_Pillow for 23261 shadow damage (hit)

Keep me up on AP and do not hesitate to reopen / open a new one.

**Comment by pnmueller** [comment]
Looks good.

From what I've seen (and just checked again to be certain), it works just fine with AP and the % of the initial hit is the same with and without AP applied. Subsequently AP properly increases the damage of Insignia (but doesn't double-dip).

I haven't tested any other debuffs but that'd indicate it's a bug isolated to Vendetta, possibly because of some internal miscommunication when trying to ensure it doesn't double-dip.

**Comment by aethys256** [comment]
Yes, as I posted on Ravenholdt Theorycrafting channel, only Vendetta "creates" this bug.
