### ISSUE TITLE
[Prot Warrior] Thunder Clap not Resesting Shield slam CD

### ISSUE THREAD

**Issue by Tengenstein** [simulationcraft/simc#3437]
Please include a brief overview of the issue in the title above, as well as completing the following:

In game, Thunder Clap does more Damage the Devastate, on a single target by about 35% and generates 5 rage, and like Devastate has 30% chance to  reset Shield Slams CD, I can't really see why when maximizing TMI Thunderclap isn't above Devastate in the APL, however if you do change the APL to use Thunder Clap over Devastate, not only is it a 4k TMI increase the warrior casts less Shield slams but a cursory look through the sample sequence table, does not show a single TC preceding a shield slam that has not already finished it's cooldown.

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
tmi_boss=TMI_Standard_Boss_T19H
tmi_boss_type=T19H
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
scale_over=TMI
statistics_level=1
### Begin simulateText ###
warrior="Tengenstein"
origin="https://eu.api.battle.net/wow/character/azuremyst/Tengenstein/advanced"
thumbnail="http://eu.battle.net/static-render/eu/azuremyst/139/68691851-avatar.jpg"
level=110
race=goblin
role=tank
position=front
professions=engineering=783/mining=800
talents=http://eu.battle.net/wow/en/tool/talent-calculator#Zb!0112101
artifact=11:0:0:0:0:91:1:92:1:93:1:94:1:95:3:96:3:97:1:98:3:99:3:100:3:101:3:102:3:103:1:104:1:105:3:106:3:1358:1:1395:12
spec=protection

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=azshari_salad
actions.precombat+=/augmentation,type=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=unbending_potion

# Executed every time the actor is available.
actions=auto_attack
actions+=/intercept
actions+=/use_item,name=girdle_of_the_nethertouched
actions+=/use_item,name=unbridled_fury
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/call_action_list,name=prot

actions.prot=spell_reflection,if=incoming_damage_2500ms>health.max*0.20
actions.prot+=/demoralizing_shout,if=incoming_damage_2500ms>health.max*0.20
actions.prot+=/last_stand,if=incoming_damage_2500ms>health.max*0.50
actions.prot+=/shield_wall,if=incoming_damage_2500ms>health.max*0.50&!cooldown.last_stand.remains=0
actions.prot+=/potion,name=unbending_potion,if=(incoming_damage_2500ms>health.max*0.15&!buff.potion.up)|target.time_to_die<=25
actions.prot+=/battle_cry,if=cooldown.shield_slam.remains=0
actions.prot+=/revenge,if=buff.revenge.react
actions.prot+=/demoralizing_shout,if=talent.booming_voice.enabled&buff.battle_cry.up
actions.prot+=/ravager,if=talent.ravager.enabled&buff.battle_cry.up
actions.prot+=/neltharions_fury,if=!buff.shield_block.up&cooldown.shield_block.remains>3&cooldown.shield_slam.remains>3
actions.prot+=/shield_block,if=!buff.neltharions_fury.up&(cooldown.shield_slam.remains=0|action.shield_block.charges=2)
actions.prot+=/shield_slam,if=!(cooldown.shield_block.remains<=gcd.max*2&!buff.shield_block.up&talent.heavy_repercussions.enabled)
actions.prot+=/revenge,if=cooldown.shield_slam.remains<=gcd.max*1.5|spell_targets.revenge>=2
actions.prot+=/ignore_pain,if=(rage>=60&!talent.vengeance.enabled)|(buff.vengeance_ignore_pain.up&rage>=39)|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage<30)
actions.prot+=/revenge,if=(buff.vengeance_revenge.up&!buff.vengeance_ignore_pain.up&rage>=59)|!buff.vengeance_ignore_pain.up|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage>=69)|(rage>=100)
actions.prot+=/thunder_clap
actions.prot+=/devastate

head=venomfanged_barbute,id=139229,bonus_id=1805/1492/3336
neck=prydaz_xavarics_magnum_opus,id=132444,bonus_id=1811/3458,gems=150haste,enchant=mark_of_the_heavy_hide
shoulders=crusaders_inferno_pauldrons,id=140021
back=drape_of_the_unworthy,id=142521,bonus_id=3507/1497,enchant=gift_of_haste
chest=destiny_driver,id=137018,bonus_id=3459/3458
shirt=brawlers_harness,id=6125
wrists=wristclamps_of_mad_dreams,id=139235,bonus_id=1805/1492/3336
hands=reinforced_houndhandlers_gauntlets,id=142435,bonus_id=3468/40/1492
waist=girdle_of_the_nethertouched,id=140000,addon=nitro_boosts
legs=goldrune_legplates,id=142425,bonus_id=3468/1808/43/1492,gems=150haste
feet=duskwatch_guards_boots,id=137482,bonus_id=3416/1522/3336
finger1=dreadful_cyclopean_signet,id=139237,bonus_id=1805/1487,enchant=200haste
finger2=mindrend_band,id=138220,bonus_id=1805/1808/1502/3337,gems=150haste,enchant=200haste
trinket1=unstable_arcanocrystal,id=141482,bonus_id=1487/3337
trinket2=unbridled_fury,id=139327,bonus_id=1805/1487
main_hand=scaleshard,id=128288
off_hand=scale_of_the_earthwarder,id=128289,bonus_id=752,gem_id=140815/137544/142516/0,relic_id=3444:1482:1813/3414:1517:3336/3468:1492/0

# Gear Summary
# gear_ilvl=880.56
# gear_strength=14850
# gear_stamina=27121
# gear_crit_rating=6372
# gear_haste_rating=9734
# gear_mastery_rating=9759
# gear_versatility_rating=896
# gear_avoidance_rating=483
# gear_armor=4324

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:
Run a sim using standard prot warrior APL

invert last two lines of apl;
- actions.prot+=/devastate
- actions.prot+=/thunder_clap

So they now read
- actions.prot+=/thunder_clap
- actions.prot+=/devastate

Run a sim using the now modified APL
Compare TMI results.

**Comment by adamhl8** [comment]
The Prot Warrior APL was updated in commit acb2867. It includes the Thunder Clap > Devastate change you mentioned. The new APL is in the [latest nightly build](http://downloads.simulationcraft.org/?C=M;O=D).

**Comment by Tengenstein** [comment]
The nightly build has the same issue, if you prioritize Thunder Clap over Devastate, TMI goes up, RPS and number of Shield Slam casts go down. Something is not quite right; TC should  not lead to less SS casts.

**Comment by adamhl8** [comment]
503d6b6

Fixed Thunder Clap not resetting Shield Slam.

Unfortunately free Revenges are bugged so testing for which spell to prioritize is basically impossible right now.

**Comment by adamhl8** [comment]
Just ran a few sims with the TClap fix in place; prioritizing TClap > Devastate is always a gain now,
