### ISSUE TITLE
[Unholy Death Knight] APL Improvements

### ISSUE THREAD

**Issue by Maxweii** [simulationcraft/simc#3440]
#### Simulationcraft Version

715-02

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/qJE8QGuS

Various APL improvements for Unholy Death Knight's.

**Comment by gixxpunk** [comment]
https://github.com/simulationcraft/simc/commit/b7f09a2e30313b2bb6283da050a3b1275c5abeaf
