### ISSUE TITLE
[Rogue] Negative Mastery Stat weight for Outlaw

### ISSUE THREAD

**Issue by ogot** [simulationcraft/simc#3441]
Had a sim give a negative stat weight for Mastery as Outlaw.

#### Simulationcraft Version

SimulationCraft 715-02
for World of Warcraft 7.1.5 Live (wow build level 23360, git build b4fa3d9)

#### simc_gui.simc file or contents

https://drive.google.com/open?id=0BxO4oDY4CriCZGx5T1h1WlZnYU0

#### Reproduction Steps:

I logged out, imported my character on SimC, changed to 5 targets and HecticAddCleave in Globals and enabled scaling, then simmed.

**Comment by aethys256** [comment]
I see the "bug" but I don't know how to fix it atm.
@navv1234 @mrdmnd Any idea ?

**Comment by aethys256** [comment]
This is related to this commit:
https://github.com/simulationcraft/simc/commit/b17d600fc2138a3906273aee0ed4927dcb7b48b7

But I don't know why yet.

**Comment by Collisionc** [comment]
Fixed here - https://github.com/simulationcraft/simc/commit/5835edceb6ef403a478a1b462b86ee8b4e22160c
