### ISSUE TITLE
[Demonhunter] Fel Erruption damage is broken

### ISSUE THREAD

**Issue by cnork** [simulationcraft/simc#3442]
#### Simulationcraft Version:
git build 4e1343e

#### simc_gui.simc file or contents:
http://pastebin.com/kjctzgig

#### Issue Description: 
I just simd my Vengeance Tank with Fel Erruption taken as the T3 talent. The DPS result was way above of what you can archive, a quick look at the simulation showed fel_erruption was calculated to do 2.9M damage per execute.

**Comment by Zarania** [comment]
Will take a look tonight.

**Comment by Zarania** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/77521fbde26b1946323690cac1c6478df91c5547
