### ISSUE TITLE
Sphere of Insanity doesn't deal damage

### ISSUE THREAD

**Issue by nasirabtw** [simulationcraft/simc#3446]
http://pastebin.com/cH0GCUcy

replace artifact line with 47:0:0:0:0:764:1:765:1:766:1:767:3:768:1:769:1:770:1:771:3:772:3:773:3:774:3:775:3:776:3:777:3:778:3:779:1:1347:1

Sphere of Insanity doesn't deal any damage. The intended mechanic is that anytime you deal damage with voidbolt, mindblast, or mindflay (excluding the aoe swp ticks), they check if any target within 100 yards has SWP, and if they do it deals 5% of the damage dealt to them in addition. This also applies to single target. ie they will deal 5% more damage to one target if it has swp applied.

**Comment by lgkern** [comment]
Thanks for reporting it. 
Looking at the code it also seems that the original implementation of Sphere is wrong, it was dealing damage only to one target instead of all targets with SWP up. I'll refactor the implementation to fix the damage and the targets affected.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/5fe3b81bd3d08163459fe86e104f3824236ba8da

Fixed ( i think) here

**Comment by lgkern** [comment]
Confirmed working now, even for multiple targets.
