### ISSUE TITLE
Trinket "Ley Spark" not working in Simulationcraft

### ISSUE THREAD

**Issue by loldcv** [simulationcraft/simc#3447]
#### Simulationcraft Version
715-02

#### simc_gui.simc file or contents
http://pastebin.com/iJ0HKvBr

#### What is the problem?
The trinket called "Ley Spark" gives you a buff called "Sparking" which increases your agility.

![buff](https://cloud.githubusercontent.com/assets/25203529/22205000/4d770cd6-e175-11e6-8ae4-e7b4a03dbb50.png)

However when you simulate with this trinket equipped, I cant find the buff anywhere in the results.

![nobuff](https://cloud.githubusercontent.com/assets/25203529/22205091/9be733b4-e175-11e6-9fa5-67d97f54b768.PNG)
![whereitismen](https://cloud.githubusercontent.com/assets/25203529/22205175/dcadf626-e175-11e6-8f68-d03640c7942d.PNG)

Is the proc just not being accounted for at all?

**Comment by Collisionc** [comment]
Will work in the next version.
