### ISSUE TITLE
[Prot Warrior] Stat calculations differ from in-game

### ISSUE THREAD

**Issue by adamhl8** [simulationcraft/simc#3450]
The total amount for some stats seems a bit off.

Sim HTML report: https://dl.dropboxusercontent.com/u/50556991/results_html.html

In-game stats (no buffs, flasks, etc): http://i.imgur.com/BI3ql8V.png

The gear is exactly the same for both.

- Stam - 72171 vs. 71687
- Strength - 28800 vs. 28809
- Armor is the biggest outlier. 8010 vs. 4797
- Parry - 17.41% vs. 21.78%

**Comment by ssateneth** [comment]
Need your simc_gui.simc file too

**Comment by adamhl8** [comment]
https://www.dropbox.com/s/twd5j3ehga64q02/simc_gui.simc?dl=0
