### ISSUE TITLE
Nightblooming Frond incorrectly benefiting from Jeweled Signet of Melandrus

### ISSUE THREAD

**Issue by Rusah** [simulationcraft/simc#3452]
Nightblooming Fronds is incorrectly gaining +10% damage from http://www.wowhead.com/item=134542/jeweled-signet-of-melandrus&bonus=1826

Proof that it should not benefit via warcraftlogs:
No ring: https://www.warcraftlogs.com/reports/32pRKzNHBF9MkmtT/#type=damage-done&source=10&view=events&ability=225739

Ring equipped: https://www.warcraftlogs.com/reports/3BLMyxcdQkY146X9/#type=damage-done&source=1&ability=225739&view=events

Proof the ring was equipped can be compared from the auto attack damage being 10% higher on average. Recursive strikes however, has the same damage at one stack as 15 between the 2 logs.

This can easily be reproduced in simc by having Nightblooming Fronds and the ring equipped at the same time, then toggling the ring as inactive and the fronds damage will be approximately 10% higher with the ring than without.

My assumption from glancing at the fronds implementation is that its pulling in the auto attack damage after its calculation has already included the ring's bonus damage.

**Comment by Collisionc** [comment]
Thanks for reporting, this will fix the damage of quite a few trinkets in cases where the person was wearing that ring.
