### ISSUE TITLE
Simulationcraft doesn't respond when i open

### ISSUE THREAD

**Issue by victorsaad00** [simulationcraft/simc#3453]
Hello,
It's my first time using simulationcraft software. I downloaded it today the version 7.1.5 ( the lastest one 64 bit ). Well, i run the first simulation for my character and when i was about to run the second simulation my PC stoped running everything and i had to reset it. When i turn on the PC and run back the simulationcraft software it just stop running, doesn't respond and i have to close the program. Well, i tried to unistall and install again, downloaded the 3th release of 7.1 and the same error occurs.

This is my DxDiag:
[DxDiag.txt](https://github.com/simulationcraft/simc/files/728026/DxDiag.txt)

This is my MsInfo : 
[MSinfo.txt](https://github.com/simulationcraft/simc/files/728029/MSinfo.txt)

I didn't find any simc_gui.simc file, sorry. 
Hope we can fix this problem!!! Thanks heeelping!!

**Comment by Collisionc** [comment]
Can you link the armory of the character you are trying to sim ?

**Comment by victorsaad00** [comment]
Is it this? http://us.battle.net/wow/en/character/zuljin/Demonsler/simple

**Comment by victorsaad00** [comment]
Well, the 32 version seens to work pretty well. In a few hours i'll be testing all stuff. If it works out, i post and close the the issue.  Thanks
