### ISSUE TITLE
Draught of Souls damage and Cooldown are incorrect

### ISSUE THREAD

**Issue by Kazkek** [simulationcraft/simc#3455]
The damage done per execute of Draught of Souls is currently undervalued. For an 885 trinket it currently sims around 175k to 196k when it should be around 225k to 246k. This is without agonizing poison being applied. If agonizing poison is used in the sim, it correctly modifies the low damage but it is still lower than what live damage is with AP. The cooldown of the trinket is also incorrectly being used in simc. Right now in Simc it is showing a 1.3 min cooldown but on live the cooldown of the trinket is 2 mins.

**Comment by Kazkek** [comment]
This might be a bug on Blizzards side of things. Currently some people in my guild see the item as 1 min and 20 second cooldown and some see it as a 2 minute cooldown.

**Comment by Collisionc** [comment]
Does the damage change depending on what they see ?

**Comment by Kazkek** [comment]
Here is what I got with a GM response. I found logs yesterday that had rogues with 1min 20sec CD and Rogues with 2min CDs I couldnt find exact times of the logs but there might have been a hotfix during the day to change it. Logs today from EU show 2 min CDs. Not sure on the damage but my damage is currently what I posted before.

> Hey, Caerriss!
>
> I'm Game Master Thiweza, the Dragon of White!
>
> Just wanted to glide on by and talk to you about your Draught of Souls!
>
> Looking into the logs, it looks like there's actually a change to the Global Cooldown on Draught of Souls overal :C looks like it's now 2 minutes.
>
> I have two links here to help clear it up.
> https://us.battle.net/forums/en/wow/topic/20752765373?page=4#79
> http://www.wowhead.com/item=140808/draught-of-souls&bonus=3515#comments
>
> If everything's a-okay with this specific issue, make sure you're hitting the 'resolved' button. If you do have any further unrelated issues, feel free to open a new ticket!
>
> Good bye, and be blessed with the light from Thiweza, the Dragon of White!

Not the most comprehensive GM response but still one none the less.

**Comment by bitfluxhound** [comment]
Tested in game on NA servers : http://i.imgur.com/4a2D5yG.png 1 min 20 sec

**Comment by Kazkek** [comment]
https://www.warcraftlogs.com/reports/N9act8TXMCn4yw1r 
This was on live yesterday afternoon. 2 min CD. Also here is a rather boring video I just took of the 2 min CD with the damage mentioned before in the tooltip.
https://youtu.be/GrjdlCO0p80

What class was that on bitfluxhound?

**Comment by Collisionc** [comment]
Yeah, it's definitely supposed to be 1 minute and 20 seconds.  Also, that is the least useful gm response I've ever seen. 

"Looking into the logs, it looks like there's actually a change to the Global Cooldown on Draught of Souls overal :C looks like it's now 2 minutes."

The Global Cooldown (GCD) was hotfixed to 1.5 seconds, he's just talking out of his ass. 

Try this to fix the problem in game -- Make sure you have exited the game first.
1: Go to your world of warcraft folder, delete all contents of the Cache\ADB\ folder
2: Reload wow, see if the trinkets cooldown is correct.

**Comment by Kazkek** [comment]
Deleting that did not do anything for me. Still 2 min CD. It was also 2 min CD for Ret paladin in the guild.  Wowhead as well has it at 2 min CD but just a day ago had it at 1min 20s. But I am unsure of where they pull their information, the changelog for 7.2 PTR build has it at 1.33min CD.
http://www.wowhead.com/spell=225141/fel-crazed-rage#changelog

**Comment by Kazkek** [comment]
Also the DH in the guild that said it was 1min 20s last night now says its 2 mins. For him it says it does 197k damage every 0.25s for 3s. Thats near the same damage as when I swap to outlaw and sub with the same 2min CD.

**Comment by Collisionc** [comment]
It might be a server-specific thing that blizzard screwed up? So far everyone I've asked on Mal'ganis has a 1 minute 20 second cd, as of 30 minutes ago or so.

**Comment by Collisionc** [comment]
Also make sure you are checking this in a raid, apparently it's showing up as a 2 minute cd while attacking training dummys for some unexplainable reason.

**Comment by Kazkek** [comment]
Yeah been doing mythic all night and its 2 min so far the whole time.

**Comment by Collisionc** [comment]
I don't know what's happening, then. I can add in options to limit the cooldown on the item, but this smells like a blizzard bug more so than anything.

**Comment by bitfluxhound** [comment]
I've had it 1:20 as rogue in raid/m+/open world.

**Comment by Kazkek** [comment]
Yeah I think the issue is trying to figure out if blizzard intended a 1min 20s or a 2min CD. Conflicting info on both CDs. Its definitely a blizzard bug and sounds most likely a server hotfix thing.

**Comment by Kazkek** [comment]
Well the trinket was hotfixed today to be 1 min 20s and the damage is on par with what is on Simc now. Although I think its a little lower than what I see in Simc. On live it looks to be 158k to 175k on my tooltip now.

This morning it was 2mins in raid so it must of went out with the hotfixes.
