### ISSUE TITLE
Player attempting 'use_item' action with item 'draught_of_souls' which is not currently equipped.

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3457]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

715-02 
Nightly Build (2017-01-25 01:59)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/eTvPMGjZ

#### Reproduction Steps:

Simulating Burrock-Bronzebeard gives the following error:
Player Burrock attempting 'use_item' action with item 'draught_of_souls' which is not currently equipped.

http://imgur.com/a/Gl9qW

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
It's just a warning, ignore it for now.
