### ISSUE TITLE
After i run a simulation it has stopped providing me with any information. 

### ISSUE THREAD

**Issue by Cernnunnose123** [simulationcraft/simc#3458]
It worked really well at first. I ran multiple simulation on my Deamon Hunter with different gear just to test it out. I went to run a simulation on my druid and now nothing works. I didnt mess with any setting other than changing my "scaling" options not not include agility but to instead include intillect and changed it from DPS to Raid_HPS.

7.1.5 release 1 Simulationcraft Version

Reproduction Steps: ran ingame addon /simc
copied into import page in program
ran simulate
results pages are empty

~File Attached

**Comment by Collisionc** [comment]
There is no file attached.

**Comment by Cernnunnose123** [comment]
apologies. apparently they dont like the file type.

the file content is as follows:

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Cernnunnose"
level=110
race=night_elf
region=us
server=lightbringer
role=
professions=alchemy=800/herbalism=800
talents=1211331
spec=restoration
artifact=13:0:0:0:0:125:1:126:1:127:1:128:1:129:1:130:3:131:3:132:3:133:3:134:3:135:3:136:3:137:3:138:1:139:1:140:3:1335:1:1367:5

head=,id=141418,bonus_id=1472
neck=,id=139239,enchant_id=5890,bonus_id=1805/1808/1487,gem_id=130248
shoulder=,id=139206,enchant_id=5442,bonus_id=1805/1492/3336
back=,id=139248,enchant_id=5436,bonus_id=1805/1492/3336
chest=,id=139208,bonus_id=1805/1487
wrist=,id=139209,bonus_id=1805/1492/3336
hands=,id=144242,enchant_id=5444,bonus_id=3529/3530
waist=,id=140858,bonus_id=3443/1472/3336
legs=,id=134448,bonus_id=1727/1497/3336
feet=,id=139200,bonus_id=1805/1808/1487,gem_id=130219
finger1=,id=137042,enchant_id=5428,bonus_id=1811/3458,gem_id=130220
finger2=,id=139238,enchant_id=5427,bonus_id=1805/1808/1492/3336,gem_id=130219
trinket1=,id=139330,bonus_id=3379/1808/1462/3336,gem_id=130220
trinket2=,id=139322,bonus_id=1805/1497/3336
main_hand=,id=128306,bonus_id=725,relic_id=3473:1517:3337/1805:1502:3337/1805:1492:3336,gem_id=141275/139259/138228/0
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

**Comment by Cernnunnose123** [comment]
![simcraft fail](https://cloud.githubusercontent.com/assets/25336610/22313811/23667a84-e324-11e6-8ef3-49db9e9e96b5.jpg)

**Comment by Collisionc** [comment]
Click on the arrow beside "Cernnunnose: 110730 hpss"
