### ISSUE TITLE
Simulationcraft is not importing three ranks for cold as ice(fdk artifact trait)

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3459]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps: When importing my character using the import feature I've noticed it only shows one rank for  the artifact trait "cold as ice" even though I have all three. It does show the extra rank I have from a relic but not the full three baseline. Instead it shows one rank plus one rank.

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
I believe this was fixed in the last 12 hours or so, can you test the newest download?

http://downloads.simulationcraft.org/?C=M;O=D

top download

**Comment by ghost** [comment]
Tested, the latest version is showing the proper amount of ranks for cold as ice now. Much obliged for all the work you all do here, thanks can't be said enough.
