### ISSUE TITLE
Fire Mage stat weights incorrectly giving haste as most value stat?

### ISSUE THREAD

**Issue by Maikel1983** [simulationcraft/simc#3460]
Just ran several sims of type cleave and type patchwerk single target ...
Simcraft suggested to drop my crit down to 51% (from 62%)  and increase my haste on another test on a patchwork fight ......
After rerunning the sim at 51% crit it still gives the highest stat weight to haste ... This doesn't seem to make sense.

currently after first cycle (increasing both dps on 3 targets same level as caster as patchwork raid boss..

33.6k int
51% crit
13% haste
15% mastery
6% versatility
2% leech.

#### Simulationcraft Version
70501

#### simc_gui.simc file or contents

DPS Ranking:
 359701 100.0%  Raid
 359701  100.0%  Kalanya

HPS Ranking:
      0 100.0%  Raid

Player: Kalanya human mage fire 110
  DPS: 359701.5  DPS-Error=296.7/0.082%  DPS-Range=56406/15.7%  DPS-Convergence=70.7%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=19.6  RPS-Out=18279.4 RPS-In=18279.4  Resource=(mana) Waiting=0.0 ApM=47.8
  Talents: 2121111
  Artifact: 54:0:0:0:0:748:1:749:3:750:3:751:3:752:3:753:3:754:3:755:3:756:3:757:3:758:1:759:1:760:1:761:1:762:1:763:1:1340:1:1372:4
  Core Stats:    strength=4875|4550(4550)  agility=6577|6252(6252)  stamina=43552|43552(32746)  intellect=35307|33601(32368)  spirit=0|0(0)  health=2613120|2613120  mana=1100000|1100000
  Generic Stats: mastery=15.34%|15.34%(4979)  versatility=6.06%|6.06%(2878)  leech=1.60%|1.60%(369)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=35307|33601(0)  hit=15.00%|15.00%(0)  crit=52.13%|51.08%(12431)  haste=13.03%|13.03%(4886)  speed=13.03%|13.03%  manareg=16500|16500(0)
  Attack Stats:  power=0|0(0)  hit=7.50%|7.50%(0)  crit=34.21%|33.25%(11301)  expertise=7.50%|7.50%(0)  haste=13.03%|13.03%(4886)  speed=13.03%|13.03%
  Defense Stats: armor=1779|1779(1779) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=3.03%|3.03%(2878)
  Priorities (actions.precombat):
    flask,type=flask_of_the_whispered_pact/food,type=the_hungry_magister
    augmentation,type=defiled/snapshot_stats/mirror_image/potion,name=deadly_grace
    pyroblast
  Priorities:
    counterspell,if=target.debuff.casting.react
    time_warp,if=(time=0&buff.bloodlust.down)|(buff.bloodlust.down&equipped.132410&(cooldown.combustion.remains<1|target.time_to_die.remains<50))
    mirror_image,if=buff.combustion.down
    rune_of_power,if=cooldown.combustion.remains>40&buff.combustion.down&!talent.kindling.enabled|target.time_to_die.remains<11|talent.kindling.enabled&(charges_fractional>1.8|time<40)&cooldown.combustion.remains>40
    call_action_list,name=combustion_phase,if=cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)|buff.combustion.up
    call_action_list,name=rop_phase,if=buff.rune_of_power.up&buff.combustion.down
    call_action_list,name=standard_rotation
  Priorities (actions.combustion_phase):
    rune_of_power,if=buff.combustion.down/call_action_list,name=active_talents
    combustion/potion,name=deadly_grace/blood_fury/berserking/arcane_torrent
    use_item,slot=trinket1
    pyroblast,if=buff.kaelthas_ultimate_ability.react&buff.combustion.remains>execute_time
    pyroblast,if=buff.hot_streak.up/fire_blast,if=buff.heating_up.up/phoenixs_flames
    scorch,if=buff.combustion.remains>cast_time
    dragons_breath,if=buff.hot_streak.down&action.fire_blast.charges<1&action.phoenixs_flames.charges<1
    scorch,if=target.health.pct<=30&equipped.132454
  Priorities (actions.rop_phase):
    rune_of_power
    flamestrike,if=((talent.flame_patch.enabled&active_enemies>1)|(active_enemies>3))&buff.hot_streak.up
    pyroblast,if=buff.hot_streak.up/call_action_list,name=active_talents
    pyroblast,if=buff.kaelthas_ultimate_ability.react&execute_time<buff.kaelthas_ultimate_ability.remains
    fire_blast,if=!prev_off_gcd.fire_blast
    phoenixs_flames,if=!prev_gcd.1.phoenixs_flames
    scorch,if=target.health.pct<=30&equipped.132454
    dragons_breath,if=active_enemies>2
    flamestrike,if=(talent.flame_patch.enabled&active_enemies>2)|active_enemies>5
    fireball
  Priorities (actions.active_talents):
    blast_wave,if=(buff.combustion.down)|(buff.combustion.up&action.fire_blast.charges<1&action.phoenixs_flames.charges<1)
    meteor,if=cooldown.combustion.remains>15|(cooldown.combustion.remains>target.time_to_die)|buff.rune_of_power.up
    cinderstorm,if=cooldown.combustion.remains<cast_time&(buff.rune_of_power.up|!talent.rune_on_power.enabled)|cooldown.combustion.remains>10*spell_haste&!buff.combustion.up
    dragons_breath,if=equipped.132863|(talent.alexstraszas_fury.enabled&buff.hot_streak.down)
    living_bomb,if=active_enemies>1&buff.combustion.down
  Priorities (actions.standard_rotation):
    flamestrike,if=((talent.flame_patch.enabled&active_enemies>1)|active_enemies>3)&buff.hot_streak.up
    pyroblast,if=buff.hot_streak.up&buff.hot_streak.remains<action.fireball.execute_time
    phoenixs_flames,if=charges_fractional>2.7&active_enemies>2
    pyroblast,if=buff.hot_streak.up&!prev_gcd.1.pyroblast
    pyroblast,if=buff.hot_streak.react&target.health.pct<=30&equipped.132454
    pyroblast,if=buff.kaelthas_ultimate_ability.react&execute_time<buff.kaelthas_ultimate_ability.remains
    call_action_list,name=active_talents
    fire_blast,if=!talent.kindling.enabled&buff.heating_up.up&(!talent.rune_of_power.enabled|charges_fractional>1.4|cooldown.combustion.remains<40)&(3-charges_fractional)*(12*spell_haste)<cooldown.combustion.remains+3|target.time_to_die.remains<4
    fire_blast,if=talent.kindling.enabled&buff.heating_up.up&(!talent.rune_of_power.enabled|charges_fractional>1.5|cooldown.combustion.remains<40)&(3-charges_fractional)*(18*spell_haste)<cooldown.combustion.remains+3|target.time_to_die.remains<4
    phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up|buff.incanters_flow.stack>3|talent.mirror_image.enabled)&artifact.phoenix_reborn.enabled&(4-charges_fractional)*13<cooldown.combustion.remains+5|target.time_to_die.remains<10
    phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up)&(4-charges_fractional)*30<cooldown.combustion.remains+5
    flamestrike,if=(talent.flame_patch.enabled&active_enemies>1)|active_enemies>5
    scorch,if=target.health.pct<=30&equipped.132454/fireball
  Actions:
    blast_furance            Count= 27.7| 10.99sec  DPE=  42214| 1%  DPET=     0  DPR= 0.0  pDPS=  3894  TickCount=214  MissTick=0.0%  Tick=3041|6|4027  CritTick=7114|19|9125|59.4%  UpTime=69.5%
    combustion               Count=  4.1| 85.14sec  DPE=      0| 0%  DPET=     0  DPR= 0.0  pDPS=     0
    conflagration_dot        Count= 95.3|  2.98sec  DPE=   3207| 0%  DPET=     0  DPR= 0.0  pDPS=  1016  TickCount=137  MissTick=0.0%  Tick=2229|1|2875  UpTime=90.1%
    conflagration_explosion  Count= 29.9|  9.68sec  DPE=  34699| 1%  DPET=     0  DPR= 0.0  pDPS=  3462  Miss=0.00%  Hit=19686|18486|25880  Crit=45352|38080|58644|58.5%
    deadly_grace             Count= 24.3|  4.77sec  DPE= 196074| 4%  DPET=     0  DPR= 0.0  pDPS= 16158  Miss=0.00%  Hit=99594|83970|117558  Crit=232821|167940|258628|72.4%
    dragons_breath           Count= 14.9| 20.80sec  DPE= 577311| 8%  DPET=447424  DPR=13.1  pDPS= 28692  Miss=0.00%  Crit=577315|486553|749291|100.0%
    fire_blast               Count= 27.7| 10.99sec  DPE= 244110| 6%  DPET=     0  DPR=22.2  pDPS= 22538  Miss=0.00%  Crit=244109|193064|297319|100.0%
    fireball                 Count= 95.5|  2.98sec  DPE= 176495|16%  DPET=104422  DPR= 8.0  pDPS= 56082  Miss=0.00%  Hit=107310|102981|144173  Crit=226979|212140|326696|58.0%
    ignite                   Count=208.8|  1.45sec  DPE=  99864|19%  DPET=     0  DPR= 0.0  pDPS= 69587  TickCount=299  MissTick=0.0%  Tick=69657|4236|225384  UpTime=99.6%
    maddening_whispers       Count=  2.1|172.04sec  DPE=1678735| 3%  DPET=     0  DPR= 0.0  pDPS= 11914  Miss=0.00%  Hit=682518|681153|953614  Crit=1911622|1362306|2097951|81.1%
    phoenix_reborn           Count= 24.9| 11.70sec  DPE=  38566| 1%  DPET=     0  DPR= 0.0  pDPS=  3206  Miss=0.00%  Hit=21877|20538|28754  Crit=50373|42309|65156|58.6%
    phoenixs_flames          Count= 13.9| 22.37sec  DPE= 479102| 6%  DPET=379128  DPR= 0.0  pDPS= 22194  Miss=0.00%  Crit=479608|321128|494537|100.0%
    phoenixs_flames_splash   Count= 13.9| 22.38sec  DPE=      0| 0%  DPET=     0  DPR= 0.0  pDPS=     0
    potion                   Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=     0  DPR= 0.0  pDPS=     0
    pyroblast                Count= 70.9|  4.23sec  DPE= 463907|31%  DPET=363526  DPR=16.6  pDPS=109872  Miss=0.00%  Hit=234179|214274|299983  Crit=574865|441404|679762|65.7%
    rune_of_power            Count=  8.3| 39.99sec  DPE=      0| 0%  DPET=     0  DPR= 0.0  pDPS=     0
    scorch                   Count=  0.8| 67.97sec  DPE=  87786| 0%  DPET= 65966  DPR= 8.0  pDPS=   234  Miss=0.00%  Crit=87783|58389|89919|100.0%
    volatile_ichor           Count= 13.4| 21.71sec  DPE= 242815| 3%  DPET=     0  DPR= 0.0  pDPS= 10853  Miss=0.00%  Hit=141189|132669|185737  Crit=316072|265338|408621|58.6%
  Constant Buffs: defiled_augmentation/flask_of_the_whispered_pact/the_hungry_magister
  Dynamic Buffs:
    bloodlust              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.57%  benefit=39%
    combustion             : start= 4.1 refresh=  0.0 interval= 85.1 trigger= 85.1 uptime=13.22%  benefit=89%
    enhanced_pyrotechnics  : start=27.0 refresh= 13.1 interval= 10.5 trigger=  7.0 uptime=39.42%  benefit=41%
    heating_up             : start=84.2 refresh=  0.0 interval=  3.6 trigger=  3.6 uptime=37.05%  benefit=46%
    hot_streak             : start=71.2 refresh=  0.0 interval=  4.2 trigger=  4.2 uptime=20.20%  benefit=99%
    maddening_whispers     : start= 2.2 refresh=  0.0 interval=169.7 trigger=169.7 uptime= 6.86%  benefit= 7%
    potion_of_deadly_grace : start= 2.0 refresh=  0.0 interval= 84.7 trigger=  0.0 uptime=16.29%  benefit=16%
    pyretic_incantation    : start=44.8 refresh=114.9 interval=  6.7 trigger=  1.9 uptime=68.49%
    rune_of_power          : start= 8.3 refresh=  0.0 interval= 40.0 trigger= 40.0 uptime=26.73%  benefit=27%
  Procs:
     84.2 |   3.58sec : Heating Up generated
     12.5 |  21.58sec : Heating Up removed
     25.2 |  11.99sec : IB conversions of HU
     71.2 |   4.23sec : Total Hot Streak procs
    224.4 |   1.34sec : Hot Streak spells used
    159.7 |   1.88sec : Hot Streak spell crits
      4.3 |  51.25sec : Wasted Hot Streak spell crits
      1.0 |   0.00sec : Direct Ignite applications
      1.0 |   0.00sec : Ignites spread
  Gains:
    4955383.8 : mp5_regen (mana)
  Scale Factors:
    Weights :  Int=9.38(0.32)  SP=0.00(0.00)  Crit=8.50(0.32)  Haste=9.57(0.32)  Mastery=6.76(0.32)  Vers=7.25(0.32)
    Wowhead : 
  Waiting: 0.00%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|86075518  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.82%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.80%  benefit=12%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.93%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.30%  benefit=11%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.52%  benefit=12%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.41%  benefit=10%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.61%  benefit=10%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.25%  benefit=13%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 6.77%  benefit= 7%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 3.61%  benefit= 4%
    maddening_whispers       : start= 2.2 refresh= 19.6 interval=169.8 trigger= 10.5 uptime= 6.52%  benefit= 7%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
    All players active 100% of the time.

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10003
  TotalEvents   = 26176651
  MaxEventQueue = 56
  TargetHealth  = 86075518
  SimSeconds    = 3006143
  CpuSeconds    = 10.188
  WallSeconds   = 3.197
  SpeedUp       = 295082
  EndTime       = 2017-01-25 13:30:36+0100 (1485347436)

Scale Factors:
  Kalanya  Int=9.38(0.32)  SP=0.00(0.00)  Crit=8.50(0.32)  Haste=9.57(0.32)  Mastery=6.76(0.32)  Vers=7.25(0.32)

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Frostedmages** [comment]
This is more of an issue with interpreting results than the sim itself as far as I know. Closing.
