### ISSUE TITLE
Simcraft crashing straight away

### ISSUE THREAD

**Issue by ESRBViolence** [simulationcraft/simc#3465]
Please include a brief overview of the issue in the title above, as well as completing the following:

I go to launch SimCraft and it first tells me "We have reset your configuration settings due to major changes to the GUI". I have never used SimCraft before but it always tells me this. I hit OK and it launches SimCraft and after 2-3 seconds, it stops responding and closes with no error messages.

#### Simulationcraft Version
Simcraft 7.1.5, release 1 (newest release as of 26/01/2017). I have also tried the release 2 option from the "builds every few days here" hyperlink on their website.
#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
http://pastebin.com/qYiUXijQ
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
Unable to do so as the file doesn't exist as I can't even get to simulate anything.
#### Reproduction Steps:
Open SimCraft.
Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/wiki/CommonIssues

Try the third option on this page.

**Comment by ESRBViolence** [comment]
I don't suppose you know what I need to put in as the variable value? It doesn't seem to say, it just tells me to enter the name.

**Comment by Collisionc** [comment]
Set the variable to 
software

**Comment by ESRBViolence** [comment]
Ahhh, software worked perfectly, thank you very much :D

**Comment by Collisionc** [comment]
Glad to hear it!
