### ISSUE TITLE
Claw of the Crystalline Scorpid ignoring armor in error

### ISSUE THREAD

**Issue by Thordros** [simulationcraft/simc#3466]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

SimulationCraft 715-02 for World of Warcraft 7.1.5 Live (wow build level 23360, git build a181c58)

#### simc_gui.simc file or contents

http://pastebin.com/H6Zc1zKX

#### Reproduction Steps:

[This log](https://www.warcraftlogs.com/reports/68a3Apf7zkHyJQLY/#type=damage-done&source=1) is two hours of fighting a target dummy using a simplified rotation, with an ilvl 875 Claw of the Crystalline Scorpid equipped.

You can see from the log that the trinket's effect will always hit for either 92,978 or 92,979, and always crit for either 185,956 or 185,957. However, the simulation always has the trinket hit for the value listed in the tooltip (136,687).

[This commit](https://github.com/simulationcraft/simc/commit/4663516b478f7558769cf60e35938fa9d0be4a34) from two days ago added Claw of the Crystalline Scorpid to an exception list of trinkets that ignore armor. This isn't correct based on my testing in-game.

**Comment by Collisionc** [comment]
Yeah I meant to revert that, thanks.
