### ISSUE TITLE
Override option "outside=0" does not seem to work on copy

### ISSUE THREAD

**Issue by cont1nuity** [simulationcraft/simc#3470]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
 715-01-win64 Release

#### simc_gui.simc file or contents
http://pastebin.com/V9S2f0qu

#### Reproduction Steps:
Configure override: outside=0
Profile: http://pastebin.com/6rZEX1BC

#### Result :
The versatility values for the copies "*Neck" differ from what I would get by using the profile without copy: http://pastebin.com/19bNjsBk - it seems that the Sylvan Maelstrom Amulet outdoor effect for additional versatility is used when using the "copy" functionality. The "outside" option was added for Issue #3365

**Comment by Collisionc** [comment]
Should be fixed now .

**Comment by cont1nuity** [comment]
Working fine on the latest nightly build for me. Thank you!
