### ISSUE TITLE
Stat Scaling Option Issue

### ISSUE THREAD

**Issue by Neolina1512** [simulationcraft/simc#3472]
715-01 Simulationcraft Version

I have the Stat Scaling option checked but SimC will not let me choose which stats to scale and therefore won't give me a pawn string.

![simc options scale capture](https://cloud.githubusercontent.com/assets/25397357/22393686/4331eab6-e4d1-11e6-861e-78823ad6ade0.JPG)

**Comment by Collisionc** [comment]
Click the maximize button

**Comment by Neolina1512** [comment]
thanks!!! I feel silly now...
