### ISSUE TITLE
[Warrior] Recent Arms APL changes introduced operator precedence errors?

### ISSUE THREAD

**Issue by sparkcoil** [simulationcraft/simc#3474]
These two issues are both related to the precedence of the ! (TOK_NOT) operator.  According to engine/sim/sc_expressions.cpp this unary operator has very high precidence, so will bind to the token immediately to its right and not to an expression (unless that expression is itself in parentheses).

First issue:

`actions+=/battle_cry,if=gcd.remains<0.25&cooldown.avatar.remains>=10&(buff.shattered_defenses.up|cooldown.warbreaker.remains>7&cooldown.colossus_smash.remains>7|cooldown.colossus_smash.remains&debuff.colossus_smash.remains>gcd)|!cooldown.colossus_smash.remains<gcd|target.time_to_die<=7`

The sub-expression `!cooldown.colossus_smash.remains<gcd` will parse as `(!cooldown.colossus_smash.remains)<gcd`, which means that a boolean is being compared against a numeric value.

Second issue:

`actions.single+=/mortal_strike,if=cooldown.battle_cry.remains>8|!buff.battle_cry.remains>(gcd.max*2)&buff.focused_rage.stack<3|buff.battle_cry.remains<=gcd`

The sub-expression `!buff.battle_cry.remains>(gcd.max*2)` will parse as `(!buff.battle_cry.remains)>(gcd.max*2)`, again comparing a boolean against a numeric value.

**Comment by Collisionc** [comment]
I'm trying to figure out what sarri was thinking when he made those lines, and I really can't, but removing the offending parts only reduces the dps by 100~ or so.
