### ISSUE TITLE
Engineering helm use issue

### ISSUE THREAD

**Issue by cuj0cless** [simulationcraft/simc#3479]
The on use action of the new engineering helms (Head Shot) shares a Cooldown with action potions in game. This means it can only be used once per combat and that you can't use anymore potions during the fight. When I sim with this helm equipped, it is casting it multiple times during combat (around 7-8 per 450sec) as well as still using the second potion. This inflated my dps by almost 10,000

SimC version 715-02

This is the text from my most recent simulation

head_shot        Count=  8.0| 60.50sec  DPE=365800| 1%  DPET=     0  DPR=   0.0  pDPS=  6501  Miss=0.00%  Hit=299587|275018|360274  Crit=604832|550037|720548|22.3%

**Comment by cuj0cless** [comment]
Also this is my first time opening an issue, sorry if i left anything out

**Comment by navv1234** [comment]
I think most class module default APLs now default to not using engineering add-ons because of issues like this. Closing for now, if this is still an issue please reply.
