### ISSUE TITLE
Infinite Loop in Report Generation (Fury War / HelterSkelter)

### ISSUE THREAD

**Issue by seriallos** [simulationcraft/simc#3480]
There appears to be some kind of infinite loop in very specific setups in the current legion-dev branch (git hash cfc935c)

I have examples of a specific Fury Warrior which hangs during the HTML report generation.

Example of the hang: https://raidbots.com/simbot/report/HJvQQPnDx

It appears to be the combination of that fury war and the helter skelter fight that cause the error. The following variations do not have any issue:

Same fury war with gear compare on patchwerk: https://raidbots.com/simbot/report/SJqFXPhPx
Same fury war with gear compare on HecticAddCleave: https://raidbots.com/simbot/report/rJN1Ev3we
Feral druid with gear compare on HelterSkelter: https://raidbots.com/simbot/report/SkftrPhDx

**Comment by Collisionc** [comment]
Ok, should be fixed - https://github.com/simulationcraft/simc/commit/df22a0efb56a2dae56bf8118dff9afc19b2e2a81
