### ISSUE TITLE
Simulation Craft Crash on start-up (windows 7 64)

### ISSUE THREAD

**Issue by Lucifherus** [simulationcraft/simc#3481]
Hello, I have an issue about crashing on start-up whit Sim craft , only the lastes version, ( 71.5. release 1) I already tried to use 64 bit and 32 bit, already tried to use zip file and autoinxtalling files...
Here my dxdiag and msinfo files.
[DxDiag.txt](https://github.com/simulationcraft/simc/files/739018/DxDiag.txt)
[msinfo.txt](https://github.com/simulationcraft/simc/files/739019/msinfo.txt)

Please let me know how to fix this, I heard about run  the program from a virtual machine, but I have not idea what is it!
Thank you . best regards

**Comment by Collisionc** [comment]
Most likely the third option here will help you - https://github.com/simulationcraft/simc/wiki/CommonIssues

**Comment by Lucifherus** [comment]
Thx you for your fast answer.
IT WORKS NOW!
THANK YOU SO MUCH!

**Comment by Collisionc** [comment]
Glad to hear!
