### ISSUE TITLE
[SV Hunter] Steel Trap duration and Initial Tick

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3487]
After some Ingame testing
Steel Trap results in 38 seconds and 20 ticks
Means there is an initial tick and the duration on Tooltip+SimC is wrong

**Comment by nuoHep** [comment]
So... it does not actually have an initial tick.

https://gist.github.com/nuoHep/c59a3f61b1a2f1d058984e9fffaefccc
As you can see in both cases the trap lasts for ~39 seconds (AURA_APPLIED -> AURA_REMOVED), 9 extra seconds which give 4 full and 1 partial tick (the last one). 
Now, the funny thing is the AURA_REFRESHED event right after AURA_APPLIED which perfectly explains all of this. It triggers "pandemic" right after dot application which extends the duration by 30% giving us our extra 9 seconds (30 * .3).

I'll implement it in simc some time later today (eu time).

**Comment by nuoHep** [comment]
Merged
