### ISSUE TITLE
Rogue Wound Poison damage incorrect

### ISSUE THREAD

**Issue by antonychan11** [simulationcraft/simc#3490]
[simc_report.txt](https://github.com/simulationcraft/simc/files/746865/simc_report.txt)
It seems that Wound Poison when used in Simc, the damage is much lower than what it does in live server.

I would like this to work because Wound poison seems to do higher DPS than Deadly in signal target fight while using Alacrity talent. Proving it in Simc would be great.

Wound poison damage should be around 25~28% during my dummy testing.

**Comment by aethys256** [comment]
Fixed some weeks ago.
