### ISSUE TITLE
Magistrike Restraints

### ISSUE THREAD

**Issue by nasirabtw** [simulationcraft/simc#3494]
http://www.wowhead.com/item=132407/magistrike-restraints

Was never coded because I don't know how to handle target vector stuff.

The chaos bolt fired has a different spell id but functions the same. It applies eradication on impact.

http://www.wowhead.com/spell=213229/chaos-bolt

**Comment by Collisionc** [comment]
You'll probably wanna check that, but it looks like it works ok to me.
