### ISSUE TITLE
Algorithmic Bug on Arcane Mage without talent Charged Up

### ISSUE THREAD

**Issue by 5joono** [simulationcraft/simc#3495]
This problem occurred on 715-02(x64) version.
If I don't use talent Charged Up, simc doesn't use evocation forever....
Perhaps the Action Priority list should be modified like this:

actions.burn+=/arcane_barrage,if=(equipped.132451&cooldown.charged_up.remains=0&mana.pct<(100-(buff.arcane_charge.stack*0.03)))

=>

actions.burn+=/arcane_barrage,if=(talent.charged_up.enabled&equipped.132451&cooldown.charged_up.remains=0&mana.pct<(100-(buff.arcane_charge.stack*0.03)))

**Comment by Frostedmages** [comment]
Your SimC is out of date, this was fixed awhile ago. Be sure to grab the most recent nightly from downloads.simulationcraft.org
