### ISSUE TITLE
Fury DPS bug!??

### ISSUE THREAD

**Issue by Elandrielle** [simulationcraft/simc#3496]
I tried to sim my char with the last official build from the "Downloads" page.
It was about 735k DPS.
Today I tried the "newest" build.
It was about 686k DPS.
49k missing, without any hotfix!?
Please tell me, what i do wrong.

**Comment by Collisionc** [comment]
Can you link your armory? It's probably an item.  Since the last official build they nerfed draught fairly significantly for Fury, since it's now on the GCD.

**Comment by Elandrielle** [comment]
http://eu.battle.net/wow/de/character/thrall/Elandrielle/simple

I don´t got draught. Don´t know which item could be abt 50k

**Comment by Collisionc** [comment]
Looks like an action list change I made was a dps decrease for your character but not other characters. I'll see if I can fix it.

**Comment by Elandrielle** [comment]
Thx a lot

**Comment by Elandrielle** [comment]
With the newest build
"SimulationCraft 715-02
for World of Warcraft 7.1.5 Live (wow build level 23360, git build cf18572)"
It´s 705k with 54 Traits now.
Still ober 30k missing.
Hope you can fix it :)

**Comment by Collisionc** [comment]
This is fixed in the newest update, and it should actually be a little bit higher than before.
