### ISSUE TITLE
Custom On Use Damage not working.

### ISSUE THREAD

**Issue by Bunnychaser999** [simulationcraft/simc#3498]
When adding a custom on-use to a trinket for dps purposes, (Attempting to simulate Archimonde's Hatred Reborn) simc throws off an error stating;
"Baseline no buff or action found for effect '' on item 'custom_trinket'
Unable to initialize item 'custom_trinket' on player 'Baseline'
Simulation has been canceled during player setup! (thread=0)                     
Player Baseline has 'use_item' action with no custom buff or action setup."

The attempted added lines were: 
trinket1=custom_trinket,stats=2994agi_685vers_685mastery,use=1462500Fire_75cd
actions+=/use_item,slot=trinket1

I tried the following aswell;
trinket1=custom_trinket,use=1462500Fire_75cd
trinket1=custom_trinket,use=1462500physical_75cd
actions+=/use_item,name=custom_trinket

Simc Version 7.1.5-2

simc_gui.simc file: https://hastebin.com/ucejefages.makefile

**Comment by navv1234** [comment]
This is a (long standing) known issue, when we transitioned to a system where special effects can be automatically deduced from Wow client data in some cases. I have something locally that will bring back this functionality, but I need to look into some related things before I add it.

**Comment by navv1234** [comment]
This should be now fixed, as of a34d0bf49.
