### ISSUE TITLE
Crashing while region change

### ISSUE THREAD

**Issue by Clayn083** [simulationcraft/simc#3501]
Hello,

I've never used simcraft before but downloaded the newest version (715-01) for win 64bit to get an indepth look on my character. My problem is I'm not even able to simulate a character, since the program is always crashing when I change the region from US  to EU. I'm also using the simcraft addon which offers me ingame this big wall of text I can simply copy & paste into the simulation window. While doing this without changing the region, the program crashes when the simulation hits 100%. Importing a character isn't possible, too, due to the not doable regionchange. I have absolutely no clue what is going wrong there because it seems to work well for everyone except me and I haven't found someone with the same problem like me. Maybe u have an idea on how to fix this?

**Comment by schaefer-dev** [comment]
I have exactly the same issue right now!

**Comment by havoccc** [comment]
![capture](https://cloud.githubusercontent.com/assets/25767526/22926020/cecb4430-f2a2-11e6-9741-9c8fc60b315f.JPG)
I also have this problem and I find it does it when trying to import from battlenet.  I have tried disabling the antivirus too and still no joy :(
