### ISSUE TITLE
Blood Thirsty insticts

### ISSUE THREAD

**Issue by Runaria1** [simulationcraft/simc#3504]
Please include a brief overview of the issue in the title above, as well as completing the following:
The trinked blood Thristy instincts is not given the correct proc value on the current version of simcraft it shows the proc amount of 5.3k on the Mythic 880 version aswell as a 4.3k proc amount on the 865 version
The mythic one Procs for amount of 3.2k and the normal has a proc of 3k. Thus greatly affecting how good the trinket really is

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by nuoHep** [comment]
Where do you see it?
It gives the correct value as far as I can tell
```
2.092 Hunter_Survival_T19M_NH attempts to proc blood_frenzy type=equip source=item driver=221786 trigger=221796 stat=Haste amount=0 duration=10 proc_chance=101% rppm=3 on serpent_sting: 1
2.092 Hunter_Survival_T19M_NH gains blood_frenzy_1 ( value=-0.00 )
2.092 Hunter_Survival_T19M_NH gains 3223.30 haste_rating (temporary)
```
(mythic version)

**Comment by Zuliane** [comment]
It's just a tooltip issue while mouseovering the proc. See: http://imgur.com/a/VvDGR (890 version)
