### ISSUE TITLE
Kil Jaedens Burning Wish Not being used or tracked in sim

### ISSUE THREAD

**Issue by Wolfy2032** [simulationcraft/simc#3505]
For some reason when I sim my Dh using the new kil jaedens burning wish it isnt using the on use ability. If it is its not being listed on the damage sources.

**Comment by lgkern** [comment]
Are you using a custom Action Priority List or the default one? If you're using your own APL, you need to add a use for it manually, otherwise it should handle the usage for it automatically.

**Comment by Wolfy2032** [comment]
I am not using a custom

**Comment by N1gh7h4wk** [comment]
How did you import the toon with the trinket? via armory or addon?

**Comment by Wolfy2032** [comment]
Used the simcraft addons in game to copy and paste the gear after importing
the armory

**Comment by lgkern** [comment]
Can you link your armory so we can try to reproduce it?

**Comment by Wolfy2032** [comment]
On my phone right now but i am glaiveheart from zuljin us

**Comment by EvanMichaels** [comment]
Default APL definitely has support for KJBW so it should be getting used if you import from the armory or use the addon. I have tested this as I have the trinket myself.

**Comment by Wolfy2032** [comment]
it started working today
