### ISSUE TITLE
HPS Guardian wtf?

### ISSUE THREAD

**Issue by serrufs** [simulationcraft/simc#3509]
715-02 what HPS Guardian?

http://jpegshare.net/images/19/01/1901ed1c2a538e90fe8e406d02fbc452.jpg

**Comment by lgkern** [comment]
Please provide  more details on what you were doing.

Most tank specs are not currently supported by anyone, so all info you might gather from tank spec sims might be wrong.

**Comment by serrufs** [comment]
Nothing special I do not. Simply import from the World of Warcraft using the addon. And inserted into the data simulationcraft. HPS no longer properly be considered, after I updated  from 710-03 to 715-02.
