### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Kezedj** [simulationcraft/simc#3510]
Hi,
I found no other place to ask the following question, as http://simulationcraft.org/ bug report link drove me here immediately. How efficient is SimC for previous versions of WoW? I'm currently playing on a private server (WotLK, 3.3.5), and I'd love to do some theorycrafting, but I'd like to know beforehand if SimC is suited for that version of the game.
Thanks very much in advance,

**Comment by Zarggg** [comment]
SimC is developed for the current and PTR versions of WoW. Do not expect results to match those on unauthorized servers or versions of the game client.

**Comment by Kezedj** [comment]
Ok, thanks for the quick answer man :-)

**Comment by Frostedmages** [comment]
There are old versions of SimC cached on the downloads.simulationcraft.org page. Additionally the commits go back to the start of things I think? You could probably grab one of those old versions or checkout and build from a super old commit if you really wanted to.

**Comment by lgkern** [comment]
As Frosted mentioned, you can dig in the commits (https://github.com/simulationcraft/simc/commits/master) back to before Cataclysm data started getting pulled in. Don't expect it to be correct and/or to be fixed and/or supported if anything is broken, however.
