### ISSUE TITLE
PALA [Holy] is using an unsupported spec

### ISSUE THREAD

**Issue by Mohlinger** [simulationcraft/simc#3511]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 7.1.5, release 1

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
No funktion!
------------------------------------------------------------------------------------------------------
#### Errormasages:

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: http://eu.battle.net/wow/en/character/arthas/Mohlinger/advanced

# Mohlinger is using an unsupported spec.
# Paladin holy healing for player Mohlinger is not currently supported.
# No active players in sim!

!!! Retro Spec runs fine !!!

------------------------------------------------------------------------------------------------------
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: https://worldofwarcraft.com/en-gb/search?q=Mohlinger

# Unable to determine Server and Character information!

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

-------------------------------------------------------------------------------------------

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Zarggg** [comment]
None of the healing specs are supported because no one has come forward to develop them.

**Comment by lgkern** [comment]
As Zarggg and the error said

> Paladin holy healing is not currently supported.

Since no one steps up to implement/maintain it.
