### ISSUE TITLE
Distance override does not work

### ISSUE THREAD

**Issue by vituscze** [simulationcraft/simc#3513]
Profile:

```
mage=test
spec=frost
level=110

actions.precombat=water_elemental
actions.precombat+=/snapshot_stats
actions=frostbolt

distance=10
```

`base.distance` is set to 10 before `mage_t::init_base_stats` is called (which sets it to 30, undoing the effect of `distance=10`).

**Comment by Collisionc** [comment]
Ok, should work better now.
