### ISSUE TITLE
Havoc Demonhunter simulation is/seems incorrect

### ISSUE THREAD

**Issue by NostalgiaX** [simulationcraft/simc#3515]
Simulationcraft Version : 7.1.5 -01

Was running a simulation on my havoc demonhunter, and noticed some strange things. First of all, under resources, it sees my max fury as being 110, though it is 130. This is an import error, but don't know why it happens. 

Secondly, I find it hard to understand that Fel rush should be used, it moves you out of position, and does less damage than throwglaive (atleast without fel mastery talent) (https://gyazo.com/6c1c161734ca0dd116a397214def2b03).

Thirdly and lastly (this might be due to half baked knowledge!), I have the Draught of souls item, but as seen in above screenshot, it tells me to use it after I have used potion of the old war. Now, I don't know if draught is counted as a melee ability, but if it is not, then would it not be wiser to stall it untill old war is done?

Regards - NostalgiaX (same name in-game on Kazzak)

**Comment by EvanMichaels** [comment]
Fel Rush should do more damage than Throw Glaive, even without Fel Mastery. Additionally, Fel Rush has a smaller than normal GCD so the opportunity cost is lower even if it moves you slightly out of position. 

Given that Old War is RPPM, I don't think DoS should really affect it in any meaningful way even if it didn't proc, especially since you melee during the DoS channel.

Not sure what the issue with the 110 max Fury is though. Will take a look.

**Comment by NostalgiaX** [comment]
> Fel Rush should do more damage than Throw Glaive, even without Fel Mastery. Additionally, Fel Rush has a smaller than normal GCD so the opportunity cost is lower even if it moves you slightly out of position.

Just tested in-game, and you are correct. My original comment was based on Fel Rush tooltip saying 152k dmg, and throwglaive 192k. Guess it has a difference whether it's chaos or physical damage.

About the DoS, I don't know, you might be right. I only figgured it would be an issue, since using DoS prevents you from using, say, Chaos Strike, and therefore only have your auto attacks to rely on.

**Comment by EvanMichaels** [comment]
Yes, Throw Glaive is reduced by armor while Fel Rush is not, so the actual values will be lower when used on a target.
