### ISSUE TITLE
Kil'jaeden's Burning Wish defaults to lining up with dps cooldowns

### ISSUE THREAD

**Issue by You-Too** [simulationcraft/simc#3518]
Simulationcraft version: simc-715-02-win64-5674e80
Item: http://www.wowhead.com/item=144259/kiljaedens-burning-wish

The issue is with how Simc defaults to line up the trinket active with dps cooldowns.
In the game, the active ability on the trinket will do the same damage no matter if you have a dps cooldown buff or not. Apparently it doesn't scale or get buffed by anything. It just hits for the same amount every time. (Some more reports of this from wowhead users on that page)

In my case (retribution paladin) when imported into Simc the action will look like this:
actions+=/use_item,name=kiljaedens_burning_wish,if=(buff.avenging_wrath.up|buff.crusade.up)
This will give me a result of 581344 dps with the trinket's active doing 1.5% of dps at 50 000 iterations.

If I change that line to:
actions+=/use_item,name=kiljaedens_burning_wish
It will result in 585492 dps with the trinket's active doing 2.1% of dps at 50 000 iterations.

I haven't tried it with other classes but it's worth looking into. If it always hits for the same amount, it should just be used on cooldown, maybe except in certain add AoE situations.

**Comment by EvanMichaels** [comment]
Yeah KJBW only benefits from target debuffs, so personal damage buffs won't do anything.
