### ISSUE TITLE
Cinidaria legendary not triggering off of Blade flurry

### ISSUE THREAD

**Issue by Loktark** [simulationcraft/simc#3520]
Please include a brief overview of the issue in the title above, as well as completing the following:

Blade flurry is not triggering the increased damage from cinidaria against targets above 90% life in the simulation. Blade flurry does trigger this damage during in game testing.

#### Reproduction Steps:

This issue can be easily replicated by running a multi target simulation as outlaw with cinidaria equipped.

**Comment by mrdmnd** [comment]
@Aethys256 - I think this could potentially be related to the issue we fixed a while back with delayed execute on blade flurry not counting mastery right.

**Comment by navv1234** [comment]
This has really nothing to do with Blade Flurry, but rather how we treat "procs" in general. As it stands, this specific case (Cinidaria) needs a different kind of implementation in the simulator, that bypasses some of the restrictions we have set on things that can proc from other things.

I have a ballpark idea in my head on what to do, but I need to find time to do it.

**Comment by navv1234** [comment]
Fixed in c2bf39897, though individual spells that are not supposed to proc it may need to be blacklisted still.
