### ISSUE TITLE
Speed of simmin.

### ISSUE THREAD

**Issue by Bupkiss** [simulationcraft/simc#3523]
Everything I'm reading says simming should be done in a very short amount of time. Apparently not for me. It takes anywhere from 10-20 minutes to finish. Any recommendations?

While my rig is definately not state of the art it is more than enough to handle WoW and run multiple applications on my second screen. Just wanna know if there is something I'm missing.

Thanks!

**Comment by NostalgiaX** [comment]
In the options menu you can chose how big of a priority that Simulcraft has, in other words, how much power it can take from the system, maybe take a look at that. Also, enabling scaling plots increases the simulation time drastically, so if that is on, consider turning it off. That's the only thing I can think of.

**Comment by Collisionc** [comment]
What are your system specs and what are you simulating?
