### ISSUE TITLE
SV Hunter: Aspect of the Skylord seems to be adding 0% damage

### ISSUE THREAD

**Issue by ZeroStride** [simulationcraft/simc#3526]
Aspect of the Skylord should add 30% damage however the generated spell data seems to indicate it will add 0% damage

`{ "Aspect of the Skylord"             , 203927, 0x0000000000000000, 0.000000, 1, 0x000, 0x000, 0, 0, 0, 0, 0.000000, 0.000000,       0, 0, 0, 0, 0,    0, 10000, 0, 0, 0, 0, 0, 0.000000, 0, 0, 0, 0, 0, 0, 0, 0,      0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0 }, 0, 0x00000000,  0,     0, "Increases damage dealt by $m1%.", "Increases damage dealt by $m1%.", 0, 0, 0, 0, 0, 0 }`

#### Simulationcraft Version
HEAD

**Comment by nuoHep** [comment]
Running a simple spell query shows
```
$ ./simc64 spell_query=spell.id=203927
SimulationCraft 715-02 for World of Warcraft 7.1.5 Live (wow build 23360)

Name             : Aspect of the Skylord (id=203927)
School           : Physical
Duration         : 10 seconds
Triggered by     : Aspect of the Skylord (203755)
Attributes       : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
Effects          :
#1 (id=300916)   : Apply Aura (6) | Modify Damage Done% (79)
                   Base Value: 30 | Scaled Value: 30 | Misc Value: 0x7f | Target: Self(1)
Description      : Increases damage dealt by $m1%.
Tooltip          : Increases damage dealt by $m1%.
```
I'm not even sure how you concluded the 0% from the quote (considering that most of the spell numbers are usually in the effects).

**Comment by ZeroStride** [comment]
This was an incorrect bug report.
