### ISSUE TITLE
Survival: Frizzo fingertrap

### ISSUE THREAD

**Issue by mick19955** [simulationcraft/simc#3527]
Frizzo  doesnt spread a copy of lacerate to another target, but rather applies a new fresh lacerate

**Comment by nuoHep** [comment]
> Frizzo reapplies lacerate to a random target, if all targets hit already got lacerate debuff.

-ENOPARSE

> Frizzo also doesnt spread a copy of lacerate to another target, but rather applies a new fresh lacerate

Will check

> The if case i believe should be omitted, since it checks if there are more than 1 target available, but frizzo got uses on single target due to its ability to refresh lacerate on single target

This is already taken care of in the else case ( https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_hunter.cpp#L4100 )

**Comment by mick19955** [comment]
Yeah, somehow managed to completely overlook the else case

**Comment by navv1234** [comment]
Fixed, I guess, closing.
