### ISSUE TITLE
SV Hunter: Aspect of the Skylord is a separate buff from Aspect of the Eagle in WoW client

### ISSUE THREAD

**Issue by ZeroStride** [simulationcraft/simc#3528]
Aspect of the Skylord is implemented in game as a separate buff (203927), so it should show up in the Dynamic Buffs as its own spell. Currently just Aspect of the Eagle is shown.

#### Simulationcraft Version
HEAD

**Comment by nuoHep** [comment]
But why? It has the same duration as AotE and is basically just an additional "effect" of it (which is modeled in simc)

**Comment by ZeroStride** [comment]
Yep, understood. Closing. Thanks again.
