### ISSUE TITLE
SimulationCraft crashing just before completing simulation

### ISSUE THREAD

**Issue by Sinister13Rain** [simulationcraft/simc#3529]
#### Simulationcraft Version 715-01

[DxDiag.txt](https://github.com/simulationcraft/simc/files/768391/DxDiag.txt)

[simc_gui.zip](https://github.com/simulationcraft/simc/files/768392/simc_gui.zip)

I used the addon as well. As the tittle suggests, I copy the text into the SimCraft, press simulate and I can see he does something and just about it finishes the program crashes. Tried all compatibility options and none work.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/wiki/CommonIssues

Option 1 is the answer, your dxdiag mentions LavasoftTcpService64.dll - this is a very common piece of malware that crashes simulationcraft's gui

**Comment by Sinister13Rain** [comment]
Thank you for your comment Collisionc, all I did was to remove Web-Companion then it worked.
