### ISSUE TITLE
Everytime i open Simc i get an error and the program crashes.

### ISSUE THREAD

**Issue by metlin123** [simulationcraft/simc#3530]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### If Simulationcraft is crashing, please include your dxdiag file - 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/768445/DxDiag.txt)

#### Reproduction Steps: I click on the client and "We have reset your configuration settings due to major changes to the GUI" text box shows up i click ok then the client opens and instantly crashes. Attached are 2 screens shops of the errors i get.
![error](https://cloud.githubusercontent.com/assets/25706905/22854341/6a632996-f03a-11e6-82bf-74d36b6cd7c8.PNG)
![error2](https://cloud.githubusercontent.com/assets/25706905/22854342/6a650ffe-f03a-11e6-9f7c-789a9017877d.PNG)

PLEASE HELP ME !!!

**Comment by Collisionc** [comment]
Option 3 here -  https://github.com/simulationcraft/simc/wiki/CommonIssues - should fix this.
