### ISSUE TITLE
[Survival Hunter] Aspect of the Eagle is still not providing its +20% Crit increase.

### ISSUE THREAD

**Issue by Archernick** [simulationcraft/simc#3532]
Please include a brief overview of the issue in the title above, as well as completing the following:

SimulationCraft 715-02 (wow build level 23360, git build c5c2d5d)

Sim without Convergence of Fates (8 casts of Aspect of the Eagle): http://pastebin.com/PCBgtDUU
Sim with Convergence of Fates (11 casts of Aspect of the Eagle): http://pastebin.com/v2pdCqPt

Reproduction Steps:

I believe this is meant to be fixed in last night's build, but it would appear as if it isn't. With both Call of the Wild, Convergence of Fate and Animal Instincts, I get another three casts of Aspect of the Eagle in a 450-second fight (Patchwerk - 25,000 iterations). However the number of crits between the sims of having it, and without are identical. Therefore I believe that the 20% crit bonus during Aspect of the Eagle is still not being factored into the sim correctly.

**Comment by Archernick** [comment]
If you need anymore information - let me know. Will answer asap.

**Comment by nuoHep** [comment]
It does?
```
2.411 Hunter_Survival_T19M_NH performs auto_attack_mh (100)
2.411 attack_t::build_table: miss=0.000 dodge=0.000 parry=0.000 glance=0.000 crit=0.186
3.029 Hunter_Survival_T19M_NH performs aspect_of_the_eagle (100)
3.029 Hunter_Survival_T19M_NH gains aspect_of_the_eagle_1 ( value=0.20 )
4.465 Hunter_Survival_T19M_NH performs auto_attack_mh (100)
4.465 attack_t::build_table: miss=0.000 dodge=0.000 parry=0.000 glance=0.000 crit=0.386
```

**Comment by nuoHep** [comment]
And even simming your profiles (without scale factors and with default combat length) gives
```mongoose_bite          Count=117.1|  2.54sec  DPE= 609478|36%  DPET=544196  DPR=    0.0  pDPS=238387  Miss=0.00%  Hit=451152|140656|925158  Crit=958751|281312|1850317|31.2%```
for the first one and
```mongoose_bite          Count=110.7|  2.68sec  DPE= 617913|35%  DPET=551491  DPR=    0.0  pDPS=228537  Miss=0.00%  Hit=451226|141404|929823  Crit=959535|282807|1859647|32.8%```
for the second one.
That's with target_error=.5 , so pretty reliable.

**Comment by Archernick** [comment]
Then why do I get 52 crits with Mongoose Bite between both sims, when one sim gives me 3 extra casts of Aspect of the Eagle? Surely I should see more crits?

**Comment by Archernick** [comment]
It's now believed that the 20% crit is applying, but there are other issues that are contributing to the strange results. So I'm closing this and will open other reports with the new-found issues. (thanks NuoHep for the discussions!)
