### ISSUE TITLE
Might of Krosus - Guaranteed Critical Strikes Not Working, Ret Module APL Optimization

### ISSUE THREAD

**Issue by Thordros** [simulationcraft/simc#3534]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 715-02 for World of Warcraft 7.1.5 Live (wow build level 23360, git build c5c2d5d)

#### simc_gui.simc file or contents
http://pastebin.com/b10Xnr27

#### Reproduction Steps:
There are two issues with Might of Krosus' current implementation:

1) Its on use effect should always be a critical strike, equal to the value listed in the tooltip (minus armor reduction, since it's physical damage). It currently is not working that way in the simulation. Here is a log of a Ret Paladin using the trinket on cooldown:

https://www.warcraftlogs.com/reports/8HktGF16rj39zTBa/#type=damage-done&view=analytical&source=2&fight=2

2) It is not optimized in the Retribution module's APL at the moment (by default, it's only activating during Crusade). This is tricky to optimize without the first issue being fixed. But it's certain that using Might of Krosus every 45s would be a massive improvement over waiting 2⅔x its cooldown. If I had to hazard a guess, ideal usage may look something like this:

`actions+=/use_item,name=might_of_krosus,if=(buff.avenging_wrath.up|buff.crusade.up&buff.crusade.stack>=15|cooldown.crusade.remains>5&!buff.crusade.up)`

But that's just a guess. Expressing things programmatically isn't really in my wheelhouse.

**Comment by Collisionc** [comment]
Ok, added that in, thanks.
