### ISSUE TITLE
Cant Simulate bcs new Legendarys are missing in this App!

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3539]
cant Simulate my DPS becaues i got a new legendary and it says he cant find this Item which i wear currently on my character

pls import the new legendarys !

**Comment by lgkern** [comment]
All legendaries should be working for all DPS classes. Please provide more details, like which legendary, which class/spec, how are you importing the item, etc.

**Comment by ghost** [comment]
My steps to simulate are:

 

Siimulation -> copy my stats from wow -> paste it in the simulation window -> press simluate -> result

anything wrong ?

 

PS: i sent a picture whit the current issue i have its the Legendary "Kil'Jaedens burning wish he couldnt finde on my mage

 

Gesendet: Montag, 13. Februar 2017 um 16:44 Uhr
Von: "Lucas Kern" <notifications@github.com>
An: simulationcraft/simc <simc@noreply.github.com>
Cc: iZantes <nyco@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [simulationcraft/simc] Cant Simulate bcs new Legendarys are missing in this App! (#3539)


All legendaries should be working for all DPS classes. Please provide more details, like which legendary, which class/spec, how are you importing the item, etc.

**Comment by ssateneth** [comment]
Find simc_gui.simc file (its located where simulationcraft.exe is located) and attach a copy here. Will be better able to find the problem then.

**Comment by lgkern** [comment]
(Attach the copy in the actual thread on Github.com and not on the email reply)

**Comment by navv1234** [comment]
As far as I know, all DPS legendaries have been implemented. Closing, if this is still an issue, need more information.
