### ISSUE TITLE
Sephuz's Secret not showing up as a buff with successful interrupts

### ISSUE THREAD

**Issue by xfrenzie** [simulationcraft/simc#3541]
#### Simulationcraft Version - 715-01

I am trying to simulate gaining the buff from Sephuz's Secret via interrupt during my sims.

I am getting successful interrupts but I am noticing that I am not seeing the buff appear in my sims.

I know i saw that the buff has been added the DPS profiles, but I can't seem to make it work.

**Comment by nuoHep** [comment]
What class(es)?

**Comment by xfrenzie** [comment]
Sorry, demon hunter.

**Comment by EvanMichaels** [comment]
This was fixed in the following commit: https://github.com/simulationcraft/simc/commit/7595449155279bfaee48a8a7656d4d7d1628ca36

If you run 715-02 it will be working. Thanks!
