### ISSUE TITLE
Error after attempting to simulate

### ISSUE THREAD

**Issue by Ntrz33** [simulationcraft/simc#3542]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
715-02

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/771307/DxDiag.txt)

gives the error: Unable to open output file 'C:/Program Files (x86)/simc-715-02-win64\simc_report.txt'

**Comment by scamille** [comment]
This is likely because SimulationCraft does not have sufficient permissions to write the output file (simc_report.txt) to C:/Program Files (x86)/simc-715-02-win64.

Please install SimC to a folder where you have write permissions, eg. C:/Users/<yourusername>/simc-715-02-win64.
