### ISSUE TITLE
[Druid][Balance] Starfall double haste-scaling

### ISSUE THREAD

**Issue by iPilot** [simulationcraft/simc#3543]
I've noticed overvalued haste on 10-target-run.

Source code doesn't contain any starfall duration dependings on players haste. Assuming that starfall it's a simple area effect like consecration is wrong.

Starfalls duration must decrease depending on players haste.

**Comment by Collisionc** [comment]
Does it update as haste changes, or is it static ?

**Comment by iPilot** [comment]
Assuming that starfall must be haste-independed it has to updates when haste changes. Guess it corresponding with moonfire and sunfire, but ticks are limited - always 9. So hard find proofs even using WCL - high interval dispersion about +-100 ms without any haste changes.

**Comment by Collisionc** [comment]
Ok, I'm pretty sure that I coded it like that, test the latest 710-02 downloads and let me know.
