### ISSUE TITLE
ROGUE - Assassination deadly poison 30% boss health!

### ISSUE THREAD

**Issue by Wunjuh** [simulationcraft/simc#3544]
To Aethys:
This is following our talk in discord about trying to see if applying deadly poison <30% boss health with zoldycks bracers would be a benefit, you suggested:

actions=apply_poison,lethal=deadly,if=target.health.pct<=30&!buff.deadly_poison.up
actions+=/call_action_list,name=cds

Which gave the error:

Player Wunju action apply_poison : Unable to decode expression function 'buff.deadly_poison.up'
Wunju-apply_poison: Unable to build expression tree from target.health.pct<=30&!buff.deadly_poison.up
Simulation has been canceled during player setup! (thread=0)
Player Wunju action apply_poison : Unable to decode expression function 'buff.deadly_poison.up'
Wunju-apply_poison: Unable to build expression tree from target.health.pct<=30&!buff.deadly_poison.up

**Comment by Mystler** [comment]
Since Agonizing Poison is gone and poison switching is unnecessary once again, I think this can be closed.
