### ISSUE TITLE
Simc Crashes when I try to import character

### ISSUE THREAD

**Issue by havoccc** [simulationcraft/simc#3546]
The game crashes and shows this message after I try to import a character by selecting US/EU or battlenet.
![capture](https://cloud.githubusercontent.com/assets/25767526/22937190/cc343754-f2cf-11e6-894f-feaaaeee3f43.JPG)

715-02

[DxDiag.txt](https://github.com/simulationcraft/simc/files/774613/DxDiag.txt)

I have tried using https://github.com/simulationcraft/simc/wiki/CommonIssues options 2 and 3 and still comes up with the message. Also I have tried disabling the antivirus.

**Comment by lgkern** [comment]
Which character? (region realm and name)

**Comment by havoccc** [comment]
Sorry if this was not clear, I can't import **any** character. As soon as I try an select from the US/EU dropdown it crashes, as soon as I try and log in to battlenet  page it crashes.  In fact I have found that trying to adjust any dropdown it crashes.

**Comment by lgkern** [comment]
Hmm, that's really weird. I assume you already tried re-downloading it and installing again? I've tried here on both the live version and the dev version and both are working fine for armory imports.

**Comment by havoccc** [comment]
I have tried a few different versions. Is there a particular one you can recommend?

**Comment by havoccc** [comment]
As soon as I touch that dropdown it stops working.
![capture](https://cloud.githubusercontent.com/assets/25767526/23029169/86a023ea-f461-11e6-8d18-feb380fc948e.JPG)

**Comment by havoccc** [comment]
This is a Microsoft message that appears:
_Files that help describe the problem:
  C:\AppData\Local\Temp\WER37AB.tmp.WERInternalMetadata.xml
  C:\AppData\Local\Temp\WER4350.tmp.appcompat.txt
  C:\AppData\Local\Temp\WER439F.tmp.mdmp

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt_

**Comment by lgkern** [comment]
Hey, please try to see if the same error occurs on 715-01? Trying to pin down a possible cause for it.

**Comment by havoccc** [comment]
yes it still happens on 715.01  from main page

**Comment by Collisionc** [comment]
Try solution #1 on the common issues page. Also, there is no appcrash or blue screen information in your dxdiag. 

Can you run this program - http://www.nirsoft.net/utils/app_crash_view.html - and find cases where simulationcraft.exe had an error, and copy/paste the contents of the crash here

**Comment by havoccc** [comment]
hi,
Thank you, this worked!
