### ISSUE TITLE
My computer gets frozen during the simulation.

### ISSUE THREAD

**Issue by noh626** [simulationcraft/simc#3548]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
715-01
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.
[simc_gui.zip](https://github.com/simulationcraft/simc/files/776207/simc_gui.zip)
[DxDiag.txt](https://github.com/simulationcraft/simc/files/776208/DxDiag.txt)

Thanks!

**Comment by lgkern** [comment]
the simc_gui you sent has no data on it, please re-upload it with the correct data
