### ISSUE TITLE
apply poison

### ISSUE THREAD

**Issue by schnello** [simulationcraft/simc#3549]
#### Simulationcraft Version
World of Warcraft 7.1.5 Live (wow build level 23360, git build cd36b8c)

#### simc_gui.simc file or contents
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=old_war
actions.precombat+=/marked_for_death,if=raid_event.adds.in>40

#### Reproduction Steps:

Hello.

I try to add in the apply_poison the type of the poison.
The Wiki say´s:
actions+=/apply_poison,main_hand=deadly,off_hand=deadly

I also tried:
actions.precombat+=/apply_poison,deadly
actions.precombat+=/apply_poison,name=deadly
actions+=/apply_poison,main_hand=deadly

I get only a error message like:  
Unable to parse options str 'deadly'
'name=deadly': apply_poison: Unexpected parameter 'name'.

etc.

Br,
Christian

**Comment by aethys256** [comment]
Use lethal= or nonlethal= instead.
