### ISSUE TITLE
Vary Length seems ignored ?

### ISSUE THREAD

**Issue by amdev74** [simulationcraft/simc#3550]
With simcraft 715-02 and simcraft 715-01

With my DH I put 240 sec in Globals -> Length and 0% to vary length because i don't want any variation ( variation add an extra meta and the final result become inconsistant )

But even if I put 0% vary length, the final graph at the end goes to 287sec and not 240sec

![simcraftbug](https://cloud.githubusercontent.com/assets/12050544/22966356/2a610dec-f362-11e6-81be-11da10548686.jpg)

**Comment by ssateneth** [comment]
Try adding fixed_time=1 to the overrides. Without it, simc has to guess what health to set the boss at. With it, boss health decreases at a predictable rate regardless of damage done and should exactly match your settings.

**Comment by amdev74** [comment]
It works ! thx.
