### ISSUE TITLE
[Death Knight] Hungering Rune Weapon

### ISSUE THREAD

**Issue by Demei** [simulationcraft/simc#3552]
Build 715-02 ea39c9d

I'm not clear whether Hungering Rune Weapon is implemented correctly. The spelldata (id=207127) suggests two Periodic Energize Power auras are applied by the buff: a rune refresh every 1.5 seconds, and 5 runic power every 1 second, so the expected gain in runes should be 11 runes (initial tick + 10 buff ticks) and 80 runic power (initial tick + 15 buff ticks).  This is consistent with in-game behaviour, though the tooltip (which indicates that the buff provides 5 runic power every 1.5 seconds) is wrong.

However, in every sim I've run, the number of rune refresh ticks is exactly equal to the number of runic power ticks, e.g.:

![rp_gain](https://cloud.githubusercontent.com/assets/25807573/23002884/12f812da-f3e5-11e6-8a83-1b7cc044e49a.png)

The gain in runic power is also lower than expected, being a total gain of approx. 55 runic power, i.e. as if the buff ticked only 10 times rather than 15 times.

Sample results using T19M_NH profile attached:
[results_html_hrw_160217.zip](https://github.com/simulationcraft/simc/files/778819/results_html_hrw_160217.zip)

**Comment by navv1234** [comment]
Yeah, we don't at the moment support a single "spell" (buff) having different tick times. I'll kludge this in somehow.

**Comment by navv1234** [comment]
See the commit message. The reality is more interesting than the theory, it seems.
