### ISSUE TITLE
[Druid] The damage reduction (not the reflect) from Rage of the Sleeper should be an absorb

### ISSUE THREAD

**Issue by Alpheus** [simulationcraft/simc#3554]
Currently implemented as pure mitigation in `druid_t::target_mitigation`. This has an effect on the healing done from frenzied regen.

**Comment by Alpheus** [comment]
Will look into it, just posted for clarity

**Comment by scamille** [comment]
Is this still a relevant problem in bfa?

**Comment by Jundarer** [comment]
Since Rage of the Sleeper has been removed (rip) this is now irrelevant.
