### ISSUE TITLE
Spell Data For Kiljaeden's Burning Wish Not Found When Importing

### ISSUE THREAD

**Issue by deltahalo014** [simulationcraft/simc#3556]
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Player Moocowd could not find spell data for action kiljaedens_burning_wish
# Simulation has been canceled during player setup! (thread=0)          

This is the error thats coming up every time I try to import character data to simulate

**Comment by Collisionc** [comment]
I'm not getting this when importing characters with that trinket, can you try the latest versions at the top of the list here - http://downloads.simulationcraft.org/?C=M;O=D - and let me know if they also do it ?
