### ISSUE TITLE
715-02 - Mage APL - Firestarter

### ISSUE THREAD

**Issue by Lothrik** [simulationcraft/simc#3558]
The current Fire Mage APL uses Firestarter inefficiently, and undervalues the talent in all situations.

Specifically it does not optimize around it at all, and will use Combustion immediately regardless of the talent.

Replacing the line:
actions+=/call_action_list,name=combustion_phase,if=cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)|buff.combustion.up

With the following line:
actions+=/call_action_list,name=combustion_phase,if=(cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)|buff.combustion.up)&(!talent.firestarter.enabled|target.health.pct<90)

Results in a 4K DPS increase for my character with Firestarter, and pushes the talent well above both Pyromaniac and Conflagration on Single Target. This mirrors the results I've seen in-game, using Firestarter on fights like Star Augur Etraeus.

**Comment by vituscze** [comment]
Fixed some time ago, closing.
