### ISSUE TITLE
Is there a plan to remove reforging from the app?

### ISSUE THREAD

**Issue by lorddev** [simulationcraft/simc#3561]
I noticed there are some features still included in the application like reforging and some tertiary stats that no longer exist. Would it be ok if I explored the removal of these features from the application?

**Comment by Frostedmages** [comment]
Reforging is a useful tool for investigating different issues related to stat values, removing it is not something I think would be beneficial.

**Comment by lorddev** [comment]
So it doesn't mean what it used to mean?

**Comment by Collisionc** [comment]
Yeah, the common player still knows that reforging means taking -500 of one stat and moving that 500 to another stat.  We may look at renaming it at some point, but it's not being removed from the program.

**Comment by lorddev** [comment]
OK, I thought reforging was a thing you did near the xmog vendor to take -x from one stat and move it to another. Which had been removed.
