### ISSUE TITLE
715-01 - Druid Balance Starfall with Fury Of Elune

### ISSUE THREAD

**Issue by luansievers** [simulationcraft/simc#3562]
there is a step on acion list of fury_of_elune:
`actions.fury_of_elune+=/starfall,if=(active_enemies>=2&talent.stellar_flare.enabled|active_enemies>=3)&buff.fury_of_elune_up.down&cooldown.fury_of_elune.remains>10`

Talent Stellar Flare will never be enabled with Fury Of Elune

**Comment by iPilot** [comment]
Are you mean "Stellar drift"? Cause Stellar flare in 5 tier, but Fury of Elune in 7 tier. Everything is fine now.

**Comment by ghost** [comment]
my bad
