### ISSUE TITLE
Error on opening, cannot access Specified file

### ISSUE THREAD

**Issue by haywireid** [simulationcraft/simc#3564]
installed 64 on my 64 system extracted but when I try to open I get 

"windows cannot access specified device, path or file, you may not have the appropriate permissions"

Im the only account on thsi computer with all admin rights, and even opened the program as admin ..

Have unistalled my antivirus and everything, cant figure out whats going on

**Comment by Collisionc** [comment]
Try moving the simulationcraft folder that you extracted to another folder, it sounds like it's autoextracting into appdata
