### ISSUE TITLE
Simulationcraft not running at all

### ISSUE THREAD

**Issue by Dstrst** [simulationcraft/simc#3565]
I have tried uninstalling I have tried every version. Window just flashes and then nothing

**Comment by norsehealer** [comment]
If you log into another windows account, does SimC work? This is the only way I can currently get my Windows 10 SimC to work.

**Comment by Deezelgurl** [comment]
I am also having this same issue. I've tried multiple accounts, I tried creating a new Environment Variable. Nothing seems to work. Right clicking and opening as Admin doesn't work either. I can provide any information you need.

This is the error log:
```
Fault bucket 120709849615, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: SimulationCraft.exe
P2: 0.0.0.0
P3: 58b737df
P4: Qt5Core.dll
P5: 5.7.1.0
P6: 583ffc1b
P7: c0000005
P8: 00000000000aca73
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3024.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SimulationCraft._2b3350e0272a61f055655f5de66e15ae24ee6c1b_f0087a23_2a333340

Analysis symbol: 
Rechecking for solution: 0
Report Id: c79fde3d-3ffb-4009-a21e-985e0b723e4d
Report Status: 0
Hashed bucket: 339d7b8a383dcfa2252b36e2efb76f88
```
Other log reads:
```
Faulting application name: SimulationCraft.exe, version: 0.0.0.0, time stamp: 0x58b737df
Faulting module name: Qt5Core.dll, version: 5.7.1.0, time stamp: 0x583ffc1b
Exception code: 0xc0000005
Fault offset: 0x00000000000aca73
Faulting process id: 0x20d0
Faulting application start time: 0x01d2931cd81bf804
Faulting application path: C:\Simulationcraft(x64)\715-02\SimulationCraft.exe
Faulting module path: C:\Simulationcraft(x64)\715-02\Qt5Core.dll
Report Id: c79fde3d-3ffb-4009-a21e-985e0b723e4d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Collisionc** [comment]
I'm sure you may have already tried, but option 3 here - https://github.com/simulationcraft/simc/wiki/CommonIssues - usually resolves this. 

for @Deezelgurl  that may be your antivirus sandboxing qt5core.dll, try disabling it temporarily to see if simulationcraft will load. If that doesn't work, does the the 32 bit download work? 

Also I uploaded a new simulationcraft with a newer version of QT at the top here - http://downloads.simulationcraft.org/?C=M;O=D.

**Comment by norsehealer** [comment]
I've personally tried that and it didn't work. I've used the 32-bit and 64-bit. I've tried the zip and the exe. I've tried the daily builds. I've moved the install location. I've disabled my antivirus too.

I tried simc-715-02-win64-92af786.7z version and it works. Thanks!

**Comment by Deezelgurl** [comment]
The new version you posted today works! Don't know what changed, but thank you! I can finally sim myself! I appreciate you taking the time to look into it.

**Comment by Collisionc** [comment]
Glad to see that fixes it, it must have been an issue with QT. I'll continue using that version.
