### ISSUE TITLE
sudden error when simming my character(s) (solved)

### ISSUE THREAD

**Issue by satiwa** [simulationcraft/simc#3568]
Hi. I'm new to sim (about 1 month) and it worked perfectly.
I decided to try a thing and started a sim. then I switched out an item, and did a new sim. (with /csim addon) and then an error poped up, and now I can't sim at all.
Option parsing error:
Unexpected parameter 'd#'. Expected format: name=value
I've tried to update with nightly, I've uninstalled, installed on different lokations etc, can't get it to work.

(message)
# SimulationCraft encountered an error!
* Category: Option parsing error
* Error: Unexpected parameter 'd#'. Expected format: name=value

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
d# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
shaman="Slaken"
level=110
race=dwarf
region=eu
server=darksorrow
role=
professions=enchanting=64/jewelcrafting=127
talents=2212122
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:3:906:3:907:3:908:3:909:3:910:3:911:3:912:3:913:3:930:1:1351:1:1388:9

head=,id=140903,bonus_id=3444/1482/1813
neck=,id=142428,enchant_id=5439,bonus_id=3507/1808/1502/3336,gem_id=130220
shoulder=,id=138348,enchant_id=5883,bonus_id=3514/1472/1813
back=,id=138372,enchant_id=5435,bonus_id=3516/42/1502/3337
chest=,id=138346,bonus_id=3514/43/1472/1813
wrist=,id=137084,bonus_id=3458/3455
hands=,id=138341,bonus_id=3516/1487/1813
waist=,id=140868,bonus_id=3514/1487/3337
legs=,id=140871,bonus_id=3444/1487/3336
feet=,id=138117,bonus_id=3458/3455
finger1=,id=140897,enchant_id=5429,bonus_id=3515/41/1482/3336
finger2=,id=134540,enchant_id=5429,bonus_id=3416/1808/1517/3336,gem_id=130222
trinket1=,id=139329,bonus_id=1805/41/1502/3337
trinket2=,id=139325,bonus_id=1805/1808/1487,gem_id=130222
main_hand=,id=128819,bonus_id=745,relic_id=3514:1472:1813/3515:1482:3336/3516:1487:1813,gem_id=140835/140817/140841/0
off_hand=,id=128873,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
Might be the same that I linked, but I link it anyway in case of.
Simc_gui.simc
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
d# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
shaman="Slaken"
level=110
race=dwarf
region=eu
server=darksorrow
role=
professions=enchanting=64/jewelcrafting=127
talents=2212122
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:3:906:3:907:3:908:3:909:3:910:3:911:3:912:3:913:3:930:1:1351:1:1388:9

head=,id=140903,bonus_id=3444/1482/1813
neck=,id=142428,enchant_id=5439,bonus_id=3507/1808/1502/3336,gem_id=130220
shoulder=,id=138348,enchant_id=5883,bonus_id=3514/1472/1813
back=,id=138372,enchant_id=5435,bonus_id=3516/42/1502/3337
chest=,id=138346,bonus_id=3514/43/1472/1813
wrist=,id=137084,bonus_id=3458/3455
hands=,id=138341,bonus_id=3516/1487/1813
waist=,id=140868,bonus_id=3514/1487/3337
legs=,id=140871,bonus_id=3444/1487/3336
feet=,id=138117,bonus_id=3458/3455
finger1=,id=140897,enchant_id=5429,bonus_id=3515/41/1482/3336
finger2=,id=134540,enchant_id=5429,bonus_id=3416/1808/1517/3336,gem_id=130222
trinket1=,id=139329,bonus_id=1805/41/1502/3337
trinket2=,id=139325,bonus_id=1805/1808/1487,gem_id=130222
main_hand=,id=128819,bonus_id=745,relic_id=3514:1472:1813/3515:1482:3336/3516:1487:1813,gem_id=140835/140817/140841/0
off_hand=,id=128873,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

Please help, thanks in advance!

**Comment by Collisionc** [comment]
Make a new simulate tab and copy/paste your character again, you have an errant 'd' in your simulation.

### Begin simulateText ###
d# Profile will be downloaded into a new tab.
#
^

**Comment by satiwa** [comment]
Thank you, that solved it! Not sure what an arrant D is, but thanks mate!
