### ISSUE TITLE
[Rogue-Outlaw] Relic - Edge of the First Blade - Incorrect Trait

### ISSUE THREAD

**Issue by Dicerr** [simulationcraft/simc#3569]
715-02 wow23360 git 6dbd258

I just got a relic from my weekly chest.  ilvl 900 Edge of the First Blade which has a Fatebringer trait.  But when I change my current relic to the new one it is giving a Fortune Strike Trait.

I have tried the item as per AMR's interface  id: 137493 bonus: 1552:3337:3536, I thought I'd try the id and bonus from wowheads interface, but it gives the same bonus.  I'm guessing the gem ID gives the actual trait?  ilvl and name come up as correct.  Just the trait is incorrect.

**Comment by aethys256** [comment]
I just tested it, for me it's Fatebringer:

![image](https://cloud.githubusercontent.com/assets/10969743/23217859/e0e26bd4-f91a-11e6-84b9-eee03d606085.png)

![image](https://cloud.githubusercontent.com/assets/10969743/23217880/f016c9ec-f91a-11e6-98fb-72031985fb2f.png)

`main_hand=the_dreadblades,id=128872,bonus_id=742,gem_id=137493,ilevel=920`

I guess you used the wrong gem_id.
If you still experience it, post your profile.
