### ISSUE TITLE
Demon Hunter Output Issues Wrong Abilities

### ISSUE THREAD

**Issue by HnyBear** [simulationcraft/simc#3574]
SC Ver: simc-715-01-win64

Importing my Havoc Demon Hunter from Azuremyst, Failtrail.

The end results show abilities I don't have; Death_Sweep, Annihilation and on one import/sim it showed Demons _Bite.

Even though it is grabbing the proper spec for what I'm currently using the wrong abilities keep showing up. I'm attaching a saved html in pdf format since zip won't upload.

[Simulationcraft Results.pdf](https://github.com/simulationcraft/simc/files/794598/Simulationcraft.Results.pdf)

**Comment by EvanMichaels** [comment]
Death Sweep and Annihilation are used when in Metamorphosis. Nothing wrong here.
