### ISSUE TITLE
Cinidaria, the Symbiote causes segfault

### ISSUE THREAD

**Issue by riccozzz** [simulationcraft/simc#3576]
This problem occurred on the latest nightly build for windows (ff6af4d) and building from git on Linux. When simming a rogue or demon hunter using this legendary it causes the program to immediately segfault (have not tested the other classes its usable on). Commenting out the waist= line fixes the problem. Likely due to this commit:

https://github.com/simulationcraft/simc/commit/c2bf39897b6e7a843a341258e33ba8e1ccad94c5

**Comment by navv1234** [comment]
This is fixed in 30c1a4e.
