### ISSUE TITLE
[Rogue Assa] Draught Of Souls usage

### ISSUE THREAD

**Issue by Fjellryn** [simulationcraft/simc#3579]
Regarding DoS usage, right now the APL line is like this
 "if=energy.time_to_max>3.5&!debuff.kingsbane.up&(!talent.agonizing_poison.enabled|(debuff.agonizing_poison.stack=5&debuff.surge_of_toxins.remains>3))"
but by deleting the kingsbane debuff condition I gain 7.5k DPS on the base T19M_NH profile (772.5k => 780k). Because we have melee attacks during DoS we shouldn't care about kingsbane.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/bf3e1bb5220dcad06753595fca27d82d4e206841
