### ISSUE TITLE
Prot Warrior 2pc has no affect on critical block chance.

### ISSUE THREAD

**Issue by Tengenstein** [simulationcraft/simc#3581]
Please include a brief overview of the issue in the title above, as well as completing the following:

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
tmi_boss=TMI_Standard_Boss_T19H
tmi_boss_type=T19H
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,sta,crit,haste,mastery,vers,armor
center_scale_delta=1
scale_over=TMI
statistics_level=1
### Begin simulateText ###
warrior="Tengenstein"
origin="https://eu.api.battle.net/wow/character/azuremyst/Tengenstein/advanced"
thumbnail="http://eu.battle.net/static-render/eu/azuremyst/139/68691851-avatar.jpg"
level=110
race=goblin
role=tank
position=front
professions=engineering=793/mining=800
talents=http://eu.battle.net/wow/en/tool/talent-calculator#Zb!0112101
artifact=11:0:0:0:0:91:1:92:1:93:1:94:1:95:3:96:3:97:1:98:3:99:3:100:3:101:3:102:3:103:1:104:1:105:3:106:3:1358:1:1395:20
spec=protection

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=ten_thousand_scars
actions.precombat+=/food,type=seed-battered_fish_plate
actions.precombat+=/augmentation,type=defiled
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=unbending_potion

# Executed every time the actor is available.
actions=auto_attack
actions+=/intercept
actions+=/use_item,name=heavy_skullblasters
actions+=/use_item,name=archimondes_hatred_reborn
# actions+=/use_item,name=animated_exoskeleton
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/call_action_list,name=prot

actions.prot=spell_reflection,if=incoming_damage_2500ms>health.max*0.20
actions.prot+=/demoralizing_shout,if=incoming_damage_2500ms>health.max*0.20&!talent.booming_voice.enabled
actions.prot+=/last_stand,if=incoming_damage_2500ms>health.max*0.40
actions.prot+=/shield_wall,if=incoming_damage_2500ms>health.max*0.40&!cooldown.last_stand.remains=0
actions.prot+=/potion,name=unbending_potion,if=(incoming_damage_2500ms>health.max*0.15&!buff.potion.up)|target.time_to_die<=25
actions.prot+=/battle_cry,if=cooldown.shield_slam.remains=0
actions.prot+=/demoralizing_shout,if=talent.booming_voice.enabled&buff.battle_cry.up
actions.prot+=/ravager,if=talent.ravager.enabled&buff.battle_cry.up
actions.prot+=/neltharions_fury,if=!buff.shield_block.up&cooldown.shield_block.remains>3&((cooldown.shield_slam.remains>3&talent.heavy_repercussions.enabled)|(!talent.heavy_repercussions.enabled))
actions.prot+=/shield_block,if=!buff.neltharions_fury.up&((cooldown.shield_slam.remains=0&talent.heavy_repercussions.enabled)|action.shield_block.charges=2|!talent.heavy_repercussions.enabled)
actions.prot+=/ignore_pain,if=(rage>=60&!talent.vengeance.enabled)|(buff.vengeance_ignore_pain.up&rage>=39)|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage<30&!buff.revenge.react)
actions.prot+=/revenge,if=(talent.vengeance.enabled&buff.revenge.react&!buff.vengeance_ignore_pain.up)|(buff.vengeance_revenge.up&rage>=59)|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage>=69)|(!talent.vengeance.enabled&buff.revenge.react)
actions.prot+=/shield_slam,if=(!(cooldown.shield_block.remains<=gcd.max*2&!buff.shield_block.up)&talent.heavy_repercussions.enabled)|!talent.heavy_repercussions.enabled
actions.prot+=/thunder_clap
actions.prot+=/devastate

head=heavy_skullblasters,id=144334,bonus_id=600/1705/3408
neck=prydaz_xavarics_magnum_opus,id=132444,bonus_id=3458/3455,gems=150haste,enchant=mark_of_the_heavy_hide
shoulders=pauldrons_of_encroaching_limits,id=142128,bonus_id=1808/3453/1497/3337,gems=150haste
back=greatcloak_of_the_obsidian_aspect,id=138374,bonus_id=3514/1472/1813,enchant=gift_of_haste
chest=chestplate_of_the_obsidian_aspect,id=138351,bonus_id=3516/1487/1813
shirt=brawlers_harness,id=6125
wrists=jagged_carapace_wristclamps,id=140902,bonus_id=3444/1487/3336
hands=fists_of_the_legion,id=134509,bonus_id=3510/1537/3337
waist=goresmeared_abyssal_waistplate,id=140892,bonus_id=3514/1472/1813,addon=nitro_boosts
legs=chronotempered_legplates,id=140882,bonus_id=3444/1482/1813
feet=leystonetoe_kickers,id=140884,bonus_id=3444/40/1482/1813
finger1=ring_of_braided_stems,id=140896,bonus_id=3516/1808/1487/1813,gems=150haste,enchant=200haste
finger2=mindrend_band,id=138220,bonus_id=1805/1808/1502/3337,gems=150haste,enchant=200haste00haste
trinket1=unstable_arcanocrystal,id=141482,bonus_id=1487/3337
# trinket1=animated_exoskeleton,id=140789,bonus_id=3443/1467/1813
trinket2=archimondes_hatred_reborn,id=144249,bonus_id=3529/3530
main_hand=scaleshard,id=128288
off_hand=scale_of_the_earthwarder,id=128289,bonus_id=752,gem_id=140815/140820/140836/0,relic_id=3444:1482:1813/3515:1477:1813/3514:1472:1813/0

# Gear Summary
# gear_ilvl=891.69
# gear_strength=18207
# gear_stamina=28665
# gear_crit_rating=4349
# gear_haste_rating=9312
# gear_mastery_rating=9262
# gear_versatility_rating=5594
# gear_speed_rating=644
# gear_armor=4346
# set_bonus=tier19_2pc=1

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:
Sim with prot warrior 2 piece equipped

Sim a second time with set_bonus=tier19_2pc=0 (delete the # and change 1 to 0)

Observe a negligible variance in TMI, Damage taken, Scales of Earth Up-time, and fluffy pillow melee_main_hand_Tengenstein hit (critical blocked) rate.

**Comment by Collisionc** [comment]
Sorry about that, will be in the next release.
