### ISSUE TITLE
APL is not optimal for Sin MotMA playstyle

### ISSUE THREAD

**Issue by Thernn** [simulationcraft/simc#3582]
The Simc APL for the MotMA playstyle is not optimal. Significant confusion exists over openers along with the best way to synergize Vendetta, Kingsbane & Vanish. Proper utilization of garrote with the subterfuge buff it recieves must also be considered. Complicating these interactions further is the addition of Draught of Souls when a rogue has it.

Kiwifruity's logs - A few playstyles. Older Feb logs use one playstyle while newer logs use another. Has DoS.
https://www.warcraftlogs.com/rankings/character/20414689/latest/#boss=1842

Mythic Krosus log of a Rogue w/ Mantle + Boots but without DoS
https://www.warcraftlogs.com/reports/8yWhKqpYAMrHdzL7#fight=8&type=casts&source=9&view=timeline

Another opener and playstyle
https://www.warcraftlogs.com/reports/XvqNQaRrj3G8ZD4b#fight=28&type=casts&view=timeline&source=20

Question: When a rogue only has CoF and 3MA relics should Kingsbane be banked so it can be used alongside Vendetta & Vanish?

**Comment by Thernn** [comment]
It appears the community has settled on the optimal opener for Mantle + DoS when you have Boots + CoF and MA relics. 

Here is a time line of a Krosus fight for a rogue who has DoS
https://www.warcraftlogs.com/reports/1PnzdFgxB3Dh8rVJ#fight=42&type=casts&view=timeline&source=44

Opener is pretty much set in stone at this point.
Garrote > Mutilate > Rupture > Mutilate > Vendetta> Envenom>Kingsbane>Mutilate>Wait and then Vanish & Envenom before the envenom buff drops> Garrote > Mutilate> Envenom> Mutilate>DoS>Envenom

Napkin math time. 

Garrote would give us **2632.5% AP**!!! over it's duration if applied during the subterfuge period.
(((90%AP)x4)x2.25)x2) which is equal to 1620% AP (est 4 ticks with 100% crit) + ((90%AP)x5)x2.25) which is equal to 1012.5% AP (5 ticks assuming none crit). 

A mantled envenom would give 
((60%AP)x5)x1.3)x2) = 780% AP @ 5CP
((60%AP)x4)x1.3)x2) = 624% AP @ 4CP

The super Garrote wins by a **LARGE** margin over an extra envenom.

If DoS does not line up with vanish, I think the most optimal ability usage would be as follows. Kingsbane after 4-5cp envenom>Mutilate > Mutilate > Wait until KB is about 9.5 seconds remaining (We want to clip envenom buff)> Vendetta> Vanish > Envenom> Garrote >Mutilate> Envenom >Mutilate > Envenom>Mutilate>Envenom

If DoS does line up with vanish, I think the most optimal ability usage would be as follows.  Kingsbane after 4-5cp envenom>Mutilate> Mutilate>Wait until KB is about 9.5 seconds remaining (We want to clip envenom buff)> Vendetta>Vanish> Envenom > Garrote >Mutilate>Envenom> DoS > Envenom.


Notes.
Outside of the Mantle period Vendetta and KB should be used together on CD. Make sure your dots are refreshed. Cast KB first then immediately Vendetta to replenish energy. Mut & Envenom at 4-5cp clipping SoT until you can't clip anymore.

Other than it's initial application, we don't want to reapply rupture during the mantle period.

Unless vanish is <10s (estimate) from CD we want to bank it for next KB/VEN use.

DoS should be used on CD when you are energy deficient and after you've dumped a 4-5cp envenom or Rupture for the SoT bonus. However, it should line up pretty naturally with your 4th vanish. Only bank it for Vanish if you know you wouldn't be able to get another full length use out of it had you not banked.

You should be able to have your garrote up for every vanish. You may need to refresh it earlier than is normally optimal or rarely let it drop for a second or two. Remember you will have the 4 seconds before we vanish + the 3 seconds period we can apply during subterfuge.  

Subterfuge Garrote should be allowed to tick for its' full length.

Be smart with your CD usage. If you know there is only time for one more vanish in a fight bank it so you can line it up with KB/VEN & DoS.

I'll update this post after I finish thinking about the best opener for rogues who have Mantle + boots + cof and at least 2MA relics but don't have DoS. For draughtless rogues the best use of vanish during the fight would be identical to the one DoS rogues use when that trinket is on CD.
 
Simulation needs to be done with regards to waiting for Vendetta to come off CD and its
relation to KB and Vanish when you have only CoF or only Boots or even neither.

**Comment by aethys256** [comment]
Should be all good now, only thing missing is Vanish under 30% with Bracers.
