### ISSUE TITLE
Compilation struggles on FreeBSD and sc_report error

### ISSUE THREAD

**Issue by Phied** [simulationcraft/simc#3586]
#### Compilation Steps:
Try to build the source on FreeBSD 10.3-RELEASE.  You will get a ton of errors.  I have been able to compile successfully as long as I do the following.

- Install gcc6 or higher
- Compile with gmake
- #include <stdarg.h> in util/str.hpp
- #include <netinet/in.h>, <sys/socket.h>, and <arpa/inet.h> in file interfaces/sc_http.cpp

I am able to run simulations successfully at this point. 

### HTML Report Generation Error
When I try to send the results to html there are many times (depending on character being simmed) I get an error that says:

`terminate called after throwing an instance of '(anonymous namespace)::tooltip_parser_t::error'`

When this error is thrown, the html page is missing all of the charts and I am unable to expand the different sections.  The only workaround I am able to do is to set report_details=0 when I simulate anything.  When I do this, I no longer get the error listed above.

As far as I can tell, no other report method (xml, json, etc) have this problem.

**Comment by scamille** [comment]
I studied the tooltip parser code, and I can't see how any '(anonymous namespace)::tooltip_parser_t::error' exception can propagate outside of the tooltip parser code.

Can you please post
1) The exact input you used for the simulation (If you use the GUI, see https://github.com/simulationcraft/simc/wiki/simc_gui.simc)
2) If possible debug the program, and get a stacktrace of the exception.
