### ISSUE TITLE
Standard derivation for DPS

### ISSUE THREAD

**Issue by frosty808** [simulationcraft/simc#3591]
I really like simming for mean DPS, trying out different gearsets and gems/enchants. However, aside of the mean DPS i am also very interested in doing consistant damage. Thats why i would really like knowing about the standard deviation. Would be really nice to add that, maybe under the graph. Thanks a lot.

**Comment by scamille** [comment]
In the character overview there is the metric "DPS Range", representing percentile(0.025) to percentile(0.975) length of your DPS distribution.

And for each character, in the Statistics & Data Analysis section -> DPS there are tons of statistical numbers.
