### ISSUE TITLE
Simcraft crashes anytime I try to sim more than 2 targets or do add cleave sims

### ISSUE THREAD

**Issue by Aravell1** [simulationcraft/simc#3598]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

715-02

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files

[DxDiag.txt](https://github.com/simulationcraft/simc/files/804805/DxDiag.txt)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

http://pastebin.com/KkgVKuHd

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

in that particular sim the fight was set to hectic add cleave, with 1 enemy

**Comment by EvanMichaels** [comment]
Fixed this in https://github.com/simulationcraft/simc/commit/13c760bd849dc9152c27bf54d672afbf06eec4f7
