### ISSUE TITLE
Balance Druid Nature's Balance talent

### ISSUE THREAD

**Issue by Jundarer** [simulationcraft/simc#3599]
Using this talent causes neither sunfire nor moonfire to ever fall of in a single target patchwerk sim even though that is impossible, especially with ed. There have been a few fixes for nb before but it is still extending the dot duration by too much for some reason. My first guess would be that the extension doesn't scale with haste(even though it should) but I have no idea what causes it in the end.

**Comment by Hyperion244** [comment]
I noticed that you commented late on the thread here (https://github.com/simulationcraft/simc/issues/3344) the last time this issue arose.  I had the same thought process as you regarding it not updating dynamically/scaling with haste, as did Gebuz, but @Collisionc checked it out and it seems to be functioning correctly, so we're not really sure where it stands.  I guess the next step is to go into the output and go through step by step and calculate everything by hand to make sure its outputting correctly.

**Comment by Jundarer** [comment]
I took a look at it with the detail option and here is what I found every time it extends the duration:

7.439 Tunderer invalidates spell_haste
7.439 Tunderer invalidates spell_speed
7.439 Tunderer gains star_power_6 ( value=0.01 )
7.439 Adjusting reschedule of event buff_expiration (28) from 20.58 to 22.44 time=16.12
7.439 Tunderer extends duration of moonfire on Fluffy_Pillow by 6.6 second(s).
7.439 Rescheduling event DoT End (18) from 22.00 to 28.61

8.071 Tunderer invalidates spell_haste
8.071 Tunderer invalidates spell_speed
8.071 Tunderer gains star_power_7 ( value=0.01 )
8.071 Adjusting reschedule of event buff_expiration (28) from 22.44 to 23.07 time=16.12
8.071 Tunderer extends duration of sunfire on Fluffy_Pillow by 4.2 second(s).
8.071 Adjusting reschedule of event DoT End (31) from 23.70 to 27.91 time=19.12

12.207 Tunderer invalidates spell_haste
12.207 Tunderer invalidates spell_speed
12.207 Tunderer gains star_power_12 ( value=0.01 )
12.207 Adjusting reschedule of event buff_expiration (28) from 25.48 to 27.21 time=16.12
12.207 Tunderer extends duration of moonfire on Fluffy_Pillow by 6.1 second(s).
12.207 Adjusting reschedule of event DoT End (18) from 34.69 to 40.81 time=22.00

etc
It extends the duration by more than it should as I understand that. Not sure if the 6.x/4.x is before or after haste but either way it's wrong

**Comment by Gebuz** [comment]
Are you sure that those events are not just pandemic extension when refreshing the dots?
With starlord, cast time of LS is 2 sec, and SW is 1.2 sec, while extend duration is 6 and 4 seconds. If you want to keep them rolling forever, you'll need to spend 2/6=33% of your time casting LS, and 1.2/4=30% of your time casting SW. I'm not on my home PC atm, so I can't check myself, but if you run a patchwork sim with starlord and NB you should be able to confirm/deny if the numbers are realistic.

**Comment by Collisionc** [comment]
I'll try and get this fixed today/tomorrow.

**Comment by Bloodmallet** [comment]
Fixed hasted calculation and exchanged the increase for the actual spell data
https://github.com/simulationcraft/simc/commit/732a071d2bdee40cf5d02ab3df0c946b3824d59b
