### ISSUE TITLE
Assassination rogue rupture time spent overlarge

### ISSUE THREAD

**Issue by Shlorp** [simulationcraft/simc#3603]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
simc-715-01-win64

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=1
default_world_lag=0.1
max_time=300
vary_combat_length=0
fight_style=LightMovement
tmi_window_global=6
target_level+=3
target_race=Demon
default_skill=0.85
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Normal
scale_over=DPS
statistics_level=1
### Begin simulateText ###
rogue="Shlorp"
origin="https://us.api.battle.net/wow/character/moonrunner/Shlorp/advanced"
thumbnail="http://us.battle.net/static-render/us/moonrunner/224/74527456-avatar.jpg"
level=110
race=undead
role=attack
position=back
professions=engineering=733/mining=736
talents=http://us.battle.net/wow/en/tool/talent-calculator#ca!0020000
artifact=43:0:0:0:0:323:1:324:3:325:3:326:3:327:3:328:3:329:3:330:3:331:3:332:1:333:1:334:1:335:1:337:1:346:1:347:1:1276:1:1384:4
spec=assassination

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,name=flask_of_the_seventh_demon
actions.precombat+=/augmentation,name=defiled
actions.precombat+=/food,name=seedbattered_fish_plate
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=old_war
actions.precombat+=/marked_for_death,if=raid_event.adds.in>40

# Executed every time the actor is available.
actions=call_action_list,name=cds
actions+=/call_action_list,name=maintain
# The 'active_dot.rupture>=spell_targets.rupture' means that we don't want to envenom as long as we can multi-rupture (i.e. units that don't have rupture yet).
actions+=/call_action_list,name=finish,if=(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains>2)&(!dot.rupture.refreshable|(dot.rupture.exsanguinated&dot.rupture.remains>=3.5)|target.time_to_die-dot.rupture.remains<=4)&active_dot.rupture>=spell_targets.rupture
actions+=/call_action_list,name=build,if=(combo_points.deficit>0|energy.time_to_max<1)

# Builders
actions.build=hemorrhage,if=refreshable
actions.build+=/hemorrhage,cycle_targets=1,if=refreshable&dot.rupture.ticking&spell_targets.fan_of_knives<=3
actions.build+=/fan_of_knives,if=spell_targets>=3|buff.the_dreadlords_deceit.stack>=29
actions.build+=/mutilate,cycle_targets=1,if=(!talent.agonizing_poison.enabled&dot.deadly_poison_dot.refreshable)|(talent.agonizing_poison.enabled&debuff.agonizing_poison.remains<debuff.agonizing_poison.duration*0.3)|(set_bonus.tier19_2pc=1&dot.mutilated_flesh.refreshable)
actions.build+=/mutilate

# Cooldowns
actions.cds=potion,name=old_war,if=buff.bloodlust.react|target.time_to_die<=25|debuff.vendetta.up
actions.cds+=/blood_fury,if=debuff.vendetta.up
actions.cds+=/berserking,if=debuff.vendetta.up
actions.cds+=/arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
actions.cds+=/marked_for_death,target_if=min:target.time_to_die,if=target.time_to_die<combo_points.deficit|combo_points.deficit>=5
actions.cds+=/vendetta,if=talent.exsanguinate.enabled&cooldown.exsanguinate.remains<5&dot.rupture.ticking
actions.cds+=/vendetta,if=talent.exsanguinate.enabled&(artifact.master_assassin.rank>=4-equipped.convergence_of_fates|equipped.duskwalkers_footpads)&energy.deficit>=75&!(artifact.master_assassin.rank=5-equipped.convergence_of_fates&equipped.duskwalkers_footpads)
actions.cds+=/vendetta,if=!talent.exsanguinate.enabled&energy.deficit>=88-!talent.venom_rush.enabled*10
actions.cds+=/vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&((talent.exsanguinate.enabled&cooldown.exsanguinate.remains<1&(dot.rupture.ticking|time>10))|(!talent.exsanguinate.enabled&dot.rupture.refreshable))
actions.cds+=/vanish,if=talent.subterfuge.enabled&dot.garrote.refreshable&((spell_targets.fan_of_knives<=3&combo_points.deficit>=1+spell_targets.fan_of_knives)|(spell_targets.fan_of_knives>=4&combo_points.deficit>=4))
actions.cds+=/vanish,if=talent.shadow_focus.enabled&energy.time_to_max>=2&combo_points.deficit>=4
actions.cds+=/exsanguinate,if=prev_gcd.1.rupture&dot.rupture.remains>4+4*cp_max_spend

# Finishers
actions.finish=death_from_above,if=combo_points>=cp_max_spend
actions.finish+=/envenom,if=combo_points>=4|(talent.elaborate_planning.enabled&combo_points>=3+!talent.exsanguinate.enabled&buff.elaborate_planning.remains<0.1)

# Maintain
actions.maintain=rupture,if=(talent.nightstalker.enabled&stealthed.rogue)|(talent.exsanguinate.enabled&((combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1)|(!ticking&(time>10|combo_points>=2+artifact.urge_to_kill.enabled))))
actions.maintain+=/rupture,cycle_targets=1,if=combo_points>=cp_max_spend-talent.exsanguinate.enabled&refreshable&(!exsanguinated|remains<=1.5)&target.time_to_die-remains>4
actions.maintain+=/kingsbane,if=(talent.exsanguinate.enabled&dot.rupture.exsanguinated)|(!talent.exsanguinate.enabled&(debuff.vendetta.up|cooldown.vendetta.remains>10))
actions.maintain+=/pool_resource,for_next=1
actions.maintain+=/garrote,cycle_targets=1,if=refreshable&(!exsanguinated|remains<=1.5)&target.time_to_die-remains>4

head=kraken_hide_helm,id=133618,bonus_id=3412/1808/1517/3337,gems=100crit
neck=roughhammered_silver_necklace,id=134187,bonus_id=3474/1507/1674
shoulders=mantle_of_the_master_assassin,id=144236,bonus_id=3458/3455
back=windwhipped_greatcloak,id=141541,bonus_id=3466/1477/3336
chest=grove_keepers_robe,id=139207,bonus_id=1805/1487
shirt=wound_dressing,id=44693
wrists=brinewashed_leather_bracers,id=134236,bonus_id=3474/1507/1674
hands=manasaber_hide_gloves,id=134327,bonus_id=3473/1517/3337
waist=biornskin_belt,id=134199,bonus_id=3432/1517/3337
legs=will_of_valeera,id=137069,bonus_id=3529/3530
feet=bleak_underworld_treads,id=137324,bonus_id=3412/1507/3336
finger1=nazjatar_manapearl_ring,id=134245,bonus_id=3474/1808/1507/1674,gems=100crit
finger2=valkyr_ascension_signet,id=133679,bonus_id=1727/1492/1813
trinket1=hunger_of_the_pack,id=136975,bonus_id=3410/1502/3336
trinket2=arcanogolem_digit,id=140794,bonus_id=3446/1452
main_hand=the_kingslayers,id=128870,bonus_id=741,gem_id=143693/137371/143684/0,relic_id=3474:1527:3337/3415:1512:3336/3474:1507:1674/0
off_hand=the_kingslayers,id=128869

# Gear Summary
# gear_ilvl=868.25
# gear_agility=17748
# gear_stamina=25887
# gear_crit_rating=7710
# gear_haste_rating=3935
# gear_mastery_rating=6013
# gear_versatility_rating=2064
# gear_armor=2254

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by aethys256** [comment]
What does it means ?
Also, I don't see any report in the issue.

**Comment by Shlorp** [comment]
Rupture is being cast about once every 6 seconds (as if it's always cast with 1 combo point-8s)
51.5s casting rupture in a 300s fight
[RuptueResult.txt](https://github.com/simulationcraft/simc/files/813469/RuptueResult.txt)
while that time casting should be slightly smaller than subtlety's nightblade(considering duration scaling tween the two spells)
18.6s casting nightblade in a 300s fight
[NightbladeResult.txt](https://github.com/simulationcraft/simc/files/813480/NightbladeResult.txt)

Amounts to resources being misspent in the simulation

**Comment by Shlorp** [comment]
oops

**Comment by SOLiNARY** [comment]
That's because you're **stealthed** for like 2 minutes into fight.
It keeps using rupture over & over again.
Must be a bug.
I have the resulting html over here:
https://cdn.discordapp.com/attachments/228879234540503040/286904736475643904/results_html.html
You can check in Sequence table, **stealthed** buff is on the player for a **VERY** long time.

**Comment by SOLiNARY** [comment]
This commit must fix the problem, #1307eb5 let's wait for another build.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/1307eb5c55080166ea1cf80ed57e5732dc0140ff ^^
