### ISSUE TITLE
Unholy str buff for frost (possibly unholy) 

### ISSUE THREAD

**Issue by zapnaz** [simulationcraft/simc#3607]
Ran a sim for my frost dk and noticed the uptime for the Unholy Strength buff from the Fallen Crusader runeforge enchant looked high (around 90% uptime) 

When comparing this to logs they show between 50-75% uptime. Duration of the buff looks ok, could be that the proc chance is set too high?

html file can be found here: http://www.filedropper.com/unholystrcheck

**Comment by Demei** [comment]
Both mainhand and offhand weapons on that sim are enchanted with Fallen Crusader, which will increase uptime on the strength buff. Changing the enchantment on the mainhand to Razorice should bring it in line with logs (~70% uptime).

**Comment by Collisionc** [comment]
Yeah, this is working as intended. Most people don't use FCR enchant on both weapons. :)
