### ISSUE TITLE
Unable to Sim Blood DK

### ISSUE THREAD

**Issue by CrusadersSin** [simulationcraft/simc#3609]
Please include a brief overview of the issue in the title above, as well as completing the following:
When importing my character Eydís, I can not sim. It shows up with these error codes: 
Player Eydís uses call_action_list with unknown action list bos
Simulation has been canceled during player setup! (thread=0)  
#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
[DxDiag.txt](https://github.com/simulationcraft/simc/files/819447/DxDiag.txt)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Please provide more data on what you're doing and how you're doing it.

Tank and Healing specs are not being actively supported by anyone, so errors with them are expected.

**Comment by lgkern** [comment]
It seems to be calling a action_list used for Frost DKs only, are you importing the character while it is using Blood Spec or are you importing as Frost and manually changing to Blood?

**Comment by CrusadersSin** [comment]
This is the code that I use from the in-game addon:

deathknight="Eydís"

level=110

race=night_elf

region=us

server=veknilash

role=

professions=blacksmithing=486/mining=562

talents=2112331

spec=blood

artifact=15:0:0:0:0:272:3:273:3:274:1:275:3:276:3:277:3:278:3:280:3:281:1:282:1:283:1:284:1:285:1:286:1:289:1:1331:1


head=,id=144280,bonus_id=3529/3530

neck=,id=140894,bonus_id=3443/1467/1813

shoulder=,id=142565,bonus_id=3462/1714/1492/3336

back=,id=140910,bonus_id=3516/1487/1813

chest=,id=142560,bonus_id=3462/1680/1487/1813

wrist=,id=138218,bonus_id=1807/1482/3336

hands=,id=139226,bonus_id=1807/1472

waist=,id=137361,bonus_id=3414/1507/1813

legs=,id=134183,bonus_id=3474/1512/3336

feet=,id=137334,bonus_id=3414/1808/1517/3336

finger1=,id=133637,enchant_id=5428,bonus_id=3410/40/1512/3337

finger2=,id=141534,enchant_id=5428,bonus_id=3466/1472

trinket1=,id=140789,bonus_id=3443/1477/3336

trinket2=,id=140791,bonus_id=3443/1467/1813

main_hand=,id=128402,enchant_id=3847,bonus_id=716,relic_id=3473:1507:3336/3432:1497:1674/3474:1507:1674,gem_id=143682/140041/143705/0


These at at least run through the sim, but all my character does is sit
there and auto attack, that is all the sim is doing. . .


This is the code for when I import my character using simcraft:

deathknight="Eydís"

origin="https://us.api.battle.net/wow/character/veknilash/Eydís/advanced"

thumbnail="
http://us.battle.net/static-render/us/veknilash/77/130922573-avatar.jpg"

level=110

race=night_elf

timeofday=day

role=tank

position=front

professions=blacksmithing=486/mining=562

talents=http://us.battle.net/wow/en/tool/talent-calculator#da!1001220

artifact=15:0:0:0:0:272:3:273:3:274:1:275:3:276:3:277:3:278:3:280:3:281:1:282:1:283:1:284:1:285:1:286:1:289:1:1331:1

spec=blood


# This default action priority list is automatically created based on your
character.

# It is a attempt to provide you with a action list that is both simple and
practicable,

# while resulting in a meaningful and good simulation. It may not result in
the absolutely highest possible dps.

# Feel free to edit, adapt and improve it to your own needs.

# SimulationCraft is always looking for updates and improvements to the
default action lists.


# Executed before combat begins. Accepts non-harmful actions only.

actions.precombat=flask,name=countless_armies

actions.precombat+=/food,name=seedbattered_fish_plate

actions.precombat+=/augmentation,name=defiled

# Snapshot raid buffed stats before combat begins and pre-potting is done.

actions.precombat+=/snapshot_stats

actions.precombat+=/potion,name=unbending_potion


# Executed every time the actor is available.

actions=auto_attack

actions+=/mind_freeze

actions+=/arcane_torrent,if=runic_power.deficit>20

actions+=/blood_fury,if=buff.pillar_of_frost.up

actions+=/berserking,if=buff.pillar_of_frost.up

actions+=/use_item,slot=trinket1

actions+=/potion,name=old_war,if=buff.pillar_of_frost.up

actions+=/sindragosas_fury,if=buff.pillar_of_frost.up&(buff.unholy_strength.up|(buff.pillar_of_frost.remains<3&target.time_to_die<60))&debuff.razorice.stack==5&!buff.obliteration.up

actions+=/call_action_list,name=generic,if=!talent.breath_of_sindragosa.enabled&!(talent.gathering_storm.enabled&buff.remorseless_winter.remains)

actions+=/call_action_list,name=bos,if=talent.breath_of_sindragosa.enabled&!dot.breath_of_sindragosa.ticking

actions+=/call_action_list,name=bos_ticking,if=talent.breath_of_sindragosa.enabled&dot.breath_of_sindragosa.ticking

actions+=/call_action_list,name=gs_ticking,if=talent.gathering_storm.enabled&buff.remorseless_winter.remains&!talent.breath_of_sindragosa.enabled


actions.generic=empower_rune_weapon


actions.gs_ticking=empower_rune_weapon


head=death_march,id=144280,bonus_id=3529/3530

neck=zealous_timestone_pendant,id=140894,bonus_id=3443/1467/1813

shoulders=fearless_gladiators_dreadplate_shoulders,id=142565,bonus_id=3462/1714/1492/3336

back=cloak_of_temporal_recalibration,id=140910,bonus_id=3516/1487/1813

chest=fearless_gladiators_dreadplate_chestpiece,id=142560,bonus_id=3462/1680/1487/1813

wrists=dragonbone_wristclamps,id=138218,bonus_id=1807/1482/3336

hands=primal_gauntlets_of_rage,id=139226,bonus_id=1807/1472

waist=roaring_shellbreaker_greatbelt,id=137361,bonus_id=3414/1507/1813

legs=skoldiir_legguards,id=134183,bonus_id=3474/1512/3336

feet=saltladen_stompers,id=137334,bonus_id=3414/1808/1517/3336

finger1=utgarde_royal_signet,id=133637,bonus_id=3410/40/1512/3337,enchant=200haste

finger2=loop_of_polished_pebbles,id=141534,bonus_id=3466/1472,enchant=200haste

trinket1=animated_exoskeleton,id=140789,bonus_id=3443/1477/3336

trinket2=royal_dagger_haft,id=140791,bonus_id=3443/1467/1813

main_hand=maw_of_the_damned,id=128402,bonus_id=716,gem_id=143682/140041/143705/0,relic_id=3473:1507:3336/3432:1497:1674/3474:1507:1674/0,enchant=rune_of_the_stoneskin_gargoyle


# Gear Summary

# gear_ilvl=869.20

# gear_strength=13965

# gear_stamina=27423

# gear_crit_rating=8387

# gear_haste_rating=1908

# gear_mastery_rating=6293

# gear_versatility_rating=4011

# gear_avoidance_rating=394

# gear_armor=4242


This one is giving the errors that I gave in my previous message. I am not
sure what is wrong.

**Comment by navv1234** [comment]
Simulating blood death knights is not supported at this point in time.

**Comment by navv1234** [comment]
There is now a very basic default APL for Blood DKs, so at least they can be rudimentarily simulated.
