### ISSUE TITLE
[Warrior - Fury] Ring of Collapsing Futures

### ISSUE THREAD

**Issue by Synesthetix** [simulationcraft/simc#3610]
On-use for ring is not being activated. Looks like the line in the default action list is missing a comma.

actions+=/use_item,name=ring_of_collapsing_**futuresif**=equipped.ring_of_collapsing_futures&buff.battle_cry.up&buff.enrage.up&!buff.temptation.up

Simulationcraft Version: 715-01, git build 4e1343e

**Comment by Collisionc** [comment]
Whoops :D

**Comment by Collisionc** [comment]
Looks like I have fixed this in 710-02 - http://downloads.simulationcraft.org/?C=M;O=D

Top downloads
