### ISSUE TITLE
I dont see stats to scale in the options?

### ISSUE THREAD

**Issue by vanvlasselaerkevin** [simulationcraft/simc#3611]
so when i go into the options and go to the scaling tab.

the stats to scale square is empty, where normally should be stats too turn of or on.
Any know what i am doing wrong

**Comment by lgkern** [comment]
![image](https://cloud.githubusercontent.com/assets/495152/23658370/0c480652-0321-11e7-8d7e-5e0f4e455276.png)
Here it seems normal in the latest nightly. Can you try that version to see if the problem persists?

**Comment by vanvlasselaerkevin** [comment]
ah wonderfull its ok in the latest version.
