### ISSUE TITLE
SimCraft prioritize Nitro-Boost over second Potion

### ISSUE THREAD

**Issue by Partholan** [simulationcraft/simc#3613]
Version: SimCraft 715-01
Class: Warrior
Spec: Fury
Profession: Engineer
Enchantment: Nitro-Boost on Belt
Fight: Patchwork

On of the first points of the **standard** Fury APL is:
actions+=/use_item,name=goresmeared_abyssal_waistplate,if=buff.battle_cry.up&buff.enrage.up

With this i will get **one** use of "potion of old war" and **one** use of "nitro-boost" per fight (see abilities -> simple action stats).

If i delete this line and the enchantment on my belt i will get **two** uses of "potion of old war".

In my case this is an improvement of roughly 2%.

Dont know if this is just a fury problem, a warrior problem, a engineer problem (meele) or an overall engineer problem.

**Comment by lgkern** [comment]
@Collisionc The issue happens because in the warriors APL builder (https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_warrior.cpp#L4872) it skips for items called "nitro_boosts", but it should look for enchant or effect with that name instead.

**Comment by Sinnoh** [comment]
Same thing happens for paladins (Retribution). Tested in SimulationCraft 715-02, git build 3eb4aac;

**Comment by Collisionc** [comment]
Should be fixed for warrior/paladin.
