### ISSUE TITLE
Time dependency on a dps CD

### ISSUE THREAD

**Issue by Gengiwar** [simulationcraft/simc#3616]
hello everyone, first time here so hopefully won't make some stupid question or mistake :) so here it goes:

I'm an Enhancement shaman, and wanted to make a sim exp where I would change the APL in this way:

Cast our dps cd (doomwinds) only if you have a stormbringer proc (this seems simple enough) but hold it only for an X amount of time where I could change the time in order to optimize how long can you wait for a proc to cast doomwinds and not loose dps on the long run. 

From what I gather this time dependency is not easy to achieve and to be honest I am not savvy at all on the language of sims APL (and this is an understatement cuz basically i know nothing about it) but was hoping someone could help.

Thank you very much,
Cheers

**Comment by lgkern** [comment]
actions+=/spell_name,if=cooldown.cooldown_name.remains>X

**Comment by N1gh7h4wk** [comment]
I think what you want to do is something like
actions+=/variable,op=set,name=doomwindcheck,value=time,line_cd=59,if=cooldown.doomwind.up
actions+=/Doomwinds,if=buff.stormbringer.up|time-variable.doomwindcheck>X
this stores the actual sim time where your doomwind is ready once every doomwind gets off cd
then for doomwinds it checks for either the procc or the timedifference from doomwind ready to now, with X being your threshold up to how many seconds you would want to delay the cast
i didn't test it but it should work
