### ISSUE TITLE
[715-02] simc sometimes hangs when creating HTML report

### ISSUE THREAD

**Issue by Valdiralita** [simulationcraft/simc#3618]
Simulationcraft Version: 715-02 (build 11.03.2017)

I use the TCI.
I tried to create an HTML report but when it finished the simulation and created the report it hung. It will hang there forever until I kill the process. This happens maybe every 1 in 50 sims.

I used this command to generate a HTML report:
./simc apikey=<key> process_priority=low armory=eu,Blackmoore,Valdiralita calculate_scale_factors=1 html=./results/Valdiralita.html max_time=400 vary_combat_length=0.2 iterations=25000 threads=4 scale_only=agility,strength,intellect,crit_rating,haste_rating,mastery_rating,versatility_rating strict_gcd_queue=1 gcd_lag=0.05 gcd_lag_stddev=0.01 channel_lag=0.1 channel_lag_stddev=0.02 queue_lag=0.005 queue_lag_stddev=0.002 default_world_lag=0.05 default_world_lag_stddev=0.01

Log: http://pastebin.com/6bUFdNvD
Resulting HTML after killing process: http://pastebin.com/R0GrRYTv
CPU usage: http://i.imgur.com/RlZJ1rj.png

**Comment by scamille** [comment]
Might be fixed with the newer GUI library version we now use. Please try again with 8.0 nightly release.
