### ISSUE TITLE
[Trinket] Stormsinger Fulmination Charge showing wrong tooltip/using wrong values.

### ISSUE THREAD

**Issue by 5erade** [simulationcraft/simc#3620]
http://www.wowhead.com/item=137367/stormsinger-fulmination-charge&bonus=1552:1726:1808
ingame and on wowhead it shows 845 mastery per second at ilvl900 but in SimC it is showing as 1477 mastery per second. Does this mean it is causing my dps to be inflated?

########
priest="Realserade"
level=110
race=blood_elf
region=us
server=kiljaeden
role=
professions=alchemy=780/herbalism=383
talents=1211111
spec=shadow
artifact=47:0:0:0:0:764:1:765:1:766:1:767:3:768:1:769:1:770:1:771:3:772:3:773:3:774:3:775:3:776:3:777:3:778:3:779:1:1347:1:1381:20

head=,id=138313,bonus_id=3516/1497/3336
neck=,id=134492,enchant_id=5439,bonus_id=3536/1552/3337
shoulder=,id=138322,enchant_id=5883,bonus_id=3516/1487/1813
back=,id=133771,enchant_id=5436,bonus_id=3418/1547/3337
chest=,id=140848,bonus_id=3445/1502/3336
shirt=,id=89195
tabard=,id=23709
wrist=,id=140886,bonus_id=3516/1808/1487/1813,gem_id=130220
hands=,id=138310,enchant_id=5444,bonus_id=3516/1808/1487/1813,gem_id=130220
waist=,id=132864,bonus_id=3529/3530
legs=,id=138316,bonus_id=3516/1492/3336
feet=,id=140854,bonus_id=3445/1502/3336
finger1=,id=140897,enchant_id=5428,bonus_id=3517/1492/1813
finger2=,id=134487,enchant_id=5428,bonus_id=3536/1808/1542/3336,gem_id=130220
trinket1=,id=144259,bonus_id=3529/3530
trinket2=,id=137367,bonus_id=1552/1726/1808,gem_id=130222
main_hand=,id=128827,bonus_id=740,relic_id=3536:1552:3337/3445:1512:3337/3516:1502:3337,gem_id=137347/140818/140822/0
off_hand=,id=133958,relic_id=0/0,gem_id=0/0/0/0

**Comment by 5erade** [comment]
Nevermind looking through I saw
Stat Buff details

stat:mastery_rating
amount:845.36

So despite showing the wrong tooltip when mousing over it seems its only applying 845 in the Simulation.

**Comment by navv1234** [comment]
Wowhead tooltips, we don't have much control over those.

**Comment by 5erade** [comment]
Yep makes sense, Realized I should probably check inside the log to make sure what value was exactly being added. Sorry!
