### ISSUE TITLE
Results Tabs Named the Same when Queueing 3+ Simulations

### ISSUE THREAD

**Issue by kaizerfreak** [simulationcraft/simc#3621]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 715-02
for World of Warcraft 7.1.5 Live (wow build level 23360, git build 22bf567)

#### simc_gui.simc file or contents
http://pastebin.com/fuMFV6bG

#### Reproduction Steps:
Queue 3 or more simulations with different tab names. Once finished, all results tabs from 2nd onward will have the same name as the last queued simluation tab.

**Comment by Kamiray** [comment]
I'm having the same issue for the last couple of builds since nighthold. It's not really a dealbreaker and therefore not urgent but since it's an ongoing issue it annoys the shit out of me thinking about dealing with it in the future. 
pls fix1!!11!1111!!!!!
much appreciated <3

**Comment by navv1234** [comment]
This should definitely be fixed now. I guess I can take another look.

**Comment by Kamiray** [comment]
that's some badass response time.
thanks, i'm looking forward to it =)

**Comment by navv1234** [comment]
You are renaming the simulation tabs, right? The GUI will not automatically make the names unique for you.

**Comment by Kamiray** [comment]
I am. I create a new tab, name it myself, paste the code and qeue the sim while another sim is running. the last few results then have the same tab name, sometimes of the last tab qeued, sometimes the name of the one 'in between' and from there on up to the last one.
