### ISSUE TITLE
Demon Hunter CLI crash

### ISSUE THREAD

**Issue by dortmonger** [simulationcraft/simc#3622]
Hi all,
i'm running the legion-dev branch through the CLI. I've been able to run the DH before, 
i just updated the branch today and tried to run again, i got the following error

simc: class_modules/sc_demon_hunter.cpp:3784: virtual void {anonymous}::actions::attacks::death_sweep_t::execute(): Assertion `p() -> buff.metamorphosis -> check()' failed.

Here's my simc profile which i'm running
demonhunter="E"
level=110
race=blood_elf
region=us
server=hyjal
role=
professions=herbalism=800/tailoring=672
talents=2223311
spec=havoc
artifact=3:0:0:0:0:1000:3:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:2

head=,id=138378,bonus_id=3514/1477/3336
neck=,id=140898,bonus_id=3444/1482/1813
shoulder=,id=138380,enchant_id=5883,bonus_id=3514/1472/1813
back=,id=138375,bonus_id=3516/1492/3336
chest=,id=140865,bonus_id=3444/1482/1813
wrist=,id=140857,bonus_id=3514/42/1477/3336
hands=,id=140863,enchant_id=5444,bonus_id=3444/1482/1813
waist=,id=140858,bonus_id=3443/1472/3336
legs=,id=138379,bonus_id=3514/1472/1813
feet=,id=138949,bonus_id=3529/3530
finger1=,id=134542,enchant_id=5430,bonus_id=3417/1542/3337
finger2=,id=138854,enchant_id=5430,bonus_id=3458/3455,gem_id=130247
trinket1=,id=140794,bonus_id=3444/1482/1813
trinket2=,id=139329,bonus_id=1805/1487
main_hand=,id=127829,bonus_id=719,relic_id=3514:1487:3337/1805:1492:3336/3415:1522:3337,gem_id=140825/138226/137491/0
off_hand=,id=127830,relic_id=0/0,gem_id=0/0/0/0

copy="E leggo cloak"
back=,id=137066,enchant_id=5435,bonus_id=3458/3455
feet=,id=139200,bonus_id=1805/1492/3336

[DxDiag.txt](https://github.com/simulationcraft/simc/files/845481/DxDiag.txt)

**Comment by dortmonger** [comment]
This error does not occur if i remove the "copy" block, and just run as a single actor simulation.
I've made the "copy" block work before on my Rogue, is there some problem in my implementation?

**Comment by SagepathSReinhardt** [comment]
I am unable to replicate this.

**Comment by Zarania** [comment]
I am unable to replicate this.

**Comment by dortmonger** [comment]
i did a git pull again last night and the problem has gone away. thanks for your reply
