### ISSUE TITLE
Simcraft crashing while simming a particular talent/gear set up only

### ISSUE THREAD

**Issue by Emowyn** [simulationcraft/simc#3625]
I have run this talent and gear sim on 4 different builds you have released over the past week, with the same crashing. It seems to sim upto versatility or wdps then crash.
It works fine with other talents with gear the same and changing.

715-02 win32-b20a3cb Simulationcraft Version. Plus previous versions over the past week.

Simulationcraft is crashing dxdiag file -
[DxDiag.txt](https://github.com/simulationcraft/simc/files/847731/DxDiag.txt)

simc_gui.simc contents
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=25000
default_world_lag=0.05
max_time=450
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=6
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### Begin simulateText ###
hunter="Emojin"
level=110
race=troll
region=eu
server=draenor
role=
professions=alchemy=800/engineering=800
talents=3111132
spec=beast_mastery
artifact=56:0:0:0:0:868:3:869:3:870:3:871:3:872:3:873:3:874:3:875:3:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:3:1336:1:1368:20

head=,id=140870,bonus_id=3516/1492/3336
neck=,id=140899,enchant_id=5437,bonus_id=3514/1482/3336
shoulder=,id=144326,enchant_id=5900,bonus_id=3529/3530
back=,id=138368,enchant_id=5435,bonus_id=3516/1487/1813
chest=,id=138339,bonus_id=3514/1477/3336
shirt=,id=98543
wrist=,id=134296,bonus_id=3415/1808/1532/3337,gem_id=130219
hands=,id=138340,bonus_id=3514/1477/3336
waist=,id=137520,bonus_id=3536/1552/3337
legs=,id=138344,bonus_id=3514/1487/3337
feet=,id=140873,bonus_id=3514/1487/3337
finger1=,id=139236,enchant_id=5427,bonus_id=1805/1517/3337
finger2=,id=134487,enchant_id=5427,bonus_id=3509/1552/3337
trinket1=,id=144259,bonus_id=3529/3530
trinket2=,id=141482,bonus_id=1808/3466/1472,gem_id=130219
main_hand=,id=128861,bonus_id=726,relic_id=3510:1537:3337/3443:1467:1813/3444:1482:1813,gem_id=137313/140827/140815/0

### End simulateText ###
desired_targets=2
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

I have never posted here before so please excuse the complete and utter lack of knowledge, if I've missed anything you need pls let me know

Thank you for any help you can give
Emo

**Comment by nuoHep** [comment]
I'm like 99.5% sure this hits our Dire Beast maximum count (which is 8 atm) bacause that's Mantle + OwtP. Will have to bump it to 10 or so.

**Comment by Emowyn** [comment]
oh right, thank you so much for the speedy reply, I'm new to this and was worried i'd done something wrong, Cheers, have a fab day o/

**Comment by Collisionc** [comment]
Should be fixed in the newest downloads. :)
