### ISSUE TITLE
about the relic level 

### ISSUE THREAD

**Issue by YesonW** [simulationcraft/simc#3629]
this version can't read the real relic level！！！

#### simc_gui.simc file or contents
DPS Ranking:
 736751 100.0%  Raid
 736751  100.0%  崇髙的幻象

HPS Ranking:
      0 100.0%  Raid

Player: 崇髙的幻象 blood_elf demonhunter havoc 110
  DPS: 736750.6  DPS-Error=657.7/0.089%  DPS-Range=122800/16.7%  DPS-Convergence=70.4%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=40041.5  RPS-Out=18.3 RPS-In=18.3  Resource=(fury) Waiting=3.5 ApM=54.6
  Talents: 2223311
  Artifact: 3:0:0:0:0:1000:3:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:20
  Core Stats:    strength=8803|8478(8478)  agility=34428|32722(31617)  stamina=57859|57859(39903)  intellect=5328|5003(5003)  spirit=2|2(2)  health=3471540|3471540  mana=0|0
  Generic Stats: mastery=31.68%|30.37%(5476)  versatility=3.92%|3.92%(1862)  leech=0.00%|0.00%(0)  runspeed=8.65%|8.59%(1062)
  Spell Stats:   power=0|0(0)  hit=15.00%|15.00%(0)  crit=41.11%|41.11%(12044)  haste=11.55%|11.55%(4332)  speed=11.55%|11.55%  manareg=0|0(0)
  Attack Stats:  power=34428|32722(0)  hit=7.50%|7.50%(0)  crit=41.11%|41.11%(12044)  expertise=7.50%/7.50%|7.50%/7.50%(0)  haste=11.55%|11.55%(4332)  speed=11.55%|11.55%
  Defense Stats: armor=2394|2394(2394) miss=3.00%|3.00%  dodge=18.52%|17.97%(0)  parry=3.00%|3.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=1.96%|1.96%(1862)
  Priorities (actions.precombat):
    flask,type=flask_of_the_seventh_demon/food,type=nightborne_delicacy_platter
    augmentation,type=defiled/snapshot_stats/potion,name=old_war
    metamorphosis,if=!(talent.demon_reborn.enabled&talent.demonic.enabled)
  Priorities:
    auto_attack
    variable,name=pooling_for_meta,value=cooldown.metamorphosis.ready&(!talent.demonic.enabled|!cooldown.eye_beam.ready)&(!talent.chaos_blades.enabled|cooldown.chaos_blades.ready)&(!talent.nemesis.enabled|debuff.nemesis.up|cooldown.nemesis.ready)
    variable,name=blade_dance,value=talent.first_blood.enabled|spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2)
    variable,name=pooling_for_blade_dance,value=variable.blade_dance&fury-40<35-talent.first_blood.enabled*20&(spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2))
    variable,name=pooling_for_chaos_strike,value=talent.chaos_cleave.enabled&fury.deficit>40&!raid_event.adds.up&raid_event.adds.in<2*gcd
    call_action_list,name=cooldown
    pick_up_fragment,if=talent.demonic_appetite.enabled&fury.deficit>=35
    consume_magic
    vengeful_retreat,if=(talent.prepared.enabled|talent.momentum.enabled)&buff.prepared.down&buff.momentum.down
    fel_rush,if=(talent.momentum.enabled|talent.fel_mastery.enabled)&(!talent.momentum.enabled|(charges=2|cooldown.vengeful_retreat.remains>4)&buff.momentum.down)&(!talent.fel_mastery.enabled|fury.deficit>=25)&(charges=2|(raid_event.movement.in>10&raid_event.adds.in>10))
    fel_barrage,if=charges>=5&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    throw_glaive,if=talent.bloodlet.enabled&(!talent.momentum.enabled|buff.momentum.up)&charges=2
    felblade,if=fury<15&(cooldown.death_sweep.remains<2*gcd|cooldown.blade_dance.remains<2*gcd)
    death_sweep,if=variable.blade_dance
    fel_rush,if=charges=2&!talent.momentum.enabled&!talent.fel_mastery.enabled
    fel_eruption
    fury_of_the_illidari,if=(active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>55&(!talent.momentum.enabled|buff.momentum.up)
    eye_beam,if=talent.demonic.enabled&(talent.demon_blades.enabled|(talent.blind_fury.enabled&fury.deficit>=35)|(!talent.blind_fury.enabled&fury.deficit<30))&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    blade_dance,if=variable.blade_dance&(!talent.demonic.enabled|cooldown.eye_beam.remains>5)
    throw_glaive,if=talent.bloodlet.enabled&spell_targets>=2&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&(spell_targets>=3|raid_event.adds.in>recharge_time+cooldown)
    felblade,if=fury.deficit>=30+buff.prepared.up*8
    eye_beam,if=talent.blind_fury.enabled&(spell_targets.eye_beam_tick>desired_targets|fury.deficit>=35)
    annihilation,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8|buff.metamorphosis.remains<5)&!variable.pooling_for_blade_dance
    throw_glaive,if=talent.bloodlet.enabled&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&raid_event.adds.in>recharge_time+cooldown
    eye_beam,if=!talent.demonic.enabled&!talent.blind_fury.enabled&((spell_targets.eye_beam_tick>desired_targets&active_enemies>1)|(raid_event.adds.in>45&!variable.pooling_for_meta&buff.metamorphosis.down&(artifact.anguish_of_the_deceiver.enabled|active_enemies>1)&!talent.chaos_cleave.enabled))
    demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<gcd&fury.deficit>=20
    demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<2*gcd&fury.deficit>=45
    throw_glaive,if=buff.metamorphosis.down&spell_targets>=2
    chaos_strike,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8)&!variable.pooling_for_chaos_strike&!variable.pooling_for_meta&!variable.pooling_for_blade_dance&(!talent.demonic.enabled|!cooldown.eye_beam.ready|(talent.blind_fury.enabled&fury.deficit<35))
    fel_barrage,if=charges=4&buff.metamorphosis.down&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    fel_rush,if=!talent.momentum.enabled&raid_event.movement.in>charges*10
    demons_bite/throw_glaive,if=buff.out_of_range.up
    felblade,if=movement.distance|buff.out_of_range.up
    fel_rush,if=movement.distance>15|(buff.out_of_range.up&!talent.momentum.enabled)
    vengeful_retreat,if=movement.distance>15/throw_glaive,if=!talent.bloodlet.enabled
  Priorities (actions.cooldown):
    nemesis,target_if=min:target.time_to_die,if=raid_event.adds.exists&debuff.nemesis.down&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>60)
    nemesis,if=!raid_event.adds.exists&(cooldown.metamorphosis.remains>100|target.time_to_die<70)
    nemesis,sync=metamorphosis,if=!raid_event.adds.exists
    chaos_blades,if=buff.metamorphosis.up|cooldown.metamorphosis.remains>100|target.time_to_die<20
    metamorphosis,if=variable.pooling_for_meta&fury.deficit<30
    potion,name=old_war,if=buff.metamorphosis.remains>25|target.time_to_die<30
  Actions:
    anguish                Count=  0.0|  0.00sec  DPE=      0| 1%  DPET=      0  DPR=     0.0  pDPS=  7352  Miss=0.00%  Hit=262489|215776|444792  Crit=525370|431552|889585|42.6%
    annihilation           Count= 31.1|  8.02sec  DPE=1068611|15%  DPET=1198920  DPR= 26712.8  pDPS=109516  Miss=0.00%  Hit=323743|249506|518568  Crit=725202|558894|1161592|52.6%
    auto_attack_mh         Count=126.4|  2.30sec  DPE=  39025| 2%  DPET=  19679  DPR=     0.0  pDPS= 16194  Miss=18.96%  Hit=31510|27948|34934  Crit=63054|55895|69869|42.8%
    auto_attack_oh         Count=126.4|  2.30sec  DPE=  19515| 1%  DPET=   9844  DPR=     0.0  pDPS=  8099  Miss=19.00%  Hit=15761|13974|17467  Crit=31519|27948|34934|42.8%
    blade_dance            Count= 28.0|  9.74sec  DPE= 820338|10%  DPET= 648726  DPR= 54691.1  pDPS= 75450  Miss=0.00%  Hit=143877|84435|466592  Crit=287718|168869|933185|42.7%
    chaos_blade_mh         Count= 21.1| 13.16sec  DPE= 322416| 3%  DPET= 219099  DPR=     0.0  pDPS= 22678  Miss=0.00%  Hit=225694|222635|278812  Crit=451493|445269|557623|42.8%
    chaos_blade_oh         Count= 21.1| 13.16sec  DPE= 161213| 2%  DPET= 109554  DPR=     0.0  pDPS= 11337  Miss=0.00%  Hit=112906|111317|139406  Crit=225836|222635|278812|42.8%
    chaos_blades           Count=  3.1|125.00sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=     0  TickCount=55  UpTime=11.8%
    chaos_strike           Count= 86.2|  3.06sec  DPE= 651751|25%  DPET= 512493  DPR= 16294.1  pDPS=185431  Miss=0.00%  Hit=197210|153664|398396  Crit=441610|344208|892407|52.8%
    death_sweep            Count= 11.1| 24.15sec  DPE=1531429| 8%  DPET=1733728  DPR=102087.4  pDPS= 55854  Miss=0.00%  Hit=268511|157216|695028  Crit=536936|314431|1390056|42.8%
    demon_blades           Count=148.1|  2.69sec  DPE=  76716| 5%  DPET=      0  DPR=     0.0  pDPS= 37456  Miss=0.00%  Hit=53701|44104|81240  Crit=107425|88208|162481|42.8%
    eye_beam               Count=  6.0| 48.39sec  DPE=1295915| 3%  DPET= 685426  DPR= 25918.4  pDPS= 18381  TickCount=60  MissTick=0.0%  CritTick=92845|75625|155890|100.0%  UpTime=3.3%
    fel_rush               Count= 30.5| 10.02sec  DPE= 291089| 4%  DPET= 720505  DPR=     0.0  pDPS= 29209  Miss=0.00%  Hit=203672|171283|353076  Crit=407655|342566|706153|42.9%
    felblade               Count= 40.8|  7.65sec  DPE= 405541| 7%  DPET= 345548  DPR=     0.0  pDPS= 54451  Miss=0.00%  Hit=283662|234335|431652  Crit=567664|468671|863303|42.9%
    fury_of_the_illidari   Count=  5.6| 60.46sec  DPE=1963143| 3%  DPET=1666401  DPR=     0.0  pDPS= 22682  TickCount=39  MissTick=0.0%  Tick=61872|30857|127214  CritTick=123803|61714|254428|42.9%  UpTime=5.5%
    inner_demons           Count=  6.1| 45.61sec  DPE= 618648| 2%  DPET=      0  DPR=     0.0  pDPS= 12437  Miss=0.00%  Hit=434254|350636|722788  Crit=868682|701271|1445576|43.2%
    metamorphosis_impact   Count=  1.9|  0.00sec  DPE= 186613| 0%  DPET=      0  DPR=     0.0  pDPS=  1171  Miss=0.00%  Hit=130941|116519|162992  Crit=262220|233038|325984|42.4%
    nemesis                Count=  3.1|120.37sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=     0
    potion                 Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=      0  DPR=     0.0  pDPS=     0
    potion_of_the_old_war  Count= 27.7| 10.19sec  DPE= 229440| 3%  DPET=      0  DPR=     0.0  pDPS= 21124  Miss=0.00%  Hit=160647|137516|202646  Crit=321345|275032|405292|42.8%
    rage_of_the_illidari   Count=  5.5| 60.46sec  DPE= 742424| 2%  DPET=      0  DPR=     0.0  pDPS= 13496  Miss=0.00%  Hit=742414|388796|1526570
    symbiote_strike        Count= 55.3|  0.24sec  DPE=  71568| 2%  DPET=      0  DPR=     0.0  pDPS= 13070  Miss=0.00%  Hit=71554|7704|388779
    throw_glaive           Count= 24.8| 11.38sec  DPE= 263517| 3%  DPET= 216961  DPR=     0.0  pDPS= 21362  Miss=0.00%  Hit=184831|160393|295448  Crit=369813|320786|590895|42.6%
  Constant Buffs: defiled_augmentation/flask_of_the_seventh_demon/nightborne_delicacy_platter
  Dynamic Buffs:
    arcane_enchant        : start= 1.2 refresh=  0.1 interval=105.2 trigger= 88.2 uptime= 8.17%  benefit= 8%
    blade_dance           : start=28.0 refresh=  0.0 interval=  9.7 trigger=  9.7 uptime= 9.17%  benefit= 9%
    blood_frenzy          : start=10.8 refresh=  6.6 interval= 28.4 trigger= 17.1 uptime=45.03%  benefit=45%
    bloodlust             : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.39%  benefit=15%
    chaos_blades          : start= 3.1 refresh=  0.0 interval=122.8 trigger=125.0 uptime=11.93%  benefit=16%
    death_sweep           : start=11.1 refresh=  0.0 interval= 24.2 trigger= 24.2 uptime= 3.63%  benefit= 4%
    fel_rush_movement     : start=30.5 refresh=  0.0 interval= 10.0 trigger= 10.0 uptime= 2.50%  benefit= 3%
    fiery_enchant         : start= 1.2 refresh=  0.1 interval=104.2 trigger= 86.4 uptime= 8.26%  benefit= 8%
    frost_enchant         : start= 1.2 refresh=  0.1 interval=106.5 trigger= 88.8 uptime= 8.01%  benefit= 8%
    mark_of_the_claw      : start=13.2 refresh=  4.3 interval= 23.1 trigger= 17.1 uptime=29.89%  benefit=30%
    metamorphosis         : start= 1.9 refresh=  0.2 interval=245.3 trigger=127.0 uptime=17.77%  benefit=27%
    nemesis_buff          : start= 0.6 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 0.00%
    potion_of_the_old_war : start= 2.0 refresh=  0.0 interval=242.7 trigger=  0.0 uptime=15.45%  benefit=15%
    rage_of_the_illidari  : start= 5.6 refresh= 72.0 interval= 60.5 trigger=  3.6 uptime= 5.48%  benefit= 5%
  Up-Times:
      2.0% : Fury Cap                      
  Procs:
      7.3 |  67.22sec : delayed_swing__channeling
     32.5 |   9.43sec : felblade_reset
  Gains:
       620.5 : anger_of_the_half_giants (fury)  (overflow=6.8%)
      2444.7 : demon_blades             (fury)  (overflow=3.5%)
      1343.5 : felblade_dmg             (fury)
       323.8 : annihilation             (fury)
       906.4 : chaos_strike             (fury)
  Scale Factors:
    Weights :  Agi=0.00(0.00)  AP=0.00(0.00)  Crit=16.44(0.71)  Haste=14.22(0.72)  Mastery=17.00(0.73)  Vers=14.88(0.72)  Wdps=0.00(0.00)  WOHdps=0.00(0.00)
    Wowhead : 
  Waiting: 3.52%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|264977384  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:

  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.62%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.91%  benefit=10%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.82%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.32%  benefit=13%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.83%  benefit=12%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.35%  benefit=12%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=14.18%  benefit=14%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.38%  benefit= 9%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.94%  benefit= 5%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 2.66%  benefit= 3%
    anguish                  : start= 6.0 refresh= 54.2 interval= 48.4 trigger=  4.1 uptime= 6.85%  benefit= 7%
    nemesis                  : start= 3.1 refresh=  0.0 interval=120.3 trigger=120.4 uptime=54.23%  benefit=59%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
     3.5% : 崇髙的幻象

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10007
  TotalEvents   = 30092983
  MaxEventQueue = 38
  TargetHealth  = 264977384
  SimSeconds    = 3045520
  CpuSeconds    = 34.719
  WallSeconds   = 4.476
  SpeedUp       = 87720
  EndTime       = 2017-03-19 01:02:23+0800 (1489856543)

Scale Factors:
  崇髙的幻象  Agi=0.00(0.00)  AP=0.00(0.00)  Crit=16.44(0.71)  Haste=14.22(0.72)  Mastery=17.00(0.73)  Vers=14.88(0.72)  Wdps=0.00(0.00)  WOHdps=0.00(0.00)

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by navv1234** [comment]
Leave a reply if this is still an issue. Presuming an intermittent issue with the eastern Blizzard API. Closing.
