### ISSUE TITLE
Make talents= consistent with wow armory

### ISSUE THREAD

**Issue by Heanthor** [simulationcraft/simc#3630]
#### Simulationcraft Version

Most recent, 715-02 bdd3ba8

#### simc_gui.simc file or contents
Doesn't appear to happen in GUI..

#### Reproduction Steps:
On Windows 10, the TCI string I'm using to trigger this is "armory=US,Fizzcrank,Thanaton spec=elemental talents=0001220 fight_style=HecticAddCleave". I get an infinite loop of errors such as

```Simulation has been forcefully cancelled at 600.00 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 599.96 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 599.28 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 601.06 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 598.91 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 598.82 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 601.45 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 601.64 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 602.29 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 602.51 because twice the expected combat length has been exceeded.
Simulation has been forcefully cancelled at 597.20 because twice the expected combat length has been exceeded...
```
forcing me to ctrl-C.

Tried with another shaman (armory=US,Fizzcrank,Giasham spec=elemental talents=0001220 fight_style=HecticAddCleave), same problem happened.

**Comment by Collisionc** [comment]
talents=0001220  is the problem, 0 means no talent, and since the action list is based on which level 100 talent the shaman uses, it doesn't work.

**Comment by Heanthor** [comment]
I was under the impression the talented are 0-indexed, so 0 is the first column, 1 is the second, etc.
When I import Thanaton entirely from the armory, his talent string is http://US.battle.net/wow/en/tool/talent-calculator#Wa!0001220, seemingly the same talents

I do see that the error does not happen when I remove the talent string from the arguments. If the talents are the same as those imported from the armory, isn't this a bug?

**Comment by Collisionc** [comment]
They are from the armory, they aren't when using talents= 

It's one of those oddities from early burning crusade that we never changed, we probably should make the armory and our talents= mean the same thing.

**Comment by Heanthor** [comment]
Oh 😓 that's pretty confusing. So, is the equivalent simc string 1-based, like 1112331?

**Comment by Collisionc** [comment]
Yeah, but don't get used to it, I'll see if there's a reason why we do it that way, and if there really isn't I'm probably going to make it work like the armory.

**Comment by Heanthor** [comment]
Cool, thanks. I've been writing an automated sim tool, and I bet all my results thus far are total garbage because I've been using 0-based indexing for talents. How did I not notice this sooner..

**Comment by navv1234** [comment]
The generated talents= url (for armory) should now be fully consistent with the new talent calculator for armory. Furthermore, Blizzard's new talent calculator uses essentially the same format as simc (i.e., 0 disabled, 1, 2, 3 selects the left, middle, or right column, respectively).
