### ISSUE TITLE
can't build simc on current commit

### ISSUE THREAD

**Issue by nezorflame** [simulationcraft/simc#3631]
trying to build from source on Debian on commit https://github.com/simulationcraft/simc/commit/81a8e394b1cc874c62aa6a30814bf033f802864f

log output:
```
...
[simc] Compiling sc_unique_gear.cpp
player/sc_unique_gear.cpp: In function ‘void {anonymous}::item::warlords_unseeing_eye(special_effect_t&)’:
player/sc_unique_gear.cpp:3579:40: error: ‘class std::map<unsigned int, instant_absorb_t>’ has no member named ‘emplace’
make: *** [player/sc_unique_gear.o] Error 1
```

**Comment by scamille** [comment]
What compiler version are you using? (g++ -v)

Oh and what Debian version?

The problem here is some C++11 or C++14 usage, I think.

**Comment by nezorflame** [comment]
Debian 7.11
gcc version 4.7.2 (Debian 4.7.2-5)
Full output:
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)
```

**Comment by scamille** [comment]
Problem is described here: http://stackoverflow.com/a/15813328

I'll fix, since debian wheezy is a LTS release. But be aware that this might change and we might upgrade to a minimal requirement of GCC4.8 at some point.

**Comment by nezorflame** [comment]
alright, but please announce when it's happening to make sure we update our tools.

**Comment by scamille** [comment]
Should be fixed with 71c8a40305e7fdde5b9d9bf6e09490deeaaff7d8

**Comment by scamille** [comment]
Well May 2018 would be a good date, since LTS release ends then.

The problem here is that with such special language/STL restrictions is the extra burden it puts on the developers, since we need to remember that we cannot yet use those features, and most of us already use newer, fully C++11 compliant compilers, where the problem does not show up at all.

**Comment by nezorflame** [comment]
well, personally I'm OK with that & you can still move to a newer chain before the end of LTS, just make sure to inform us about that.
thanks for clarification!

**Comment by navv1234** [comment]
Just fyi, you may need to be aware of occasional breakage. We have moved to full C++11 a while back, and a lot of our class modules developers are not experts with the c++ versioning (and occasionally platform specific support).

**Comment by nezorflame** [comment]
ok, guess I'll update to 4.8 anyway in that case.

**Comment by scamille** [comment]
2017-05-01 it is then (Ubuntu 12.04 LTS end of support in April 2017).
