### ISSUE TITLE
[Rogue] Second Garrote with Nightstalker

### ISSUE THREAD

**Issue by schnello** [simulationcraft/simc#3632]
#### Simulationcraft Version

SimulationCraft 715-02
for World of Warcraft 7.1.5 Live (wow build level 23360, git build c655bf0)

#### simc_gui.simc file or contents

#!./simc
fight_style=LightMovement
enemy=Add1
enemy=Add2
enemy=Add3

#### Reproduction Steps:

Hello.

I start a simulation with 3 Targets.

The talents for the rogue are:
![image](https://cloud.githubusercontent.com/assets/6481341/24116453/25d9d5f6-0da7-11e7-84e7-378672a361fe.png)

The problem:
It should not possible to add a second garrote in 2 seconds with the talent "Nightstalker". This is only possible with "Subterfuge"

![image](https://cloud.githubusercontent.com/assets/6481341/24116500/4b97afb6-0da7-11e7-9b53-e5393258363b.png)

**Comment by aethys256** [comment]
Thanks I'll look into.

**Comment by aethys256** [comment]
I just tested it, it works fine for me. Is it possible for you to use one of the latest nightlies (there were some things about buffs recently) and try it again ?
Also if you can attach the html report it would be nice :)

**Comment by schnello** [comment]
Hello.

Sorry but what is a nightly? :)
I clone and rebuild simc on a ubuntu station.

>Also if you can attach the html report it would be nice :)

the report: http://uplink.spdns.eu/issue
the simc file: http://uplink.spdns.eu/default.simc 


I update the simc git folder and rebuild simc. Same problem:
![image](https://cloud.githubusercontent.com/assets/6481341/24193567/fd29bf8e-0ef2-11e7-9bec-dd2f7867c6ee.png)
