### ISSUE TITLE
Transfer server bug?

### ISSUE THREAD

**Issue by turgorr** [simulationcraft/simc#3634]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
64bit jan 17 installer

Used to sim around 740k dps with stat weights around 15-20.

Transferred servers, now i sim at 400k dps with 7-9 stat weights with the exact same gear

**Comment by Collisionc** [comment]
Please link your armory so we can test it.

**Comment by turgorr** [comment]
http://us.battle.net/wow/en/character/tichondrius/Turgorr/advanced

**Comment by navv1234** [comment]
Chalk this up to Blizzard api issues associated with server transfers. Closing.
