### ISSUE TITLE
Cannot run simc profile when building from source on Amazon AMI Linux

### ISSUE THREAD

**Issue by phroph** [simulationcraft/simc#3635]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
Building from legion-dev source on Linux.

#### simc_gui.simc file or contents

Profiles can be found here:
https://gist.github.com/phroph/7b91370eba2af86931b09de946f5404a#file-altrius-simc-L8

#### Reproduction Steps:

Using the Amazon EC2 Linux AMI (which uses Yum, not Aptitude), `yum groupinstall "Development Tools"` and `yum install openssl-devel`

Now build from source as described in Wiki. Source compilation succeeds. Now run the supplied simc profile (IE: "simc Altrius_250_patchwerk_na_st.simc") and we see the output 

> ERROR! Incorrect option format: Unexpected parameter 'Altrius_250_patchwerk_na_st.simc'. Expected format: name=value

**Comment by phroph** [comment]
After talking with Anshlun (who talked to Navv), it looks like prepending '$(pwd)/' works and causes the profile to properly execute.

(I'll leave it up to your discretion to close this as mitigated or whether you want to keep it open and fix this so it doesn't require user mitigation)

**Comment by navv1234** [comment]
I'll close for now, probably some weird issue in the environment that is hard to replicate outside of it.
