### ISSUE TITLE
Crash Sc64 at load

### ISSUE THREAD

**Issue by kitefly13** [simulationcraft/simc#3636]
Hi and thanks for you program

On my computer W10 when i open SC64 V715-01, SC crash (picture 1) and i must to  kill the program 

I send my Dxdiag and screenshot 
I try the 3 solutions on your site for crash problem
![screenshot](https://cloud.githubusercontent.com/assets/26619928/24237533/f5c197c6-0fa6-11e7-8a08-c9da7514dda9.jpg)

Thanks 

Herve France
[DxDiag.txt](https://github.com/simulationcraft/simc/files/863968/DxDiag.txt)

**Comment by Collisionc** [comment]
See if the newer versions of simc fix this - http://downloads.simulationcraft.org/?C=M;O=D

**Comment by kitefly13** [comment]
same problem

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
