### ISSUE TITLE
Nothing to sim error, ability priorities messed up

### ISSUE THREAD

**Issue by Oldalf** [simulationcraft/simc#3637]
This is what i get in the logs. The note worthy stuff is that for action priorities it lists abilities only available to havoc demon hunter (which is my main and the one i sim the most) but the abilities also show up now when trying to sim my rogue.

Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Have you actually imported your toon to create the profile for your Rogue?

**Comment by Oldalf** [comment]
I use the in game addon(checked to make sure that it was up to date) and copied the result from a "/simc" into simulationcraft. I assume that's the importing that you refer to or did i miss doing something?

edit: looking back at the main issue text there's quite a lot of error text that was generated that didn't make it into it. I'll make sure to copy and paste it properly once i get home

**Comment by Oldalf** [comment]
Missed updating it sorry. I got the same error minus the ability priority being for the wrong class when simming my Demon hunter as well. These are the logs:

SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Nothing to sim!

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```


DPS Ranking:
 543023 100.0%  Raid
 543023  100.0%  Dimonda

HPS Ranking:
      0 100.0%  Raid

Player: Dimonda blood_elf demonhunter havoc 110
  DPS: 543023.4  DPS-Error=505.2/0.093%  DPS-Range=82171/15.1%  DPS-Convergence=72.6%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=33371.5  RPS-Out=16.2 RPS-In=16.2  Resource=(fury) Waiting=6.0 ApM=52.1
  Origin: https://eu.api.battle.net/wow/character/kazzak/dimonda/advanced
  Talents: http://us.battle.net/wow/en/tool/talent-calculator#ga!1112200
  Artifact: 3:0:0:0:0:1000:1:1001:3:1002:3:1003:3:1004:3:1005:3:1006:3:1007:3:1008:3:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:4
  Core Stats:    strength=8803|8478(8478)  agility=29457|27750(26882)  stamina=45059|45059(34266)  intellect=5328|5003(5003)  spirit=2|2(2)  health=2703540|2703540  mana=0|0
  Generic Stats: mastery=39.47%|38.15%(7701)  versatility=2.11%|2.11%(1003)  leech=2.80%|2.80%(644)  runspeed=8.97%|8.91%(0)
  Spell Stats:   power=0|0(0)  hit=15.00%|15.00%(0)  crit=41.55%|41.55%(12221)  haste=10.15%|10.15%(3808)  speed=10.15%|10.15%  manareg=0|0(0)
  Attack Stats:  power=29457|27750(0)  hit=7.50%|7.50%(0)  crit=41.55%|41.55%(12221)  expertise=7.50%/7.50%|7.50%/7.50%(0)  haste=10.15%|10.15%(3808)  speed=10.15%|10.15%
  Defense Stats: armor=2186|2186(2186) miss=3.00%|3.00%  dodge=16.81%|16.13%(0)  parry=3.00%|3.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=1.06%|1.06%(1003)
  Priorities (actions.precombat):
    flask,type=flask_of_the_seventh_demon/food,type=nightborne_delicacy_platter
    augmentation,type=defiled/snapshot_stats/potion,name=old_war
    metamorphosis,if=!(talent.demon_reborn.enabled&talent.demonic.enabled)
  Priorities:
    auto_attack
    variable,name=pooling_for_meta,value=cooldown.metamorphosis.ready&(!talent.demonic.enabled|!cooldown.eye_beam.ready)&(!talent.chaos_blades.enabled|cooldown.chaos_blades.ready)&(!talent.nemesis.enabled|debuff.nemesis.up|cooldown.nemesis.ready)
    variable,name=blade_dance,value=talent.first_blood.enabled|spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2)
    variable,name=pooling_for_blade_dance,value=variable.blade_dance&fury-40<35-talent.first_blood.enabled*20&(spell_targets.blade_dance1>=3+(talent.chaos_cleave.enabled*2))
    variable,name=pooling_for_chaos_strike,value=talent.chaos_cleave.enabled&fury.deficit>40&!raid_event.adds.up&raid_event.adds.in<2*gcd
    call_action_list,name=cooldown
    pick_up_fragment,if=talent.demonic_appetite.enabled&fury.deficit>=35
    consume_magic
    vengeful_retreat,if=(talent.prepared.enabled|talent.momentum.enabled)&buff.prepared.down&buff.momentum.down
    fel_rush,if=(talent.momentum.enabled|talent.fel_mastery.enabled)&(!talent.momentum.enabled|(charges=2|cooldown.vengeful_retreat.remains>4)&buff.momentum.down)&(!talent.fel_mastery.enabled|fury.deficit>=25)&(charges=2|(raid_event.movement.in>10&raid_event.adds.in>10))
    fel_barrage,if=charges>=5&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    throw_glaive,if=talent.bloodlet.enabled&(!talent.momentum.enabled|buff.momentum.up)&charges=2
    felblade,if=fury<15&(cooldown.death_sweep.remains<2*gcd|cooldown.blade_dance.remains<2*gcd)
    death_sweep,if=variable.blade_dance
    fel_rush,if=charges=2&!talent.momentum.enabled&!talent.fel_mastery.enabled
    fel_eruption
    fury_of_the_illidari,if=(active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>55&(!talent.momentum.enabled|buff.momentum.up)
    eye_beam,if=talent.demonic.enabled&(talent.demon_blades.enabled|(talent.blind_fury.enabled&fury.deficit>=35)|(!talent.blind_fury.enabled&fury.deficit<30))&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    blade_dance,if=variable.blade_dance&(!talent.demonic.enabled|cooldown.eye_beam.remains>5)
    throw_glaive,if=talent.bloodlet.enabled&spell_targets>=2&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&(spell_targets>=3|raid_event.adds.in>recharge_time+cooldown)
    felblade,if=fury.deficit>=30+buff.prepared.up*8
    eye_beam,if=talent.blind_fury.enabled&(spell_targets.eye_beam_tick>desired_targets|fury.deficit>=35)
    annihilation,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8|buff.metamorphosis.remains<5)&!variable.pooling_for_blade_dance
    throw_glaive,if=talent.bloodlet.enabled&(!talent.master_of_the_glaive.enabled|!talent.momentum.enabled|buff.momentum.up)&raid_event.adds.in>recharge_time+cooldown
    eye_beam,if=!talent.demonic.enabled&!talent.blind_fury.enabled&((spell_targets.eye_beam_tick>desired_targets&active_enemies>1)|(raid_event.adds.in>45&!variable.pooling_for_meta&buff.metamorphosis.down&(artifact.anguish_of_the_deceiver.enabled|active_enemies>1)&!talent.chaos_cleave.enabled))
    demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<gcd&fury.deficit>=20
    demons_bite,if=talent.demonic.enabled&!talent.blind_fury.enabled&buff.metamorphosis.down&cooldown.eye_beam.remains<2*gcd&fury.deficit>=45
    throw_glaive,if=buff.metamorphosis.down&spell_targets>=2
    chaos_strike,if=(talent.demon_blades.enabled|!talent.momentum.enabled|buff.momentum.up|fury.deficit<30+buff.prepared.up*8)&!variable.pooling_for_chaos_strike&!variable.pooling_for_meta&!variable.pooling_for_blade_dance&(!talent.demonic.enabled|!cooldown.eye_beam.ready|(talent.blind_fury.enabled&fury.deficit<35))
    fel_barrage,if=charges=4&buff.metamorphosis.down&(buff.momentum.up|!talent.momentum.enabled)&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>30)
    fel_rush,if=!talent.momentum.enabled&raid_event.movement.in>charges*10
    demons_bite/throw_glaive,if=buff.out_of_range.up
    felblade,if=movement.distance|buff.out_of_range.up
    fel_rush,if=movement.distance>15|(buff.out_of_range.up&!talent.momentum.enabled)
    vengeful_retreat,if=movement.distance>15/throw_glaive,if=!talent.bloodlet.enabled
  Priorities (actions.cooldown):
    nemesis,target_if=min:target.time_to_die,if=raid_event.adds.exists&debuff.nemesis.down&((active_enemies>desired_targets&active_enemies>1)|raid_event.adds.in>60)
    nemesis,if=!raid_event.adds.exists&(cooldown.metamorphosis.remains>100|target.time_to_die<70)
    nemesis,sync=metamorphosis,if=!raid_event.adds.exists
    chaos_blades,if=buff.metamorphosis.up|cooldown.metamorphosis.remains>100|target.time_to_die<20
    metamorphosis,if=variable.pooling_for_meta&fury.deficit<30
    potion,name=old_war,if=buff.metamorphosis.remains>25|target.time_to_die<30
  Actions:
    anguish                   Count=  0.0|  0.00sec  DPE=      0| 1%  DPET=      0  DPR=    0.0  pDPS=  5957  Miss=0.00%  Hit=214976|178707|311544  Crit=430683|357414|623089|41.6%
    annihilation              Count= 27.4|  9.24sec  DPE= 814572|14%  DPET= 890534  DPR=20363.3  pDPS= 73636  Miss=0.00%  Hit=282405|213213|374768  Crit=615556|464804|816994|40.2%  Parry=3.0%
    auto_attack_mh            Count=122.7|  2.37sec  DPE=  30071| 2%  DPET=  14730  DPR=    0.0  pDPS= 12125  Miss=19.06%  Hit=25160|15757|28137  Crit=50313|31514|56275|41.6%  Parry=3.0%
    auto_attack_oh            Count=122.7|  2.37sec  DPE=  15023| 1%  DPET=   7361  DPR=    0.0  pDPS=  6057  Miss=19.08%  Hit=12578|7878|14069  Crit=25155|15757|28137|41.5%  Parry=3.0%
    blade_dance               Count= 27.1| 10.04sec  DPE= 632179|10%  DPET= 485379  DPR=42146.1  pDPS= 56300  Miss=0.00%  Hit=115306|47688|356296  Crit=230546|95376|712592|40.3%  Parry=3.0%
    chaos_blade_mh            Count= 19.9| 14.08sec  DPE= 279133| 3%  DPET= 190474  DPR=    0.0  pDPS= 18513  Miss=0.00%  Hit=201143|201143|201143  Crit=402285|402285|402285|41.8%  Parry=3.0%
    chaos_blade_oh            Count= 19.9| 14.08sec  DPE= 139305| 2%  DPET=  95061  DPR=    0.0  pDPS=  9239  Miss=0.00%  Hit=100571|100571|100571  Crit=201143|201143|201143|41.5%  Parry=3.0%
    chaos_blades              Count=  3.1|124.84sec  DPE=      0| 0%  DPET=      0  DPR=    0.0  pDPS=     0  TickCount=53  UpTime=11.7%
    chaos_strike              Count= 74.2|  3.54sec  DPE= 483074|22%  DPET= 368869  DPR=12077.2  pDPS=118291  Miss=0.00%  Hit=167343|131312|287920  Crit=364854|286261|627665|40.2%  Parry=3.0%
    death_sweep               Count= 10.8| 25.02sec  DPE=1214242| 8%  DPET=1346796  DPR=80945.8  pDPS= 43258  Miss=0.00%  Hit=221086|88794|530733  Crit=443265|177588|1061465|40.3%  Parry=3.0%
    demon_blades              Count=137.9|  2.87sec  DPE=  57231| 5%  DPET=      0  DPR=    0.0  pDPS= 26038  Miss=0.00%  Hit=41681|33863|59035  Crit=83387|67726|118069|40.3%  Parry=3.0%
    eye_beam                  Count=  6.0| 48.65sec  DPE=1141389| 3%  DPET= 590569  DPR=22827.8  pDPS= 16604  TickCount=60  MissTick=0.0%  CritTick=84251|69003|120295|100.0%  UpTime=3.3%
    fel_rush                  Count= 30.8|  9.92sec  DPE= 233387| 4%  DPET= 577581  DPR=    0.0  pDPS= 23685  Miss=0.00%  Hit=169943|141858|247304  Crit=339274|283715|494608|40.4%  Parry=2.9%
    felblade                  Count= 39.6|  7.88sec  DPE= 318004| 8%  DPET= 263354  DPR=    0.0  pDPS= 41515  Miss=0.00%  Hit=231638|189073|329616  Crit=463448|378147|659232|41.5%
    fury_of_the_illidari      Count=  5.6| 60.46sec  DPE=1630093| 4%  DPET=1346669  DPR=    0.0  pDPS= 19097  TickCount=39  MissTick=0.0%  Tick=54069|26368|91937  CritTick=108246|52737|183875|40.3%  UpTime=5.5%
    inner_demons              Count=  5.9| 46.67sec  DPE= 509463| 2%  DPET=      0  DPR=    0.0  pDPS=  9870  Miss=0.00%  Hit=359932|290399|506259  Crit=723210|580798|1012519|41.8%
    mark_of_the_hidden_satyr  Count= 17.9| 16.98sec  DPE= 136672| 1%  DPET=      0  DPR=    0.0  pDPS=  8074  Miss=0.00%  Hit=96538|80085|139615  Crit=193282|160171|279230|41.5%
    metamorphosis_impact      Count=  1.9|  0.00sec  DPE= 153126| 0%  DPET=      0  DPR=    0.0  pDPS=   965  Miss=0.00%  Hit=107892|96502|120627  Crit=216090|193004|241254|41.8%
    nemesis                   Count=  3.1|120.39sec  DPE=      0| 0%  DPET=      0  DPR=    0.0  pDPS=     0
    potion                    Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=      0  DPR=    0.0  pDPS=     0
    potion_of_the_old_war     Count= 26.7| 10.66sec  DPE= 257515| 4%  DPET=      0  DPR=    0.0  pDPS= 22863  Miss=0.00%  Hit=187207|87977|219104  Crit=374525|175955|438209|40.5%  Parry=3.0%
    rage_of_the_illidari      Count=  5.5| 60.46sec  DPE= 604316| 2%  DPET=      0  DPR=    0.0  pDPS= 11005  Miss=0.00%  Hit=623718|268957|1158410  Parry=3.1%
    throw_glaive              Count= 29.5|  9.79sec  DPE= 206037| 4%  DPET= 166716  DPR=    0.0  pDPS= 19931  Miss=0.00%  Hit=150159|90589|225608  Crit=300507|181177|451216|40.2%  Parry=3.0%
  Constant Buffs: defiled_augmentation/flask_of_the_seventh_demon/nightborne_delicacy_platter
  Dynamic Buffs:
    blade_dance           : start=27.1 refresh=  0.0 interval= 10.0 trigger= 10.0 uptime= 8.88%  benefit= 9%
    blood_frenzy          : start=10.9 refresh=  6.6 interval= 28.2 trigger= 17.1 uptime=45.39%  benefit=45%
    bloodlust             : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.40%  benefit=17%
    chaos_blades          : start= 3.1 refresh=  0.0 interval=122.8 trigger=125.0 uptime=11.92%  benefit=12%
    death_sweep           : start=10.8 refresh=  0.0 interval= 25.0 trigger= 25.0 uptime= 3.55%  benefit= 4%
    fel_rush_movement     : start=30.8 refresh=  0.0 interval=  9.9 trigger=  9.9 uptime= 2.53%  benefit= 3%
    metamorphosis         : start= 1.9 refresh=  0.0 interval=245.1 trigger=  0.0 uptime=17.75%  benefit=27%
    nemesis_buff          : start= 0.7 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 0.00%
    potion_of_the_old_war : start= 2.0 refresh=  0.0 interval=243.1 trigger=  0.0 uptime=15.31%  benefit=15%
    rage_of_the_illidari  : start= 5.6 refresh= 69.8 interval= 60.5 trigger=  3.8 uptime= 5.48%  benefit= 5%
  Up-Times:
      2.0% : Fury Cap                      
  Procs:
      8.5 |  57.19sec : delayed_swing__channeling
     31.3 |   9.79sec : felblade_reset
  Gains:
        96.7 : miss_refund             (fury)
       577.5 : anger_of_the_halfgiants (fury)  (overflow=7.0%)
      2205.0 : demon_blades            (fury)  (overflow=3.6%)
      1266.6 : felblade_dmg            (fury)
       223.4 : annihilation            (fury)  (overflow=1.1%)
       611.7 : chaos_strike            (fury)
  Scale Factors:
    Weights :  Agi=13.87(0.56)  AP=13.09(0.55)  Crit=12.25(0.55)  Haste=11.36(0.55)  Mastery=11.66(0.56)  Vers=11.34(0.55)  Wdps=31.20(0.56)  WOHdps=9.97(0.56)
    Wowhead : 
  Waiting: 6.01%

 *** Targets *** 


Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|195039464  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.46%  benefit=10%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.66%  benefit=10%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.55%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.34%  benefit=13%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.02%  benefit=12%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.19%  benefit=12%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=14.28%  benefit=14%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.70%  benefit=10%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.91%  benefit= 5%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 2.88%  benefit= 3%
    anguish                  : start= 6.0 refresh= 53.9 interval= 48.7 trigger=  4.2 uptime= 6.90%  benefit= 7%
    nemesis                  : start= 3.1 refresh=  0.0 interval=120.4 trigger=120.4 uptime=54.17%  benefit=61%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
     6.0% : Dimonda

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10003
  TotalEvents   = 29221169
  MaxEventQueue = 34
  TargetHealth  = 195039464
  SimSeconds    = 3043541
  CpuSeconds    = 26.609
  WallSeconds   = 15.687
  SpeedUp       = 114379
  EndTime       = 2017-03-18 10:44:05+0100 (1489830245)


Scale Factors:
  Dimonda  Agi=13.87(0.56)  AP=13.09(0.55)  Crit=12.25(0.55)  Haste=11.36(0.55)  Mastery=11.66(0.56)  Vers=11.34(0.55)  Wdps=31.20(0.56)  WOHdps=9.97(0.56)

**Comment by Oldalf** [comment]
Closed it since it was a user made error (partly because of bad ui) and not a real bug.
