### ISSUE TITLE
Can't Simulate Balance Druid

### ISSUE THREAD

**Issue by menethiil** [simulationcraft/simc#3638]
I can import my druid just fine, but as soon as I hit simulate it goes for a few seconds and then freezes and has to be closed. This happens no matter which way I import my toon. I had my friend run my druid through simcraft on her computer, and it happened to her as well. I can sim my hunter just fine.

#### Simulationcraft Version

715-02

#### If Simulationcraft is crashing, please include your dxdiag file

[DxDiag.txt](https://github.com/simulationcraft/simc/files/868508/DxDiag.txt)

#### simc_gui.simc file or contents
http://pastebin.com/z5f2EM0H

**Comment by Collisionc** [comment]
Same issue as https://github.com/simulationcraft/simc/issues/3639, fixed there.
