### ISSUE TITLE
Balance druid simcraft crash on simulate

### ISSUE THREAD

**Issue by A-Deeley** [simulationcraft/simc#3639]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
715-01
#### If Simulationcraft is crashing, please include your dxdiag file
[DxDiag.txt](https://github.com/simulationcraft/simc/files/868901/DxDiag.txt)
#### simc_gui.simc file or contents
[simc_gui.simc.txt](https://github.com/simulationcraft/simc/files/868904/simc_gui.simc.txt)
#### Reproduction Steps:

**Comment by Bloodmallet** [comment]
is this still happening?

**Comment by ChaoticWeg** [comment]
Just tried simming a balance druid for my SO, it tried to sim and didn't crash, but failed out fairly quickly and rendered a [results page](https://i.gyazo.com/8a1b71735446d002838cc6321773931c.png) (hotlinks to screen-cap) with the error message `Player Ysabel could not find spell data for action starfall_tick`.  This is on a fresh install of the x86 program, just downloaded from the site within an hour of posting this.  I'll try it on a repo clone and edit this comment or post a new one with results.

**Comment by navv1234** [comment]
Pretty sure this has been fixed by now, no?
