### ISSUE TITLE
not work - SimulationCraft 7.1.5, release 1 -  help pls

### ISSUE THREAD

**Issue by MAKARON111** [simulationcraft/simc#3642]
i import my profile: http://eu.battle.net/wow/ru/character/ясеневыи-лес/Маккарон/advanced

screenshot 1: http://imgur.com/a/vDvQD

error:

> # Profile will be downloaded into a new tab.
> #
> # Clicking Simulate will create a simc_gui.simc profile for review.
> 
> # Unable to generate profile from: http://eu.battle.net/wow/ru/character/ясеневыи-лес/Маккарон/advanced
> 
> # BCP API (html): Unable to download player from 'http://eu.battle.net/wow/en/character/ясеневыи-лес/Маккарон/advanced', invalid profile

screenshot 2: http://imgur.com/QZcufWs

SimulationCraft 7.1.5, release 1

i have such a mistake for a very long time
help pls

**Comment by lgkern** [comment]
Brewmaster monks, and all other tanks/healers, aren't currently supported by SimC, so any sims using them can have any behavior. https://github.com/simulationcraft/simc/issues/2775
