### ISSUE TITLE
[CLI] Segmentation fault if sim many characters

### ISSUE THREAD

**Issue by Hilzerak** [simulationcraft/simc#3643]
Hello pls help i'm new to simulationcraft cli.

#### Simulationcraft Version
7.1.5 Live (wow build 23360, git build c10db73)
and
World of Warcraft 7.1.5 Live (wow build 23360, git build ) 27.03.2017:1400

Hostsystem is an Ubuntu 16.04.2LTS with ubuntu-lts 4.4.0-66-generic

#### simc_gui.simc file or contents
I use only the CLI.

#### Reproduction Steps:
Every time i will try to simulate multiple Chars in one Sheet the App Crashes with Segmentation fault!
Exampleerror: 
"super
super
super
...
sim_signal_handler: Segmentation fault! Iteration=1 Seed=14858835488867255634 TargetHealth=6637570217"

No else errors. Every time Segmentation faults. I've tried with less charakters or different. It seems very random and i dont have a pattern for this found. Thats on both versions.

"simc guild.simc html=page.html"
[guild.simc pastebin](https://pastebin.com/hxxcQYVM)

If you need any further Informations pls let me know.
Thank for help!

**Comment by Hilzerak** [comment]
Problem still exist with "World of Warcraft 7.2.0 Live (wow build level 23826, git build 36cff59)"
Singlesim from Characters no Problem.
Sim multiple Chars in on Chart with less (10-100) iterations work fine.
But if i change iterations above every time the Simc CLI crashes with "Segmentation fault".
Because i try to simulate many chars, can it be an RAM problem?
The computer which simulate have 8GB RAM but the Application only uses ~3,6GB. Is it an 32/64 Bit problem?
The OS is 64bit.

Alternatively can i workaround this issue?

PLS HELP!

**Comment by Hilzerak** [comment]
Problem still exist with with actual build.
for World of Warcraft 7.2.0 Live (wow build level 23826, git build 2dd443e)

[file.simc](https://pastebin.com/zLRNT4NQ)

Application crashes on windows systems too with the 7.2 release

**Comment by navv1234** [comment]
I fixed a couple of crashes from that list of profiles that popped up. In general though, importing very many actors from armory is just asking for trouble, since the armory often simply refuses to give up the data. A safer way is to import the characters to separate files (armory=xx,yy,zz save=zz.simc) and then include the individual profiles in a larger simc file fed to the command line client.

**Comment by Hilzerak** [comment]
@navv1234 
Thx for reply!
Unfortunately it crashes also with the newest build :\

But with the workaround you tell it runs fine.
BIG BIG THX for that!
