### ISSUE TITLE
Successful Roll the Bones in prepull does not list out specific individual buffs

### ISSUE THREAD

**Issue by omrlick** [simulationcraft/simc#3646]
hi on the Outlaw APL if the prepull rtb gets tb or any +3 it just says roll_the_bones and you are unable to see what buffs it is. However if it rerolls again the buffs will be listed out along with roll_the_bones was wondering down the line if its possible to get the buffs listed on the first successful rtb as well! It's not Urgent because it doesn't change the way you perform the following actions but it's nice to be able to see specifically what it rolled. 

SimulationCraft 715-02
for World of Warcraft 7.2.0 Live (wow build level 23826, git build a47c9e5

**Comment by Mystler** [comment]
Thanks for the report. This should be fixed in a9f378c2b1f2b44762c80635af6e4cefc4ae3e94. 😃
