### ISSUE TITLE
Vengeance (all tanks?) and food buff

### ISSUE THREAD

**Issue by Myrroddin** [simulationcraft/simc#3647]
Please include a brief overview of the issue in the title above, as well as completing the following:
Demon Hunter tanks, Vengeance spec, and possibly all tanks are using the wrong food buff in SimulationCraft. Instead of Nightborne Delicacy Platter (itemID 201556), we should be using Seed-Battered Fish Plate (itemID 201557).

I have provided the itemIDs for the rank 3 versions, but the buff is the same for all ranks.

#### Simulationcraft Version
7.1.5, release1
7.2.0, build 01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
https://pastebin.com/qV42wp5r

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Tanks are not supported at this time. https://github.com/simulationcraft/simc/issues/2775
But maybe people taking care of the DH module can change the food if it should be a different one?

**Comment by Myrroddin** [comment]
Nightborne Delicacy Platter got a huge buff, +500 primary stat (Str, Agil, Int) so this may become the food of choice in raids rather than the +375 secondary stat foods.

**Comment by EvanMichaels** [comment]
I can change this for Vengeance if needed, sure. But yeah, it's likely we will just swap both specs to the new +500 primary stat food.

**Comment by Myrroddin** [comment]
Okay, it seems that **all** classes and all specs now require Lavish Suramar Feast as the raid food.

http://ptr.wowdb.com/items/133579-lavish-suramar-feast

**Comment by EvanMichaels** [comment]
Added.
