### ISSUE TITLE
875 Crafting gear is not working correctly.  Looking at the gear in the results, the tooltip is correct when you mouse over it, the the gear is showing as ilevel 851 with lower stats.

### ISSUE THREAD

**Issue by Kozmaja** [simulationcraft/simc#3652]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Kozmaja** [comment]
Looking at the gear in the results, the tooltip is correct when you mouse over it, but the the gear is showing as ilevel 851 with lower stats.  For example and 875 crafted "Subtle Shadowruby Pendant of the Quickblade" with 1450 Stam, 1656 Crit & 864 Vers has this listed below it:
"level: 851, stats: { +1160 Sta, +1433 Crit, +748 Vers }, gems: { +150 Crit }, enchant: mark_of_the_hidden_satyr"

This is for version 715-01

**Comment by Kozmaja** [comment]
Closed issue by mistake

**Comment by navv1234** [comment]
Would need simc_gui.simc file to look into this.

**Comment by Kozmaja** [comment]
Here is the simc_gui.simc contents:
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
rogue="Onceaday"
level=110
race=blood_elf
region=us
server=hyjal
role=
professions=leatherworking=800/alchemy=800
talents=3112322
spec=outlaw
artifact=44:0:0:0:0:1052:1:1053:1:1054:1:1055:1:1056:1:1057:1:1058:1:1059:3:1060:3:1061:3:1062:3:1063:3:1064:3:1065:3:1066:3:1067:3:1348:1:1385:1:1652:1

head=,id=134196,bonus_id=3474/1527/3337
neck=,id=130236,enchant_id=5439,bonus_id=1743/689/601/674,gem_id=130219
shoulder=,id=141445,enchant_id=5442,bonus_id=3466/1477/3336
back=,id=141543,enchant_id=5435,bonus_id=1477/3336
chest=,id=128884,bonus_id=689/1682/3408/600/674
wrist=,id=137099,bonus_id=3458/3455/1811
hands=,id=136741,bonus_id=1824/1808/41/1537/3337,gem_id=130221
waist=,id=128890,bonus_id=689/1678/3408/601/674
legs=,id=128888,bonus_id=689/1678/3408/600/674
feet=,id=128885,bonus_id=689/1679/3408/600/674
finger1=,id=132452,enchant_id=5430,bonus_id=1811/3458,gem_id=130247
finger2=,id=130229,enchant_id=5429,bonus_id=3344/689/601/674,gem_id=130222
trinket1=,id=127842,bonus_id=689/600/674
trinket2=,id=144477,bonus_id=1726/42/1517/3337
main_hand=,id=128872,bonus_id=742,relic_id=0/3474:1512:3336/3473:1527:3337,gem_id=146933/141263/143704/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

**Comment by navv1234** [comment]
What version of simulationcraft are you using? I cannot replicate this, the HTML report correctly says 875 for the neck.

**Comment by Kozmaja** [comment]
I am using 715-01.  The HTML report does have the correct tooltip (or mouse over) but below that link and ilevel “851” item is displayed.

**Comment by Kozmaja** [comment]
I am using 715-01.  The HTML report does have the correct tooltip (or mouse over) but below that link and ilevel “851” item is displayed.

**Comment by navv1234** [comment]
That is quite out of date. Try a nightly build from http://downloads.simulationcraft.org/?C=M;O=D

**Comment by navv1234** [comment]
New releases have come out for 7.2.0 that should have fixed this. Reply here if not.
