### ISSUE TITLE
No version bump when re-compiling.

### ISSUE THREAD

**Issue by stokbaek** [simulationcraft/simc#3653]
When compiling from source the version of simc does not get bumped. Removing `sc_main.o` before rebuilding makes the compiler bump version

```
*******@stokbaek:/opt/simc-git/engine (legion-dev) $ ./simc 
SimulationCraft 720-01 for World of Warcraft 7.2.0 Live (wow build 23826, git build 1668f21e6)
ERROR! Setup failure: Nothing to sim!
*******@stokbaek:/opt/simc-git/engine (legion-dev) $ sudo make OPENSSL=1 optimized -j8
[simc] Compiling sc_warlock.cpp
[simc] Compiling sc_paladin.cpp
[simc] Linking simc
*******@stokbaek:/opt/simc-git/engine (legion-dev) $ ./simc 
SimulationCraft 720-01 for World of Warcraft 7.2.0 Live (wow build 23826, git build 1668f21e6)
ERROR! Setup failure: Nothing to sim!
*******@stokbaek:/opt/simc-git/engine (legion-dev) $ 
```

**Comment by navv1234** [comment]
I'm guessing you are talking about the "git build" thing. Yeah. This is an issue with how we do the git commit-hash. A better solution probably would be to generate a temporary include file for it, and make it depend on all files.

**Comment by stokbaek** [comment]
I dont think this is an issue with git. The following steps doesn't change the version of simc.
* git pull
* make OPENSSL=1

If `sc_main.o` is removed in between `git pull` and `make` will simc be compiled with a new version number. To me this looks more like an error on how files are handled during the compiling.

**Comment by navv1234** [comment]
It's not an issue with git. It's an issue with the (makefile) build system.

**Comment by navv1234** [comment]
Alright, I made a change to the Makefile now that forces sc_main.cpp to be compiled every time. This should ensure that the git shorthash of the CLI binary always changes to the HEAD shorthash, even if sc_main.cpp has not changed (as it usually does not).
