### ISSUE TITLE
Indications of Breath of Sindragosa snapshotting

### ISSUE THREAD

**Issue by Wrektum** [simulationcraft/simc#3656]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

SimulationCraft 720-01
for World of Warcraft 7.2.0 Live (wow build level 23826, git build 1668f21)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

https://pastebin.com/sCsjf5ZE

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Results are different if using Horn of Valor immediately after or immediately before activating Breath. See simulation results. I get 795k vs 770k and that seems excessive.

Edit: Further exacerbated by using Pillar of Frost / Blood Fury immediately after BOS, I then end up with a 90k discrepancy of popping buffs after BOS activation.

**Comment by navv1234** [comment]
So it is, only updates damage multiplier(s).

**Comment by navv1234** [comment]
Fixed in d717d82ca, it was snapshotting AP only, the rest were ok.
