### ISSUE TITLE
Running 3 meta relics, and being 4/4 slots causes meta uptime to drop.

### ISSUE THREAD

**Issue by YouizDirty** [simulationcraft/simc#3657]
While using Legendary shoulders as a demon hunter. Maybe incorrectly reading for 4th trait and causing an error.

Running 2 relics and 4/4 was giving me an uptime of 25.51%.
"Metamorphosis	2.7	0.4	136.7sec	108.6sec	25.51%	37.42%	0.4(0.4)	2.4".

But when swapping to 3 relics and 4/4 was giving me an uptime of 17.83%.
"Metamorphosis	1.9	0.5	245.0sec	177.8sec	17.83%	27.40%	0.5(0.5)	1.6"

Version 715-01

**Comment by EvanMichaels** [comment]
Do you have profiles for these you could pastebin or something?

**Comment by navv1234** [comment]
Nothing occurred in 3 months, so presuming issue has resolved itself?
