### ISSUE TITLE
Vengeance DH tanks flask (maybe all tanks?)

### ISSUE THREAD

**Issue by Myrroddin** [simulationcraft/simc#3662]
Please include a brief overview of the issue in the title above, as well as completing the following:
I heard that tanks are not yet supported, and that's fine, I am just testing. In the meantime, tanks would use Flask of Ten Thousand Scars, whereas SimulationCraft has Flask of the Seventh Demon. The latter is for Agility based DPS, like Havoc, Rogues, cat Druids, etc.

I changed the options in the import panel to reflect both Flask of Ten Thousand Scars and Lavish Suramar Feast (seperate issue).

#### Simulationcraft Version
720-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
https://pastebin.com/ZkgYYbuf

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by EvanMichaels** [comment]
Most tanks these days seem to prefer primary stat flasks, so unlike the food issue I'm not so sure if this change should be made.

**Comment by navv1234** [comment]
There should now be an easy way to change the flask anyhow by anyone using the ```flask``` option, presuming the DH module implements it. Closing for nwo.
