### ISSUE TITLE
simcraft error and stopped working

### ISSUE THREAD

**Issue by bskm5z** [simulationcraft/simc#3668]
please simcraft doesn't work every time i tried it stopped and closed please check your version 64 bit

**Comment by bskm5z** [comment]
monk="Bombohealer"
level=110
race=pandaren
region=eu
server=silvermoon
role=spell
talents=3213131
spec=windwalker
artifact=50:0:0:0:0:800:3:801:3:820:3:821:3:822:3:824:3:825:3:827:1:828:1:829:1:830:1:831:1:832:1:833:1:1094:3:1341:1

name=Base 
head=,id=138331,bonus_id=3520/1457
neck=,id=140899,bonus_id=3514/1808/1477/3336
shoulder=,id=138337,bonus_id=3514/1487/3337
back=,id=138367,enchant_id=5433,bonus_id=3514/1472/3528
chest=,id=144340,bonus_id=3529/3530/1811
wrist=,id=140889,bonus_id=3514/1472/1813
hands=,id=140863,bonus_id=3443/1477/3336
waist=,id=138879,bonus_id=3529/3530/1811
legs=,id=140862,bonus_id=3443/1467/1813
feet=,id=140914,bonus_id=3515/1487/3336
finger1=,id=140897,bonus_id=3515/1808/1477/3528
finger2=,id=134534,bonus_id=3414/1542/3336
trinket1=,id=140805,bonus_id=3520/1467/3336
trinket2=,id=140803,bonus_id=3516/1808/1487/1813
main_hand=,id=128940,bonus_id=734,relic_id=3474:1522:3337/3397:1507:3337/1807:1477:3336,gem_id=143688/140045/139262/0
off_hand=,id=133948,relic_id=0/0


copy=copy1,Base
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy2,Base
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy3,Base
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy4,Base
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy5,Base
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy6,Base
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy7,Base
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy8,Base
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy9,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy10,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy11,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy12,Base
shoulder=,id=137364,bonus_id=1727/1527/3337

copy=copy13,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy14,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy15,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy16,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy17,Base
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy18,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy19,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy20,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy21,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813

copy=copy22,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy23,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy24,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy25,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy26,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy27,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy28,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy29,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy30,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337

copy=copy31,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy32,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy33,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy34,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy35,Base
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy36,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy37,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy38,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy39,Base
head=,id=140901,bonus_id=3443/1477/3336

copy=copy40,Base
head=,id=140901,bonus_id=3443/1477/3336
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy41,Base
head=,id=140901,bonus_id=3443/1477/3336
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy42,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy43,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy44,Base
head=,id=140901,bonus_id=3443/1477/3336
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy45,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy46,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy47,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy48,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337

copy=copy49,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy50,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy51,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy52,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy53,Base
head=,id=140901,bonus_id=3443/1477/3336
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy54,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy55,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy56,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy57,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813

copy=copy58,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy59,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy60,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy61,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy62,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy63,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528

copy=copy64,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy65,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=134199,bonus_id=3414/1542/3528
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy66,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337

copy=copy67,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy68,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy69,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337

copy=copy70,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket2=,id=140792,bonus_id=3443/1467/1813

copy=copy71,Base
head=,id=140901,bonus_id=3443/1477/3336
neck=,id=140899,enchant_id=5891,bonus_id=3514/1808/41/1472/1813
shoulder=,id=137364,bonus_id=1727/1527/3337
waist=,id=140919,bonus_id=3515/1492/3337
trinket1=,id=140803,bonus_id=3516/1808/1487/1813
trinket2=,id=140792,bonus_id=3443/1467/1813

**Comment by navv1234** [comment]
Have you tried with recent versions? I cannot reproduce an issue with that.
