### ISSUE TITLE
Promise of Elune 7.2 buff not implemented

### ISSUE THREAD

**Issue by Slippykins** [simulationcraft/simc#3670]
8% damage buff to Solar Wrath and Lunar Strike is not implemented in SimC. This was the 7.2 buff to the legendary.

SimC Version: any and all.

Reproduction: simulate build with Promise of Elune on, check damage % of Solar Wrath and Lunar Strike, resim without Promise of Elune on, notice damage % of Solar Wrath and Lunar Strike is the same.

**Comment by Bloodmallet** [comment]
added in https://github.com/simulationcraft/simc/commit/c01098c2f866e6d1afb0a0942bc348c638d88002
