### ISSUE TITLE
Simcraft keeps crashing my pc - Fatal error complete reset.

### ISSUE THREAD

**Issue by Alexander-H-Dinesen** [simulationcraft/simc#3672]
Title says it all Simcraft keeps crashing my pc on end of the simulation.
https://paste.ee/p/JGWAh simc_gui.simc
[DxDiag.txt](https://github.com/simulationcraft/simc/files/890310/DxDiag.txt)

WhoCrashed analysis dump.
"Crash dump directory: C:\WINDOWS\Minidump

Crash dumps are enabled on your computer.

On Mon 03-04-2017 16:00:45 your computer crashed
crash dump file: C:\WINDOWS\memory.dmp
This was probably caused by the following module: Unknown (0xFFFFBD0F79F17028) 
Bugcheck code: 0x124 (0x0, 0xFFFFBD0F79F17028, 0xBE000000, 0x800400)
Error: WHEA_UNCORRECTABLE_ERROR
Bug check description: This bug check indicates that a fatal hardware error has occurred. This bug check uses the error data that is provided by the Windows Hardware Error Architecture (WHEA). 
This is likely to be caused by a hardware problem problem. This problem might also be caused because of overheating (thermal issue). 
A third party driver was identified as the probable root cause of this system error. 
Google query: WHEA_UNCORRECTABLE_ERROR

On Mon 03-04-2017 14:42:12 your computer crashed
crash dump file: C:\WINDOWS\Minidump\040317-4390-01.dmp
This was probably caused by the following module: hal.dll (hal+0x3627F) 
Bugcheck code: 0x124 (0x0, 0xFFFFE788AC837028, 0xBE000000, 0x800400)
Error: WHEA_UNCORRECTABLE_ERROR
file path: C:\WINDOWS\system32\hal.dll
product: MicrosoftR WindowsR Operating System
company: Microsoft Corporation
description: Hardware Abstraction Layer DLL
Bug check description: This bug check indicates that a fatal hardware error has occurred. This bug check uses the error data that is provided by the Windows Hardware Error Architecture (WHEA). 
This is likely to be caused by a hardware problem problem. This problem might also be caused because of overheating (thermal issue). 
The crash took place in a standard Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time. 

On Mon 03-04-2017 14:35:09 your computer crashed
crash dump file: C:\WINDOWS\Minidump\040317-4515-01.dmp
This was probably caused by the following module: hal.dll (hal+0x3627F) 
Bugcheck code: 0x124 (0x0, 0xFFFFA00833F2A028, 0xBE000000, 0x800400)
Error: WHEA_UNCORRECTABLE_ERROR
file path: C:\WINDOWS\system32\hal.dll
product: MicrosoftR WindowsR Operating System
company: Microsoft Corporation
description: Hardware Abstraction Layer DLL
Bug check description: This bug check indicates that a fatal hardware error has occurred. This bug check uses the error data that is provided by the Windows Hardware Error Architecture (WHEA). 
This is likely to be caused by a hardware problem problem. This problem might also be caused because of overheating (thermal issue). 
The crash took place in a standard Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time. "

**Comment by Alexander-H-Dinesen** [comment]
Also i need help. Desperately. 
Thanks in advance.

Alex.

**Comment by navv1234** [comment]
Nothing here points to Simulationcraft per say, more to a hardware issue with your setup.
