### ISSUE TITLE
Ret paladin gets 2% haste after simming bug

### ISSUE THREAD

**Issue by ziradin** [simulationcraft/simc#3673]
with all the builds of 7.2 rets gets 2% more haste after simming on the stats pannel 
like 
https://gyazo.com/e00495d70998e7a8ea41e30ced7ea3ca

check the % and the rating and u can see it doesnt match

**Comment by vituscze** [comment]
This might be due to `sephuzs_secret_enabler_t` creating a fallback when the legendary is not equipped.

**Comment by mserrano** [comment]
Should be fixed by 82b45c34edc747a94e38c4434f14f69c939f8178
