### ISSUE TITLE
Sephuz's Updated Stats not accounted for

### ISSUE THREAD

**Issue by sunneh** [simulationcraft/simc#3675]
Sephuz's Secret was updated with a base 10% movespeed and 2% haste before the proc occurs. This isn't accounted for in the simulation according to the results of the sim under the stats tab.

SimulationCraft 720-01
for World of Warcraft 7.2.0 Live (wow build level 23826, git build 82b45c3)

**Comment by sunneh** [comment]
![image](https://cloud.githubusercontent.com/assets/3278591/24765507/14d4bc22-1ac6-11e7-978f-cba7ea8e9fcd.png)

**Comment by lgkern** [comment]
This should be working currently, can you check it?

**Comment by navv1234** [comment]
Updated stats are now in Warrior module, closing.
