### ISSUE TITLE
rank 7 traits ignored

### ISSUE THREAD

**Issue by yourdead** [simulationcraft/simc#3678]
Simulationcraft Version 7.1.5

When you have 3 relics buffing the same trait and 4 rank ups learned (a total of 7 ranks on a single trait) simcraft is ignoring it and setting it as 0 ranks.
On my warlock i have 7/7 on +crit% on immolate, i have 18% crit so +56% from trait should be 74% crit chance on immolate however simcraft is setting it to 18%, it works on 6/6 giving me 66% crit chance  probably because you could already get that far on the previous patch.
I've tried importing artifact traits from wowhead calculater instead of the built in import, it would fix the tooltip on the result page but the results on crit chance remained the same.

**Comment by vituscze** [comment]
Most likely due to your simc being out of date. Update to a more recent version and try it again.

**Comment by yourdead** [comment]
I didn't see the nighly updated build thingie i just downloaded whatever said installer :p thanks for the help

**Comment by vituscze** [comment]
If you find problems with the nightly version, let me know and I'll reopen it.
