### ISSUE TITLE
Issues with frost mage rotation and missing buffs from buffs section of the result report.

### ISSUE THREAD

**Issue by Workingbob** [simulationcraft/simc#3684]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 720-01 

**Buff issues:**
Simulation craft dose not display the buff "chain reaction" 

Chain Reaction artifact trait: Frostbolt critical strikes empower Ice Lance, increasing damage dealt by 10% for 6 sec, stacking up to 3 times.

I don't know if this is being applied and just not being shown, past that this appears as a buff in your buff bar and as such I have been told it should be appearing in the buff's section on simcraft's results. 

**Past that I find issues in the single target rotation for frost mages in the current build. **

**Default:** 
actions.single=ice_nova,if=debuff.winters_chill.up
actions.single+=/frostbolt,if=prev_off_gcd.water_jet
actions.single+=/water_jet,if=prev_gcd.1.frostbolt&buff.fingers_of_frost.stack<(2+artifact.icy_hand.enabled)&buff.brain_freeze.react=0
actions.single+=/ray_of_frost,if=buff.icy_veins.up|(cooldown.icy_veins.remains>action.ray_of_frost.cooldown&buff.rune_of_power.down)
actions.single+=/flurry,if=prev_gcd.1.ebonbolt|prev_gcd.1.frostbolt&buff.brain_freeze.react
actions.single+=/blizzard,if=cast_time=0&active_enemies>1&variable.fof_react<3
actions.single+=/frost_bomb,if=debuff.frost_bomb.remains<action.ice_lance.travel_time&variable.fof_react>0
actions.single+=/ice_lance,if=variable.fof_react>0&cooldown.icy_veins.remains>10|variable.fof_react>2
actions.single+=/frozen_orb
actions.single+=/ice_nova
actions.single+=/comet_storm
actions.single+=/blizzard,if=active_enemies>2|active_enemies>1&!(talent.glacial_spike.enabled&talent.splitting_ice.enabled)|(buff.zannesu_journey.stack=5&buff.zannesu_journey.remains>cast_time)
actions.single+=/ebonbolt,if=buff.brain_freeze.react=0
actions.single+=/glacial_spike
actions.single+=/frostbolt

**This isnt a bad idea, and is a good base but lacks a few things or tweeks I would make to improve apon this.** 

**1.** after you use flurry with a brain freeze proc you should be immediately following that with an ice nova or a ice lance to benefit from winters chill debuff to shatter your ice lance. 

**2.** you should use ice lances with fingers of frost procs before you use brain freeze procs, because when you use brain freez your next ice lance benefits from a fingers of frost proc without getting a fingers of frost proc because the winters chill debuff should freeze the target and apply the 3x damage modifier and crit modifier of shatter, and as such if you use flurry before your fof proc you are effectively eating a fof proc because you would of gotten the benefit of fof without using the proc. Therefore you should be using fof procs before your brain freeze procs so you effectively shatter 2 ice lances over 1.

**My Single target changes:**
actions.single=ice_nova,if=debuff.winters_chill.up
actions.single+=/ice_lance,if=prev_gcd.1.flurry
actions.single+=/frostbolt,if=prev_off_gcd.water_jet
actions.single+=/water_jet,if=prev_gcd.1.frostbolt&buff.fingers_of_frost.stack<(2+artifact.icy_hand.enabled)&buff.brain_freeze.react=0
actions.single+=/ray_of_frost,if=buff.icy_veins.up|(cooldown.icy_veins.remains>action.ray_of_frost.cooldown&buff.rune_of_power.down)
actions.single+=/ice_lance,if=variable.fof_react>0&cooldown.icy_veins.remains>10|variable.fof_react>2
actions.single+=/flurry,if=prev_gcd.1.ebonbolt|prev_gcd.1.frostbolt&buff.brain_freeze.react
actions.single+=/blizzard,if=cast_time=0&active_enemies>1&variable.fof_react<3
actions.single+=/frost_bomb,if=debuff.frost_bomb.remains<action.ice_lance.travel_time&variable.fof_react>0
actions.single+=/frozen_orb
actions.single+=/ice_nova
actions.single+=/comet_storm
actions.single+=/blizzard,if=active_enemies>2|active_enemies>1&!(talent.glacial_spike.enabled&talent.splitting_ice.enabled)|(buff.zannesu_journey.stack=5&buff.zannesu_journey.remains>cast_time)
actions.single+=/ebonbolt,if=buff.brain_freeze.react=0
actions.single+=/glacial_spike
actions.single+=/frostbolt

**Comment by vituscze** [comment]
Cannot reproduce the Chain Reaction thing, it shows correctly in the buff breakdown.

As for the APL, it already does both things you mention.

**Comment by jcadduono** [comment]
https://github.com/simulationcraft/simc/issues/3096 this is probably why (no artifact traits, no chain reaction)

**Comment by Workingbob** [comment]
**I looked again and the line now reads:** 
actions.single+=/flurry,if=(buff.brain_freeze.react|prev_gcd.1.ebonbolt)&buff.fingers_of_frost.react=0
**Has changed from what I was using:**
actions.single+=/flurry,if=prev_gcd.1.ebonbolt|prev_gcd.1.frostbolt&buff.brain_freeze.react

and as such it dose only casts flurry if fof are not up as @vituscze said.
and the problem with chain reaction was most likely @jcadduono said and with the new/new to me APL things are working as intended. 

I also missed a line earlier in the APL:
actions+=/ice_lance,if=buff.fingers_of_frost.react=0&prev_gcd.1.flurry&spell_haste<0.845

I can not confirm weather or not it was in the old APL I was using but it is there for the new one and as such the simulation is much closer to my actual dps and is in my mind very correct.
