### ISSUE TITLE
[Balance Druid] Wax and Wane not applying to Sunfire

### ISSUE THREAD

**Issue by Killuha** [simulationcraft/simc#3688]
Simulationcraft Version: 720-01 (wow build level 23826, git build 99c024f)

The new balance druid trait "Wax and Wane" (239952) is not applying the damage bonus to the direct damage portion of "Sunfire" (93402).

Sunfire was added to Wax and Wane in a Hotfix on 29th of march, this change is not reflected in the tooltip yet.

**Comment by Bloodmallet** [comment]
Fixed
https://github.com/simulationcraft/simc/commit/d5084375b690e3449d5d956f67ec8f6c3edaa0d9
