### ISSUE TITLE
Cant open exe

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3689]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version simc-720-01-win64

cant open the exe. Not much i can tell u about it. Lastest win10 drivers, Restarted pc after install didnt work either. 
Tested all version u had on the download page too.

**Comment by tjalex** [comment]
Potential issue w/ win10 creators update?

**Comment by Collisionc** [comment]
I messed up the release, I think. I re-uploaded fixed versions, try it again.

**Comment by Nightdrift** [comment]
Hi same problem (Win10 creators update installed)  tested all new version and some old also not working
Windows eventlog attached;  NVIDIA driver latest installed with clean install.
[Windows eventlog.txt](https://github.com/simulationcraft/simc/files/923579/Windows.eventlog.txt)

**Comment by zitnik1ng** [comment]
+1 i ahve installed windows 10 1703build (Creators update), and i cant launch .exe

**Comment by Nightdrift** [comment]
Hi again : problem solved  NVIDIA driver 381.65 is the problem  .  Use pervious 378.92 and its all good.
