### ISSUE TITLE
Trinket: 'Dreadstone of Endless Shadows' using wrong buffs

### ISSUE THREAD

**Issue by cont1nuity** [simulationcraft/simc#3700]
#### Simulationcraft Version
7.2.0, release 1

#### simc_gui.simc file or contents
https://pastebin.com/mnAVRRDS

#### Reproduction Steps:
Simulate the following profile: https://pastebin.com/WLDM914u

In the Buffs section the buffs belonging to "Etraeus' Celestial Map" are shown:
- "Sign of the Dragon" - id 225753
- "Sign of the Hare" - id 225752
- "Sign of the Hippo" - id 225749

These provide more stats than the actual buffs of the Dreadstone: 
- "Shadow's Strike" - id 238499
- "Shadow Master" - id 238500
- "Swarming Shadows" - id 238501

Thus the simulation results are wrong if this trinket is used.

**Comment by vituscze** [comment]
The buff names are different, but the stats provided are the same.

In fact, Dreadstone even refers to Sign of the Hippo in its tooltip.

**Comment by lgkern** [comment]
as @vituscze said, that comes from us having it implemented before anyone got it to figure out the buffs. If you look the buffs you'll see they are exactly the same, so the results aren't compromised, just aesthetically wrong.

**Comment by cont1nuity** [comment]
Ok, I agree, the values are the same, it seems I was confused by the tooltip values. The applied "Stat Buff details" seem to be fine.

Edit: Thanks for answering and looking into it.

**Comment by navv1234** [comment]
I'll fix them in a bit. Forgot to swap the spell ids.
