### ISSUE TITLE
Trinket completely ignored by simcraft: blackened naaru sliver

### ISSUE THREAD

**Issue by Somniox** [simulationcraft/simc#3701]
Using newest version of simcraft. Have also tried raidbots.com
http://www.wowhead.com/item=34427/blackened-naaru-sliver
This trinket is completely ignored by simcraft.

**Comment by navv1234** [comment]
We don't generally support this old trinkets. You can use the custom trinket modeling to create somewhat accurate model of that trinket, if you want.
