### ISSUE TITLE
Trinket not simming correctly: Faulty Countermeasure not critting 

### ISSUE THREAD

**Issue by koshkau** [simulationcraft/simc#3702]
I noticed while simming that faulty countermeasure's on hit ability doesn't crit in simc, which it does in game (can be seen with warcraft logs and in game metres).
This behaviour was noted with simc-720-02-win64-c158563.

**Comment by nuoHep** [comment]
Should be fixed by 2dd443ec8db17f8f90678b63e87fae2d32d6998f
