### ISSUE TITLE
Simulation craft Does not Launch after Windows 10 Creators Update

### ISSUE THREAD

**Issue by BenekC** [simulationcraft/simc#3706]
#Please include a brief overview of the issue in the title above, as well as completing the following: Simulationcraft does not run with Nvidia Driver 381.65 and 381.89. Running in compatibility mode does not resolve. Driver rollback does resolve.
 

#### Simulationcraft Version : 720-01, 720-02, 720-03 64-bit and 32-bit

[dxdiag.txt](https://github.com/simulationcraft/simc/files/927415/dxdiag.txt)

#### Reproduction Steps: Windows 10 Creators Update, Antivirus off, Run as Administrator, GTX 970, Driver: 381.65 and 381.89.

**Comment by zitnik1ng** [comment]
if u have nvidia graphic use pervious 378.92 drivers works well

**Comment by nille02** [comment]
i doubt that this is an issue with simc or win10ca. work here without a problem. Im using the 378.92 WHQL drivers with an gtx960

**Comment by BenekC** [comment]
Alright, thank you. I'll try a prior graphics driver version and see if that fixes it.

**Comment by BenekC** [comment]
Confirmed working with a GTX 970 Nvidia driver 378.92. It does not work with 381.65.

**Comment by JagO-3a** [comment]
Confirmed this, the 64-bit version of SimulationCraft 720-01 does not work with the GTX 980, Windows 10 Creators Update, and the Nvidia 381.65 WHQL driver. But it works fine with the 32-bit version of Simcraft 720-01!

**Comment by BenekC** [comment]
Updated to add that the 720-02 and 720-03; (64-bit version AND 32-bit versions) do not fix this issue for Nvidia Driver version 381.65 and the just released 381.89

**Comment by nille02** [comment]
@BenekC the problem is not simc, its the Nvidia driver.

**Comment by psykogit** [comment]
Experiencing the same issue here. 
nVidia Display Driver v381.89 + Windows 10 x64 Creators Edition
