### ISSUE TITLE
Havoc - Death Sweep doesn't benefit from Bladedancer's Grace

### ISSUE THREAD

**Issue by Sinbrand** [simulationcraft/simc#3708]
Bladedancer's Grace trait correctly buffs Blade Dance's crit damage to 240%, but Death Sweep's crit damage remains unchanged.

Issue found in git build 505e246

**Comment by Zarania** [comment]
This is because it is bugged in game and does not reflect it.  I will double check that it hasn't been fixed very recently.

**Comment by Zarania** [comment]
From looking at logs, still bugged in game.  We've reported it, but it's not been fixed yet.
