### ISSUE TITLE
Simulationcraft contradicting itself? (Frost Mage)

### ISSUE THREAD

**Issue by Itsmesoft** [simulationcraft/simc#3709]
Hello! I have Simulationcraft for 7.2 (from April 8 2017)  installed and when I do a /simc and run the simulation it says I have 852400 dps. When I then put the Pawn string into Pawn (Pawn is the newest version) it suggests that a ring I have in my bags would be a 15% upgrade to one of the rings I have equipped.

When I then equip the suggested upgrade and run a new /simc the results only comes to 851400 dps wich is 1k dps less with the supposedly better ring. When I then put the Pawn string in it suggests that the two rings are equally good.

I have been doing this back and forth now 4 times with the same results. I find this confusing as the Simulationcraft 7.2 build (from April 8 2017) seems to be contradicting itself.

Also Im sitting at 32% ingame crit and yet Simulationcraft value crit the least for me and I have learned by reading that Frost Mage should be at 33.34%. Whats up with this? Why does Simulationcraft say that Crit is the least valued stat for me even though I havn't reached the crit "cap" yet?

This is what Simulationcraft tells me while I am on 32% crit in game:

Int: 1.00 Vers: 0.90 Haste: 0.84 Mastery: 0.58 Crit: 049

I find all this very confusing at it just doesn't add up and it's giving me the impression that Simulationcraft is not reliable! Am I missing something obvious here? Help to sort this out would be highly appreciated. 

Thanks :)

EDIT: Here is my battle.net profile - http://eu.battle.net/wow/en/character/draenor/Itsmesoft/simple

**Comment by vituscze** [comment]
This is a consequence of how stat scaling is done.

Simc takes your current stats, gets your average DPS, increases the stat that is being weighted by ~1300 (at level 110), gets your average DPS again. Stat weight is then simply DPS delta/1300.

If the stat weights change wildly between your stats and your stats + 1300 (as is the case when you're around shatter cap), stat scaling won't give accurate results. You can fight this by enabling centering of scale delta, or reducing the scale delta.

Actual average DPS you get by simming your profile is the ultimate metric, though.
