### ISSUE TITLE
All Simulationcraft builds post 7.1.5 broken in Vista:

### ISSUE THREAD

**Issue by Firebrandx** [simulationcraft/simc#3714]
Issue involves "TryAcquireSRWLockExclusive" which is a feature not available in Vista, and must have been added after 7.1.5 as that build still works in Vista.

For example using the latest public build of 7.2.0 64-bit:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SimulationCraft.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58ec355b
  Fault Module Name:	KERNEL32.dll!TryAcquireSRWLockExclusive
  Fault Module Version:	6.0.6002.19623
  Fault Module Timestamp:	56ec4641
  Exception Code:	c0000139
  Exception Offset:	00000000000b7e68
  OS Version:	6.0.6002.2.2.0.256.1
  Locale ID:	1033
  Additional Information 1:	fa3e
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	fa3e
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

**Comment by Collisionc** [comment]
I'll change the QT version back to 5.6.2, was trying to see if 5.8 would fix some odd crashes

**Comment by Firebrandx** [comment]
Cool, much appreciated. I'm saving up to build a new computer this year as this is the last year Microsoft will support Vista, but I'd like to be able to run my sims in the meantime. Cheers!

**Comment by Collisionc** [comment]
Ok, nightlies are now on qt 5.6.2
