### ISSUE TITLE
Incorrect Modeling for Arcanogolem Digit Proc

### ISSUE THREAD

**Issue by MoonBunnie** [simulationcraft/simc#3716]
Arcanogolem Digit (trinket) has an RPPM proc that deals damage in an area. Currently in SimC, this damage proc cannot crit (SimC reports 0% crit rate with the item) but the proc can definitely crit in game. 

See this [log](https://www.warcraftlogs.com/reports/r9vFVhACjN74WKBb/#view=analytical&type=damage-done&by=ability) for in game data with a character with 31.77% critical hit rate to see that the effect should crit.

#### Simulationcraft Version
720-02, git build f6e16cb

#### simc_gui.simc file or contents
https://pastebin.com/2Kfc45LY

#### Reproduction Steps:
1. import a character profile that has Arcanogolem Digit equipped (id=140794)
2. Sim character and note that crit rate on the Arcane Swipes ability is 0%

**Comment by nuoHep** [comment]
Should be fixed by 2dd443ec8db17f8f90678b63e87fae2d32d6998f

**Comment by MoonBunnie** [comment]
Confirming that it is fixed in latest nightly build.
