### ISSUE TITLE
Chaos Talisman

### ISSUE THREAD

**Issue by Dismoral** [simulationcraft/simc#3717]
tried simc my character and dat what i seen in simcraft
![image](https://cloud.githubusercontent.com/assets/6111696/25286623/1855d7ca-26c7-11e7-8787-daa6d21a75e4.png)
![image](https://cloud.githubusercontent.com/assets/6111696/25286632/22f294f2-26c7-11e7-9095-9a73fe208664.png)

dat trinket is http://www.wowhead.com/item=137459/chaos-talisman&bonus=1826#comments
but in simc its looks different

**Comment by navv1234** [comment]
Would need to get your armory to check what's going on here.

**Comment by Dismoral** [comment]
http://eu.battle.net/wow/en/character/ashenvale/%D0%94%D0%B8%D0%B7%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D1%8C/simple

shaman="Дизмораль"
level=110
race=orc
region=eu
server=
role=attack
professions=alchemy=800/herbalism=800
talents=2213112
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:3:906:3:907:3:908:3:909:4:910:4:911:4:912:4:913:3:930:1:1351:1:1388:1:1593:4:1594:1:1687:1

head=,id=138343,bonus_id=3516/1808/1487/1813,gem_id=130222
neck=,id=139239,enchant_id=5439,bonus_id=1806/1517/3337
shoulder=,id=140917,enchant_id=5883,bonus_id=3517/1492/1813
back=,id=138372,enchant_id=5435,bonus_id=3518/1808/1517/3337,gem_id=130222
chest=,id=138346,bonus_id=3516/1492/3336
wrist=,id=137084,bonus_id=1811/3455
hands=,id=137300,enchant_id=5444,bonus_id=3418/1808/1557/3337,gem_id=130222
waist=,id=140868,bonus_id=3516/1507/3337
legs=,id=138345,bonus_id=3516/1487/1813
feet=,id=134464,bonus_id=3418/1542/3528
finger1=,id=140897,enchant_id=5429,bonus_id=3517/1497/3336
finger2=,id=137050,enchant_id=5429,bonus_id=1811/3455,gem_id=130247
trinket1=,id=137459,bonus_id=3536/1552/3337
trinket2=,id=139329,bonus_id=1806/1507/3336
main_hand=,id=128819,bonus_id=745,relic_id=3535:1547:3337/3417:1507:3336/3509:1542:3337,gem_id=137316/142177/133682/0
off_hand=,id=128873,relic_id=0/0,gem_id=0/0/0/0

**Comment by Dismoral** [comment]
simmed 5 mins ago and all good, but simmed yesterday 3 times: 2 in 720-01 build and 1 in 720-02 and i saw wat i screened

**Comment by navv1234** [comment]
What you screenshotted makes no sense from simc point of view, I wonder if that was actually some sort of armory hiccup ... We can't really randomly make your items have a random suffix, unless someone explicitly tells us to (via a Bonus ID).

**Comment by pworek** [comment]
I've experienced the same bug using the simulationcraft addon ingame to export gear.
So far, I've gotten the harmonious affix for the following 3 trinkets:

900 Tempered Egg of Serpentrix (Proc from the trinket doesn't get simmed either)
trinket1=,id=137373,bonus_id=3418/1552/333

895 Chrono Shard
trinket1=,id=137419,bonus_id=3416/1547/333

885 Fury of the Burning Skies
trinket1=,id=140801,bonus_id=3514/1482/333

Using a nightly 720-02 build from a day or 5 ago, not sure. Don't know if it's a Simc bug or a bug related to the ingame addon. Can provide screenshots if it's helpful.
