### ISSUE TITLE
Outlaw Rogue: Pawn string contains wrong spec ID

### ISSUE THREAD

**Issue by oberstnova** [simulationcraft/simc#3720]
The Pawn stings for outlaw rogues contains the speccID "combat" instead of "outlaw". In result Pawn doesn't show the specc icon in tooltips.

wrong: 

( Pawn: v1: "Arturîus": Class=Rogue, Spec=Combat, Agility=19.29, CritRating=14.10, HasteRating=9.59, MasteryRating=9.72, Versatility=14.79 )

correct would be:

( Pawn: v1: "Arturîus": Class=Rogue, Spec=Outlaw, Agility=19.29, CritRating=14.10, HasteRating=9.59, MasteryRating=9.72, Versatility=14.79 )

Kind regards

#### Simulationcraft Version
720-02 release

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,int,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
rogue="Arturîus"
level=110
race=worgen
region=eu
server=amanthul
role=attack
professions=mining=800/jewelcrafting=800
talents=3213222
spec=outlaw
artifact=44:0:0:0:0:1052:1:1053:1:1054:1:1055:1:1056:1:1057:1:1058:1:1059:3:1060:3:1061:4:1062:4:1063:3:1064:4:1065:4:1066:3:1067:3:1348:1:1385:1:1581:4:1582:1:1583:1:1652:1

head=,id=138332,bonus_id=3514/1492/3337
neck=,id=140900,enchant_id=5439,bonus_id=3516/1492/3336
shoulder=,id=142144,enchant_id=5441,bonus_id=3414/1507/3337
back=,id=138371,enchant_id=5435,bonus_id=3516/1487/1813
chest=,id=138326,bonus_id=3516/1497/3336
wrist=,id=137099,bonus_id=1811/3455
hands=,id=134443,bonus_id=3536/1552/3337
waist=,id=140858,bonus_id=3444/1482/1813
legs=,id=138335,bonus_id=3514/41/1472/1813
feet=,id=147738,bonus_id=3572/1808/1482/3528,gem_id=130221
finger1=,id=137049,enchant_id=5430,bonus_id=1811/3530,gem_id=130247
finger2=,id=144478,enchant_id=5430,bonus_id=1727/1808/1542/3337,gem_id=130221
trinket1=,id=140806,bonus_id=3514/1472/1813
trinket2=,id=140802,bonus_id=3514/1482/3336
main_hand=,id=128872,bonus_id=742,relic_id=3454:1482:3336/3515:1492:3337/3514:1477:3336,gem_id=143524/140817/140841/0
off_hand=,id=134552,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by Mystler** [comment]
Fixed this in adab529.
