### ISSUE TITLE
Mantle of the Astral Warden WRONG STATS

### ISSUE THREAD

**Issue by Streetfarm** [simulationcraft/simc#3721]
Nightly Simulationcraft Version

Take a look at this: Every time I sim Mantle of the Astral Warden, extra stats are added. Doesn't matter if I use the downloaded program or raidbots.com. Release version has the same problem.

![untitled](https://cloud.githubusercontent.com/assets/27927211/25316605/74ad2b96-286a-11e7-9d8a-148a9f4d27db.png)

druid="Streetfarm"
level=110
race=night_elf
region=eu
server=auchindoun
role=attack
professions=herbalism=800/enchanting=800
talents=2313322
spec=feral
artifact=58:0:0:0:0:1153:1:1154:1:1155:1:1156:1:1157:1:1158:1:1159:1:1160:3:1161:4:1162:4:1163:3:1164:4:1165:3:1166:4:1167:4:1168:3:1327:1:1365:1:1505:4:1506:1:1507:1:1633:1

head=,id=140866,bonus_id=3518/1502/3528
neck=,id=140899,enchant_id=5439,bonus_id=3518/1502/1813
shoulder=,id=138336,bonus_id=3516/1497/3336
back=,id=138366,enchant_id=5435,bonus_id=3518/1502/1813
chest=,id=138324,bonus_id=3518/1507/3336
wrist=,id=140857,bonus_id=3518/42/1512/3336
hands=,id=138327,enchant_id=5444,bonus_id=3516/1487/1813
waist=,id=140919,bonus_id=3517/41/1507/3337
legs=,id=144354,bonus_id=3529/3530/1811
feet=,id=137024,bonus_id=1811/3455
finger1=,id=134527,enchant_id=5429,bonus_id=3536/1552/3337
finger2=,id=133637,enchant_id=5429,bonus_id=3536/1808/1552/3337,gem_id=130247
trinket1=,id=139329,bonus_id=1806/1517/3337
trinket2=,id=140802,bonus_id=3518/1808/1502/1813,gem_id=130222
main_hand=,id=128860,bonus_id=723,relic_id=3518:1502:3528/3516:1497:3336/3418:1542:3528,gem_id=140832/140819/137327/0
off_hand=,id=128859,relic_id=0/0,gem_id=0/0/0/0

**Comment by navv1234** [comment]
Wowdb has wrong stats on that item, which are out of our hands to fix (this is what you see on the tooltip). Simc uses the stats shown in the report, i.e., ilevel: 900, stats: { 291 Armor, +2442 Sta, +1628 AgiInt, +805 Haste, +433 Mastery }

**Comment by Streetfarm** [comment]
Ah that is great news, so I can reliably sim my gear now without fear of wrong stat weights
