### ISSUE TITLE
Minimum GCD in Simulationcraft and in Game

### ISSUE THREAD

**Issue by ready3** [simulationcraft/simc#3724]
This is not a report of a bug, but instead requesting confirmation that a key parameter in Simulationcraft is correct.  The minimum GCD shows as 0.75 for Shadow Priest spells achievable with Haste, Buffs, Spells, and Trinkets which can increase haste percentages well above 200%.

I understand DoT's benefit from the entire amount of haste, but from a pure casting frequency I thought the in game GCD was hard stopped at 1.00 seconds.  I saw where they were considering a trial experiment during BETA testing where they might reduce it to 0.75 seconds, but I can not locate any blue posts or even chat posts where this was implemented.  Is the 0.75 second minimum GCD for casters definitely in game?

Thanks.

**Comment by vituscze** [comment]
Yes, it is. You can easily check this by enabling combat logging and spamming instants at 100% (or more) haste. For example: https://www.warcraftlogs.com/reports/hbcR2d6a8AvKPmzg#fight=13&view=events&type=casts&source=9
