### ISSUE TITLE
Balance Druid - Stellar Empowerment not being calculated

### ISSUE THREAD

**Issue by wor2** [simulationcraft/simc#3727]
I hope I'm putting all the information in that I need to. Stellar Empowerment is basically mastery for balance druids. I'm pretty sure it isn't calculating it correctly because 7.1.5 when I was simming 3 targets mastery was the top stat. There hasn't been any changes to it since then but the 7.2 simming is putting it crazy low. It's saying my stat priority went from haste > mastery > vers > crit > int... to... crit > vers > int > haste > mastery which seems... VERY wrong.

I've also been asking on the boomkin discord and they've all been saying stellar empowerment isn't simming correctly but I didn't see any bug posts about it so hopefully this helps!

Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
720-03

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
N/A

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

DPS Ranking:
1461176 100.0%  Raid
1461176  100.0%  Gev

HPS Ranking:
      0 100.0%  Raid

Player: Gev night_elf druid balance 110
  DPS: 1461175.5  DPS-Error=682.8/0.047%  DPS-Range=126973/8.7%  DPS-Convergence=72.4%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=179322.4  RPS-Out=8.1 RPS-In=8.1  Resource=(astral_power) Waiting=0.0 ApM=45.9
  Talents: 3233112
  Artifact: 59:0:0:0:0:1034:3:1035:3:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:3:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1632:1
  Core Stats:    strength=4723|4398(4398)  agility=9359|9034(9034)  stamina=56876|56876(42053)  intellect=50781|49075(47105)  spirit=0|0(0)  health=3412560|3412560  mana=704000|704000
  Generic Stats: mastery=72.58%|72.58%(9703)  versatility=0.59%|0.59%(281)  leech=0.00%|0.00%(0)  runspeed=7.18%|7.18%(534)
  Spell Stats:   power=50781|49075(0)  hit=15.00%|15.00%(0)  crit=14.66%|14.66%(3465)  haste=31.69%|30.69%(11510)  speed=31.69%|30.69%  manareg=0|0(0)
  Attack Stats:  power=9359|9034(0)  hit=7.50%|7.50%(0)  crit=14.66%|14.66%(3465)  expertise=7.50%|7.50%(0)  haste=31.69%|30.69%(11510)  speed=31.69%|30.69%
  Defense Stats: armor=9214|2457(2457) miss=3.00%|3.00%  dodge=5.40%|5.01%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=0.30%|0.30%(281)
  Priorities (actions.precombat):
    flask,type=flask_of_the_whispered_pact/food,type=azshari_salad
    augmentation,type=defiled/moonkin_form/blessing_of_elune/snapshot_stats
    potion,name=deadly_grace/new_moon
  Priorities:
    potion,name=deadly_grace,if=buff.celestial_alignment.up|buff.incarnation.up
    blessing_of_elune,if=active_enemies<=2&talent.blessing_of_the_ancients.enabled&buff.blessing_of_elune.down
    blessing_of_elune,if=active_enemies>=3&talent.blessing_of_the_ancients.enabled&buff.blessing_of_anshe.down
    blood_fury,if=buff.celestial_alignment.up|buff.incarnation.up
    berserking,if=buff.celestial_alignment.up|buff.incarnation.up
    arcane_torrent,if=buff.celestial_alignment.up|buff.incarnation.up
    call_action_list,name=fury_of_elune,if=talent.fury_of_elune.enabled&cooldown.fury_of_elue.remains<target.time_to_die
    call_action_list,name=ed,if=equipped.the_emerald_dreamcatcher&active_enemies<=2
    new_moon,if=(charges=2&recharge_time<5)|charges=3
    half_moon,if=(charges=2&recharge_time<5)|charges=3|(target.time_to_die<15&charges=2)
    full_moon,if=(charges=2&recharge_time<5)|charges=3|target.time_to_die<15
    stellar_flare,cycle_targets=1,max_cycle_targets=4,if=active_enemies<4&remains<7.2&astral_power>=15
    moonfire,cycle_targets=1,if=(talent.natures_balance.enabled&remains<3)|(remains<6.6&!talent.natures_balance.enabled)
    sunfire,if=(talent.natures_balance.enabled&remains<3)|(remains<5.4&!talent.natures_balance.enabled)
    astral_communion,if=astral_power.deficit>=75/incarnation,if=astral_power>=40
    celestial_alignment,if=astral_power>=40/starfall,if=buff.oneths_overconfidence.up
    solar_wrath,if=buff.solar_empowerment.stack=3
    lunar_strike,if=buff.lunar_empowerment.stack=3
    call_action_list,name=celestial_alignment_phase,if=buff.celestial_alignment.up|buff.incarnation.up
    call_action_list,name=single_target
  Priorities (actions.celestial_alignment_phase):
    starfall,if=((active_enemies>=2&talent.stellar_drift.enabled)|active_enemies>=3)
    starsurge,if=active_enemies<=2/warrior_of_elune
    lunar_strike,if=buff.warrior_of_elune.up/solar_wrath,if=buff.solar_empowerment.up
    lunar_strike,if=buff.lunar_empowerment.up
    solar_wrath,if=talent.natures_balance.enabled&dot.sunfire_dmg.remains<5&cast_time<dot.sunfire_dmg.remains
    lunar_strike,if=(talent.natures_balance.enabled&dot.moonfire_dmg.remains<5&cast_time<dot.moonfire_dmg.remains)|active_enemies>=2
    solar_wrath
  Priorities (actions.single_target):
    new_moon,if=astral_power<=90/half_moon,if=astral_power<=80
    full_moon,if=astral_power<=60
    starfall,if=((active_enemies>=2&talent.stellar_drift.enabled)|active_enemies>=3)
    starsurge,if=active_enemies<=2/warrior_of_elune
    lunar_strike,if=buff.warrior_of_elune.up/solar_wrath,if=buff.solar_empowerment.up
    lunar_strike,if=buff.lunar_empowerment.up
    solar_wrath,if=talent.natures_balance.enabled&dot.sunfire_dmg.remains<5&cast_time<dot.sunfire_dmg.remains
    lunar_strike,if=(talent.natures_balance.enabled&dot.moonfire_dmg.remains<5&cast_time<dot.moonfire_dmg.remains)|active_enemies>=2
    solar_wrath
  Actions:
    celestial_alignment  Count=  3.2|109.62sec  DPE=      0| 0%  DPET=      0  DPR=    0.0  pDPS=     0
    deadly_grace    Count= 37.8|  3.86sec  DPE= 143462| 1%  DPET=      0  DPR=    0.0  pDPS= 18421  Miss=0.00%  Hit=124955|101184|139432  Crit=250048|202369|278864|14.8%
    echoing_stars   Count=  0.0|  0.00sec  DPE=      0|10%  DPET=      0  DPR=    0.0  pDPS=151104  MissTick=0.0%  Tick=27344|25717|33432  CritTick=54684|51434|66865|14.7%
    full_moon       Count=  7.1| 43.15sec  DPE=1302810| 2%  DPET= 622011  DPR=    0.0  pDPS= 30767  Miss=0.00%  Hit=429013|421169|429268  Crit=858025|842337|858536|14.7%
    half_moon       Count=  7.4| 42.46sec  DPE= 732729| 1%  DPET= 540441  DPR=    0.0  pDPS= 18121  Miss=0.00%  Hit=642248|625679|837073  Crit=1284580|1251358|1287805|14.5%
    lunar_strike    Count= 96.6|  3.04sec  DPE= 523771|12%  DPET= 317827  DPR=    0.0  pDPS=169284  Miss=0.00%  Hit=129669|75382|279991  Crit=259325|150764|559982|34.6%
    moonfire        Count= 28.1| 11.13sec  DPE=2624971|17%  DPET=2537955  DPR=    0.0  pDPS=246517  Miss=0.00%  Hit=300147|125445|388944  Crit=600059|250891|777887|14.6%  TickCount=675  MissTick=0.0%  Tick=70247|62724|86433  CritTick=140526|125448|172867|14.7%  UpTime=299.0%
    new_moon        Count=  6.7| 44.37sec  DPE= 420087| 1%  DPET= 400045  DPR=    0.0  pDPS=  9489  Miss=0.00%  Hit=319605|303728|321952  Crit=639042|607457|643904|14.8%
    potion          Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=      0  DPR=    0.0  pDPS=     0
    shooting_stars  Count=134.6|  2.21sec  DPE=  42534| 1%  DPET=      0  DPR=    0.0  pDPS= 19117  Miss=0.00%  Hit=42207|35694|51971  Crit=84381|71389|103942|14.7%
    starfall        Count= 60.9|  4.87sec  DPE=3708669|41%  DPET=3683079  DPR=92716.2  pDPS=604457  MissTick=0.0%  Tick=109372|102869|133729  CritTick=218761|205737|267458|14.7%
    starsurge       Count=  0.0|  0.00sec  DPE=1174184| 0%  DPET=      0  DPR=29366.4  pDPS=     0  Miss=0.00%  Crit=1174184|1174184|1174184|100.0%
    sunfire         Count= 17.3| 17.72sec  DPE=3356349|13%  DPET=3287701  DPR=    0.0  pDPS=193899  Miss=0.00%  Hit=247526|200463|310768  Crit=494996|400927|621536|14.7%  TickCount=672  MissTick=0.0%  Tick=56160|50117|69061  CritTick=112321|100233|138122|14.7%  UpTime=297.4%
  Constant Buffs: azshari_salad/defiled_augmentation/flask_of_the_whispered_pact/moonkin_form
  Dynamic Buffs:
    accelerando            : start=19.8 refresh=  0.0 interval= 15.5 trigger= 15.5 uptime=77.62%  benefit=78%
    bloodlust              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.58%  benefit=14%
    celestial_alignment    : start= 3.2 refresh=  0.0 interval=109.6 trigger=109.6 uptime=15.99%  benefit=16%
    devils_due             : start= 3.5 refresh=  0.0 interval= 69.6 trigger= 69.6 uptime= 8.70%  benefit= 9%
    lunar_empowerment      : start= 0.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 0.00%  benefit= 0%
    nefarious_pact         : start= 3.5 refresh=  0.0 interval= 70.0 trigger= 69.3 uptime=13.63%  benefit=14%
    potion_of_deadly_grace : start= 2.0 refresh=  0.0 interval=110.9 trigger=  0.0 uptime=19.70%  benefit=20%
    solar_empowerment      : start= 0.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 0.00%  benefit= 0%
    star_power             : start= 3.2 refresh= 38.1 interval=109.6 trigger=  6.4 uptime=15.99%  benefit=18%
    wax_and_wane           : start= 1.0 refresh= 55.2 interval=  0.0 trigger=  5.5 uptime=100.00%  benefit=100%
  Up-Times:
      0.0% : Astral Power Cap              
  Gains:
        77.3 : new_moon       (astral_power)
       147.7 : half_moon      (astral_power)
       282.7 : full_moon      (astral_power)
        84.1 : moonfire       (astral_power)
       538.3 : shooting_stars (astral_power)
        51.8 : sunfire        (astral_power)
         0.0 : solar_wrath    (astral_power)
      1280.2 : lunar_strike   (astral_power)
  Scale Factors:
    Weights :  Int=29.94(0.75)  SP=0.00(0.00)  Crit=31.55(0.76)  Haste=28.16(0.75)  Mastery=24.84(0.75)  Vers=30.64(0.75)
    Wowhead : 
  Waiting: 0.00%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|197742241  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)      : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.45%  benefit=10%
    Health Decade (10 - 20)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.53%  benefit=11%
    Health Decade (20 - 30)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.51%  benefit=11%
    Health Decade (30 - 40)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.95%  benefit=11%
    Health Decade (40 - 50)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.61%  benefit=11%
    Health Decade (50 - 60)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.53%  benefit=10%
    Health Decade (60 - 70)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.64%  benefit=11%
    Health Decade (70 - 80)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.23%  benefit=11%
    Health Decade (80 - 90)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.82%  benefit= 9%
    Health Decade (90 - 100)    : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 6.73%  benefit= 7%
    circadian_invocation_arcane : start= 1.0 refresh=234.4 interval=  0.0 trigger=  1.3 uptime=100.00%  benefit=100%
    circadian_invocation_nature : start= 1.0 refresh=240.2 interval=  1.9 trigger=  1.2 uptime=99.34%  benefit=100%
    stellar_empowerment         : start=57.1 refresh=  3.8 interval=  5.2 trigger=  4.9 uptime=29.91%  benefit=30%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Target: enemy2 humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|179844227  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)      : start= 0.9 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 2.50%  benefit= 3%
    Health Decade (10 - 20)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.10%  benefit=11%
    Health Decade (20 - 30)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.31%  benefit=11%
    Health Decade (30 - 40)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.46%  benefit=11%
    Health Decade (40 - 50)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.11%  benefit=12%
    Health Decade (50 - 60)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.49%  benefit=10%
    Health Decade (60 - 70)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.83%  benefit=11%
    Health Decade (70 - 80)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.25%  benefit=12%
    Health Decade (80 - 90)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.27%  benefit=10%
    Health Decade (90 - 100)    : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 7.67%  benefit= 8%
    circadian_invocation_arcane : start= 1.0 refresh=233.1 interval=  1.4 trigger=  1.3 uptime=99.57%  benefit=100%
    circadian_invocation_nature : start= 1.0 refresh=222.9 interval=  3.0 trigger=  1.3 uptime=98.96%  benefit=100%
    stellar_empowerment         : start=57.1 refresh=  3.8 interval=  5.2 trigger=  4.9 uptime=29.91%  benefit=30%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Target: enemy3 humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|175452482  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)      : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.52%  benefit= 5%
    Health Decade (10 - 20)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.01%  benefit=11%
    Health Decade (20 - 30)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.14%  benefit=11%
    Health Decade (30 - 40)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.30%  benefit=11%
    Health Decade (40 - 50)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.77%  benefit=12%
    Health Decade (50 - 60)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.07%  benefit=10%
    Health Decade (60 - 70)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.71%  benefit=11%
    Health Decade (70 - 80)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.01%  benefit=12%
    Health Decade (80 - 90)     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.95%  benefit=10%
    Health Decade (90 - 100)    : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 7.53%  benefit= 8%
    circadian_invocation_arcane : start= 1.0 refresh=232.8 interval=  1.0 trigger=  1.3 uptime=99.57%  benefit=100%
    circadian_invocation_nature : start= 1.0 refresh=222.9 interval=  3.0 trigger=  1.3 uptime=98.96%  benefit=100%
    stellar_empowerment         : start=57.1 refresh=  3.8 interval=  5.2 trigger=  4.9 uptime=29.91%  benefit=30%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
    All players active 100% of the time.

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10003
  TotalEvents   = 73675399
  MaxEventQueue = 124
  TargetHealth  = 197742241
  SimSeconds    = 2994593
  CpuSeconds    = 36.359
  WallSeconds   = 21.997
  SpeedUp       = 82361
  EndTime       = 2017-04-26 23:44:46-0500 (1493268286)

Scale Factors:
  Gev  Int=29.94(0.75)  SP=0.00(0.00)  Crit=31.55(0.76)  Haste=28.16(0.75)  Mastery=24.84(0.75)  Vers=30.64(0.75)

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

druid="Gev"
level=110
race=night_elf
region=us
server=silver_hand
role=spell
professions=alchemy=800/herbalism=216
talents=3233112
spec=balance
artifact=59:0:0:0:0:1034:3:1035:3:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:3:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1632:1

head=,id=140901,bonus_id=3445/1497/3528
neck=,id=137535,enchant_id=5890,bonus_id=3418/1557/3337
shoulder=,id=144295,enchant_id=5883,bonus_id=3529/3530/1811
back=,id=140909,enchant_id=5436,bonus_id=3516/1512/3337
chest=,id=140865,bonus_id=3445/1507/3336
wrist=,id=134459,bonus_id=3536/1552/3337
hands=,id=137509,enchant_id=5444,bonus_id=3536/1552/3337
waist=,id=139243,bonus_id=3418/1808/1542/3528,gem_id=130220
legs=,id=134449,bonus_id=3418/1557/3337
feet=,id=147738,bonus_id=3572/1487/3336
finger1=,id=134487,enchant_id=5428,bonus_id=3418/42/1562/3337
finger2=,id=137039,enchant_id=5428,bonus_id=3459/3530,gem_id=130248
trinket1=,id=140792,bonus_id=3445/1497/3528
trinket2=,id=140809,bonus_id=3517/1492/3528
main_hand=,id=128858,bonus_id=722,relic_id=3536:1557:3337/1806:1522:3337/3444:1512:3337,gem_id=133768/139263/140812/0

That is what I plugin to simulation craft.

**Comment by Slippykins** [comment]
Yep, can confirm Stellar Empowerment is not working at all in the most recent nightly build, and hasn't been working for a couple of weeks now. Was working perfectly fine prior to that.

**Comment by Killuha** [comment]
As of 23826 Stellar Empowerment duration is still set to 1.5 seconds rather than 8 seconds. This is reflected in the uptime of the Stellar Empowerment debuff as well as the periodic damage of Moonfire and Sunfire.

Fixable via override: 
`override.spell_data=spell.197637.duration=8000`

**Comment by Xanzara** [comment]
It seems Blizzard removed all useful spelldata, regardless I hard-coded in the proper duration so it should work from now on.

**Comment by wor2** [comment]
TY much! Will this show up in the nightly build?
