### ISSUE TITLE
Old gear socket bonuses are added twice, timewalking errors

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#3728]
Doing some timewalking shenanigans, I noticed some of the older gear stuff is wrong. Most socket bonuses are added twice when activated

simc_gui.simc -> http://codepad.org/dlpM63eD (html report will show this)

Also, may not be your fault; when importing from the "import" -> "import" tab within the GUI, some of the resulting equipment's enchant strengths are wrong; The neck enchant is imported as a straight 75 mastery instead of 'gift of mastery', like the cloak which is imported correctly and scaled back in strength correctly. The same thing happens with the gem in trinket1 slot.

Also some of the enchants are incorrect at that level. Shoulder enchant at that level is 16str 4crit, chest is [s]7 stats[/s] (actually, tooltip error on blizz side, actually 4 stats is correct), legs is actually 14 str 8 crit. This is assuming wotlk timewalking ilvl 175.

**Comment by navv1234** [comment]
Gonna need a character for this to play around with (so that API returns the data), and simc addon output would be helpful. I fixed the double socket bonus issue though.
