### ISSUE TITLE
Stat weights off for BM hunters - see description below

### ISSUE THREAD

**Issue by ceylina** [simulationcraft/simc#3731]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
720-02

There is no way on a BM hunter that this

http://www.wowhead.com/item=137535/lavadrip-pendant&bonus=1552:1808:3412
(Lavadrip pendant - item level 900 with a socket - 1173 haste and 1750 mastery)

is a 10k dps loss over

http://www.wowhead.com/item=140899/belerons-choker-of-misery&bonus=1492:3516

(Beleron's choker of misery - item level 895 with a socket - 1626 crit, 1219 mastery)

Both have the 150 mastery gem in them 

This is my armory page to get an idea of my stats

http://us.battle.net/wow/en/character/whisperwind/Breech/advanced

With the lavadrip, my stats are 16.47% crit, 19.21% haste, and 90.53% mastery

Beleron's drops it to 
20.55% crit, 16.05% haste, and 87.49% mastery.

there is just no way, with crit being depreciated with the recent changes to BM that 20% crit is more valuable than 19% haste andr 90% mastery

Here is the output of the sim (only change is neck)

![results](https://cloud.githubusercontent.com/assets/9342192/25490146/90dc11c8-2b31-11e7-8428-dbd75c5266cf.jpg)

**Comment by AlexanderKenny** [comment]
Can't tell because you included a picture instead of just the report (or your profile or really anything relevant to debugging if this were an actual issue) but you added a neck enchant when you simmed right? Because your armory does not have one and that would easily explain a difference.

**Comment by ceylina** [comment]
I figured it out. and it was on my end. Closing this out.
