### ISSUE TITLE
None of my artifacts shows any relics in them from simulationcraft addon

### ISSUE THREAD

**Issue by peterpekkanen** [simulationcraft/simc#3741]
I get the error message for example "Ebonchill (128862) slot 1 / 2  / 3 no longer has a relic in it?"

Whenever I type /simc it just shows my artifact tree with no error message, same goes for every other artifact that I'm currently using across all characters.

I have tried to reinstall simulationcraft multiple times & I havent found a fix so far by googling it.

How do I fix the problem?

**Comment by AlexanderKenny** [comment]
Did you update the addon recently (or just reinstall SimC)? The addon was broken briefly with 7.2/is all that is relevant to what is displayed in-game.

**Comment by peterpekkanen** [comment]
I manually reinstalled simc &, saw yday that my twitch addon installed the updated version of simc in a entirely different folder, but thanks for the reply! :)
