### ISSUE TITLE
Stats to scale window unreadable

### ISSUE THREAD

**Issue by MartimCorreia** [simulationcraft/simc#3742]
Hello, 

So i accidentaly posted the /simc code where it wasnt supose and after that my stats to scale window bugged out i cant see nothin in there.. I got a picture of how it looks like and another where i show where i pasted the code. I've already tryed to uninstall and re-install but it doesnt seem to help.

Best regards, Martim
![simbug](https://cloud.githubusercontent.com/assets/28545626/25825526/2cc2e1d6-343b-11e7-81b4-7969443a8bd2.jpg)

![simbug2](https://cloud.githubusercontent.com/assets/28545626/25825535/336d555c-343b-11e7-9eb9-f9bccc104213.jpg)

**Comment by navv1234** [comment]
Did you try resetting the settings?

**Comment by navv1234** [comment]
I have forced that particular window now to have a minimum height, and spread the options horizontally into groups.
