### ISSUE TITLE
simcarft won't start up

### ISSUE THREAD

**Issue by stiffan** [simulationcraft/simc#3743]
yes i just download 720-2 and it won't start up at all

**Comment by stefanw1337** [comment]
I can't get it to run either, getting error that api-ms-win-crt-locale-l1-1-0.dll is missing. Tried downloading it and putting it in System32, SysWOW64 and the SimulationCraft folder, to no avail.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/wiki/CommonIssues

Options 2 or 3 should fix it.

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
