### ISSUE TITLE
Can't change iterations in nightly build

### ISSUE THREAD

**Issue by Xintho** [simulationcraft/simc#3745]
When trying to set up options I'm unable to change the number of iterations to run. I've tried the "Reset All Settings" button as well as reloading the program and even restarting my computer and it's still grayed out. I've had no issues with this in the last 7 months or so and I've been getting the nightly build usually once every other week.

Version: simc-720-03-win64-93a7b7f.7z	2017-05-08 16:0

**Comment by Mystler** [comment]
I suppose you have target error set? In that case, Iterations is grayed out because it does as many iterations as needed to get to that target error point (which is also explained in the tooltip, if I'm not mistaken).
