### ISSUE TITLE
Unable to import character since the new WoW toon profile page

### ISSUE THREAD

**Issue by Aeryndil** [simulationcraft/simc#3749]
Simulationcraft Version MAC OS X 720 r 2

I am unable to import my toon into SimC from the armory/Blizz page.  This only started after Blizz implemented the new Character Profile page.

**Comment by lgkern** [comment]
Try using the tab that imports using Region/Realm dropdowns and character name, that should work as long as the armory API is responding

**Comment by Drevil-Dion** [comment]
I can confirm the original report and also confirm that Igkern's comment works to import your characters.

**Comment by Aeryndil** [comment]
it must be an API issue on the Blizz end - sometimes it works, sometimes it doesn't.  I always import via the import tab with realm and toon name.  At first I thought it might be a capitalization thing, but ruled that out pretty quick.  Still occasionally give an error.

**Comment by penguinlust** [comment]
It works fine on the released 720-02, but if I build it myself it doesn't work at all.

**Comment by lgkern** [comment]
HTML import has been removed in the dev branch, which will likely be going to release as well. The other import options (addon, API, etc) are still available
