### ISSUE TITLE
ProtWarrior Anger Management talent issue

### ISSUE THREAD

**Issue by sergeysh93** [simulationcraft/simc#3754]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
simc-720-03-win64-f334c7e

Protection warrior talent anger management id=152278, doesn't reduce cd on battle cry id=1719 properly

**Comment by lgkern** [comment]
Prot and other tank/healing specs aren't actively supported, save few exceptions, you can find more about it at: https://github.com/simulationcraft/simc/issues/2775

**Comment by Collisionc** [comment]
protection warrior is one of the few that is supported, just doesn't have an updated action list.
