### ISSUE TITLE
DH Relic

### ISSUE THREAD

**Issue by Baelrah** [simulationcraft/simc#3756]
720-02 Simulationcraft Version

The relic Sealed Fel Fissure doesn't apper to be correctly showing warforged IL increases. The sim shows me using a rare quality that is bring the item level of my weapon down to 879. I currently have an 890 Mythic 7 warforged equipped and the item level of my weapon should be 910. If this has already been address I apologize. I've attached some pictures to show the difference. The bottom picture is what the Sim is showing and the top picture is what I have equipped. 

![dh relic 2](https://cloud.githubusercontent.com/assets/28697934/26042999/780bdd6e-38ff-11e7-8738-f1f5d4c5909e.jpg)
![dh relic](https://cloud.githubusercontent.com/assets/28697934/26043002/7fb530e2-38ff-11e7-9c6f-c47ba0a065b7.jpg)

**Comment by AlexanderKenny** [comment]
The tooltip that is pulled from wowhead is irrelevant (and entirely on their end). If you check the text print out below that you can see your weapon as far as the sim is concerned is correctly 910.

**Comment by lgkern** [comment]
As mentioned above, don't give much credit to tooltips, check the string below the item to see its stats.
