### ISSUE TITLE
Simcraft Won't Open

### ISSUE THREAD

**Issue by rutigs** [simulationcraft/simc#3759]
Latest stable 720-02 or even the newest nightly's won't open.

Windows 10 Version 1703 (OS Build 15063.296)

From Windows Logs > Application

Error Log:
Faulting application name: SimulationCraft.exe, version: 0.0.0.0, time stamp: 0x58fa1ac2
Faulting module name: nvoglv64.DLL, version: 22.21.13.8165, time stamp: 0x58df0143
Exception code: 0xc0000005
Fault offset: 0x0000000000c1035d
Faulting process id: 0xc30
Faulting application start time: 0x01d2cea32c72a71a
Faulting application path: D:\Programs\Simuationcraft(x64)\720-02\SimulationCraft.exe
Faulting module path: C:\WINDOWS\SYSTEM32\nvoglv64.DLL
Report Id: 02dcf891-6f63-499f-86a0-fe0df0a1e1f5
Faulting package full name: 
Faulting package-relative application ID: 

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-05-17T00:18:57.928923000Z" /> 
  <EventRecordID>536</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SimulationCraft.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>58fa1ac2</Data> 
  <Data>nvoglv64.DLL</Data> 
  <Data>22.21.13.8165</Data> 
  <Data>58df0143</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000c1035d</Data> 
  <Data>c30</Data> 
  <Data>01d2cea32c72a71a</Data> 
  <Data>D:\Programs\Simuationcraft(x64)\720-02\SimulationCraft.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\nvoglv64.DLL</Data> 
  <Data>02dcf891-6f63-499f-86a0-fe0df0a1e1f5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by exoursia** [comment]
Same problem here, SimC not responding at all when I open it. Just nothing happening.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/wiki/CommonIssues

Option three should fix this for you. This is ultimately a nvidia driver problem with specific chipsets on creator's update, somethings swapping drivers will fix it as well.
