### ISSUE TITLE
mannoroths_bloodletting_manacles slows things to a crawl

### ISSUE THREAD

**Issue by penguinlust** [simulationcraft/simc#3762]
Normally I peg all 16 (virtual) cores when running on high priority, but with mannoroths_bloodletting_manacles only 8 show activity and it's minimal (maybe two get to 50 percent utilization). I suspect it's trying to simulate the healing effect, which has no relevance in a dps simulation. In any event, it increases the simulation time by an order of magnitude.

#### Simulationcraft Version
720-02, 720-03 nightly builds

#### simc_gui.simc file or contents
No such file (running this on OS X)

#### Reproduction Steps:
Import a character (warrior) with mannoroths_bloodletting_manacles, simulate.

**Comment by Zarania** [comment]
Issue is probably that this line is getting the driver repeatedly each action which means it's checking the DBC.  Caching the values would solve the issue.

https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_warrior.cpp#L839

**Comment by penguinlust** [comment]
Easy enough to check. Since the calculation isn't relevant to simulating dps in my case, I'll just change it to an if(0) and see what happens.

Edit: Did this and the problem went away. So this is in fact the problem line.

Edit 2: with the revisions to the file for other issues, the problem line is no longer the same as shown in the link. It should be:

p() -> resource_gain( RESOURCE_HEALTH, ( ( tactician_cost() / p() -> mannoroths_bloodletting_manacles -> driver() -> effectN( 2 ).base_value() ) * p() -> mannoroths_bloodletting_manacles -> driver() -> effectN( 1 ).percent() ) * p() -> resources.max[RESOURCE_HEALTH], p() -> gain.mannoroths_bloodletting_manacles );

**Comment by vituscze** [comment]
Fixed in 6ce96864bb895e12d1f0424f476c0a610399b329
