### ISSUE TITLE
Custom APL = SimulationCraft has stopped working

### ISSUE THREAD

**Issue by Tanklordgodx** [simulationcraft/simc#3763]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
7.2.0 build 2
#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/1012634/DxDiag.txt)

#### simc_gui.simc file or contents
https://pastebin.com/tJTgyPA5

#### Reproduction Steps:
I replace the original apl with a custom apl I've gotten from the monk discord for brewmaster DPS, I then hit simulate and a pop up comes up saying "SimulationCraft has stopped working". 
Program works fine when I use the original apl and another person in the discord has tried my export and it works fine for them. Here's what I replace
![what i do](https://cloud.githubusercontent.com/assets/28793966/26226870/dea28f50-3bfc-11e7-8dd8-89069ae4b9e3.png)

and here's the export that works for them but not for me
https://pastebin.com/v3ApEatt

**Comment by 012299** [comment]
It won't fix whatever causes this, but you could try setting player skill level to elite and it'll most likely work.

**Comment by Tanklordgodx** [comment]
That DID fix it...
Damnit, I thought "well I'm only a good player, not elite so I think good will simulate my dps more"

Closing the thread with this. Thanks for that.
