### ISSUE TITLE
[Death Knight] Unholy only cast's Army of the Dead during pre pull

### ISSUE THREAD

**Issue by BanterDK** [simulationcraft/simc#3764]
_Simulationcraft Version git build 58e75e0 - 7.2.5 PTR_

Basically the APL only ever casts AotD on pre pull. 

Due to Legion AotD buffs and the tier 20 4p (-3s/Rune Spent), the player would be casting it a lot more often/likely on CD. This issue is somewhat important considering its synergy with t20 + Dark Arbiter.

**Comment by navv1234** [comment]
Fixed in f7d7232d7.
