### ISSUE TITLE
scale_to_itemlevel not overriding timewalk=70's forced 95ilvl

### ISSUE THREAD

**Issue by JBA9084** [simulationcraft/simc#3767]
I would like to use Simcraft to sim some pieces of gear to use for Timewalking in the new Black Temple raid coming in tomb.

The default iLvl for the timewalk option in Simcraft sets the ilvl to 95, but the ilvl for Black Temple timewalking will be 141. I would like to sim lvl 70 timewalking but at 141 item level.

I thought that including an overwritten item level would cancel out the forced 95 ilvl, but it did not work.

#### simc_gui.simc file or contents
timewalk=70
scale_to_itemlevel=141

#### Reproduction Steps:

Step 1. Type timewalk=70 at the top of the profile in the Simulate tab.
Step 2. Type scale_to_itemlevel=141 beneath or above it, I do not know if it matters.
Step 3. Simulate, and you end up with the forced itemlevel scale being ignored and the items instead scaled to 95.

**Comment by navv1234** [comment]
Should be able to use custom scale_to_itemlevel values in conjunction with timewalk now.
