### ISSUE TITLE
Blood DK dps is being reported much lower in simulation than in game.

### ISSUE THREAD

**Issue by Auteyus** [simulationcraft/simc#3773]
Been testing with profiles of others and using their warcraftlogs to compare.  Seems in-game is consistently higher by a fair bit.

Something like, if in-game is usually around 390k dps, simulation is reporting 280k dps.

**Comment by Auteyus** [comment]
My guess is blood boil is too low in the action priority list.  But, I'll leave it to you guys.

**Comment by seanpeters86** [comment]
Sim for blood DK is very much in progress and not even close to being done yet. Most of the talents are not implemented yet, APL still needs works, no legendaries are implemented, and some artifact abilities are inaccurate as well

**Comment by Auteyus** [comment]
thank you for the update!  I'm excited to see the progress so far!
