### ISSUE TITLE
Tempered Egg of Serpentix No longer Simming

### ISSUE THREAD

**Issue by Glutooth** [simulationcraft/simc#3778]
This trinket seems to no longer sim at all. Simulation craft just treats it as an Agility statstick and ignores the secondary effect.

#### Simulationcraft Version
720-03

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
shaman="Obsydion"
level=110
race=tauren
region=us
server=area_52
role=
professions=engineering=674/
talents=2323112
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:4:906:4:907:4:908:4:909:4:910:4:911:4:912:4:913:4:930:1:1351:1:1388:1:1593:4:1594:1:1595:1:1596:1:1687:1

head=,id=138343,bonus_id=3516/1492/3336
neck=,id=140894,enchant_id=5439,bonus_id=3445/1507/3336
shoulder=,id=140917,bonus_id=3519/1522/3337
back=,id=138372,enchant_id=5312,bonus_id=3518/1502/1813
chest=,id=138346,bonus_id=3518/1502/3528
shirt=,id=2579
wrist=,id=137084,bonus_id=3455/1811
hands=,id=137519,bonus_id=3418/1808/1557/3337,gem_id=130222
waist=,id=144406,bonus_id=3445/1502/3336
legs=,id=138345,bonus_id=3516/1492/3336
feet=,id=140867,bonus_id=3518/1507/3336
finger1=,id=137050,enchant_id=5429,bonus_id=1811/3455,gem_id=130222
finger2=,id=140896,enchant_id=5429,bonus_id=3518/1522/3337
trinket1=,id=137373,bonus_id=3415/1537/3336
trinket2=,id=139329,bonus_id=1806/1502
main_hand=,id=128819,bonus_id=745,relic_id=3516:1497:3336/3445:1502:3336/1806:1502,gem_id=140836/140815/139264/0
off_hand=,id=128873,relic_id=0/0,gem_id=0/0/0/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

-Equip Tempered Egg of Serpentix (either slot).
-Simulate Character wearing Tempered Egg of Serpentix

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Should be fixed with https://github.com/simulationcraft/simc/commit/807f6a38b9a1febac91ca30f20b345c8fce49d59
