### ISSUE TITLE
Wowhead link doesn't work. Cannot compare items according to your guide.

### ISSUE THREAD

**Issue by smtips** [simulationcraft/simc#3779]
Please include a brief overview of the issue in the title above, as well as completing the following:
So I was following your instructions exactly to do a compare. You say to click the wowhead link. Well first of all you can't click it, you have to right click it and choose one of the linking options. But the wowhead page simply won't load. 

The URL looks something like this that your program generated.
www.wowhead.com/?items&filter=ub=4;gm=3;gb=1;minle=600;ro=1;wt=21:77:96:103:170:215:32;wtv=17.29:16.97:13.89:10.82:13.28:11.58:16.23;

The page just never loads. I've tried this on two characters, have no issue importing them from the armory at all. 

This is following the exact instructions in your guide at https://github.com/simulationcraft/simc/wiki/StartersGuide, in the Results section and the "Using the scale factors to compare items" section. It simply does not work like you say it does. 

This is my very first time trying to use Simcraft. So I'm just not impressed at all that it doesn't "**work as advertised**."

Thanks.

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Thanks for the report. 
Indeed the format of the Wowhead link given is no longer supported. It will be fixed probably after 7.2.5 updated slow down.

**Comment by navv1234** [comment]
Wowhead currently does not have a functional interface for a proper item search we could give the users, so I removed the non-functional link from reports for now. Closing this issue, but if Wowhead gets a functional search interface together (that we can point an url to), we can rewrite the gear ranking url to properly point to that again.
