### ISSUE TITLE
Protections warriors incorrect shield slam damage

### ISSUE THREAD

**Issue by Cosmao** [simulationcraft/simc#3781]
SimC does not seem to account for the 30% extra damage shield slam is supposed to deal when you have shield block up.

#### 720-03 Nightly build from 2017-05-29 03:43 (git build e1f5e09)

Reproduction Steps:

Simply simulate a protection warrior with and without shield block in the APL, the damage dealt by shield slam will not change simply the crit rate from STB which is a seperate trait.

**Comment by adamhl8** [comment]
Fixed in bc05cce
