### ISSUE TITLE
Relic ilvl issues

### ISSUE THREAD

**Issue by edpham** [simulationcraft/simc#3793]
Please include a brief overview of the issue in the title above, as well as completing the following:
The issue I'm encountering is that I can't seem to select the correct ilvl for the relic that I want to sim for. It keeps giving me different ilvls, even though Wowhead says otherwise (I read another ticket about how it's on their end). Is there any way to remedy this?

#### Simulationcraft Version
Using the nightly version for 720-03 (June 2 version)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=25000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### Begin simulateText ###
warlock="Imphamously"
level=110
race=orc
region=us
server=wyrmrest_accord
role=spell
professions=tailoring=604/enchanting=601
talents=3112213
spec=affliction
artifact=39:0:0:0:0:915:3:916:3:917:3:918:3:919:3:920:4:921:4:922:3:923:3:924:1:925:1:926:1:927:1:928:1:929:1:999:1:1353:1:1390:1:1601:4:1602:1:1603:1:1711:1

head=,id=138314,bonus_id=3573/1482/3336
neck=,id=132444,enchant_id=5890,bonus_id=3459/3530,gem_id=130222
shoulder=,id=138323,bonus_id=3514/1472/3528
back=,id=138373,enchant_id=5436,bonus_id=3516/40/1487/3528
chest=,id=138320,bonus_id=3514/1472/3528
shirt=,id=4334
tabard=,id=45582
wrist=,id=140886,bonus_id=3516/1808/1487/1813,gem_id=130222
hands=,id=140888,bonus_id=3443/1472/3336
waist=,id=132457,bonus_id=1811/3530
legs=,id=134218,bonus_id=3411/1532/3528
feet=,id=140914,bonus_id=3515/1808/1477/3528,gem_id=130222
finger1=,id=134487,enchant_id=5429,bonus_id=3416/1808/1557/3337,gem_id=130222
finger2=,id=140897,enchant_id=5429,bonus_id=3515/1487/3336
trinket1=,id=140809,bonus_id=3515/1477/3528
trinket2=,id=141482,bonus_id=3466/1472/3528
main_hand=,id=128942,bonus_id=747,relic_id=1824:1522:3336/3412:1527:3528/1727:1517:3528,gem_id=143694/137302/137377/0

copy="Replaces perdition"
main_hand=,id=128942,bonus_id=747,relic_id=1477:3411/3412:1527:3528/1727:1517:3528,gem_id=141273/137302/137377/0

copy="Replaces shadow incantation"
main_hand=,id=128942,bonus_id=747,relic_id=1824:1522:3336/3412:1527:3528/1477:3411,gem_id=143694/137302/141273/0

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by AlexanderKenny** [comment]
First confirm there actually is an issue with how SimC is parsing the weapon and not just an incorrect wowhead tooltip (read the text print out below the tooltip in the gear section not the tooltip itself) and check if it lines up. If it does there is no issue just ignore the tooltip and move on.

If the text does not line up correctly you could remove relic_id (the bonus ids for each relic) and use relic_ilevel=ilvl1/ilvl2/ilvl3/ilvl4 to set your relic ilvls instead (it goes on the weapon string same as relic_id currently is).
