### ISSUE TITLE
The head set for warlock from nighthold, don´t sim it only ¨error

### ISSUE THREAD

**Issue by wertios** [simulationcraft/simc#3794]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps: SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'head' with value ',id=138314,bonus_id=3516/1487/3528'

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by vituscze** [comment]
This error doesn't tell us much. You'll need to include the profile that gave you the error.
