### ISSUE TITLE
Cannot set iterations on Ryzen CPU

### ISSUE THREAD

**Issue by LeifEriccson** [simulationcraft/simc#3796]
Please include a brief overview of the issue in the title above, as well as completing the following:

Version 720.2  720.3 are the ones i've tested it on.

When I installed Simcraft or used the zip version on my main rig (i7 6700k) everything works fine, but on my 1500x computer when I install, use the zip, or even directly copy from my main pc, the "Iterations," "Tank Dummy," and "TMI Standard Boss," are greyed out and locked at 10,000, none, and none respectively.

**Comment by AlexanderKenny** [comment]
Hard to say for sure with no debug information but if iterations are greyed out I suspect you have target error enabled. It will run however many iterations are needed to hit that error amount in that case.

**Comment by lgkern** [comment]
Make sure Target Error is set to N/A, otherwise it uses the error to get the iteration amount.

**Comment by LeifEriccson** [comment]
It was the target error set to N/A. I'm not sure why it wasn't defaulting to that after install like it is on my other pc. Thanks for the help.
