### ISSUE TITLE
[Death Knight] Cold Heart Legendary not implemented

### ISSUE THREAD

**Issue by Melekus** [simulationcraft/simc#3797]
The new legendary chest for Unholy and Frost Death Knights isn't yet implemented in simc.

Item : http://ptr.wowhead.com/item=151796/cold-heart

I found various spell IDs that correspond to the item : 
http://ptr.wowhead.com/spell=235592/chilled-heart
http://ptr.wowhead.com/spell=235599/cold-heart
http://ptr.wowhead.com/spell=248397/cold-heart
http://ptr.wowhead.com/spell=248406/cold-heart

I'm working on it myself but I don't think I know enough about C++ and simc code to implement it correctly.

While doing that I also noticed that Chains of Ice applies Frost Fever even though it doesn't ingame.

What I started doing can be found here : https://github.com/Melekus/simc/commit/8a4ce3c7c46006417577684d37509cc438631b45

**Comment by navv1234** [comment]
Doesn't look too bad, I'll implement it today

**Comment by lgkern** [comment]
Done at https://github.com/simulationcraft/simc/commit/c6597105ba4a0a34e18f44c6c786fb7a14b3c67c
