### ISSUE TITLE
error import and export for Ovale spell priority

### ISSUE THREAD

**Issue by nertzhul** [simulationcraft/simc#3798]
I have an error importing from the official blizzard page and with the command Ctrl + i if it imports and manages to simulate but, when I export the file simc_gui in the game I skip error in the addon Ovale spell priority and it does not manage to help in anything

**Comment by nertzhul** [comment]
Also this skips when I import links from the page
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: https://worldofwarcraft.com/en-us/character/ragnaros/nértzhul/simple

# Unable to determine Server and Character information!

**Comment by nertzhul** [comment]
I have an image to see the errors ..
http://prntscr.com/ffyjjr
http://prntscr.com/ffyk4p

**Comment by lgkern** [comment]
That's an error on the script generated by the Ovale addon, so you're better off asking for a fix on their project page: https://wow.curseforge.com/projects/ovale
