### ISSUE TITLE
[Retribution] Simming Specter of Betrayal crashes sim

### ISSUE THREAD

**Issue by Hyperion244** [simulationcraft/simc#3799]
I'm running the latest Nightly build (aa02dfc) and when I attempted to simulate the Specter of Betrayal trinket in the ret paladin APL, instead of simming, it said "Canceled!", but wouldn't let me do anything else, and was clearly still using my CPU for something.  Technically the program didn't "crash", but to do anything else and stop the leak, I had to restart the program.  This was only when I put in the line:

`actions.cooldowns=use_item,slot=trinket1` 
or 
`actions.cooldowns=use_item,name=specter_of_betrayal`

without actually adding those lines (to use the trinket), the sim runs fine.

**Comment by navv1234** [comment]
Very likely because you are simulating with live data (no ptr selected). Never the less, I fixed it to not crash now, it'll simply not be able to use the item.
