### ISSUE TITLE
Concordance of the Legionfall inaccurate buff value

### ISSUE THREAD

**Issue by Drakkmur** [simulationcraft/simc#3801]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
720-02
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Under the buff value for feral version of concordance of the legionfall, it shows 2,000 agility.  The value should be 4,000.

**Comment by vituscze** [comment]
The Concordance hotfix should be in the nightly builds. If the tooltip is wrong, then that's an issue on wowdb's end.
