### ISSUE TITLE
Healing specs not supported

### ISSUE THREAD

**Issue by magocchi** [simulationcraft/simc#3804]
Version 720-02

Was gonna add a healer to my TMI simulation since I'm dropping below 0% and I'm a pally (% hp heal), but whichever one I pick I get a "spec not supported" error. I didn't test all the healing specs but holy pally is not supported and holy priest doesn't even get simmed as healer (even tho it says role=heal). My friend also tried shaman and monk which didn't work either.
Was trying to do something like this: https://github.com/simulationcraft/simc/wiki/SimcForTanks (see healers)

**Comment by N1gh7h4wk** [comment]
You can add heals as raid events.
[https://github.com/simulationcraft/simc/wiki/RaidEvents#incoming-heals](url)
Healers are, as the error says, currently not supported by simc

**Comment by magocchi** [comment]
Oh that's a great idea, thanks N1gh7h4wk :D
