### ISSUE TITLE
doesn't include artifact weapon.

### ISSUE THREAD

**Issue by blixen1994** [simulationcraft/simc#3806]
I have downloaded the new 7.2.0 simc and ran it deleted it ran it for my ret pally and it never takes in my ashbringer or anyone of my legendaries or relics. other people says it works for them but it won't for me and i deleted the simc and re-downloaded it still doesn't work.

**Comment by daaelight** [comment]
I have had the same issue for the last 2 builds, I have SIMC 1.7.2 at the moment.  It started for me after 7.2.0 went live.  From what i can find it doesn't affect everyone.  It has been a couple months now and a fix would be greatly appreciated.

My LUA error:

Interface\AddOns\Simulationcraft\core.lua:148: attempt to compare number with nil

Stack: [C]: ?
Interface\AddOns\Simulationcraft\core.lua:148: in function `GetArtifactString'
Interface\AddOns\Simulationcraft\core.lua:339: in function `?'
...ns\ElvUI\Libraries\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4397: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4065: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4101: in function <Interface\FrameXML\ChatFrame.lua:4097>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by navv1234** [comment]
Line 148 in 1.7.2 does not have a comparison that could produce that error. Are you sure you are running the latest version?

**Comment by daaelight** [comment]
So that error was returned from 1.7.2 and I see that 1.7.3 was just released and it returns the same error: 
Interface\AddOns\Simulationcraft\core.lua:148: attempt to compare number with nil

I am really not very familiar with coding/programming, yet I do see the following in the core.lua file.

function Simulationcraft:GetArtifactString()
  local ArtifactFrame = _G.ArtifactFrame

  if not HasArtifactEquipped() then
    return nil
  end

I have no idea why I am adding this but it seems its related to this somehow but I really don't have a clue how.  I assume you're telling me it's not line 148.

Anyway, that last post was definitely 1.7.2 and it returns me the same error in 1.7.3.

The rest of the error dialogue is:

Stack: [C]: ?
Interface\AddOns\Simulationcraft\core.lua:148: in function `GetArtifactString'
Interface\AddOns\Simulationcraft\core.lua:339: in function `?'
...ns\ElvUI\Libraries\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4397: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4065: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4101: in function <Interface\FrameXML\ChatFrame.lua:4097>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by daaelight** [comment]
Just in case it makes a difference here is the error i receive when no addons are enabled _except_ for SIMC:

Stack: [C]: ?
Interface\AddOns\Simulationcraft\core.lua:148: in function `GetArtifactString'
Interface\AddOns\Simulationcraft\core.lua:339: in function `?'
...ns\ElvUI\Libraries\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4397: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4065: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4101: in function <Interface\FrameXML\ChatFrame.lua:4097>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Enable = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 defaultModuleLibraries = <table> {
 }
 upgradeTable = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface\AddOns\Simulationcraft\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetArtifactString = <function> defined @Interface\AddOns\Simulationcraft\core.lua:122
 Printf = <function> defined @Interface\AddOns\Simulationcraft\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 GetName = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GetItemStrings = <function> defined @Interface\AddOns\Simulationcraft\core.lua:158
 name = "Simulationcraft"
 IsEnabled = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ProfNames = <table> {
 }
 slotNames = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 RegisterMessage = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 RegionString = <table> {
 }
 Print = <function> defined @Interface\AddOns\Simulationcraft\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 baseName = "Simulationcraft"
 PrintSimcProfile = <function> defined @Interface\AddOns\Simulationcraft\core.lua:275
 OnDisable = <function> defined @Interface\AddOns\Simulationcraft\core.lua:44
 OnEnable = <function> defined @Interface\AddOns\Simulationcraft\core.lua:40
 IsModule = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:499
 OnInitialize = <function> defined @Interface\AddOns\Simulationcraft\core.lua:36
 SetDefaultModuleState = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:418
 UnregisterAllMessages = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 UnregisterAllEvents = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 SetEnabledState = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 SendMessage = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 enabledState = true
 UnregisterMessage = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterEvent = <function> defined @Interface\AddOns\Simulationcraft\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 SpecNames = <table> {
 }
 Disable = <function> defined @Interface\AddOns\Simulationcraft\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 GetArgs = <function> defined @Interface\AddOns\Simulationcraft\libs\AceCo

**Comment by daaelight** [comment]
So... any thoughts?  Would really like to use this add-on again.  Also, is there a manual way to export the relevant info?

**Comment by navv1234** [comment]
If 1.7.4 errors still then no, not really. 

You can always use armory import if the addon does not work.

**Comment by daaelight** [comment]
So I figured out my problem, and it's a bit embarrassing, but in case it helps someone else I will post it.

There was a second Interface folder from a previous install which I didn't realize was there.  All new add-on files that I had to manually install were added there and not affecting the game.

Hopefully this might help anyone else with the same problem.

Thanks
