### ISSUE TITLE
[Balance] Radiant Moonlight not implemented

### ISSUE THREAD

**Issue by Gebuz** [simulationcraft/simc#3814]
The balance druid legendary: http://ptr.wowhead.com/item=151800/radiant-moonlight is not currently implemented. I would be very happy if someone could implement it soon please <3.

How it works: First Full Moon cast does not change the spell back to New Moon, and returns a charge on cast. The total number of Half and New Moon casts should remain unchanged, but we should end up twice the usual amount of Full Moon casts.

**Comment by aethys256** [comment]
Cf: https://github.com/simulationcraft/simc/pull/3817
