### ISSUE TITLE
TMI is 0.000k

### ISSUE THREAD

**Issue by FireCulex** [simulationcraft/simc#3825]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
725-01

#### Reproduction Steps:
Paladin Protection
if level=96 or anything below 110 TMI will equal 0.000k
change level=110 and TMI is computed while dps,dtps,hps etc. are way off
I dont have legion.

**Comment by navv1234** [comment]
TMI is not supported on actors below current maximum player level.
