### ISSUE TITLE
Missing Arcane Mage in the Legion T20M Raid Results

### ISSUE THREAD

**Issue by dsteinyb** [simulationcraft/simc#3827]
I was looking at the Raid Results on the main page, specifically the one labeled "Legion T20M 940 ilevel Patchwerk-style + Legendarys." As I was looking through I noticed that every single DPS spec has been included in the results, other than Arcane Mage. Is this just an oversight, or has the spec intentionally been left out of the results?

**Comment by N1gh7h4wk** [comment]
I can't see such a Results page, but Arcane Mage APL has been added like yesterday so its likely that some profiles are missing.

**Comment by N1gh7h4wk** [comment]
Okay got my browser to clear the cache, Arcane Profile has been added so it should be in, once that report is regenerated.

**Comment by dsteinyb** [comment]
Ah, thank you very much. This is the page I was referring to: https://simulationcraft.org/reports/Raid_T20M.html
