### ISSUE TITLE
Relic information importing incorrectly

### ISSUE THREAD

**Issue by justinhixson** [simulationcraft/simc#3836]
EDIT: After looking into it a little bit, it appears the real problem is with wowdb, because the higher ilvl versions of these relics son't appear to exist there: 

http://www.wowdb.com/items/151522-thundering-impact

Please include a brief overview of the issue in the title above, as well as completing the following:

Values about my weapon appear to be completely incorrect.  I have attempted importing them using both the built in character importer and using the simulationcraft addon

This is what SimC is saying my weapon is like:

http://imgur.com/BBJQJnS

Here is what it looks like in game:

http://imgur.com/asJneHT

http://imgur.com/kkICcNe

http://imgur.com/QZMdAdP

http://imgur.com/xA0Wk0x

Am I doing something wrong?

#### Simulationcraft Version

720-02

#### simc_gui.simc file or contents

https://pastebin.com/SjBVnZcx

#### Reproduction Steps:

Import a character and compare the imported relics to the ones in-game.  I imagine that the bug is that it isn't importing the propper bonus id, so your relics probably need to have a bonus_id attached to them in order to notice this issue (warforged, heroic, mythic, something like that)

**Comment by N1gh7h4wk** [comment]
Is it wrong in the 7.25 version from simc?

**Comment by justinhixson** [comment]
Good call, it is working correctly on the nightly build.  Closing.
