### ISSUE TITLE
Vanish bug 7.2.5

### ISSUE THREAD

**Issue by che0522** [simulationcraft/simc#3841]
http://www.mmo-champion.com/threads/2240331-vanish-bug-7-2-5

For publicity so blizz might fix. Hate being played by the game. I just want to use vanish with vanish not 3 vanish macros. Hope pushing this out would force blizz to fix it.

Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by aethys256** [comment]
Duplicate of https://github.com/Ravenholdt-TC/Rogue/issues/4 (Our bug tracker)
Not implemented in SimC yet considering I was pretty sure they would fix it. Considering that's not the case I might consider adding it.
