### ISSUE TITLE
Item Link does not pick up right stats

### ISSUE THREAD

**Issue by Salthegrey** [simulationcraft/simc#3842]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Salthegrey** [comment]
shoulders=ferocious_gladiators_satin_mantle,id=145528,bonus_id=3567/1693/1808/1547/3337,gems=200int

Mousing over the item shows the correct item with the correct stats, however Simulationcraft picks up a ilevel=810 version of this ilevel=915 item.

**Comment by navv1234** [comment]
Seems to be working fine (simc says 915, wowdb tooltip says 915). What version of simc ar you using?

**Comment by Salthegrey** [comment]
Thanks for your note.  I just downloaded yesterday's build and indeed the problem is fixed.
Attached is a screenshot of the old error from the old (April) build.
Thank you...I love the program!
Regards,
David Parsons


![simcraft0621](https://user-images.githubusercontent.com/29603095/27401062-35e2c12e-5690-11e7-803e-9aaeb2c983de.jpg)
