### ISSUE TITLE
simcraft undervaluing new legendary mage ring

### ISSUE THREAD

**Issue by alpacapacino** [simulationcraft/simc#3845]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 725 1

The legendary ring soul of the archmage, for at least frost, is being undervalued in simcraft. If you go under talents it only accounts for the talent you selected. for example i have splitting ice so it's only splitting ice. not both frozen touch and splitting ice.

When i have run mythic +, ToS this week with the ring i see a large difference if i were to wear  my blizzard belt which is not stronger the ring.

**Comment by vituscze** [comment]
It just doesn't show up in the report, but the ring is implemented correctly.

Also, the effect is fairly weak (at least for Frost).
