### ISSUE TITLE
Simcraft- Item "Parsel's Tongue" is not working

### ISSUE THREAD

**Issue by Stinkbombe** [simulationcraft/simc#3850]
Hi, so my problem is i cant get the Item "Parsel's Tongue" on ilvl 970, doesnt matter what i do its always on 910 in Simcraft

**Comment by Hinalover** [comment]
there is two ways you can try adjusting for 970

chest=parsels_tongue,id=151805,ilevel=970
or
chest=parsels_tongue,id=151805,bonus_id=3570

if neither of theses work, let us know.

**Comment by vituscze** [comment]
Closing this for now.
