### ISSUE TITLE
Nightelf SimDPS wrong (Racial stats)

### ISSUE THREAD

**Issue by Kira999999** [simulationcraft/simc#3854]
I observered that the SimDPS of Nightelves isnt calculated in an appropriate way.
The Race bonus of Nightelves gives 1% crit at daytime and 1% haste at Nighttime. Nighttime starts at 6.30pm servertime until sunrise.
As 99%+ of all Raidguilds raid during that period, I strongly suggest to change SimDPS engine to always calculate with 1% haste as this reflects actual reality in a raiding setup.
Gnomes have perm 1% haste as racial, so Nightelves should sim just like them in my opinion.

#### Simulationcraft Version

Every

#### Reproduction Steps:

-----

**Comment by vituscze** [comment]
It's usually always "daylight" in raid instances. Both ToS and NH work this way, so the current behavior is fine.

**Comment by Kira999999** [comment]
Do you mind telling me where you got that info?
To my knowledge that racial is only determinded via server time.

**Comment by vituscze** [comment]
Check a5997bdb7014e8f6c86f4f42fa6c488ed6d9b90c.

I just confirmed that zoning into ToS and NH still changes the buff from 1% haste to 1% crit during night hours.

**Comment by Kira999999** [comment]
Thank you for the info! Then everything is working correct
