### ISSUE TITLE
Simcraft win64 will not install.

### ISSUE THREAD

**Issue by Arn2148** [simulationcraft/simc#3856]
I just tried to install the latest veriosn of simcraft win64 with the .exe file. and even though the .exe downloaded correctly every time I click on the .exe to install simcraft win64 it does absolutely nothing at all...IE: it will not allow me to even install Simcraft win64 from the .exe installer.

Now I also tried to just downlaod the Zip/Rar version and use the Simcraft.exe via the Zip/rar file...and it still does nothing at all. 

So even though I have win 10 64bit and the 64 version of warcraft the simcraft win 64 version(s) do not work at all for me...they will not even install.

I'm just wondering if I need to use the Simcraft version for win64 or will the win32 version work...and If it's best to use the win64 version of simcraft then maybe someone can help me with the installation issue.

this is the only .exe I have this issue with no other .exe files give me any problems with installation. and as stated the win32 version of simcraft seems to install without any issue.

(I am using windows 10 64bit OS) if that helps at all.

again thank you fro your time.

TTFN,
   Arn2148

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
