### ISSUE TITLE
warrior sim doesn't want to use legendary trinket

### ISSUE THREAD

**Issue by mqqtheone** [simulationcraft/simc#3858]
sim version:
SimulationCraft 725-01 for World of Warcraft 7.2.5 Live (wow build level 24287, git build b5fec2b)
report url: https://www.raidbots.com/reports/Byxei8RmW/index.html
problem: i have two usable trinkets, kiljaedens burning wish (legendary trinket) and umbral moonglaives (trinket from ToS), i can use both, since legendary trinket doesn't affected by another trinkets, but sim doesn't want to.
there a line in Action Priority List: use_item,name=kiljaedens_burning_wish,if=!equipped.umbral_moonglaives&buff.battle_cry.up&buff.enrage.up
so legendary trinket doesn't used at all during simulation.

and there gif showing that i can use both in Battle Cry
https://gfycat.com/ShyComplicatedGalapagosdove

**Comment by navv1234** [comment]
The APL seems to work properly now. Closing.

**Comment by mqqtheone** [comment]
https://www.raidbots.com/reports/gRk61pjVwGthUSHN4SWENk/index.html
default APL still same, won't use KJBW (wow build level 24461, git build cd62916)
