### ISSUE TITLE
Simulationcraft gear ilvl is wrong

### ISSUE THREAD

**Issue by blizzard105** [simulationcraft/simc#3859]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by blizzard105** [comment]
Loaded up all my highest ilvl gear to my character. So the current ilvl is 908, but when I got sim my character it says the ilvl is only 903.  checked it 3 times and still showing incorrect ilvl.

**Comment by lgkern** [comment]
can you give us the contents of your simc_gui.simc as explained above?

**Comment by blizzard105** [comment]
I figured it out. Thanks

**Comment by AlexanderKenny** [comment]
Dollars to donuts out of date version and some of the gear pieces are not in game/sim on your version. Make sure you are on a 725 nightly build. If you are then post the diagnostic materials the opener asks for.
