### ISSUE TITLE
Balance APL wrong lines

### ISSUE THREAD

**Issue by Hujain** [simulationcraft/simc#3861]
This lines

actions+=/incarnation,if=astral_power>=40
actions+=/celestial_alignment,if=astral_power>=40

U can sim, it's better to use Incarn/celestial on CD.

**Comment by Guy18** [comment]
725-02 Balance typo:
actions+=/call_action_list,name=fury_of_elune,if=talent.fury_of_elune.enabled&cooldown.fury_of_elue.remains<target.time_to_die

elue. No one simming uses FoE anyway so it's cool
