### ISSUE TITLE
Terror From Below (Tos trinket)

### ISSUE THREAD

**Issue by 1SEBI1** [simulationcraft/simc#3865]
Please include a brief overview of the issue in the title above, as well as completing the following:
After the simulation, when looking at the results there are no procs for the trinket (Terror From Below), no damage is present on the damage meter, when checking on the equiped items, the trinket is showed in there but there are no procs or damage related to the trinket.

#### Simulationcraft Version
7.20 - 02

#### simc_gui.simc file or contents

hunter="Select"
level=110
race=human
region=eu
server=sylvanas
role=attack
professions=alchemy=1/enchanting=57
talents=3111133
spec=beast_mastery
artifact=56:0:0:0:0:868:4:869:4:870:4:871:3:872:4:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1636:1

head=,id=134473,bonus_id=3418/1562/3337
neck=,id=134492,bonus_id=3416/1537/3528
shoulder=,id=139121,bonus_id=3418/1557/3336
back=,id=138368,bonus_id=3520/1467/3336
chest=,id=137354,bonus_id=3418/1808/43/1557/3337,gem_id=130219
wrist=,id=137305,bonus_id=3418/1542/3528
hands=,id=137348,bonus_id=3414/1532/3528
waist=,id=137456,bonus_id=3573/1537/3336
legs=,id=138344,bonus_id=3520/1457/3528
feet=,id=137227,bonus_id=3459/3570
finger1=,id=151641,enchant_id=5427,bonus_id=3459/3570,gem_id=130247
finger2=,id=134531,enchant_id=5427,bonus_id=3418/1808/1542/3528,gem_id=130219
trinket1=,id=140796,bonus_id=3520/1457/3528
trinket2=,id=147016,bonus_id=3564/1467/3528
main_hand=,id=128861,bonus_id=726,relic_id=3564:1467:3528/3418:1542:3528/3417:1552:3337,gem_id=147112/133768/137371/0

### Gear from Bags
#
# Stormsky Greatcloak (895)
# back=,id=134202,bonus_id=1824/1557/3337
#
# Drape of Shame (905)
# back=,id=142170,bonus_id=3418/1522/3337
#
# Wildstalker Gauntlets (885)
# hands=,id=147141,bonus_id=3564/43/1467/3528
#
# Leggings of Biting Links (880)
# legs=,id=137518,bonus_id=3415/40/1532/3528
#
# Arch-Druid's Tainted Seal (890)
# finger1=,id=134487,bonus_id=3418/1542/3528
#
# Seal of the Nazjatar Empire (905)
# finger1=,id=134525,bonus_id=3418/1557/3337
#
# Hunger of the Pack (880)
# trinket1=,id=136975,bonus_id=3415/1532/3528
#
# Horn of Valor (885)
# trinket1=,id=133642,bonus_id=3416/1537/3528
#
# Rocksunder Lucky Statue (860)
# trinket1=,id=134159,bonus_id=3394/605/1522/3528
#

# Default consumables
potion=prolonged_power
flask=seventh_demon
food=lavish_suramar_feast

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion

# Executed every time the actor is available.
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/berserking
actions+=/blood_fury
actions+=/volley,toggle=on
actions+=/potion,if=buff.bestial_wrath.remains|!cooldown.beastial_wrath.remains
actions+=/a_murder_of_crows
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/dire_beast,if=cooldown.bestial_wrath.remains>3
actions+=/dire_frenzy,if=(cooldown.bestial_wrath.remains>6&(!equipped.the_mantle_of_command|pet.cat.buff.dire_frenzy.remains<=gcd.max*1.2))|(charges>=2&focus.deficit>=25+talent.dire_stable.enabled*12)|target.time_to_die<9
actions+=/aspect_of_the_wild,if=buff.bestial_wrath.up|target.time_to_die<12
actions+=/barrage,if=spell_targets.barrage>1
actions+=/titans_thunder,if=talent.dire_frenzy.enabled|cooldown.dire_beast.remains>=3|(buff.bestial_wrath.up&pet.dire_beast.active)
actions+=/bestial_wrath
actions+=/multishot,if=spell_targets>4&(pet.cat.buff.beast_cleave.remains<gcd.max|pet.cat.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multishot,if=spell_targets>1&(pet.cat.buff.beast_cleave.remains<gcd.max*2|pet.cat.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=(cooldown.kill_command.remains>focus.time_to_max&cooldown.bestial_wrath.remains>focus.time_to_max)|(buff.bestial_wrath.up&focus.regen*cooldown.kill_command.remains>30)|target.time_to_die<cooldown.kill_command.remains

summon_pet=cat

#### Reproduction Steps:

Import from EU, Sylvanas, Select.
1 boss fight.

**Comment by N1gh7h4wk** [comment]
you need to use the 7.25 version of simc, the trinket was not implemented in 7.20
