### ISSUE TITLE
Bloodstained Handkerchief damage incorrect

### ISSUE THREAD

**Issue by Digimortals** [simulationcraft/simc#3866]
http://www.wowhead.com/item=142159/bloodstained-handkerchief&bonus=1826:1442

I have a 930 item level variant of this item. Tooltip states 25,839 damage every 2.8 seconds = 9,228 dps if it never was able to crit. Warcraft logs of me using this item generally end up performing around 1.6% overall dps with a crit rate of over 35%.

When I perform a simulation with the item it calculates as 4,561 dps with a crit rate of ~24% and a total percentage of 0.4% dps. It appears to be grossly undervalued at the moment.

**Comment by Digimortals** [comment]
Also the simulation uses the item multiple times on a single target fight, the debuff does not stack and has an unlimited duration so there is no need to recast. It is also off the GCD.

**Comment by EvanMichaels** [comment]
This if fixed in https://github.com/simulationcraft/simc/commit/cee7efcf6f834883d2a4cc1b3f73ef0b89a959c3
