### ISSUE TITLE
Soul effigy still counted in talents

### ISSUE THREAD

**Issue by Jeza40100** [simulationcraft/simc#3867]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 725-01

Hi there wasn't any crash. It's just that after simulating a build I find that the Talent Soul Effigy is still there for Affliction Warlocks. 

Also does the Netherlord ring count both talents selected ?

**Comment by lgkern** [comment]
Still there where, may I ask?

**Comment by Jeza40100** [comment]
All good thanks. I don't think it takes the legendary ring into account though

**Comment by lgkern** [comment]
Looking at the implementation, Soul of the Netherlord seems to be working properly. It won't show up in the talents selected section, but its effects shoulds show in simulations done with it.
