### ISSUE TITLE
Unable to import Pi on Barthilas win10 64 exe install of 725-01

### ISSUE THREAD

**Issue by drbobs1** [simulationcraft/simc#3868]
Please include a brief overview of the issue in the title above, as well as completing the following:
unable to import Pi on Barthilas
https://worldofwarcraft.com/en-us/character/barthilas/pi
feels like a 2 letter name issue?
Can navigate to it via Import/Battlenet.
clicking on import gives:
==============================
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: https://worldofwarcraft.com/en-us/character/barthilas/pi

# Unable to determine Server and Character information!
=========================================
#### Simulationcraft Version
724-01
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by navv1234** [comment]
Trying to import with the web-page based importer no longer works (ever since Blizzard changed their armory web pages). Use the import widget in the gui.
