### ISSUE TITLE
Crashing on simulation completion 

### ISSUE THREAD

**Issue by ChaoticMaNa** [simulationcraft/simc#3870]
#### Simulationcraft Version
Version 725-01 (nightly build of 1st of July 2017)
However has been a problem with all patch 7.25 builds

[DxDiag.txt](https://github.com/simulationcraft/simc/files/1116963/DxDiag.txt)

#### simc_gui.simc file or contents

https://pastebin.com/iykWWe8J

#### Reproduction Steps:
Run any simulation and wait for it to complete, program crashes to desktop.

**Comment by lgkern** [comment]
I have ran the profile you attached in the latest nightly build and it worked fine. Can you test it again to see if the problem persists on your end?

**Comment by ChaoticMaNa** [comment]
Issue continues to happen regardless of build and i cannot figure out the cause

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
