### ISSUE TITLE
Darkmoon Card: Immortality

### ISSUE THREAD

**Issue by Tehclaw** [simulationcraft/simc#3873]
Simulationcraft Version 7.2.0 R2

Darkmoon Card: Immortality is not showing up with any related effect during the sim.  No buff located in the buff section and the tool tip in the gear section correctly shows the card reading iLvl 900 but shows that it gives 0-0 bonus AC 

I tried the version from the /Simc command and also editing the bonus Id from Wowhead;

Trinket1=,id=128711,bonus_id=689/600/679 
and
Trinket1=,id=128711,bonus_id=689/1537

I'm guessing the random armor bonus is not able to be simulated?

**Comment by navv1234** [comment]
I'm seeing all deck buffs in the buffs breakdown with a new Simulationcraft version. Debug output also confirms the bonus armor is applied to the actor.
