### ISSUE TITLE
Unknown option 'artifact' with value

### ISSUE THREAD

**Issue by Michel-Tremblay** [simulationcraft/simc#3874]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
 725-01

#### Reproduction Steps:
Copied my character details from in-game using '/simc'
Opened SimCraft as normal and imported my character details successfully
After clicking simulate in the bottom right corner the error occured
Happening every time i attempt to sim

####Error details 
This was copied from the log window after the error occured

SimulationCraft encountered an error!

Simulation setup error:
Unknown option 'artifact' with value '32:0:0:0:0:1102:1:1103:4:1104:4:1105:4:1106:4:1107:4:1108:4:1109:4:1110:4:1111:4:1112:1:1113:1:1114:1:1115:1:1116:1:1117:1:1352:1:1389:1:1597:4:1598:1:1599:1:1693:1'

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'artifact' with value '32:0:0:0:0:1102:1:1103:4:1104:4:1105:4:1106:4:1107:4:1108:4:1109:4:1110:4:1111:4:1112:1:1113:1:1114:1:1115:1:1116:1:1117:1:1352:1:1389:1:1597:4:1598:1:1599:1:1693:1'

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
shaman="Selleal"
level=110
race=pandaren
region=us
server=korgath
role=heal
professions=alchemy=795/herbalism=800
talents=2212123
spec=restoration
artifact=32:0:0:0:0:1102:1:1103:4:1104:4:1105:4:1106:4:1107:4:1108:4:1109:4:1110:4:1111:4:1112:1:1113:1:1114:1:1115:1:1116:1:1117:1:1352:1:1389:1:1597:4:1598:1:1599:1:1693:1

head=,id=143732,bonus_id=1811/3530
neck=,id=134491,enchant_id=5437,bonus_id=3413/1527/3528
shoulder=,id=133625,bonus_id=3418/1808/1542/3528,gem_id=130248
back=,id=134408,enchant_id=5436,bonus_id=3416/1808/1537/3528,gem_id=130219
chest=,id=134214,bonus_id=3413/1537/3528
wrist=,id=137325,bonus_id=3414/1532/3528
hands=,id=137348,bonus_id=3415/1537/3336
waist=,id=134207,bonus_id=1824/1532/3337
legs=,id=132466,bonus_id=1811/3570
feet=,id=147045,bonus_id=3561/1482/3528
finger1=,id=140897,enchant_id=5427,bonus_id=3515/1482/3336
finger2=,id=133637,enchant_id=5427,bonus_id=3410/1542/3337
trinket1=,id=147003,bonus_id=3561/1482/3528
trinket2=,id=147004,bonus_id=3561/1808/1482/3528,gem_id=130219
main_hand=,id=128911,bonus_id=746,relic_id=3414:1502:3336/3516:1487:3528/3418:1557:3337,gem_id=142309/140833/137327/0
off_hand=,id=128934,relic_id=0/0,gem_id=0/0/0/0

### Gear from Bags
#
# Cloak of Shackled Elements (890)
# back=,id=138372,enchant_id=5435,bonus_id=3516/1487/3528
#
# Gauntlets of Shackled Elements (875)
# hands=,id=138341,enchant_id=5444,bonus_id=3520/1472/3337
#
# Fishing Pole (1)
# main_hand=,id=6256
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment]
Restoration weapon is artifact ID 42 not 32 (the first value in the artifact string). Healers are not really supported by SimC though regardless once you get imported so doubt you get much of value out of it.

**Comment by navv1234** [comment]
Restoration shamans are not supported currently in simulationcraft.
