### ISSUE TITLE
Unclear calculation of two paladins

### ISSUE THREAD

**Issue by WitcherHammer** [simulationcraft/simc#3879]
Simulationcraft Version: 720-02
Here is a profiles of two paladins. They are similar in all things exept gear and respectively stats. Paladin "Serberen" have better stats and gear but his DPS is lower.... Is it a wrong calculation?

paladin="Serberen"
origin="https://eu.api.battle.net/wow/character/darksorrow/Serberen/advanced"
thumbnail="http://eu.battle.net/static-render/eu/darksorrow/8/101064968-avatar.jpg"
level=110
race=human
role=attack
position=back
professions=engineering=784/alchemy=800
talents=http://us.battle.net/wow/en/tool/talent-calculator#bb!0101101
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:5:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:8:1647:1
spec=retribution

head=cruel_gladiators_scaled_helm,ilevel=915,stats=640armor_2496str_3744sta_874crit_874mastery,gems=100haste
neck=radiant_string_of_scorpid_eyes,ilevel=920,stats=2206sta_1041crit_2271haste,gems=150crit
shoulders=gravedredged_pauldrons,ilevel=915,stats=591armor_1872str_2808sta_796crit_515vers
back=radiant_lightbringer_cape,ilevel=940,stats=179armor_1772str_2658sta_653haste_423vers,gems=200str,enchant=200str
chest=crackling_overcharge_chestguard,ilevel=930,stats=815armor_2870str_4305sta_1122crit_726vers
wrists=cruel_gladiators_scaled_wristplates,ilevel=925,stats=352armor_1541str_2311sta_510haste_510vers
hands=cruel_gladiators_scaled_gauntlets,ilevel=915,stats=493armor_1872str_2808sta_562haste_749vers
waist=chain_of_thrayn,ilevel=970,stats=501armor_3124str_4687sta_1035haste_575crit
legs=cruel_gladiators_scaled_legguards,ilevel=925,stats=705armor_2739str_4109sta_778crit_1037vers
feet=ferocious_gladiators_scaled_sabatons,ilevel=910,stats=536armor_1786str_2680sta_735crit_551vers
finger1=liadrins_fury_unleashed,ilevel=970,stats=3515sta_2563crit_1922haste,gems=150crit,enchant=200vers
finger2=cruel_gladiators_ring,ilevel=925,stats=2311sta_1366crit_2049vers,enchant=200vers
trinket1=kiljaedens_burning_wish,ilevel=940,stats=2994str_456crit_456vers_456haste
trinket2=cruel_gladiators_insignia_of_victory,ilevel=925,stats=1296vers_4212str
main_hand=ashbringer,id=120978,bonus_id=737,gem_id=144520/144515/144520/0,relic_id=3568:3164:3337/3568:3174:3337/3568:3174:3337/0

# Gear Summary
# gear_ilvl=931.13
# gear_strength=30887
# gear_stamina=42956
# gear_crit_rating=11589
# gear_haste_rating=7509
# gear_mastery_rating=1818
# gear_versatility_rating=8712
# gear_armor=4812

paladin="Shayisback"
origin="https://eu.api.battle.net/wow/character/aegwynn/Shayisback/advanced"
thumbnail="http://eu.battle.net/static-render/eu/aegwynn/172/143111596-avatar.jpg"
level=110
race=blood_elf
role=attack
position=back
professions=engineering=800
talents=http://us.battle.net/wow/en/tool/talent-calculator#bb!0101101
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:5:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:8:1647:1
spec=retribution

head=cruel_gladiators_scaled_helm,id=144913,bonus_id=3568/1709/1522/3337
neck=cruel_gladiators_pendant,id=144903,bonus_id=3568/1808/1512/3336,gems=150haste,enchant=mark_of_the_hidden_satyr
shoulders=cruel_gladiators_scaled_shoulders,id=144917,bonus_id=3568/1710/1517/3336
back=cruel_gladiators_greatcloak_of_faith,id=144793,bonus_id=3568/1706/1527/3337,enchant=200str
chest=inferno_breastplate,id=134503,bonus_id=3536/1582/3337
shirt=precious_ribbon,id=52019
tabard=tabard_of_the_lightbringer,id=52252
wrists=cruel_gladiators_scaled_wristplates,id=144921,bonus_id=3568/1716/1517/3336
hands=ferocious_gladiators_scaled_gauntlets,id=145506,bonus_id=3567/1695/1552/3337
waist=chain_of_thrayn,id=137086,bonus_id=1811/3570,addon=nitro_boosts
legs=cruel_gladiators_scaled_legguards,id=144915,bonus_id=3568/1681/1527/3337
feet=cruel_gladiators_scaled_sabatons,id=144909,bonus_id=3568/1681/1517/3336
finger1=liadrins_fury_unleashed,id=137048,bonus_id=1811/3570,gems=150haste,enchant=200haste
finger2=ferocious_gladiators_ring,id=145781,bonus_id=3567/1808/1527/3336,gems=150haste,enchant=200haste
trinket1=cruel_gladiators_insignia_of_victory,id=144993,bonus_id=3568/1808/1527/3337,gems=200str
trinket2=cruel_gladiators_accolade_of_victory,id=144990,bonus_id=3568/603/1527/3337
main_hand=ashbringer,id=120978,bonus_id=737,gem_id=144520/144515/144520/0,relic_id=3568:3164:3337/3568:3174:3337/3568:3174:3337/0

# Gear Summary
# gear_ilvl=913.80
# gear_strength=24935
# gear_stamina=39193
# gear_crit_rating=7921
# gear_haste_rating=7947
# gear_mastery_rating=1295
# gear_versatility_rating=9141
# gear_armor=4706

**Comment by AlexanderKenny** [comment]
Hard to say without the report but I would suspect this comes down to you being on a 7.2 client. Grab a 7.2.5 nightly build and see if the issue persists.

**Comment by WitcherHammer** [comment]
I made another test in version 725-01 I took two very similar profiles main difference - stats (in APL I used comand "use_item" for different gear if it was possible) :
Serberen	999'622 DPS
Raid-Buffed	Unbuffed	Gear Amount
Strength	41063	39289	25748 (19503)
Agility	3200	3200	0
Stamina	70044	70044	42148
Intellect	7328	7328	0
Spirit	0	0	0
Health	4202640	4202640	0
Mana	220000	220000	0
Holy Power	5	5	0
Spell Power	41063	39289	0
Crit	37.84%	37.84%	13136
Haste	21.78%	20.76%	7786
Damage / Heal Versatility	15.50%	15.50%	7363
Attack Power	41063	39289	0
Mastery	18.96%	18.96%	1857
Armor	4774	4774	4774
Run Speed	7	0	0

Serberen2  951'739 DPS
Raid-Buffed	Unbuffed	Gear Amount
Strength	44486	42796	30918 (2994)
Agility	3200	3200	0
Stamina	71280	71280	43002
Intellect	7328	7328	0
Spirit	0	0	0
Health	4276800	4276800	0
Mana	220000	220000	0
Holy Power	5	5	0
Spell Power	44486	42796	0
Crit	34.56%	34.56%	11824
Haste	21.45%	20.42%	7659
Damage / Heal Versatility	17.73%	17.73%	8421
Attack Power	44486	42796	0
Mastery	20.71%	20.71%	2323
Armor	4812	4812	4812
Run Speed	7	0	0

BUT Serberen2 must have bigger DPS

**Comment by WitcherHammer** [comment]
Some problems were solved. Especially with identification id and bonus id of items (one time SimCraft showed me that Ashbringer have only 842 ilevel, but in real it have 943).

**Comment by navv1234** [comment]
Serberen is missing item ids on all items but the artifact. This means that things like the two legendary items are currently not doing what they are supposed to be doing. Additionally, the Kiljaeden's Burning Wish is doing nothing.

**Comment by WitcherHammer** [comment]
Yes, but it's not the problem. the Kiljaeden's Burning Wish active ability give only <=1% of damage..... With the 725-01 they have similar damage, but stats of Serberen is better......

**Comment by navv1234** [comment]
Stats are better yes, but Serberen for all intents and purposes does not have the benefits of two legendary item effects, nor the trinket effect.

**Comment by WitcherHammer** [comment]
Few days ago I've changed his trinkets and legendary items with the help of id, they dont give such great difference.  Serberen have +20% of main stat Strength and a lot of crit.... and SimCraft showed that his dmg.....lower.

**Comment by navv1234** [comment]
Simply enabling the legendary effects, and fixing Serberen's non-legendary trinket to a proc results in Serberen doing significantly more dps in the default setup of Simulationcraft.
