### ISSUE TITLE
725-01 "program stopped working" massage

### ISSUE THREAD

**Issue by ziradin** [simulationcraft/simc#3885]
simply when i installed the latest version it never worked , i downloaded the 7.2 one and that works fine , but when i get the latest 7.2.5 one after the installation completes it doesnt launch and stops working.

https://gyazo.com/8dbe727d1adfa15061044667b5aca4cd

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
