### ISSUE TITLE
Brewmaster stagger reschedule crash

### ISSUE THREAD

**Issue by zeehamster** [simulationcraft/simc#3890]
Please include a brief overview of the issue in the title above, as well as completing the following:
whenever I try and sim my brewmaster the app stops working. 
#### Simulationcraft Version
725-01
#### If Simulationcraft is crashing, please include your dxdiag file
[DxDiag.txt](https://github.com/simulationcraft/simc/files/1126381/DxDiag.txt)

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=25000
default_world_lag=0.025
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=0.95
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
monk="xxxxxx"
level=110
race=blood_elf
region=us
server=xxxxx
role=tank
professions=leatherworking=800/inscription=800
talents=2123132
spec=brewmaster
artifact=52:0:0:0:0:1277:1:1278:4:1279:4:1280:4:1281:4:1282:4:1283:4:1284:4:1285:4:1286:4:1287:1:1288:1:1289:1:1290:1:1291:1:1292:1:1293:1:1374:1:1541:4:1542:1:1543:1:1544:3:1642:1

head=,id=128887,bonus_id=689/1706/3408/600/679
neck=,id=130237,enchant_id=5889,bonus_id=1787/689/600/679,gem_id=130220
shoulder=,id=151788,enchant_id=5883,bonus_id=1811/3570
back=,id=138367,enchant_id=5435,bonus_id=3514/1808/1472/3528,gem_id=130221
chest=,id=138325,bonus_id=3514/1497/3337
wrist=,id=134236,bonus_id=3573/1542/3528
hands=,id=147739,bonus_id=3572/1808/1482/3528,gem_id=130221
waist=,id=144486,bonus_id=1727/1547/3337
legs=,id=147741,bonus_id=3572/1487/3336
feet=,id=140860,bonus_id=3443/42/1472/3336
finger1=,id=137044,enchant_id=5430,bonus_id=3529/3459/3570,gem_id=130221
finger2=,id=147766,bonus_id=3572/1482/3528
trinket1=,id=128711,bonus_id=689/601/679
trinket2=,id=140807,bonus_id=3515/1477/3528
main_hand=,id=128938,bonus_id=732,relic_id=3514:1497:3337/1727:1507:3337/3521:1467:3336,gem_id=140839/142193/140817/0

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Hinalover** [comment]
Sorry for the delay but I'll take a look at it this weekend.

**Comment by scamille** [comment]
@navv1234 that looks like a problem for you.

Looks like stagger_self_damage_t dot reschedule is doing something nasty to the dot invariants.

**Comment by navv1234** [comment]
I have no clue of brewmasters, or staggers.

**Comment by scamille** [comment]
Neither do I. Just saying the problem here is a somewhat messed up dot_t object, because of https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_monk.cpp#L5740

Basically there needs to be a different way to implement the "Pauses Stagger damage for 3 sec." functionality here.
By the current implementation this means "Delay next dot tick event by 3 seconds", just in a non-crashing way ;)

Apparently extending both tick and end event of the dot isn't enough.

**Comment by scamille** [comment]
This seems still to be a thing in bfa, so I'll keep it open.
