### ISSUE TITLE
7.2.5 crashing upon completion of sim HELP

### ISSUE THREAD

**Issue by jeckyll88** [simulationcraft/simc#3895]
So 7.2 worked fine, and I downloaded the newest official 64 bit release, and now right before the sim completes, it gives me the "program has stopped working message" and forces a close. I have my dxdiag and msinfo specs attached help much appreciated 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/1131953/DxDiag.txt)
[ms info.txt](https://github.com/simulationcraft/simc/files/1131955/ms.info.txt)

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
