### ISSUE TITLE
Skill attempting to execute function without required spec

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3896]
SimCraft has been outputting the above mentioned issue involving Dancing Rune Weapon saying that it isn't in the required spec (which is Blood Tank Spec for a Death Knight).  In the 7.1.5 version and earlier I never ran into this issue ever happening while using the TMI option for simulating.  It seems this is appearing in this latest version of SimCraft.  In-game the data is being compiled correctly........it is in the program when it is doing the simulations that this has popped up.

#### Simulationcraft Version 7.2.5-02 (using nightly version updates into original folder)

![simcraft](https://user-images.githubusercontent.com/29992091/27981647-1fdad54a-635d-11e7-8919-86a370020990.jpg)

**Comment by kelvinmyles** [comment]
Having the same issue with Blood Dk in 7.2.5-02 and 7.2.5-01 after reinstalling.
