### ISSUE TITLE
Simc not pooling for vanish & Shadow Blades used during mantle period.

### ISSUE THREAD

**Issue by Thernn** [simulationcraft/simc#3898]
Simc isn't pooling before a vanish with my gearset. It also uses shadowblades during the mantle period instead of delaying vanish until it is off cd. This has lead to situations were only a single evis is used while the 100% buff is up.

Myst was able to reproduce it with my gearset.

Current Nightly.

#### Reproduction Steps:

spec=subtlety
level=110
race=night_elf
timeofday=day
role=attack
position=back
professions=enchanting=800/jewelcrafting=800
talents=1113313
artifact=17:0:0:0:0:851:1:852:4:853:4:854:4:855:4:856:4:857:4:858:4:859:4:860:4:861:1:862:1:863:1:864:1:865:1:866:1:1349:1:1386:1:1585:4:1586:1:1587:1:1588:5:1653:1

head=doomblade_cowl,id=138332,bonus_id=3518/1502/3528
neck=zealous_timestone_pendant,id=140894,bonus_id=3445/1507/3336,enchant=600mastery
shoulders=mantle_of_the_master_assassin,id=144236,bonus_id=3529/3459/3570
back=doomblade_shadowwrap,id=138371,bonus_id=3518/1808/1502/3528,gems=200agi,enchant=200agi
chest=doomblade_tunic,id=138326,bonus_id=3518/1517/3337
shirt=precious_ribbon,id=52019
tabard=argent_crusaders_tabard,id=46874
wrists=denial_of_the_halfgiants,id=137100,bonus_id=3459/3570
hands=gloves_of_synchronous_elements,id=140905,bonus_id=3518/1507/3336
waist=high_shadow_councilors_wrap,id=140919,bonus_id=3517/1808/1512/3337,gems=150mastery
legs=doomblade_pants,id=138335,bonus_id=3518/1502/3528
feet=grovetenders_moccasins,id=140861,bonus_id=3518/1808/1502/1813,gems=150mastery
finger1=spellblades_gemmed_signet,id=140895,bonus_id=3516/1512/3337,enchant=200mastery
finger2=woebearers_band,id=133638,bonus_id=3418/1557/3337,enchant=200mastery
trinket1=convergence_of_fates,id=140806,bonus_id=3518/1502/3528
trinket2=nightblooming_frond,id=140802,bonus_id=3516/1497/3336
main_hand=fangs_of_the_devourer,id=128476,bonus_id=743,gem_id=136721/140822/140826/0,relic_id=3536:1552:3337/3518:1512:3336/3517:1492:1813/0
off_hand=fangs_of_the_devourer,id=128479

**Comment by Mystler** [comment]
There was an issue with the pooling line for Vanish in the APL. Fixed it in 9a4ac481f2dcd2a9d687012f4782667261966bf2.
As a side note: We prefer collecting all kinds of rogue-related issues and suggestions via our TC hub. It is easier for us to track if you open APL issues here. https://github.com/Ravenholdt-TC/Rogue/projects/1
