### ISSUE TITLE
Bugs with timewalk simming

### ISSUE THREAD

**Issue by JBA9084** [simulationcraft/simc#3901]
#### Please include a brief overview of the issue in the title above, as well as completing the following:

The timewalk=X command does not work at all unless you include a scale_to_itemlevel command, and if you dont include that command your character level is brought down to 70 but the iLvl of your gear remains the same. Even when you do include a scale itemlevel command, the iLvl you choose is  ignored anyway and the default iLvl associated with the timewalk level is used instead (ex. tw=70 = 95 ilvl). 

Also, concordance of the legionfall buff is not scaling down, Ring of Collapsing Future's active isn't scaling down either either, and stats from socket bonuses are being counted twice upon loading a character template or using gem_id functions for filling in sockets. In addition, the AP buff from Band of the Eternal Champion's proc is giving 0 ap, although tooltip says it should be 80.

#### Simulationcraft Version
725-01

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - 
No crash

#### Reproduction Steps:

1. Type timewalk=(70, 80, anything) and scale_to_itemlevel=(95, 160, anything, I used 141) into a character tab under Simulate
2. Run the simulation
3. Check the Gear section under results, and you will see everything is set to 95 ilvl. I know that the scale itemlevel command works, since it works fine when used without the timewalk command.

To reproduce the broken timewalk command, just do the same as above but do not include a scale itemlevel command. Your character's level will be scaled to 70 but your gear will not, so youll end up with like 160% crit, 140% mastery, etc. 

Thank you for reading.

**Comment by totofeo** [comment]
Hoping this gets some fix, i have so much old gear lying around that i want to sim.

**Comment by Zootor** [comment]
I'm having this problem with 2 items from Black Temple (raid) timewalking.


Simulationcraft Version = 725-01
shoulders=shoulders_of_the_hidden_predator,id=150462,bonus_id=3589 and waist=boneweave_girdle,id=150498,bonus_id=3589/3590

showing >>>
Shoulders of the Hidden Predator
ilevel: 141, stats: { 29 Armor, +28 Sta, +18 Agi/Int, +13 Mastery, +11 Haste }
Boneweave Girdle
ilevel: 141, stats: { 22 Armor, +28 Sta, +18 Agi/Int, +14 Mastery, +11 Haste }

Simulationcraft is simulating the above item(s) as an item level 141 item, when in fact it's item level 900 (timewarped) for Shoulders of the Hidden Predator and item level 915 (timewarped warforged) for Boneweave Girdle.  Just wanted to report.

**Comment by vituscze** [comment]
This is unrelated to the original issue. You need to include `drop_level`, for example:

```
waist=boneweave_girdle,id=150498,bonus_id=3589/3590,drop_level=110
```

**Comment by Zootor** [comment]
@vituscze Thanks, much appreciated.

**Comment by Extort713** [comment]
Tested the newest build from(1/25/2018) and most of these issues are still present, besides the double gems bug that was fixed already. 

"timewalk=X"......................Still does not scale down gear.
"scale_to_itemlevel=X"....Still being overwritten by command above.
Concordance Still isn't scaled down, among a plethora of other buffs/item procs.
Crucible Teir 2 bonuses are not scaled properly. My torment of the weak was showing 27% overall dps, when in play testing it was around 1-3%.

When using the two commands above that scaled level to 70 and ilvl to 95, it gives me around 1000% more dps on average than I find during play testing.
[Timewalking_profile.txt](https://github.com/simulationcraft/simc/files/1669750/Timewalking_profile.txt)

**Comment by navv1234** [comment]
The timewalking auto-downgrade is fixed now. We have no clue how artifact abilities scale with player levels.

**Comment by Extort713** [comment]
Awesome, hopefully ability scaling could be resolved at some point since artifacts should stay around for the foreseeable future and will be highly relevant in time walking.
