### ISSUE TITLE
Vanish linked with Symbols of Death

### ISSUE THREAD

**Issue by Thernn** [simulationcraft/simc#3904]
Linking Vanish use to having the Symbols of death buff could be improved further. Haven't had the chance for more thorough testing with other builds and the default profile but the line below provided a 1.8k dps increase using my gearset on a 450s fight. I'll do some additional testing soon.

My line
actions.cds+=/vanish,if=(variable.dsh_dfa&charges_fractional<=variable.shd_fractional&buff.symbols_of_death.up&!buff.shadow_dance.up&!buff.stealth.up&mantle_duration=0&(dot.nightblade.remains>=cooldown.death_from_above.remains+3|target.time_to_die-dot.nightblade.remains<=6)&cooldown.death_from_above.remains<=1&(time<7|combo_points.deficit>=2))|target.time_to_die<=7

Current implementation
actions.cds+=/vanish,if=energy>=65-talent.shadow_focus.enabled*10&variable.dsh_dfa&(!equipped.mantle_of_the_master_assassin|buff.symbols_of_death.up)&cooldown.shadow_dance.charges_fractional<=variable.shd_fractional&!buff.shadow_dance.up&!buff.stealth.up&mantle_duration=0&(dot.nightblade.remains>=cooldown.death_from_above.remains+3|target.time_to_die-dot.nightblade.remains<=6)&cooldown.death_from_above.remains<=1&(time<10|combo_points.deficit>=2)|target.time_to_die<=7

**Comment by Mystler** [comment]
Vanish condition has changed with the latest APL and should be an increase now.
