### ISSUE TITLE
Player xxxxxx attempting to execute action xxxx_xxxxxx_xxxxx without the required level (xx>xx).

### ISSUE THREAD

**Issue by doutrnz** [simulationcraft/simc#3907]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Reproduction Steps:
This is more of a question as to what this means. A brief background of my character was that I started this character as a level 1 and have been running simulationcraft after a few upgraded armor/trinkets to keep it up to date. I've been getting this since the beginning of the character and haven't payed much attention to it. 

Here is the full list as it appears in the results page as well as the string results. Again, this hasn't prevented me from progressing my character or cause any glitches or crashes. Just wondering what this means. If there is a way to adjust Simulationcraft to work without prompting this notification, that would be great.

Player Dysokimbo attempting to execute action rising_sun_kick_tornado_kick without the required level (39 < 56).
Player Dysokimbo attempting to execute action rising_sun_kick_trinket without the required level (39 < 56).
Player Dysokimbo attempting to execute action rising_sun_kick_trinket without the required level (39 < 56).
Player Dysokimbo attempting to execute action rising_sun_kick_tornado_kick without the required level (39 < 56).
Player Dysokimbo attempting to execute action rising_sun_kick_trinket without the required level (39 < 56).
Player Dysokimbo attempting to execute action rising_sun_kick_trinket without the required level (39 < 56).

( Pawn: v1: "Dysokimbo": Class=Monk, Spec=Windwalker, Agility=5.20, Stamina=0.16, CritRating=1.31, HasteRating=1.35, MasteryRating=0.02, Versatility=1.21 )

**Comment by Zarggg** [comment]
Simcraft is intended to be run on characters at max level (110 as of Legion). If you attempt to sim a character that is not at max level, the results you get cannot be guaranteed to be accurate.

**Comment by scamille** [comment]
Yeah this is just a lack of complete level-aware implementation of the rising_sun_kick code.
Maybe someone @simulationcraft/monk wants to adjust this. It should still work correctly right now, because SimC automatically does not execute the trinket/tornado_kick actions, and thats why you get those warning messages.
