### ISSUE TITLE
Cannot import characters

### ISSUE THREAD

**Issue by Strit** [simulationcraft/simc#3908]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
725-01

#### Reproduction Steps:
Launch SimulationCraft GUI.
Click the Import tap.
Select region, server and type character name.
Hit Import button.

Expected:
Character gets imported and ready to be simmed.

What actually happens:
Import Failed with this:

``` # Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# BCP API: Unable to download player from 'http://eu.battle.net/api/wow/character/server/character?fields=talents,items,professions&locale=en_US', JSON parse error
# If you built this from source, remember to add your own api key.```

**Comment by Zarggg** [comment]
It appears you did not actually enter your character information before attempting to import.

**Comment by Strit** [comment]
I did. I just replaced them with "server" and "character".
They where Silvermoon and Zygophylasis if you really need to know them, but I can't think that my characters is the only ones giving this result. Whic is why I replaced them with generic terms.

**Comment by Strit** [comment]
Extra information:
Running 64-bit Linux
Tried version 720-02, 725-01 and the git version from today.

**Comment by navv1234** [comment]
You need to compile with OPENSSL=1, and you need an apikey to import characters. Wiki has more information.

**Comment by Strit** [comment]
Found out about the apikey. So I need to tell Blizzard that I'm an App developer, before I can be a user of SimulationCraft GUI without being logged into WoW?

**Comment by navv1234** [comment]
To import your character from the World of Warcraft armory, if you compile from the source yourself, yes.
