### ISSUE TITLE
Item level problem when importing (some) hunter gear from Black Temple Timewalking

### ISSUE THREAD

**Issue by Zootor** [simulationcraft/simc#3913]
#### Simulationcraft Version = 725-01

shoulders=shoulders_of_the_hidden_predator,id=150462,bonus_id=3589
and
waist=boneweave_girdle,id=150498,bonus_id=3589/3590

showing >>>

Shoulders of the Hidden Predator
--
ilevel: 141, stats: { 29 Armor, +28 Sta, +18 Agi/Int, +13 Mastery, +11 Haste }

Boneweave Girdle
--
ilevel: 141, stats: { 22 Armor, +28 Sta, +18 Agi/Int, +14 Mastery, +11 Haste }

Simulationcraft is simulating the above item(s) as an item level 141 item, when in fact it's item level 900 (timewarped) for Shoulders of the Hidden Predator
and
item level 915 (timewarped warforged) for Boneweave Girdle.

Just wanted to report.

**Comment by Zootor** [comment]
Reported already.

**Comment by AlexanderKenny** [comment]
These have the correct Id/bonus to correspond to TW versions they just need a drop_level=x to sim correctly (where x is your true player level when they were acquired). The add-on correctly adds this (as do wowhead/raidbots) I suspect that you used an armory import however which does not supply that information in the API so is unavailable to us.

**Comment by Zootor** [comment]
Thanks.  I will use this now: waist=boneweave_girdle,id=150498,bonus_id=3589/3590,drop_level=110
