### ISSUE TITLE
Unable to import 2 character name

### ISSUE THREAD

**Issue by drbobs1** [simulationcraft/simc#3916]
Unable to import Pi on Barthilas win10 64 exe install of 725-01
Thx for your reply to not use the Battle.Net import tab and to Use the import widget in the gui. Unfortunately this does not work either. I am unable to import  character "Pi" on Barthilas, clicking import or enter like with 3 character names does nothing

I would really like to use Simcraft, but it seems it will not load my 2 character name?
I have tried other 2 character names with the same error. 

Am I miss understanding where I should be trying to import from?
Can anyone else import a 2 character name in this way?
Thx

![image](https://user-images.githubusercontent.com/29809250/28390141-f3e53ea6-6d2c-11e7-9d69-64e05014b412.png)

**Comment by navv1234** [comment]
This should be fixed in the next nightly build.
