### ISSUE TITLE
Simc stops respond when i open it

### ISSUE THREAD

**Issue by Paladunno** [simulationcraft/simc#3921]
Hey, when i open simc it just stops responding and my video card AMD says " AMD video driver stopped responding and saved from it" then simc doesn't respond waiting at background. Tried 7.2 version but same problem. I am using laptop, and i set 3d graphics for simc to High Performance but it didn't help. Thanks for help.

#### Dxdiag

[DxDiag.txt](https://github.com/simulationcraft/simc/files/1165421/DxDiag.txt)

**Comment by Paladunno** [comment]
No one knows ?

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
