### ISSUE TITLE
Priority list: code line not understood

### ISSUE THREAD

**Issue by Fosphen** [simulationcraft/simc#3922]
This is in the priority list for enhancement shaman and I don't understand what "strike" relates to:

actions.cds+=/ascendance,if=(cooldown.strike.remains>0)&buff.ascendance.down

Please tell me ! Thanks

**Comment by navv1234** [comment]
"Strike" is the shared cooldown between Windstrike, Stormstrike(, and now removed Primal Strike).

**Comment by Fosphen** [comment]
Thanks buddy !
