### ISSUE TITLE
wrong dps simulation

### ISSUE THREAD

**Issue by Markzaal100** [simulationcraft/simc#3923]
When I sim feet=softstep_boots_of_tracking,id=150528,bonus_id=3589/3590  i get way less dps then when I sim feet=corruptionfused_stompers,id=144490,bonus_id=3418/1557/3337.

As the corruption feets is 915 and with the stats it has it should be more dps output.

**Comment by N1gh7h4wk** [comment]
could you provide more information about your simulation? like the report or the used profile. Are the stats not correctly pulled into simC?

**Comment by Markzaal100** [comment]
The simulation has been done with:
Character: Thundergun
Realm: Frostmane (EU)

The item appears correct in the list, but the stats are not pulled into simC correctly

**Comment by N1gh7h4wk** [comment]
It's a known issue with Timewalking, simc needs to know the droplevel of the item.
feet=softstep_boots_of_tracking,id=150528,bonus_id=3589/3590,drop_level=110 works fine
