### ISSUE TITLE
Fury Warrior War Machine buff 0 uptime on hectic add cleave sims

### ISSUE THREAD

**Issue by goiteralert** [simulationcraft/simc#3928]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Reproduction Steps:

1) Use a fury warrior character with the War Machine (30% haste and 30% movement speed for 15s after killing an enemy, does not require actual killing blow) talent.

2) Sim with hectic add cleave or helter skelter style fight.

3) Notice in report that there is 0 buff uptime for War Machine (which is also the buff name) and that sims will yield noticeably lower dps than using endless rage (single target talent). This was not the case during Nighthold simming earlier this year. 

Adds picked for these sims apparently do not die, is that the issue? 
If so, this needs to be a toggle instead, for situations exactly like this.

**Comment by penguinlust** [comment]
This looks to still be the case. Beastlord shows the same thing. In fact, looking at the code going back for over a year, I don't think it was ever implemented. It doesn't show up in 703-02.

**Comment by penguinlust** [comment]
Looks like there were substantial changes between 720-02 and 725-01 to SpellDataDump/warrior.txt. Looking there.

**Comment by penguinlust** [comment]
Should be closed -- fixed in #4299
