### ISSUE TITLE
Can't interact with anything

### ISSUE THREAD

**Issue by EragonTrible** [simulationcraft/simc#3931]
I'm using the current version atm and whenever i open it i can't interact with anything the GUI seems to be broken completely... i can only minimize it or close it... reinstalling doesn't work.

**Comment by Tevihn** [comment]
Having the exact same issue, not sure what's going on. And I don't think the Developer is very active here. 

Shame

**Comment by Tevihn** [comment]
So I seemed to have found a fix? Of sorts

I'm willing to bet you're trying to run it on a laptop?

What I did is right clicked it, and chose to run it with my integrated graphics processor, and it seems to have done the job.

Can now interact with everything normally, not sure why I have to do this but it works for now.

**Comment by navv1234** [comment]
This is one of those issues that almost certainly is a mix of the framework we use for GUI (qt) and the hardware configuration (gpu, probably), and drivers. It is very hard to impossible for us to fix, and it is surprisingly common especially with AMD GPUs.

The CommonIssues wiki page (https://github.com/simulationcraft/simc/wiki/CommonIssues) item 3 is one thing you could try.

**Comment by EragonTrible** [comment]
I tried Tevihn's method and the bars are just hidden and noninteractable while the item 3 on the common issues didn't do anything... its still the same can't interact between the bars only see the welcome page can't switch to sim or any other bar

**Comment by EragonTrible** [comment]
http://imgur.com/a/vl1zD This is a more detailed description of my problem atm.

**Comment by Strepsiades** [comment]
same here. @EragonTrible

**Comment by Strepsiades** [comment]
but then I solved the problem by tying @Tevihn's way.

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
