### ISSUE TITLE
Soul of the Huntmaster/Soul Rings simulation not functioning.

### ISSUE THREAD

**Issue by Adus11** [simulationcraft/simc#3932]
Current simc version: SimulationCraft 7.2.5, release 1

Ring Soul of the Huntmaster (and likely all other Soul rings) don't seem to be simming correctly. 

hunter="Annika"
level=110
race=blood_elf
region=us
server=chogall
role=attack
professions=alchemy=800/herbalism=800
**talents=2111112**
spec=beast_mastery
artifact=56:0:0:0:0:868:4:869:4:870:4:871:4:872:4:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1520:8:1636:1

head=,id=147142,bonus_id=3562/40/1497/3528
neck=,id=133633,enchant_id=5437,bonus_id=3536/42/1562/3528
shoulder=,id=147144,bonus_id=3561/1482/3528
back=,id=138368,enchant_id=5435,bonus_id=3516/1502/3337
chest=,id=147139,bonus_id=3562/1502/3336
tabard=,id=147205
wrist=,id=147057,bonus_id=3562/42/1497/3528
hands=,id=147141,enchant_id=5444,bonus_id=3562/1497/3528
waist=,id=137080,bonus_id=3529/3459/3570
legs=,id=138344,bonus_id=3516/1502/3337
feet=,id=134298,bonus_id=3536/1592/3337
finger1=,id=147195,enchant_id=5427,bonus_id=3561/1492/3528
finger2=,id=151641,enchant_id=5427,gem_id=130247,bonus_id=1811/3570
trinket1=,id=147017,bonus_id=3562/1507/3336
trinket2=,id=147019,bonus_id=3561/1507/3337
main_hand=,id=128861,gem_id=147114/147079/140817,bonus_id=726,relic_id=3562:1507:3336/3561:1497:3336/3517:1497:3336

Bolded section shows talent distribution. 2111112 are my talents, however #4 does not take into account 2 talents on that row.

Not sure if this was mentioned yet.

**Comment by vituscze** [comment]
The extra talent is just not reported, rings are implemented correctly.
