### ISSUE TITLE
Don't build engine again

### ISSUE THREAD

**Issue by Thaodan** [simulationcraft/simc#3938]
I don't know if a simliar issue exits but usally when building the engine (simc) and the gui (simulationcraft) the engine is build twice. Once for the cli client and 2nd for the gui:
for arch we do this to avoid this:
sed -e 's|SOURCES|OBJECTS|' -e 's|\.cpp|\.o|' -i source_files/QT_engine{,_main}.pri

Maybe it would be better to have something like libsimcraft where simc and simulationcraft is linked to.

**Comment by scamille** [comment]
Would you be ok with a cmake solution?

Not that I have one ready, but I suspect that it could be easy to pull that off with cmake.

**Comment by Thaodan** [comment]
sure why not. I think it would be better to commit to one build system.  KDE is a good example of C++/Qt and cmake.

**Comment by scamille** [comment]
I don't know if SimC will/can ever commit to one build system, there are too many different interests involved ;)
I am personally not that involved anymore, so do not have any interest to force anything onto the other developers. Additionally, most Windows developers will likely only ever use the VS project files, and never anything like qmake/qtcreator or cmake.

I added some improved cmake files in 9287d7584c04fbd7333a4af350ffb524f58b5656 which seems to work in only building engine once. At least its a start... ;)

**Comment by Thaodan** [comment]
Thanks I will look into this later.


I'm just an admin so I don't know about Vs but I think cmake supports Vs solutions generating pretty good.

Usually it's very easy to build a cmake or qmake application but with this it's hard to tell the app where it data lies (system Vs userdata.

Is simc used by raidbots or ask mr robot?

**Comment by navv1234** [comment]
Raidbots.

**Comment by navv1234** [comment]
As for building things twice, simulationcraft.pro (the newer qmake project) should not build the "lib" twice.

**Comment by Thaodan** [comment]
If you build simc first than yes.

**Comment by scamille** [comment]
Closing this as both simulationcraft.pro and new cmake should offer separated engine lib now and with a much simpler setup. If packaging for linux distributioins is once again picked up by someone we can discuss remaining issues in a new ticket.
