### ISSUE TITLE
Disc Priest simc is broken

### ISSUE THREAD

**Issue by Atramedes** [simulationcraft/simc#3947]
It seems that Simc doesn't support some crucial disc procs/Mechanics:

Power of the Dark Side(Artifact)
T20 2set
Cord of Maiev, Priestess of the Moon(Disc legendary)
Lights wrath(when i write the script with this spell in the line, an error occurs.)

**Comment by AlexanderKenny** [comment]
As stated on the main download page healer and tank specs are not currently supported in SimC as they have no developers interested in maintaining them.

**Comment by lgkern** [comment]
You can find more information at https://github.com/simulationcraft/simc/issues/2775
