### ISSUE TITLE
[Survival] Pet damage and Pet flanking strike damage too low in 7.3/PTR simulations

### ISSUE THREAD

**Issue by Vyrtan** [simulationcraft/simc#3961]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

Nightly (725-02)

#### simc_gui.simc file or contents

attached:

[simc_gui.txt](https://github.com/simulationcraft/simc/files/1260147/simc_gui.txt)

#### Reproduction Steps:

- run one live and one ptr simulation (or a simulation with option both), as a survival hunter.

pet dmg and pet flanking strike dmg is roughly 50% lower in ptr simulations then on live, while theres no change in 7.3 thats supporting this behaviour.

**Comment by nuoHep** [comment]
Should be fixed by 1fa582dcd4974dd87c1b3a70796508e39d7fc45c
