### ISSUE TITLE
sizing issue with any version after 7.2.5 1

### ISSUE THREAD

**Issue by traininngamin** [simulationcraft/simc#3968]
whenever i install and run any simcraft version after 7.2.5 version 1 the window is either extremely huge to where i can barely see any results on my main monitor or extremely small where i also can't see results on my 2nd monitor. is there some way to fix this?

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
