### ISSUE TITLE
Heiler Simulieren

### ISSUE THREAD

**Issue by Tyranny20** [simulationcraft/simc#3969]
ich kann meinen heiler nicht simulieren da zeigt er mir den fehler code 32 an

**Comment by Hilzerak** [comment]
Wie überall nachzulesen gibt es aktuell keinen Support für Heiler.

**Comment by Bloodmallet** [comment]
Der gegebenen Antwort ist nichts weiter hinzuzufügen, außer: viele Heiler Theorycrafter haben Tabellenkalkulationen gebastelt. Schaue dort mal rein.
