### ISSUE TITLE
Blank error code

### ISSUE THREAD

**Issue by NoxumbraX** [simulationcraft/simc#3970]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version : 730-01

Good afternoon,

Trying to experience simcraft for the first time, I encounter an error that i'm not able to solve by myself since the code error stay blank.

> SimulationCraft encountered an error!
> 
> Simulation runtime error:
> 
> 
> Please open a ticket, copying the detailed text below.
> It contains all the input options of the last simulation and helps us reproduce the issue.
> 
> # SimulationCraft encountered an error!
> * Category: Simulation runtime error
> * Error: 
> 
> ## All options used for simulation:
> ``` ini
> ### Begin GUI options ###
> item_db_source=local/bcpapi/wowhead
> target_error=0
> iterations=0
> default_world_lag=0.1
> max_time=300
> vary_combat_length=0.2
> fight_style=Patchwerk
> tmi_window_global=6
> target_level+=3
> target_race=Humanoid
> optimal_raid=0
> override.bloodlust=1
> override.bleeding=1
> override.mortal_wounds=1
> threads=4
> process_priority=Low
> statistics_level=1
> ### End GUI options ###
> ### Begin simulateText ###
> priest="Belùmbra"
> level=110
> race=blood_elf
> region=eu
> server=archimonde
> role=heal
> 
> talents=1131312
> spec=holy
> artifact=45:0:0:0:0:834:1:835:1:836:1:837:1:838:3:839:1:840:1:841:4:842:4:843:4:844:4:845:1:846:4:847:4:848:3:849:4:1346:1:1380:1:1569:4:1570:1:1571:1:1649:1
> 
> head=,id=134348,bonus_id=1824/1497/3527
> neck=,id=146867,bonus_id=1825/42/1507/3528
> shoulder=,id=137503,bonus_id=1826/1497/3528
> back=,id=121804
> chest=,id=133413,bonus_id=3623,drop_level=110
> wrist=,id=139926
> hands=,id=134173,bonus_id=1825/1502/3528
> waist=,id=121757,bonus_id=1825/1808/1507/3528
> legs=,id=133389,bonus_id=3623,drop_level=110
> feet=,id=121420,bonus_id=768/1740,drop_level=106
> finger1=,id=129168,bonus_id=664,drop_level=109
> finger2=,id=130021,bonus_id=767/1733,drop_level=107
> trinket1=,id=134160,bonus_id=3394/607/1507/3528
> trinket2=,id=141619,bonus_id=767/1734,drop_level=107
> main_hand=,id=128825,gem_id=132345/132322,bonus_id=739,relic_id=1793:1741:1625:1809/664:1591:1809
> 
> ### Gear from Bags
> #
> # Bluefen Cowl of the Feverflare (312)
> # head=,id=55747,suffix=-138
> #
> # Cowl of Absolution (146)
> # head=,id=31063
> #
> # Radiant Charm of Elune (680)
> # neck=,id=121641,bonus_id=664,drop_level=108
> #
> # Shaladrassil Vestments (800)
> # chest=,id=129985
> #
> # Gloves of Absolution (146)
> # hands=,id=31060
> #
> # Cord of the High Priest (840)
> # waist=,id=139761,bonus_id=3386/3384
> #
> # Valor-Bound Trousers (800)
> # legs=,id=129989
> #
> # Biting Wind (346)
> # main_hand=,id=133233,bonus_id=3623,drop_level=110
> #
> 
> ### End simulateText ###
> desired_targets=1
> ### Begin overrides ###
> # User-specified persistent global and player parameters will be set here.
> 
> ### End overrides ###
> ### Begin final options ###
> ### End final options ###
> ### END ###
> ```

I hope you guys could help me,

Belumbra

**Comment by NoxumbraX** [comment]
Nobody can help me? :(

**Comment by scamille** [comment]
This issue should be fixed in the newest revision.

But we also just disabled holy priests with a nicer error message, so you will get 

```
Player Belùmbra's role (heal) or spec(Holy Priest) is currently not supported.
No active players in sim!
Simulation was canceled.
```
