### ISSUE TITLE
Protection Paladin T20 2P Not Working

### ISSUE THREAD

**Issue by Dalfiuss** [simulationcraft/simc#3972]
The Tier 20 Protection Paladin 2p (Judgment has a 30% chance to reset the cooldown of Avenger's Shield) is not working/not added

#### Reproduction Steps:
Run a sim with 2p and without 2p with an adjusted APL to increase AS priority.

**Comment by BlacKcuD** [comment]
Confirmed, T20 Protection Paladin not working.

**Comment by Bloodmallet** [comment]
Tanks aren't as supported as dd-specs. That beeing said, if you're interested in maintaining the tank aspect of paladins or know someone who might be, clone the repo, fix whatever you want to fix and create a pull request. If you need a point to start, the wiki here is a good place and if you need more join https://discord.gg/tFR2uvK to ask questions about how to do something. C++ is required for the class modules.

**Comment by Melekus** [comment]
Actually that was fixed in https://github.com/simulationcraft/simc/commit/9878e2c019ef1d651b471fa444b1ee865a33e06a
