### ISSUE TITLE
Batch simulation not working

### ISSUE THREAD

**Issue by sly9** [simulationcraft/simc#3974]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
Just synced to head and built from source(12:23PM PDT Sep 6, 2017).
Built on linux(Ubuntu 14.04)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
iterations=3000
vary_combat_length=0.2
max_time=300
html=/var/www/html/simc/ehope.html

armory=us,illidan,aierbeijuare
armory=us,illidan,arceuscc
armory=us,illidan,archher
armory=us,illidan,assamaster
armory=us,illidan,candyseller
armory=us,illidan,catalysiz
armory=us,illidan,chelriver
armory=us,illidan,crystalori
armory=us,illidan,dabiaojie
armory=us,illidan,danchaofan
armory=us,illidan,ettohh
armory=us,illidan,euroblood
armory=us,illidan,gilgammesh
armory=us,illidan,inoriyuzuri
armory=us,illidan,klaht
armory=us,illidan,lawlea
armory=us,illidan,lesbiaan
armory=us,illidan,lithivm
armory=us,illidan,madgroot
armory=us,illidan,mannose
armory=us,illidan,mikaaqq
armory=us,illidan,mikuruasahin
armory=us,illidan,mlgbpal
armory=us,illidan,monstersoul
armory=us,illidan,nijimula
armory=us,illidan,orionzc
armory=us,illidan,pandashooter
armory=us,illidan,penguinduck
armory=us,illidan,qianyue
#armory=us,illidan,rianlorian
armory=us,illidan,shaluria
armory=us,illidan,xalatathie
armory=us,illidan,yoyorock
armory=us,illidan,yvesh
#### Reproduction Steps:

Save the above content to guild.simc, and run "simc guild.simc"

Expected behavior: After importing all the characters, start simulating and generate report afterwards.

Actual behavior:
sly@liuyi:~$ simc guild.simc@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SimulationCraft 730-02 for World of Warcraft 7.3.0 Live (wow build 24931, git build d01aa7a)

Simulating... ( iterations=3000, threads=2, target_error=0.000,  max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )
sly@liuyi:~$ 

It didn't simulate at all, stopped immediately after importing.

Other commands like 'simc guild="E Hope",region=us,server=illidan,ranks=0/1 iterations=3000 ' results in similar issue:

sly@liuyi:~$ simc guild="E Hope",region=us,server=illidan,ranks=0/1 iterations=3000  vary_combat_length=0.2 max_time=300 html=/var/www/html/simc/ehope_test.html
@Downloading character: Gongfoopanda
@Downloading character: Hailhydrazz
@Downloading character: Imei
@Downloading character: Kezhanfu
@Downloading character: Monstersoul
@Downloading character: Pandiamonk
@Downloading character: Rosewar
@Downloading character: Silei
@Downloading character: Yoyorock
@SimulationCraft 730-02 for World of Warcraft 7.3.0 Live (wow build 24931, git build d01aa7a)

Simulating... ( iterations=3000, threads=2, target_error=0.000,  max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )

Downloading character: Gongfoopanda
Downloading character: Hailhydrazz
Downloading character: Imei
Downloading character: Kezhanfu
Downloading character: Monstersoul
Downloading character: Pandiamonk
Downloading character: Rosewar
Downloading character: Silei
Downloading character: Yoyorock

This issue started around 4-5 days ago, as I have a script updating my simc every night, and run a guild report every day.

**Comment by sly9** [comment]
I had a friend downloaded the latest nightly build for windows, and had him running same command, and he got exactly the same result. So it's likely to be an issue in simc. Is this feature abandoned on purpose or is it a bug?

**Comment by schnello** [comment]
Tested with the latest build with your simc file (only 1 iterations) . Works fine (Ubuntu 16.04)
