### ISSUE TITLE
Simulationcraft crashes at the very end of simulating

### ISSUE THREAD

**Issue by Drneferious** [simulationcraft/simc#3975]
Every time I simulate any character my simulationcraft crashes It does it at the very end of the sim right as its about to show the sim.

**Comment by scamille** [comment]
Please provide more information.

Exact SimC version, your OS, etc.

Also add your simc_gui.simc file (see https://github.com/simulationcraft/simc/wiki/simc_gui.simc) so we can reproduce the issue.

**Comment by keallachtool** [comment]
I'm gonna steal his thread since i have the same issue.

I'm using 730-02 on Windows 10
https://my.pcloud.com/publink/show?code=XZDfx57ZGAKqjWJdhRypSlKDiDekTf2nDInX -> simc_gui.simc file
Crash occurs only with scaling option "on".

Please let me know if you need more info.
