### ISSUE TITLE
Blood Deathknight T20 2P/4P Not Working

### ISSUE THREAD

**Issue by stollsen** [simulationcraft/simc#3976]
the versatilitygain from 2p and the runepowerreduce from 4p is not working

Reproduction Steps:

Run a sim with 2p/4p and without 2p/4p

**Comment by Melekus** [comment]
Blood Death Knight isn't supported at the moment and nobody is actively working on it. Even if T20 was implemented, I doubt you could get accurate information from the results : some spells/mechanics aren't properly implemented and a lot of spells have lower damage in simc compared to ingame numbers.
