### ISSUE TITLE
Please make the Pawn weights output string look like "Bob - Fire" or "Bob - Ice", not just "Bob"!

### ISSUE THREAD

**Issue by Nefrathar** [simulationcraft/simc#3977]
#### SimCraft Version: 725-01

Not a bug, more like a nice-to-have change. But it really kills me to always rename, delete, change the imported weights profiles in Pawn for each specialization by hand, since "Bob" always overwrites "Bob", no matter of the spec.

Since I trust SimCraft more than Mr. Robot - that does put out a string marked for the appropriate spec - I hope that this easy change is implemented at some point.

I'm a first time poster here, so please be nice if I posted in the wrong place. Still a little overwhelmed of the specific GitHub genre and structure.

e.g. not ( Pawn: v1: "Rakzhul": Class=Mage, Spec=Frost, Intellect=15.84, SpellPower=15.26, CritRating=17.78, HasteRating=14.95, MasteryRating=11.12, Versatility=14.94 )

but

( Pawn: v1: "Rakzhul - **FROST**": Class=Mage, Spec=Frost, Intellect=15.84, SpellPower=15.26, CritRating=17.78, HasteRating=14.95, MasteryRating=11.12, Versatility=14.94 )

Thanks a lot,

Nef

**Comment by lgkern** [comment]
https://github.com/simulationcraft/simc/commit/c31a50fb5f6cf10bb7bae6702c94971f6deb93d9 adds the funcionality asked
