### ISSUE TITLE
Brewmaster: Haste simming out to negative values for DPS

### ISSUE THREAD

**Issue by honoraryorange** [simulationcraft/simc#3978]
#### Simulationcraft Version
730-02 (and 730-01, but I don't believe any 7.2.5 builds)

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here -
n/a

#### simc_gui.simc file or contents
https://pastebin.com/kN92w3ut

#### Reproduction Steps:

Whenever my haste is ~11% it starts reporting Haste's value for DPS as around -5.50 to -6.00 or so. If I drop my under haste 10% it seems alright, or if I bump it way up (tested at 21%) it sims fine. But when it is around 11% Simcraft seems to freak out and give me negative values for haste.

**Comment by Bloodmallet** [comment]
Calculated Stat Weights depend on the apl. Therefore if the apl does work very well at certain stat values or very bad at others, you'll see such behaviour. Check out your class discord to find out more about haste and such behaviour. It is not a SimulationCraft issue.
