### ISSUE TITLE
Suramar absent from EU server list

### ISSUE THREAD

**Issue by Magikreaper** [simulationcraft/simc#3988]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by navv1234** [comment]
I have refreshed the GUI realmlists. Updated realm list includes suramar, so it should be available in the next nightly build (OS X already uploaded).
