### ISSUE TITLE
Significantly longer "Merging Data from thread X" with very large thread count

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#3989]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
Doesn't apply

#### Reproduction Steps:
When doing a sim with a large amount of threads (20+), a significant amount of time is spent merging data from thread X, ruining any time speed gains from using larger thread amounts.

I use a third party program called Simpermut AutoSimC to permutate through many different gear combinations to find optimum solutions. This usually starts with simming 30-150 actors at a time with low iteration counts (100-200 or so) to get rough baselines. Each actor sims quite quickly obviously, but after the last actor, it seems a single thread is used to 'merge data from thread X', which significantly slows down the process, sometimes taking longer than the actor simulations themselves.

Could this behavior be optimized maybe? I had an 8c/16t intel CPU before, but now I'm running on a 16c/32t AMD threadripper CPU, and I do see very significant gains in simming speed, but the thread merging behavior is much slower now, negating any sim speed gains.

**Comment by ssateneth** [comment]
In case you want some sort of idea what the speed difference is like, I recorded the console output. One of 4 thread, then 8 threads, then 16 threads, then 32 threads. Hardware used is AMD Ryzen Threadripper 1950x @ 4.2GHz, 4 x 16GiB DDR4 3066MHz @ 14-14-14-30 1T, 1250 watt seasonic power supply, Windows 8.1 Pro.

Heres a .simc file that replicates the first set of 100 actors, just adjust thread count.
https://hastebin.com/karehobabu.makefile

Heres the video recordings.

4 threads
https://i.imgur.com/UFThXIl.gifv

8 threads
https://i.imgur.com/B7dIETP.gifv

16 threads
https://i.imgur.com/eEYdlDD.gifv

32 threads
https://i.imgur.com/7kxJtIc.gifv

**Comment by navv1234** [comment]
This is probably fixed in the next nightly. Probably. Maybe.

**Comment by scamille** [comment]
@ssateneth is this fixed?

So was not deleting threads by default what fixed this?
