### ISSUE TITLE
Runtime error; invalid crucible rank

### ISSUE THREAD

**Issue by superquark** [simulationcraft/simc#3990]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Unexpected parameter '*'. Expected format: name=value
Player Vyralea invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Vyralea invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Vyralea invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Vyralea invalid crucible rank '1782&&1739&&1739' for power '1739', expected a number > 0 && <= 255
Player Vyralea invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Vyralea invalid crucible format, expected: power_id:rank[:power_id:rank...]

#### Reproduction Steps:
ran /simc in game
copied all items from the modal
pasted them into the Simulate tab
Clicked simulate

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by navv1234** [comment]
You have a couple of options:

1) You can install the latest nightly build from http://downloads.simulationcraft.org/?C=M;O=D that will have support for the new crucible option format
2) You can install an earlier version of the simulationcraft addon that will export the earlier version (1.8.1) of the crucible string

We will do an official release soon.
