### ISSUE TITLE
Simulation runtime error

### ISSUE THREAD

**Issue by goblinmaage** [simulationcraft/simc#3998]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 
----simulationcraft 730-01

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
-----(Simc isn't crashing)

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
-----
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=250
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=0
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
mage="st"
level=110
race=goblin
region=kr
server=
role=spell
professions=alchemy=120/jewelcrafting=4
talents=2133131
spec=frost
artifact=53:0:0:0:0:783:1:784:4:785:4:786:4:787:4:788:4:789:4:790:4:791:4:792:4:793:1:794:1:795:1:796:1:797:1:798:1:1296:1:1373:1:1537:4:1538:1:1539:1:1540:13:1641:1
crucible=1739:1783/1739:1783/0

head=,id=147147,bonus_id=3561/1482/3528
neck=,id=148030,enchant_id=5439,gem_id=151585,bonus_id=3579/1808/1527/3336
shoulder=,id=152354,bonus_id=3614/40/1472/3528
back=,id=150988,enchant_id=5433,bonus_id=3397/1572/3337
chest=,id=146994,bonus_id=3562/41/1507/3336
shirt=,id=10055
wrist=,id=134310,bonus_id=3415/1567/3528
hands=,id=147146,bonus_id=3561/1497/3337
waist=,id=146876,gem_id=130221,bonus_id=3394/1808/1567/3337
legs=,id=137496,bonus_id=3414/1577/3337
feet=,id=146987,bonus_id=3562/1502/3336
finger1=,id=151642,enchant_id=5427,gem_id=130221,bonus_id=3459/3570
finger2=,id=132452,enchant_id=5427,gem_id=130219,bonus_id=1811/3570
trinket1=,id=139076,bonus_id=3573/604/1582/3336
trinket2=,id=134336,bonus_id=3573/603/1587/3337
main_hand=,id=128862,gem_id=142185/147078/152346,bonus_id=731,relic_id=3573:1527:3528/3562:1497:3528/3614:1482:3336
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:
----After the netherlight crucible patch, every time I try to sim my character, a 'Simuation runtime error' message pops up. The message says 'Player st invalid crucible format, expected: power_id:rank[:power_id:rank...]'
 I'm currently using the 730-01 version and simulationcraft doesn't crashes, just the message above keeps on to pop up.
 Thank you.

**Comment by navv1234** [comment]
You have a couple of options:

1) If you are on MacOS, you can download http://downloads.simulationcraft.org/simc-730-02-osx-x86.dmg, which supports the new crucible= option format
2) Otherwise, you can install the latest nightly build for windows from http://downloads.simulationcraft.org/?C=M;O=D 
3) Or, you can install an earlier version of the simulationcraft addon that will export the earlier version (1.8.1) of the crucible string

We will do an official release soon.

**Comment by goblinmaage** [comment]
Thanks!
