### ISSUE TITLE
SimCraft won't start 

### ISSUE THREAD

**Issue by Janson1234** [simulationcraft/simc#3999]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
7.3.0.02
 If I start it nothing happens even if I try to start it more than once.

**Comment by dragsuffer** [comment]
I have the same problem. It does not start any more.

Maybe the error report brings something.

Version=1
EventType=APPCRASH
EventTime=131499893897925818
ReportType=2
Consent=1
UploadTime=131499893901970860
ReportStatus=268435456
ReportIdentifier=b452b504-1000-4c98-ba89-5db6f41b6f17
IntegratorReportIdentifier=8e085e02-d18f-41a0-bd4e-d8c94e62e499
Wow64Host=34404
NsAppName=SimulationCraft.exe
AppSessionGuid=00002d54-0001-0014-8d57-26ef742ed301
TargetAppId=W:0000c1122c27600d88e80611b1fdeb7adda80000ffff!0000ced2c60af440087276ecfc155f844ab444046f77!SimulationCraft.exe
TargetAppVer=2017//09//14:14:22:15!0!SimulationCraft.exe
BootId=4294967295
TargetAsId=191
Response.BucketId=44d5ef40ea9b65f441314a63f2785952
Response.BucketTable=4
Response.LegacyBucketId=120833285912
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=SimulationCraft.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=0.0.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=59ba9097
Sig[3].Name=Fehlermodulname
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=5.6.2.0
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=57e776af
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=00000000000af813
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=0d78
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=0d7839bf26c11d363f39a585a4a187b6
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=35fc
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=35fc34e974d838d72e81c369a4c81d4c
UI[2]=E:\Simulationcraft\730-02\SimulationCraft.exe
UI[3]=SimulationCraft funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=E:\Simulationcraft\730-02\SimulationCraft.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[5]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\WININET.dll
LoadedModule[7]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[8]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[9]=C:\WINDOWS\System32\shcore.dll
LoadedModule[10]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[11]=C:\WINDOWS\System32\combase.dll
LoadedModule[12]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[13]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[14]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[15]=C:\WINDOWS\System32\sechost.dll
LoadedModule[16]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[17]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[18]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[19]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[20]=C:\WINDOWS\System32\USER32.dll
LoadedModule[21]=C:\WINDOWS\System32\win32u.dll
LoadedModule[22]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[23]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[24]=C:\WINDOWS\System32\profapi.dll
LoadedModule[25]=E:\Simulationcraft\730-02\Qt5WebEngineWidgets.dll
LoadedModule[26]=E:\Simulationcraft\730-02\Qt5Widgets.dll
LoadedModule[27]=E:\Simulationcraft\730-02\Qt5Network.dll
LoadedModule[28]=E:\Simulationcraft\730-02\Qt5Gui.dll
LoadedModule[29]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[30]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[31]=E:\Simulationcraft\730-02\Qt5Core.dll
LoadedModule[32]=E:\Simulationcraft\730-02\MSVCP140.dll
LoadedModule[33]=C:\WINDOWS\System32\ole32.dll
LoadedModule[34]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[35]=E:\Simulationcraft\730-02\VCRUNTIME140.dll
LoadedModule[36]=E:\Simulationcraft\730-02\Qt5Quick.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[38]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[39]=C:\WINDOWS\System32\NSI.dll
LoadedModule[40]=E:\Simulationcraft\730-02\Qt5WebEngineCore.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[42]=C:\WINDOWS\System32\IMM32.dll
LoadedModule[43]=E:\Simulationcraft\730-02\Qt5Qml.dll
LoadedModule[44]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[45]=C:\WINDOWS\System32\COMDLG32.dll
LoadedModule[46]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[47]=E:\Simulationcraft\730-02\Qt5WebChannel.dll
LoadedModule[48]=E:\Simulationcraft\730-02\Qt5Positioning.dll
LoadedModule[49]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.483_none_26002d27e7c744a2\COMCTL32.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\Secur32.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\WINHTTP.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[53]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\winmmbase.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL
LoadedModule[59]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[60]=E:\Simulationcraft\730-02\platforms\qwindows.dll
LoadedModule[61]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[62]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[63]=C:\WINDOWS\system32\d3d9.dll
LoadedModule[64]=C:\WINDOWS\System32\WINTRUST.DLL
LoadedModule[65]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[67]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[69]=C:\WINDOWS\system32\nvspcap64.dll
LoadedModule[70]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[72]=C:\WINDOWS\system32\nvapi64.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[75]=C:\WINDOWS\SYSTEM32\opengl32.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[77]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\nvoglv64.DLL
LoadedModule[79]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\WINSTA.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=SimulationCraft
AppPath=E:\Simulationcraft\730-02\SimulationCraft.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=5EAFB21B31562A5E90F79D06E8E9B8F6
MetadataHash=1087056403

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
