### ISSUE TITLE
Error: Player <name> invalid crucible rank

### ISSUE THREAD

**Issue by lightsfaster** [simulationcraft/simc#4000]
so when i try to sim i get this error "Error: Player Zanwa invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255"
 
is this something to do with the netherlight crucible?
both simcraft and the in-game addon are up to date. 

 Simulationcraft Version - 730-01

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Zanwa invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
hunter="Zanwa"
level=110
race=troll
region=eu
server=draenor
role=attack
professions=leatherworking=800/skinning=800
talents=2111112
spec=beast_mastery
artifact=56:0:0:0:0:868:4:869:4:870:4:871:4:872:4:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1520:10:1636:1
crucible=1739:1782/1739/1739

head=,id=147142,bonus_id=3561/1482/3528
neck=,id=137418,enchant_id=5437,bonus_id=3536/1582/3337
shoulder=,id=147144,bonus_id=3561/1487/3336
back=,id=147140,enchant_id=5432,bonus_id=3562/1497/3528
chest=,id=151805,bonus_id=1811/3570
shirt=,id=127
tabard=,id=118372
wrist=,id=152373,bonus_id=3614/1472/3528
hands=,id=150435,bonus_id=3589/3590,drop_level=110
waist=,id=137080,bonus_id=1811/3570
legs=,id=147143,bonus_id=3561/1482/3528
feet=,id=147045,bonus_id=3562/1497/3528
finger1=,id=133679,bonus_id=3573/1562/3528
finger2=,id=134323,bonus_id=3573/1577/3336
trinket1=,id=147010,gem_id=130222,bonus_id=3561/1808/1482/3528
trinket2=,id=147015,bonus_id=3561/1482/3528
main_hand=,id=128861,gem_id=150353/147076/140817,bonus_id=726,relic_id=3579:3149:3336/3562:1497:3528/3517:1492:1813

**Comment by navv1234** [comment]
You have a couple of options:

1) If you are on MacOS, you can download http://downloads.simulationcraft.org/simc-730-02-osx-x86.dmg, which supports the new crucible= option format
2) Otherwise, you can install the latest nightly build for windows from http://downloads.simulationcraft.org/?C=M;O=D 
3) Or, you can install an earlier version of the simulationcraft addon that will export the earlier version (1.8.1) of the crucible string

We will do an official release soon.
