### ISSUE TITLE
 invalid crucible format, expected: power_id:rank[:power_id:rank...] 

### ISSUE THREAD

**Issue by eentje** [simulationcraft/simc#4006]
Please include a brief overview of the issue in the title above, as well as completing the following:

wanted to sim new gear. got error about crudiclbe format. i didnt have it unlocked first time i tried simming. having it unlocked on the char still gave same error

#### simc_gui.simc file or contents

error log.
[log.txt](https://github.com/simulationcraft/simc/files/1304313/log.txt)

#### Reproduction Steps:
inporting /simc output from addon. 
https://pastebin.com/RPypcLkZ

**Comment by lgkern** [comment]
Hello, the issue is caused because you're running an old SimC version with a updated addon version.
You can find more info at #4000
