### ISSUE TITLE
Havoc Demon Hunter error

### ISSUE THREAD

**Issue by Elzena** [simulationcraft/simc#4008]
Hello I've just installed Simcraft and tried to get a profile of my character and sim it. When getting character info and attempting to sim I get an error:

> Simulation runtime error:
Player Demon_Hunter_Havoc_T19H action throw_glaive : Unable to decode expression function 'buff.raid_movement.up' Demon_Hunter_Havoc_T19H-throw_glaive: Unable to build expression tree from buff.out_of_range.up|buff.raid_movement.up Simulation has been canceled during player setup! (thread=0) Player Elzena action throw_glaive : Unable to decode expression function 'buff.raid_movement.up' Elzena-throw_glaive: Unable to build expression tree from buff.out_of_range.up|buff.raid_movement.up Simulation has been canceled during player setup! (thread=0) Player Elzena action throw_glaive : Unable to decode expression function 'buff.raid_movement.up' Elzena-throw_glaive: Unable to build expression tree from buff.out_of_range.up|buff.raid_movement.up Simulation has been canceled during player setup! (thread=0) Player Elzena action throw_glaive : Unable to decode expression function 'buff.raid_movement.up' Elzena-throw_glaive: Unable to build expression tree from buff.out_of_range.up|buff.raid_movement.up Simulation has been canceled during player setup! (thread=0)

**Comment by EvanMichaels** [comment]
Unable to reproduce this, possible it was just an issue with that particular build. Thanks.
