### ISSUE TITLE
Simulation Runtime Error - Crucible

### ISSUE THREAD

**Issue by A11ectis** [simulationcraft/simc#4009]
#### Simulationcraft Version
730-01
1.8.2 Add-on

#### simc_gui.simc file or contents
https://pastebin.com/1aNMq12V

#### Reproduction Steps:

Use /simc in-game when Crucible is unlocked, and trying to sim.

**Comment by AlexanderKenny** [comment]
Duplicate of #4000 read the comments on that issue for how to fix
