### ISSUE TITLE
Frost mages use WoD Food

### ISSUE THREAD

**Issue by Edwinger** [simulationcraft/simc#4028]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 7.3.0, release 1

#### simc_gui.simc file or contents
# Default consumables
potion=prolonged_power
flask=whispered_pact
food=lemon_herb_filet
augmentation=defiled

#### Reproduction Steps:
Create any Simc file of a frost mage.

**Comment by vituscze** [comment]
Is that a problem? Lemon Herb Filet is slightly better than Lavish Suramar Feast at the current gear level.

**Comment by Edwinger** [comment]
Yes because 1% versatility is not going to beat 375 versatility unless they have more then 37500 versatility.

**Comment by vituscze** [comment]
The food gives the equivalent of 1% versatility, which is 475 at level 110 (465 for a human).

**Comment by Edwinger** [comment]
Oh ok, I was misunderstanding on how the buff was calculated.
