### ISSUE TITLE
profile/action list problem with sephuz usage

### ISSUE THREAD

**Issue by JR-Samples** [simulationcraft/simc#4029]
This applies to all the shadow priest simc profiles. 

When using silence to proc Sephuzs, one of the conditions checked is ```cooldown.buff_sephuzs_secret.remains<1```

Since silence is instant cast, the cooldown buff (ID: 226262) needs to be down/expired before casting silence.

Here is an example of the condition check in context:
```actions.s2m=silence,if=equipped.sephuzs_secret&(target.is_add|target.debuff.casting.react)&cooldown.buff_sephuzs_secret.remains<1&!buff.sephuzs_secret.up,cycle_targets=1```

#### Simulationcraft Version: N/A / all

**Comment by N1gh7h4wk** [comment]
[https://github.com/simulationcraft/simc/commit/f751ccdb171ce08e45838592e901b693fd3ea8c6](url)
Should fix that logic. Thank you for noticing!
