### ISSUE TITLE
hand full of errors while simming lower lvl characters (lvl 70)

### ISSUE THREAD

**Issue by zoke0117** [simulationcraft/simc#4037]
elemental shaman's rotation/ priority isnt  simming, all that shows up is  the fire elemental's damage

unholy dk below lvl 80 scourge strike's shadow damage isnt working and causing the sim to fail

fish feast not recognized
thundering skyflare and all other proc meta gems dont work
blackened naaru sliver also being ignored

lvl 70 frost dk remorseless winter and glacial advance arent showing in the sim either

**Comment by vituscze** [comment]
simc doesn't really support simming low level characters, all efforts are focused on max level.

**Comment by zoke0117** [comment]
that is lame

**Comment by lgkern** [comment]
we're always open to more people willing to contribute and make those sims possible.

**Comment by zoke0117** [comment]
if i knew how to do that id probably  have already  posted the fix

**Comment by scamille** [comment]
I am going to close this.

As said, most specs do not really support low level characters at all. What we certainly will never promise is any support for default action priority lists for low level characters.
So you at least need to adjust the action priority list yourself for your character, and do the fine-tuning for it.

If there are any actual bugs like actions crashing, we will likely fix it even for low level only things, provided you can give easy to reproduce examples.
