### ISSUE TITLE
all stats negative

### ISSUE THREAD

**Issue by darkseid4nk** [simulationcraft/simc#4038]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-02
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Demon
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech
scale_over=TMI
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
druid="Riphritp"
level=110
race=night_elf
region=us
server=darkspear
role=tank
professions=engineering=704/skinning=689
talents=3331321
spec=guardian
artifact=57:0:0:0:0:948:4:949:4:950:4:951:4:952:4:953:4:954:4:955:4:956:4:957:1:958:1:959:1:960:1:961:1:962:1:979:1:1334:1:1366:1:1509:4:1510:1:1511:1:1512:10:1634:1
crucible=1739:1784/1739/1739

head=,id=151588,gem_id=151585,bonus_id=1717/3408/3609/600/3608
neck=,id=130239,enchant_id=5889,gem_id=151585,bonus_id=1777/689/600/679
shoulder=,id=147138,bonus_id=3561/1497/3337
back=,id=146984,bonus_id=3562/1502/3336
chest=,id=137015,bonus_id=3459/3570
wrist=,id=144485,bonus_id=3416/1577/3337
hands=,id=147135,bonus_id=3562/41/1497/3528
waist=,id=147425,bonus_id=3562/41/1497/3528
legs=,id=137067,bonus_id=3459/3570
feet=,id=147424,gem_id=151585,bonus_id=3562/1808/41/1497/3528
finger1=,id=139065,bonus_id=3573/41/1572/3528
finger2=,id=147257,bonus_id=1780/41/3574/1652/3336
trinket1=,id=147022,bonus_id=3562/1497/3528
trinket2=,id=147015,bonus_id=3561/1497/3337
main_hand=,id=128821,gem_id=147088/147081/147104,bonus_id=724,relic_id=3562:1497:3528/3562:1497:3528/3562:1497:3528
off_hand=,id=128822

### Gear from Bags
#
# Lunar-Wrath Headgear (915)
# head=,id=147033,bonus_id=3562/1808/1497/3528
#
# Plague-Resistant Headcover (910)
# head=,id=147740,bonus_id=3573/1492/3528
#
# Twilight's Edge Spaulders (905)
# shoulder=,id=151319,bonus_id=1727/1808/1557/3337
#
# Stygian Shoulderguards (915)
# shoulder=,id=150970,bonus_id=3397/1808/1577/3337
#
# Shroud of Cooperation (35)
# back=,id=63352
#
# Shroud of the Drowned Adherent (905)
# back=,id=146985,bonus_id=3561/40/1487/3336
#
# Wrap of Unity (35)
# back=,id=63206
#
# Fury of Nature (970)
# back=,id=151802,enchant_id=5435,bonus_id=1811/3570
#
# Cloak of Coordination (60)
# back=,id=65360
#
# Spore-Coated Vest (940)
# chest=,id=144483,bonus_id=3418/1592/3337
#
# Cinch of Sizzling Flesh (915)
# waist=,id=147039,bonus_id=3562/43/1497/3528
#
# Bonespur Studded Legwraps (915)
# legs=,id=147035,bonus_id=3562/1497/3528
#
# Vile Drifter's Footpads (935)
# feet=,id=152359,bonus_id=3614/1477/3336
#
# Portal Keeper's Seal (910)
# finger1=,id=146767,bonus_id=3573/1572/3528
#
# Arch-Druid's Tainted Seal (910)
# finger1=,id=134487,bonus_id=3573/1562/3528
#
# Scaled Band of Servitude (915)
# finger1=,id=147020,bonus_id=3562/1497/3528
#
# Ring of Braided Stems (910)
# finger1=,id=140896,bonus_id=3573/40/1507/3528
#
# Ring of Contempt (910)
# finger1=,id=134490,bonus_id=3417/1562/3528
#
# Seal of Malicious Deceit (910)
# finger1=,id=134489,bonus_id=3573/1562/3528
#
# Maelstrom Band of the Harmonious (900)
# finger1=,id=130230,enchant_id=5430,gem_id=130221,bonus_id=3368/689/600/679
#
# Band of the Kirin Tor (200)
# finger1=,id=40586
#
# Dual Determination (970)
# finger1=,id=137041,gem_id=151585,bonus_id=3459/3570
#
# Signet of the Kirin Tor (200)
# finger1=,id=40585
#
# Nightmare Loop (910)
# finger1=,id=121288,bonus_id=3573/1572/3528
#
# Shadowruby Band of the Harmonious (900)
# finger1=,id=136713,enchant_id=5430,gem_id=130221,bonus_id=3359/689/600/679
#
# Cradle of Anguish (915)
# trinket1=,id=147010,bonus_id=3562/1497/3528
#
# Fishing Pole (1)
# main_hand=,id=6256
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

steps taken:
/simc in game. copied to clipboard.
open simcraft, options -> scaling tab
enable scaling
center scale data left on no
scale over TMI
selected all scale factors other than movement speed and latency

**Comment by Melekus** [comment]
TMI is a Tanking metric used to gauge how spikey the damage intake of a tank is. It's not an accurate meter to represent tanking performance and it will vary a lot depending on the fight's damage pattern.

The lower your TMI is, the better you are at dealing with large damage intake :
Your stats' scaling for this meter are negative because a lower TMI indicates a higher performance.

**Comment by darkseid4nk** [comment]
Great explanation Melekus. It is really confusing to me because im trying to get a correct pawn string so i can gear efficiently. and with negative values i have no idea what to do or change. simc has an overwhelming amount of options. :(
