### ISSUE TITLE
Default Arcane Profile Seems Suboptimal

### ISSUE THREAD

**Issue by dsteinyb** [simulationcraft/simc#4042]
I was testing the default Arcane Mage profile on the simulationcraft website for various ways it would be improved with the release of Antorus, and I discovered that the current relic lineup is not the most optimal one to use. It says that three ranks of Murderous Intent yields 1.575M dps, which did turn out to be the case in my SimC; however, when I put in three ranks of Torment of the Weak instead, I got a much higher dps value of 1.608M. If anyone else could confirm or deny that the latter case would be better for Arcane, I would appreciate it, and if it does turn out to be better, would the default profile be updated to reflect these changes?

**Comment by vituscze** [comment]
The profile was updated shortly before the last-minute crucible trait hotfixes, so yeah, it's a bit suboptimal at the moment.
