### ISSUE TITLE
Monk

### ISSUE THREAD

**Issue by Selinthya** [simulationcraft/simc#4073]
monk="Селинтия"
level=110
race=draenei
region=eu
server=
role=hybrid
professions=alchemy=800/herbalism=800
talents=1133111
spec=mistweaver
artifact=51:0:0:0:0:931:1:932:1:933:1:934:1:935:1:936:1:937:1:938:4:939:4:940:4:941:4:942:4:943:4:944:4:945:4:946:4:1295:1:1375:1:1545:4:1546:1:1547:1:1548:13:1643:1
crucible=1739:1779/1739:1770/1739

head=,id=147154,bonus_id=3562/1512/3337
neck=,id=147013,enchant_id=5437,bonus_id=3561/1512/3337
shoulder=,id=147156,gem_id=130217,bonus_id=3562/1808/1502/3336
back=,id=142215,enchant_id=5436,bonus_id=3418/1547/3337
chest=,id=147151,bonus_id=3562/1497/3528
wrist=,id=134461,gem_id=151580,bonus_id=3418/1808/1587/3337
hands=,id=152360,bonus_id=3614/1487/3337
waist=,id=147040,bonus_id=3562/1507/3336
legs=,id=147155,bonus_id=3564/1502/3337
feet=,id=137028,bonus_id=1811/3570
finger1=,id=134490,enchant_id=5427,gem_id=130248,bonus_id=3418/1808/1597/3337
finger2=,id=134524,enchant_id=5427,gem_id=151580,bonus_id=3418/1808/1567/3528
trinket1=,id=151607,bonus_id=3609/600/3608
trinket2=,id=144258,bonus_id=1811/3570
main_hand=,id=128937,gem_id=142186/140838/147114,bonus_id=733,relic_id=3573:1532:3336/3573:1517:3336/3562:1497:3528

### Gear from Bags
#
# Эполеты пожухлой листвы (940)
# shoulder=,id=134452,bonus_id=3418/1592/3337
#
# Оплечье из шкуры сталегляда (915)
# shoulder=,id=134154,bonus_id=3418/1577/3528
#
# Императорский конденсатор (970)
# chest=,id=144239,bonus_id=3459/3570
#
# Мундир обволакивающего диссонанса (905)
# chest=,id=138325,bonus_id=3518/1808/41/1502/3528
#
# Укрытие Жинь (970)
# chest=,id=144340,bonus_id=1811/3570
#
# Чехол от рога для питья (970)
# wrist=,id=137097,bonus_id=1811/3570
#
# Рукавицы Сюэня (925)
# hands=,id=147153,bonus_id=3562/1507/3336
#
# Зимняя повязка Овида (970)
# waist=,id=138879,bonus_id=1811/3570
#
# Бриджи недостойных душ (930)
# legs=,id=133616,bonus_id=3536/40/1582/3337
#
# Ботфорты грубого вторжения (915)
# feet=,id=147424,bonus_id=3562/1497/3528
#
# Ледоступы (915)
# feet=,id=147029,bonus_id=3561/1497/3337
#
# Кольцо из цепкого щупальца (935)
# finger1=,id=133634,enchant_id=5427,bonus_id=3418/1587/3337
#
# Великое творение Искусителя (915)
# trinket1=,id=147007,bonus_id=3561/1497/3336
#
# Знак Даргрула (915)
# trinket1=,id=137357,bonus_id=3418/1567/3528
#

**Comment by N1gh7h4wk** [comment]
Did you get any error message? Try out a newer version of simc if its a problem with crucible=

**Comment by Melekus** [comment]
Healers aren't supported in simc at the moment. That being said, if you're interested in supporting healing specs or know someone who might be, clone the repo, fix whatever you want to fix and create a pull request. If you need a point to start, the wiki here is a good place and if you need more join https://discord.gg/tFR2uvK to ask questions about how to do something. C++ is required for the class modules.
