### ISSUE TITLE
Mastery Gem +200 seems broken

### ISSUE THREAD

**Issue by GWdd** [simulationcraft/simc#4091]
Two identical simc inputs - with the exception one uses +150 Mastery gem and the other a +200 Mastery gem,  DPS output falls from about 1.20M to 1.09M ... 

Again, only identifiable difference is a single gem - and maybe higher level relics... hmm - maybe a different relic is that important  it can change dps 10% ???

head=blackened_mask_of_disgrace,id=146991,bonus_id=3562/1507/3336
neck=strand_of_the_stars,id=137487,bonus_id=3536/1582/3337,enchant=600mastery
shoulders=diabolic_mantle,id=147186,bonus_id=3562/1497/3528
back=reap_and_sow,id=144364,bonus_id=1811/3570,enchant=200int
chest=diabolic_robe,id=147185,bonus_id=3562/1502/3336
wrists=ravenous_devotees_bracelets,id=147000,bonus_id=3562/1497/3528
hands=diabolic_gloves,id=147182,bonus_id=3562/1507/3336
waist=braided_torture_lash,id=146998,bonus_id=3562/40/1512/3337
legs=diabolic_leggings,id=147184,bonus_id=3562/1808/43/1507/3336,gems=200mastery
feet=emberscatter_treads,id=146986,bonus_id=3562/1502/3336
finger1=scaled_band_of_servitude,id=147020,bonus_id=3562/1808/1497/3528,gems=200haste,enchant=200mastery
finger2=soul_of_the_netherlord,id=151649,bonus_id=1811/3570,gems=200haste,enchant=200mastery
trinket1=charm_of_the_rising_tide,id=147002,bonus_id=3562/1497/3528
trinket2=dreadstone_of_endless_shadows,id=144480,bonus_id=3573/1562/3528
main_hand=ulthalesh_the_deadwind_harvester,id=128942,bonus_id=747,gem_id=147110/147082/147108/0,relic_id=3561:1497:3337/3562:1507:3528/3562:1502:3336/0

head=,id=146991,bonus_id=3562/1507/3336
neck=,id=137487,enchant_id=5890,bonus_id=3536/1582/3337
shoulder=,id=147186,enchant_id=5931,bonus_id=3562/1497/3528
back=,id=144364,enchant_id=5436,bonus_id=1811/3570
chest=,id=147185,bonus_id=3562/1502/3336
wrist=,id=147000,bonus_id=3562/1497/3528
hands=,id=147182,bonus_id=3562/1507/3336
waist=,id=146998,bonus_id=3562/40/1512/3337
legs=,id=147184,gem_id=130222,bonus_id=3562/1808/43/1507/3336
feet=,id=146986,bonus_id=3562/1502/3336
finger1=,id=147020,enchant_id=5429,gem_id=151583,bonus_id=3562/1808/1497/3528
finger2=,id=151649,enchant_id=5429,gem_id=151583,bonus_id=1811/3570
trinket1=,id=147002,bonus_id=3562/1497/3528
trinket2=,id=144480,bonus_id=3573/1562/3528
main_hand=,id=128942,gem_id=147110/147082/147108,bonus_id=747,relic_id=3561:1497:3337/3562:1507:3528/3562:1502:3336

**Comment by GWdd** [comment]
Further check revealed that HASTE and MASTERY on the Main Hand Weapon is wrong when importing from Armory.  Weapon has +1020 Haste and +1020 Mastery; but SimCraft is only showing +965 to both, along with much lower Intellect.

Local	Main Hand	Ulthalesh, the Deadwind Harvester
ilevel: 941, weapon: { 8324 - 11264, 3.6 }, stats: { +3180 Int, +4770 Sta, +965 Haste, +965 Mastery, +17345 Int }, relics: { +62 ilevels, +65 ilevels, +64 ilevels }

Interestingly, RAIDBOTS imports seem to get it right.

**Comment by AlexanderKenny** [comment]
Could you save and upload the html output reports somewhere such as Dropbox or drive so I can view them (the GUI has a save button bottom right when viewing a report or include an html= line and rerun). The weapon difference you noted I suspect is due to a missing crucible line and the accompanying 15 ilvl but I'd like to confirm/root out the other issues for you.

**Comment by GWdd** [comment]
www.mvei.com\hold\1_20M_results.html
www.mvei.com\hold\1_09M_results.html

**Comment by GWdd** [comment]
While I am at it, a small nit is that the PROCS > arrow function is reversed.  When the item is OPEN the arrow is >; when the item is CLOSED the arrow is V  ... a cosmetic issue.

**Comment by vituscze** [comment]
Yes, one of the profiles is missing information about crucible traits, which results in 100k DPS difference.

**Comment by GWdd** [comment]
Can you guys point me to change logs I can follow so I know when this is fixed?

**Comment by vituscze** [comment]
Fixed? It's simming correctly.

**Comment by GWdd** [comment]
Maybe I am misunderstanding something then.  The low, incorrect sim, is from nightly Simulationcraft 7.30-03; and if I understand right, it is not capturing the Crucible numbers correctly, and if that is missing, then the math is going to be wrong.

If not the calculation engine, then the Import function isn't working as expected?

**Comment by vituscze** [comment]
If you add the missing crucible information (the `crucible=` line in your profile), it will match.

It seems that one of the profiles was done with /simc addon and the other one was done with armory import. Armory doesn't export any information about crucible traits, that's a Blizzard issue we can do nothing about.

**Comment by GWdd** [comment]
Got it; thanks.
