### ISSUE TITLE
Shaman sims with 0 DPS

### ISSUE THREAD

**Issue by PMueller9119** [simulationcraft/simc#4092]
Regardless if I use the Addon or import stats from https://worldofwarcraft.com/de-de/character/senjin/ioben the result is always 0 DPS...

#### Simulationcraft Version
730-02

[Shaman_Log.txt](https://github.com/simulationcraft/simc/files/1390040/Shaman_Log.txt)
[Shaman_Sim.txt](https://github.com/simulationcraft/simc/files/1390041/Shaman_Sim.txt)

[Shaman_simc_gui.simc.txt](https://github.com/simulationcraft/simc/files/1390046/Shaman_simc_gui.simc.txt)

**Comment by vituscze** [comment]
simc doesn't really support low level characters.

In particular, Elemental Shaman APL assumes you have a lvl 100 talent.

**Comment by PMueller9119** [comment]
I understand. So a note or warning instead of a simple "0" would be helpfull in such a case.
