### ISSUE TITLE
Can't import character

### ISSUE THREAD

**Issue by rhkdang** [simulationcraft/simc#4096]
After I upgrade nvidia grapic driver

i can't click any sim's import button
same problems are reported  in korean wow community.

how can i solve this problem?

![s1](https://user-images.githubusercontent.com/32887307/31696126-21aa3784-b3ea-11e7-8684-b131964f2ad7.jpg)

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
