### ISSUE TITLE
Simc 7.3 release 2 didnt install, wont uninstall

### ISSUE THREAD

**Issue by bender1981** [simulationcraft/simc#4105]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 7.3 Release 2
So I had 7.2.5 installed and working... then I had 7.3 installed and working... then I tried to upgrade to Release 2... 
the install didn't work
I tried to uninstall
Remove Program showed that it was uninstalled
However, File Explorer showed the program STILL on my computer with two folders, one for 7.3 and one for 7.2.5
I successfully deleted the 7.2.5 folder however the 7.3 folder refuses to be deleted... 
I tried to overinstall 7.3 but it errors out with a "file already exists"... but the program refuses to operate and keeps asking for the administrator... I bought this computer brand new from Dell weeks ago... there is no administrator other than me...  and I am not smart enough to know how to move forward from here... please assist on the following:
how do I get this program off my computer.... why is it demanding the administrator?
v/r
Ken Westlund

**Comment by scamille** [comment]
If you installed to eg. C:\Program Files\ and gave the SimC installer elevated administration privileges during installation, you usually also need admin rights to remove a folder from C:\Program Files\.
