### ISSUE TITLE
Simcraft APL question - help with a lua code?

### ISSUE THREAD

**Issue by sanavina** [simulationcraft/simc#4111]
Simulationcraft Version: 730-02

Hello, 

First I would like to thank you for responding to my other questions. I appreciate that very much. There is another issue that has been bugging me. 

Here the APL lists:

void_torrent,if=dot.shadow_word_pain.remains>5.5&dot.vampiric_touch.remains>5.5&(!talent.surrender_to_madness.enabled|(talent.surrender_to_madness.enabled&target.time_to_die>variable.s2mcheck-(**buff.insanity_drain_stacks.value**)+60))

shadow_word_void,if=talent.shadow_word_void.enabled&(insanity-(**current_insanity_drain***gcd.max)+25)<100

I understand what the condition is. How do you track the insanity drain stacks? I've been trying to come up with a custom code for weakauras using lua but I am having trouble tracking down the exact stack as well as the rate at which it drains.

Also, the gcd.max is the player's max hasted gcd or the game's max gcd (1.5)?

Thank you for any help you can provide.

**Comment by N1gh7h4wk** [comment]
gcd.max is the gcd duration that would occur when a player triggers it in that exact moment.

insanity drain stacks basically increment per second in voidform.
You cannot track insanity drain stacks, they are occurring behind the scenes.
Twintops Insanity bar weakaura tracks it with a increment loop (that needs freeze conditions tho for torrent/dispersion)

**Comment by sanavina** [comment]
Ah ok. It would be great if we were able to track those stacks.

I'll check out that weakaura. If the weakaura does it based on a loop, then
there must exist a code that can be used in a custom trigger

The way you mention gcd.max seems like it's the same as gcd? I'm a little
confused still. Is gcd just the measure of your current gcd based on
outside haste affects while gcd.max is the lowest gcd that the player can
attain?

In my case, I believe gcd.max would be 0.75 since I'm able to get over 100%
haste. I believe my cap as shadow is 0.75.

Thanks for your help

**Comment by N1gh7h4wk** [comment]
gcd.max is not the cap, just the duration of the gcd if it would occur in that moment. The other way you could check on a gcd is how long your current gcd is remaining.

**Comment by N1gh7h4wk** [comment]
example on that would be like 
at 50 VF stacks and no base haste:
50% haste means your GCD is exactly 1 second, gcd.max returns 1
at 50.5 stacks you use an ability on gcd,
as soon as you hit 51 stacks your current gcd still remains at 0.5 seconds, gcd.max returns  0.9934 [1.5/(1+51/100)]

**Comment by N1gh7h4wk** [comment]
With the expression gcd.max you can basically estimate how many casts you can get off within a certain timeframe (if haste does not change too much) basically by doing time/gcd.max = number of possible casts

**Comment by sanavina** [comment]
Thank you very much for the explanation. Much appreciated!
