### ISSUE TITLE
BM hunter Dire Beast usage

### ISSUE THREAD

**Issue by varonel** [simulationcraft/simc#4113]
https://github.com/simulationcraft/simc/blob/983fb604c0caf0df7e7dac9536c472bbc712e740/engine/class_modules/sc_hunter.cpp#L6399

This will just return true if you're not using the legendary which means it will just ignore all other conditions and just use it on CD. Does not seem to be the desired effect.
Probably needs to be changed to:
`if=(equipped.qapla_eredun_war_order &cooldown.kill_command.remains>=1)|full_recharge_time<gcd.max|cooldown.titans_thunder.up|spell_targets>1`

**Comment by varonel** [comment]
Also, same line, same conditions: `cooldown.titans_thunder.up` if you're using this as condition, but for Titan's Thunder, condition is `buff.bestial_wrath.up`. This means, while titan's thunder is off cd, but bestial wrath is not on, it will just cast Dire Beast on CD.

**Comment by N1gh7h4wk** [comment]
Has this been resolved with the latest changes to bm?

**Comment by Jayezi** [comment]
The intent of that original logic is correct, the proposed change tanks the dps by 100k.

**Comment by varonel** [comment]
My point was that the other conditions will never be checked if you're not using the legendary. 
If the dps drops, then it could be that it is just better for the rotation to use Dire Beast there on CD, when not using that legendary.

**Comment by Snitzel** [comment]
as you've noted, casting DB on cooldown without boots is correct, which is what it's doing now. I'm not sure I see a flaw in this logic at all

**Comment by N1gh7h4wk** [comment]
so the line is perfectly fine, since its either having the legendary and checking for conditions, or not having the legendary and doing what it should?
