### ISSUE TITLE
make: No rule to make target `/Users/xxxx/simcdev/simc/profiles/Tier19H'

### ISSUE THREAD

**Issue by penguinlust** [simulationcraft/simc#4120]
The current sources won't make under Mac OS. Some change in the last couple of days made the project unbuildable.

My last successful build was on 2 November 2017

#### Simulationcraft Version
730-3

#### simc_gui.simc file or contents
NA

#### Reproduction Steps:

from the terminal:
% git pull origin
% make

make: *** No rule to make target `/Users/xxxx/simcdev/simc/profiles/Tier19H', needed by `SimulationCraft.app/Contents/Resources/profiles/Tier19H'.  Stop.

**Comment by aethys256** [comment]
Will look into today.

**Comment by navv1234** [comment]
Should be fixed now.

**Comment by penguinlust** [comment]
Looks like it just shifted the error -- I now get:

% make
make: *** No rule to make target `profiles/Tier19P', needed by `SimulationCraft.app/Contents/Resources/profiles/Tier19P'.  Stop.

But reading the makefile the rule is there. So debugging....

**Comment by navv1234** [comment]
Oh right, you are using simcqt.pro I guess. Fixing that too.

**Comment by penguinlust** [comment]
Yup, that was it apparently. Built. Thanks.
