### ISSUE TITLE
Monk Windwalker Touch Of the Death incorrect damage

### ISSUE THREAD

**Issue by xFnii** [simulationcraft/simc#4124]
This start to happen only with simc 8fba8bf.
Touch of Death damage decreased 3.6 times.
For example 
BEFORE 
https://www.raidbots.com/reports/o6HFmjGb8H4Ncqmfvm9rLC/index.html (5.5m per exec)
AFTER 
https://www.raidbots.com/reports/g4npLTtGW9RhrHtxKWdmwn/index.html (1.5m per exec)
All similar except version of SIMC

**Comment by vituscze** [comment]
Should be fixed in aac7ae664fd7c803e02387d5730228ef0639edbd
