### ISSUE TITLE
Enh Shaman's missing on the T21 results

### ISSUE THREAD

**Issue by Dysterkvist** [simulationcraft/simc#4131]
Does this has the same reason as the last issue I wrote? That the under performing build in a spec wont make it on the list?
The raid result I'm talking about is the "Legion Tier 21 960 ilevel patchwerk-style (w/Legendaries)

**Comment by N1gh7h4wk** [comment]
There was no Profile pushed into the Repo until yesterday. The next time the nightly is updated and the tests are rerun, it will appear on the site. SimC lives from contributions from the community, unless someone contributes a profile/apl changes etc. there won't be changes at all.
