### ISSUE TITLE
Missing Spell Data v730-02

### ISSUE THREAD

**Issue by nekromancin** [simulationcraft/simc#4144]
When trying to simulate my Shadow Priest I get the following error:

> Player Nekromancin could not find spell data for action **mind_sear_tick**
Simulation has been canceled after 1 iterations! (thread=0)                     

I use the desktop client alongside the addon; Both have been updated; SimC v730-02, addon v1.8.4. The following is what is exported from the addon https://pastebin.com/TJyUXfcv

It seems to be solely a SPriest issue as I don't get any errors when simulating other classes (Feral/Balance Druid, Affliction/Destruction Warlock, Arcane Mage).

**Comment by N1gh7h4wk** [comment]
I think if you use the nightly build this should not happen, might be an issue with the release canditate you are using.

**Comment by N1gh7h4wk** [comment]
Oh ya its not an issue of your simc, its an issue of your toon being level 21. Spell data for that spell does not seem to exist at that level, so the sim crashes.
Simc does not support low level for many classes, if you want to change that, feel free to contribute by making pull requests with your proposed code changes.

**Comment by N1gh7h4wk** [comment]
apparently it works on the current git build, so probably also on the current nightly, just no guarantees for the actual sim results at that level.
