### ISSUE TITLE
Importing from Simc causes error upon hitting simulate!

### ISSUE THREAD

**Issue by Dudeliduu** [simulationcraft/simc#4145]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-01

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - 
Not crashing, just an error

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor
statistics_level=1
### Begin simulateText ###
druid="Talvarah"
level=110
race=night_elf
region=eu
server=ravencrest
role=tank
professions=alchemy=4/herbalism=193
talents=2113321
spec=guardian
artifact=57:0:0:0:0:948:4:949:4:950:4:951:4:952:4:953:4:954:4:955:4:956:4:957:1:958:1:959:1:960:1:961:1:962:1:979:1:1334:1:1366:1:1509:4:1510:1:1511:1:1512:25:1634:1
crucible=1739:1782:949/1739:1775:950/1739:1784:1509

head=,id=133618,gem_id=151584,bonus_id=3418/1808/1587/3337
neck=,id=134488,enchant_id=5889,bonus_id=3418/1587/3337
shoulder=,id=151319,bonus_id=3418/1597/3337
back=,id=147134,enchant_id=5435,bonus_id=3562/1512/3337
chest=,id=147028,bonus_id=3562/1527/3337
wrist=,id=152365,bonus_id=3614/1487/3337
hands=,id=147135,bonus_id=3562/1517/3337
waist=,id=147347,gem_id=151585,bonus_id=3562/1808/1517/3336
legs=,id=137067,bonus_id=1811/3570
feet=,id=147030,bonus_id=3562/1512/3337
finger1=,id=151636,enchant_id=5427,gem_id=130222,bonus_id=1811/3570
finger2=,id=147020,enchant_id=5430,bonus_id=3563/1512/3528
trinket1=,id=133642,bonus_id=3536/1582/3337
trinket2=,id=147025,bonus_id=3563/1512/3528
main_hand=,id=128821,gem_id=137316/142180/136973,bonus_id=724,relic_id=3418:1602:3337/3418:1552:3337/3418:1587:3337
off_hand=,id=128822

### Gear from Bags
#
# The Emerald Dreamcatcher (970)
# head=,id=137062,bonus_id=1811/3570
#
# Behemoth Headdress (970)
# head=,id=151801,bonus_id=3459/3570
#
# Stormheart Headdress (930)
# head=,id=147136,bonus_id=3563/41/1512/3528
#
# Lady and the Child (970)
# shoulder=,id=144295,bonus_id=1811/3570
#
# Twilight's Edge Spaulders (885)
# shoulder=,id=151319,bonus_id=1727/40/1537/3528
#
# Fury of Nature (970)
# back=,id=151802,bonus_id=1811/3570
#
# Drape of Shame (930)
# back=,id=142170,enchant_id=5435,bonus_id=3536/1547/3337
#
# Ekowraith, Creator of Worlds (970)
# chest=,id=137015,bonus_id=1811/3570
#
# Ruined Krokul Wristguards (380)
# wrist=,id=153079
#
# Luffa Wrappings (970)
# wrist=,id=137056,bonus_id=3529/3459/3570
#
# The Wildshaper's Clutch (970)
# hands=,id=137094,bonus_id=1811/3570
#
# The Dark Titan's Advice (970)
# waist=,id=137078,bonus_id=3459/3570
#
# Fierce Combatant's Dragonhide Legguards (930)
# legs=,id=149569,bonus_id=3573/1708/1592/3337
#
# Glacier Walkers (935)
# feet=,id=147029,bonus_id=3563/1517/3336
#
# Tearstone of Elune (970)
# finger1=,id=137042,enchant_id=5429,gem_id=151584,bonus_id=1811/3570
#
# Yathae's Thumb Ring (935)
# finger1=,id=147021,enchant_id=5430,bonus_id=3563/1517/3336
#
# Dual Determination (970)
# finger1=,id=137041,enchant_id=5430,gem_id=151585,bonus_id=3459/3570
#
# Chatoyant Signet (970)
# finger1=,id=137040,enchant_id=5429,gem_id=151584,bonus_id=3459/3570
#
# Tome of Unraveling Sanity (925)
# trinket1=,id=147019,bonus_id=3562/1507/3528
#
# Feverish Carapace (930)
# trinket1=,id=147022,bonus_id=3563/1512/3528
#
# Void Stalker's Contract (865)
# trinket1=,id=151307,bonus_id=1726/1517/3528
#
# Whispers in the Dark (895)
# trinket1=,id=140809,bonus_id=3517/1492/3528
#
# Amalgam's Seventh Spine (900)
# trinket1=,id=136714,bonus_id=3573/1552/3337
#
# Shifting Cosmic Sliver (925)
# trinket1=,id=147026,bonus_id=3562/1507/3528
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

####Error message text from Simcraft
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Nothing to sim!
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Talvarah invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Talvarah"
level=110
race=night_elf
region=eu
server=ravencrest
role=tank
professions=alchemy=4/herbalism=193
talents=2113321
spec=guardian
artifact=57:0:0:0:0:948:4:949:4:950:4:951:4:952:4:953:4:954:4:955:4:956:4:957:1:958:1:959:1:960:1:961:1:962:1:979:1:1334:1:1366:1:1509:4:1510:1:1511:1:1512:25:1634:1
crucible=1739:1782:949/1739:1775:950/1739:1784:1509

head=,id=133618,gem_id=151584,bonus_id=3418/1808/1587/3337
neck=,id=134488,enchant_id=5889,bonus_id=3418/1587/3337
shoulder=,id=151319,bonus_id=3418/1597/3337
back=,id=147134,enchant_id=5435,bonus_id=3562/1512/3337
chest=,id=147028,bonus_id=3562/1527/3337
wrist=,id=152365,bonus_id=3614/1487/3337
hands=,id=147135,bonus_id=3562/1517/3337
waist=,id=147347,gem_id=151585,bonus_id=3562/1808/1517/3336
legs=,id=137067,bonus_id=1811/3570
feet=,id=147030,bonus_id=3562/1512/3337
finger1=,id=151636,enchant_id=5427,gem_id=130222,bonus_id=1811/3570
finger2=,id=147020,enchant_id=5430,bonus_id=3563/1512/3528
trinket1=,id=133642,bonus_id=3536/1582/3337
trinket2=,id=147025,bonus_id=3563/1512/3528
main_hand=,id=128821,gem_id=137316/142180/136973,bonus_id=724,relic_id=3418:1602:3337/3418:1552:3337/3418:1587:3337
off_hand=,id=128822

### Gear from Bags
#
# The Emerald Dreamcatcher (970)
# head=,id=137062,bonus_id=1811/3570
#
# Behemoth Headdress (970)
# head=,id=151801,bonus_id=3459/3570
#
# Stormheart Headdress (930)
# head=,id=147136,bonus_id=3563/41/1512/3528
#
# Lady and the Child (970)
# shoulder=,id=144295,bonus_id=1811/3570
#
# Twilight's Edge Spaulders (885)
# shoulder=,id=151319,bonus_id=1727/40/1537/3528
#
# Fury of Nature (970)
# back=,id=151802,bonus_id=1811/3570
#
# Drape of Shame (930)
# back=,id=142170,enchant_id=5435,bonus_id=3536/1547/3337
#
# Ekowraith, Creator of Worlds (970)
# chest=,id=137015,bonus_id=1811/3570
#
# Ruined Krokul Wristguards (380)
# wrist=,id=153079
#
# Luffa Wrappings (970)
# wrist=,id=137056,bonus_id=3529/3459/3570
#
# The Wildshaper's Clutch (970)
# hands=,id=137094,bonus_id=1811/3570
#
# The Dark Titan's Advice (970)
# waist=,id=137078,bonus_id=3459/3570
#
# Fierce Combatant's Dragonhide Legguards (930)
# legs=,id=149569,bonus_id=3573/1708/1592/3337
#
# Glacier Walkers (935)
# feet=,id=147029,bonus_id=3563/1517/3336
#
# Tearstone of Elune (970)
# finger1=,id=137042,enchant_id=5429,gem_id=151584,bonus_id=1811/3570
#
# Yathae's Thumb Ring (935)
# finger1=,id=147021,enchant_id=5430,bonus_id=3563/1517/3336
#
# Dual Determination (970)
# finger1=,id=137041,enchant_id=5430,gem_id=151585,bonus_id=3459/3570
#
# Chatoyant Signet (970)
# finger1=,id=137040,enchant_id=5429,gem_id=151584,bonus_id=3459/3570
#
# Tome of Unraveling Sanity (925)
# trinket1=,id=147019,bonus_id=3562/1507/3528
#
# Feverish Carapace (930)
# trinket1=,id=147022,bonus_id=3563/1512/3528
#
# Void Stalker's Contract (865)
# trinket1=,id=151307,bonus_id=1726/1517/3528
#
# Whispers in the Dark (895)
# trinket1=,id=140809,bonus_id=3517/1492/3528
#
# Amalgam's Seventh Spine (900)
# trinket1=,id=136714,bonus_id=3573/1552/3337
#
# Shifting Cosmic Sliver (925)
# trinket1=,id=147026,bonus_id=3562/1507/3528
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

#### Reproduction Steps:

Nothing special is done, copied text from simc addon, pasted it into import - Simc Addon Tab and pressed import and when I then press simulate, I get this error.

**Comment by N1gh7h4wk** [comment]
Seems like either your version of simc or the addon is out of date?

**Comment by Melekus** [comment]
Indeed, make sure you're using the latest nightly version. If I remember correctly the crucible wasn't properly implemented (or at least not in this format) in the 730-01 version
