### ISSUE TITLE
Night Elf Racial Passive

### ISSUE THREAD

**Issue by DrJest** [simulationcraft/simc#4147]
Hello, 
in a previous report here it was said that the default simulationcraft behaviour (giving +1% crit to night elves) is to be considered correct because "the instances are set to day time".
I've been tracking my stats and the buff "Touch of Elune" for a while, and i can state that for me (and for all the other elves in my timezone, i suppose) the raid hours are mostly during night time, and the buff i receive is 1% haste. I'd like to put this setting in the simulation. Is there a setting to change to simulate for +1% haste instead? 
Thanks

(Every simcraft release is affected by this)

**Comment by vituscze** [comment]
You can change that with `timeofday=night` or `timeofday=day`.
