### ISSUE TITLE
Golganneth's Vitality trinket not splitting AoE damage

### ISSUE THREAD

**Issue by bendakwow** [simulationcraft/simc#4153]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

730-03 (nightly build on raidbots)

#### Reproduction Steps:

The Golgenneth's Vitality (154174) trinket's proc spawns a "Ravaging Storm" that deals damage within 6 yards. This damage is split so it does not increase multi-target DPS. 

In simulations the damage of Ravaging Storm is multiplying with the number of targets instead of splitting, leading to an inflated value on multi-target sims.

**Comment by vituscze** [comment]
Should be fixed in 27f64ee1122359224c1f541309bdcca8fb7c959d
