### ISSUE TITLE
Monk Windwalker Simulation canceled

### ISSUE THREAD

**Issue by Bloodmallet** [simulationcraft/simc#4158]
#### Simulationcraft Version da50aeb29d378f4fa7e5f11f03a91b6780575adf

CLI used. Minimalistic input is: 
`.\simc.exe T21_Monk_Windwalker.simc optimize_expressions=1 default_actions=1 html=monk_test.html trinket2=,id=151963,ilevel=980`

The combination of optimize_expressions, default_actions and this trinket make the simulation crash.

Error: `Reference to unknown buff/debuff touch_of_death by player T21_Monk_Windwalker
Simulation has been canceled after 1 iterations! (thread=0)`

**Comment by scamille** [comment]
Seems to be fixed ;)
