### ISSUE TITLE
display bug when the prodigious weapon is equipped wow addon

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#4161]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
equip yourself with your prodigious weapon then made / simc

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by ghost** [comment]
when the prodigious weapon is equipped and the smic executing a window with the information does not open it is necessary to equip the weapon so that it works but suddenly no information on the prodigious weapon

**Comment by N1gh7h4wk** [comment]
did you try updating the simC addon and your simulationcraft version? the current version is 7.3.2.
Which specc did you have problems with?

**Comment by ghost** [comment]
I am currently on a private server that runs under the version 7.1.5 I posse however the last version of simC the problem would come from the?

**Comment by N1gh7h4wk** [comment]
That is not supported by the SimC addon at all, so its very likely not supporting the servers data format/version.

**Comment by ghost** [comment]
So there is no hope?

**Comment by N1gh7h4wk** [comment]
the only thing that could work is a 7.1.5 version of the simc addon and a 7.1.5 simc version, but no guarantees.

**Comment by ghost** [comment]
anyway there is no version 7.1.5 of the addon thank you in any case for your help it was very useful
