### ISSUE TITLE
Bonus ID 3622 Weirdness (Player Scaling World Boss Items)

### ISSUE THREAD

**Issue by seriallos** [simulationcraft/simc#4170]
#### Simulationcraft Version

d3a74cd73

#### simc_gui.simc file or contents

```
# Sapphire-Encrusted Tunic 915
chest=",id=150543,bonus_id=3621/3622,drop_level=110"
```

#### Reproduction Steps:

This item is 915 in-game but SImC seems to be parsing it at 900:

![image](https://user-images.githubusercontent.com/1010294/33342919-7bf3f798-d438-11e7-95f4-28b8886d21b6.png)

![image](https://user-images.githubusercontent.com/1010294/33342943-8ea5571a-d438-11e7-9894-f3a7e88a2b31.png)

The Bonus ID data from `show_bonus_ids=1` also appears strange: (note the plvl 0) 

```
bonus_id={ 3622 }, desc={ Warforged }, ilevel={ 10 @plvl 1 - 10 @plvl 0 }
```

WowDB appears to have the same issue (wowDB tooltip shows 900) for this bonus ID. Also seems like wowhead has an issue with this item as well:

http://www.wowdb.com/items/150543-sapphire-encrusted-tunic?bonusIDs=3621,3622

https://www.wowhead.com/item=150543/sapphire-encrusted-tunic&bonus=3621:3622

Is this an error in the client data or some weird new scaling behavior?

**Comment by navv1234** [comment]
Pretty sure this has been fixed, if I recall correctly it was a bogus curve data from blizzard.
