### ISSUE TITLE
SimulationCraft encountered an error

### ISSUE THREAD

**Issue by Konsolka** [simulationcraft/simc#4171]
#### Simulationcraft log:  https://pastebin.com/KQrJeuF2

No code for Error????

**Comment by Melekus** [comment]
Holy paladin healer simulations are not supported at the moment.
If you want an in-depth look at your character's abilities, I suggest you take a look at the spreadsheet tools you can find in the paladin class discord server ( discord.gg/hammerofwrath )

Dps holy paladin ("shockadin") simulations are supported if you change your input from role=heal to role=dps.
