### ISSUE TITLE
engine/sim/sc_profileset.cpp:425:14: error: no matching member function for call       to 'output_data'

### ISSUE THREAD

**Issue by penguinlust** [simulationcraft/simc#4172]
Commit 02e9bb0a44621da2e009ed49aaae13fbe31955b0 broke the build under clang (clang-802.0.35)

#### Simulationcraft Version
Current (730-03)

#### simc_gui.simc file or contents
NA

#### Reproduction Steps:
On OS X 10.12.6:

% git pull origin
% make

/Users/xxxx/Qt/5.7/clang_64/bin/qmake -o Makefile simcqt.pro
Project MESSAGE: Using WebEngine
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wno-inconsistent-missing-override -ffast-math -Woverloaded-virtual -DNDEBUG -O3 -fomit-frame-pointer -flto -Os -std=gnu++11 -Wall -W -fPIC -DSC_USE_WEBENGINE -DQT_VERSION_5 -DSIMC_NO_AUTOUPDATE -DSC_TO_INSTALL -DQT_NO_DEBUG -DQT_WEBENGINE_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -Iengine -I../../Qt/5.7/clang_64/lib/QtWebEngine.framework/Headers -I../../Qt/5.7/clang_64/lib/QtWebEngineWidgets.framework/Headers -I../../Qt/5.7/clang_64/lib/QtWebEngineCore.framework/Headers -I../../Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.7/clang_64/lib/QtWebChannel.framework/Headers -I../../Qt/5.7/clang_64/lib/QtQml.framework/Headers -I../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../Qt/5.7/clang_64/lib/QtPositioning.framework/Headers -I../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/xxxx/Qt/5.7/clang_64/lib -o qt/sc_profileset.o engine/sim/sc_profileset.cpp
engine/sim/sc_profileset.cpp:425:14: error: no matching member function for call
      to 'output_data'
      set -> output_data ( profile_output_data_t() );
      ~~~~~~~^~~~~~~~~~~
engine/sim/sc_profileset.hpp:255:18: note: candidate function not viable:
      expects an l-value for 1st argument
  profile_set_t& output_data( profile_output_data_t& v )
                 ^
engine/sim/sc_profileset.hpp:252:26: note: candidate function not viable:
      requires 0 arguments, but 1 was provided
  profile_output_data_t& output_data()
                         ^
1 error generated.
make: *** [qt/sc_profileset.o] Error 1

**Comment by penguinlust** [comment]
A clean build didn't solve it.

**Comment by vituscze** [comment]
Should be fine now, closing.

**Comment by aethys256** [comment]
Yes, was my bad :P

**Comment by penguinlust** [comment]
Looks good on my end. Thanks.
