### ISSUE TITLE
SimCraft has encountered an error

### ISSUE THREAD

**Issue by MrNargleFargle** [simulationcraft/simc#4173]
Whenever I go to import my stats or whatever using the addon I get an error and it tells me to open a ticked giving the info below

#### simc_gui.simc file or contents
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Smoldin invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Smoldin invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Smoldin invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Smoldin invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Smoldin invalid crucible format, expected: power_id:rank[:power_id:rank...]
 
## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=25000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,int,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
shaman="Smoldin"
level=110
race=dwarf
region=us
server=proudmoore
role=attack
professions=enchanting=80/
talents=3212111
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:4:906:4:907:4:908:4:909:4:910:4:911:4:912:4:913:4:930:1:1351:1:1388:1:1593:4:1594:1:1595:1:1596:11:1687:1
crucible=0/0/0
 
head=,id=134343,bonus_id=1825/1537/3528
neck=,id=147013,bonus_id=3564/1467/3528
shoulder=,id=139121,bonus_id=1824/1532/3528
back=,id=140910,enchant_id=5432,bonus_id=3516/1492/3336
chest=,id=137616,bonus_id=3529/3530/1811
wrist=,id=140874,bonus_id=3514/1487/3337
hands=,id=146870,bonus_id=3394/1542/3528
waist=,id=139077,bonus_id=3394/1542/3528
legs=,id=140871,bonus_id=3443/1467/1813
feet=,id=134166,bonus_id=1825/1808/1537/3528
finger1=,id=147020,bonus_id=3564/1472/3336
finger2=,id=137050,enchant_id=5428,gem_id=130220,bonus_id=1811/3455
trinket1=,id=140794,bonus_id=3443/1482/3337
trinket2=,id=133644,bonus_id=3411/1512/3337
main_hand=,id=128819,gem_id=139256/139261/137550,bonus_id=745,relic_id=1807:1502:3337/1805:1507:3337/3413:1517:3337
off_hand=,id=128873
 
### Gear from Bags
#
# Architect's Coif of Despair (875)
# head=,id=140870,bonus_id=3514/1472/1813
#
# Helm of the Betrayed (840)
# head=,id=121745
#
# Soultrapper's Pendant (865)
# neck=,id=141506,bonus_id=3466/1477/3336
#
# Zealous Timestone Pendant (870)
# neck=,id=140894,enchant_id=5439,bonus_id=3443/1467/1813
#
# Pauldrons of Warped Memory (855)
# shoulder=,id=140872,bonus_id=3446/1808/1452
#
# Drape of the Skybreaker (885)
# back=,id=147176,bonus_id=3564/1467/3528
#
# Hauberk of the Snarled Vale (875)
# chest=,id=141491,bonus_id=3466/1487/3337
#
# Gauntlets of Innumerable Barbs (860)
# hands=,id=137348,bonus_id=3416/1512/1813
#
# Emblazoned Duskwatch Belt (875)
# waist=,id=140868,bonus_id=3514/1472/1813
#
# Mardum Chain Boots (885)
# feet=,id=134386,bonus_id=1825/1547/3336
#
# Spiritual Journey (940)
# feet=,id=138117,bonus_id=1811/3455
#
# Mardum Chain Boots (875)
# feet=,id=134386,bonus_id=3417/1808/41/1537/3337
#
# Ring of Braided Stems (875)
# finger1=,id=140896,enchant_id=5425,bonus_id=3514/1472/1813
#
# Mindrend Band (860)
# finger1=,id=138220,enchant_id=5425,gem_id=130220,bonus_id=1807/1808/1482/3336
#
# Giant Ornamental Pearl (870)
# trinket1=,id=137369,bonus_id=3416/1522/3336
#
# Bloodthirsty Instinct (850)
# trinket1=,id=139329,bonus_id=1807/1472
#
# Huge Roggstone (855)
# trinket1=,id=134160,bonus_id=3474/604/1517/3336
#
# Spontaneous Appendages (850)
# trinket1=,id=139325,bonus_id=1807/1472
#
# Nightborne Researcher's Phial (850)
# trinket1=,id=134292,bonus_id=3474/607/1512/3336
#
 
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.
 
### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

#### Reproduction Steps: Idk why but entering my character into the import seems to work lol
shaman="Smoldin"
level=110
race=dwarf
region=us
server=proudmoore
role=attack
professions=enchanting=80/
talents=3212111
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:4:906:4:907:4:908:4:909:4:910:4:911:4:912:4:913:4:930:1:1351:1:1388:1:1593:4:1594:1:1595:1:1596:11:1687:1
crucible=0/0/0

head=,id=134343,bonus_id=1825/1537/3528
neck=,id=147013,bonus_id=3564/1467/3528
shoulder=,id=139121,bonus_id=1824/1532/3528
back=,id=140910,enchant_id=5432,bonus_id=3516/1492/3336
chest=,id=137616,bonus_id=3529/3530/1811
wrist=,id=140874,bonus_id=3514/1487/3337
hands=,id=146870,bonus_id=3394/1542/3528
waist=,id=139077,bonus_id=3394/1542/3528
legs=,id=140871,bonus_id=3443/1467/1813
feet=,id=134166,bonus_id=1825/1808/1537/3528
finger1=,id=147020,bonus_id=3564/1472/3336
finger2=,id=137050,enchant_id=5428,gem_id=130220,bonus_id=1811/3455
trinket1=,id=140794,bonus_id=3443/1482/3337
trinket2=,id=133644,bonus_id=3411/1512/3337
main_hand=,id=128819,gem_id=139256/139261/137550,bonus_id=745,relic_id=1807:1502:3337/1805:1507:3337/3413:1517:3337
off_hand=,id=128873

### Gear from Bags
#
# Architect's Coif of Despair (875)
# head=,id=140870,bonus_id=3514/1472/1813
#
# Helm of the Betrayed (840)
# head=,id=121745
#
# Soultrapper's Pendant (865)
# neck=,id=141506,bonus_id=3466/1477/3336
#
# Zealous Timestone Pendant (870)
# neck=,id=140894,enchant_id=5439,bonus_id=3443/1467/1813
#
# Pauldrons of Warped Memory (855)
# shoulder=,id=140872,bonus_id=3446/1808/1452
#
# Drape of the Skybreaker (885)
# back=,id=147176,bonus_id=3564/1467/3528
#
# Hauberk of the Snarled Vale (875)
# chest=,id=141491,bonus_id=3466/1487/3337
#
# Gauntlets of Innumerable Barbs (860)
# hands=,id=137348,bonus_id=3416/1512/1813
#
# Emblazoned Duskwatch Belt (875)
# waist=,id=140868,bonus_id=3514/1472/1813
#
# Mardum Chain Boots (885)
# feet=,id=134386,bonus_id=1825/1547/3336
#
# Spiritual Journey (940)
# feet=,id=138117,bonus_id=1811/3455
#
# Mardum Chain Boots (875)
# feet=,id=134386,bonus_id=3417/1808/41/1537/3337
#
# Ring of Braided Stems (875)
# finger1=,id=140896,enchant_id=5425,bonus_id=3514/1472/1813
#
# Mindrend Band (860)
# finger1=,id=138220,enchant_id=5425,gem_id=130220,bonus_id=1807/1808/1482/3336
#
# Giant Ornamental Pearl (870)
# trinket1=,id=137369,bonus_id=3416/1522/3336
#
# Bloodthirsty Instinct (850)
# trinket1=,id=139329,bonus_id=1807/1472
#
# Huge Roggstone (855)
# trinket1=,id=134160,bonus_id=3474/604/1517/3336
#
# Spontaneous Appendages (850)
# trinket1=,id=139325,bonus_id=1807/1472
#
# Nightborne Researcher's Phial (850)
# trinket1=,id=134292,bonus_id=3474/607/1512/3336
#

**Comment by vituscze** [comment]
Update your simc. This new format was added about two months ago.
