### ISSUE TITLE
Will not let me change to certain tabs when i did change to simulate it was frozen.

### ISSUE THREAD

**Issue by Tylup** [simulationcraft/simc#4174]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by N1gh7h4wk** [comment]
I'd highly recommend to swap to a 7.3.2 version of SimC

**Comment by Tylup** [comment]
Still didnt work for me same thing happened...

**Comment by Sophie2712** [comment]
Same thing is happening to me, fresh, brand new first time install 5 minutes ago. I have found that I can only change tabs if I go back to the welcome tab each time. So, options->welcome->simulate->welcome

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly
