### ISSUE TITLE
Documentation Request: Crucible Weight Strings with Simulationcraft

### ISSUE THREAD

**Issue by btcll** [simulationcraft/simc#4177]
Apologies if this isn't the correct place. I'm seeking documentation regarding how I can generate a Crucible Weight string for use with the CrucibleWeight addon. In the recent Release Notes for 730-02 it says, "Support the new Simulationcraft addon crucible option format". Does this mean my Simcraft report now contains weighting for the best crucible trait choices?

What I would like documentation for is how I can go from running a simulation of my character to being able to import the crucible trait stat weights into the CrucibleWeight addon. I searched the documentation and website for information about this but I wasn't able to find anything. If the documentation exists I would really appreciate a link. 

Release Notes that mention this: http://www.simulationcraft.org/2017/09/14/release-730-02.html

CrucibleWeight Addon: https://www.curseforge.com/wow/addons/crucibleweight

**Comment by N1gh7h4wk** [comment]
The Release Notes refer to the crucible= string from the Simulationcraft Addon, that lets your import your crucible into Simulationcraft. There is no option to generate a crucibleweight addon string in the Simulatoncraft output.

**Comment by btcll** [comment]
Thank you so much for your reply @N1gh7h4wk . I'll mark this issue closed and keep an eye on the patch notes. Hopefully this can be added at some point.
