### ISSUE TITLE
Incorrect Importing of Weapon / Relic Info

### ISSUE THREAD

**Issue by ready3** [simulationcraft/simc#4189]
Please include a brief overview of the issue in the title above, as well as completing the following:
The Titanstrike weapon with the upgraded relics shows an iLevel of 970 in game and also in Armory. Character is Thanraptor, specification is Beastmaster, realm Mug'Thol.  In Simulationcraft the weapon shows as an iLevel of 955. My relics are not maxed out because I have not gotten to level 75 of Concordance (currently at 71), but all have the +5 iLevel bump.

Simulationcraft Version: 730-02-Win64

simc_gui.simc file or contents
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0.05
iterations=0
default_world_lag=0.1
max_time=500
vary_combat_length=0.2
fight_style=LightMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=2
### Begin simulateText ###
hunter="Thanraptor"
origin="https://us.api.battle.net/wow/character/mugthol/thanraptor/advanced"
thumbnail="https://render-us.worldofwarcraft.com/character/mugthol/66/131882562-avatar.jpg"
spec=beast_mastery
level=110
race=tauren
role=attack
position=ranged_back
professions=engineering=742/mining=180
talents=https://worldofwarcraft.com/en-us/game/talent-calculator#hunter/beast_mastery/talents=2131312
artifact=56:0:0:0:0:868:4:869:5:870:4:871:4:872:3:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1520:20:1636:1

# Default consumables
potion=prolonged_power
flask=seventh_demon
food=lavish_suramar_feast
augmentation=defiled

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/augmentation
actions.precombat+=/food
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion

# Executed every time the actor is available.
actions=auto_shot
actions+=/counter_shot,if=target.debuff.casting.react
actions+=/use_items
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/berserking,if=buff.bestial_wrath.remains>7
actions+=/blood_fury,if=buff.bestial_wrath.remains>7
actions+=/volley,toggle=on
actions+=/potion,if=buff.bestial_wrath.up&buff.aspect_of_the_wild.up
actions+=/a_murder_of_crows,if=cooldown.bestial_wrath.remains<3|cooldown.bestial_wrath.remains>30|target.time_to_die<16
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/bestial_wrath,if=!buff.bestial_wrath.up
# With both AotW cdr sources and OwtP, there's no visible benefit if it's delayed, use it on cd. With only one or neither, pair it with Bestial Wrath. Also use it if the fight will end when the buff does.
actions+=/aspect_of_the_wild,if=(equipped.call_of_the_wild&equipped.convergence_of_fates&talent.one_with_the_pack.enabled)|buff.bestial_wrath.remains>7|target.time_to_die<12
actions+=/kill_command,target_if=min:bestial_ferocity.remains,if=equipped.qapla_eredun_war_order
# Hold charges of Dire Beast as long as possible to take advantage of T20 2pc unless T19 2pc is on. With Qa'pla, also try not to waste Kill Command cdr if it is just about to come off cooldown.
actions+=/dire_beast,if=((!equipped.qapla_eredun_war_order|cooldown.kill_command.remains>=1)&(set_bonus.tier19_2pc|!buff.bestial_wrath.up))|full_recharge_time<gcd.max|cooldown.titans_thunder.up|spell_targets>1
actions+=/dire_frenzy,if=(pet.cat.buff.dire_frenzy.remains<=gcd.max*1.2)|full_recharge_time<gcd.max|target.time_to_die<9
actions+=/barrage,if=spell_targets.barrage>1
actions+=/titans_thunder,if=(talent.dire_frenzy.enabled&(buff.bestial_wrath.up|cooldown.bestial_wrath.remains>35))|buff.bestial_wrath.up
actions+=/multishot,if=spell_targets>4&(pet.cat.buff.beast_cleave.remains<gcd.max|pet.cat.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multishot,if=spell_targets>1&(pet.cat.buff.beast_cleave.remains<gcd.max|pet.cat.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=(cooldown.kill_command.remains>focus.time_to_max&cooldown.bestial_wrath.remains>focus.time_to_max)|(buff.bestial_wrath.up&(spell_targets.multishot=1|focus.regen*cooldown.kill_command.remains>action.kill_command.cost))|target.time_to_die<cooldown.kill_command.remains|(equipped.parsels_tongue&buff.parsels_tongue.remains<=gcd.max*2)
actions+=/dire_beast,if=buff.bestial_wrath.up

head=wildstalker_helmet,id=147142,bonus_id=3562/1512/3337
neck=collar_of_nullflame,id=151973,bonus_id=3610/1477/3336
shoulders=wildstalker_spaulders,id=147144,bonus_id=3562/43/1512/3337
back=wildstalker_cape,id=147140,bonus_id=3562/1512/3337,enchant=200agi
chest=wildstalker_chestguard,id=147139,bonus_id=3562/1502/3336
wrists=painsinged_armguards,id=147057,bonus_id=3562/1808/1507/3336,gems=150crit
hands=vicegrip_of_the_unrepentant,id=147048,bonus_id=3561/42/1532/3337
waist=worldravager_waistguard,id=152683,bonus_id=3610/1472/3528
legs=roots_of_shaladrassil,id=132466,bonus_id=3459/3630
feet=ley_dragoons_stompers,id=134298,bonus_id=3415/1597/3337
finger1=scaled_band_of_servitude,id=147020,bonus_id=3564/1472/3336
finger2=avenging_band,id=147257,bonus_id=1752/1808/3573/3174/3337,gems=150crit,enchant=200crit
trinket1=kiljaedens_burning_wish,id=144259,bonus_id=1811/3630
trinket2=shadowsinged_fang,id=151968,bonus_id=3613/1457/3528
main_hand=titanstrike,id=128861,bonus_id=726,gem_id=152058/152027/152293/0,relic_id=3610:1477:3336/3610:1472:3528/3610:1482:3336/0

# Gear Summary
# gear_ilvl=938.00
# gear_agility=32364
# gear_stamina=46907
# gear_crit_rating=8918
# gear_haste_rating=7515
# gear_mastery_rating=11681
# gear_versatility_rating=515
# gear_speed_rating=640
# gear_armor=3347
# set_bonus=tier20_2pc=1
# set_bonus=tier20_4pc=1
summon_pet=cat

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Melekus** [comment]
It looks like you're importing from armory. 
The armory API does not contain the crucible data of your character, so you will have to import using the addon if you want your netherlight crucible to be taken into account.
