### ISSUE TITLE
No versatility tab? 

### ISSUE THREAD

**Issue by DonDave11** [simulationcraft/simc#4192]
For some reason, I can't see the versatility tab when I'm on the stats the scale place. Please help.

**Comment by Mystler** [comment]
What exactly do you mean with versatility tab? Did you enable versa scaling in the options?

**Comment by scamille** [comment]
I just checked, there is versatility rating in all 3 scaling option tabs (scaling, plots, reforge plots).

Since there has not been any reply for a while, I'm closing this for now.
