### ISSUE TITLE
Import Failed on just one character

### ISSUE THREAD

**Issue by KittiePanic** [simulationcraft/simc#4193]
I'm able to import and sim my other characters just fine. There is just one that keeps failing to import. I'm unsure how to resolve this. I've logged in and out of my character on wow, opened the profile on battle.net to make sure everything was loaded in. Nothing seems to be helping. 

Version 730-02

Message given:
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from:

**Comment by N1gh7h4wk** [comment]
did you make sure there was an actual profile in the simulation tab? or did you miss a part of the error message.

**Comment by KarboniteKream** [comment]
Which role and spec is your character? I got the same issue on 730-02, but 730-03 tells me that Healers (Holy Priest) are not supported.
