### ISSUE TITLE
Incorrect stats on some items

### ISSUE THREAD

**Issue by sthuro** [simulationcraft/simc#4194]
Some items are using incorrect stats which can be seen on the Results page. The mouseover tooltip from wowdb will show the correct stats while the ones listed under the item name/tooltip are incorrect.

So far I've only noticed this with a few items and only tested on one character/spec which is a Tauren Windwalker Monk.

![stats](https://user-images.githubusercontent.com/30851615/33851125-b76cb61a-df01-11e7-8248-a2eff627556b.png)

This doesn't appear to just be a visual bug, as the 'Gear Amount' column of the 'Stats' section is showing different numbers to the ones in-game (which were check by adding them manually).

The affected items noticed so far:
Vicious Flamepaws: 
feet=,id=151983,bonus_id=3611/1487/3528
Grips of Chi'Ji:
hands=,id=152144,bonus_id=3610/1482/3336

I've noticed it also with another item that I've simmed but don't own, so I can't be certain that it is actually affected (Meditation Spheres of Chi'Ji).

Here is a zip of the simc_gui.simc with unaltered items (taken straight from /simc ingame).
[simc_gui.zip](https://github.com/simulationcraft/simc/files/1549198/simc_gui.zip)

NOTE: Some items such as the WW T21 were changed on the PTR so it's possible these are using old values? I'm not sure if the boots were ever different though.

#### Simulationcraft Version
Build 730-02 (stable)

#### Reproduction Steps:
- Sim a Windwalker character with affected items
- On results page, go down to first 'Gear' dropdown.
- Compare stats of affected items shown on the wowdb tooltip to the ones underneath it.
- Go up one dropdown to the 'Stats' section.
- Compare 'Gear Amount' stats to in-game/manually calculated stats.

**Comment by vituscze** [comment]
Stats are correct in the nightlies, perhaps it's time to make another release? @navv1234

**Comment by sthuro** [comment]
I'll try one of the nightlies then, thanks for the info!

EDIT: Just confirming that the items listed are showing correct stats in the latest nightly build.
