### ISSUE TITLE
T21 2/4pc and crucible paths

### ISSUE THREAD

**Issue by BIGJAKE2400** [simulationcraft/simc#4195]
Please include a brief overview of the issue in the title above, as well as completing the following:
Simcraft isnt accounting for T21 4pc frost dk a good chance that t21 2pc is also not being accounted for.  It does note that I am wearing t21 2/4pc but the ability isnt showing up on the overall damage done. Its also not accounting for relic path choice at all. Simmed my dk after putting a relic in but didn't upgrade it at the crucible. Re-simmed after choosing crucible path and didn't change sim dps at all. I sim 50k iterations each time and triple simmed it to make sure it wasn't accounting for the relic path.

deleted and re-downloaded and installed simc to make sure it wasnt just out of date.
#### Simulationcraft Version
730-2
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
For crucible, you must use the addon SimulationCraft in order to extract the value from your character.
As far as 2pc and 4pc working or not, there are plenty of simulations showing the differences between having and not having 2pc and 4pc.

In order to continue to help you, please follow the instructions to include the simc_gui.simc file so we can spot any possible errors in your profile.

**Comment by Melekus** [comment]
Make sure you're using the latest nightly version (tagged 730-03), the T21 bonuses for frost DK weren't implemented when 730-02 was released back in September. It may also help with the issue you're having with crucible.
