### ISSUE TITLE
[Rogue] Nightstalker vs. Subterfuge (Assa)

### ISSUE THREAD

**Issue by schnello** [simulationcraft/simc#4198]
Hello.

I perform a talentcompare: Nighstalker vs Subterfuge
As player i used the T21 Profile from git. (T21_Rogue_Assassination.simc)

The result is:
Subterfuge performs with 28kDPS/s better.
I reviewed also the Sample Sequence Table:
The virtual player used only one time garrote after stealth (Timecode: 0:00.000)
At all other phases after stealth (and +3 seconds after), garrote is not used (so no dmg+)

So why is the "Subterfuge" Build 28kdps ahead even if this talent was used only once?
Link to the report:
http://uplink.spdns.eu/talentcompare2

#### Simulationcraft Version
wow build level 25383, git build 6ac889b)

**Comment by bitfluxhound** [comment]
Currently NS is ahead due to DP snapshotting.
