### ISSUE TITLE
Override Bloodlust timing not working according to  wiki

### ISSUE THREAD

**Issue by Saevi** [simulationcraft/simc#4201]
Version: 730-03 64-Bit Windows Version

Was trying to delay bloodlust in the sim. Found this wiki article:
https://github.com/simulationcraft/simc/wiki/BuffsAndDebuffs

First, the override command "override.bloodlust_early" does not seem to exist any more (throws an error when used), but is mentioned in the wiki.
When I tried the following override:

optimal_raid=1
bloodlust_time=-100
bloodlust_percent=20

Bloodlust was just fired 1s into the combat. Other values (like positive ones for bloodlust_time ) did not change that. Not too sure it isn't my fault, haven't experimented with these overrides before.

**Comment by Melekus** [comment]
The options seems to work fine now.
The bug may have been resolved, or this may have been caused by a shaman/mage character casting bloodlust/timewarp from the APL directly. 

edit: Removed bloodlust_early from the wiki
