### ISSUE TITLE
Some items have wrong stats/values

### ISSUE THREAD

**Issue by Moyhis** [simulationcraft/simc#4202]
I imported my character from armory and "#gear summary" in Simulate tab had different ratings than in-game. 
After Simulation I checked "Gear" under Results tab and some gear had different stats in this window than in-game. 
For example Chest 
"Soul-tempered Chestplate"   
ilevel: 945, stats: { 842 Armor, +4950 Sta, +3300 StrInt, **+1229 Crit, +726 Mastery** }

in-game
[Soul-tempered Chestplate](http://www.wowhead.com/item=152017/soul-tempered-chestplate&bonus=3610:1472)
ilvl 945
842 armor , +4950 Sta, 3300 Str, **+1103 Haste, +852 Mastery**

**Comment by milney74** [comment]
I am having the same issue. I am including a notepad file with my gear and stats while wearing [http://www.wowhead.com/item=152063/seal-of-the-portalmaster&bonus=1477:3610](url) and one without. Versatility is unaffected, and crit goes down, by not by an equivalent amount. There are other errors, but I have not gone piece by piece to locate those. I am running Version 730-03.
[Seal of the Portal Master bug.txt](https://github.com/simulationcraft/simc/files/1586108/Seal.of.the.Portal.Master.bug.txt)

**Comment by vituscze** [comment]
Most likely caused by old simc version, the stats for these items changed during PTR. Try it with nightly.
