### ISSUE TITLE
[Hunter] Marksman APL occasionally starts a vulnerability cycle in which it can only fire 1 aimed shot. This only happens when above 17.1% haste

### ISSUE THREAD

**Issue by Streammz** [simulationcraft/simc#4206]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimC Version -> Nightly (730-03)
SimC Build Date -> Dec 22 2017
SimC Git Hash -> 5eb01aa

#### simc_gui.simc file or contents
~~This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/~~

N/A as this was done [on Raidbots](https://www.raidbots.com/simbot/report/9cPhFSupGjWDU25vAC2XPh/simc).

#### Reproduction Steps:

- Have a MM Hunter gearset with above 17.1% haste, and simulate a single-target Patchwerk fight

----

There is a line in the Hunter Marksman APL that occasionally makes it so you have vulnerability cycles with 3 arcane shots and 1 aimed shot, if the first arcane shot would be moved before the marked shot however, you would be essentially doing the same damage initially, but add a second aimed shot to the vulnerability cycle.

This only happens if you are ABOVE 17.1% haste. which also is a breakpoint which is also only relevant if you're using the T20 4pc. It does not check if this is the case either.

```
marked_shot,if=!talent.sidewinders.enabled&!variable.pooling_for_piercing&!action.windburst.in_flight&(focus>65|buff.trueshot.up|(1%attack_haste)>1.171)
```

As you can see in the last part of this rule, `&(focus>65|buff.trueshot.up|(1%attack_haste)>1.171)`, it assumes that it can fire a marked shot if you have above 65 focus, if you have trueshot up, or if you have high enough haste. This last check should be different.

I went through one of my [personal simcraft outputs](https://www.raidbots.com/simbot/report/9cPhFSupGjWDU25vAC2XPh/simc) (the 1313113 profile specifically), and noticed in the APL sample sequence table, that this happened at least four times (1:46-1:51, 3:12-3:17, 4:07-4:12, 4:24-4:29) in a fight of five minutes.

**Comment by Streammz** [comment]
![image](https://user-images.githubusercontent.com/626948/34292181-0f6301ac-e700-11e7-8a24-b3dbdfceeab1.png)
![image](https://user-images.githubusercontent.com/626948/34292203-2c3e08d0-e700-11e7-8493-9144a9820f34.png)

Here is one of the samples mentioned in the OP which shows how it does triple arcane shot into 1 aimed shot.

**Comment by Jayezi** [comment]
That idea may seem intuitive but the sim doesn't really care if that happens. Bare minimum focus to force an Aimed pair (without considering t21 2pc or critical focus procs) is 37.6 focus so even if it forces that the default profile (17.19% haste) doesn't change.

(~800 error)
1605362  50.0%  marked>38
1605231  50.0%  T20_Hunter_Marksmanship

The same happens with t21 where setting up its new haste point (21.7 to be safe) and minimum focus (40) made no difference, though I have it in this tier's update just to be proper about it.

(~1100 error)
2251840  33.3%  T21_Hunter_Marksmanship
2251711  33.3%  21.7 haste & marked>40
2251392  33.3%  21.7_haste

**Comment by Streammz** [comment]
Since you pointed out such a case is unnecessery to check for because it ends up not being a damage increase to do so, I will close this issue as to not clog the issues list.

Thank you for your time!
