### ISSUE TITLE
Cant simulate, no active players in sim!

### ISSUE THREAD

**Issue by NichoTheMan** [simulationcraft/simc#4207]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
SimulationCraft 730-02

#### simc_gui.simc file or contents
https://pastebin.com/FqXni6Z7

#### Reproduction Steps:
Running simulationcraft on my Mistweaver Spec. Running on my main spec, Windwalker it works without issues.

**Comment by bitfluxhound** [comment]
Healer modules outside of hpal shockadin dps are not supported.
