### ISSUE TITLE
priest_suppress_sephuz works, but the APL can't tell that it can't proc it.

### ISSUE THREAD

**Issue by nullKomplex** [simulationcraft/simc#4209]
#### Simulationcraft Version simc-730-03-win64-7b8d526bb

priest_suppress_sephuz successfully prevents Sephuz from being procced. However the APL will still attempt to silence/mind bomb adds and from what I can tell there's no way to check for the priest_suppress_sephuz flag.

**Comment by N1gh7h4wk** [comment]
Yes, either you remove the lines from the apl alongside, or something for that needs to be implemented
