### ISSUE TITLE
Imported from AddOn, Runtime Error on Simulate

### ISSUE THREAD

**Issue by Dashulol** [simulationcraft/simc#4212]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-02

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
no crash

#### simc_gui.simc file or contents
https://pastebin.com/xNGFLpYf

#### Reproduction Steps:
Run /simc ingame
copy/paste the message to SimulationCraft
Press Import -> 100%
Press Simulate -> Runtime Error

#### detailed error
https://pastebin.com/RdNztixT

**Comment by bitfluxhound** [comment]
Healer modules outside of hpal shockadin dps are not supported.
Switch role to damage to sim for dps.
