### ISSUE TITLE
Missing relic / not taken into account

### ISSUE THREAD

**Issue by Kaizersauze** [simulationcraft/simc#4214]
Please include a brief overview of the issue in the title above, as well as completing the following:
Since I changed 2 of my relics, one seems missing in results
**Before change :**
1550258 dps, weapons ilvl 955 (in Gear part of results), seen relics :  { +74 ilevels, +64 ilevels, +67 ilevels }
**After changes :**
- From SimC addon :
1495586 dps, weapons ilvl 906 (in Gear part of results), seen relics :  { +77 ilevels, +64 ilevels }
- From import : 
1406063 dps, weapons ilvl 891 (in Gear part of results), seen relics :  { +77 ilevels, +64 ilevels }

#### Simulationcraft Version
730-02
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
Before change : https://pastebin.com/me7Wgmxg
After changes (from SimC addon) : https://pastebin.com/dedMR7ME
After changes (from Import) : https://pastebin.com/fNUMH3FC

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Melekus** [comment]
If I were to guess, the relic that is not taken into account was looted on Argus.
The last SimC release (the one you're using, 730-02) doesn't have some of the Argus relics in its spelldata and can't take them into account when you sim your character.

To fix this, just update your simc version to the latest nightly version found here : http://downloads.simulationcraft.org/?C=M;O=D

edit : just checked the pastebin, and your "Conch of the thunderer" Storm relic indeed comes from Argus.

About the difference between import and simc addon : the armory API doesn't currently display your character's Netherlight Crucible traits and you can only get them from importing with the addon at the moment.

**Comment by Kaizersauze** [comment]
Thanks a lot, exactly what you said, "nightly" 730-03 works like a charm !
And thank you again for the little difference (Armory API Vs addon) explained
