### ISSUE TITLE
Simc tabs

### ISSUE THREAD

**Issue by nochance911** [simulationcraft/simc#4221]
I have Simc 64 bit installed. When i open the webengine and click through the tabs it will not go from one tab to another without me clicking the welcome tab first.

**Comment by Atko3314** [comment]
Having the same problem!

**Comment by hammy-Moay** [comment]
I'm currently having the same issue, has this been resolved?

**Comment by Kutikuti** [comment]
Closing this as this is old, don't hesitate to create a new issue or re-open if the problem persists with the latest release or nightly

**Comment by jackdneilson** [comment]
Suggest reopening, still an issue when running with an nvidia GPU
