### ISSUE TITLE
No weapong equipted at the main hand slot

### ISSUE THREAD

**Issue by brat4300** [simulationcraft/simc#4223]
[DxDiag - Brat4300.txt](https://github.com/simulationcraft/simc/files/1601903/DxDiag.-.Brat4300.txt)
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
paladin="Tinkess"
level=110
race=human
region=us
server=draenor
role=heal
professions=engineering=608/enchanting=782
talents=1321223
spec=holy
artifact=48:0:0:0:0:963:1:964:1:965:1:966:1:967:1:968:1:969:4:970:4:971:4:972:4:973:1:974:4:975:4:976:4:977:4:1186:4:1342:1:1377:1:1553:4:1554:1:1555:1:1556:7:1645:1
crucible=0/0/0

head=,id=147244,gem_id=151583,bonus_id=1707/1808/3573/3159/3528
neck=,id=132444,enchant_id=5889,gem_id=151583,bonus_id=3529/3530/1811
shoulder=,id=134272,bonus_id=3573/1572/3528
back=,id=152400,enchant_id=5434
chest=,id=139224,bonus_id=3573/1532/3528
wrist=,id=137105,bonus_id=1811/3570
hands=,id=150961,bonus_id=3397/41/1557/3528
waist=,id=134357,bonus_id=3573/1808/1572/3528
legs=,id=138359,bonus_id=3573/41/1512/3336
feet=,id=150963,bonus_id=3397/1557/3528
finger1=,id=134191,bonus_id=3394/1542/3528
finger2=,id=140024,bonus_id=3394/1542/3528
trinket1=,id=134204,gem_id=151580,bonus_id=3474/1808/605/1507/1674
trinket2=,id=147276,bonus_id=603/3574/1642/3528
main_hand=,id=128823,gem_id=150996/151012/141276,bonus_id=735,relic_id=3629:1472:3528/3395:3169:3336/3394:1542:3528

### Gear from Bags
#
# Nightsfall Helmet (890)
# head=,id=139058,bonus_id=1727/1552/3336
#
# Ley-Scarred Helm (880)
# head=,id=134314,bonus_id=3394/1542/3528
#
# Conservatory Ward's Drape of the Fireflash (880)
# back=,id=152778,bonus_id=1696/1808/3629/1472/3528
#
# Garothi Breastplate (895)
# chest=,id=150958,bonus_id=3397/1557/3528
#
# Garothi Vambraces (895)
# wrist=,id=150962,bonus_id=3397/41/1557/3528
#
# Shieldguard Girdle (880)
# waist=,id=121756,bonus_id=3394/41/1542/3528
#
# Heathcliff's Immortality (940)
# finger1=,id=137047,enchant_id=5428,gem_id=151583,bonus_id=1811/3455
#
# Foul-Sadist's Seal (900)
# finger1=,id=150989,enchant_id=5428,bonus_id=3397/1562/3336
#
# Avenging Band of the Fireflash (850)
# finger1=,id=147257,bonus_id=1761/3574/1642/3528
#
# Marshstomper Oracle's Loop (860)
# finger1=,id=141544,enchant_id=5430,bonus_id=3466/1472
#
# Nightmare Bark (880)
# trinket1=,id=121287,bonus_id=3394/605/1542/3528
#
# Stalwart Crest (855)
# trinket1=,id=147278,bonus_id=604/1808/3574/1647/3336
#
# Legionnaire's Mandate (910)
# trinket1=,id=134366,bonus_id=3573/605/1572/3528
#
# Dragon Fishing Pole (20)
# main_hand=,id=84661
#

#### Reproduction Steps:

Used the SIMC add-on to pull from the game, also got same issue when trying to pull  from profile online. This worked just fine with my Prot and Ret specs but will not do my Holy spec.

**Comment by bitfluxhound** [comment]
Healer modules outside of hpal shockadin dps are not supported.
Switch role to damage to sim for dps.
