### ISSUE TITLE
Application data is only retrieved from user data

### ISSUE THREAD

**Issue by Thaodan** [simulationcraft/simc#4225]
Currently the application data is retrieved by QStandardpaths which is good.
But only the first location is used, which is the data of the user.
But it should be first try user data than system data.
At least for simc profiles, everything alse could be loaded from last value of AppDataLocation.

This also the reason why application icon is also missing on linux.

#### Simulationcraft Version
730_2
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
1. Start Simcraft.
2. See that there are no simc profiles present or localisation couldn't be loaded.

**Comment by scamille** [comment]
Would using https://doc-snapshots.qt.io/qt5-dev/qstandardpaths.html#writableLocation help here?

Or how exactly should we "try" each folder? Just check if it exists? 
Checking each possibility at each file-writing operation would require quite a bit of rework I don't see happening anytime soon.

**Comment by Thaodan** [comment]
It depends on what you want.

User data eg simc profiles made by the user should be loaded from user data.  I think it would be better to read the user profile dir and than read the system profile dir and load all profiles found.

So just try to look for what is found in each returned.
Except when try to write permanent user data eg. Profiles or profile logs. Qt has a function to return exactly this.
https://doc-snapshots.qt.io/qt5-dev/qstandardpaths.html#writableLocation


But something that is clearly data from the application that is  static or generated at build time like the welcome page should be loaded from system data and nowhere else (except for data where this intended).


The issue is relevant for all platform's. 
It's just that usually the application for is writable for the user on every other platforms except Linux.

Am 15. Januar 2018 20:27:19 MEZ schrieb Serge Camille <notifications@github.com>:
>Would using
>https://doc-snapshots.qt.io/qt5-dev/qstandardpaths.html#writableLocation
>help here?
>
>Or how exactly should we "try" each folder? Just check if it exists? 
>Checking each possibility at each file-writing operation would require
>quite a bit of rework I don't see happening anytime soon.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/simulationcraft/simc/issues/4225#issuecomment-357769558

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Thaodan** [comment]
Oh sorry I don't saw you already mentioned the function.

**Comment by scamille** [comment]
I tried to implement things as good as possible.

If the icon is not showing that means a different problem, since the icon should be added into the resource file and bundled with the app.
