### ISSUE TITLE
Issue with artefact weapons?  Simulations have lower ilvl than characters

### ISSUE THREAD

**Issue by professionaltart** [simulationcraft/simc#4228]
When running this https://pastebin.com/BGbTE7ZD via in-game addon, the simulation reports my character as having a 911 ilvl weapon, which drops about 10 ilvl from my character average, thus dropping my DPS.  When run in simc, it reports ~1.5m dps.  Via raidbots where it recognises the weapons correct ilvl, it reports ~1.8m dps (see: https://www.raidbots.com/simbot/report/7GUji8nDmrjYcgBwxCxHBv )

#### Simulationcraft Version
730-02

#### Reproduction Steps:
/simc in game, C&P into simulationcraft in windows.  Disable stat scaling (for speed), hit simulate.  Check DPS in results, check ilvl in results, notice ilvl discrepency.  Hit simulate on a simulate tab from an older session (see: https://pastebin.com/yA7NKCCG ), with lower ilvl/worse gear/stats, and notice it has a higher DPS output for a higher ilvl.

Check for confirmation via raidbots and notice it seems to report the correct average ilvl and weapon ilvl, and has much higher DPS.

I'm not sure how long this has been an issue for.  I've only noticed it for my feral druid so far.

**Comment by vituscze** [comment]
You're probably using stable version (or older), which was released before Argus relics were added into the game. So Cruor of the Avenger isn't recognized as a relic. Switching to nightly should fix this.

**Comment by professionaltart** [comment]
Thanks.  I checked that I was using an alpha release of the simc in-game addon, but not for simc itself.
