### ISSUE TITLE
Assassination Rogue APL when using PK Relics

### ISSUE THREAD

**Issue by Seliathan** [simulationcraft/simc#4239]
Depending on stat values, there is a slight DPS increase (about 20-25k with the simmed gear) when using Fok at 3+ CP (4+ when running DS) instead of using Mutilate again. 

#### Simcraft Version
Simcraft 730-03, gitbuild 3d7fa4ca9

#### simc_gui.simc file or contents
https://pastebin.com/uMLMnVJu

#### Reproduction Steps:

-Using the linked profile/APL yields a better result than using the default APL.

**Comment by Mystler** [comment]
Thanks a lot for reporting this. I incorporated your suggestion into the default APL in https://github.com/simulationcraft/simc/commit/35d406de4d094a194aa592fd4cd8a15f11c5caf9.
