### ISSUE TITLE
umbral moonglaves

### ISSUE THREAD

**Issue by Fyshtank** [simulationcraft/simc#4240]
getting spammed with
unknown spell with ID umbral_moonglaves used in PreviousOFFGCDSpell(umbral_moonglaves)

**Comment by vituscze** [comment]
Can you provide steps to reproduce this? Simc input perhaps?

**Comment by Fyshtank** [comment]
Here is the simc input data that I have generated from my character.
Hope this help
Thanks Fýshtank

**Comment by vituscze** [comment]
Looks like this is related to Ovale and not simc itself, closing.
