### ISSUE TITLE
query on scale factors

### ISSUE THREAD

**Issue by LOZH63** [simulationcraft/simc#4243]
not sure if this is the right forum , but the disparity between scale factor stat with the replacement on one item seems wrong .  i replaced the legs and haste goes from  along way last to along way first on required stats.     hopefully the file uploaded is sufficient.
[monk.zip](https://github.com/simulationcraft/simc/files/1646442/monk.zip)

cheers Laurie

**Comment by vituscze** [comment]
Most likely because the value of haste rating isn't a smooth curve. You're probably near a breakpoint, which would make the stat weight jump up. You could run a stat plot to be sure, check the wiki: https://github.com/simulationcraft/simc/wiki/StatsScaling#plotting

**Comment by LOZH63** [comment]
thanks for the reply,  this is the result
haste_rating, DPS, DPS-Error
-1500, 1.65806e+06, 2986.38
-1350, 1.65987e+06, 2955.58
-1200, 1.66485e+06, 3187.8
-1050, 1.66657e+06, 3179.23
-900, 1.66991e+06, 3438.89
-750, 1.66971e+06, 2859.44
-600, 1.67608e+06, 3314.56
-450, 1.68394e+06, 2910.13
-300, 1.68606e+06, 2979.11
-150, 1.69017e+06, 2892.27
0, 1.69644e+06, 659.72
150, 1.70167e+06, 3388.54
300, 1.70527e+06, 2963.13
450, 1.71192e+06, 3040.48
600, 1.71471e+06, 2907.55
750, 1.72112e+06, 3235.86
900, 1.72818e+06, 3171.78
1050, 1.73962e+06, 3220.54
1200, 1.74296e+06, 3159.71
1350, 1.7495e+06, 3157.01
1500, 1.75385e+06, 3262

will take someone alot smarter than me to tell me if its the cause of my probs .   as you seen in html of my char  with 960ilvl legs with haste tells me  haste has a normalised factor of 1.32,  when i replace thoselegs with 930ilvl no haste, it tells me haste is now 0.86 i have never seen this huge of a swing with one bit of gear.    
cheers Laurie

**Comment by vituscze** [comment]
If you generate HTML report, you'll get a nice graph where it should be pretty easy to see.

**Comment by LOZH63** [comment]
thanks again ,  after looking at the plots for both , i think i can seethe difference . not sure i understand it , but will assume its working as intended
