### ISSUE TITLE
Acrid Catalyst Injector not working in sim

### ISSUE THREAD

**Issue by clef462** [simulationcraft/simc#4244]
[Simulationcraft Results.pdf](https://github.com/simulationcraft/simc/files/1648568/Simulationcraft.Results.pdf)
When importing my profile using the simc addon in game, import worked, however - the Acrid Catalyst Injector is stating that it gives 0 extra intellegence on proc, therefore not providing the accurate DPS for sim

#### 730-03

####SIMcraft is not crashing

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by N1gh7h4wk** [comment]
i suggest you use a 7.3.2 or 7.3.5 simulationcraft version, which will have it implemented most likely. That would be for example the nightly build available here http://downloads.simulationcraft.org/?C=M;O=D
