### ISSUE TITLE
Forgefiend Fabricator DPS calculation error

### ISSUE THREAD

**Issue by Toogyboogy** [simulationcraft/simc#4246]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-02
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
Forgefiend fabricator calculates as 0 damage.
Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Rusah** [comment]
730-02 is an old version. Update to latest nightly build and try again.
