### ISSUE TITLE
Simcraft weird low level values

### ISSUE THREAD

**Issue by edzer7** [simulationcraft/simc#4247]
#### 730-02

Tried simming my 48 shadow priest, which used to just properly work prior to 7.3.5. However, it now suddenly shows that my 48 priest deals 315878 dps and gives me a bunch of strange pawn values ( Pawn: v1: "Fhay-Shadow": Class=Priest, Spec=Shadow, Intellect=34.05, SpellPower=34.05, CritRating=0.17, HasteRating=61.71, MasteryRating=-0.00, Versatility=130.47 ).

Is there a way to fix this? Have tried importing through both the simcraft addon and battle.net, both give strange values.

**Comment by N1gh7h4wk** [comment]
I suggest you use the current nightly build of simc to have an up-to-date version, and maybe update your simc addon

**Comment by scamille** [comment]
If you still have problems, please attach your https://github.com/simulationcraft/simc/wiki/simc_gui.simc file so we can more easily reproduce the problem.

**Comment by edzer7** [comment]
Already had updated my simcraft addon, but the nightly build solved my issue. Thank you.
