### ISSUE TITLE
Sim Copy Block drastically alters other Copy Block

### ISSUE THREAD

**Issue by AbrojoROU** [simulationcraft/simc#4252]
Please include a brief overview of the issue in the title above, as well as completing the following:

OVERVIEW: A sim copy block can break other copy block dps. 
Uploaded a profile with 3 block (the standard + 2 copy block), removing 1 copy block breaks the other.

[simc_gui.zip](https://github.com/simulationcraft/simc/files/1658295/simc_gui.zip)

#### Simulationcraft Version
ANSWER: 735-01 nightly 64bit version (just downloaded)

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
ANSWER: Simcraft is not crashing

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
ANSWER: attached as a zip

#### Reproduction Steps:
ANSWER:
[BreakingLog.txt](https://github.com/simulationcraft/simc/files/1658266/BreakingLog.txt)

Using the attached SimProfile BreakingLog.txt

1) Run the sim normally (without scaling, just standard dps), you will get 3 results (1 for each copy block): Abrojo, SETUP_2 and SETUP_1
2) See that SETUP_2 has around 1,643,496 (of course it will vary a bit)

2) Now to the same Log remove the whole SETUP_1 block and run it again. 
3) See that removing SETUP_1 strongly changed the dps (towards the mid 1,500s range) on SETUP_2 which should not be possible.
 
4) Add SETUP_1 back and it will cause SETUP_2 to jump back again.
(this is completely repeatable, SETUP_1 is breaking SETUP_2 for some reason)

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by seriallos** [comment]
`copy` will copy the previous actor, not the base actor. Removing the second `copy` results in a different actor set up than with all 3 actors in the sim (specifically, SETUP_1 changes the `wrists` slot which will affect SETUP_2. If you remove SETUP_1 for the second run, it will not change the `wrists`).

If you require fewer details in the report (only need DPS for each actor, for example), take a look at profilesets. Profilesets are order independent as each profileset mutates the base actor, not the previous actor.

https://github.com/simulationcraft/simc/wiki/ProfileSet

**Comment by AbrojoROU** [comment]
Thank you for your quick response.

I assume the copy can support overwritting of gear slots within a same block?
If thats the case then you could just write all gear slots on the 2nd copy effectively overwriting everything again? Would that work or does anything else from the first actor sim spill over to the 2nd block?

For example

Copy Block 1
Full Base Actor Gear list (Helm, wrists, etc) 
Talents
Wrists


Copy Block 2
Full Base Actor Gear list (Helm, wrists, etc) 
Ring

Would this work?

**Comment by seriallos** [comment]
Yup!

_Most_ simc options follow a "last wins" approach for handling duplicate values. So you can specify the same base actor every time and then overwrite the options you want for that actor (or just specify all the slots every time and only mutate the slots you care about)

e.g.

```
copy="my actor"
wrists=,id=1234
wrists=,id=9876 # this one gets used
```
