### ISSUE TITLE
Arcane T21 Default Profile Suboptimal Crucible Traits

### ISSUE THREAD

**Issue by dsteinyb** [simulationcraft/simc#4257]
I didn't know where to best post this, so I'll just leave this here. If there's somewhere else for me to post this, please let me know and I'll post there.

While looking at the T21 default profile for Arcane Mage, I saw that two ranks of Aegwynn's Intensity have been added to the Arcane relics. I was surprised that these were the recommended traits to go with, as most places I've searched have used Ethereal Sensitivity or Aegwynn's Fury as the second best trait (Aegwynn's Imperative is already the default trait). So I did some simming, and I discovered that using two Ethereal Sensitivity is better than two Aegwynn's Intensity in the first and third relics, crucible row three; the former gives about a 0.2% damage increase over the latter. Could anyone else confirm this, and/or make any necessary changes? 

I'm too poor to download my own simcraft, so I used Raidbots for these sims (I simulated less than two hours before making this post, so it should be fairly accurate). Below is a link to my results:
https://www.raidbots.com/simbot/report/vuAmeyVERhoQ97DiVSGm1T

Thank you in advance.
-Cobalt

**Comment by vituscze** [comment]
That's very tiny damage increase, but sure. Added in a0f65da05765bc106ceb952a0858ce0e28d57ed3
