### ISSUE TITLE
Wrong stats on some pieces of gear!!!

### ISSUE THREAD

**Issue by Farbotnik** [simulationcraft/simc#4258]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-02

#### simc_gui.simc file or contents
[https://pastebin.com/BQyQBEEu](https://pastebin.com/BQyQBEEu)

#### Reproduction Steps:
[https://imgur.com/a/NKbbW](https://imgur.com/a/NKbbW)
So I recently obtained a few new pieces of gear and started simming away. I began noticing som inconsistencies with the results I was getting. I kept importing my Pawn string, and adjusting my stats to improve my dps. 
*Notable example:* ( Pawn: v1: "Petulah-Elemental": Class=Shaman, Spec=Elemental, Intellect=24.97, CritRating=44.70, HasteRating=41.69, MasteryRating=38.13, Versatility=38.32 )
So I adjusted and equipped a piece with more Crit and Haste, Pawn even recognized that it would be an increase. So I equipped [Chain of the Unmaker](http://www.wowhead.com/item=152283/chain-of-the-unmaker&bonus=1477:3610) and simmed again. My dps went down. I checked the gear panel and to my surprise simulationcraft was stated gear had different stats than it actually had. Stating my [Chain of the Unmaker](http://www.wowhead.com/item=152283/chain-of-the-unmaker&bonus=1477:3610) had Haste and Mastery instead of Haste and Crit. This theme continues on my Head, Shoulders,Legs, and even a few rings. I noticed my geared that dropped from the 7.3 Antorus the Burning Throne had these incorrect stats in Simulationcraft.

**Comment by Extort713** [comment]
Must have been fixed, just tested chain and it has correct stats. Have you tested it recently with new builds?

**Comment by Farbotnik** [comment]
Thank you for that. The current release build was what I was using. But I updated to 

  | SimcSetup-735-01-Win64.exe | 2018-01-26 00:07 | 45M |  

 and theres a fix for it in there. Closing the issue.
