### ISSUE TITLE
Hey um weird problem when I try to download simcraft it download with a csgo icon and when I try to boot it up it launches csgo any ideas as to how I could fix this?

### ISSUE THREAD

**Issue by Lucidcx** [simulationcraft/simc#4261]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Lucidcx** [comment]
Hey um weird problem when I try to download simcraft it download with a csgo icon and when I try to boot it up it launches csgo any ideas as to how I could fix this?

**Comment by lgkern** [comment]
Hello, 

I recommend you to try using RaidBots (https://www.raidbots.com) for your simulation needs as it will provide you with quick and easy to use tools for general simulation.
