### ISSUE TITLE
fury odyns fury not simming 

### ISSUE THREAD

**Issue by gavstarxx** [simulationcraft/simc#4266]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by gavstarxx** [comment]
# SimC Addon 1.9.1

warrior="Gavstar"
level=110
race=night_elf
region=eu
server=quelthalas
role=attack
professions=blacksmithing=800/mining=788
talents=2333212
spec=fury
artifact=35:0:0:0:0:1617:4:1618:1:1619:1:1620:26:982:1:981:1:980:1:984:1:985:1:986:1:996:4:995:4:994:4:993:4:992:4:991:4:987:1:988:4:989:4:990:4:1394:1:1357:1:1715:1
crucible=1739:1784:995/1739:1782:988/1739:1782:990

head=,id=137451,gem_id=151583,bonus_id=3536/1808/1612/3337
neck=,id=151973,enchant_id=5439,bonus_id=3611/1497/3336
shoulder=,id=152183,bonus_id=3611/1487/3528
back=,id=152179,enchant_id=5434,bonus_id=3610/1477/3336
chest=,id=152178,bonus_id=3610/43/1477/3336
tabard=,id=152399
wrist=,id=152023,bonus_id=3611/1487/3528
hands=,id=152180,bonus_id=3610/1497/3337
waist=,id=144497,bonus_id=3536/1612/3337
legs=,id=134271,bonus_id=3536/1607/3336
feet=,id=132443,bonus_id=3459/3630
finger1=,id=133634,enchant_id=5428,gem_id=151583,bonus_id=3536/1808/1592/3528
finger2=,id=151650,enchant_id=5428,gem_id=151583,bonus_id=1811/3630
trinket1=,id=140806,gem_id=151583,bonus_id=3520/1808/1457/3528
trinket2=,id=154176,bonus_id=3985/3992
main_hand=,id=128908,gem_id=155849/137313/152293,bonus_id=751,relic_id=3611:1497:3528/3536:1617:3337/3611:1497:3336
off_hand=,id=134553

### Gear from Bags
#
# Visage of Brutish Iron (960)
# head=,id=142304,bonus_id=3536/1577/3337
#
# Helmet of Reverent Loyalty (935)
# head=,id=134513,bonus_id=3535/1587/3528
#
# Titanic Onslaught Greathelm (925)
# head=,id=147190,bonus_id=3562/1507/3336
#
# Juggernaut Helm (945)
# head=,id=152181,bonus_id=3611/1487/3528
#
# The Great Storm's Eye (1000)
# head=,id=151823,bonus_id=3459/3630
#
# Titan-Subjugator's Visage (930)
# head=,id=152014,bonus_id=3610/1472/3528
#
# Crown of Fallen Kings (955)
# head=,id=133629,bonus_id=3510/1607/3337
#
# Riveted Choker of Delirium (945)
# neck=,id=151966,enchant_id=5890,bonus_id=3611/1487/3528
#
# Man'ari Training Amulet (800)
# neck=,id=153130
#
# Wolfstride Pendant (935)
# neck=,id=133633,enchant_id=5890,bonus_id=3418/1587/3337
#
# Amulet of the Last Guardian (940)
# neck=,id=142207,bonus_id=3536/1552/3528
#
# Wolfstride Pendant (945)
# neck=,id=133633,bonus_id=3536/1597/3336
#
# Juggernaut Pauldrons (940)
# shoulder=,id=152183,enchant_id=5931,bonus_id=3610/1482/3336
#
# Pauldrons of the Broken (935)
# shoulder=,id=151331,bonus_id=3418/1587/3337
#
# Titanic Onslaught Pauldrons (930)
# shoulder=,id=147192,bonus_id=3562/1512/3337
#
# Titanic Onslaught Pauldrons (940)
# shoulder=,id=147192,bonus_id=3562/1522/3337
#
# Shoulderguards of Indomitable Purpose (945)
# shoulder=,id=152416,bonus_id=3611/1487/3528
#
# Timeless Stratagem (1000)
# shoulder=,id=143728,bonus_id=1811/3630
#
# Mortar Guard Shoulderplates (935)
# shoulder=,id=137524,bonus_id=3534/1587/3336
#
# Cloak of Stifling Brimstone (930)
# back=,id=146984,enchant_id=5434,bonus_id=3563/42/1512/3528
#
# Cloak of the Burning Vanguard (945)
# back=,id=151937,bonus_id=3611/1487/3528
#
# Drape of the Spirited Hunt (960)
# back=,id=151938,bonus_id=3611/1502/3337
#
# Seacursed Wrap (940)
# back=,id=133771,enchant_id=5434,bonus_id=3536/1592/3528
#
# Titanic Onslaught Cloak (925)
# back=,id=147188,enchant_id=5434,bonus_id=3562/1507/3336
#
# Drape of the Spirited Hunt (930)
# back=,id=151938,bonus_id=3610/1472/3528
#
# Greatcloak of the Dark Pantheon (930)
# back=,id=152062,bonus_id=3610/1472/3528
#
# Dominant Gladiator's Cloak of Battle (900)
# back=,id=148424,bonus_id=3581/1695/1532/3528
#
# Juggernaut Cloak (930)
# back=,id=152179,enchant_id=5434,bonus_id=3610/1472/3528
#
# Titanic Onslaught Breastplate (920)
# chest=,id=147187,bonus_id=3562/1502/3336
#
# Soul-Tempered Chestplate (950)
# chest=,id=152017,bonus_id=3611/43/1492/3336
#
# Juggernaut Breastplate (930)
# chest=,id=152178,bonus_id=3610/42/1472/3528
#
# Skoldiir Breastplate (955)
# chest=,id=134179,bonus_id=3536/1617/3337
#
# Mannoroth's Bloodletting Manacles (1000)
# wrist=,id=137107,bonus_id=1811/3630
#
# Juggernaut Gauntlets (930)
# hands=,id=152180,bonus_id=3610/1472/3528
#
# Titanic Onslaught Handguards (920)
# hands=,id=147189,bonus_id=3562/1502/3336
#
# Dominant Gladiator's Plate Gauntlets (925)
# hands=,id=148636,bonus_id=1719/1557/3336
#
# Archavon's Heavy Hand (1000)
# hands=,id=137060,bonus_id=3459/3630
#
# Juggernaut Gauntlets (945)
# hands=,id=152180,bonus_id=3611/1487/3528
#
# Molten Bite Handguards (945)
# hands=,id=152012,bonus_id=3611/1487/3528
#
# Groundshatter Gauntlets (940)
# hands=,id=147062,bonus_id=3562/41/1522/3337
#
# Naj'entus's Vertebrae (1000)
# waist=,id=137087,bonus_id=3459/3630
#
# Rethu's Incessant Courage (1000)
# waist=,id=146667,gem_id=151584/151584/151584,bonus_id=1811/3630
#
# Arcane Defender's Belt (950)
# waist=,id=134269,bonus_id=3418/1612/3337
#
# Waistguard of Fel Magics (935)
# waist=,id=152380,bonus_id=3614/1477/3336
#
# Shiversleet Waistguard (930)
# waist=,id=147071,bonus_id=3562/1512/3337
#
# Flamelicked Girdle (930)
# waist=,id=152021,bonus_id=3610/1472/3528
#
# Juggernaut Legplates (950)
# legs=,id=152182,bonus_id=3611/1492/3336
#
# Legplates of the Obsidian Aspect (905)
# legs=,id=138360,bonus_id=3518/1808/1502/3528
#
# Greaves of Mercurial Allegiance (950)
# legs=,id=152015,bonus_id=3611/1492/3336
#
# Juggernaut Legplates (935)
# legs=,id=152182,bonus_id=3610/1477/3336
#
# Arcane Defender's Pants (940)
# legs=,id=134271,bonus_id=3536/1602/3528
#
# Titanic Onslaught Greaves (915)
# legs=,id=147191,gem_id=151584,bonus_id=3561/1808/1497/3337
#
# Juggernaut Legplates (930)
# legs=,id=152182,bonus_id=3610/43/1472/3528
#
# Cosmos-Culling Legplates (940)
# legs=,id=152016,bonus_id=3610/1472/3528
#
# Soul Crushing Stompers (930)
# feet=,id=152374,bonus_id=3614/1472/3528
#
# Doomwalker Warboots (930)
# feet=,id=152009,bonus_id=3610/1808/1472/3528
#
# Eredar Warcouncil Sabatons (945)
# feet=,id=152011,bonus_id=3611/1487/3528
#
# Burning Coven Sabatons (930)
# feet=,id=152010,bonus_id=3610/1472/3528
#
# Valkyra Protector Greatboots (940)
# feet=,id=136772,gem_id=151584,bonus_id=3536/1808/1592/3528
#
# Avenging Band of the Peerless (940)
# finger1=,id=147257,enchant_id=5429,gem_id=151584,bonus_id=3402/1808/40/3573/3189/3337
#
# Ring of Minute Mirrors (940)
# finger1=,id=137533,enchant_id=5429,gem_id=151584,bonus_id=3536/1808/1592/3528
#
# Loop of Vitriolic Intent (930)
# finger1=,id=134530,enchant_id=5428,bonus_id=3418/1582/3337
#
# Ring of Collapsing Futures (940)
# finger1=,id=142173,bonus_id=3536/1552/3528
#
# Insignia of the Grand Army (1000)
# finger1=,id=152626,enchant_id=5429,gem_id=151584,bonus_id=3459/3630
#
# Ayala's Stone Heart (1000)
# finger1=,id=137052,enchant_id=5429,gem_id=151584,bonus_id=1811/3630
#
# Arch-Druid's Tainted Seal (915)
# finger1=,id=134487,enchant_id=5429,gem_id=151584,bonus_id=3573/1808/1567/3336
#
# Seal of Darkshire Nobility (910)
# finger1=,id=142171,bonus_id=3573/1527/3528
#
# Seal of the Portalmaster (945)
# finger1=,id=152063,bonus_id=3611/1487/3528
#
# Band of the Sargerite Smith (945)
# finger1=,id=152064,bonus_id=3611/1487/3528
#
# Sullied Seal of the Pantheon (940)
# finger1=,id=151972,bonus_id=3610/1472/3528
#
# Sullied Seal of the Pantheon (955)
# finger1=,id=151972,enchant_id=5429,bonus_id=3611/1487/3528
#
# Loop of the Life-Binder (945)
# finger1=,id=152688,enchant_id=5429,bonus_id=3611/1487/3528
#
# Ironrune Charm (910)
# trinket1=,id=134190,bonus_id=3573/1808/604/1572/3528
#
# Windscar Whetstone (940)
# trinket1=,id=137486,bonus_id=3536/1592/3528
#
# Terrorbound Nexus (910)
# trinket1=,id=137406,bonus_id=3573/1562/3528
#
# Kil'jaeden's Burning Wish (1000)
# trinket1=,id=144259,bonus_id=3459/3630
#
# Shadow-Singed Fang (930)
# trinket1=,id=151968,bonus_id=3610/1472/3528
#
# Drained Mana Crystal (930)
# trinket1=,id=134322,bonus_id=3573/607/1592/3337
#
# Giant Ornamental Pearl (945)
# trinket1=,id=137369,bonus_id=3536/1597/3336
#
# Mark of Dargrul (925)
# trinket1=,id=137357,bonus_id=3573/1577/3337
#
# Gorshalach's Legacy (945)
# trinket1=,id=152093,bonus_id=3611/1808/1487/3528
#
# Legionnaire's Mandate (925)
# trinket1=,id=134366,gem_id=151584,bonus_id=3573/1808/605/1587/3337
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#

**Comment by navv1234** [comment]
Artifact abilities are not intended to function when wielding a Mining Pick and a Blacksmith Hammer.

**Comment by Pewtro** [comment]
He doesn't have those equipped, those are just in his bags - he has Warswords of the Valarjar equipped with the ID 128908.

But I just ran it on raidbots and it does sim Odyn's Fury
![image](https://user-images.githubusercontent.com/29204244/35729730-f6375c38-080f-11e8-946d-edbfd8bec78b.png)

**Comment by navv1234** [comment]
Ah yes, the github thinking it's markup issue. In any case the artifact stuff has been implemented for a long while and working.

**Comment by gavstarxx** [comment]
Can this be fixed

Sent from my iPhone

On 2 Feb 2018, at 10:59, PRAISE EARTHQUAKE TOTEM <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah yes, the github thinking it's markup issue. In any case the artifact stuff has been implemented for a long while and working.

**Comment by navv1234** [comment]
The github markup issue? Yes, should be possible.

**Comment by gavstarxx** [comment]
What is the markup issue sorry I’m not that tech fluent

Sent from my iPhone

On 2 Feb 2018, at 11:40, PRAISE EARTHQUAKE TOTEM <notifications@github.com<mailto:notifications@github.com>> wrote:


The github markup issue? Yes, should be possible.

**Comment by Pewtro** [comment]
Your normal import should work fine gavstarxx so long as you have Warswords equipped when you do /simc, it does sim with Odyn's Fury as I just showed you above.

**Comment by navv1234** [comment]
Unrelated to this issue, the big letters in your pasted simc profile. They should not be like that, and makes the information harder to process.

There is no issue regarding Odyn's Fury, it is functional in simulationcraft.

**Comment by gavstarxx** [comment]
The war sword are equipped every time I do /Simc in game than I just copy an past in to Simcraft

Sent from my iPhone

On 2 Feb 2018, at 11:46, Laust <notifications@github.com<mailto:notifications@github.com>> wrote:


Your normal import should work fine gavstarxx so long as you have Warswords equipped when you do /simc, it does sim with Odyn's Fury as I just showed you above.

**Comment by gavstarxx** [comment]
ok so i just sim my self an this 
is what I'm getting not sure what I'm doing wrong 
![image](https://user-images.githubusercontent.com/36053058/35732480-6706da5a-0811-11e8-91f9-a1cd052c5b66.png)
![image](https://user-images.githubusercontent.com/36053058/35732496-74b13f92-0811-11e8-8dad-44f74925cd76.png)
using this sim/c 
# SimC Addon 1.9.1

warrior="Gavstar"
level=110
race=night_elf
region=eu
server=quelthalas
role=attack
professions=blacksmithing=800/mining=788
talents=2133212
spec=fury
artifact=35:0:0:0:0:1617:4:1618:1:1619:1:1620:26:982:1:981:1:980:1:984:1:985:1:986:1:996:4:995:4:994:4:993:4:992:4:991:4:987:1:988:4:989:4:990:4:1394:1:1357:1:1715:1
crucible=1739:1784:995/1739:1782:988/1739:1782:990

head=,id=137451,gem_id=151583,bonus_id=3536/1808/1612/3337
neck=,id=151973,enchant_id=5439,bonus_id=3611/1497/3336
shoulder=,id=152183,bonus_id=3611/1487/3528
back=,id=152179,enchant_id=5434,bonus_id=3610/1477/3336
chest=,id=152178,bonus_id=3610/43/1477/3336
tabard=,id=152399
wrist=,id=152023,bonus_id=3611/1487/3528
hands=,id=152180,bonus_id=3610/1497/3337
waist=,id=144497,bonus_id=3536/1612/3337
legs=,id=134271,bonus_id=3536/1607/3336
feet=,id=132443,bonus_id=3459/3630
finger1=,id=133634,enchant_id=5428,gem_id=151583,bonus_id=3536/1808/1592/3528
finger2=,id=151650,enchant_id=5428,gem_id=151583,bonus_id=1811/3630
trinket1=,id=140806,gem_id=151583,bonus_id=3520/1808/1457/3528
trinket2=,id=154176,bonus_id=3985/3992
main_hand=,id=128908,gem_id=155849/137313/152293,bonus_id=751,relic_id=3611:1497:3528/3536:1617:3337/3611:1497:3336
off_hand=,id=134553

### Gear from Bags
#
# Helmet of Reverent Loyalty (935)
# head=,id=134513,bonus_id=3535/1587/3528
#
# Visage of Brutish Iron (960)
# head=,id=142304,bonus_id=3536/1577/3337
#
# Titan-Subjugator's Visage (930)
# head=,id=152014,bonus_id=3610/1472/3528
#
# The Great Storm's Eye (1000)
# head=,id=151823,bonus_id=3459/3630
#
# Juggernaut Helm (945)
# head=,id=152181,bonus_id=3611/1487/3528
#
# Titanic Onslaught Greathelm (925)
# head=,id=147190,bonus_id=3562/1507/3336
#
# Crown of Fallen Kings (955)
# head=,id=133629,bonus_id=3510/1607/3337
#
# Amulet of the Last Guardian (940)
# neck=,id=142207,bonus_id=3536/1552/3528
#
# Wolfstride Pendant (935)
# neck=,id=133633,enchant_id=5890,bonus_id=3418/1587/3337
#
# Wolfstride Pendant (945)
# neck=,id=133633,bonus_id=3536/1597/3336
#
# Riveted Choker of Delirium (945)
# neck=,id=151966,enchant_id=5890,bonus_id=3611/1487/3528
#
# Timeless Stratagem (1000)
# shoulder=,id=143728,bonus_id=1811/3630
#
# Mortar Guard Shoulderplates (935)
# shoulder=,id=137524,bonus_id=3534/1587/3336
#
# Juggernaut Pauldrons (940)
# shoulder=,id=152183,enchant_id=5931,bonus_id=3610/1482/3336
#
# Shoulderguards of Indomitable Purpose (945)
# shoulder=,id=152416,bonus_id=3611/1487/3528
#
# Titanic Onslaught Pauldrons (940)
# shoulder=,id=147192,bonus_id=3562/1522/3337
#
# Dominant Gladiator's Cloak of Battle (900)
# back=,id=148424,bonus_id=3581/1695/1532/3528
#
# Cloak of Stifling Brimstone (930)
# back=,id=146984,enchant_id=5434,bonus_id=3563/42/1512/3528
#
# Cloak of the Burning Vanguard (945)
# back=,id=151937,bonus_id=3611/1487/3528
#
# Drape of the Spirited Hunt (930)
# back=,id=151938,bonus_id=3610/1472/3528
#
# Seacursed Wrap (940)
# back=,id=133771,enchant_id=5434,bonus_id=3536/1592/3528
#
# Juggernaut Cloak (930)
# back=,id=152179,enchant_id=5434,bonus_id=3610/1472/3528
#
# Drape of the Spirited Hunt (960)
# back=,id=151938,bonus_id=3611/1502/3337
#
# Greatcloak of the Dark Pantheon (930)
# back=,id=152062,bonus_id=3610/1472/3528
#
# Titanic Onslaught Cloak (925)
# back=,id=147188,enchant_id=5434,bonus_id=3562/1507/3336
#
# Titanic Onslaught Breastplate (920)
# chest=,id=147187,bonus_id=3562/1502/3336
#
# Skoldiir Breastplate (955)
# chest=,id=134179,bonus_id=3536/1617/3337
#
# Coralplate Chestguard (890)
# chest=,id=134223,bonus_id=3410/1552/3528
#
# Soul-Tempered Chestplate (950)
# chest=,id=152017,bonus_id=3611/43/1492/3336
#
# Juggernaut Breastplate (930)
# chest=,id=152178,bonus_id=3610/42/1472/3528
#
# Mannoroth's Bloodletting Manacles (1000)
# wrist=,id=137107,bonus_id=1811/3630
#
# Archavon's Heavy Hand (1000)
# hands=,id=137060,bonus_id=3459/3630
#
# Juggernaut Gauntlets (945)
# hands=,id=152180,bonus_id=3611/1487/3528
#
# Dominant Gladiator's Plate Gauntlets (925)
# hands=,id=148636,bonus_id=1719/1557/3336
#
# Titanic Onslaught Handguards (920)
# hands=,id=147189,bonus_id=3562/1502/3336
#
# Molten Bite Handguards (945)
# hands=,id=152012,bonus_id=3611/1487/3528
#
# Juggernaut Gauntlets (930)
# hands=,id=152180,bonus_id=3610/1472/3528
#
# Groundshatter Gauntlets (940)
# hands=,id=147062,bonus_id=3562/41/1522/3337
#
# Waistguard of Fel Magics (935)
# waist=,id=152380,bonus_id=3614/1477/3336
#
# Naj'entus's Vertebrae (1000)
# waist=,id=137087,bonus_id=3459/3630
#
# Rethu's Incessant Courage (1000)
# waist=,id=146667,gem_id=151584/151584/151584,bonus_id=1811/3630
#
# Flamelicked Girdle (930)
# waist=,id=152021,bonus_id=3610/1472/3528
#
# Shiversleet Waistguard (930)
# waist=,id=147071,bonus_id=3562/1512/3337
#
# Arcane Defender's Belt (950)
# waist=,id=134269,bonus_id=3418/1612/3337
#
# Juggernaut Legplates (935)
# legs=,id=152182,bonus_id=3610/1477/3336
#
# Juggernaut Legplates (950)
# legs=,id=152182,bonus_id=3611/1492/3336
#
# Dominant Combatant's Plate Legguards (870)
# legs=,id=149994,bonus_id=3582/1709/1808/41/1532/3528
#
# Legplates of the Obsidian Aspect (905)
# legs=,id=138360,bonus_id=3518/1808/1502/3528
#
# Greaves of Mercurial Allegiance (950)
# legs=,id=152015,bonus_id=3611/1492/3336
#
# Juggernaut Legplates (930)
# legs=,id=152182,bonus_id=3610/43/1472/3528
#
# Cosmos-Culling Legplates (940)
# legs=,id=152016,bonus_id=3610/1472/3528
#
# Arcane Defender's Pants (940)
# legs=,id=134271,bonus_id=3536/1602/3528
#
# Titanic Onslaught Greaves (915)
# legs=,id=147191,gem_id=151584,bonus_id=3561/1808/1497/3337
#
# Doomwalker Warboots (930)
# feet=,id=152009,bonus_id=3610/1808/1472/3528
#
# Soul Crushing Stompers (930)
# feet=,id=152374,bonus_id=3614/1472/3528
#
# Valkyra Protector Greatboots (940)
# feet=,id=136772,gem_id=151584,bonus_id=3536/1808/1592/3528
#
# Burning Coven Sabatons (930)
# feet=,id=152010,bonus_id=3610/1472/3528
#
# Eredar Warcouncil Sabatons (945)
# feet=,id=152011,bonus_id=3611/1487/3528
#
# Insignia of the Grand Army (1000)
# finger1=,id=152626,enchant_id=5429,gem_id=151584,bonus_id=3459/3630
#
# Ring of Minute Mirrors (940)
# finger1=,id=137533,enchant_id=5429,gem_id=151584,bonus_id=3536/1808/1592/3528
#
# Loop of Vitriolic Intent (930)
# finger1=,id=134530,enchant_id=5428,bonus_id=3418/1582/3337
#
# Seal of the Portalmaster (945)
# finger1=,id=152063,bonus_id=3611/1487/3528
#
# Sullied Seal of the Pantheon (940)
# finger1=,id=151972,bonus_id=3610/1472/3528
#
# Ayala's Stone Heart (1000)
# finger1=,id=137052,enchant_id=5429,gem_id=151584,bonus_id=1811/3630
#
# Avenging Band of the Peerless (940)
# finger1=,id=147257,enchant_id=5429,gem_id=151584,bonus_id=3402/1808/40/3573/3189/3337
#
# Arch-Druid's Tainted Seal (915)
# finger1=,id=134487,enchant_id=5429,gem_id=151584,bonus_id=3573/1808/1567/3336
#
# Loop of the Life-Binder (945)
# finger1=,id=152688,enchant_id=5429,bonus_id=3611/1487/3528
#
# Ring of Collapsing Futures (940)
# finger1=,id=142173,bonus_id=3536/1552/3528
#
# Band of the Sargerite Smith (945)
# finger1=,id=152064,bonus_id=3611/1487/3528
#
# Sullied Seal of the Pantheon (955)
# finger1=,id=151972,enchant_id=5429,bonus_id=3611/1487/3528
#
# Seal of Darkshire Nobility (910)
# finger1=,id=142171,bonus_id=3573/1527/3528
#
# Mark of Dargrul (925)
# trinket1=,id=137357,bonus_id=3573/1577/3337
#
# Shadow-Singed Fang (930)
# trinket1=,id=151968,bonus_id=3610/1472/3528
#
# Ironrune Charm (910)
# trinket1=,id=134190,bonus_id=3573/1808/604/1572/3528
#
# Legionnaire's Mandate (925)
# trinket1=,id=134366,gem_id=151584,bonus_id=3573/1808/605/1587/3337
#
# Gorshalach's Legacy (945)
# trinket1=,id=152093,bonus_id=3611/1808/1487/3528
#
# Kil'jaeden's Burning Wish (1000)
# trinket1=,id=144259,bonus_id=3459/3630
#
# Terrorbound Nexus (910)
# trinket1=,id=137406,bonus_id=3573/1562/3528
#
# Drained Mana Crystal (930)
# trinket1=,id=134322,bonus_id=3573/607/1592/3337
#
# Windscar Whetstone (940)
# trinket1=,id=137486,bonus_id=3536/1592/3528
#
# Terrorbound Nexus (910)
# trinket1=,id=137406,bonus_id=3573/1562/3528
#
# Giant Ornamental Pearl (945)
# trinket1=,id=137369,bonus_id=3536/1597/3336
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#

**Comment by navv1234** [comment]
Use a nightly simulationcraft build from http://downloads.simulationcraft.org/?C=M;O=D

**Comment by gavstarxx** [comment]
Thank you I will give it a try ty for your help

Sent from my iPhone

On 2 Feb 2018, at 12:09, PRAISE EARTHQUAKE TOTEM <notifications@github.com<mailto:notifications@github.com>> wrote:


Use a nightly simulationcraft build from http://downloads.simulationcraft.org/?C=M;O=D
