### ISSUE TITLE
Simming way too low.

### ISSUE THREAD

**Issue by lopso111** [simulationcraft/simc#4268]
So on my ilvl 941 ret paladin, when i run a sim it says my dps is around 500k. That is way low. I tried resetting the settings and selecting my stats, strength, crit, haste, versatility, and mastery, and enabling scaling again, but i got the same results. I don't know if it's the simcraft addon or what, but it's starting to bug me.

**Comment by bitfluxhound** [comment]
Have you updated simc addon to get artifact traits / relics ?

**Comment by lgkern** [comment]
What version are you using? Are you using the SimC addon to export the Netherlight Crucible? Can you paste the profile you're using?
