### ISSUE TITLE
Item causes Simcraft to crash

### ISSUE THREAD

**Issue by robertbrodbeck** [simulationcraft/simc#4269]
After messing around a little bit, I figured the reason my SimCraft is crashing. 
finger2=signet_of_the_hidden_door,id=88285,bonus_id=4043
Is causing the crash. After removing it from my import file, simulates fine again. Try to replace it back into the import profile, and it immediately crashes after clicking 'Simulate'. 

#### Simulationcraft Version 730-02

No need for dxdiag, item is the cause for the crash, reported so it may be fixed in next update.

#### simc_gui.simc file or contents
hunter="Dernath"
level=35
race=worgen
region=us
server=proudmoore
role=attack
professions=leatherworking=73/skinning=90
talents=2100000
spec=beast_mastery

head=,id=131455,bonus_id=3645,drop_level=34
neck=,id=57421,bonus_id=3645,drop_level=33
shoulder=,id=131532,bonus_id=3643,drop_level=31
back=,id=120167,bonus_id=3998,drop_level=28
chest=,id=131291,enchant_id=15,bonus_id=3636,drop_level=22
shirt=,id=2576
wrist=,id=14580,bonus_id=3833,drop_level=34
hands=,id=131311,enchant_id=15,bonus_id=3636,drop_level=23
waist=,id=131317,bonus_id=3636,drop_level=25
legs=,id=131713,bonus_id=3998,drop_level=28
feet=,id=131880,bonus_id=3645,drop_level=33
finger1=,id=151436,bonus_id=3998,drop_level=27
finger2=,id=88285,bonus_id=4043,drop_level=35
main_hand=,id=57454,bonus_id=3645,drop_level=35

### Gear from Bags
#
# Tumultuous Cloak of the Sorcerer (25)
# back=,id=51994,suffix=-85,bonus_id=4244,drop_level=35
#
# Jalin's Recompense (25)
# finger1=,id=56703,bonus_id=3722,drop_level=30
#
# Skinning Knife (4)
# main_hand=,id=7005
#
# Skinning Knife (4)
# off_hand=,id=7005
#

^^Complete file, although the reason has already been identified.

**Comment by lgkern** [comment]
The issue is because you're trying to sim a low-level character. SimC doesn't support low-level characters and has unreliable results when doing so.

**Comment by scamille** [comment]
Seems to be working fine now with simc-735-02-win64-30c64452e.7z from 2018-03-01.

**Comment by navv1234** [comment]
This is a more general issue than a specific profile, I have a todo item for myself to solve the low-level crashing issues on special effect init (which is almost certainly the root cause of this issue), but it requires tweaking in a couple of places.
