### ISSUE TITLE
Simcraft crashes - Monitors loose signal

### ISSUE THREAD

**Issue by kaeptnJ** [simulationcraft/simc#4275]
Hello,

I have a slight problem. Whenever I start simulating my DPS my monitors turn black near the end of the sim. It's usually around the scaling of mastery when all three of my monitors loose their signal. I checked the temperature/performance of my CPU. My CPU in idle is around 40 degrees (celcius), when the simulation starts scaling the stats it's using 100% of my CPU and it peaks at around 60 degrees. As far as I can tell the CPU is not the problem here and it's probably the video card (Nvidia GTX 1060) or its driver causing the crash. After it crashes my only option is turning off my computer and restarting it. So far I have tried simulating about six times, monitoring my CPU temperature, updating my drivers and reinstalling the program inbetween each attempt. 

One thing that is interesting is that it only crashes while scaling. Whenever I turn off scaling it works fine..

Hope you can help me find a solution.

(Not a native speaker, sorry for typos)

#### ### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=600
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=0
override.mortal_wounds=0
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### Begin simulateText ###
# SimC Addon 1.9.1

hunter="Alfrek"
level=110
race=human
region=eu
server=antonidas
role=attack
professions=alchemy=77/herbalism=800
talents=2111112
spec=beast_mastery
artifact=56:0:0:0:0:1095:4:1636:1:882:1:1336:1:1520:22:881:1:880:1:879:1:878:1:1368:1:1519:1:877:1:876:1:875:4:874:4:873:4:872:4:871:4:870:4:869:4:868:4:1518:1:1517:4
crucible=1739:1774:875/1739:1780:1517/1739:1783

head=,id=138342,bonus_id=3516/1492/3336
neck=,id=140894,enchant_id=5890,bonus_id=3445/1512/3337
shoulder=,id=139121,enchant_id=5883,bonus_id=3418/1567/3337
back=,id=138368,enchant_id=5435,gem_id=130222,bonus_id=3518/1808/1502/3528
chest=,id=151805,bonus_id=1811/3630
wrist=,id=134484,bonus_id=3418/1567/3337
hands=,id=138340,enchant_id=5444,gem_id=130247,bonus_id=3516/1808/1487/1813
waist=,id=137080,bonus_id=3529/3459/3630
legs=,id=138344,bonus_id=3516/42/1487/1813
feet=,id=152367,bonus_id=3614/1472/3528
finger1=,id=147766,enchant_id=5429,gem_id=130222,bonus_id=3572/1808/1502/3337
finger2=,id=134487,enchant_id=5429,bonus_id=3536/1552/3337
trinket1=,id=134247,bonus_id=3573/604/1572/3528
trinket2=,id=147275,bonus_id=605/3573/3164/3336
main_hand=,id=128861,gem_id=140840/137303/155855,bonus_id=726,relic_id=3444:1502:3337/3573:1562:3528/3613:1467:3528

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:

Turning on Scaling for Agility, Mastery, Crit, Haste, Versatility. Importing through simcraft ingame addon. 
Starting the simulation.

**Comment by kaeptnJ** [comment]
Edit: on the 7.3.5 Live Version the same bug appears.

**Comment by scamille** [comment]
Sorry for not really being able to help, but we just don't have the resources to debug all exotic GUI problems :-/

From a code perspective, I would say it is very unlikely that this has anything to do with scale factor generation itself, and is still some specific Qt/GPU problem, even if it happens specifically on scale factor sims.

We nowadays recommend Raidbots as a web-based alternative for you, or if still want to do massive sims locally try out the command line interface (simc.exe).
