### ISSUE TITLE
Wrong calculation with Ulduar timewarp items

### ISSUE THREAD

**Issue by hoaaarrrhh** [simulationcraft/simc#4284]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
calculation with items from Ulduar show wrong dps
all items from Ulduar are handled with itemlevels between 219 and 226
![zwischenablage06](https://user-images.githubusercontent.com/36855811/36681474-097acd68-1b19-11e8-9e12-ec5cac8870c0.jpg)
should be 930 or 945 for correct calculation

**Comment by lgkern** [comment]
You're likely not using the option `drop_level=110` at the end of the item, as reported on https://github.com/simulationcraft/simc/issues/3913

> These have the correct Id/bonus to correspond to TW versions they just need a drop_level=x to sim correctly (where x is your true player level when they were acquired). The add-on correctly adds this (as do wowhead/raidbots) I suspect that you used an armory import however which does not supply that information in the API so is unavailable to us.
