### ISSUE TITLE
Link to downloads fail

### ISSUE THREAD

**Issue by Namaroka** [simulationcraft/simc#4286]
Please include a brief overview of the issue in the title above, as well as completing the following:

I'm trying to download the Newest version of simulation craft. When I click on the link i get sent to "page not found"

**Comment by lgkern** [comment]
Hello, 

I've just tested all three download links (Win32, Win64, and OSX) at the [downloads page](http://simulationcraft.org/download.html) and they all seem to be working. Where did you try to download it?

Edit: Ah I see, the .7z files are missing. We will fix it soon. In the meantime, you can use the installers if you'd like.

**Comment by lgkern** [comment]
The links should now be fixed, thanks to your report! If you need further help with downloads, re-open this issue.
