### ISSUE TITLE
Sim Freezes in Menu

### ISSUE THREAD

**Issue by Arcadius8925** [simulationcraft/simc#4287]
Version = http://downloads.simulationcraft.org/SimcSetup-735-02-Win32.exe

When I go to type in my Characters name to import data simcraft just stops. I can change primary menu tabs but not secondary either. What am I doing wrong here? Never had this issue with simcraft before.

**Comment by thunderchylde** [comment]
I've had this problem too I think - can't interact with most of the UI

**Comment by scamille** [comment]
Can you please try again with the latest SimC nightly and updated graphic drivers?

See #4450 for how this resolved the problem in that case.
