### ISSUE TITLE
Simulation runtime error: Unknown scaling metric 'Raid_DPS'

### ISSUE THREAD

**Issue by WhoTHCares** [simulationcraft/simc#4288]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents - https://pastebin.com/Mf6XYusv
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by lgkern** [comment]
Hello, 
Unfortunately, you won't be able to use it to show scaled DPS, that option, in fact, hasn't existed in the last five years at least, according to commit history. I've removed it from the wiki page to reflect that. You can find all currently supported options at https://github.com/simulationcraft/simc/blob/c0b899ebf24e37ebe4b08202b894a700d7a9cebc/engine/sc_util.cpp#L1584
