### ISSUE TITLE
simc cmd api

### ISSUE THREAD

**Issue by hershko765** [simulationcraft/simc#4296]
Not much of issue but more of a question, i wanna create server like raidbots that will calculate the sims trough simulationcraft, now for that i need somekind of API to the simulationcraft software, is there such a think? or the only way to sim is trough the software UI?

**Comment by lgkern** [comment]
SimC supports command line input. The format is the same as the .simc file. 
I.e. `simc.exe iterations=10000 max_time=300 my_profile.simc`
For more information check out [the wiki](https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface) about the profile syntax
