### ISSUE TITLE
Fury Warrior talent War Machine is not implemented

### ISSUE THREAD

**Issue by penguinlust** [simulationcraft/simc#4299]
Please include a brief overview of the issue in the title above, as well as completing the following:
Taking the talent War Machine for Fury Warrior seems to do absolutely nothing on fights it should affect (e.g. Beastlord)

#### Simulationcraft Version
703-02 to current

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files

NA

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

NA

#### Reproduction Steps:

Simulate  a Fury Warrior with the War Machine talent on any fight with add(s). It does nothing. Looking at the code in engine/class_modules/sc_warrior.cpp, it appears it's just a placeholder

**Comment by Bloodmallet** [comment]
Yes, it seems that talent isn't fully implemented. If you can, please clone the repo, fix the problem and create a pull request.

**Comment by penguinlust** [comment]
If I knew where to put the hooks in the combat resolution system I would. Don't know where adds in fights get killed off in the code -- was unable to find it in the engine. There is someone assigned to this bug already in its earlier incarnation.

**Comment by vekk513** [comment]
Was digging into this, and admittedly I only just started looking at code and am NOT at all experienced with simc, but I found this comment in the sc_sim.cpp file, line 1942:
`      const player_t* t = target_list[ i ];`
      `// Once we start hitting adds (instead of real enemies), break out as those don't have real`
      `// hitpoints.`
     ` if ( t -> is_add() )`
      `{`
            `break;`
      `}`

Does the sim even track if adds die? I haven't been able to find anything related to adds dying.

**Comment by penguinlust** [comment]
So I think I figured out where this can be hooked in. Override acquire_target() for warriors and simply add a check if passed in retarget_event_e == ACTOR_DEMISE and the warrior in question has the talent then apply the buff. The obviously call the base method. I need to play with this in game (lots of falcosaurs are about to die) to see if it stacks (doubtful) or extends the duration if active and another applicable target dies (likely). Also need to figure out how to instantiate it as a buff as this code is missing (another clue that it was never implemented)

Hopefully I'll get this done before 8.0 hits. If anyone reading this can take this and run with it -- go for it.

**Comment by penguinlust** [comment]
I got it at least have some effect and show up in the report. Not really working yet, but on beastlord it now shows up if I have it talented. Doesn't do what's it's supposed to, but progress

**Comment by vituscze** [comment]
Look at `player_t::callbacks_on_demise`. Should be able to just add your own callback to that list for every enemy in the sim.

**Comment by penguinlust** [comment]
Thank you -- more progress. Means no need to override acquire_target() and it works just as well (plus that's the way it's supposed to be done). Everything is firing properly, just need it to do the buff properly.

**Comment by penguinlust** [comment]
Now have it firing and expiring when expected. Just need the buff to actually do something. I've found the values in sc_spell_data.inc, fixed the bad duration for war machine (it's listed as 0 instead of 15000), found the default haste and movement bonuses, but I'm missing something in actually applying them -- nothing happens

**Comment by vituscze** [comment]
You need to add it to `warrior_t::composite_melee_haste`. Also, spell id 215562 seems to have the correct duration and values.

**Comment by penguinlust** [comment]
Was looking at 215556, which points at 215562. 215556 has 0 for the duration. Will give it a shot with 215562. Used 215556 as it had the string that matches the tooltip in game.

It's due to things like this that I keep posting here. Thanks for the help.

**Comment by vituscze** [comment]
You can run `./simc spell_query=spell.name=war_machine`. One of the spells it finds is

```
Name             : War Machine (id=215562) [Spell Family (4)]
Class            : Warrior
School           : Physical
Duration         : 15 seconds
Attributes       : ........ ........ ..x..... ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ xx...... ........
                 : ........ ........ .......x ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : Disable player procs (112), Disable target procs (113), Disable weapon procs (151)
Effects          :
#1 (id=320514)   : Apply Aura (6) | Modify All Haste% (193)
                   Base Value: 30 | Scaled Value: 30 | Target: Self (1)
#2 (id=320515)   : Apply Aura (6) | Increase Speed% (31)
                   Base Value: 30 | Scaled Value: 30 | Target: Self (1)
Description      : $@spelldesc215556
Tooltip          : Haste increased by $s1%. Movement speed increased by $s2%.
```

Another option is to check what's the spell id of the buff applied in game (rather than trying to find it on wowhead etc).

**Comment by penguinlust** [comment]
Thanks for the tip -- noticed the other two the above listed are 215556 and 215557, but yes, 215562 looks correct in this form. Will give it a shot this evening when I get back home.

Learning experience -- thanks for the help!

**Comment by penguinlust** [comment]
I think I have it working! Getting the correct spell number was all it took. Just going to do a bit of testing and make sure the code is clean and I'll post a pull request.

**Comment by penguinlust** [comment]
Assuming I can push the branch up.

% git push -f origin war_machine
Username for 'https://github.com': penguinlust
Password for 'https://penguinlust@github.com': 
remote: Permission to simulationcraft/simc.git denied to penguinlust.
fatal: unable to access 'https://github.com/simulationcraft/simc.git/': The requested URL returned error: 403

I was able to create the branch, add to it, commit to it, but the final push fails.

**Comment by penguinlust** [comment]
Was told to fork the sources, then do the work. That worked. Pull request made.

**Comment by penguinlust** [comment]
Code was integrated into the legion-dev branch this morning. Closing
