### ISSUE TITLE
Please fix what appears to be a massive memory leak

### ISSUE THREAD

**Issue by mgretzin** [simulationcraft/simc#4300]
I very much like this program and appreciate all the hard work that goes into it.  However, there is what appears to be a memory leak that has been around for many versions of the program.

Each simulation run eats up a chunk of virtual memory that is never released.  After 25-30 runs the "Commit size" of SimulationCraft.exe gets to about 4,700,000 K, and it crashes.  This has been the case as long as I've used it (about a year).  As I'm often doing many simulations to find the best combination of things, I often run up against this limit.  It wouldn't be quite as bad if the program retained the Results windows as it does with the Simulate windows, but it doesn't.

#### Simulationcraft Version
735-01 and previous versions (Win x64)

#### Reproduction Steps:
Run any simulation 25-30 times and watch the virtual memory increase until it crashes.

**Comment by Bloodmallet** [comment]
Please provide an input that creates that issue for you. 

And what do you mean by "25-30 runs". Are you redoing the same simulation over and over again?

A detailed description of what you're doing for us to follow, can help find the problem.

**Comment by mgretzin** [comment]
Every time I run a simulation of any kind, it consumes a little more virtual memory.  As an example, say I've just received a new piece of legendary gear.  I want to find some combination of gear and/or talents that includes that piece and raises my DPS.  It may take me a while to go through the available combinations.  I check the commit size in Task Explorer after every few simulations.  Once it exceeds about 5GB of memory, I can expect it to crash the next time I press the Simulate! button, usually at the point that it is trying to display the results.   This has been the case for the year or so that I have been using the program.  I have also seen this on three different computers running Windows 10.  

I just ran 10 simulations and recorded the memory usage:

Run | VM (MB) | ∆ VM
0 | 378 |  
1 | 521 | 143
2 | 658 | 137
3 | 798 | 140
4 | 943 | 145
5 | 1087 | 144
6 | 1234 | 147
7 | 1378 | 144
8 | 1524 | 146
9 | 1669 | 145
10 | 1814 | 145
Average   increase:  143.6 MB

I then closed each result window to see how much memory was released, which on average was about 4.7 MB per window.

Is it possible you're never releasing the browser control from the results windows?

**Comment by navv1234** [comment]
This is a relatively known issue in the GUI, the reason being there's some stuff underneath when you close the window that still keeps a reference to it elsewhere.

**Comment by scamille** [comment]
I made some changes so that you should get memory back if you close a results tab.
This should help enough for you use case, I think. Most memory just seems to be taken by the WebView for the html page, and not a memory leak in SimC itself. So in any case, you can not have unlimited results page open and need to close some at some point, which should now correctly free its objects.
