### ISSUE TITLE
Error in my simulationcrarf

### ISSUE THREAD

**Issue by Romerocarlosgaldino** [simulationcraft/simc#4301]
SimulationCraft encountered an error!

Simulation setup error:
Nothing to sim!

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Nothing to sim!

## All options used for simulation:
``` ini
### SimulationCraft 735-01 for World of Warcraft 7.3.5 Live (wow build 25901) ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HeavyMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery
reforge_plot_stat=crit,haste,mastery
reforge_plot_amount=500
reforge_plot_step=50
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment]
Your simulate tab appears to be empty. Make sure that you include character information of some sort on the simulate tab; there are plenty of guides around the internet including on the wiki here or you can simply use the simc addon to output the requisite text in-game.

You need to supply some form of simulation text or as the error says there will be "Nothing to sim!"
