### ISSUE TITLE
simcraft tabs not showing

### ISSUE THREAD

**Issue by Cytoon** [simulationcraft/simc#4304]
I can't properly switch between tabs like options or results or simulate, the programm visualy freezes if im on one of these tabs.
I can freely switch between the help and welcome tab and I can switch from help or welcome to one of the other ones but then in stuck there and the programm does not react on a visual level unless i go back to help or welcome. 
I can use the dropdown menus on options but my choice will only be visible after i switched to help or welcome and then back to options.
I dont know what to do, I've tried 32 and 64 bit versions aswell as the 7z files and installers and a nightly build. All have the same problem and it came out of nowhere after it working properly for a few days

**Comment by scamille** [comment]
Please try again with the latest nightly build from today: http://downloads.simulationcraft.org/?C=M;O=D

**Comment by scamille** [comment]
Please try again using a 8.x nightly release. The new GUI library version used there should have solved that once and for all.
Otherwise reopen and include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files
