### ISSUE TITLE
isolate simc

### ISSUE THREAD

**Issue by roeehershko** [simulationcraft/simc#4309]
i am trying to isolate the project, i am trying create docker container out of it, 
my c++ knowledge is eh.. i am coming from nodejs/php world where external libraries are part of the project and located in the same directory 

is there a way to change the libraries include path? like instead of 
```
/var/usr/lib 
```
to take it from 
```
/root/my-simc-project/lib
```

i tried using the "OPENSSL_PATH" it got me trough some errors but got stuck right in the end of the compile process with this error - 
```
[simc] Compiling git_info.cpp
[simc] Linking simc
/usr/bin/ld: cannot find -lssl
```

**Comment by scamille** [comment]
Try 'make LINK_LIBS=/root/my-simc-project/lib'

If that does not work: engine/Makefile is the place where compiler settings are set. You can eg. Manually add your path in there and report back with what exactly works.

**Comment by roeehershko** [comment]
getting now
```
cannot find /root/my-simc-project/usr/lib, file format not recognized
```
after adding "LINK_LIBS += /root/my-simc-project/usr/lib", i wonder why it look for directory and not a single file, i figured it get stuck on this line
```
	$(CXX) $(CPP_FLAGS) -DUNIT_TEST $(OPTS) $(LINK_FLAGS) $^ $(LINK_LIBS) -o $@
```
but its all Chinese to me

**Comment by scamille** [comment]
Have you tried our now improved Cmake solution?

I would assume you should be able to specify lib search paths for cmake somehow.

**Comment by navv1234** [comment]
-L/root/my-simc-project/usr/lib

**Comment by scamille** [comment]
Closing this, as there is now a [Dockerfile](https://github.com/simulationcraft/simc/blob/shadowlands/Dockerfile) available, which is also integrated into our CI test pipeline.
