### ISSUE TITLE
Imported character is in the wrong spec

### ISSUE THREAD

**Issue by oleyungin** [simulationcraft/simc#4310]
Please include a brief overview of the issue in the title above, as well as completing the following:
Im a frost dk not an unholy one. When I import, my spec is unholy and runs a simulation for an unholy dk
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

DPS Ranking:
 888268 100.0%  Raid
 888268  100.0%  Azaaquira

HPS Ranking:
      0 100.0%  Raid

Player: Azaaquira orc deathknight unholy 110
  DPS: 888268.3  DPS-Error=1773.7/0.200%  DPS-Range=130451/14.7%  DPS-Convergence=69.0%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=76821.8  RPS-Out=8.1 RPS-In=8.1  Resource=(runic_power) Waiting=9.7 ApM=49.7
  Origin: https://us.api.battle.net/wow/character/thrall/azaaquira/advanced
  Talents: https://worldofwarcraft.com/en-us/game/talent-calculator#death-knight/unholy/talents=3231331
  Artifact: 
  Core Stats:    strength=45392|43686(42119)  agility=7854|7529(7529)  stamina=91703|87337(54419)  intellect=4326|4001(4001)  spirit=0|0(0)  health=5502180|5240220  mana=0|0
  Generic Stats: mastery=61.29%|59.17%(7321)  versatility=9.38%|9.38%(4455)  leech=2.58%|2.58%(594)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=15.00%|15.00%(0)  crit=23.90%|23.90%(7560)  haste=24.85%|24.85%(9319)  speed=24.85%|24.85%  manareg=0|0(0)
  Attack Stats:  power=45392|43686(0)  hit=7.50%|7.50%(0)  crit=23.90%|23.90%(7560)  expertise=7.50%|7.50%(0)  haste=24.85%|24.85%(9319)  speed=24.85%|24.85%
  Defense Stats: armor=5236|4987(4987) miss=3.00%|3.00%  dodge=6.00%|6.00%(0)  parry=26.94%|26.26%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=4.69%|4.69%(4455)
  Priorities (actions.precombat):
    flask/food/augmentation/snapshot_stats/potion/raise_dead/army_of_the_dead
    blighted_rune_weapon
  Priorities:
    auto_attack/mind_freeze
    arcane_torrent,if=runic_power.deficit>20&(pet.valkyr_battlemaiden.active|!talent.dark_arbiter.enabled)
    blood_fury,if=pet.valkyr_battlemaiden.active|!talent.dark_arbiter.enabled
    berserking,if=pet.valkyr_battlemaiden.active|!talent.dark_arbiter.enabled
    use_items
    use_item,name=feloiled_infernal_machine,if=pet.valkyr_battlemaiden.active|!talent.dark_arbiter.enabled
    use_item,name=ring_of_collapsing_futures,if=(buff.temptation.stack=0&target.time_to_die>60)|target.time_to_die<60
    potion,if=buff.unholy_strength.react
    blighted_rune_weapon,if=debuff.festering_wound.stack<=4
    outbreak,target_if=(dot.virulent_plague.tick_time_remains+tick_time<=dot.virulent_plague.remains)&dot.virulent_plague.remains<=gcd
    call_action_list,name=cooldowns
    run_action_list,name=valkyr,if=pet.valkyr_battlemaiden.active&talent.dark_arbiter.enabled
    call_action_list,name=generic
  Priorities (actions.valkyr):
    death_coil
    festering_strike,if=debuff.festering_wound.stack<6&cooldown.apocalypse.remains<3
    call_action_list,name=aoe,if=active_enemies>=2
    festering_strike,if=debuff.festering_wound.stack<=4
    scourge_strike,if=debuff.festering_wound.up
    clawing_shadows,if=debuff.festering_wound.up
  Priorities (actions.generic):
    scourge_strike,if=debuff.soul_reaper.up&debuff.festering_wound.up
    clawing_shadows,if=debuff.soul_reaper.up&debuff.festering_wound.up
    death_coil,if=runic_power.deficit<22&(talent.shadow_infusion.enabled|(!talent.dark_arbiter.enabled|cooldown.dark_arbiter.remains>5))
    death_coil,if=!buff.necrosis.up&buff.sudden_doom.react&((!talent.dark_arbiter.enabled&rune<=3)|cooldown.dark_arbiter.remains>5)
    festering_strike,if=debuff.festering_wound.stack<6&cooldown.apocalypse.remains<=6
    defile/call_action_list,name=aoe,if=active_enemies>=2
    festering_strike,if=(buff.blighted_rune_weapon.stack*2+debuff.festering_wound.stack)<=2|((buff.blighted_rune_weapon.stack*2+debuff.festering_wound.stack)<=4&talent.castigator.enabled)&(cooldown.army_of_the_dead.remains>5|rune.time_to_4<=gcd)
    death_coil,if=!buff.necrosis.up&talent.necrosis.enabled&rune.time_to_4>=gcd
    scourge_strike,if=(buff.necrosis.up|buff.unholy_strength.react|rune>=2)&debuff.festering_wound.stack>=1&(debuff.festering_wound.stack>=3|!(talent.castigator.enabled|equipped.132448))&(cooldown.army_of_the_dead.remains>5|rune.time_to_4<=gcd)
    clawing_shadows,if=(buff.necrosis.up|buff.unholy_strength.react|rune>=2)&debuff.festering_wound.stack>=1&(debuff.festering_wound.stack>=3|!equipped.132448)&(cooldown.army_of_the_dead.remains>5|rune.time_to_4<=gcd)
    death_coil,if=(talent.dark_arbiter.enabled&cooldown.dark_arbiter.remains>10)|!talent.dark_arbiter.enabled
  Priorities (actions.cooldowns):
    call_action_list,name=cold_heart,if=equipped.cold_heart&buff.cold_heart.stack>10&!debuff.soul_reaper.up
    army_of_the_dead/apocalypse,if=debuff.festering_wound.stack>=6
    dark_arbiter,if=(!equipped.137075|cooldown.dark_transformation.remains<2)&runic_power.deficit<30
    summon_gargoyle,if=(!equipped.137075|cooldown.dark_transformation.remains<10)&rune.time_to_4>=gcd
    soul_reaper,if=(debuff.festering_wound.stack>=6&cooldown.apocalypse.remains<=gcd)|(debuff.festering_wound.stack>=3&rune>=3&cooldown.apocalypse.remains>20)
    call_action_list,name=dt,if=cooldown.dark_transformation.ready
  Priorities (actions.dt):
    dark_transformation,if=equipped.137075&talent.dark_arbiter.enabled&(talent.shadow_infusion.enabled|cooldown.dark_arbiter.remains>52)&cooldown.dark_arbiter.remains>30&!equipped.140806
    dark_transformation,if=equipped.137075&(talent.shadow_infusion.enabled|cooldown.dark_arbiter.remains>(52*1.333))&equipped.140806&cooldown.dark_arbiter.remains>(30*1.333)
    dark_transformation,if=equipped.137075&target.time_to_die<cooldown.dark_arbiter.remains-8
    dark_transformation,if=equipped.137075&(talent.shadow_infusion.enabled|cooldown.summon_gargoyle.remains>55)&cooldown.summon_gargoyle.remains>35
    dark_transformation,if=equipped.137075&target.time_to_die<cooldown.summon_gargoyle.remains-8
    dark_transformation,if=!equipped.137075&rune.time_to_4>=gcd
  Actions:
    apocalypse          Count=  3.7| 90.76sec  DPE= 672318| 1%  DPET=594245  DPR=    0.0  pDPS=  8298  Miss=0.00%  Hit=539064|495204|693710  Crit=1078118|990407|1387419|24.7%
    auto_attack_mh      Count=110.2|  2.78sec  DPE=  75329| 3%  DPET= 27411  DPR=    0.0  pDPS= 27340  Miss=0.00%  Hit=60805|55745|78448  Crit=121581|111490|156895|23.9%
    blood_fury          Count=  3.0|120.86sec  DPE=      0| 0%  DPET=     0  DPR=    0.0  pDPS=     0
    chilling_nova       Count=  5.1| 60.45sec  DPE= 322947| 1%  DPET=     0  DPR=    0.0  pDPS=  5477  Miss=0.00%  Hit=260760|252957|290900  Crit=520368|505913|581800|24.0%
    clawing_shadows     Count= 94.1|  3.11sec  DPE= 359664|13%  DPET=308122  DPR=    0.0  pDPS=111499  Miss=0.00%  Hit=289999|236794|431229  Crit=580534|473588|862458|24.0%
    dark_arbiter        Count=  3.0|120.72sec  DPE=      0| 0%  DPET=     0  DPR=    0.0  pDPS=     0
    dark_transformation  Count=  5.5| 60.99sec  DPE=      0| 0%  DPET=     0  DPR=    0.0  pDPS=     0
    death_coil          Count= 79.0|  3.78sec  DPE= 424154|12%  DPET=366232  DPR=13620.3  pDPS=110457  Miss=0.00%  Hit=342126|304382|458833  Crit=684236|608765|917667|24.0%
    dragged_to_helheim  Count= 45.6| 62.64sec  DPE= 145835| 2%  DPET=     0  DPR=    0.0  pDPS= 22089  Miss=0.00%  Hit=181305|164820|216047  Crit=362598|329640|432094|23.9%
    festering_strike    Count= 35.6|  8.55sec  DPE= 482968| 6%  DPET=421556  DPR=    0.0  pDPS= 56719  Miss=0.00%  Hit=389332|354252|496258  Crit=778583|708504|992516|24.1%
    festering_wound     Count=153.4|  2.23sec  DPE= 204607|12%  DPET=     0  DPR=    0.0  pDPS=103502  Miss=0.00%  Hit=165069|147209|221906  Crit=330283|294418|443812|23.9%
    necrobomb           Count=  8.6| 33.41sec  DPE= 520439| 2%  DPET=     0  DPR=    0.0  pDPS= 14823  Miss=0.00%  Hit=419605|388467|509203  Crit=839992|776934|1018407|24.0%
    outbreak            Count= 16.4| 19.13sec  DPE=  55514| 0%  DPET= 47374  DPR=    0.0  pDPS=  2997  Miss=0.00%  Hit=44972|40595|61193  Crit=89982|81189|122387|23.4%
    pestilence          Count= 24.2| 14.00sec  DPE=  84913| 1%  DPET=     0  DPR=    0.0  pDPS=  6845  TickCount=66  MissTick=0.0%  Tick=30963|2680|46018  UpTime=21.4%
    spear_of_light      Count=  5.6| 60.25sec  DPE= 204098| 0%  DPET=     0  DPR=    0.0  pDPS=  3769  Miss=0.00%  Hit=164743|163841|188417  Crit=329693|327682|376834|23.9%
    virulent_eruption   Count= 61.4|  4.92sec  DPE= 199488| 5%  DPET=     0  DPR=    0.0  pDPS= 40336  Miss=0.00%  Hit=160944|144944|218492  Crit=321620|289888|436984|24.0%
    virulent_plague     Count=113.7|  2.67sec  DPE= 407698|13%  DPET=     0  DPR=    0.0  pDPS=112224  TickCount=205  MissTick=0.0%  Tick=134608|81|183533  CritTick=269076|162|367067|23.9%  UpTime=99.5%
   valkyr_battlemaiden  (DPS=658920.4)
    valkyr_strike       Count= 39.9|  6.45sec  DPE=1095579|16%  DPET=757830  DPR=    0.0  pDPS=658920  Miss=0.00%  Hit=882262|226455|1987046  Crit=1770207|452911|4219071|24.1%
   sludge_belcher  (DPS=83252.5)
    cleaver             Count= 74.8|  4.05sec  DPE=  50796| 1%  DPET= 33763  DPR= 1269.8  pDPS= 12502  Miss=0.00%  Hit=41079|38127|137664  Crit=82229|76254|228761|23.6%
    main_hand           Count=196.8|  1.54sec  DPE=  50527| 4%  DPET= 32789  DPR=    0.0  pDPS= 32784  Miss=0.00%  Hit=40811|18911|74365  Crit=81447|37822|148731|23.9%
    powerful_smash      Count=  3.1|115.48sec  DPE=  95826| 0%  DPET= 63697  DPR=    0.0  pDPS=   977  Miss=0.00%  Hit=78095|23639|92957  Crit=156453|56901|185914|22.6%
    vile_gas            Count= 76.2|  3.86sec  DPE= 146905| 4%  DPET=146248  DPR= 3673.2  pDPS= 36990  Miss=0.00%  Hit=118391|107616|141063  Crit=236979|215232|282127|24.0%
   army_ghoul  (DPS=175565.5)
    claw                Count=184.0|  1.50sec  DPE=  16734| 1%  DPET= 11156  DPR=  418.3  pDPS= 90560  Miss=0.00%  Hit=13502|12472|15454  Crit=27015|24943|30908|23.9%
    main_hand           Count=216.0|  1.23sec  DPE=  13381| 1%  DPET= 10742  DPR=    0.0  pDPS= 85006  Miss=0.00%  Hit=10810|9977|12363  Crit=21622|19955|24727|23.8%
   apocalypse_ghoul  (DPS=111604.5)
    claw                Count=138.4| 11.65sec  DPE=  16089| 1%  DPET= 10726  DPR=  402.1  pDPS= 60832  Miss=0.00%  Hit=12989|11790|15454  Crit=25968|23580|30908|23.9%
    main_hand           Count=143.7| 11.08sec  DPE=  12908| 1%  DPET=  8735  DPR=    0.0  pDPS= 50773  Miss=0.00%  Hit=10416|9432|12363  Crit=20825|18864|24727|23.9%
  Constant Buffs: defiled_augmentation/flask_of_the_countless_armies/nightborne_delicacy_platter/stoneskin_gargoyle
  Dynamic Buffs:
    blood_fury                             : start= 3.0 refresh=  0.0 interval=120.8 trigger=120.8 uptime=14.16%  benefit=14%
    bloodlust                              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.48%  benefit=13%
    chilling_nova                          : start= 5.1 refresh=  0.0 interval= 60.4 trigger= 60.4 uptime=19.89%  benefit=20%
    concordance_of_the_legionfall          : start= 8.5 refresh=  3.1 interval= 35.2 trigger= 25.1 uptime=32.30%  benefit=32%
    dark_transformation                    : start= 5.5 refresh=  0.0 interval= 60.9 trigger= 60.9 uptime=47.90%  benefit=50%
    potion_of_prolonged_power              : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=19.55%  benefit=20%
    runic_corruption                       : start=32.1 refresh=  0.0 interval=  9.3 trigger=  9.3 uptime=26.97%  benefit=27%
    sudden_doom                            : start=23.9 refresh=  0.7 interval= 12.7 trigger= 12.5 uptime= 9.83%  benefit=10%
    valkyr_battlemaiden-shadow_empowerment : start= 3.0 refresh=  0.0 interval=121.0 trigger=121.0 uptime=94.25%  benefit=100%
  Up-Times:
      1.7% : Runic Power Cap               
  Procs:
    180.5 |   1.93sec : Rune ready
  Gains:
        33.9 : army_of_the_dead       (runic_power)
       180.9 : outbreak               (runic_power)  (overflow=2.3%)
      1059.3 : clawing_shadows        (runic_power)
       799.8 : festering_strike       (runic_power)
         7.5 : Death's Harbinger      (rune)
       453.5 : Festering Wound        (runic_power)  (overflow=1.4%)
       139.5 : Rune Regeneration      (rune)
        18.5 : Pestilent Pustules     (rune)
        15.0 : Scourge the Unbeliever (rune)
    Pet "sludge_belcher" Gains:
       789.6 : Unholy Vigor (energy)
      5167.5 : energy_regen (energy)
    Pet "army_ghoul" Gains:
       886.0 : energy_regen (energy)
    Pet "apocalypse_ghoul" Gains:
       658.3 : energy_regen (energy)
  Waiting: 9.70%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=0.0  RPS-Out=883656.4 RPS-In=883656.4  Resource=(health) Waiting=0.0 ApM=0.0
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|212906833  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.46%  benefit=12%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.31%  benefit=11%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.73%  benefit=12%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.33%  benefit=11%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.11%  benefit=11%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.26%  benefit=11%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.03%  benefit=13%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.75%  benefit= 9%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 3.79%  benefit= 4%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 5.24%  benefit= 5%
    death                    : start= 4.8 refresh= 19.5 interval= 64.7 trigger= 10.9 uptime=19.92%  benefit=27%
    festering_wound          : start= 3.3 refresh= 85.2 interval= 66.2 trigger=  3.4 uptime=98.54%  benefit=99%
    scourge_of_worlds        : start=17.2 refresh=  8.9 interval= 17.4 trigger= 11.3 uptime=42.77%  benefit=43%
  Waiting: 0.00%
Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 1690 (213, 212, 206, 212, 213, 212, 208, 214)
  TotalEvents   = 8040452
  MaxEventQueue = 96
  TargetHealth  = 212906833
  SimSeconds    = 513888
  CpuSeconds    = 8.198
  WallSeconds   = 1.200
  InitSeconds   = 0.090317
  MergeSeconds  = 0.005722
  AnalyzeSeconds= 0.003159
  SpeedUp       = 62685
  EndTime       = 2018-04-24 20:28:42-0400 (1524616122)

Waiting:
     9.7% : Azaaquira

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Kutikuti** [comment]
Try with the 735-02 nightly http://downloads.simulationcraft.org/?C=M;O=D
it seems to work fine with the latest version

**Comment by Kutikuti** [comment]
Try with the 735-02 nightly http://downloads.simulationcraft.org/?C=M;O=D
it seems to work fine with the latest version
