### ISSUE TITLE
Cannot click tabs. Have to reinstall every time.

### ISSUE THREAD

**Issue by saraneth0o** [simulationcraft/simc#4313]
I see this is an issue that has been around for a long time and never seems to get fixed. The latest issue for it was just closed a few days ago.
I have tried both 64bit and 32bit versions. Both release builds and nightly builds.

When I first install it all works find. If I close the app though when I open it again I can only click Welcome, Import, Help and Log. The other ones are locked out for some reason. Restarting the PC does not help. Only reinstalling.

Let me know of any info you may need.

Edit: Ok! Now it's doing it after a fresh reinstall. I can sometimes click the simulate tab but then cannot paste anything into it.

**Comment by saraneth0o** [comment]
Ok, I have figured out it is working. Kind of. While on the Options and Simulate tabs anything you do looks like it's not wokring. It is though. It's just not drawing it. If you click the Welcome tab then click back to Options/Simulate you can see the changes that were made. So it works. You just cannot see it...

**Comment by saraneth0o** [comment]
Just reinstalled windows. Still having the same issue.

**Comment by Kutikuti** [comment]
Hi, can you try with the latest gpu drivers installed?

**Comment by saraneth0o** [comment]
Still no luck.

**Comment by ghost** [comment]
Still an issue in the latest version

**Comment by saraneth0o** [comment]
I have not come across this issue in the latest version. Cheers.
