### ISSUE TITLE
ticket sim issue

### ISSUE THREAD

**Issue by arythazin** [simulationcraft/simc#4316]
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Eissa action vuln_aim_casts : Unable to decode expression function 'action.aimed_shot.vuln_casts'
Eissa-vuln_aim_casts: Unable to build expression tree from action.aimed_shot.vuln_casts
Simulation has been canceled during player setup! (thread=0)                     
Player Eissa unable to parse 'variable' value 'action.aimed_shot.vuln_casts'
Player Eissa action can_gcd : Unable to decode expression function 'action.aimed_shot.cast_time'
Eissa-can_gcd: Unable to build expression tree from variable.vuln_window<action.aimed_shot.cast_time|variable.vuln_window>variable.vuln_aim_casts*action.aimed_shot.execute_time+gcd.max+0.1
Player Eissa unable to parse 'variable' value 'variable.vuln_window<action.aimed_shot.cast_time|variable.vuln_window>variable.vuln_aim_casts*action.aimed_shot.execute_time+gcd.max+0.1'
Player Eissa action arcane_shot : Unable to decode expression function 'action.aimed_shot.in_flight'
Eissa-arcane_shot: Unable to build expression tree from spell_targets.multishot=1&(!set_bonus.tier20_2pc|!action.aimed_shot.in_flight|buff.t20_2p_critical_aimed_damage.remains>action.aimed_shot.cast_time+gcd)&(variable.vuln_aim_casts>0|action.windburst.in_flight&!set_bonus.tier21_4pc)&variable.can_gcd&focus+cast_regen+action.aimed_shot.cast_regen<focus.max&(!variable.pooling_for_piercing|lowest_vuln_within.5>gcd)

## All options used for simulation:
``` ini
### SimulationCraft 735-02 for World of Warcraft 7.3.5 Live (wow build 25901) ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers,wdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.9.1

hunter="Eissa"
level=10
race=gnome
region=eu
server=silvermoon
role=attack

talents=0000000
spec=marksmanship

neck=,id=153130
shoulder=,id=122374,bonus_id=582
back=,id=59038
chest=,id=131205,bonus_id=3797,drop_level=10
wrist=,id=131516
hands=,id=131207,bonus_id=3797,drop_level=8
waist=,id=131448,bonus_id=3797,drop_level=9
legs=,id=131436,bonus_id=3797,drop_level=8
feet=,id=131458,bonus_id=3797,drop_level=10
trinket1=,id=122361,bonus_id=582
main_hand=,id=156940,bonus_id=3797,drop_level=8

### Gear from Bags
#
# Rugged Trapper's Vest (1)
# chest=,id=58232
#
# Battleworn Thrash Blade (15)
# main_hand=,id=122369,bonus_id=582
#
# Battleworn Thrash Blade (15)
# off_hand=,id=122369,bonus_id=582
#
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment]
Which version of SimulationCraft did you use exactly?

We can recommend the nightly builds from https://www.simulationcraft.org/download.html

**Comment by nuoHep** [comment]
Pretty sure it's simply an issue of the default apl being unprepared to sim level 10 characters.

Yeah, on `bfa-dev` setting the level to 12 works as it now can find Aimed Shot for the expressions. Not sure how we can fix that (or if it's even worth fixing) in the generic apl.

**Comment by scamille** [comment]
Oh level 10. I did not see that.

Fixing this is quite easy if the proper apl add_action functions are used which check for the spell being ok().

Anyway I'll close this now. We should at some point after BFA release check that low level chars at least import/sim something. But it certainly is low priority now.

**Comment by nuoHep** [comment]
We do use `add_action`, the setup fails not in the action creation but in expression 'creation'. Specifically it can't parse `action.aimed_shot.cast_time` for example because it can't create `aimed_shot` as the character is too low level.
