### ISSUE TITLE
Ticket Sim Issue. Assassination Rogue

### ISSUE THREAD

**Issue by Narzzrik** [simulationcraft/simc#4317]
When trying to simulate AssassinationT21 import this error pops ups:

Simulation runtime error:
Player Narzzrik action rupture : Unable to decode expression function 'exsanguinated' Narzzrik-rupture: Unable to build expression tree from combo_points>=cp_max_spend&refreshable&(pmultiplier4 Simulation has been canceled during player setup! (thread=0) Player Narzzrik action garrote : Unable to decode expression function 'exsanguinated' Narzzrik-garrote: Unable to build expression tree from talent.subterfuge.enabled&stealthed.rogue&refreshable&!exsanguinated Player Narzzrik action rupture : Unable to decode expression function 'exsanguinated' Narzzrik-rupture: Unable to build expression tree from combo_points>=4&refreshable&(pmultiplier6 Player Narzzrik action garrote : Unable to decode expression function 'exsanguinated' Narzzrik-garrote: Unable to build expression tree from (!talent.subterfuge.enabled|!(cooldown.vanish.up&cooldown.vendetta.remains=1&refreshable&(pmultiplier4 Player Narzzrik action garrote : Unable to decode expression function 'exsanguinated' Narzzrik-garrote: Unable to build expression tree from talent.subterfuge.enabled&combo_points.deficit>=1&set_bonus.tier20_4pc&((dot.garrote.remains=1&!set_bonus.tier20_4pc&refreshable&(!exsanguinated|remains2 Player Narzzrik action garrote : Unable to decode expression function 'exsanguinated' Narzzrik-garrote: Unable to build expression tree from talent.subterfuge.enabled&combo_points.deficit>=1&!set_bonus.tier20_4pc&remains2 Player Narzzrik action rupture : Unable to decode expression function 'exsanguinated' Narzzrik-rupture: Unable to build expression tree from combo_points>=4&refreshable&(pmultiplier6

**Comment by Mystler** [comment]
Can you specify what client and version you used to run the simulation?

**Comment by Narzzrik** [comment]
I'm not sure I know how exactly to look at that as I'm horrible with these
kind of things but I use Version 735-01.

2018-05-15 17:03 GMT+02:00 Florian Meißner <notifications@github.com>:

**Comment by Mystler** [comment]
Can you provide the steps how to reproduce the issue? I cannot reproduce it on my end. Furthermore, you can try running a newer [nightly build](http://downloads.simulationcraft.org/?C=M;O=D) of simc and see if that solves your problem.

**Comment by Mystler** [comment]
Since there was no reply in over a week i assume this is was resolved and can be closed.
