### ISSUE TITLE
Netherlight Crucible

### ISSUE THREAD

**Issue by Asjeel** [simulationcraft/simc#4318]
Please include a brief overview of the issue in the title above, as well as completing the following:

Can't find a database of relic traits.

I'm trying to determine if it's a good idea to put a different relic in my weapon and go for a different Legendary. (Havoc DH going from deleting his BiS-trait to going for -15sec on Meta-couldown, possibly/probably lining it up with Nemesis)

Problem is I can't find out what the numerical value for the Unleashed Demon trait is. I've backtraced the fact that 1739 is the +5 ilvl, 1001 is Chaos Strike, but now I need to replace one of the Chaos Strikes with Unleashed Demon.

Is there a database? If not is there a possibility to dig it out of the code (without having relics with the same two traits)?

Thanks in advance, can't find somewhere to post questions except for this bugreport, so sorry if I post on the wrong page.

**Comment by Mystler** [comment]
There are two ways to compare relics that I can mention here as options you have:
1) This does not answer your question but it is probably the easiest way to use the Relic Compare feature on Raidbots which offers a nice GUI and runs SimC in the cloud for you.
2) To get the artifact power ID of a trait that you need for the crucible line, you can use SimC spell queries. This works either in the GUI tab or via command line. You can there search for your artifact trait by name by converting the name to all lower case, removing special characters and replacing spaces with underscores. E.g.
![Spell Query](https://i.imgur.com/YP3Kus4.png)
This is from the CLI of SimC but it works similarly in the GUI.

**Comment by Mystler** [comment]
I will close this issue since the question has been answered and there were no further replies.
