### ISSUE TITLE
Retribution Simcraft issue saying to use Divine Storm for single target

### ISSUE THREAD

**Issue by Gynso** [simulationcraft/simc#4320]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents

DPS Ranking:
 771239 100.0%  Raid
 771239  100.0%  Gynnso

HPS Ranking:
      0 100.0%  Raid

Player: Gynnso human paladin retribution 110
  DPS: 771238.7  DPS-Error=385.3/0.050%  DPS-Range=109440/14.2%  DPS-Convergence=71.2%
  HPS: 0.0 HPS-Error=0.0/0.0%

  Origin: https://us.api.battle.net/wow/character/dalaran/gynnso/advanced
  Talents: https://worldofwarcraft.com/en-us/game/talent-calculator#paladin/retribution/talents=1312211
  Artifact: 
  Core Stats:    strength=36927|35153(32704)  agility=3200|3200(3200)  stamina=64746|64746(44241)  intellect=7328|7328(7328)  spirit=0|0(0)  health=3884760|3884760  mana=220000|220000
  Generic Stats: mastery=64.52%|64.52%(11549)  versatility=8.62%|8.62%(4093)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=36927|35153(0)  hit=15.00%|15.00%(0)  crit=17.48%|17.48%(4992)  haste=21.33%|20.31%(7615)  speed=21.33%|20.31%  manareg=3300|3300(0)
  Attack Stats:  power=36927|35153(0)  hit=7.50%|7.50%(0)  crit=17.48%|17.48%(4992)  expertise=7.50%|7.50%(0)  haste=21.33%|20.31%(7615)  speed=21.33%|20.31%
  Defense Stats: armor=3876|3876(3876) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=23.27%|22.40%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=4.31%|4.31%(4093)
  Priorities (actions.precombat):
    flask/food/augmentation/snapshot_stats/potion
  Priorities:
    auto_attack/rebuke/call_action_list,name=opener,if=time<2
    call_action_list,name=cooldowns/call_action_list,name=generators
  Priorities (actions.opener):
    blood_fury/berserking/arcane_torrent,if=!set_bonus.tier20_2pc/lights_judgment
    judgment
    blade_of_justice,if=equipped.137048|race.blood_elf|!cooldown.wake_of_ashes.up
    divine_hammer,if=equipped.137048|race.blood_elf|!cooldown.wake_of_ashes.up
    wake_of_ashes
  Priorities (actions.finishers):
    execution_sentence,if=spell_targets.divine_storm<=3&(cooldown.judgment.remains<gcd*4.25|debuff.judgment.remains>gcd*4.25)
    divine_storm,if=debuff.judgment.up&variable.ds_castable&buff.divine_purpose.react
    divine_storm,if=debuff.judgment.up&variable.ds_castable&(!talent.crusade.enabled|cooldown.crusade.remains>gcd*2)
    justicars_vengeance,if=debuff.judgment.up&buff.divine_purpose.react&!equipped.137020
    templars_verdict,if=debuff.judgment.up&buff.divine_purpose.react
    templars_verdict,if=debuff.judgment.up&(!talent.crusade.enabled|cooldown.crusade.remains>gcd*2)&(!talent.execution_sentence.enabled|cooldown.execution_sentence.remains>gcd)
  Priorities (actions.cooldowns):
    potion,if=(buff.bloodlust.react|buff.avenging_wrath.up|buff.crusade.up&buff.crusade.remains<25|target.time_to_die<=40)
    blood_fury/berserking
    arcane_torrent,if=(buff.crusade.up|buff.avenging_wrath.up)&holy_power=2&(cooldown.blade_of_justice.remains>gcd|cooldown.divine_hammer.remains>gcd)
    lights_judgment/holy_wrath/shield_of_vengeance/avenging_wrath
    crusade,if=holy_power>=3|((equipped.137048|race.blood_elf)&holy_power>=2)
  Priorities (actions.generators):
    variable,name=ds_castable,value=spell_targets.divine_storm>=2|(buff.scarlet_inquisitors_expurgation.stack>=29&(equipped.144358&(dot.wake_of_ashes.ticking&time>10|dot.wake_of_ashes.remains<gcd))|(buff.scarlet_inquisitors_expurgation.stack>=29&(buff.avenging_wrath.up|buff.crusade.up&buff.crusade.stack>=15|cooldown.crusade.remains>15&!buff.crusade.up)|cooldown.avenging_wrath.remains>15)&!equipped.144358)
    call_action_list,name=finishers,if=(buff.crusade.up&buff.crusade.stack<15|buff.liadrins_fury_unleashed.up)|(artifact.ashes_to_ashes.enabled&cooldown.wake_of_ashes.remains<gcd*2)
    call_action_list,name=finishers,if=talent.execution_sentence.enabled&(cooldown.judgment.remains<gcd*4.25|debuff.judgment.remains>gcd*4.25)&cooldown.execution_sentence.up|buff.whisper_of_the_nathrezim.up&buff.whisper_of_the_nathrezim.remains<gcd*1.5
    judgment,if=dot.execution_sentence.ticking&dot.execution_sentence.remains<gcd*2&debuff.judgment.remains<gcd*2|set_bonus.tier21_4pc
    blade_of_justice,if=holy_power<=2&(set_bonus.tier20_2pc|set_bonus.tier20_4pc)
    divine_hammer,if=holy_power<=2&(set_bonus.tier20_2pc|set_bonus.tier20_4pc)
    wake_of_ashes,if=(!raid_event.adds.exists|raid_event.adds.in>15)&(holy_power<=0|holy_power=1&(cooldown.blade_of_justice.remains>gcd|cooldown.divine_hammer.remains>gcd)|holy_power=2&((cooldown.zeal.charges_fractional<=0.65|cooldown.crusader_strike.charges_fractional<=0.65)))
    blade_of_justice,if=holy_power<=3&!set_bonus.tier20_4pc
    divine_hammer,if=holy_power<=3&!set_bonus.tier20_4pc/judgment
    call_action_list,name=finishers,if=buff.divine_purpose.up
    zeal,if=cooldown.zeal.charges_fractional>=1.65&holy_power<=4&(cooldown.blade_of_justice.remains>gcd*2|cooldown.divine_hammer.remains>gcd*2)&debuff.judgment.remains>gcd
    crusader_strike,if=cooldown.crusader_strike.charges_fractional>=1.65&holy_power<=4&(cooldown.blade_of_justice.remains>gcd*2|cooldown.divine_hammer.remains>gcd*2)&debuff.judgment.remains>gcd&(talent.greater_judgment.enabled|!set_bonus.tier20_4pc&talent.the_fires_of_justice.enabled)
    consecration
    hammer_of_justice,if=equipped.137065&target.health.pct>=75&holy_power<=4
    call_action_list,name=finishers/zeal/crusader_strike
  Actions:
    avenging_wrath            Count=  3.0|120.38sec  DPE=      0| 0%  DPET=     0  DPR=0.0  pDPS=     0
    blade_of_justice          Count= 45.0|  6.70sec  DPE= 944917|18%  DPET=792606  DPR=0.0  pDPS=141541  Miss=0.00%  Hit=804390|527768|1109050  Crit=1609278|1055537|2218099|17.5%
    crusader_strike           Count= 72.6|  4.09sec  DPE= 310974|10%  DPET=260499  DPR=0.0  pDPS= 75154  Miss=0.00%  Hit=219842|188167|299555  Crit=439510|376333|599110|41.5%
    divine_storm              Count= 77.1|  3.89sec  DPE= 745837|25%  DPET=627786  DPR=0.0  pDPS=191515  Miss=0.00%  Hit=634583|539423|858743  Crit=1269615|1078847|1717487|17.5%
    echoed_divine_storm       Count= 76.8|  3.88sec  DPE=  74101| 2%  DPET=     0  DPR=0.0  pDPS= 18942  Miss=0.00%  Hit=63055|30909|85874  Crit=126196|61817|171749|17.5%
    echoed_verdict            Count=  7.7| 21.32sec  DPE= 107294| 0%  DPET=     0  DPR=0.0  pDPS=  2752  Miss=0.00%  Hit=91347|54260|111669  Crit=183077|108521|223339|17.4%
    isolated_strike           Count= 21.7| 13.79sec  DPE= 286744| 3%  DPET=     0  DPR=0.0  pDPS= 20799  Miss=0.00%  Hit=244196|222629|300549  Crit=488430|445257|601097|17.4%
    judgment                  Count= 31.5|  9.79sec  DPE=1122651|15%  DPET=937765  DPR=0.0  pDPS=117651  Miss=0.00%  Hit=711620|604002|1049313  Crit=1438396|1208005|2098625|56.6%
    judgment_aoe              Count= 31.5|  9.74sec  DPE=      0| 0%  DPET=     0  DPR=0.0  pDPS=     0
    mark_of_the_hidden_satyr  Count= 18.1| 16.54sec  DPE= 171577| 1%  DPET=     0  DPR=0.0  pDPS= 10355  Miss=0.00%  Hit=146109|121605|211261  Crit=292087|243211|422521|17.4%
    melee                     Count=105.0|  2.86sec  DPE=  72344| 3%  DPET= 25330  DPR=0.0  pDPS= 25280  Miss=0.00%  Hit=61581|52767|84415  Crit=123133|105534|168830|17.5%
    potion                    Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=     0  DPR=0.0  pDPS=     0
    potion_of_the_old_war     Count= 24.8|  6.34sec  DPE= 238786| 3%  DPET=     0  DPR=0.0  pDPS= 19982  Miss=0.00%  Hit=203250|152236|205518  Crit=406469|304471|411036|17.5%
    shadow_strike             Count= 21.7| 13.79sec  DPE= 822013| 5%  DPET=     0  DPR=0.0  pDPS= 38831  Miss=0.00%  Hit=455878|415575|561027  Crit=911334|831151|1122054|17.4%
    shield_of_vengeance       Count=  4.3| 80.45sec  DPE=      0| 0%  DPET=     0  DPR=0.0  pDPS=     0  Miss=0.00%
    shield_of_vengeance_proc  Count=  4.3| 79.92sec  DPE= 975741| 2%  DPET=     0  DPR=0.0  pDPS= 13883  Miss=0.00%  Hit=1031768|802179|2064589
    templars_verdict          Count=  7.7| 21.39sec  DPE=1176624| 4%  DPET=948536  DPR=0.0  pDPS= 30442  Miss=0.00%  Hit=1001029|946967|1116693  Crit=2002225|1893934|2233385|17.5%
    wake_of_ashes             Count=  9.8| 32.44sec  DPE=1123019| 5%  DPET=950050  DPR=0.0  pDPS= 36472  Miss=0.00%  Hit=469830|403731|701387  Crit=939358|807462|1402774|17.5%  TickCount=58  MissTick=0.0%  Tick=82086|68099|118306  CritTick=164247|136198|236612|17.5%  UpTime=19.2%
    worldforgers_flame        Count= 28.8|  8.86sec  DPE= 287391| 4%  DPET=     0  DPR=0.0  pDPS= 27639  Miss=0.00%  Hit=244637|221973|299664  Crit=489220|443946|599327|17.5%
  Constant Buffs: azshari_salad/defiled_augmentation/flask_of_the_countless_armies
  Dynamic Buffs:
    avenging_wrath                : start= 3.0 refresh=  0.0 interval=120.4 trigger=120.4 uptime=26.68%  benefit=29%
    blade_of_wrath                : start=21.7 refresh=  6.7 interval= 14.0 trigger= 10.6 uptime=27.89%  benefit=28%
    bloodlust                     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.51%  benefit=14%
    concordance_of_the_legionfall : start= 8.3 refresh=  3.2 interval= 35.7 trigger= 25.1 uptime=32.33%  benefit=32%
    divine_purpose                : start=17.0 refresh=  0.0 interval= 16.7 trigger= 16.7 uptime=11.10%  benefit=11%
    potion_of_the_old_war         : start= 2.0 refresh=  0.0 interval=122.6 trigger=  0.0 uptime=16.21%  benefit=16%
    righteous_verdict             : start=43.6 refresh= 41.3 interval=  6.9 trigger=  3.5 uptime=68.05%  benefit=95%
    shield_of_vengeance           : start= 4.3 refresh=  0.0 interval= 80.4 trigger= 80.4 uptime=20.77%  benefit=21%
    worldforgers_flame            : start= 6.1 refresh=  1.8 interval= 46.7 trigger= 34.6 uptime=27.47%  benefit=27%
  Procs:
     17.0 |  16.70sec : divine_purpose
     28.5 |  10.59sec : blade_of_wrath
  Gains:
        89.9 : blade_of_justice (holy_power)
        46.0 : wake_of_ashes    (holy_power)  (overflow=5.7%)
        70.6 : crusader_strike  (holy_power)  (overflow=2.8%)
         0.0 : mp5_regen        (mana)  (overflow=100.0%)
  Scale Factors:
    Weights :  Str=13.43(0.42)  Int=0.00(0.00)  SP=0.00(0.00)  AP=0.00(0.00)  Crit=14.82(0.42)  Haste=18.19(0.42)  Mastery=11.46(0.42)  Vers=15.20(0.42)  Wdps=0.00(0.00)
    Wowhead : 
  Waiting: 3.02%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=0.0  RPS-Out=767894.3 RPS-In=767894.3  Resource=(health) Waiting=0.0 ApM=0.0
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|184522089  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.18%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.04%  benefit=11%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.34%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.69%  benefit=12%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.17%  benefit=10%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.13%  benefit= 9%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.93%  benefit=11%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.36%  benefit=11%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 7.47%  benefit= 7%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 5.69%  benefit= 6%
    judgment                 : start=27.9 refresh= 35.1 interval= 11.0 trigger=  4.8 uptime=82.04%  benefit=98%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 20048 (3475, 3326, 3302, 3358, 3279, 3308)
  TotalEvents   = 97731356
  MaxEventQueue = 30
  TargetHealth  = 184522089
  SimSeconds    = 6033110
  CpuSeconds    = 61.266
  WallSeconds   = 10.706
  InitSeconds   = 0.317230
  MergeSeconds  = 0.003264
  AnalyzeSeconds= 0.031959
  SpeedUp       = 98475
  EndTime       = 2018-05-24 17:27:25-0500 (1527200845)

Waiting:
     3.0% : Gynnso

Scale Factors:
  Gynnso  Str=13.43(0.42)  Int=0.00(0.00)  SP=0.00(0.00)  AP=0.00(0.00)  Crit=14.82(0.42)  Haste=18.19(0.42)  Mastery=11.46(0.42)  Vers=15.20(0.42)  Wdps=0.00(0.00)

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by scamille** [comment]
Please add some more information to the discussion next time, so we don't have to do that much guessing.

I assume you have a different opinion about some of the retribution action priority list?
If so, which lines exactly, why and what would be an improved solution?

Since this is legion, and legion development has pretty much stopped for quite a while now, I am going to close this.

If you have any improvements for BFA, feel free to open a new ticket. If you want to discuss best/optimal Action Priority List for your Class, we can also recommend going to your classes main theorycrafting Discord. Most class developers in SimC can be found there and discussing specific rotations can be done in much more detail than in a SimC ticket.
