### ISSUE TITLE
Survival stuck on invulnerable

### ISSUE THREAD

**Issue by Juliacare** [simulationcraft/simc#4324]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

SimulationCraft 735-02 for World of Warcraft 7.3.5 Live (wow build 25901, git build HEAD 3068eed13)

#### Reproduction Steps:

Use the raid event and simply run the survival t21 profile through it

The line below is causing the issue
> raid_events+=/invulnerable,first=170,duration=90,cooldown=100000

preview: https://www.raidbots.com/simbot/report/bThCux5EFBgnBLwQiYEZB7
input: https://pastebin.com/NETc4TAx

**Comment by Juliacare** [comment]
Bug occured again

FULL log: https://www.raidbots.com/reports/46KBwdH3EaYnm6m3LaHLn9/output.txt
input: https://pastebin.com/ZAUmaBpP

**Comment by Juliacare** [comment]
3rd occurance

full log: https://www.raidbots.com/reports/98StoBYGNq9ZAbLq3T7C9F/output.txt
input: https://pastebin.com/8W7brLdB

**Comment by nuoHep** [comment]
It's fixed on bfa-dev (https://www.raidbots.com/simbot/report/roeqrJF5sxKjA67rEJktKL)
Not sure I'll have the time to find the fix and backport it to legion-dev.

**Comment by Juliacare** [comment]
All good, Legion dev is gone in a few weeks anyways 👍
