### ISSUE TITLE
Outlaw exceeding twice the combat lenght

### ISSUE THREAD

**Issue by Juliacare** [simulationcraft/simc#4325]
Please include a brief overview of the issue in the title above, as well as completing the following:
 
#### Simulationcraft Version
 
SimulationCraft 735-02 for World of Warcraft 7.3.5 Live (wow build 25901, git build HEAD 3068eed13)
 
#### Reproduction Steps:
 
Use the raid event and simply run the outlaw t21 profile through it
 
The line below is causing the issue
> raid_events+=/invulnerable,first=170,duration=90,cooldown=100000
 
> Simulation has been forcefully cancelled at 1328.420 (1328.420) because twice the expected combat length has been exceeded.
 
preview: https://www.raidbots.com/simbot/report/hk7huWSYwUchs8KoNhMCeH/simc
input: https://pastebin.com/Y9JC41vr

**Comment by Juliacare** [comment]
Both the normal t21_outlaw and the SND version are causing this issue

**Comment by N1gh7h4wk** [comment]
does this still happen in 8.x?

**Comment by Juliacare** [comment]
It does not, I forgot about the issue. Closing.
