### ISSUE TITLE
Importing a character with different crucible relic traits

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4334]
I import a character after they have acquired a Tier2 or Tier3 crucible relic trait, and the imported text/script is exactly the same as before the crucible upgrade, therefore I am wondering if those crucible relic traits are taken into account at all?

#### Simulationcraft Version
735-01

**Comment by vituscze** [comment]
Yes, they are simed correctly. If you do not see any difference, make sure to update your simc addon.

**Comment by akis-t** [comment]
I am not sure I understand your reply. I have no simc addon. I simply go to "Import" and I select my character from there and press "import". The resulting imported character and associated script is the same before and after the relic upgrade at the crucible.

**Comment by Frostedmages** [comment]
Importing from battle.net is going to cause issues with the Arifact - they don't store all of your info there in a way we can access. Using the SimC Addon in game to generate the profile will solve the problem.
