### ISSUE TITLE
Fire mage : taking out Dragon's breath results in 10% DPS boost

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4336]
I am trying to write a simpler Fire Mage script and have stumbled upon Dragon's Breath which when I add it into my script results in a large DPS loss, so I tried the default script and it does the same there too. Could you please look into it?

Default options:
Vesuvius : 1125253 dps - with dragon's breath taken out 
Vesuvius : 1068383 dps - with dragon's breath in

600 seconds, 25,000 iterations
Vesuvius : 938537 dps - with dragon's breath taken out 
Vesuvius : 875881 dps - with dragon's breath in

The offending line is:

1)
actions.active_talents+=/dragons_breath,if=equipped.132863|(talent.alexstraszas_fury.enabled&!buff.hot_streak.react)

2) actions.combustion_phase+=/dragons_breath,if=!buff.hot_streak.react&action.fire_blast.charges<1&action.phoenixs_flames.charges<1

(1) is  much worse than (2) but both are bad

This is the script :

#### Simulationcraft Version 
735-01

mage="Vesuvius"
origin="https://eu.api.battle.net/wow/character/silvermoon/vesuvius/advanced"
thumbnail="https://render-eu.worldofwarcraft.com/character/silvermoon/13/129991181-avatar.jpg"
spec=fire
level=110
race=gnome
role=spell
position=back
professions=tailoring=700/jewelcrafting=224
talents=https://worldofwarcraft.com/en-gb/game/talent-calculator#mage/fire/talents=1121121
artifact=54:0:0:0:0:748:1:749:4:750:4:751:4:752:4:753:4:754:4:755:4:756:4:757:4:758:1:759:1:760:1:761:1:762:1:763:1:1340:1:1372:1:1533:4:1534:1:1535:1:1536:19:1640:1

# Default consumables
potion=prolonged_power
flask=whispered_pact
food=lemon_herb_filet
augmentation=defiled

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/mirror_image
actions.precombat+=/potion
actions.precombat+=/pyroblast

# Executed every time the actor is available.
actions=counterspell,if=target.debuff.casting.react
actions+=/time_warp,if=(time=0&buff.bloodlust.down)|(buff.bloodlust.down&equipped.132410&(cooldown.combustion.remains<1|target.time_to_die<50))
actions+=/mirror_image,if=buff.combustion.down
# Standard Talent RoP Logic.
actions+=/rune_of_power,if=firestarter.active&action.rune_of_power.charges=2|cooldown.combustion.remains>40&buff.combustion.down&!talent.kindling.enabled|target.time_to_die<11|talent.kindling.enabled&(charges_fractional>1.8|time<40)&cooldown.combustion.remains>40
# RoP use while using Legendary Items.
actions+=/rune_of_power,if=(buff.kaelthas_ultimate_ability.react&(cooldown.combustion.remains>40|action.rune_of_power.charges>1))|(buff.erupting_infernal_core.up&(cooldown.combustion.remains>40|action.rune_of_power.charges>1))
actions+=/call_action_list,name=combustion_phase,if=cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)&(!talent.firestarter.enabled|!firestarter.active|active_enemies>=4|active_enemies>=2&talent.flame_patch.enabled)|buff.combustion.up
actions+=/call_action_list,name=rop_phase,if=buff.rune_of_power.up&buff.combustion.down
actions+=/call_action_list,name=standard_rotation

actions.active_talents=blast_wave,if=(buff.combustion.down)|(buff.combustion.up&action.fire_blast.charges<1&action.phoenixs_flames.charges<1)
actions.active_talents+=/meteor,if=cooldown.combustion.remains>40|(cooldown.combustion.remains>target.time_to_die)|buff.rune_of_power.up|firestarter.active
actions.active_talents+=/cinderstorm,if=cooldown.combustion.remains<cast_time&(buff.rune_of_power.up|!talent.rune_of_power.enabled)|cooldown.combustion.remains>10*spell_haste&!buff.combustion.up
#actions.active_talents+=/dragons_breath,if=equipped.132863|(talent.alexstraszas_fury.enabled&!buff.hot_streak.react)
actions.active_talents+=/living_bomb,if=active_enemies>1&buff.combustion.down

actions.combustion_phase=lights_judgment,if=buff.combustion.down
actions.combustion_phase+=/rune_of_power,if=buff.combustion.down
actions.combustion_phase+=/call_action_list,name=active_talents
actions.combustion_phase+=/combustion
actions.combustion_phase+=/potion
actions.combustion_phase+=/blood_fury
actions.combustion_phase+=/berserking
actions.combustion_phase+=/arcane_torrent
actions.combustion_phase+=/use_items
actions.combustion_phase+=/flamestrike,if=(talent.flame_patch.enabled&active_enemies>2|active_enemies>4)&buff.hot_streak.react
actions.combustion_phase+=/pyroblast,if=buff.kaelthas_ultimate_ability.react&buff.combustion.remains>execute_time
actions.combustion_phase+=/pyroblast,if=buff.hot_streak.react
actions.combustion_phase+=/fire_blast,if=buff.heating_up.react
actions.combustion_phase+=/phoenixs_flames
actions.combustion_phase+=/scorch,if=buff.combustion.remains>cast_time
actions.combustion_phase+=/dragons_breath,if=!buff.hot_streak.react&action.fire_blast.charges<1&action.phoenixs_flames.charges<1
actions.combustion_phase+=/scorch,if=target.health.pct<=30&equipped.132454

actions.rop_phase=rune_of_power
actions.rop_phase+=/flamestrike,if=((talent.flame_patch.enabled&active_enemies>1)|active_enemies>3)&buff.hot_streak.react
actions.rop_phase+=/pyroblast,if=buff.hot_streak.react
actions.rop_phase+=/call_action_list,name=active_talents
actions.rop_phase+=/pyroblast,if=buff.kaelthas_ultimate_ability.react&execute_time<buff.kaelthas_ultimate_ability.remains&buff.rune_of_power.remains>cast_time
actions.rop_phase+=/fire_blast,if=!prev_off_gcd.fire_blast&buff.heating_up.react&firestarter.active&charges_fractional>1.7
actions.rop_phase+=/phoenixs_flames,if=!prev_gcd.1.phoenixs_flames&charges_fractional>2.7&firestarter.active
actions.rop_phase+=/fire_blast,if=!prev_off_gcd.fire_blast&!firestarter.active
actions.rop_phase+=/phoenixs_flames,if=!prev_gcd.1.phoenixs_flames
actions.rop_phase+=/scorch,if=target.health.pct<=30&equipped.132454
actions.rop_phase+=/dragons_breath,if=active_enemies>2
actions.rop_phase+=/flamestrike,if=(talent.flame_patch.enabled&active_enemies>2)|active_enemies>5
actions.rop_phase+=/fireball

actions.standard_rotation=flamestrike,if=((talent.flame_patch.enabled&active_enemies>1)|active_enemies>3)&buff.hot_streak.react
actions.standard_rotation+=/pyroblast,if=buff.hot_streak.react&buff.hot_streak.remains<action.fireball.execute_time
actions.standard_rotation+=/pyroblast,if=buff.hot_streak.react&firestarter.active&!talent.rune_of_power.enabled
actions.standard_rotation+=/phoenixs_flames,if=charges_fractional>2.7&active_enemies>2
actions.standard_rotation+=/pyroblast,if=buff.hot_streak.react&(!prev_gcd.1.pyroblast|action.pyroblast.in_flight)
actions.standard_rotation+=/pyroblast,if=buff.hot_streak.react&target.health.pct<=30&equipped.132454
actions.standard_rotation+=/pyroblast,if=buff.kaelthas_ultimate_ability.react&execute_time<buff.kaelthas_ultimate_ability.remains
actions.standard_rotation+=/call_action_list,name=active_talents
actions.standard_rotation+=/fire_blast,if=!talent.kindling.enabled&buff.heating_up.react&(!talent.rune_of_power.enabled|charges_fractional>1.4|cooldown.combustion.remains<40)&(3-charges_fractional)*(12*spell_haste)<cooldown.combustion.remains+3|target.time_to_die<4
actions.standard_rotation+=/fire_blast,if=talent.kindling.enabled&buff.heating_up.react&(!talent.rune_of_power.enabled|charges_fractional>1.5|cooldown.combustion.remains<40)&(3-charges_fractional)*(18*spell_haste)<cooldown.combustion.remains+3|target.time_to_die<4
actions.standard_rotation+=/phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up|buff.incanters_flow.stack>3|talent.mirror_image.enabled)&artifact.phoenix_reborn.enabled&(4-charges_fractional)*13<cooldown.combustion.remains+5|target.time_to_die<10
actions.standard_rotation+=/phoenixs_flames,if=(buff.combustion.up|buff.rune_of_power.up)&(4-charges_fractional)*30<cooldown.combustion.remains+5
actions.standard_rotation+=/phoenixs_flames,if=charges_fractional>2.5&cooldown.combustion.remains>23
actions.standard_rotation+=/flamestrike,if=(talent.flame_patch.enabled&active_enemies>3)|active_enemies>5
actions.standard_rotation+=/scorch,if=target.health.pct<=30&equipped.132454
actions.standard_rotation+=/fireball
actions.standard_rotation+=/scorch

head=runebound_collar,id=152138,bonus_id=3613/1462/3336
neck=riveted_choker_of_delirium,id=151966,bonus_id=3611/40/1487/3528,enchant=200crit
shoulders=runebound_mantle,id=152141,bonus_id=3613/1462/3336
back=runebound_cape,id=152136,bonus_id=3613/1808/1462/3336,gems=200crit,enchant=150int
chest=runebound_tunic,id=152140,bonus_id=3613/1808/1462/3336,gems=200crit
wrists=manari_pyromancer_cuffs,id=151953,bonus_id=3613/1472/3337
hands=seawitch_gloves,id=134261,bonus_id=3410/1592/3337
waist=enhanced_worldscorcher_cinch,id=151951,bonus_id=3613/1462/3336
legs=legwraps_of_the_seasoned_exterminator,id=152424,bonus_id=3611/1487/3528
feet=lady_dacidions_silk_slippers,id=151945,bonus_id=3613/1457/3528
finger1=soul_of_the_archmage,id=151642,bonus_id=3459/3630,gems=200crit,enchant=200crit
finger2=shard_of_the_exodar,id=132410,bonus_id=1811/3630,gems=200crit,enchant=200crit
trinket1=terminus_signaling_beacon,id=151969,bonus_id=3611/1487/3528
trinket2=prototype_personnel_decimator,id=151962,bonus_id=3610/1487/3337
main_hand=felomelorn,id=128820,bonus_id=730,gem_id=152036/152024/155849/0,relic_id=3613:1457:3528/3613:1462:3336/3613:1467:3528/0
off_hand=heart_of_the_phoenix,id=133959

# Gear Summary
# gear_ilvl=939.81
# gear_stamina=46150
# gear_intellect=40204
# gear_crit_rating=8894
# gear_haste_rating=11350
# gear_mastery_rating=10492
# gear_versatility_rating=2598
# gear_avoidance_rating=660
# gear_armor=2124
# set_bonus=tier21_2pc=1
# set_bonus=tier21_4pc=1

**Comment by Frostedmages** [comment]
The lines are actually fine. The real issue is the mana cost of DB coupled with the extra PBs and combustions you get when combining the Soul legendary, Kindling, and Alex's Fury. If you look at the mana charts for both profiles it should be clear the DB casting profiles are OOMing.

You can get around this issue by adding infinite_mana=1 to each profile. It does not get copied by copy=. I'm going to close the issue now, but if you need further clarification feel free to respond.

**Comment by akis-t** [comment]
Hello

Many thanks for your reply and the explanation.

I am now testing with Soul of the Archdruid,  Balance, and the ring results
in DPS loss - something is wrong, it's better to leave the slot empty! Is
there a way you could possibly help me with this?

Many thanks
akis

**Comment by Frostedmages** [comment]
I don't do anything with Balance Druid. Consider opening up another issue or heading over to the Druid discord to ask.

**Comment by akis-t** [comment]
Thank you for your reply, I have raised it as another issue with the script
and hopefully someone will pick it up.
