### ISSUE TITLE
[Raidevents] Add master race error

### ISSUE THREAD

**Issue by Juliacare** [simulationcraft/simc#4342]
The add event tries to mimic it's master target's race but it doesn't work at all.

> Could not create raid event from 'adds,count=1,duration=4,cooldown=9,first_pct=61,last_pct=59,force_stop=0,duration_stddev=20': Raid event (type=adds name=) could not parse race from sim target race 'Elemental'.

Getting error messages such as the one listed above from inputs like:
https://pastebin.com/raw/HmSb3v3t
and

> Could not create raid event from 'adds,count=1,duration=10,cooldown=15,first_pct=26,duration_stddev=20': Raid event (type=adds name=) could not parse race from sim target race 'Aberration'.

from https://pastebin.com/raw/pGeR00jR

**Comment by Juliacare** [comment]
For clarity's sake:
Removing the line

> target_race=x

allows it to sim correctly

**Comment by scamille** [comment]
Fixed. As discussed, main problem was that normal actor race= parsing could fail silently.

* Aberration is no valid simc race.
* Elemental race string was missing.
