### ISSUE TITLE
Simcraft crashing when simming Demonology Warlocks

### ISSUE THREAD

**Issue by ManbaneAD** [simulationcraft/simc#4352]
Please include a brief overview of the issue in the title above, as well as completing the following:

Version 801-01

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### Begin simulateText ###
# SimC Addon 1.9.1

warlock="Manbane"
level=110
race=orc
region=eu
server=argent_dawn
role=spell
professions=alchemy=800/herbalism=209
talents=2222121
spec=demonology
artifact=37:0:0:0:0:1183:1:1184:1:1185:1:1182:1:1181:1:1180:1:1179:4:1607:1:1178:4:1177:4:1176:4:1175:4:1712:1:1174:4:1173:4:1172:4:1171:4:1391:1:1170:1:1608:80:1606:1:1605:4:1354:1
crucible=1739:1782:1173/1739:1779:1174/1739:1770:1605

head=,id=134426,bonus_id=3536/1612/3337
neck=,id=132444,enchant_id=5890,gem_id=151583,bonus_id=1811/3630
shoulder=,id=152177,enchant_id=5883,gem_id=151583,bonus_id=3611/1808/1492/3336
back=,id=152172,enchant_id=5436,bonus_id=3612/1502/3528
chest=,id=152176,bonus_id=3612/1502/3528
shirt=,id=42368
wrist=,id=152085,bonus_id=3612/1502/3528
hands=,id=151941,bonus_id=3612/1507/3336
waist=,id=132374,bonus_id=1811/3630
legs=,id=152175,bonus_id=3612/1502/3528
feet=,id=151939,bonus_id=3612/1517/3337
finger1=,id=152688,enchant_id=5428,bonus_id=3612/1507/3336
finger2=,id=147195,enchant_id=5428,bonus_id=3562/1532/3337
trinket1=,id=151955,bonus_id=3612/1502/3528
trinket2=,id=154177,bonus_id=3984/3997
main_hand=,id=137246
off_hand=,id=128943,gem_id=152054/152036/152031,bonus_id=748,relic_id=3612:1502:3528/3612:1507:3336/3612:1502:3528

### Gear from Bags
#
# Grim Inquisitor's Death Mask (950)
# head=,id=152174,bonus_id=3611/1492/3336
#
# Hood of Eternal Disdain (1000)
# head=,id=132394,bonus_id=1811/3630
#
# Wolfstride Pendant (930)
# neck=,id=133633,enchant_id=5890,gem_id=151584,bonus_id=3536/1808/1582/3337
#
# Blessed Medallion of Karabor (141)
# neck=,id=32757
#
# Riveted Choker of Delirium (965)
# neck=,id=151966,enchant_id=5890,bonus_id=3612/1507/3336
#
# Necklace of the Twisting Void (965)
# neck=,id=151309,enchant_id=5890,bonus_id=3536/1617/3337
#
# Chain of the Unmaker (975)
# neck=,id=152283,enchant_id=5890,gem_id=151583,bonus_id=3611/1808/1507/3337
#
# Riveted Choker of Delirium (960)
# neck=,id=151966,bonus_id=3611/1502/3337
#
# Soul-Siphon Mantle (950)
# shoulder=,id=151949,bonus_id=3611/1492/3336
#
# Caretaker's Budding Mantle (960)
# shoulder=,id=144469,bonus_id=3536/1612/3337
#
# Grim Inquisitor's Shoulderguards (945)
# shoulder=,id=152177,bonus_id=3611/1487/3528
#
# Seacursed Wrap (960)
# back=,id=133771,bonus_id=3536/1612/3337
#
# Drape of the Spirited Hunt (960)
# back=,id=151938,bonus_id=3612/1502/3528
#
# Bonespeaker Robes (970)
# chest=,id=134219,bonus_id=3536/1808/1632/3337
#
# Blood-Drenched Bindings (970)
# wrist=,id=151954,bonus_id=3612/1512/3336
#
# Ink-Smudged Handwraps (960)
# hands=,id=134421,bonus_id=3536/1612/3337
#
# Grim Inquisitor's Gloves (960)
# hands=,id=152173,enchant_id=5444,bonus_id=3612/1502/3528
#
# Bonespeaker Gloves (965)
# hands=,id=134217,bonus_id=3536/1808/1627/3337
#
# Handwraps of Inevitable Doom (970)
# hands=,id=152680,bonus_id=3612/1502/3528
#
# Enhanced Worldscorcher Cinch (960)
# waist=,id=151951,bonus_id=3612/1502/3528
#
# Power Cord of Lethtendris (1000)
# waist=,id=132457,bonus_id=1811/3630
#
# Cord of Surging Hysteria (960)
# waist=,id=151942,bonus_id=3612/1502/3528
#
# Legwraps of the Seasoned Exterminator (985)
# legs=,id=152424,bonus_id=3612/1527/3337
#
# Sandals of the Reborn Colossus (975)
# feet=,id=151940,bonus_id=3612/1517/3337
#
# Band of the Sargerite Smith (960)
# finger1=,id=152064,bonus_id=3612/1502/3528
#
# Band of the Sargerite Smith (975)
# finger1=,id=152064,enchant_id=5428,bonus_id=3611/1517/3337
#
# Insignia of the Grand Army (1000)
# finger1=,id=152626,gem_id=151583,bonus_id=3459/3630
#
# Demonic Combatant's Ring (870)
# finger1=,id=150161,bonus_id=3584/1532/3528
#
# Sephuz's Secret (1000)
# finger1=,id=132452,enchant_id=5428,gem_id=151583,bonus_id=3459/3630
#
# Soul of the Netherlord (1000)
# finger1=,id=151649,enchant_id=5428,gem_id=151583,bonus_id=3459/3630
#
# Sacrolash's Dark Strike (1000)
# finger1=,id=132378,enchant_id=5429,gem_id=151584,bonus_id=3529/1811/3630
#
# Terminus Signaling Beacon (965)
# trinket1=,id=151969,bonus_id=3612/1507/3336
#
# Unstable Arcanocrystal (860)
# trinket1=,id=141482,bonus_id=1472
#
# Bouquet of Black Roses (60)
# off_hand=,id=3424
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

#### Reproduction Steps:
Added info: Simming other speccs works just fine. I have tried /simc the beta char and also the live character. Simcraft both crashes when trying it for Demonology warlocks.

**Comment by scamille** [comment]
Works fine with current HEAD 5c73e5f

Keep in mind that current bfa branch is in flux a lot. So while it can be helpful to test things out, some stuff might just not yet be ready.
