### ISSUE TITLE
Druid Balance script - variable,name=starfall_st

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4354]
I stumbled upon this trying to use the "Soul of the Archdruid" ring.

I think the line

"actions.precombat+=/variable,name=starfall_st,value=talent.soul_of_the_forest.enabled"

is not very good, because it forces Starfall in the ST rotation if talent "Soul of the Forest" is taken and this is definitely a bad idea.

The figures look more believable if you set the variable value to 0.

**Comment by Jundarer** [comment]
This is intentional. While this will be irrelevant in about one week you can check out the guide on how to use it here: https://www.dreamgrove.gg/balance/2018-02-25-dad_spec_guide/

**Comment by Jundarer** [comment]
Just as a clarification if you are using very low gear the Starfall will be worse than Starsurge causing the APL to execute the wrong actions.

**Comment by akis-t** [comment]
My gear was around the 948-952 mark-  not quite that low.

I think there could be an option or at least a check to see if the talent has been acquired through the legendary ring, therefore not intentionally seeking the Starfall playstyle.

**Comment by Jundarer** [comment]
That's an edge case that'll be irrelevant a few days anyways so not much point to fixing it now. Also the ring does not mean starfall isn't the way to go, it doing much less dps would be caused by something else.
