### ISSUE TITLE
Simcraft not calculating properly?

### ISSUE THREAD

**Issue by Weisshuf** [simulationcraft/simc#4357]
Hey Guys,

I tried out testing my options. i calculated the top dps (affli lock) on varimathras and in the log, he was doing 3,6M dps, but in simcraft he was doing only 1,9M.

**Comment by scamille** [comment]
Hi Weisshuf

If you are seriously interested in improving the SimulationCraft model, please try to offer a bit more information than that.

Also try to analyze and point out differences between any InGame numbers/logs and SimulationCraft reports. Both have very detailed metrics and can be compared to a certain degree. Just stating some arbitrary numbers without adding any detailed information is not helpful at all.

Closing this.
