### ISSUE TITLE
Shadowmourne, Fangs of the Father, Tarecgosa, Warglaives are not working.

### ISSUE THREAD

**Issue by JBA9084** [simulationcraft/simc#4372]
Overview: Old legendaries do not work(excluding cloak). Shadowmourne does not generate soul fragments or trigger chaos bane, Tarecgosa does not trigger Wrath of Tarecgosa, Fangs do not generate agility stacks or CP buff, and Warglaives do not give Attack Power vs Demons or trigger their haste buff. 

Note: I know the fangs say their set bonus is disabled, but they were hotfixed to work in Timewalking dungeons in 6.2.3; https://worldofwarcraft.com/en-us/news/19962858

#### Simulationcraft Version
801-01

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here -
No crash

#### Reproduction Steps:
Place the following lines beneath your character information at the top of your Simulate tab:

timewalk=70
scale_to_itemlevel=95 

The itemlvl part does not matter, just the sim bugs if you do not include it.  After you place those lines, replace your weapon with one of the legendaries above in your base profile or a copy, then sim.

Once you check your sim results, you will see the legendary procs are completely absent.

**Comment by navv1234** [comment]
Old legendaries are no longer implemented in the simulator. Nobody is currently interested in implementing them either.

**Comment by JBA9084** [comment]
Ah I see, thank you. Is there any specific literature I can read to try myself? I'd love to learn.

**Comment by N1gh7h4wk** [comment]
The wiki points to how to build it yourself, then you'd prolly want to make them work similar to other items in unique_gear_x<xpac number>.cpp

**Comment by JBA9084** [comment]
Thank you very much for pointing me in this direction, I'm currently installing QT and downloading Microsoft Visual Studio Express 2013. One last thing, will I be able to find the proc rates and other info required for making the items in unique_gear_x.cpp, or is it somewhere else?

**Comment by scamille** [comment]
Uuuh please get Visual Studio Community 2017. We don't even support 2013 anymore, and that guide was just horribly outdated. I updated it somewhat.

**Comment by N1gh7h4wk** [comment]
hmm the procc rates should be in the spell data itself, at least if its whitelisted to be pulled into that.
unique item effects are implemented in the respective unique gear files like for example legion had karazahn stuff [https://github.com/simulationcraft/simc/blob/f9ac2bd24b929f23fe07cda8a161b23ea198ab03/engine/player/sc_unique_gear_x6.cpp#L483](url)

**Comment by scamille** [comment]
Closing this. If you ever find the time to add support for this item, feel free to open a pull request.
