### ISSUE TITLE
seafood_magnifique_feast missing / not working in consumables database

### ISSUE THREAD

**Issue by Salchichaky** [simulationcraft/simc#4377]
Trying running the simulation with default settings for a level 80 beast mastery hunter character produces the following error:

> Action 'food': Unable to initialize consumable 'food' from 'seafood_magnifique_feast': Unable to find consumable.

Since the food is added automatically when importing, it makes it impossible to import my character from armory. When writing a profile manually, adding "food=skewered_eel" does work as a replacement, but this food doesn't get suggested by the import function for some reason.

#### Simulationcraft Version
any for the last 2 months, including the latest nightly (22 july)

#### Reproduction Steps:
Just try importing this char from armory: EU - Los Errantes - Dopeasballs

**Comment by scamille** [comment]
@navv1234 you don't plan to include this lower level spell data, correct?

If so this is a hunter APL issue.

**Comment by navv1234** [comment]
seafood magnifique feast should work. I don't know what has broken it, havent had time to look at the food situation yet. I believe some other food are also broken. In my opinion, anything specified by the default apl (or profile) should be supported.

**Comment by scamille** [comment]
Yeah I agree that anything in the default APL should be supported.

But since for that both DBC export filters for food and what is coded into the default APL's need to be in sync I specifically wanted to ask you first.

**Comment by scamille** [comment]
Fixed in ad466113b53804997c006f54a667d188cbaefb3c

Thanks navv.
