### ISSUE TITLE
Automation import option removed

### ISSUE THREAD

**Issue by vitor-f2f** [simulationcraft/simc#4380]
Simulationcraft Version 801-01

As of 8.0.1 versions, there's no "Automation" tab under "Import" anymore. It's probably an intended removal so not necessarily a glitch or issue per se, but I'm not too savvy and am left without a tool to easily simulate multiple talent sets at once.

**Comment by scamille** [comment]
Yes it was removed because it was no longer maintained.

There are nowadays external tools to get you Simc talent/gear combinations, most notably AutoSimc https://github.com/SimCMinMax/AutoSimC
