### ISSUE TITLE
Crash when simming rogue with Exsanguinate

### ISSUE THREAD

**Issue by tflo** [simulationcraft/simc#4384]
With the CL binary (macOS) built from the current bfa-dev branch I’m unable to sim an Assassination rogue _with the Exsanguinate talent activated_ (e.g. 1221133). I get a crash with this output:

```
Assertion failed: (dot -> current_tick == dot -> num_ticks), function execute, file ./simulationcraft.hpp, line 6318.
```

The bin from the latest Mac nightly (9eaf0bca35 from 19 July) works fine with Exsanguinate.

**Comment by Mystler** [comment]
Can you please pull the latest version and try again? I did a change to the dot system yesterday and that issue came up for about an hour until i pushed a fix. I would guess you pulled during that time.

**Comment by tflo** [comment]
> I would guess you pulled during that time.

Nope. I pulled various times in the last days since I’ve noticed that the Mac nightly on downloads.simulationcraft.org is outdated.

I pulled again now (398bbbe) and I still get the crash with the same message (now it is line 6319).

- To ensure I’m not working with an older copy of the bin I checked my Paths.
- To ensure that my git client is pulling properly I manually downloaded simulationcraft.hpp and sc_rogue.cpp: they are identical to the ones in my local repo.
- I tested it with several different talent combinations: the crucial factor is definitely talent 6/3 (Exsanguinate). Any other talent choices don’t affect the crash.
- I tested it with the default Rogue profile, generated with PR_Generate_Rogue.simc: as soon as I set talent 6/3 I get the crash also here.

So, it’s a mystery to me at the moment 😕

Do you not see the crash on your machine?

***

PS/Edit:

Probably unrelated, but when compiling I noticed a Rogue-related warning:

```
class_modules/sc_rogue.cpp:8012:12: warning: private field 'p' is not used
      [-Wunused-private-field]
  rogue_t& p;
           ^
1 warning generated.
```

**Comment by Mystler** [comment]
Ah, thank you, I was able to reproduce it with the PR profile and pushed https://github.com/simulationcraft/simc/commit/0ce286cd7c723b930447d941e5b4a04095e34f45. This should fix the issue.

**Comment by tflo** [comment]
Great, it works now, thanks!

\[Off-topic question:\]

While I was looking for the “change to the dot system” you mentioned in your [comment above](https://github.com/simulationcraft/simc/issues/4384#issuecomment-408043982) I’ve seen another dot [change](c505b72) from 24 July, where Crimson has been removed from `poisoned_bleeds`: Does this mean that the bleeds from Crimson do not generate energy?

**Comment by Mystler** [comment]
Yes, Crimson Tempest is not counting towards Venomous Wounds.
However, I was referring to a change to address refreshing right before the very last tick. https://github.com/simulationcraft/simc/commit/d882f582f8e7215eab5c0762a51cc56b67d4f956
