### ISSUE TITLE
composite_spell_power calculation for paladin/monk is wrong

### ISSUE THREAD

**Issue by johnsolver** [simulationcraft/simc#4390]
### Describe the bug
composite_spell_power for prot/ret paladin and ww/brew monk is calculated based on AP only (multiplied by 'Override Spell Power By AP %' aura)

### Expected behavior
In BFA the AP>SP multiplier multiplies (ap + wdps*6), eg. it's implemented correctly in the druid module

### To Reproduce
none, but any spell that scales with SP for the above specs is calculated incorrectly

### Additional information
SimulationCraft Version (a5b2174)

**Comment by scamille** [comment]
For Monk there have been some changes in 51ed08d8b56dfc7823c390f2b497bb7dfaa5f334 dunno if that is correct/enough.

**Comment by mserrano** [comment]
Should be fixed by https://github.com/simulationcraft/simc/commit/e42ad61389c0f5611449be13cb7fa2bf96f72462 for paladins
