### ISSUE TITLE
Stat weights for Holy Priest still not availible

### ISSUE THREAD

**Issue by BigBenny91** [simulationcraft/simc#4396]
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
i would like my stat weights to sim my charator to be available
### Describe alternatives you've considered
none
### Additional context
none

**Comment by scamille** [comment]
As Simc clearly states, holy priest is not implemented and unfortunately will not implement itself.

If you are interested in developing the Simc priest module or know someone who is, check out the Contributing section in the Readme and join our small development team :-)
