### ISSUE TITLE
Wiki: Broken images in SimcForTanks page 

### ISSUE THREAD

**Issue by Rafnak** [simulationcraft/simc#4401]
### Describe the bug
All image references are broken on this page: 
https://github.com/simulationcraft/simc/wiki/SimcForTanks

### Expected behavior
All images work well.

**Comment by scamille** [comment]
Thanks for your input. I will check if we still have access to those old image on googlecode somehow. Otherwise they would just have to be removed.

**Comment by scamille** [comment]
Fixed

@Melekus  If you want to take a look at that page and cleanup things further, feel free :-)
