### ISSUE TITLE
Arms Warrior T21 Profile has some inefficiencies

### ISSUE THREAD

**Issue by dsteinyb** [simulationcraft/simc#4402]
When looking through the current pre-patch profiles, I noticed that Arms Warrior was quite a ways down the list. This is to be expected, since some of the Arms changes have not been too kind to it. However, when I looked at the gear I noticed that every single piece of gear, apart from tier pieces, legendaries, and trinkets, has Mastery as a secondary stat. I don't think that this is an optimal gear setup, given that current mastery has such a low stat weight that it's better to equip a piece without mastery than one 30 or more levels higher that does have it. For example, currently the neck piece is Riveted Choker of Delirium from hounds, whereas a much better piece would be Vulcanarcore Pendant or Chain of the Unmaker. 

I would suggest looking over Arms again and replacing all the mastery pieces with non-mastery pieces, and seeing how much of a difference it makes. If you need me to help with some of this process, I'll be more than happy to assist.

**Comment by scamille** [comment]
Thanks for your input.

The current T21 bfa profiles are mainly just replicas of the old legion ones, and are not adjusted for any major shifts in equipment for bfa, as seems to be the case for Arms warrior mastery.

It is unlikely though that anybody will invest any effort in changing those leftover profiles. Main development work is currently focused on getting level120 things and azerite traits finished for BFA launch. As always, time is limited.

If you are interested in changing T21 profiles anyway, feel free to create a pull request with changes to profiles/generators/Tier21/T21_Generate_Warrior.simc

**Comment by Archimtiros** [comment]
To piggyback, it was also unlikely that anyone would have a full set of crit gear coming into prepatch, or enough time in a mere three weeks to obtain one, so I made the decision to leave the profile alone and more realistically replicate what people would be wearing once the prepatch hit.

Future (Level 120) profiles will be better itemized to help show players what to gear for and how that gear should stack up.
