### ISSUE TITLE
Error al importar un personaje paladin

### ISSUE THREAD

**Issue by NECROTITAN** [simulationcraft/simc#4408]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

Cuando le doy en la opcion de importar un personaje mio paladin level 10 me sale el eeror de
simulation error y cuando le doy los datos de el simc y pego me sale este mensaje[

Player Ålfredo action bastion_of_light : Unable to decode expression function 'action.shield_of_the_righteous.charges' Ålfredo-bastion_of_light: Unable to build expression tree from !talent.seraphim.enabled&talent.bastion_of_light.enabled&action.shield_of_the_righteous.charges=2

**Comment by Melekus** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/3d24fd4c002f659984e0ba84caf408090df29fbf
