### ISSUE TITLE
Survival Hunter Raptor Strike No AP scaling.

### ISSUE THREAD

**Issue by 87golfgt** [simulationcraft/simc#4409]
### Describe the bug
Raptor Strike rank 2 id=262839 is not reflecting AP scaling, only base amount.

I believe it should have the 49.327% AP scaling in addition to the +40% from its Rank 2.

### To Reproduce
Name             : Raptor Strike (rank=Rank 2) (id=262839) [Spell Family (9), Passive] 
Class            : Survival Hunter
School           : Nature
Spell Level      : 52
Attributes       : ......x. ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ x....... ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : Passive (6)
Effects          :
#1 (id=624335)   : Apply Aura (6) | Add Percent Modifier (108): Spell Direct Amount (0)
                   Base Value: 40 | Scaled Value: 40 | Target: Self (1)
                   Affected Spells: Raptor Strike (186270), Raptor Strike (265189)

### Additional information
* SimulationCraft Version 801-01

**Comment by nuoHep** [comment]
Raptor Strike rank 2 is a 'simple' damage multiplier on all raptor strike damage and the spell reflects that. Not sure what AP scaling has to do with it.
