### ISSUE TITLE
avatar prot

### ISSUE THREAD

**Issue by milesobrien** [simulationcraft/simc#4410]
### Describe the bug
avatar is casting as if it has no cd

### Expected behavior
anytime avatar is in a sim it casts repeatedly

### Additional information
8.01

**Comment by Archimtiros** [comment]
The protection module is currently not being maintained. It's on my to-do list, but low priority since I primarily focus on Arms & Fury.

**Comment by milesobrien** [comment]
thanks archimtiros.

until then can anyone help me out with an override to change the avatar cd?  ive been messing with it and I cant seem to get the format right.

**Comment by Archimtiros** [comment]
I'll see if I can fix it tomorrow, but the point is that the module isn't being maintained and hasn't been updated for BfA, so even if Avatar weren't giving you problems, many other things would still be broken.

Easy fix for now would be to simply remove Avatar from the action list.

**Comment by scamille** [comment]
Why are you not disabling the module @Archimtiros ?
See e.g. https://github.com/simulationcraft/simc/blob/9494b38b82acee0e270d297b6485b5594e81597e/engine/class_modules/priest/sc_priest.cpp#L1284

**Comment by scamille** [comment]
We have disabled the protection warrior module for now, until there is some concentrated effort to fully update its code.
