### ISSUE TITLE
Character talents aren't the actual talents i have chosen

### ISSUE THREAD

**Issue by edweezy27** [simulationcraft/simc#4416]
Im currently running simulationcraft 735-02 WebEngine, and for the past couple weeks ive been trying to sim my character but the talents that are shown after the simulation are not the ones i currently have on my character therefore it is not accurate whatsoever. Can you please help me out / fix this bug because its because doing this for last few weeks. (i did /simc in game and pasted in the webengine but still same result as well as importing character using my character name and realm name but still doesnt work. 

Please respond asap. Simc is very helpful for me and im sure for many others and i have not been able to use it

**Comment by scamille** [comment]
Please realize that World of Warcraft is currently on version 8.0.1, even if BFA has not been fully released.

Thus you need to get a 8.x version of SimulationCraft, which you can find as a nightly at https://www.simulationcraft.org/download.html

A 7,x legion version of SimC will of course give you unexpected results.
