### ISSUE TITLE
Phantom Singularity doesn't (yet) scale correctly with haste

### ISSUE THREAD

**Issue by MartinZnamirowski** [simulationcraft/simc#4420]
I am not sure, if you treat inaccuracies in calculation as a bug. But I wouldn't know where else to report it, so here goes.

### Describe the bug
Despite Blizzard saying that all dots now correctly scale with haste (I.e. they keep their duration, but the ticks are sped up) the talented skill Phantom Singularity of the Affliction warlock still doesn't work that way. Ticks ARE sped up, but the duration is still reduced as a result. Confirmed in the live-build of WoW 9th of August 2018. 
I hope that is a bug from blizzard side that will be fixed (already reported), but for the state now it seems to be wrongly calculated.

### Expected behavior
I expected the duration of phantom singularity to be reduced through haste, but according to the result staticstics it is not. Or at least I cannot find it.

### To Reproduce
Load any affliction warlock, simulate and look at the spell description in detail and the duration.

### Additional information
Nightly build from win-64x installer 7th of August 2018

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
No Crashes

* **simc_gui.simc** file or contents
Not necessary. Can be done with any affliction warlock.

**Comment by MartinZnamirowski** [comment]
Reconfirmed that the actual duration does not change through haset with the log=1 option by reading through the log.

**Comment by scamille** [comment]
This is the right place to report such a thing, thank you. Always good to have a ticket so the problem does not get forgotten and there is a clear status.

Top men will be working on it, breaking the warlock module even further ;)

**Comment by nasirabtw** [comment]
It's not actually a bug. It's intended that Phantom Singularity has it's duration reduced by haste, similarly to how UA used to work in legion and how Rain of Fire also works. The developers feared that Phantom Singularity would become too powerful at higher haste levels.

As far as simc implementation of Phantom Singularity goes, everything functions exactly how it does in-game. The reason you may see an increase in the number of ticks as you add haste with the default APL is that Summon Darkglare extends PS by a static duration (8 seconds). PS retains its constant tick rate, which it snapshots on execute, resulting in an increase in ticks during the 8 seconds added from Darkglare as you increase haste.

I've attached some images below showing that as you increase haste, PS does not gain ticks unless Summon Darkglare is included in the APL.

1105 haste
![image](https://user-images.githubusercontent.com/2917657/43931272-abf6c34e-9c0b-11e8-9b2d-0cbf6dbb0a3d.png)

10105 haste
![image](https://user-images.githubusercontent.com/2917657/43931283-baf0d9de-9c0b-11e8-9c9e-671168485328.png)

**Comment by MartinZnamirowski** [comment]
Wow, my bad then. I am so sorry for wasting your time :/

**Comment by nasirabtw** [comment]
NP I made the same mistake a week ago when implementing it.
