### ISSUE TITLE
Survival Hunter doesn't check for melee weapon

### ISSUE THREAD

**Issue by seriallos** [simulationcraft/simc#4422]
### Describe the bug

Survival hunter module doesn't look to check for a melee weapon when simming. If a ranged weapon is equipped all melee abilities are used in the APL. Raptor strike is still used.

### Expected behavior

Expectation is either an error is thrown or melee abilities are not used.

### To Reproduce

Example sim showing full damage:

https://www.raidbots.com/simbot/report/81di4DfCNMcd7Nq3D9YCGs

https://www.raidbots.com/simbot/report/81di4DfCNMcd7Nq3D9YCGs/simc

### Additional information
* SimulationCraft Version (required)

https://github.com/simulationcraft/simc/commits/4c44d036c2

**Comment by Jayezi** [comment]
d959eebe04129212c8824d12cc8b3f4589614474
