### ISSUE TITLE
Monk: Brewmaster rushing jade wind duration

### ISSUE THREAD

**Issue by kanka123** [simulationcraft/simc#4425]
The duration should be reduced by haste along with cooldown and the freqency of damage ticks, but currently the duration is fixed at 9s.

**Comment by Melekus** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/af780df8656c7f8471ac958764a0412cebfe177d#diff-bb0b90481946cd22a6be0ce0abed8298
