### ISSUE TITLE
Monk - Boiling Brew azerite trait doesn't work

### ISSUE THREAD

**Issue by johnsolver** [simulationcraft/simc#4426]
### Describe the bug
An item with Boiling Brew selected and shown in the items section, however the damage from BB isn't calculated in BoF dot.

### Additional information
* SimulationCraft Version: 88100cf092

**Comment by scamille** [comment]
Do you have a simc input so I can easily replicate this?

Boiling Brew is coded and should be working, but I guess something is bugging.
