### ISSUE TITLE
Arcane Mage PreRaid Profile Better Trinkets

### ISSUE THREAD

**Issue by dsteinyb** [simulationcraft/simc#4431]
With the new arcane PreRaid profile out and topping the charts, I thought I'd take a look at it and see how strong the gear is. I was looking through the trinkets, and I noticed a slight discrepancy between them and those on current Trinket sims. I thought this might be a latency error, so I went through some of my own simming, and it turns out my results, trinket sims, and the preraid profile differ quite vastly between each other. I'm too dum to make a pull request, so I thought I'd post my results here so a more competent person might verify/make the changes for me.

Basically, I took the default PreRaid profile on simc and compared every combination of BfA dungeon Ranged DPS trinkets, excluding those with two on-use trinkets equipped simultaneously. I did it over the course of multiple separate comparisons, as my computer started to get really slow. The results are shown in the following reports:

https://www.raidbots.com/simbot/report/ptK2DfAfaSVXPuPqSWKu5n
https://www.raidbots.com/simbot/report/7sS9hEJDfAu4uKMGLrkAwA
https://www.raidbots.com/simbot/report/neryLBLG4EqnSnP3B4LH1g

If these reports are not accurately visible, in summary the Balefire Branch is the best trinket at 340 by far, with Ignition Mage's Fuse being the second best on-use trinket. In terms of not on-use trinkets, the Music Box is still the best, although Hadal's Nautilus, Conch, and Vessel of Skittering Shadows are all pretty close depending on which other trinket is equipped. The top three trinket combos are Branch/Music Box, Branch/Nautilus, and Branch/Conch, all at +1.5% increase over the current profile dps. These are followed by Branch/Vessel at +1.4%, and then Fuse/Music Box at +0.6%.

**Comment by ronoudgenoeg** [comment]
Thanks for contributing to the profile. These trinkets are recently implemented. I will look into optimizing trinkets tonight.

**Comment by ronoudgenoeg** [comment]
@Cobalt314 Fixed in https://github.com/simulationcraft/simc/pull/4439
