### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by Eradoryn** [simulationcraft/simc#4444]
i am unable to run simcraft 8.0.1, whenever i try to load the program i get "the code execution cannot proceed because MSVCP140.dll was not found","the code execution cannot proceed because VCRUNTIME140.dll was not found." errors. i am on windows 10 and i am fully updated.

**Comment by Ergoglobe** [comment]
Try to Reinstall the Microsoft Visual C ++ Redistributable package

**Comment by Eradoryn** [comment]
That did it! Thank you
