### ISSUE TITLE
Wrong condition for Rising Sun Kick for the AoE profile of Windwalker

### ISSUE THREAD

**Issue by Pwaite2** [simulationcraft/simc#4449]
Good morning,

Today while taking a look at the Windwalker profile I noticed that the condition for using Rising Sun Kick in AoE was as follows:

`actions.aoe+=/rising_sun_kick,target_if=cooldown.whirling_dragon_punch.remains>=gcd&!prev_gcd.1.rising_sun_kick&cooldown.fists_of_fury.remains>gcd
`

The issue with having the condition "if=cooldown.whirling_dragon_punch.remains **>=** gcd" is that, since Whirling Dragon Punch is not on cooldown at the beginning of an encounter, it will never use RSK and therefore never enable the use of Whirling Dragon Punch.

Since as a Windwalker it is advised to use RSK in AoE **only** to enable the use of Whirling Dragon Punch, I suggest the following modification:

`actions.aoe+=/rising_sun_kick,target_if=cooldown.whirling_dragon_punch.remains<=gcd&!prev_gcd.1.rising_sun_kick&cooldown.fists_of_fury.remains>gcd
`

With "if=cooldown.whirling_dragon_punch.remains **<=** gcd"

This way, it will use RSK only to trigger the use of Whirling Dragon Punch on the next GCD.

Thanks for reading, I hope this helps.

**Comment by Hinalover** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/2e0feca0ce0702b281a8ece8025c80231a1c966b
