### ISSUE TITLE
Disc Priest, I can't simulate Healing

### ISSUE THREAD

**Issue by Discpriest** [simulationcraft/simc#4454]
### Describe the bug
Here's the thing, I started using Simcraft today, I just finished simulating my character three times. But all I get when I do the simulation is DPS. No stats about healing. Which makes the rating Simcraft gives to mastery 0.00 or 0.01, essentially useless. I don't know what the problem is because I can't get a healing simulation.

I've changed the basic role to Heal. But I can't seem to change the target. I've tried changing the target type to Tank Dummy but it doesn't change the outcome. 

Maybe I'm just stupid and it's my fault it isn't working. Or maybe it isn't even possible to get healing simulated. Anyway I'd love some instructions. 

Here's my "simc_gui.simc" https://pastebin.com/2xtApJFW

**Comment by Juliacare** [comment]
Heal simulations are currently not supported or possible, nor is disc priest updated for BFA.

Closing the issue.
