### ISSUE TITLE
Demon Hunter Blade Dance - Death Sweep

### ISSUE THREAD

**Issue by Ramilek** [simulationcraft/simc#4457]
In the last version (801-01), when i simulate my char, checked the action priority list - simple sequence table, and there is this:
1:43.264	demonic	J	chaos_strike	Fluffy_Pillow	82.0/120: 68% fury	thirsting_blades(2), phenomenal_power(3)
1:44.655	demonic	H	eye_beam	Fluffy_Pillow	44.0/120: 37% fury	thirsting_blades, phenomenal_power(3)
1:47.152	default	6	auto_attack	Fluffy_Pillow	120.0/120: 100% fury	metamorphosis, thirsting_blades(3), phenomenal_power(3)
1:47.152	demonic	E	death_sweep	Fluffy_Pillow	120.0/120: 100% fury	metamorphosis, thirsting_blades(3), phenomenal_power(3)

The problem is, if i use chaos strike right before eye beam, i cant use death sweep right after, because getting metamorphosis from eye beam (demonic talent) not resetting the cooldown of chaos strike/death sweep.

**Comment by EvanMichaels** [comment]
Hi, I'm a bit unclear what the issue in what you posted above is. The time between 1:44 and 1:47 should be the channeling time of Eye Beam.

**Comment by Ramilek** [comment]
Hi, sorry now i see, i thought i saw blade dance in the table, but thats chaos strike, so i made a mistake. Sorry.

**Comment by scamille** [comment]
Thanks for the report though. Always good to have things checked by multiple people, and to be able to resolve problems.

Closing this.
