### ISSUE TITLE
Trinket Bygone Bee Almanac not implemented at all

### ISSUE THREAD

**Issue by nzall** [simulationcraft/simc#4460]
### Describe the bug
The Bygone Bee Almanac item is not implemented properly. It does not reduce the cooldown or increase the duration of the effect. This has been noticed in the Fury Warrior profile, but I do not know if this occurs in other profiles as well.

### Expected behavior
Spending resources should have the appropriate effect, so the effect should be used more often than every 2 minutes and last more than (fight length in minutes/2)*12 seconds.

### To Reproduce
Using the Nightly build of Raidbots, I have made a sim: https://www.raidbots.com/simbot/report/tGBB6YygonLGroMCsWdkZc/simc

As you can see, the report has a Process Improvement (name of the buff) interval of roughly 120 seconds. I do not know if Raidbots is considered an appropriate source to report this stuff, but I do not have a local install of the software available to run tests with.

### Additional information
SimC Version

Nightly (801-02)

SimC Build Date

Aug 21 2018

SimC Git Hash

57250019bf

**Comment by navv1234** [comment]
We cannot implement this trinket unless someone comes up with information on how it works.

**Comment by navv1234** [comment]
Ret paladin is implemented now.

**Comment by nzall** [comment]
I have created a pair of videos simulating DPS warrior gains. https://www.youtube.com/watch?v=aWy0JpQ7TCM is the Fury test and https://www.youtube.com/watch?v=AUTyWiojUME is the Arms test.

**Comment by nzall** [comment]
I have done some extra math and changed my weakauras. After some testing, the effects adds 0.025s per rage spent and reduces the CD by 0.05s per rage spent.

**Comment by navv1234** [comment]
Pretty sure this is now handled by the various class module authors, and the simulator has a working model for it. Closing.
