### ISSUE TITLE
system error

### ISSUE THREAD

**Issue by WrathofBone** [simulationcraft/simc#4462]
the code execution cant  be proceed because MSVCP140.dll was not found.......help

**Comment by scamille** [comment]
Please install the vc_redist.x64.exe found in your SimulationCraft folder. It installs Visual C++ Redistributable for Visual Studio 2015 which should fix your problem.

**Comment by WrathofBone** [comment]
That worked like a charm. Thank you very much

**Comment by WrathofBone** [comment]
That worked like a charm. Thank you very much
