### ISSUE TITLE
[Feature Request] Add ability to cancel spellcasts in favor of other actions

### ISSUE THREAD

**Issue by JamesMWyatt** [simulationcraft/simc#4464]
### Is your feature request related to a problem? Please describe.
The problem is the inability to program stopping a cast for another action. An example is that under normal priority with abilities available the simulation would cast Lava Burst over Lightning Bolt, however, if it start a Lightning Bolt cast with Lava Burst still on cooldown and then a Lava Surge proc happens which grants a charge of Lava Burst, it is locked into the full Lightning Bolt cast instead of the clearly more optimal stopcasting into Lava Burst.

### Describe the solution you'd like
Similarly to channeled spell's ability to interrupt in response to a tick event, I would like the ability to interrupt a spell cast in response to a buff/spell gained charge/spell came off cooldown event.

**Comment by vituscze** [comment]
Implemented in 399c8e2713685b599a1f6060b07639bd6bc169e1
