### ISSUE TITLE
Protection Paladin APL Typos

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#4468]
### Describe the bug
Typo 2x of "avenger_shield" (should be avengers_shield)
See lines 1042 and 1053 in engine/class_modules/paladin/sc_paladin.cpp (and resultant profiles).

### Expected behavior
The APL as written checks the cooldown of Avenger's Shield but uses the wrong token.  HOWEVER, note that correcting this issue actually results in a DPS loss (checking Avenger's Shield's CD on line 1053 shouldn't be an issue since Avenger's Shield is above it in priority on line 1052, and would've been cast first).

### To Reproduce
Sim the default Protection Paladin profile (PreRaid, any, it doesn't matter).
Correct "avenger_shield" typos to "avengers_shield".
Resim.
Remove Avenger's Shield cooldown checks from those lines and resim again.  Or revise the check to confirm Avenger's Shield's CD is greater than the GCD (which was probably what was intended).

### Additional information
* SimulationCraft Version (required)
World of Warcraft 8.0.1 Live (wow build level 27404, git build 7394552bf1) - via RaidBots

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
N/A

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
N/A

**Comment by Melekus** [comment]
The APL was updated and doesn't use these typos anymore, thanks for the heads up !
