### ISSUE TITLE
T22 Sample profiles: Windwalker gear is too low.

### ISSUE THREAD

**Issue by boombeef** [simulationcraft/simc#4471]
### Describe the bug
The Sim results on the front page link here are grossly misrepresented for WW Monks.
http://www.simulationcraft.org/reports/T22_Raid.html

### Expected behavior
If their Avg Gear was equal to the other specs, results are dramatically different.

### To Reproduce
Basically went to the main page link: 
http://www.simulationcraft.org/reports/T22_Raid.html

Click on second info tile arrow for "T22_Monk_Windwalker : 13279 dps"
Scroll down to Gear. Click arrow to reveal Avg iLvL to be 341.

Random similar sample of other class and specs show Avg ilvl of 385 mostly. 

### Additional information
Guessing with all the work that went into this large report; that was probably overlooked. 
Could be fixed for better and more accurate spec comparison. 
Thanks for all the effort to coral all this data thus far and making it make sense to us all.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/d3198a35a002a6193e59a5427eb7f4736ea28c96#diff-9b85618370d7a2d0769e2cff19b2e391
