### ISSUE TITLE
outlaw using Slice and Dice has less Adrenaline Rush and Blade Rush times than Roll the Bones

### ISSUE THREAD

**Issue by SaSloth** [simulationcraft/simc#4474]
pr_rogue_outlaw in sample profile:
![image](https://user-images.githubusercontent.com/13166459/44579015-a7c77f80-a7c7-11e8-9611-6598d5ba7163.png)

snake eyes &  slice and dice:
![image](https://user-images.githubusercontent.com/13166459/44579028-b0b85100-a7c7-11e8-8efd-af80b41ce40f.png)

this build only cast slice and dice to get snake eyes buff and Sinister Strike to cosume them,
it should have more Adrenaline Rush respawn

[snake_eyes.txt](https://github.com/simulationcraft/simc/files/2317911/snake_eyes.txt)

**Comment by Mystler** [comment]
Why should it have more Rushes? Snake Eyes profiles casts less finishers and can have no True Bearing uptime, so the total CDR on Rush is noticeably lower.

**Comment by Mystler** [comment]
Second update, there was indeed a bug with SnD not triggering Restless Blades. I initially thought you meant the meme profile should have more Rushes than the default one, but ofc it should be less than a 180s interval. Thanks for reporting, I pushed the fix.
