### ISSUE TITLE
Glompmaw's Ring is crashing the program

### ISSUE THREAD

**Issue by imperia777** [simulationcraft/simc#4476]
Glompmaw's Ring is crashing the program
finger2=,id=160985,bonus_id=4776/42/4802,drop_level=120,reforge=19

also

wearing Underlight Angler
main_hand=,id=133755,enchant_id=5930,reforge=11

throws following error:
_No active player to sim._

**Comment by navv1234** [comment]
Gonna need a full profile that is crashing, that item alone does not produce a crash. Underlight Angler is treated as an invalid item in terms of simulating and cancels it.

**Comment by imperia777** [comment]
# SimC Addon 1.10.5
# 8.0 Note: reforge= is being used as a hacky way to capture item context. This will be changed in 8.1

warrior="Bot"
level=120
race=undead
region=eu
server=alakir
role=attack
professions=mining=77/engineering=25
talents=1111211
spec=arms

head=,id=157961,bonus_id=1502/4785,reforge=26,azerite_powers=196
neck=,id=158075,bonus_id=4932/4933/4936/1498,reforge=11,azerite_level=14
shoulder=,id=158060,bonus_id=1487/4785,reforge=25,azerite_powers=478
back=,id=160529,reforge=14
chest=,id=157894,bonus_id=1502/4785,reforge=26,azerite_powers=194
shirt=,id=6796
wrist=,id=159441,bonus_id=4777/1482/4785,reforge=1
hands=,id=158984,bonus_id=4793,drop_level=119,reforge=11
waist=,id=159034,bonus_id=4793,drop_level=119,reforge=11
legs=,id=157899,bonus_id=4803/1492/4785,reforge=27
feet=,id=158055,bonus_id=4803/4802/1507/4782,reforge=26
finger1=,id=162453,bonus_id=4793,drop_level=120,reforge=11
finger2=,id=160985,bonus_id=4776/42/4802,drop_level=120,reforge=19
trinket1=,id=161113,bonus_id=4802/4803/1477/4785,reforge=26
trinket2=,id=159077,bonus_id=4790,drop_level=119,reforge=11
main_hand=,id=159634,bonus_id=4777/1492/4781,reforge=1

### Gear from Bags
#
# Ceann-Ar Charger (265)
# head=,id=137088,bonus_id=1811/3630
#
# Prydaz, Xavaric's Magnum Opus (240)
# neck=,id=132444,enchant_id=5439,gem_id=130222,bonus_id=3459/3570
#
# Timeless Stratagem (240)
# shoulder=,id=143728,bonus_id=1811/3570
#
# Kazzalax, Fujieda's Fury (265)
# back=,id=137053,enchant_id=5434,bonus_id=1811/3630
#
# Vambraces of Rezan's Bladeguard (300)
# wrist=,id=157934,bonus_id=4803/4802/1492/4781,reforge=26
#
# Rastari Waistplate (290)
# waist=,id=158440,bonus_id=4793,drop_level=120,reforge=11
#
# Naj'entus's Vertebrae (240)
# waist=,id=137087,bonus_id=3459/3570
#
# Valarjar Berserkers (265)
# legs=,id=151824,bonus_id=1811/3630
#
# Weight of the Earth (265)
# legs=,id=137077,bonus_id=1811/3630
#
# Aggramar's Stride (240)
# feet=,id=132443,bonus_id=1811/3570
#
# Spearfisher's Band (285)
# finger1=,id=158161,bonus_id=4803/1477/4785,reforge=26
#
# Stormbinder Signet Ring (281)
# finger1=,id=155304,bonus_id=4787,drop_level=120,reforge=11
#
# Zul Adherent's Band (281)
# finger1=,id=159942,bonus_id=4787,drop_level=120,reforge=11
#
# Lightning Caller's Band (281)
# finger1=,id=155309,bonus_id=4787,drop_level=120,reforge=11
#
# Warmongering Gladiator's Medallion of Adaptation (144)
# trinket1=,id=125978,reforge=14
#
# Kil'jaeden's Burning Wish (240)
# trinket1=,id=144259,bonus_id=3529/3459/3570
#
# Potency Manipulator (286)
# trinket1=,id=159078,bonus_id=4790,drop_level=119,reforge=11
#
# Corrupted Tribe Headsmasher (305)
# main_hand=,id=159086,bonus_id=4813/4816,drop_level=119,reforge=11
#
# Fallen Spider Handaxe (298)
# main_hand=,id=159110,bonus_id=4793/4794,drop_level=120,reforge=11
#
# Golden Tomb Defender (290)
# off_hand=,id=160978,bonus_id=4803/1482/4781,reforge=25
#

**Comment by imperia777** [comment]
[https://pastebin.com/raw/jLdL5DfH](url)
I tried it today and it crashed few times and few times it didn't. 
I will try to force the crash again and report back.
Is there a way to force the program to dump crash log or something?
