### ISSUE TITLE
Outlaw: Snake eyes damage not stacking when using multiple traits?

### ISSUE THREAD

**Issue by nvelat** [simulationcraft/simc#4480]
https://www.raidbots.com/simbot/report/t7vKz1Xv6DRyD61tYT6REP/simc, compare "current" vs "snek eyes"

Sinister strike mean damage only goes up ~1.1k when using 3x snake eyes traits compared to 0. This is as if 1 trait was active (237 x 5cp), but not 3. Correct damage increase should be 3.3k (I think)

**Comment by Mystler** [comment]
There was indeed a bug with the buff resetting the CP multiplier after the first stack was consumed. Fixed in 20259dad4528d689c7f523c6d85659f7b7d8fee4.
