### ISSUE TITLE
GUI Scaling is wonky on windows (most likely a Qt issue)

### ISSUE THREAD

**Issue by jackdneilson** [simulationcraft/simc#4494]
### Describe the bug

Hotspots do not match button visual indicators, text scaling is wrong, bars are hidden (see attached screenshot)

### Expected behavior

n/a

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

On a clean install of windows with DPI scaling set to 100% and no Qt environment variables set, open simulationcraft

### Additional information
* SimulationCraft Version (required)

801-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

n/a

![image](https://user-images.githubusercontent.com/17084543/44871486-c972ac00-ac8a-11e8-9b5e-90ca0d18bbac.png)

**Comment by scamille** [comment]
We switched QT versions to 5.15.2, which has major changes to UI scaling and high DPI stuff. Please try again with the latest nightly from http://downloads.simulationcraft.org/nightly/?C=M;O=D .

If you still have that problem, feel free to open this issue again.
