### ISSUE TITLE
2nd eye beam in metamorphosis does not extend its duration

### ISSUE THREAD

**Issue by zeroztz** [simulationcraft/simc#4495]
### Describe the bug
Using eye beam during metamorphosis should extend its duration if talent demonic is enabled.

A sample of my start is usually metamorphosis+eye beam so I get metamorphosis buff >30s, and in th end I will do another eye beam and further extend the metamorphosis buff.

But in simc, the 2nd eye beam doesn't extend metamorphosis buff as expected.

### Expected behavior
the 2nd eye beam should also extend metamorphosis buff.

### To Reproduce
Run any DH with talent:
`talents=https://worldofwarcraft.com/en-us/game/talent-calculator#demon-hunter/havoc/talents=1311211`

and action list:
`actions=auto_attack
actions+=/eye_beam
actions+=/chaos_strike,if=cooldown.eye_beam.ready&fury>=30
actions+=/demons_bite,if=cooldown.eye_beam.ready&fury<30
actions+=/annihilation,if=(talent.blind_fury.enabled|fury.deficit<30|buff.metamorphosis.remains<5)
actions+=/chaos_strike,if=(talent.blind_fury.enabled|fury.deficit<30)`

Got the sim result > Action Priority List > Sample Sequence Table, check around 33 second, there will be an eye beam in metamorphosis. and at 37 second, we will lose metamorphosis buff because only one demonic eye beam is contributed to the duration

### Additional information
* SimulationCraft Version (required)
801-02, nightly build

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by zeroztz** [comment]
I tried the action sequence in WoW. it does extend metamorphosis to 30+8*2=46s.

**Comment by Zarania** [comment]
We had tested this pre launch, looks like somewhere in between they changed it again.  It doesn't go to 46 seconds, it goes to 46 sec + channel time, though there's a bug in game that also got reported.  This is fixed in 357a6ba4d87a020feaa2e3db5289e9ca058a73b3
