### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by sfjuocekr** [simulationcraft/simc#4503]
Trying to import this profile: https://worldofwarcraft.com/en-gb/character/defias-brotherhood/Fritzldinge

This is the result:

# Unable to download JSON from 'https://eu.api.battle.net/wow/character/defias-brotherhood/Fritzldinge?fields=talents,items,professions&locale=en_US&apikey='.

API key is empty?

**Comment by scamille** [comment]
API Key is deliberately not shown on errors.

Please specify what OS and SimulationCraft version you are using. Are you building SimC yourself, if yes how?

**Comment by p-takacs** [comment]
I have the same problem on Win7 64 bit. Both the 801-02 nightly installer and the 801-01 installer version, but if I remember correctly this was an issue when I tried it about a month ago. I even tried with my own api key, with the same result.

**Comment by ghost** [comment]
I have the same problem also. I am building SimC by myself on openSUSE 42.3. The simc binary with apikey.txt does work but importing via GUI and with ~.simc_apikey does not work. Interestingly when I copy the URL to browser and append the API key it does work also. I am using my own API key. Tested on SimC commit da24163522.

**Comment by Nysosis** [comment]
Receiving the same error - simc-801-01-win64 from the downloads page on Windows 7 Professional 64bit

**Comment by JiwoongLee** [comment]
Receiving the same error in the Raidbots and SimulationCraft 801-02 (x64)
"https://worldofwarcraft.com/ko-kr/character/azshara/Ministab"

**Comment by scamille** [comment]
@515k4 in the GUI, try adding the api key directly in the options tab where there is a special TextBox.

For all the other errors: I suspect that this could just be some armory problem on Blizzards end, maybe even some rate limiting.
What could be improved here is a better error message, assuming we can obtain better information why the download failed.
@navv1234 What do you think is the problem here?

**Comment by Nysosis** [comment]
I think one simple improvement that would be nice, is instead of
`&apikey=`, put in `&apikey=[REDACTED]` or similar, just to indicate that
the lack of value is for security purposes, and not because there is no
value set (which was my initial thought as to what the problem may be).

**Comment by navv1234** [comment]
The korean api endpoint claims character unavaiable for the above character, which isnt something we can really do much about.

**Comment by CBWAR1** [comment]
Geez, then why have program if Navv1234 says "which isnt something we can really do much about"?
