### ISSUE TITLE
[Feature request] Better translation support for the GUI

### ISSUE THREAD

**Issue by Ruby437** [simulationcraft/simc#4505]
### Is your feature request related to a problem? Please describe.
I cannot seem to find an option to change the interface language away from German to English. I live in Germany, but I have my PC set to English, pretty much all websites who don't IP detect me default to english, but simcraft has German labels at the top, which are confusing to me, and I cannot find an option to change it.

### Describe the solution you'd like
I'd like to see some option in the Options tab to change that language rather than it trying to autodetect it for me.

### Describe alternatives you've considered
Not use Simcraft anymore, or use a VPN to fake my location so simcraft doesn't translate software that I don't want translated.

### Additional context
IP detecting to change language is bad practice, system language is often a lot more accurate.

**Comment by scamille** [comment]
You are talking about the SimulationCraft Desktop Application, right?

As far as I know, this should not have anything to do with your IP settings or whatever, solely your System Language.

Besides the GUI does offer the option to change the language under Options -> Globals -> Basic Options -> GUI Localization

**Comment by theRubyUnicorn** [comment]
My system language is set to English and the entire interface is in German. It is clearly detecting the System Language wrong then. Also, its kinda hard to find that option when in German, there isn't GUI in the name, and its hidden between combat options. Thanks for pointing it out though.

**Comment by Ruby437** [comment]
My system language is set to English and the entire interface is in German. It is clearly detecting the System Language wrong then. Also, its kinda hard to find that option when in German, there isn't GUI in the name, and its hidden between combat options. Thanks for pointing it out though.
