### ISSUE TITLE
Arcane Blast wrong damage

### ISSUE THREAD

**Issue by KebabOfDeath** [simulationcraft/simc#4511]
### 
Hello, i've found out that Arcane blast doesn't do damage as it should. Wowhead shows spell=30451 (arcane blast) should do 55% of spell damage, but in reallity it does only 45% of that amount, i checked it on my naked mage without any buffs

### Expected behavior
I don't really know where you gathering data from, but if your source is same as Wowhead, arcane mage damage calculations is completely wrong. It should be checked and recalculated.

### To Reproduce
You can check it on any naked mage. You will see damage doesn't equal 55% of Spell damage at all.

### Additional information
* SimulationCraft Version 801-02

i also asked Wowhead team, they sent me this response:
"This data is entirely from Blizzard, so if it's incorrect it's wrong on their end. It's also possible they reduced it in a hotfix which hasn't been patched yet via a client update (our site is based on the client version, hotfixes are server side)."

P.S.
I'm sorry if i made any grammar misstakes, it's not my native language and it's hard to express my thoughts properly

sincerely Шаурмасмерти

**Comment by Melekus** [comment]
I'm not a mage dev, but most specializations have a hidden damage modifier aura for tuning purpose.
This is the aura for arcane mage : https://www.wowhead.com/spell=137021/arcane-mage

As you can see, every arcane spell has a hidden modifier of -18% damage, so arcane blast will deal 82% of the 55% Spell Power stated in the spell's data, which is equal to 45.1, the value you observed ingame.

This hidden modifier is properly taken into account in Simulationcraft so the damage in your simulations should be correct, unless there's something else I'm not aware of.

**Comment by KebabOfDeath** [comment]
thank you, it all make sense now
