### ISSUE TITLE
Simulation Runtime Error , destruction warlock 

### ISSUE THREAD

**Issue by filologiggy** [simulationcraft/simc#4520]
### Describe the bug
The error:
Simulation runtime error 

Simulation runtime error:
Initializing:Actor 'FourTwo':Item 'inactive' Slot 'hands':Cannot initialize data

If you think this is a bug,please open a ticket,copying the detailed text below.
It contains all the input options of the last simulation and help us reproduce the issue.

### Expected behavior
It was suppose to simulate my character.It worked properly 2-3 days ago but since then i get error everytime i try to simulate my charactet

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* My simulation craft version is 801-02 win64 

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
Thanks for the ticket.

For this we absolutely need the input used for your simulation. So either copy-paste the detailed text from the error message you got or attach the https://github.com/simulationcraft/simc/wiki/simc_gui.simc file.

**Comment by filologiggy** [comment]
Thanks for the quick reply.

This is the Simc.gui.simc file

### SimulationCraft 801-02 for World of Warcraft 8.0.1 Live (wow build 27481) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,int,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.6
# 8.0 Note: reforge= is being used as a hacky way to capture item context. This will be changed in 8.1

warlock="Fourtwo"
level=120
race=orc
region=eu
server=genjuros
role=spell
professions=alchemy=135/herbalism=150
talents=1223212
spec=destruction

head=,id=159244,bonus_id=4819/1512/4786,reforge=23,azerite_powers=478/30
neck=,id=158075,bonus_id=4933/4936/4929/1508,reforge=11,azerite_level=19
shoulder=,id=157907,bonus_id=1517/5139,reforge=28,azerite_powers=432/15
back=,id=155572,bonus_id=4802/4803/1522/4781,reforge=26
chest=,id=157962,bonus_id=1532/5138,reforge=28,azerite_powers=444/22
wrist=,id=161498,reforge=14
hands=,id=165234,enchant_id=5932,reforge=14
waist=,id=159255,bonus_id=4779/1512/4786,reforge=23
legs=,id=159269,bonus_id=4779/1517/4783,reforge=23
feet=,id=159259,bonus_id=4779/1527/4784,reforge=23
finger1=,id=159461,bonus_id=4779/1512/4786,reforge=23
finger2=,id=158362,gem_id=153709,bonus_id=4779/4802/1512/4786,reforge=23
trinket1=,id=161125,bonus_id=4803/1522/4781,reforge=26
trinket2=,id=159615,bonus_id=4778/1497/4785,reforge=2
main_hand=,id=159636,bonus_id=4779/1517/4783,reforge=23

### Gear from Bags
#
# Fen Spirit Headdress (325)
# head=,id=157873,bonus_id=1517/4785,reforge=26,azerite_powers=
#
# Shadra Silk Headband (325)
# head=,id=157905,bonus_id=1517/4785,reforge=26,azerite_powers=
#
# Sandspinner Headdress (325)
# head=,id=157937,bonus_id=1517/4785,reforge=25,azerite_powers=
#
# Smartly Plumed Cap (325)
# head=,id=155886,bonus_id=4818/1497/4785,reforge=2,azerite_powers=192/44
#
# Sandspinner Headdress (325)
# head=,id=157937,bonus_id=1517/4785,reforge=26,azerite_powers=
#
# Shadra Silk Mantle (325)
# shoulder=,id=157907,bonus_id=1517/4785,reforge=26,azerite_powers=
#
# Corlain Cape of the Quickblade (266)
# back=,id=159284,bonus_id=4796/4802/1677,drop_level=120
#
# Dread Aspirant's Cloak (325)
# back=,id=162864,bonus_id=1517/4785,reforge=47
#
# Eventide Cape of the Peerless (266)
# back=,id=159264,bonus_id=4796/1688,drop_level=120
#
# Petticoat of the Self-Stylized Azerite Baron (325)
# chest=,id=158349,bonus_id=4818/1497/4785,reforge=2,azerite_powers=
#
# Ruffled Poet Blouse (340)
# chest=,id=158301,bonus_id=4819/1512/4786,reforge=23,azerite_powers=444/31
#
# Wristbands of the Black Harvest (161)
# wrist=,id=139770,bonus_id=3386/3381,reforge=11
#
# Sandspinner Gloves (330)
# hands=,id=157936,bonus_id=4803/1522/4781,reforge=25
#
# Sandspinner Gloves (325)
# hands=,id=157936,enchant_id=5932,bonus_id=4803/1517/4785,reforge=27
#
# Dread Aspirant's Silk Gloves (330)
# hands=,id=162943,bonus_id=1522/4781,reforge=47
#
# Shadra Silk Legwraps (325)
# legs=,id=157906,bonus_id=4803/1517/4785,reforge=26
#
# Thornwoven Band (340)
# finger1=,id=162548,gem_id=153713,bonus_id=4779/4802/1512/4786,reforge=23
#
# Golden Empire Signet (335)
# finger1=,id=158152,bonus_id=4803/1527/4783,reforge=26
#
# Zandalari Band (355)
# finger1=,id=158151,bonus_id=4803/1547/4784,reforge=26
#
# Golden Empire Signet (320)
# finger1=,id=158152,bonus_id=4803/1512/4785,reforge=25
#
# Dinobone Charm (320)
# trinket1=,id=158155,bonus_id=4803/1512/4785,reforge=25
#
# Tideguard Sword of the Peerless (266)
# main_hand=,id=159589,bonus_id=4796/1685,drop_level=120
#
# Coldscale Dagger of the Quickblade (266)
# main_hand=,id=159525,bonus_id=4796/43/1681,drop_level=120
#
# Tideguard Shanker of the Fireflash (266)
# main_hand=,id=159523,bonus_id=4796/1695,drop_level=120
#
# Fishing Pole (1)
# main_hand=,id=6256,reforge=14
#
# Mining Pick (4)
# main_hand=,id=2901,reforge=14
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

I also found out that the problem is caused by the gloves ''Swamp Medic's Gloves''.When i change back to the old gloves the simulation was able to run smoothly.Sadly i need to simulate using these gloves in order to get accurate pawn strings.

**Comment by scamille** [comment]
Thanks. That should make it easy to replicate and fix the problem.

**Comment by filologiggy** [comment]
Did u find any solutions or do i need to farm new gloves in order to get a simulation?

**Comment by navv1234** [comment]
Sims fine on bfa-dev/HEAD, could be that's a hotfix only item and the nightly does not have it.

**Comment by scamille** [comment]
I just run this successfully as well with the current nightly. Seems to be resolved, closing.

**Comment by Sukmymagic** [comment]
Same error .. please help

Initializing: Actor 'Sukmymagic': Item 'inactive' Slot 'head': Cannot parse option from ',id=155886,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=168/461/205/13': Unexpected parameter 'context'.

**Comment by AlexanderKenny** [comment]
This is not the same issue but the solution is the same. Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Comment by Sukmymagic** [comment]
Thanks a lot for your reply Kenny, appreciate it

Best,
Oberon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
