### ISSUE TITLE
Not drawing

### ISSUE THREAD

**Issue by saraneth0o** [simulationcraft/simc#4529]
Thought this issue was fixed but it has come back again. The GUI feels like it freezes. Clicking tabs does nothing that can be seen.

Clicking welcome then back to whatever tab and you can see the changes that were made. If you change more though you will not see it until you click welcome then go back to whatever tab. I can only open other tabs from the welcome tab. If I try from any other tab it does nothing.

**Comment by scamille** [comment]
Have you tried updating your graphics drivers? See eg. Issue #4450

Other than that we cannot really offer the support for the GUI you probably expect, and the best recommendation is to just switch to Raidbots or use the Command-Line Interface to SimC.

**Comment by saraneth0o** [comment]
Drivers are all up-to-date.
Yeah I have moved on to raidbots. It's much easier to use and seems to have
more features.

**Comment by scamille** [comment]
Yeah sorry about not being able to help you directly with SimC, but debugging and resolving GUI issues has often been a problem in the past. We use Qt framwork, and there have always been rare but obscure problems on some peoples hardware/software setups.

Great to hear that Raidbots is a working alternative for you.
