### ISSUE TITLE
Windwalker not using tiger palm correctly when pooling.

### ISSUE THREAD

**Issue by tamedbeast** [simulationcraft/simc#4534]
### Describe the bug
Instead of using the Tiger palm to build chi it just stays on pooling (showing no spell) , needs to use tiger palm when there is access energy available. 

Also using Rushing Jade Wind Talent this might play a role into this issue. 

### Expected behavior
while pooling use Tiger Palm when energy is available without using STE.

### To Reproduce
I'm not sure how to do that. 

### Additional information
I've used the latest SimC profile on Hekili addon and seems tiger palm does not use energy resources when available, but instead pools energy. 

May help increase dps by fixing this issue.

**Comment by scamille** [comment]
So if I understand you correctly, it is just the Action Priority List which currently does not do any resource pooling for Tiger Palm?
Not some "bug" in the narrow sense.

That can be achieved with pool_resource, see https://github.com/simulationcraft/simc/wiki/ActionLists#resources

Maybe our Monk dev might find some time to tune it, but I can't promise anything, so feel free to tune the APL yourself and report back your improvements.

**Comment by tamedbeast** [comment]
> So if I understand you correctly, it is just the Action Priority List which currently does not do any resource pooling for Tiger Palm?
> Not some "bug" in the narrow sense.
> 
> That can be achieved with pool_resource, see https://github.com/simulationcraft/simc/wiki/ActionLists#resources
> 
> Maybe our Monk dev might find some time to tune it, but I can't promise anything, so feel free to tune the APL yourself and report back your improvements.

I wish I could but I have no idea how to use the code, if I could I would update a lot of things that appear off, but the best I can do is point them out.

**Comment by Hinalover** [comment]
There should be some pooling for Tiger Palm

`tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=!prev_gcd.1.tiger_palm&chi.max-chi>=2&(buff.rushing_jade_wind.down|energy>56)`

If that is not happening, I will need to look into it.

There was an update to the APL that was posted after this; I didn't see this issue till just now. But there was a bug were TP didn't want to break Mastery but then didn't want to cast BoK due to FoF was off cooldown. That has since been fixed. So that could have been what you were seeing.

**Comment by tamedbeast** [comment]
> There should be some pooling for Tiger Palm
> 
> `tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=!prev_gcd.1.tiger_palm&chi.max-chi>=2&(buff.rushing_jade_wind.down|energy>56)`
> 
> If that is not happening, I will need to look into it.
> 
> There was an update to the APL that was posted after this; I didn't see this issue till just now. But there was a bug were TP didn't want to break Mastery but then didn't want to cast BoK due to FoF was off cooldown. That has since been fixed. So that could have been what you were seeing.



'I will try today and see if I'm still having the same issue and report back to you.

**Comment by seanpeters86** [comment]
@tamedbeast any update here?
