### ISSUE TITLE
Only one on-use trinket is used

### ISSUE THREAD

**Issue by cremor** [simulationcraft/simc#4545]
### Describe the bug
As a Ret Paladin, if I have two on-use trinkets equipped, only one (the first) is used. This happens because all trinket usages seem to have the condition "buff.avenging_wrath.up" but the 20 seconds shared CD prevents using both during Avenging Wrath.

### Expected behavior
Both trinkets should be used.

### To Reproduce
Run this profile: https://pastebin.com/yarc7DmB

### Additional information
SimulationCraft Version (required): git build ab166b41cc run on raidbots

Sample reports:
https://www.raidbots.com/simbot/report/kRb1nMCQa31sErC45DKU1P/simc
https://www.raidbots.com/simbot/report/pfFwVtVFuL3d6XFDH2zTmA/simc
Just the two trinkets were swapped in those reports. Note the difference in buffs (one trinket buff missing each time) and in APL (second trinket with 0 usage).

**Comment by scamille** [comment]
Just remove the conditions on one/both trinkets or replace them with something better for now. The action priority list is a user-modifiable input :-)

But thanks for the report, we will eventually adjust this in the default APL eventually.

**Comment by cremor** [comment]
Seems like the default APL now has special cases for all current trinkets. Some are used outside of Avenging Wrath, some are not. But for the latter the 5 seconds additional Avenging Wrath duration from the azerite trait also helps. I consider this resolved.
