### ISSUE TITLE
Computer crashing when simulating on SimC

### ISSUE THREAD

**Issue by cindynico** [simulationcraft/simc#4546]
When I try to simulate a character, my entire SimC closes down OR even wors it makes my computer crash.
I expected it to be working fine and normal like any other program is use. I am now using raidbots because I cna not use SimC. I know raidbots uses SimC but it would be nicer to use the source where the data comes from.

 SimcSetup-801-02-Win64.exe

[DxDiag.txt](https://github.com/simulationcraft/simc/files/2397943/DxDiag.txt)

I can not really give sim info seeing that the last few times I simulated, my entire computer shut down and it really isnt healthy for my computer.

**Comment by cindynico** [comment]
When I try to simulate a character, my entire SimC closes down OR even wors it makes my computer crash.
I expected it to be working fine and normal like any other program is use. I am now using raidbots because I cna not use SimC. I know raidbots uses SimC but it would be nicer to use the source where the data comes from.

* SimulationCraft Version (required) : SimcSetup-801-02-Win64.exe

* If SimulationCraft is crashing, please include your **dxdiag** file - 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/2397943/DxDiag.txt)


* **simc_gui.simc** file or contents
  I can not really do that seeing that the last few times I did that, my entire computer shut down and it really isnt healthy for my computer.

**Comment by scamille** [comment]
This sounds like your CPU is overheating, either because your cooling is inadequate or you overclocked too much. SimulationCraft uses your CPU to the limit and will quickly discover such problems.

You can also test this by seeing if you get a crash with other CPU-stress programs like Prime95.
