### ISSUE TITLE
Arms Warrior Execute Phase

### ISSUE THREAD

**Issue by Beats23** [simulationcraft/simc#4547]
### Describe the bug
Hey, 

First of all sorry I'm kinda new to this but I researched it now for a while and I just wondered why Arms Warrior isn't using Mortal strike in Execute Phase at all? It should with either Dreadnaught Talented or 2 Stacks of Executioners Precision. But as you can see in this report, it doesn't:
https://www.raidbots.com/simbot/report/uj2qxGS3fhuvuSLsJPeF28/simc

Thanks in Advance for helping.

### To Reproduce
Tested with Arms Warrior Beats from Azshara-EU
https://pastebin.com/bRxFvmPv

### Additional information
* SimulationCraft 801-02 | wow build level 27602, git build ab166b41cc

**Comment by Archimtiros** [comment]
You neither have Dreadnaught talented, nor do you have the Executioner's Precision Azerite trait enabled in that simulation report, so it (correctly) does not use Mortal Strike during the Execute phase.

The action is controlled by this line in the APL:
`actions.execute+=/mortal_strike,if=debuff.colossus_smash.up&buff.overpower.stack=2&(talent.dreadnaught.enabled|buff.executioners_precision.stack=2)`

And if you use the proper azerite/talent, such as in this report, Mortal Strike will be used.
https://www.raidbots.com/simbot/report/4Yu41ALVreJLB4Aw6VKbvJ/simc

**Comment by Beats23** [comment]
Sorry, I mixed up the 2 stacks from Overpower with the Executioner's Precision Azerite trait. Note to myself, think first, write later. Thanks for your amazing theorycrafting work btw.
