### ISSUE TITLE
crash error  MSVCP140

### ISSUE THREAD

**Issue by phillipm14** [simulationcraft/simc#4549]
I have downloaded the newest version for 64bit on 9/19/2018.

 It installs fine, when I try to use Simcraft, I get the following errors

MSVCP140.dll

VCRuntime140

  I removed several times and redownloaded several times.

Thoughts please

**Comment by scamille** [comment]
Install the vc_redist.x64.exe file you find in the downloaded SimulationCraft folder.

**Comment by phillipm14** [comment]
Hi, I am really sorry to trouble you but I cant find  vc_redist.x64.exe

**Comment by scamille** [comment]
Which version did you download exactly, can you provide a link?

The nightly builds at https://www.simulationcraft.org/download.html do contain vc_redist.x64.exe , I just checked again.

**Comment by phillipm14** [comment]
Mr Camille, 
  I'm really sorry to have troubled you. I did find and install it. I should have done more before bothering you.
Thank you for your time and please take care.
Phillip

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 20, 2018 at 3:15 AM, Serge Camille<notifications@github.com> wrote:   
Which version did you download exactly, can you provide a link?

The nightly builds at https://www.simulationcraft.org/download.html do contain vc_redist.x64.exe , I just checked again.
