### ISSUE TITLE
Arcane Mage Profile AOE issues, Proc issues and other Issue

### ISSUE THREAD

**Issue by tamedbeast** [simulationcraft/simc#4551]
I've been trying out the Arcane mage profile and it appears that for AOE situations it fails to use Arcane Explosion 99% of the time and also doesn't use Arcane barrage very often. 

Also noticed that rune of power is not used a lot when it's up for use. 

Another issue seems to be that when arcane barrage is proc is does not fire it off all the time which seems like a major waste of resources and dps loss.

**Comment by vituscze** [comment]
Rune of Power usage could probably be improved, but I don't see any problem with Arcane Explosion or Arcane Barrage use (also, there's no Arcane Barrage related proc).

Do you have a more specific example where the APL fails to use these spells correctly?

@ronoudgenoeg Might want to take a look at RoP use, T22_Mage_Arcane is wasting 1 full charge with 3 targets.

**Comment by ronoudgenoeg** [comment]
RoP usage fixed in https://github.com/simulationcraft/simc/pull/4554

What was happening: Some lines that only exists for single-target was also being applied in AoE situations, which caused the burn phase to take way too long to finish. And since RoP only gets used on high-ish mana in burn phases, it was capping on rune of power during these insanely long burn phases.

**Comment by tamedbeast** [comment]
> RoP usage fixed in #4554
> 
> What was happening: Some lines that only exists for single-target was also being applied in AoE situations, which caused the burn phase to take way too long to finish. And since RoP only gets used on high-ish mana in burn phases, it was capping on rune of power during these insanely long burn phases.

Sorry I meant to say Arcane Barrage was not being used when proct.

**Comment by tamedbeast** [comment]
> Rune of Power usage could probably be improved, but I don't see any problem with Arcane Explosion or Arcane Barrage use (also, there's no Arcane Barrage related proc).
> 
> Do you have a more specific example where the APL fails to use these spells correctly?
> 
> @ronoudgenoeg Might want to take a look at RoP use, T22_Mage_Arcane is wasting 1 full charge with 3 targets.

Sorry I meant that Arcane Missiles was not spending when proc.

**Comment by vituscze** [comment]
The Clearcasting procs are spent on Arcane Explosion. Not sure why would you want to spend the procs on Arcane Missiles instead?

**Comment by ronoudgenoeg** [comment]
> > Rune of Power usage could probably be improved, but I don't see any problem with Arcane Explosion or Arcane Barrage use (also, there's no Arcane Barrage related proc).
> > Do you have a more specific example where the APL fails to use these spells correctly?
> > @ronoudgenoeg Might want to take a look at RoP use, T22_Mage_Arcane is wasting 1 full charge with 3 targets.
> 
> Sorry I meant that Arcane Missiles was not spending when proc.

Are you talking about single-target now? Instead of AoE.

During Arcane Power & Rune of Power, the APL does not cast Arcane Missiles on purpose, because it was simmed a DPS increase to ignore Clearcasting procs during those DPS cooldowns.

**Comment by tamedbeast** [comment]
Okay Just to be clear as I might have caused some confusion. 

On non-AOE related matters, Arcane Missiles does not always fire off as a priority on proc in a single target situation instead it just continues to use Arcane Blast and spend mana when there is a free spender up, this is even with out using rune of power talent.

In terms of AOE at the moment, I find that from distance it from time to time will launch Arcane Barrage if there are 3+ mobs, until your deadly close to them and then it will start using AE which it should but it tends to leave out Arcane Barrage on when its off CD which I think is a massive DPS loss. Basically what I'm saying is when using AE it should always use barrage when off CD. 

Previously when I wrote this 2 days ago I was using other talents which might have had an effect on the outcome of AE or else there was an update that corrected it.

**Comment by ronoudgenoeg** [comment]
Arcane Barrage scales with Arcane Charges. Using Arcane Barrages with less than 4 charges is a DPS loss, which is why it uses Arcane Explosion until 4 charges, and then uses Arcane Barrage.
