### ISSUE TITLE
C:\Simulationcraft(x64)\730-02\log.txt

### ISSUE THREAD

**Issue by Misfitorc** [simulationcraft/simc#4557]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
With just a filename and no actual information we can not help you.

Even if there was a file attached, a little bit more info would would be expected.
