### ISSUE TITLE
Unholy DK profile - outbreak optimization

### ISSUE THREAD

**Issue by Hemario** [simulationcraft/simc#4559]
### Describe the bug
https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/PreRaids/PR_Death_Knight_Unholy.simc
The current script has weird behavior for outbreak. 
`
actions+=/outbreak,target_if=(dot.virulent_plague.tick_time_remains+tick_time<=dot.virulent_plague.remains)&dot.virulent_plague.remains<=gcd
`

The first part `dot.virulent_plague.tick_time_remains+tick_time<=dot.virulent_plague.remains` is always negated by the last part `dot.virulent_plague.remains<=gcd`.

### Expected behavior
Optimization can be obtained here.

### Additional information
* SimulationCraft Version (required)
not really sure what version, I just read the profile to understand the class better.

**Comment by seanpeters86** [comment]
@Hemario can you open a pull request with the change to the apl here https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_death_knight.cpp#L7950 and also provide a sim with the new apl and the dps increase?
