### ISSUE TITLE
Enhancement Shaman Pre-Level 40 Simulation Has Maelstrom Gains from Maelstrom Weapon

### ISSUE THREAD

**Issue by codymurphyjones** [simulationcraft/simc#4565]
### Describe the bug
As an enhancement shaman, below level 40 without Malestrom Weapon yet learned, the simulation still assumes that you get gains on every attack.  Maelstrom weapon should NEVER trigger for a shaman below level 40

### Expected behavior
Shamans below level 40 should have normal non maelstrom weapon auto attacks

### To Reproduce
Sim any shaman below level 40 and try to replicate the DPS (its impossible because its almost twice the obtainable DPS)

### Additional information
Version 801-01

* **simc_gui.simc** file or contents
https://pastebin.com/aLNBRYnH

Proposed Solution:
I review the enhancement shaman code and noticed that there is no level gate on Maelstrom Weapon.  On line 1475 if you had a check to determine if the shaman is level 40 you can resolve this issue.  No enhancement shaman will be able to have Maelstrom Weapon until level 40 and No enhancement shaman will not have it past level 40.

https://pastebin.com/zg5A7n0z

The paste bin code is here.  Feel free to remove my comment if this is applied, I was just clarifying what I was doing (even though its obvious)

**Comment by seanpeters86** [comment]
@codymurphyjones can you make a pull request with your change please?

**Comment by scamille** [comment]
@simulationcraft/shaman does this still have any relevance for shadowlands? If so we can keep it open as a "nice to have" enhancement, otherwise I think it is time to close it.

**Comment by wfarr** [comment]
I can't speak for the other folks, but personally I'm not terribly interested in prioritizing support for non-max level characters.
