### ISSUE TITLE
Warlock Bilescourge Bomber

### ISSUE THREAD

**Issue by Allarius** [simulationcraft/simc#4568]
### Describe the bug
I was attempting to sim the single target difference between the level 15 demonology talent when I found that it never casts nor even accounts for the Bilescourge Bomber talent. However the damage still appears in the abilities section under the listing pet - bilescourge. The strangest part about this though is that it applies the damage even when the talent is not selected.

After a little investigation it looks like Bilescourge Bomber is only ever coded in conjunction with action.implosion so I'm assuming that because this is patchwerk fight, the APL doesn't ever trigger the talent because there is no aoe present to trigger it.

### 

B | 0.00 | call_action_list,name=implosion,if=spell_targets.implosion>1
-- | -- | --

### 

This is what I believe is the offender. The talent is not called by itself, unlike Summon Vilefiend and Summon Felguard. I'm still slightly confused as to how it was recording the DPS values for Bilescourge on both profiles however. One of them doesn't even take that talent, yet you can clearly see it

### **DREADLASH BUILD: BILESCOURGE PET LISTING**

pet - bilescourge | 1085 / 64 |  
-- | -- | --
Toxic Bile | 1085 | 0.5% | 

Dreadlash | A | B
-- | -- | --
augmentation | 1.0 | 0.00sec
Call Dreadstalkers | 13.9 | 22.21sec
flask | 1.0 | 0.00sec
food | 1.0 | 0.00sec
inner_demons | 1.0 | 0.00sec
potion | 2.0 | 0.00sec
Power Siphon | 9.5 | 30.98sec
Soul Strike | 25.4 | 11.90sec
Summon Demonic Tyrant | 3.6 | 92.54sec
Summon Felguard | 1.0 | 0.00sec
summon_random_demon | 2.9 | 59.06sec

### **BILESCOURGE BUILD: BILESCOURGE PET LISTING**

pet - bilescourge | 1090 / 64 |  
-- | -- | --
Toxic Bile | 1090 | 0.5% | 

Bilescourge | A | B 
-- | -- | --
augmentation | 1.0 | 0.00sec
Call Dreadstalkers | 13.9 | 22.20sec
flask | 1.0 | 0.00sec
food | 1.0 | 0.00sec
inner_demons | 1.0 | 0.00sec
potion | 2.0 | 0.00sec
Power Siphon | 9.5 | 31.01sec
Soul Strike | 25.4 | 11.92sec
Summon Demonic Tyrant | 3.6 | 92.60sec
Summon Felguard | 1.0 | 0.00sec
summon_random_demon | 2.9 | 65.24sec

As you can see Bilescourge Bomber is not listed on either simple APL and only vaguely mentioned in conjunction with the implosion function call.

### **DREADLASH**
warlock="1232321"
source=blizzard
origin="/tmp/4xDbJwNifkd7te4JaXmvum.armory.json"
spec=demonology
level=120
race=undead
role=spell
position=back
talents=1232321

# Executed every time the actor is available.
actions=potion,if=pet.demonic_tyrant.active|target.time_to_die<30
actions+=/use_items,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/berserking,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/blood_fury,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/fireblood,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/doom,if=!ticking&time_to_die>30&spell_targets.implosion<2
actions+=/demonic_strength,if=(buff.wild_imps.stack<6|buff.demonic_power.up)|spell_targets.implosion<2
actions+=/call_action_list,name=nether_portal,if=talent.nether_portal.enabled&spell_targets.implosion<=2
actions+=/call_action_list,name=implosion,if=spell_targets.implosion>1
actions+=/grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions+=/summon_vilefiend,if=equipped.132369|cooldown.summon_demonic_tyrant.remains>40|cooldown.summon_demonic_tyrant.remains<12
actions+=/call_dreadstalkers,if=equipped.132369|(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions+=/summon_demonic_tyrant,if=equipped.132369|(buff.dreadstalkers.remains>cast_time&(buff.wild_imps.stack>=3|prev_gcd.1.hand_of_guldan)&(soul_shard<3|buff.dreadstalkers.remains<gcd*2.7|buff.grimoire_felguard.remains<gcd*2.7))
actions+=/power_siphon,if=buff.wild_imps.stack>=2&buff.demonic_core.stack<=2&buff.demonic_power.down&spell_targets.implosion<2
actions+=/doom,if=talent.doom.enabled&refreshable&time_to_die>(dot.doom.remains+30)
actions+=/hand_of_guldan,if=soul_shard>=5|(soul_shard>=3&cooldown.call_dreadstalkers.remains>4&(!talent.summon_vilefiend.enabled|cooldown.summon_vilefiend.remains>3))
actions+=/soul_strike,if=soul_shard<5&buff.demonic_core.stack<=2
actions+=/demonbolt,if=soul_shard<=3&buff.demonic_core.up&((cooldown.summon_demonic_tyrant.remains<10|cooldown.summon_demonic_tyrant.remains>22)|buff.demonic_core.stack>=3|buff.demonic_core.remains<5|time_to_die<25)
actions+=/call_action_list,name=build_a_shard

actions.build_a_shard=demonbolt,if=azerite.forbidden_knowledge.enabled&buff.forbidden_knowledge.react&!buff.demonic_core.react&cooldown.summon_demonic_tyrant.remains>20
actions.build_a_shard+=/soul_strike
actions.build_a_shard+=/shadow_bolt

actions.implosion=implosion,if=(buff.wild_imps.stack>=6&(soul_shard<3|prev_gcd.1.call_dreadstalkers|buff.wild_imps.stack>=9|prev_gcd.1.bilescourge_bombers|(!prev_gcd.1.hand_of_guldan&!prev_gcd.2.hand_of_guldan))&!prev_gcd.1.hand_of_guldan&!prev_gcd.2.hand_of_guldan&buff.demonic_power.down)|(time_to_die<3&buff.wild_imps.stack>0)|(prev_gcd.2.call_dreadstalkers&buff.wild_imps.stack>2&!talent.demonic_calling.enabled)
actions.implosion+=/grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions.implosion+=/call_dreadstalkers,if=(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions.implosion+=/summon_demonic_tyrant
actions.implosion+=/hand_of_guldan,if=soul_shard>=5
actions.implosion+=/hand_of_guldan,if=soul_shard>=3&(((prev_gcd.2.hand_of_guldan|buff.wild_imps.stack>=3)&buff.wild_imps.stack<9)|cooldown.summon_demonic_tyrant.remains<=gcd*2|buff.demonic_power.remains>gcd*2)
actions.implosion+=/demonbolt,if=prev_gcd.1.hand_of_guldan&soul_shard>=1&(buff.wild_imps.stack<=3|prev_gcd.3.hand_of_guldan)&soul_shard<4&buff.demonic_core.up
actions.implosion+=/summon_vilefiend,if=(cooldown.summon_demonic_tyrant.remains>40&spell_targets.implosion<=2)|cooldown.summon_demonic_tyrant.remains<12
actions.implosion+=/bilescourge_bombers,if=cooldown.summon_demonic_tyrant.remains>9
actions.implosion+=/soul_strike,if=soul_shard<5&buff.demonic_core.stack<=2
actions.implosion+=/demonbolt,if=soul_shard<=3&buff.demonic_core.up&(buff.demonic_core.stack>=3|buff.demonic_core.remains<=gcd*5.7)
actions.implosion+=/doom,cycle_targets=1,max_cycle_targets=7,if=refreshable
actions.implosion+=/call_action_list,name=build_a_shard

actions.nether_portal=call_action_list,name=nether_portal_building,if=cooldown.nether_portal.remains<20
actions.nether_portal+=/call_action_list,name=nether_portal_active,if=cooldown.nether_portal.remains>160

actions.nether_portal_active=grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions.nether_portal_active+=/summon_vilefiend,if=cooldown.summon_demonic_tyrant.remains>40|cooldown.summon_demonic_tyrant.remains<12
actions.nether_portal_active+=/call_dreadstalkers,if=(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions.nether_portal_active+=/call_action_list,name=build_a_shard,if=soul_shard=1&(cooldown.call_dreadstalkers.remains<action.shadow_bolt.cast_time|(talent.bilescourge_bombers.enabled&cooldown.bilescourge_bombers.remains<action.shadow_bolt.cast_time))
actions.nether_portal_active+=/hand_of_guldan,if=((cooldown.call_dreadstalkers.remains>action.demonbolt.cast_time)&(cooldown.call_dreadstalkers.remains>action.shadow_bolt.cast_time))&cooldown.nether_portal.remains>(160+action.hand_of_guldan.cast_time)
actions.nether_portal_active+=/summon_demonic_tyrant,if=buff.nether_portal.remains<10&soul_shard=0
actions.nether_portal_active+=/summon_demonic_tyrant,if=buff.nether_portal.remains<action.summon_demonic_tyrant.cast_time+5.5
actions.nether_portal_active+=/demonbolt,if=buff.demonic_core.up
actions.nether_portal_active+=/call_action_list,name=build_a_shard

actions.nether_portal_building=nether_portal,if=soul_shard>=5&(!talent.power_siphon.enabled|buff.demonic_core.up)
actions.nether_portal_building+=/call_dreadstalkers
actions.nether_portal_building+=/hand_of_guldan,if=cooldown.call_dreadstalkers.remains>18&soul_shard>=3
actions.nether_portal_building+=/power_siphon,if=buff.wild_imps.stack>=2&buff.demonic_core.stack<=2&buff.demonic_power.down&soul_shard>=3
actions.nether_portal_building+=/hand_of_guldan,if=soul_shard>=5
actions.nether_portal_building+=/call_action_list,name=build_a_shard

### **BILESCOURGE BOMBER**
warlock="Destromancer"
source=blizzard
origin="/tmp/4xDbJwNifkd7te4JaXmvum.armory.json"
thumbnail="https://render-us.worldofwarcraft.com/character/malganis/44/118242348-avatar.jpg"
spec=demonology
level=120
race=undead
role=spell
position=back
talents=3232321

# Executed every time the actor is available.
actions=potion,if=pet.demonic_tyrant.active|target.time_to_die<30
actions+=/use_items,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/berserking,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/blood_fury,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/fireblood,if=pet.demonic_tyrant.active|target.time_to_die<=15
actions+=/doom,if=!ticking&time_to_die>30&spell_targets.implosion<2
actions+=/demonic_strength,if=(buff.wild_imps.stack<6|buff.demonic_power.up)|spell_targets.implosion<2
actions+=/call_action_list,name=nether_portal,if=talent.nether_portal.enabled&spell_targets.implosion<=2
actions+=/call_action_list,name=implosion,if=spell_targets.implosion>1
actions+=/grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions+=/summon_vilefiend,if=equipped.132369|cooldown.summon_demonic_tyrant.remains>40|cooldown.summon_demonic_tyrant.remains<12
actions+=/call_dreadstalkers,if=equipped.132369|(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions+=/summon_demonic_tyrant,if=equipped.132369|(buff.dreadstalkers.remains>cast_time&(buff.wild_imps.stack>=3|prev_gcd.1.hand_of_guldan)&(soul_shard<3|buff.dreadstalkers.remains<gcd*2.7|buff.grimoire_felguard.remains<gcd*2.7))
actions+=/power_siphon,if=buff.wild_imps.stack>=2&buff.demonic_core.stack<=2&buff.demonic_power.down&spell_targets.implosion<2
actions+=/doom,if=talent.doom.enabled&refreshable&time_to_die>(dot.doom.remains+30)
actions+=/hand_of_guldan,if=soul_shard>=5|(soul_shard>=3&cooldown.call_dreadstalkers.remains>4&(!talent.summon_vilefiend.enabled|cooldown.summon_vilefiend.remains>3))
actions+=/soul_strike,if=soul_shard<5&buff.demonic_core.stack<=2
actions+=/demonbolt,if=soul_shard<=3&buff.demonic_core.up&((cooldown.summon_demonic_tyrant.remains<10|cooldown.summon_demonic_tyrant.remains>22)|buff.demonic_core.stack>=3|buff.demonic_core.remains<5|time_to_die<25)
actions+=/call_action_list,name=build_a_shard

actions.build_a_shard=demonbolt,if=azerite.forbidden_knowledge.enabled&buff.forbidden_knowledge.react&!buff.demonic_core.react&cooldown.summon_demonic_tyrant.remains>20
actions.build_a_shard+=/soul_strike
actions.build_a_shard+=/shadow_bolt

actions.implosion=implosion,if=(buff.wild_imps.stack>=6&(soul_shard<3|prev_gcd.1.call_dreadstalkers|buff.wild_imps.stack>=9|prev_gcd.1.bilescourge_bombers|(!prev_gcd.1.hand_of_guldan&!prev_gcd.2.hand_of_guldan))&!prev_gcd.1.hand_of_guldan&!prev_gcd.2.hand_of_guldan&buff.demonic_power.down)|(time_to_die<3&buff.wild_imps.stack>0)|(prev_gcd.2.call_dreadstalkers&buff.wild_imps.stack>2&!talent.demonic_calling.enabled)
actions.implosion+=/grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions.implosion+=/call_dreadstalkers,if=(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions.implosion+=/summon_demonic_tyrant
actions.implosion+=/hand_of_guldan,if=soul_shard>=5
actions.implosion+=/hand_of_guldan,if=soul_shard>=3&(((prev_gcd.2.hand_of_guldan|buff.wild_imps.stack>=3)&buff.wild_imps.stack<9)|cooldown.summon_demonic_tyrant.remains<=gcd*2|buff.demonic_power.remains>gcd*2)
actions.implosion+=/demonbolt,if=prev_gcd.1.hand_of_guldan&soul_shard>=1&(buff.wild_imps.stack<=3|prev_gcd.3.hand_of_guldan)&soul_shard<4&buff.demonic_core.up
actions.implosion+=/summon_vilefiend,if=(cooldown.summon_demonic_tyrant.remains>40&spell_targets.implosion<=2)|cooldown.summon_demonic_tyrant.remains<12
actions.implosion+=/bilescourge_bombers,if=cooldown.summon_demonic_tyrant.remains>9
actions.implosion+=/soul_strike,if=soul_shard<5&buff.demonic_core.stack<=2
actions.implosion+=/demonbolt,if=soul_shard<=3&buff.demonic_core.up&(buff.demonic_core.stack>=3|buff.demonic_core.remains<=gcd*5.7)
actions.implosion+=/doom,cycle_targets=1,max_cycle_targets=7,if=refreshable
actions.implosion+=/call_action_list,name=build_a_shard

actions.nether_portal=call_action_list,name=nether_portal_building,if=cooldown.nether_portal.remains<20
actions.nether_portal+=/call_action_list,name=nether_portal_active,if=cooldown.nether_portal.remains>160

actions.nether_portal_active=grimoire_felguard,if=cooldown.summon_demonic_tyrant.remains<13|!equipped.132369
actions.nether_portal_active+=/summon_vilefiend,if=cooldown.summon_demonic_tyrant.remains>40|cooldown.summon_demonic_tyrant.remains<12
actions.nether_portal_active+=/call_dreadstalkers,if=(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
actions.nether_portal_active+=/call_action_list,name=build_a_shard,if=soul_shard=1&(cooldown.call_dreadstalkers.remains<action.shadow_bolt.cast_time|(talent.bilescourge_bombers.enabled&cooldown.bilescourge_bombers.remains<action.shadow_bolt.cast_time))
actions.nether_portal_active+=/hand_of_guldan,if=((cooldown.call_dreadstalkers.remains>action.demonbolt.cast_time)&(cooldown.call_dreadstalkers.remains>action.shadow_bolt.cast_time))&cooldown.nether_portal.remains>(160+action.hand_of_guldan.cast_time)
actions.nether_portal_active+=/summon_demonic_tyrant,if=buff.nether_portal.remains<10&soul_shard=0
actions.nether_portal_active+=/summon_demonic_tyrant,if=buff.nether_portal.remains<action.summon_demonic_tyrant.cast_time+5.5
actions.nether_portal_active+=/demonbolt,if=buff.demonic_core.up
actions.nether_portal_active+=/call_action_list,name=build_a_shard

actions.nether_portal_building=nether_portal,if=soul_shard>=5&(!talent.power_siphon.enabled|buff.demonic_core.up)
actions.nether_portal_building+=/call_dreadstalkers
actions.nether_portal_building+=/hand_of_guldan,if=cooldown.call_dreadstalkers.remains>18&soul_shard>=3
actions.nether_portal_building+=/power_siphon,if=buff.wild_imps.stack>=2&buff.demonic_core.stack<=2&buff.demonic_power.down&soul_shard>=3
actions.nether_portal_building+=/hand_of_guldan,if=soul_shard>=5
actions.nether_portal_building+=/call_action_list,name=build_a_shard

### **GEAR**
head=visage_of_the_ascended_prophet,id=160719,bonus_id=4823/1492/4786,azerite_powers=31/183
neck=heart_of_azeroth,id=158075,bonus_id=4936/4929/4930,azerite_level=23
shoulders=exquisitely_aerodynamic_shoulderpads,id=159232,bonus_id=4819/1512/4786,azerite_powers=85/22/458
back=honorbound_artificers_cloak,id=163357,bonus_id=5126/40/1562/4786
chest=honorbound_artificers_robes,id=163280,bonus_id=5125/1532/5138,azerite_powers=14/30/458
tabard=tabard_of_the_honorbound,id=160545
wrists=wraps_of_everliving_fealty,id=158348,bonus_id=4946/1527/4783
hands=mine_rats_handwarmers,id=159231,bonus_id=4946/1517/4786
waist=ouroborial_sash,id=159255,bonus_id=4780/1522/4783
legs=leggings_of_lingering_infestation,id=160615,bonus_id=4798/1808/1477/4786,gems=40mastery
feet=volatile_walkers,id=160714,bonus_id=4798/1477/4786
finger1=seal_of_questionable_loyalties,id=158314,bonus_id=4780/4802/1527/4783,gems=40int,enchant=27haste
finger2=lord_waycrests_signet,id=158362,bonus_id=4946/1517/4786,enchant=9haste
trinket1=ignition_mages_fuse,id=159615,bonus_id=4779/4802/40/1512/4786,gems=30haste
trinket2=emblem_of_zandalar,id=158154,bonus_id=4803/1522/4781
main_hand=titanspark_animator,id=160680,bonus_id=4798/1482/4783,enchant=quick_navigation
off_hand=gilded_hexmaw,id=162458,bonus_id=4803/40/1522/4785

# Gear Summary
# gear_ilvl=350.56
# gear_stamina=4999
# gear_intellect=3995
# gear_crit_rating=784
# gear_haste_rating=897
# gear_mastery_rating=688
# gear_versatility_rating=306
# gear_avoidance_rating=159
# gear_armor=931
default_pet=felguard

**Comment by nasirabtw** [comment]
Bilescourge Bomber doesn't actually spawn a pet. The bilescourge you see there is a pet summoned from Inner Demons. Bilescourge Bomber just deals direct damage (from the player) in an area.

Bilescourge Bombers isn't used in the APL ST because it's a dps loss ST. You're better off just hitting Hand of Gul'dan right now.
