### ISSUE TITLE
Thundercrash set

### ISSUE THREAD

**Issue by Hookie1** [simulationcraft/simc#4571]
https://www.wowhead.com/spell=274225/thundercrash-armor
for first time in xpac a piece of this armor set spawned as WQ,got 325boots

tried to sim boots/bracer to see effect of proc vs ilev of other items
https://www.raidbots.com/simbot/report/biJBM3vxmoycwcLxs71cio/simc

i dont see the proc represented anywhere in logs https://www.wowhead.com/spell=274226/static-bolt

would mostly be an instance of insane titanforge to use the set,but depending where the WQ item level cap lands in 8.1 and beyond the sets could become relevant or for new toons

these would be the other dps related sets,no idea if any of them are functional
https://www.wowhead.com/item-set=1334 2 pieces: Increases Intellect by 82.
https://www.wowhead.com/item-set=1338/frenzied-battleplate 2 pieces: Your damaging spells and abilities have a chance to send you into a wild frenzy, granting you 225 Strength for 15 sec.
https://www.wowhead.com/item-set=1335/venombite-garb 2 pieces: Your damaging spells and abilities have a chance to poison your target, dealing 670 damage every 1.5 seconds.

**Comment by scamille** [comment]
If this hasn't been resolved up until now, it is unlikely that it ever will.

The main problem with low level items (and characters) is that it takes effort to implement and test things out, and the time of most class developers is limited and focused on max level current raid content.
