### ISSUE TITLE
Need to disable freeze effect for raid boss

### ISSUE THREAD

**Issue by LiangYiJlu** [simulationcraft/simc#4574]
Simc uses 1 s as the default freeze duration. I don't know how to turn it off. When frozen_duration is set to 0 or lower, freeze effects are assumed to be permanent. 
Most bosses (and the biggest dummy which is the favorite of many frost mages) can't be frozen. But freeze effect happens even when you set target level to raid boss. This will lead to higher results in most cases. In my test, it's about 10%. 
So I hope to add an option to turn off freeze effect.

**Comment by vituscze** [comment]
Freeze effects are not applied to boss enemies that are 3 levels above the player level.

**Comment by LiangYiJlu** [comment]
Thanks. It seems I made some mistakes in the test. Set target to level solved the problem.
