### ISSUE TITLE
Enemy abilities

### ISSUE THREAD

**Issue by 012299** [simulationcraft/simc#4584]
Posting for kanka#6569@discord:
Enemy abilities
Following the simc instrucitions, I'm only able to create a single instance of meleenuke or spellnuke, I'd need a number of them to model bossfights. Please excuse me if such functionality exists already, but it's not mentioned in the wiki. (Especially since I'd need them to properly add and substract damage taken stacks, and I lose one of four(?) abilities already to a pseudo-
tankswap cast.

**Comment by scamille** [comment]
As explained on Discord, do not use cooldown=x option, instead use line_cd=x.

```
enemy=M_Fetid_OT
actions+=/spell_nuke,damage=32140,range=7500,attack_speed=2.5,if=time>28,line_cd=30
actions+=/melee_nuke,damage=505000,range=7500,line_cd=6,if=time>7&time<200,apply_debuff=50
actions+=/melee_nuke,damage=505000,range=7500,line_cd=6,if=time>200,apply_debuff=50
actions+=/spell_aoe,damage=2500,attack_speed=6.5,range=500,line_cd=35,if=time>56
```
works fine.
