### ISSUE TITLE
using wrong crit chance

### ISSUE THREAD

**Issue by Romalla** [simulationcraft/simc#4590]
sims are using melee crit chance for my fire mage (havent tested any others) blizz ui has my crit at 1026, annd the armory import profile shows it at 933 which raid bots shows as my melee crit chance.

I expected to have more crit than haste allowing reorigination array to provide crit, but my crit shows slightly less then what the blizz ui says and it is now giving me haste as my RA buff

i can provide a screen shot of blizz ui and of simc import if you need it

latest nightly build as of oct 27th 2018

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=100000
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=10
process_priority=High
statistics_level=1
### Begin simulateText ###
mage="Romalla"
source=blizzard
origin="https://us.battle.net/wow/character/illidan/romalla/advanced"
thumbnail="https://render-us.worldofwarcraft.com/character/illidan/200/132945352-avatar.jpg"
spec=fire
level=120
race=troll
role=spell
position=back
professions=tailoring=141/enchanting=150
talents=https://worldofwarcraft.com/en-us/game/talent-calculator#mage/fire/talents=3231123

**Comment by vituscze** [comment]
The spells are most definitely using spell crit chance. There was an issue with Reorigination Array not granting the right buff which should be fixed now.
