### ISSUE TITLE
SHADOW PRIEST dps bug

### ISSUE THREAD

**Issue by Mglt-b** [simulationcraft/simc#4596]
### Describe the bug
Dps of Shadow Priest was buggued, 87 415 670 dps

### Expected behavior
T22_Priest_Shadow : 87415670 dps

![image](https://user-images.githubusercontent.com/20703341/48125035-115f1200-e27e-11e8-9c6c-ccab5406570b.png)

### To Reproduce
Just go on
http://www.simulationcraft.org/reports/T22_Raid.html

### Additional information
Ty for job

**Comment by vituscze** [comment]
This was fixed yesterday, closing.
