### ISSUE TITLE
Simcraft is hanging upon open (blank white screen)

### ISSUE THREAD

**Issue by klepp0906** [simulationcraft/simc#4601]
### Describe the bug
SimC hangs at a blank white screen upon opening.

### Expected behavior
SimC to open and function as intended.

### To Reproduce
Simply double clicking the exe, or right clicking run-as-admin both result in the same webengine not responding error/hang.

### Additional information
* SimulationCraft Version 801-02 (newest nightly but have tried man versions going back as far as the builds allow (sept-1 iirc).  They did work at that point in time so I imagine its something else that was updated potentially interfering.  Its been happening for weeks if not months now, i periodically try again with nightlies every so often.

* If SimulationCraft is crashing, please include your **dxdiag** file - https://pastebin.com/tZdZmh6P 

***simc_gui.simc** file or contents
  File not present since I cannot run a sim to generate it.

I have already purged the simcraft folder from appdata/local and roaming.  This presented me with the box (your gui settings have been reset blah blah) which displayed and functioned properly, however after closing that box, the main simc webengine/window hung blank white as per usual.

anything else i can provide to help figure this out, please let me know.

**Comment by klepp0906** [comment]
Jesus, no wonder it took me so long to get ANYWHERE with this issue.

I found something that narrows it down a bit.   Purely by chance.  Still requires the know how of someone much higher up the food chain than I.

I went to run synergy, which uses a similar interface, and to my surprise - it opened to a blank white window as well.

Turned out, if i moved the non-responding window to my other display and closed it there, in order to save that location and have it re-open there next time, it works.

Tried this with simcraft, same thing.  Will launch properly on one display but not the other.

Now out of dozens of pieces of software i run on my pc, these are the only two that present this issue.  I have them set to open on my accessory display for obvious reasons, and would like to keep it as such.

Any ideas why its behaving in this fashion?  Both displays are connected to the same gpu ftr.

**Comment by AlexanderKenny** [comment]
Both make use of QT for their graphical UI the issue likely originates there however I am not nearly familiar enough with their codebase to diagnose the issue unfortunately.

You could open an issue over there and someone may be able to help you though you'll want to include your system info when you do as this is definitely not a widespread issue so hardware/driver info will be needed.

https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by klepp0906** [comment]
Okie doke, ill head over tehre and make a post.  Will report back if anything concrete comes of it.  Thank you for the link.

**Comment by klepp0906** [comment]
Hey guys.. I posted over at the QT bug report link you shared.. and theyre asking what version of QT was used to build simc?

**Comment by AlexanderKenny** [comment]
I believe it's currently using 5.9.1

**Comment by klepp0906** [comment]
ok, 5.9.1 doesnt seem to be a selectable option, but 5.9 is so we'll go with that.

theyre telling me they may not be able to help any further without attaching a debugger which puts it squarely outside my realm.  

time will tell.

**Comment by klepp0906** [comment]
fwiw - I found the culprit.  Asus Sonic Studio/Radar.

having it installed somehow breaks anything QT related.  foudn someone posting about his autodesk/maya presenting said behavior and that was the fix.   Was for me as well.

was going out of my mind as it affected simc, citra, synergy... and i was just waiting to run across something else using qt to cause me to lose more hair 📦 

unsure if this info needs to go to asus, or qt or both... or if anything will come of it.  QT wants stack/trace info or debug info or something or another which is unfortunately above my pay grade so to speak.

**Comment by klepp0906** [comment]
seems its NahimicSvc64.exe that does it specifically.

**Comment by AlexanderKenny** [comment]
Glad you figured it out. Should pass it along to the qt guys to look at if you haven't!
