### ISSUE TITLE
simcraft no run

### ISSUE THREAD

**Issue by Caliya** [simulationcraft/simc#4606]
Hello, I have a problem with simulationcraft for 2 weeks see 3.

When I copy my simc wow to simcraft and I run the simultion, nothing happens the bar is empty, I can stay on the page 1 hour it will not change anything.

Someone can help me please.
thank you in advance

**Comment by seanpeters86** [comment]
Have you tried downloading the nightly build from here? http://downloads.simulationcraft.org/?C=M;O=D

You can also try using https://www.raidbots.com

**Comment by seanpeters86** [comment]
Going to close this issue for now as you need to give more information about the potential issue. If you still encounter the problem using the nightly build and raidbots.com feel free to reopen the issue or contact us in the discord: https://discord.gg/tFR2uvK
