### ISSUE TITLE
Enhancement Shaman azerite power problem between "Lightning Conduit" and "Thunderaan's Fury" 

### ISSUE THREAD

**Issue by tangxianghui03** [simulationcraft/simc#4607]
Lighting conduit id is 223, and thunderaan's fury id is 530.

When I try to compare dps difference, lighting conduit will using thunderran's fury buff, also shows in gear as thunderran's fury.
But when i run tuhunderran's fury, shows in gear but no buff.

SimulationCraft 801-02
for World of Warcraft 8.1.0 PTR (wow build level 28085)

simc input:
shaman="Lighting conduit"
level=120
race=pandaren
region=us
server=gladiators_sanctum
role=attack

talents=3221233
spec=enhancement

head=target_tracking_headgear,id=165543,bonus_id=4822/1507,reforge=6,azerite_powers=223
neck=,id=158075,bonus_id=4936/4929/4930/1540,reforge=11,azerite_level=35
shoulder=mantle_of_the_soulbinders_caress,id=165537,bonus_id=4822/1507
back=,id=160643,gem_id=154127,bonus_id=4800/1808/1507/4786,reforge=6
chest=flag_officers_overcoat,id=165831,bonus_id=4822/1507
wrist=,id=160629,bonus_id=4800/1517/4783,reforge=6
hands=,id=163948,enchant_id=5932,bonus_id=1517/4784,reforge=54
waist=,id=159353,bonus_id=5010/1562/4784,reforge=16
legs=,id=160716,bonus_id=4800/1507/4786,reforge=6
feet=,id=160628,bonus_id=4800/1507/4786,reforge=6
finger1=,id=160645,enchant_id=5943,bonus_id=4800/1512/4783,reforge=6
finger2=,id=159458,enchant_id=5943,bonus_id=5010/40/1567/4784,reforge=35
trinket1=,id=159614,bonus_id=5010/1542/4786,reforge=16
trinket2=,id=155881,gem_id=154127,bonus_id=5010/4802/1547/4783,reforge=16
main_hand=,id=160682,enchant_id=5950,bonus_id=4800/1517/4783,reforge=6
off_hand=,id=159653,enchant_id=5965,bonus_id=5010/1557/4784,reforge=35

shaman="thunderran's fury"
level=120
race=pandaren
region=us
server=gladiators_sanctum
role=attack

talents=3221233
spec=enhancement

head=target_tracking_headgear,id=165543,bonus_id=4822/1507,reforge=6,azerite_powers=530
neck=,id=158075,bonus_id=4936/4929/4930/1540,reforge=11,azerite_level=35
shoulder=mantle_of_the_soulbinders_caress,id=165537,bonus_id=4822/1507
back=,id=160643,gem_id=154127,bonus_id=4800/1808/1507/4786,reforge=6
chest=flag_officers_overcoat,id=165831,bonus_id=4822/1507
wrist=,id=160629,bonus_id=4800/1517/4783,reforge=6
hands=,id=163948,enchant_id=5932,bonus_id=1517/4784,reforge=54
waist=,id=159353,bonus_id=5010/1562/4784,reforge=16
legs=,id=160716,bonus_id=4800/1507/4786,reforge=6
feet=,id=160628,bonus_id=4800/1507/4786,reforge=6
finger1=,id=160645,enchant_id=5943,bonus_id=4800/1512/4783,reforge=6
finger2=,id=159458,enchant_id=5943,bonus_id=5010/40/1567/4784,reforge=35
trinket1=,id=159614,bonus_id=5010/1542/4786,reforge=16
trinket2=,id=155881,gem_id=154127,bonus_id=5010/4802/1547/4783,reforge=16
main_hand=,id=160682,enchant_id=5950,bonus_id=4800/1517/4783,reforge=6
off_hand=,id=159653,enchant_id=5965,bonus_id=5010/1557/4784,reforge=35

**Comment by vituscze** [comment]
Lightning Conduit no longer exists on PTR, all references to it have been replaced with Thunderaan's Fury. This includes the trait ids as well, Thunderaan's Fury now has id 223.

**Comment by tangxianghui03** [comment]
> Lightning Conduit no longer exists on PTR, all references to it have been replaced with Thunderaan's Fury. This includes the trait ids as well, Thunderaan's Fury now has id 223.

after ptr patch 28616， Lighting Conduit is back and appears in azerite gear in next raid.

**Comment by lgkern** [comment]
Lightning Conduit was removed in 8.1 and isn't usable as an Azerite power because of it
