### ISSUE TITLE
warlock nether_portal should have only 15s

### ISSUE THREAD

**Issue by MENGYU6565** [simulationcraft/simc#4624]
### Describe the bug
warlock's nether portal lasting 20s in the sim but it only have 15s now

### Expected behavior
it should only last for 15s after patch 8.1

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by MENGYU6565** [comment]
warlock's nether_portal should only have 15s in current patch, but in the simc, it have 20s

**Comment by frmimue** [comment]
The actual duration of the Nether Portal is 15 seconds, just the APL is not optimized and stays in the Nether Portal rotation for 20 seconds.
I proposed fixes for the APL here: #4655
