### ISSUE TITLE
unable to improt character from EU

### ISSUE THREAD

**Issue by Zstriker1** [simulationcraft/simc#4633]
keep getting this, 
"Unable to download JSON from 'https://eu.api.battle.net/wow/character/whatever/whatever?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'."

while all variables locales set EU it's still put `en_US` on this link, so can't import character at all from armory

**Comment by AlexanderKenny** [comment]
That's just the localization of text (in this case English). The actual issues has to do with the new community API and simc not yet being migrated. That said I would have to look into if there are any plans to continue supporting the API/any work to migrate it in progress yet before supplying a fix as the new setup/OAuth could cause some issues with us supplying a singular key.

**Comment by Zstriker1** [comment]
I have my own api and want to use,  but that minor issue not changing US to GB(I bet other locales not changing too) make link invalid, manually working fine
otherwise maybe remove this option at all to not mislead people

**Comment by AlexanderKenny** [comment]
Should be fixed in recent versions.
