### ISSUE TITLE
Precombat ability with precast time not having its count incremented.

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#4649]
### Describe the bug

The "count" in the SimC report is not apparently incremented for abilities with a precast time.

### Expected behavior

Given that entry #8 (bestial_wrath) was actually cast by the sim, I expected the count for that entry to show **1**.

\# | count | action,conditions
-- | -- | --
0 | 0.00 | flask
1 | 0.00 | augmentation
2 | 0.00 | food
3 | 0.00 | summon_pet
4 | 0.00 | snapshot_stats
5 | 0.00 | potion
6 | 0.00 | aspect_of_the_wild,precast_time=2.2,if=!azerite.primal_instincts.enabled
7 | 0.00 | bestial_wrath,precast_time=1.1,if=!azerite.primal_instincts.enabled
8 | 0.00 | bestial_wrath,precast_time=1.5,if=azerite.primal_instincts.enabled

Sample Sequence:  01235**8**...

So entry 8 should have a 1.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

I simmed via RaidBots (in case that has any impact); you can use the default Beast Mastery profile to observe this behavior.

### Additional information
* SimulationCraft Version (required)

Git Hash 8189f921d6; built 17 Dec 2018.

**Comment by Hekili** [comment]
I guess it's worth noting that none of the precombat actions are incremented, actually.  I'll test if this is RaidBots-only.

**Comment by Hekili** [comment]
This behavior occurs in simc via the GUI as well.

actions.precombat Executed before combat begins. Accepts non-harmful actions only.

\#	count	action,conditions
-- | -- | --
0	0.00	flask
1	0.00	augmentation
2	0.00	food
3	0.00	summon_pet
4	0.00	snapshot_stats
5	0.00	potion
6	0.00	aspect_of_the_wild,precast_time=1.1,if=!azerite.primal_instincts.enabled
7	0.00	bestial_wrath,precast_time=1.5,if=azerite.primal_instincts.enabled

**Comment by navv1234** [comment]
This is "intended behavior" in the context of the code itself. Last I checked, fixing it was non-trivial.
