### ISSUE TITLE
Feral druid single_target APL

### ISSUE THREAD

**Issue by snikz** [simulationcraft/simc#4656]
actions.single_target+=/ferocious_bite,target_if=dot.rip.ticking&dot.rip.remains<3&target.time_to_die>10&(target.health.pct<25|talent.sabertooth.enabled)

This line is outdated since 8.1 Ferocious Bite no longer refresh Rip on target < 25% health.

**Comment by seanpeters86** [comment]
Can you make a PR with this change and provide a sim that shows the increase with the new apl? Feral druid apl starts here https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_druid.cpp#L8018

**Comment by snikz** [comment]
It is aready fixed in one of the latest releases.
