### ISSUE TITLE
Unable to open the client because of these error messages welp

### ISSUE THREAD

**Issue by Twiggy-jw** [simulationcraft/simc#4660]
### Describe the bug

Unable to open after downloading

![simcerror](https://user-images.githubusercontent.com/46061910/50370765-d97c0780-0569-11e9-96e1-9ccf920299dd.png)

### Expected behavior
I'd expect the simulationcraft 64bit installer to open the client after the install, but it will not.

### To Reproduce
Download it 
### Additional information
* SimulationCraft Version 64bit installer of 8.0.1

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Twiggy-jw** [comment]
Seriously. I still cant download Simcraft

**Comment by AlexanderKenny** [comment]
Reinstall visual c++ redistributable. Windows should automatically fetch one in updates if you're on a licensed version or just do it manually. It's required for a lot more than just simc.

**Comment by seanpeters86** [comment]
Are you downloading the nightly build here? http://downloads.simulationcraft.org/?C=M;O=D

Alternatively you can also try using raidbots.com

**Comment by Twiggy-jw** [comment]
Thank you guys, I definitely needed to download the C++ redistributable, worked perfectly and thank you for the help
