### ISSUE TITLE
Ancient Bulwark azerite trait not simming at all?

### ISSUE THREAD

**Issue by vpoluektov** [simulationcraft/simc#4661]
Ancient Bulwark azerite trait is now in game, dropping for Alliance, at least, from the new Darkshore world boss. However, it looks like it is not simming at all. Its index is 522, and entering it into the sim shows the name correctly - but other than that, it does not affect damage at all, the numbers showing are exactly the same as if the trait was not even selected. Basically, replacing this line:
chest=sharpshooters_chainmail_hauberk,id=161469,bonus_id=5120/1492/4786/4775,azerite_powers=30/15/13
with this:
chest=sharpshooters_chainmail_hauberk,id=161469,bonus_id=5120/1492/4786/4775,azerite_powers=522/30/15/13
does not change the results one bit.

The simulation was run using patchwerk profile, so I would have expected seeing the versatility difference - but it completely isn't there.

**Comment by Pewtro** [comment]
In simc as of https://github.com/simulationcraft/simc/commit/bdab21b33ddc1d3b50693f1d76892ed207352d1a
