### ISSUE TITLE
[Unholy] Dark Transformation Improvements for Adds

### ISSUE THREAD

**Issue by Tzodk** [simulationcraft/simc#4666]
change

> actions.cooldowns+=/dark_transformation

to

> actions.cooldowns+=/dark_transformation,if=(!raid_event.adds.exists|raid_event.adds.in>15)

This replicates player behavior as well as is a large increase in aoe. See here: https://www.raidbots.com/simbot/report/jrUwFXijNTXZCjhAxSqTZ3

**Comment by seanpeters86** [comment]
@Tzodk can you please open a pull request with this change? https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_death_knight.cpp#L7950

**Comment by Melekus** [comment]
Applied in https://github.com/simulationcraft/simc/pull/4684
