### ISSUE TITLE
[Feral] Iron Jaws Inflated

### ISSUE THREAD

**Issue by Maxkittty** [simulationcraft/simc#4669]
After doing a sim with a tripple Iron Jaws gearset, (https://www.raidbots.com/simbot/report/9FrTe7bnTSh3vheQEzxcJa) I found that Maim's numbers were simming much higher than what it was actually doing ingame. With each trait giving around +2600 damage for each CP, plus the 5000 damage I have from Maim baseline, it hit for no more than 50k and crit for 80-100k, far lower than the numbers in the sim. 

I looked at the changelog of the trait on wowhead (https://www.wowhead.com/spell=276021/iron-jaws) and the sim seems to very accurately reflect the numbers of the 28724 build's tooltip, however, ingame, the trait never received a change in that build; it still has the same numbers as it did during the 28711 build. The tooltip didn't change and the damage it deals is the exact same. This is causing sims using the trait to be inflated, giving it more value than it really has. Maybe it's a problem with the build on Blizzard's part?

Edit: Looks like the same issue is occurring with Untamed Ferocity and Gushing Lacerations.

**Comment by seanpeters86** [comment]
@Maxkittty can you provide a combat log that shows the damage it is doing in-game to compare?

**Comment by Maxkittty** [comment]
Actually, disregard this. It looks like it was a tooltip issue on Blizzard's part and they seem to have fixed it on the 8.1.5 PTR.
