### ISSUE TITLE
Warlock demonology profile trinkets

### ISSUE THREAD

**Issue by chugbug14** [simulationcraft/simc#4675]
Warlock demo profile syncs trinket use to demonic tyrant which works well for trinkets that have 1.5min CD. For trinkets that have 2 min CD I get higher DPS when i synced the trinket to grim felgaurd. I got about 0.4% dps increase when I synced the mage ignition fuse trinket to grim felguard.

**Comment by seanpeters86** [comment]
Can you provide a PR to this file with the change and show the dps improvement? 

https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/warlock/sc_warlock_demonology.cpp#L1037

**Comment by chugbug14** [comment]
DPS with mage ignition fuse synced to tyrant
[https://www.raidbots.com/simbot/report/p1M447htZ5PHdBd6ZwJoPE](url)

DPS with mage ignition fuse synced to grim felguard
[https://www.raidbots.com/simbot/report/sEz9umtDV15ivU2skoAnz5](url)

**Comment by chugbug14** [comment]
sim DPS with mage ignition fuse synced to tyrant (23030 dps)
https://www.raidbots.com/simbot/report/2hvvgG11TF91CUJhyV7bmY

sim DPS with mage ignition fuse synced to grim felguard (23233 dps)
https://www.raidbots.com/simbot/report/sEz9umtDV15ivU2skoAnz5
