### ISSUE TITLE
[Warlock] Havoc sets spells to new target permanently.

### ISSUE THREAD

**Issue by Azevara** [simulationcraft/simc#4676]
### Describe the bug
When cycling targets to apply Havoc to a secondary target, casting a spell that duplicates during Havoc will set the target of that spell to permanently be the second target.

This appears to be the case for the baseline Havoc copying behavior in the Destruction module, and will most likely occur for any spell that can be copied using Havoc.

### Expected behavior
Since the target is never cycled or set in the action in question, it should always hit the primary target.

### To Reproduce
You can reproduce the problem concisely using a two line APL for Destruction in a 2 target sim:
```
actions+=/havoc,cycle_targets=1,if=!(target=sim.target)
actions+=/incinerate
```

After the first Incinerate, all subsequent Incinerates will be targeting the second enemy.

### Additional information
* SimulationCraft Version (required)
SimulationCraft 810-02 for World of Warcraft 8.1.0 Live (wow build 28768)

**Comment by vituscze** [comment]
Should be fixed now, closing.
