### ISSUE TITLE
Import from World of Warcraft fails.  

### ISSUE THREAD

**Issue by jb322** [simulationcraft/simc#4686]
### Describe the bug
When name is entered into import page, import comes back with the following

# BCP API: Unable to download player from 'https://us.api.battle.net/wow/character/area-52/XXXXXXXXX?fields=talents,items,professions&locale=en_US&apikey=', JSON download failed

I tried placing Armory string in bottom, read directions, set up and API Key with Battle.net

**Comment by navv1234** [comment]
We have not released a new Simulationcraft version yet that supports the new API endpoints from Blizzard, which is why the armory import is failing. New release will hopefully be built soon.

**Comment by hoaaarrrhh** [comment]
website's answer is:
{"status":"nok", "reason": "Error! The service you are trying to reach has been moved. Please refer to develop.battle.net for more information."}

**Comment by navv1234** [comment]
Correct. We will hopefully be releasing a new version of Simulationcraft in the next few days that will add support for the new service.

**Comment by moonbatmike** [comment]
# Unable to download JSON from 'https://us.api.battle.net/wow/character/cenarius/markypoo?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.
I see everyone has this issue

**Comment by Flayzen** [comment]
Any ETA on when this program will become functional again? Still unable to import characters.

**Comment by vituscze** [comment]
The program is already functional, just grab the latest version here: http://downloads.simulationcraft.org/?C=M;O=D
