### ISSUE TITLE
Can't import any characters.

### ISSUE THREAD

**Issue by jeffreylight** [simulationcraft/simc#4693]
Cant import any characters:
Windows 10
Simc 810-01
Used the 7z File download and unzipped
Also tried the Windows 64bit 7z file — 64bit installer - same result
Went to Import tab
Entered US - Cenarion Circle - Grenchlok
Get the following error:

#Profile will be downloaded into a new tab.
#
#Clicking Simulate will create a simc_gui.simc profile for review.

#Unable to generate profile from:

#Unable to download JSON from 'https://us.api.battle.net/wow/character/cenarion-circle/grenchlok?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

Did some wiki reading.
Went to Blizz and got a Client ID (API key)
Put it in the Globals in Armory API Key field.
Didn't see a place to put the Client Secret

Same error.

**Comment by jeffreylight** [comment]
Cant import any characters:
Windows 10
Simc 810-01
Used the 7z File download and unzipped
Also tried the Windows 64bit 7z file — 64bit installer - same result
Went to Import tab
Entered US - Cenarion Circle - Grenchlok
Get the following error:

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.battle.net/wow/character/cenarion-circle/grenchlok?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

Did some wiki reading.
Went to Blizz and got a Client ID (API key)
Put it in the Globals in Armory API Key field.
Didn't see a place to put the Client Secret

Same error.

**Comment by navv1234** [comment]
You need a new version of the client. 810-01 does not have any support for the new api endpoints. There are nightlies for 810-02 that support it at http://downloads.simulationcraft.org/?C=M;O=D

**Comment by jeffreylight** [comment]
Thank you!  Back up and running now.

**Comment by CBWAR1** [comment]
I have the same issue with 810-02

**Comment by bluesh34** [comment]
I have the same issue too.  Anyone know what the problem is and if/how it can it be fixed please?
