### ISSUE TITLE
Please link the executable with static libraries

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4702]
In my experience linking with C runtime DLLs is asking for trouble for multiple reasons. One reason is that the DLLs are not part of a standard Windows distribution and the user will have to go hunting for the VC runtimes to install, if he even understands the error messages. Another issue may be the shared heap that other DLLs might mess with; it's better to have your own heap. Outside of COM and of obligatory OS modules, the only reason to have DLLs at all is to economise on DISK and on some memory space (the TEXT segment usually), but that was 20 years ago, not relevant anymore. Please provide a statically linked version if you can, as an option even, Many thanks.

**Comment by navv1234** [comment]
As far as I understand that would also imply a statically linked Qt version. As Qt pre-builts come with only in dynamically linked versions, it'd require people who want to build the GUI to also build a statically linked version of Qt.

**Comment by scamille** [comment]
statically linking QT is certainly a show-stopper. Back in the days it was nearly impossible to get Webkit compiled with it anyways. Not sure how it is now, but certainly not worth the effort.

Now that Windows has moved to this universal C runtime, the problem of having to install the correct VSRedist should also be a problem of the past.

Then there is curl, which also rather likes to be linked dynamically.

In any case, I don't really see much to gain here for our Windows releases. If you want static libs for your CLI binary, or on Linux, that should be quite simple to do yourself.
