### ISSUE TITLE
Simc Build out of date?

### ISSUE THREAD

**Issue by Maxkittty** [simulationcraft/simc#4704]
According to simcraft, the API is using the build, 28768, but the current wow build on live is actually 29088. I might be wrong but is it out of date? 

<img width="1273" alt="screen shot 2019-01-22 at 12 50 44 pm" src="https://user-images.githubusercontent.com/46368024/51564835-31e24580-1e45-11e9-8a16-535dc0b2eb55.png">

**Comment by navv1234** [comment]
People just forget to update the wow build level, since it's not automated.

**Comment by Maxkittty** [comment]
I see, thanks for the quick response! Will it be updated anytime soon? I know there were several changes to abilities that were added in the most recent build that aren’t in simc at the moment

**Comment by navv1234** [comment]
The only thing not up to date is the number. Simc should be fully up to date with any class changes that have occurred.

**Comment by Maxkittty** [comment]
Actually, I remember seeing that the numbers for a few traits for Feral Druid seem to be incorrect due to an issue on Blizzard's part where the ability's data showed them doing more or less damage than it did ingame. These patch notes were actually part of the PTR patch notes for 8.1.5 over on MMOchampion, but on live, ingame, the value of the traits match the changes that I screenshotted perfectly, so I think they may have hotfixed it without putting it in the notes. 

<img width="1124" alt="screen shot 2019-01-22 at 2 08 05 pm" src="https://user-images.githubusercontent.com/46368024/51569221-9eaf0d00-1e50-11e9-88c4-3990994471e6.png">

These changes don't seem to be in simc though, considering that one sim with Iron Jaws was causing maim to sim for about 70% more damage than it did ingame. I don't really have any logs to show but I can try to gather more info if you need. The data looks incorrect to me though, so here's my log that I used for the trait. https://www.raidbots.com/simbot/report/bfqRGoauCwFgkC9obWSzA3
