### ISSUE TITLE
[Havoc][APL] Fel barrage usage does not respect haste buffs

### ISSUE THREAD

**Issue by iPilot** [simulationcraft/simc#4715]
### Describe the bug
Fel barrage usage in havoc sims is incorrect, especially for demoniq build, cause it casts barrage without any haste buff provided by meta and furious gaze azerite trait.

### Expected behavior
Fel barrage should be casted right after eye beam

### To Reproduce
Default simulation for demoniq build

### Additional information
SimulationCraft 810-02
for World of Warcraft 8.1.0 Live (wow build level 29088, git build e4a4a585c4)

**Comment by seanpeters86** [comment]
@iPilot can you provide sim dps comparison with your suggested APL change?

**Comment by EvanMichaels** [comment]
I could potentially see waiting for Eye Beam in some cases here when using Furious Gaze. Although it's unlikely to be major, I'll investigate.

**Comment by EvanMichaels** [comment]
https://github.com/simulationcraft/simc/commit/0e855e697e9696c672a9d34d17672edbd2582d0e
