### ISSUE TITLE
impossible to import my character

### ISSUE THREAD

**Issue by enaidLOH** [simulationcraft/simc#4717]
### Is your feature request related to a problem? Please describe.
error while importing my character
version 810-01

### Describe the solution you'd like

# Unable to download JSON from 'https://eu.api.battle.net/wow/character/elune/enaïd?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

### Describe alternatives you've considered
try and try again. removing the ï

**Comment by enaidLOH** [comment]
it is a hunter.

**Comment by AlexanderKenny** [comment]
Update your version you have one from before Blizzard changed the API.
