### ISSUE TITLE
unable to import Characters

### ISSUE THREAD

**Issue by Unrak** [simulationcraft/simc#4719]
### Describe the bug
Clicking on the import tab, and filling the requirements produces an error

### Expected behaviour
I expected a character to load 

### To Reproduce
using any of my characters on Earthen Ring, EU or Argent Dawn, EU  produces the error
Unrak (ER)
Andrite (ER)
Sarella(ER)
Nathraelle (AD)

I get Import Failed:
# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.battle.net/wow/character/argent-dawn/Nathraelle?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

### Additional information
* SimulationCraft Version (required)
810-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
 ### SimulationCraft 810-01 for World of Warcraft 8.1.0 Live (wow build 28768) ###
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.battle.net/wow/character/earthen-ring/Sarella?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by AlexanderKenny** [comment]
Update your version to one that supports the Blizzard API changes.
