### ISSUE TITLE
Import Character from eu.api.battle.net failed

### ISSUE THREAD

**Issue by marcbourbaki** [simulationcraft/simc#4721]
### Describe the bug
I can't import a caracter from eu.api.battlenet.
at this adress : https://eu.api.battle.net/wow/character/confrerie-du-thorium/Bourbaki?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]
I can read : {"status":"nok", "reason": "Error! The service you are trying to reach has been moved. Please refer to develop.battle.net for more information."}

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)
version 810-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.battle.net/wow/character/confrerie-du-thorium/Bourbaki?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by AlexanderKenny** [comment]
Blizzard changed their API you need to update your simcraft to a recent version which supports this change.

**Comment by marcbourbaki** [comment]
I have the latest version proposed :
<https://www.simulationcraft.org/2018/12/19/release-810-01.html>
SimulationCraft 8.1.0, release 1<https://www.simulationcraft.org/2018/12/19/release-810-01.html>


Released on 19 Dec 2018




________________________________
De : AlexanderKenny <notifications@github.com>
Envoyé : Thursday, January 31, 2019 10:03:47 AM
À : simulationcraft/simc
Cc : marcbourbaki; Author
Objet : Re: [simulationcraft/simc] Import Character from eu.api.battle.net failed (#4721)


Blizzard changed their API you need to update your simcraft to a recent version which supports this change.

**Comment by Melekus** [comment]
You should use the latest nightly version as releases don't happen very often.

Nightly versions can be found here http://downloads.simulationcraft.org/?C=M;O=D

**Comment by disshishkov** [comment]
Have the same issue on 820-01
