### ISSUE TITLE
When two Bile-Stained Crawg Tusks are equipped, vile bile (the proc) appears to sim incorrectly.

### ISSUE THREAD

**Issue by ferzerp** [simulationcraft/simc#4727]
### Describe the bug
Simulationcraft appears to currently treat each Bile-Stained Crawg Tusk's (item ID: 159653) proc as a separate debuff that can stack to 3 independently.

### Expected behavior
Vile bile (Spell ID: 281721) procs from either weapon apply to the same debuff and will both contribute to the max 3x stacks.  This causes the sim to model it incorrectly as sometimes it will have the wrong numbers of stacks present when its model causes the one debuff to expire (when in the game there would be a refresh and a second stack).  Sometimes the stack count is too high since simulationcraft allows for two debuffs that can discretely stack to 3 each, for a total of 6 stacks which does not occur in game.

### To Reproduce
Equip two bile-stained crawg tusks in game and use them in combat.  Only one debuff will ever appear, with a max of 3 stacks.  If more in game logging info is needed, I can provide if I am told what is needed.

### Additional information
* SimulationCraft Version (required): 810-02

**Comment by AlexanderKenny** [comment]
Could you shoot me a five minute training dummy log of someone using two to look over? I'll make any adjustments as needed :)

**Comment by ferzerp** [comment]
[WoWCombatLog.txt](https://github.com/simulationcraft/simc/files/2827750/WoWCombatLog.txt)

Here you go.

**Comment by gastank** [comment]
Should be fixed in 9ef2ebe25e3fecb29c427a85b13163147a1486ab and ebc38b1cda3c5de91cf611c99c8ed4ad19fe5d2a. Please re-open if further issues are found.
