### ISSUE TITLE
using Daelin Proudmoore's Saber in both hands activates the set bonus

### ISSUE THREAD

**Issue by nzall** [simulationcraft/simc#4730]
### Describe the bug
Simming a Demon Hunter with a Daelin Proudmoore's Saber in both hands triggers the set bonus that adds frost damage to your attacks.

### Expected behavior
The set bonus should most likely only trigger if using a ring and a sword, and not 2 swords, though I can't seem to find ingame evidence for that.

### To Reproduce
Run a simulation on any character that can dual wield swords with 2 Daelin Proudmoore's Sabers equipped. Example of sim on Raidbots that shows the issue: https://www.raidbots.com/simbot/report/mEfZWUb4AvXRDKpvDH76Q6/simc

### Additional information
* SimulationCraft Version (required)
Nightly build used by Raidbots, based on commit https://github.com/simulationcraft/simc/commit/c1758f7df4

**Comment by vituscze** [comment]
Double swords shouldn't enable the set bonus, as of 2eaaaa8e4010cf7ac9bb4e9fb231fc35d4df36bd

Going to keep this one open until we have in-game confirmation.
