### ISSUE TITLE
Problem with ADK Trinkets rotation

### ISSUE THREAD

**Issue by geraint425** [simulationcraft/simc#4731]
Good day. I watched the action priority list and saw during the simulation that he suggested that I use trickets immediately with the pool. I checked and looked that my DPS would be very low if I gave them by CD immediately from the pool, as I indicated below a footnote when they need to be used. Because if I use them as indicated in the footnote, the DPS grows by 1.2%, which already looks better. I hope you will be able to test what I described about the trickets.

When should I use the Grongs trinket?
Pretty much off Cooldown. Use it in the opener after you've popped Unholy Frenzy (wounds will still be applied).

How do I use the RAGE trinket (Mekkatorque) correctly?
Use it in opener and use Unholy Frenzy as you usually do. Then save Unholy Frenzy for your other uses, popping Unholy Frenzy 6 seconds after using the trinket.

**Comment by Melekus** [comment]
Trinket usage for Unholy DK was updated in various commits
