### ISSUE TITLE
Unable to fetch bearer token

### ISSUE THREAD

**Issue by Manikoul** [simulationcraft/simc#4732]
Hello,

I have this issue after following instructions from wiki :

### Describe the bug
ubuntu@ip-172-31-37-47:~/simc/engine$ ./simc armory=eu,hyjal,gandallf
SimulationCraft 810-02 for World of Warcraft 8.1.0 Live (wow build 29088, git build bfa-dev f874f1e209)

Unable to fetch bearer token from https://eu.battle.net/oauth/token, The requested URL returned error: 401 Unauthorized
Error: Option 'armory' with value 'eu,hyjal,gandallf': BCP API: Unable to download JSON from 'https://eu.api.blizzard.com/wow/character/hyjal/gandallf?fields=talents,items,professions&locale=en_GB'.

### To Reproduce
Ubuntu Server 18.04 LTS

Any idea ? :/

**Comment by Adam-Braincorp** [comment]
Ever find a solution to this?

**Comment by Homainc** [comment]
If you built CLI yourself, you should specify your own API token from Battle.net. Here is details:
https://github.com/simulationcraft/simc/wiki/BattleArmoryAPI
