### ISSUE TITLE
Damage done chart

### ISSUE THREAD

**Issue by Warbigold** [simulationcraft/simc#4748]
Hey, first i'm sorry if this isn't the right place to ask questions but i didn't find any other place to ask this.

I was wondering if there is a way to see a chart similar to the Damage Per Second one but for damage done instead? I'm asking because i'd like to see how much damage i can put out in 10, 20 , 30 sec et cetera, Thanks.(and sorry again if this isn't the right place)

**Comment by scamille** [comment]
No there really is not. If you want to see how much damage you do on a short fight, you would also need to simulate a short fight and you always have dps * time = damage done.

If you are talking about the DPS timeline, then you should be able to just integrate that over time. But beware, any value/chart you have here is average over many iterations of combat, so this doesn't mean that this is the actual amount of damage you will perform during a single sample of combat.
