### ISSUE TITLE
BM Hunter n x Rapid Reload at n Enemys

### ISSUE THREAD

**Issue by totalschaden** [simulationcraft/simc#4751]
shoudnt BM Hunter with n x https://www.wowhead.com/spell=278530/rapid-reload use multishot over other spells at n enemys at some point ?
On big pulls it seems much more effective to just spam Multishot. How manys Rapid Reload traits does it need at how many enemys to be better then Ability x ?

**Comment by Jayezi** [comment]
Right now at 4 or more targets with Rapid Reload it ignores Kill Command and Multishot takes priority over everything but cooldowns basically.
`actions.cleave+=/kill_command,if=active_enemies<4|!azerite.rapid_reload.enabled`
