### ISSUE TITLE
Ghost Iron Dragonling Trinket Proc

### ISSUE THREAD

**Issue by SwordSmith14** [simulationcraft/simc#4755]
I have been simming trinkets for burning crusade timewalking dps (lvl 70 scale, ilvl 83 scale) and the 
Ghost Iron Dragonling trinket proc never shows damage.

SimulationCraft Version 810-01

**Comment by scamille** [comment]
Sorry for not replying earlier.

The trinket is just not supported by SimulationCraft and will likely never be. Development is focused on max-level simulations and while low level simulations are not restricted there is no active effort to support them, in particular items with special procs like this one that do not just give a certain stat.

We of course always accept pull requests with your implementation.

Closing this for now.
