### ISSUE TITLE
sim impossible

### ISSUE THREAD

**Issue by minidam160779** [simulationcraft/simc#4780]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
SimulationCraft encountered an error!

Simulation runtime error:
Incorrect option format: Unexpected parameter 'SimulationCraft'. Expected format: name=value

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

**Comment by minidam160779** [comment]
SimulationCraft encountered an error!

Simulation runtime error:
Incorrect option format: Unexpected parameter 'SimulationCraft'. Expected format: name=value

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

**Comment by vituscze** [comment]
We need more information to be able to help. Can you show us the contents of the simc_gui.simc file?
