### ISSUE TITLE
Chargestone of the Thunder King's Court - Hunters

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4782]
On simulation the "Chargestone of the Thunder King's Court" trinket does not proc as often as it does in game. I discovered this as the simulation showed that a lesser 385 trinket was producing more DPS than the 395 [Chargestone of the Thunder King's Court] and I decided to investigate.

I did a run up at the dummy and at precisely 2 minutes, the time to recharge Aspect of the Wild, the trinket procced 8 times.

On the simulation the trinket procced 8 times but in a 5 minute simulation (300 seconds).

Simulation is 815-01.

Many thanks
Akis

**Comment by vituscze** [comment]
Spell data for the trinket states the effect has 1.5 RPPM, so the game data is probably wrong. We'll need a bigger sample size before we can adjust anything, though.

**Comment by akis-t** [comment]
Thanks for the quick reply. I will test again for more than 2 mins and will let you know.

**Comment by akis-t** [comment]
I just ran another real test at 12 minutes and it produced 19 procs, so it seems your data is correct at around 1.5 procs per min. Sorry for the confusion.
