### ISSUE TITLE
Variable Intensity Gigavolt Oscillating Reactor trinket being recommended to use on less than 6 stacks.

### ISSUE THREAD

**Issue by beanlord7** [simulationcraft/simc#4788]
### Describe the bug
Not sure if really a bug, just something that was missed and could be improved: the trinket "variable intensity gigavolt oscillating reactor" is being recommended regardless of the amount of stacks of the "V.I.G.O.R. engaged" aura. This happens on the latest monk priority list. I don't have any way to test on other classes.

### Expected behavior
It would be optimal to only recommend using the trinket, as well as other burst cds and pots only after the buff reaches 6 stacks.

### To Reproduce
Use the priority for monks, might be same for dh, feral, rogues, enha, and hunters.

### Additional information
v1.11.1 simC, latest monk list, with hekili v8.1.5-07

### Suggestion
Add conditions 
>(buff.vigor_engaged.stack = 6 & equipped.variable_intensity_gigavolt_oscillating_reactor = true) | equipped.variable_intensity_gigavolt_oscillating_reactor = false)

to the cd action lists. or something similar might work? It seems to work great for me after I edited the windwalker priority and also added the trinket to the top of "cd" list

**Comment by vituscze** [comment]
`simc` already uses the trinket only at max stacks unless you specify otherwise via the `bfa_opts.auto_oscillating_overload` option.
