### ISSUE TITLE
Unable to sim toon

### ISSUE THREAD

**Issue by Niteowl71** [simulationcraft/simc#4794]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Niteowl71** [comment]
Tried every version listed and when I go to sim all I get is Simulation runtime error:
Setup failure: Nothing to sim!

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Setup failure: Nothing to sim!

## All options used for simulation:
``` ini
### SimulationCraft 815-01 for World of Warcraft 8.1.5 Live (wow build 29683) ###
### Using QT 5.12.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=6
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.battle.net/wow/character/kiljaeden/Åzrael?fields=talents,items,professions&locale=en_US&apikey=[REDACTED]'.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
haven't used in a long time but it used to work!!!

**Comment by vituscze** [comment]
Blizzard is currently having some issues with Armory. There's not much we can do about it. In the meantime, you can use the simc addon.
