### ISSUE TITLE
Can't download SimCraft

### ISSUE THREAD

**Issue by gregor5582** [simulationcraft/simc#4795]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by gregor5582** [comment]
When I klick on any downloadlink i get following message: Not Found
The requested URL /SimcSetup-815-01-Win32.exe was not found on this server.

Any ideas? Are there other Servers to download it?

Greets

**Comment by GabrielleDirk** [comment]
ive got the same problem. i can't download the 64 bit one

Not Found
The requested URL /simc-815-01-win64.7z was not found on this server.

Apache Server at downloads.simulationcraft.org Port 443

**Comment by navv1234** [comment]
Should work now.
