### ISSUE TITLE
Leaking of Spell Data Overrides in ProfileSets

### ISSUE THREAD

**Issue by Dorovon** [simulationcraft/simc#4799]
### Describe the bug
When overriding spell data with profile sets, the overrides from one profile set can leak into another. This conflicts with the stated behavior in the documentation.

### Expected behavior
The [documentation in the wiki](https://github.com/simulationcraft/simc/wiki/ProfileSet) states:
> Profile sets support the vast majority of simulation and player scope options. You can control the number of threads, override spell data, define different `raid_events`, or use `target_error` or `iterations` in an individual profile set without it leaking to other profile sets.

Based on this, the expected behavior is that overrides to spell data should be local to the profile set they are a part of.

### To Reproduce
Run the following example with the base T23_Mage_Frost profile, which overrides the travel speed of Flurry using profile sets:
```
mage="T23_Mage_Frost"
spec=frost
level=120
race=dwarf
role=spell
position=ranged_back
talents=1013033

head=grasping_crown_of_the_deep,id=159252,bonus_id=1587/4819/4775,azerite_powers=170/479/30/13
neck=heart_of_azeroth,id=158075,bonus_id=4929/5814/4936/1566,azerite_level=48
shoulders=brood_cleansers_amice,id=159254,bonus_id=1587/4819/4775,azerite_powers=170/196/31/13
back=loa_exultants_shroud,id=165512,bonus_id=4800/1537
chest=vestments_of_the_afterlife,id=165498,bonus_id=4824/1537/4775,azerite_powers=379/170/30/13
wrists=lever_stabilizing_wristwraps,id=165508,bonus_id=4800/1537
hands=firecallers_handwraps,id=165764,bonus_id=4800/1537
waist=waistcord_of_flowing_silk,id=165504,bonus_id=4800/1537
legs=wavecaller_leggings,id=165506,bonus_id=4800/1537
feet=lightfeather_footpads,id=165502,bonus_id=4800/1537
finger1=band_of_multisided_strikes,id=165565,bonus_id=4800/1537,enchant=pact_of_versatility
finger2=seal_of_the_zandalari_empire,id=165567,bonus_id=4800/1537,enchant=pact_of_versatility
trinket1=crest_of_paku,id=165581,bonus_id=4800/1537
trinket2=incandescent_sliver,id=165571,bonus_id=4800/1537
main_hand=deathspeaker_spire,id=165597,bonus_id=4800/1537,enchant=torrent_of_elements

profileset.flurry_10="override.spell_data=spell.44614.prj_speed=10"
profileset.flurry_30="override.spell_data=spell.44614.prj_speed=30"
profileset.flurry_50="override.spell_data=spell.44614.prj_speed=50"
```
The values produced by all three profilesets are approximately the same (this result corresponds to a prj_speed value of 10):
```
Profilesets (median Damage per Second):
     22317.162 : flurry_30
     22307.264 : flurry_10
     22281.030 : flurry_50
```

### Additional information
* SimulationCraft 815-02 for World of Warcraft 8.1.5 Live (wow build 29683, git build bfa-dev a5ba417)
* The overrides do not leak into the base profile, which appears to be simulated before they are applied.

**Comment by navv1234** [comment]
Yeah, it's a known issue currently. Spell overrides were designed to be global, and implemented before profilesets. As far as I can remember, overriding the same value in a profileset will replace the previous override, however since profilesets are simulated in non-deterministic order, you cannot really control what gets overwritten and when.

EDIT: Looks like I have forgotten to update the wiki about that.

**Comment by Dorovon** [comment]
I see that the following was added to the wiki.
> Note that currently spell data overrides will leak from profileset to profileset. If you intend to use them, you must override the full set of values on each profileset to guarantee correct simulation environment.

Are you sure this is correct? In the example I provided above I was only overriding a single value and overrode it in each profileset. It appears that these overrides are applied before any of the profilesets are actually simulated.

**Comment by navv1234** [comment]
It's not correct, since I forgot how this stuff was implemented. I'll adjust the notice.
