### ISSUE TITLE
Fury Warrior Meat Cleaver buff does not exist

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4803]
FURY WARRIOR

This line in the script adds a lot of multi target DPS but I do not understand it, as there is no such buff as "Meat Cleaver". In addition I do not even have the relevant talent, "Meat Cleaver". 

actions+=/whirlwind,if=!buff.meat_cleaver.up

From the little debugging I have done, it would appears that this line is not executed all the time, otherwise the script would simply stop there and not execute any following lines, as WW is available all the time.

Therefore this line is executed only some times, and adds 10K DPS multi target, but am not sure when.

Can you please help explain it?

### Additional information
* SimulationCraft Version (required) 
815-02

**Comment by vituscze** [comment]
Meat Cleaver used to be the name of the current Whirlwind buff up until 8.0. Warriors decided to stick with the old name in the warrior simc module.

**Comment by akis-t** [comment]
Thank you.
