### ISSUE TITLE
Fury Warrior cleave problem

### ISSUE THREAD

**Issue by guras3** [simulationcraft/simc#4804]
1) Siedgebreaker(level 100 talent) does not consume whirlwind charge and therefore does not deal damage to all enemies and does not apply debuff on all enemies.

also, whirlwind buff is called meat_cleaver in apl which is confusing, because meat_cleaver is now a talent and the buff is called simply "whirlwind".

https://www.wowhead.com/spell=280772/siegebreaker
https://www.wowhead.com/spell=85739/whirlwind

2) Something is definitely wrong with Gushing Wound. I assume it is applied only to current target, but in game when you use whirlwind + bloodthirst it is applied to every enemy to which bloodthirst crits. This results in more than 2 times difference between simulated and real Gushing Wound damage when fighting 4 training dummies. However the reason may be different, not sure about this.

https://www.wowhead.com/spell=85739/whirlwind
https://www.wowhead.com/spell=288091/gushing-wound

### Additional information
* SimulationCraft Version (required) - 815-02 May 14 2019

**Comment by vituscze** [comment]
Fixed the second issue in 52b60f1cbc77569e99249e587181c74567aa828c, I'll take a look at the first one.

**Comment by guras3** [comment]
this may help you

https://www.raidbots.com/simbot/report/tGeai7KHgWj5CbGnYH1HKx

![image](https://user-images.githubusercontent.com/15032877/57855207-c99fe100-77f2-11e9-96a8-6b366b310144.png)

**Comment by vituscze** [comment]
I'm checking it on my warrior right now. Just double checking the code and then I'll push a fix.

**Comment by vituscze** [comment]
Fixed in 9d348ac199c7534058be023270b96a4810785729.
