### ISSUE TITLE
Simulation runtime error - Item 'frayed_scoundrels_cap' Slot 'head': Error decoding gems from 'tireless_skyflare_6int_8haste': Invalid stat 'tireless'

### ISSUE THREAD

**Issue by DOT2010-EU** [simulationcraft/simc#4805]
### Describe the bug
Simulation runtime error:
Initializing: Actor 'Eightý': Item 'frayed_scoundrels_cap' Slot 'head': Error decoding gems from 'tireless_skyflare_6int_8haste': Invalid stat 'tireless'.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)
815-01 WebEngine

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
------------------------------
druid="Eightý"
source=blizzard
origin="https://worldofwarcraft.com/en-gb/character/dun-morogh/Eightý"
thumbnail="https://render-eu.worldofwarcraft.com/character/dun-morogh/134/122936454-avatar.jpg"
spec=balance
level=80
race=kul_tiran
role=spell
position=back
professions=alchemy=70
talents=https://worldofwarcraft.com/en-gb/game/talent-calculator#druid/balance/talents=1233100

# Default consumables
potion=volcanic
flask=draconic_mind
food=seafood_magnifique_feast
augmentation=disabled

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
# Azerite variables
actions.precombat+=/variable,name=az_ss,value=azerite.streaking_stars.rank
actions.precombat+=/variable,name=az_ap,value=azerite.arcanic_pulsar.rank
# Starfall v Starsurge target cutoff
actions.precombat+=/variable,name=sf_targets,value=4
actions.precombat+=/variable,name=sf_targets,op=add,value=1,if=talent.twin_moons.enabled&(azerite.arcanic_pulsar.enabled|talent.starlord.enabled)
actions.precombat+=/variable,name=sf_targets,op=sub,value=1,if=!azerite.arcanic_pulsar.enabled&!talent.starlord.enabled&talent.stellar_drift.enabled
actions.precombat+=/moonkin_form
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/solar_wrath

# Executed every time the actor is available.
actions=potion,if=buff.ca_inc.remains>6&active_enemies=1
actions+=/potion,name=battle_potion_of_intellect,if=buff.ca_inc.remains>6
actions+=/blood_fury,if=buff.ca_inc.up
actions+=/berserking,if=buff.ca_inc.up
actions+=/arcane_torrent,if=buff.ca_inc.up
actions+=/lights_judgment,if=buff.ca_inc.up
actions+=/fireblood,if=buff.ca_inc.up
actions+=/ancestral_call,if=buff.ca_inc.up
# CDs
actions+=/use_item,name=balefire_branch,if=equipped.159630&cooldown.ca_inc.remains>30
actions+=/use_item,name=dread_gladiators_badge,if=equipped.161902&cooldown.ca_inc.remains>30
actions+=/use_item,name=azurethos_singed_plumage,if=equipped.161377&cooldown.ca_inc.remains>30
actions+=/use_item,name=tidestorm_codex,if=equipped.165576
actions+=/use_items,if=cooldown.ca_inc.remains>30
actions+=/warrior_of_elune
actions+=/innervate,if=azerite.lively_spirit.enabled&(cooldown.incarnation.remains<2|cooldown.celestial_alignment.remains<12)
actions+=/incarnation,if=dot.sunfire.remains>8&dot.moonfire.remains>12&(dot.stellar_flare.remains>6|!talent.stellar_flare.enabled)
actions+=/celestial_alignment,if=astral_power>=40&ap_check&(!azerite.lively_spirit.enabled|buff.lively_spirit.up)&(dot.sunfire.remains>2&dot.moonfire.ticking&(dot.stellar_flare.ticking|!talent.stellar_flare.enabled))
actions+=/fury_of_elune,if=(buff.ca_inc.up|cooldown.ca_inc.remains>30)&solar_wrath.ap_check
actions+=/force_of_nature,if=(buff.ca_inc.up|cooldown.ca_inc.remains>30)&ap_check
# Spenders
actions+=/cancel_buff,name=starlord,if=buff.starlord.remains<8&!solar_wrath.ap_check
actions+=/starfall,if=(buff.starlord.stack<3|buff.starlord.remains>=8)&spell_targets>=variable.sf_targets&(target.time_to_die+1)*spell_targets>cost%2.5
actions+=/starsurge,if=(talent.starlord.enabled&(buff.starlord.stack<3|buff.starlord.remains>=8&buff.arcanic_pulsar.stack<8)|!talent.starlord.enabled&(buff.arcanic_pulsar.stack<8|buff.ca_inc.up))&spell_targets.starfall<variable.sf_targets&buff.lunar_empowerment.stack+buff.solar_empowerment.stack<4&buff.solar_empowerment.stack<3&buff.lunar_empowerment.stack<3&(!variable.az_ss|!buff.ca_inc.up|!prev.starsurge)|target.time_to_die<=execute_time*astral_power%40|!solar_wrath.ap_check
actions+=/sunfire,if=buff.ca_inc.up&buff.ca_inc.remains<gcd.max&variable.az_ss&dot.moonfire.remains>remains
actions+=/moonfire,if=buff.ca_inc.up&buff.ca_inc.remains<gcd.max&variable.az_ss
# DoTs
actions+=/sunfire,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))*spell_targets>=ceil(floor(2%spell_targets)*1.5)+2*spell_targets&(spell_targets>1+talent.twin_moons.enabled|dot.moonfire.ticking)&(!variable.az_ss|!buff.ca_inc.up|!prev.sunfire)&(buff.ca_inc.remains>remains|!buff.ca_inc.up)
actions+=/moonfire,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))*spell_targets>=6&(!variable.az_ss|!buff.ca_inc.up|!prev.moonfire)&(buff.ca_inc.remains>remains|!buff.ca_inc.up)
actions+=/stellar_flare,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))>=5&(!variable.az_ss|!buff.ca_inc.up|!prev.stellar_flare)
# Generators
actions+=/new_moon,if=ap_check
actions+=/half_moon,if=ap_check
actions+=/full_moon,if=ap_check
actions+=/lunar_strike,if=buff.solar_empowerment.stack<3&(ap_check|buff.lunar_empowerment.stack=3)&((buff.warrior_of_elune.up|buff.lunar_empowerment.up|spell_targets>=2&!buff.solar_empowerment.up)&(!variable.az_ss|!buff.ca_inc.up)|variable.az_ss&buff.ca_inc.up&prev.solar_wrath)
actions+=/solar_wrath,if=variable.az_ss<3|!buff.ca_inc.up|!prev.solar_wrath
# Fallthru for movement
actions+=/sunfire

head=frayed_scoundrels_cap,id=50206,bonus_id=4752,ilevel=113,gems=tireless_skyflare_6int_8haste
neck=blood_queens_crimson_choker,id=50724,gems=6int_2sp,enchant=16mastery
shoulders=cultists_bloodsoaked_spaulders,id=50646,gems=6int_6int_2agi
back=drape_of_the_violet_tower,id=50468,gems=6int_2sp,enchant=gift_of_mastery
chest=shadow_seekers_tunic,id=50972,gems=6int_6int_6int_3agi,enchant=glorious_stats
shirt=stylish_blue_shirt,id=6384
wrists=giants_toewrap,id=44696,bonus_id=1706/3771,ilevel=105,enchant=10haste
hands=cat_burglars_grips,id=50982,gems=6int_6int_2agi,enchant=14mastery
waist=vengeful_noose,id=50995,gems=6int_6int_6int_2agi
legs=sanctified_lasherweave_legguards,id=51297,gems=6int_6int_2agi,enchant=7int_5vers
feet=boots_of_unnatural_growth,id=50665,gems=6int_6int_2sp,enchant=8haste
finger1=the_prospectors_prize,id=37651,bonus_id=4123,ilevel=84,enchant=5mastery
finger2=ashen_band_of_greater_destruction,id=50384,enchant=4mastery
trinket1=purified_lunar_dust,id=50358
trinket2=mercurial_alchemist_stone,id=44322
main_hand=frozen_bonespike,id=50608,gems=6int_2sp,enchant=power_torrent
off_hand=musty_tome_of_the_lost,id=122390,bonus_id=5805,enchant=17int

# Gear Summary
# gear_ilvl=100.94
# gear_strength=9
# gear_agility=20
# gear_stamina=304
# gear_intellect=474
# gear_spirit=9
# gear_spell_power=8
# gear_crit_rating=124
# gear_haste_rating=146
# gear_mastery_rating=43
# gear_versatility_rating=38
# gear_armor=162
# meta_gem=tireless_skyflare

-------------------------------

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Eightý': Item 'frayed_scoundrels_cap' Slot 'head': Error decoding gems from 'tireless_skyflare_6int_8haste': Invalid stat 'tireless'.

## All options used for simulation:
``` ini
### SimulationCraft 815-01 for World of Warcraft 8.1.5 Live (wow build 29683) ###
### Using QT 5.12.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Eightý"
source=blizzard
origin="https://worldofwarcraft.com/en-gb/character/dun-morogh/Eightý"
thumbnail="https://render-eu.worldofwarcraft.com/character/dun-morogh/134/122936454-avatar.jpg"
spec=balance
level=80
race=kul_tiran
role=spell
position=back
professions=alchemy=70
talents=https://worldofwarcraft.com/en-gb/game/talent-calculator#druid/balance/talents=1233100

# Default consumables
potion=volcanic
flask=draconic_mind
food=seafood_magnifique_feast
augmentation=disabled

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
# Azerite variables
actions.precombat+=/variable,name=az_ss,value=azerite.streaking_stars.rank
actions.precombat+=/variable,name=az_ap,value=azerite.arcanic_pulsar.rank
# Starfall v Starsurge target cutoff
actions.precombat+=/variable,name=sf_targets,value=4
actions.precombat+=/variable,name=sf_targets,op=add,value=1,if=talent.twin_moons.enabled&(azerite.arcanic_pulsar.enabled|talent.starlord.enabled)
actions.precombat+=/variable,name=sf_targets,op=sub,value=1,if=!azerite.arcanic_pulsar.enabled&!talent.starlord.enabled&talent.stellar_drift.enabled
actions.precombat+=/moonkin_form
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/solar_wrath

# Executed every time the actor is available.
actions=potion,if=buff.ca_inc.remains>6&active_enemies=1
actions+=/potion,name=battle_potion_of_intellect,if=buff.ca_inc.remains>6
actions+=/blood_fury,if=buff.ca_inc.up
actions+=/berserking,if=buff.ca_inc.up
actions+=/arcane_torrent,if=buff.ca_inc.up
actions+=/lights_judgment,if=buff.ca_inc.up
actions+=/fireblood,if=buff.ca_inc.up
actions+=/ancestral_call,if=buff.ca_inc.up
# CDs
actions+=/use_item,name=balefire_branch,if=equipped.159630&cooldown.ca_inc.remains>30
actions+=/use_item,name=dread_gladiators_badge,if=equipped.161902&cooldown.ca_inc.remains>30
actions+=/use_item,name=azurethos_singed_plumage,if=equipped.161377&cooldown.ca_inc.remains>30
actions+=/use_item,name=tidestorm_codex,if=equipped.165576
actions+=/use_items,if=cooldown.ca_inc.remains>30
actions+=/warrior_of_elune
actions+=/innervate,if=azerite.lively_spirit.enabled&(cooldown.incarnation.remains<2|cooldown.celestial_alignment.remains<12)
actions+=/incarnation,if=dot.sunfire.remains>8&dot.moonfire.remains>12&(dot.stellar_flare.remains>6|!talent.stellar_flare.enabled)
actions+=/celestial_alignment,if=astral_power>=40&ap_check&(!azerite.lively_spirit.enabled|buff.lively_spirit.up)&(dot.sunfire.remains>2&dot.moonfire.ticking&(dot.stellar_flare.ticking|!talent.stellar_flare.enabled))
actions+=/fury_of_elune,if=(buff.ca_inc.up|cooldown.ca_inc.remains>30)&solar_wrath.ap_check
actions+=/force_of_nature,if=(buff.ca_inc.up|cooldown.ca_inc.remains>30)&ap_check
# Spenders
actions+=/cancel_buff,name=starlord,if=buff.starlord.remains<8&!solar_wrath.ap_check
actions+=/starfall,if=(buff.starlord.stack<3|buff.starlord.remains>=8)&spell_targets>=variable.sf_targets&(target.time_to_die+1)*spell_targets>cost%2.5
actions+=/starsurge,if=(talent.starlord.enabled&(buff.starlord.stack<3|buff.starlord.remains>=8&buff.arcanic_pulsar.stack<8)|!talent.starlord.enabled&(buff.arcanic_pulsar.stack<8|buff.ca_inc.up))&spell_targets.starfall<variable.sf_targets&buff.lunar_empowerment.stack+buff.solar_empowerment.stack<4&buff.solar_empowerment.stack<3&buff.lunar_empowerment.stack<3&(!variable.az_ss|!buff.ca_inc.up|!prev.starsurge)|target.time_to_die<=execute_time*astral_power%40|!solar_wrath.ap_check
actions+=/sunfire,if=buff.ca_inc.up&buff.ca_inc.remains<gcd.max&variable.az_ss&dot.moonfire.remains>remains
actions+=/moonfire,if=buff.ca_inc.up&buff.ca_inc.remains<gcd.max&variable.az_ss
# DoTs
actions+=/sunfire,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))*spell_targets>=ceil(floor(2%spell_targets)*1.5)+2*spell_targets&(spell_targets>1+talent.twin_moons.enabled|dot.moonfire.ticking)&(!variable.az_ss|!buff.ca_inc.up|!prev.sunfire)&(buff.ca_inc.remains>remains|!buff.ca_inc.up)
actions+=/moonfire,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))*spell_targets>=6&(!variable.az_ss|!buff.ca_inc.up|!prev.moonfire)&(buff.ca_inc.remains>remains|!buff.ca_inc.up)
actions+=/stellar_flare,target_if=refreshable,if=ap_check&floor(target.time_to_die%(2*spell_haste))>=5&(!variable.az_ss|!buff.ca_inc.up|!prev.stellar_flare)
# Generators
actions+=/new_moon,if=ap_check
actions+=/half_moon,if=ap_check
actions+=/full_moon,if=ap_check
actions+=/lunar_strike,if=buff.solar_empowerment.stack<3&(ap_check|buff.lunar_empowerment.stack=3)&((buff.warrior_of_elune.up|buff.lunar_empowerment.up|spell_targets>=2&!buff.solar_empowerment.up)&(!variable.az_ss|!buff.ca_inc.up)|variable.az_ss&buff.ca_inc.up&prev.solar_wrath)
actions+=/solar_wrath,if=variable.az_ss<3|!buff.ca_inc.up|!prev.solar_wrath
# Fallthru for movement
actions+=/sunfire

head=frayed_scoundrels_cap,id=50206,bonus_id=4752,ilevel=113,gems=tireless_skyflare_6int_8haste
neck=blood_queens_crimson_choker,id=50724,gems=6int_2sp,enchant=16mastery
shoulders=cultists_bloodsoaked_spaulders,id=50646,gems=6int_6int_2agi
back=drape_of_the_violet_tower,id=50468,gems=6int_2sp,enchant=gift_of_mastery
chest=shadow_seekers_tunic,id=50972,gems=6int_6int_6int_3agi,enchant=glorious_stats
shirt=stylish_blue_shirt,id=6384
wrists=giants_toewrap,id=44696,bonus_id=1706/3771,ilevel=105,enchant=10haste
hands=cat_burglars_grips,id=50982,gems=6int_6int_2agi,enchant=14mastery
waist=vengeful_noose,id=50995,gems=6int_6int_6int_2agi
legs=sanctified_lasherweave_legguards,id=51297,gems=6int_6int_2agi,enchant=7int_5vers
feet=boots_of_unnatural_growth,id=50665,gems=6int_6int_2sp,enchant=8haste
finger1=the_prospectors_prize,id=37651,bonus_id=4123,ilevel=84,enchant=5mastery
finger2=ashen_band_of_greater_destruction,id=50384,enchant=4mastery
trinket1=purified_lunar_dust,id=50358
trinket2=mercurial_alchemist_stone,id=44322
main_hand=frozen_bonespike,id=50608,gems=6int_2sp,enchant=power_torrent
off_hand=musty_tome_of_the_lost,id=122390,bonus_id=5805,enchant=17int

# Gear Summary
# gear_ilvl=100.94
# gear_strength=9
# gear_agility=20
# gear_stamina=304
# gear_intellect=474
# gear_spirit=9
# gear_spell_power=8
# gear_crit_rating=124
# gear_haste_rating=146
# gear_mastery_rating=43
# gear_versatility_rating=38
# gear_armor=162
# meta_gem=tireless_skyflare

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
----------------

**Comment by vituscze** [comment]
Low level characters are generally not supported

**Comment by scamille** [comment]
The error message basically says that your gem tireless_skyflare could not be decoded, since it is not implemented in SimC.

Even if you remove it and eventually get to simulate your character, as vituscze said, SimulationCraft does not really support low level characters, so the results you get will usually not help you much.
