### ISSUE TITLE
[Essence] Guardian of Azeroth pet being buffed by Beast Mastery mastery stat

### ISSUE THREAD

**Issue by bendakwow** [simulationcraft/simc#4819]
### Describe the bug
The damage from the Guardian of Azeroth pet from the Condensed Life Force essence appears to be buffed by Beast Mastery's Mastery stat in simc. Normally the stat should increase all pet damage, but Blizzard has added an exception in-game so that the essence isn't too strong for one spec.

### Expected behavior
Direct damage from the Guardian of Azeroth pet should not be buffed by Mastery stat for BM hunters.

### To Reproduce
Start with any Beast Mastery sim with the Condensed Life Force essence, then add more Mastery stat. Notice how the damage of the Guardian of Azeroth's "Azerite Spike" and "Azerite Volley" attacks is being increased with extra mastery.

### Additional information
SimulationCraft 815-02
for World of Warcraft 8.2.0 PTR (wow build level 30329, git build bd7e7fca14)

**Comment by Jayezi** [comment]
Looks to be so. Lovely how Animal Companion still nerfs it in game though...

**Comment by Jayezi** [comment]
Should be accurate now in builds going out today.
