### ISSUE TITLE
Simc Crash in sc_dot:83

### ISSUE THREAD

**Issue by Mrnikbobjeff** [simulationcraft/simc#4823]
### Describe the bug
Simc crashes becuase end_event is null in sc_dot.cpp

### Expected behavior
No crash,

### To Reproduce
https://pastebin.com/xhLVc9Rd sim this
### Additional information
* SimulationCraft Version (required)
bfa dev, head b90d19d4c32da4a9c610d4a25b169ccf96cf8019

**Comment by Mrnikbobjeff** [comment]
Happens when simming vision of perfection rank 1 in major slot

**Comment by Mrnikbobjeff** [comment]
Introduced in 6694745e2db43e7f1b59a0ce2c5fad8e36a7e263

**Comment by vituscze** [comment]
I believe this one was fixed at some point. Closing.
