### ISSUE TITLE
Create PGO profile and build

### ISSUE THREAD

**Issue by Mrnikbobjeff** [simulationcraft/simc#4824]
Profile guided optimization as well as applying some additional flags gives measurable performance benefits on windows and on linux. For people to be able to simply generate profiles for their individual use cases we should add build options for profiled builds which can then be used to increase simc performance.

**Comment by scamille** [comment]
which build system are you concerned?
For the makefile in /engine, there are already various options you can use. A quick glance gives
LLVM_PGO_GENERATE
LLVM_PGO_USE
as well as LTO and LTO_THIN

I guess we could add something about this to the wiki, or you could add some scripts to util_scripts to automate this. But I would not integrated this into the default builds for everyone.

Not sure how good pgo can be enable in the cmake file. I once tried to add LTO but it requires a much higher minimum version, and was just complicated to do, so I eventually gave up.

Anyway, I see either the wiki or some scripts automating this for linux builds as the way to go, contributions are certainly welcome :-)

**Comment by scamille** [comment]
Closing this. If anybody has a sensible pull request, we'll gladly merge that.
