### ISSUE TITLE
Item 'wardenguards_battlegloves' Slot 'hands': Error decoding gems from '': No gem data for id 168639

### ISSUE THREAD

**Issue by Etigo86** [simulationcraft/simc#4835]
[log.txt](https://github.com/simulationcraft/simc/files/3349634/log.txt)

**Comment by gastank** [comment]
Version 815 of simc does not support the new 8.2 gems. You can download the latest nightly build of simc820 here: http://downloads.simulationcraft.org/?C=M;O=D

**Comment by Etigo86** [comment]
Thank you for the help. Now it works again.
