### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Nexso1983** [simulationcraft/simc#4854]
Simulation runtime error:
Initializing: Actor 'Bokar': Item 'inactive' Slot 'trinket1': Cannot parse option from ',id=167555,gem_id=167556/168744/167693,gem_bonus_id=0/1461:5857:6319,bonus_id=1482,context=11': Unexpected parameter 'gem_bonus_id'.

**Comment by AlexanderKenny** [comment]
Please update to a recent version of Simcraft. Either the nightly or build from source and the issue will be resolved.
