### ISSUE TITLE
Trinket error

### ISSUE THREAD

**Issue by lacticsnergy** [simulationcraft/simc#4857]
### Describe the bug
Was simming my character

### To Reproduce
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Lacticsnergy': Item 'inactive' Slot 'trinket1': Cannot parse option from ',id=167555,gem_id=167556/168743,gem_bonus_id=0/1461:4786,bonus_id=1476,context=11': Unexpected parameter 'gem_bonus_id'.

### Additional information
* SimulationCraft Version (required)
Using 815-01

**Comment by gastank** [comment]
simc-815 does not support new additions from patch 8.2. You can download the latest simc-820 nightly build from http://downloads.simulationcraft.org/?C=M;O=D
