### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by ffabr** [simulationcraft/simc#4858]
### Describe the bug
Downloaded the nightly build, unzipped it, lauched simulationcraft.exe and noticed that disk's free space got claimed. Is there any way i can track where simulation craft stores data ? becouse it saves simulations even if i delete the unzipped folder and then download the new one

### Expected behavior
I expected that nothing will change with the free space

### Additional information

simc-820-01-win64-nonetwork-8c3924750b

**Comment by navv1234** [comment]
On windows, everything should be saved into the directory you unpack it in. In general, Simulationcraft GUI does not use much disk space. The only things it saves are the various results you have (textual and html), armory api cache things (if armory api is used, in the package you unpacked it is not), and the option file.

None of this should take much disk space outside of what the unpacked version of the program takes itself.

**Comment by ffabr** [comment]
Can i view the directory where it stores the cache? 16:41, 12 July 2019, PRAISE EARTHQUAKE TOTEM <notifications@github.com>:On windows, everything should be saved into the directory you unpack it in. In general, Simulationcraft GUI does not use much disk space. The only things it saves are the various results you have (textual and html), armory api cache things (if armory api is used, in the package you unpacked it is not), and the option file.
None of this should take much disk space outside of what the unpacked version of the program takes itself.

**Comment by navv1234** [comment]
On windows it should store the cache in the same directory as simulationcraft.exe, the cache file name is "simc_cache.dat".

**Comment by ffabr** [comment]
No the thing is when i delete the folder and download new version, it still saves all settings and old sims17:14, 12 July 2019, PRAISE EARTHQUAKE TOTEM <notifications@github.com>:On windows it should store the cache in the same directory as simulationcraft.exe, the cache file name is "simc_cache.dat".

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by navv1234** [comment]
Settings may be located in `c:\users\<yourusername>\AppData\Roaming\Simulationcraft\Simulationcraft` or something like that.

**Comment by ffabr** [comment]
Thank you for help.17:21, 12 July 2019, PRAISE EARTHQUAKE TOTEM <notifications@github.com>:Settings may be located in c:\users\<yourusername>\AppData\Roaming\Simulationcraft\Simulationcraft or something like that.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
