### ISSUE TITLE
Issue with Gem import

### ISSUE THREAD

**Issue by FrostyMage** [simulationcraft/simc#4866]
Hi There..

I get the following error when trying to import via the armory...

# Actor 'Zaphim': Item 'pocketsized_computation_device' Slot 'trinket1': Error decoding gems from '': No gem data for id 167556.

Is there a workaround please?

**Comment by AlexanderKenny** [comment]
You're using an 8.1.5 version of Simcraft which does not support items added in 8.2. Update to a recent nightly build.
