### ISSUE TITLE
Demonology - From the Shadows request

### ISSUE THREAD

**Issue by Nazeth** [simulationcraft/simc#4871]
**From the Shadows** is one of the Demonology talents, who allow us to deal extra 20% Shadowlame damage to the first Dreadstalkers target per 12 sec every 20 sec. Many of popular pages use your rotations to calculate potential dps, but actual rotation maybe isn't compatible with that talent and that can make it weaker than others?

After analyze your rotation on github i thought. 
"What happen, if during longer fights i should be able to safe as much Demonbolts, Implosions, Tyrant and Hand of Guldans for that 12 sec window every 20 sec?"

**Main assumptions to check:**
- prepare soul shards before Call Dreadstalkers to use as many Hand of Guldans as possible during From the Shadows
- use as many Demonbolts as possible during From the Shadows
- calculate that better is to use Demonbolts during From the Shadows to increase number of caster Hand of Guldans or safe them to the Shadow Bite phase?
- safe Imps for Implosion to the From the Shadows phase during AoE, if targets don't die too fast
- summon Demonic Tyrant during From the Shadows to increase Demonfire damage to main target

I tried many times upgrade official rotation and test it with rotation addons on patchworks, but i have problem with optimize it to many different situations, traits and talents.

**Comment by scamille** [comment]
Cc @simulationcraft/warlock 
I will close this for now. Thanks for your suggestions in how to improve the APL. That said, resources are always limited and developers few, so the best thing are specific changes which are proven to be dps increases.
Maybe you can get more directly involved in warlock APL discussions / development for shadowlands, optimizing it for covenants. We also always accept pull requests.
