### ISSUE TITLE
Character import error due to missing gem code for abyssal alchemist stone

### ISSUE THREAD

**Issue by BlackKnight1984** [simulationcraft/simc#4881]
Hi Simcraft team, 

Simming was no longer working on the old 810-01 version I had, so I downloaded the latest 815-01 version. When reimporting my character, an error occurred. Simcraft could not decode the gem data for the abyssal alchemist stone slot. Can you please advise on how I can resolve this? 

Regards, BK84

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Actor 'Virabhadrasa': Item 'abyssal_alchemist_stone' Slot 'trinket2': Error decoding gems from '': No gem data for id 168642.

**Comment by AlexanderKenny** [comment]
You downloaded an 8.1.5 version which does not support 8.2 items. Update to a recent nightly.

**Comment by BlackKnight1984** [comment]
Thank you!
