### ISSUE TITLE
Cyclotronic Blast via Use Items appears to be instant-cast and off GCD.

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#4895]
### Describe the bug
If Pocket-Sized Computation Device / Cyclotronic Blast is used via the Use Items action, it is treated as instantaneous and off-GCD.

### Expected behavior
Cyclotronic Blast should have a cast and channel time.

### To Reproduce
Load the current Feral APL, which has no specific entry for PSCD/CB but does use Use Items (w/o conditions).  Run a sim and look at the Sample Sequence.  `use_items` and the next action (`brutal_slash`) occur simultaneously.

![image](https://user-images.githubusercontent.com/9438134/61586354-d9fc7100-ab3f-11e9-8be9-0928d3a1cb4b.png)

If you modify the Feral APL to use the trinket directly, it appears to have a cast time.  I changed `actions.cooldowns+=/use_items` to `actions.cooldowns+=/use_item,effect_name=cyclotronic_blast` and got the following result:

![image](https://user-images.githubusercontent.com/9438134/61586372-48413380-ab40-11e9-9320-c43c660b22c3.png)

`brutal_slash` now occurs at 0:08.083, 2.889s after PSCD/CB.

### Additional information
* SimulationCraft Version (required)

SimC Version - Nightly (820-02)
SimC Build Date - Jul 20 2019
SimC Git Hash - 59b47998e1
(run via raidbots)

**Comment by vituscze** [comment]
Can you provide a profile that exhibits this problem? I tried reproducing it and everything seems to work correctly.

**Comment by Hekili** [comment]
I've found the issue and it was with the profile I was testing.  It had 2 on-use trinkets; the first cast was using the regular instant off-GCD trinket.  Closing.
