### ISSUE TITLE
SimulationCraft.exe doesn't run

### ISSUE THREAD

**Issue by Blacknblue123** [simulationcraft/simc#4902]
SimulationCraft 8.2.0, release 1 (Released on 17 July 2019) doesn't run. Windows 7 64. Any suggestions?
[DxDiag.txt](https://github.com/simulationcraft/simc/files/3439236/DxDiag.txt)

**Comment by navv1234** [comment]
Install 7-Zip and try <http://downloads.simulationcraft.org/?C=M;O=D> the "-nonetwork" version, does that start?

**Comment by Blacknblue123** [comment]
Yes, it is working now. So I can only use "nonetwork" version or I can use "network" version somehow?

**Comment by navv1234** [comment]
There's a handful of people who cannot run the "network" version of simc due to the library we use to perform armory API lookups. If you don't need to import characters from armory, the nonetwork version will work fine.

**Comment by Blacknblue123** [comment]
Okay, got it. Thank you very much!
