### ISSUE TITLE
Demonology - Demonic Tyrant during AoE with Demonic Consumption

### ISSUE THREAD

**Issue by Nazeth** [simulationcraft/simc#4903]
### Describe the bug
Default AoE rotation suggest us to use Demonic Tyrant whenever is possible (_actions.implosion+=/summon_demonic_tyrant_), but with Demonic Consumption buffed Tyrant can dealt more damage in AoE skirmish, than use that imps on implosion.

### Expected behavior
modernize Demonic Tyrant script in "actions.implosion".

### To Reproduce
Just check default rotation. I used Hekili with updated rotation from _https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/Tier24/T24_Warlock_Demonology.simc_ to reproduce your rotation as close as possible.

### Additional information
Current version https://github.com/simulationcraft/simc/commit/954504cb15ed6181de4f67a6a4c2fda2262acbab

I used my warlock with EP build - 3x Baleful Invocation and Demonic Consumption

**Demonifire**
My average Normal Demonfire dealt ~36'000 damage with, 3x Baleful Invocation and 280% Tyrand buff from Demonic Consumption (6 imps consumed)
If my tyrant is able to do 11 Demonfires during 15 sec that's ~396'000 damage in total
If my average imp buffing Demon Tyrant by 30% and i'm using 6 of them, then it's ~42'000 damage per imp in 11 Demonfires. It's ~3'800 damage per Demonfire per imp.
**Implosion**
My average Normal Implosion dealt ~3800 damage to 1 target per imp

That's mean that 1 of my imps during implosion must hit ~11 targets to dealt the same amount of damage compared to 1 imp Demonic Consumption buff during 15 sec

**How to simple calculate when its worth for me:**
1. Choose the strongest target to aim your tyrant
_If 1 imp implosion damage to 1 target = Demonfire buff damage from 1 imp Demonic Consumption_
2. floor("Number of targets") <= ("target time to die" - "Summon Demonic Tyrant cast time") / "Demonfire cast time" 
and >= 6 imps are ready to sacrifice

**Comment by scamille** [comment]
@simulationcraft/warlock is this something still relevant in shadowlands?

**Comment by Azevara** [comment]
This is no longer relevant moving into shadowlands, closing this issue
