### ISSUE TITLE
Elemental shaman ascendance incorrect usage in APL

### ISSUE THREAD

**Issue by zorkesh** [simulationcraft/simc#4925]
### Problem
Ascendance talent cast incorrectly when using Vision of Perfection essence and Primal Elementalist with Storm Elemental talents.
In APL there is condition for Ascendance cooldown.storm_elemental<120
But with Vision of Perfection its cooldown already lower than 120 sec (112s). This cause Ascendance to be cast immediatly after spending all Lava Burst Stacks (at 5-6 seconds of storm elemental if cooldowns are crossed)
 Another problem that Vision of Perfection can extend Storm Elemental for more than 30sec

### Suggestion
Use Ascendance after losing Wind Gust buff, not just by calculated cooldown

**Comment by Bloodmallet** [comment]
Greetings,
the suggestion about using the actual WInd Gust buff is good. But it doesn't work if no Lightning Bolt was cast yet, So at the start of the fight or at random points on Elemental procs, the current issue would still persist. It's a good idea, regardless.

**Comment by Bloodmallet** [comment]
This issue should be solved with the now available APL.
