### ISSUE TITLE
simc import of json data from local file "local_json=filename,character" stopped working

### ISSUE THREAD

**Issue by yurko13** [simulationcraft/simc#4932]
### Describe the bug
feature to load json data from local file instead from battlenet stopped working
> local_json=filename,CharacterName

### Expected behavior
character data for simulation loaded from local file, it worked for release 8.1.

### To Reproduce
$ curl -s "https://us.api.blizzard.com/wow/character/${SERVER}/${CHAR}?fields=class,talents,items,professions&locale=en_US&access_token=${TOKEN}" >temp.temp
$ cat file.simc
local_json=temp.temp,Charname
save=char.simc
$ ./simc file.simc
SimulationCraft 820-02 for World of Warcraft 8.2.0 Live (wow build 31429)
Error: Option 'local_json' with value 'temp.temp,Charname': BCP API: Cannot parse option from 'Charname': Unexpected parameter 'Charname'. Expected format: name=value

### Additional information
* simc version 8.2, also current night builds, few last 8.1.5x
It worked before in 8.1 release.

**Comment by navv1234** [comment]
Simulationcraft swapped to the new Blizzard API end points recently, and as a result, the syntax of that command changed. the syntax now is `local_json=mainfile,spec=specfile,equipment=equipmentfile`. Additionally, there's a `media=mediafile` suboption available if you want to have character backgrounds in the HTML report.

The "XXfile" files in question, are the sub-documents for a character profile that you get, as per information found in https://us.battle.net/forums/en/bnet/topic/20772457051

**Comment by brendabosi** [comment]
Mine stopped working after the start of Classic in World of Warcraft. when i type in /simc it doesn't recognize it.....any suggestions??
![Screenshot_4](https://user-images.githubusercontent.com/54644558/63890126-50e32000-c9b0-11e9-806a-ef7a7180e27b.jpg)

**Comment by scamille** [comment]
I copy pasted your explanation into the wiki.
