### ISSUE TITLE
simc-820-01-Win64 does not open

### ISSUE THREAD

**Issue by h308676539** [simulationcraft/simc#4941]
simc-820-01-win64.7z
simc-820-01-win64.exe

does not open

Double-click program（exe），

The following programs disappear in the task manager

**Comment by h308676539** [comment]
I found the problem.

win10 1803 can open
win10 1903 can't open

**Comment by scamille** [comment]
Try out the last nightly release at http://downloads.simulationcraft.org/?C=M;O=D

Also make sure you updated your graphics driver.

Works fine for me with 1903...
