### ISSUE TITLE
Guardian Druid and Brewmaster Monk missing Razor Coral/Inkpod actions

### ISSUE THREAD

**Issue by hynelohr** [simulationcraft/simc#4953]
The default APL for Guardian Druids is missing some trinket interactions, most notably Razor Coral and Inkpod. Right now it just uses everything on cooldown through actions.cooldowns+="/use_items"

I'd like to request an update to the Guardian APL for the Razor Coral trinket:

actions.cooldowns+="/use_item,name=ashvanes_razor_coral,target_if=debuff.razor_coral_debuff.down|debuff.conductive_ink_debuff.up&target.time_to_pct_30<1.5|debuff.razor_coral_debuff.up&time_to_die<21"

As for Brewmasters, I'm unable to suggest an update since I'm not knowledgeable in the spec, but it is also missing the Razor Coral/Inkpod interaction.

**Comment by Melekus** [comment]
Brewmaster fixed in https://github.com/simulationcraft/simc/commit/6abc4acebc82f36ca37999c66f891a7492a30f0d

Guardian APL updated in https://github.com/simulationcraft/simc/commit/135a4b88e2118b9b07ac52fda91de9a97fb898aa

to ```use_item,name=ashvanes_razor_coral,if=debuff.razor_coral_debuff.down|debuff.conductive_ink_debuff.up&target.health.pct<31|target.time_to_die<20```
