### ISSUE TITLE
Ashvane's razor coral doesn't activate for windwalkers?

### ISSUE THREAD

**Issue by Zrilian** [simulationcraft/simc#4958]
### Describe the bug
Windwalker Default sim model doesn't seem to use the active of ashevane's razor coral

### Expected behavior
One would expect the damage sources to include razor coral, one would also expect it do perform reasonably well. Neither is true.

### To Reproduce
Start any sim for a windwalker that includes a razor coral, it will only contribute it's agility to your damage

https://www.raidbots.com/simbot/report/wxwFSbBVcstspiCXDzS8qG/simc

the trinket needs to activated on pull and at some frequency, no idea what that interval is but presumably in conjuction with your cooldowns, probably before touch of death.

### Additional information
* SimulationCraft Version (required)
SimulationCraft 820-02

**Comment by Melekus** [comment]
Fixed as of https://github.com/simulationcraft/simc/commit/4a0a6b808c6e081b00bdf7b2d358ae3eb227d382
