### ISSUE TITLE
Is '&' prior to '|'?

### ISSUE THREAD

**Issue by addf0214** [simulationcraft/simc#4966]
I assume it is, but the [document ](https://github.com/simulationcraft/simc/wiki/Conditional-expressions)didn't mention that

**Comment by Azevara** [comment]
> Finally, here is the full operators priorities list, from the highest ones to the lowest ones:
> 
> Function calls (floor , ceil)
> Unary operators (+ , - , @ , !)
> Multiplication and division (* , %)
> Addition and subtraction (+ , -)
> Comparison operators (= , != , < , <= , >= , > , ~, !~)
> Binary logical and (&)
> Binary logical xor (^)
> Binary logical or (|)
