### ISSUE TITLE
Dark iron dwarf

### ISSUE THREAD

**Issue by GuroTentacles** [simulationcraft/simc#4967]
Dark iron dwarf incorrectly shows fireblood. Indicates 200 when on should be 600 primary stat.
https://www.wowhead.com/spell=265221/fireblood

**Comment by vituscze** [comment]
Works fine, make sure you're checking the actual buff and not just wowhead tooltips.

![image](https://user-images.githubusercontent.com/4149104/66611756-d1a45700-ebbf-11e9-9854-c5865665cf33.png)
