### ISSUE TITLE
Lady Waycrest's Music Box - no Set bonus

### ISSUE THREAD

**Issue by mbabigian** [simulationcraft/simc#4969]
If I combine the Lady Waycrest's Music Box trinket with the Ring (Lord Waycrest's Signet), the set bonus appears to be ignored.  The count and dps from Cacaphonous Chord is unchanged.

Running: simc-820-02-win64-6fd18cf417.7z

FYI

**Comment by Jundarer** [comment]
The set bonus adds no dps as it only procs from active healing spells. From memory there is only feral with bloodtalons that use active healing spells in their rotation and it is irrelevant for all other specs.

**Comment by AlexanderKenny** [comment]
It's definitely implemented just not dps relevant as said (you should see harmonious procs more easily). Retested and it's still working so nothing broke either
