### ISSUE TITLE
Error downloading timewalking item

### ISSUE THREAD

**Issue by neifion** [simulationcraft/simc#4972]
### Describe the bug

The error message below shows up after trying to run the simu:

---
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: No active players in sim!

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.
---

And the player does exist. Here is the log:

---
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: No active players in sim!

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: No active players in sim!

## All options used for simulation:
``` ini
### SimulationCraft 820-01 for World of Warcraft 8.2.0 Live (wow build 30918) ###
### Using QT 5.12.4 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.12.3
# Requires SimulationCraft 820-01 or newer

deathknight="Corwynt"
level=120
race=night_elf
region=tw
server=hellscream
role=attack
professions=mining=43/jewelcrafting=26
talents=2232212
spec=frost

head=,id=166565,bonus_id=5126/1517/4786/5417,context=6,azerite_powers=198
neck=,id=158075,bonus_id=4936/4929/5814/1502,context=11,azerite_level=16
shoulder=,id=127539,bonus_id=5473,drop_level=120,context=22
back=,id=129832,bonus_id=6312,drop_level=120,context=22
chest=,id=167775,bonus_id=6296/6300/1472/4786/5413,azerite_powers=242
wrist=,id=150909,bonus_id=4803/1567/4785,context=27
hands=,id=127557,enchant_id=5933,bonus_id=5473,drop_level=120,context=22
waist=,id=170370,bonus_id=6288/6300
legs=,id=127433,bonus_id=6314,drop_level=120,context=22
feet=,id=167776,bonus_id=6288/6300
finger1=,id=129876,enchant_id=5939,bonus_id=5477,drop_level=120,context=22
finger2=,id=129875,enchant_id=5939,bonus_id=5477,drop_level=120,context=22
trinket1=,id=129937,bonus_id=6312,drop_level=120,context=22
trinket2=,id=129849,bonus_id=6312,drop_level=120,context=22
main_hand=,id=129861,bonus_id=6312,drop_level=120,context=22
off_hand=,id=129861,bonus_id=6312,drop_level=120,context=22

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
---
### Additional information
* SimulationCraft Version: 820-01

**Comment by Melekus** [comment]
I can't reproduce the error. Make sure you download the latest nightly at http://downloads.simulationcraft.org/?C=M;O=D and try again.

**Comment by scamille** [comment]
I added some better error messages in the GUI. CLI gives me the following:
@@@@@Player Corwynt has no weapon equipped at the Main-Hand slot.
Error: No active players in sim!

There seems to be a problem with downloading item data.

@navv1234  the item download of the timewalking items seems to fail silently. Can we add/improve the error message here, even if we cannot / don't want to support timewalking items?

**Comment by scamille** [comment]
Timewalking item download should be resolved, for more information on the original item download problem see #5278
