### ISSUE TITLE
[Retribution] Zeal sims wrong (maybe at any time active)

### ISSUE THREAD

**Issue by holytobi** [simulationcraft/simc#4973]
### Describe the bug
I tried around with the first talent row (Zeal, RV & ES) in combination with the second row Talent "Blade of Wrath". At the beginning i had a feeling, that i have more Art of War Procs with Zeal than with the other both talent (RV/ES). But Simcraftresults says that all tier 1 talents have no impact on how many cast of blade of justice i can do in one fight. So i create my own test to verify the simcraft result. 
To avoid the rng i make 100x 200sec fight against the boss puppet without any kind of buffs. (yeah i know much time invest xD)

Simcraft configuration: fight length 200sec, vary length 0% and the "optimal_raid=0" flag for no buffs.

Simcraft result: AVG 34.5 Cast of Blade of Justice no matter which tier 1 talent i choose

Ingame result: 
        - Zeal: AVG 34.5 cast of BoJ (min 31, max 40)
        - RV||ES: AVG 31 cast of BoJ (min 28, max 34)

There seams to be something wrong. With Zeal i have the exact AVG value of simcraft that's amazing
xD, but without i never reached 35 cast and simcraft says that's the avg? how can that be possible?

Maybe in the Simulation the "zeal" effect is every time active? 

I test several versions of simcraft on different pc's the result was every time the same!

**Comment by Melekus** [comment]
At the moment Art of War's rppm is only increased by haste in simc, and not by Attack speed modifiers like Zeal. I'll investigate more.

**Comment by Melekus** [comment]
Can you provide logs of Art of War having a higher proc rate with Zeal than with other talents?

**Comment by holytobi** [comment]
U mean raid loggs? or loggs of my ingame tests?

**Comment by holytobi** [comment]
I read "Art of war" is ppm not rppm maybe thats the problem?

**Comment by Melekus** [comment]
Logs from your ingame tests, or just a sufficiently long test against a dummy with the different setups. (for example 30min straight each should be enough to see a trend, 60 would make the results more reliable). 

PPM is an old system and most if not all rng mechanics nowadays use rppm instead. Do you have a source on that statement?

**Comment by holytobi** [comment]
i can made a log but where can i upload such data its noch a raid content. Can u show me a page where this kind of data can get analysed?

I know, that PPM is old but everyone speaks about it^^I have no offical source just forum post of WoW players:
for example: https://us.forums.blizzard.com/en/wow/t/bfa-art-of-war-questions/309752/5

**Comment by holytobi** [comment]
i create some loggs:
https://www.warcraftlogs.com/reports/YmMX3QPL4aTfcv1y/#fight=last&type=damage-done&source=1
https://www.warcraftlogs.com/reports/f2bgcrdyXmVCw6QZ#fight=1&type=damage-done&source=7

**Comment by Melekus** [comment]
Thanks for the logs! It indeed looks like Art of War's rppm is increased by attack speed modifiers. It used to be the case during BfA's beta but was changed before release. Looks like the "bug" is back on live servers or it was actually intended all along.

For the record, this has nothing to do with the proc being ppm or rppm.

Fixed in https://github.com/simulationcraft/simc/commit/d4048507d0eb875c953385ca675acaa63c7b556d
