### ISSUE TITLE
[Elemental] Improper cast of Flame Shock at fight start when using Essences

### ISSUE THREAD

**Issue by Lavindar** [simulationcraft/simc#4975]
### Describe the bug
Because of the way the essences are listed on the general action list, the simulation casts essences before casting Flame Shock after a pre-combat cast of Lava Burst, causing the Lava Burst to not benefit of the guaranteed critical from having the DoT up.

### Expected behavior
Flame Shock should be cast immediately after the pre-cast of the Lava Burst.

The problem is fixed if the following lines are removed from the general action list and put into their own "essences" sublist that would be called on the correct time into the ST/AOE/Funnel sublist

`actions+=/concentrated_flame
actions+=/blood_of_the_enemy
actions+=/guardian_of_azeroth
actions+=/focused_azerite_beam
actions+=/purifying_blast
actions+=/the_unbound_force
actions+=/memory_of_lucid_dreams
actions+=/ripple_in_space
actions+=/worldvein_resonance`

**Comment by Bloodmallet** [comment]
This issue should now be fixed. Thank you for reaching out.
