### ISSUE TITLE
Balance Druid possibly incorrect DPS shown

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4983]
Hello guys, 
I am simming my Balance Druid and the reported DPS is way above what I am pulling on the dummy, maybe as much as 30% more.
I have trimmed down the script to simply "actions+=/solar_wrath", removed all buffs foods heroism etc. The simulation shows 7958 DPS, 400 secs, 10000 iterations., 0% variance, TMI=T19N. I am getting about 6500-6600 DPS on the dummy simply spamming the one button, Solar Wrath. My lag is 15ms.
Many thanks

**Comment by Jundarer** [comment]
You would need to provide more details like the report/log and your in game damage numbers.

**Comment by Jundarer** [comment]
Closing if no reply for another week.

**Comment by AlexanderKenny** [comment]
Closing due to lack of reply. Can reopen if anything gets given.
