### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Mansos91** [simulationcraft/simc#4985]
Hello simulationcraft is not starting at all on my pc, there is no error or any message at all, added dxdiag
[DxDiag.txt](https://github.com/simulationcraft/simc/files/3939861/DxDiag.txt)

**Comment by scamille** [comment]
Sorry for not replying sooner.

Have you been able to resolve the problem in the meantime?

If not, can you please tell us which application you are trying to start? Simulationcraft.exe or something else?

What operating system do you have, and which version of SimulationCraft did you download?

**Comment by scamille** [comment]
Closing this since the original error description was already laking a lot of details to help with anything.

My assumption would be that simc.exe was being opened instead of Sinulationcraft.exe
