### ISSUE TITLE
Slice and Dice Criteria

### ISSUE THREAD

**Issue by illion20** [simulationcraft/simc#4987]
Would someone be so kind and to explain the logic behind having combo points + 1 multiplied with the value 1.8 as a criteria for Slice and Dice?

https://github.com/simulationcraft/simc/blob/24c788f908eb7a791fae026f05c7a6970a54639d/profiles/PreRaids/PR_Rogue_Outlaw.simc#L109

**Comment by scamille** [comment]
cc @simulationcraft/rogue

**Comment by EvanMichaels** [comment]
@fuu1 worked on this logic, he may be able to clarify

**Comment by Mystler** [comment]
That is simply a calculation for pandemic refresh threshold. 1.8 is 6 * 0.3.
