### ISSUE TITLE
The Unbound Force (major essence) implementation

### ISSUE THREAD

**Issue by flapjack831** [simulationcraft/simc#4989]
### Describe the bug
The Unbound Force's final (partial) tick does reduced damage in sim.

### Expected behavior
The Unbound Force's final (partial) tick does full damage in game.
(see: https://www.warcraftlogs.com/reports/3CvFRgTn42VPyhMz/#fight=last&type=damage-done&source=2&ability=298453&view=events&start=105780&end=117021 )

### To Reproduce
Sim any character with The Unbound Force in its major essence slot.

### Additional information
* SimulationCraft Version (required): Any

**Comment by Jundarer** [comment]
Fixed via aa217e8
