### ISSUE TITLE
Disc Priest - Death Throes azerite/cyclotronic blast not working

### ISSUE THREAD

**Issue by seriallos** [simulationcraft/simc#4990]
Cross-posting from Raidbots GitHub issues: https://github.com/seriallos/raidbots-issues/issues/151

### Describe the bug

The sim thinks disc can't use death throes because it's a shadow "specific" trait and isn't calculating SWP/purge the wicked properly. Also, the sim isn't using cyclo at all simming disc.

I understand it's not popular to sim healer dps, but it's quite relevant for disc m+.

**Comment by scamille** [comment]
Death Throes seems to be working, I can't find any restriction for disc priest. I also added the death throes damage nerf for disc in ffc31774d53e1b14cd83607b7aac784411453c69 , so it should hopefully even use the correct values now.

not sure what cyclo is.

**Comment by scamille** [comment]
Also @seriallos I added https://github.com/simulationcraft/simc/wiki/Options#allow-experimental-specialization and used it to guard most disabled specs behind it. This came after the discipline module was disabled, but some people wanted it back because most core stuff is somewhat working.
