### ISSUE TITLE
Simultation Bug

### ISSUE THREAD

**Issue by lgalvaoface** [simulationcraft/simc#4996]
SimulationCraft encountered an error!

Simulation runtime error:
Setup failure: Nothing to sim!

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Setup failure: Nothing to sim!

## All options used for simulation:
``` ini
### SimulationCraft 820-01 for World of Warcraft 8.2.0 Live (wow build 30918) ###
### Using QT 5.12.4 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/nemesis/hateyou?namespace=profile-us&locale=en_US'.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

DPS Ranking:
    584 100.0%  Raid
    584  100.0%  Arrascapeta

HPS Ranking:
      0 100.0%%  Raid

Player: Arrascapeta orc warlock demonology 75
  DPS=584.343 DPS-Error=0.292005/0.05% DPS-Range=44.1593/7.56%
  DPR=3.97571 RPS-Out=64.3052 RPS-In=63.8792 Resource=mana Waiting=0 ApM=42.0882
  Origin: https://worldofwarcraft.com/en-us/character/azralon/arrascapeta
  Talents: https://worldofwarcraft.com/en-us/game/talent-calculator#warlock/demonology/talents=3132300
  Core Stats:    strength=113|113(113)  agility=193|193(193)  stamina=488|444(444)  intellect=532|484(461)  spirit=0|0(0)  health=7320|6660  mana=8855|8855
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=7.16%|7.16%(88)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=532|484(0)  hit=15.00%|15.00%(0)  crit=17.01%|17.01%(125)  haste=11.80%|11.80%(116)  speed=11.80%|11.80%  manareg=89|89(0)
  Attack Stats:  power=0|0(0)  hit=7.50%|7.50%(0)  crit=17.01%|17.01%(125)  expertise=7.50%|7.50%(0)  haste=11.80%|11.80%(116)  speed=11.80%|11.80%
  Defense Stats: armor=77|77(77) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=3.58%|3.58%(88)
  Priorities (actions.precombat):
    flask/food/augmentation/summon_pet/inner_demons,if=talent.inner_demons.enabled/snapshot_stats/potion/demonbolt
  Priorities (actions.default):
    potion,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)&(!talent.nether_portal.enabled|cooldown.nether_portal.remains>160)|target.time_to_die<30
    use_item,name=azsharas_font_of_power,if=cooldown.summon_demonic_tyrant.remains<=20
    use_items,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15
    berserking,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15
    blood_fury,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15
    fireblood,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15
    blood_of_the_enemy,if=pet.demonic_tyrant.active&pet.demonic_tyrant.remains<=15-gcd*3&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)
    worldvein_resonance,if=buff.lifeblood.stack<3&(pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15)
    ripple_in_space,if=pet.demonic_tyrant.active&(!essence.vision_of_perfection.major|!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>=cooldown.summon_demonic_tyrant.duration-5)|target.time_to_die<=15
    call_action_list,name=dcon_opener,if=talent.demonic_consumption.enabled&time<30&!cooldown.summon_demonic_tyrant.remains
    use_item,name=azsharas_font_of_power,if=talent.grimoire_felguard.enabled&(target.time_to_die>120|target.time_to_die<cooldown.summon_demonic_tyrant.remains+15)|target.time_to_die<=35
    hand_of_guldan,if=azerite.explosive_potential.rank&time<5&soul_shard>2&buff.explosive_potential.down&buff.wild_imps.stack<3&!prev_gcd.1.hand_of_guldan&&!prev_gcd.2.hand_of_guldan
    demonbolt,if=soul_shard<=3&buff.demonic_core.up&buff.demonic_core.stack=4
    implosion,if=azerite.explosive_potential.rank&buff.wild_imps.stack>2&buff.explosive_potential.remains<action.shadow_bolt.execute_time&(!talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains>12)
    doom,if=!ticking&time_to_die>30&spell_targets.implosion<2
    bilescourge_bombers,if=azerite.explosive_potential.rank>0&time<10&spell_targets.implosion<2&buff.dreadstalkers.remains&talent.nether_portal.enabled
    demonic_strength,if=(buff.wild_imps.stack<6|buff.demonic_power.up)|spell_targets.implosion<2
    call_action_list,name=nether_portal,if=talent.nether_portal.enabled&spell_targets.implosion<=2
    call_action_list,name=implosion,if=spell_targets.implosion>1
    guardian_of_azeroth,if=cooldown.summon_demonic_tyrant.remains<=15|target.time_to_die<=30
    grimoire_felguard,if=(target.time_to_die>120|target.time_to_die<cooldown.summon_demonic_tyrant.remains+15|cooldown.summon_demonic_tyrant.remains<13)
    summon_vilefiend,if=cooldown.summon_demonic_tyrant.remains>40|cooldown.summon_demonic_tyrant.remains<12
    call_dreadstalkers,if=(cooldown.summon_demonic_tyrant.remains<9&buff.demonic_calling.remains)|(cooldown.summon_demonic_tyrant.remains<11&!buff.demonic_calling.remains)|cooldown.summon_demonic_tyrant.remains>14
    the_unbound_force,if=buff.reckless_force.react/bilescourge_bombers
    hand_of_guldan,if=(azerite.baleful_invocation.enabled|talent.demonic_consumption.enabled)&prev_gcd.1.hand_of_guldan&cooldown.summon_demonic_tyrant.remains<2
    power_siphon,if=buff.wild_imps.stack>=2&buff.demonic_core.stack<=2&buff.demonic_power.down&spell_targets.implosion<2
    doom,if=talent.doom.enabled&refreshable&time_to_die>(dot.doom.remains+30)
    hand_of_guldan,if=soul_shard>=5|(soul_shard>=3&cooldown.call_dreadstalkers.remains>4&(cooldown.summon_demonic_tyrant.remains>20|(cooldown.summon_demonic_tyrant.remains<gcd*2&talent.demonic_consumption.enabled|cooldown.summon_demonic_tyrant.remains<gcd*4&!talent.demonic_consumption.enabled))&(!talent.summon_vilefiend.enabled|cooldown.summon_vilefiend.remains>3))
    soul_strike,if=soul_shard<5&buff.demonic_core.stack<=2
    demonbolt,if=soul_shard<=3&buff.demonic_core.up&((cooldown.summon_demonic_tyrant.remains<6|cooldown.summon_demonic_tyrant.remains>22&!azerite.shadows_bite.enabled)|buff.demonic_core.stack>=3|buff.demonic_core.remains<5|time_to_die<25|buff.shadows_bite.remains)
    focused_azerite_beam,if=!pet.demonic_tyrant.active/purifying_blast/blood_of_the_enemy
    concentrated_flame,if=!dot.concentrated_flame_burn.remains&!action.concentrated_flame.in_flight&!pet.demonic_tyrant.active
    call_action_list,name=build_a_shard
  Priorities (actions.build_a_shard):
    memory_of_lucid_dreams,if=soul_shard<2
    soul_strike,if=!talent.demonic_consumption.enabled|time>15|prev_gcd.1.hand_of_guldan&!buff.bloodlust.remains/shadow_bolt
  Actions:
    bilescourge_bombers              Count=  10.0| 31.575sec  DPE=1941|11.02%  DPET=1513  DPR=   0  pDPS=64  MissTick= 0.00%  Tick=   140|   138|   172  CritTick=   280|   277|   344|16.95%
    call_dreadstalkers               Count=  14.7| 21.037sec  DPE=   0| 0.00%  DPET=   0  DPR=   0  pDPS= 0
    demonbolt                        Count=  41.6|  6.924sec  DPE= 530|12.56%  DPET= 407  DPR=   3  pDPS=73  Miss= 0.00%  Hit=   444|   439|   546  Crit=   888|   878|  1091|17.00%
    hand_of_guldan                   Count=  47.4|  6.266sec  DPE= 373|10.08%  DPET= 288  DPR=   0  pDPS=59  Miss= 0.00%  Hit=   319|   316|   393  Crit=   639|   632|   785|17.09%
    shadow_bolt                      Count=  66.6|  4.446sec  DPE= 267|10.11%  DPET= 156  DPR=   2  pDPS=59  Miss= 0.00%  Hit=   229|   227|   282  Crit=   458|   454|   565|17.07%
    soul_strike                      Count=  27.9| 10.850sec  DPE=   0| 0.00%  DPET=   0  DPR=   0  pDPS= 0
   felguard (DPS=161.502)
    felstorm                         Count=  10.3| 30.447sec  DPE= 612| 3.60%  DPET= 137  DPR=  10  pDPS=21  TickCount=    62  MissTick= 0.00%  Tick=    88|    87|   108  CritTick=   176|   174|   216|17.01%  UpTime= 14.55%
    legion_strike                    Count=  49.9|  5.973sec  DPE= 254| 7.21%  DPET= 253  DPR=   4  pDPS=42  Miss= 0.00%  Hit=   217|   215|   267  Crit=   434|   429|   534|16.90%
    melee                            Count= 147.9|  2.009sec  DPE= 114| 9.61%  DPET=  67  DPR=   0  pDPS=56  Miss= 0.00%  Hit=    98|    96|   120  Crit=   195|   193|   240|16.91%
    soul_strike                      Count=  27.9| 10.850sec  DPE= 453| 7.21%  DPET=   0  DPR=   0  pDPS=42  Miss= 0.00%  Hit=   387|   382|   475  Crit=   774|   765|   950|17.06%
   dreadstalker (DPS=144.948)
    dreadbite                        Count=  29.3| 21.026sec  DPE= 361| 6.04%  DPET=   0  DPR=   0  pDPS=61  Miss= 0.00%  Hit=   309|   306|   380  Crit=   618|   612|   760|16.88%
    melee                            Count= 210.5|  2.841sec  DPE=  69| 8.27%  DPET=  47  DPR=   0  pDPS=84  Miss= 0.00%  Hit=    59|    58|    72  Crit=   118|   116|   145|17.00%
   wild_imp (DPS=87.3056)
    fel_firebolt                     Count= 695.7|  0.420sec  DPE=  36|14.28%  DPET=  21  DPR=   2  pDPS=87  Miss= 0.00%  Hit=    31|    31|    38  Crit=    62|    61|    76|17.03%

  Constant Buffs:
    arcane_intellect/battle_shout/power_word_fortitude
  Dynamic Buffs:
    blood_fury      : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  4.80%
    bloodlust       : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 13.50%
    demonic_calling : start= 11.8 refresh=  9.9 interval= 25.3 trigger= 13.3 uptime= 42.95%  benefit= 77.10%
    demonic_core    : start= 22.8 refresh= 22.1 interval= 13.1 trigger=  6.5 uptime= 30.64%  benefit= 97.60%
    dreadstalkers   : start= 14.7 refresh= 14.7 interval= 21.0 trigger= 10.1 uptime= 57.68%
    infinite_power  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  4.80%
    wild_imps       : start=  6.2 refresh=135.4 interval= 49.8 trigger=  0.0 uptime= 95.56%
  Up-Times:
     17.22% : Mana Cap                      
  Procs:
    47.4255 | 6.2637sec : three_shard_hog
  Gains:
        85.2 : demonbolt    (soul_shard)   
        27.9 : soul_strike  (soul_shard)   
        66.6 : shadow_bolt  (soul_shard)   
     19191.1 : mana_regen   (mana)           (overflow=27.70%)
    Pet "felguard" Gains:
      3471.0 : energy_regen (energy)       
    Pet "dreadstalker" Gains:
    Pet "wild_imp" Gains:
  Scale Factors:
    Weights :  Int=1.25118(0.0125962)  SP=1.09251(0.0125388)  Crit=0.482808(0.0123158)  Haste=0.387754(0.012282)  Mastery=0.00425812(0.0121458)  Vers=0.44782(0.0123035)
    Wowhead : https://www.wowhead.com/?items&filter=ub=9;gm=3;gb=1;minle=250;ro=2;wt=23:123:96:103:170:215;wtv=1.25:1.09:0.48:0.39:0.00:0.45;
  Waiting:  0.00%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 78
  DTPS=584.343 DTPS-Error=0.292005/0.05% DTPS-Range=44.1593/7.56%
  DPR=0 RPS-Out=543.305 RPS-In=0 Resource=health Waiting=0 ApM=0
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|141892  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=357|357(357) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities (actions.default):

  Actions:

  Constant Buffs:
    arcane_intellect/battle_shout/bleeding/chaos_brand/mortal_wounds/mystic_touch/power_word_fortitude
  Dynamic Buffs:
    Health Decade (0 - 10)   : start=  0.7 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 11.97%
    Health Decade (10 - 20)  : start=  0.9 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  8.12%
    Health Decade (20 - 30)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  9.87%
    Health Decade (30 - 40)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 10.47%
    Health Decade (40 - 50)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 10.50%
    Health Decade (50 - 60)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 10.47%
    Health Decade (60 - 70)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 10.52%
    Health Decade (70 - 80)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 10.46%
    Health Decade (80 - 90)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  9.07%
    Health Decade (90 - 100) : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=  8.55%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting:  0.00%

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 5638 (1405, 1396, 1433, 1404)
  TotalEvents   = 22

**Comment by scamille** [comment]
this just looks like you copied a text output into the input tab, which is not a valid simc input.

In any case, the error message Error: Setup failure: Nothing to sim! directly tells you that there was no valid character specified to simulate.
