### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by massageotp** [simulationcraft/simc#4999]
### Describe the bug
Unable to import.  Receive the below message no matter which version I run.
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/sargeras/massage?namespace=profile-us&locale=en_US'.

### Expected behavior
To be able to import my toons

### To Reproduce
Open simulationcraft.exe click import.  Select US, Sargeras, type Massage > click import

### Additional information
820-01 32
820-01 64
820-02 32
820-02 64

**Comment by voidbeard** [comment]
Same thing is happening on Aman'Thul.

**Comment by navv1234** [comment]
Things may be working again, if you try now.

**Comment by voidbeard** [comment]
Working on my end here :) Thanks for the quick work

**Comment by navv1234** [comment]
Alright, I'll close the issue then, seeing as this was probably related to the API changes blizzard did on their end over the new year.
