### ISSUE TITLE
Initializing Actor '[name]': Item 'inactive' Slot 'wrists': Cannot initialize data

### ISSUE THREAD

**Issue by tlmason** [simulationcraft/simc#5008]
Trying to sim this morning, using the version installed from the latest downloads (820-01), I get this error. 

Here's the output:

> # SimulationCraft encountered an error!
> * Category: Simulation runtime error
> * Error: Initializing: Actor 'Jidhra': Item 'inactive' Slot 'wrists': Cannot initialize data
> 
> ## All options used for simulation:
> ``` ini
> ### SimulationCraft 820-01 for World of Warcraft 8.2.0 Live (wow build 30918) ###
> ### Using QT 5.12.4 with WebEngine ###
> 
> ### Begin GUI options ###
> item_db_source=local/bcpapi/wowhead
> target_error=0
> iterations=0
> default_world_lag=0.1
> max_time=300
> vary_combat_length=0.2
> tmi_window_global=6
> target_level+=3
> target_race=Humanoid
> optimal_raid=0
> override.bloodlust=1
> override.arcane_intellect=1
> override.power_word_fortitude=1
> override.battle_shout=1
> override.bleeding=1
> override.mortal_wounds=1
> override.chaos_brand=1
> override.mystic_touch=1
> threads=12
> process_priority=Low
> calculate_scale_factors=1
> scale_only=str,agi,sta,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
> statistics_level=1
> ### End GUI options ###
> ### Begin simulateText ###
> # SimC Addon 1.12.4
> # Requires SimulationCraft 820-01 or newer
> 
> demonhunter="Jidhra"
> level=120
> race=night_elf
> region=us
> server=wyrmrest_accord
> role=attack
> professions=leatherworking=175/skinning=175
> talents=1311211
> spec=havoc
> 
> azerite_essences=14:1/300573/12:4/300575/300576/5:2/300577
> # azerite_essences_available=3:1/5:2/6:1/12:4/13:1/14:1/15:1/23:1/25:2/27:2/32:1/33:1/35:1
> 
> head=,id=167281,bonus_id=6348/1527/4786/6264/6346/4775,context=25,azerite_powers=159/352/21/466/13
> neck=,id=158075,bonus_id=4932/4933/6316/1610,azerite_level=70
> shoulder=,id=163377,bonus_id=5845/1622/4786/6268/4775,context=23,azerite_powers=245/352/459/14/13
> back=,id=169223,bonus_id=6272,context=11
> chest=,id=173843,bonus_id=1487/4786/6501/4775,context=36,azerite_powers=159/126/31/15/13
> wrist=,id=174954,bonus_id=6540/6513/6578/6579/4803,context=28
> hands=,id=163256,enchant_id=5934,bonus_id=5845/1622/5850/4783,context=23
> waist=,id=173815,bonus_id=6412/4803/6515/6516/1487/4786,context=36
> legs=,id=159306,gem_id=168642,bonus_id=5008/4802/1602/4783,context=35
> feet=,id=173516,bonus_id=6412/4803/6515/6516/1487/4786,context=29
> finger1=,id=168889,enchant_id=6111,gem_id=168637,bonus_id=4801/1808/1472/4786,context=4
> finger2=,id=168890,enchant_id=6111,bonus_id=4801/42/1472/4786,context=4
> trinket1=,id=167380,bonus_id=6349/1527/4786/5843,context=25
> trinket2=,id=167555,gem_id=167672/168752/167693,bonus_id=1482,context=11
> main_hand=,id=169712,enchant_id=5962,bonus_id=6324/6349/1527/4786,context=56
> off_hand=,id=169710,enchant_id=6148,bonus_id=6324/6349/1527/4786,context=56
> 
> ### Gear from Bags
> #
> # Irontide Captain's Hat (420)
> # head=,id=155888,bonus_id=5442/1587/4786/6264/4775,context=35,azerite_powers=354/134/30/44/13
> #
> # Shoulders of the Sanguine Monstrosity (420)
> # shoulder=,id=159323,bonus_id=5442/1587/4786/6265/4775,context=35,azerite_powers=354/160/99/15/13
> #
> # Fairweather Tunic (420)
> # chest=,id=158038,bonus_id=1607/4786/6263/4775,context=28,azerite_powers=134/478/462/14/13
> #
> # Vim's Scalecrusher Clasp (420)
> # waist=,id=170368,gem_id=168642,bonus_id=6300/4802/6293/1507/4786
> #
> # Skinning Knife (4)
> # main_hand=,id=7005,context=14
> #
> # Skinning Knife (4)
> # off_hand=,id=7005,context=14
> 
> ### End simulateText ###
> desired_targets=1
> ### Begin overrides ###
> # User-specified persistent global and player parameters will be set here.
> 
> ### End overrides ###
> ### Begin final options ###
> ### End final options ###
> ### END ###
> ```

**Comment by AlexanderKenny** [comment]
8.3 item on an 8.2 version of Simcraft. Update to a newer version and it should correct itself. As of writing this you may need to build from source yourself as I don't believe a recent build has been put on the download server. Using raidbots is also an option if not familiar compiling yourself.
