### ISSUE TITLE
Allow Azerite Traits and Heart of Azeroth essenses in text form in the script

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#5020]
Currently we have Essenses like this:
azerite_essences=22:2:1/5:3:0/12:4:0

and we have Azerite Traits like this
head=high_altitude_turban,id=158364,bonus_id=5445/1602/4786/6267/4775,azerite_powers=13/15/18/122/250

This is not in human readable format, and I would like to be able to modify it so I can sim various combinations without needing to respec my gear each time and re-importing the character.

If the Essenses and more importantly the Azerite Traits were in text form I would be able to modify the script and run simulations much easier.

Many thanks

**Comment by AlexanderKenny** [comment]
You should already be able to use tokenized names for traits/essences

**Comment by akis-t** [comment]
Great, is there a guide and/or example somewhere so I can test?

**Comment by AlexanderKenny** [comment]
It's covered that they're supported for azerite on the Wiki: https://github.com/simulationcraft/simc/wiki/ExpansionOptions 

Tokenized names in simc follow the format of all lower case, spaces to underscores, other punctuation removed which is also covered by the wiki https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface#names-formatting

**Comment by akis-t** [comment]
Thank you. One more request involving azerite powers (head, shoulders, chest).
Currently we have (as an example) :
head=,id=157985,bonus_id=1637/4786/6505/4775,context=28,azerite_powers=211/192/30/543/13

Can we add to this something like this:
head=,id=157985,bonus_id=1637/4786/6505/4775,context=28,azerite_powers=211/192/30/543/13,azerite_powers_available=211,367/192,234/123,345/ ...

Basically we need the list of available azerite traits to choose from so we can simulate combinations.

**Comment by AlexanderKenny** [comment]
SimC doesn't care about actually valid azerite traits on gear or have any first party support for combinatorics what purpose would adding that info to the item string solve?

**Comment by akis-t** [comment]
It is :

1) to be in keeping with 
# azerite_essences_available=4:3/5:3/12:3/14:2/22:3/27:2/28:3/35:2/36:1

2) I have written an application that runs simc.exe with many/all combinations of azerite_essences_available
I would like to be able to do the same over combinations of azerite traits found on my gear items, not imaginary ones.

Here is a small (truncated) sample output of my application, and how useful it might be if I could do the same for azerite traits found on head, chest and shoulders.

C:\Users\akis>\Utils\SimulationCraftScripting.exe -X c:\Programs\simcraft\simc-830-01-win64-aa1e90e78f\simc.exe -S d:\Users\akis\Documents\Games\RexalSimulation.txt -I 500

AutoSimcraft - by sharesandgames@gmail.com

simc executable: [c:\Programs\simcraft\simc-830-01-win64-aa1e90e78f\simc.exe]
input script: [d:\Users\akis\Documents\Games\RexalSimulation.txt]
output file: [d:\Users\akis\Documents\Games\RexalSimulation.txt.sim]
iterations: [500]
hero=[Rexal]
azerite_essences=[4:3/300573/5:3/300575/300576/22:3/300577/312927]
azerite_essences_available=[4:3/5:3/12:3/14:2/22:3/27:2/28:3/35:2/36:1]
Running essence combinations
**Completed simulation.
Memory of Lucid Dreams:2 - Condensed Life-Force:2 - Spark of Inspiration:1 - 44119
Memory of Lucid Dreams:2 - Worldvein Resonance:3 - Spark of Inspiration:1 - 44241
Spark of Inspiration:1 - Condensed Life-Force:2 - Memory of Lucid Dreams:2 - 44293
Spark of Inspiration:1 - Worldvein Resonance:3 - Memory of Lucid Dreams:2 - 44459
Memory of Lucid Dreams:2 - Vision of Perfection:3 - Spark of Inspiration:1 - 44589
...
...
...
Worldvein Resonance:3 - The Unbound Force:3 - Breath of the Dying:2 - 49962
The Crucible of Flame:3 - Worldvein Resonance:3 - Essence of the Focusing Iris:3 - 49968
The Crucible of Flame:3 - Essence of the Focusing Iris:3 - Condensed Life-Force:2 - 50004
Worldvein Resonance:3 - The Crucible of Flame:3 - The Unbound Force:3 - 50057
The Unbound Force:3 - Essence of the Focusing Iris:3 - Vision of Perfection:3 - 50075
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - Spark of Inspiration:1 - 50176
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - Condensed Life-Force:2 - 50258
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - Vision of Perfection:3 - 50311
The Unbound Force:3 - Essence of the Focusing Iris:3 - Breath of the Dying:2 - 50427
The Crucible of Flame:3 - Essence of the Focusing Iris:3 - Vision of Perfection:3 - 50458
The Unbound Force:3 - Essence of the Focusing Iris:3 - The Crucible of Flame:3 - 50470
The Crucible of Flame:3 - Essence of the Focusing Iris:3 - Breath of the Dying:2 - 50477
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - Breath of the Dying:2 - 50604
The Crucible of Flame:3 - Essence of the Focusing Iris:3 - The Unbound Force:3 - 50773
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - The Crucible of Flame:3 - 50822
Worldvein Resonance:3 - Essence of the Focusing Iris:3 - The Unbound Force:3 - 51055
Finished.
