### ISSUE TITLE
Dribbling Inkpod does not show up in damage report

### ISSUE THREAD

**Issue by chadlittle** [simulationcraft/simc#5027]
### Describe the bug
Simc reports no damage from Dribbling Inkpod when used with a Havoc Demon Hunter.

### Expected behavior
I expect this to do some damage, or be reported as 0.

### To Reproduce
Equip Dribbling Inkpod and run simulation

### Additional information
Tested Weekly and Nightly builds on Raidbots
https://www.raidbots.com/simbot/report/nqhyeHmKBFtmGWXeuq8R56/simc

**Comment by chadlittle** [comment]
Ok, downloaded the same build as Raidbots, but conductive_ink shows fine in that report, but not in Raidbots, even though running same build afaik.

**Comment by Jundarer** [comment]
Fixed with recent Inkpod fixes: https://www.raidbots.com/simbot/report/3a6XWAUjtBGpuzp92SMe8L
