### ISSUE TITLE
Bug overvaluing Dribbling Inkpod by ~20-30%

### ISSUE THREAD

**Issue by Gistwik** [simulationcraft/simc#5030]
In simc Dribbling Inkpod continues to deal additional hits below 30%. On live the trinket does only one big hit at 30% and then "turns off" below 30%.

https://www.warcraftlogs.com/reports/XxjqckmnCy8BgYMG#fight=1&type=damage-done&ability=302491&view=events - Log showcasing this behavior in 8.2.5

https://www.warcraftlogs.com/reports/38PYMHqhZ2CzkG7a#fight=8&type=damage-done&ability=302491&view=events - Log showcasing this behavior in 8.3

Raidbots link showing that in current build of simc inkpod is hitting more than once - https://www.raidbots.com/simbot/report/nFgvU6Xwq2U59kLhzTjrqd/simc

Most important aspects of the above image:

1) Simc lists more than 1 execute for Dribbling Inkpod, when there should only ever be 1 for a Patchwerk fight.
2)The DPS graph for Conductive Ink (while the DPS graphs aren't the most accurate of things for individual abilities like this) shows steady dps after the initial hit, when it should be 1 hit then 0 dps.

**Comment by Jundarer** [comment]
Fixed via b52ab6f
