### ISSUE TITLE
Unable to download item id from wowhead

### ISSUE THREAD

**Issue by bobkat2000** [simulationcraft/simc#5036]
Updated to 830-01 release (why does it write itself to a subfolder called 815-01?) and get this error... I realize it is not a 120-level character, but previous releases didn't have this issue.  Confirmed that item ID exists in Wowhead.  Log output posted below:

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: BCP API: Player 'Bobkitty' unable to download item id '37941' at slot hands.
Player Bobkitty unable to download item id '37941' from wowhead at slot hands.Initializing: Actor 'Bobkitty': Item 'inactive' Slot 'hands': Cannot initialize data

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.025
max_time=300
vary_combat_length=0.2
tmi_window_global=6
tmi_boss=TMI_Standard_Boss_T19L
tmi_boss_type=T19L
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
center_scale_delta=1
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Bobkitty - Destruction - 2020-02-02 08:05 - US/Trollbane
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

warlock="Bobkitty"
level=101
race=blood_elf
region=us
server=trollbane
role=spell
professions=herbalism=7/inscription=5
talents=3323212
spec=destruction

# Default consumables
potion=disabled
flask=disabled
food=disabled
augmentation=disabled

head=,id=122250,bonus_id=583
neck=,id=114951,bonus_id=3709,drop_level=98,context=11
shoulder=,id=121164,bonus_id=1812/1700,drop_level=100
back=,id=129075,bonus_id=1794,drop_level=100
chest=,id=122384,bonus_id=583
wrist=,id=114740,bonus_id=3709/4331,drop_level=99,context=11
hands=,id=37941,bonus_id=3687,drop_level=80,context=11
waist=,id=141874,bonus_id=1794,drop_level=101
legs=,id=122256,bonus_id=583
feet=,id=82527,bonus_id=3701/5491,drop_level=90,context=11
finger1=,id=129172,bonus_id=664,drop_level=100,context=11
finger2=,id=121481,bonus_id=767,drop_level=101,context=11
trinket1=,id=132970,bonus_id=767,drop_level=101,context=11
trinket2=,id=132963,bonus_id=767,drop_level=100,context=11
main_hand=,id=128941,gem_id=0/132987,gem_bonus_id=0/767:1474:1809,bonus_id=1475

### Gear from Bags
#
# Will of the Red Dragonflight (105)
# trinket1=,id=38073,bonus_id=3687/5539,drop_level=80,context=11
#
# Herbalist's Spade (4)
# main_hand=,id=85663

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by navv1234** [comment]
Unsure why it writes itself to that sort of subfolder, unless you had a previous installation.

As for the item download, for some reason the Blizzard API is not returning that item, so it reverts to downloading it from wowhead.  Something goes wrong with that item download/parsing. When I have a bit of time I can take a look at why this is happening. Blizzard should be returning valid data for their own items, so it may have been an intermittent issue on their API.

**Comment by bobkat2000** [comment]
Thanks for the reply… I’ll check it again later today to see if it was a temporary issue… if it helps, I could try running a network packet capture to see if I’m getting any kind of error from the API that might make sense, unless there’s a log file somewhere for this.

For the install, I had the 820-01 subfolder, which it detected—it asked to uninstall but it didn’t—and then just chose 815-01 instead of 830-01.  I did have one of the Beta installs of the program (820-02) which I was just copying into the existing folder, so that might have complicated things--not a straightforward/predictable install setup.  No worries.

Thanks!

**Comment by jesta777** [comment]
I have the same issue... log below...

SimulationCraft encountered an error!

Simulation runtime error:
BCP API: Player 'Strigor' unable to download item id '4786' at slot waist.
Player Strigor unable to download item id '4786' from wowhead at slot waist.Initializing: Actor 'Strigor': Item 'inactive' Slot 'waist': Cannot initialize data

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: BCP API: Player 'Strigor' unable to download item id '4786' at slot waist.
Player Strigor unable to download item id '4786' from wowhead at slot waist.Initializing: Actor 'Strigor': Item 'inactive' Slot 'waist': Cannot initialize data

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=bcpapi/wowhead/local
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Normal
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=3
### End GUI options ###
### Begin simulateText ###
# Strigor - Fire - 2020-02-13 11:43 - EU/Argent Dawn
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

mage="Strigor"
level=22
race=undead
region=eu
server=argent_dawn
role=spell
professions=mining=59/engineering=78
talents=1000000
spec=fire

head=,id=122250,bonus_id=583
neck=,id=122663
shoulder=,id=122378,bonus_id=582
back=,id=5193,bonus_id=4005,drop_level=21,context=1
chest=,id=122384,bonus_id=582
shirt=,id=3428,context=14
wrist=,id=151062,bonus_id=4005,drop_level=20,context=1
hands=,id=3308,bonus_id=3829,drop_level=15,context=26
waist=,id=4786,context=14
legs=,id=122256
feet=,id=51967,bonus_id=1709/4244,drop_level=22,context=17
trinket1=,id=122362,bonus_id=582
trinket2=,id=122361
main_hand=,id=122368,bonus_id=582

### Gear from Bags
#
# Weather-Beaten Fishing Hat (10)
# head=,id=33820,context=11
#
# Ancient Bloodmoon Cloak (26)
# back=,id=122262,bonus_id=582
#
# Disciple's Vest of the Quickblade (16)
# chest=,id=6266,bonus_id=1681/3830,drop_level=20,context=27
#
# Flax Bracers (5)
# wrist=,id=6060,context=11
#
# Inherited Insignia of the Horde (26)
# trinket1=,id=122370,bonus_id=582
#
# Fishing Pole (1)
# main_hand=,id=6256,context=14
#
# Shadow Wand (18)
# main_hand=,id=5071,bonus_id=3859,drop_level=20,context=27
#
# Arclight Spanner (10)
# main_hand=,id=6219
#
# Blacksmith Hammer (1)
# main_hand=,id=5956,context=14
#
# Mining Pick (4)
# main_hand=,id=2901,context=14

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
I have removed any/all copies of Simulationcraft and re-installed. Issue still persists. (Also cannot import chatracter from WoW, I have to use addon to copy character dat into Simulatiocraft, then it fails as above.

**Comment by bobkat2000** [comment]
Sorry for the delay in my reply... first off, the install issue is likely my fault... I originally installed the 815-01 version a while ago, and just did manual updates of the 820-xx versions without actually using an installer.  I think I updated the folder name and manually updated the shortcut.  So, yea, that puts it in a "out-of-scope" scenario, and totally my issue.

For the API error, I still have the same issue with the same Hand slot item.  I tested looking up the item directly in Blizzard's API site: https://develop.battle.net/documentation/world-of-warcraft-classic/game-data-apis and used the following Parameters (without quotes):
:region "us"
{item-id} "37941"
namespace "static-us"
locale "en_US"

For the resulting request URL:
https://us.api.blizzard.com/data/wow/item/37941?namespace=static-us&locale=en_US&access_token={leftblank}

That returned a valid response with the right data.  If I revert back to an earlier version of SimCraft, it works as well...

**Comment by bobkat2000** [comment]
FYI, I tested the "beta" download from Feb 11 - simc-830-02-win64-d82b909dab - and it works!  :)

Not sure if that means this can be closed, and I haven't tested other items that others have reported, but it is likely the issue is resolved.

**Comment by navv1234** [comment]
We did not do anything, so may have been a transient issue on Blizzard's side. I have not had time to look into this yet, I do plan to take a look at how the item download works. At the very least it somewhat looks like the Wowhead item download is currently not working.
