### ISSUE TITLE
Error importing from Battle.Net with uppercase Cyrillic characters

### ISSUE THREAD

**Issue by tarpaha** [simulationcraft/simc#5044]
### Describe the bug
Simulation craft uses wrong URL when importing character profile from Battle.Net

### Expected behavior
Proper downloading of player profile from Battle.Net.

### To Reproduce
Open client, open tab Import -> Battle.Net
Region: EU, Realm: Gordunni, Character: Тар
Press "Import" button.

After second it show tab "Import Failed" with text:

`Unable to download JSON from https://eu.api.blizzard.com/profile/wow/character/gordunni/%D0%A2%D0%B0%D1%80?namespace=profile-eu&locale=en_GB.`

`Error response 404 from Blizzard API: Not Found`

This URL do not work in browser even after adding access token.

But URL
`https://eu.api.blizzard.com/wow/character/gordunni/%D0%A2%D0%B0%D1%80?namespace=profile-eu&locale=en_GB&access_token=.....`
Works fine.

So I think that problem is `/profile/` word in URL generated by SimulationCraft.

### Additional information
* SimulationCraft Version 830-01.

**Comment by navv1234** [comment]
They seem to have changed the end-points again, however the old ones we use still work. Guessing there's some issue with the url decoding of the name.

EDIT: Scratch that, the end-points we use are still there.. looking at the import issue then.

EDIT2: More interesting stuff. Their new API endpoints return 404 not found even when using their own tools for your character. The "old"-style API endpoints return the correct information. This seems more like a Blizzard issue, honestly.

**Comment by tarpaha** [comment]
I tried characters from different realms and found what is wrong.
When I use "Тар" simcraft shows 404, **but** when I use "тар" (lowercase) its works fine!

Latin nick names works in both upper and lowercase variants.

So error caused by uppercase letter in russian nickname (may be any non-latin, did not check that).

**Comment by navv1234** [comment]
Yes, the URI expects lowercase letters, even for UTF-8 which makes it particularly tricky. We should be accommodating for that though (we turn all names into lowercase with an utf-8 aware library), so I'm not sure what is going on there.

**Comment by navv1234** [comment]
Fixing this would require using a much larger library than what we currently have for UTF-8 processing. I wish Blizzard would just accept case-insensitive character names instead ...

**Comment by esteinborn** [comment]
I also cannot get a download from blizzard:

```
# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/wildhammer/drpimento?namespace=profile-us&locale=en_US'.
```

**Comment by esteinborn** [comment]
May be related to #5032 

I was initially running the `nonetwork` version. Changing to a non-`nonetwork` version allowed me to download from WoW Armory without issue

**Comment by barkermn01** [comment]
I'm not running the "no networking" version and I have this issue with no special chars.

```
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/ravenholdt/keatran?namespace=profile-eu&locale=en_GB'.
```

**Comment by scamille** [comment]
Works fine with the latest Nightly from http://downloads.simulationcraft.org/nightly/

@navv1234 Do you mind producing a bfa nightly in the old location, or do we just want to adjust the download link eventually? Might be a bit too early to expose the new 9.0 nightly, but I personally don't care that much.

**Comment by navv1234** [comment]
Yeah, I'll make one today.
