### ISSUE TITLE
Cannot download simcraft files

### ISSUE THREAD

**Issue by punyhuman8** [simulationcraft/simc#5049]
I am getting an error saying "This file does not have an app associated with it for performing this action. Please install an app, or if one is already installed, create an association in the Default Apps Settings page.

I have the base program of simcraft downloaded and get this error if i try to download a new nightly build or a classicsim file.  Just looking for a fix.  I have tried uninstalling and reinstalling, as well as checking regeditor and nothing is working.

**Comment by Melekus** [comment]
If you're on Windows, nightlies are available in the 7z archive format, you will have to download an application to open and extract files from 7z archives such as 7-zip https://www.7-zip.org/

I don't know what "Classicsim" files are but they are not associated with this project.
