### ISSUE TITLE
[Brewmaster] Incorrect GCD

### ISSUE THREAD

**Issue by ManagerWoW** [simulationcraft/simc#5051]
The GCD for Breath of Fire and Rushing Jade Wind is incorrectly hasted in Simc, when they should be non-hasted 1 second. 

[Breath of Fire ](http://manager.heroicstrike.org/8d9etXBj.png)
[Rushing Jade Wind](http://manager.heroicstrike.org/v5wc6dL3.png)

The timestamp in those example pictures should be 1s apart.

Version: The latest nightly (feb 11: simc-830-02-win64-d82b909dab.7z)

**Comment by scamille** [comment]
4cdb03ebbe039a5092a602ca056fb0db664297cf changes some more gcds.

**Comment by ManagerWoW** [comment]
@scamille Thank you for fixing those and many others. Everything looks good except Breath of Fire still seems to be hasted: [sample sequence](http://manager.heroicstrike.org/PgMGkJsh.png)

Tested on today's latest commit.

**Comment by scamille** [comment]
Sorry, seems to have slipped my verification after I got a bit distracted with the azerite essence gcd stuff. I wrongly added gcd_haste_type=none it to the breath of fire ticks instead of the main action.
