### ISSUE TITLE
expedient 2 not working properly

### ISSUE THREAD

**Issue by nieber** [simulationcraft/simc#5060]
I simmed expedient 2 on both a 460 and a 475 item. The 460 item simmed lower than the same piece with no corruption on it. The 475 piece looked to sim ok. Below is the sim I used.

[temp.txt](https://github.com/simulationcraft/simc/files/4242738/temp.txt)

**Comment by vituscze** [comment]
6460 is bonus id for 15 corruption, so your item just has 30 corruption without any other effects.

**Comment by vituscze** [comment]
You can check what the bonus ids do [here](https://github.com/simulationcraft/simc/blob/bfa-dev/SpellDataDump/bonus_ids.txt), for example
