### ISSUE TITLE
Echoing Void damage percentage is pre-nerf value

### ISSUE THREAD

**Issue by musatuncarslan** [simulationcraft/simc#5062]
Echoing void is nerfed couple of weeks ago by around half. Now the rank 2 of echoing void deals 0.6% of the total health as damage each tick. However, in the application it is still the old 1.2% of total health value. 

Description of rank 2 echoing void inside the application under the abilities tab is as follows:

> {$@spelldesc317014={$@spelldesc318280=Your damaging abilities build the Echoing Void. Each time it builds, Echoing Void has a chance to collapse, dealing ${{$s1=10}/10}.2% of your Health as Shadow damage to all nearby enemies every {$s2=1} sec until no stacks remain.}}

which is wrong, it should be 0.6% instead. Raidbots uses the correct 0.6% value and calculates my dps properly (echoing void deals half the damage for the same fight settings) compared to simulationcraft application.

**Comment by AlexanderKenny** [comment]
The spell data for EV rank 2 is as follows:
`Name             : Echoing Void (id=318485) [Passive, Hidden] 
Hotfixed         : Description
School           : Shadow
Spell Type       : None
Attributes       : ......xx ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ..x..... 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : ........ ........ ........ ........   ........ ........ ........ ......x. 
                 : ........ ........ ........ ........   ........ ........ ........ ........ 
                 : Passive (6), Hidden (7)
Effects          :
#1 (id=804325)   : Apply Aura (6) | Unknown(285)
                   Base Value: 60 | Scaled Value: 60 | PvP Coefficient: 1.00000 | Trigger Spell: 317014 | Target: Self (1)
                   Hotfixed: Base Value (15 -> 60)
#2 (id=804326)   : Dummy (3)
                   Base Value: 1 | Scaled Value: 1 | PvP Coefficient: 1.00000 | Target: Self (1)
Description      : Your damaging abilities build the Echoing Void. Each time it builds, Echoing Void has a chance to collapse, dealing ${$s1/100}.2% of your Health as Shadow damage to all nearby enemies every $s2 sec until no stacks remain.`
You can see it has value 60 which is divided by 100 in the codebase to get the health value of 0.6 which is correct. You can also verify this yourself using [Spell Queries](https://github.com/simulationcraft/simc/wiki/SpellQuery)

Furthermore Raidbots is using Simcraft they won't differ if using the same build version of each. If you're sure it's incorrect in your local install make sure to update to something more recent.

**Comment by musatuncarslan** [comment]
For the same gear, raidbots nets in 54k dps and simulationcraft nets in 58k'ish, and the only difference is total damage from the Echoing Void. I just downloaded the newest simulationcraft build by the way prior to this simulation. I am unsure what I am doing wrong.
