### ISSUE TITLE
Set ability on cooldown before simulating

### ISSUE THREAD

**Issue by kkalera** [simulationcraft/simc#5071]
Hi, I'm completely new to Simulationcraft so I don't know if this is possible or not.

I'm trying to use the TCI from the command line. I would like to set an ability on cooldown at the start of a simulation. 

For example: I want to simulate a trash pack of mobs where I use a few cooldowns and after that do a boss fight.

I've read the wiki and documentation, but can't find it anywhere. How do i best do this?

**Comment by vituscze** [comment]
This is currently not possible.

**Comment by scamille** [comment]
You might be able to pull this off by using line_cd= option on the actions you want to use only once.

https://github.com/simulationcraft/simc/wiki/ActionLists#time-based-usages

Just set it so some high value like 1000 (seconds), and it should hopefully only be used once each iteration.
