### ISSUE TITLE
simc addon minimap button to be removable by click

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#5073]

**Comment by akis-t** [comment]
Upon installation of simc addon, it defaults to visible minimap button.

We have a ton of buttons around the minimap and simc is not used very often and most likely not used at all during combat/raids/dungeons, where time and quick clicks are of the essence.

The simc minimap button very annoyingly cannot be clicked on to "hide". Instead the user must type "/simc minimap", which is patronising at the very best. One should always be able to interact with GUI components.

Looking at the code this section defaults it to shown:

```
function Simulationcraft:OnInitialize()
  -- init databroker
  self.db = LibStub("AceDB-3.0"):New("SimulationCraftDB", {
    profile = {
      minimap = {
        hide = false,
      },
    },
  });
  LibDBIcon:Register("SimulationCraft", SimcLDB, self.db.profile.minimap)
  Simulationcraft:UpdateMinimapButton()

  Simulationcraft:RegisterChatCommand('simc', 'HandleChatCommand')
end

```

I think it should default to 
        hide = true,
since the button is not interact-able otherwise.

Many thanks

**Comment by vituscze** [comment]
Please report simc addon bugs/issues in the simc addon repository: https://github.com/simulationcraft/simc-addon
