### ISSUE TITLE
SimC does not seem to use all CPU resources in Linux.

### ISSUE THREAD

**Issue by Magicloud** [simulationcraft/simc#5076]
### Describe the bug
Running SimC on Linux with 24 cores. None is "busy" as expected. The ETA of the simulation is 24 days.

### Expected behavior
All CPU cores busy and get the result in less an hour.

### To Reproduce
I used the profileset downloaded from raidbots.com. Running SimC CLI against it without other parameters.

### Additional information
* SimulationCraft Version (required)
Latest Github source.

**Comment by scamille** [comment]
Sorry for not replying earlier.

SimC should definitely use all threads when correctly specified. See https://github.com/simulationcraft/simc/wiki/ProfileSet#parallel-processing-for-profilesets for profileset specific option.

To debug this we would need a pastebin of the profile you are trying to simulate. Maybe you copied something from raidbots which has a lower number of threads specified than your system has available.

**Comment by Magicloud** [comment]
Thanks for the reply. I think I found the correct config.
