### ISSUE TITLE
macos compiled simc returns "Segmentation fault: 11"

### ISSUE THREAD

**Issue by yurko13** [simulationcraft/simc#5081]
### Describe the bug
1) Executing the following commands (output supressed):
$ git clone https://github.com/simulationcraft/simc.git
$ cd simc
$ git pull
$ cd engine
$ make optimized

2) running compiled file simc in current directory:
$ ./simc
Segmentation fault: 11

### Expected behavior
I should be able to execute "./simc" and use it to simulate data.

### Additional information
* SimulationCraft Version (required) - downloaded from git today 2020-04-07 around noon

* macOS Catalina version 10.15.4 (19E266), updated to latest.
  MacBook Pro (Retina, 15-inch, Late 2013)
  Processor 2.6 GHz Quad-Core Intel Core i7
$ uname -a
Darwin MacBookPro 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

* When it stopped working.
I was updating simc from git and recompiling nightly for months, to simulate data every day.
The last version I am able to execute after compiled is from I believe March 22nd.
From the next day (and any day later I tried) compiled versions simc always returned only "Segmentation fault: 11" error.
The last compiled and working for me version (that one from March 22nd) details:
SimulationCraft 830-02 for World of Warcraft 8.3.0 Live (wow build 33051, git build bfa-dev 4be90c628d)

**Comment by navv1234** [comment]
There are no commits between March 20 (4be90c628dc03906aaaca20c2744e063ec89fa26) and March 25 (a424464760de51901c34b30393b7fc468fbe5290), so I'm not sure how this could be a code issue.

This also occurs with an optimized build on my MacOS, it currently seems to die in dyld handling (loading shared libraries), where we have little to no control over what happens. I'll try to see if we can adjust the optimization flags to get around the problem somehow.

Internet sleuthing [1] seems to point to a problem in XCode 11, which is somewhat scary. XCode 11.4 released on March 24 [2], which would fit this timeline, however why it was not a problem before I don't know.

The workaround is as stated. Issuing `make MACOSX_DEPLOYMENT_TARGET=10.14 optimized` hides the problem (more specifically, probably does that stack checking disable discussed in [1]). The real fix has to wait for apple. I will also update the `Makefile` for now to add this until Apple does something.

[1] https://forums.developer.apple.com/thread/121887
[2] https://en.wikipedia.org/wiki/Xcode#11.x_series

**Comment by yurko13** [comment]
Thank you.
I confirm the issue fixed.
