### ISSUE TITLE
[Guardian] Survival Instincts bug

### ISSUE THREAD

**Issue by hynelohr** [simulationcraft/simc#5088]
### Describe the bug
When trying to add the spell Survival Instincts to the APL without conditionals, the simulation hangs without an error. When delaying it to optimize the uptime of the Masterful Instincts azerite trait, the spell is cast after roughly 36 seconds (5 seconds delay from the Survival Instincts duration + 30 seconds of the Masterful Instincts duration + 1 GCD).

### Expected behavior
The cooldown of Survival Instincts should be of 240 seconds, reduced by 33% if the talent Survival of the Fittest is selected and 25% if Vision of Perfection minor is used. Forcing those cooldowns with line_cd provides no error.

### To Reproduce
Adding `actions.cooldowns+=/survival_instincts` results in a hang

Adding `actions.cooldowns+=/survival_instincts,if=buff.survival_instincts.down&buff.masterful_instincts.down` results in Survival Instincts being cast as soon as possible, seemingly without a cooldown

### Additional information
SimulationCraft 830-02 WebEngine
Nightly version on Raidbots

* **simc_gui.simc** file or contents
[simc_gui.zip](https://github.com/simulationcraft/simc/files/4498451/simc_gui.zip)

**Comment by Melekus** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/cd57a4df32f8cacce56d5447cfc87c1a0a697f5b
