### ISSUE TITLE
Chi Burst not giving the right amount of Chi (Windwalker)

### ISSUE THREAD

**Issue by scurch1** [simulationcraft/simc#5091]
### Describe the bug
[Chi Burst ](https://www.wowhead.com/spell=123986/chi-burst) is not giving any Chi if it's cast pre-combat and is also only giving 1 chi when hitting more than 1 target
### Expected behavior
Chi Burst should generate 1 Chi if hitting 1 target, 2 Chi if hitting more than 1 target. This is true for both pre-combat and during combat

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

https://www.raidbots.com/simbot/report/9CY7eZVTzoVyu9WX7AgmWC
This is set up to cast Chi Burst pre-combat and afterwards off cooldown. It will also cast Blackout Kick whenever it can (requires 1 Chi). You can see it only casted the first Blackout Kick after the 2nd Chi Burst is casted, indicating the pre-combat did not generate any Chi. You can also see it only using 1 Blackout Kick after every Chi Burst, indicating it only generated 1 Chi even though Chi Burst hit 2 targets.

### Additional information
* SimulationCraft Version (required)
https://github.com/simulationcraft/simc/commits/6949e1d108
* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
@Hinalover can you take a look at this, assuming it is still relevant for shadowlands.

Resolving the problem of having 1chi per target should be easy by moving stuff from execute to impact.

Dunno why it is not working precombat.
