### ISSUE TITLE
Ret Paladin: No finnishers being used

### ISSUE THREAD

**Issue by Veelaavulpera** [simulationcraft/simc#5092]
When Siming my ret paladin I am missing most of my talents and spenders.
![image](https://user-images.githubusercontent.com/64599305/80725818-70d76000-8ab8-11ea-951a-c170e10ff0c0.png)
I've noticed under Simulate upon opening it up it had no call to  use any of them
![image](https://user-images.githubusercontent.com/64599305/80725916-91071f00-8ab8-11ea-976a-f11b4324e6b3.png)

but even after adding said line 
![image](https://user-images.githubusercontent.com/64599305/80725995-b136de00-8ab8-11ea-9bf9-31d1260f5bb9.png)

it still comes up with the same results
![image](https://user-images.githubusercontent.com/64599305/80726030-c01d9080-8ab8-11ea-9a22-2265db86d8c0.png)

**Comment by Melekus** [comment]
The finisher actionlist should normally be generated and added to the APL, similarly to the cooldowns and generators lists. Are you running a custom APL or did you change the input in any way?

If that's not the case, could you provide your simc_gui.simc file (contains the input from your last simulation) as well as the version you're running and the process you followed to simulate your character?
