### ISSUE TITLE
Remaining Time / Remaining Combinations

### ISSUE THREAD

**Issue by jfamadas** [simulationcraft/simc#5101]
I have tried to find if there is a way to see which is the remaining time of my simulation but I have found nothing. Currently, I have a simulation running for 4 hours now and I don't know if it has done 1% of the progress and I should stop it or if it has already done 95% of the progress and I should wait for it to finish.

It would be really nice if, for example, I run 100 different gear combinations I had something that says XX out of 100 combinations simulated.

Thank you

**Comment by seriallos** [comment]
Ignore this, I'm an idiot. Didn't look at email/screen closely enough to see that this was the SimC repo...
