### ISSUE TITLE
Neural Synapse Enhancer does not activate gold-coated superconductors

### ISSUE THREAD

**Issue by Zrilian** [simulationcraft/simc#5107]
### Describe the bug
The staff Neural Synapse Enhancer from mechagon does not activate the stat buff from gold-coated superconductors 

### Expected behavior
Activating Neural Synapse Enhancer deals nature damage to the caster and should activate the superconductive buff

### To Reproduce
Run any sim with both of the above items equipped. Make sure the staff activates.
https://www.raidbots.com/simbot/report/7yivGPr1hJSyKK26T7oC59/simc

### Additional information
SimulationCraft 830-02

**Comment by Melekus** [comment]
The effect of Neural Synapse Enhancer doesn't deal damage to the player in the simulation, and the effect of Gold-Coated Superconductors isn't implemented at all.

**Comment by scamille** [comment]
Closing this as a duplicate of #4994 . There are probably a ton of other items not supported, and we always accept pull requests for implementations.
