### ISSUE TITLE
Cant import Character - Version 8.3 

### ISSUE THREAD

**Issue by kharsch1337** [simulationcraft/simc#5117]
Simcraft failes to import my character.
Iam Using the Version 8.3.

The following message is produced when i try import:

**>     # Profile will be downloaded into a new tab.
>     #
>     # Clicking Simulate will create a simc_gui.simc profile for review.
> 
>     # Unable to generate profile from: 
> 
>     # Unable to download JSON from 
>     'https://eu.api.blizzard.com/profile/wow/character/durotan/thallia?namespace=profile- 
>      eu&locale=en_GB'.**

It seems theyve changed the API Endpoints maybe? 

Do you have any advice to fix it?

**Comment by Hairy0tter** [comment]
I am getting the same issue, although I have a character that has been previously stored on there that is working fine.

**Comment by pateljatin** [comment]
I am getting the same issue as well for win64.
downloaded nightly and works fine

**Comment by navv1234** [comment]
If you are using the 830-01 release setup package and not nightlies, redownloading & installing it might help. I would suggest using nightly builds instead, however.

**Comment by freakynl** [comment]
Same issue on linux, just built it. 

**Import Failed Tab**

```
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/kul-tiras/smokinfreaky?namespace=profile-eu&locale=en_GB'.
```

**CLI Output**
freaky@flaptoppy /tmp/sim/simc/build/qt $ ./SimulationCraft
[Localization]: Selected gui language:  "auto"
[Localization]: QLocale system language:  "us"
[Localization]: Trying to load local file from:  "/tmp/sim/simc/build/qt/locale" / "sc_us" .qm
[Localization]: Loaded translator isEmpty():  true
TmpDir:  "/home/freaky/.cache/SimulationCraft/SimulationCraft"
ResultsDestDir:  "/home/freaky/Documents"
welcome_uri:  "file:////tmp/sim/simc/build/qt/Welcome.html" 

Loaded realm information for "US" n_model_entries 246
Loaded realm information for "EU" n_model_entries 267
Loaded realm information for "TW" n_model_entries 25
Loaded realm information for "KR" n_model_entries 18
Sample Profiles Base Path:  "/tmp/sim/simc/build/qt/profiles"  exists:  false
Unable to fetch bearer token from https://eu.battle.net/oauth/token, response=401, error=, result={"error":"unauthorized","error_description":"An Authentication object was not found in the SecurityContext"}


**git log**

78258b9d73 (HEAD -> bfa-dev, origin/bfa-dev, origin/HEAD) windwalker APL fixes (#5160)

**Comment by navv1234** [comment]
If you self-compile, you will need an API key from Blizzard.

**Comment by AntonAlekseevAA** [comment]
Same issue. I install program using win64 no-network installer from here http://downloads.simulationcraft.org/simc-830-02-win64-nonetwork-92ef842e32.7z

**Comment by navv1234** [comment]
The no-networking ones are just that. No networking. They will not be able to import anything since they don't include the code to access Blizzzrd's api.

**Comment by freakynl** [comment]
> If you self-compile, you will need an API key from Blizzard.

Okay, will try that (still fails now, but might take up to 10 mins the site says to propagate).

Anyways I just followed build instructions (https://github.com/simulationcraft/simc/wiki/HowToBuild) might want to mention it there / link to https://github.com/simulationcraft/simc/wiki/BattleArmoryAPI 

Thanks :)

**Comment by AntonAlekseevAA** [comment]
Some possible bug with characters names in russian locale. I try import my profile, but take this error. After this, i create my armory api account, import id and secret key on `Options` page. But error not fixed. Next i try get profile data manually. I use this request, to get my account info and hrefs for all characters.
```
curl "https://eu.api.blizzard.com/profile/user/wow?namespace=profile-eu&locale=ru_RU&access_token=<mytoken>"
```
Result is:
```
curl "https://eu.api.blizzard.com/profile/user/wow?namespace=profile-eu&locale=ru_RU&access_token=<mytoken>"
{"_links":{"self":{"href":"https://eu.api.blizzard.com/profile/user/wow?namespace=profile-eu"},"user":{"href":"https://eu.api.blizzard.com/profile/user"},"profile":{"href":"https://eu.api.blizzard.com/profile/user/wow?namespace=profile-eu"}},"id":476322090,"wow_accounts":[{"id":926161710,"characters":[{"character":{"href":"https://eu.api.blizzard.com/profile/wow/character/eversong/%D0%BF%D1%80%D0%B8%D0%BA%D0%BE%D0%BF%D0%B4%D0%B2%D0%B0?namespace=profile-eu"},"protected_character":{"href":"https://eu.api.blizzard.com/profile/user/wow/protected-character/1925-202502181?namespace=profile-eu"},"name":"╨Я╤А╨╕╨║╨╛╨┐╨┤╨▓╨░","id":202502181,"realm":{"key":{"href":"https://eu.api.blizzard.com/data/wow/realm/1925?namespace=dynamic-eu"},"name":"╨Т╨╡╤З╨╜╨░╤П ╨Я╨╡╤Б╨╜╤П","id":1925,"slug":"eversong"},"playable_class":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-class/1?namespace=static-8.3.0_32861-eu"},"name":"╨Т╨╛╨╕╨╜","id":1},"playable_race":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-race/1?namespace=static-8.3.0_32861-eu"},"name":"╨з╨╡╨╗╨╛╨▓╨╡╨║","id":1},"gender":{"type":"MALE","name":"╨Ь╤Г╨╢╤Б╨║╨╛╨╣"},"faction":{"type":"ALLIANCE","name":"╨Р╨╗╤М╤П╨╜╤Б"},"level":110},{"character":{"href":"https://eu.api.blizzard.com/profile/wow/character/eversong/%D1%81%D0%BA%D0%BC%D0%B5%D1%84%D0%BF%D1%80%D0%BE%D0%B1%D1%8B?namespace=profile-eu"},"protected_character":{"href":"https://eu.api.blizzard.com/profile/user/wow/protected-character/1925-202508753?namespace=profile-eu"},"name":"╨б╨║╨╝╨╡╤Д╨┐╤А╨╛╨▒╤Л","id":202508753,"realm":{"key":{"href":"https://eu.api.blizzard.com/data/wow/realm/1925?namespace=dynamic-eu"},"name":"╨Т╨╡╤З╨╜╨░╤П ╨Я╨╡╤Б╨╜╤П","id":1925,"slug":"eversong"},"playable_class":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-class/6?namespace=static-8.3.0_32861-eu"},"name":"╨а╤Л╤Ж╨░╤А╤М ╤Б╨╝╨╡╤А╤В╨╕","id":6},"playable_race":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-race/1?namespace=static-8.3.0_32861-eu"},"name":"╨з╨╡╨╗╨╛╨▓╨╡╨║","id":1},"gender":{"type":"FEMALE","name":"╨Ц╨╡╨╜╤Б╨║╨╕╨╣"},"faction":{"type":"ALLIANCE","name":"╨Р╨╗╤М╤П╨╜╤Б"},"level":120},{"character":{"href":"https://eu.api.blizzard.com/profile/wow/character/eversong/%D0%BB%D0%B0%D0%B2%D1%80%D0%B5%D0%BD%D1%82%D0%B5%D1%8F?namespace=profile-eu"},"protected_character":{"href":"https://eu.api.blizzard.com/profile/user/wow/protected-character/1925-202758297?namespace=profile-eu"},"name":"╨Ы╨░╨▓╤А╨╡╨╜╤В╨╡╤П","id":202758297,"realm":{"key":{"href":"https://eu.api.blizzard.com/data/wow/realm/1925?namespace=dynamic-eu"},"name":"╨Т╨╡╤З╨╜╨░╤П ╨Я╨╡╤Б╨╜╤П","id":1925,"slug":"eversong"},"playable_class":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-class/3?namespace=static-8.3.0_32861-eu"},"name":"╨Ю╤Е╨╛╤В╨╜╨╕╨║","id":3},"playable_race":{"key":{"href":"https://eu.api.blizzard.com/data/wow/playable-race/4?namespace=static-8.3.0_32861-eu"},"name":"╨Э╨╛╤З╨╜╨╛╨╣ ╤Н╨╗╤М╤Д","id":4},"gender":{"type":"FEMALE","name":"╨Ц╨╡╨╜╤Б╨║╨╕╨╣"},"faction":{"type":"ALLIANCE","name":"╨Р╨╗╤М╤П╨╜╤Б"},"level":120}]}],"collections":{"href":"https://eu.api.blizzard.com/profile/user/wow/collections?namespace=profile-eu"}}
```
Character I'm interested in has this profile link 
```
https://eu.api.blizzard.com/profile/wow/character/eversong/%D1%81%D0%BA%D0%BC%D0%B5%D1%84%D0%BF%D1%80%D0%BE%D0%B1%D1%8B?namespace=profile-eu
```
But when i input my character name in simcraft, follow import link generated
```
https://eu.api.blizzard.com/profile/wow/character/eversong/%D0%A1%D0%BA%D0%BC%D0%B5%D1%84%D0%BF%D1%80%D0%BE%D0%B1%D1%8B?namespace=profile-eu&locale=en_GB
```
As you see, url encode of ru symbols is different in responce from blizzard api and program request link

**Comment by ghost** [comment]
Hi there i got something that is similar to the others in here, Maybe i am doing everything wrong , but i got this message.


# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Paladin holy for player Arthalas is not currently supported.Initializing: No active players in sim!

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=600
vary_combat_length=0.2
fight_style=LightMovement
challenge_mode=1
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=16
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Arthalas - Holy - 2020-08-14 18:21 - EU/Perenolde
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

paladin="Arthalas"
level=120
race=human
region=eu
server=perenolde
role=attack
professions=blacksmithing=95/mining=175
talents=1331311
spec=holy

azerite_essences=12:3/300573/24:1/300575/300576/0:0/300577/312927
# azerite_essences_available=12:3/24:1/35:1

head=,id=155885,bonus_id=4818/1587/4785/6258/4775,context=2,azerite_powers=125/15/13
neck=,id=158075,bonus_id=4932/4933/6316/1618,context=11,azerite_level=74
shoulder=,id=173835,bonus_id=1487/4786/6503/4775,context=9,azerite_powers=233/582/38/14/13
back=,id=169223,bonus_id=6272,context=11
chest=,id=159424,bonus_id=4818/1587/4785/6257/4775,context=2,azerite_powers=188/85/13
shirt=,id=6833
wrist=,id=174956,bonus_id=6540/6513/6578/6579/4803,context=29
hands=,id=168885,bonus_id=4798/1487/4786,context=3
waist=,id=159434,bonus_id=4778/6516/6515/1587/4785,context=2
legs=,id=169811,bonus_id=6288/6300
feet=,id=159452,bonus_id=4779/1572/4786,context=23
finger1=,id=168977,bonus_id=4778/6516/6515/1472/4785,context=2
finger2=,id=159459,bonus_id=4778/4802/6516/6513/1587/4785,context=2
trinket1=,id=169301,context=13
trinket2=,id=169328,context=13
main_hand=,id=158369,bonus_id=4778/6516/6513/1587/4785,context=2
off_hand=,id=158713,bonus_id=4778/6516/6515/1587/4785,context=2

### Gear from Bags
#
# Knöcherne Angelrute (15)
# main_hand=,id=45991

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment]
The error message

 Paladin holy for player Arthalas is not currently supported

means that simulation paladins with holy specialization is currently not supported. To get it working requires somebody picking up development for holy paladins and finishing their SimC implementation.

**Comment by ghost** [comment]
Ok thx for the Informationen.

Serge Camille <notifications@github.com> schrieb am Fr., 14. Aug. 2020,
19:06:

**Comment by scamille** [comment]
Closing this, since it is outdated and should be fixed with the latest nightly release.

@AntonAlekseevAA as far as I can tell, SimC always uses en_gb locale for any eu download. I think this is done on purpose.

I was able to successfully download your character both in the GUI and CLI, and also click the armory link in the generated html report.

If there are still unresolved problems with it, please open a new and separate ticket so we can resolve any issues with russian locale.
