### ISSUE TITLE
Gear and weapons stats, corruption

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#5127]
Can you please document how the "bonus_id=" is encoded ? 

Can you please document how corruption effects are encoded, eg I want to add "+66 corruption, tentacle mind flay" - how do I do that?

Can you please document all the valid weapon string types? You have only documented in an example "axe2h" ... I have guessed a one handed sword is "sword" and not "sword_1h"...

**Comment by vituscze** [comment]
You can run simc with show_bonus_ids=1 to see what the bonus id that simc recognizes do. You can also check [here](https://github.com/simulationcraft/simc/blob/bfa-dev/SpellDataDump/bonus_ids.txt).

**Comment by akis-t** [comment]
Great,

how do I add 66 corruption twisted appendage to this weapon?

main_hand=swarms,ilevel=450,weapon=sword_2.60speed_667min_1113max,stats=301agi_555sta_90vers_65haste,enchant_id=5965

the relevant line from simc help is:
bonus_id={ 6545 }, stats={ 100% Cor [66.0000] }, effects={ Twisted Appendage (id=318483, index=2, type=equip) }

**Comment by AlexanderKenny** [comment]
Weapon string types I believe should be documented on the [wiki](https://github.com/simulationcraft/simc/wiki/Equipment#stats) or they can be found [here](https://github.com/simulationcraft/simc/blob/4aab92473678254393b1c68e4b785b750be5359b/engine/util/util.cpp#L977)

As for the `bonus_id=6545` if the field is not already in use like in your example you simply can append it (with a comma to separate fields). If the field is already in use on the item and you just wish to add additional bonus IDs to it then you can simply separate them using a `/`

**Comment by akis-t** [comment]
Thank you. But I was talking about the case where the weapon is specified manually, eg

main_hand=swarms,ilevel=450,weapon=sword_2.60speed_667min_1113max,stats=301agi_555sta_90vers_65haste,enchant_id=5965

How do I add the bonus_id=6545 to the above weapon? If I tag it at the end it seems it ignores it, eg

main_hand=swarms,ilevel=450,weapon=sword_2.60speed_667min_1113max,stats=301agi_555sta_90vers_65haste,enchant_id=5965,bonus_id=6545

**Comment by navv1234** [comment]
The simulator currently only applies item bonuses if it gets the item from an actual item source (local database, wowhead, or blizzard). This essentially means that the item has an `id` option specified.

**Comment by akis-t** [comment]
Hello, thanks for the clarification. Please make it so we can code in the Corruption stats just as we can code in all the other stats. It is the only way we can compare sets of gear with and without their corruption, imaginary gear with corruption, and with added corruption from Mother.

**Comment by Melekus** [comment]
What stops you from using actual gear input and adding/removing the specific bonus IDs associated with corruption?

**Comment by akis-t** [comment]
Imaginary gear, as I mentioned earlier. And since we already support "stats", why not also "corruption" and "traits" too?

**Comment by Melekus** [comment]
A solution for your problem would be to use regular gear, mix and match corruption bonus IDs, and override the total stats contribution from gear using the options found here.

https://github.com/simulationcraft/simc/wiki/Characters#overriding-the-gear-contribution

**Comment by navv1234** [comment]
> Imaginary gear, as I mentioned earlier. And since we already support "stats", why not also "corruption" and "traits" too?

Because nobody has implemented it. In the case of corruption, it's a non-trivial implementation.

**Comment by akis-t** [comment]
thanks guys
