### ISSUE TITLE
Wrong DPS simulating gloves with agi instead of agiint

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#5128]
On a Outlaw Rogue

The below :
hands=,id=158040,bonus_id=4803/42/6516/6513/1612/4785,context=27

which is
Fairweather Gloves
ilevel: 420, stats: { 249 Armor, +341 AgiInt, +605 Sta, +118 Crit, +91 Vers, +90 RunSpeed }

gives around 1000 extra DPS compared to

hands=fairweather,ilevel=420,stats=249armor_341agiint_605sta_118crit_91vers_90runspeed

They are both the same, so why the extra 1000 DPS?

**Comment by AlexanderKenny** [comment]
Add type=leather as well. You'd be deactivating your armor matching passive as is.

**Comment by akis-t** [comment]
thanks!
