### ISSUE TITLE
Avenger's Might w/ Vision of Perfection and Crusade Interaction

### ISSUE THREAD

**Issue by Gnashes** [simulationcraft/simc#5138]
In-game, a Vision of Perfection (VoP) proc that is standalone (that is, one which does not extend the duration of an existing Crusade buff), will apply the Avenger's Might (AM) buff for an amount of time equal to the Crusade buff (35% of the 25s base duration of Crusade, or 8.75s). However, if a VoP proc extends the duration of an existing Crusade buff, the AM buff is only extended for 7s (it seems the calculation incorrectly uses the base Avenging Wrath duration of 20s for some reason). This can be seen via the links below:

1.  https://www.warcraftlogs.com/reports/LZA1HdM6YjvCW4RB/#fight=19&type=auras&source=7&ability=272903&view=events

2. https://www.warcraftlogs.com/reports/LZA1HdM6YjvCW4RB/#fight=19&type=auras&source=7&ability=231895&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%24193328683.0.0.Paladin%24true%24193328683.0.0.Paladin%24false%24272903%5E0%24Separate%24%23909049%24auras-gained%240%240.0.0.Any%24193328683.0.0.Paladin%24true%24193328683.0.0.Paladin%24false%24231895

In simulationcraft, it would appear that the AM buff uptime always matches the Crusade buff uptime, even when the maximum Crusade duration for the simulation is as high as 186.8s which would indicate that VoP extended an existing Crusade buff (Seen within https://www.raidbots.com/simbot/report/ucZbhx3LyWwkTUBG5zrKws/simc

I know it's a minor thing, but I figured I would bring it to your attention.

**Comment by Melekus** [comment]
Bug applied in https://github.com/simulationcraft/simc/commit/153f5c3e778ef44fb1b7cb0c5c115f80111f49d3
