### ISSUE TITLE
There hasn't been a new nightly build published in over a month

### ISSUE THREAD

**Issue by IgorekSF** [simulationcraft/simc#5145]
### Describe the bug
These used to be posted nightly, or close to it; but the most recent one now dates May 2.

### Expected behavior
Nightly builds to be published more often; weekly would be sufficient.

**Comment by navv1234** [comment]
Yeah sorry about that, RL been busy and the sim went through a reorganization of source files.

I have updated local release build scripts now to the new world order and published new nightlies for x64 and x86.

**Comment by IgorekSF** [comment]
Thanks a lot!

**Comment by IgorekSF** [comment]
Reopening, as the most recent build dates Jun 30.

**Comment by scamille** [comment]
There are some nightly builds from august, which should be good enough now since not much is happening.

We have windows nightly builds automated for shadowlands, so this problem should no longer occur in the future.
