### ISSUE TITLE
Havoc DH sim using throw glaive due to demon blades being selected as a talent.

### ISSUE THREAD

**Issue by Nickthenec** [simulationcraft/simc#5146]
![image](https://user-images.githubusercontent.com/44248076/84089885-082baf00-a9a5-11ea-942f-aa0b57befcaa.png)
Demon blades does not affect throw glaive and should not warrant using 53 GCDs in a 5 minute patchwerk fight.

**Comment by EvanMichaels** [comment]
Not totally sure what your objection is here. DBlades specs have many free globals since there is no DBite filler. Removing TG would just be a DPS loss. TG is not as strong as in Legion so it is not a massive DPS gain but I’m curious if you have evidence to show it is not worth using at all.

**Comment by Nickthenec** [comment]
Well after running like 50 sims I'm just wrong. Sorry to waste your time. I was surprised at how a 9 second cooldown could be 1.5% dps.

**Comment by EvanMichaels** [comment]
No problem! Glad you sorted it out!
