### ISSUE TITLE
Cannot run own compiled SimC

### ISSUE THREAD

**Issue by Wolf-DK** [simulationcraft/simc#5150]
Hi all,
Noob "developer" here... Wanted to compile my own SimCraft to have the latest and updated version when I wanted to sim myself.
(Since the nightly was falling behind the info released on Icyveins and other sites - I know this has since been fixed, but I kept trying to get it at least to compile).

Despite the lacking (and outdated) info in the how-to-build guide, I managed to setup my Dev PC with all the right settings:
QT 5.14.2 and MSVC 2017 running on Windows 10.

Found the build bat file "Build-simc.bat" and set the required environment variables.
System variables:
```
CURL_ROOT=C:\Progs\curl\
INSTALL=C:\Out\Build\
MSBUILDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\
qt_dir=C:\Qt\5.14.2\
QTDIR=C:\Qt\5.14.2\msvc2017_64\
RELEASE_CREDENTIALS=Wolf (not sure if I need to set this or not)
SIMCAPPFULLVERSION=8.3.0.05 (not sure if I need to set this or not)
SIMCDIR=C:\Projects\simc\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\
visualstudio=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\
SIMCVERSION=830-05 (had to set it to something)
```
And updated path to include "C:\Qt\5.14.2\msvc2017_64\bin\"

Running "Qt 5.14.2 (MSVC 2017 64-bit)" (link)
And then calling: 
	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
Before running the build file with this command:
	"C:\Projects\simc\WinReleaseScripts\build-simc.bat release x64"

I kept getting the following error:

Build FAILED.

       "C:\Projects\simc\simulationcraft.sln" (Clean;Build target) (1) ->
       "C:\Projects\simc\lib\Simulationcraft Engine.vcxproj" (default target) (2:7) ->
       (ClCompile target) ->
         c:\projects\simc\engine\dbc\generated\item_data.inc(63994): fatal error C1060: compiler is out of heap space (
       compiling source file ..\engine\dbc\item_import.cpp) [C:\Projects\simc\lib\Simulationcraft Engine.vcxproj]

    0 Warning(s)
    1 Error(s)
	
	
	-----------
Edited "item_data.inc" and removed all entries with "Gladiator" (I don't play PVP)
Now I was finally able to compile without any error.
( I would love to know how to compile without this error using original file).

When I run the resulting release, I get the following error:
	
	# SimulationCraft encountered an error!
	# SimulationCraft 830-02 for World of Warcraft 8.3.0.34220 Live (hotfix 2020-06-02/34220)
	* Category: Simulation runtime error
	* Error: Initializing: Actor 'Adep': Item 'psychics_subtle_slippers' Slot 'feet': Error decoding gems from '': No gem data for id 168641.

	## All options used for simulation:
	``` ini
	### SimulationCraft 830-02 for World of Warcraft 8.3.0.34220 Live (wow build 34220)  ###
	### Using QT 5.14.2 with WebEngine ###

	### Begin GUI options ###
	item_db_source=local/bcpapi/wowhead
	target_error=0
	iterations=0
	default_world_lag=0.1
	max_time=300
	vary_combat_length=0.2
	tmi_window_global=6
	target_level+=3
	target_race=Humanoid
	optimal_raid=0
	override.bloodlust=1
	override.arcane_intellect=1
	override.power_word_fortitude=1
	override.battle_shout=1
	override.bleeding=1
	override.mortal_wounds=1
	override.chaos_brand=1
	override.mystic_touch=1
	threads=12
	process_priority=Low
	statistics_level=1
	### End GUI options ###
	### Begin simulateText ###
	# Adep - Destruction - 2020-06-05 15:12 - EU/Draenor
	# SimC Addon 1.12.5
	# Requires SimulationCraft 820-01 or newer

	warlock="Adep"
	level=120
	race=blood_elf
	region=eu
	server=draenor
	role=spell
	professions=alchemy=175/herbalism=175
	talents=1123323
	spec=destruction

	azerite_essences=22:3/300573/35:4/300575/300576/27:3/300577/312927/5:3/312928
	# azerite_essences_available=4:3/5:3/6:3/12:4/14:3/15:1/22:3/27:3/28:3/32:1/35:4/36:4/37:3

	head=,id=174118,bonus_id=4823/1502/4786/6508/4775,context=5,azerite_powers=131/232/22/83/13
	neck=,id=158075,bonus_id=6316/4932/4933/1652,context=11,azerite_level=91
	shoulder=,id=174117,bonus_id=4823/1502/4786/6509/4775,context=5,azerite_powers=431/232/30/44/13
	back=,id=169223,bonus_id=6589/1472,context=11
	chest=,id=159268,bonus_id=5448/1647/4786/6510/4775,context=35,azerite_powers=460/232/21/83/13
	shirt=,id=169878
	wrist=,id=174129,gem_id=168641,bonus_id=4823/1808/6515/1502/4786/6475/6462,context=5
	hands=,id=159253,enchant_id=5932,bonus_id=6528/6578/6513/1637/4786/6516,context=35
	waist=,id=173436,bonus_id=6412/6513/6578/6579/6542/1522/4786,context=54
	legs=,id=168988,bonus_id=6536/6578/6579/6473/6470/6515/1532/4786,context=35
	feet=,id=174123,gem_id=168641,bonus_id=4824/1517/4786/6476/6470/6514,context=6
	finger1=,id=169157,enchant_id=6109,bonus_id=6536/6516/6515/1522/4786,context=16
	finger2=,id=169160,enchant_id=6109,bonus_id=6530/6578/6513/1527/4786/6516,context=35
	trinket1=,id=174500,gem_id=168641,bonus_id=4823/1808/6515/1502/4786,context=5
	trinket2=,id=174103,gem_id=168641,bonus_id=4823/1502/4786/6514,context=5
	main_hand=,id=172201,enchant_id=6112,gem_id=168641,bonus_id=4823/1808/6515/1502/4786/6474/6455,context=5
	off_hand=,id=159667,bonus_id=6534/6516/6515/1637/4786,context=16



	### End simulateText ###
	desired_targets=3
	### Begin overrides ###
	# User-specified persistent global and player parameters will be set here.

	### End overrides ###
	### Begin final options ###
	### End final options ###
	### END ###
	```
--------- 
I have verified that info for Gem 168641 is included in my modified item_data.inc:
`	{ 168641, "Quick Sand Spinel", 0x00000040, 0x00002000, 0x00, 120, 0, 0, 0, 4, 0, 3, 7, 0, 0, 0.000000, 0.000000, 0xffffffffffffffff, 0xffff, { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000 }, {   0,   0,   0,   0,   0 }, {      0,      0,      0,      0,      0 }, {      0,      0,      0,      0,      0 }, {    0,    0,    0,    0,    0 }, {      0,      0,      0,      0,      0 }, { 0, 0, 0 }, 3763, 0, 0, 0, 0 },`

So now I am not sure how to proceed and fix this issue.

Any help appriciated.

I know there are multiple issues mentioned in this post, and if needed I can create a bug report for each - please let me know.

Regards
Wolf

**PS: Issue in guides:**
1) Newbie build instructions:
https://github.com/simulationcraft/simc/wiki/Newbie-build-instructions
Wrong VS and QT version (QT5.6.0 is bloody difficult to find).
Suggestion: Remove

2) How to Build instructions:
https://github.com/simulationcraft/simc/wiki/HowToBuild
No mention of the build scripts or the environment settings needed.
Instruction won't allow user to get the full release version created.
Suggestion: Update with clear instruction for setting up and running the build bat file.
Including how to call vcvarsall.bat.

**Comment by navv1234** [comment]
Build scripts in bfa-dev are not modified for the new file structure, so they may probably not work. Item database is large enough nowadays that the default Visual Studio 32-bit toolchain can not allocate enough heap space to compile the item data compilation unit. You will need to use the 64-bit toolchain compiler to compile simc.

I don't use VS 2017, on 2019 this seems to be automatic when you use amd64 (or x64) platform setting when you load the "vc vars". You can check from the path variable what it is using by looking for "HostX64" (64-bit toolchain) or "HostX86" (32-bit toolchain).

The build instructions were probably written when 5.6 was the newest version. It is not intended that you use specifically Qt 5.6 to build simc.

**Comment by Wolf-DK** [comment]
That is kinda why I don't get the issue, I initialize VCVARSALL with x64:
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.23
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
**[vcvarsall.bat] Environment initialized for: 'x64'**
Then I use build script with x64 too.

And the QT command prompt I am using is for x64 too.

/Wolf

**Comment by navv1234** [comment]
Because Qt is stupid. `set PreferredToolArchitecture=x64` should do the trick before compilation.

**Comment by Wolf-DK** [comment]
That actually worked, thanks
And to be clear, I did a new git clone and was able to compile without any errors.
And the build also works and I could complete a sim.
Should have asked when I got the first error... guess my doctored file had some issues still.

Thanks - closing issue.
