### ISSUE TITLE
Incorrect haste scaling on Merektha's Fang

### ISSUE THREAD

**Issue by inkounter** [simulationcraft/simc#5169]
### Describe the bug
Merektha's Fang's modeled total damage output does not scale with haste as much as it should. Glancing at the code and comparing to in-game observations, [the debuff duration](https://github.com/simulationcraft/simc/blob/e79981b7b59668609bd4e89dc4e145f5c9a48956/engine/player/unique_gear_bfa.cpp#L1188) looks like it should not be modified by haste; in-game, the duration is a flat 4.0 seconds (and gets refreshed to 4.0 seconds on application of the 2nd and 3rd stacks), regardless of haste.

Simc does predict more total damage from Noxious Venom with a large haste proc, with a multiplier of about 1.25x:
https://www.raidbots.com/simbot/report/77WAQxziUGdPMbPFSrPKX7/simc
https://www.raidbots.com/simbot/report/syt98N6nmtKToAVs9yibUp/simc

But this is nowhere near the multiplier of nearly 2x observed in-game. (See logs below.)

### Expected behavior
Getting a massive haste proc (e.g., Metamorphosis + 3x Furious Gaze for a 25% flat haste plus ~3300 haste rating, all modified by 2x Expedient 3) should scale the total damage output by Merektha's Fang over its full duration because there are more hits over a very similar duration (4 seconds + some buffer X, where X decreases as haste increases).

### To Reproduce
https://www.warcraftlogs.com/reports/4Dta1zx7TCpJVrAK

In the 0:14 duration pull, Havocker uses Merektha's Fang once with no big haste proc. It hits 8 times.
In the 0:45 duration pull, Havocker uses Merektha's Fang once with a big haste proc. It hits 12 times.

### Additional information
* SimulationCraft Version (required)

SimC Version: Nightly (830-02)
SimC Build Date: Jul 1 2020
SimC Git Hash: feeda6957d

**Comment by EvanMichaels** [comment]
This trinket has some very odd behavior and the last time it was updated to a special case behavior, it matched in-game values. However it does seem like it has changed at some unknown point to behave differently again, in a way that neither matches "normal" behavior or the previously-coded behavior.

When I last looked at this, no simple change seemed to match the logged values but perhaps this can be revisited.
