### ISSUE TITLE
cant start /simc

### ISSUE THREAD

**Issue by Snowmanmc87** [simulationcraft/simc#5182]
5x Simulationcraft\core.lua:5: Cannot find a library instance of "LibRealmInfo".
[string "=[C]"]: in function `error'
[string "@ElvUI\Libraries\Ace3\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@Simulationcraft\core.lua"]:5: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibRealmInfo"."

**Comment by vituscze** [comment]
Please report bugs related to the simc addon here: https://github.com/simulationcraft/simc-addon
