### ISSUE TITLE
[Shadowlands Hunter] Dire Best and Frenzy talents

### ISSUE THREAD

**Issue by cyberc0re** [simulationcraft/simc#5239]
### Describe the bug
Beast master hunter is unable to be simulated with the Dire Beast and Stomp talent combination. 
Assertion failed: 0, file D:\Shadowlands Simc\simc\engine\action\sc_stats.cpp, line 74
stats_t stomp already has parent barbed_shot, can't parent to dire_beastAssertion failed: 0, file D:\Shadowlands Simc\simc\engine\action\sc_stats.cpp, line 74

### To Reproduce
Run any beast mastery simulation with the talent combination Dire Beast and Stomp.

### Additional information
* SimulationCraft Version (required)
901-01

**Comment by Pewtro** [comment]
I’ve simmed those without an issue - can you give more information? Which profile? Which git hash?

**Comment by Jayezi** [comment]
Think if you build release it will pass fine, he might be doing debug, which I usually do and ran into this, been using this to make it pass
```diff
@@ -4832,11 +4835,11 @@ struct dire_beast_t: public hunter_spell_t
     harmful = may_hit = false;
   }
 
   void init_finished() override
   {
-    add_pet_stats( p() -> pets.dire_beast, { "dire_beast_melee", "stomp" } );
+    add_pet_stats( p() -> pets.dire_beast, { "dire_beast_melee" } );
 
     hunter_spell_t::init_finished();
   }
 
   void execute() override
```
