### ISSUE TITLE
Unably to simulate Unholy in Nightly 901-01 build

### ISSUE THREAD

**Issue by Rothulian** [simulationcraft/simc#5241]
### Describe the bug
901-01-win64

2020-09-06 21:22 | 52M |  

This build has been completely unable to sim Unholy.  The APL Im using comes from a DK Discord link: https://pastebin.com/jDw2zH4j

Apologies if this issue is already being worked on and/or youre already aware of it.  But all of the bugs seem to revolve sound Summon Gargoyle, Epidemic, Sacrificial Pact and Unholy Assault.  My guess is because all of those skills changed in some way (Gargoyle went baseline, Epidemic moved a spot, Sacrificial Pact is new and Unholy Assault was changed).

### Expected behavior
Just trying to run a basic single target patchwerk sim.  But APL issues are preventing that.

### To Reproduce
I imported my level 60 character from beta with beta gear.  Then plugged in the APL from the link above ^.  But cannot get the simulation to ever complete. 

### Additional information
simc-901-01-win64-e05d32f.7z | 2020-09-06 21:22 | 52M |  

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
Not crashing.

* **simc_gui.simc** file or contents
https://pastebin.com/YTM54GdB  (hopefully I linked to the right thing)

**Comment by scamille** [comment]
Looking at the error message, I would definitely say that your APL does not really work with the current state of the DK module, or might just be incomplete.
```Player T25_Death_Knight_Unholy no variable named 'pooling_for_gargoyle' found```

**Comment by Melekus** [comment]
The Unholy module has not been updated for Shadowlands yet, the APL you found is most likely for research/internal purpous only and will not provide you accurate results yet.

**Comment by scamille** [comment]
I am closing this for now. Feel free to open a new ticket or directly talk with DK devs for other problems.

That said, I would recommend using default_actions=1 for now to run simulations on the shadowlands branch. At least those specs which are in a non-crashing, somewhat developed state should have it running correctly. If you want to use your custom APL and try out things, the burden is somewhat on you to make sure the APL itself works. The wiki pages can help a lot with the if= action expression syntax.
