### ISSUE TITLE
Unable to generate profile

### ISSUE THREAD

**Issue by Tiddlestomp** [simulationcraft/simc#5242]
### Describe the bug
Import message: 
# Unable to generate profile from: 
# Actor 'Donotenter': Action 'memory_of_lucid_dreams': Cannot parse expression from 'active_enemies<5&(buff.icicles.stack<=1|!talent.glacial_spike.enabled)&cooldown.frozen_orb.remains>10&!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.

### Expected behavior
I expected the import to complete successfully as my other toon imports have.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)
830-01 x64bit 7z file

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
The sim doesn't crash...the blue bar fills but then throws the error message

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
There was no simc_report file generated

**Comment by scamille** [comment]
Please try the latest nightly release from http://downloads.simulationcraft.org/?C=M;O=D (you need to extra the 7z archive and then start Simulationcraft.exe from there)

**Comment by scamille** [comment]
Oh and it would also be great if you could share the character you try to import, assuming the problem persists.

**Comment by Tiddlestomp** [comment]
Thanks for the fast follow up.
I downloaded, extracted and ran http://downloads.simulationcraft.org/simc-830-02-win64-2e438b4513.7z
I made no changes to the default settings, just entered the character name in import and pressed import
The blue bar filled and I got the following error text:
```
"statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Actor 'Donotenter': Action 'memory_of_lucid_dreams': Cannot parse expression from 'active_enemies<5&(buff.icicles.stack<=1|!talent.glacial_spike.enabled)&cooldown.frozen_orb.remains>10&!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.
# BCP API: Player 'Donotenter' unable to download item id '9875' at slot waist.
# BCP API: Player 'Donotenter' unable to download item id '14236' at slot feet.
# BCP API: Player 'Donotenter' unable to download item id '9909' at slot wrists.
# BCP API: Player 'Donotenter' unable to download item id '9848' at slot hands.
# BCP API: Player 'Donotenter' unable to download item id '1077' at slot finger1.
# BCP API: Player 'Donotenter' unable to download item id '13093' at slot finger2.

### End simulateText ###"
```
Again, there was no simc_gui.simc file report generated.

The armory record of the character is at:
https://worldofwarcraft.com/en-us/character/us/proudmoore/donotenter

**Comment by scamille** [comment]
Ok so the main problem here is probably that this is a low level character, for which the default Action Priority List import does not work.
While we do not discourage low level sims, they are not really supported either.
Since the GUI unfortunately requires a successful APL import to work.

It really is up to the mage module if they want to fix this. But considering that shadowlands is right around the corner, I think that is unlikely.

**Comment by Tiddlestomp** [comment]
Thanks, that's very clear.
My higher end toons gave no problems.
I'm coming back to Wow after a break and wanted to start off with this lowbie to make the relearning curve a little easier.
Well...I'll persist without the benefit of the sim until he grows up a bit.
Thanks
