### ISSUE TITLE
Error retrieving item from BCP API

### ISSUE THREAD

**Issue by scamille** [simulationcraft/simc#5278]
This ticket is tracking a currently common issue in SimulationCraft.

### Describe the bug
Simulating a character which requires low level items to be downloaded from blizzard community platform (BCP) can sometimes fail.

### Expected behavior
When simulating a character which has items which are not included in the SimulationCraft database, the fallback system of downloading items from BCP API should work and allow simulation.

### Additional information
* SimulationCraft Version: any

-------------------------------------------

It is at this point not clear what exactly causes those intermittent failures.

To mitigate the impact of this, Timewalking gear has been added to the local item database.

**Comment by scamille** [comment]
@navv1234 is this related / the same issue as #2630 ? I have not seen that issue when creating this.

**Comment by navv1234** [comment]
#2630 is old news and not really relevant anymore. Item bonus system replaced such things.

**Comment by scamille** [comment]
Ok. So does this mean that the old issue can be closed or is it still relevant in any way?

**Comment by navv1234** [comment]
I think it can be closed. The data model and associated api endpoints are long gone.

**Comment by tmzhuang** [comment]
I get a similar error loading my character (https://worldofwarcraft.com/en-us/character/us/emerald-dream/kapitol) using this simc:
https://gist.github.com/tmzhuang/06f4f94f508018a4dea7e0fe64c57740

Using most recent build of simc CLI from github. Error shows:
```SimulationCraft 902-01 for World of Warcraft 9.0.2.36294 shadowlands-BETA (git build shadowlands 03b9c1d080)

@@@@
Simulating... ( iterations=1000000, threads=12, target_error=0.050, max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style= )

Error: Actor 'Kapitol': Item 'inactive' Slot 'shoulders': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.
```

**Comment by navv1234** [comment]
We have extended the simulationcraft local item database to contain every single armor and weapon in the client data files. This issue should be resolved now.
