### ISSUE TITLE
"Unable to download JSON" When Importing

### ISSUE THREAD

**Issue by mastapetz** [simulationcraft/simc#5279]
### Describe the bug
I tried several times to import my character with the import tab, I always get the same result in the simulation
# Unable to generate profile from: 
# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/kelthuzad/dabu?namespace=profile-eu&locale=en_GB' 

It works when I copy paste the data from the wow addon

### Expected behavior
It importing my Character like it says it would

### To Reproduce
Open simulation craft, change to import, enter  EU Kel'Thuzad Dabu click import

### Additional information
* SimulationCraft Version (required)
830-01

* **simc_gui.simc** file or contents
doesnt even begin simulating

**Comment by scamille** [comment]
which exact version of SimulationCraft did you download?

**Comment by mastapetz** [comment]
As I wrote in the OP. 830-01

**Comment by scamille** [comment]
for macos? windows? 32bit or 64bit?

I strongly suspect you downloaded the no-networking version. In that version downloads from Blizzard armory are not supported - because there is no networking capability.

**Comment by mastapetz** [comment]
windows 64bit.

The normal one, not the no network. I extra watched for that one.

**Comment by scamille** [comment]
Sorry for suspecting a no-networking version, but we had that problem a few times in the past.

I can import your character fine both with the release and the nightly version.

Since SimC changed the networking library it internally uses between the old release and the current nightly builds, I ask you to please try the latest nightly build from http://downloads.simulationcraft.org/?C=M;O=D and see if that works for you.

**Comment by scamille** [comment]
Did you have any success by using the nightly version?

**Comment by codyf86** [comment]
Compiling the latest source from github on ubuntu 20.10 and building the release version with cmake also provides the same error / results.

**Comment by navv1234** [comment]
Building your own requires you to get your own api key.

**Comment by codyf86** [comment]
Sorry meant to edit my post and accidentally deleted it.

Ubuntu 20.10 compiling the latest source from github and using my own oauth id and secret gives me either
unable to retrieve bearer token or  Unable to authorize: Previous authorization failed

The id and secret are correct and ive repasted them in multiple times.

**Comment by codyf86** [comment]
Using the python requests library I can successfully return an access token with my provided client id and secret, so I know its not an issue with the client I setup in battle.net

**Comment by navv1234** [comment]
No clue on what could be the issue. I just tried on my macos using the bog standard .simc-apikey file and it seems to be ok. How are you invoking simc, using apikey= option or something else?

**Comment by codyf86** [comment]
I've only tried putting the api id and secret in the gui, I can try just using the command line also and see what happens.

Here is the actual error now, if it fails to authorize once it will fail for awhile saying previous authorization failed, but the actual error:
# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/illidan/aaradone?namespace=profile-us&locale=en_US'.: Unable to authorize: Unable to fetch bearer token from https://us.battle.net/oauth/token, response=401, error=, result=

I know that with requests I had to specify grant_type when getting the auth token. I'll look at the actual code and see how it is getting it, but I can do the follow in python and get the token and a characters request json.

        with open('PyConnect.json') as config_file:
            self.config = json.load(config_file)
            self.wow_id = self.config['wow']['id']
            self.wow_secret = self.config['wow']['secret']

        r = requests.get('https://us.battle.net/oauth/token',
            auth=(self.wow_id, self.wow_secret),
                    params=('grant_type=client_credentials'))

        r = requests.get('https://us.api.blizzard.com/profile/wow/character'
                '/illidan/aaradin?namespace=profile-us&locale=en_US',
                        params=('access_token=self.token'))

I can look through the wiki also but is there a way to turn more logging on when building it?

**Comment by scamille** [comment]
Can you try building shadowlands and importing a character there?

I think some http calls might give you more extensive error messages there.

**Comment by scamille** [comment]
Did you have any luck with a self-built shadowlands version?

**Comment by codyf86** [comment]
The only version I have ever used was the shadow lands branch built on a Linux box I'll check again when I get home. It worked one time in the past then stopped working again. It's been a couple weeks so I'll try again when I get home.

**Comment by codyf86** [comment]
Still does not work on the latest shadowlands branch built on linux.

# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/illidan/aaradin?namespace=profile-us&locale=en_US'.: Unable to authorize: Unable to fetch bearer token from https://us.battle.net/oauth/token, response=401, error=, result=

The way it's handling getting an API key and bearer token is wrong somehow.  I pasted an example of how to successfully grab data from the Blizzard API above (Albeit using Python), but it's still basically the same.  Need to make sure grant_type is specified.

**Comment by navv1234** [comment]
You can always enable curl debug for simc and recompile, it should spit out curl internal stuff to stderr, which should get you a hint on what exactly is going wrong. You can enable it by recompiling with -DCURL_DEBUG=1.

Locally, it's more or less impossible to debug currently, as I have never seen the client credentials flow in simc fail to authorize (get an access token) as long as the client id and secret are correct.

**Comment by codyf86** [comment]
For sure ill recompile it right now. I readded the id and token to make sure I wasn't messing it up.  Give me a few and ill see what it says.

Also just as a test made a second ID on the blizzard API to make sure it wasn't being weird from using it from other things also and that is not it...a few minutes and ill post the output.

**Comment by codyf86** [comment]
hmmm?

Trying to build it as DEBUG in general though to see if it outputs the same.

 >Manually-specified variables were not used by the project:
>
>   CURL_DEBUG

**Comment by navv1234** [comment]
Unsure how to pass it to qmake, i just compile with the makefile (CURL_DEBUG=1 make -C engine debug install), or so.

**Comment by codyf86** [comment]
Think I got it, it's building.

**Comment by codyf86** [comment]
*   Trying 137.221.106.102:443...
* TCP_NODELAY set
* Connected to us.battle.net (137.221.106.102) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=Irvine; O=Blizzard Entertainment, Inc.; CN=*.battle.net
*  start date: Jul 30 00:00:00 2020 GMT
*  expire date: Aug  3 12:00:00 2022 GMT
*  subjectAltName: host "us.battle.net" matched cert's "*.battle.net"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> POST /oauth/token HTTP/1.1
Host: us.battle.net
User-Agent: Simulationcraft+CURL/902-01
Accept: */*
Accept-Encoding: deflate, gzip, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 29

* upload completely sent off: 29 out of 29 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Fri, 06 Nov 2020 17:02:03 GMT
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Retry-After: 600
< Cache-Control: no-store
< Pragma: no-cache
< WWW-Authenticate: Bearer realm="Blizzard OAuth", error="unauthorized", error_description="An Authentication object was not found in the SecurityContext"
< Transfer-Encoding: chunked
< Content-Type: application/json;charset=UTF-8
< 
* Connection #0 to host us.battle.net left intact
Error: Option 'armory' with value 'us,illidan,aaradin': BCP API: Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/illidan/aaradin?namespace=profile-us&locale=en_US'.: Unable to authorize: Unable to fetch bearer token from https://us.battle.net/oauth/token, response=401, error=, result=

**Comment by codyf86** [comment]
It's not passing the access token for some reason, even when you use the GUI and put your api info in the boxes at least on linux it seems.

**Comment by navv1234** [comment]
Unless you removed some lines from that, it looks like `Server auth using Basic with user '<client id>'` is missing from the curl output. In turn, it's also missing `Authorization: Basic <base64 output>` from the post.

Were you doing this with CLI or GUI? Was your apikey contents (`<client id>:<client secret>`) with apikey option, $HOME/.simc_apikey file?

**Comment by elegos** [comment]
It seems that on Linux the GUI API information is stored in `~/.config/SimulationCraft/SimulationCraft.ini`, while it will attempt to access `~/.simc_apikey` during the import.
