### ISSUE TITLE
[Arcane Mage] Assertion fails when simming Combat Meditation

### ISSUE THREAD

**Issue by Sergrand1** [simulationcraft/simc#5296]
### Describe the bug
Attempting to sim the Pelagos soulbind's Combat Meditation trait causes an assertion in player_stat_cache.cpp to fail. Unsure if this is actually specific to arcane, but I tried a few other class/specs without any issues.

Error printed by simcraft: 
"Assertion failed: _mastery == player->composite_mastery(), file player_stat_cache.cpp, line 393"

### To Reproduce
Build simcraft in debug mode and run an arcane mage simulation that has kyrian selected as its covenant, combat_meditation selected as a soulbind, and uses the radiant_spark action.

### Additional information
* SimulationCraft Version (required)
901-01

**Comment by scamille** [comment]
cc @simulationcraft/mage

**Comment by Dorovon** [comment]
I think this should be fixed now. The problem was that maximum mana was recalculated for Arcane's mastery when the cache was invalidated, but that was happening before the buff actually expired.
