### ISSUE TITLE
DoT Extension of Void Bolt and partial ticks

### ISSUE THREAD

**Issue by kaesebrezen** [simulationcraft/simc#5319]
### Describe the bug
If Void Bolt extends a DoT that has only a partial tick remaining, the next tick of theDoT will be a partial tick, while it should be a full tick.

21.148 Dot vampiric_touch ticks (8 of 9). last_start=1.244, duration=21.000 time_to_tick=2.488
21.148 Player 'T25_Priest_Shadow' tick amount for Action vampiric_touch on Player 'Fluffy_Pillow': amount=823.7068797018447 initial_amount=411.85343985092237 base=0.0 bonus=0.0 s_mod=0.27 s_power=1176.0 a_mod=0.0 a_power=0.0 mult=1.297094481767833, tick_mult=1.0
21.148 New DoT Tick Event: Dot vampiric_touch tick 9-of9 time_to_tick=1.096
21.377 Player result for Action void_bolt_extension is hit.
21.377 Player extends duration of Dot vampiric_touch on Player 'Fluffy_Pillow' by 3.000 second(s).
21.377 Rescheduling event DoT End(10) from 22.244 to 25.244
**22.244 Dot vampiric_touch ticks (9 of 9). last_start=1.244, duration=24.000 time_to_tick=1.096
22.244 Player tick amount for Action vampiric_touch on Player 'Fluffy_Pillow': amount=362.8547990969541  <- this tick is a partial tick and should not happen at all**
24.732 Dot vampiric_touch ticks (10 of 11). last_start=1.244, duration=24.000 time_to_tick=2.488
24.732 Player tick amount for Action vampiric_touch on Player 'Fluffy_Pillow': amount=411.85343985092237 
25.244 Dot vampiric_touch ticks (11 of 11). last_start=1.244, duration=24.000 time_to_tick=0.512
25.244 Player 'T25_Priest_Shadow' tick amount for Action vampiric_touch on Player 'Fluffy_Pillow': amount=84.75440562848563

The extend_duration() function used to extend DoTs is incapable of rescheduling partial ticks, whereas it should to properly mirror ingame behaviour. ( it might extend past Void Bolt to a issue with the extend function)

### Expected behavior
Following log:https://www.warcraftlogs.com/reports/mG2H9CNyjdLMQV8t/#fight=2&source=17&type=damage-done&view=events

My VT should a total of 9 ticks, 8 full damage, the 9th being a partial (at 150 danage without extension)

At 22.559 my Voidbolt hit the target after the 8th VT tick, the next tick will happen at 24.667 seconds as a full tick.
At 26.334 seconds the last partial tick will happen with 264 damage (more then the value of 150 at no extension)

### To Reproduce
that's the apl i used:

actions.main+=/vampiric_touch,if=!dot.vampiric_touch.ticking
actions.main+=/void_eruption,if=dot.vampiric_touch.ticks_remain=3
actions.main+=/void_bolt,if=dot.vampiric_touch.ticks_remain=1,cooldown=500

with the following stats:
gear_intellect=726
gear_haste_rating=678
gear_mastery_rating=92
gear_versatility_rating=570

### Additional information
* SimulationCraft Version (shadowlands newest nightly build)

**Comment by scamille** [comment]
As @vituscze mentioned in discord, buff_t::refresh takes care of partial ticks but buff_t:extend_duration does not. So that needs to be adjusted somehow.
