### ISSUE TITLE
Windwalker's profile question on Opener

### ISSUE THREAD

**Issue by iPisces77** [simulationcraft/simc#5443]
When I use this profile to simulate, the following sequence of actions occurs
![Snipaste_2020-10-22_10-18-20](https://user-images.githubusercontent.com/39837211/96816404-f3c9e980-144f-11eb-8aea-b6b8aa10d39a.png)
It uses Tiger Palm twice, then expel_harm.
Mastery of windwalker requires us to use a different skill than the last one.
I tested it in the game, using Hit Combo, using Tiger Palm, and then using Expel Harm, and it was able to provide the buff of the combo, stacking the buff twice!
Using tiger palm then using expel_harm,then using tiger palm seems to be a good option

**Comment by iPisces77** [comment]
# Opener
actions.opener=fist_of_the_white_tiger,target_if=min:debuff.mark_of_the_crane.remains
actions.opener+=/expel_harm,if=talent.chi_burst.enabled
actions.opener+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&chi.max-chi>=2
actions.opener+=/expel_harm,if=chi.max-chi=3|chi.max-chi=1
actions.opener+=/flying_serpent_kick,if=talent.hit_combo.enabled
actions.opener+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=chi.max-chi>=2

**Comment by scamille** [comment]
Can you please tell us which exact version of SimulationCraft you are using?

**Comment by scamille** [comment]
cc @simulationcraft/monk

**Comment by iPisces77** [comment]
Just the nightly version of simc,simc-901-01-win64-65dbefc

**Comment by Hinalover** [comment]
@iPisces77 the other day I posted an update to the opener. Can you see if this is still happening?

**Comment by iPisces77** [comment]
All right, problem solved. The same problem won't happen again.
