### ISSUE TITLE
 Item 'inactive' Slot 'waist error

### ISSUE THREAD

**Issue by kdulep** [simulationcraft/simc#5449]
SimulationCraft 902-01 for World of Warcraft 9.0.2.36267 shadowlands-BETA (hotfix 2020-10-17/36267, git build HEAD e8f1723ec9)
Simulating... ( iterations=100000, threads=32, target_error=0.050, max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )
Error: Actor 'kahunanui': Item 'inactive' Slot 'waist': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.

both for in from armory and app
i even bought from AH new waist

EU/Kazzak/ kahunanui

**Comment by scamille** [comment]
This is a manifestation of the known issue #5278 , I think. It means that SimC is not having the item in your waist slot in its internal database, and tries to download it from online sources, which fails.
That has been broken for a while, but is hard to fix.

Can you post the waist= line you get from the /simc addon, to document here which item is causing it before it is changed on your character?

cc @navv1234

**Comment by kdulep** [comment]
there was also blue belt i forgot that didnt work too
https://www.wowhead.com/item=9901/jazeraint-belt
[Jazeraint Belt of the Quickblade]

[paste with simc data](https://pastebin.com/9YHAMa24)

**Comment by Point01IV** [comment]
Hello, 

I'm new to SimCraft, but I'm experiencing the same issue, too.  Here is the waist line that you are requesting.  PLease be gentle on me - still trying to learn everything with it.  I'll get you any other data you need to know!

waist=,id=27768,gem_id=30583,bonus_id=4109,drop_level=27

Thanks!

Full data from log:

SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Frozenßooger': Item 'inactive' Slot 'waist': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
# SimulationCraft 902-01 for World of Warcraft 9.0.2.36294 shadowlands-BETA (git build shadowlands 03b9c1d)
* Category: Simulation runtime error
* Error: Initializing: Actor 'Frozenßooger': Item 'inactive' Slot 'waist': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.

## All options used for simulation:
``` ini
### SimulationCraft 902-01 for World of Warcraft 9.0.2.36294 shadowlands-BETA (wow build 36294, git build shadowlands 03b9c1d)  ###
### Using QT 5.12.9 with WebEngine ###

### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead/shadowlandshead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Frozenßooger - Frost - 2020-10-25 02:53 - US/Zul'jin
# SimC Addon 9.0.1-02
# Requires SimulationCraft 901-01 or newer

mage="Frozenßooger"
level=50
race=human
region=us
server=zuljin
role=spell
professions=alchemy=27/herbalism=38
talents=2332211
spec=frost

head=,id=57263,bonus_id=6691,drop_level=41
neck=,id=39483,enchant_id=5317,bonus_id=3769,drop_level=30
shoulder=,id=126992,bonus_id=1690/3392/3408
back=,id=46042,enchant_id=4087,gem_id=28123
chest=,id=39337,enchant_id=4419,bonus_id=3690,drop_level=30
shirt=,id=3428
tabard=,id=65905
wrist=,id=57308,bonus_id=3631,drop_level=49
hands=,id=37941,enchant_id=4431,bonus_id=3687,drop_level=30
waist=,id=27768,gem_id=30583,bonus_id=4109,drop_level=27
legs=,id=57289,bonus_id=3631,drop_level=49
feet=,id=159188,bonus_id=6654/43/1695,drop_level=50
finger1=,id=143903,bonus_id=6423,drop_level=47
finger2=,id=143902,bonus_id=6423,drop_level=46
trinket1=,id=47041
trinket2=,id=40682
main_hand=,id=55444,bonus_id=6655/1684,drop_level=47

### Gear from Bags
#
# Darkmoon Fishing Cap (1)
# head=,id=93732
#
# Argent Crusader's Tabard (1)
# tabard=,id=46874
#
# Seal of the Regal Loa (72)
# finger1=,id=159458,bonus_id=4777/6516/6515/1485/4785
#
# Mercurial Alchemist Stone (35)
# trinket1=,id=44322
#
# Mastercraft Kalu'ak Fishing Pole (35)
# main_hand=,id=44050

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment]
Thanks for the information.

I can't really promise you a fast resolution, but I am hopeful that this will be fixed at some point. For now you are best off trying to simulate your character without the problematic items.

**Comment by Point01IV** [comment]
It is all good.  I managed to find a belt piece that was a major upgrade
and the sims worked fine.  Totally understand this is prepatch and all.
Thanks!

**Comment by navv1234** [comment]
We have extended the simulationcraft local item database to contain every single armor and weapon in the client data files. This issue should be resolved now.

**Comment by Point01IV** [comment]
Ok thank you!!
