### ISSUE TITLE
SimC VS Builds are not uniform

### ISSUE THREAD

**Issue by seanpeters86** [simulationcraft/simc#5458]
### Describe the bug
When building on VS 2019 we do not copy over a `simc.exe` into the root directory, like we do with vs2017. Instead we just leave it in `x64\Release\simc_vs2019.exe`. 

### Expected behavior
I'd expect both solutions to output a `simc.exe` in the root directory of the project. This is used for various things like the SpellDataDump scripts that expect this to be here.

### To Reproduce
Build the solution with `simc_vs2019.sln`

### Additional Info
I tried fixing this by simply adding `<Import Project="OutputDirectories.props" />` to the build solution, but this breaks the CI build: 

```
Run vs\x64\Debug-NoNetworking\simc_vs2019.exe $env:SIMC_PROFILE iterations=5 output=nul html=nul json2=nul cleanup_threads=1
vs\x64\Debug-NoNetworking\simc_vs2019.exe: D:\a\_temp\5c1f50af-75ab-4b31-9f32-cee96865305e.ps1:2
Line |
   2 |  vs\x64\Debug-NoNetworking\simc_vs2019.exe $env:SIMC_PROFILE iteration …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The module 'vs' could not be loaded. For more information, run 'Import-Module vs'.

Error: Process completed with exit code 1.
```

This should also rename the project to match, as the 2017 one is just `simc` but the 2019 one is `simc_vs2019.exe`.

**Comment by scamille** [comment]
As mentioned on Discord, my intention when setting up the VS2019 solution was to be "not-special" by default, so I intentionally left the output at its default path that VS puts it.
That also gave the benefit to having things contained inside the vs folder for the appropriate solution.

But if we rely on simc.exe being in the main folder, then it does make sense to adjust it.
