### ISSUE TITLE
simulationcraft does not start

### ISSUE THREAD

**Issue by gopognom** [simulationcraft/simc#5466]
I have win 10 x64
simulationcraft win64 does not start. 
Visual C++ Redistributable installed
trying other versions. doesnt work

**Comment by scamille** [comment]
Which exact version did you download from where?
What application are you trying to start? simc.exe or Simulationcraft.exe?
What error message do you get when it is not starting?

**Comment by gopognom** [comment]
1. simc-902-01-win64, also tried to start other versions 9+
2. both of them
3. Nothing happened

**Comment by gopognom** [comment]
> Which exact version did you download from where?
> What application are you trying to start? simc.exe or Simulationcraft.exe?
> What error message do you get when it is not starting?

simc-902-01-win64, also tried to start other versions 9+
both of them
Nothing happened

**Comment by scamille** [comment]
That sounds strange, Simulationcraft.exe should definitely show you a graphical user interface.
Can you try updating your graphics drivers to the latest version?
Which operating system are you using?

**Comment by gopognom** [comment]
> That sounds strange, Simulationcraft.exe should definitely show you a graphical user interface.
> Can you try updating your graphics drivers to the latest version?
> Which operating system are you using?

I use win10x64. All drivers and updates are installed

**Comment by Krovaks** [comment]
Same issue.
Try to download and run 901/902 x32/64 and nothing. simc.exe opens prompt, simulationcraft.exe do nothing(((
win10x64 pro v1909 build 18363.1139
upd. my vcr: https://i.imgur.com/v7J9kmI.png

**Comment by scamille** [comment]
Can you try installing the latest Visual C++ Redistributable from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ?
That should in theory be included with any modern, updated version of windows, but it can't hurt just to make sure that this is not missing here.

simc.exe can only be used from command line (cmd or PowerShell) - it will instantly close again if you start it from the desktop.

SimulationCraft.exe should definitely show you the graphical user interface.

There have always been rare problems with the QT framework in the past. It is often related to graphic drivers, but it is often hard to find the root cause. And there is often not that much help we can provide with resolving the issue, unfortunately.

As an alternative, you can always create SimulationCraft throught the command line interface (simc.exe), or try using Raidbots.com

**Comment by Krovaks** [comment]
Reinstall vcr didn't lead to changes((
What about command line?

**Comment by evgeniygrim** [comment]
> Reinstall vcr didn't lead to changes((
> What about command line?

i have the same problem (((

OS: win10x64 home v1909 build 18363.1139,
vcr: like Krovaks screenshot
video driver : GeFocre GRD 457.30

**Comment by scamille** [comment]
Could this be related to antivirus preventing SimulationCraft.exe from running?

@Krovaks simc.exe is the command line version of SimulationCraft. You use it in a terminal (eg. cmd.exe) and can run your simulations through it. See https://github.com/simulationcraft/simc/wiki/StartersGuide#the-command-line-client

**Comment by Krovaks** [comment]
I don't think so. I use only default windows guard.

**Comment by ar0green** [comment]
> Could this be related to antivirus preventing SimulationCraft.exe from running?
> 
> @Krovaks simc.exe is the command line version of SimulationCraft. You use it in a terminal (eg. cmd.exe) and can run your simulations through it. See https://github.com/simulationcraft/simc/wiki/StartersGuide#the-command-line-client

i have the same problem
I don't use any antivirus programs. And Defualt Windows guard is disabled. All drivers are up to date.

**Comment by serrufs** [comment]
There used to be a "nonetwork" assembly, but now new ones do not start in win 8.1 x64

**Comment by Noketchap** [comment]
Same problem. "Code execution cannot proceed because VCRUNTIME140_1.dll was not found" 
Op system:  win.10 x64 
video driver : GeFocre GRD 457.51

**Comment by scamille** [comment]
@Noketchap See #5625 for how to resolve the problem.

**Comment by scamille** [comment]
@gopognom Please try again tomorrow with the next nightly build which will include #5595 . Thanks @suujonH for hopefully fixing this.

**Comment by Krovaks** [comment]
@scamille Can you check these dumps? 

[simc_dump_12072020.zip](https://github.com/simulationcraft/simc/files/5651526/simc_dump_12072020.zip)

**Comment by scamille** [comment]
I don't really know how to do much with this, sorry.

**Comment by Krovaks** [comment]
Ok, i tried downloading the nightly version, it works.
@gopognom, https://github.com/simulationcraft/simc-publish/actions/runs/405753326

**Comment by scamille** [comment]
Great to hear. #5595 seems to have resolved this problem sucecssfully.
