### ISSUE TITLE
Legion Artifact weapons and Crusader enchant not supported.

### ISSUE THREAD

**Issue by zoke21** [simulationcraft/simc#5477]
1, when i try to set my enchant as crusader on my unholy dk it acts like i have no enchants, but rune of the fallen crusader works fine.
2, how do i make my artifact weapon correctly upscale? (i have 2 relics in it and its ilvl 43 now not 20) 

edit:  apparently you can just add ",ilevel=x" for the second one.  turns out crusader just doesnt  work yet

**Comment by scamille** [comment]
What artifact weapon are you talking about exactly?

Can you post some SimC profile inputs here for both problems, so it can be replicated properly?

cc @simulationcraft/death-knight

**Comment by Melekus** [comment]
1. Unless I'm mistaken, the crusader enchant is an old content enchant and even though it might be a competitive option on prepatch, it's unlikely that simulationcraft will (re-?) implement it just for a few weeks. Runeforges on the other hand are a core mechanic of the death knight class year after year and we do our best to keep them supported.

2. Artifact weapons and relics from Legion are also old content, and I don't think anyone went ahead and checked that we still support them after the shadowlands level and ilevel squish.

**Comment by zoke21** [comment]
yeah i figured out how to write in  crusader myself, and also how to  alter my artifacts item levels

**Comment by scamille** [comment]
I am closing this, since the question is answered.

If you want to have this supported, we gladly accept pull requests. Beware that simulating low level characters probably needs a lot more work than just supporting those older items. (Mainly a good action priority list)
