### ISSUE TITLE
SimC build simc-902-01-win64-4704e59 crashes

### ISSUE THREAD

**Issue by SaxSeven** [simulationcraft/simc#5488]
Simc crashes after starting the simulation without any error.

i added the simc_gui.simc file, but changed the suffix form .simc to .txt

SimC build simc-902-01-win64-4704e59

**Comment by vituscze** [comment]
Link to the simc_gui file: https://github.com/simulationcraft/simc/files/5477489/simc_gui.txt

**Comment by vituscze** [comment]
Noticed there's ptr=1 in the simc_gui file. That's almost surely what's causing the issues. Can you try simming with the live option?

**Comment by SaxSeven** [comment]
exact same behaviour

**Comment by SaxSeven** [comment]
[simc_gui (2).txt](https://github.com/simulationcraft/simc/files/5477605/simc_gui.2.txt)

**Comment by vituscze** [comment]
Hm, that simc_gui still has the ptr=1 line

**Comment by SaxSeven** [comment]
right....my error....doing fine now

**Comment by vituscze** [comment]
PTR is now disabled so this won't happen.
