### ISSUE TITLE
Error message on daily build:  This app can't run on your PC

### ISSUE THREAD

**Issue by StrykerJC** [simulationcraft/simc#5542]
I've successfully installed and run previous versions of Simulationcraft, but when trying to run one of the daily builds (901-01-win64) I get the error message that This app can't run on your PC (see attachment).

I have successfully run the 64-bit versions of 735, 801, 810, 820, and 830 with no problems.  902, however, only returns the error message.

Any suggestions?

![Capture](https://user-images.githubusercontent.com/74741623/99727532-bd4ab300-2a7d-11eb-9229-c88dc74cfbe8.JPG)

**Comment by navv1234** [comment]
There should not be anything fundamentally different with 830 or 902 really that would cause it to act that way.

**Comment by StrykerJC** [comment]
> There should not be anything fundamentally different with 830 or 902 really that would cause it to act that way.

I agree, that's why I'm puzzled.  I even tried the 32-bit version, got the same result.  The older versions run with no issues at all.

**Comment by scamille** [comment]
Works fine here.

What is your operating system, with what exact version?

**Comment by StrykerJC** [comment]
> Works fine here.
> 
> What is your operating system, with what exact version?

Windows 10 Pro (64-bit), build 19041

**Comment by StrykerJC** [comment]
I got it figured out.  I have been using TugZIP for years as my default unzip application.  I switched to 7-Zip just to see if it made a difference.  It did. :)
