### ISSUE TITLE
pet.fiend.up/down is inconsistent with pet.X.up/down for other specializations.

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#5547]
### Describe the bug
In the Shadow Priest APL, `pet.fiend.down` is used to indicate that your Shadowfiend/Mindbender is active (used in the conditions for Void Eruption).  For other classes/specializations, `pet.X.down` would mean the pet is not active.

### Expected behavior
`pet.fiend.X` should be consistent with other historical simc behavior.  The Wiki actually only cites `active` and `remains` as pet properties, so I can't point to a `pet.fiend.up` example, but one would probably expect `pet.fiend.active` to align with `pet.fiend.up` rather than `pet.fiend.down`.  (I could be incorrect.)

### To Reproduce
Sim:  https://www.raidbots.com/simbot/report/fh5nj2DQ8eWaxx4HW5ZT8c/simc

Opener portion: casts Mindbender, then Mind Blast, then Mind Flay, then Void Eruption (VE is 3.5 seconds after Mindbender, so we know Mindbender is active).

![image](https://user-images.githubusercontent.com/9438134/99878608-c1d5af80-2bd4-11eb-83b7-6b8ddbbb0bf8.png)

The conditions for `F` (VE) include a check for `pet.fiend.down`, with the comment indicating that this is requiring Shadowfiend/Mindbender to be on cooldown.  At the point Void Eruption is active, Mindbender is up and `pet.fiend.up` is `0`.

![image](https://user-images.githubusercontent.com/9438134/99878631-ea5da980-2bd4-11eb-804e-cbc166757123.png)

### Additional information
* 9.0.2.36671 Live (hotfix 2020-11-20/36671, git build eccfe72b6c)

* **simc_gui.simc** file or contents

Not included; ran simc via Raidbots (sorry!).

**Comment by Saeldur** [comment]
The observed behavior is correct to how it is intended.
`pet.fiend.down` is referring to the pet being on cooldown and was created to simplify APL because we have different pet names depending on talents.
I agree the name is potentially misleading and will be changing it in a commit.
