### ISSUE TITLE
Rogue_Subtlety APL animacharged_cp bug

### ISSUE THREAD

**Issue by leifan8440** [simulationcraft/simc#5570]
call_action_list,name=finish,if=combo_points=animacharged_cp

"call_action_list" should be change to  "run_action_list"
because eviscerate.cost > backstab.cost

**Comment by scamille** [comment]
cc @simulationcraft/rogue

**Comment by Mystler** [comment]
The reasoning is wrong. Eviscerate does not cost more than Backstab and there is no such bug. We could discuss using run over call because of what the intent may be, in fact, we've started discussing this. Nevertheless, the issue does not exist, it makes zero difference.
