### ISSUE TITLE
Paladin default flask/food/potion/rune not updated for Shadowlands

### ISSUE THREAD

**Issue by cremor** [simulationcraft/simc#5575]
### Describe the bug
Paladin specs don't have a Shadowlands flask/food/potion/rune defined to be used as default. Seems like this leads to them not using any flask/food/potion/rune at all.

### Expected behavior
Paladin specs should use the optimum flask/food/potion/rune by default.

### To Reproduce
Run a Paladin sim on Raidbots with "SimC Default" settings and check the used flask/food/potion/rune.

Also see the code here:
https://github.com/simulationcraft/simc/blob/37ff6763f9e5d0d1ae25b8a10e91bfcb41138450/engine/class_modules/paladin/sc_paladin.cpp#L2074-L2198

### Additional information
* SimulationCraft Version (required)
Nightly (902-01)
SimC Git Hash d891189322

* **simc_gui.simc** file or contents
https://pastebin.com/p83SCXPi
https://www.raidbots.com/simbot/report/5eC3yoAP5pwZXoMSJc7dKG/simc

**Comment by scamille** [comment]
cc @simulationcraft/paladin

**Comment by Melekus** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/034dbff5d7bb416f746a96725fd1084786ca206c#diff-4e60d93aeb4291792cfe49964b277a556294d53fe32fc857922934e962e6828f (ret) and https://github.com/simulationcraft/simc/commit/31c563b1f2fbed61f169cd3211331a752deec5da (prot)
