### ISSUE TITLE
Simulation prot pala bug with night fae.

### ISSUE THREAD

**Issue by FenrisOxy** [simulationcraft/simc#5596]
Hello, when I sim using night fae paladin prot, it's not using the blessings at all and then do not gain the 8 mastery bonus stacks from niya.

Thank you.

**Comment by scamille** [comment]
cc @simulationcraft/paladin

**Comment by scamille** [comment]
@mserrano is this taken care of with the blessing of seasons PR and other changes?

**Comment by mserrano** [comment]
I believe so.
