### ISSUE TITLE
[Ret] Sephuz Proclamation Buff not considered

### ISSUE THREAD

**Issue by Rushhourzet** [simulationcraft/simc#5619]
### Describe the bug
Sephuz Proclamation isnt considered while calculating DPS with it. Or atleast it doesnt show up

### Expected behavior
Sephuz Buff to show up with a uptime of around ~40%+. You can even trigger it on stun immune targets

### To Reproduce
Simming someone with Sephuz Proclamation Legendary

### Additional information
* SimulationCraft Version: 902-01

* **simc_gui.simc** file or contents
[Sephuz_sim_ret_902_01.zip](https://github.com/simulationcraft/simc/files/5645034/Sephuz_sim_ret_902_01.zip)

**Comment by scamille** [comment]
cc @simulationcraft/paladin

**Comment by cremor** [comment]
> You can even trigger it on stun immune targets

Seems like this was fixed in yesterdays hotfixes:

> Fixed an issue with Sephuz's Proclamation (Legendary Effect) granting its buff regardless of whether the crowd controlling ability was successful or not.

**Comment by mserrano** [comment]
Sounds like this proccing reliably on stun-immune targets was a bug, so closing this
