### ISSUE TITLE
mr

### ISSUE THREAD

**Issue by silverfoxray** [simulationcraft/simc#5624]
### Describe the bug
The report alwasys said "BCP API: Player 'Silverfoxray' unable to download item id '178759' at slot head."
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by vituscze** [comment]
What is your simc version? This item works just fine on my end.

**Comment by silverfoxray** [comment]
Hi,

Every time when I try to simulate the system said
[cid:18EA9AFB-9627-4167-AE2D-9F755C9740D9-L0-001]
And I can’t use the import function to import my character.
My character is
EU
Realm: Twisting Nether
Name: Silverfoxray


Thanks
Ray

On 5 Dec 2020, at 11:51, Vít Šefl <notifications@github.com> wrote:

﻿

What is your simc version? This item works just fine on my end.

**Comment by scamille** [comment]
Please download the latest nightly from http://downloads.simulationcraft.org/nightly/ and try again.

I strongly suspect that this problem occured with a 901-01 version of SimulationCraft, which did not yet have the mentioned item included.
