### ISSUE TITLE
VCRUNTIME140_1.DLL not found

### ISSUE THREAD

**Issue by Ruski837** [simulationcraft/simc#5625]
Your most recent nightly build is missing this file and cannot compile or execute.

**Comment by scamille** [comment]
Please download an install it from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I'll take a look that we can get it back into the executable or at least show some information about this somewhere.

**Comment by Ruski837** [comment]
Thank you!!!!

**Comment by Ruski837** [comment]
So I downloaded this and still getting the same error
https://support.microsoft.com/en-us/help/4032938/update-for-visual-c-2013-redistributable-package

**Comment by scamille** [comment]
Download from the **Visual Studio 2015, 2017 and 2019** section the vc_redist.x64.exe

That goes together with **simc-902-01-win64-.7z** from http://downloads.simulationcraft.org/nightly/?C=M;O=D

**Comment by scamille** [comment]
The correct vc_redist.exe is now included in the published nightly files.
