### ISSUE TITLE
Gem values need updating after recent nerf.

### ISSUE THREAD

**Issue by LavingRunatic** [simulationcraft/simc#5632]
With recent nerfs to the main stats provided by Leviathan & Kraken's Eye gems from +18 &+12 respectively to +7 &+6, it would be nice to see this updated so it's not throwing off the numbers.

**Comment by vituscze** [comment]
Looks fine to me
![image](https://user-images.githubusercontent.com/4149104/101293960-721df780-3814-11eb-9ad7-670abb4efbbc.png)
