### ISSUE TITLE
[Fire mage] Possible optimizations for combustion casting criteria

### ISSUE THREAD

**Issue by Caffretro** [simulationcraft/simc#5635]
### Is your feature request related to a problem? Please describe.

The AOE and Single target rotations for fire mage's combustion are put together under combustion_phase. However, the criteria for activating combustion requires a casting scorch, fireball, pyroblast, or a landing meteor.  As the last AND parenthesis in the if statement specified (in line 367 of simc/engine/class_modules/apl/mage.cpp, commit ba46262):
 `combustion_phase->add_action( "combustion,use_off_gcd=1,use_while_casting=1,if=buff.combustion.down&(!runeforge.disciplinary_command|buff.disciplinary_command.up|buff.disciplinary_command_frost.up&talent.rune_of_power&cooldown.buff_disciplinary_command.ready)&(!runeforge.grisly_icicle|debuff.grisly_icicle.up)&(action.meteor.in_flight&action.meteor.in_flight_remains<=0.6|action.scorch.executing&action.scorch.execute_remains<0.6|action.fireball.executing&action.fireball.execute_remains<0.6|action.pyroblast.executing&action.pyroblast.execute_remains<0.6)" );`

Since kindling is much more prevalent (with night fae) in the current meta, a casting scorch/fireball/pyroblast is necessary for combustion activation under this logic. 

However, one of the combustion AOE rotations starts directly with a phoenix flame, fire blast, and combust, which doesn't involve the precast of any one of the three spells mentioned above. Another rotation involves the precasting of a flamestrike, and activate combust at the end of casting, which is also not covered in this version.

### Describe the solution you'd like
I guess adding the casting of flamestrike to the last parenthesis would be very helpful since precasting of flamestrike can add one more 100% crit flametrike to the very beginning of the combustion phase. I'm not sure if the precasting of single-target spells would be nicer in the acquiring of hot streak, but starting with a phoenix and combust before it hits would give the same result in hot streak acquiring. 

Although we are channeling shifting power in AOE combustion rotation, I'm not sure if there will be enough time to charge one more stack of phoenix if all three stacks are used before channeling shifting power. I guess the current rotation of starting conbustion with a non-phoenix spell is also competitive. If there is a phoenix cast in the later part of combustion, more ignite damage will be spread, which I assume is better to treat phoenix as a starter in the beginning for acquiring hot streak.

Though, channeling flamestrike would be a much better precast than single target spells in AOE combats.

**Comment by Dorovon** [comment]
Yeah, the Fire APL isn't fully optimized for AoE yet. I think that starting with PF or Flamestrike before Combustion is probably the best option starting at some target threshold and also potentially depending on haste. Additionally, Shifting Power likely needs to be saved for Combustion when Combustion will be up soon, which doesn't happen in all cases, especially with certain on-use trinkets.

I'm not sure if I'll have time sooner, but sometime in the next few weeks I plan to fix this if nobody else has by then. So far most of my time working on the Fire APL has been spent making sure the ST rotation is fully ready for raids.

**Comment by Dorovon** [comment]
Okay, that was quicker than I thought. This is fixed in https://github.com/simulationcraft/simc/commit/fc49567fd4d78eb28ead81dd39a6061c18b3f95a. Using PF was a DPS loss over Fireball, mainly because there isn't much of a window to let the GCD finish before pressing Combustion, but a hardcast Flamestrike was a big gain.
