### ISSUE TITLE
Discipline Priest Bugs and Implementation problems with DPS sims

### ISSUE THREAD

**Issue by seanpeters86** [simulationcraft/simc#5640]
### Describe the bug
Discipline Priest is far from being complete, even in terms of just a raw DPS sim. Issues aside that simming for pure DPS is different than a hybrid sim (which is currently an empty APL basically), things are not complete.

### Expected behavior
If Discipline sims are to be enabled, they should be as accurate as possible. The following is a list of things that are currently NYI.

- [ ] Holy Nova refactor (extra proc at 3+ targets and sqrt scaling past 5)
- [ ] Twist of Fate (would need some sort of configurable uptime and a healing spell in the apl to proc this)
- [ ] Mind Sear in APL? + make sure the damage matches
- [x] Verify Shadow Covenant is affecting the correct spells (and not trinkets)
- [x] Make sure Schism does not affect trinket damage
- [ ] Purge the wicked and SW:P helper condition. Right now we need two apl lines for the same thing, should change this to make the APL easier to read/write
- [ ] Sins of the Many talent is not simable right now, would need to work out some form of atonement in simc to be able to sim this
- [x] Check if Power Word: Solace CD is properly being hasted
- [ ] Develop the non-dps focused APL that does the normal healing rotation to determine more accurate dps
- [ ] Handle APL entries for on-use trinkets like we do with Shadow
- [ ] Check Racial spell use in the APL
- [ ] Verify Potion/Feast item for default sim, and change where potion is used if needed
- [ ] Implement Ramp + Atonement Management into the APL. This should mix in "healing" spells with damage ones to maintain maximum atonements during ramp and then output dps to heal via atonement to mimic a raid fight. This should be highly configurable with priest options. Possibly include smaller ramps depending on your cooldowns/config

**Comment by scamille** [comment]
Non-single dps has never been worked on. If you want this to get working there might be more to be checked than Noly Nova and Mind Sear.

Schism definitely needs to be fixed, and PW:Solace CD checked.

Sins of the Many is a somewhat flat DPS% increase depending on the the number of stacks, so shouldn't really affect your relative dps.

Shadow Covenant uses the affected_by system, so should be working fine and not affect any trinkets.

PTW/SW:P would be nice to have helper condition, but this is not really hindering any dps related things.

**Comment by scamille** [comment]
I am going to disable multi target simulations so that those problems are out of the way :)

Sins of the Many could also get a configurable number of atonement targets. I think 2 would be a good value for a dps-centric playstyle, still allowing you to shield the tank and heal another player.

**Comment by elegos** [comment]
As my main is a disc priest (or at least I try to :D ), I'm interested in helping in here. Where should I start at to help with discipline priest? (i.e. the simpliest task you can find to help in this refactoring).

**Comment by scamille** [comment]
I think the most impactful things would be to resolve Twist of Fate and Sins of the many. As stated above, it is probably best to model those with some configurable option to approximate the number of atonment target and twist of fate uptime. A option can be added to https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/priest/sc_priest.hpp#L398 , just check how other variables are hooked up there.

After that the Purge the Wicke/SW:P Action Priority List adjustments, which is done in https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/priest/sc_priest_discipline.cpp#L388

And besides doing those changes I guess it would be best to verify things (the html report has a lot of information in it) as well.

**Comment by scamille** [comment]
You could also try setting up Spirit Shell as discussed in #5681

**Comment by Hudokin** [comment]
Not sure what is need to help with this but Would love to help in any way -

**Comment by seanpeters86** [comment]
moving to https://github.com/simulationcraft/simc/issues/7389
