### ISSUE TITLE
Unholy DK APL would use Apocalypse w/o 4 Wounds

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#5642]
### Describe the bug

Updated DK APL seems to use Apocalypse erroneously with specific talents/conduits/runeforges.

### Expected behavior

You would expect Apocalypse to be used at 4+ wounds only.

### To Reproduce

Take Unholy Assault as a talent.  Equip Convocation of the Dead rank 5+.

Sim.

https://www.raidbots.com/simbot/report/5PkJUyKGzwjrTtsFjf7wJs

This line seems to be the issue; the last 'or' clause is not bracketed and therefore the enemy count / wound check is ignored with Unholy Assault and Convocation of the Dead 5+.

https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier26/T26_Death_Knight_Unholy.simc#L93

`if=active_enemies=1&debuff.festering_wound.stack>=4&!talent.unholy_blight|talent.army_of_the_damned&(!runeforge.deadliest_coil|conduit.convocation_of_the_dead.rank<5)|talent.unholy_assault&conduit.convocation_of_the_dead.rank>=5`

My "ApocChanged" sim adjusts the bracketing as follows:

`if=active_enemies=1&debuff.festering_wound.stack>=4&(!talent.unholy_blight|talent.army_of_the_damned&!runeforge.deadliest_coil|conduit.convocation_of_the_dead.rank<5|talent.unholy_assault&conduit.convocation_of_the_dead.rank>=5)`

I'm not sure if that's the intended logic, but it preserves the enemy # and wound check.  I did not test against other builds (runeforges, conduits, talents).

### Additional information
* SimulationCraft Version (required)

SimulationCraft 902-01
for World of Warcraft 9.0.2.36839 Live (hotfix 2020-12-07/36839, git build 4e360c8d7d)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

N/A

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

N/A

**Comment by scamille** [comment]
cc @simulationcraft/death-knight

**Comment by nyterage** [comment]
This was my error, a case of missing parenthesis from an update the other day. PR is open and ready to merge here https://github.com/simulationcraft/simc/pull/5638. 

Sorry about that!
