### ISSUE TITLE
Mistcaller Ocarina buff issue

### ISSUE THREAD

**Issue by Worzard** [simulationcraft/simc#5644]
The buff from the trinket Mistcaller Ocarina (id:178715) isn't simmed at all. I currently have the crit version which gives me the buff Mistcaller Ocarina (id:332299) for 15 minutes and when it procs I get the buff Mistcaller's Dirge (id:332077). Every sim shows no indication that the the buff exists. Here is a sim report with the trinket that I did with raidbots nightly [here](https://www.raidbots.com/simbot/report/xeQDnygoxZ5U6t1YHu7Fw/simc).

**Comment by navv1234** [comment]
Was implemented as a self buff in d76703b.
