### ISSUE TITLE
Sub and sin rogue APL is missing kidney shot/cheap shot when Prey on the Weak talent slotted

### ISSUE THREAD

**Issue by dazedsean** [simulationcraft/simc#5664]
### Describe the bug
When rogues have the Prey on the Weak talent slotted it provides a buff to their damage by 10% for 6 seconds. The APL for subtlety and assassination is missing this. It is there for Outlaw 

### Expected behavior
Should match Outlaw

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
9.0.2-11

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Mystler** [comment]
Using those to fish for prey is a massive DPS loss. The line in the APL was outdated and I just removed it in 99519d5e5c4c35bf40466368af2063f1aa71b324. Prey is something you use for specific situations and to make your entire group/raid benefit, but not as part of the player rotation and for personal DPS. What I did add is using Cheap Shot with Shot in the Dark if the target is stunnable and you don't have the energy to use Shadowstrike within the next global.
