### ISSUE TITLE
Simcraft downloading at bytes per second

### ISSUE THREAD

**Issue by Marscgm** [simulationcraft/simc#5673]
Wondering if anyone else is experiencing this? Every other download I try operates fine. Download speed goes around 300Mbs except trying to download SimC. Tried changing dns servers. Nothing? Been an outstanding issue for me for a few days.

**Comment by scamille** [comment]
Just to make sure we talk about the same thing, you are talking about the downloads at http://downloads.simulationcraft.org/nightly/ , correct?

I personally can download them fine at good speeds, but that of course doesn't mean that there can be problems for you.

@navv1234 Do you have any insight on why this might occur?

**Comment by navv1234** [comment]
Not really, our download server is as simple setup as it can get. There's very little we impose on it, other than store files. It might be our provider that is having issues currently, but as far as I know there hasnt been any notices about that.

**Comment by Marscgm** [comment]
URL I get is 
http://downloads.simulationcraft.org/nightly/?C=M;O=D
But same result without the extra ?C=M;O=D
