### ISSUE TITLE
Retribution: Damage from execution sentence is calculated incorrectly

### ISSUE THREAD

**Issue by relaksoid** [simulationcraft/simc#5678]
### Describe the bug

When simcraft calculate total damage from execution sentence he miss to multiply accumulated damage by mastery, vers, etc.
### Expected behavior

Resulted damage should be calculated by formula: `initial_damage+accumulated_damage*damage_multipliers`. Cause I doesn't have C++ exp - I can't help with PR. Here missed damage multiply: [click](https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/paladin/sc_paladin_retribution.cpp#L140-L143)
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Tested on live servers. Damage in combat log correspond formula. In simulationcraft damage in simulates less than on live server by 15-25% (correspond my secondary stats)

### Additional information
* SimulationCraft Version (required)
157fdd31af3ea4601ceff0b5f4ab1d2cef6a39ec

P.S. Sorry for the short description without combat logs and etc. Right now doesn't have this opportunity.

**Comment by scamille** [comment]
cc @simulationcraft/paladin

**Comment by mserrano** [comment]
Sorry for the delay here. @relaksoid : I'm struggling to reconcile this with past evidence from logs, but it's plausible. However, I'm curious: did you determine this based on logs of individual events, or aggregate damage across the entire sim? While digging, I discovered that there was another bug based on debuff vs spell cooldowns that should be resolved in 8c9a3e29912746bb4c5cac3f30fea883917406c6 . Can you confirm which of these you did?

**Comment by mserrano** [comment]
Further digging leading to 9a40e2bcfedc3175dcabcc65c6065e4510f2d25b suggests that it is the *base damage* that was being calculated incorrectly. This should be fixed now.
