### ISSUE TITLE
[PvP] Incorrect formula used for critical bonus

### ISSUE THREAD

**Issue by Exolia** [simulationcraft/simc#5679]
### Describe the bug
At line 1114 of file "engine/action/sc_action.cpp" the pvp critical bonus is incorrectly computed.
In shadowlands the critical bonus is 175% instead of 150% (bfa).

### Expected behavior
The correct formula should be: base_crit_bonus -= 0.25;

**Comment by seanpeters86** [comment]
@Exolia do you have a blue post or some calculations you can share to help confirm this? Thanks!

**Comment by Exolia** [comment]
I don't have any blue post available, but everyone can verify this by using any spells in pvp condition (arena, battleground, world pvp). Wait a critical and you will see that critical is base spell damage * 1.75 in pvp condition.

**Comment by scamille** [comment]
I think the main point is not that this change is debated, but that there currently is no developer interested in supporting PvP. If you are (or know someone) that is interested in implementing and also maintaining PvP related things, feel free to contact us in Discord or just start creating new pull requests. We always accept those.
