### ISSUE TITLE
No app associated 

### ISSUE THREAD

**Issue by vorthus** [simulationcraft/simc#5683]
I am getting an error on download saying "This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, creat an association in the Default Apps Settings page."  Does anyone know how to fix this?

**Comment by scamille** [comment]
The Nightly downloads at http://downloads.simulationcraft.org/nightly/?C=M;O=D are packages using 7Zip (https://www.7-zip.org/), a compression program. This results in much smaller file sizes.

You need to download and install 7Zip first and then extract the package before you can start the contained SimulationCraft.exe program.
