### ISSUE TITLE
Inactive Slot Error

### ISSUE THREAD

**Issue by Eevetv** [simulationcraft/simc#5684]
### Describe the bug
I have imported my character from the addon. Moment I hit simulate! I get an error: 

SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Eevetvð': Item 'inactive' Slot 'waist': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.

### Expected behavior
Expected it to simulate and provide information

### To Reproduce
Character: Eevetvð
Server: US/Aerie Peak

### Additional information
* SimulationCraft Version 901-01 (tried 902 with the same error)

https://pastebin.com/1Gu0kd31

**Comment by scamille** [comment]
Works fine for my on raidbots (Advanced Sim) with Nightly build.

Please make sure you have the latest Simc nightly from http://downloads.simulationcraft.org/nightly/?C=M;O=D

Also note that holy priest simulations are not really supported at this point in time.
