### ISSUE TITLE
Update GUI realm lists

### ISSUE THREAD

**Issue by JoaoFranciscoNeto** [simulationcraft/simc#5685]
### Describe the bug
Unable to load characters because of incorrect slug
Slug is aggra-portugues but should be aggra-português.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version simc-902-01

**Comment by scamille** [comment]
Do I understand this correct that the server name used by SimC is incorrect, and thus the armory import does not work?

Please provide a armory link to one of your characters on Aggra so we can more easily replicate the problem.

cc @navv1234

**Comment by JoaoFranciscoNeto** [comment]
That is correct, the slug should have the special character
Armory link:
https://worldofwarcraft.com/en-us/character/eu/aggra-portugu%C3%AAs/smashstein

Profile request:
https://eu.api.blizzard.com/profile/wow/character/aggra-portugu%C3%AAs/smashstein?namespace=profile-eu&locale=en_GB

Created a Pull Request with a fix.

**Comment by scamille** [comment]
Please check with the latest nightly that it is working, and then this can be closed. Thanks for the pull request :-)

**Comment by navv1234** [comment]
Just fyi @scamille there are several other realms that are also broken like that. I'll try to re-generate all our realmlist data at some point soon.

**Comment by JoaoFranciscoNeto** [comment]
> Please check with the latest nightly that it is working, and then this can be closed. Thanks for the pull request :-)

No, thank you for the fantastic work you have been putting on the project.
I just did what was probably the shortest Pull Request in Git history 😄
