### ISSUE TITLE
gluttonous spike trinket

### ISSUE THREAD

**Issue by sogav** [simulationcraft/simc#5687]
on last raidbot version the trinket damage just disappeared even the buff from the trinket

**Comment by scamille** [comment]
Please either post a link to a raidbots report or the input for your simulation (eg. /simc text), so we can replicate this.

**Comment by sogav** [comment]
This is the link from my report https://www.raidbots.com/simbot/report/qSixyYjUtggMwrV41pNtoA/simc

**Comment by seanpeters86** [comment]
resolved by https://github.com/simulationcraft/simc/commit/99703db7f21dec75c66beb945b086c459fdbb73b
