### ISSUE TITLE
An Optimization for Outlaw Rogue APL

### ISSUE THREAD

**Issue by wwricu** [simulationcraft/simc#5693]
Hi Everyone:

I found the ability "between the eyes" is higher prioritized than "Slice and Dice" in PR_Rogue_Outlaw.simc but the sim result show me that always casting "Slice and Dice" first can do us a higher dps by about 1%.

Have this issue been discussed? Or should we improve it?

`actions.finish=slice_and_dice,if=buff.slice_and_dice.remains<fight_remains&refreshable
actions.finish+=/between_the_eyes
`

Maybe this is better.

**Comment by scamille** [comment]
cc @simulationcraft/rogue

**Comment by EvanMichaels** [comment]
Does seem like it may be a gain, although I'm seeing closer to around 0.3% than 1%.
