### ISSUE TITLE
Wierd Inconsistency on Festering Strike of Unholy DK

### ISSUE THREAD

**Issue by hyqwow9** [simulationcraft/simc#5695]
Hi Simc staff:

### Describe the bug
I find there is a significant inconsistency on Festering Strike of Unholy DK. The average damage of Festering Strike is 1440 as I attack the raid dummy at Bastion, while the corresponding average damage in simc is 1800.  I have modified the profile and have deleted all buffs, foods, potion, etc... as shown in the attachment.   There is a 20% difference on the damage, and it seems to be very wierd. 

### Expected behavior
Damage on Festering Strike should be consistent with in-game damage.

### To Reproduce
Simply casting Festering Strike at raid dummy and then using simc to simulate the exact same profile will show the difference on the average damage.

### Additional information
* SimulationCraft Version (required)  902-01 
* Meanwhile the average of auto attack is somehow consistent.

simc.gui:
[simc_gui.zip](https://github.com/simulationcraft/simc/files/5739817/simc_gui.zip)

Simc Result:
![Simc Result](https://user-images.githubusercontent.com/76561401/103093291-da524300-4634-11eb-80b7-9cd86605b19e.jpg)

Festering Strike damage in game:
Average damage 1440, acquired from skada. From top to buttom are min, max and average damage.
![Festering Strike](https://user-images.githubusercontent.com/76561401/103093300-e3431480-4634-11eb-9bd9-5b054cd8b387.jpeg)

Auto attack damage in game:
![Auto attack](https://user-images.githubusercontent.com/76561401/103093303-e5a56e80-4634-11eb-85db-c74472cab1bb.jpeg)

Simc buffs:
No food, potion, flask, bloodthirst, etc......
![Simc Buffs](https://user-images.githubusercontent.com/76561401/103093306-e76f3200-4634-11eb-8484-53d87826931e.jpg)

Where I test damage in game:
![Raid Dummy](https://user-images.githubusercontent.com/76561401/103093316-eccc7c80-4634-11eb-90ca-8117a984407e.jpg)

**Comment by hyqwow9** [comment]
Festering Strike deals physical damage, which means mastery will not affect it. Reasonably Fstering Strike should be independent to all other skills, or at least nearly independent. That's why I find it so wierd.

**Comment by Melekus** [comment]
Thanks for the issue, it looks like Festering Strike rank 2 ingame doesn't actually increase Festering Strike damage by 20% like its tooltip implies, but instead increases Festering Wound damage by the same amount.

**Comment by hyqwow9** [comment]
That's probably it. Thank you so much for fix the issue! 
Meanwhile I still have 150-200 dps gap comparing to simc result lol.

**Comment by Melekus** [comment]
If you have observed other damage differences between simc and the game, feel free to report it.
Just know that you shouldn't be basing everything on the "average" metrics, because an average may and will vary a lot for your limited sample size. Your usage during testing may also vary a lot from how a default simulation is run, with regards to buff uptime and cooldown usage that will affect the average damage.

The best way is to compare the minimum damage observed in simc vs ingame, or you can tweak the simc profile so it doesn't use cooldowns and compare ingame damage to that if you know how to do it.
