### ISSUE TITLE
Destruction Warlock - Dark Soul: Instability

### ISSUE THREAD

**Issue by godsfear** [simulationcraft/simc#5697]
When select talent "Dark Soul: Instability" or "Soul Conduit" in "Results" -> "Abilities" -> "Chaos Bolt" MAX value has about same value. I think it misses 30% crit BUF.

**Comment by scamille** [comment]
cc @simulationcraft/warlock

**Comment by 0xjc** [comment]
Should be fixed via 2bd26339dd325d223687c6c03cd2697ee4df928b

Seems that DSI was bugged and having no effect at all in sims.
