### ISSUE TITLE
Arms Warrior HecticAddCleave/multitarget underperforms.

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#5704]
### Describe the bug

The T26 profile (which is Venthyr) underperforms when the `hac` list is invoked vs. making use of the `execute` list.

### Expected behavior

The `hac` list should either (1) outperform the `execute` list or (2) not be invoked in front of the `execute` list.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Sim with any of the following adjustments:
- `ExecuteMore` = `execute` action list moved ahead of `hac` list.
- `3TargetHAC`  = `hac` list condition changed to `raid_events.adds.exists&active_enemies>2`
- `UseHACwMultiBoss` = `hac` list condition changed to `raid_event.adds.up|active_enemies>2`

1 boss HAC:  https://www.raidbots.com/simbot/report/vY66bigsBMmqLHGTeM72Zz

`UseHACwMultiBoss` = `3TargetHAC` > `ExecuteMore` >> Default

2 boss HAC:  https://www.raidbots.com/simbot/report/vFNAfE87LJiKgeRz1rx5Lf

`UseHACwMultiBoss` = `3TargetHAC` > `ExecuteMore` >> Default

3 boss HAC:  https://www.raidbots.com/simbot/report/ffCCGSNUjJFUXsXgPt6Mtr

`ExecuteMore` >> `3TargetHAC` = Default = `UseHACwMultiBoss`

4 boss HAC:  https://www.raidbots.com/simbot/report/8r4USw1CWQbq4DhvsvRjwo

`ExecuteMore` >> `3TargetHAC` = Default = `UseHACwMultiBoss`

I think the key lessons from these sims are:
1. `hac` should probably be concerned with adds being up, rather than the event existing.
2. The number of targets where you'd prefer the `hac` list as a Venthyr probably should be tested out.
3. Moving the `Execute` list ahead of `hac` is an easy win for Venthyr, but would need testing for other Covenants.  (A bonus bad-sim for Night Fae is available here -- https://www.raidbots.com/simbot/report/cdodKoDzjDBNnrDhvcCFgX -- I didn't change soulbind/conduits though but the numbers are...alarming).

### Additional information
* SimulationCraft Version (required)

![image](https://user-images.githubusercontent.com/9438134/103233419-1d4d3880-490b-11eb-96da-2bcdb39dfebf.png)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

N/A

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

N/A

**Comment by Pewtro** [comment]
@simulationcraft/warrior

**Comment by Hekili** [comment]
Hey, I know this is a very old ticket, but I tested again more recently...

https://www.raidbots.com/simbot/report/nsCiRgCzdXjBfwZmdYiLtv

![image](https://user-images.githubusercontent.com/9438134/153760657-c1f99682-e74a-4e56-8f8c-836dc609bd9a.png)

The recommendation changes still hold up (well, 1 and 2, I didn't test moving Execute).  The `hac` list should be used if there are adds up now or use `active_enemies` or `spell_targets`; just using `hac` all the time if there is ever an add wave in your sim isn't not the right approach.

**Comment by Hekili** [comment]
Alright, one more set of tests before I move on:

https://www.raidbots.com/simbot/report/qCD1FFJVMry8gMpHoNtFwa

Screenshot since Raidbots reports expire:

![image](https://user-images.githubusercontent.com/9438134/153761699-79c7f919-fb0f-4bc8-821a-5e781baa0ec4.png)

I didn't have the info readily available to test a Venthyr sim, but I split the `run_action_list` for `execute` in two: one for Condemn and one for Execute.  This makes it so I can tell the sim to switch to a high health target for Venthyr, and if that target isn't Condemnable, switch to a low health target which could be Executed or Condemned.  (I didn't know that `target_if` could work with `run_action_list` or `call_action_list` until I just tried it.)

Trade-offs:

![image](https://user-images.githubusercontent.com/9438134/153761843-6398c6a1-d724-4df7-80c8-53ea4107e519.png)

Looks like cutting the `hac` list entirely is your best option for tunneling a boss, which makes sense.

If you don't get to tunnel the boss, using HAC only when you can actually hit multiple targets (`spell_targets.whirlwind>1`) pays off more consistently than using the HAC list for the whole encounter.  Using `target_if` to swap to a high health (Condemn) / low health (Execute) target before considering the `execute` list ends up with better opportunistic use of Condemn/Execute.
