### ISSUE TITLE
Inscrutable Quantum Device's Execute Not 100% Crit (It is 100% ingame)

### ISSUE THREAD

**Issue by MaxDeadly** [simulationcraft/simc#5708]
Title, basically. This proc has a 100% chance to crit ingame (I even tested it 20 times with a 22% crit chance and it crit every time), but this isn't reflected in the sims. Here's my sim, for an example.

https://www.raidbots.com/simbot/report/r4NDM3utKzueYzfuEiPSun

**Comment by seanpeters86** [comment]
resolved via https://github.com/simulationcraft/simc/commit/6dcb2d1f8c22121b64c210086c34f9e0a4ee8085
