### ISSUE TITLE
Poxstorm incorrectly applies effect to training dummies

### ISSUE THREAD

**Issue by laraweisleitner** [simulationcraft/simc#5711]
### Describe the bug
Poxstorm ( https://www.wowhead.com/item=178754/poxstorm-longsword-of-pestilence?bonus=6805:1472 ) applies its effect to the training dummy in simulations, but not in-game

### Expected behavior
The effect should not be applied to the training dummy

### To Reproduce
Compare the provided SimC file to:
![image](https://user-images.githubusercontent.com/74208616/103410524-ed50a000-4b6b-11eb-948c-e2661db36b65.png)

### Additional information
* SimulationCraft Version: hotfix 2020-12-22/36949, git build 6dcb2d1f8c

* **simc_gui.simc** file or contents
https://pastebin.com/fRtK0hjQ

**Comment by vituscze** [comment]
I'm not sure what the issue is here? There's nothing that says enemies in simc are target dummies.

**Comment by laraweisleitner** [comment]
You are absolutely right! I checked out the code myself to run it locally instead of using Raidbots and I realised that 'target dummy' is really just a label there. I'm having a think now about how I can handle this disparity with the existing options.
