### ISSUE TITLE
[Warlock]Phantom Singularity duration doesn't scale with haste

### ISSUE THREAD

**Issue by cyli1223** [simulationcraft/simc#5716]
### Describe the bug
Duration of phantom singularity doesn't scale with haste

### Expected behavior
The default duration of Phantom Singularity is 16s but it should scale with haste and become shorter.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft 902-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
Looking at the PR Raid report on simulationcraft.org, I think the ticks are correctly hasted (from 2s to ~1.5s):

![image](https://user-images.githubusercontent.com/1479348/103455726-a68bb300-4cef-11eb-9058-6d4b16a97507.png)

there also seem to be about 10 ticks per execution (73 ticks / 7 executions), giving each execution still the roughly 16s duration just with shorter ticks. Is this the part that is not correct, and the total amount of ticks should stay at 8?

cc @simulationcraft/warlock

**Comment by cyli1223** [comment]
The duration is not 16s. It is dynamic scaled with haste. For example my duration is 14.1s. I checked the code, you have hardcoded the duration to be 16s. I guess you need retrieve it from spellbook.

**Comment by Azevara** [comment]
See the output log here: https://www.raidbots.com/reports/whHtjJPccEC9W4WWvqdzYR/output.txt
The duration of PS is <16 seconds and the code looks correct at a first pass.

Can you please verify you are using the latest version of simc and that you are not mistaking Darkglare extending PS as the issue?
