### ISSUE TITLE
Inscrutable Quantum Device Buff error.

### ISSUE THREAD

**Issue by Recruitie** [simulationcraft/simc#5733]
### Describe the bug
I Believe (through testing with 5 other players every 10m when lust is off CD and looking through logs) that quantum device is not working properly during lust. 

### Expected behavior
What the trinket should be doing during lust is choosing your best stat overall, yet it is still adhering to the 50/50 rule between the two best stats. This causes top gear sims to drop your mastery for instance, to a number that no longer procs mastery during lust, yet the sim still has it happening at a 50/50 odds.

### To Reproduce
Simply sit anywhere and use the trinket during lust, test with different top stats. This is time consuming, but I was able to replicate getting mastery every single time as a balance druid. For death knight it seems more complicated because we assume that runic corruption is counting as haste since it makes your runes recharge faster, which is scaled by haste. Making the trinket sometimes give you haste in the opener if you have the buff present.

### Additional information
I want to be clear that this is only during lust, other times it's still seems to be 50/50. It may require more testing, we're just like 5/6 ppl testing every 10m, but it seems to be pretty consistent to me so far. 
I also went through our mythic pulls on lady inerva where you lust on the pull every time; only 7 pulls. I had 6 pulls where I got vers proc every time with vers being my top stat, then 1 pull with a mastery proc, but on that pull I got +75 mastery from the Grove Invigoration soulbind talent with the Niya soulbind. So it would seem the 1 pull mastery was my highest stat is the 1 pull I got mastery trinket proc. 

Thanks for your time, hopefully I was concise enough to fix this issue, it's a decently big deal with top gear specifically causing you to drop too much of a certain stat.

**Comment by Dorovon** [comment]
This seems to match with some other log data I've looked at where someone got their highest stat 31/31 times at the start of combat when Bloodlust happened to be up. I've updated the trinket in simc to match this.
