### ISSUE TITLE
Simulation Runtime Error

### ISSUE THREAD

**Issue by Jaegermikkel** [simulationcraft/simc#5737]
### Describe the bug
I am trying to Sim my character in WoW as I usually do, but it keeps giving me a runtime error. I will copy paste the result underneath.

### Expected behavior
Get a simulationcraft report

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
simc-902-01-win32-4be7826.7z

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
 # Jægermikkel - Marksmanship - 2021-01-08 19:17 - EU/Ragnaros
# SimC Addon 9.0.2-15
# Requires SimulationCraft 901-01 or newer

hunter="Jægermikkel"
level=60
race=orc
region=eu
server=ragnaros
role=attack
professions=mining=150/jewelcrafting=100
talents=1121232
spec=marksmanship

covenant=night_fae
soulbind=niya:1,322721/140:4/342270/175:6/320687/170:6
# soulbind=dreamweaver:2,
# conduits_available=140:4/183:5/185:5/188:5/189:5/192:5/199:5/223:5/224:5/226:5/251:5/252:5/253:5/175:6/178:6/181:6/282:4/157:6/166:4/170:6/173:4
# renown=19

head=,id=178738,gem_id=173127,bonus_id=7212/6652/1501/5865/6646/6935
neck=,id=183040,gem_id=173128,bonus_id=7188/6652/1485/6646/6935
shoulder=,id=178695,bonus_id=7213/6652/1501/5884/6646
back=,id=178851,enchant_id=6203,bonus_id=7214/6652/1501/5868/6646
chest=,id=182988,enchant_id=6230,bonus_id=7188/6652/1485/6646
tabard=,id=118372
wrist=,id=180114,bonus_id=7214/6652/7193/1501/5868/6646
hands=,id=183014,bonus_id=7188/6652/1485/6646
waist=,id=182976,gem_id=173127,bonus_id=7188/6652/1485/6646/6935
legs=,id=178762,bonus_id=7213/6652/1501/5884/6646
feet=,id=179345,enchant_id=6211,bonus_id=7209/6652/1501/5861/6646
finger1=,id=178871,enchant_id=6166,gem_id=173127,bonus_id=7209/6652/1501/5861/6646/6935
finger2=,id=178926,enchant_id=6168,gem_id=168637,bonus_id=7013/6647/6648/6758/1532/6935
trinket1=,id=184024,bonus_id=7189/6652/1472/6646
trinket2=,id=179350,bonus_id=7214/6652/1501/5884/6646
main_hand=,id=180071,enchant_id=6228,bonus_id=7189/6652/1505/6646

### Gear from Bags
#
# Green Winter Hat (1)
# head=,id=21525
#
# Red Winter Hat (1)
# head=,id=21524
#
# Decadent Nathrian Shawl (213)
# back=,id=184778,enchant_id=6203,bonus_id=7188/6652/1485/6646
#
# Borogove Cloak (155)
# back=,id=184107,bonus_id=41
#
# Ashjra'kamas, Shroud of Resolve (155)
# back=,id=169223,bonus_id=6586/1472
#
# Faewoven Branches (1)
# back=,id=181301
#
# Tortured Assistant's Bindings (203)
# wrist=,id=178767,bonus_id=7210/6652/7194/1501/5861/6646
#
# Ritual Commander's Ring (210)
# finger1=,id=178781,bonus_id=7214/7193/1501/5868/6646
#
# Ritual Bone Band (203)
# finger1=,id=178870,enchant_id=6168,bonus_id=7210/6652/7193/1501/5861/6646
#
# Mistcaller Ocarina (203)
# trinket1=,id=178715,bonus_id=7209/42/6923/1501/5861/6646
#
# Infinitely Divisible Ooze (184)
# trinket1=,id=178769,bonus_id=6807/40/1498/6646
#
# Bottled Flayedwing Toxin (171)
# trinket1=,id=178742,bonus_id=6806/6652/1485/4785
#
# Withergrove Shardling (174)
# trinket1=,id=181459,bonus_id=6652/1472/5871/6616
#
# Bottled Flayedwing Toxin (210)
# trinket1=,id=178742,bonus_id=7214/6652/1501/5868/6646
#
# Darkmoon Deck: Voracity (200)
# trinket1=,id=173087
#
# Mining Pick (2)
# main_hand=,id=2901

 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Warning: Unknown option 'covenant' with value 'night_fae', ignoring
Warning: Unknown option 'soulbind' with value 'niya:1,322721/140:4/342270/175:6/320687/170:6', ignoring
BCP API: Player 'Jægermikkel' unable to download item id '178738' at slot head.
Player Jægermikkel unable to download item id '178738' from wowhead at slot head.Initializing: Actor 'Jægermikkel': Item 'inactive' Slot 'head': Cannot initialize data

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Jægermikkel - Marksmanship - 2021-01-08 19:15 - EU/Ragnaros
# SimC Addon 9.0.2-15
# Requires SimulationCraft 901-01 or newer

hunter="Jægermikkel"
level=60
race=orc
region=eu
server=ragnaros
role=attack
professions=mining=150/jewelcrafting=100
talents=1121232
spec=marksmanship

covenant=night_fae
soulbind=niya:1,322721/140:4/342270/175:6/320687/170:6
# soulbind=dreamweaver:2,
# conduits_available=140:4/183:5/185:5/188:5/189:5/192:5/199:5/223:5/224:5/226:5/251:5/252:5/253:5/175:6/178:6/181:6/282:4/157:6/166:4/170:6/173:4
# renown=19

head=,id=178738,gem_id=173127,bonus_id=7212/6652/1501/5865/6646/6935
neck=,id=183040,gem_id=173128,bonus_id=7188/6652/1485/6646/6935
shoulder=,id=178695,bonus_id=7213/6652/1501/5884/6646
back=,id=178851,enchant_id=6203,bonus_id=7214/6652/1501/5868/6646
chest=,id=182988,enchant_id=6230,bonus_id=7188/6652/1485/6646
tabard=,id=118372
wrist=,id=180114,bonus_id=7214/6652/7193/1501/5868/6646
hands=,id=183014,bonus_id=7188/6652/1485/6646
waist=,id=182976,gem_id=173127,bonus_id=7188/6652/1485/6646/6935
legs=,id=178762,bonus_id=7213/6652/1501/5884/6646
feet=,id=179345,enchant_id=6211,bonus_id=7209/6652/1501/5861/6646
finger1=,id=178871,enchant_id=6166,gem_id=173127,bonus_id=7209/6652/1501/5861/6646/6935
finger2=,id=178926,enchant_id=6168,gem_id=168637,bonus_id=7013/6647/6648/6758/1532/6935
trinket1=,id=184024,bonus_id=7189/6652/1472/6646
trinket2=,id=179350,bonus_id=7214/6652/1501/5884/6646
main_hand=,id=180071,enchant_id=6228,bonus_id=7189/6652/1505/6646

### Gear from Bags
#
# Green Winter Hat (1)
# head=,id=21525
#
# Red Winter Hat (1)
# head=,id=21524
#
# Decadent Nathrian Shawl (213)
# back=,id=184778,enchant_id=6203,bonus_id=7188/6652/1485/6646
#
# Borogove Cloak (155)
# back=,id=184107,bonus_id=41
#
# Ashjra'kamas, Shroud of Resolve (155)
# back=,id=169223,bonus_id=6586/1472
#
# Faewoven Branches (1)
# back=,id=181301
#
# Tortured Assistant's Bindings (203)
# wrist=,id=178767,bonus_id=7210/6652/7194/1501/5861/6646
#
# Ritual Commander's Ring (210)
# finger1=,id=178781,bonus_id=7214/7193/1501/5868/6646
#
# Ritual Bone Band (203)
# finger1=,id=178870,enchant_id=6168,bonus_id=7210/6652/7193/1501/5861/6646
#
# Mistcaller Ocarina (203)
# trinket1=,id=178715,bonus_id=7209/42/6923/1501/5861/6646
#
# Infinitely Divisible Ooze (184)
# trinket1=,id=178769,bonus_id=6807/40/1498/6646
#
# Bottled Flayedwing Toxin (171)
# trinket1=,id=178742,bonus_id=6806/6652/1485/4785
#
# Withergrove Shardling (174)
# trinket1=,id=181459,bonus_id=6652/1472/5871/6616
#
# Bottled Flayedwing Toxin (210)
# trinket1=,id=178742,bonus_id=7214/6652/1501/5868/6646
#
# Darkmoon Deck: Voracity (200)
# trinket1=,id=173087
#
# Mining Pick (2)
# main_hand=,id=2901


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment]
You are using a BFA version of SimulationCraft. Please get the latest nightly from https://www.simulationcraft.org/download.html

**Comment by Jaegermikkel** [comment]
That doesn't make any sense. I've literally reinstalled it from the homepage and wednesday I used the simulation without issues.

**Comment by scamille** [comment]
Your posted text clearly states:
```
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
```

Your WoW SimulationCraft Addon is updated, but SimulationCraft itself is not.
Make sure to grab the newest version, which is 902-01
