### ISSUE TITLE
Docker image fails to run with "Illegal Instruction"

### ISSUE THREAD

**Issue by brianbruggeman** [simulationcraft/simc#5750]
### Describe the bug
Running simc within the docker image causes an Illegal Instruction

### Expected behavior
A failure which indicates that simc was run correctly and failed without the proper arguments supplied

### To Reproduce

```
$ docker run --rm -it simulationcraftorg/simc /bin/sh
/app/SimulationCraft # ./simc spell_query=spell.name=frost_shock
Illegal instruction
```

### Additional information
* SimulationCraft Version (required)
/app/SimulationCraft # ./simc --version
Illegal instruction

**Comment by scamille** [comment]
cc @Bloodmallet 
@Ceriloch is this related to #5751 ?

**Comment by Armadk** [comment]
I'm not sure if it is or not.  I had someone mention to me CI was failing due to Docker builds failing.  It looks like the alpine image that our docker container is based on was updated the other day, and is now including gcc10, which failed to compile with the old flags. The MR fixed it so it's able to build, by using gcc compatible flags.

I did also pull our container from docker hub to see if these were related, and it had a simc binary inside which did output illegal instruction when I tried to use it.  I don't think we should have had a binary given that the container in CI wasn't able to build the source code.  That said, now that the build is fixed, I expect our next nightly to work correctly, and was going to test it before responding that it was fixed, or start investigating the issue further if it was not fixed.

**Comment by Armadk** [comment]
It looks like this still occurs on older CPUs.  I checked the asm in our current docker build and it is failing on the shlx instruction, part of BMI2 which came with Haswell.

**Comment by scamille** [comment]
I think I have a fix for this in 181915e872e7f75748cf9e1086cc58aa46eae911. We discussed this on Discord in the past, but never actually adjusted it in the Dockerfile.

I also started a new dockerhub build job, should hopefully be fixed after this.

**Comment by Armadk** [comment]
Confirming that new image on dockerhub runs successfully on my old 2500k now.

**Comment by brianbruggeman** [comment]
Thanks all!

 
```
./simc spell_query=spell.name=frost_shock
SimulationCraft 902-01 for World of Warcraft 9.0.2.37176 Live (hotfix 2021-01-17/37176, git build shadowlands 5d180fd)

Name             : Frost Shock (id=196840) [Spell Family (11)]
Class            : Shaman
School           : Frost
Spell Type       : Magic
Resource         : 1% Base Mana (0) (id=215292)
Spell Level      : 17
Range            : 40 yards
GCD              : 1.5 seconds
Duration         : 6 seconds
Affecting spells : Shaman Shock Range Bonus (32973 effect#1), Elemental Fury (60188 effect#1), Mastery: Enhanced Elements (77223 effects: #1, #5), Spiritwalker's Grace (79206 effect#1), Restoration Shaman (137039 effects: #3, #4), Elemental Shaman (137040 effects: #1, #2), Enhancement Shaman (137041 effects: #1, #2, #7, #8, #9), Icefury (210714 effect#2), Hailstorm (334196 effect#1)
Family Flags     : 31, 39, 56
Attributes       : ........ ........ x.x..... ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   x....... ........ ........ ........
                 : ........ ........ ........ ........
Effects          :
#1 (id=288995)   : School Damage (2): frost
                   Base Value: 0 | Scaled Value: 0 (coefficient=0, delta coefficient=0.05) | SP Coefficient: 0.45000 | PvP Coefficient: 1.00000 | Target: Enemy (6)
#2 (id=288996)   : Apply Aura (6) | Decrease Movement Speed% (33)
                   Base Value: -50 | Scaled Value: -50 | PvP Coefficient: 1.00000 | Mechanic: Snare | Target: Enemy (6)
#3 (id=313061)   : Dummy (3)
                   Base Value: 100 | Scaled Value: 100 | PvP Coefficient: 1.00000 | Target: Enemy (6)
Description      : Chills the target with frost, causing $s1 Frost damage and reducing the target's movement speed by $s2% for $d.$?s33757[

Frost Shock shares a cooldown with Flame Shock.][]
Tooltip          : Movement speed reduced by $s2%.
```
