### ISSUE TITLE
Boomkin simc (And i assume others that use the trinket) Is holding divine bell for 3 min 30 secs, when it could be easily used again within that window and come off cooldown for the major cooldown rotation

### ISSUE THREAD

**Issue by CSAtkinson** [simulationcraft/simc#5760]
### Describe the bug
In the event sequence of Simc, while using Instructors divine bell, simc holds divine bell for the entire 3min 27 sec till we have our major burst window again. With it only being a 1min 30sec CD, it should be used on cooldown

**Comment by scamille** [comment]
cc @simulationcraft/druid

**Comment by Jundarer** [comment]
Fixed in 8780600. Mind that this only affects specific fight times but it should work for those.
