### ISSUE TITLE
Time_to_pct expressions ignore the enemy_fixed_health_percentage option

### ISSUE THREAD

**Issue by psylic** [simulationcraft/simc#5761]
### Describe the bug
Soul Reaper periodic damage not reported in results of sims. Looks like Soul Reaper debuff is never applied to target on use of ability

### Expected behavior
Soul Reaper does damage directly on use of ability, and more damage 5 seconds later when debuff falls off target if under 35% health

### To Reproduce
Take Soul Reaper talent
sim1: https://www.raidbots.com/simbot/report/hap6weHigVMcTzmh2LjojX/simc
sim2: https://www.raidbots.com/simbot/report/tEYvvRTT1xMimRSiwK9sMH/simc

### Additional information
* SimulationCraft Version (required)
SimulationCraft 902-01 for World of Warcraft 9.0.2.37176 Live (hotfix 2021-01-20/37176, git build 8c95de6fb9)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Melekus** [comment]
It seems that you are using a custom enemy with a fixed health percentage of 100 in your input, so Soul Reaper's execute is never triggered.

The problem here is that the set of APL conditions for Soul Reaper ``target.time_to_pct_35<5&target.time_to_die>5`` returns true even though the enemy has a fixed health percentage well above 35.

**Comment by Melekus** [comment]
Should be fixed as of https://github.com/simulationcraft/simc/commit/575cdcf610a795a05ab59c48073f179f456e3c2c
Make sure you remove your custom health option if you want to take execute into account 👍
