### ISSUE TITLE
Covenant armor set bonus not working

### ISSUE THREAD

**Issue by ubersonic** [simulationcraft/simc#5764]
As title, the Venthyr 5pc set bonus penance brand (660 damage over 6 seconds proc) isn't showing in Simulation

**Comment by scamille** [comment]
I don't think any of the covenant armor set bonuses are implemented in SimC.

But I am not sure if it is worth it. Even if implementing the actual bonus might not be that hard, this also needs some support in the item system to detect when a player has 5pc equipped. 
@navv1234 how much work would this be to implement?

**Comment by scamille** [comment]
Work in progress: #5818
