### ISSUE TITLE
[Warlock] Venthyr Warlock APL does not cast Darkglare/Dark Soul

### ISSUE THREAD

**Issue by danlemmond** [simulationcraft/simc#5765]
### Describe the bug
Running a sim with a Venthyr Warlock causes the APL to skip casting Darkglare and Dark Soul entirely, drastically lowering sim DPS.

### Expected behavior
Venthyr Warlocks should still cast Darkglare / Dark Soul

### To Reproduce
Run a sim with a Venthyr Warlock. Shadowcattra of Zul'jin-US is a suitable candidate.

Output: https://www.raidbots.com/simbot/report/9kQRQqZQ2TxSeRGePXAYFa/simc

### Additional information
* SimulationCraft Version (required)
 (hotfix 2021-01-20/37176, git build 5ce98c9bff)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
cc @simulationcraft/warlock

**Comment by Azevara** [comment]
Should be fixed in #5768
