### ISSUE TITLE
Trinket Memory of Past Sins on shaman enhancement sims

### ISSUE THREAD

**Issue by alyssonaldrin** [simulationcraft/simc#5771]
Any simulation with shaman enhancement using the trinket Memory of Past Sins gives more "hits" of it then expected. we expect to have 5*numberOfCasts at max, but it always have more than it.

Any log using this trinket will have 5*numberOfCasts or less as expected.(https://br.warcraftlogs.com/reports/Fj2rKfcwYkqMaBV6/#fight=last&type=damage-done&source=5).
On this 54 hits for 11 casts for example.

On sims: https://www.raidbots.com/simbot/report/hm4Zgw3cGZYwuT3HEDnx3Z (single target)
39 hits for 5 casts.
https://www.raidbots.com/simbot/report/2ozdGUTaysM52S9SjgiDSv (single target)
36 hits for 5 casts.
https://www.raidbots.com/simbot/report/fifcZpiyNARALXTgCCb7GH (5 targets)
37hits for 3 casts.

I tested on another class to see if it is a global or just enhancement problem, and looks like it is only for enhancements.
For a DK simulation:
https://www.raidbots.com/simbot/report/wHzJceNaFviLJTmxnL5GLh
15 hits for 3 casts.

**Comment by scamille** [comment]
cc @Jayezi

**Comment by scamille** [comment]
@gastank  Do you know why this might be happening?

**Comment by gastank** [comment]
Looks like from all the various procs on procs that enhance has? Things like
```
122.801 Player 'Inalvejavel' schedules execute for Action stormstrike
122.801 Player 'Inalvejavel' performs Action stormstrike (10000)
122.801 Player 'Inalvejavel' stormstrike hits Player 'Fluffy_Pillow' for 0 physical damage (hit)
122.801 Player 'Inalvejavel' consumes 200 mana for Action stormstrike (9800)
122.801 Player 'Inalvejavel' performs Action stormstrike_mh (9800)
122.801 Player 'Inalvejavel' stormstrike_mh hits Player 'Fluffy_Pillow' for 2144.857301392356 physical damage (hit)
122.801 Player 'Inalvejavel' performs Action flametongue_attack (9800)
122.801 Player 'Inalvejavel' flametongue_attack hits Player 'Fluffy_Pillow' for 84.30187003698111 fire damage (hit)
122.801 Player 'Inalvejavel' performs Action stormstrike_offhand (9800)
122.801 Player 'Inalvejavel' stormstrike_offhand hits Player 'Fluffy_Pillow' for 1057.421898388925 physical damage (hit)
122.801 Player 'Inalvejavel' gains Buff maelstrom_weapon (stacks=6) (value=-2.2250738585072014e-308)
122.801 Player 'Inalvejavel' refreshes maelstrom_weapon_6 (value=-2.2250738585072014e-308, duration=30.000)
122.801 Player 'Inalvejavel' performs Action flametongue_attack (9800)
122.801 Player 'Inalvejavel' flametongue_attack hits Player 'Fluffy_Pillow' for 84.30187003698111 fire damage (hit)
122.801 Player 'Inalvejavel' loses Buff gathering_storms
122.801 Player 'Inalvejavel' gains Buff maelstrom_weapon (stacks=7) (value=-2.2250738585072014e-308)
122.801 Player 'Inalvejavel' refreshes maelstrom_weapon_7 (value=-2.2250738585072014e-308, duration=30.000)
122.801 Player 'Inalvejavel' performs Action shattered_psyche (9800)
122.801 Player 'Inalvejavel' schedules travel (0.500) for Action shattered_psyche
122.801 Player 'Inalvejavel' performs Action shattered_psyche (9800)
122.801 Player 'Inalvejavel' schedules travel (0.500) for Action shattered_psyche
122.801 Player 'Inalvejavel' loses Buff shattered_psyche
122.801 Player 'Inalvejavel' performs Action shattered_psyche (9800)
122.801 Player 'Inalvejavel' schedules travel (0.500) for Action shattered_psyche
122.801 Player 'Inalvejavel' performs Action shattered_psyche (9800)
122.801 Player 'Inalvejavel' schedules travel (0.500) for Action shattered_psyche
122.801 Player 'Inalvejavel' performs Action shattered_psyche (9800)
122.801 Player 'Inalvejavel' schedules travel (0.500) for Action shattered_psyche
```

I don't know how the trinket functions with procs on procs like these in-game. But at least it proccing off the stormstrike proxy action and then again off both stormstrike_mh and stormstrike_oh looks like a bug in simc. IDK if this is just an issue specifically with this trinket, or if other procs for enhancement are similarly effected with the proxy + mh + oh actions all potentially causing procs.

**Comment by scamille** [comment]
cc @simulationcraft/shaman

**Comment by EvanMichaels** [comment]
This was fixed with https://github.com/simulationcraft/simc/commit/02fd72b146e4f02bc7d7ecf3f3ba6c26eeef466d
