### ISSUE TITLE
Support pre-combat usage of trinket Memory of Past Sins

### ISSUE THREAD

**Issue by dinfyru** [simulationcraft/simc#5774]
Prepull sim Memory of Past Sins (trinket from Inerva). Like Azshara trinket 20s.

https://shadowlands.wowhead.com/item=184025/memory-of-past-sins?bonus=6805

**Comment by scamille** [comment]
What are you trying to tell us exactly?

**Comment by dinfyru** [comment]
@scamille Is there way to simulate the use of the trinket 20 seconds before the fight. Like Azshara trinket in BFA.

This trinket https://shadowlands.wowhead.com/item=184025/memory-of-past-sins?bonus=6805

**Comment by scamille** [comment]
There currently is no extra support for triggering it pre-combat, as far as I can tell from looking at the code. Unfortunately, SimC has no generic system for truly triggering things before combat starts. If it is considered important, it needs to be manually added to an effect.

@gastank @Jayezi Do you think we could support this without too much effort? I am not sure if we can even add a custom option to something implemented through special_effect_t.

**Comment by dinfyru** [comment]
As far as I know, such a feature was in Battle for Azeroth. With trinket from Azshara

**Comment by Jayezi** [comment]
Can do something like `shadowlands.memory_of_past_sins_precast=20` now. Takes a value from 0 to 30 seconds. f1feb835b6e972692414ce95eca16653c5c5e79f
