### ISSUE TITLE
Necrolord Warrior Lead By Example is not simulated 

### ISSUE THREAD

**Issue by zeidrich** [simulationcraft/simc#5778]
### Describe the bug
Lead By Example is not simulated for the player. 

### Expected behavior
A 30 second buff granting a 13% strength multiplier should be applied when Conqueror's Banner is used. (5% + 4*2%)

### To Reproduce
Create a character with Lead By Example as a trait, with Conqueror's Banner in priority list, the buff is not applied when Conqueror's Banner is used

### Additional information
* 902-01 Feb 2nd Build

* **simc_gui.simc** file or contents
warrior="NecroWarrior"
spec=fury
level=60
race=orc
role=attack
position=back
talents=https://worldofwarcraft.com/en-us/game/talent-calculator#warrior/fury/talents=3331331
covenant=necrolord
soulbind=emeni,lead_by_example/veterans_repute:7

**Comment by scamille** [comment]
cc @simulationcraft/warrior
