### ISSUE TITLE
Enhancement shaman dps rotation

### ISSUE THREAD

**Issue by Greencatinglasses** [simulationcraft/simc#5780]
Hello.
1.  I recently found that hot hand procs should be implemented differently for dps rotation. **Placing it before frequent casts (like lightning bolt) gives more dps.**
2.  **Bis shaman dps in ST seems to be also incorrect.** Simed it with Nya, correctly impemented hot hand, and magma first conduit. Resulted dps is greater for about 100 points compared to the current one.

**Comment by scamille** [comment]
Do you have some reports (eg. to raidbots) to show those results?
Have you checked how your change behaves in other fight styles than patchwerk? While most APLs are only optimized for single target fights, it still makes sense to at least check that there is not a significant dps regression when changing the APL.

Thanks for your report.

cc @simulationcraft/shaman

**Comment by Greencatinglasses** [comment]
1) https://www.raidbots.com/simbot/report/h8AoFrPoJ2KFn1i4xYSpNd <- loaded the default one from yesterday simcraft.
2) https://www.raidbots.com/simbot/report/a9s8fRfUtgTTz1hgJ9SLLp <- loaded my updated APL and conduit.
3) Checked for the ultraxion-type seems true too (6342 vs 6424)
4) For heavy movement my build seems to be lightly behind (5780 vs 5728)

**Comment by flapjack831** [comment]
Fixed with https://github.com/simulationcraft/simc/commit/aab12d9ce72867443d2f7d9bd36c73cb6cef6779
