### ISSUE TITLE
Import failed server with accents

### ISSUE THREAD

**Issue by vincent-bru** [simulationcraft/simc#5782]
region:
EU
Server:
Marécage de Zangar
Character:
Domtrooper

Import bar roll, then throw an error fail tab:
error:
 Profile will be downloaded into a new tab.

 Clicking Simulate will create a simc_gui.simc profile for review.

 Unable to generate profile from: 

 Error response 404 from Blizzard API: Not Found

**Comment by scamille** [comment]
Thanks for your report.

@navv1234 I assume this is because we have the wrong server name in the list the GUI uses, as in #5685

@seriallos Do you have any currently functional scripts for realm list generation which you could easily adjust to generate https://github.com/simulationcraft/simc/blob/shadowlands/qt/eu-realmlist.json (and other regions)?

**Comment by seriallos** [comment]
I think eu-realmlist.json is the data returned from the old API which doesn't exist any more.

I have some scripts that pull the new API data and generates some files but the data available is slightly different. My files have entries like this:

```
      {
        "name": "Marécage de Zangar",
        "slug": "marécage-de-zangar",
        "names": {
          "en_US": "Marécage de Zangar",
          "es_MX": "Marécage de Zangar",
          "pt_BR": "Marécage de Zangar",
          "de_DE": "Marécage de Zangar",
          "en_GB": "Marécage de Zangar",
          "es_ES": "Marécage de Zangar",
          "fr_FR": "Marécage de Zangar",
          "it_IT": "Marécage de Zangar",
          "ru_RU": "Marécage de Zangar",
          "ko_KR": "Marécage de Zangar",
          "zh_TW": "Marecage de Zangar",
          "zh_CN": "Marécage de Zangar"
        }
      },
```

I'm not sure if this would work to be dropped into SimC without any changes or not

**Comment by seriallos** [comment]
And yeah, I think the fundamental issues is that Blizz changed the realm slugs with the new API. They now seem to keep accented unicode characters rather than down-converting them into plain ASCII. So `marécage-de-zangar` now has the `é` when it was previously an unaccented `e`

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/shadowlands/qt/sc_importWidget.cpp#L71 looks like fairly small amount of code, I am confident that this can be adjusted.

Can you just commit your realm list to the qt\ folder in the simc repository? Then either navv or myself can try to adjust the gui code to parse the new file.

**Comment by seriallos** [comment]
Here's the current eu.json I'm using if you want to see if that can be dropped in and see if it works with the Import tab - I've never gotten GUI builds set up on my dev environments so I don't think I can test it.

https://gist.github.com/seriallos/53345add6fe4674dd0f84e0687570821

**Comment by seriallos** [comment]
> Can you just commit your realm list to the qt\ folder in the simc repository? Then either navv or myself can try to adjust the gui code to parse the new file.

Sure thing, I just committed some files into `qt/realms`

**Comment by scamille** [comment]
Thanks. I'll give it a try.

**Comment by scamille** [comment]
That was easier than I thought.

@vincent-bru Please try again in 24 hours with the next nightly build.

**Comment by vincent-bru** [comment]
Thank you, you guys rocks ;)
ok I'll try again with the next build, I'll let you know
