### ISSUE TITLE
PVP Trinket bonus not applied 

### ISSUE THREAD

**Issue by mbabigian** [simulationcraft/simc#5785]
### Describe the bug
I see no substantial change in the relative value of versatility when equipping the Shadowlands PVP trinket set.  It appears this bonus is never activated.  I don't see the SIMC addon gathering that I am in Warmode, which would be necessary to enable the bonus.  Need some way of simulating with the bonus enabled for Arena's, BGs, and warmode.

### Expected behavior
With a 40% buff to vers, I expect to see a large jump in the relative versatility stat weighting when I equip both pieces.

### To Reproduce
Sim a character with the PVP trinket set and again removing one trinket (remove only the medallion).  The change in Versatility stat weighting for my Shadow Priest is tiny and the change in dps is solely due to the intellect loss of removing the trinket.

### Additional information
9.0.2-15

**Comment by scamille** [comment]
Currently SimC does not really support PvP in a serious manner, even if you can of course set up SimC to mimic some kind of pvp fight.

There just isn't that much interest, and if you want to have things like pvp items implemented, that would require someone interested in the topic to implement (and maintain) them. We are always accepting pull requests :-)

Proper PvP support would also require testing and implementing all other things related to it, to make sure that they are modeled correctly in SimC. See for example #5679

**Comment by YomamaNow** [comment]
the trinket bonus is static though and could just be done like a pvp checkbox option, in order to appropriately weight stats.

**Comment by mbabigian** [comment]
Like Blizzard open source projects could care less what the vast majority of users want. Only what the devs want gets done without a model that provides an incentive to support user’s needs. Blizzard has such a feedback system $$$.  FF14 is explaining to them how it works.  ;)
