### ISSUE TITLE
Niya's Tool's: Poisons not showing any damage for UH DK Nightfae w/Niya Soulbind

### ISSUE THREAD

**Issue by nb41** [simulationcraft/simc#5787]
### Describe the bug
Casting Patchwerk sims don't seem to be simming any interrupts for an Unholy DK, that I can tell. I set a Raidbots Top Gear sim to Casting Patchwerk for my UH DK (report linked below), and asked it to compare Niya's Tools: Burrs to Niya's Tools: Poisons. The report output indicated there is no Paralytic Poison damage, and that no interrupts were cast. But if it's set to Casting Patchwerk, shouldn't there be some? 

Note that pet interrupts WILL apply Paralytic Poison (though I understand if that's a bit much to sim). I do see some interrupts as Blood or Frost, but hardly any; it's enough to show damage getting through, at least. Nothing for UH, though.

### Expected behavior
There should be at least some interrupts simmed for Unholy--even if it's just one every 30 seconds (which is half as often as it can be cast) to keep the Paralytic Poison DoT up.  I'm not seeing a single Mind Freeze cast in a UH simulation, though Blood and Frost do see some.

### To Reproduce
Take an Unholy DK and run a simulation of Nightfae Soulbind for Niya with the final route set to terminate on Niya's Tools: Poisons. Set the simulation type to any sim type which would include interrupts (but this was happening specifically with Casting Patchwek). Note that you can see this here in a Raidbots Top Gear report: https://www.raidbots.com/simbot/report/jCTECixnGjUztYN6Z7g8uh and you can see it here on BloodMallet as well, where Poisons--despite a Casting Patchwerk setting--reports [0 damage for Unholy](https://bloodmallet.com/chart/death_knight/unholy/soul_binds/castingpatchwerk), but [some damage for Blood](https://bloodmallet.com/chart/death_knight/blood/soul_binds/castingpatchwerk) and a tiny bit [for Frost](https://bloodmallet.com/chart/death_knight/frost/soul_binds/castingpatchwerk).

### Additional information
* SimulationCraft Version (required)
6c77a12184

**Comment by scamille** [comment]
cc @simulationcraft/death-knight 

Thanks for your report.

This is likely either a problem with interrupts not being implemented/buggy, or if they are just not used in the default action priority list.

**Comment by Melekus** [comment]
The difference you're seeing on Bloodmallet is most likely just based on margin of error. Mind Freeze isn't used in any of Blood, Frost, or Unholy APL.

**Comment by Melekus** [comment]
Fixed by https://github.com/simulationcraft/simc/commit/556bdcb241b1992137ce6c566bb96d51777b969e
