### ISSUE TITLE
Demon Hunter "Relentless Onslaught" Conduit procs refund fury while they do not in game

### ISSUE THREAD

**Issue by MichaelFogg** [simulationcraft/simc#5788]
### Describe the bug
Demon hunters using the conduit "Relentless Onslaught" are incorrectly generating fury from procced chaos strikes/annihilates. SimulationCraft separates these gains in the resource tab as chaos_strike_onslaught and annihilation_onslaught to differentiate between normal refunds, but in game they never seem to generate any fury. 

### Expected behavior
In game, demon hunters never receive this fury, and as such also do not double reduce the cd of eye beam with the talent "Cycle of Hatred"

### To Reproduce
Equip the "chaos theory" legendary and proc the "chaotic blades" buff with a blade dance, every chaos strike is guaranteed to refund 20 fury with the buff, however when 4 damage events occur following a successful cast in this window (non-procs are 2 events, 1 for main hand 1 for off hand), only 1 spell energize occurs for chaos strike generating 20 fury.

Occurs in [this log](https://pastebin.com/d5PZMW7u) at lines 636-650 (chaotic blades being up 615-695)

I was using a [4fun janky weakaura](https://wago.io/VoMBoa-PO) I had made to track my Relentless Onslaught procs when I realized I had never seen a 2 hit, 2 refund cast, I assumed the energize was possibly happening with a different spell id or too far outside of the multi-hit window but upon forcing the event to occur found it did not refund. Figured I'd upload the WA since noticing the procs happen especially with such a low chance can be difficult
### Additional information
* SimulationCraft Version (required)
simc-902-01-win64-14e486a.7z | 2021-02-09 01:30

**Comment by scamille** [comment]
@simulationcraft/demon-hunter

**Comment by EvanMichaels** [comment]
@MichaelFogg this was not the case in Beta or in the Legion implementation of Onslaught, however it could be a timing issue since the refund has a 0.5s ICD.

In these logs it is _barely_ outside of this window:
2/9 06:36:39.263
2/9 06:36:39.724

These events are 461ms apart, which means technically they would be impacted by the ICD.

Do you know if this is 100% reproducible or if it's based on latency? Possible Blizzard made a subtle timing change without realizing the impact.

**Comment by MichaelFogg** [comment]
[WoWCombatLog_OnslaughtDummyTestLong.txt](https://github.com/simulationcraft/simc/files/5957733/WoWCombatLog_OnslaughtDummyTestLong.txt)
Here's a log where I spent 30 minutes fishing for onslaught procs in Chaotic Blades windows. Anytime one procced I would cast a "Red Firework Rocket" after since they are quite difficult to spot sifting through logs, so if you search for that cast, it is immediately following a relentless onslaught proc (I was late on one cast so a normal CS is between for one of them), regardless for all 18 casts it behaves how I describe, with 1 cast_success, 1 energize for 20, and 4 damage events. I garrison hearth partway through to see if being on an instance server changes it. I also shadowmeld and remove all my haste gear (went from 600+ to 32) for the last 5 casts and it did not appear to impact the timing of the procced strikes.
