### ISSUE TITLE
Moderate night fae Shadow Priest 4+ target improvement

### ISSUE THREAD

**Issue by jmoyers** [simulationcraft/simc#5792]
When Searing Nightmare is talented, applying Shadow Word: Pain manually to a target results in a small dps gain for 3 targets and under if you are Night Fae due to Wrathful Faeries.

However, once you reach 4 targets, the extra global to manually apply SW:P to a primary target is a moderate loss to dps (a little under 10%).

Original:
actions.main+=/shadow_word_pain,if=buff.fae_guardians.up&!debuff.wrathful_faerie.up

Suggested:
actions.main+=/shadow_word_pain,if=buff.fae_guardians.up&!debuff.wrathful_faerie.up&spell_targets.mind_sear<4

I'm new to looking at APL, so prob needs a sniff test.

**Comment by scamille** [comment]
cc @simulationcraft/priest

**Comment by seanpeters86** [comment]
Whoops, sorry I missed this. Here are the results:

## Misery
- 3T Misery: <https://www.raidbots.com/simbot/report/sgM3iVmjkyT63XuXtnrep3> (-0.1%)
- 4T Misery: <https://www.raidbots.com/simbot/report/2aRGcbg1ksiMq7dttsbzHW> (2.2%)
- 5T Misery: <https://www.raidbots.com/simbot/report/9LWC3TkUKgenuWh7o4uHve> (2.9%)
- DS Misery: <https://www.raidbots.com/simbot/report/hEEAiSwixrJP7tMrvpcQ1v> (3.3%)

## Searing Nightmare
- 3T SN: <https://www.raidbots.com/simbot/report/hZrWWEm45pwZuUtHLKzEt> (0.0%)
- 4T SN: <https://www.raidbots.com/simbot/report/6Uk485tbPdnpb3nuxgM5E2> (6.1%)
- 5T SN: <https://www.raidbots.com/simbot/report/ujhzmJAYuoM8daUePjwZJo> (6.2%)
- DS SN: <https://www.raidbots.com/simbot/report/jVq4UKiCryohyWakhKDKeR> (4.7%)

https://github.com/simulationcraft/simc/commit/3f557e277f58fcbcc22b43681fa0a4d6bbea3795

Thanks for the suggestion! It will be in raidbots nightly in ~24 hours.
