### ISSUE TITLE
Major Balance druid APL error.

### ISSUE THREAD

**Issue by Recruitie** [simulationcraft/simc#5800]
### Describe the bug
The balance druid apl is currently not casting dots until 43 seconds into the pull, once cooldowns are finished.

### Expected behavior
The apl should be casting it asap in the opener, then refreshing during CDs and on.

### To Reproduce
Quick sim and look at the apl.

### Additional information
Unsure what the recent update was for/fixing, but it clearly made a negative reaction. I'm also not aware if this is something on raidbots end, or the class writers. I'm quite ignorant on these topics. Just aware of the problem and don't know where else to put this information. Thanks for your time and good luck!
"Incorrect" apl (After recent changes.) https://www.raidbots.com/simbot/report/szPRoCS2J8KfEviqtxNiTF

"Correct" apl (Before recent changes.) https://www.raidbots.com/simbot/report/85a6Su8s3kNJwpprPwfWLb

**Comment by Zelop** [comment]
Commenting to add that this issue is in commit https://github.com/simulationcraft/simc/commit/ea9fc69658e2256d6f1f5fe4b53b68c4e38017f3

**Comment by Recruitie** [comment]
Reading this I don't see how it would stop the apl from putting dots up in the opener. It's clearly not dps neutral either if it does. I've lost 300 dps between the two sims. The newer one has upgraded trinket(210 to 226,) and convoke conduit(200 to 213) as well. I could be confused with what you're saying because I don't know what "this issue is in commit" means.
