### ISSUE TITLE
[Warrior] Fresh Meat is not triggering Enrage on initial Bloodthirst

### ISSUE THREAD

**Issue by seriallos** [simulationcraft/simc#5804]
### Describe the bug

Fresh Meat talent is not causing the initial Bloodthirts on a boss to trigger Enrage

Reported on Raidbots Issues: https://github.com/seriallos/raidbots-issues/issues/259 by @weiweiqin0714

Raidbots Sample Ability Log screenshot:
![image](https://user-images.githubusercontent.com/1010294/108605425-da3a9f00-7368-11eb-819c-b51541b3675a.png)

Sample Sequence Table from SimC HTML report:
![image](https://user-images.githubusercontent.com/1010294/108605455-00603f00-7369-11eb-93c6-2bfb7d18ffe3.png)

### To Reproduce

Example sim: https://www.raidbots.com/simbot/report/q8Azu3EJxf7fbAuFyHzF3U

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
