### ISSUE TITLE
Assassination Rogue default profile covenant choices

### ISSUE THREAD

**Issue by folklores1234** [simulationcraft/simc#5805]
Hi, yes I don't know if this format is properly written, but on your sims you have the wrong soulbinds for some specs. For example you're still using Kyrian for Assassination Rogue which is about ~200 less than Night Fae Niya. Since the community is so toxic around simming and what it means for the meta it'd be nice for this to be fixed.

**Comment by scamille** [comment]
Hi thanks for the issue.

Please keep in mind that the profiles provided with SimC are just sample profiles on how one could set up a character. While they might strive to represent some form of best obtainable gear and character configuration, that might not always be 100% the case.

That said, thanks for your input. I am sure someone of @simulationcraft/rogue  will have a look and give a more meaningful response :-)

**Comment by EvanMichaels** [comment]
Profiles probably won't be updated again until after the 9.0.5 patch finalizes the mechanic updates fully.
