### ISSUE TITLE
Retribution Paladin Execution Sentence APL

### ISSUE THREAD

**Issue by Caelifer1988** [simulationcraft/simc#5806]
Hi, when I checked the sample sequence table of the most recent build, there was a weird priority of abilities happening (Execution Sentence used before Final Reckoning) so I took a closer look into the APL an found this:

actions.finishers+=/execution_sentence,if=((**!talent.crusade.enabled**|buff.crusade.down&cooldown.crusade.remains>10)|buff.crusade.stack>=3|cooldown.avenging_wrath.remains>10|debuff.final_reckoning.up)&time_to_hpg=0&target.time_to_die>8

Seems like the marked condition is always true and "overwrites" the other one(s) related to Final Reckoning. Maybe this would be a solution:

actions.finishers+=/execution_sentence,if=(((!talent.crusade.enabled|buff.crusade.down&cooldown.crusade.remains>10)|buff.crusade.stack>=3)&(cooldown.avenging_wrath.remains>10|(!talent.final_reckoning.enabled|debuff.final_reckoning.up)))&time_to_hpg=0&target.time_to_die>8

This is at least a +50 dps gain for my character when Final Reckoning talented, no change when Crusade or Sanctified Wrath talented.

Raidbots (old):
https://www.raidbots.com/simbot/report/hDix4a48K4PsMvqhb3taRt
https://www.raidbots.com/simbot/report/hq2Be2me9VFYsM8u6g6LJn

Raidbots (new):
https://www.raidbots.com/simbot/report/dn8cm55Qeu9fPdvv79qQkj

**Comment by scamille** [comment]
cc @simulationcraft/paladin

**Comment by Caelifer1988** [comment]
I have further modified the APL to optimize two Builds:

12xx3x3 (Zeal,, Blade of Wrath, Seraphim, Final Reckoning)
32xx3x3 (Execution Sentence, Blade of Wrath, Seraphim, Final Reckoning)

By accident all possible Talent sets got a slightly increased dps too :)

12xx3x3: +82 dps
https://www.raidbots.com/simbot/report/2xhWiGek1gVTU21CZWpFhp (old)
https://www.raidbots.com/simbot/report/7jrF9b12eKqtdBC84Wc6Q2 (new)

32xx3x3: +100 dps
https://www.raidbots.com/simbot/report/sS6r5ack7ughnyLEv3ZbtP (old)
https://www.raidbots.com/simbot/report/sQtVKxVzEirLZbdUuPk6jh (new)

However, Dungeon Slice sims are lower now so that has to be fixed.
Tested this new APL with legendaries "Mad Paragon" and "Magistrates Judgment" but just with Kyrian Covenant.

Here is the APL:
[Paladin APL.txt](https://github.com/simulationcraft/simc/files/6036251/Paladin.APL.txt)

**Comment by Caelifer1988** [comment]
Changed the APL again regarding AoE damaging:
[Paladin APL 2.txt](https://github.com/simulationcraft/simc/files/6041901/Paladin.APL.2.txt)

But still can't figure out why Dungeon Slice sims are much lower now.
https://www.raidbots.com/simbot/report/3jPhUL5tTt72ayGjac8wyH (old)
https://www.raidbots.com/simbot/report/tekffz61vb2DpemCzyjdyc (new)

Singletarget sims are higher (see comment above) and also Cleave/AoE sims are higher now:
https://www.raidbots.com/simbot/report/7moBJwuH1YB6CTZTNSYLfg (2 targets, old)
https://www.raidbots.com/simbot/report/cJMdZ76qWQzj9yMpbQzrRo (2 targets, new)
https://www.raidbots.com/simbot/report/mS8hHidv9Wjqryog3upWmr (5 targets, old)
https://www.raidbots.com/simbot/report/mtFBTtUeAUDg48PsLMcjcg (5 targets, new)

Really weird
