### ISSUE TITLE
Paladin "Virtuous Command" Conduit bug?

### ISSUE THREAD

**Issue by Caelifer1988** [simulationcraft/simc#5807]
https://www.wowdb.com/spells/339518-virtuous-command

In actual simulations (i.e. Raidbots.com) Virtuous Command buff average duration seems to be more than 5 seconds for Kyrian.
https://www.raidbots.com/simbot/report/fuUE7pN2uXfNR9zoRF4CrQ/simc
5.1 seconds in this case. I assume this happens because its sometimes being refreshed (prolonged).

Ingame the buff duration is technically not able to exceed 5 seconds due to its inability to be refreshed by Divine Toll (Kyrian) or Judgment. In other words the buff can not be (re)applied while the buff is already active.

This can be checked at any training dummy or at warcraftlogs.com. I took a random Log from any Paladin using this Conduit to check the combat log:

Damage:
https://www.warcraftlogs.com/reports/ZGgrKDhPMcn642LA#fight=3&type=damage-done&source=23&view=events
Buffs:
https://www.warcraftlogs.com/reports/ZGgrKDhPMcn642LA#fight=3&type=auras&source=23&view=events

At time stamp 8.294 this paladin is using Divine Toll and gains Virtuous Command buff at 8.346.
At 12.901 he is using Judgment but doesn't gain the buff, instead the old one vanishes at 13.337, which is pretty much 5 seconds after it was applied by Divine Toll 
-> Virtuous Command can not be refreshed.

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/50e17564392cb2ebbb53bd84e00e418ca527672c/engine/class_modules/paladin/sc_paladin.cpp#L979

cc @simulationcraft/paladin

**Comment by Caelifer1988** [comment]
if ( p() -> conduit.virtuous_command -> ok() && !(p() -> buffs.virtuous_command -> up() ))
    p() -> buffs.virtuous_command -> trigger();

Would make it?

**Comment by scamille** [comment]
I mainly wanted to point to the location in the code where this is happening.
Your proposed solution would resolve the problem as you described it, assuming I understood it correctly.

Since I have no clue about paladins, I am sure some paladin developer will be around shortly, who can give this the scrutiny it deserves. (And fix it)
