### ISSUE TITLE
Spell order is getting completely messed up when simming with magistrate's judgement legendary

### ISSUE THREAD

**Issue by Pootzi** [simulationcraft/simc#5811]
Here is a sim using the **mad paragon**:
https://www.raidbots.com/simbot/report/vKjfTKxxe17rPymBezDmsP

Here is a sim using the **magistrate's judgement**:
https://www.raidbots.com/simbot/report/8ycdvacyX3eQcd8yrBJwQz
https://www.raidbots.com/simbot/report/PGcH8S3i6H8RNEf1XGg9a (2nd sim that it seemed to do right)
https://www.raidbots.com/simbot/report/PGcH8S3i6H8RNEf1XGg9a (3rd sim that returned wrongly casting ES right after seraphim and before final reckoning)

If you look at the casting order of the paragon sim, everything is coming out just fine and in a reasonable order.  Notice the timing of executioner sentence, it is the optimal sequence.  Now, looking at the magistrate's judgement sim.  Look at the difference in ordering.  It is extremely wrong.  It's not just like random sim differences, it is catastrophically wasted wrong.  seraphim->3 holy power->wings -> FR -> ES -> DT->Spender->wake of ashes->, is the absolute fundamental backbone of the kyrian ES build.  Any other order and you'll be missing out on a great deal of damage.  In the first magistrate's judgement sim, at 0:04:318, ES is cast before both wings and FR.  And this happens on every iteration of ES.  Again, at 1:04:700, ES is cast giving you until 1:12:700 to get as many spenders and cds off as possible.  Wake of ashes, being a 1 minute cooldown, ALWAYS gets cast in this window, which is not cast until after the window is done.  If we put a requirement ES to be cast after FR always, I imagine the problem will be fixed or at least the underlying issue will become blatantly obvious as to what it is about the magistrate buff that is causing this issue.

What makes this even more odd, is I did the same sim twice more and one of the sims did it right the whole fight and the 3rd again botched it regularly. sometimes it does it right and other times it messes it up catastrophically again in that it chooses to ES before FR but in a slightly different way.  Either way, the fundamental rule not being enforced here is that ES should always be cast immediately after FR.

**Comment by scamille** [comment]
cc @simulationcraft/paladin 

Thanks for the report. This might not necessarily be a bug with the legendary itself, just a deficit of the Action Priority List which gets exposed when using the legendary and its effect. But it probably makes sense to first investigate if the legendary effect itself is modeled correctly in SimC.

**Comment by mserrano** [comment]
This is one of the things dbd6a1591723bbb0a44a5358659c12bc9af79939 is supposed to help address; there are more improvements in the pipeline that I'll commit once they're ready
