### ISSUE TITLE
This comes up when trying to simulate my gear

### ISSUE THREAD

**Issue by Vynora897** [simulationcraft/simc#5815]
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Warning: Unknown option 'covenant' with value 'night_fae', ignoring
Warning: Unknown item option 'crafted_stats' with value '32/40' for 'Vynora' slot 'head', ignoring
Warning: Unknown item option 'crafted_stats' with value '40' for 'Vynora' slot 'neck', ignoring
Warning: Unknown item option 'crafted_stats' with value '49/36' for 'Vynora' slot 'shoulders', ignoring
Warning: Unknown item option 'crafted_stats' with value '40/49' for 'Vynora' slot 'chest', ignoring
Warning: Unknown item option 'crafted_stats' with value '49/36' for 'Vynora' slot 'waist', ignoring
Warning: Unknown item option 'crafted_stats' with value '40/49' for 'Vynora' slot 'legs', ignoring
Warning: Unknown item option 'crafted_stats' with value '36/32' for 'Vynora' slot 'feet', ignoring
Warning: Unknown item option 'crafted_stats' with value '40/49' for 'Vynora' slot 'wrists', ignoring
Warning: Unknown item option 'crafted_stats' with value '49/40' for 'Vynora' slot 'hands', ignoring
Warning: Unknown item option 'crafted_stats' with value '49' for 'Vynora' slot 'finger1', ignoring
Warning: Unknown item option 'crafted_stats' with value '32' for 'Vynora' slot 'finger2', ignoring
Warning: Unknown item option 'crafted_stats' with value '49/36' for 'Vynora' slot 'back', ignoringInitializing: Actor 'Vynora': Item 'quick_oxxein_necklace' Slot 'neck': Error decoding gems from '': No gem data for id 173128.

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=16
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,ap,crit,haste,mastery,vers,wdps,armor
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Vynora - Beast Mastery - 2021-02-21 20:58 - US/Dalaran
# SimC Addon 9.0.2-15
# Requires SimulationCraft 901-01 or newer

hunter="Vynora"
level=60
race=night_elf
region=us
server=dalaran
role=attack
professions=alchemy=175/herbalism=51
talents=2122211
spec=beast_mastery

covenant=night_fae
# conduits_available=
# renown=1

head=,id=172261,bonus_id=6893/7185,drop_level=60,crafted_stats=32/40
neck=,id=173146,gem_id=173128,bonus_id=7185,drop_level=60,crafted_stats=40
shoulder=,id=172263,bonus_id=6893/7185,drop_level=60,crafted_stats=49/36
back=,id=173215,enchant_id=6203,bonus_id=6893/7185,drop_level=60,crafted_stats=49/36
chest=,id=172258,enchant_id=6214,bonus_id=6893/7185,drop_level=60,crafted_stats=40/49
tabard=,id=69210
wrist=,id=172265,bonus_id=6893/7185,drop_level=60,crafted_stats=40/49
hands=,id=172260,bonus_id=6893/7185,drop_level=60,crafted_stats=49/40
waist=,id=172264,bonus_id=6893/7185,drop_level=60,crafted_stats=49/36
legs=,id=172262,bonus_id=6893/7185,drop_level=60,crafted_stats=40/49
feet=,id=172259,enchant_id=6211,bonus_id=6893/7185,drop_level=60,crafted_stats=36/32
finger1=,id=173134,enchant_id=6166,gem_id=173128,bonus_id=7185,drop_level=60,crafted_stats=49
finger2=,id=173133,enchant_id=6166,gem_id=173128,bonus_id=7185,drop_level=60,crafted_stats=32
trinket1=,id=181459,bonus_id=6652/1472/5852/6616
trinket2=,id=175730,bonus_id=6707/6902,drop_level=58
main_hand=,id=179584,bonus_id=6652/1472/5874/6616

### Gear from Bags
#
# Eventide Belt of the Harmonious (129)
# waist=,id=175569,bonus_id=6907/1714,drop_level=60
#
# Stolen Maw Badge (138)
# trinket1=,id=175731,bonus_id=6707,drop_level=59
#
# Heartwood Bow (120)
# main_hand=,id=175983,enchant_id=6195,bonus_id=6707,drop_level=56
#
# Staats' Fishing Pole (5)
# main_hand=,id=46337

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment]
You're using Battle for Azeroth version of simc, you should upgrade.

**Comment by Vynora897** [comment]
Do you know how I can download the Shadowlands version? I’m looking everywhere on their website and I can’t find it.  Sent from Mail for Windows 10 From: Vít ŠeflSent: Friday, February 26, 2021 1:38 PMTo: simulationcraft/simcCc: Vynora897; AuthorSubject: Re: [simulationcraft/simc] This comes up when trying to simulate my gear (#5815) You're using Battle for Azeroth version of simc, you should upgrade.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vituscze** [comment]
Pick the appropriate version here: http://downloads.simulationcraft.org/nightly/?C=M;O=D

**Comment by Vynora897** [comment]
I appreciate the link. It brings up .dmg and .7z files. There’s no .exe files to download Sent from Mail for Windows 10 From: Vít ŠeflSent: Friday, February 26, 2021 2:31 PMTo: simulationcraft/simcCc: Vynora897; AuthorSubject: Re: [simulationcraft/simc] This comes up when trying to simulate my gear (#5815) Pick the appropriate version here: http://downloads.simulationcraft.org/nightly/?C=M;O=D—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vituscze** [comment]
Yes, download the 7z archive and unpack it somewhere.
