### ISSUE TITLE
Shadow blades with vulnerability event.

### ISSUE THREAD

**Issue by Lievet** [simulationcraft/simc#5832]
### Describe the bug
Shadow blades damage is really high with a vulnerability event and (maybe) a short fight (~20 secs). The bug seems to dissapear if you extend the fight to 300 secs, but i am not sure if it really dissapears or gets mitigated.

### To Reproduce
Unexpected behaviour: https://www.raidbots.com/simbot/report/9Rg74EFLXwsqZuaq3kvHXr

Here it seems the bug dissapears but not sure: https://www.raidbots.com/simbot/report/nyzTijrnbJreBy9rmQhQUv

### Additional information
* SimulationCraft Version (required)

Mar 7 2021 Nightly (902-01)

**Comment by Mystler** [comment]
Fixed in e080d8489e1ed8aebcb2a56309499cc88ff51d4c.
