### ISSUE TITLE
(Venthyr Hunter conduit) Empowered Release

### ISSUE THREAD

**Issue by Fakie123** [simulationcraft/simc#5839]
### Describe the bug
Upon simming with the conduit, the amount of kill shots goes from 16 -> 17 which seems like a very small increase compared to what you would expect.

### Expected behavior
going from 15 -> 22% proc chance is pretty significant, i would imagine there would certainly be more than 1 extra proc over a 5 minute fight especially given flayed shot now lasts longer.

### To Reproduce
sim with the conduit vs without and be disgusted :D

### Additional information
Weekly (905-01)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Pewtro** [comment]
The conduit works as it should in the sim, I see a 14 -> 18 kill shot when equipped the conduit. 
If you can provide more information, we can reopen this issue. 
https://www.raidbots.com/simbot/report/qYEHaeHzQE2tdbX3kcQC6v/simc
