### ISSUE TITLE
Arcane Harmony changes, calculations are not reflecting the % change

### ISSUE THREAD

**Issue by Theamara81** [simulationcraft/simc#5840]
9.0.2 simulation
https://www.raidbots.com/simbot/report/63vxfpBVaUZ2Lu8bdf7i12/simc

9.0.5 simulation
https://www.raidbots.com/simbot/report/g7jxvaUypn39NBDRsLDL5i/simc

The maximal Arcane Barrage hit with stacked harmony was 
9.0.2 - 82729 (supposed to be 15 stacks of 7% buff to arcane barrage)
9.0.5 - 98228 (supposed to be 18 stacks of 8% buff to arcane barrage)

The difference should be around 37% but it is roughly 19% in the sim, which seems to not be correct and more corresponding to a situation, where the max stack is set correctly to 18 but the dmg increase per stack is set to 7%.

This doesn't seem to be right as according to the changes the max hit should be something about 82729/(15x7)x(18x8)=113 456

**Comment by vituscze** [comment]
19% buff is exactly right, you might want to double-check the math.
