### ISSUE TITLE
Frost Nova is considered "Harmful Action"

### ISSUE THREAD

**Issue by Jackcornellober** [simulationcraft/simc#5860]
Although frost nova deals 79 damage, it is currently used from out of range of the boss by mage players in situations where they want to proc Disciplinary Command pre-pull.

There is currently no way (that I know of) for me to proc DC pre-pull because Fire mages have 0 "Non-Harmful" frost spells. 

Ice block/ring of frost would work, but they aren't recognized when I enter them.

**Comment by vituscze** [comment]
Frost Nova is intended to be a harmful action, it doesn't just proc DC but also enables Shatter and triggers Grisly Icicle.

**Comment by Jackcornellober** [comment]
Thanks for the reply Vituscze, I understand that it is intended to be that way, I suppose the "bug" I am reporting isn't with frost nova, it's with there being 0 non-harmful frost spells for a fire mage. Can we just throw iceblock or ring of frost into the spell list? Or perhaps is there a way for me to manually proc DC pre-pull instead?

**Comment by vituscze** [comment]
Added in 11db4058606f74c425c97cf228a22fa6371e31c1
