### ISSUE TITLE
Grimoire: Felguard duration is 15 sec instead of 17

### ISSUE THREAD

**Issue by basdehaan** [simulationcraft/simc#5865]
### Describe the bug
The felguard from the demonology talent Grimoire: Felguard has a 15 second duration

### Expected behavior
The duration should be 17 seconds.

### To Reproduce
Check the base duration of the buff in any demo lock sim that uses the talent. Example: https://www.raidbots.com/simbot/report/pHTh6XbT9hLVLLVrxTQmxr/simc

### Additional information
SimC Version Weekly (905-01) - via raidbots.com

**Comment by Azevara** [comment]
This turned out to only be an issue with the dummy buff. Fixed in #5866
