### ISSUE TITLE
Druid NecroLord's Adaptive Swarm should have a higher uptime

### ISSUE THREAD

**Issue by mwertz83** [simulationcraft/simc#5886]
### Describe the bug
I believe adaptive swarm should have a higher up time. Every other cast should switch between the target and the player (or tank). This should bring the up time much closer to 100%. 

### Expected behavior
```
Time in seconds
0  First cast on the target (cast A)
13 Cast A migrates to player
25 Cast A migrates to target; cast a second swarm on player (Cast B)
37 Cast A migrates to player; Cast B migrates to target
48 Cast A expires
49 Cast A is refreshed on target; Cast B migrates to player
61 Cast A migrates to player; Cast B migrates to target 
72 Cast B expires
<repeat 25-36 and so on>
```

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Throw away all reason for not going night fae and getting convoke.

### Additional information
* SimulationCraft Version (required)
April 06, 2021
https://www.raidbots.com/simbot/report/dRNn5ekciXeQcTGGDRPUb6

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Jundarer** [comment]
You are ignoring flight times at certain parts which can and will introduce gaps. Distance can play a big role here and the apl was created while being at 30m at all times. If you can provide a log or apl change that achieves a higher uptime please do.

**Comment by Jundarer** [comment]
Closing due to no answer for 1 month. If you have more input don't hesitate to comment again.
