### ISSUE TITLE
Trinket “Hymnal of the Path” Not Simming

### ISSUE THREAD

**Issue by kentaaa94** [simulationcraft/simc#5902]
Hello! I recently received a trinket on my Blood Elf Paladin, and wanted to find out if it was a DPS increase. One of his trinkets is “Hymnal of the Path”, which (at mine’s ilvl 174) has +74 Vers. and its effect is that your damaging abilities have a chance to deal 2,169 Holy damage while you’re above 50% health, or heal for 3,388 health when under 50%. However, when I attempted to sim my character, this damage proc will not show up, no matter how many times/tries/or ways I attempt. It simply shows up as a +74 Vers stat stick, and therefore ANY trinket i swap it with (even ones MUCH lower ilvl) sim considerably higher than this trinket, because it’s equip effect isn’t added to DPS output. All other proc trinkets sim just find. Any help/insight would be greatly appreciated!

**Comment by gastank** [comment]
The trinket should sim correctly if you're using a current build of either simc itself or raidbots.
