### ISSUE TITLE
[MM Hunter] Vulpera APL improvement

### ISSUE THREAD

**Issue by mwoetzel** [simulationcraft/simc#5914]
I suggest lowering the priority of the Vulpera racial ability `Bag of Tricks`:

Remove it from highest priority `actions.cds` and add it to the normal priority lists at a lower position, i.e., penultimate position of `actions.st` and `actions.trickshots`.

I see a tiny DPS gain (~5 DPS), but most importantly it makes the opener & rotation much smoother.

Here is a report with the current APL: https://www.raidbots.com/simbot/report/mhbZAWGfANzqTYg8dkAnF1
Report with lower `Bag of Tricks` priority as suggested: https://www.raidbots.com/simbot/report/3uxDVpZWxE2LmMKb9oNdQq

In addition, this aligns with the BM APL, where `Bag of Tricks` is already part of the normal prioritiy lists for single target and AoE.

**Comment by Pewtro** [comment]
Fixed in 2039a0213c3769d9c2b8c1df9b52d9aa874d5625
