### ISSUE TITLE
Simc output ingame has default 0 renown

### ISSUE THREAD

**Issue by Terarrc** [simulationcraft/simc#5932]
### Bug
-----------
When I use /simc and get the string to sim on raidbots.com the sim doesn't have the +6% bonus health from renown levels.
But on the other hand when I pull the string directly with the name of my character, I do get the +6% stamina.

The issue is visibly tied to the string you get ingame. (I'm renown 40)

### Issue created 
--------------------
Now what is the problem with having 6% missing stamina ...?

For 99% of the simulations you won't ever notice the difference since stamina scaling is very niche.
But Demonology warlocks with Demonic Consumption see their DPS scale really well with stamina, thus it is a stat interesting to consider while simming. 

With that 6% Stamina missing I sim about 1% / 60dps lower right now.
And it obviously makes micro opti biased towards a lower stamina build.

### Confirmation with other player 
I have tested this with other Demonlogy player and they indeed sim higher with a "server - name" pulled string from Raidbot rather than the /simc one from ingame.

### Additional information 
------------------------------
I use the latest simc version available on CurseForge.
And so did other players.

My simc strings if that helps :
--------------------------------
/simc in game : https://pastebin.com/nm6XmfYF
converted to simc from raidbots : https://pastebin.com/K0UNvcb5

**Comment by vituscze** [comment]
Please open an issue in the simc addon repository (you can just give a brief overview and link to this issue): https://github.com/simulationcraft/simc-addon
