### ISSUE TITLE
Effusive Anima Accelerator Seg Faults as a Priest

### ISSUE THREAD

**Issue by seanpeters86** [simulationcraft/simc#5958]
### Describe the bug
While simming a Kyrian Priest simc seg faults.

### Expected behavior
It should not seg fault :)

### To Reproduce
```
ptr=1

priest="Base"
level=60
role=spell
position=back
talents=2131322
spec=shadow
covenant=kyrian
soulbind=forgelite_prime_mikanikos,107:9/115:9/333950/333935/352186/352188
```

### Additional information
Seg fault is thrown [here](https://github.com/simulationcraft/simc/blob/shadowlands/engine/player/soulbinds.cpp#L1315) under `string_view`/`strlen` due to a nullptr.

**Comment by seanpeters86** [comment]
CC: @Saeldur @Dorovon

**Comment by Dorovon** [comment]
This should be fixed in https://github.com/simulationcraft/simc/commit/0e5ff04eb53aa655ee99428222ce8e22c34796dc.
