### ISSUE TITLE
Plague-Etched Set not Simming

### ISSUE THREAD

**Issue by CrystalBearer** [simulationcraft/simc#5962]
The Plague-Etched set bonus is not simming. The 2-weapon set is available via WQ, and therefore will scale with ilvl.

**Comment by scamille** [comment]
This is probably just not implemented, see #4994. Since it is not really something used in higher-end content, I don't think it will be implemented anytime soon even if it is now available via WQ.

**Comment by gastank** [comment]
This is implemented in e593570 but requires further verification & testing as to how the damage value is calculated. Leaving the issue open until people can confirm.
