### ISSUE TITLE
SV APL Issue with Nesingwary's Trapping Apparatus

### ISSUE THREAD

**Issue by 87golfgt** [simulationcraft/simc#5976]
### Describe the bug
While simming SV with Nesingwary's Trapping Apparatus, Simulations with Mongoose bite work fine, Steel trap, Freezing trap, and Tar trap are all used as expected.

However when not talented into Mongoose bite, Raptor strike does not include Freezing trap and Tar trap in its rotation.

### Expected behavior
When talented into tip of the spear, or flanking strike both Freezing and Tar trap should be in the rotation. 

### To Reproduce
https://www.raidbots.com/simbot/report/9cht7uJLUxytdSQY1gthRr
Moongoose strike talented, Traps used correctly as seen in sample sequence V, W, X.

https://www.raidbots.com/simbot/report/azMkN7qCWAyEy8pM5QBFCD
Tip of the spear talented, Only Steel trap used sample sequence L.

### Additional information
World of Warcraft 9.1.0.38872 PTR (hotfix 2021-06-02/38872, git build d8c4c921aa)

**Comment by Pewtro** [comment]
Fixed in fe84dcd4840ca151c52e9af1f984190a42467191
