### ISSUE TITLE
[Warlock] Scouring Tithe is being vastly under-used

### ISSUE THREAD

**Issue by gandalfwg** [simulationcraft/simc#6046]
### Describe the bug
Scouring Tithe is being under cast. During a 5 minute simulation, it's only being cast 3.5 times for an uptime of ~20%.

### Expected behavior
Scouring Tithe (on a boss with no target switching) has an effective CD of only 18 seconds (since the CD refreshes if the target isn't dead at the end of the DoT) and should have an uptime above 70% (my real tests clock it in at around ~80% because it's my lowest priority). It seems like the only damage that Scouring Tithe is doing is related to the the uptime of the buff (which can only happen once every minute) which is accurate in the simulation. But this means that a massive amount of the potential damage is being lost (4 times as much damage in my real life testing vs the simulation).

### To Reproduce
Run any Warlock simulation with the Bastion Covenant and look at the Executes vs the possible Executes for a 18 second CD.

### Additional information
* SimulationCraft Version: 910-01 (git build 126481b)

* **simc_gui.simc** file or contents
[simc_gui.txt](https://github.com/simulationcraft/simc/files/6757868/simc_gui.txt)

**Comment by Vanishoxyact** [comment]
Looks to be an issue with pelagos and the APL, where it holds scouring tithe for tyrant
```
actions.covenant_ability+=/scouring_tithe,if=soulbind.combat_meditation&pet.demonic_tyrant.active
actions.covenant_ability+=/scouring_tithe,if=!soulbind.combat_meditation
```

**Comment by basdehaan** [comment]
the difference with using it on cd was 4 dps. using it with tyrant guarantees the mastery buff when you most need it.

**Comment by basdehaan** [comment]
https://www.raidbots.com/simbot/report/gGZiWddhXdqCKCSmFyHFFq
https://www.raidbots.com/simbot/report/6sEukZjZKkDJRHnscA8fLH

**Comment by basdehaan** [comment]
seems the difference got bigger with the patch:
tithe with tyrant: https://www.raidbots.com/simbot/report/mm4oMQNvofjnroXBRrk8Se
tithe on cd: https://www.raidbots.com/simbot/report/fxsco2APgKfToaLvJxzjc5

**Comment by gandalfwg** [comment]
That makes sense, I wasn't thinking about specifically lining up the mastery buff with Tyrant. Thanks for looking into this!
