### ISSUE TITLE
Trinket "Unchained gladiator badge of ferocity" behaving poorly

### ISSUE THREAD

**Issue by ManuelVs** [simulationcraft/simc#6076]
### Describe the bug

The trinket "[Unchained gladiator badge of ferocity](https://www.wowhead.com/item=185197/unchained-gladiators-badge-of-ferocity?bonus=7313:1505:6646&ilvl=233)" (PvP trinket Season 2) gets worse results than "[Sinful Gladiator's Badge of Ferocity](https://www.wowhead.com/item=175921/sinful-gladiators-badge-of-ferocity?bonus=6626:1485:6646&ilvl=213)" (PvP trinket Season 1).

I consider this unlikely since the new trinket has more "Critical strike" and its buff give more "Strength" when activated.

### Expected behavior

I consider the DPS calculated should be greater with the new trinket than with the old one.

### To Reproduce

* Actual Raidbots simulation: https://www.raidbots.com/simbot/report/bcbUuFJT2QbrN5ijeSB5XZ
* Trigger a raidbots simulation with both trinkets selected:
```
# Zannaffer - Retribution - 2021-07-10 01:26 - EU/Zul'jin
# SimC Addon 9.1.0-01
# Requires SimulationCraft 910-01 or newer

paladin="Zannaffer"
level=60
race=blood_elf
region=eu
server=zuljin
role=attack
professions=herbalism=150/inscription=100
talents=3211313
spec=retribution

covenant=kyrian
soulbind=pelagos:7,328266/216:5:0/328261/129:6:0/328265/182:6:0/133:6:0/328257/176:5:0
# soulbind=kleia:13,329791/216:5:0/334066/159:7:0/328258
# soulbind=forjador_supremo_mikanikos:18,
# conduits_available=164:5/167:6/176:5/177:5/182:6/184:5/193:5/194:5/195:5/216:5/284:5/196:6/142:5/159:7/161:5/163:5/129:6/133:6/141:5/197:5/209:5/283:8
renown=45

head=,id=178812,gem_id=173128,bonus_id=7351/7359/6652/6935/1530/6646
neck=,id=178827,bonus_id=7359/6652/7194/7385/1527/6646
shoulder=,id=178802,bonus_id=7359/6652/7369/1521/6646
back=,id=183033,enchant_id=6202,bonus_id=7188/6652/1485/6646
chest=,id=171412,enchant_id=6230,bonus_id=7064/6758/6649/6648/1532
wrist=,id=183018,gem_id=173128,bonus_id=7189/6652/6935/1472/6646
hands=,id=178775,enchant_id=6210,bonus_id=7375/7359/6652/1540/6646
waist=,id=179326,bonus_id=7373/7359/6652/7193/1534/6646
legs=,id=183002,bonus_id=7188/43/1485/6646
feet=,id=178774,bonus_id=7375/7359/6652/1540/6646
finger1=,id=179355,enchant_id=6166,bonus_id=7359/6652/7194/7385/1527/6646
finger2=,id=178869,enchant_id=6166,gem_id=173128,bonus_id=7359/6652/6935/7387/1534/6646
trinket1=,id=178771,bonus_id=7359/6652/7373/1534/6646
trinket2=,id=185197,bonus_id=7313/1505/6646
main_hand=,id=178866,enchant_id=6228,bonus_id=7416/7359/6652/1537/6646

### Gear from Bags
#
# Distintivo de victoria de Gladiador pecaminoso (213)
# trinket1=,id=175921,bonus_id=6626/1485/6646
#
```

### Additional information
* SimulationCraft Version (required)

[Commit e48e016a76](https://github.com/simulationcraft/simc/commits/e48e016a76)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by vituscze** [comment]
Trinket works correctly. Try again with a newer simc that includes https://github.com/simulationcraft/simc/commit/f5bba092d74f8d9b557a3ae8b91f1d976a121eec
