### ISSUE TITLE
Update build instructions for ubuntu

### ISSUE THREAD

**Issue by drnick88101** [simulationcraft/simc#6082]
The build instructions on the wiki are incorrect. For ubuntu it says to install qt5 all you have to do is: sudo apt install qt5-default

If you try to build you will get this error though:
**CMake Error at qt/CMakeLists.txt:11 (find_package):**
**  Could not find a package configuration file provided by "Qt5WebEngine" with**
**  any of the following names:**

**    Qt5WebEngineConfig.cmake**
**    qt5webengine-config.cmake**

**  Add the installation prefix of "Qt5WebEngine" to CMAKE_PREFIX_PATH or set**
**  "Qt5WebEngine_DIR" to a directory containing one of the above files.  If**
**  "Qt5WebEngine" provides a separate development package or SDK, be sure it**
**  has been installed.**

**-- Configuring incomplete, errors occurred!**

In order to build it you also need to do this: sudo apt install qtwebengine5-dev

**Comment by scamille** [comment]
Thanks for reporting this. I adjusted the wiki page in https://github.com/simulationcraft/simc/wiki/HowToBuild/_compare/660ec81%5E...660ec81
