### ISSUE TITLE
Destro Warlock Sim CDs Never Allign

### ISSUE THREAD

**Issue by zhangeric1994** [simulationcraft/simc#6091]
### Problem
I saw the latest sim for destro warlocks on simulationcraft.org, and found out that in a 6-min fight our Dark Soul and Summon Infernal have only been cast at the same time at the very beginning. But in the real case, we always want to allign our big CDs by either pushing the Dark Soul to 3 mintue or by delaying Summon Inferno to 4 mintue. Also, we also want to use our trinket with our big CDs.

### Solution
Make warlock sims allign those CDs and trinket usage properly according to the fight duration. For example, in a 5 minute or 6 minute fight, we should cast Dark Soul at 0, 2, 4 mintue and Summon Inferno at 0, 4 mintue while, in a 7 minute fight, we should cast Dark Soul at 0,2,4,6 and Summon Inferno at 0,3,6.

**Comment by Azevara** [comment]
With the current default profile, there is no noticeable difference seen in holding infernal to 4 minutes on a fixed 5 minute fight length, see here: https://www.raidbots.com/simbot/report/b2q3jtZ4jKXvwjVrvzsQW3

Timings can be adjusted if there is evidence to be found for gains, but as of right now it is not clear that this would be an improvement.

**Comment by zhangeric1994** [comment]
I always use my own priority list which just gives more dps if I play NF on single target fights. https://github.com/zhangeric1994/simc_warlock/blob/main/warlock_9.0 You can try to use this and test again. 发件人: Azevara发送时间: 2021年9月15日 18:17收件人: simulationcraft/simc抄送: Zheyu Zhang; Author主题: Re: [simulationcraft/simc] Destro Warlock Sim CDs Never Allign (#6091) With the current default profile, there is no noticeable difference seen in holding infernal to 4 minutes on a fixed 5 minute fight length, see here: https://www.raidbots.com/simbot/report/b2q3jtZ4jKXvwjVrvzsQW3Timings can be adjusted if there is evidence to be found for gains, but as of right now it is not clear that this would be an improvement.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Azevara** [comment]
Closing old issue as 9.2 has changed things significantly for Destruction rotation.
