### ISSUE TITLE
[DK FROST]  Cold Heart

### ISSUE THREAD

**Issue by GermainP277** [simulationcraft/simc#6092]
![image](https://user-images.githubusercontent.com/65245996/125833048-c67e1cbf-c08d-4b49-96d6-bf1742c0ac02.png)
Firsts Cold Heart stacks are not printed.

profil : [simc.txt](https://github.com/simulationcraft/simc/files/6825250/simc.txt)

logs : https://www.raidbots.com/simbot/report/h3ydNiGsiMCvmJHRqZ76ji

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
