### ISSUE TITLE
[Trinket] The Time Duration Before Soulletting Ruby Takes Effect is Unreasonably Long

### ISSUE THREAD

**Issue by zhangeric1994** [simulationcraft/simc#6093]
### Describe the bug
As the title states, the time duration before soulletting Ruby Takes Effect is Unreasonably Long (alsmost 8s) with 'position=back'. In fact, in real fights, the time is usually 2s.

### Expected behavior
The delay time should be more reasonable.

### To Reproduce
Just run a warlock sim with Ruby I think.

### Additional information
git build: https://github.com/simulationcraft/simc/commit/fdfcb02ea9

* **simc_gui.simc** file or contents
https://www.raidbots.com/simbot/report/nhj5zQyaYtcs9mzoAQw8xc/simc

**Comment by vituscze** [comment]
`position` has no impact on spell travel time, you're looking for `distance`. Default value for warlocks is most likely 30.

Game data claims the projectile speed is 5.6 yd/s, which would mean the travel time is about 5 seconds. Is the projectile faster than that? Or is there an upper limit on the travel time?

```
Name             : Soul Fragment (id=345802) [Hidden]
School           : Shadow
Spell Type       : None
Range            : 40 yards
Velocity         : 5.6 yards/sec
Triggered by     : Soulletting Ruby (345801)
```

**Comment by vituscze** [comment]
I have confirmed that the trinket indeed takes as long as 8 seconds to reach the target. I'm gonna close the issue. If you want to reduce the travel time in sims, use the `distance` option mentioned previously.

**Comment by zhangeric1994** [comment]
But it tells me `distance` is invalid in RaidBots.

**Comment by vituscze** [comment]
Try expert mode, pre-actors section
