### ISSUE TITLE
[Demon Hunter] T27 Momentum gear set has not been updated.

### ISSUE THREAD

**Issue by CarlDizL** [simulationcraft/simc#6095]
The gear set within T27 Dh momentum build is exactly the same as T26. Where as the Demonic T27 build has the updated gear set.

**Comment by EvanMichaels** [comment]
This was intentional as it was disabled in the stack charts for T27. However, I updated it in https://github.com/simulationcraft/simc/commit/17498d3866ecb3894de04157f449864a452686bd just for completeness.
