### ISSUE TITLE
Necrolord VDH cold heart interaction

### ISSUE THREAD

**Issue by viperjason** [simulationcraft/simc#6107]
![image](https://user-images.githubusercontent.com/55452088/126431280-d1fb0c34-91da-4f4e-bdfc-2323909d830e.png)

Every time the demon spawns it is considered a new enemy.  In game, you can not insta-kill it with throw glaive or else the demon doesn't count.  However if you let it survive for 2-3 seconds so it can get hit by immolation aura or sigil of flame then you can get the cold heart buff to trigger.

So under the optimal scenario, every time you trigger a demon soul you should also have a cold heart.

**Comment by EvanMichaels** [comment]
In SimC the buff is just faked because we did not want to deal with additional add spawning and there weren't really any notable interactions. But at this point, it does seem like this may need to be revisited to allow for certain procs.
