### ISSUE TITLE
Codex of the First Technique is not implemented

### ISSUE THREAD

**Issue by srenauld** [simulationcraft/simc#6108]
### Describe the bug
[Codex of the first Technique](https://www.wowhead.com/item=185836/codex-of-the-first-technique?bonus=6805), a 9.1 trinket, currently has its spellData incorrectly set to absorb X damage and immediately gets removed on sims (example [here](https://www.raidbots.com/simbot/report/5vBrAgubk9fpVmMwCsEhMz/simc)).

The actual trinket behavior is a buff that, while the buff is active, reflects X damage from each melee hit. You can see it in action [on this log](https://www.warcraftlogs.com/reports/1vz3PYDqJnWbGyjt#fight=7&type=damage-taken&translate=true&source=227&pins=2%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24101659169.0.0.DeathKnight%24false%24351316%24true%24false%5E0%24Separate%24%23909049%24damage%240%240.0.0.Any%24101659169.0.0.DeathKnight%24true%240.0.0.Any%24false%24351450%5E0%24Separate%24%23a04D8A%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24101659169.0.0.DeathKnight%24false%24351316&view=events)

I tried with Melekus to fix it myself but I'm, sadly, out of my depth :-(

### Expected behavior
The trinket should be providing a buff lasting 12 seconds, that reflects 10% of the damage taken in that time, each hit capped to the trinket's absorb value in spellData

### To Reproduce
Log showing the behavior: https://www.warcraftlogs.com/reports/1vz3PYDqJnWbGyjt#fight=7&type=damage-taken&translate=true&source=227&pins=2%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24101659169.0.0.DeathKnight%24false%24351316%24true%24false%5E0%24Separate%24%23909049%24damage%240%240.0.0.Any%24101659169.0.0.DeathKnight%24true%240.0.0.Any%24false%24351450%5E0%24Separate%24%23a04D8A%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24101659169.0.0.DeathKnight%24false%24351316&view=events

### Additional information
* SimulationCraft Version: 9.1 nightly ( SimulationCraft 910-01 for World of Warcraft 9.1.0.39427 Live (hotfix 2021-07-16/39427) )

**Comment by scamille** [comment]
Can you please provide a .simc input file to reproduce this?
The raidbots link is outdate I think.

**Comment by srenauld** [comment]
> Can you please provide a .simc input file to reproduce this? The raidbots link is outdate I think.

https://www.raidbots.com/simbot/report/iS6GGhFmpoJAZ3njHFLxby

You can clearly see in the report that the buff instantly disappears without either honouring how it works on live (it has no cap) or reflecting damage. With 50k effective DTPS one would expect the trinket to easily be top in terms of sources of damage.
