### ISSUE TITLE
Support hardcast counterspell

### ISSUE THREAD

**Issue by jaehunkim** [simulationcraft/simc#6115]
### Is your feature request related to a problem? Please describe.
Though counterspell included in Fire Mage [APL](https://github.com/simulationcraft/simc/blob/a8738999e0c03bac4faa6f8aa2bc5c0bae456c2c/profiles/Tier27/T27_Mage_Fire.simc#L101), it never executed even once in my scenario.
Counterspell is the best way to enable Disciplinary Command, since it does not trigger global cooldown. 
I think it's just because there's no spell to interrupt in patchwerk scenario.

### Describe the solution you'd like
Support hardcast counterspell.

### Describe alternatives you've considered
I've considered casting shimmer instead of counterspell, but it disturbs ROP buff.

**Comment by vituscze** [comment]
The CastingPatchwerk fight style exists (partly) for this reason. Is that good enough to solve your problem?

**Comment by jaehunkim** [comment]
Problem solved perfectly
