### ISSUE TITLE
can not find the buff in buffs list

### ISSUE THREAD

**Issue by windpc319** [simulationcraft/simc#6125]
trinket2=,id=171323,bonus_id=7461,drop_level=60
SpellID=299789
It's seems worked,But dose not show the buff's detail information.
simc-901-01-win64-7bd7371

![1628837930(1)](https://user-images.githubusercontent.com/43026915/129316693-9fdc5dc7-afc6-4fa1-a895-4ae285b8d33b.png)

**Comment by windpc319** [comment]
It's seems worked,But dose not show the buff's detail information.

**Comment by windpc319** [comment]
simc-901-01-win64-7bd7371

**Comment by vituscze** [comment]
The buff seems to be there. What exactly is the problem?

![image](https://user-images.githubusercontent.com/4149104/130256348-79c6ec5e-be34-4660-b145-fec1a0c8b615.png)

**Comment by windpc319** [comment]
The exactly problem is my poor English,I just want to find the buff iocn,but ignore the name.
Thank you for your answer.
