### ISSUE TITLE
Titanic Ocular Gland Buffed Wrong Stat When Equipped With Old Warriors Soul

### ISSUE THREAD

**Issue by yuyuyzl** [simulationcraft/simc#6126]
### Describe the bug
It seems the stat that simc choose to buff is different from the stat in game.

Old warriors soul will give player a 40 haste buff at combat start, and simc use the base haste + 40 haste from the trinket, to decide the stat that Titanic Ocular Gland should add to, and the result is 815+40>840.

While in game, the Worthy buff from Titanic Ocular Gland is applied before combat start, and it buffed mastery before haste buffed by Old Warriors Soul. Then, Titanic Ocular Gland will compare the buffed mastery(840+132) with buffed haste(815+40), and continue buffing mastery until Old warriors soul stacks enough haste more than 840+132, then change to Worthy(_haste_rating)

### Expected behavior
Always calculate and buff the highest stat before combat starts.
eg. In the profile below, at combat start, the buff should be Worthy(_mastery_rating).

### To Reproduce
[simcissue.txt](https://github.com/simulationcraft/simc/files/6988006/simcissue.txt)

### Additional information
* SimulationCraft Version (required)
* (hotfix 2021-08-05/39653, git build f33ae9a)

**Comment by yuyuyzl** [comment]
Well, it seems simply switch the position of the trinkets will solve this problem

Good: trinket1=titanic_ocular_gland trinket2=old_warriors_soul
Bad: trinket2=titanic_ocular_gland trinket1=old_warriors_soul

**Comment by gastank** [comment]
fixed in b22447f
