### ISSUE TITLE
Fire Mage: Possible conditional issue for Necrolord

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#6133]
The condition for Fireball, found at the link below, is not likely to work as intended.

https://github.com/simulationcraft/simc/blob/b55b743edd822e16bf33c36f63fe60e54a80b814/profiles/Tier27/T27_Mage_Fire.simc#L231

If SimC evaluates left-to-right, then `variable.time_to_combustion<buff.deathborne.remains` would evaluate to 1 or 0, then the remaining test would be `1>=2` or `0>=2`, or always false/0.

I assume the intention is to check `variable.time_to_combustion<buff.deathborne.remains` and `buff.deathborne.remains>=2`.

**Comment by Dorovon** [comment]
Good catch, it should have been the same as the rop_phase line, which checks the number of targets there.
```
actions.rop_phase+=/fireball,if=buff.deathborne.up&runeforge.deaths_fathom&variable.time_to_combustion<buff.deathborne.remains&active_enemies>=2
```
This is fixed in https://github.com/simulationcraft/simc/commit/8b2b2ac231f50252716e2a5eeef065d0e398ef88
