### ISSUE TITLE
Balance Druid's IQD Trigger Bugs

### ISSUE THREAD

**Issue by HanJinjing** [simulationcraft/simc#6136]
### Describe the bug
Balance Druid's IQD trinket is triggered in the wrong way. Currently, mastery buff will be triggered no matter how much mastery the profile has.
First, the situation without bloodlust. For instance, if it has 1000 haste, 900 crits, 400 mastery, 100 vers, there will be 50% to trigger haste (which is correct), 40% to trigger crit (incorrect), 10% to trigger mastery (incorrect).
Then, the situation with bloodlust. For instance, if it has 1000 haste, 900 mastery, 200 crits, and 100 vers, there will be a 90% or 80% percent chance to trigger haste, the rest to trigger mastery.

### Expected behavior
When with bloodlust, IQD will always trigger the biggest stats.
When without bloodlust, IQD will have a 50/50 chance to trigger the two biggest stats. 

### To Reproduce
Personally, I went to a WOD raid to test this. By wipe and leave the boss area, cooldowns for bloodlust (I use drums) and IQD will reset. I tested like 40 times for each situation. 

### Additional information
* SimulationCraft Version (required)
* 2021-8-10 windows 64 version

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
Profile I used for simulating no bloodlust situation:
```
druid=
level=60
race=troll
role=spell
professions=alchemy=175/engineering=100
talents=1333332
spec=balance

covenant=venthyr
soulbind=癫狂公爵西塔尔:9,336239/259:9:1/336147/280:9:0/336247/271:9:0/257:9:0/319983/262:9:0/351748/283:9:0/351750
renown=62

head=,id=186292,gem_id=187318,bonus_id=7187/6652/1498/6646
feet=,id=186363,enchant_id=6207,gem_id=187310,bonus_id=7188/42/1485/6646
finger1=,id=144392
trinket1=,id=184842,bonus_id=6652/1472/5891/6646
trinket2=,id=179350,bonus_id=7359/6652/7606/1560/6646

combat_lenth=100
```

Profile I used for simulating bloodlust situation:
```
druid=
level=60
race=troll
role=spell
professions=alchemy=175/engineering=100
talents=1333332
spec=balance

covenant=venthyr
soulbind=癫狂公爵西塔尔:9,336239/259:9:1/336147/280:9:0/336247/271:9:0/257:9:0/319983/262:9:0/351748/283:9:0/351750
renown=62

head=,id=186292,gem_id=187318,bonus_id=7187/6652/1498/6646
neck=,id=178707,gem_id=173128,bonus_id=7622/7359/6652/1566/6646/7576
shoulder=,id=186298,gem_id=187287,bonus_id=7187/6652/1498/6646
back=,id=178851,enchant_id=6203,bonus_id=7622/7359/6652/1566/6646
chest=,id=186296,enchant_id=6230,gem_id=187302,bonus_id=7188/6652/1485/6646
shirt=,id=4336
tabard=,id=69210
wrist=,id=186362,enchant_id=6220,gem_id=173128,bonus_id=7187/6652/1498/6646/7576
hands=,id=186295,enchant_id=6205,gem_id=187309,bonus_id=7188/42/1485/6646
waist=,id=172320,gem_id=173128,bonus_id=7474/6649/6648/6935/7451/1559
legs=,id=179324,bonus_id=7359/6652/7591/1560/6646
feet=,id=186363,enchant_id=6207,gem_id=187310,bonus_id=7188/42/1485/6646
finger1=,id=178870,enchant_id=6168,gem_id=173128,bonus_id=7622/7359/6652/1566/6646/7576
finger2=,id=186290,enchant_id=6168,gem_id=173128,bonus_id=7188/6652/7576/1485/6646
trinket1=,id=184842,bonus_id=6652/1472/5891/6646
trinket2=,id=179350,bonus_id=7359/6652/7606/1560/6646
main_hand=,id=178714,enchant_id=6229,bonus_id=7650/7359/6652/1566/6646

combat_lenth=100
```

**Comment by vituscze** [comment]
The simc implementation of the trinket works exactly as you described. It seems you forgot to take into account this soulbind ability: https://www.wowhead.com/spell=336239/soothing-shade
