### ISSUE TITLE
[Demo Warlock] Opener casts Call Dreadstalkers immediately after Summon Vilefiend instead of first building to five shards

### ISSUE THREAD

**Issue by fzarr** [simulationcraft/simc#6138]
Theoretically a better opener would be to cast 2 Shadowbolts after Summon Vilefiend and before Call Dreadstalkers for the chance to proc Demonic Calling, and it may also prolong the Dreadstalkers for a slightly longer Demonic Consumption timing window.

**Comment by Azevara** [comment]
Handled by #6147
