### ISSUE TITLE
monk necrolord

### ISSUE THREAD

**Issue by roces43** [simulationcraft/simc#6164]
Hello i see that monk necrolord rotasion isn't working that well,any chance of update the rotasion? thnx you!

**Comment by scamille** [comment]
Action Priority lists are part of the input to the simulation. You can always adjust them yourself and see if you can get more DPS with a different priority.

If you find improvements, raidbots link are a great tool to show the difference. We even accept pull requests for changes, see https://github.com/simulationcraft/simc/blob/shadowlands/CONTRIBUTING.md#action-priority-list-apl

**Comment by seanpeters86** [comment]
rip shadowlands
