### ISSUE TITLE
10-29 nightly build fails to authenicate

### ISSUE THREAD

**Issue by mickking06** [simulationcraft/simc#6188]
### Describe the bug
Get a 401 when trying to import a character from bleeding hollow saying bearer token failed to be retrieved

### Expected behavior
Expected character to import for sims

### To Reproduce
Select US, Bleeding Hollow, and character and hit import after a fresh download of simcraft. Failed to auth user. 

### Additional information
* SimulationCraft Version (required) 910-01 running in win8 compatibility mode on windows 10

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by mickking06** [comment]
Here is the error from the log
Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/bleeding-hollow/restituti%C3%B6n?namespace=profile-us&locale=en_US'.: Unable to authorize: Unable to fetch bearer token from https://us.battle.net/oauth/token, response=401, error=, result=

**Comment by scamille** [comment]
Thanks for reporting this, I will fix it.

**Comment by scamille** [comment]
Fixed, new nightly has been uploaded.
