### ISSUE TITLE
Download Button Not Working

### ISSUE THREAD

**Issue by seanren78** [simulationcraft/simc#6267]
### Describe the bug
When I click download for simcraft, the screen refreshes, but does not start download
### Expected behavior
Clicking download, the program should verify I want to download it, then the program should be downloaded

### To Reproduce
Easy to recreate, press "download" and watch nothing happen

### Additional information
, simc-901-01-win64-7bd7371.7z 

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions n/a

* **simc_gui.simc** file or contents
n/a I cannot download

**Comment by scamille** [comment]
Please get the latest version of SimulationCraft at https://www.simulationcraft.org/download.html and try again. Today that would be `simc-915-01-win64-822f037.7z`.
