### ISSUE TITLE
Frost Mage Cold Front Legendary interaction with Deathborne bug

### ISSUE THREAD

**Issue by flollef** [simulationcraft/simc#6269]
### Describe the bug
The simcraft implemention of the interaction between deathborne and the cold front mage legendary does not match the in-game behavior.

### Expected behavior
In-game behavior appears to vary between two scenarios. I am always assuming that 3 targets are hit by frostbolt.

Type 1 seems to occur when the player is closer to the target:
Cold Front Stacks after consecutive frostbolts->
0, 3, 6, 9, 12, 15, 18, 21, 24, 27, orb triggers with 0 stacks after, 3, 6, 9, 12 etc

Type 2:
Cold Front Stacks after consecutive frostbolts->
0, 3, 6, 9, 12, 15, 18, 21, 24, 27, cold front trigger buff, orb triggers with 3 stacks after, 6, 9, 12, etc

Essentially what appears to be happening is that the orb is triggering one cast later in type 2, but is at the same stack level in the next step because it fires off the orb _and_ grants 3 stacks in the following cast

Neither of these in-game behaviors appears to match what is happening in the simulation. In the sim:
Cold Front Stacks after consecutive frostbolts->
3, 6, 9, 12, 15, 18, 21, 24, 27, 1, 4, 7, 10, 13, etc

An extra stack is gained in the sim after the orb triggers that is not seen in the in-game testing.

### To Reproduce
Testing was conducted on stormwind target dummies.

### Additional information
* SimulationCraft Version (required)
simc-915-01-win64

**Comment by vituscze** [comment]
Fixed in 0adef64f12db45ef9565a55277c0a1fb49907def
