### ISSUE TITLE
Frost Mage Cold Front Legendary Prepull Implementation

### ISSUE THREAD

**Issue by flollef** [simulationcraft/simc#6270]
### Is your feature request related to a problem? Please describe.
There does not appear to be a simple way to simulate a pull where the Cold Front legendary is precharged and ready to fire with the next cast of flurry or frostbolt.

### Describe the solution you'd like
Something similiar to what was done for Disciplinary Command or Arcane Harmony legendaries would be useful.

Disciplinary Command->
mage.prepull_dc=<0/1>

Arcane Harmony->
mage.prepull_harmony_stacks=<number>

**Comment by vituscze** [comment]
Are you aware that both of the Cold Front buffs expire when raid combat begins?

**Comment by flollef** [comment]
This is for M+
