### ISSUE TITLE
Dungeon Slice should allow disabling of class buffs

### ISSUE THREAD

**Issue by diab64** [simulationcraft/simc#6452]
### Describe the bug
First posted under raidbots here: https://github.com/seriallos/raidbots-issues/issues/324

Dungeon Slice sims with Bloodlust, Arcane Intellect, Power Word: Fortitude, and Battle Shout active, with no way for them to be unchecked. According to a post in the above-linked issue, this was originally because of the fact that if those classes were not in the group, groups would use scrolls to supplement those buffs. As this is no longer the case, you should be able to sim Dungeon Slice without those buffs in effect.

### Expected behavior
Expect to be able to check and uncheck Bloodlust, Arcane Intellect, Power Word: Fortitude, and Battle Shout from being used in the simulation, based on the group comp.

### To Reproduce
Run a simulation with Dungeon Slice and see results for active buffs: Bloodlust, Arcane Intellect, Power Word: Fortitude, Battle Shout

### Additional information
I am using Raidbots, but I was told that Raidbots is based on SimulationCraft, thus Raidbots cannot update without SimulationCraft updating.

![raidbotsbug](https://user-images.githubusercontent.com/44482861/157292306-455829cd-a348-46bc-b3b3-1c7c0cf5cdb2.JPG)

**Comment by JontiH** [comment]
I made a PR for this, seemed simple enough
https://github.com/simulationcraft/simc/pull/6708
