### ISSUE TITLE
wow addon imports won't simulate

### ISSUE THREAD

**Issue by ANaPhOrAX** [simulationcraft/simc#6453]
### Describe the bug
Imports from the wow addon don't work. Simulating them does nothing. Gets stuck at 0%, and if you hit cancel, the app even crashes. I tried one simulation with importing from the armory, to see if that did work, and it indeed worked fine. But I obviously can't always use the armory.

### Expected behavior
for the imported data to simulate normally

### To Reproduce
Don't have any logs, I looked at the log tab and there was nothing there.

### Additional information
* simc-920-01-win64
* latest version of the wow addon as well

**Comment by ANaPhOrAX** [comment]
I tried some more imports from the wow armory, and some do work, but for certain characters it'll give me this error:

> Profile will be downloaded into a new tab.
> 
> Clicking Simulate will create a simc_gui.simc profile for review.
> 
> Unable to generate profile from: 
> 
> Actor 'character': cannot write to file: bad file descriptor

**Comment by scamille** [comment]
Do you have write permission where you installed/extracted simc? It sounds there is a problem when writing output files.

It might also be that the path you installed/extracted simc to has some special characters. While this should in theory shouldn't be a problem, you might want to give it a try if you move Simc to a folder with only plain ASCII characters in it.
