### ISSUE TITLE
Ripped Secrets set bonus not implemented?

### ISSUE THREAD

**Issue by timwoj** [simulationcraft/simc#6476]
### Describe the bug

The set bonus damage from the Ripped Secrets daggers from Zereth Mortis doesn't appear in simc logs. The set bonus is this one https://www.wowhead.com/item-set=1508/ripped-secrets.

### Expected behavior

Damage from the bonus to appear.  An example log missing the damage is here: https://www.raidbots.com/simbot/report/sqiBDbDjZxykmRB64R1Hnv/simc

### To Reproduce

Add the two daggers to the equipment for a character and run a simulation.

### Additional information

* SimulationCraft Version (required): hotfix 2022-03-15/42698, git build [baf098a229](https://github.com/simulationcraft/simc/commit/baf098a229) (from the above log link)

**Comment by gastank** [comment]
implemented in 991ec63
