### ISSUE TITLE
Gemstone of Prismatic Brilliance trinket not implemented

### ISSUE THREAD

**Issue by dywolf1** [simulationcraft/simc#6483]
### Describe the bug
The trinket Gemstone of Prismatic Brilliance appears to not be implemented, or implemented incorrectly.

-The proc effect buff doesn't appear in the buff uptime report at all.
-Sim results are the same as if no trinket were equipped.

https://www.wowhead.com/item=190374/gemstone-of-prismatic-brilliance?bonus=6935

**Comment by gastank** [comment]
implemented back in 5c2bb00b8069a2da0a6282d59754684b776ef1b9

please re-open if you still cannot sim it after updating to latest nightly build.
