### ISSUE TITLE
Progentior Enchancements are not currently simmed.

### ISSUE THREAD

**Issue by Majoolwip** [simulationcraft/simc#6488]
With 9.2, gear can be crafted with powerful procs such as spawning a mote that grants 41 primary stat or summoning an regulated automa core that explodes dealing damage. Currently, these effects are not simulated and as such, determining which one to use is not very clear. Currently, the community seems to have settled on the primary stat buff though it seems bugged and has a delay when walking over it. It would be nice to quickly determine the dps loss/gain of each proc.

**Comment by scamille** [comment]
Closing this, as it is likely no longer relevant for dragonflight.

Sorry that you never got a better, timely response.
