### ISSUE TITLE
The trinket "Symbol of the Vombata" does not work

### ISSUE THREAD

**Issue by Tryxtira** [simulationcraft/simc#6498]
The proc of  the trinket Symbol of the Vombata (https://www.wowhead.com/item=190582/symbol-of-the-vombata) does not seem to work in SimC, making it impossible to sim trinkets when you have that equipped. 

Thank you!

**Comment by gastank** [comment]
Implemented in 459163a3df2e126d0951d81dddcb88aa41b9e3f0
