### ISSUE TITLE
Destruction Warlock AOE (5 target Patchwerk) spams Immolate

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#6513]
### Describe the bug

The default Destruction Warlock profile will spam Immolate in multi-target situations regardless of buff uptime or even attempting to multidot effectively.

### Expected behavior

Immolate should be used to apply/refresh Immolate on targets.  Sim testing/tuning is probably required to determine when to abandon multidotting this way (i.e., `fight_remains` or `target.time_to_die` is not sufficient to get damage out of the multiple DOTs).  However, immediately making the filler Immolate check whether the DOT is refreshable (and `cycle_targets`) is a significant multi-target gain (+67.6% DPS).

I also didn't test other talents/covenants/soulbinds/legendaries/etc., but it seems really unlikely that pure Immolate spam is "the play" for any of those scenarios.

### To Reproduce

![image](https://user-images.githubusercontent.com/9438134/161434147-7b58dde2-e8e4-4df5-840a-2403929efab8.png)

https://www.raidbots.com/simbot/report/ou69AFLgrgdzt2ssYVVbux

* https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/warlock/sc_warlock_destruction.cpp#L1333
* From: `aoe->add_action( "immolate");`
* To: `aoe->add_action( "immolate,cycle_targets=1,if=refreshable" );`

### Additional information
* SimulationCraft Version (required)

[56b28cac90](https://github.com/simulationcraft/simc/commits/56b28cac90)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

N/A

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

N/A

**Comment by Azevara** [comment]
#6514 will fix the spam. There are larger questions at play about what to do for AOE now that the Destruction tier set is in the wild which won't be resolved easily by this fix such as how many active immolates to cap cycling on etc. These will require future work.
