### ISSUE TITLE
warlock，Where is the vilefiend talent

### ISSUE THREAD

**Issue by gkh8936285** [simulationcraft/simc#6517]
### Describe the bug

**i see warlock simc,
actions+=/variable,name=buff_sync_cd,op=set,value=0,if=!variable.use_bolt_timings&variable.in_opener&pet.dreadstalker.active&buff.wild_imps.stack>0&!talent.vilefiend.enabled
Where is the vilefiend talent.**

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)
* 920-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Azevara** [comment]
This report is unclear, please provide a more complete description or this issue will be closed.

**Comment by gkh8936285** [comment]
> This report is unclear, please provide a more complete description or this issue will be closed.

warlock simc，for example：

actions+=/variable,name=buff_sync_cd,op=set,value=0,if=!variable.use_bolt_timings&variable.in_opener&pet.dreadstalker.active&buff.wild_imps.stack>0&!talent.vilefiend.enabled
actions+=/variable,name=buff_sync_cd,op=set,value=0,if=!variable.use_bolt_timings&variable.in_opener&pet.dreadstalker.active&prev_gcd.1.hand_of_guldan&talent.vilefiend.enabled

But I didn't find vilefiend talent，Could it be that it was written wrongly?

**Comment by Pewtro** [comment]
https://www.wowhead.com/spell=264119/summon-vilefiend

talent.vilefiend is in both the lines you posted.
