### ISSUE TITLE
Warrior tallent "fresh meat" doesnt work like intended

### ISSUE THREAD

**Issue by BohdanDiachun** [simulationcraft/simc#6519]
### Describe the bug
With tallent "fresh meat", first "bloodthirst" should always apply "enrage" but it doesnt happen.

### Expected behavior
"Fresh meat" tallent should make 1st bloodthirst always apply "enrage" buff

### To Reproduce
Sim warrior with "fresh meat" tallent. Keep in mind that "bloodthirst" has baseline chance to buff "enrage" and it will sometimes happen in sims(a lot of times actually since its 45% chance) but !first "bloodthirst" should !always be buffing "enrage"

### Additional information
SimulationCraft Version: Weekly (920-01)
https://www.raidbots.com/simbot/report/eWVHDsFLd6YxKb2eTRqC4s
https://imgur.com/a/nrr1FH2 (screenshot of the same sim in case link is broken)

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
