### ISSUE TITLE
Balance Druid Ardenweald not working

### ISSUE THREAD

**Issue by Tomathan14** [simulationcraft/simc#6532]
### Describe the bug
Balance druid sim with T-Set as Ardenweald not working correctly.
6 min Patchwerk results in 1.8k DPS. The Sim starts normal and prepares every buff/precast etc. After 5 seconds Convoke is castet.
After that nothing happens. After 4 Minutes  Celestial Alignment is off CD which is used, followed by another Convoke and thats it.

### Additional information
[SimulationCraft 920-01]
for World of Warcraft 9.2.0.43206 Live (hotfix 2022-04-19/43206, git build [850618a2f1]

[simc_gui.txt](https://github.com/simulationcraft/simc/files/8520745/simc_gui.txt)
![DPS](https://user-images.githubusercontent.com/104069573/164213601-45835227-c907-49ae-9b8d-2946a1bedc0b.png)
![Castsequence](https://user-images.githubusercontent.com/104069573/164213609-8ac79045-5733-4751-bdf5-0e0360bd6914.png)

**Comment by gastank** [comment]
This should be fixed with the latest nightly build.
