### ISSUE TITLE
Executing Arcane Explosion as Frostmage on Single Target

### ISSUE THREAD

**Issue by Texxer** [simulationcraft/simc#6538]
When playing with the Disciplinary Command Legendary as Frostmage, the Simulation wants to use Arcane Explosion to keep up the 20% Crit Damage Buff, although it is not necessary to cast any Arcane Spells at all since the Incanter's Flow Talent automatically proccs once every second.

Also, without that talent, the Simulation should consider using Counterspell instead of Arcane Explosion since it wouldn't consume a GCD and could be lined up every single time since the CD of the spell is shorter than the CD of the procc.

**Comment by vituscze** [comment]
Counterspell will be used if you use a fight style that lets the actor use it (such as CastingPatchwerk). I've fixed the Incanter's Flow issue in https://github.com/simulationcraft/simc/commit/fc3473895e3b299c12a60f7056d4759044ae0dd0
