### ISSUE TITLE
Warrior APL adding trinket logic

### ISSUE THREAD

**Issue by Bont1234** [simulationcraft/simc#6540]
Currently the warrior APL does not have any trinket logic, it will pop on use trinkets at 00:00:00 and then pop them again as soon as they come up.

This wastes like 1-2 GCDS during the opener, which is a minor 20-30 DPS loss compared to actual use. The problem comes in with longer sims, If ur running a 7-minute sim, which would be the correct choice for something like mythic rygelon, with a trinket like the first sigil, it will do the second use at 5 minutes flat. Regardless of cooldowns, It would be a significant gain if the APL held this trinket until the next avatar/recklessness cast at 6 min.

![image](https://user-images.githubusercontent.com/104497949/165500209-580d7961-93c5-494e-90b0-376fb9087cec.png)
![image](https://user-images.githubusercontent.com/104497949/165500264-4e4de07b-ce91-464a-b04f-48b53ea83b38.png)

I'd generate a pull request myself if i knew how to fix it in the code. But i can't get it working myself.

https://www.raidbots.com/simbot/report/n2v5NXvQ1EsxgC1Ly42c5R without trinket logic

https://www.raidbots.com/simbot/report/aJRSNvPaMPy8FrYE9VabgA With trinket logic

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
