### ISSUE TITLE
Kyrian Subtlety Rogue uses Slice and Dice finisher on anima-charged CPs when it gains no benefit

### ISSUE THREAD

**Issue by kel8458** [simulationcraft/simc#6555]
### Describe the bug
Slice and Dice does not benefit from anima-charged combo points. Finishing on one with SnD does not consume it, and does not generate a 7CP SnD. The APL runs the finishers based on "effective_combo_points" which takes into account if the current combo point is anima-charged. The finishers list contains Slice and Dice and does not check for actual combo points.

Perhaps it actually doesn't matter and SnD uptime is all that counts but it does feel weird for it to be "trying" to use the anima-charged CP on it.

### Expected behavior
Slice and Dice should ignore anima-charged combo points. I modified the APL (no idea if I did it properly, haven't done this before) by adding an actual combo point check before the SnD casts (combo_points.deficit<=1) on Lines 124 and 125 and it resulted in a negligible DPS improvement on 5 min Patchwerk sims (+7). Could this be explored and improved further by somebody who knows what they are doing?

```
Line 124: actions.finish+=/slice_and_dice,if=combo_points.deficit<=1&!variable.premed_snd_condition&spell_targets.shuriken_storm<6&!buff.shadow_dance.up&buff.slice_and_dice.remains<fight_remains&refreshable
Line 125: actions.finish+=/slice_and_dice,if=combo_points.deficit<=1&variable.premed_snd_condition&cooldown.shadow_dance.charges_fractional<1.75&buff.slice_and_dice.remains<cooldown.symbols_of_death.remains&(cooldown.shadow_dance.ready&buff.symbols_of_death.remains-buff.shadow_dance.remains<1.2)
```

### To Reproduce
Simply run the current Subtlety Rogue APL on a 10min Patchwerk to confirm its occurrence. It's rare, but here's an example: 
![image](https://user-images.githubusercontent.com/25411980/168945754-a0470660-1408-4855-80ce-bcbd192e84f2.png)

### Additional information
Weekly (920-01)

**Comment by soloxcx** [comment]
The Outlaw APL does this as well, but for both specs there is no dps difference beyond 0.05% margin of error so I suppose it was just left alone.

**Comment by EvanMichaels** [comment]
This is currently neutral or a gain just due to the fact that if SnD is within pandemic it's basically always worth casting regardless of CP. This just happens to check earlier than normal but ends up doing the same thing in the long run.
