### ISSUE TITLE
[Monk] Slow dbc/vector lookups during iterations (e.g., player_t::find_spell)

### ISSUE THREAD

**Issue by Dorovon** [simulationcraft/simc#6564]
There are several instances of slow lookups happening repeatedly during iterations in the monk module (`player_t::find_spell`, `buff_t::find`, etc.). These are likely significantly slowing down monk simulations that use these sections of code.

`blackout_kick_t::impact` has a `find_spell` usage here.
https://github.com/simulationcraft/simc/blob/7df2bff49b4d0a23eab02c0ab26ae6fdc8efce04/engine/class_modules/monk/sc_monk.cpp#L1773

`bountiful_brew_t::execute` has two usages of `find_spell`, one `find_soulbind_spell`, and one `buff_t::find`. Specifically for Lead By Example, I would recommend calling `buff_t::find` once during `bountiful_brew_t::init_finished` to set a `buff_t*` pointer and during `bountiful_brew_t::execute` you can check if it is a `nullptr` or not before triggering it.
https://github.com/simulationcraft/simc/blob/7df2bff49b4d0a23eab02c0ab26ae6fdc8efce04/engine/class_modules/monk/sc_monk.cpp#L4088-L4102

`bountiful_brew_t::impact` has a `find_spell` usage here.
https://github.com/simulationcraft/simc/blob/7df2bff49b4d0a23eab02c0ab26ae6fdc8efce04/engine/class_modules/monk/sc_monk.cpp#L4108

`chi_burst_damage_t::impact` has a `find_spell` usage here.
https://github.com/simulationcraft/simc/blob/7df2bff49b4d0a23eab02c0ab26ae6fdc8efce04/engine/class_modules/monk/sc_monk.cpp#L5170

`monk_t::composite_player_target_pet_damage_multiplier` has two usages of `find_spell` here.
https://github.com/simulationcraft/simc/blob/7df2bff49b4d0a23eab02c0ab26ae6fdc8efce04/engine/class_modules/monk/sc_monk.cpp#L7943-L7949

**Comment by scamille** [comment]
Great research, but why not just make this into a PR? From my past experience, the monk module has always been rather understaffed and the maintainers were happy if things at least worked somehow, even if the code and performance haven't been perfect. Assuming that is still the case, don't hesitate to just improve things yourself :-)

**Comment by Dorovon** [comment]
Yeah, that might be a good idea. I don't have profiles on hand to get coverage of all of these parts to make sure that a modified version works, but I suppose if it's in a PR that might not be necessary, especially since the changes are pretty simple.
