### ISSUE TITLE
[Ret Paladin] Wake of Ashes damage does not scale down for targets beyond the first

### ISSUE THREAD

**Issue by fulletron** [simulationcraft/simc#6566]
I believe what I am seeing is that the damage caused by Wake of Ashes is not properly calculated beyond the first target. 

While trying to optimize my Wake of Ashes damage, I noticed I could never get close to the damage shown in the damage breakdown against 5 target dummies (while all the abilities were close, wake of ashes was off by 50%).

Using the Custom APL and SimC options, I added:
actions=wake_of_ashes
actions+=/wake_of_ashes

to ensure I only used wake. The rest of the setup was 1 or 2 target dummies, 20 seconds, no buffs. I ran two tests:

1 Target Dummy Sim:
https://www.raidbots.com/simbot/report/dRY48zkpf9QrUvZyEBcKLg

2 Target Dummy Sim:
https://www.raidbots.com/simbot/report/vFL4YLUnQBTmgo9CzCsJsJ

2 Target Dummy Sim Details:
https://www.raidbots.com/simbot/report/vFL4YLUnQBTmgo9CzCsJsJ/simc

These tests showed a linear increase in damage from one to two targets, even though that isn't possible with the actual in game wake of ashes, due to 
![image](https://user-images.githubusercontent.com/5178701/170803228-71e96511-cb01-4084-99b9-cab3128b98a6.png)

Here are relevant Screenshots:
![Wake_of_ashes_1](https://user-images.githubusercontent.com/5178701/170803117-cc4bfec2-5d73-4d14-ad8b-83758e12054a.png)

![Wake_of_ashes_2](https://user-images.githubusercontent.com/5178701/170803126-052e0996-1574-47a5-a6f8-aa3e4cd496bd.png)

![Wake_of_ashes_3](https://user-images.githubusercontent.com/5178701/170803128-df1d0c79-cab3-45fa-b8d4-af5bb91148f7.png)

Hopefully this is the right place for this information. Thanks for reading.

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
