### ISSUE TITLE
Arms Warrior 2+ Target Cleave MS improvment

### ISSUE THREAD

**Issue by killer1209** [simulationcraft/simc#6604]
[###_](url) Describe the bug

Arms 2+ Target DPS- Currently with 2+ targets MS is currently only being recommending when sweeping strike buff is up. and when deep wounds is about to fall off
https://i.imgur.com/0ESbWGI.png

The current sim rotation will only whirlwind and overpower when sweepy strike is not up.

It is a dps increase to continue to use Mortal strike pretty much on cd even when sweepy strike is not available

### Expected behavior
Mortal Strike should be used pretty much on cooldown even without sweeping strike.

When no CD's are available and sweepy strike is on CD Mortal Strike should continue to be used

I think the following lines need to be added

actions.hac+="/mortal_strike,if=runeforge.enduring_blow|runeforge.battlelord|buff.overpower.stack>=2"
actions.hac+="/mortal_strike"

https://i.imgur.com/XdsZazA.png

### To Reproduce
https://www.raidbots.com/simbot/report/kQt6xDhrvET59vgkTuuhk9

This is a log of the default sim plus i did a small edit to make it MS on cd. That change alone increased the dps by 749 almost 5%. My knowledge is very limited with editing the api but i feel like you could fine tune it and increase the dps even more 
https://i.imgur.com/pxUzHXW.png

### Additional information
* weekly version(required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

Does not Crash

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
[simc MS improvment.txt](https://github.com/simulationcraft/simc/files/9060311/simc.MS.improvment.txt)

**Comment by seanpeters86** [comment]
Closing due to being stale, if still needed feel free to reopen.
