### ISSUE TITLE
Docker build for Dragonflight branch failling

### ISSUE THREAD

**Issue by Horaddrim** [simulationcraft/simc#6683]
### Describe the bug
Trying to build the Docker image for the Dragonflight branch is currently failing due to an error on using old spells with the new version of the engine.
From what I could gather from my currently superficial understanding of the code is that by using the "T26_raid.simc" file in the LLVM profilling run in the build, you ran into an error related to the Arcane mage talents as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/25853444/187083750-a8e16d9c-df2c-4297-a7a5-c182f5c4b848.png)

I think the fact it's reporting for the Arcane mage is unrelated to the mage simulation itself, probably just the first thing to break.

If anyone can provide me any guidance on what is nice to have on this profilling run, I can try to adapt the simc file itself to not use any of the old spells but still generate a good profilling, but this is probably better to get done by more experienced members of the community 😅 

### Expected behavior
The Docker image build succesfully.

### To Reproduce
Command used: `docker build -t simc-dragonflight .`

### Additional information
* SimulationCraft [commit](https://github.com/Horaddrim/simc-dragonflight/commit/5389ac2d45247c7df81587fe7b963d0e5fc847ce)
* The full build log from my CI tool: [link to log](https://00f74ba44bc15be11490666f4138c0a6f8f2bc39e8-apidata.googleusercontent.com/download/storage/v1/b/864051914506.cloudbuild-logs.googleusercontent.com/o/log-7d95692a-7202-4872-8f1a-a99048b72fc7.txt?jk=AFshE3W-T3VTcEev7pZARaLycyiSVeZJ1SCMKDMWCmPVTbPrNo306soG0tUHbZ9fiC6dMmmI5up08u9XboF2dKwWh8yE8OFQjzDO4neogDs2h3MiH_ArcxxBRsb8WufIjAv8_u8NZbITbxIFrhe7voKlMRvd5aXWrJvEK4MgVqFjRyieyVcNWe6_-2zMXXrgAj4J9uk0kcA3L3UNCqB6OiGA9_cYH2W1lV0x-GUx2bBhyq8VB8rhGQM96dGlYNH9ypsi2K-tcdSLuttyb6bIekHKkyE-yWvpnU-APmw-P9nvBdTPyW0rfdOVM01bcWLrsix-RnwpY-MzXApifiN_nOf6I85bYptO6VdJLzOZRR1Xs_vYBkebQOK-QiryXu23YaUuHcDKigwgt5nwnlYgJ1iiA_9K-q-6oZIVXom_3SM0XgLJA0ViqSNsVI2WEJN8xAmiuVjE7g5VT-xehEo9RyldwPmgGLunQ9-2-qxpkKWNmAWMWNGPoA-HkomJi5tfk1K8aZ3ow2aOl1b-JmsQ8pwoYYxayFTlBKUyeIQ3U_x4yRqH0zUskwqgx7xVejX9aBMRnq7WmmpoT_SnkQu5qDAevAnIypyZWeZAuYb5taFkotQv1HyeAXZnXRncF9bqQYtiSkuMBdAsVuK0h9S-i29d3CIapLPKtiBbFb4oS567w284T5_zhEqlXKKwvE2TaBMKvbT-PekLLZNNPG7H-EcPRLB9n4VKnaXmRbefsQeyjoSJ-0yH8XWbTsy3akTGsjORW1ek9GbiMjlY_W5Xc93L78n1ibGcR1f6pc6ncogBPjpEoVhOgb1aIEJwNVhtaYfbO_Sn627kCn4IKcJT7IJ40VOGmExfG7Mo055KRviYeAUxYhx-3rE4G1UbfrBv4d3YrZrwic2GXQRCxaO4A3AXSkT2UFMtHd_t1spVNlQHETzlW7CQLNR18lke8UvoqthMyr-_akyobjyOt1MpEy5owdBpglfzbOS-TJ4fyYShI3P3DQJ6i0MmnnUloowK3fIQJThxkuUc-Qq8T4T0BLVV7j4VyQZZEbCu-VpkHmAFNOrw9m8HSpP_HZN2C1SjWCCf&isca=1)

**Comment by scamille** [comment]
Please check if 28c114d4a287fc914f41646f9b1259fd91afd125 resolves the issue for you. Unfortunately I currently don't have docker set up to test it.

**Comment by JontiH** [comment]
hey @Horaddrim , on https://github.com/simulationcraft/simc/commit/28c114d4a287fc914f41646f9b1259fd91afd125#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R49

you put {$PGO_PROFILE} instead of ${PGO_PROFILE}. this causes error:
```
Error: Unexpected parameter '{}'. Expected format: name=value`
```
when building. Even after fixing that, it still fails with error
```
Error: Nothing to sim!
The command '/bin/sh -c cd /app/SimulationCraft/engine && LLVM_PROFILE_FILE="code-%p.profraw" ./simc ${PGO_PROFILE} single_actor_batch=1 iterations=100' returned a non-zero code: 1
```

**Comment by JontiH** [comment]
I made a folder of really basic simc files to get the docker image to build. Let me know what you think

**Comment by Horaddrim** [comment]
I loved the solution! This will address not only my issue, but also the breaking changes going forward not messing with the build :) tyvm
