### ISSUE TITLE
Bug: Destruction Warlock - Cataclysm being cast with no cooldown in a 40 seconds hectic Addcleave sim.

### ISSUE THREAD

**Issue by HakiFox** [simulationcraft/simc#6713]
Looking at the spell rotation in a 40 seconds hectic addcleave sim I saw cataclysm being cast as every other spell when it should have a 30 second cooldown. Yet it is nowhere to see in the damage breakdown.
This showed both in the nightly and weekly setting.

My sim: https://www.raidbots.com/simbot/report/sfYC41skUNnVxEzANFZWTi

**Comment by vituscze** [comment]
None of those casts finish because there's movement raid event happening every second. So what you're seeing is expected.

Hectic add cleave wasn't really meant to be used with such short fight lengths.

**Comment by Azevara** [comment]
Closing as this is an APL issue and HAC is not supported in this manner.
