### ISSUE TITLE
Nightly release builds are pointing towards the shadowlands branch instead of the dragonfight branch.

### ISSUE THREAD

**Issue by JH2535** [simulationcraft/simc#6970]
### Describe the bug
On the simulationcraft download page https://www.simulationcraft.org/download.html the when you click the link "[Simulationcraft nightly builds are found here](http://downloads.simulationcraft.org/nightly/?C=M;O=D)" you see the realse constructed from the commit for the latest version is 948f6a8 which points towards this commit https://github.com/simulationcraft/simc/commit/948f6a8f56db6760f0a79c3a8f25ec66dd05e90b - the latest commit in the shadowlands branch.

Due to shadowlands branch not being updated since the talent system change happened when you download the applications "current" nightly version it's broken throwing errors saying "Simulation runtime error: Unable to decode talent string 'BQQAU3BjZ/IAySQ6AmAmsjvQ+BAAABJBQSCJtkkIJBSISAkIAAAAAAAJBpRJJIJJpFAAAA' for player 'Grumphray'.Setup failure: Unknown option 'talents' with value 'BQQAU3BjZ/IAySQ6AmAmsjvQ+BAAABJBQSCJtkkIJBSISAkIAAAAAAAJBpRJJIJJpFAAAA'." - this is because it's still using the old talent system.

### Expected behavior
I believe it's time to use the latest dragonflight commit to create a build to be released. That *should* at least resolve this error.  (currently the most recent commit as of writing this in the dragonflight branch is: https://github.com/simulationcraft/simc/commit/15ad268584e3a337c5ba3a4397422a2dc608455c

### To Reproduce
* Click on http://downloads.simulationcraft.org/nightly/?C=M;O=D
* Note the build at X: simc-920.01.XXXXXXX-win64.7z - it's currently 948f6a8
* This should be 15ad2685

(Note: Instructions on how to build from the github project would be appreciated)

**Comment by scamille** [comment]
Changed in https://github.com/simulationcraft/simc-publish/pull/14
Currently, both shadowlands and dragonflight are built - but we'll probably disable the former soon.

The docker build still needs to be fixed in dragonflight, see https://github.com/simulationcraft/simc-publish/issues/17

**Comment by JH2535** [comment]
Thank you <3
