### ISSUE TITLE
Evoker/Devastation Heavy Add Cleave error.

### ISSUE THREAD

**Issue by Pandaabear0** [simulationcraft/simc#6988]
### Describe the bug
When trying to simulate an Evoker with the Devastation spec on the Heavy Add Cleave profile, SimulationCraft(simc-1000.01.d2a14cb-win64) spits out this error:

# SimulationCraft encountered an error!
 # SimulationCraft 1000-01 for World of Warcraft 10.0.0.46455 Live (hotfix 2022-11-05/46455, git build dragonflight d2a14cb) * Category: Simulation runtime error * Error: Player Drakform unable to download item id=201759 information from Blizzard, reason: The document is empty. primalist_oathsworn cannot add stat from effect
 #1: STAT_NONE  cannot add stat from effect#1: STAT_NONE Error in child simulation (1): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (10): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (31): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (12): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (4): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (16): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (2): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (13): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (30): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (3): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (14): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (27): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (24): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (5): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (6): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (22): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (19): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (9): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (18): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (7): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (17): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (8): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (25): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (23): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (26): Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute. Error in child simulation (15): Non-channeling action eternity_surge_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute.Non-channeling action fire_breath_damage for Player 'Drakform' is trying to overwrite player-ready-event upon execute.  #
 # All options used for simulation: ``` ini ##
 # SimulationCraft 1000-01 for World of Warcraft 10.0.0.46455 Live (wow build 46455, git build dragonflight d2a14cb)  ### ##
 # Using QT 6.4.0 with WebEngine ###  ### Begin GUI options ##
 # ptr=0 item_db_source=ptrhead/local/bcpapi/wowhead target_error=0.05 iterations=0 default_world_lag=0.05 max_time=300 vary_combat_length=0.2 fight_style=HecticAddCleave tmi_window_global=6 target_level+=3 target_race=Humanoid optimal_raid=0 override.bloodlust=1 override.arcane_intellect=1 override.power_word_fortitude=1 override.battle_shout=1 override.mark_of_the_wild=1 override.windfury_totem=1 override.bleeding=1 override.mortal_wounds=1 override.chaos_brand=1 override.mystic_touch=1 threads=32 process_priority=Low statistics_level=1 ##
 # End GUI options ### ### Begin simulateText ### 
 # Drakform - Devastation - 2022-11-09 01:08 - us/Valdrakken 
 # SimC Addon 10.0.0-3 # WoW 10.0.2.46479, TOC 100002 # Requires SimulationCraft 1000-01 or newer  evoker="Drakform" level=70 race=dracthyr region=us server=valdrakken role=spell professions=leatherworking=100/jewelcrafting=100 spec=devastation  talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiWIJikQCJRSJJ5AtESJkIhkASSSSESSC
   # Saved Loadout: Preheat Boss Talent # talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDEAAAAAAoogkISSkQSSSLJRDSJRikIJcAkkkEhkkA 
 # Saved Loadout: New New M+ # talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiWIJikQCJRSJJ5AtESJkIhkASSSSESSC # Saved Loadout: Raid ST
 # talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiSKkIkQCJJJtkENhUCJSIJEkkkEhkkA # Saved Loadout: Firestorm # talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDEAAAAAAopgkISSIJSSSJJRLhUCJSIJgkkkEhkkA  covenant=necrolord 
 # conduits_available= renown=80  head=,id=200381,bonus_id=1463/8767 neck=,id=201759,gem_id=192988/192967/192967,bonus_id=8836/8840/8902/8784/8782/8802/8793,crafted_stats=40/36 shoulder=,id=200383,bonus_id=1463/8767 back=,id=193511,enchant_id=6592,bonus_id=8836/8840/8902/8802/8791,crafted_stats=40/32 chest=,id=200378,enchant_id=6619,bonus_id=1466/8767 tabard=,id=5976 wrist=,id=193428,enchant_id=6574,bonus_id=8836/8840/8902/8802/8793,crafted_stats=32/40 hands=,id=200380,bonus_id=1466/8767 waist=,id=193425,bonus_id=8836/8840/8902/8802/8793,crafted_stats=40/36 legs=,id=200382,enchant_id=6541,bonus_id=1472/8767 feet=,id=201507,bonus_id=9008/6652/9009/1498/8767 finger1=,id=193000,enchant_id=6550,gem_id=192967,bonus_id=8836/8840/8902/8780/8802/8791,crafted_stats=36/32 finger2=,id=195480,bonus_id=6652/7936/7979/1472/8767 trinket1=,id=193757,bonus_id=6652/1643/8767 trinket2=,id=194301,bonus_id=6652/7979/1472/8767 main_hand=,id=195519,bonus_id=6652/7979/1472/8767  ### Gear from Bags # # Crimson Gladiator's Chain Helm (408) # head=,id=201510,bonus_id=9008/6652/7936/9009/1498/8767 # # Crimson Gladiator's Amulet (408) # neck=,id=201806,bonus_id=9008/6652/7936/8783/9009/1498/8767 # # Ancestor's Dew Drippers (392) # shoulder=,id=193459,enchant_id=6613,bonus_id=8836/8840/8902/8960/8802 # # Crimson Gladiator's Chain Monnion (408) # shoulder=,id=201514,bonus_id=9008/6652/9009/1498/8767 # # Shroud of the Awakened (389) # back=,id=200386,bonus_id=1472/8767 # # Crimson Gladiator's Chain Vest (408) # chest=,id=201504,bonus_id=9008/6652/9009/1498/8767 # # Crimson Gladiator's Chain Wristguards (408) # wrist=,id=201518,bonus_id=9008/6652/7936/9009/1498/8767 # # Crimson Gladiator's Chain Gauntlets (408) # hands=,id=201508,bonus_id=9008/6652/9009/1498/8767 # # Scale Rein Grips (392) # hands=,id=193465,bonus_id=8836/8840/8902/8960/8802 # # Clasp of Unity (265) # waist=,id=199551,bonus_id=6652/7578 # # Crimson Gladiator's Chain Belt (408) # waist=,id=201516,bonus_id=9008/6652/7936/9009/1498/8767 # # Crimson Gladiator's Chain Leggings (408) # legs=,id=201512,bonus_id=9008/6652/9009/1498/8767 # # Signet of Titanic Insight (392) # finger1=,id=192999,enchant_id=6550,gem_id=192967,bonus_id=8836/8840/8902/8780/8802/8791,crafted_stats=36/40 # # Seal of Filial Duty (405) # finger1=,id=195526,bonus_id=6652/7936/7979/1472/8767 # # Idol of the Earth Warder (392) # trinket1=,id=193006,bonus_id=8836/8840/8902/8802 # # Rumbling Ruby (389) # trinket1=,id=194303,bonus_id=6652/7979/1472/8767 # # Time-Breaching Talon (372) # trinket1=,id=193791,bonus_id=7977/6652/1594/8767 # # Darkmoon Deck: Watcher (372) # trinket1=,id=198089 # # Idol of the Dreamer (389) # trinket1=,id=193005,bonus_id=8836/8840/8902/8801 # # Conjured Chillglobe (389) # trinket1=,id=194300,bonus_id=6652/7979/1472/8767 # # Iceblood Deathsnare (389) # trinket1=,id=194304,bonus_id=6652/7979/1472/8767 # # Darkmoon Deck Box: Inferno (392) # trinket1=,id=194872,bonus_id=8836/8840/8902/8802 # # Spiteful Storm (398) # trinket1=,id=194309,bonus_id=7979/6652/1472/8767 # # Darkmoon Deck Box: Dance (392) # trinket1=,id=198478,bonus_id=8836/8840/8902/8802/8857 # # Horn of Valor (421) # trinket1=,id=133642,bonus_id=6652/3300/8767 # # Irideus Fragment (421) # trinket1=,id=193743,bonus_id=6652/1643/8767 # # Idol of Pure Decay (421) # trinket1=,id=193660,bonus_id=6652/1643/8767 # # Tome of Unstable Power (421) # trinket1=,id=193628,bonus_id=6652/1643/8767 # # Spoils of Neltharus (421) # trinket1=,id=193773,bonus_id=6652/1643/8767 # # Time-Breaching Talon (421) # trinket1=,id=193791,bonus_id=6652/1643/8767 # # Erupting Spear Fragment (421) # trinket1=,id=193769,bonus_id=6652/1643/8767 # # Furious Ragefeather (421) # trinket1=,id=193677,bonus_id=6652/1643/8767 # # Umbrelskul's Fractured Heart (421) # trinket1=,id=193639,bonus_id=6652/1643/8767 # # Infernal Writ (421) # trinket1=,id=137485,bonus_id=6652/3300/8767 # # Eye of Skovald (421) # trinket1=,id=133641,bonus_id=6652/3300/8767 # # Manic Grieftorch (398) # trinket1=,id=194308,bonus_id=7979/6652/1472/8767 # # Storm-Eater's Boon (395) # trinket1=,id=194302,bonus_id=6652/7979/1472/8767 # # Darkmoon Deck Box: Rime (392)
  # trinket1=,id=198477,bonus_id=8836/8840/8902/8802/8857 # # Broodkeeper's Promise (398) 
 # trinket1=,id=194307,bonus_id=7979/6652/1472/8767 # # Illuminating Pillar of the Isles (392)
  # main_hand=,id=194898,enchant_id=6655,bonus_id=8836/8840/8902/8802/8791,crafted_stats=32/40 
 # # Crimson Gladiator's Gavel (408) # main_hand=,id=201979,bonus_id=9008/6652/9009/1498/8767 # # Crimson Gladiator's Horn (408) # off_hand=,id=201980,bonus_id=9008/6652/9009/1498/8767 # # Kokia's Burnout Rod (389) 
 # off_hand=,id=193766,bonus_id=8965/7977/6652/1611/8767  ### Weekly Reward Choices  # Checksum: 13fe388b ### 
 End simulateText 
 ### desired_targets=1
  ###  Begin overrides 
 ### # User-specified persistent global and player parameters will be set here.  ### End overrides ### ### Begin final options ### ### End final options 
 ### ### END ###

### Expected behavior
To run the profile, I guess.

### To Reproduce
I just plucking in a Simc addon import profile into Simc, picking HeavyAddCleave as Fight Style and press "Simulate!" in the SimulationCraft Software(simc-1000.01.d2a14cb-win64).

### Additional information
* simc-1000.01.d2a14cb-win64

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  No crash.

* **simc_gui.simc** file or contents
https://pastebin.com/wf0M9P7a

**Comment by nyterage** [comment]
Live spell data does not include some items/spells from beta. 

Set `ptr=1` in the input to fix this.
