### ISSUE TITLE
[Elemental APL] Duplicate actions

### ISSUE THREAD

**Issue by Snoogens101** [simulationcraft/simc#7026]
### Describe the bug
There seems to be two actions which are identical, even if the descriptions of them aren't.
Line 103
`actions.aoe+=/lava_burst,target_if=dot.flame_shock.remains,if=buff.lava_surge.up&talent.deeply_rooted_elements.enabled`
Line 109
`actions.aoe+=/lava_burst,target_if=dot.flame_shock.remains,if=buff.lava_surge.up&talent.deeply_rooted_elements.enabled`

### Expected behavior
I'm not sure what the APL should actually be, however the one on line 109 will never be hit.

**Comment by Bloodmallet** [comment]
I somehow missed to add Windspeaker's Lav Resurgence to the first line .This is now fixed.
