### ISSUE TITLE
Azureweave Crafted Gear Effect is missing from the TODO sheet

### ISSUE THREAD

**Issue by fred-bonn** [simulationcraft/simc#7098]
There is a box in the TODO sheet that says "Something missing? Open an issue on GitHub!", so that is what I am doing.

The Azureweave Crafted Gear Effect is missing from the TODO sheet. I am not sure if this is because it has just been left out on the sheet or something else. Just pointing it out in the case that the effect might have slipped through the cracks.

EDIT: Also the Chronoweave set is missing.

**Comment by seanpeters86** [comment]
these were added a few weeks ago
