### ISSUE TITLE
Setup failure: Option 'level' with value '62': Option 'level' with value '62' not within valid boundaries

### ISSUE THREAD

**Issue by Wolke23** [simulationcraft/simc#7100]
SimulationCraft ist auf einen Fehler gestoßen!

Laufzeit-Fehler während der Simulation:
Setup failure: Option 'level' with value '62': Option 'level' with value '62' not within valid boundaries [1..60]

Wenn du denkst dass dieser Fehler ein Bug ist, öffne Bitte ein Ticket und kopiere den darunterliegenden Text.
Dieser beinhaltet alle Eingabe-Optionen der letzten Simulation und hilft uns das Problem nachzustellen.

# SimulationCraft encountered an error!
# SimulationCraft 902-01 for World of Warcraft 9.0.2.36753 shadowlands-BETA (hotfix 2020-11-25/36753, git build shadowlands b9137ba)
* Category: Laufzeit-Fehler während der Simulation
* Error: Setup failure: Option 'level' with value '62': Option 'level' with value '62' not within valid boundaries [1..60]

## All options used for simulation:
``` ini
### SimulationCraft 902-01 for World of Warcraft 9.0.2.36753 shadowlands-BETA (wow build 36753, git build shadowlands b9137ba)  ###
### Using QT 5.12.9 with WebEngine ###

### Begin GUI options ###
item_db_source=shadowlandshead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=0
override.power_word_fortitude=0
override.battle_shout=0
override.windfury_totem=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=0
override.mystic_touch=0
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Fearghul - Affliction - 2022-12-04 21:36 - EU/Nozdormu
# SimC Addon 10.0.2-04
# WoW 10.0.2.46924, TOC 100002
# Requires SimulationCraft 1000-01 or newer

warlock="Fearghul"
level=62
race=undead
region=eu
server=nozdormu
role=spell
professions=tailoring=13/enchanting=9
spec=affliction

talents=BkQAbtPS25JQs0VfQSDmhm+p3gcAyBOQkIBSLCINSSSaAAAAAHAAAAAAAAyBIJRkkkkUECAA


head=,id=199351,bonus_id=6652/7578/8936,drop_level=60
neck=,id=193809,bonus_id=9158/6652/7937/8783/1500/4785
shoulder=,id=199353,bonus_id=6652/8936,drop_level=60
back=,id=199386,bonus_id=6652/8936,drop_level=60
chest=,id=199348,bonus_id=6652/8936,drop_level=60
shirt=,id=89195
tabard=,id=45583
wrist=,id=193497,bonus_id=8837/8838/4785/8799,crafted_stats=40/32
hands=,id=199350,bonus_id=6652/8936,drop_level=60
waist=,id=199354,bonus_id=6652/7578/8936,drop_level=60
legs=,id=199352,bonus_id=6652/8936,drop_level=60
feet=,id=193498,bonus_id=8837/8838/4785/8799,crafted_stats=32/36
finger1=,id=199382,bonus_id=6652/7578/8936,drop_level=60
finger2=,id=199381,bonus_id=6652/7578/8936,drop_level=60
trinket1=,id=199555,bonus_id=6652/8936,drop_level=60
trinket2=,id=199645,bonus_id=6652/8936,drop_level=60
main_hand=,id=201307,bonus_id=6652

### Gear from Bags
#
# Umhang der Koordination (29)
# back=,id=65274
#
# Blutnarbengamaschen der Unvergleichlichkeit (170)
# legs=,id=176978,bonus_id=6907/42/1684,drop_level=60
#
# Beschwörergamaschen des Klingenschwurs (155)
# legs=,id=182272,bonus_id=7195/1472/6616
#
# Instabiler Elementarzusammenfluss (187)
# trinket1=,id=199686,bonus_id=7920
#
# Wendiges Rapier der Aurora (170)
# main_hand=,id=177809,bonus_id=6908/6652/1709,drop_level=60
#
# Überquellender violetter Braufestkrug (1)
# main_hand=,id=56836
#
# Blutverschmiertes Schwert des Hitzeschocks (170)
# main_hand=,id=178946,bonus_id=6908/6652/1699,drop_level=60

# Checksum: f7cb341a
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

 * Beta! Beta! Beta! Beta! Beta! Beta! 
 * Not All classes are yet supported. 
 * Some class models still need tweaking. 
 * Some class action lists need tweaking. 
 * Some class BiS gear setups need tweaking. 
 * Some trinkets not yet implemented. 
 * Constructive feedback regarding our output will shorten the Beta phase dramatically. 
 * Beta! Beta! Beta! Beta! Beta! Beta! 

DPS Ranking:
   1656 100.0%  Raid
   1656  100.0%  Fearghul_aktiv

HPS Ranking:
      0 100.0%%  Raid

Player: Fearghul_aktiv undead warlock affliction 60
  DPS=1655.6683450770784 DPS-Error=0.8273179221375645/0.05% DPS-Range=116.16129998624388/7.02%
  DPR=3.0579892268043296 RPS-Out=442.5759220477883 RPS-In=439.69830150039616 Resource=mana Waiting=0 ApM=38.88917747792173
  Origin: https://worldofwarcraft.com/en-gb/character/nozdormu/fearghul
  Talents: https://worldofwarcraft.com/en-us/game/talent-calculator#warlock/affliction/talents=0000000
  Covenant: invalid
  Core Stats:    strength=191|173(173)  agility=363|345(345)  stamina=1217|1217(1217)  intellect=1276|1163(1108)  spirit=0|0(0)  health=24340|24340  mana=50000|50000
  Generic Stats: mastery=56.71%|56.71%(514)  versatility=6.22%|6.22%(249)  leech=0.00%|0.00%(0)  runspeed=7.02%|7.02%(30)
  Spell Stats:   power=1276|1163(0)  hit=15.00%|15.00%(0)  crit=14.97%|14.97%(349)  haste=6.97%|6.97%(230)  speed=6.97%|6.97%  manareg=500|500(0)
  Attack Stats:  power=0|0(0)  hit=7.50%|7.50%(0)  crit=14.97%|14.97%(349)  expertise=7.50%|7.50%(0)  haste=6.97%|6.97%(230)  speed=6.97%|6.97%
  Defense Stats: armor=279|279(279) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=3.11%|3.11%(249)
  Priorities (actions.precombat):
    flask/food/augmentation/summon_pet/grimoire_of_sacrifice,if=talent.grimoire_of_sacrifice.enabled/snapshot_stats
    use_item,name=azsharas_font_of_power/seed_of_corruption,if=spell_targets.seed_of_corruption_aoe>=3&!equipped.169314/haunt
    shadow_bolt,if=!talent.haunt.enabled&spell_targets.seed_of_corruption_aoe<3&!equipped.169314
  Priorities (actions.default):
    call_action_list,name=aoe,if=active_enemies>3/phantom_singularity,if=time>30
    call_action_list,name=darkglare_prep,if=covenant.venthyr&dot.impending_catastrophe_dot.ticking&cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=covenant.night_fae&dot.soul_rot.ticking&cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=(covenant.necrolord|covenant.kyrian|covenant.none)&dot.phantom_singularity.ticking&dot.phantom_singularity.remains<2
    agony,if=dot.agony.remains<4/agony,cycle_targets=1,if=active_enemies>1,target_if=dot.agony.remains<4/haunt
    call_action_list,name=darkglare_prep,if=active_enemies>2&covenant.venthyr&(cooldown.impending_catastrophe.ready|dot.impending_catastrophe_dot.ticking)&(dot.phantom_singularity.ticking|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=active_enemies>2&(covenant.necrolord|covenant.kyrian|covenant.none)&(dot.phantom_singularity.ticking|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=active_enemies>2&covenant.night_fae&(cooldown.soul_rot.ready|dot.soul_rot.ticking)&(dot.phantom_singularity.ticking|!talent.phantom_singularity.enabled)
    seed_of_corruption,if=active_enemies>2&talent.sow_the_seeds.enabled&!dot.seed_of_corruption.ticking&!in_flight
    seed_of_corruption,if=active_enemies>2&talent.siphon_life.enabled&!dot.seed_of_corruption.ticking&!in_flight&dot.corruption.remains<4
    vile_taint,if=(soul_shard>1|active_enemies>2)&cooldown.summon_darkglare.remains>12/unstable_affliction,if=dot.unstable_affliction.remains<4
    siphon_life,if=dot.siphon_life.remains<4/siphon_life,cycle_targets=1,if=active_enemies>1,target_if=dot.siphon_life.remains<4
    call_action_list,name=covenant,if=!covenant.necrolord
    corruption,if=active_enemies<4-(talent.sow_the_seeds.enabled|talent.siphon_life.enabled)&dot.corruption.remains<2
    corruption,cycle_targets=1,if=active_enemies<4-(talent.sow_the_seeds.enabled|talent.siphon_life.enabled),target_if=dot.corruption.remains<2
    phantom_singularity,if=covenant.necrolord|covenant.night_fae|covenant.kyrian|covenant.none/malefic_rapture,if=soul_shard>4
    call_action_list,name=darkglare_prep,if=covenant.venthyr&(cooldown.impending_catastrophe.ready|dot.impending_catastrophe_dot.ticking)&cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=(covenant.necrolord|covenant.kyrian|covenant.none)&cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
    call_action_list,name=darkglare_prep,if=covenant.night_fae&(cooldown.soul_rot.ready|dot.soul_rot.ticking)&cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
    dark_soul,if=cooldown.summon_darkglare.remains>time_to_die/call_action_list,name=item
    call_action_list,name=se,if=debuff.shadow_embrace.stack<(2-action.shadow_bolt.in_flight)|debuff.shadow_embrace.remains<3
    malefic_rapture,if=dot.vile_taint.ticking/malefic_rapture,if=dot.impending_catastrophe_dot.ticking/malefic_rapture,if=dot.soul_rot.ticking
    malefic_rapture,if=talent.phantom_singularity.enabled&(dot.phantom_singularity.ticking|soul_shard>3|time_to_die<cooldown.phantom_singularity.remains)
    malefic_rapture,if=talent.sow_the_seeds.enabled/drain_life,if=buff.inevitable_demise.stack>40|buff.inevitable_demise.up&time_to_die<4
    call_action_list,name=covenant/agony,if=refreshable/agony,cycle_targets=1,if=active_enemies>1,target_if=refreshable
    corruption,if=refreshable&active_enemies<4-(talent.sow_the_seeds.enabled|talent.siphon_life.enabled)/unstable_affliction,if=refreshable
    siphon_life,if=refreshable/siphon_life,cycle_targets=1,if=active_enemies>1,target_if=refreshable
    corruption,cycle_targets=1,if=active_enemies<4-(talent.sow_the_seeds.enabled|talent.siphon_life.enabled),target_if=refreshable
    drain_soul,interrupt=1/shadow_bolt
  Priorities (actions.darkglare_prep):
    vile_taint,if=cooldown.summon_darkglare.remains<2/dark_soul/potion/fireblood/blood_fury/berserking
    call_action_list,name=covenant,if=!covenant.necrolord&cooldown.summon_darkglare.remains<2/summon_darkglare
  Priorities (actions.se):
    haunt/drain_soul,interrupt_global=1,interrupt_if=debuff.shadow_embrace.stack>=3/shadow_bolt
  Priorities (actions.item):
    use_items
  Actions:
    agony                               Count=  16.5| 18.549sec  DPE=3149|10.48%  DPET=2303  DPR=   6  pDPS=173  TickCount=   166  MissTick= 0.00%  Tick=   269|    48|   348  CritTick=   538|    95|   696|16.06%  UpTime= 99.69%
    corruption                          Count=  20.8| 14.657sec  DPE=2839|11.91%  DPET=2088  DPR=   6  pDPS=197  Miss= 0.00%  Hit=   292|   263|   373  TickCount=   165  MissTick= 0.00%  Tick=   277|    28|   350  CritTick=   553|    57|   699|16.09%  UpTime= 98.86%
    eternal_insight                     Count=  18.4| 15.823sec  DPE= 536| 1.99%  DPET=   0  DPR=   0  pDPS= 33  Miss= 0.00%  Hit=   462|   425|   463  Crit=   925|   850|   926|15.98%
    malefic_rapture                     Count=  29.4|  9.815sec  DPE=2851| 0.00%  DPET=2093  DPR=   0  pDPS=  0
    malefic_rapture_aoe                 Count=  29.4|  9.815sec  DPE=2851|16.90%  DPET=   0  DPR=   0  pDPS=279  Miss= 0.00%  Hit=  2459|  2327|  3124  Crit=  4908|  4654|  6248|16.00%
    putrid_burst                        Count=   3.4| 92.350sec  DPE=3091| 2.11%  DPET=   0  DPR=   0  pDPS= 35  Miss= 0.00%  Hit=  2699|  2699|  2699  Crit=  5398|  5398|  5398|14.52%
    shadow_bolt                         Count= 104.1|  2.834sec  DPE= 714|14.98%  DPET= 398  DPR=   1  pDPS=248  Miss= 0.00%  Hit=   613|   529|   774  Crit=  1222|  1057|  1547|16.17%
    summon_darkglare                    Count=   2.0|181.263sec  DPE=   0| 0.00%  DPET=   0  DPR=   0  pDPS=  0
    touch_of_the_grave                  Count=  17.8| 17.173sec  DPE= 450| 1.62%  DPET=   0  DPR=   0  pDPS= 27  Miss= 0.00%  Hit=   388|   339|   496  Crit=   774|   678|   992|16.09%
    unstable_affliction                 Count=  14.1| 21.941sec  DPE=7701|21.85%  DPET=5660  DPR=  15  pDPS=362  TickCount=   165  MissTick= 0.00%  Tick=   567|   533|   715  CritTick=  1130|  1065|  1430|16.11%  UpTime= 98.86%
   darkglare (DPS=440.00005085060855)
    dark_glare                          Count=  23.0|  9.023sec  DPE= 765| 3.55%  DPET= 471  DPR=   0  pDPS=440  Miss= 0.00%  Hit=   666|   564|   757  Crit=  1331|  1128|  1514|14.94%
   imp (DPS=242.10370515174512)
    firebolt                            Count=  86.9|  3.451sec  DPE= 834|14.62%  DPET= 533  DPR=  21  pDPS=242  Miss= 0.00%  Hit=   726|   678|   910  Crit=  1446|  1355|  1820|16.00%

  Constant Buffs:
    feast_of_gluttonous_hedonism/spectral_flask_of_power/veiled_augmentation
  Dynamic Buffs:
    bloodlust                    : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 40.0 uptime= 13.52%
    celestial_guidance           : start= 10.4 refresh=  6.1 interval= 28.2 trigger= 17.3 duration= 12.9 uptime= 44.55%
    flashfreeze                  : start=  2.3 refresh=  0.0 interval=153.5 trigger=153.5 duration= 23.9 uptime= 18.68%
    potion_of_spectral_intellect : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 25.0 uptime=  8.45%
  Up-Times:
      1.63% : Mana Cap                      
  Gains:
        30.6 : agony                      (soul_shard)   
    131908.9 : mana_regen                 (mana)           (overflow=11.82%)
         0.8 : unstable_affliction_refund (soul_shard)     (overflow=23.83%)
    Pet "darkglare" Gains:
         0.0 : energy_regen               (energy)         (overflow=100.00%)
    Pet "imp" Gains:
      3306.3 : energy_regen               (energy)       
  Scale Factors:
    Weights :  Int=1.2482232424524722(0.01053400333045218)  SP=1.1610897978070471(0.010495962500082091)  Crit=0.40066114473233744(0.01023064951824017)  Haste=0.5181547659545521(0.010244234932256135)  Mastery=0.45661605812835526(0.010206195319758613)  Vers=0.38530246104371874(0.010190757132532667)
    Wowhead : https://www.wowhead.com/?items&filter=ub=9;gm=3;gb=1;minle=250;ro=2;wt=23:123:96:103:170:215;wtv=1.25:1.16:0.40:0.52:0.46:0.39;
  Waiting:  0.00%

 *** Targets *** 

Target: Fluffy_Pillow humanoid enemy unknown 63
  DTPS=1655.66834507707 DTPS-Error=0.8273179221375787/0.05% DTPS-Range=116.16129998624706/7.02%
  DPR=0 RPS-Out=1529.7320899664394 RPS-In=0 Resource=health Waiting=0 ApM=0
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|500525  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=1071|1071(1071) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities (actions.default):

  Actions:

  Constant Buffs:
    bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start=  0.8 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 58.9 uptime= 14.10%
    Health Decade (10 - 20)  : start=  0.9 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 28.7 uptime=  8.76%
    Health Decade (20 - 30)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 29.8 uptime= 10.01%
    Health Decade (30 - 40)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 29.9 uptime= 10.10%
    Health Decade (40 - 50)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 31.0 uptime= 10.47%
    Health Decade (50 - 60)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 31.8 uptime= 10.75%
    Health Decade (60 - 70)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 33.2 uptime= 11.22%
    Health Decade (70 - 80)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 32.1 uptime= 10.85%
    Health Decade (80 - 90)  : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 20.6 uptime=  6.97%
    Health Decade (90 - 100) : start=  1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 duration= 20.2 uptime=  6.77%
    putrid_burst             : start=  3.4 refresh=  0.0 interval= 92.2 trigger= 92.2 duration=  9.9 uptime= 11.17%
    shadow_embrace           : start=  1.0 refresh=103.4 interval=  2.0 trigger=  2.9 duration=298.0 uptime= 99.32%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting:  0.00%

Baseline Performance:
  RNG Engine    = xoshiro256+
  Iterations    = 6009 (2006, 1271, 1367, 1365)
  TotalEvents   = 12021190
  MaxEventQueue = 29
  TargetHealth  = 500526
  SimSeconds    = 1801485.260
  CpuSeconds    = 13.25
  WallSeconds   = 5.3484255
  InitSeconds   = 0.0132889
  MergeSeconds  = 0.0013958
  AnalyzeSeconds= 0.0068756
  SpeedUp       = 136052
  EndTime       = 2022-11-16 20:58:50+0100 (1668628730)

Waiting:
    All players active 100% of the time.

Scale Factors:
  Fearghul_aktiv  Int=1.248223(0.010534)  SP=1.161090(0.010496)  Crit=0.400661(0.010231)  Haste=0.518155(0.010244)  Mastery=0.456616(0.010206)  Vers=0.385302(0.010191)

**Comment by vituscze** [comment]
Your simc is about 2 years out of date. It will work fine once you update.
