### ISSUE TITLE
Missing Trinket effects

### ISSUE THREAD

**Issue by Ricodyn** [simulationcraft/simc#7112]
It seems to me that some (passive) trinket's effects are not included in the sims. Ones that I have found missing from my simulations so far are Ruby Whelp Shell and Gral's Discarded Tooth, their effects are not present in either the damage or buffs.

This is using Simcraft version 1002-01

**Comment by nezroy** [comment]
Also seems to be the case for the Primal Ritual Shell, which has a selectable passive buff.

**Comment by LightVirus** [comment]
I have encountered the same problem with the trinket [Static-Charged Scale](https://www.wowhead.com/item=200676/static-charged-scale?bonus=6652:40:1478:8767&ilvl=395) , the buff [Overcharged](https://www.wowhead.com/spell=392128/overcharged) it should grant does not appear in the buff list of the simulation.

Tested with build 1002.01.5588e1f

**Comment by FakeGodz** [comment]
[Desperate Invoker's Codex](https://www.wowhead.com/item=194310/desperate-invokers-codex)

Also seems to not work, it's not even being used, and missing the buff [Hatred](https://www.wowhead.com/spell=382419/hatred) when casting any spell.

Build [3cba7ad392](https://github.com/simulationcraft/simc/commit/3cba7ad392)

**Comment by FakeGodz** [comment]
[Desperate Invoker's Codex](https://www.wowhead.com/item=194310/desperate-invokers-codex) seems to be fixed

Build [3b3e795551](https://github.com/simulationcraft/simc/commit/3b3e795551)

**Comment by cremor** [comment]
Ruby Whelp Shell has just been implemented.
Primal Ritual Shell was already implemented some time ago.
See here for trinket options: https://github.com/simulationcraft/simc/wiki/ExpansionOptions
