### ISSUE TITLE
Unholy DK: Unholy Assault used rarely in HAC/AOE

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#7115]
### Describe the bug
The current Unholy DK APL only uses Unholy Assault wh

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Sim in HecticAddCleave:  https://www.raidbots.com/simbot/report/nMQVuw3D3AvCYmwScKymK3/simc

![image](https://user-images.githubusercontent.com/9438134/206295670-41298b1f-a692-4ff3-a42e-21ae70120dc8.png)

Unholy Assault is used 1.33 times on average in a 5 minute fight.  This is because the `st_planning` variable is rarely met in HAC and never met with 4+ targets:

`active_enemies<=3&(!raid_event.adds.exists|raid_event.adds.in>15)`

I tested a couple of alternate conditions for Unholy Assault:  https://www.raidbots.com/simbot/report/7uvrt9xU1cS3MH8PyzYKhG

![image](https://user-images.githubusercontent.com/9438134/206296352-78b2e48a-85d5-49e9-a9e0-83b68c310e9b.png)

It's likely that optimal conditions would avoid wasting the Festering Wounds generated by Unholy Assault (i.e.,  `target_if=min:dot.festering_wound.stack`) but simply using UA on CD is a 7% gain on its own.

### Additional information
* SimulationCraft Version (required):  [1a2d7db902](https://github.com/simulationcraft/simc/commits/1a2d7db902)

**Comment by nyterage** [comment]
Not sure how i missed that, thank you! 

fixed in https://github.com/simulationcraft/simc/commit/9b9bd13d082990cf29ab00c1cfb26e081ab1cf53
