### ISSUE TITLE
Storm Earth Fire -> Fists of Fury bug

### ISSUE THREAD

**Issue by flollef** [simulationcraft/simc#7197]
Fists of fury cast by the clones appears to be doing excessive damage.

Tested with the simple APL:

monk.initial_chi=6
# actions+=/sequence,name=attack:fists_of_fury
 #actions+=/sequence,name=attack:storm_earth_and_fire:fists_of_fury

Edit: Unsure if other abilities are affected.

**Comment by Hurstilol** [comment]
Your test was either not good or bugged out.

![image](https://user-images.githubusercontent.com/85832226/209649485-39c99189-2cfd-4820-ae8c-7cd791623509.png)

As you can see in this sim: https://www.raidbots.com/simbot/report/o8mSPh1c7rHj8TngYKehZn/simc
the DPE of a single FoF during Clones is the same for the Clones and the Player.

**Comment by flollef** [comment]
This issue was fixed in a recent update.
