### ISSUE TITLE
Monk- Open Palm Strikes Bug

### ISSUE THREAD

**Issue by flollef** [simulationcraft/simc#7201]
Open Palm strikes appears to be generating Chi in proportion to the number of targets hit by Fists of Fury, which is not how it functions in game.

**Comment by Hurstilol** [comment]
Thats not correct, OPS just has the chance to generate Chi per Tick. 

![image](https://user-images.githubusercontent.com/85832226/209645561-ebb4ff9e-da29-4b4d-a395-03d30ccb091a.png)

As you can see in this picture of this sim: https://www.raidbots.com/simbot/report/52FGo5c7MmaYQwy3Q6R4b3/simc its a single fof in a 5 target patchwerksim which only generates 2 chi. Other casts did not generate any Chi or generated a different amount of Chi. Thats just how OPS behaves ingame and its properly simulated right now.

**Comment by flollef** [comment]
With the latest nightly build, on 5 targets with an average of 8.8 casts its generating 10.9 chi on average according to the Chi gain output. This is nearly exactly what it would be generating if it was 5% per tick of damage on each target, which is not how it functions in game.

**Comment by seanpeters86** [comment]
@flollef is this still an issue? CC: @Hinalover

**Comment by Hinalover** [comment]
I'm still not sure what they mean by "how it functions in game". The talent is nearly the exact same thing we had back in Battle for Azeroth, and we extensively tested back then to be 5% per tick.
