### ISSUE TITLE
[Fury Warrior] WW prioritises over BT

### ISSUE THREAD

**Issue by wcrotations** [simulationcraft/simc#7206]
### Describe the bug
On Fury Simc build WW is being prioritised over BT if we talent Wrath and Fury

### Expected behavior
We should have a single_target+=/bloodthirst before WW

### To Reproduce
If we cast our RB/CB and if we are enraged and/or used 2x BB from Reckless Abandon, the logic skips to WW even if we have BT off cooldown

### Additional information
1002-01 - Fury commit c048e16

**Comment by seanpeters86** [comment]
@sucuoglu @Archimtiros is this still needed?

**Comment by seanpeters86** [comment]
closing due to stale
