### ISSUE TITLE
Generated Talent Failes to Import

### ISSUE THREAD

**Issue by mpalermo73** [simulationcraft/simc#7228]
### Describe the bug
The generated talent string results in "Failed to import loadout" in the game.

### Expected behavior
Expected the generated string to load.

### To Reproduce

- Build Simulationcraft on Linux using [the provided directions](https://github.com/simulationcraft/simc/wiki/HowToBuild#graphical-user-interface-using-qmake).
- Run and load character from BLizzard (Dwarf Unholy DK)
- Copy the talent string from the "Results, Spec and Gear" sexction of the results
  - `BwPAAAAAAAAAAAAAAAAAAAAAAAAiEJJk0iECikECJJSEAAAAAAAAAAkkESkkCAApIlDQSSikcA`
- Paste string into "import" text box in the in-game talent tree UI
- mushroom clouds

### Additional information
```
commit 3eeab0e67d9cef64c72efb1f34c3b37bac237774 (HEAD -> dragonflight, origin/dragonflight, origin/HEAD)
Author: EvanMichaels <evan.michaels@gmail.com>
Date:   Sun Jan 1 21:35:22 2023 -0500
```

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

- This file was not automatically generated as indicated.  I manually saved the "text" tab's output:
  - [simc_gui.simc.txt](https://github.com/simulationcraft/simc/files/10332441/simc_gui.simc.txt)
  - ![WoWScrnShot_010223_102211](https://user-images.githubusercontent.com/847259/210252293-dd98bb4b-8cff-4039-8626-8300f3c90547.jpg)

**Comment by seanpeters86** [comment]
Known problem when using miss-matched version of simc and in-game. If everything is updated this should work as expected.
