### ISSUE TITLE
Trinket cast time ignored

### ISSUE THREAD

**Issue by Vanishoxyact** [simulationcraft/simc#7232]
### Describe the bug
When using a trinket with a cast time, the cast time is not accounted for and actions continue immediately. This is seen when using Algeth'ar Puzzle Box, can not confirm for other trinkets with cast times.

### Expected behavior
Trinket has a 2 second cast time, no other action should be performed until 2 seconds has passed.

### To Reproduce
https://www.raidbots.com/simbot/report/w27bJj4drVuirvA5zhPDso/simc
See cast at 3:00.046 in Action Priority List/Sample Sequence Table. Next action occurs at 3:00.431, when it should be 2 seconds after starting the use of the trinket.

### Additional information
git build [1ba8871ffc](https://github.com/simulationcraft/simc/commit/1ba8871ffc)

Please note that in a previous build (dfe9696) this worked correctly.

**Comment by EvanMichaels** [comment]
Should be fixed in https://github.com/simulationcraft/simc/commit/e3a7ee0b009a6f007df077117fd0ad8c7599f7d8
