### ISSUE TITLE
How to create 100% simc files ?

### ISSUE THREAD

**Issue by unrealshape** [simulationcraft/simc#7240]
I want to write an addon which gives you the rotation of SimulationCraft running the program... there I saw the file ".simc" which in effect provides every possible rotation.
However, I only find the files DemonHunter and Rogue under APL and I would be interested in how you create the files...

Manually or by running the so-called .py file

Thank you, I'm new here and would appreciate any reply.

**Comment by vituscze** [comment]
These files are created manually. If you want to see what the default APL is without going through the C++ code, you can run a sim with the `save=<filename>` option, which will create and save a full profile (APL included) of the given actor.

**Comment by scamille** [comment]
Or see https://github.com/simulationcraft/simc/wiki/ActionLists for more documentation on how to create your own action priority list - which is just part of the input telling SimulationCraft how to simulate your character.

Simulating multiple different action lists and observing the resulting output (eg. dps) allows you to iteratively converge on a "optimal" action priority list for your character. That process is done manually by class maintainers and other contributors (class discord discussion, pull requests, etc.) to create the default action priority lists that are shipped with SimulationCraft.
