### ISSUE TITLE
Subtlety Rogue

### ISSUE THREAD

**Issue by gkh8936285** [simulationcraft/simc#7243]
actions.build+=/variable,name=anima_helper,value=!talent.echoing_reprimand.enabled|!(variable.is_next_cp_animacharged&(time_to_sht.3.plus<0.5|time_to_sht.4.plus<1)&energy<60)

What does that mean “time_to_sht.3.plus<0.5”，thanks

**Comment by EvanMichaels** [comment]
Means less than half a second until a 3rd or 4th Shadow Techniques AA proc
