### ISSUE TITLE
sub rogue rotation 

### ISSUE THREAD

**Issue by steveozz** [simulationcraft/simc#7247]
### Is your feature request related to a problem? Please describe.
right now the rotation is cold blood then other spell 
### Describe the solution you'd like
please make a change first use cold blood then Shadow clone if avilable they should connect each when aoe

**Comment by steveozz** [comment]
please update sub rogue rotation ？  thank you

**Comment by EvanMichaels** [comment]
Cold Blood is already synced with Secret Techniques.
