### ISSUE TITLE
outlaw rogue between the eyes after pistol shot？  

### ISSUE THREAD

**Issue by steveozz** [simulationcraft/simc#7248]
### Is your feature request related to a problem? Please describe.
outlaw rogue between the eyes after pistol shot？
### Describe the solution you'd like
should always use Dispatch after pistol shot， and between the eye always after Sinister Strike or Ambush， 
### Additional context
also pistol shot should cast more freq. if its aviliable

**Comment by EvanMichaels** [comment]
Has been looked into and does not appear to be a gain to play around the set bonus in this way.
