### ISSUE TITLE
Assassination Rogue Opener not optimized in APL?

### ISSUE THREAD

**Issue by fzarr** [simulationcraft/simc#7250]
Noticed a difference between the opener in sims vs what the recommended opener is, not sure if this makes any difference numbers wise.

Using DTB + Exsang, following the APL suggests - seems to waste the combo points from SBS and some shiv uptime:
Garrote->SnD->Garrote->SBS->Rupture->ER->Shiv->Rupture->Exsang->DM->TT+Mutilate->Envenom

Recommended Opener is: 
Garrote->SnD->Garrote->Rupture->ER->Rupture->SBS->Exsang->DM->Mutilate/Shiv/Envenom

**Comment by EvanMichaels** [comment]
This is not a difference that would matter for DPS although generally speaking the general case is the ER Rupture directly into Exsanguinate for maximum duration.
