### ISSUE TITLE
[BUG][Druid][Feral] Brutal Slash does not consume Clearcasting buff

### ISSUE THREAD

**Issue by mmichaelzhang** [simulationcraft/simc#7261]
### Describe the bug

Based on simulation version bf0ba94f4d, if talent Brutal Slash and Omen of Clarity are selected, skill Brutal Slash does not consume buff clearcasting.

### Expected behavior

Expect buff clearcasting to be consumed one stack after casting the skill Brutal Slash.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Simply select (or unselect) talent Brutal Slash and run the simulation, check the casting list table to see if any brutal slash is consuming clearcasting. (If somehow it does consumes one stack, it must regenerates a new stack somehow because I cannot find any single Brutal Slash that after casting it the number of stacks of clearcasting is decreased)

### Additional information
* SimulationCraft Version (required)
* bf0ba94f4d

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

Attached the full report URL from raidbots

BUG file: https://www.raidbots.com/simbot/report/iaKtymuVNhTYyJU5CHGAZH/simc (there is NO Brutal Slash in this report that has ever consumed a single stack of clearcasting)
Compare group file: https://www.raidbots.com/simbot/report/b7Q6uGfRs1uNg91zDvZbEg/simc (I substitute talent Brutal Slash that now only has swipe available, the casting list table clearly shows swipe consumes one stack of clearcasting buff.)

**Comment by gastank** [comment]
resolved in aaac803cf7e9eb5942d1a740a9fd277c2ea620fb
