### ISSUE TITLE
Importing char from armory shows as having the wrong missives used on crafted gear.

### ISSUE THREAD

**Issue by Strumash** [simulationcraft/simc#7267]
### Describe the bug
Although I am unsure if the actual sim results are affected, in the code where it defines what the character is wearing it is showing the wrong targeted stats on crafted items, ie all my mage crafted have master/haste missive but when I import mage from armory eu the code shows me as having crit/haste missives used on my crafter items.
### Expected behavior
I expect then import to arrive with the correct items/enhancements that are currently on the character.
### To Reproduce
There is no issue in game, to reproduce simply import a char with crafted gear and targetted missives and check the armor list in the raw pre-sim data.

### Additional information
* SimulationCraft Version (required)
1002-01
* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
simcraft is not crashing
* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
![image](https://user-images.githubusercontent.com/122741173/212553543-83024b9b-ace1-446f-9517-dc1967471370.png)
![image](https://user-images.githubusercontent.com/122741173/212553617-32560fd3-ce51-4adc-b494-88e34706d6a8.png)

**Comment by gastank** [comment]
`crafted_stats` refers to the original crafted state of the item, before missives are applied. Your item has the 8793 bonus_id, which comes from the missive being applied to override the original crafted stats from crit/mas to haste/mas
