### ISSUE TITLE
Simcraft not scaling Evokers Intellect

### ISSUE THREAD

**Issue by Strumash** [simulationcraft/simc#7268]
### Describe the bug

I have noticed while simming friends evokers It will not scale the intellect stat nomatter how it is selected in the options either manually or by setting it to scale all character stats.

### Expected behavior
I expected to see a scale factor for intellect on the new evoker class

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.
Sim any evoker and enable scaling factors

* SimulationCraft Version (required)
1002.01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
Simulationcraft is not crashing.

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
![image](https://user-images.githubusercontent.com/122741173/212553891-3e1eae45-c77c-4e98-9dac-fb343cf7a55b.png)
![image](https://user-images.githubusercontent.com/122741173/212553913-1fbeb14f-853d-4f38-977e-7fb568d3f272.png)

**Comment by Strumash** [comment]
After some messing around I have found the reason it is not scaling int/sp etc for evokers is because when the profile is pulled from the armory the role for evoker is set to Auto. 

![image](https://user-images.githubusercontent.com/122741173/212573331-1fbcf78b-581a-4aae-9828-5a578e6fe2e6.png)
see image above for import from armory vs image below which is the sample t29 evoker dps sim.

![image](https://user-images.githubusercontent.com/122741173/212573369-96f12148-f3f9-4e1e-9ed4-bb962083cfba.png)

After manually setting this to "spell" on the import the program did indeed generate scale factors for int/sp etc.

**Comment by Saeldur** [comment]
Above commit should fix it. I think.
