### ISSUE TITLE
CAN'T INSTALL SIMULATION CRAFT ON MY COMPUTER

### ISSUE THREAD

**Issue by Theunseen33** [simulationcraft/simc#7270]
I can't find a current version of the software and if I did, I don't know how to install it. Please help.

**Comment by scamille** [comment]
Please visit https://www.simulationcraft.org/download.html

There usually is no need to install anything - just download & extract, and run the executable.

If you need more assistance on how to run your computer, we unfortunately can't offer you any. If you truly have trouble using SimulationCraft, please add more info than just a ALLCAPS ticket.
