### ISSUE TITLE
Affliction Warlock sims not showing Focus Malignancy and Inq Gaze

### ISSUE THREAD

**Issue by Bobbyteo** [simulationcraft/simc#7308]
### Describe the bug
Talent table not showing the chosen talent

### Expected behavior
damage breakdown shows no increase in Malific Rapture when Focus Malignancy is chosen

### To Reproduce
run any simc

### Additional information
[SimulationCraft 1002-01](https://www.simulationcraft.org/)
for World of Warcraft 10.0.2.47631 Live (hotfix 2023-01-18/47631, git build [afae166](https://github.com/simulationcraft/simc/commit/afae166))

**Comment by Azevara** [comment]
This was reported in 10.0.2, but Focused Malignancy was not available until 10.0.5. Closing this issue.
