### ISSUE TITLE
Discipline and Holy Priest DPS Sims

### ISSUE THREAD

**Issue by seanpeters86** [simulationcraft/simc#7389]
new version to replace https://github.com/simulationcraft/simc/issues/5640

Discipline and Holy Priest DPS sims are currently not supported in SimC. This issue is meant to talk about what is missing and what is needed to be worked on in order to make it usable for DPS sims.

Both of these specs require almost every single spec-specific spell to be looked at, created, or modified. Any class generic spells are likely working correctly with the Shadow Priest implementations requiring them already.

Each spell will need the following:
- [ ] verify current implementation works correctly
- [ ] verify current implementation does the correct amount of damage and matches in-game
- [ ] create and implement all new spells, talents, and core passives from Dragonflight
- [ ] add or update the APL for that spell

See the [Priest Wiki](https://github.com/simulationcraft/simc/wiki/Priests) for any Priest specific documentation on the module.

The below is not an exhaustive list, but at least it's a start for damage-related things.

### Generic
- [ ] Add T29 Profiles
- [ ] Smite
- [ ] Holy Nova
- [ ] Words of the Pious
- [ ] Unwavering Will
- [ ] Crystalline Reflection
- [ ] Shadow Word: Pain (should work with Shadow implementation)
- [ ] Mind Blast (should work with Shadow implementation)

### Discipline
- [ ] [Discipline Priest Passive](https://www.wowhead.com/spell=137032/discipline-priest)
- [ ] Sins of the Many
- [ ] Penance
- [ ] Purge the Wicked
- [ ] Atonement (modeling?)
- [ ] Power Word: Radiance
- [ ] Power of the Dark Side
- [ ] Light's Promise
- [ ] Make Amends
- [ ] Dark Indulgence
- [ ] Schism
- [ ] Bright Pupil
- [ ] Enduring Luminescence
- [ ] Shield Discipline
- [ ] Power Word: Solace
- [ ] Painful Punishment
- [ ] Malicious Intent
- [ ] Rapture
- [ ] Shadow Covenant
- [ ] Revel in Purity
- [ ] Contrition
- [ ] Pain and Suffering
- [ ] Embrace Shadow
- [ ] Twilight Corruption
- [ ] Borrowed Time
- [ ] Castigation
- [ ] Abyssal Reverie
- [ ] Train of Thought
- [ ] Light's Wrath
- [ ] Lenience
- [ ] Evangelism
- [ ] Mindbender (should work with Shadow implementation)
- [ ] Divine Aegis
- [ ] Blaze of Light
- [ ] Resplendent Light
- [ ] Harsh Discipline
- [ ] Expiation
- [ ] Inescapable Torment (should work with Shadow implementation)
- [ ] Weal and Woe
- [ ] Wrath Unleashed
- [ ] Twilight Equilibrium
- [ ] Void Summoner

### Holy
- [ ] Holy Fire
- [ ] Holy Words (Passive)
- [ ] [Holy Priest Passive](https://www.wowhead.com/spell=137031/holy-priest)
- [ ] Holy Word: Chastise
- [ ] Holy Word: Sanctify
- [ ] Empyreal Blaze
- [ ] Holy Word: Serenity
- [ ] Searing Light
- [ ] Apotheosis
- [ ] Light of the Naaru
- [ ] Harmonious Apparatus
- [ ] Circle of Healing
- [ ] Orison
- [ ] Divine Image
- [ ] Divine Word
- [ ] Burning Vehemence
- [ ] Answered Prayers (might need modeling)
- [ ] Miracle Worker
- [ ] Prayers of the Virtuous
- [ ] Say Your Prayers

**Comment by taherbert** [comment]
- [ ] AOE spreading with revel in purity
