### ISSUE TITLE
Evoker Leaping Flames Patchwork Sim Bug

### ISSUE THREAD

**Issue by Saviorself300** [simulationcraft/simc#7407]
### Describe the bug
Taking Evoker's Leaping Flames talent is increasing single target Patchwork sim DPS by ~3.7-3.8%. This talent should not increase DPS for a single-target patchwork fight since there is only one enemy to be hit. Since there are no additional enemies to be hit, the additional charges of the spell will be cast as healing to the player or their allies and will offer no extra DPS.

### Expected behavior
I expected single-target "Patchwork" DPS to be the same regardless of whether or not the Leaping Flames talent was taken.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.
Create two identical talent builds, except one with Leaping Flames and one without. Run Patchwork sims.

### Additional information
* SimulationCraft Version (required) 
Weekly (1005-01)

**Comment by vituscze** [comment]
I believe that's because of the extra healing getting stored and then released via Scarlet Adaptation. The spell isn't hitting the same target twice.

**Comment by Saeldur** [comment]
This is not a bug.

Leaping flame when there isn't sufficient enemies in the sim will cleave to allies, when it cleaves to allies it can make essence bursts and it will also contribute some healing towards scarlet adaptation.
By default, 90% chance to make an essence burst and 50% overhealing on the scarlet adaptation.
See https://github.com/simulationcraft/simc/wiki/Evokers for more info
