### ISSUE TITLE
Wont allow me simulate

### ISSUE THREAD

**Issue by WrightTylerC** [simulationcraft/simc#7411]
Every time I try to simulate a character all it tells me is "Unknown option 'talents' with value" an the code given "BcEAoonA2h02U1PVo4204nicFAgSikkkQIpVKJBAAAAkQESDJAR0QSSQgEhEgkEJAAAAAAAAEpkcgIAQDB". I've copied an pasted the text the simulationcraft gave me In wow. What do I need to do to fix this issue.

**Comment by vituscze** [comment]
What's your simc version?
