### ISSUE TITLE
Retribution Paladin

### ISSUE THREAD

**Issue by dasbumsding** [simulationcraft/simc#7481]
### Describe the bug
When I type "/simc" in chat, I can't click enter. I can't click on the minimap icon either. I'm not getting any input. Other Retri players that I know don't have the problem. If I switch to Prot or Heal, simulationcraft works. Simc also works with other classes. Only Retri Pala does not work.

### Expected behavior
If I type "/simc" in the chat, I can click enter. Then a new window appears where I can copy the content. But I can't even click enter.

### To Reproduce
see up.

### Additional information
I'm up-to-date. I testing since 3 Version from simulationcraft (now 10.0.7-3)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
No file available - Maybe because I completely reinstalled the addon to test it. But reinstalling didn't help.

**Comment by vituscze** [comment]
Please report issues with the addon here: https://github.com/simulationcraft/simc-addon
