### ISSUE TITLE
hellp SimulationCraft encountered an error! version 830-01

### ISSUE THREAD

**Issue by daff5578** [simulationcraft/simc#7567]
SimulationCraft encountered an error!

Simulation runtime error:
Unable to decode talent string 'BgEAoonA2h02U1PVo4204nicFEAAAAAAAAAAQggSCQEEiIJRBSICEOQIJplEJRCCRSSkSASikEAAAEQQA' for player 'Ungsan'.Setup failure: Unknown option 'talents' with value 'BgEAoonA2h02U1PVo4204nicFEAAAAAAAAAAQggSCQEEiIJRBSICEOQIJplEJRCCRSSkSASikEAAAEQQA'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue

**Comment by scamille** [comment]
Please upgrade your SimulationCraft version. You are very likely using an outdated one.

You can find the download page here: https://www.simulationcraft.org/download.html

**Comment by daff5578** [comment]
> Please upgrade your SimulationCraft version. You are very likely using an outdated one.
> 
> You can find the download page here: https://www.simulationcraft.org/download.html

isn't that the latest one? please put the SimcSetup-xxx-xx-Win64.exe link here, because I can't find anything newer than version 830-01

**Comment by scamille** [comment]
> Simulationcraft nightly builds are found here

http://downloads.simulationcraft.org/nightly/?C=M;O=D

>Simulationcraft nightly builds are created daily for both Windows and MacOS. The link above always contains only the latest available build for a given version. The graphical user interface on windows requires Windows 10/11 version 21H2 or later. The windows nightly is compressed using 7-Zip - to uncompress, get 7-Zip here 


So today you would grab http://downloads.simulationcraft.org/nightly/simc-1007.01.8f7a3ca-win64.7z

There is no installer available anymore.
