### ISSUE TITLE
Is /SIMC still supported on Classic era realms i currently cant get it to work

### ISSUE THREAD

**Issue by littlefletchy** [simulationcraft/simc#7574]

**Comment by vituscze** [comment]
I don't believe it was ever supported. In any case, no support for classic is currently planned.

**Comment by littlefletchy** [comment]
I used it in 2020 ? on aq release but haven't played since tbc release so i'm trying to get an older version working on vanilla again?

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc-addon is the repository for the ingame addon. (Technically also the better place for a ticket related to it).

You can always try to get it working yourself, the source code is available. Older versions are available through the git history.
