### ISSUE TITLE
Spore Keeper's Baton not proccing properly

### ISSUE THREAD

**Issue by kaesebrezen** [simulationcraft/simc#7714]
### Describe the bug
The special effect of the Spore Keeper's Baton does not seem to proc properly. Shadow Priest and Warlock sims have the Sporeadic Adaptibility Effect at 2 to 4 Procs on a 5 minute fight.

### Expected behavior
Pen and Paper math for a 2 RPPM hasted proc should average on at least 10 procs on a 5 minute fight. Frost Mage is getting the expected result, Shadow and Warlock sims are not,

### To Reproduce
Run any sim with the the Spore keepers Baton equipped on Warlock and Shadowpriests and compare it to Frost Mages.

Generally, looking at the debug log, whenever a DoT procs the sporeadic adaptibility effect, the debuff isn't applied to the target.

### Additional information
simc-1010.01

**Comment by gastank** [comment]
fixed in a2a26b2

**Comment by kaesebrezen** [comment]
thanks for the quick fix!
