### ISSUE TITLE
[Hunter] Windrunner's Barrage does not fire secondary arrows on AOE.

### ISSUE THREAD

**Issue by HonorWOW** [simulationcraft/simc#7759]
### Describe the bug
When using the Windrunner's Barrage talent with 2 or more targets, only the "primary" arrows are fired. The secondary arrows are never fired, reducing the value of this talent in sims.

### Expected behavior
When at least 1 extra target is present, the 10 secondary arrows should fire.

### To Reproduce
Sim with Windrunner's Barrage and at least 2 targets.

### Additional information
It looks like, under wailing_arrow_t, we are explicitly firing the primary Wind Arrows, but there is no explicit handling for secondary arrows. We should probably split the secondary arrows among targets beside the primary target.

I tested a hacky fix locally (just adding the secondary arrows to the primary arrow loop) and found it was a ~1.3% DPS increase, which means this talent still sucks on AOE. However, I think it might actually be decent on 2T specifically. I'd put up a pull request, but I don't know enough about the code base to know the "proper" way to fire off the secondary arrows and split them up among targets.

**Comment by Jayezi** [comment]
Right now it fires off the secondary arrows in the impact action of Wailing Arrow, so it shares the list of targets hit and divides the 10 arrows among them. This 2T sim sees an expected amount of arrows with an average 5.3 WA casts -> 79.2 Wind Arrows (15 per) https://www.raidbots.com/simbot/report/68amnATtMP59wbSWcLUYEA/simc

**Comment by HonorWOW** [comment]
Hm, okay, I guess I was just misled by the log, which only has events for 5 Windrunner's Barrage arrows for the first Wailing Arrow in this log:
[output.txt](https://github.com/simulationcraft/simc/files/11628625/output.txt)

**Comment by HonorWOW** [comment]
The others are there, they're just delayed (like you said, until the Wailing Arrow impact). I'm blind. Never mind!
