### ISSUE TITLE
Arcane Mage - Arcane Surge not setting mana to 0

### ISSUE THREAD

**Issue by TylerR909** [simulationcraft/simc#7764]
### Describe the bug
I'm digging through the Sample Sequence Table trying to pick out patterns and noticed that when [Arcane Surge](https://www.wowhead.com/spell=365350/arcane-surge) is cast, despite the tooltip opening with `Expend all your current mana...`, Mana in the resource column doesn't budge.

<html>
<body>

Time | List | # | Name | Target | Resources
-- | -- | -- | -- | -- | -- 
3:08.089 | spark_phase | p | nether_tempest | Fluffy_Pillow | 214298.2/354715: 60% mana
3:09.367 | spark_phase | q | arcane_surge | Fluffy_Pillow | 218790.5/354715: 62% mana
3:10.016 | spark_phase | v | arcane_barrage | Fluffy_Pillow | 222976.1/354715: 63% mana
3:10.310 | spark_phase | t | touch_of_the_magi | Fluffy_Pillow | 224872.2/354715: 63% mana 

</body>
</html>

### Expected behavior

Mana is 0%, or close to 0%, after casting Arcane Surge.

### Additional information
simc-1010.01.1cebc5b-win64

* **simc_gui.simc** file or contents
<details><summary>expand...</summary>

```
### SimulationCraft 1010-01 for World of Warcraft 10.1.0.49801 Live (wow build 49801, git build dragonflight 1cebc5b)  ###
### Using QT 6.4.0 with WebEngine ###

### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.05
max_time=400
vary_combat_length=0.2
fight_style=LightMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.mark_of_the_wild=1
override.windfury_totem=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
scale_over=PriorityDps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Bellemae - Arcane - 2023-06-03 00:16 - US/Tichondrius
# SimC Addon 10.1.0-06
# WoW 10.1.0.49801, TOC 100100
# Requires SimulationCraft 1000-01 or newer

mage="Bellemae"
level=70
race=blood_elf
region=us
server=tichondrius
role=spell
professions=herbalism=61/inscription=23
spec=arcane

talents=B4DAHVkVsxxZrVqBmAzlSR2f7LJAHolIhk0AJtEiIikIhEaBSLJAAAAAAAAAAAAJJJJhkkkcAA

# Saved Loadout: Questing
# talents=B4DAHVkVsxxZrVqBmAzlSR2f7DCokkQQLRSSRIiIECCkISLAAAAAAAAAAAAkkkkEgkkA
# Saved Loadout: IV Raiding ST
# talents=B4DAHVkVsxxZrVqBmAzlSR2f7LJAHolIhk0AJtEiIikIhEaBSLJAAAAAAAAAAAAJJJJhkkkcAA
# Saved Loadout: MH Dungeon
# talents=B4DAHVkVsxxZrVqBmAzlSR2f7LJChWiESSDEtkIiISiESolg0SCAAAAAAAAAAAgkkkESSSiA
# Saved Loadout: IV M+
# talents=B4DAHVkVsxxZrVqBmAzlSR2f7LJQolIxBSSDEtkIiISikAplQSLJAAAAAAAAAAAAkkkESSSiA

head=,id=204786,bonus_id=9314/6652/9414/9223/9221/1527/8767
neck=,id=200762,gem_id=192954,bonus_id=6652/7935/8783/1478/8767
shoulder=,id=204586,bonus_id=9296/1472/8766
back=,id=204618,bonus_id=9301/1488/8766
chest=,id=204920,bonus_id=6652/9306/1624/8767
wrist=,id=204588,bonus_id=8902/9301/1491/8766
hands=,id=204583,bonus_id=8902/9301/1491/8766
waist=,id=204587,bonus_id=8902/9301/1491/8766
legs=,id=204585,bonus_id=9301/1488/8766
feet=,id=204409,bonus_id=9323/9222/9219/6652/1478/8767
finger1=,id=204746,bonus_id=9314/6652/9414/1527/8767
finger2=,id=201960,bonus_id=7937/9377/1489/8767
trinket1=,id=194301,bonus_id=6652/7979/1472/8767
trinket2=,id=203996,bonus_id=6652/9323/7979/1472/8767
main_hand=,id=204452,bonus_id=8902/9301/1491/8766

### Gear from Bags
#
# Endowed Hood (392)
# head=,id=204584,bonus_id=9299/1479/8766
#
# Shalkeel's Remembrance (379)
# neck=,id=204461,bonus_id=9417/8902/9295/1475
#
# Surveyor's Seasoned Shoulders (343)
# shoulder=,id=201937,bonus_id=8851/8852/9405,crafted_stats=40/36,crafting_quality=5
#
# Surveyor's Tailored Cloak (343)
# back=,id=193500,bonus_id=8837/8838/4785/9405/8847,crafted_stats=49/32,crafting_quality=5
#
# Suffused Greatcloak (395)
# back=,id=204896,bonus_id=9304/42/9216/1517/8766
#
# Surveyor's Cloth Robe (319)
# chest=,id=193515,bonus_id=8837/8838/4785/9405,crafted_stats=49/32,crafting_quality=5
#
# Singed Cloth Armbands (180)
# wrist=,id=188720,bonus_id=7966,drop_level=70
#
# Suffused Handwraps (385)
# hands=,id=204787,bonus_id=9297/6652/9214/1507/8766
#
# Surveyor's Seasoned Cord (343)
# waist=,id=201940,bonus_id=8851/8852/9405/9415,crafted_stats=36/32,crafting_quality=5
#
# Endowed Slippers (379)
# feet=,id=204582,bonus_id=9295/8902/1472
#
# Frozen Footwraps (395)
# feet=,id=200743,bonus_id=8821/8818/6652/1478/8767
#
# Seal of Vindication (359)
# finger1=,id=109781,bonus_id=6652/8812/8171/7756,drop_level=70
#
# Buzzing Orb Core (379)
# trinket1=,id=204387,bonus_id=9295/8902/6652/1472
#
# Overseer's Writhebark Stave (333)
# main_hand=,id=194893,bonus_id=8851/8852/9402,crafted_stats=40/49,crafting_quality=2
#
# Neltharic Ritual Knife (402)
# main_hand=,id=204954,bonus_id=6652/9313/1624/8767
#
# Suffused Spellblade (389)
# main_hand=,id=204752,bonus_id=9302/6652/1511/8766
#
# Grounded Stone Focus (382)
# off_hand=,id=204629,bonus_id=9296/1472/8766

### Additional Character Info
#
# upgrade_currencies=c:2122:2/c:2245:319/i:204195:4/i:204193:4
#
# slot_high_watermarks=0:405:418/1:395:408/2:382:421/3:402:421/4:398:415/5:398:398/6:421:421/7:398:411/8:398:424/9:389:424/10:395:411/11:398:421/12:398:424/13:402:402/14:0:421/15:0:408/16:382:402

# Checksum: d37dded7
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

</details>

**Comment by vituscze** [comment]
The spell consumes mana correctly. Without seeing the exact sim you ran, I'm guessing that the cast didn't actually go through (was interrupted by movement, most likely) since you'd need insane amounts of haste to get Surge to 0.649s cast time.

**Comment by TylerR909** [comment]
I looked again at these sims and it looks like you're right. No matter what mana Surge is cast at, the Arcane Blast that follows it is reliably 15-16%. I had to look at the opener to determine that the Mana snapshot is taken before the cast. i.e. Time Warp costs 10k mana but still shows 100% on that row. Here are a few lines from the same run (new sim from the run above):

Here I'd expect to see near-zero mana after Surge or AB:
<html>
<body>


0:12.793 | spark_phase | p | nether_tempest | Fluffy_Pillow | 107248.4/355466: 30% mana 
-- | -- | -- | -- | -- | -- 
0:13.553 | spark_phase | q | arcane_surge | Fluffy_Pillow | 108410.3/355466: 30% mana
0:14.818 | spark_phase | r | arcane_blast | Fluffy_Pillow | 53523.8/355466: 15% mana 


<br class="Apple-interchange-newline">
</body>
</html>

Here, maybe 39% is snapshot right before it gets set to 0% and by the time AB casts it's back up to 16%? 

<html>
<body>


2:20.793 | spark_phase | p | nether_tempest | Fluffy_Pillow | 134341.7/355466: 38% mana 
-- | -- | -- | -- | -- | -- 
2:22.032 | spark_phase | q | arcane_surge | Fluffy_Pillow | 138599.4/355466: 39% mana 
2:24.148 | spark_phase | r | arcane_blast | Fluffy_Pillow | 55186.9/355466: 16% mana


<br class="Apple-interchange-newline">
</body>
</html>

Could follow the same logic as above^:

<html>
<body>


3:56.640 | spark_phase | p | nether_tempest | Fluffy_Pillow | 5300.1/355466: 1% mana
-- | -- | -- | -- | -- | --
3:57.897 | spark_phase | q | arcane_surge | Fluffy_Pillow | 9674.1/355466: 3% mana 
4:00.038 | spark_phase | r | arcane_blast | Fluffy_Pillow | 55187.1/355466: 16% mana 


<br class="Apple-interchange-newline">
</body>
</html>

Same here:

<html>
<body>


5:27.629 | spark_phase | p | nether_tempest | Fluffy_Pillow | 13706.6/355466: 4% mana
-- | -- | -- | -- | -- | --
5:28.566 | spark_phase | q | arcane_surge | Fluffy_Pillow | 16012.4/355466: 5% mana 
5:30.173 | spark_phase | u | arcane_blast | Fluffy_Pillow | 55084.8/355466: 15% mana


<br class="Apple-interchange-newline">
</body>
</html>
