### ISSUE TITLE
Higher priority actions being ignored due to queuing system

### ISSUE THREAD

**Issue by nimeji** [simulationcraft/simc#7774]
### Describe the bug
Higher priority actions can get ignored when they depend on an action that has been queued for execution.

### To Reproduce
Run a simulation with the following APL ([example](https://www.raidbots.com/simbot/report/aWEn4SrbUh8dFaamJ11aFA/simc))
```
actions=/shattering_star,if=time=0
actions+=/azure_strike,if=cooldown.shattering_star.up
actions+=/shattering_star
```

### Current behavior
Azure Strike is not used because Shattering Star is being queued up i.e.:

* Time 19:850 - shattering star is still on cooldown and gets queued for time 20:000
* Time 20:000 - shattering star gets executed as a queued action even though there is a higher priority action available

### Expected behavior
Azure Strike should be used

### Additional information
* SimulationCraft Version: World of Warcraft 10.1.0.49890 Live (hotfix 2023-06-09/49890, git build [e0773f48fd](https://github.com/simulationcraft/simc/commit/e0773f48fd))

**Comment by vituscze** [comment]
This is intentional. If you do not want the cooldown to be queued, you can change the cooldown tolerance (`default_cooldown_tolerance` if you want to change it globally, `cooldown_tolerance` if you want to change it just for the player). Alternatively, you can add additional conditions to the action to make sure it doesn't queue (such as `if=charges>=1`)

**Comment by nimeji** [comment]
I would argue that it shouldn't work like that though. For one its not executing the APL as written and its also not very obvious that this is a thing that needs to be considered when writing APLs. The above is just a minimal example but it leads to occational missed casts of an important cooldown in the current evoker APL. I'm fine with adding the workaround you described but maybe this interaction should be reevaluated.

**Comment by vituscze** [comment]
The simple fact is that cooldown tolerance exists in the game, therefore it exists in simc as well and APLs have to account for it, as with every other quirk of the game.

**Comment by nimeji** [comment]
Alright I think I understand the reasoning behind it now. I'll change the APL to account for it. Thanks for the help!
