### ISSUE TITLE
Affliction warlock Doom Blossom spell not configured correctly for simulation

### ISSUE THREAD

**Issue by Bobbyteo** [simulationcraft/simc#7797]
### Describe the bug
sim dont run.  error message says  Doom Blossom spell data not found

### Expected behavior
Doom Blossom spell sim correctly

### To Reproduce
any sim run with Doom Blossom talent taken

### Additional information
on simc-1010.01.5376750-win64

Part of error message:
Player Hosaylock could not find spell data for action doom_blossom
Simulation has been canceled after 1 iterations! (thread=0)                     
Player Hosaylock could not find spell data for action doom_blossom
Player Hosaylock could not find spell data for action doom_blossom
Player Hosaylock could not find spell data for action doom_blossom
Player Hosaylock could not find spell data for action doom_blossom
Player Hosaylock could not find spell data for action doom_blossom
Player Hosaylock could not find spell data for action doom_blossom

**Comment by Azevara** [comment]
Most likely resolved by #7798 . Please open a new issue if this is still observed.
