### ISSUE TITLE
Old stats for recently re-tuned Zaralek trinkets in SimC?

### ISSUE THREAD

**Issue by Voxxel** [simulationcraft/simc#7845]
### Describe the bug

Trinket tuning implemented on 16 June seems to be missing from SimC. At least Smoldering Howler Horn is still counting +2526 crit rating on ilvl 411 (adventurer 8/8) while it's only 1893 on live realms. Probably other Zaralek trinkets that re-tuned in that hotfix are affected as well.

https://www.wowhead.com/news/trinket-tuning-hotfixes-june-16th-dragonflight-patch-10-1-333524

![Untitled](https://github.com/simulationcraft/simc/assets/3882152/5a1e26b6-38be-4d2d-bcc1-a7eeedb9439a)

**Comment by vituscze** [comment]
Those are wowhead tooltips, which we have no control over. Look at the buff details instead.

**Comment by seriallos** [comment]
SimC is using the correct value:

![image](https://github.com/simulationcraft/simc/assets/1010294/15d81da3-d8b1-44b9-9c88-7f9d5cd7829e)

**Comment by Voxxel** [comment]
Cool, thank you. So that means raidbots.com simming this trinket correctly?

**Comment by seriallos** [comment]
Yes, Raidbots uses SimC
