### ISSUE TITLE
Arcane mage sim cannot recognise new talent tree

### ISSUE THREAD

**Issue by Bobbyteo** [simulationcraft/simc#7919]
### Describe the bug
Sim complete but has missing calculation due to talents in new tree structure not recognised.  
Error message says : ""Player <toon name> has invalid talent tree hash B4DArSxcnei16P8xFL3rzzOyRCIlUSkkDkkCIHIJRERkQgkkQSLJAAAAAAAAAAAASSSikkkIkA: partial rank indicated for node 62100 but all 1 ranks are allocated.

### Expected behavior
sim complete with all talents computed and without error messages

### To Reproduce
Just run any sims.  My talents used were
B4DAAAAAAAAAAAAAAAAAAAAAAAIJpEJBAAAAAAAAAAAAAAAAAAAAAAAA

### Additional information
[SimulationCraft 1010-01](https://www.simulationcraft.org/)
for World of Warcraft 10.1.0.50000 Live (hotfix 2023-07-03/50000, git build [f4bda22](https://github.com/simulationcraft/simc/commit/f4bda22))

*** **simc_gui.simc** file contents attached below**
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HeavyMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.mark_of_the_wild=0
override.windfury_totem=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=2
process_priority=Normal
calculate_scale_factors=1
scale_only=str,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps
dps_plot_stat=int,sp,ap,crit,haste,mastery,vers,wdps,wohdps
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
reforge_plot_stat=int
reforge_plot_amount=500
reforge_plot_step=50
statistics_level=1
report_pets_separately=1
### Begin simulateText ###
# Talent tree: A1 AT-AFCO-ACNT:SS-PS2-HE-MG.   Patch10.1
# S3 436 C27 H27 M30 V6 Head:UCA437(358Avoid) Neck:BDL431(In75C66+2xH70C33) Shoulder:UCA437 Back:SS437(GA3*) Chest:ToSI437 Wrist:LLB434(Avoid200) Hands:UCG428 Waist:VWG437(SfAP) Legs:UCT437(I177+Mana5%) Feet:SoAF431(PB2*) FRing:BotWM431(M82)>SoQL431(M82)+DL424(H82) Trinket:VoSS437+IF441 Weap:ToPA437?47(SD3*)+CCotI437
# 
# Fuomage - Arcane - 2023-07-13 17:27 - US/Frostmourne
# SimC Addon 10.1.5-02
# WoW 10.1.5.50401, TOC 100105
# Requires SimulationCraft 1000-01 or newer

mage="Fuomage"
level=70
race=gnome
region=us
server=frostmourne
role=spell
professions=tailoring=100/enchanting=97
spec=arcane

talents=B4DArSxcnei16P8xFL3rzzOyRCIlUSkkDkkCIHIJRERkQgkkQSLJAAAAAAAAAAAASSSikkkIkA

# Saved Loadout: IS1 AT-AF-ACNTI:SS-PS2-HE-MG
# talents=B4DArSxcnei16P8xFL3rzzOyRKAWQJRikkCIHIJRERaJkAJJk0SCAAAAAAAAAAAISSSCJJJAA
# Saved Loadout: A1  AT-AFCO-ACNT:SS-PS2-HE-MG
# talents=B4DArSxcnei16P8xFL3rzzOyRCIlUSkkDkkCIHIJRERkQgkkQSLJAAAAAAAAAAAASSSikkkIkA

# Underlight Conjurer's Arcanocowl (437)
head=,id=202551,bonus_id=40/9414/9229/9333/1494/8767
# Bromach's Disentombed Locket (431)
neck=,id=193809,gem_id=192982/192945/192945,bonus_id=6652/9144/9477/8782/9327/1653/8767
# Underlight Conjurer's Aurora (437)
shoulder=,id=202549,bonus_id=6652/9333/9227/1494
# Sporecaller's Shroud (437)
back=,id=159292,enchant_id=6592,bonus_id=6652/9223/9220/9144/9329/3307/8767
# Tunic of Smoldering Ire (437)
chest=,id=137352,enchant_id=6625,bonus_id=40/9223/9221/9144/9329/3316/8767
# Captain Sanders' Shirt (1)
shirt=,id=3342
# Rajani Tabard (40)
tabard=,id=174647
# Lily-Laced Bracelets (434)
wrist=,id=193724,enchant_id=6574,bonus_id=9332/6652/9415/9223/9220/9144/1656/8767
# Underlight Conjurer's Gloves (428)
hands=,id=202552,bonus_id=6652/9230/9325/1479/8767
# Vibrant Wildercloth Girdle  (437)
waist=,id=193516,bonus_id=8836/8840/8902/9405/9373/8791/9379/8960/9366/9414,crafted_stats=49/32,crafting_quality=5
# Underlight Conjurer's Trousers (437)
legs=,id=202550,enchant_id=6544,bonus_id=6652/9228/9409/9333/1494/8767
# Sandals of Ancient Fury (431)
feet=,id=202603,enchant_id=6607,bonus_id=6652/9226/9219/9409/9331/1485/8767
# Seal of Questionable Loyalties (431)
finger1=,id=158314,enchant_id=6562,bonus_id=6652/9414/9144/9327/3301/8767
# Deeprock Loop (437)
finger2=,id=204916,enchant_id=6556,bonus_id=6652/9415/9329/1659/8767
# Vessel of Searing Shadow (437)
trinket1=,id=202615,bonus_id=7979/6652/9329/1494/8767
# Irideus Fragment (441)
trinket2=,id=193743,bonus_id=9380/6652/9144/1663/8767
# Torch of Primal Awakening  (447)
main_hand=,id=200642,enchant_id=6643,bonus_id=8836/8840/8902/9405/8791/9376/9366,crafted_stats=40/32,crafting_quality=5
# Crackling Codex of the Isles  (437)
off_hand=,id=194879,bonus_id=8836/8840/8902/9405/8793/9373/9366,crafted_stats=36/40,crafting_quality=5

### Gear from Bags
#
# Understone Gorget (424)
# neck=,id=134491,bonus_id=9324/6652/9414/8783/9144/3303/8767
#
# Chain of the Underking (418)
# neck=,id=134495,bonus_id=9322/6652/9414/8783/9144/3297/8767
#
# Elemental Lariat  (421)
# neck=,id=193001,gem_id=192982/192945/192945,bonus_id=8836/8840/8902/8960/8783/8782/9405/8791/8846/9365,crafted_stats=36/40,crafting_quality=5
#
# Boastful Stalker's Epaulets (424)
# shoulder=,id=193667,bonus_id=9324/6652/9223/9218/9144/1646/8767
#
# Putrid Carapace (437)
# back=,id=134408,bonus_id=6652/9223/9220/9144/9329/3316/8767
#
# Parrotfeather Cloak (437)
# back=,id=155884,enchant_id=6592,bonus_id=9333/9223/9220/9144/3307/8767
#
# Wristwraps of Twined Morels (421)
# wrist=,id=159275,bonus_id=9323/6652/9414/9223/9220/9144/3291/8767
#
# Gloves of Staunched Wounds (421)
# hands=,id=159253,bonus_id=9323/6652/9223/9218/9144/3291/8767
#
# Vibrant Wildercloth Slacks  (404)
# legs=,id=193518,enchant_id=6543,bonus_id=8836/8840/8902/9404/8845/8792/8174/9365,crafted_stats=40/49,crafting_quality=4
#
# Sandals of the West Wind (431)
# feet=,id=133370,bonus_id=6652/9223/9219/9144/9327/3323/8767
#
# Anachronistic Slippers (402)
# feet=,id=207596,bonus_id=9313/9225/9219/6652/1472/8767
#
# Scalebane Signet (346)
# finger1=,id=193768,bonus_id=7978/7975/6652/7936,drop_level=70
#
# Captain's Signet of Command (70)
# finger1=,id=166560,enchant_id=5942
#
# Band of the Wyrm Matron (431)
# finger1=,id=134524,enchant_id=6562,bonus_id=6652/9415/9144/9327/3310/8767
#
# Onyx Annulet (424)
# finger1=,id=203460,enchant_id=6556,gem_id=204000/204029/204027,bonus_id=1491,gem_bonus_id=1472/2/9369/1472/2/9369/1472/0/0
#
# Loop of Vitriolic Intent (431)
# finger1=,id=134530,bonus_id=6652/9414/9144/9327/3310/8767
#
# Circle of Ascended Frost (346)
# finger1=,id=193731,enchant_id=6567,bonus_id=7978/7975/6652/7937,drop_level=70
#
# Platinum Star Band (346)
# finger1=,id=193708,enchant_id=6548,bonus_id=7978/7975/6652/7936,drop_level=70
#
# Bloodied Wedding Ring (424)
# finger1=,id=193671,bonus_id=6652/9414/9144/9324/1646/8767
#
# Scalebane Signet (431)
# finger1=,id=193768,enchant_id=6550,bonus_id=6652/9414/9144/9331/1653/8767
#
# Naraxas' Spiked Tongue (428)
# trinket1=,id=137349,bonus_id=9330/6652/9144/3307/8767
#
# Time-Breaching Talon (437)
# trinket1=,id=193791,bonus_id=6652/9144/9329/1659/8767
#
# Zskarn's Autopsy Scalpel (437)
# main_hand=,id=202555,bonus_id=42/7979/9329/1488/8767
#
# Biting Wind (437)
# main_hand=,id=133233,bonus_id=9333/6652/9147/3329/8767

### Additional Character Info
#
# upgrade_currencies=c:1792:686/c:2122:6/c:2245:692/i:204195:1/i:204440:2/i:204681:1/i:204193:25/i:198058:3/i:198048:1
#
# slot_high_watermarks=0:437:437/1:431:431/2:437:441/3:437:447/4:437:441/5:437:447/6:431:441/7:434:441/8:428:441/9:431:444/10:437:437/11:437:441/12:408:437/13:447:447/14:1:312/15:0:130/16:437:447

# Checksum: 6913d74e
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by Pewtro** [comment]
You're using a 10.1 client trying to run a 10.1.5 sim, that won't work. Investigating why a 10.1.5 client hasn't been released, in the meantime you'll need to use Raidbots or build the client yourself.

**Comment by Bobbyteo** [comment]
How to build the client ?

**Comment by Pewtro** [comment]
https://github.com/simulationcraft/simc/wiki/HowToBuild

**Comment by Pewtro** [comment]
There is now a 10.1.5 client you can download http://downloads.simulationcraft.org/nightly/?C=M;O=D
