### ISSUE TITLE
Shadowlands Screen

### ISSUE THREAD

**Issue by gleiNNek** [simulationcraft/simc#7923]
Splash Screen says Shadowlands. Is this also the Dragonflight version? I downloaded the July 4th version from the downloads.

**Comment by Pewtro** [comment]
Yes, but that one is not updated for 10.1.5 yet.

**Comment by Pewtro** [comment]
There is now a 10.1.5 client you can download http://downloads.simulationcraft.org/nightly/?C=M;O=D
