### ISSUE TITLE
[Monk] Brewmaster monk is missing Spinning Crane Kick when the talent Press The Advantage is active

### ISSUE THREAD

**Issue by olidennis** [simulationcraft/simc#7950]
The APL for Brewmaster is not suggesting Spinning Crane Kick at all when the Press The Advantage talent is active. Apparently, the line about sck has been entirely removed from the rotation.

In the rotation_boc case these two lines are present
```
actions.rotation_boc+=/tiger_palm,if=active_enemies=1&!talent.blackout_combo.enabled
actions.rotation_boc+=/spinning_crane_kick,if=active_enemies>1
```

In the rotation_pta case, both have been removed. PtA makes tiger palm passive, so it makes sense that it is removed, but the line about spinning crane kick should be put back in the rotation.

**Comment by ToppleTheNun** [comment]
From one of the maintainers of the BrM APL:
> This is a known issue, but adding SCK to the PtA rotation is not as simple as one might think. Changes will come eventually on this front, though.
>
> If you have a tested, consistent improvement on this front, it and the supporting data would be appreciated!
