### ISSUE TITLE
Update Demon Hunter wiki page

### ISSUE THREAD

**Issue by hotbees** [simulationcraft/simc#7962]
There isn't a way to PR changes to the wiki so I'm submitting this as an issue.

The [DH wiki page](https://github.com/simulationcraft/simc/wiki/Demon-Hunters) hasn't been updated since 2016 and since then there's been myriad changes to available expressions/options/procs.

I wrote an update on my fork: https://github.com/hotbees/simc/wiki/Demon-Hunters

Here's some relevant associated pages:
- [the rendered diff](https://github.com/hotbees/simc/wiki/Demon-Hunters/_compare/de3625c3a7b1ada87150b57c6c2a96778dff22ca...97115adf9f8e80962501759d3ed4ef5b6325d946?short_path=a1e7987#diff-a1e798792a244d8f60b1c8e57001a7b0548090665e435ec67a8bddc4667340f5)
- [the source diff](https://github.com/hotbees/simc/wiki/Demon-Hunters/_compare/de3625c3a7b1ada87150b57c6c2a96778dff22ca...97115adf9f8e80962501759d3ed4ef5b6325d946)
- [the raw source alone](https://raw.githubusercontent.com/wiki/hotbees/simc/Demon-Hunters.md)

I would appreciate if these changes could be applied to the actual wiki pending any feedback.

**Comment by EvanMichaels** [comment]
Merged in https://github.com/simulationcraft/simc/wiki/Demon-Hunters/8f9a6415496f2c12714a4907bd3c44cad94c2dd3
