### ISSUE TITLE
Resto Druid "Action 'ferocious_bite': Cannot parse expression from...

### ISSUE THREAD

**Issue by Eeleco** [simulationcraft/simc#7963]
### Describe the bug
When trying to simulate an error occurse

### To Reproduce
SimulationCraft encountered an error! # SimulationCraft 1015-01 for World of Warcraft 10.1.5.50504 Live # hotfix 2023-07-19/50504, git build dragonflight 502edee * Category: Simulation runtime error * Error: Initializing: Actor 'Kyneau': Action 'ferocious_bite': Cannot parse expression from '(combo_points>3&target.1.time_to_die<3)|(combo_points=5&energy>=50&dot.rip.remains>10)&spell_targets.swipe_cat<4': Cannot find target by number '1'.  ## All options used for simulation: ``` ini ### SimulationCraft 1015-01 for World of Warcraft 10.1.5.50504 Live (wow build 50504, git build dragonflight 502edee)  ### ### Using QT 6.4.0 with WebEngine ###  ### Begin GUI options ### ptr=0 item_db_source=ptrhead/local/bcpapi/wowhead target_error=0 iterations=0 default_world_lag=0.025 max_time=300 vary_combat_length=0.1 fight_style=DungeonSlice show_etmi=1 tmi_window_global=4 tank_dummy=Tank_Dummy_Mythic tank_dummy_type=Mythic optimal_raid=0 override.bloodlust=1 override.arcane_intellect=0 override.power_word_fortitude=0 override.battle_shout=0 override.mark_of_the_wild=1 override.windfury_totem=0 override.bleeding=0 override.mortal_wounds=0 override.chaos_brand=0 override.mystic_touch=0 threads=14 process_priority=High calculate_scale_factors=1 scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed center_scale_delta=1 statistics_level=1 ### End GUI options ### ### Begin simulateText ### druid="Kyneau" source=blizzard origin="https://worldofwarcraft.com/en-gb/character/kazzak/kyneau" spec=restoration level=70 race=zandalari_troll zandalari_loa=paku role=attack position=back talents=BkGAAAAAAAAAAAAAAAAAAAAAAgkENJJJpItkAHINaaplEAAAAAAAAAAAAokQIJCiEQIJhkASaJAAAAAAEBAAE  # Default consumables potion=elemental_potion_of_ultimate_power_3 flask=phial_of_elemental_chaos_3 food=fated_fortune_cookie augmentation=draconic temporary_enchant=main_hand:howling_rune_3  # This default action priority list is automatically created based on your character. # It is a attempt to provide you with a action list that is both simple and practicable, # while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps. # Feel free to edit, adapt and improve it to your own needs. # SimulationCraft is always looking for updates and improvements to the default action lists.  # Restoration DPS APL can be found at https://www.dreamgrove.gg/sims/tree/restoration.txt  # Executed before combat begins. Accepts non-harmful actions only. actions.precombat=flask actions.precombat+=/food actions.precombat+=/augmentation # Snapshot raid buffed stats before combat begins and pre-potting is done. actions.precombat+=/snapshot_stats # Executed before combat begins. Accepts non-harmful actions only. actions.precombat+=/heart_of_the_wild actions.precombat+=/cat_form,if=talent.rake.enabled actions.precombat+=/prowl,if=talent.rake.enabled actions.precombat+=/moonkin_form,if=talent.moonkin_form.enabled&!talent.rake.enabled  # Executed every time the actor is available. # Executed every time the actor is available. actions=berserking actions+=/natures_vigil,if=!buff.prowl.up&!buff.shadowmeld.up actions+=/run_action_list,name=healing,if=!buff.prowl.up&!buff.shadowmeld.up&druid.time_spend_healing,line_cd=10 actions+=/use_items,if=!buff.prowl.up&!buff.shadowmeld.up actions+=/potion,if=!buff.prowl.up&!buff.shadowmeld.up actions+=/run_action_list,name=cat,if=talent.rake.enabled actions+=/run_action_list,name=owl,if=active_enemies>2&talent.moonkin_form.enabled&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled) actions+=/moonkin_form,if=talent.moonkin_form.enabled actions+=/convoke_the_spirits,if=(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled) actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=2&dot.adaptive_swarm_damage.remains>2 actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=1&dot.adaptive_swarm_damage.remains>2 actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=3&dot.adaptive_swarm_damage.remains>2 actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=4&dot.adaptive_swarm_damage.remains>2 actions+=/adaptive_swarm,target_if=!dot.adaptive_swarm_damage.ticking actions+=/sunfire,target_if=refreshable&target.time_to_die>5&talent.improved_sunfire.enabled actions+=/moonfire,target_if=refreshable&time_to_die>12 actions+=/starsurge,if=active_enemies<8 actions+=/sunfire,target_if=refreshable&target.time_to_die>7&active_enemies<7 actions+=/starfire,if=spell_targets.starfire>1 actions+=/wrath  actions.cat=rake,if=buff.shadowmeld.up|buff.prowl.up|buff.sudden_ambush.up actions.cat+=/auto_attack,if=!buff.prowl.up&!buff.shadowmeld.up actions.cat+=/heart_of_the_wild,if=(cooldown.convoke_the_spirits.remains<30|!covenant.night_fae)&!buff.heart_of_the_wild.up actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=2&dot.adaptive_swarm_damage.remains>2 actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=1&dot.adaptive_swarm_damage.remains>2 actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=3&dot.adaptive_swarm_damage.remains>2 actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=4&dot.adaptive_swarm_damage.remains>2 actions.cat+=/adaptive_swarm,target_if=!dot.adaptive_swarm_damage.ticking actions.cat+=/run_action_list,name=owl,if=active_enemies>2&talent.convoke_the_spirits.enabled&talent.moonkin_form.enabled&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled) actions.cat+=/cat_form,if=talent.convoke_the_spirits.enabled&(active_enemies<2|!talent.moonkin_form.enabled)&(!buff.cat_form.up&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled)) actions.cat+=/convoke_the_spirits,if=(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled) actions.cat+=/rake,if=remains<=gcd&combo_points<5&(talent.deep_focus.enabled&active_dot.rake<=1&dot.rake.refreshable) actions.cat+=/rip,if=remains<=gcd&combo_points=5&(talent.deep_focus.enabled&active_dot.rip<=1&dot.rip.refreshable) actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5&spell_targets.thrash_cat>4 actions.cat+=/sunfire,target_if=(refreshable&target.time_to_die>5)&!prev_gcd.1.cat_form&(active_enemies=1|talent.improved_sunfire.enabled) actions.cat+=/cat_form,if=!buff.cat_form.up&energy>50&((dot.thrash_cat.refreshable&spell_targets.swipe_cat>=9&talent.thrash.enabled)|(talent.deep_focus.enabled&dot.rip.refreshable&active_dot.rip<=1&active_enemies>=5))&cooldown.healing.remains>(gcd.max*2) actions.cat+=/moonfire,target_if=(refreshable&time_to_die>12&!ticking|(prev_gcd.1.sunfire&remains<duration*0.8&spell_targets.sunfire=1))&!prev_gcd.1.cat_form actions.cat+=/sunfire,if=prev_gcd.1.moonfire&remains<duration*0.8 actions.cat+=/starsurge,if=active_enemies=1|(active_enemies<8&!buff.cat_form.up) actions.cat+=/starfire,if=time_to_die<10&spell_targets.starfire>1&(!talent.improved_swipe.enabled|spell_targets.swipe_cat>=9) actions.cat+=/cat_form,if=!buff.cat_form.up&energy>50 actions.cat+=/ferocious_bite,if=(combo_points>3&target.1.time_to_die<3)|(combo_points=5&energy>=50&dot.rip.remains>10)&spell_targets.swipe_cat<4 actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5&spell_targets.thrash_cat>2 actions.cat+=/rake,target_if=dot.adaptive_swarm_damage.ticking&refreshable actions.cat+=/rip,target_if=((refreshable|energy>90&remains<=10)&(combo_points=5&time_to_die>remains+24|(remains+combo_points*4<time_to_die&remains+4+combo_points*4>time_to_die))|!ticking&combo_points>2+spell_targets.swipe_cat*2) actions.cat+=/rake,target_if=(refreshable&time_to_die>10&spell_targets.swipe_cat<10)&(combo_points<5|remains<1) actions.cat+=/sunfire,target_if=refreshable&target.time_to_die>5&active_enemies<7&!talent.improved_sunfire.enabled actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5 actions.cat+=/swipe_cat,if=active_enemies>1&combo_points<5&talent.improved_swipe.enabled actions.cat+=/shred,if=energy>60&combo_points<5  actions.healing=strict_sequence,name=heal:regrowth:regrowth:regrowth  actions.owl=moonkin_form,if=!buff.moonkin_form.up actions.owl+=/convoke_the_spirits  head=mask_of_discontinuity,id=207606,bonus_id=9225/9221/6652/9414/9318/1488/8767 neck=eye_of_the_vengeful_hurricane,id=195496,bonus_id=6652/7982/1459/8767/8783/8781,gems=70haste_33crit_70haste_33mastery shoulders=ottuk_hide_epaulets,id=192014,bonus_id=6652/1491/5865/8767 back=deeprock_cloak,id=204914,bonus_id=6652/9317/1637/8767 chest=lost_landcallers_robes,id=200351,bonus_id=6652/8967/7977/8830/1472,enchant=waking_stats_3 tabard=valdrakken_accord_tabard,id=198732 wrists=tuskarr_trappers_bracers,id=199887,bonus_id=1472,enchant=devotion_of_leech_3 hands=lost_landcallers_claws,id=200353,bonus_id=7979/6652/8829/1472/8767 waist=inherited_cincture,id=204595,bonus_id=8902/9301/1491/8766 legs=suffused_breeches,id=204779,bonus_id=6652/9223/9221/9316/1533/8767 feet=ottuk_hide_waders,id=191991,bonus_id=6652/1485/5864/8767,enchant=watchers_loam_3 finger1=chronologically_unstable_loop,id=201960,bonus_id=7936/9378/1498/8767,enchant=devotion_of_haste_3 finger2=onyx_annulet,id=203460,bonus_id=1478,gem_id=204011/204012/204007/0,gem_bonus_id=9367/9367/9367/0,enchant=devotion_of_haste_3 trinket1=friendship_censer,id=204728,bonus_id=6652/9302/1611/8766 trinket2=azure_arcanic_amplifier,id=198407,bonus_id=41/1437/5864/8767 main_hand=neltharic_ritual_knife,id=204954,bonus_id=6652/9318/1640/8767 off_hand=scripture_of_primal_devotion,id=195513,bonus_id=6652/7979/1472/8767  # Gear Summary # gear_ilvl=397.13 # gear_stamina=13269 # gear_intellect=5749 # gear_crit_rating=2816 # gear_haste_rating=4256 # gear_mastery_rating=33 # gear_versatility_rating=1101 # gear_leech_rating=401 # gear_armor=2911 # set_bonus=tier29_2pc=1  ### End simulateText ### desired_targets=3 ### Begin overrides ### # User-specified persistent global and player parameters will be set here.  ### End overrides ### ### Begin final options ### ### End final options ### ### END ### ```

### Additional information
simc-1015.01.502edee-win64

* **simc_gui.simc** file or contents
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.025
max_time=300
vary_combat_length=0.1
fight_style=DungeonSlice
show_etmi=1
tmi_window_global=4
tank_dummy=Tank_Dummy_Mythic
tank_dummy_type=Mythic
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=0
override.power_word_fortitude=0
override.battle_shout=0
override.mark_of_the_wild=1
override.windfury_totem=0
override.bleeding=0
override.mortal_wounds=0
override.chaos_brand=0
override.mystic_touch=0
threads=14
process_priority=High
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
center_scale_delta=1
statistics_level=1
### Begin simulateText ###
druid="Kyneau"
source=blizzard
origin="https://worldofwarcraft.com/en-gb/character/kazzak/kyneau"
spec=restoration
level=70
race=zandalari_troll
zandalari_loa=paku
role=attack
position=back
talents=BkGAAAAAAAAAAAAAAAAAAAAAAgkENJJJpItkAHINaaplEAAAAAAAAAAAAokQIJCiEQIJhkASaJAAAAAAEBAAE

### Default consumables
potion=elemental_potion_of_ultimate_power_3
flask=phial_of_elemental_chaos_3
food=fated_fortune_cookie
augmentation=draconic
temporary_enchant=main_hand:howling_rune_3

### Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
### Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
### Executed before combat begins. Accepts non-harmful actions only.
actions.precombat+=/heart_of_the_wild
actions.precombat+=/cat_form,if=talent.rake.enabled
actions.precombat+=/prowl,if=talent.rake.enabled
actions.precombat+=/moonkin_form,if=talent.moonkin_form.enabled&!talent.rake.enabled

### Executed every time the actor is available.
actions=berserking
actions+=/natures_vigil,if=!buff.prowl.up&!buff.shadowmeld.up
actions+=/run_action_list,name=healing,if=!buff.prowl.up&!buff.shadowmeld.up&druid.time_spend_healing,line_cd=10
actions+=/use_items,if=!buff.prowl.up&!buff.shadowmeld.up
actions+=/potion,if=!buff.prowl.up&!buff.shadowmeld.up
actions+=/run_action_list,name=cat,if=talent.rake.enabled
actions+=/run_action_list,name=owl,if=active_enemies>2&talent.moonkin_form.enabled&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled)
actions+=/moonkin_form,if=talent.moonkin_form.enabled
actions+=/convoke_the_spirits,if=(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled)
actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=2&dot.adaptive_swarm_damage.remains>2
actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=1&dot.adaptive_swarm_damage.remains>2
actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=3&dot.adaptive_swarm_damage.remains>2
actions+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=4&dot.adaptive_swarm_damage.remains>2
actions+=/adaptive_swarm,target_if=!dot.adaptive_swarm_damage.ticking
actions+=/sunfire,target_if=refreshable&target.time_to_die>5&talent.improved_sunfire.enabled
actions+=/moonfire,target_if=refreshable&time_to_die>12
actions+=/starsurge,if=active_enemies<8
actions+=/sunfire,target_if=refreshable&target.time_to_die>7&active_enemies<7
actions+=/starfire,if=spell_targets.starfire>1
actions+=/wrath

actions.cat=rake,if=buff.shadowmeld.up|buff.prowl.up|buff.sudden_ambush.up
actions.cat+=/auto_attack,if=!buff.prowl.up&!buff.shadowmeld.up
actions.cat+=/heart_of_the_wild,if=(cooldown.convoke_the_spirits.remains<30|!covenant.night_fae)&!buff.heart_of_the_wild.up
actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=2&dot.adaptive_swarm_damage.remains>2
actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=1&dot.adaptive_swarm_damage.remains>2
actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=3&dot.adaptive_swarm_damage.remains>2
actions.cat+=/adaptive_swarm,target_if=dot.adaptive_swarm_damage.stack=4&dot.adaptive_swarm_damage.remains>2
actions.cat+=/adaptive_swarm,target_if=!dot.adaptive_swarm_damage.ticking
actions.cat+=/run_action_list,name=owl,if=active_enemies>2&talent.convoke_the_spirits.enabled&talent.moonkin_form.enabled&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled)
actions.cat+=/cat_form,if=talent.convoke_the_spirits.enabled&(active_enemies<2|!talent.moonkin_form.enabled)&(!buff.cat_form.up&cooldown.convoke_the_spirits.remains<=gcd.max&(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled))
actions.cat+=/convoke_the_spirits,if=(buff.heart_of_the_wild.up|cooldown.heart_of_the_wild.remains>60-30*talent.cenarius_guidance.enabled|!talent.heart_of_the_wild.enabled)
actions.cat+=/rake,if=remains<=gcd&combo_points<5&(talent.deep_focus.enabled&active_dot.rake<=1&dot.rake.refreshable)
actions.cat+=/rip,if=remains<=gcd&combo_points=5&(talent.deep_focus.enabled&active_dot.rip<=1&dot.rip.refreshable)
actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5&spell_targets.thrash_cat>4
actions.cat+=/sunfire,target_if=(refreshable&target.time_to_die>5)&!prev_gcd.1.cat_form&(active_enemies=1|talent.improved_sunfire.enabled)
actions.cat+=/cat_form,if=!buff.cat_form.up&energy>50&((dot.thrash_cat.refreshable&spell_targets.swipe_cat>=9&talent.thrash.enabled)|(talent.deep_focus.enabled&dot.rip.refreshable&active_dot.rip<=1&active_enemies>=5))&cooldown.healing.remains>(gcd.max*2)
actions.cat+=/moonfire,target_if=(refreshable&time_to_die>12&!ticking|(prev_gcd.1.sunfire&remains<duration*0.8&spell_targets.sunfire=1))&!prev_gcd.1.cat_form
actions.cat+=/sunfire,if=prev_gcd.1.moonfire&remains<duration*0.8
actions.cat+=/starsurge,if=active_enemies=1|(active_enemies<8&!buff.cat_form.up)
actions.cat+=/starfire,if=time_to_die<10&spell_targets.starfire>1&(!talent.improved_swipe.enabled|spell_targets.swipe_cat>=9)
actions.cat+=/cat_form,if=!buff.cat_form.up&energy>50
actions.cat+=/ferocious_bite,if=(combo_points>3&target.1.time_to_die<3)|(combo_points=5&energy>=50&dot.rip.remains>10)&spell_targets.swipe_cat<4
actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5&spell_targets.thrash_cat>2
actions.cat+=/rake,target_if=dot.adaptive_swarm_damage.ticking&refreshable
actions.cat+=/rip,target_if=((refreshable|energy>90&remains<=10)&(combo_points=5&time_to_die>remains+24|(remains+combo_points*4<time_to_die&remains+4+combo_points*4>time_to_die))|!ticking&combo_points>2+spell_targets.swipe_cat*2)
actions.cat+=/rake,target_if=(refreshable&time_to_die>10&spell_targets.swipe_cat<10)&(combo_points<5|remains<1)
actions.cat+=/sunfire,target_if=refreshable&target.time_to_die>5&active_enemies<7&!talent.improved_sunfire.enabled
actions.cat+=/thrash_cat,target_if=refreshable&target.time_to_die>5
actions.cat+=/swipe_cat,if=active_enemies>1&combo_points<5&talent.improved_swipe.enabled
actions.cat+=/shred,if=energy>60&combo_points<5

actions.healing=strict_sequence,name=heal:regrowth:regrowth:regrowth

actions.owl=moonkin_form,if=!buff.moonkin_form.up
actions.owl+=/convoke_the_spirits

head=mask_of_discontinuity,id=207606,bonus_id=9225/9221/6652/9414/9318/1488/8767
neck=eye_of_the_vengeful_hurricane,id=195496,bonus_id=6652/7982/1459/8767/8783/8781,gems=70haste_33crit_70haste_33mastery
shoulders=ottuk_hide_epaulets,id=192014,bonus_id=6652/1491/5865/8767
back=deeprock_cloak,id=204914,bonus_id=6652/9317/1637/8767
chest=lost_landcallers_robes,id=200351,bonus_id=6652/8967/7977/8830/1472,enchant=waking_stats_3
tabard=valdrakken_accord_tabard,id=198732
wrists=tuskarr_trappers_bracers,id=199887,bonus_id=1472,enchant=devotion_of_leech_3
hands=lost_landcallers_claws,id=200353,bonus_id=7979/6652/8829/1472/8767
waist=inherited_cincture,id=204595,bonus_id=8902/9301/1491/8766
legs=suffused_breeches,id=204779,bonus_id=6652/9223/9221/9316/1533/8767
feet=ottuk_hide_waders,id=191991,bonus_id=6652/1485/5864/8767,enchant=watchers_loam_3
finger1=chronologically_unstable_loop,id=201960,bonus_id=7936/9378/1498/8767,enchant=devotion_of_haste_3
finger2=onyx_annulet,id=203460,bonus_id=1478,gem_id=204011/204012/204007/0,gem_bonus_id=9367/9367/9367/0,enchant=devotion_of_haste_3
trinket1=friendship_censer,id=204728,bonus_id=6652/9302/1611/8766
trinket2=azure_arcanic_amplifier,id=198407,bonus_id=41/1437/5864/8767
main_hand=neltharic_ritual_knife,id=204954,bonus_id=6652/9318/1640/8767
off_hand=scripture_of_primal_devotion,id=195513,bonus_id=6652/7979/1472/8767

### End simulateText ###
desired_targets=3
### END ###

**Comment by gastank** [comment]
fixed in 8814744
