### ISSUE TITLE
Unable to create action: ashen_hallow

### ISSUE THREAD

**Issue by dbalata** [simulationcraft/simc#7972]
### Describe the bug
When trying to import a profile for my paladin, either through the addon or through lookup, the following error appears:
```
# Unable to generate profile from:

# Actor 'Ethic': Player 'Ethic' unable to create action: ashen_hallow
```

### Expected behavior
The import to succeed.

### To Reproduce
This should be easily reproducible by attempting to import a profile for Ethic - Kel'Thuzad

### Additional information
simc-1015.01.0376352-win64

[simc_gui.txt](https://github.com/simulationcraft/simc/files/12164065/simc_gui.txt)

(switched the extension to `.txt` to allow github upload)

**Comment by gastank** [comment]
Holy paladin dps simming support has not been actively updated to Dragonflight. At the very least you'll have to provide your own APL with obsolete abilities like ashen hallow taken out.

**Comment by seanpeters86** [comment]
closing due to stale
