### ISSUE TITLE
[DungeonRoute] Update delay functionality for pull raid_event

### ISSUE THREAD

**Issue by jordanritzie19** [simulationcraft/simc#7977]
### Is your feature request related to a problem? Please describe.
Yes, currently when the sim reaches the delay section of a DungeonRoute sim it prevents 2 things. Firstly, the actor is kept in combat, meaning spells like stealth and prowl don't get used. Secondly, it has the actor 'wait' instead of taking possible actions. For instance, if I wanted to use adaptive swarm (or even cat form) on myself between pulls, I cannot do so currently. 

### Describe the solution you'd like
I'd like if the actor was out of combat and able to use non-harmful spells during this delay portion

### Describe alternatives you've considered
Perhaps an option is to make all the mobs of the pull retarget to prevent harmful actions, or maybe a standalone raid event similar to pull that just contains 0 mobs for the specified amount of time before proceeding that doesn't put you in combat.

### Additional context
https://www.raidbots.com/simbot/report/pZdh67RLeJLrVsDHwoDoxP

For instance in this sim, prowl does not get casted between pulls. Also note that for some reason Cat Form doesn't even get casted until the delay period ends. I'm not really sure why Nature's Vigil can (and does) get casted regardless of waiting or not, though per the apl it should only be casted during combat anyway.

### p.s
Actually after looking at that sim link above, it would be really nice if pull delay can be separated from waiting, since it messes with the 'Spent Time' pie chart in the HTML report. Perhaps it could be renamed traveling or something I dont know.

**Comment by Jayezi** [comment]
There were some druid code changes yesterday that should allow all the strictly non-harmful stuff to work outside of combat, which is a fuzzy distinction in simc but for droute can be considered to be any time there's no active enemies alive and targetable. For adaptive swarm, it'd take an apl specifying the target to be the caster player with "target=self" to work. Shouldn't need anything to change about the raid events to make it happen at this point.
