### ISSUE TITLE
[Survival] Both T31 buffs not refreshed during channeling Fury of the Eagle 

### ISSUE THREAD

**Issue by valiliy** [simulationcraft/simc#8240]
### Describe the bug
Both T31 buffs: Fury Strikes and Contained Explosion seems not refreshed during Fury of the Eagle channeling.

### Expected behavior
Expecting Fury Strikes and Contained Explosion refresh duration after each Fury of the Eagle tick

### To Reproduce
On the PTR server after full channeling  Fury of the Eagle buffs duration 11-12 seconds left 
Run simulation with provided simc file content and you will see what after full FotE channel left only about 9 seconds

### Additional information
SimulationCraft Version is simc-1015.01.08a840b-win64

* **simc_gui.simc** file or contents
https://pastebin.com/Y8W2Sv3B

**Comment by Pewtro** [comment]
Should be fixed as of 6d3db5c72cfce6d6ae25c8a7f99a29af393bf8c4
