### ISSUE TITLE
casc_extract fails to parse .build.info (new format, multiple versions)

### ISSUE THREAD

**Issue by micolous** [simulationcraft/simc#8294]
### Describe the bug

`casc_extract.py` can't parse the current format of `.build.info` properly, and also can't handle having multiple versions of the game (eg: both live and PTR) installed. Both issues come from the same bit of code, so I've rolled these it into one report.

The fields on my copies of `.build.info` are:

```
Branch!STRING:0|Active!DEC:1|Build Key!HEX:16|CDN Key!HEX:16|Install Key!HEX:16|IM Size!DEC:4|CDN Path!STRING:0|CDN Hosts!STRING:0|CDN Servers!STRING:0|Tags!STRING:0|Armadillo!STRING:0|Last Activated!STRING:0|Version!STRING:0|KeyRing!HEX:16|Product!STRING:0
```

It's not clear to me which fields are client secrets, so I haven't posted it here. I can see the same file format on both the macOS and Windows versions of the game, so I suspect that most people should have the same file format. My files have:

* On a machine that has Live and PTR installed, that file has three lines: the header, followed by the Live install details, followed by the PTR install details.
* On a machine that only has Live installed, that file has two lines: the header, followed by the Live install details.

I've managed to get data extraction [using the `--cdn` option instead][1]; this just took a while to download everything again, and doesn't have any hotfix data.

[1]: https://github.com/simulationcraft/simc/wiki/Using-CASC-Extract-and-DBC-Extract#download-game-data-from-cdn

#### Incorrect format

Loading data from an installation with only one version gives:

```
$ python3 ./casc_extract.py -m batch -o ../casc_data/ -d '/path/to/warcraft/root'

casc_extract.py: error: Unknown file format for .build.info file, expected 14 fields, got 15
```

Despite that error, it looks like this is actually checking for _12_ fields, not _14_:

https://github.com/simulationcraft/simc/blob/d5fca19cf5578589865d017cc006dc4771f2e6be/casc_extract/build_cfg.py#L89-L91

It also appears to be hard coding field offsets:

https://github.com/simulationcraft/simc/blob/d5fca19cf5578589865d017cc006dc4771f2e6be/casc_extract/build_cfg.py#L93-L95

Ideally, this should read in the header line to figure out what the fields are what is expected, maybe even [use `csv.DictReader`][2] with [a custom dialect][3] if feasible.

[2]: https://docs.python.org/3/library/csv.html#csv.DictReader
[3]: https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters

#### Multiple versions

Extracting using an install with both Live and PTR installed gives:

```
$ python3 ./casc_extract.py -m batch -o ../casc_data/ -d '/path/to/warcraft/root'

Usage: casc_extract.py -d wow_install_dir [options] file_path ...

casc_extract.py: error: Unknown file format for .build.info file, expected 2 lines, got 3
```

This appears to be thrown from:

https://github.com/simulationcraft/simc/blob/d5fca19cf5578589865d017cc006dc4771f2e6be/casc_extract/build_cfg.py#L86-L87

### Expected behavior

It should be possible to extract data from the local cache when there are multiple versions of the game installed, and with files in the current Battle.net launcher.

### To Reproduce

1. Install WoW Retail (currently 10.1.7.51972) using Battle.net launcher, and wait for it to fully download.
2. (to reproduce multiple version issue) Install WoW PTR (currently 10.2.0.51851) using Battle.net launcher, and wait for it to fully download.
3. Run `casc_extract.py` pointed at that directory:
 
   `python3 ./casc_extract.py -m batch -o ../casc_data/ -d '/path/to/warcraft/root'`

### Additional information

* SimulationCraft Version (required): ea98a985a35f39762b78ba517ba4b09283ad8d93
* If SimulationCraft is crashing, please include your **dxdiag** file:  n/a
* **simc_gui.simc** file or contents: n/a
* Battle.net Launcher version: 2.26.1.14494

**Comment by navv1234** [comment]
Yes, this is broken, however, there are data format changes introduced into the locally stored CASC structures that prevent the local extraction from working right now. Most people just use the --cdn to fetch the assets required. Regardless, I'll try to see if i can fix the local extraction also.

**Comment by micolous** [comment]
Thanks! That saved me from hitting a wall trying to fix this myself :)

**Comment by navv1234** [comment]
Should be okay now, see the referenced commit.
