### ISSUE TITLE
Missing Pants

### ISSUE THREAD

**Issue by spaceturttle** [simulationcraft/simc#8372]
[this page](https://github.com/simulationcraft/simc/wiki/Equipment) is missing "legs" as an option in available slots.

[Slots keywords](https://github.com/simulationcraft/simc/wiki/Equipment#slots-keywords)
Acceptable slots are:

- meta_gem
- head
- neck
- shoulder, shoulders
- back
- shirt
- chest
- waist
- wrist, wrists
- hand, hands
- finger1, ring1, finger2, ring2
- trinket1, trinket2
- main_hand, off_hand
- ranged
- tabard

**Comment by spaceturttle** [comment]
and feet

**Comment by Pewtro** [comment]
Fixed
