### ISSUE TITLE
Bloodcraze shows the Slaughtering Strikes tooltip on Fury Sims

### ISSUE THREAD

**Issue by Tidalwar** [simulationcraft/simc#8419]
### Describe the bug
Bloodcraze shows the Slaughtering Strikes tooltip on Fury Sims....Does this affect the actual sim DPS too? Is picking Bloodcraze simming as if it was Slaughtering Strikes?

### Expected behavior
I would expect to see the Bloodcraze tooltip.

### To Reproduce

1. Open this sim https://www.raidbots.com/simbot/report/6TLcy2Uw9EX8fFLJBxRe3r/simc
2. Open T31 4pc section
3. Go to buffs
4. Hover over Bloodcraze

Screenshot of the bug:
![image](https://github.com/simulationcraft/simc/assets/6751786/fe7b5cd7-b60a-458f-b1aa-1de8e7a68777)

https://i.imgur.com/pr1tZ4y.png

### Additional information
* SimulationCraft Version (required)
[SimulationCraft 1020-01](https://www.simulationcraft.org/)
for World of Warcraft 10.2.0.52106 Live (hotfix 2023-11-10/52106, git build [1c2b41664a](https://github.com/simulationcraft/simc/commit/1c2b41664a))

**Comment by nyterage** [comment]
Tooltips are just pulled from Wowhead.com, has no bearings on what was actually run in that sim. Sadly, since its a wowhead tooltip issue, theres nothing we can really do.

**Comment by gastank** [comment]
This is a bug on blizzard's end. The bloodcraze buff refers to the slaughtering strikes description text most likely as a typo (bloodcraze is 393950, slaughtering strikes is 393930). Your only recourse is to report the bug in-game.
