### ISSUE TITLE
[Havoc DH] Incorrect Check for Unbound Chaos Buff Affecting Fel Rush/Immo/Inertia Interaction

### ISSUE THREAD

**Issue by Elehiggle** [simulationcraft/simc#8455]
APL will check if Unbound Chaos buff is up to determine if Fel Rush will trigger Inertia, but the Inertia talent only requires that you have HAD Unbound Chaos, it does not matter if you had the buff 1 minute ago, it will still trigger Inertia. Poorly formulated talent maybe.

Since APL will try to make use of Fel Rush when Unbound Chaos is up, I don't know if this really changes sims, since this only matters in situations where you have to take care a lot and can't use Fel Rush. This also changes behaviour of Immolation Aura usage.

**Comment by seanpeters86** [comment]
@Elehiggle is this still an issue?
