### ISSUE TITLE
Rogue/Assassination: Long Idle Periods Waiting for Envenom

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#8467]
### Describe the bug
In 10.2, the sim for Assassination seeks to pool Energy to chain Envenom for long periods of time.  However, this creates scenarios where there is extended idle time waiting for Energy to use Envenom (6+ seconds).  This appears misleading; it is likely there is other activity that could be completed to encourage Always Be Casting behavior.

### Expected behavior
Idle times should be minimized in the sim.

### To Reproduce
Looking at https://simulationcraft.org/reports/T31_Raid.html, we can see that the sim does a great job of keeping Envenom up most of the time.  However, later in the fight, we have a ~8s period of downtime.

![image](https://github.com/simulationcraft/simc/assets/9438134/44b8b3a2-4974-4fdd-90ac-b64efbb4f1a5)

For the well-geared Assassin, the end result isn't too problematic.  APM is near 60 with 8% of your time spent waiting.
![image](https://github.com/simulationcraft/simc/assets/9438134/3b7cb274-31c0-4de1-bf3b-6f548586b4c0)

**However**, in [lower gear](https://www.raidbots.com/simbot/report/mBLEjXCECa2QyZc6hBTAKP/simc), these occurances are more frequent and may cause Assassination to look underperformant.

![image](https://github.com/simulationcraft/simc/assets/9438134/88935d2e-7312-49b5-a312-2a343b330b82)

![image](https://github.com/simulationcraft/simc/assets/9438134/dc0e426a-2828-4064-bd5a-6d67cb3ee40b)

12.5 seconds!
![image](https://github.com/simulationcraft/simc/assets/9438134/40baa6a6-d094-4008-9be8-d8a12c862e48)

![image](https://github.com/simulationcraft/simc/assets/9438134/49da07ed-75c1-4e54-90c9-59937dec6c0b)

![image](https://github.com/simulationcraft/simc/assets/9438134/4365e6c8-2aa4-40c3-bc41-91ad6a2a8c05)

This puts the lower geared Assassin at 40 APM and waiting 30% of the time:
![image](https://github.com/simulationcraft/simc/assets/9438134/8a809597-312a-492a-b599-3c9c3e5047e0)

### Additional information
* [SimulationCraft 1020-01](https://www.simulationcraft.org/)
for World of Warcraft 10.2.0.52188 Live (hotfix 2023-11-22/52188, git build [9d9d7138af](https://github.com/simulationcraft/simc/commit/9d9d7138af))

**Comment by EvanMichaels** [comment]
Probably for @JannickMueller-Whispyr to double-check/review but "Always Be Casting behavior" isn't historically a thing for Assassination and long periods of pooling are fairly expected, especially at low haste levels with some builds. Assassination has very low Energy generation and especially if players take Sanguine Blades (which auto-spends Energy over 50%) this can lead to a very slow playstyle.

**Comment by JannickMueller-Whispyr** [comment]
@EvanMichaels is correct. Due to the chain of envenoms from the tier set and sanguine blades uptime, long idle times to reset the chain is a more efficient use of resources. Typically, ABC behavior is heavily steeped in a pretense of "if you're always casting something, you're not wasting a resource/cooldown." In the case of assassination, energy is a finite resource that creates an artificial limit to casts in a single target environment, causing optimizations to skew towards the efficiency of a resource rather than waste reduction. This is intended gameplay from the systems created around assassination in Season 3 of Dragonflight, and the implementation of the gameplay in simc is intended alongside it

**Comment by seanpeters86** [comment]
@Hekili good to close this?

**Comment by Hekili** [comment]
I'm okay with closing it, but not sure that I agree that 12.5 seconds of pooling is truly intended behavior. It's probably an edge case in low gear, so the issue is probably moot anyway for current players.
