### ISSUE TITLE
Survival Hunter throws more bombs than should

### ISSUE THREAD

**Issue by valiliy** [simulationcraft/simc#8470]
### Describe the bug
When sims target dummy damage with talent build without any signle talent in Ruthless Marauder I got more throws bombs than possible. It's look like FotE reset cd for bomb on crits ecent when no talents in Ruthless Marauder
Example: 
Sim sometimes shows Opening with Steel trap ->throw 1st bomb -> cast FotE and interrupt when gcd -> throw 2nd bomb -> throw 3rd bomb -> throw 4th bomb

https://i.imgur.com/apIaS07.png

### Expected behavior
Steel trap ->throw 1st bomb -> cast FotE and interrupt when gcd -> throw 2nd bomb -> throw 3rd bomb -> bomb still in cd for 5-6 seconds 
https://www.warcraftlogs.com/reports/tDy8F3hKn6C9vGWf#fight=17&type=casts&source=2&view=timeline

### To Reproduce
Run sim multiple times for action list with 3 bombs in line

### Additional information
SimulationCraft 1020-01] for World of Warcraft 10.2.0.52188 PTR (hotfix 2023-11-17/52188, git build [186d3b7](https://github.com/simulationcraft/simc/commit/186d3b7))

https://pastebin.com/raw/FTbdQy1Q

**Comment by Pewtro** [comment]
You're using the t31 4 piece, this seems entirely plausible?
I see no difference in the sim behaviour when adding even more ruthless marauder checks.

**Comment by valiliy** [comment]
4p t31 throw free bomb when start FotE and give free charge for bombs, but not reset cd for bomb 

Example: 
1. throw bomb - start 14sec cd for 1st charge, 2nd charge avaliable 
2. start FotE and inturrupt when gcd ready, T31 4p throw bomb and  give 1 free charge 
3. throw 2nd bomb and consume free charge from t31 4p,cd for 1st bomb still persist
4. throw 3rd bomb (2nd charge), cd for 1st bomb still persist

https://www.youtube.com/watch?v=y0gye2M_zzk
https://www.raidbots.com/simbot/report/ffZuNo9sMEuAz5VzZrKe7P

**Comment by valiliy** [comment]
Here more information
1. https://www.raidbots.com/simbot/report/gxgKkBJTKTkR6hRLqYmqHo/simc
This build without FotE, so we have only raw bombs without T31 4p bonus at all. 
We have for 6minutes about 14 casts for each bomb type  with total 42.64 casts average for 6 minutes

2. https://www.raidbots.com/simbot/report/hLxSCwe1eJ5whWBGLWcqdy/simc
Same build but with only FotE talent, so we have T31 4p bonus active. We have 11.3 avg casts for FotE for 6minutes so we should got 11.3 automatic impacts and 11.3 free charges at maximum so at average we should got 42.64 + 11.3 + 11.3 = 65.25 bomb impacts, but simulation result shows 24.78 for shrapnel, 24.27 for pheromone, 24.22 for volatile bombs with total 73.27 impacts at average which impossible for this build.
