### ISSUE TITLE
Shadowmeld does not attribute Crackshot to BtE's casts

### ISSUE THREAD

**Issue by mhunk** [simulationcraft/simc#8494]
https://github.com/simulationcraft/simc/blob/88735c060f44737c30542fb2962820afd6c967dd/profiles/Tier31/T31_Rogue_Outlaw.simc#L150

Video of Shadowmeld > BtE, incurring cooldown.
https://youtu.be/_PYNBocmxuA

**Comment by soloxcx** [comment]
Good catch, this line was written because Dungeonslice and Dungeonroute sims would properly Shadowmeld > Stealth > BtE on the non-boss targets, but on bosses it should not be possible to Shadowmeld > BtE and trigger Crackshot. Fixing shortly.
