### ISSUE TITLE
Greenlines unable to read 

### ISSUE THREAD

**Issue by symbolicrage** [simulationcraft/simc#8528]
![Simcraft Greenlines](https://github.com/simulationcraft/simc/assets/153960769/67150bd7-8945-430c-896a-f06d07b19ec4)

win11 23h2

video card driver # 546.17

12-15-2023 night build

Not sure what's wrong.

**Comment by renanthera** [comment]
Apologies for taking a while to get back to you on this, you were the only report of this behaviour until today and I had no way to replicate this.

Switching the graphics adapter used for rendering the Simc GUI from "Auto" to your NVidia GPU will fix this issue.

Nvidia Control Panel > 3D Settings > Manage 3D settings > Program Settings > (add SimulationCraft.exe) > OpenGL Rendering GPU > (select standalone gpu).

A fix may be possible on simc's side, but presently we have no one to replicate the issue unfortunately.
