### ISSUE TITLE
Ubuntu installation instructions not working with 22.04

### ISSUE THREAD

**Issue by matteolucchini1** [simulationcraft/simc#8532]
### Describe the bug
The guide for building locally on Ubuntu states "Install qt5-qmake & qt5-webengine if you want to build the GUI. On Ubuntu, the required packages are called qt5-default and qtwebengine5-dev". However, qt5-default does not seem to be available for Ubuntu 22.04 (https://stackoverflow.com/questions/74110674/problem-installing-qt5-default-on-ubuntu-22-04), resulting in cmake throwing an error:

```
CMake Error at qt/CMakeLists.txt:3 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:
    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake
  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
```

Replacing qt5-default with qtbase5-dev or qt5-qmake per the StackOverflow post above does not work either.

### Additional information
The commit I'm attempting to build from is 836b2903.

**Comment by RobinFrcd** [comment]
Just tried `sudo apt install qtwebengine5-dev`, seems to help

**Comment by matteolucchini1** [comment]
I tried that also but it didn't work, same error message.

**Comment by matteolucchini1** [comment]
Issue fixed, I had to remove the CmakeCache.txt file manually.
