### ISSUE TITLE
WOLK Classic Support

### ISSUE THREAD

**Issue by mprimeaux** [simulationcraft/simc#8549]
Is WOTLK Classic still supported in SimC? Asking for a friend :)

**Comment by vituscze** [comment]
WotLK classic was never supported.

**Comment by mprimeaux** [comment]
Thanks. Sincerely appreciate you taking the time to reply.

**Comment by Undertoe** [comment]
@mprimeaux I recommend you check out wowsims: https://wowsims.github.io/wotlk/

The power isn't quite as strong as simcraft but it will be able to get most of your questions answered.
