### ISSUE TITLE
Xeri'tac's Unhatched Egg Sac Not Implemented

### ISSUE THREAD

**Issue by Eltinator92** [simulationcraft/simc#8556]
### Describe the bug
Running a few sims I am unable to proc the "Xeri'tac's Unhatched Egg Sac" and doing a search of the code it seems this trinket may not be implemented altough it does perform quite well for tank DPS and can might be a good option for M+ tanks that cant get the Fyrakk Trinkets.

### Expected behavior
When the tank takes damadge the trinket should spawn an add that shields the tank and attacks nearby enemies (training dummy logs suggests about 6% of a warrior tanks dmg should be from this trinket)

### Additional information
SimulationCraft Version 1020-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
"
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead/ptr2head
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HecticAddCleave
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.mark_of_the_wild=1
override.windfury_totem=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=20
process_priority=Above_normal
statistics_level=1
### Begin simulateText ###
# Post your Simc Addon Export text here.
# Thandrell - Protection - 2023-12-29 12:24 - US/Barthilas
# SimC Addon 10.2.0-01
# WoW 10.2.0.52649, TOC 100200
# Requires SimulationCraft 1000-01 or newer

warrior="Thandrell"
level=70
race=blood_elf
region=us
server=barthilas
role=tank

spec=protection

talents=BkEAfuKaizEAgP2qANDB2hmf7LEBAAAASSSkkQSLpkkkCEBCFJSUSCgAJBNkkECQkAAAAAAAASAAKlGAIA

# Saved Loadout: icy
# talents=BkEAfuKaizEAgP2qANDB2hmf7LEBAAAASSSkkQSLpkkkCEBCFJSUSCgAJBNkkECQkAAAAAAAASAAKlGAIA

# Molten Vanguard's Domeplate (483)
head=,id=207182,enchant_id=7052,bonus_id=40/9600/7980/8094/9513/9581/1514/8767
# Elemental Lariat  (486)
neck=,id=193001,gem_id=192991/192935/192935,bonus_id=8836/8840/8902/8960/9477/8782/9405/8792/9500/9498,crafted_stats=36/49,crafting_quality=5
# Molten Vanguard's Shouldervents (483)
shoulder=,id=207180,bonus_id=6652/7980/8094/9511/9581/1514/8767
# Shadowfeather Shawl (483)
back=,id=136977,enchant_id=6604,bonus_id=9639/6652/9506/9144/9581/9876/8767
# Molten Vanguard's Plackart (483)
chest=,id=207185,enchant_id=6625,bonus_id=6652/7980/8094/9515/9581/1514/8767
# Zealous Commander's Cuffs (483)
wrist=,id=207923,enchant_id=6586,bonus_id=9639/6652/9599/9506/9144/9581/1576/8767
# Ravencrest Bonecrush Gauntlets (483)
hands=,id=134519,bonus_id=9639/6652/9506/9144/9581/9876/8767
# Unwinding Eon Girdle (483)
waist=,id=207858,enchant_id=6904,gem_id=192935,bonus_id=9639/6652/9516/9506/9144/9581/1576/8767
# Molten Vanguard's Steel Tassets (483)
legs=,id=207181,enchant_id=6490,bonus_id=6652/7980/9512/9581/1514/8767
# Goldsteel Sabatons (483)
feet=,id=109795,enchant_id=6607,bonus_id=9639/6652/9506/9144/9581/9882/8767
# Ring-Bound Hourglass  (486)
finger1=,id=193000,enchant_id=6568,gem_id=192935,bonus_id=8836/8840/8902/8780/9405/8792/9500/9498,crafted_stats=49/40,crafting_quality=5
# Thornwoven Band (489)
finger2=,id=162548,enchant_id=6568,bonus_id=9639/6652/9600/9144/9576/9853/8767
# Accelerating Sandglass (483)
# trinket1=,id=207566,bonus_id=9639/6652/9144/9581/1534/8767
# Xeri'tac's Unhatched Egg Sac (483)
trinket1=,id=110019,bonus_id=9639/6652/9144/9581/9882/8767
# Ember of Nullification (489)
trinket2=,id=136978,bonus_id=9639/6652/9144/9576/9882/8767
# Primal Molten Longsword  (486)
main_hand=,id=190507,enchant_id=6643,bonus_id=8836/8840/8902/9405/9500/8791/9498,crafted_stats=32/40,crafting_quality=5
# Primal Molten Defender  (486)
off_hand=,id=190503,bonus_id=8836/8840/8902/9405/9500/8792/9379/8960/9498,crafted_stats=40/49,crafting_quality=5

### Gear from Bags
#
# Incarnate's Perceptive Casque (470)
# head=,id=207920,bonus_id=9569/9639/6652/9600/9506/9144/1557/8767
#
# Greathelm of the Unbreakable (428)
# head=,id=123984,bonus_id=9536/7756/9518/3325/8766
#
# Perennial Pompon Pendant (415)
# neck=,id=209915,bonus_id=9544/6652/8784/10244/1472
#
# Oathsworn Amulet (424)
# neck=,id=154043,bonus_id=3303/8767
#
# Raven Filigree Pendant (480)
# neck=,id=134499,bonus_id=9639/6652/8784/10245/9144/9572/9853/8767
#
# Slumbering Ursine Talisman (460)
# neck=,id=208443,bonus_id=42/8783/10244/7979/9562/1491/8767
#
# Arctic Warden's Shoulderplates (444)
# shoulder=,id=210365,bonus_id=9553/9506/6652/1475/8767
#
# Harp Shell Pauldrons (467)
# shoulder=,id=133185,bonus_id=9568/9639/6652/9506/9144/9853/8767
#
# Dazhak's Desiccated Wingbones (457)
# shoulder=,id=207921,bonus_id=9561/9639/6652/9506/9144/1547/8767
#
# Spaulders of Slaughter (428)
# shoulder=,id=124011,bonus_id=9536/7756/3325/8766
#
# Frigid Conservator's Wrap (444)
# back=,id=210382,bonus_id=9553/9506/6652/1475/8767
#
# Arctic Warden's Cloak (441)
# back=,id=210408,bonus_id=9552/9506/6652/1472/8767
#
# Abalone Plate Armor (470)
# chest=,id=133202,bonus_id=9569/9639/6652/9506/9144/9876/8767
#
# Netherforce Chestplate (428)
# chest=,id=133478,bonus_id=9536/7756/3325/8766
#
# Etheldrin's Breastplate (470)
# chest=,id=136976,bonus_id=9569/9639/6652/9506/9144/9843/8767
#
# Zealous Commander's Cuffs (460)
# wrist=,id=207923,bonus_id=9562/9639/6652/9599/9506/9144/1553/8767
#
# Oathsworn Armguards (424)
# wrist=,id=154050,bonus_id=3303/8767
#
# Chartreuse Champion's Bracers (421)
# wrist=,id=209908,bonus_id=9546/6652/9600/1478/8766
#
# Shadowshroud Vambraces (463)
# wrist=,id=160212,bonus_id=9563/9639/6652/9599/9506/9144/9458/8767
#
# Shadowshroud Vambraces (470)
# wrist=,id=160212,bonus_id=9569/9639/6652/9599/9506/9144/9834/8767
#
# Incarnadine Bracers (470)
# wrist=,id=109876,bonus_id=9569/9639/6652/9600/9506/9144/9849/8767
#
# Arctic Warden's Gauntlets (463)
# hands=,id=210354,bonus_id=9506/6652/9559/1494/8767
#
# Oathsworn Handguards (424)
# hands=,id=154040,bonus_id=3303/8767
#
# Molten Vanguard's Crushers (483)
# hands=,id=207183,bonus_id=6652/9639/9514/9581/1514/8767
#
# Girdle of the Righteous Path (101)
# waist=,id=29965,bonus_id=9035,drop_level=30
#
# Onslaught Belt (109)
# waist=,id=34546,bonus_id=9037,drop_level=30
#
# Greatbelt of Disruption (470)
# waist=,id=137310,bonus_id=9569/9639/6652/9599/9506/9144/9843/8767
#
# Unwinding Eon Girdle (483)
# waist=,id=207858,enchant_id=6904,bonus_id=9639/6652/9599/9506/9144/9581/1576/8767
#
# Rivet-Sealed Waistplate (470)
# waist=,id=109841,bonus_id=9569/9639/6652/9599/9506/9144/9849/8767
#
# Oathsworn Waistband (424)
# waist=,id=154049,bonus_id=3303/8767
#
# Bloodlord Legplates (428)
# legs=,id=188293,bonus_id=9536/7756/3325/8766
#
# Destroyer Greaves (101)
# legs=,id=30121,bonus_id=9035,drop_level=30
#
# Rook Footman's Legplates (470)
# legs=,id=139240,bonus_id=9569/9639/6652/9506/9144/9843/8767
#
# Marbled Oathstone Greatboots (467)
# feet=,id=207950,bonus_id=9568/9639/6652/9506/9144/1560/8767
#
# Dreadboots of the Legion (467)
# feet=,id=150497,bonus_id=9568/7756/9505/9878/8767
#
# Goldsteel Sabatons (457)
# feet=,id=109795,bonus_id=9561/9639/6652/9506/9144/9836/8767
#
# Boots of the Righteous Path (428)
# feet=,id=124027,bonus_id=9536/7756/3325/8766
#
# Fatty Hooves of Gory Comfort (463)
# feet=,id=159452,bonus_id=9563/9639/6652/9506/9144/9458/8767
#
# Anthia's Ring (467)
# finger1=,id=133189,enchant_id=6568,bonus_id=9568/9639/6652/9599/9144/9853/8767
#
# Thornwoven Band (483)
# finger1=,id=162548,enchant_id=6568,bonus_id=9639/6652/9600/9144/9581/9847/8767
#
# Oathsworn Band of Stoicism (424)
# finger1=,id=154045,enchant_id=6563,bonus_id=3303/8767
#
# Band of the Abyssal Lord (454)
# finger1=,id=150459,bonus_id=9560/7756/9845/8767
#
# Beautiful Blizzard Binding (441)
# finger1=,id=210376,bonus_id=9552/6652/9599/1472/8767
#
# Rime Ridden Ring (444)
# finger1=,id=210378,enchant_id=6563,bonus_id=9553/6652/9600/1475/8767
#
# Oathsworn Ring of Stoicism (424)
# finger1=,id=154046,bonus_id=3303/8767
#
# Arch-Druid's Tainted Seal (476)
# finger1=,id=134487,bonus_id=9639/6652/9600/9144/9567/9849/8767
#
# Iron Branch (123)
# trinket1=,id=130126,bonus_id=6691,drop_level=45
#
# Oathsworn Defender Stone (424)
# trinket1=,id=154047,bonus_id=3303/8767
#
# Mirror of Fractured Tomorrows (480)
# trinket1=,id=207581,bonus_id=9639/6652/9144/9572/1531/8767
#
# Accelerating Sandglass (483)
# trinket1=,id=207566,bonus_id=9639/6652/9144/9581/1534/8767
#
# Ashes of the Embersoul (460)
# trinket1=,id=207167,bonus_id=6652/7979/9562/1491/8767
#
# Spores of Alacrity (460)
# trinket1=,id=110014,bonus_id=9562/9639/6652/9144/9839/8767
#
# Commendation of Kael'thas (428)
# trinket1=,id=133464,bonus_id=9536/7756/3325/8766
#
# Oathsworn Defender Idol (424)
# trinket1=,id=154044,bonus_id=3303/8767
#
# Whitefin Axe (483)
# main_hand=,id=133196,enchant_id=6643,bonus_id=9639/6652/9147/9581/9889/8767
#
# Whitefin Axe (483)
# main_hand=,id=133196,enchant_id=6643,bonus_id=9639/41/9147/9581/9889/8767
#
# Oathsworn Greataxe (424)
# main_hand=,id=170743,bonus_id=3285/8767
#
# Oathsworn Headchopper (424)
# main_hand=,id=170744,bonus_id=3285/8767
#
# World Breaker (101)
# main_hand=,id=30090,bonus_id=9035,drop_level=30
#
# Adulation Enforcer (463)
# main_hand=,id=159632,bonus_id=9563/9639/6652/9147/9458/8767
#
# Quel'Zaram, High Blade of the Lion (483)
# main_hand=,id=207994,enchant_id=6643,bonus_id=9522/9639/6652/9147/9581/1605/8767
#
# Gurubashi Punisher (42)
# main_hand=,id=69803,bonus_id=4236,drop_level=35
#
# Oathsworn Axe (424)
# main_hand=,id=170745,bonus_id=3285/8767
#
# Oathsworn Axe (424)
# main_hand=,id=154035,bonus_id=3303/8767
#
# Corrupted Knot (457)
# main_hand=,id=211473,bonus_id=9561/9639/6652/9147/3136/8767
#
# Shield of the Void (428)
# off_hand=,id=127254,bonus_id=9536/7756/3326/8766
#
# Oathsworn Bulwark (424)
# off_hand=,id=154036,bonus_id=3303/8767
#
# Arctic Warden's Bulwark (441)
# off_hand=,id=210383,bonus_id=9552/6652/1472/8767
#
# Murozond's Timeless Scale (467)
# off_hand=,id=207978,bonus_id=9568/9639/6652/9144/1589/8767
#
# Etched Osteoderm Shield (106)
# off_hand=,id=119391,bonus_id=6691,drop_level=40
#
# Murozond's Timeless Scale (460)
# off_hand=,id=207978,bonus_id=9639/6652/9144/9562/1582/8767
#
# Golden Tomb Defender (194)
# off_hand=,id=160978,bonus_id=4776,drop_level=60

### Additional Character Info
#
# upgrade_currencies=c:2708:188/c:2707:52/c:2706:67/c:2245:1162
#
# slot_high_watermarks=0:483:483/1:486:486/2:483:483/3:483:483/4:483:483/5:483:489/6:483:486/7:483:483/8:483:489/9:486:486/10:483:483/11:483:486/12:483:483/13:0:389/14:486:486/15:483:483/16:486:486

# Checksum: 1d29f98a
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###
"

**Comment by renanthera** [comment]
Keep in mind that this trinket has Stamina on it instead of Mainstat or a secondary stat.
Even if it yields "large" bars on Details or Warcraftlogs, it needs to perform significantly ahead of any other option in the game, and that's just not the case.

A PR to implement it would be welcomed, but I doubt that any of the active simc maintainers would implement it, especially at this point in the tier.
