### ISSUE TITLE
Unholy DK "invalid talent tree hash"

### ISSUE THREAD

**Issue by mpalermo73** [simulationcraft/simc#8560]
### Describe the bug
I'm getting an "invalid talent tree hash" when importing my profile from Blizzard

### Expected behavior
Pull profile and sim

### To Reproduce
Dawnbringer --> Lofar

```
Player Lofar has invalid talent tree hash BwPAAAAAAAAAAAAAAAAAAAAAAAAiERCJtIhgIJhQSiEBAAAAAAAAAAJJhEJpAAQKS5AkkkIJHA: selected node 76165 is not available to player's spec.
Error: Actor 'Lofar': Action 'army_of_the_dead': Cannot parse expression from 'talent.commander_of_the_dead&(cooldown.dark_transformation.remains<3|buff.commander_of_the_dead_window.up)|!talent.commander_of_the_dead&talent.unholy_assault&cooldown.unholy_assault.remains<10|!talent.unholy_assault&!talent.commander_of_the_dead|fight_remains<=34': Cannot find buff 'commander_of_the_dead_window'.
```

### Additional information
* SimulationCraft Version (required)
```
commit 4cf54fdf15d8bdf8d7b339b162d8602646165007 (HEAD -> dragonflight, origin/dragonflight, origin/HEAD)
Author: Jayezi <4423285+Jayezi@users.noreply.github.com>
Date:   Sun Dec 31 20:50:22 2023 -0600
```

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
- N/A

* **simc_gui.simc** file or contents
Not using GUI

This is the actual talents exported from the game itself:
```
BwPA/gf1fDREKLfAcG9Z2HkF/BAiQSCJiERkIRIkkIRAAAAAAAAAgCJ5AhIJpBAQiUEJJJSyBA
```

blizzard.simc
```
armory=us,dawnbringer,lofar
save=profile.simc
```

[profile.simc.txt](https://github.com/simulationcraft/simc/files/13804880/profile.simc.txt)

**Comment by nyterage** [comment]
hrmm, running the armory import on a fresh build does appear to work just fine. your `profile.simc` input file that you linked here, appears to be from season 1 of dragonflight, including an APL (and apl features) that havent existed since 10.0.7. Are you just trying to run that profile? if so, it wont work in the current simc builds.

**Comment by mpalermo73** [comment]
> your `profile.simc` input file that you linked here, appears to be from season 1 of dragonflight

:facepalm: 

You're completely right.  I was using the cli and had the symlink for `profile.simc` pointing to the wrong place...  Pointing it to the correct profile (fresh from the in-game ui) and everything runs fine.

I'm sorry for having totally wasted your time...

M.
