### ISSUE TITLE
The target's health percentages do not affect the simulation

### ISSUE THREAD

**Issue by tecbiio** [simulationcraft/simc#8572]
### Describe the bug
The target's health percentages do not seem to be taken during the simulation.

### Expected behavior
The target's health percentages should be taken dynamically during the simulation in order to correctly handle the different spells that are modified by the target's health percentages. (Like the **shadow word : death**)

### To Reproduce
I ran three simulations each time with a different _enemy_health_ parameter. Two where the target's health percentage varies and one where it does not vary. The three simulations indicate a roughly equivalent dps. What is abnormal.
[sim1.txt](https://github.com/simulationcraft/simc/files/13834387/sim1.txt)
[sim2.txt](https://github.com/simulationcraft/simc/files/13834388/sim2.txt)
[sim3.txt](https://github.com/simulationcraft/simc/files/13834389/sim3.txt)

### Additional information
* SimulationCraft Version 1020-01

* **simc_gui.simc** file or contents
[simc_gui.txt](https://github.com/simulationcraft/simc/files/13834413/simc_gui.txt)
(Change the extension to .simc to use)

**Comment by Azevara** [comment]
The only input file you provided has a fixed health value. Please provide the other inputs in order to reproduce.

**Comment by tecbiio** [comment]
The inputs replace the inital health value according to the wiki :
![image](https://github.com/simulationcraft/simc/assets/73758134/3e2f9a04-477e-44a1-8953-9168c4aa06af)
Health value decreases during combat

**Comment by tecbiio** [comment]
The simc_gui file is provided from the latest simulation.
I can redo the simulations I mention if you wish.

**Comment by Azevara** [comment]
You have three outputs but only one input file. To reproduce and compare each of the outputs we need the exact inputs for each of the three sims.

You also mention that there are "Two where the target's health percentage varies" but that is not seen in the current input parameters.

**Comment by tecbiio** [comment]
Ok, let's be clear, the dps is generally the same. (less than 0.01% difference between each simulation)
But, I should have considerably more damage when the target goes below 35% first and then 20% afterwards. For the respective use of my staff active and the spell: Shadow word: death.

Here are the simulations : 

## Character import : 
[character.txt](https://github.com/simulationcraft/simc/files/13841830/character.txt)

## Simulation 1 :

### Inputs : 
```
enemy=Fluffy_Pillow 
enemy_health=27000000
```
### Simc_gui : 
[simc_gui.txt](https://github.com/simulationcraft/simc/files/13841847/simc_gui.txt)

![image](https://github.com/simulationcraft/simc/assets/73758134/4cae0540-51ff-4d67-8800-b2de80e9c30d)

## Simulation 2 : 

### Inputs : 
```
enemy=Fluffy_Pillow 
enemy_health=9999999999999999999
```
### Simc_gui : 
[simc_gui.txt](https://github.com/simulationcraft/simc/files/13841889/simc_gui.txt)

![image](https://github.com/simulationcraft/simc/assets/73758134/92c647cf-bb65-43eb-9b9e-151f91f02a9d)

## Simulation 3 : 

### Inputs : 
no inputs, default values
### Simc_gui : 
[simc_gui.txt](https://github.com/simulationcraft/simc/files/13841903/simc_gui.txt)

![image](https://github.com/simulationcraft/simc/assets/73758134/a4e8c198-a7a6-4a3b-b64f-eec621480e91)

### P.S : 
How is it possible to have this in the Abilities summary of the simulation 2 ?
![image](https://github.com/simulationcraft/simc/assets/73758134/b9e40e1f-b2cf-4985-ac17-df5fc4b68dc7)
As you can see, the enemy must be under 35% health to use it.

**Comment by Dorovon** [comment]
If you want to override the health of enemies to an absolute number and want it to affect that you will also need to add `fixed_time=0` to your input. With the default of `fixed_time=1`, the "percentage health" of enemies used for effects like that staff is not a function of their absolute health value and is determined based on the fraction of the simulation's time that has passed (although the absolute health is still shown on that graph because it can be useful sometimes).

Note that if you use `fixed_time=0`, the simulation will end when the main target dies (and will stop early with an error message if you use a health value that is too high, such as the one in your second example).

Lastly, you might find the percentage settings easier to use for examining this sort of thing (https://github.com/simulationcraft/simc/wiki/Enemies#health-related-options).
