### ISSUE TITLE
Error importing my monk. Addon or Site

### ISSUE THREAD

**Issue by ChristopherPBS** [simulationcraft/simc#8596]
### Describe the bug
I cant import my monk Pshaolin-Goldrin

### Expected behavior
Expecting import. 

### To Reproduce
Try import Pshaolin-Goldrinn

### Additional information

# SimulationCraft encountered an error! # SimulationCraft 1020-01 for World of Warcraft 10.2.0.52808 Live # hotfix 2024-01-10/52808, git build dragonflight d08cf7a * Category: Simulation runtime error * Error: Initializing: Actor 'Pshaolin': Action 'chi_burst': Cannot parse expression from '!talent.jadefire_stomp': Cannot find talent 'jadefire_stomp'.  ## All options used for simulation: ``` ini ### SimulationCraft 1020-01 for World of Warcraft 10.2.0.52808 Live (wow build 52808, git build dragonflight d08cf7a)  ### ### Using QT 6.4.0 with WebEngine ###  ### Begin GUI options ### ptr=0 item_db_source=ptr2head/ptrhead/local/bcpapi/wowhead target_error=0 iterations=0 default_world_lag=0.20 max_time=200 vary_combat_length=0.2 fight_style=DungeonSlice tmi_window_global=6 target_level+=2 target_race=Humanoid optimal_raid=0 override.bloodlust=1 override.arcane_intellect=1 override.power_word_fortitude=1 override.battle_shout=1 override.mark_of_the_wild=1 override.windfury_totem=1 override.bleeding=1 override.mortal_wounds=1 override.chaos_brand=1 override.mystic_touch=1 threads=12 process_priority=Low calculate_scale_factors=1 scale_only=str,agi,sta,int,crit,haste,mastery,vers,wdps,wohdps statistics_level=1 ### End GUI options ### ### Begin simulateText ### # Pshaolin - Windwalker - 2024-01-15 23:05 - US/Goldrinn # SimC Addon 10.2.0-01 # WoW 10.2.0.52808, TOC 100200 # Requires SimulationCraft 1000-01 or newer  monk="Pshaolin" level=70 race=mechagnome region=us server=goldrinn role=attack professions=mining=65/engineering=44 spec=windwalker  talents=B0QAPOfh8E5EV1u1/5sg+UnhAAAAAAAAARSkkElkIRAAAAgEJJNJASSigUSSEJ0KSSaJJtEAAAA  # Saved Loadout: M+ # talents=B0QAPOfh8E5EV1u1/5sg+UnhAAAAAAAAARSkkElkIRAAAAgEJJNJASSigUSSEJ0KSSaJJtEAAAA  # Hatsuburi da Garça Mística (463) head=,id=207245,bonus_id=43/9599/9513/9639/9563/1494/8767 # Corrente da Revoada Verde (460) neck=,id=137311,bonus_id=9562/9639/6652/8784/9516/9144/9466/8767 # Guarda-ombros do Sábio Degradado (483) shoulder=,id=150768,bonus_id=7756/9505/9581/9893/8767 # Manto de Caramujo (476) back=,id=133180,bonus_id=9571/9639/6652/9506/9144/9882/8767 # Fardos da Garça Mística (463) chest=,id=207248,enchant_id=6624,bonus_id=41/9515/9636/9559/1494/8767 # Tabardo Gnomecânico (1) tabard=,id=174068 # Embraces do Santuário Verdejante (470) wrist=,id=210206,bonus_id=6652/9516/9508/7980/9569/1501/8767 # Luvas Pontiagudas da Garça Mística (476) hands=,id=207246,bonus_id=6652/9639/9514/9567/1507/8767 # Cinto da Mantenedora Cristalina (447) waist=,id=210371,bonus_id=9506/6652/9599/9554/1478/8767 # Galochas da Garça Mística (476) legs=,id=207244,bonus_id=6652/9512/9571/9639/1507/8767 # Sapatilhas de Decápode (473) feet=,id=133190,bonus_id=9570/9639/6652/9506/9144/9879/8767 # Elo Trançado com Espinhos (460) finger1=,id=162548,enchant_id=6547,bonus_id=9639/6652/9516/9144/9558/9455/8767 # Sinete da Última Anciã (463) finger2=,id=207162,enchant_id=6547,bonus_id=6652/9599/7982/9559/1494/8767 # Ídolo de Serpente Enroscada (470) trinket1=,id=207175,bonus_id=6652/7980/9569/1501/8767 # Caranguejo de Porcelana (457) trinket2=,id=133192,bonus_id=9639/6652/9144/9557/9843/8767 # Ecos Uivantes (476) main_hand=,id=211513,bonus_id=9571/9639/6652/9147/3155/8767  ### Gear from Bags # # Socapa da Mantenedora Cristalina (444) # head=,id=210359,bonus_id=9553/9506/6652/9600/1475/8767 # # Capacete Mão Despedaçada do Clarão de Fogo (66) # head=,id=25018,bonus_id=6654/1693,drop_level=30 # # Diadema da Alvorada (415) # neck=,id=209916,bonus_id=9544/6652/8784/10244/1472 # # Pingente Primevista (327) # neck=,id=194369,bonus_id=7963,drop_level=70 # # Gargantilha Onírica (428) # neck=,id=209356,bonus_id=9536/8783/9414/1550/8766 # # Ombreiras da Mantenedora Cristalina (450) # shoulder=,id=210364,bonus_id=9555/9506/6652/1481/8767 # # Ombreiras da Mantenedora Cristalina (441) # shoulder=,id=210364,bonus_id=9552/9506/6652/1472/8767 # # Efígie Esperançosa da Garça Mística (444) # shoulder=,id=207243,bonus_id=6652/9553/7982/8096/9511/1475 # # Palas Punho de Sangue do Clarão de Fogo (66) # shoulder=,id=25004,bonus_id=6654/1693,drop_level=30 # # Clâmide do Vassalo Leal (457) # back=,id=158375,bonus_id=9561/9639/6652/9506/9144/3327/8767 # # Mantelete do Apaziguador do Verão (421) # back=,id=209918,bonus_id=9546/6652/1478/8766 # # Mantelete do Apaziguador do Verão (415) # back=,id=209918,bonus_id=9544/6652/1472 # # Manto do Sacrifício Fulgurante (460) # back=,id=207161,enchant_id=6588,bonus_id=6652/9507/7982/9558/1491/8767 # # Xale da Pluma Sombria (460) # back=,id=136977,bonus_id=9562/9639/6652/9506/9144/9466/8767 # # Carapaça Corroída de Ahnzon (463) # chest=,id=207836,bonus_id=9563/9639/6652/9506/9144/1553/8767 # # Peito d'Armas do Lobo do Vento (418) # chest=,id=210085,bonus_id=9545/6652/1475 # # Colete da Fada Destemida (415) # chest=,id=209887,bonus_id=9544/6652/1472 # # Munhequeiras do Feitor de Escravos do Gumepresto (66) # wrist=,id=24628,bonus_id=6654/1681,drop_level=30 # # Braceletes de Couro de Raptor Venerado (463) # wrist=,id=160214,enchant_id=6572,bonus_id=9639/6652/9600/9506/9144/9563/9458/8767 # # Braceletes da Vida  (463) # wrist=,id=193419,bonus_id=8836/8840/8902/9405/9498/9600,crafted_stats=32/36,crafting_quality=5 # # Braceletes Oníricos (415) # wrist=,id=209399,bonus_id=9544/9223/9220/9414/1537 # # Cinto da Luta Eterna (447) # waist=,id=207874,bonus_id=9554/9639/6652/9599/9506/9144/1540/8767 # # Cinturão Salgado Cravejado de Conchas (447) # waist=,id=133368,bonus_id=9636/43/9599/9506/9144/9554/9466/8767 # # Calçotes da Fada Destemida (415) # legs=,id=209898,bonus_id=9544/6652/1472 # # Coxotes Punho de Sangue da Aurora (66) # legs=,id=25003,bonus_id=6654/1705,drop_level=30 # # Calças Astralaan da Aurora (66) # legs=,id=24650,bonus_id=6654/1709,drop_level=30 # # Coxotes do Aniquilador do Clarão de Fogo (66) # legs=,id=24979,bonus_id=6654/1693,drop_level=30 # # Grevas Encadeadas de Faronaar do Gumepresto (114) # feet=,id=121043,bonus_id=6654/43/1682,drop_level=45 # # Botas da Fada Destemida (415) # feet=,id=209929,bonus_id=9544/6652/1472 # # Botas de Couro do Pioneiro  (319) # feet=,id=193386,bonus_id=8837/8838/4785/9405,crafted_stats=49/32,crafting_quality=5 # # Anel Arcano Instável (428) # finger1=,id=193633,bonus_id=9536/9636/6652/9599/1650/8766 # # Anel Tomado pela Geada (441) # finger1=,id=210378,bonus_id=9552/6652/9599/1472/8767 # # Selo do Loa Régio (457) # finger1=,id=159458,bonus_id=9561/9639/6652/9599/9144/3327/8767 # # Elo de Casca de Espinheiro (415) # finger1=,id=209914,bonus_id=9544/6652/9600/1472 # # Elo de Espinhos Flamejantes (460) # finger1=,id=207159,bonus_id=6652/9600/7979/9562/1491/8767 # # Elo da Estrela de Platina (428) # finger1=,id=193708,bonus_id=9536/9636/6652/9516/1650/8766 # # Talismã de My'das (450) # trinket1=,id=158319,bonus_id=9555/9639/6652/9144/3320/8767 # # Sangue Coagulado de Genessauro (457) # trinket1=,id=110004,bonus_id=9561/9639/6652/9144/9836/8767 # # Espada do Coureador da Ilha do Gumepresto (302) # main_hand=,id=199023,bonus_id=7969/40/1676,drop_level=70 # # Garra Rasga-almas (460) # main_hand=,id=160269,bonus_id=9562/9639/6652/9147/9455/8767 # # Machado de Mão Folhatroz (434) # main_hand=,id=210124,bonus_id=9538/9589/6652/1491/8766 # # Rashon, a Labareda Imortal (463) # main_hand=,id=207793,enchant_id=6638,bonus_id=6652/7982/9584/9559/1494/8767 # # Espeto Trovão da Aurora (66) # main_hand=,id=25308,bonus_id=6655/1707,drop_level=30 # # Adaga de Jaedenis do Gumepresto (66) # main_hand=,id=25102,bonus_id=6655/1677,drop_level=30 # # Adaga de Combustão do Clarão de Fogo (66) # main_hand=,id=25298,bonus_id=6655/1693,drop_level=30 # # Rocha da Égide (1) # off_hand=,id=198357 # # Rocha da Égide (1) # off_hand=,id=198357  ### Additional Character Info # # upgrade_currencies=c:2708:85/c:2709:18/c:2122:3/c:2707:104/c:2706:345/c:2245:1090/i:190453:4/i:198056:1 # # slot_high_watermarks=0:463:473/1:460:470/2:483:483/3:463:476/4:447:470/5:476:476/6:473:473/7:470:470/8:476:476/9:460:460/10:457:463/11:476:476/12:476:476/13:63:463/14:460:470/15:447:447/16:10:457  # Checksum: 1763a9a5 ### End simulateText ### desired_targets=1 ### Begin overrides ### # User-specified persistent global and player parameters will be set here.  ### End overrides ### ### Begin final options ### ### End final options ### ### END ### ```

**Comment by seanpeters86** [comment]
simc is ported over to 10.2.5 where they renamed certain spells. Should be fixed on a latest build or wait till tomorrow.

**Comment by Hinalover** [comment]
I would wait until tomorrow

**Comment by Hinalover** [comment]
This should be fixed now that the patch has released.
