### ISSUE TITLE
PTR Flag not working for spell_query

### ISSUE THREAD

**Issue by JeremyMonk** [simulationcraft/simc#8623]
### Describe the bug
Running `simc ptr=1 spell_query="x"` will output the same as ptr=0

### Expected behavior
spell_query should run in ptr mode when ptr is set to 1 

### To Reproduce
Run the spell_query command manually or run the spelldatadump_ptr.bat file in /SpellDataDump, the output will be Live data and the build info will also output live.

### Additional information
* SimulationCraft Version (required)
Latest

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
N/A

* **simc_gui.simc** file or contents
N/A

**Comment by vituscze** [comment]
It does run in PTR mode. What spell(s) did you use to test this?

**Comment by JeremyMonk** [comment]
> It does run in PTR mode. What spell(s) did you use to test this?

If you look at the top of https://raw.githubusercontent.com/simulationcraft/simc/dragonflight/SpellDataDump/allspells_ptr.txt you can see that it says "Live" 

The same thing occurs when I run the .bat or use spell_query with ANY spellID

**Comment by JeremyMonk** [comment]
and the data outputted is also live, it's not just the buildinfo being wonky. If you run a debugger you will also see that sim.dbc->ptr is false.

**Comment by JeremyMonk** [comment]
![image](https://github.com/simulationcraft/simc/assets/101205288/bb7bb650-b4d8-4329-8bf8-0b9980c95a68)
![image](https://github.com/simulationcraft/simc/assets/101205288/18c58e00-17b7-4060-aa34-3f7c939731bb)

**Comment by Azevara** [comment]
What version number are you expecting the command to use right now?

**Comment by vituscze** [comment]
I'm confused. You say that `dbc->ptr` is false in spell data output, but your debug screenshot shows it being false in the version string. So is this a report about the version string being wrong?

**Comment by JeremyMonk** [comment]
> I'm confused. You say that `dbc->ptr` is false in spell data output, but your debug screenshot shows it being false in the version string. So is this a report about the version string being wrong?

They will both be wrong because dbc->ptr is not being attributed correctly by the sim options. If the PTR flag was enabled the build info would be:

```
SimulationCraft 1020-01 for World of Warcraft 10.2.5.52646 PTR
```

Instead it prints

```
SimulationCraft 1020-01 for World of Warcraft 10.2.5.52902 Live
```

Yes, this example is only a version info string and not that important, but print_spell_query will also use the wrong DBC version and will not print the expected information. For example, you will see this change in all_spells_ptr.txt if you force dbc->ptr to true in main()

![image](https://github.com/simulationcraft/simc/assets/101205288/c59ddb30-abc1-46b5-a5d1-d1142638185b)

This only affects spell_query, it does not affect simming a player with the ptr flag, but any spell data dumped with ptr=1 does not match the current ptr value, and this will become relevant with the next major content PTR (such as 10.2.7)

**Comment by JeremyMonk** [comment]
Sorry, you are correct, I put a breakpoint at print_spell_query and the value of dbc was correctly attributed there. I don't know why it's not being printed correctly in version_info_str then. This may only be an issue with the build info.

![image](https://github.com/simulationcraft/simc/assets/101205288/4f2c7a59-5d6c-4202-afcc-26f83038768f)

**Comment by vituscze** [comment]
Build info is printed before command line arguments are parsed, if I'm reading sc_main.cpp correctly.

**Comment by JeremyMonk** [comment]
PR up for fix, sorry for the confusion.
