### ISSUE TITLE
Talent loadout 'pvp' is corrupt/incomplete

### ISSUE THREAD

**Issue by useless-stuff** [simulationcraft/simc#8627]
### Describe the bug
If I click on the simc icon addon this message will appear. ( It also happens if I type /simc )
"Talent loadout 'pvp' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly."

### Expected behaviour
Addon should work 

### To Reproduce
I'm trying to figure out how to reproduce it, but I tried to delete all WTF vars related to Simc; I attempted to rebuild a new talent tree from scratch. I also swapped PVP talents many times, but the problem persists. 
I don't even do PVP :D 
Any suggestions? 
Thank you so much 

### Additional information
* 10.2.5-01

**Comment by renanthera** [comment]
This sounds to me like you have a stale talent tree from a previous patch attached to your character somehow that either the simc addon is picking up, or an external addon is injecting.

At the bottom left of the talent tree GUI, there are some options to save preset talent trees. - Do you possibly have a preset named `pvp` there?
- Do you possibly have any addons that provide a similar functionality? (I believe there are several)

**Comment by useless-stuff** [comment]
hI @renanthera thank you for your reply.
Unfortunately, I don't have any preset called PVP. Funny fact, I don't do PVP at all :) Never had something like a preset configured for PVP.
I also tried to make a new preset from scratch, allocating skill points all over again, but nope, I had no luck.
I don't have any addon related to PVP or to load/unload skills presets.
Of course, I tried to reinstall Simc from scratch and also delete the WTF-related files, but nothing seemed to solve the problem.
Out of clues at this stage  :( 
The thing is, if I try to run simc for a different spec for the same character, it works.
So definitely something is messed up for that spec but I can't figure out how to reset simc

**Comment by vituscze** [comment]
Please run the following macro on the problematic spec and show us what it prints:
```lua
/run for _,id in pairs(C_ClassTalents.GetConfigIDsBySpecID(GetSpecializationInfo(GetSpecialization()))) do print(C_Traits.GetConfigInfo(id).name) end
```

**Comment by useless-stuff** [comment]
Thank you so much guys!! I ran the command which lists all the profiles and actually surprises surprise (don't know how to say this ) I had a PVP profile created some time ago for a random BG problem that was hidden by ElvUI -_-
Long story short, I deleted the profile and now everything works just fine. 
I'm so sorry that I bothered you with such a stupid thing.
Going to close this 
Once again thank you!! :D
