### ISSUE TITLE
[Monk] Definition of "recent_purifies" for Monk BrewMaster

### ISSUE THREAD

**Issue by BrewingCoder** [simulationcraft/simc#8684]
a search of this in the repo turns up a note that this is an internal buff.

It's not a buff I can locate, nor have I seen it occur.

Is this related to an amount of stagger cleared with a purifying brew?  If so what is the definition of recent?  in tracking stagger and stagger cleared would recent refer to some sliding amount over time? i.e. last 30 seconds, last 10 seconds, etc.

I would appreciate some clarification on what this means since it's strewn throughout my simulation results

**Comment by Hinalover** [comment]
Recent_purifies is related to the amount of stagger that was purified. It is mostly used for the talent Improved Invoke Niuzao the Black Ox. The talent increases the amount of damage that Niuzao's Stomp does based on how much stagger was recently purified. I am not sure if there is a duration of the buff off-hand. The code is saying there isn't any duration, but I would have to check with the other brewmaster theorycrafters on that. Maybe @renanthera would know more. If need be, we could make the spell hidden from the public similar to what we do with the Windwalker Mastery buff where it is hidden from public but still used internally.

**Comment by renanthera** [comment]
Recent Purifies is indeed what Hina mentioned, and it is used as an internal tracking aura for Improved Invoke Niuzao. This is handled vaguely similarly in game as far as anyone could ascertain, but is largely scripted so not very dataminable.

I would also prefer not to hide the buff in any way, as it's potentially a very useful tool for optimization in specific scenarios (if Improved Invoke Niuzao were to become clearly desirable) and being able to see its uptime behaviour is arguably useful for making APL purification behaviour more consistent w.r.t real-world gameplay.

I would be in favor of a more clear indication of what the effect is though!

All of the relevant behaviour can be found in the following locations:

https://github.com/simulationcraft/simc/blob/0403687117dd23e70accf6b96a65afe07dc2768b/engine/class_modules/monk/sc_monk.cpp#L4739
https://github.com/simulationcraft/simc/blob/0403687117dd23e70accf6b96a65afe07dc2768b/engine/class_modules/monk/sc_monk.cpp#L8546
https://github.com/simulationcraft/simc/blob/0403687117dd23e70accf6b96a65afe07dc2768b/engine/class_modules/monk/sc_monk.cpp#L6865-L6936
https://github.com/simulationcraft/simc/blob/0403687117dd23e70accf6b96a65afe07dc2768b/engine/class_modules/monk/sc_monk_pets.cpp#L1478-L1521

If you have further questions w.r.t this or anything else Brewmaster, do reach out either here, or more conveniently in the Peak of Serenity Discord, where I can be reached @_renanthera.
