### ISSUE TITLE
freshly installed simc wont open with command or by the minimap

### ISSUE THREAD

**Issue by tarapice** [simulationcraft/simc#8690]
### Describe the bug
SimC wont open when pressing the minimap button or using the command

### Expected behavior
by pressing minimap button or using the /simc command, i exspect to get a window up with a code so i can import it to raidbot

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
simulationcraft-v9.2.0-alpha-03

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by gastank** [comment]
You're using an extremely outdated version of the addon. Please use the latest version from curseforge https://www.curseforge.com/wow/addons/simulationcraft or directly download from github https://github.com/simulationcraft/simc-addon/releases

**Comment by tarapice** [comment]
im using the curseforge version tough

**Comment by nyterage** [comment]
![image](https://github.com/simulationcraft/simc/assets/6393808/0d2b16d6-9e30-48ff-a996-b2fe35f5e7d9)
the version you reported using is over 2 years old.

**Comment by tarapice** [comment]
![image](https://github.com/simulationcraft/simc/assets/16495081/26ea034e-87b1-4cce-9ee5-f72633647693)

**Comment by nyterage** [comment]
click versions, install the latest version.

**Comment by tarapice** [comment]
![image](https://github.com/simulationcraft/simc/assets/16495081/6cfdce3f-1cfb-4bbf-9ce3-8807af68f756)

**Comment by nyterage** [comment]
if youre trying to install for a classic version of the game, we do not in any way support classic, curseforge must have labeled those as classic versions incorrectly.

**Comment by tarapice** [comment]
no im trying to install on retail, all my other addons work but this one dose not. dont know if its a bug with curseforge or something. ty for the help

**Comment by nyterage** [comment]
seems to be a curseforge bug, or some incorrect configuration, its trying to install for game version 1.14.2 (classic)

**Comment by gastank** [comment]
Try going to curseforge website and click install from there, instead of within the app.

**Comment by seriallos** [comment]
Even though this looks like a funky CurseForge problem, I went ahead and archived those two alpha releases. Hopefully that will prevent them from showing up in that weird way.
