### ISSUE TITLE
Unable to download latest nightly build - Virus detected

### ISSUE THREAD

**Issue by KNP54** [simulationcraft/simc#8696]
### Describe the bug
Probably a false positive. But windows defender reports a virus.

### Expected behavior
I expect the download to complete.

### To Reproduce
Tried with Chrome: Chrome report a virus detected. Tried with edge: Windows Defender deletes the file.

### Additional information
1025.01.f346913-win64

![image](https://github.com/simulationcraft/simc/assets/28404059/0c9430c9-bd62-4f15-b899-3974a74850f9)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by renanthera** [comment]
This has also been reported in the simc discord, and appears to be a false positive. Tests by several maintainers against both Windows Defender and Virustotal both came back clean.

The best you can do is report it to Microsoft as a false positive and get Windows Defender to add this version of simc as an exception, or build it yourself.
