### ISSUE TITLE
Monk WindWalker profile contains double commas

### ISSUE THREAD

**Issue by BrewingCoder** [simulationcraft/simc#8701]
### Describe the bug
double commas appear in WW profile

### Expected behavior
If no parameter is displayed don't add the comma

### To Reproduce
run sim on WW Monk; look at profile text, specifically tiger_palm in serenity_aoe and serenity_aoelist
```
actions.serenity_aoe+=/spinning_crane_kick,target_if=max:target.time_to_die,if=target.time_to_die>duration&combo_strike&spinning_crane_kick.max
actions.serenity_aoe+=/tiger_palm,,target_if=min:debuff.mark_of_the_crane.remains,if=!debuff.skyreach_exhaustion.up*20&combo_strike&active_enemies=5
actions.serenity_aoe+=/rushing_jade_wind,if=!buff.rushing_jade_wind.up
```

### Additional information
* SimulationCraft Version 1026-01

**Comment by renanthera** [comment]
While it may be unintended, I do not believe it changes the intended behaviour.
