### ISSUE TITLE
Crashing in command line and GUI during scaling

### ISSUE THREAD

**Issue by ghostedstep** [simulationcraft/simc#8718]
### Describe the bug
The command line and GUI are both failing and stopping when scaling

### Expected behavior
When I run simc from command line or GUI it will crash. The GUI will just close or the scaling will just cancel in the command line.

### To Reproduce
No clue how to reproduce I'm assuming its a PC conflict error but I have a very basic gaming setup. Its a high end setup but it only has games downloaded.

### Additional information
1026-01 version

* **simc_gui.simc** file or contents
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead/ptr2head
target_error=0
iterations=10000
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=0
override.arcane_intellect=0
override.power_word_fortitude=0
override.battle_shout=0
override.mark_of_the_wild=0
override.windfury_totem=0
override.bleeding=0
override.mortal_wounds=0
override.chaos_brand=0
override.mystic_touch=0
threads=32
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
center_scale_delta=1
statistics_level=1
### Begin simulateText ###
# Vashtv - Balance - 2024-03-27 09:29 - US/Area 52
# SimC Addon 10.2.6-01
# WoW 10.2.6.53913, TOC 100206
# Requires SimulationCraft 1000-01 or newer

druid="Vashtv"
level=70
race=tauren
region=us
server=area_52
role=spell
professions=leatherworking=67/alchemy=54
spec=balance

talents=BYGAORarfDaLt4uMx8TYOtl8GAAAAAAAAAAAAAAAAAAAgCQkIiIJJAJhkkUgGSkkUSCJJEaSLSkENAKAQA

# Saved Loadout: M+
# talents=BYGAORarfDaLt4uMx8TYOtl8GAAAAAAAAAAAAAAAAAAAgCQkIiIJJAJhkkUgGSkkUSCJJEaSLSkENAKAQA

# Benevolent Embersage's Casque (483)
head=,id=207254,bonus_id=6652/9599/7980/9513/9581/1514/8767
# Chain of the Green Flight (483)
neck=,id=137311,gem_id=192958/192958/192958,bonus_id=9639/6652/9144/9581/9876/8767/9477/8782
# Benevolent Embersage's Wisdom (483)
shoulder=,id=207252,bonus_id=6652/9639/9511/9581/1514/8767
# Periwinkle Cloak (483)
back=,id=133180,enchant_id=6604,bonus_id=9639/6652/9506/9144/9581/9889/8767
# Spymaster's Wrap (483)
chest=,id=211404,enchant_id=6625,bonus_id=9639/43/9506/9144/9581/3162/8767
# Stylish Black Shirt (1)
shirt=,id=3427
# Renowned Guild Tabard (1)
tabard=,id=69210
# Thermal Bindings (483)
wrist=,id=134461,enchant_id=6580,gem_id=192919,bonus_id=9639/6652/9516/9506/9144/9581/9876/8767
# Benevolent Embersage's Talons (483)
hands=,id=207255,bonus_id=41/9639/9514/9581/1514/8767
# Eternal Sentinel's Cord (483)
waist=,id=207135,enchant_id=6904,gem_id=192958,bonus_id=6652/9516/9508/7980/9581/1514/8767
# Benevolent Embersage's Leggings (489)
legs=,id=207253,enchant_id=6496,bonus_id=6652/9639/9512/9576/1520/8767
# Toxic Thorn Footwraps  (486)
feet=,id=193452,enchant_id=6613,bonus_id=8836/8840/8902/8960/9405/9500/9498,crafting_quality=5
# Anthia's Ring (483)
finger1=,id=133189,enchant_id=6550,gem_id=192919,bonus_id=9639/6652/9516/9144/9581/9889/8767
# Arch-Druid's Tainted Seal (483)
finger2=,id=134487,enchant_id=6550,gem_id=192919,bonus_id=9639/6652/9516/9144/9581/9876/8767
# Caged Horror (483)
trinket1=,id=136716,bonus_id=9639/6652/9144/9581/9876/8767
# Coagulated Genesaur Blood (483)
trinket2=,id=110004,bonus_id=9639/6652/9144/9581/9882/8767
# The Infinite Hand (476)
main_hand=,id=208391,enchant_id=6655,bonus_id=9639/6652/9147/9529/9571/1511/8767

### Gear from Bags
#
# Blackwater Helm (483)
# head=,id=109979,bonus_id=9639/6652/9599/9506/9144/9581/9882/8767
#
# Hood of Perpetual Conflict (467)
# head=,id=207936,bonus_id=9568/9639/6652/9599/9506/9144/1554/8767
#
# Soulstarve Hood (470)
# head=,id=134440,bonus_id=9569/9639/6652/9600/9506/9144/9843/8767
#
# Old One Eye's Cowl (470)
# head=,id=133358,bonus_id=9569/9639/6652/9599/9506/9144/9876/8767
#
# Eye of the Rising Flame (476)
# neck=,id=207163,bonus_id=6652/8783/10245/7980/9571/1507/8767
#
# Glittering Gelid Goldchain (441)
# neck=,id=210380,bonus_id=9552/6652/8783/10245/1472/8767
#
# Ironshell Pendant (483)
# neck=,id=133359,gem_id=192919/192919/192919,bonus_id=9639/6652/9144/9581/9889/8767/9477/8782
#
# Raven Filigree Pendant (489)
# neck=,id=134499,gem_id=192938/192938/192938,bonus_id=9639/6652/9144/9477/8782/9576/9882/8767
#
# Titanic Shouldersparks (467)
# shoulder=,id=207873,bonus_id=9568/9639/6652/9506/9144/1557/8767
#
# Caridean Epaulets (470)
# shoulder=,id=133186,bonus_id=9569/9639/6652/9506/9144/9876/8767
#
# Raal's Bib (483)
# back=,id=159294,enchant_id=6598,bonus_id=9639/6652/9506/9144/9581/9847/8767
#
# Benevolent Embersage's Featherdrape (483)
# back=,id=207249,enchant_id=6598,bonus_id=41/9639/9581/1514
#
# Drape of the Loyal Vassal (467)
# back=,id=158375,bonus_id=9568/9639/6652/9506/9144/9464/8767
#
# Crystalbinder Chestguard (470)
# chest=,id=109886,bonus_id=9569/9639/6652/9506/9144/9849/8767
#
# Benevolent Embersage's Robe (483)
# chest=,id=207257,enchant_id=6625,bonus_id=6652/7980/9515/9581/1514/8767
#
# Verdant Sanctuary Bands (470)
# wrist=,id=210206,bonus_id=6652/9599/9508/7980/9569/1501/8767
#
# Venerated Raptorhide Bindings (483)
# wrist=,id=160214,enchant_id=6580,bonus_id=9639/6652/9599/9506/9144/9581/9847/8767
#
# Chronomancer's Stasis Shackles (483)
# wrist=,id=207939,enchant_id=6580,bonus_id=9639/6652/9600/9506/9144/9581/1576/8767
#
# Bracers of Dreadful Maladies (470)
# wrist=,id=159340,bonus_id=9569/9639/6652/9599/9506/9144/9834/8767
#
# Flamewaker's Grips (470)
# hands=,id=207130,bonus_id=6652/9508/7980/9569/1501/8767
#
# Gauntlets of Burning Focus (483)
# hands=,id=109848,bonus_id=9639/6652/9506/9144/9581/9882/8767
#
# Fading Chronogrips (470)
# hands=,id=207903,bonus_id=9569/9639/6652/9506/9144/1563/8767
#
# Gauntlets of Burning Focus (489)
# hands=,id=109848,bonus_id=9639/6652/9506/9144/9576/9888/8767
#
# Belt of Gleaming Determination (470)
# waist=,id=158306,bonus_id=9569/9639/6652/9516/9506/9144/9834/8767
#
# Bloody Dragonhide Belt (467)
# waist=,id=207131,bonus_id=6652/9600/9508/7980/9568/1498/8767
#
# Belt of the Eternal Struggle (470)
# waist=,id=207874,bonus_id=9569/9639/6652/9600/9506/9144/1563/8767
#
# Belt of Gleaming Determination (483)
# waist=,id=158306,enchant_id=6904,gem_id=192919,bonus_id=9639/6652/9516/9506/9144/9581/9847/8767
#
# Hound-Jowl Waistband (483)
# waist=,id=159341,enchant_id=6904,bonus_id=9639/6652/9599/9506/9144/9581/9847/8767
#
# Galakrond's Voracious Hide (483)
# legs=,id=207820,enchant_id=6496,bonus_id=9639/6652/9506/9144/9581/1573/8767
#
# Frenzied Incarnate Legwraps (476)
# legs=,id=207132,enchant_id=6830,bonus_id=41/9505/7979/9567/1507/8767
#
# Legguards of Endless Horrors (483)
# legs=,id=134451,enchant_id=6496,bonus_id=9639/6652/9506/9144/9581/9876/8767
#
# Frenzied Incarnate Legwraps (483)
# legs=,id=207132,enchant_id=6830,bonus_id=43/9508/7980/9581/1514/8767
#
# Blight Toadskin Leggings (467)
# legs=,id=159345,bonus_id=9568/9639/43/9506/9144/9464/8767
#
# Shambling Berserker's Leggings (467)
# legs=,id=155869,bonus_id=9568/9639/6652/9506/9144/9464/8767
#
# Moss-Covered Wingtip Shoes (470)
# feet=,id=159347,bonus_id=9569/9639/6652/9506/9144/9834/8767
#
# Vigorous Sandstompers (470)
# feet=,id=207838,bonus_id=9569/9639/6652/9506/9144/1563/8767
#
# Grove Darkener's Treads (470)
# feet=,id=134429,bonus_id=9569/9639/6652/9506/9144/9843/8767
#
# Thornwoven Band (483)
# finger1=,id=162548,enchant_id=6568,bonus_id=9639/6652/9600/9144/9581/9847/8767
#
# Lord Waycrest's Signet (476)
# finger1=,id=158362,enchant_id=6568,bonus_id=9639/6652/9599/9144/9571/9840/8767
#
# Seal of the Regal Loa (483)
# finger1=,id=159458,enchant_id=6568,bonus_id=9639/6652/9600/9144/9581/9847/8767
#
# Band of Callous Dominance (483)
# finger1=,id=134528,enchant_id=6550,bonus_id=9639/6652/9600/9144/9581/9876/8767
#
# Ring of Contempt (483)
# finger1=,id=134490,bonus_id=9639/6652/9600/9144/9581/9876/8767
#
# Ember of Nullification (483)
# trinket1=,id=136978,bonus_id=9639/6652/9144/9581/9876/8767
#
# Prophetic Stonescales (483)
# trinket1=,id=207528,bonus_id=9639/6652/9144/9581/1534/8767
#
# Belor'relos, the Suncaller (476)
# trinket1=,id=207172,bonus_id=6652/7980/9571/1507/8767
#
# Nymue's Unraveling Spindle (460)
# trinket1=,id=208615,bonus_id=6652/7979/9562/1491/8767
#
# Xeri'tac's Unhatched Egg Sac (483)
# trinket1=,id=110019,bonus_id=9639/6652/9144/9581/9882/8767
#
# Writhing Heart of Darkness (470)
# trinket1=,id=137315,bonus_id=9569/9639/6652/9144/9843/8767
#
# Mirror of Fractured Tomorrows (470)
# trinket1=,id=207581,bonus_id=9569/9639/6652/9144/1521/8767
#
# Gift of Ursine Vengeance (483)
# trinket1=,id=207173,bonus_id=6652/7980/9581/1514/8767
#
# Borrowed Time (483)
# main_hand=,id=207987,enchant_id=6655,bonus_id=9526/9639/6652/9147/9581/1605/8767
#
# Blightreaper (483)
# main_hand=,id=159662,enchant_id=6646,bonus_id=9639/6652/9147/9581/9847/8767
#
# Morchie's Distorted Spellblade (470)
# main_hand=,id=207997,bonus_id=9569/9639/6652/9147/1592/8767
#
# Hoof of Yalnu (470)
# main_hand=,id=119181,bonus_id=9569/9639/6652/9147/9849/8767
#
# Ancestor's Necromantic Focus (470)
# off_hand=,id=207983,bonus_id=9569/9639/6652/9144/1592/8767
#
# Solena's Watchful Collection (470)
# off_hand=,id=159669,bonus_id=9569/9639/6652/9144/9834/8767

### Additional Character Info
#
# upgrade_currencies=c:2708:319/c:2709:801/c:2122:2/c:2707:411/c:1792:514/c:2706:775/c:2245:320/i:206959:7/i:206960:1/i:198048:4
#
# slot_high_watermarks=0:483:483/1:489:489/2:483:483/3:483:483/4:483:483/5:489:489/6:486:486/7:483:483/8:489:489/9:483:483/10:483:483/11:483:483/12:483:483/13:470:470/14:333:424/15:0:424/16:470:470

# Checksum: 18e9eff5
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###

**Comment by renanthera** [comment]
Saeldur and I were both unable to reproduce. I tested a previous input in gui and cli on Linux, with Saeldur testing cli on windows

Apparently reducing thread count improved stability, so I expect it's a system issue.

**Comment by seanpeters86** [comment]
closing due to no response
