### ISSUE TITLE
Typos in wiki

### ISSUE THREAD

**Issue by hianick** [simulationcraft/simc#8737]
### Describe the bug
Typos in https://github.com/simulationcraft/simc/wiki/Characters

### Expected behavior
padaren_horde to pandaren_horde
maghar_\orc to maghar_orc
zandalari_\troll to zandalari_troll

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Bloodmallet** [comment]
Thank you for the report. It's fixed now.
