### ISSUE TITLE
Neltharion call to dominance possibly *adding* stacks instead of replacing them

### ISSUE THREAD

**Issue by nano1895** [simulationcraft/simc#8873]
### Describe the bug
When simming with Neltharion's Call to Dominance the primary stat stacks are not getting replaced instead they are getting added if it is procced while having an existing stat buff. 

### Expected behavior
1. Gain stacks of Domineering arrogance, say you get 2 stacks
2. Proc it with an ability (Feral Spirits for example)
3. Gain 2 "stacks" of Call to Dominance
4. While you have 2 stacks of Call to Dominance gain x amount of stacks of Domineering Arrogance again
5. Active the trinket again while existing 2 stacks of Call to Dominance is active
6. **The new buff should refresh ats full duration with the X stacks of Call to Dominance**
7. **Instead it seems the new buff is 2 + X, adding instead of replacing**

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

Run a sim with the trinket used for enhancement shaman since they have the best chance at reactivating the buff with an existing buff stack since their Feral Spirits are on very short CD using quick sim. Observe that instead of the stacks getting replaced in the sample iteration they are being added together. 

### Additional information
* SimulationCraft Version (required)

I am using the latest raidbots simc version. Here is a link to the quick sim I used and a screencap of the behavior. 
https://www.raidbots.com/simbot/report/n4CBZ2ECiFc8cobZoq3av3
![image](https://github.com/simulationcraft/simc/assets/10660213/7b2e0d0a-57aa-42b6-a720-feaaba936a7d)

I believe the bug is sourced from how it refreshes the stacks, you can look at the implementation of the trinket here

https://github.com/simulationcraft/simc/blob/dragonflight/engine/player/unique_gear_dragonflight.cpp#L4600

It triggers the buff with the existing stacks of "Domineering Arrogance". However when I follow the execution path of what "trigger" it could be incrementing them instead of replacing them. 

[Trigger calls "execute"](https://github.com/simulationcraft/simc/blob/dragonflight/engine/buff/buff.cpp#L2025)

[Which calls "increment"](https://github.com/simulationcraft/simc/blob/dragonflight/engine/buff/buff.cpp#L2062)

[Which calls "refresh"](https://github.com/simulationcraft/simc/blob/dragonflight/engine/buff/buff.cpp#L2094)

[Which calls bump](https://github.com/simulationcraft/simc/blob/dragonflight/engine/buff/buff.cpp#L2329)

[Which seems to add the stacks together](https://github.com/simulationcraft/simc/blob/dragonflight/engine/buff/buff.cpp#L2431)

Edit - I added a `stat_buff -> expire()` line right before triggering the buff again and that returns results that look alot more accurate. FWIW.

**Comment by seanpeters86** [comment]
Closing as dragonflight is ending
