### ISSUE TITLE
GUI disappears on open, only on 10.2.7 version.

### ISSUE THREAD

**Issue by gerinamoo** [simulationcraft/simc#8931]
### Describe the bug
Upon running simulation craft, a blank web 1027 web engine window appears as if simc is going to load, then the window quickly disappears.  No task is left running in task manager.  

I can revert back to 10.2.6 and simc works correctly.

Steps taken so far -  1.  Clean install of graphics driver w reboot.  2. Complete wipe of simc directory and reinstall.  3.  Tried compatibility fix for Windows 8 (always run program as admin for write access).  4.  Disabled secondary monitor.

[DxDiag.txt](https://github.com/user-attachments/files/15891147/DxDiag.txt)

**Comment by Shaan67** [comment]
same here

**Comment by gerinamoo** [comment]
Also tried disabling AV and any optional startup processes.

**Comment by ef4203** [comment]
Same issue for me, I could reproduce it with version `simc-1027.01.87c5dd2-win64`.

**Comment by Wolke23** [comment]
Same problem. Nothing helps. 10.2.7 doesn't work at Windows 11.

**Comment by ef4203** [comment]
Different to @Wolke23 , I had the issue with Windows 10

**Comment by Kastor91** [comment]
Hello ! If you're still having this issue you could try the fix I posted here : https://github.com/simulationcraft/simc/issues/9311#issuecomment-2308204334 
It looks like the same issue so let's hope it works for you too :)

**Comment by imperia777** [comment]
> Hello ! If you're still having this issue you could try the fix I posted here : [#9311 (comment)](https://github.com/simulationcraft/simc/issues/9311#issuecomment-2308204334) It looks like the same issue so let's hope it works for you too :)

that worked, but i had to delete configuration files from %appdata% folder

**Comment by Wolke23** [comment]
Yes, it works!
I deleted ALL MS Visual C++ and installed the newest version again. Thanks.
