### ISSUE TITLE
Blue Dragon Soles

### ISSUE THREAD

**Issue by Ragowit** [simulationcraft/simc#8938]
### Describe the bug
Running a sim (with movement) with the gear Blue Dragon Soles doesn't seem to apply any Charged Soles buffs. Making the item render almost useless for the sim.

### Expected behavior
I expect to find Charged Soles buffs in the report when running a sim with Blue Dragon Soles and movement.

### To Reproduce
Run a sim with movement and the gear Blue Dragon Soles.

### Additional information
* https://www.raidbots.com/simbot/report/etoBjU4nwaDNKxYUAawzT1/simc

**Comment by Pewtro** [comment]
Movement sims are at best, partially supported. 
As for the item, it has no implementation and will probably not see any implementation as primary focus is on the war within
