### ISSUE TITLE
Balance Druid profile in DF4 list missing

### ISSUE THREAD

**Issue by Xeano5** [simulationcraft/simc#8939]
### Is your feature request related to a problem? Please describe.
The profile for Balance Druid in the DF4 list of profiles is missing.

### Describe the solution you'd like
Add a profile for Balance druid in the DF4 list of profiles.

### Describe alternatives you've considered
Not adding one.

### Additional context
Just found this when using the "Blood mallet" website since it was the only DPS spec with nothing working.
<img width="484" alt="Screenshot_1" src="https://github.com/simulationcraft/simc/assets/109247360/b3237ddf-a970-4a29-814c-e15907792236">

**Comment by Dsune0** [comment]
Fixed in https://github.com/simulationcraft/simc/pull/8940
