### ISSUE TITLE
Holy Priest Simulation bug  looking for a talent i don't have 

### ISSUE THREAD

**Issue by westtell4** [simulationcraft/simc#8941]
# SimulationCraft encountered an error! # SimulationCraft 1027-01 for World of Warcraft 10.2.7.55165 Live # hotfix 2024-06-17/55165, git build dragonflight 44ac75b * Category: Simulation runtime error * Error: Initializing: Actor 'Capziellinas': Action 'holy_fire': Cannot parse expression from '(talent.empyreal_blaze|talent.harmonious_apparatus|!ticking|refreshable)&!(buff.empyreal_blaze.up&(cooldown.divine_word.up|buff.divine_word.up)&cooldown.holy_word_chastise.up)': Cannot find talent 'harmonious_apparatus'.  ## All options used for simulation: ``` ini ### SimulationCraft 1027-01 for World of Warcraft 10.2.7.55165 Live (wow build 55165, git build dragonflight 44ac75b)  ### ### Using QT 6.4.0 with WebEngine ###  ### Begin GUI options ### ptr=0 item_db_source=local/bcpapi/wowhead/ptrhead/ptr2head target_error=0 iterations=0 default_world_lag=0.1 max_time=300 vary_combat_length=0.2 tmi_window_global=6 target_level+=3 target_race=Humanoid optimal_raid=0 override.bloodlust=1 override.arcane_intellect=1 override.power_word_fortitude=1 override.battle_shout=1 override.mark_of_the_wild=1 override.windfury_totem=1 override.bleeding=1 override.mortal_wounds=1 override.chaos_brand=1 override.mystic_touch=1 threads=12 process_priority=Low calculate_scale_factors=1 scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed statistics_level=1 ### End GUI options ### ### Begin simulateText ### # Post your Simc Addon Export text here. # Capziellinas - Holy - 2024-06-22 09:30 - US/Moon Guard # SimC Addon 10.2.7-01 # WoW 10.2.7.55165, TOC 100207 # Requires SimulationCraft 1000-01 or newer  priest="Capziellinas" level=70 race=void_elf region=us server=moon_guard role=attack professions=herbalism=35/enchanting=15 spec=holy  talents=BEQA/KVNHBYFUG61hTBXiMbcYSEAAAAAAAcgmIlEkERgEJElkkSAAAAA0SJUSCkCpkIJioQjkEUAA  # Saved Loadout: Mythic+ build # talents=BEQA/KVNHBYFUG61hTBXiMbcYSEAAAAAAAcgmIlEkERgEJElkkSAAAAA0SJUSCkCpkIJioQjkEUAA  # Headwrap of the Abandoned (480) head=,id=193641,enchant_id=7052,bonus_id=9636/6652/10531/10864/10309/3159/8767 # Ukhel Ancestry Beads (480) neck=,id=193676,bonus_id=9636/6652/8784/10244/10309/3159/8767 # Molten Magma Mantle (489) shoulder=,id=193788,bonus_id=10344/9636/6652/10870/9144/3168/8767 # Cloak of Lost Devotion (480) back=,id=193629,bonus_id=9636/6652/10864/10309/3159/8767 # Command of the Furnace Seraph (489) chest=,id=217205,bonus_id=6652/10344/9636/10865/1481 # Ren'dorei Tabard (1) tabard=,id=157758 # Cuffs of the Furnace Seraph (489) wrist=,id=202538,bonus_id=6652/7982/10533/10884/8096/10344/1546/8767 # Gloves of the Crystal Gardener (489) hands=,id=127590,bonus_id=7756/10312/9921/8767 # Evelyn's Belt (483) waist=,id=133278,bonus_id=7756/10533/10310/9889/8767 # Breeches of the Furnace Seraph (489) legs=,id=217203,bonus_id=6652/10344/9636/10868/1481 # Sabatons of the Furnace Seraph (496) feet=,id=202544,bonus_id=6652/10314/7979/10884/1553 # Signet of the Last Elder (493) finger1=,id=207162,bonus_id=42/10533/7979/10313/10884/1524/8767 # Unstable Arcane Loop (476) finger2=,id=193633,bonus_id=7974/40/10531/10328/3155/8766 # Rainsong (476) trinket1=,id=133252,bonus_id=7756/10308/9882/8766 # Blossom of Amirdrassil (509) trinket2=,id=207171,bonus_id=6652/7979/10330/10884/1540/8767 # Dreambinder, Loom of the Great Cycle (493) main_hand=,id=208616,bonus_id=10407/6652/9418/1524/8767  ### Gear from Bags # # Draconic Combatant's Wildercloth Shoulderpads  (451) # shoulder=,id=211555,bonus_id=10250/8840/5247/10251/9405,crafted_stats=32,crafting_quality=5 # # Command of the Furnace Seraph (486) # chest=,id=217205,bonus_id=6652/7982/10343/10865/10884/1478/8767 # # Bracers of the Black Dream (450) # wrist=,id=133536,bonus_id=10845,drop_level=70 # # Belt of the Blood Nova (115) # waist=,id=50671,bonus_id=9051,drop_level=30 # # Sabatons of the Furnace Seraph (483) # feet=,id=202544,bonus_id=6652/7982/10342/10884/8096/1540 # # Lost Scholar's Belted Treads (496) # feet=,id=207122,bonus_id=6652/10872/7979/10314/10884/1527/8767 # # Bottled Wishes (450) # trinket1=,id=133538,bonus_id=10845,drop_level=70 # # Reflection of the Light (450) # trinket1=,id=133539,bonus_id=10845,drop_level=70 # # Vakash, the Shadowed Inferno (489) # main_hand=,id=207788,bonus_id=6652/7982/10344/10884/1520/8767 # # Constructor's Worklight (467) # main_hand=,id=188454,bonus_id=10305/7756/9876/8766 # # Final Grade (493) # main_hand=,id=193707,bonus_id=10313/9635/6652/3172/8767 # # Rod of Perfect Order (336) # off_hand=,id=193745,bonus_id=7978/7975/6652,drop_level=69  ### Additional Character Info # # upgrade_currencies=c:2806:6/c:2807:100/c:2245:163/c:1792:4 # # slot_high_watermarks=0:480:496/1:480:489/2:489:496/3:489:493/4:483:493/5:489:502/6:496:496/7:489:506/8:489:506/9:476:489/10:476:493/11:480:502/12:493:496/13:489:489/14:115:450/15:0:441/16:336:346  # Checksum: 9a67b892 ### End simulateText ### desired_targets=1 ### Begin overrides ### # User-specified persistent global and player parameters will be set here.  ### End overrides ### ### Begin final options ### ### End final options ### ### END ### ```

**Comment by gastank** [comment]
Holy priest has not been updated since 10.1, so will be missing any changes since then including talent changes.
