### ISSUE TITLE
Can't see Balance Druid in latest SIMC build

### ISSUE THREAD

**Issue by cshellyb** [simulationcraft/simc#9002]
I am unable to see Balance Druid in the latest  Dragonflight Awakened Update 
([Dragonflight Awakened ~525 ilevel Patchwerk-style](https://simulationcraft.org/reports/DF4_Raid.html)
hotfix 2024-06-26/55261, git build 7c6490f2a3

If you click on the Amirdrassil regular raid, it is listed as intended.
![image](https://github.com/simulationcraft/simc/assets/175166578/b6c47255-ad1d-446c-871e-f635402039ba)

**Comment by nyterage** [comment]
Fixed in commit [86233a](https://github.com/simulationcraft/simc/commit/e455ac57441bd332c8b5467c5df097774f86233a), will be there in the next data regeneration.
