### ISSUE TITLE
Sim result has error related to "Invalid serialization version"

### ISSUE THREAD

**Issue by Bobbyteo** [simulationcraft/simc#9100]
### Describe the bug
Sim completed but with error message of
"Player <playername> has invalid talent tree hash CkQAZFAP+MsTYonZag5QQDYLkDzMzMzMjY2MMmNzMDz2AAAAzMjZWMzMWmZmZhxMDAYGAAAAAAzAAAAAAAAAGzGA: Invalid serialization version""

### Expected behavior
no such error message

### To Reproduce
Target: Fluffy_Pillow humanoid tank_dummy unknown 73   DTPS=37613.29891553313 DTPS-Error=23.455742123357222/0.06% DTPS-Range=5183.438049246477/13.78%   DPR=0 RPS-Out=35489.6888766498 RPS-In=0 Resource=health Waiting=0 ApM=0   Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|10118349  mana=0|0   Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)   Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)   Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%   Defense Stats: armor=5043|5043(5043) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)   Priorities (actions.precombat):     snapshot_stats   Priorities (actions.default):    Actions:    Constant Buffs:     arcane_intellect/battle_shout/bleeding/chaos_brand/mortal_wounds/mystic_touch/power_word_fortitude   Scale Factors:     Weights :     Wowhead :    DPS Plot Data ( min=-1500 max=1500 points=21 )   Waiting:  0.00%   Baseline Performance:   Networking    = enabled   RNG Engine    = xoshiro256+   Iterations    = 14310 (3911, 3518, 3441, 3440)   TotalEvents   = 74245443   MaxEventQueue = 46   TargetHealth  = 10118349   SimSeconds    = 4289508.044   CpuSeconds    = 85.9375   WallSeconds   = 22.428459   InitSeconds   = 0.0096347   MergeSeconds  = 0.00525   AnalyzeSeconds= 0.0260531   SpeedUp       = 49928   EndTime       = 2024-07-25 13:58:41+0800 (1721887121)   

### Additional information
[SimulationCraft 1027-01](https://www.simulationcraft.org/)
for World of Warcraft 10.2.7.55261 Live (hotfix 2024-06-26/55261, git build [e455ac5](https://github.com/simulationcraft/simc/commit/e455ac5))

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
* attached below
* 
### Begin GUI options ###
ptr=0
item_db_source=ptr2head/ptrhead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HeavyMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.mark_of_the_wild=0
override.windfury_totem=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Normal
calculate_scale_factors=1
scale_only=str,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps
dps_plot_stat=int,sp,ap,crit,haste,mastery,vers,wdps,wohdps
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
reforge_plot_stat=int
reforge_plot_amount=500
reforge_plot_step=50
statistics_level=1
report_pets_separately=1
### Begin simulateText ###
# Talent tree: ST Infirmity, SB-PS, XGambit-FM, Oblibion
# Set7 527 C34 H39 M129 V15 Head:GotSS522(+C70V33)>528(M70H33) Neck:BDL522(2x70M33V+70V33H) Shoulder:AotSS528 Back:VotSS535(GA3*) Chest:CRotSS528(WS3*) Weap:DLotGC528(SD3*) Wrist:VWW525(Avoid200+SfAP+70M33V) Hands:AWG528 Waist:VWG525(BSL+70H33V) Legs:LotSS528(Int177Stam131) Feet:VWS525(PB3*) Ring:SoDC528(H82+M70H33)+SoFD532(70H33V+M82) Trink:WII528+IR528
# 
# Hosaylock - Affliction - 2024-07-25 13:41 - US/Frostmourne
# SimC Addon 11.0.0-01
# WoW 11.0.0.55824, TOC 110000
# Requires SimulationCraft 1000-01 or newer

warlock="Hosaylock"
level=70
race=void_elf
region=us
server=frostmourne
role=spell
professions=alchemy=100/herbalism=100
spec=affliction

talents=CkQAZFAP+MsTYonZag5QQDYLkDzMzMzMjY2MMmNzMDz2AAAAzMjZWMzMWmZmZhxMDAYGAAAAAAzAAAAAAAAAGzGA

# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDmZGzMDMbGGz2MzMMLDAAAAADPwiZmZBAAYGAAAAAAAAAAAAAAAAA
# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwMz2MzMMLDAAAMmZgZmLwiZmZxMXwYAAzAAAAAAAAAAAAAAAAA
# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwMz2MzMMLDAAAMMzgZmLwiZmZxMXwYAAzAAAAAAAAAAAAAAAAA
# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwMz2MzMMLDAAAMmZgZmLwiZmZxMXwYAAzAAAAAAAAAAAAAAAAA
# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwMz2MzMMLDAAAMMDMzcBWMzMLm5CmZAAzAAAAAAAAAAAAAAAAA
# Saved Loadout: A4 TC DB-Dg-DH
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwY2ugZmhZZAAAgxwgZmLwiZmZxMXwMDAYGAAAAAAAAAAAAAAAAA
# Saved Loadout: unused
# talents=CkQAZFAP+MsTYonZag5QQDYLkDXwMzYmZgZzwY2ugZmhZZAAAghxgZmLwiZmZxMXwMDAYGAAAAAAAAAAAAAAAAA
# Saved Loadout: PP Raid-ST SEmb SBolt
# talents=CkQAZFAP+MsTYonZag5QQDYLkDzMzMzMDMbGGzmZmhZbAAAgZmxMLmZGLzMzswYmBAMDAAAAAgZAAAAAAAAAjZD
# Saved Loadout: PP Raid-ST/Cleave
# talents=CkQAZFAP+MsTYonZag5QQDYLkDmZmZmZgZzwY2MzMMbDAAAYmxMLzMDLzMzswMzMAgZAAAAAAMDAAAAAAAAYMbA
# Saved Loadout: PP M+
# talents=CkQAZFAP+MsTYonZag5QQDYLkDmZmZmZgZzwY2MzMMbDAAAYmxMLzMDbzMzsYGzMAgZAAAAAAMDAAAAAAAAYMLA

# Grimhorns of the Sinister Savant (528)
head=,id=217212,gem_id=192961,bonus_id=6652/10338/10531/9639/10867/1520
# Bromach's Disentombed Locket (522)
neck=,id=193809,gem_id=192964/192964/192935,bonus_id=9639/6652/9144/9477/8782/10334/3201/8767
# Amice of the Sinister Savant (528)
shoulder=,id=217214,bonus_id=6652/9639/10869/10338/1520/8767
# Voice of the Silent Star (535)
back=,id=204465,enchant_id=6592,bonus_id=10503/1576/8767
# Cursed Robes of the Sinister Savant (528)
chest=,id=217215,enchant_id=6625,bonus_id=6652/9639/10865/10338/1520/8767
# Red Linen Shirt (1)
shirt=,id=2575
# Dream Wardens Tabard (1)
tabard=,id=210501
# Vibrant Wildercloth Wristwraps  (525)
wrist=,id=193510,enchant_id=6574,gem_id=192964,bonus_id=8836/8840/8902/9405/10359/8793/9379/8960/10249/10531,crafted_stats=40/36,crafting_quality=5
# Azureblade's Work Gloves (528)
hands=,id=193648,bonus_id=9639/6652/10870/9144/10338/3207/8767
# Vibrant Wildercloth Girdle  (525)
waist=,id=193516,gem_id=192952,bonus_id=8836/8840/8902/9405/10359/8793/8932/8960/10249/10531,crafted_stats=49/32,crafting_quality=5
# Leggings of the Sinister Savant (528)
legs=,id=217213,enchant_id=6541,bonus_id=6652/9639/10868/10338/1520/8767
# Vibrant Wildercloth Slippers  (525)
feet=,id=193519,enchant_id=6607,bonus_id=8836/8840/8902/9405/10359/8791/8174/10249,crafted_stats=40/36,crafting_quality=5
# Seal of Diurna's Chosen (528)
finger1=,id=195480,enchant_id=6556,gem_id=192961,bonus_id=6652/10531/10418/1605/8767
# Seal of Filial Duty (535)
finger2=,id=195526,enchant_id=6562,gem_id=192961,bonus_id=6652/10531/10503/1602/8767
# Whispering Incarnate Icon (528)
trinket1=,id=194301,bonus_id=6652/10418/1605/8767
# Irideus Fragment (528)
trinket2=,id=193743,bonus_id=9639/6652/9144/10338/3207/8767
# Dreambinder, Loom of the Great Cycle (528)
main_hand=,id=208616,enchant_id=6643,bonus_id=6652/9418/10418/1559/8767

### Gear from Bags
#
# Vibrant Wildercloth Headcover  (447)
# head=,id=193523,gem_id=192988,bonus_id=8836/8840/8902/9405/9376/8793/9379/8960/9366/9413,crafted_stats=32/49,crafting_quality=5
#
# Ouroboreal Necklet (512)
# neck=,id=210214,bonus_id=6652/10413/1543/8767/9477/8782
#
# Elemental Lariat  (447)
# neck=,id=193001,gem_id=192948/192948/192948,bonus_id=8836/8840/8902/8960/8783/8782/9405/8793/9376/9366,crafted_stats=49/32,crafting_quality=5
#
# Custodian's Medallion of Delusion (528)
# neck=,id=193647,gem_id=192961/192961/192961,bonus_id=9639/6652/9144/10338/3207/8767/9477/8782
#
# Pauldrons of the Dreamfused Skull (1)
# shoulder=,id=209975
#
# Cloak of Coordination (29)
# back=,id=65360
#
# Jingoist's Cuirass (1)
# chest=,id=206839
#
# Vibrant Wildercloth Vestments  (447)
# chest=,id=193509,enchant_id=6625,bonus_id=8836/8840/8902/9405/9376/8793/9379/8960/9366,crafted_stats=49/32,crafting_quality=5
#
# Personal Tabard (1)
# tabard=,id=210469
#
# Platinum Star Band (509)
# finger1=,id=193708,bonus_id=10330/9639/6652/10533/9144/3188/8767
#
# Bloodied Wedding Ring (522)
# finger1=,id=193671,enchant_id=6568,bonus_id=9639/6652/10532/9144/10334/3201/8767
#
# Circle of Ascended Frost (522)
# finger1=,id=193731,enchant_id=6550,gem_id=192958,bonus_id=9639/6652/10531/9144/10334/3201/8767
#
# Unstable Arcane Loop (522)
# finger1=,id=193633,bonus_id=9639/6652/10532/9144/10334/3201/8767
#
# Thunderous Downburst Ring (515)
# finger1=,id=193696,enchant_id=6562,bonus_id=9639/6652/10532/9144/10332/3194/8767
#
# Captain's Signet of Command (70)
# finger1=,id=166560
#
# Signet of Titanic Insight  (447)
# finger1=,id=192999,enchant_id=6562,gem_id=192948,bonus_id=8836/8840/8902/8780/9405/8793/9376/9237/9366,crafted_stats=40/32,crafting_quality=5
#
# Scalebane Signet (509)
# finger1=,id=193768,bonus_id=10330/9639/6652/10532/9144/3188/8767
#
# Alacritous Alchemist Stone  (447)
# trinket1=,id=191492,bonus_id=8836/8840/8902/9405/9376/9366,crafting_quality=5
#
# Nymue's Unraveling Spindle (528)
# trinket1=,id=208615,bonus_id=10418/1559/8767
#
# Pinch of Dream Magic (493)
# trinket1=,id=209959,bonus_id=8902/10313/6652/1537/8767
#
# Tome of Unstable Power (528)
# trinket1=,id=212685,bonus_id=9639/6652/9144/10338/3207/8767
#
# Ruby Whelp Shell (509)
# trinket1=,id=193757,bonus_id=10330/9639/6652/9144/3188/8767
#
# Dancing Dream Blossoms (502)
# trinket1=,id=209953,bonus_id=8902/10316/6652/1546/8767
#
# Torch of Primal Awakening  (447)
# main_hand=,id=200642,enchant_id=6643,bonus_id=8836/8840/8902/9405/8793/9376/9366,crafted_stats=49/36,crafting_quality=5
#
# Tyr's Guard Bulwark (1)
# off_hand=,id=208198
#
# Crackling Codex of the Isles  (447)
# off_hand=,id=194879,bonus_id=8836/8840/8902/9405/8793/9376/9366,crafted_stats=49/32,crafting_quality=5

### Additional Character Info
#
# upgrade_currencies=c:2806:74/c:2807:98/c:2245:1372/c:2812:122/c:1792:8395/c:2809:24/c:2122:19/i:198058:5/i:198059:2/i:190453:5/i:211516:2/i:197921:13/i:198048:7
#
# slot_high_watermarks=0:528:528/1:528:528/2:528:528/3:528:528/4:525:528/5:528:528/6:525:525/7:525:525/8:528:528/9:528:528/10:528:528/11:535:535/12:528:528/13:509:509/14:1:371/15:1:130/16:515:515

# Checksum: cc9235
### End simulateText ###
desired_targets=10
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

**Comment by gastank** [comment]
The 11.0 version of SimC should be available for download now. That will be compatible with the new talent strings from the game. However, do note that **prepatch sims are not fully supported and your spec may or may not sim properly (or at all).**
