### ISSUE TITLE
Fire Mage

### ISSUE THREAD

**Issue by RhynoLane** [simulationcraft/simc#9134]
Date: 2024-07-30 08:34:16
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Simulationcraft/core.lua line 367:
   Talent loadout 'Flamestrike' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly
Debug:
   [string "=[C]"]: error()
   [string "@Interface/AddOns/Simulationcraft/core.lua"]:367:
      Interface/AddOns/Simulationcraft/core.lua:337
   [string "@Interface/AddOns/Simulationcraft/core.lua"]:393:
      Interface/AddOns/Simulationcraft/core.lua:379
   [string "@Interface/AddOns/Simulationcraft/core.lua"]:912: GetSimcProfile()
   [string "@Interface/AddOns/Simulationcraft/core.lua"]:1054: PrintSimcProfile()
   [string "@Interface/AddOns/Simulationcraft/core.lua"]:19: OnClick()
   [string "@Interface/AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:179:
      ...AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177
Locals:
(*temporary) = "Talent loadout 'Flamestrike' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly"

AddOns:
  Swatter, v<%version%> (<%codename%>)
  Auctioneer, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.17 (OneMawTime)
  ChatCopyPaste, v1.19
  DBMCore, v11.0.2
  DBMStatusBarTimers, v11.0.2
  DBMVPVEM, veeae112
  Details, v#Details.12820.159
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, vv13.71
  ElvUIBenikUI, v4.50
  ElvUILibraries, vv13.71
  ElvUIMythicPlusDatatext, v1.7.3
  ElvUIRaidMarkers, v6.2.8
  FastAutoRepair, v6.1
  GTFO, v5.10
  Hekili, vv11.0.0-0.9.6a
  MaxDps, v10.0.64
  Simulationcraft, v11.0.0-01
  Stubby, v9.1.BETA.5.17 (OneMawTime)
  TomTom, vv4.0.1-release
  WeakAuras, v5.15.4
  WeakAurasArchive, v5.15.4
  BlizRuntimeLib v11.0.0.55846(US) <enUS>
  (ck=382)

**Comment by vituscze** [comment]
Have you tried doing what the error message says? Namely:

> Talent loadout 'Flamestrike' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly

**Comment by RhynoLane** [comment]
How does one delete a talent, sorry? Removed it from my bars and put it back. Not sure sorry, first time I've had a problem with the addon and I'm not super tech savvy,

**Comment by vituscze** [comment]
No, you don't delete a talent, you need to delete the talent *loadout* named Flamestrike.
