### ISSUE TITLE
Arcane Mage only casts arcane barrages

### ISSUE THREAD

**Issue by Ivan-karkit** [simulationcraft/simc#9191]
### Describe the bug
As I have been trying to run a sim, it comes back with a weird result that it only keeps casting arcane barrage. see full html report https://www.raidbots.com/simbot/report/9Kjrc2aY91b32WxMUaySut

### To Reproduce
Just ran quick sim, any fight mode has the same issue

**Comment by seanpeters86** [comment]
As noted here: https://support.raidbots.com/article/68-major-talent-issues-with-the-war-within-pre-patch

Raidbots/SimC are focused on The War Within and not Pre-Patch.

As such for the moment Mages only support simming when you have Hero Talents.
