### ISSUE TITLE
Warlock seems broken.

### ISSUE THREAD

**Issue by SneakyTurt1e** [simulationcraft/simc#9257]
### Describe the bug
Whether I use the simc addon or pull profile online, the simulation seems use only one skill `Shadow Bolt`

### Expected behavior
Should see more spells in damage source and priority list

### To Reproduce
I've run a simulation using online raidbots, check out the [https://www.raidbots.com/simbot/report/7BiXLPnQ9NomNH9VwREbqM](https://www.raidbots.com/simbot/report/7BiXLPnQ9NomNH9VwREbqM)

If you guys prefer to reproduce it locally, you can pick any one of warlock's simc profile.

### Additional information
* SimulationCraft Version (required): simc-1100.01.fab5ea8-win64

**Comment by Pewtro** [comment]
Warlocks have no [default APL right now beyond shadow bolt](https://github.com/simulationcraft/simc/blob/thewarwithin/engine/class_modules/apl/warlock.cpp), nothing is broken.

**Comment by SneakyTurt1e** [comment]
> Warlocks have no [default APL right now beyond shadow bolt](https://github.com/simulationcraft/simc/blob/thewarwithin/engine/class_modules/apl/warlock.cpp), nothing is broken.

Thanks for the reply, this is my first time using it. not as well researched...Will there be plans to add APL in the future?

**Comment by Mlklock** [comment]
Think this issue can be closed, as all 3 warlocks have APLs up to date.
