### ISSUE TITLE
Azerite Surge not implemented or on TODO sheet

### ISSUE THREAD

**Issue by ArcanePorom** [simulationcraft/simc#9260]
### Is your feature request related to a problem? Please describe.
Azerite Surge does not appear to be implemented or on the the TODO spreadsheet:
https://docs.google.com/spreadsheets/d/e/2PACX-1vREwlT3zZ2R-cAp9_omhCoZvNQreuEU4VhMY88Jy-vDVWFuADIGCykuXSep35m90mmMK-61xN6pcT-v/pubhtml?gid=0&single=true

### Describe the solution you'd like
I would like it implemented (I am far too stupid to know how).

### Describe alternatives you've considered
Just not picking the race.

### Additional context
If there is somewhere that this is listed for implementation and I am stupid for opening this ticket, please let me know.

**Comment by Pewtro** [comment]
Added the three relevant Earthen racial traits, Azerite Surge, Titan-Wrought Frame and Ingest Minerals to the sheet.
