### ISSUE TITLE
GUI disappears immediately on opening with build 1100, since build 1027

### ISSUE THREAD

**Issue by Argonist852** [simulationcraft/simc#9311]
### Describe the bug
When opening the gui SimulationCraft.exe build1100 it disappear immediately after one second of a black window showing it tries to open.
the windows process disappear also like it didn't started, it appears one second and disappear immediately after just like the gui.

### Expected behavior
When launching the gui it remains open and can do simulations

### To Reproduce
Download the build 1100, unzip it, launch the simulationcraft.exe, for me it closes directly.

### Additional information
issue is present since the build 1027 and 1100.
I don't have the issue with builds older than 1026
Launched in admin, same issue.
Launched in compatibility mode, same issue.
Updated graphic drivers, same issue.
Used a different computer, same issue, so it's not juste for one computer, did it on windows 10 version 22h2 and windows 11

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  No errors in dxdiag, Gui don't give an error also, it just closes immediately after launch

* **simc_gui.simc** file or contents
 Gui doesn't launch, can't do a simulation in order to get a file.

**Comment by Kastor91** [comment]
Hey, I had the same problem and I managed to fix it.

Tried a lot of things but I think that what dit it was this : 

Uninstall this (I think mine was in version 14.0.XXXX before)
![image](https://github.com/user-attachments/assets/4f066b73-f030-49bc-a23f-5a0173d6b43f)

Reinstall it with this one : https://aka.ms/vs/17/release/vc_redist.x64.exe (it's a more recent version : 14.40 and I think that's what fixed the problem)

Does it work for you too ?

**Comment by Argonist852** [comment]
Hi,
Many thanks, it was indeed this, there was another open issue similar as this one but no solution to it.
Had several versions of Microsoft Visual C++ removed them all and installed the latest one, fixed the issue.
Now I can go back to do all the needed simulations for the TWW
Have a nice day!

**Comment by gerinamoo** [comment]
That fixed it.  Tysm !!!
