### ISSUE TITLE
Feral druid APL PW logical issue

### ISSUE THREAD

**Issue by whynotdead** [simulationcraft/simc#9357]
### Describe the bug
I'm not sure im in right place to report it but here is following:
Feral druid > finisher action list > primal wrath logic issue
Here is quick note how primal wrath logic should be happening "maintain/upgrade pws, if we have 6.5+s left on pw, we will instead bite if we have rampant ferocity talented. Without rampant, we will bite a vined target with 6 or fewer targets. If we have Ravage, we use specifically Ravage at 7 or fewer targets." 
However with even 4-5 targets outside of Apex procs (free bites) or coding it as buff.apex_predators_craving.up and ravage being up or blood vines ticking with rip dot being longer than even 9 seconds it keep spamming PW instead of prioritizing bites ruining the logic and causing potential dps loss. I cannot provide snapshot since it's not a recommendation issue but simply modifiers not doing their job in their particular sequence
Apex meanwhile works well and goes in advance of PW if it has 6+ duration, but hero talents conditions keep being ignored
Also small tip, idk exactly to what talent build that APL refers, but i guess depending on Circle of Life and Death talent dot remaining time condition should differs since talent makes it tick 20% faster

### Expected behavior
I was able to fix it i think and found out that it works with extra entry for bite, not sure if i did it right logical wise:

primal_wrath,target_if=max:dot.bloodseeker_vines.ticking,if=spell_targets.primal_wrath>1&((dot.primal_wrath.remains<6.5&!buff.bs_inc.up|dot.primal_wrath.refreshable) - cut entry for PW which is for maintaining

(!talent.rampant_ferocity.enabled&(spell_targets.primal_wrath>1&!dot.bloodseeker_vines.ticking&!buff.ravage.up|spell_targets.primal_wrath>6+talent.ravage))|dot.primal_wrath.pmultiplier<persistent_multiplier) - conditional entry for bite to utilize ravage/blood vines explosion, it looks like working, if i did everything correctly, probably should post rotation tune update cuz it clearly doesn't work in a single entry binded to PW even if we rely not just on rampant ferocity talented but apex proc buff up - it still not using bites outside of apex procs

### To Reproduce
Enter game as feral > With Ravage buff being up or Blood Vines ticking on main target it still suggest to use PW when 5 targets around only even pw duration is above 10s (same on target dummies which are exactly 5)

### Additional information
* SimulationCraft Version (required) - weekly i guess? I'm using RaidBots and checking APL Logic

Let me know if more info is needed or i'm in wrong place and where to go with this

**Comment by whynotdead** [comment]
Actually nvm, it completely ignores that condition which is "maintain/upgrade pws, if we have 6.5+s left on pw, we will instead bite if we have rampant ferocity talented. Without rampant, we will bite a vined target with 6 or fewer targets. If we have Ravage, we use specifically Ravage at 7 or fewer targets." and goes straight to ferocious_bite,target_if=max:dot.bloodseeker_vines.ticking, so ravage procs/blood vine explosions not getting utilized in cleave/aoe situation completely. Here is an example from raidbots quick sim:
https://www.raidbots.com/simbot/report/4iieyYpJqxxnfe1XRJimV9/simc
https://imgur.com/a/l80ndUX - here on 5 targets you can see that issue that conditional logic is not supported or written wrong/has wrong priority, you pw at 0:52 with ravage buff up, then feral frenzy into 5 cps and PW again with ravage buff up 3 seconds later when it suppose to be a ferocious bite to utilize ravage, so it needs to be adressed

**Comment by whynotdead** [comment]
It also possible that whole PW condition idea is not working rather than maintaining PW since in #default condition section we got apex utilize trigger with higher priority rather than 5 cp call action #finisher trigger. Most likely because it thinks new pw will have stronger snapshot at |dot.primal_wrath.pmultiplier<persistent_multiplier condition for w/e reason? (myb it takes in account adaptive swarm as snapshot mechanic or pw initial dmg?)

**Comment by jordanritzie19** [comment]
> Actually nvm, it completely ignores that condition which is "maintain/upgrade pws, if we have 6.5+s left on pw, we will instead bite if we have rampant ferocity talented. Without rampant, we will bite a vined target with 6 or fewer targets. If we have Ravage, we use specifically Ravage at 7 or fewer targets." and goes straight to ferocious_bite,target_if=max:dot.bloodseeker_vines.ticking, so ravage procs/blood vine explosions not getting utilized in cleave/aoe situation completely. Here is an example from raidbots quick sim: https://www.raidbots.com/simbot/report/4iieyYpJqxxnfe1XRJimV9/simc https://imgur.com/a/l80ndUX - here on 5 targets you can see that issue that conditional logic is not supported or written wrong/has wrong priority, you pw at 0:52 with ravage buff up, then feral frenzy into 5 cps and PW again with ravage buff up 3 seconds later when it suppose to be a ferocious bite to utilize ravage, so it needs to be adressed

Hey, thanks for reporting, but if you do the math you'll find that the primal wrath at 55s had just under 6.5s remaining. It primal wraths more than you'd think due to low gear, but it seems to be playing as intended (and what I've found to be best so far). In fact, primal wrath fell off entirely before the primal wrath at 0:52 (so maybe low gear needs an even higher number than 6.5s remaining to bite)

**Comment by whynotdead** [comment]
Hey! Thanks for explanation, my point was shouldn't it ignore PWing as to maintain the rip with conditions of ravage/apex proc buffs up or blood vine ticking? Not like normal biting that at the end of priority? So we either pwing under 6.5s duration / snapshot will be stronger, otherwise with mentioned buffs up, we utiize bites first in AoE/Cleave situation? At least that's how i interpret written conditions there. However it seems even with Ravage buff up it prioritize refreshing/maintaining pw that cause ravage buffs overlap i.e or completely wasting it

**Comment by whynotdead** [comment]
I transfered whole simc apl profile to hekili and seems like  deleting |dot.primal_wrath.pmultiplier<persistent_multiplier condition fixed the issue of ignoring ravage/blood vines persistance, but im not sure why it had such impact (not talking about pw refresh/maintain outside of ravage/blood vines  dot ticking). If that's snapshotting related thingy on this screen you would imagine it takes in account Adaptive Swarm as snapshot rather than dynamic gain https://imgur.com/a/l80ndUX (you can se we got ravage proc up whole time and it's PWing 2 times in a row and we simply lost Ravage due to no CP to spend it after 2nd PW) @jordanritzie19

**Comment by jordanritzie19** [comment]
> my point was shouldn't it ignore PWing as to maintain the rip with conditions of ravage/apex proc buffs up or blood vine ticking?

The condition you refer to lets us use primal wrath in more scenarios in the situation that we do not have rampant ferocity talented. 1. We don't have rampant ferocity and ravage/vines arent up. 2. We don't have rampant ferocity and there are (6+ravage) or more targets. The sim linked has rampant ferocity so for our sakes we can ignore this portion.

Deleting `|dot.primal_wrath.pmultiplier<persistent_multiplier` would make it such that you wouldn't prioritize upgrading the snapshots of your primal wrath (unless some other condition is true). Upon re-inspection though it seems like this is net neutral nowadays, so removing it seems to be fine. You'll still lose some Ravages from time-to-time in AoE; there's not a whole lot you can do about that. I can look into maybe dumping lower combo point ravages if it's near expiration, but don't get your hopes up that it will be a gain.

As for your last point, simc does not consider adaptive swarm as part of the dots persistent_multiplier, as adaptive swarm dynamically buffs your dots. Hekili however is not simc, so they may treat the line differently. Can't say im familiar enough with Hekili to know.

**Comment by jordanritzie19** [comment]
Also, a better place to contact me is on discord with handle CelestialRepose. You'll get faster responses that way, though I am periodically checking this thread if that's not a feasible option.
