### ISSUE TITLE
wlk dk

### ISSUE THREAD

**Issue by duanyiemo3** [simulationcraft/simc#9382]
SimulationCraft encountered an error!

Option parsing error:
Unexpected parameter '{talents:0000000000000000000000000000-32005350000200000000000000000-2300303050032152000150213130051,glyphs:{major:[{spellID:63333},{spellID:58629},{spellID:58686}],minor:[{spellID:58680},{spellID:59309},{spellID:60200}]},class:deathknight,unit:player,race:Human,name:重生之坐大牢,gear:{items:[{id:45299,gems:[41398,40011]},{id:45819,gems:[]},{id:39621,gems:[40011]},{enchant:3825,gems:[],id:39297},{enchant:3252,gems:[40011],id:45225},{enchant:1593,gems:[],id:40733},{enchant:684,gems:[40011],id:40803},{id:45550,gems:[40041,40011,40041]},{enchant:3326,gems:[40041,40011],id:45841},{enchant:3824,gems:[40041,40011],id:45559},{id:42115,gems:[]},{id:40717,gems:[]},{id:45286,gems:[]},{id:42128,gems:[]},{enchant:3368,gems:[],id:41383},{enchant:3368,gems:[],id:44311},{id:42619,gems:[]}]},professions:[{name:Enchanting,level:1}],level:80,spec:unholy,realm:加丁}'. Expected format: name=value

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Option parsing error
* Error: Unexpected parameter '{talents:0000000000000000000000000000-32005350000200000000000000000-2300303050032152000150213130051,glyphs:{major:[{spellID:63333},{spellID:58629},{spellID:58686}],minor:[{spellID:58680},{spellID:59309},{spellID:60200}]},class:deathknight,unit:player,race:Human,name:重生之坐大牢,gear:{items:[{id:45299,gems:[41398,40011]},{id:45819,gems:[]},{id:39621,gems:[40011]},{enchant:3825,gems:[],id:39297},{enchant:3252,gems:[40011],id:45225},{enchant:1593,gems:[],id:40733},{enchant:684,gems:[40011],id:40803},{id:45550,gems:[40041,40011,40041]},{enchant:3326,gems:[40041,40011],id:45841},{enchant:3824,gems:[40041,40011],id:45559},{id:42115,gems:[]},{id:40717,gems:[]},{id:45286,gems:[]},{id:42128,gems:[]},{enchant:3368,gems:[],id:41383},{enchant:3368,gems:[],id:44311},{id:42619,gems:[]}]},professions:[{name:Enchanting,level:1}],level:80,spec:unholy,realm:加丁}'. Expected format: name=value

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=0
override.mortal_wounds=0
threads=12
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
{"talents":"0000000000000000000000000000-32005350000200000000000000000-2300303050032152000150213130051","glyphs":{"major":[{"spellID":63333},{"spellID":58629},{"spellID":58686}],"minor":[{"spellID":58680},{"spellID":59309},{"spellID":60200}]},"class":"deathknight","unit":"player","race":"Human","name":"重生之坐大牢","gear":{"items":[{"id":45299,"gems":[41398,40011]},{"id":45819,"gems":[]},{"id":39621,"gems":[40011]},{"enchant":3825,"gems":[],"id":39297},{"enchant":3252,"gems":[40011],"id":45225},{"enchant":1593,"gems":[],"id":40733},{"enchant":684,"gems":[40011],"id":40803},{"id":45550,"gems":[40041,40011,40041]},{"enchant":3326,"gems":[40041,40011],"id":45841},{"enchant":3824,"gems":[40041,40011],"id":45559},{"id":42115,"gems":[]},{"id":40717,"gems":[]},{"id":45286,"gems":[]},{"id":42128,"gems":[]},{"enchant":3368,"gems":[],"id":41383},{"enchant":3368,"gems":[],"id":44311},{"id":42619,"gems":[]}]},"professions":[{"name":"Enchanting","level":1}],"level":80,"spec":"unholy","realm":"加丁"}
### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Pewtro** [comment]
SimulationCraft doesn't support Wrath of the Lich King simulations.
