### ISSUE TITLE
Can you add the function of using SimulationCraft software to realize the Top Gear of Raidbots and simulate the best equipment combination? 

### ISSUE THREAD

**Issue by Zeus93** [simulationcraft/simc#9401]
Can you add the function of using SimulationCraft software to implement Raidbots' Top Gear and simulate the best equipment combination? I checked the documents and many forum posts, but only found the function of horizontal comparison of single equipment.

**Comment by renanthera** [comment]
I would consider it unlikely for simc to support that level of UI to allow for creation of complex comparisons locally.

If you wish to run RaidBots Top Gear sims locally, you can export the simc input that is very similar to what RaidBots would have executed at the bottom of the page after you configure it.

At that point, you can use the file you downloaded as input to the binary you have built locally.

**Comment by Pewtro** [comment]
Answered on [discord](https://discord.com/channels/244067101478879234/244072792948080641/1280808438506459187)
