### ISSUE TITLE
Programm doesn't start properly

### ISSUE THREAD

**Issue by Tronarr** [simulationcraft/simc#9409]
Hey,

just downloaded the newest build. When i start the programm the window opens loads for a second and instantly closes. No error massages, nothing.

My System:

AMD Ryzen 7 5800X3D 8-Core Processor              3.40 GHz
Win 11 x64
Geforce RTX 4070

**Comment by renanthera** [comment]
Can you confirm the exact name of the executable you are attempting to run?

It is probably you are attempting to run the main binary and not the GUI, as the behaviour you mention is the expected behvaiour for running the main binary with no input (double clicking it from file explorer).

**Comment by Tronarr** [comment]
Hey,

 

im double clicking it from the afile explorer like the years before.

 

Name of the executable: SimulationCraft (the one with the SC Logo).

 

If double clicking the executable is not the way im supposed to use SimC please tell me how to use it properly.

 
 

Gesendet: Donnerstag, 05. September 2024 um 12:41 Uhr
Von: "Kate Martin" ***@***.***>
An: "simulationcraft/simc" ***@***.***>
Cc: "Tronarr" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [simulationcraft/simc] Programm doesn't start properly (Issue #9409)


 

Can you confirm the exact name of the executable you are attempting to run?

It is probably you are attempting to run the main binary and not the GUI, as the behaviour you mention is the expected behvaiour for running the main binary with no input (double clicking it from file explorer).

**Comment by renanthera** [comment]
If you were running SimulationCraft.exe and it's still failing, perhaps try the steps recommended here:

https://github.com/simulationcraft/simc/issues/9311

**Comment by Tronarr** [comment]
Thanks!Ita running again.--Gesendet mit der WEB.DE Mail AppAm 05.09.24, 13:44 schrieb Kate Martin ***@***.***>:

  
  If you were running SimulationCraft.exe and it's still failing, perhaps try the steps recommended here:
  #9311
