### ISSUE TITLE
UI doesn't launch, and Segmentation fault with the smic.exe

### ISSUE THREAD

**Issue by Aleqsd** [simulationcraft/simc#9424]
### Describe the bug
When I launch the SimulationCraft.exe, it just open a white window, and disappear after 2 seconds
If I try to launch simc from my terminal, I just encounter a `Segmentation fault` and that's it

### Additional information
* SimulationCraft Version
1100.01aef33c4-win64

[DxDiag.txt](https://github.com/user-attachments/files/16909659/DxDiag.txt)

**Comment by renanthera** [comment]
To fix the GUI, try the fix found in #9311.

To debug your CLI segfault, you will need to provide the complete input you were trying to simulate.

**Comment by Aleqsd** [comment]
It works, installing the VS Redistributable fixed it :)
https://github.com/simulationcraft/simc/issues/9311#issuecomment-2308204334
