### ISSUE TITLE
Please help me to test this opener

### ISSUE THREAD

**Issue by Chen-2905** [simulationcraft/simc#9548]
### Is your feature request related to a problem? Please describe.
I am not good at modify apl, but I want to try this theoretically higher opener

![image](https://github.com/user-attachments/assets/cefb2979-7030-4832-8d13-962993e8e89e)

### Additional context
Open an aura 20 seconds in advance, and you will have more inertia at the beginning. Can this opener be better than the current simc best opener?
Please help me to test this opener,thanks

**Comment by ToppleTheNun** [comment]
Please take this to the Fel Hammer and discuss in there; all APLs for Havoc/Vengeance Demon Hunter are worked on there: https://discord.gg/felhammer

**Comment by Chen-2905** [comment]
thanks
