### ISSUE TITLE
In Linux, the decimal point is removed from the values.

### ISSUE THREAD

**Issue by alexohneander** [simulationcraft/simc#9553]
### Describe the bug
Under Linux I get a different DPS format than under Mac and Windows.

**Windows & Mac**: 845,973 dps
**Linux**: 844776 dps

### Expected behavior
I expected that the result would be the same for all distributions.

### Additional information
* SimulationCraft Version 1100-02

**Comment by nilin2008** [comment]
WIndows:
 SimulationCraft encountered an error! 
 SimulationCraft 1100-02 for World of Warcraft 11.0.2.56513 Live 
 hotfix 2024-09-14/56513, git build thewarwithin 4d2131b 
* Category: Simulation runtime error
* Error: Initializing: Actor 'XXX': Item 'noncandescent_smithing_hood' Slot 'head': Cannot parse option from 'noncandescent_smithing_hood,id=223,294,bonus_id=10,281/10,377/10,876/1,656/10,255': Unexpected parameter '294'. Expected format: name=value

**Comment by renanthera** [comment]
> WIndows: SimulationCraft encountered an error!  SimulationCraft 1100-02 for World of Warcraft 11.0.2.56513 Live  hotfix 2024-09-14/56513, git build thewarwithin [4d2131b](https://github.com/simulationcraft/simc/commit/4d2131bc3701da8adf57d2cee574f518ff848ac0) 
> 
>     * Category: Simulation runtime error
> 
>     * Error: Initializing: Actor 'XXX': Item 'noncandescent_smithing_hood' Slot 'head': Cannot parse option from 'noncandescent_smithing_hood,id=223,294,bonus_id=10,281/10,377/10,876/1,656/10,255': Unexpected parameter '294'. Expected format: name=value

You're experiencing a different issue to the OP, which is the same one as found in issue #9416. The GUI is largely unmaintained, and the other user seemed to have success using the CLI instead.

**Comment by renanthera** [comment]
What is the locale being used in the environment you're running simc?

Numeral separators are locale based, and your locale is likely not equivalent to what you had on other systems.
