### ISSUE TITLE
The issue of damage caused by the Chaos Bolt of the Destruction Warlock

### ISSUE THREAD

**Issue by xxxxxxxxzq** [simulationcraft/simc#9630]
The highest and lowest damage simulated for the Destruction Warlock's Chaos Bolt tends to be higher than that in the actual gameplay.

**Comment by Azevara** [comment]
This is not a claim that can be made without evidence.

**Comment by xxxxxxxxzq** [comment]
> This is not a claim that can be made without evidence.

Because I'm not clear about the simulation strategy, it's difficult for me to provide evidence. So I hope someone can provide a strategy that only uses Incinerate and Chaos Bolt for comparison with the damage in the game.

**Comment by Mlklock** [comment]
https://www.raidbots.com/simbot/report/3nRyVVjMh9Hhc6rrCwACsz/simc

https://www.warcraftlogs.com/reports/qCL9yJjTV372xdZm#fight=1&type=damage-done&source=1&ability=116858&view=events 



> The highest and lowest damage simulated for the Destruction Warlock's Chaos Bolt tends to be higher than that in the actual gameplay.

I don't think this is correct, at least based on the short sample i am bringing here.
