### ISSUE TITLE
Stat scaling seems completely broken

### ISSUE THREAD

**Issue by Melkor3463** [simulationcraft/simc#9685]
Basically on any spec stat scaling is broken, numbers in the negative, or in the positive but completely outside of the realm of expectations, only weapon scaling seems to be where you would expect it.
![Screenshot (13)](https://github.com/user-attachments/assets/46296e32-332d-4cf8-a836-8e749587c999)

This is a sample of a sim i just did recently, on ret paladin, but it's the same on any spec i tried.

**Comment by Pewtro** [comment]
What was the input used to generate that report?

**Comment by Melkor3463** [comment]
# Melorias - Retribution - 2024-10-24 13:31 - EU/Silvermoon
# SimC Addon 11.0.2-02
# WoW 11.0.5.57212, TOC 110005
# Requires SimulationCraft 1000-01 or newer

paladin="Melorias"
level=80
race=human
region=eu
server=silvermoon
role=attack
professions=enchanting=19/
spec=retribution

talents=CYEA5ba6OK14IUITjS1kSUVJcBAAAYAgRjltZmlltxMbM2WmZDAAAAAAjmmhBzMbzgZbYMLmltxMYYGWWYDAAgMz02sMbzAA2AGAmBzwMA

# Saved Loadout: Crusading strikes Templar
# talents=CYEA5ba6OK14IUITjS1kSUVJcBAAAYAghxy2Mzyy2YmNGbLzsBAAAAAghxMMYmZbGMbDjZxssNmBDzwyCbAAAwMjtZZ2mBAsBMAMDmhZA
# Saved Loadout: Crusading strikes Herald
# talents=CYEA5ba6OK14IUITjS1kSUVJcBAAAYAghxy2Mzyy2YmNGbLzsBAAAAAghxMMYmZbGMLDjZxssNmBDzwyCbAgZZ2mZmFzMjtZZ2mBAsAMAMDmhZA

# Entombed Seraph's Casque (616)
head=,id=211993,bonus_id=10263/6652/10877/10371/1517
# "Emergency Stop" Keychain (619)
neck=,id=221077,bonus_id=10390/6652/10395/10878/10383/10262/1654/10255
# Entombed Seraph's Plumes (606)
shoulder=,id=211991,bonus_id=6652/10369/10270/1507/10255
# Serape of the Stygian Sea (610)
back=,id=219185,bonus_id=10265/6652/10377/3189/10255
# Entombed Seraph's Breastplate (603)
chest=,id=211996,bonus_id=10271/6652/10373/1504
# Handguards of Hidden Stars (610)
wrist=,id=219151,bonus_id=10265/6652/10876/10377/3189/10255
# Entombed Seraph's Castigation (600)
hands=,id=211994,bonus_id=6652/10272/10390/10372/1501
# Sedimentary Girdle of the Feverflare (590)
waist=,id=224696,bonus_id=6652/10397/1699/10377/10279/1662/10255
# Legplates of Broken Trust (584)
legs=,id=221092,bonus_id=10388/6652/10375/12045/10293/1619/10255
# Boots of the Underdweller (610)
feet=,id=156216,bonus_id=10265/7756/10376/8902/10042/10255
# Umbriss Band (606)
finger1=,id=133286,bonus_id=10389/6652/10394/10393/10383/10274/10036/10255
# Band of the Abyssal Lord (606)
finger2=,id=150459,bonus_id=7756/10270/10041/10255
# Quickwick Candlestick (603)
trinket1=,id=225649,bonus_id=41/6652/10271/3132/10255
# Spelunker's Waning Candle (603)
trinket2=,id=225638,bonus_id=6652/10271/3132/10255
# Mountain Shaper's Greataxe (619)
main_hand=,id=219354,bonus_id=6652/10262/1524/10255

### Gear from Bags
#
# Grand Crusader's Helm (567)
# head=,id=18718,bonus_id=6652/8812/10286/7756/10876/12090/10009
#
# Arctic Pendant of the Quickblade (357)
# neck=,id=12044,bonus_id=6654/1681,drop_level=80
#
# Silken Advisor's Favor (619)
# neck=,id=225575,bonus_id=6652/10394/10392/10355/10262/1520/10255
#
# Vambraces of the Sadist (567)
# wrist=,id=13400,bonus_id=6652/8811/10286/7756/10877/12090/10009
#
# Tidesages' Warscroll (342)
# trinket1=,id=166766,bonus_id=7920

### Additional Character Info
#
# upgrade_currencies=c:2915:81/c:2917:6/c:2916:13/c:2914:56/c:3008:634
#
# slot_high_watermarks=0:616:616/1:619:619/2:606:616/3:603:616/4:590:616/5:584:619/6:610:616/7:610:616/8:600:616/9:606:610/10:603:616/11:610:616/12:619:619/13:19:610/14:247:613/15:225:610/16:311:616

# Checksum: a5f63640

**Comment by Pewtro** [comment]
This is only the /simc input, what were all the options?

**Comment by renanthera** [comment]
OP never followed up.
