### ISSUE TITLE
Loadout Corrupt

### ISSUE THREAD

**Issue by Clickzww** [simulationcraft/simc#9745]
### Describe the bug
When I enter /simc I get an error message ( ![Screenshot at Nov 14 20-20-04](https://github.com/user-attachments/assets/dcaf319c-6c65-4d52-9ddb-a2c17d6bd2c3) ) and the following bug grabber output:

6x Simulationcraft/core.lua:367: Talent loadout 'Delves' is corrupt/incomplete. Find that talent loadout in your talents UI and delete or update it. It may be on a different spec.
[string "=[C]"]: in function `error'
[string "@Simulationcraft/core.lua"]:367: in function <Simulationcraft/core.lua:337>
[string "@Simulationcraft/core.lua"]:393: in function <Simulationcraft/core.lua:379>
[string "@Simulationcraft/core.lua"]:925: in function `GetSimcProfile'
[string "@Simulationcraft/core.lua"]:1071: in function <Simulationcraft/core.lua:1070>
[string "=[C]"]: in function `PrintSimcProfile'
[string "@Simulationcraft/core.lua"]:168: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5479: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5425>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5131: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5167: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5163>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
(*temporary) = "Talent loadout 'Delves' is corrupt/incomplete. Find that talent loadout in your talents UI and delete or update it. It may be on a different spec."

This happens with every loadout I have, also when I deactivate Talent Loadout Addon and only at one of my Characters (Blood DK).

### Expected behavior
I was expecting the Sims String

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required): patch-11.0.5-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

Sorry, I don't find this

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

I don't even get to this step and use raidbots

**Comment by vituscze** [comment]
Did you try doing what the error message suggests? That is, removing the Delves loadout.

**Comment by Clickzww** [comment]
Yes i did this. Thema i get the Message that one other loadout is corrupted, and so on.
Am 14. Nov. 2024, 22:04 +0100 schrieb Vít Šefl ***@***.***>:

**Comment by vituscze** [comment]
Is it possible that the loadout in question is hidden? See https://github.com/simulationcraft/simc/issues/8627

**Comment by Clickzww** [comment]
Thank you! That was the solution.
Am 15. Nov. 2024, 14:36 +0100 schrieb Vít Šefl ***@***.***>:
