### ISSUE TITLE
Thunder Blast damage unrealistically large in Sim

### ISSUE THREAD

**Issue by windflame3** [simulationcraft/simc#9802]
### Describe the bug

When I simulate Fury Warrior in Quick Sim with Mountain Thane Hero Talent build, Thunder Blast always shows up at the top of my the damage category. This is far beyond uncrealistic because Thunder Blast only takes up about 6-9 percent of my total damage, yet Quick Sim shows it always make 22% percent of my total damage. I don't understand such a huge discrepency between the sim and actual behaviour. This mus be a bug.

### Expected behavior
It should never be at the top of my damage in any Warrior damage dealler specs. Please check for this issue because this can lead to me choosing Mountain Thane in M+ content and it always under performs a lot than Slayer talent build, despite the Quick Sim saying Mountain Thane out performs Slayer build by much.

### To Reproduce
Pleas just Sim any Fury Warrior with Mountain Thane Hero talent build and you can see this.

### Additional information
# SimC Addon 11.0.2-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Armadk** [comment]
Simc warrior module generally rolls the damage up from secondary effects into the button press that performed them.  In this case, lightning strike damage is being included in thunder blast as well.  If you compare only the thunderblast damage between in game, and in sim, it should be similar.
