### ISSUE TITLE
[Wiki] TextualConfigurationInterface - Whitespace can be quoted?

### ISSUE THREAD

**Issue by Fylwind** [simulationcraft/simc#9817]
**Documentation page:** https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface

I was looking at this page to better understand the grammar of the TCI files. The [White spaces and tabs](https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface#white-spaces-and-tabs) section say that [spaces](https://en.wikipedia.org/wiki/Space_(punctuation)) (U+0020) always behave as line separators:

> White spaces and tabs act as line breaks in ***any*** circumstances.

However, this does not seem to be true. In particular, the examples under [Long strings](https://github.com/simulationcraft/simc/wiki/TextualConfigurationInterface#long-strings) seem to be hinting at at double quotation syntax. I did some local testing myself, and it looks like something like this will escape the spaces as one would expect:

>     monk="Test Player"

Would it be useful to explain this in the documentation?

**Comment by renanthera** [comment]
As an aside, the path option which is mentioned in the Long Strings appears to no longer exists.

I looked into the details as to the exact implementation, and this space-allowed-tokenization appears to work in all contexts, albeit not useful in most.

I slightly reordered the TCI wiki page and the behaviour should be a bit more clear.
