### ISSUE TITLE
MOP [5.4.8] SimulationCraft.exe not launching

### ISSUE THREAD

**Issue by AlucardHellsingChapel** [simulationcraft/simc#9826]
### Describe the bug
After trying to launch the exe file nothing happens

### Expected behavior
Launch the simulationcraft.exe application

### To Reproduce
no clue 
### Additional information
simc-548-8-win64
* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  
[DxDiag.txt](https://github.com/user-attachments/files/18283774/DxDiag.txt)

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by vituscze** [comment]
Old SimulationCraft versions are no longer supported.

**Comment by AlucardHellsingChapel** [comment]
ah fuq

**Comment by AlucardHellsingChapel** [comment]
@vituscze do you maybe know what could be the problem tho ?
